### ISSUE TITLE
java.util.EmptyStackException In Compiling/Running Tests

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#10018]
In running the tests in https://github.com/lafernando/ideamart, I get the bad/sad error after a while, and it shows an EmptyStackException in "ballerina-internal.log". The log file is attached herewith.
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2280162/ballerina-internal.log)

**Comment by lafernando** [comment]
This issue occurs in Ballerina 0.981.0. if you try to build the project with "ballerina build", you will get the above mentioned issue. Please check and see if the root issue is fixed for the latest version in the compiler.

**Comment by SupunS** [comment]
@lafernando This occurs due to the cyclic import `import laf/ideamart;` in the `test.bal` file. 

The latest compiler (tested on v1.0-beta) doesn't allow to have cyclic imports. It logs the below error, and continues the compiling all the way up to the  DFAnalyzer phase without crashing.
```
error: laf/ideamart:0.2.0::tests/test.bal:3:1: cyclic module imports detected 'laf/ideamart:0.2.0 -> laf/ideamart:0.2.0'
```

**Comment by lafernando** [comment]
Great, thank you for the explanation. So this issue is fixed now.
