### ISSUE TITLE
References are not working for a ballerina project directory 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#10015]
**Description:**
Find all references feature is not working for a ballerina project directory. Feature is only functioning for program files.

**Steps to reproduce:**
 1. open a ballerina project in *composer* or *VScode*.
 2. right click on a symbol and click *find all references*. 

**OS and Version:**
ballerina version: 0.981.0
OS: mac 10.13.4
IDE: composer

**Comment by rasika** [comment]
This is fixed with the changes introduced in https://github.com/ballerina-platform/ballerina-lang/pull/10184
