### ISSUE TITLE
We cannot connect to remote host using composer

### ISSUE THREAD

**Issue by AnjanaFred** [ballerina-platform/ballerina-lang#10026]
**Description:**
We tried to connect  with another host  and tried to get service from that host but  i didnt get any response from it.

**Steps to reproduce:**
* first we create a hotspot
*and we connected to it and we send request to  host 
but we didnt get response.
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
I am closing this issue since this duplicate with #10025. Please check issue #10025 for update.

**Comment by AnjanaFred** [comment]
ok sir..Thankyou for your response
