### ISSUE TITLE
Unclear error message when attempting to run a .balx file

### ISSUE THREAD

**Issue by abdullahzameek** [ballerina-platform/ballerina-lang#10021]
So, I have a file called sample.bal. I built it using "ballerina build sample.bal. Build was successful, no issues there. Since I wasn't entirely sure as to how Ballerina structures the files in the build, I assumed that the .balx file is in the same directory as the .bal file. I tried to run "ballerina run sample.balx" but the error I got was "ballerina: error reading program file 'sample.balx'"
I feel that this error message is vague and misleading because the .balx file is not in the same directory and cannot be found, which is why it did not run. The current error message made me assume that there was an error in the build which is why it did not run.
So, I think in this case, if the file is not found and is in another folder (target, in this case), it will be much more useful for the user to be informed that the requested file was not found. 

(Unless the logic behind the current error message can be clarified)

Cheers!

**Comment by Manuri** [comment]
@abdullahzameek 
Thanks for suggesting this improvement. We'll look into this. 

In case you are interested, you can contribute to Ballerina project by sending a pull request. You can find the contribution guide [here](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md).
Also you could join our [Slack](https://ballerina-platform.slack.com/messages) channel and ask any questions you have from Ballerina developers.
