### ISSUE TITLE
Cannot connect remote host 

### ISSUE THREAD

**Issue by Chalithya** [ballerina-platform/ballerina-lang#10027]
Tried to connect multiple device through remote host  but the devices are unable to find it. Only the Host can find it through localhost

**Comment by vinok88** [comment]
Hi, Can you please explain more on your issue? For what are you trying to connect? Is is a ballerina service or a ballerina composer. Please provide us more concrete information to proceed on this issue.

Thanks a lot for reporting.

**Comment by Chalithya** [comment]
When we were trying to connect two pc's using http1 protocol, only the
server created device can see the server. The other device cannot find it

**Comment by SupunS** [comment]
@Chalithya 
Can you provide the sample code you used?

Were you able to ping from one (client) machine, to the other machine?

**Comment by daneshk** [comment]
I am closing this issue since this duplicate with #10025. Please check issue #10025 for update.
