### ISSUE TITLE
Json Parsing Error

### ISSUE THREAD

**Issue by AmilaJ** [ballerina-platform/ballerina-lang#10023]
Json:{
    "store": {
        "id": 3926402,
        "name": "ABC",
        "city": "Colombo",
        "country": "LK",
        "books": [
            {
                "title": "Othello",
                "author": "William Shakespeare",
                "language": "English",
                "year": ""
            },
            {
                "title": "Anna Karenina",
                "author": "Leo Tolstoy",
                "language": "Russian",
                "year": 1877
            },
            {
                "title": "The Great Gatsby",
                "author": "Scott Fitzgerald",
                "language": "English",
                "year": 1925
            },
            {
                "title": "Madol Duwa",
                "author": "Martin Wikcramasinghe",
                "language": "Sinhala",
                "year": 1947
            },
            {
                "title": "War and Peace",
                "author": "Leo Tolstoy",
                "language": "Russian",
                "year": 1867
            }
        ]
    }
}

Sample code:
```ballerina
import  ballerina/io;

function main(string... args) {
    string path="sample.json";
    io:ByteChannel byteChannel = io:openFile(path, io:READ);
    io:CharacterChannel ch = new io:CharacterChannel(byteChannel, "UTF8");

    json bookStore;
    json|error result=ch.readJson();
    match result {
        json j => {
            bookStore=j;
        }
        error e=> {
            io:println("Error occured while reading the file"+ e.message);
            return;
        }
    }

    //io:println(bookStore.store.city);
    //io:println(bookStore["store"]["city"]);
    
    //io:println(bookStore.store.books[0]);

    foreach book in bookStore.store.books {
        match book.year{
            int year =>{
                if(year>1900){
                    io:println(book);
                }
            }
            any =>{
                io:println("Invalid year");
            }
        }
    }

}
```

Expected:
Expection should be captured within the match block.

Current:
Running readBooks.bal
ballerina: HTTP trace log enabled
error: error, message: string index out of range: 0
	at main(readBooks.bal:10)
Execution Ended.

**Comment by SupunS** [comment]
Above code works fine in v0.981.0. Issue mentioned is not reproducible.
