### ISSUE TITLE
Using ballerina JMS consumer samples with EI 6.1.1 causes errors.

### ISSUE THREAD

**Issue by sdkottegoda** [ballerina-platform/ballerina-lang#10029]
**Description:**
The issue is reported in https://twitter.com/chj915/status/1026594549269819392
The following error:
```
java.io.IOException: An existing connection was forcible closed by the remote host
```
is thrown after each message consumption though the message consumption is not affected.

**Comment by aashikam** [comment]
We have tried to reproduce this error scenario by closing the connection abruptly using WSO2 EI versions both 6.1.1 and 6.3.0, but couldn't. If you experience a similar issue again please report with the artifacts used.
