### ISSUE TITLE
Infinite recursive call gives java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by shalithasuranga** [ballerina-platform/ballerina-lang#10020]
**Description:**
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to /usr/lib/ballerina/ballerina-0.981.0/heap-dump.hprof ...
Unable to create /usr/lib/ballerina/ballerina-0.981.0/heap-dump.hprof: Permission denied
```

**Steps to reproduce:**

Run following code

```ballerina
import ballerina/io;

function test(int n) returns (int) {
    if(n==1) {return 1;}
    return test(n) * n;
}

function main(string... args) {
    io:println(test(5));
}
```

**Affected Versions:**

- Ballerina 0.981.0 on Ubuntu

**Comment by riyafa** [comment]
Instead of letting bvm to go out of memory I think we need to throw an error indicating stackoverflow and terminate the program.

**Comment by lankavitharana** [comment]
This should be fixed in the master with the PR https://github.com/ballerina-platform/ballerina-lang/pull/12642

now it should throw StackOverflow error
