### ISSUE TITLE
B7 Intelij idea plugin does not provide up to date suggestions on ballerina library packages

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [ballerina-platform/ballerina-lang#10022]
**Description:**

- In the following code segment, it shows idea error for path variable passed in openFile() function.
- Also io: does not suggest "CharacterChannel" function.
- Tried with b7 - 9.8.0.1 version.

function main (string... args) {
    string path = "sample.json";

    io:ByteChannel bychannel = io:openFile(path, io:READ);
    io:CharacterChannel ch = new io:CharacterChannel(bychannel, "UTF-8");
}

**Steps to reproduce:**
Refer description. 

**Affected Versions:**
Version: 0.9.8.0.1

**OS, DB, other environment details and versions:**
Ubuntu-16.0.4

**Comment by Shan1024** [comment]
This issue occurred due to mismatch in Ballerina IDEA plugin and the SDK.
