### ISSUE TITLE
Move proc executor away from project directory

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#10030]
**Description:**
When we generate ballerina files from proto file, it automatically downloads proc executor. In my case its called "protoc-linux-x86_64.exe". However downloaded executor file will be saved in the project directory. I believe its better if you can save the proc executor in ballerina installation directory or in a temporary file. 

**Steps to reproduce:**
`ballerina grpc --input protofile.proto `

**Affected Versions:**
 Ballerina 0.980.1

**OS, DB, other environment details and versions:**
 Ubuntu 16.04 LTS

**Suggested Labels (optional):**
Component/gRPC,Component/stdlib,Type/Improvement

**Suggested Assignees (optional):**
@daneshk

**Comment by daneshk** [comment]
Closing this issue, since fix is merged to master branch
