### ISSUE TITLE
Pattern query test with AND operator fails intermittently

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#10033]
**Description:**
Ballerina stream's pattern query test with `AND` operator fails intermittently. Therefore, it's disabled in [1]. Creating this to keep track of above, and re-enable tests once it's fixed.

**Related PRs:**
[1] https://github.com/ballerina-platform/ballerina-lang/pull/9842

**Comment by gimantha** [comment]
We will remove the legacy streams implementation and this issue will be resolved. Till then, the test has been disabled.

**Comment by gimantha** [comment]
Closing because https://github.com/ballerina-platform/ballerina-lang/issues/10033#issuecomment-473790696
