### ISSUE TITLE
Add not supported error message for proto2

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#10031]
**Description:**
Currently if I wanted to generate .bal files from proto2 .proto file I get Oh no, bad sad error. Since ballerina only supports proto3 for now,I believe its better if we can add a proper error message when compiling saying proto2 is not currently supported.

**Steps to reproduce:**
Create a .proto file with `syntax = "proto2";`
ballerina grpc --input protofile.proto

**Affected Versions:**
 Ballerina 0.980.1

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Suggested Labels (optional):**
Component/gRPC,Component/stdlib

**Suggested Assignees (optional):**
@daneshk

**Comment by daneshk** [comment]
Closing this issue, since fix is merged to master branch
