### ISSUE TITLE
[gRPC] support defining map type in request/response messages

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#10039]
**Description:**
Currently this is not supported. Add support for defining map fields.

**Steps to reproduce:**
Currently not supported

**Affected Versions:**
0.981.0

**Comment by daneshk** [comment]
In current gRPC implementation, when we have a proto definition like below,
```proto
message HelloRequest {
	map<int32, string> tags = 4;
}
```
We generate Ballerina source code like below, where we consider it as an array of the record type(TagsEntry).
```ballerina
public type HelloRequest record {|
    TagsEntry[] tags = [];
|};

public type TagsEntry record {|
    int key = 0;
    string value = "";
|};
```
We are going to change this to,
```ballerina
public type HelloRequest record {|
    record {| int key; string value; |}[] tags = [];
|};
```

**Comment by daneshk** [comment]
Related discussion ballerina-platform/ballerina-spec#269

**Comment by BuddhiWathsala** [comment]
Using a list of records might not be the optimal way of handling protobuf map type, due to the following reasons.

- we can have multiple records with same keys
- we cannot access the values using keys like maps

I think to represent maps we need to use ballerina map and improve ballerina map to support other key types.

**Comment by daneshk** [comment]
Yes agreed. This is not the ideal solution. It will be a temporary solution until we get support from the language to define the key with different types. One other workaround we can try is using the string representation of other types. WDYT?

In Protocol buffers specification[1], they also gave this solution as a second option.
1. https://developers.google.com/protocol-buffers/docs/proto3#maps

**Comment by daneshk** [comment]
Closing this issue, since we already implemented as discussed in the spec issue
