### ISSUE TITLE
Cannot anonymously initiate a map when passing to a function

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#10049]
**Description:**
For a function with a signature as follows:
`public function acceptWebSocketUpgrade(map<string> httpHeaders) returns WebSocketListener;`
It is not possibly create and pass anonymous map. The following do not work:

1. `wsServiceEp = httpEp->acceptWebSocketUpgrade(new);`
Gives this error:
```
error: ./acceptHeader.bal:16:54: cannot infer type of the object from 'map'
compilation contains errors
```
2. `wsServiceEp = httpEp->acceptWebSocketUpgrade({});`
gives this error:
```
error: ./acceptHeader.bal:16:54: invalid usage of record literal with type 'map'
compilation contains errors
```
One of the above should work.
Only the following works at the moment:
```
map<string> headers;
wsServiceEp = httpEp->acceptWebSocketUpgrade(headers);
```

**Comment by vinok88** [comment]
An empty map is legal according to the spec.
`mapping-constructor-expr := ​{​ [field (​,​ field)*] ​}`
Hence, passing {} as a map value will be allowed.
