### ISSUE TITLE
Inconsistencies in BRefValueArray initialization

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#10057]
**Description:**
There are several inconsistencies in the way in which BRefValueArray objects are initialized and how the type is set.

- Currently there is a [constructor which does not require specifying the type](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-core/src/main/java/org/ballerinalang/model/values/BRefValueArray.java#L68) when initializing the array.

- Even when the type is set, there are inconsistencies where in some situations the element type is set as the type where ideally the type should be an array type or tuple type (encapsulating the element type).

We could enforce setting the correct type by requiring the specification of either an array type or a tuple type as the type at initialization (also not allowing the initialization without a type), but we need to carefully revisit and identify the correct type to set with all inconsistent usage.

**Comment by SupunS** [comment]
This is tracked via https://github.com/ballerina-platform/ballerina-lang/issues/16765.
Hence closing this one.
