### ISSUE TITLE
[IntelliJ Plugin] Syntax highlighting issue when using new ballerina documentation syntax

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#10051]
**Description:**
IDEA plugin highlights documentation line starts ("#") as a backticked content when backticked documentation continues in a new line, as shown below.
![screenshot from 2018-08-14 13-47-39](https://user-images.githubusercontent.com/29032600/44080093-a25f42b4-9fc8-11e8-84db-6447efe8e738.png)

**Affected Versions:**
IntelliJ Plugin Version: 0.981.1-SNAPSHOT

**Comment by NipunaRanasinghe** [comment]
@Shan1024 As per the offline discussion we had, this fix should be done after the existing documentation grammar refactoring right? Do we have an ETA for that?

**Comment by Shan1024** [comment]
@NipunaRanasinghe - Grammar needs to be refactored in BNF and JFlex file. Other than that, there is no change required for the ANTLR grammar file or from the compiler side. So you can continue the refactoring without any issue.

**Comment by nadeeshaan** [comment]
No longer valid since the language syntax has been changed
