### ISSUE TITLE
Support multiple issuers in JWT validation

### ISSUE THREAD

**Issue by nalakas** [ballerina-platform/ballerina-lang#10063]
**Description:**
Current JWT validation support one issuer and there are use cases to validate more than one issuer

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Component/stdlib Type/Improvement

**Suggested Assignees (optional):**

**Comment by ayomawdb** [comment]
Currently JWT validation is reading issuer as a single string value. An array of string should be accepted here and we should validate if any of the configured issuer match with the JWT.

https://github.com/ballerina-platform/ballerina-lang/blob/7eb74f4a1cbdc451a020d9a0fd156be058f7f9a9/stdlib/internal/src/main/ballerina/internal/jwt_validator.bal#L226

The same improvement should be done for `validateAudience` IMO. 

https://github.com/ballerina-platform/ballerina-lang/blob/7eb74f4a1cbdc451a020d9a0fd156be058f7f9a9/stdlib/internal/src/main/ballerina/internal/jwt_validator.bal#L231

@isharak / @isurulucky Please let me know if you have any objection on this improvement.

**Comment by ldclakmal** [comment]
Multiple audience is supported at the moment. Multiple issuers can be supported with the use of multiple auth providers. The security concern when we support multiple issuers with validation config is discussed at https://github.com/ballerina-platform/ballerina-lang/issues/14966.
