### ISSUE TITLE
[IDEA] Add initial expression evaluation support

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#10061]
**Description:**
Initial version of expression evaluation support is added to the language.

Example request - 
```
{ "command": "EVALUATE_EXPRESSION", "expression": "x", "threadId": <threadId> }
```

**Comment by pranavan15** [comment]
Expected request json format: 

-  `{ "command": "EVALUATE_EXPRESSION", "expression": <exp>, "threadId": <threadId> }`

Response json format:
- Successful scenario:
   `{ "code": "EXPRESSION_RESULTS", "message": { "status": "success", "results": <value> } }`

- Unsuccessful scenario:
   `{ "code": "EXPRESSION_RESULTS", "message": { "status": "failure", "results": "cannot find variable '<varName>'" } }`

- Internal error scenario (When json generation fails):
   `{ "code": "EXPRESSION_RESULTS", "message": { "status": "failure", "results": "internal error" } }`

**Comment by NipunaRanasinghe** [comment]
Closing since the expression evaluation support for IDEA plugin is already added.
