### ISSUE TITLE
JSON does not preserve the quote type for strings

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-lang#10079]
If the byte channel contains the content  {'code':'123'} the resulting byte[] will produce {"code":"123"}. Instead of single quotes, double quotes were given for the resulting value. 

```ballerina
function testByteArrayWithContentType(io:ByteChannel byteChannel) returns byte[]|error {
    mime:Entity entity = new;
    entity.setByteChannel(byteChannel, contentType = "application/json");
    //First time the json will be constructed from the byte channel
    json firstTime =  check entity.getJson();
    //Then get the body as byte[]
    return entity.getByteArray();
}
```

**Comment by SupunS** [comment]
Issue is currently JSON string value does not maintain the quote type (single Quote or double quote) at runtime.
Need to fix that

**Comment by SupunS** [comment]
As per the JSON spec (https://www.json.org/), a single quote is not a valid quote for string. Only double-quotes should be supported.
Thats a bug in the JSON-parser. Created issue https://github.com/ballerina-platform/ballerina-lang/issues/19390 for tracking. Hence closing this issue.
