### ISSUE TITLE
[WebSub] Allow binding the hub service to an existing endpoint

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#10101]
**Description:**
Currently the hub start up function takes the port as a parameter and defines an endpoint internally. With this approach one needs to have a separate endpoint for the hub service.

The improvement is to provide a mechanism to bind the hub service to an existing endpoint, probably by passing it as a param, to avoid having to define a separate endpoint just for the hub service.

**Comment by chamil321** [comment]
Requirement is addressed with https://github.com/ballerina-platform/ballerina-lang/pull/12319, hence closing the issue.
