### ISSUE TITLE
Composer integration test failure with OpenJDK 10.0.1

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#10113]
**Description:**
Composer integration test module contains tests which run using a msf4j server. Sever doesn't launch giving following error. It says a NoClassDefFoundError of javax and I have installed openJDK 10.0.1. So it's assumed that the issue is with initiating microservice with openJdk. 

```
Ballerina Composer Test Suite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/chamil/Documents/projects/ballerina/composer/modules/integration-tests/target/lib/composer-server.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.wso2.msf4j.internal.router.MicroserviceMetadata.lambda$new$33(MicroserviceMetadata.java:63)
        at java.base/java.util.HashMap.forEach(HashMap.java:1341)
        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1501)
        at org.wso2.msf4j.internal.router.MicroserviceMetadata.<init>(MicroserviceMetadata.java:61)
        at org.wso2.msf4j.internal.MicroservicesRegistryImpl.updateMetadata(MicroservicesRegistryImpl.java:232)
        at org.wso2.msf4j.internal.MicroservicesRegistryImpl.addService(MicroservicesRegistryImpl.java:80)
        at org.wso2.msf4j.MicroservicesRunner.deploy(MicroservicesRunner.java:103)
        at org.ballerinalang.composer.server.core.Server.start(Server.java:60)
        at org.ballerinalang.composer.server.launcher.ServerLauncher.main(ServerLauncher.java:146)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 9 more
    1) "before all" hook


  0 passing (10s)
  1 failing

  1) Ballerina Composer Test Suite
       "before all" hook:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



npm ERR! Test failed.  See above for more details.
```

**Affected Versions:**
0.981.1

**OS, DB, other environment details and versions:**
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

**Comment by NipunaMarcus** [comment]
@daneshk - looks like this is an issue with microservice and open jdk version.

**Comment by daneshk** [comment]
This is because in Java 9, @PostConstruct isn't on the classpath by default. We need to add javax.annotation-api  dependency to the microservice application. 
```xml
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```
If we are going to support java 9 or later version, we need to add above dependency as well.

**Comment by NipunaMarcus** [comment]
@daneshk - so we have to release the microservices framework supporting this version yeah? will this affect java 8 users ... ?

**Comment by daneshk** [comment]
We have two options,

1. Include this dependency to the msf4j-service parent pom and release the framework, so that any service dependent on that version will inherently get the dependency.
2. Include the dependency to the microservice application. so that we don't need to release the framework and can use the existing version. 

I don't think it will affect java 8 users. Better if we can test in both versions

**Comment by NipunaMarcus** [comment]
Adding the dependency for microservice app will be lot of work if we have multiple apps ... also it is kinda not right to tell everyone to add this dependency when they upgrade to java 9. But if we release msf4j with this dependency we don't have to do any of above.... WDYT?

**Comment by hasithaa** [comment]
Btw, @chamil321 Why we are testing this with OpenJDK 10? Our plan is to move to JDK 11, till then we are using OpenJDK 8. any missing feature?

**Comment by chamil321** [comment]
@hasithaa Recently I updated my OS and installed JDK 10 and I wasn't aware of the plan for moving to JDK 11.

**Comment by rasika** [comment]
As mentioned in the previous comments this issue has raised due to fact that `javax.annotation.PostConstruct` is removed since JDK9 above.  

Thus, Putting this issue "**On Hold**" as the current ballerina implementation does not support JDK9 either. As I found out, there are many issues & dependencies to be solved before moving into the integration tests with JDK9 and above (or supporting msf4j on jdk9+).

**Comment by rasika** [comment]
Closing in favor of https://github.com/ballerina-platform/ballerina-lang/issues/10228
