### ISSUE TITLE
Implement an AMQP client 

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#10115]
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/9746

**Comment by Manuri** [comment]
Resolved with https://github.com/ballerina-platform/ballerina-lang/pull/14744

**Comment by aashikam** [comment]
Fixed with #14744, a RabbitMQ connector that supports AMQP version 0-9-1.
