### ISSUE TITLE
DelimitedTextRecordChannel doesn't work on sockets

### ISSUE THREAD

**Issue by autodidaddict** [ballerina-platform/ballerina-lang#10137]
**Description:**
I am attempting to build a NATS client and because it is a `\r\n` delimited protocol, it seemed like a natural fit to use `DelimitedTextRecordChannel`. However, no matter what I try, encapsulating a character channel which encapsulates a socket's byte channel never unlocks. Every attempt at `hasNext()` or `getNext()` blocks forever.

**Steps to reproduce:**
https://github.com/autodidaddict/package-nats

**Affected Versions:**
0.980.1

**OS, DB, other environment details and versions:**
Ubuntu 18.04 and macOS High Sierra

**Suggested Labels (optional):**
bug

**Comment by daneshk** [comment]
I am closing this issue since fix is already merged to the master branch. Please check this in next release version.
