### ISSUE TITLE
Single MySQL Database Endpoint Tries 2-Phase Commit and Fails

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#10141]
The code is as follows:-

```ballerina
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/employee_swap/{id1}/{id2}"
    }
    employeeSwapByIds(endpoint caller, http:Request req, int id1, int id2) {
        transaction {
            table<Employee> ts1 = check empDB->select("SELECT * FROM Employee WHERE id = ?", Employee, id1);
            table<Employee> ts2 = check empDB->select("SELECT * FROM Employee WHERE id = ?", Employee, id2);
            Employee e1 = check <Employee> ts1.getNext();
            Employee e2 = check <Employee> ts2.getNext();
            int tmp = e1.id;
            e1.id = e2.id;
            e2.id = tmp;
            _ = empDB->update("UPDATE Employee SET name = ?, age = ? WHERE id = ?", e1.name, e1.age, e1.id);
            _ = empDB->update("UPDATE Employee SET name = ?, age = ? WHERE id = ?", e2.name, e2.age, e2.id);
        }
        http:Response res = new;
        caller->respond(res) but { error e => log:printError("Error in sending response", err = e) };
    }
```

It's a single endpoint, so all the operations work on a single database (and even a single table). So this should do a local transaction. But rather, it tries to do a two-phase commit, and it fails. Two problems here, one being, trying to do a two-phase commit, and the actual two-phase commit failing. The error log is as below:-

2018-08-22 01:51:50,845 INFO  [ballerina/transactions] - Created transaction: c3f6aee8-d455-488d-9e73-b88361078543 
2018-08-22 01:51:50,951 INFO  [ballerina/transactions] - Marked initiated transaction for abortion 
2018-08-22 01:51:50,953 INFO  [ballerina/transactions] - Marked initiated transaction for abortion 
2018-08-22 01:51:50,955 INFO  [ballerina/transactions] - Aborting initiated transaction: c3f6aee8-d455-488d-9e73-b88361078543:1 
error: error, message: error in transaction end: hazard
	at dataservice.employeeSwapByIds(mysql_ds.bal:126)

This only happens in MySQL, the same service interfaced with Oracle works fine. But still, it does a two-phase commit to get it done. 

The full source code can be found here: https://github.com/lafernando/samples/tree/master/ballerina/dataservices. The service resource name is "employeeSwapByIds".

**Comment by Manuri** [comment]
Closing according to the discussion @ballerina-dev mailing list.
https://groups.google.com/forum/#!topic/ballerina-dev/ur8sekIxPqg
