### ISSUE TITLE
add update feature to ballerina CLI

### ISSUE THREAD

**Issue by rabbah** [ballerina-platform/ballerina-lang#10155]
**Description:**
It is convenient when using the ballerina CLI to know if you're using the latest version, or to be notified of a new version that might be available. Additionally, an auto-update feature would be nice.

Suggested model:
```
> ballerina --version --update-check
You are currently on version 0.975

Checking for updates... 
New version available 0.981.1

To upgrade run:
ballerina --update 0.981.1
```

`--update-check` could be abbreviated as `-u` and `--update` could default to `latest` if no version is specified.

**Suggested Labels (optional):**
enhancements, cli

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
This is available with ballerina-1.0.0-beta the command is `ballerina dist update`
