### ISSUE TITLE
marcus/gcontacts3 Google Contacts Ballerina library gives only few contacts when all contatcs requested

### ISSUE THREAD

**Issue by HishanIndrajith** [ballerina-platform/ballerina-lang#10153]
**Description:**
marcus/gcontacts3 Google Contacts Ballerina library gives only few contacts when all contatcs requested. Also erandig/gcontacts3 library doesn't work with my ballerina version. My version is 0.981.0.

**Steps to reproduce:**
This is my code 

import ballerina/config;
import ballerina/log;
import ballerina/io;
import marcus/gcontacts3;

documentation{A valid access token with google contact access.}
string accessToken = config:getAsString("ACCESS_TOKEN");

documentation{The client ID for your application.}
string clientId = config:getAsString("CLIENT_ID");

documentation{The client secret for your application.}
string clientSecret = config:getAsString("CLIENT_SECRET");

documentation{A valid refreshToken with gmail and google sheets access.}
string refreshToken = config:getAsString("REFRESH_TOKEN");

documentation{Sender email address.}
string email = config:getAsString("USER");

endpoint gcontacts3:Client contactsClient {
    clientConfig: {
        auth: {
            accessToken: accessToken,
            refreshToken: refreshToken,
            clientId: clientId,
            clientSecret: clientSecret
        }
    }
};

function getCustomerDetailsFromGSheet() returns (xml) {
    //Read all the values from the sheet.
    xml values = check contactsClient->getAllContacts(email);
    log:printInfo("Retrieved contacts xml from mail"+ sheetName);
    return values;
}

function main(string... args) {
    log:printDebug("getting contacts");
    xml result = getCustomerDetailsFromGSheet();
    xml x =result.entry.title;
    io:println(x.getTextValue());
    //io:println(result);
}

**Affected Versions:**
0.981.0
**OS, DB, other environment details and versions:**
Windows 10
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
@HishanIndrajith marcus/gcontacts3 is a package created and maintained by community contributors. Therefore correct place to report such packages would be to their original source repository. Hence I have create an issue [1] in the source repo, and closing this one.

Please follow up on [1].

[1] https://github.com/NipunaMarcus/package-gcontacts/issues/1
