### ISSUE TITLE
Fix and enable ServerSocketTest

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#10179]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/10178/ disabled the test which hangs in windows

Thread dump from @hasithaa 
https://ballerina-platform.slack.com/files/U48HZ68S2/FCEDP5H6W/thread-dump.txt

**Comment by wggihan** [comment]
This issue got fixed along with the server socket redesign.
