### ISSUE TITLE
Support throwing Ballerina error struct

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#10216]
**Description:**
Current Ballerina VM doesn't support throwing ballerina error struct and when we need to throw any error from native code, we throw runtime exception. This will let any runtime exceptions to propagate to VM. Better if the VM can support to trigger throw behavior with a Ballerina error struct.

**Comment by hasithaa** [comment]
@SupunS Can you verify this?

**Comment by vinok88** [comment]
ErrorValue is a Java Throwable in Jballerina. Now you can throw them as java exceptions.
