### ISSUE TITLE
[Editor][Improvement] Show unused variables/imports

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#1023]
Show unused variables/imports in the source view

But getting the following error in the backend
shoppingList.bal: Duplicate import package declaration: ballerina.net.http in shoppingList.bal:3

**Comment by uthaiyashankar** [comment]
Moving from https://github.com/ballerina-lang/composer/issues/149

**Comment by hevayo** [comment]
This feature should be provided by the language server. Please see https://github.com/Microsoft/vscode/issues/51104 for a related discussion.

**Comment by anupama-pathirage** [comment]
Unused imported are treated as compile time errors with ballerina-1.0.0-alpha3 version. So it is shown as an error in editors.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/16300038/63678801-99aea380-c80d-11e9-9dd5-e52b99a564de.png">

Unused variables are still not supported

**Comment by episodeyang** [comment]
Seems that unused token is supported with jedi. see screenshot below
<img width="584" alt="Screenshot 2019-08-31 10 56 13" src="https://user-images.githubusercontent.com/630490/64062441-35f5f300-cbde-11e9-8221-00babc3e3748.png">

**Comment by nadeeshaan** [comment]
> Seems that unused token is supported with jedi. see screenshot below
> <img alt="Screenshot 2019-08-31 10 56 13" width="584" src="https://user-images.githubusercontent.com/630490/64062441-35f5f300-cbde-11e9-8221-00babc3e3748.png">
> 
> Is there a way to make the token "grayed out"?

@episodeyang Currently we are not supporting unused variable highlight in the plugin(Through language server). Currently, we are working on a linter implementation and we'll be shipping this capability with it.

**Comment by hasithaa** [comment]
https://github.com/ballerina-platform/ballerina-spec/issues/356 created, Once this is added to the compiler side, We can close this issue.

**Comment by nadeeshaan** [comment]
This has been resolved according to the latest implementation. Hence closing
