### ISSUE TITLE
Change function returns from BValue[] to BValue

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#10259]
**Description:**
Currently the function [return types](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-core/src/main/java/org/ballerinalang/util/codegen/CallableUnitInfo.java#L48) and the [return values](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-core/src/main/java/org/ballerinalang/util/program/BLangFunctions.java#L190) are arrays.

Since multi-return is not supported now, we should be able to change the return type/value accordingly.

**Comment by SupunS** [comment]
In JBallerina runtime, function returns are implemented as stated in this issue. Hence removing the label.

**Comment by hasithaa** [comment]
Old issue, No longer applies for Swan Lake.
