### ISSUE TITLE
ballerina uninstall and ballerina list packages commands

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#10260]
**Description:**
Requesting for "ballerina uninstall" and "ballerina list packages" or "ballerina packages" commands. Former command should uninstall a package and later should list all the installed packages with meta like version, etc.

**Comment by hemikak** [comment]
@raj-rajaratnam When you say 'list all the installed packages', does this mean all the packages that has been pulled from central regardless of which project(s) they are being used ? If so, what kind of scenario would it be useful ?

Currently we are looking to show the dependencies of a specific project in the form of a tree.

**Comment by raj-rajaratnam** [comment]
@hemikak, I want to be able to list all the packages (\w meta) installed in my system. This is similar to "docker images" command. Couple of usecases, I want to check whether or not a package is installed in my system, I want to check what is the version of the package installed in my system. 

By the way, this command should not only work for packages pulled from ballerina central, but also for packages installed manually.
