### ISSUE TITLE
Improve tuple element identification

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#10267]
**Description:**
With the initial changes to the main/entry function with https://github.com/ballerina-platform/ballerina-lang/pull/10060, tuple elements are identified by splitting values at [commas](https://github.com/ballerina-platform/ballerina-lang/blob/736395f10ac33d4620a5212b6949cb644ec0c77d/bvm/ballerina-core/src/main/java/org/ballerinalang/util/cli/ArgumentParser.java#L399). 

This could cause issues if the tuple elements themselves include commas. This logic needs to be improved, probably by introducing a parser for better identification.

**Comment by SupunS** [comment]
@MaryamZi Can you provide a sample where the mentioned issue can be observed?
