### ISSUE TITLE
Separate LangServer classes from composer services jar

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#10304]
Right now, in ballerina distribution, all LS classes are being packed into composer services jar.

Separate them as below.

lib/resources/composer/services/*.jar
lib/resources/lang-server/*...core.jar

Also we need to pack stdio-launcher into ballerina distribution
lib/resources/lang-server/*...stdio-launcher.jar

**Comment by kaviththiranga** [comment]
Also, in maven-shade-plugin configuration, ATM we have asked to include all except a few artifacts which has resulted in an uncontrolled bundling of all transitive dependencies redundantly to final pack. Most classes are duplicated in core class path and composer class path. 
Instead we have to exclude all deps by default and selectively whitelist the ones that are mandatory.

This will reduce the pack size as well.

**Comment by kaviththiranga** [comment]
https://github.com/ballerina-platform/ballerina-lang/blob/master/composer/modules/server/distribution/pom.xml

**Comment by NipunaRanasinghe** [comment]
ATM I've added the stdio-launcher jar to lib/resources/composer/services/.jar with the PR https://github.com/ballerina-platform/ballerina-lang/pull/10494 and therefore it should be refactored along with the above changes.

**Comment by NipunaMarcus** [comment]
We have refactored to achieve this changes with following commit.
Commit:https://github.com/ballerina-platform/ballerina-lang/commit/4401fef6094561f2f7b1cdb2340c7684a5a97fd6

Hence closing this issue.
