### ISSUE TITLE
getFormParams() method does not work for file type.

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#10318]
**Description:**

When a file is sent as form data, getFormParams() method returns an error as "message:"Entity body is not text compatible since the received content-type is : multipart/form-data", cause:null"

**Steps to reproduce:**
@http:ResourceConfig {
        methods: ["POST"],
        path: "/client"
    }
    insertClientResources(endpoint client, http:Request request) {
        match request.getFormParams(){
            map<string> formParams=> io:println("formParams: ",formParams);
            error e => io:println("error: ", e);
        }
    }

**Affected Versions:**
Latest

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Comment by arukshani** [comment]
getFormParams() method is applicable only for the content-type "application/x-www-form-urlencoded". If your content type is multipart/form-data please use getBodyParts() method instead. 

Sample usage can be found here.
1) https://ballerina.io/learn/by-example/request-with-multiparts.html
2) https://ballerina.io/learn/by-example/response-with-multiparts.html

More info can be found here >>  https://github.com/ballerina-platform/ballerina-lang/issues/10214

**Comment by dulanjalidilmi** [comment]
I want to send both text values and file data along with the same request. I tried to use getBodyParts(), but it does not support type text. Once text data is sent, getContentType() returns an error as  "message: error while parsing Content-Type value: Unable to find a sub type".

**Comment by arukshani** [comment]
It should work with both the text values as well as file data. Can you send your sample and the way you called your service?

**Comment by dulanjalidilmi** [comment]
Discussed with the ballerina team and getBodyParts() can be used for type text as well.
