### ISSUE TITLE
Unable to run a single .bal file from inside a project root dir

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#10364]
**Description:**
Consider the following project dir tree.
```
 .
├── Ballerina.toml
├── test
   └── foo
       ├── ballerina.conf
       └── test.bal
```
When trying to run the `test.bal` file from the project dir the following error is given.
```
ballerina: cannot find file 'test/foo/test.bal'
```
However, if I try to run it from inside the `/test` dir, it runs fine.

Is this the expected behaviour? If not, shall we improve the error message given in this case, since it's not actually a file not found error.

**Comment by Shan1024** [comment]
This is the expected behavior AFAIK since `test` is considered as a package.

**Comment by pubudu91** [comment]
But if I really want to just run a single file, then I can't do it from the project root dir. Doesn't that seem a bit restrictive?

However, if that is the expected behaviour, then we should not be saying cannot find file. WDYT?

**Comment by Shan1024** [comment]
It seems bit restrictive, but the other alternative is to place the file directly in the root directory.

We definitely need to change the error message. It is misleading.
