### ISSUE TITLE
Compiler allows passing tuple parameter as a parameter to a function but after it is not available in the function context

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#10382]
**Description:**
it is allowed to pass a tuple parameter as a function parameter according to the grammar.  
```
annotationAttachment* LEFT_PARENTHESIS typeName Identifier (COMMA typeName Identifier)* RIGHT_PARENTHESIS       #tupleParameter
```
But when compiled this is not added to the parameters list of the function node hence it is not available in the function context. There are no any compilation or runtime errors thrown for this as well. 

But when try to invoke this function compilation error "**too many arguments in call**" is thrown.
 
**Steps to reproduce:**
Sample code is as below.
```ballerina
import ballerina/io;

function testFunction((int e, int d)) {
 
}

public function main(string... args) {
    // testFunction((0, 0));
    io:println("Hi Marcus");
}
```
1. Run above code
2. Uncomment testFunction invocation in main function and run again.

**Affected Versions:**
0.981.2-SNAPSHOT

**Comment by vinok88** [comment]
Hi Nipuna,
 Grammer rule you have mentioned is incorrect/bug. You are not getting the correct error because of that. It will be fixed along with the tuple binding improvements that are WIP. The correct way to define a tuple as a function parameter is below,
```java
function testFunction((int, int) a) {
}
```

**Comment by MaryamZi** [comment]
Compilation now fails for the above sample at L3 (0.992.0-m8).

The following works 
```ballerina
import ballerina/io;

function testFunction([int, int] t) {
 
}

public function main(string... args) {
    testFunction([0, 0]);
    io:println("Hi Marcus");
}
```
