### ISSUE TITLE
Improvements related to ballerina channels

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#10388]
**Description:**
This issue is to track the improvements to the channels implementation done in PR https://github.com/ballerina-platform/ballerina-lang/pull/10334

- Current implementation only supports the simple types, xml and json as the channels's constraint type.
- Assume we have a Json key. If the order of the elements inside the json is changed, they will not be matched as the same key.
- Taint analysis should be revisited.

**Comment by hasithaa** [comment]
@vinok88 Shall we resolve this issue. As we are removing `channel` from the compiler.

**Comment by vinok88** [comment]
+1, let's close this by referencing the channel remove from the compiler PR.

**Comment by vinok88** [comment]
Channels have been deprecated with PR https://github.com/ballerina-platform/ballerina-lang/pull/16390
