### ISSUE TITLE
change VSCode plugin activation policy to app startup

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#10390]
At the moment, Ballerina plugin for VSCode is only getting activated when a bal file is opened. This was fine for lang-server and diagram rendering features as they anyway needed a file to be opened to function properly. However, some new features such as BBE dashboard, should work irrespective to that policy as it makes sense the dashboard to be opened as the first step before creating a Ballerina project.

As per the above reason, we need to activate Ballerina plugin on VSCode startup it self. However, we can lazily start language server when a bal file is opened, rather than on plugin activation, to reduce unnecessary resource utilization.

**Comment by kaviththiranga** [comment]
https://code.visualstudio.com/docs/extensionAPI/activation-events#_activationevents

**Comment by kaviththiranga** [comment]
pushed the changes needed to make it run on startup
https://github.com/ballerina-platform/ballerina-lang/commit/331efde9fcf5dc584ed7c1fd797e79ea230ee4fc

Some regressions: need to import "ballerina show diagram" command to not open diagram view when there is no bal file is open - simply display an error/warning saying there is no bal file is open

**Comment by roonyh** [comment]
The current behavior is to not show that button at all when there is no bal file open. Even after the plugins activation the button is only shown when a bal file is open. Is there a reason to change this behavior?

**Comment by kaviththiranga** [comment]
@roonyh this is about the command. Yeah, the button is only visible when there's a bal file open, but command is registered when the plugin is activated.

**Comment by kaviththiranga** [comment]
The root cause is fixed by having two activation policies, one for on-language and one for on-command.
Fixed with
https://github.com/ballerina-platform/ballerina-lang/commit/d6d79c63a10d641981a23105d154cf9f7b671765
