### ISSUE TITLE
Record --> Map --> Inner Record conversion error

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#10405]
**Description:**
Converting a record to a map and then attempting to convert an element of the map, which was originally a record (say `Person`), to a record (of type `Person`) fails.

```bal
import ballerina/io;

type Person record {
    string fname,
    string lname,
    int age,
};

type Movie record {
    string title,
    string year,
    string released,
    Person writer,
};

public function main() {
    Movie theRevenant = {
        title: "The Revenant",
        year: "2015",
        released: "08 Jan 2016",
        writer: {
            fname: "Michael",
            lname: "Punke", age: 30
        }
    };

    map m = <map>theRevenant;
    Person writer = check <Person>m["writer"];
    io:println(writer.age);
}
```
fails with the error
```
error: error, message: 'map' cannot be cast to 'Person'
	at main(test.bal:28)
```

This fails at CPU `checkCast`, introduced because of the `any` to `record` conversion, since a `map` to `record` cast check is not defined. 

**Related Issues:**
#10402

**Comment by MaryamZi** [comment]
Current workaround is to convert the element to a map first and then to convert the map to the record.
```bal
map writerMap = check <map>m["writer"];
Person writer = check <Person>writerMap;
```

**Comment by warunalakshitha** [comment]
with introduction of stamp and convert methods with 0.990.0 we can write the above code as below.

```bal
import ballerina/io;

type Person record {
    string fname = "";
    string lname = "";
    int age = 0;
};

type Movie record {
    string title = "";
    string year = "";
    string released = "";
    Person writer;
};

public function main()  {
    Movie theRevenant = {
        title: "The Revenant",
        year: "2015",
        released: "08 Jan 2016",
        writer: {
            fname: "Michael",
            lname: "Punke", age: 30
        }
    };

    var m =  map<anydata>.convert(theRevenant);
    if (m is map<anydata>) {
        Person| error writer =  Person.convert(m["writer"]);
        if(writer is Person){
            io:println(writer.age);
        }
    }
}

```

**Comment by warunalakshitha** [comment]
This will output as 30. similer test case can be found here.
https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/ballerina-unit-test/src/test/resources/test-src/expressions/conversion/native-conversion.bal#L644

**Comment by MaryamZi** [comment]
Since we only allow conversions with `anydata` I guess the conversion working with `map<anydata>` is sufficient.

Closing the issue since it is now fixed.

**Comment by ponsilva** [comment]
Please update the example 
https://ballerina.io/learn/by-example/json-struct-map-conversion.html 
with this useful information, thanks

**Comment by MaryamZi** [comment]
@ponsilva We've opened a PR https://github.com/ballerina-platform/ballerina-lang/pull/12765 to update this BBE. Thank you!
