### ISSUE TITLE
Support tuple destructure inside arrow expression parameters

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#10419]
**Description:**
When the inferred type of a parameter inside the arrow expression is a tuple, we have to use index based access for the tuple to use it's parameters. For example:
```ballerina
function ((string, boolean), string) returns string lambda = (tupleEntry, str) => tupleEntry[0];
```

Tuple destructure should be allowed inside the arrow expression parameters as follows:
```ballerina
function ((string, boolean), string) returns string lambda = ((tupleStr, tupleBool), str) => tupleStr;
```

**Comment by hasithaa** [comment]
@Anoukh This seems to be invalid now. Spec doesn't support this.
