### ISSUE TITLE
[Debugger] Required to specify the full package name to evaluate global variables from other packages

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#10433]
**Description:**
With the newly introduced variable evaluation feature in Ballerina debugger, we required to provide the full package name including org name and version to evaluate a global variable from a different package. This imposes the following problem,

- Cannot evaluate a global variable from other packages by specifying the package alias (Need to preserve the alias info at the runtime to overcome this problem)

**Affected Versions:**
0.981.2-SNAPSHOT

**Suggested Labels (optional):**
Component/Debugger, Type/Improvement

**Suggested Assignees (optional):**
Pranavan

**Comment by NipunaRanasinghe** [comment]
Closing since global variable support is already added in the jBallerina debugger implementation
