### ISSUE TITLE
'ballerina init' command goes in a loop when you keep on providing invalid inputs

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#10438]
**Description:**
'ballerina init' command goes in a loop when you keep on providing invalid inputs. Ideally this should exit after attempting for 3 times.

**Steps to reproduce:**

- Create an empty directory
- Run 'ballerina init -i'
- For every option prompted keep on pressing invalid inputs
- The command will go in a loop without exiting until you press "f" (finish)

**Affected Versions:**
0.981.2-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu

**Comment by hevayo** [comment]
From ballerina 1.0 alpha init command will be removed hence closing the issue.
