### ISSUE TITLE
[VSCode] [Debugger] Add support for variable evaluation feature

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#10436]
**Description:**
PR https://github.com/ballerina-platform/ballerina-lang/pull/10429 introduces variable evaluation feature in the Ballerina debugger, which can be considered as an initial version of the expression evaluation feature. We need to add support for this in VSCode plugin.

**Suggested Labels (optional):**
Type/Improvement

**Comment by pranavan15** [comment]
Following are the expected formats of request/response from/to client,

Expected request json format: 

-  `{ "command": "EVALUATE_EXPRESSION", "expression": <exp>, "threadId": <threadId> }`

Response json format:
- Successful scenario:
   `{ "code": "EXPRESSION_RESULTS", "message": { "status": "success", "results": <value> } }`

- Unsuccessful scenario:
   `{ "code": "EXPRESSION_RESULTS", "message": { "status": "failure", "results": "cannot find variable '<varName>'" } }`

- Internal error scenario (When json generation fails):
   `{ "code": "EXPRESSION_RESULTS", "message": { "status": "failure", "results": "internal error" } }`

**Comment by NipunaRanasinghe** [comment]
Closing since the variable evaluation support is introduced with #23413.
