### ISSUE TITLE
Some 'ballerina build' command errors are not logged

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#10454]
$title. eg: compiling a package with empty sources.

Also, some of the build errors (errors on pulling dependencies, etc) does not get appended to the BLangDiagnosticLog. Hence ballerina compilation doesn't fail even if there are errors.

**Comment by NatashaWso2** [comment]
This issue is fixed in the latest master with  #10589, hence closing this issue.
