### ISSUE TITLE
Provide support for obtaining stored procedure OUT param values without having to know the number of OUT params or the types of them

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#10461]
**Description:**
$Subject. 
ATM it is required to know how many OUT params will be present in a stored proc call and what are the types of them. Need to check the possibility of improving the call operation such a way that, calling a stored proc doesn't require having to know those details.

**Comment by daneshk** [comment]
@niveathika please check whether this is still valid with new design

**Comment by niveathika** [comment]
There are 2 requirements outlined here,
1. User does not need to know the type of out parameter
    This is implemented in the new design. USer just have to define a variable such as, `sql:OutParameter test = new;`

2. User does not need to specify the out parameters
    This will not be a valid API. Even if with the metadata we register the out parameters we still need to know to which parameters we need to bind the out parameters returned. Let's say even if we bind to params with same name, this will be error prone since there can be typos, case issue. -1 for this requirement.

**Comment by niveathika** [comment]
@daneshk Your thoughts on this. IMO we cannot achieve the second requirement

**Comment by niveathika** [comment]
As discussed here, https://github.com/ballerina-platform/ballerina-lang/issues/25869 the first point by accessing datatypes using metadata call has security vulnerabilities and we have reverted the change. 

Since the above requirements will need metadata call which has security vulnerabilities, we have decided not to add this support.
