### ISSUE TITLE
Issue in database operations written inside the transaction block

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#10493]
**Description:**
I tried to execute an update operation inside the transaction block. Although the result status returned from the update transaction gives 1, relavent table in the database was not updated. After about 2-4 minutes, the transaction was auto-commited  and relevant table was updated. Then the same transaction would be committed for several more times. 

<img width="1620" alt="screen shot 2018-09-21 at 10 05 55 am" src="https://user-images.githubusercontent.com/38608578/45860845-0ceea080-bd87-11e8-855d-b44dbc7d3368.png">

**Steps to reproduce:**
```balleirna
function insertToAssignmentTable(int studentId, string content, string fileName, string description) returns boolean {
    log:printInfo("Inserting Data to Submission Table: ");
    transaction with retries = 4, oncommit = onCommitFunction, onabort = onAbortFunction {
        var result = mysqlEP->update(QUERY_TO_INSERT_DATA_TO_SUBMISSION, studentId, content, fileName, description);
        match result {
            int c => {
                if (c < 0) {
                    log:printError("Unable to insert Data into Submission table");
                } else {
                    handleUpdate(result, "Insert to Submission Table");
                    log:printInfo("Successful! Inserted Into Submission Table");
                    return true;
                }
            }
            error err => {
                log:printError(err.message);
            }
        }
    } onretry {
        io:println("Retrying transaction");
    }
    return false;
}
```

A sample is attached.
[studentAssignmentPortal.zip](https://github.com/ballerina-platform/ballerina-lang/files/2403954/studentAssignmentPortal.zip)

**Affected Versions:**
0.980.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulanjalidilmi** [comment]
The issue did not fix with ballerina 0.981.1 as well.

**Comment by anupama-pathirage** [comment]
@ayomawdb This seems a regression issue. Return is not allowed within the transaction block.

**Comment by dulanjalidilmi** [comment]
Hi @ayomawdb, I changed the code accordingly. Thank you for the temporary resolution.

**Comment by ayomawdb** [comment]
Hi @dulanjalidilmi, 

This is to keep you updated that PR #10567 resolve your issue partially. Basically, this will prevent transaction from getting auto-committed multiple times after the observed timeout. 

`return` statements are not allowed within a `transaction` block as @anupama-pathirage  mentioned. However, due to a bug `return` within a `match` block within a `transaction` block is allowed. We are working on a fix for this.

**Comment by ayomawdb** [comment]
@dulanjalidilmi  PR #10569, which is already merged with the master will resolve the original issues by disallowing `return` within `match` blocks within `transaction` blocks. Thank you for bringing this to our attention!
