### ISSUE TITLE
**Suggested Labels (optional):**

### ISSUE THREAD

**Issue by thileep29** [ballerina-platform/ballerina-lang#10513]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
@thileep29 Was this created mistakenly ?

**Comment by Shan1024** [comment]
Closing the issue since this seem to have opened by mistake.
