### ISSUE TITLE
Support for binding patterns

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#10525]
**Description:**
Binding patterns are used to support destructuring, which allows different parts of a single
structured value each to be assigned to separate variables at the same time.

A binding pattern may succeed or fail in matching a value. A successful match causes
values to be assigned to all the variables occurring the binding-pattern.
A binding pattern matches a value in any of the following cases.
a simple-binding-pattern matches any value; if the simple-binding-pattern consists of
a variable-name then it causes the matched value to be assigned to the named
variable;
- a tuple-binding-pattern (p1, p2, …, pn) matches a list value of length n [v1, v2, …, vn]
if pi matches vi for each i in 1 to n;
- a record-binding-pattern { f1: p1, f2: p2, …, fn: pn, r } matches a mapping value m
that has fields f1, f2, ... , fn if pi matches the value of field fi for each i in 1 to n, and if
the rest-binding-pattern r, if present, matches a new mapping x consisting of all the
fields other than f1, f2,...,fn

    - if r is !..., it matches x if x is empty
    - if r is ...v it matches any mapping x and causes x to be assigned to v
    - if r is missing, the match of the record-binding-pattern is not affected by x
    - a field-binding-pattern consisting of just a variable name x is equivalent to a
field-binding-pattern x: x

- an error-binding-pattern error(rp, dp) matches an error value if rp matches the error
reason and dp matches the error detail record;
- an error-binding-pattern error(rp) is equivalent to error(rp, _)

**Comment by Anoukh** [comment]
All types of binding patterns are supported now. 
Tuple and Record Binding patterns: https://github.com/ballerina-platform/ballerina-lang/pull/11053
Error binding pattern: https://github.com/ballerina-platform/ballerina-lang/pull/13932
