### ISSUE TITLE
Strange behavior once same file rename several times in  Ballerina  composer

### ISSUE THREAD

**Issue by nimanthag** [ballerina-platform/ballerina-lang#10537]
**Description:**
Automatically switch between files once same file rename several times in Ballerina composer.This continue until we forcefully quit the composer

**Steps to reproduce:**
Rename same file several times. screen capture video attached here.
**Affected Versions:**
version - Ballerina 0.981.1

**OS, DB, other environment details and versions:**
OS - macOS High Sierra version - 10.13.6
Ballerina 0.981.1

**Related Issues (optional):**

**Suggested Labels (optional):**
component/composer 

**Suggested Assignees (optional):**

[Ballerina_Composer_Issue.zip](https://github.com/ballerina-platform/ballerina-lang/files/2413885/Ballerina_Composer_Issue.zip)

**Comment by ayomawdb** [comment]
@nimanthag Thank you for reporting this issue. We'll update you on the status and resolution as early as possible.

**Comment by NipunaMarcus** [comment]
@nimanthag Thank you for reporting this issue.
 
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin  hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
