### ISSUE TITLE
[VSCode] Ballerina VS Code commands are not working.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#10532]
**Description:**
$Subject.

**Steps to reproduce:**
1) Open VSCode.
2) type Ctrl + Shift + P
3) Type one of the Ballerina commands.
4) It fails with following error.
![image](https://user-images.githubusercontent.com/1356214/45991597-42ef9580-c0a3-11e8-9a08-6cc988455230.png)

**Affected Versions:**
Nightly 0.981.2-SNAPSHOT (Sep 24, 2018)

**OS, DB, other environment details and versions:**
Windows 10.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/commit/5fd4cdf95213faa2e1796798784606018bb89f61
