### ISSUE TITLE
Unable to copy console text in Composer into clipboard

### ISSUE THREAD

**Issue by Savidude** [ballerina-platform/ballerina-lang#10539]
**Description:**
Text information such as logs, and errors that get displayed on the console cannot be copied to clipboard.

**Affected Versions:**
0.981.1

**OS, DB, other environment details and versions:**
macOS High Sierra Version 10.13.6

**Suggested Labels (optional):**
component/composer

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin. As VS code has a terminal and consoles to show debug, problems and output, closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
