### ISSUE TITLE
Ballerina Composer shows "Too Many Open Files" and doesn't save

### ISSUE THREAD

**Issue by pasanbox** [ballerina-platform/ballerina-lang#10536]
**Description:**
When attempting to save a source file, Ballerina composer showed error "Too Many Open Files" and didn't save the document. Closing other open files in the composer did not fix the issue. I had to restart the Composer completely for it to start saving files again.

**Steps to reproduce:**
I'm not clear about how to reproduce. It just happened occasionally.

**Affected Versions:**
0.981.1

**OS, DB, other environment details and versions:**
macOS High Sierra version 10.13.4

**Suggested Labels (optional):**
Ballerina-Composer

**Comment by MadhukaHarith92** [comment]
I could also reproduce this issue. This happened randomly and only once so unclear about the steps to reproduce.

**Comment by Shan1024** [comment]
This issue seems to occur due to the soft and hard limits set in the mac and ubuntu OSs. We need to increase these limits from the ballerina scripts.
