### ISSUE TITLE
Implementing better tab manipulation in Composer

### ISSUE THREAD

**Issue by Savidude** [ballerina-platform/ballerina-lang#10540]
**Description:**
Update tab manipulation through the addition of functionalities such as:
- Tabs could be moved around
- Implementation of functions such as "Close tabs to the right", "Close other tabs", etc.

**Affected Versions:**
Ballerina 0.981.1

**OS, DB, other environment details and versions:**
macOS High Sierra Version 10.13.6

**Suggested Labels:**
Component/Composer, Type/Improvement

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin  hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
