### ISSUE TITLE
Reformat code moves some values to new lines unexpectedly

### ISSUE THREAD

**Issue by pasanbox** [ballerina-platform/ballerina-lang#10545]
**Description:**
I'm applying **_Edit->Reformat_** from Ballerina Composer on the below piece of code.

<img width="736" alt="screen shot 2018-09-25 at 2 35 17 pm" src="https://user-images.githubusercontent.com/1252833/46004442-89a7b480-c0d0-11e8-8640-0b533bfd3dea.png">

The Composer does some unexpected formatting as shown below. Note the value in the return statement and two values from the config type moved to new lines which is unexpected behaviour.

<img width="769" alt="screen shot 2018-09-25 at 2 38 33 pm" src="https://user-images.githubusercontent.com/1252833/46004514-bcea4380-c0d0-11e8-84aa-39fd8054ff25.png">

**Steps to reproduce:**
Please refer the attached video.
[ballerina_composer_reformat_error.zip](https://github.com/ballerina-platform/ballerina-lang/files/2414534/ballerina_composer_reformat_error.zip)

**Affected Versions:**
0.981.1

**OS, DB, other environment details and versions:**
macOS High Sierra version 10.13.4

**Related Issues (optional):**

**Suggested Labels (optional):**
Component/Composer

**Suggested Assignees (optional):**

**Comment by NipunaMarcus** [comment]
Thank you for reporting this.

We are refactoring format according to a new architecture. We are currently working on the implementation which available in following branch.  https://github.com/NipunaMarcus/ballerina/tree/formatting-fixes

We are trying to release this with the next release and will update you on this.

**Comment by NipunaMarcus** [comment]
This issue is fixed hence we have pushed the new implementation (PR: https://github.com/ballerina-platform/ballerina-lang/pull/10989) of the ballerina source formatting.
