### ISSUE TITLE
[VSCode] Zoom-in shortcut combination is wrong

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#10577]
**Description:**
> Zoom-in shortcut combination should be `[Ctrl]+[+]` to match semantically to Zoom-out shortcut combination. Current combination is `[Ctrl]+[=]`.
>
> Also it is the common practice of shortcut keys for Zoom In/Out.
 
![image](https://user-images.githubusercontent.com/7569427/46127042-02cc1680-c24d-11e8-88fd-9e8115109ac3.png)

**Steps to reproduce:**
1. Open VSCode.
1. Type Ctrl + Shift + P
1. Navigate to `View: Zoom In` shortcut

**Affected Versions:**
v0.982.0

**OS, DB, other environment details and versions:**
Windows 10

**Suggested Labels (optional):**
[Type/UX]

**Comment by vinok88** [comment]
Hi Jerad,
I agree that it should be [Ctrl]+[+]  for zoom in.
But this is not something coming from the Ballerina plugin. It is the default Vscode's behavior. Please refer [1]. I think we should keep the editors behavior intact even though we feel it wrong. Btw, you are not alone, refer [2] :)

[1] - https://code.visualstudio.com/docs/getstarted/keybindings
[2] - https://github.com/Microsoft/vscode/issues/7872

**Comment by jeradrutnam** [comment]
Thanks @vinok88, agree on that. Sorry I thought we pushed that command. Didn't realize it earlier.
