### ISSUE TITLE
Support annotation processing within Ballerina code

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#10576]
In order to introduce an custom annotation and make use of the custom annotation, it is required to bring in an annotation processor as a compiler extension. This extension should be written in Java as of now. 

Instead of this approach, it is required to allow Ballerina programmers introduce new annotations and attach behavior / make use of the new annotations within the Ballerina code itself. It is required to provide a Ballerina API to process annotations.

**Comment by MaryamZi** [comment]
The annotation access expression is now available to access annotations at runtime.

```ballerina
import ballerina/io;

type Annot record {
    string s;
    int i;
};

annotation Annot ann on object type;

@ann {
    s: "hello",
    i: 1
}
type Foo object {
    
};

public function main() {
    Annot? value = Foo.@ann;
    io:println(value);
}
```

```cmd
$ ballerina run test.bal 
s=hello i=1
```

**Comment by hasithaa** [comment]
Now Annotation access expression provides this functionality.
