### ISSUE TITLE
Enable building IDEA plugin in gradle build

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#10600]
**Description:**
We need to enable building the IDEA plugin in maven build when we use the `release` profile. Also, need to have a new profile (eg - tooling) which will build the plugin along with other components.

**Comment by NipunaRanasinghe** [comment]
@Shan1024 As per the offline discussion we had, this will significantly increase the build time, as the IntelliJ platform SDK (~550MB) is required to be downloaded each time when building.

**Comment by Shan1024** [comment]
@NipunaRanasinghe - Small correction, SDK is not getting downloaded all the time. It only gets downloaded once and then it gets cached.

**Comment by hevayo** [comment]
@Shan1024 I guess in the builder since we are starting from a fresh image it will not be cached. If we are doing this we need to add that to the base image otherwise it will get downloaded. 

Since we are working on migrating to gradle It might be best to keep this till then.
