### ISSUE TITLE
[VSCode] Auto completion not works for public func

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#10606]
**Description:**
> Public function auto complete not works

![image](https://user-images.githubusercontent.com/7569427/46200563-970eaa00-c32f-11e8-808e-0f100be846c3.png)

**Steps to reproduce:**
1. Type `public func` and do `[Ctrl] + [Space]`

**Affected Versions:**
v0.982.0-RC

**OS, DB, other environment details and versions:**
Windows 10

**Suggested Labels (optional):**
[Type/UX]

**Comment by NipunaMarcus** [comment]
Thank you Jerad for reporting this. We are fixing this.
