### ISSUE TITLE
An empty json returns once a data table is cast into a json and appended to a different json

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#10617]
**Description:**
Cast a data table retrieved from a select operation to a json.
Append the json to another json object.
Although the data table consists data it returns an empty json.

**Steps to reproduce:**
Please refer the following code sample

    function getAssignments(int studentId) returns json {

       json assignments;
       var response = mysqlEP->select(QUERY_TO_GET_STUDENT_ASSIGNMENTS_BY_STUDENT_ID, (), studentId, "Active");

       match response {
          table f => {
            assignments = check <json> f;
          }
          error e => io:println(e.message);
       }

        json assignmentData = {
          "studentId" : studentId,
          "assignments" : assignments
        };

         return assignmentData;
     }
**Affected Versions:**
0.982.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Anoukh** [comment]
Closing issue as this is fixed
