### ISSUE TITLE
In-memory table's hasNext() is inconsistent with tables backed by databases

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#10615]
See below example
```ballerina
import ballerina/io;

type Person record {
    string name;
    int age;
};

public function main() {
    table<Person> dt = table{};
    Person p = {name:"john", age:25};
    _ = dt.add(p);

    io:println("more items? ", dt.hasNext());
    io:println("item:", dt.getNext());
    io:println("more items? ", dt.hasNext());
    io:println("more items? ", dt.hasNext());
    io:println("more items? ", dt.hasNext());
}
```

However if the table were created from a database, then hasNext() will always return false, once the iterator reached the end of the table.

**Comment by Manuri** [comment]
For in-memory tables iterator is  reset whereas for tables backed by databases once the data is fully iterated, it will not be possible to re-iterate as the underlying resultset cursor will not be reset.

**Comment by hasithaa** [comment]
@mohanvive @anupama-pathirage Since this is no longer applicable, Shall we resolve this issue?

**Comment by mohanvive** [comment]
Yes, it is no longer valid. Let me close this..
