### ISSUE TITLE
ExternalTimeBatchWindow not working with ballerina based stream implementations

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#10613]
**Description:**
`  from teacherStream window externalTimeBatch(Teacher.timeStamp, 1000, 1000, 200)
        select name, age
        => (TeacherOutput[] t) {
            outPutStream.publish(t);
        }`
Here the last two parameters(startTime and timeOut) are optional. Query does support for optional parameters.

**Suggested Assignees (optional):**
@gimantha

**Comment by gimantha** [comment]
@LahiruJayasekara the correct way to set values for optional parameters is a bit different. refer to the below example.

```
from teacherStream window externalTimeBatch(Teacher.timeStamp, 1000, startTime = 1000, timeout = 2000) 
select name, age => (TeacherOutput[] t) {
     outPutStream.publish(t); 
}
```
