### ISSUE TITLE
Cannot return error messages once a database transaction failed

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#10627]
**Description:**
When a database transaction is written inside the transaction block, there is no method for the developer to return the error messages if the transaction is aborted or if the transaction failed to commit.

**Steps to reproduce:**

**Affected Versions:**
0.980.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@Saubhy This needs some design level change for ballerina transactions. We are currently working on refactoring transactions. This will be supported along with that effort.

**Comment by anupama-pathirage** [comment]
This is a duplicated issue of https://github.com/ballerina-platform/ballerina-lang/issues/8873. Hence closing this and keeping the original.
