### ISSUE TITLE
Support reading array of values via config API

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#10633]
**Description:**
There is no defined method to get values as arrays from conf files (No method as getAsArray)

**Suggested Method Example:**
```ballerina
config:getAsArray ("listenerConfig.keyStore.paths")
```
Issue was moved from ballerina-platform/ballerina-www#1204 and submitted by @Chamindu36

**Comment by Rajith90** [comment]
Any future version in which this feature will be available

**Comment by pubudu91** [comment]
This should be a straight forward task now that we use a library for parsing TOML. Should only be a matter of providing an API for retrieving the array. Maybe we can include this in 1.1.1?
