### ISSUE TITLE
Ballerina thows java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by shalithasuranga** [ballerina-platform/ballerina-lang#10679]
**Description:**
ballerina throws this error during run time
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /usr/lib/ballerina/ballerina-0.981.0/heap-dump.hprof ...
Unable to create /usr/lib/ballerina/ballerina-0.981.0/heap-dump.hprof: Permission denied
error: error, message: java heap space
	at main(hello_word.bal:12)

```

**Steps to reproduce:**

Simply run this

```ballerina
 string s = "ssssssssssssssssssssssssssssssss";
   while(true) {
           s += s;
   }
```

**Affected Versions:**

Ballerina 0.981.0

**OS, DB, other environment details and versions:**

Ubuntu 16.06 LTS

**Comment by shalithasuranga** [comment]
Can throw internal `bvm` runtime error instead ?

**Comment by vinok88** [comment]
Hi,
We cannot avoid the initial part of the heap-dump related error message since it is getting printed by Java when the heap dumps are enabled.

We do catch the throwable errors that include OutOfMemoryError. I have change the wording to replace Java with runtime.

Thanks
