### ISSUE TITLE
Metadata of certificates from transport layer to application layer

### ISSUE THREAD

**Issue by Chamindu36** [ballerina-platform/ballerina-lang#10677]
**Description**
When MutualSSL connection is established there is no way to read meta data of certificates such as roles which may be needed in application layer.

**Affected Versions:**
All

**Related Issues (optional):**
Issues in TCP SSL connections.

**Suggested Labels (optional):**
Type/Improvement
Type/TransportlayerProtocols

**Comment by Bhashinee** [comment]
Thanks for reporting this. We will work on this to provide this functionality in an upcoming release.

**Comment by Bhashinee** [comment]
@Chamindu36 Can you please specify what metadata of the certificate that you want?

**Comment by Chamindu36** [comment]
These are the details we required as meta data Certificate ID
Alias
Api Id
Tier used

**Comment by Bhashinee** [comment]
I am a little bit unclear on the requirement. I am under the impression that you need certificate information of the certificates sent by the client to be used in the SSL handshake in a mutual SSL scenario. Am I correct? If that is the case, normally SSL certificates do not contain the information you requested. Are you going to add them to the certificate? If so how are you going to add them?

**Comment by Chamindu36** [comment]
Ah Akka that’s ok. I need the details that includes in the certificate sent
by the user. I thought certificate ID and Alias is on the certificate as
meta daa

**Comment by Bhashinee** [comment]
I think this got fixed from this https://github.com/ballerina-platform/ballerina-lang/pull/22333
