### ISSUE TITLE
LengthWindow compiling with false output when different type parameter is passed, in ballerina based stream implementations

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#10702]
**Description:**
In the following code lengthWindow is expecting an int parameter. But code compiles and gives false output with a string parameter.
```ballerina
from inputStream window lengthWindow("abc")
        select inputStream.name, inputStream.age, inputStream.status, inputStream.school, count() as count
        group by inputStream.school
        => (Teacher [] emp) {
            outputStream.publish(emp);
        }
```
**Suggested Assignees (optional):**
 @gimantha

**Comment by gimantha** [comment]
If a string value is provided for an int argument, compilation should be failed. We are currently working on a fix
