### ISSUE TITLE
SSL related configuration options should come from a unified location

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#10733]
**Description:**

At the moment SSL related configuration records are defined locally to each package. For example, HTTP and GRPC packages use KeyStore, TrustStore records by defining as separate records. These records should come from a unique package, Maybe from the crypto package.

**Comment by ayomawdb** [comment]
KeyStore, TrustStore records are available through crypto package with 0.990.3. Check: https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/crypto/src/main/ballerina/crypto/Module.md

Relevant records should be used in HTTP / Auth and other packages to finalize on this.
