### ISSUE TITLE
Cannot have a 0 as leading digit in int

### ISSUE THREAD

**Issue by lahirus** [ballerina-platform/ballerina-lang#10732]
**Description:**
I would get an error when defined,

`int a = 03454;`

> error: .::student_info_service.bal:47:14: extraneous input '3454'

**Affected Versions:**
0.982.0

**OS, DB, other environment details and versions:**
IntelliJ Idea

**Comment by lahirus** [comment]
@Shan1024 .

**Comment by Shan1024** [comment]
@lahirus - Putting on hold since we still haven't decided whether we should allow leading `0`s.

**Comment by sanjiva** [comment]
One of the criteria we use to measure whether to do something or not is whether its already familiar to developers. We don't break familiarity without good reason.

In this case, this is a small but unusual thing and its not what's familiar as some languages (including versions of JS) interpret that as octal. Given how tiny this particular need is, there's no value in doing this.

So, closing as won't fix.

**Comment by sanjiva** [comment]
Won't fix.
