### ISSUE TITLE
Grammar Inconsistency in using Paranthesis

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#10736]
The following code gives a compile error:-

function storeApplicationEntry(ApplicationEntry entry) {
    _ = appdb->update("MERGE INTO APPLICATION_ENTRY KEY(appid) VALUES (?,?)", entry.appid, 
                     (check <json> entry).toString());
}

error: .::loan_service.bal:127:42: mismatched input '.'. expecting {'but', ',', ')', '?', '+', '-', '*', '/', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '&', '^', '...', '|', '?:', '..<'}

It has to be written in the following way to make it work:-

function storeApplicationEntry(ApplicationEntry entry) {
    json content = check <json> entry;
    _ = appdb->update("MERGE INTO APPLICATION_ENTRY KEY(appid) VALUES (?,?)", entry.appid, 
                     content.toString());
}

**Comment by hasithaa** [comment]
This need to be verified in the following sections
 - Grammar, 
 - Semantic analysis and Type checker
 - Code Analyser.

**Comment by hasithaa** [comment]
This issue has been fixed with SLP1.
