### ISSUE TITLE
Idea plugin Bal remote debugger is not working

### ISSUE THREAD

**Issue by ChinthakaSenanayaka** [ballerina-platform/ballerina-lang#10744]
**Description:**
Ballerina remote debug is not working

**Steps to reproduce:**
![bal remote debug config](https://user-images.githubusercontent.com/2564122/46656434-ad3c2600-cbcb-11e8-9c3c-b9a8fb57b589.png)

![bal remote debug error](https://user-images.githubusercontent.com/2564122/46656452-b4fbca80-cbcb-11e8-89b7-f438b158da19.png)

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
Ballerina Idea Plugin 0.982

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pranavan15** [comment]
It seems this is not really a bug. `examples` is not imported as a Ballerina module here. Hence, the client (IDEA) doesn't identify it as a valid Ballerina module. Importing `examples` as a Ballerina module should fix this problem. 
To do so, go to `File --> Project Structure (or ctrl + alt + shift + s)` and select `module` option and import.

**Comment by ChinthakaSenanayaka** [comment]
Following are the steps to import Ballerina project which can be debugged.

Pre-conditon is to install Bllerina Idea plugin 1st.
To do, go to File --> Project Structure (or ctrl + alt + shift + s) and select module option and import module -> Create module from existing sources then next ...
