### ISSUE TITLE
Issue when running in Windows (Reported at IDEA plugin page)

### ISSUE THREAD

**Issue by lahirus** [ballerina-platform/ballerina-lang#10756]
**Description:**
Please see the comment,
https://plugins.jetbrains.com/plugin/9520-ballerina#comment=27115

**Comment by Shan1024** [comment]
This issue is already fixed. @NipunaRanasinghe added a reply to the comment as well. But seems like that comment is missing now.

**Comment by NipunaRanasinghe** [comment]
As @Shan1024 has mentioned, I've added windows related fixes (#10376 and #10408) for the above issue and added a comment as well. Hence closing the issue.

**Comment by Shan1024** [comment]
Closing since this issue is already fixed.
