### ISSUE TITLE
Compilation gives extraneous input error with no help to troubleshoot

### ISSUE THREAD

**Issue by pasanbox** [ballerina-platform/ballerina-lang#10778]
**Description:**
I'm attempting to build my Ballerina project which has the following structure
```
.
├── Ballerina.toml
├── ballerina.conf
├── contributions_from_outsiders_log
├── daily_task.bal
├── org
│   └── wso2
│       └── contributions_from_outsiders
│           ├── const.bal
│           ├── database_client.bal
│           ├── github_client.bal
│           ├── gmail_client.bal
│           ├── queries.bal
│           └── structs.bal
├── out.log
└── target
    ├── Ballerina.lock
    └── daily_task.balx
```
I'm using the `ballerina build `command. 
I get the following output
```
$ ballerina build
Compiling source
    daily_task.bal
    pasanwijesinghe/org:0.0.1
', ' 1:6 extraneous input 'e' expecting {'      ', '
', ' ', '='}

Compiling tests
    pasanwijesinghe/org:0.0.1
Running tests
    pasanwijesinghe/org:0.0.1
        No tests found
Generating executables
    ./target/daily_task.balx
```

Can you please suggest a way to find where the compilation goes wrong. 

**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.982.0

**OS, DB, other environment details and versions:**
macOS 10.13.6

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pasanbox** [comment]
Removing `string[] args` from `main()` got rid of the second issue.

**Comment by ortegafull87** [comment]
Do you solved that Issue?
