### ISSUE TITLE
[Sample][improvement] when we run jms-queue-message-producer the bal file should print a response saying message sent to queue or not : ballerina-0.970.0-beta1-SNAPSHOT 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10809]
<a href="https://github.com/shavantha"><img src="https://avatars2.githubusercontent.com/u/6552100?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shavantha](https://github.com/shavantha)**
_Wednesday Apr 18, 2018 at 09:14 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/215_

----

when we run jms-queue-message-producer the bal file should print a response saying message sent to queue or not. currently the command[1] executes but until we login to a JSM such as wso2 mb we cant figure out if the sample was successful or not. if we can print a message such as "message sent to queue" will be useful for the user whos using the sample

[1]./ballerina run /home/shavantha//products/ballerina/ballerina-examples/examples/jms-queue-message-producer/jms-queue-message-producer.bal

**Comment by keizer619** [comment]
<a href="https://github.com/shavantha"><img src="https://avatars2.githubusercontent.com/u/6552100?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shavantha](https://github.com/shavantha)**
_Wednesday Apr 18, 2018 at 09:29 GMT_

----

Same improvement should go to jms-simple-topic-message-producer

**Comment by shafreenAnfar** [comment]
Ballerina standard library team no longer maintain this module but rather NATS, RabbitMQ and Kafka. Hence, closing this issue.
