### ISSUE TITLE
Mismatches between the code and the code comment.

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10818]
<a href="https://github.com/RukshiW"><img src="https://avatars1.githubusercontent.com/u/26239861?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RukshiW](https://github.com/RukshiW)**
_Tuesday Apr 24, 2018 at 14:20 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/466_

----

**Description:**
In the strings.bal file (https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/strings/strings.bal), there are mismatches between some code and the related code comments. 
e.g.,
Code comment: "This replaces the first instance of the replacePattern string with the replaceWith string."
Code:
string s5 = statement.replaceFirst("Lion", "Tiger");
io:println("ReplaceFirst: " + s5);

**Suggested Assignees:**
Irunika

**Affected Product Version:**
ballerina-platform/ballerina-examples

**Comment by MaryamZi** [comment]
Fixed with #12806
