### ISSUE TITLE
Issues in the testerina-groups sample

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10812]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Apr 19, 2018 at 11:52 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/271_

----

**Description:**
Issues in the testerina-groups sample [1]

**Issues**
1. Output is wrong when the following command is run 
`$ ballerina test testerina-groups.bal --groups g1`

_Actual Output:_
```
I'm in test belonging to g1 and g2!
I'm in test belonging to g1!
```

2. Output is wrong when the following command is run 
`ballerina test testerina-groups.bal --groups default`

_Actual Output:_
No output. No tests run

3. Error when the following command is run 
`ballerina test testerina-groups.bal --exclude-groups g2`

_Actual Output:_
```
ballerina: unknown flag '--exclude-groups'
Run 'ballerina help' for usage.
```

**Affected Product Version:**
Ballerina Platform - beta1

**OS, DB, other environment details and versions:**  
In-built JAVA
Windows 7  

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/testerina-groups/testerina-groups.sh

**Comment by samgnaniah** [comment]
Seems to work as expected now.

**Comment by samgnaniah** [comment]
Closing this. Please reopen if any more actions are needed.
