### ISSUE TITLE
xml-functions description needs to be more descriptive 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10816]
<a href="https://github.com/shavantha"><img src="https://avatars2.githubusercontent.com/u/6552100?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shavantha](https://github.com/shavantha)**
_Saturday Apr 21, 2018 at 00:24 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/326_

----

xml-functions description needs to be more descriptive. The current documentation states only[1]. By reading this statement, the user will not know what are those built-in functions

[1]
`// Ballerina supports various built-in functions to manipulate XML.`

It would be great if those build in functions can be listed and given detailed explanations or point to a URL that has the details from within the xml-functions.description  file

**Comment by samgnaniah** [comment]
Closing this because it seems quite clear in the example comments what the functions are and the details (along with the relevant code snippet as well).
