### ISSUE TITLE
Output of the xml-to-json-conversion is incorrect

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10810]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Apr 19, 2018 at 09:33 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/258_

----

**Description:**
Output of the xml-to-json-conversion is incorrect

**Affected Product Version:**
Platform - beta1

**OS, DB, other environment details and versions:**    
In-built JAVA 
Windows 7

**Issue**
Following is the output received and it is different from the output in [1]

```
{"h:Store":{"@xmlns:h":"http://www.test.com","@id":"AST","h:name":{"@xmlns:h":"http://www.test.com","#text":"Anne"},"h:address":{"@xmlns:h":"http://www.test.com","h:street":{"@xmlns:h":"http://www.test.com","#text":"Main"},"h:city":{"@xmlns:h":
"http://www.test.com","#text":"94"}},"h:code":{"@xmlns:h":"http://www.test.com","h:item":[{"@xmlns:h":"http://www.test.com","#text":"4"},{"@xmlns:h":"http://www.test.com","#text":"8"}]}}}
{"Store":{"#id":"AST","name":"Anne","address":{"street":"Main","city":"94"},"code":{"item":["4","8"]}}}
```

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/xml-to-json-conversion/xml-to-json-conversion.sh

**Comment by samgnaniah** [comment]
I retested [1] and the output is as indicated in the example. Closing this for now. Please reopen if issue persists.

[1] - https://ballerina.io/learn/by-example/xml-to-json-conversion.html
