### ISSUE TITLE
Output is incorrect in character-i-o sample

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10814]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Apr 20, 2018 at 04:20 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/290_

----

**Description:**
Actual output:
```
Started to process the file.
 No of characters written : 5
 No of characters written : 12
 No of characters written : 13
File processing complete.
```

Output in [1]
```
Started to process the file.
 No of characters written : 5
 No of characters written : 12
 No of characters written : 12
File processing complete.
```

**Affected Product Version:**
Ballerina beta 3 nightly

**OS, DB, other environment details and versions:**   
JDK - 1.8.0_171
Windows 10

[1] https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/character-i-o/character-i-o.sh

**Comment by keizer619** [comment]
<a href="https://github.com/uthaiyashankar"><img src="https://avatars3.githubusercontent.com/u/2410076?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [uthaiyashankar](https://github.com/uthaiyashankar)**
_Saturday Apr 21, 2018 at 14:14 GMT_

----

This is working as expected in Mac. Might be a windows specific issues.

**Comment by samgnaniah** [comment]
This seems to be working as expected so I'm closing this.
