### ISSUE TITLE
The http-trace-logs sample output is not as expected on windows 7

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10821]
<a href="https://github.com/shavantha"><img src="https://avatars2.githubusercontent.com/u/6552100?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shavantha](https://github.com/shavantha)**
_Thursday Apr 26, 2018 at 11:27 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/593_

----

**Description:**
The http-trace-logs sample output is not as expected on windows 7

java :1.8.0_161
windows 7 professional
ballerina installer beta17

steps
======
$ curl http://localhost:9090/hello
```
<HTML><HEAD><TITLE> Web Authentication Redirect</TITLE><META http-equiv="Cache-c                                                     ontrol" content="no-cache"><META http-equiv="Pragma" content="no-cache"><META ht                                                     tp-equiv="Expires" content="-1"><META http-equiv="refresh" content="1; URL=https                                                     ://guestlogin.wso2.com/login.html?redirect=/200"></HEAD></HTML>

wso2@wso2-PC ~
$ curl http://localhost:9090/hello
<HTML><HEAD><TITLE> Web Authentication Redirect</TITLE><META http-equiv="Cache-c                                                     ontrol" content="no-cache"><META http-equiv="Pragma" content="no-cache"><META ht                                                     tp-equiv="Expires" content="-1"><META http-equiv="refresh" content="1; URL=https                                                     ://guestlogin.wso2.com/login.html?redirect=/200"></HEAD></HTML>
```

**Comment by praneesha** [comment]
Tested this in Windows 10 Pro using the Ballerina 0.993.0 SNAPSHOT and it works fine as shown in the below screenshot.

![screenshot 19](https://user-images.githubusercontent.com/11707273/51309986-9b400e00-1a6b-11e9-8f02-a6564a94ed18.png)
