### ISSUE TITLE
remove commands that are not available with the runtime installer

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10823]
<a href="https://github.com/shavantha"><img src="https://avatars2.githubusercontent.com/u/6552100?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shavantha](https://github.com/shavantha)**
_Friday Apr 27, 2018 at 00:12 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/630_

----

**Description:**
remove commands that are not available with the runtime installer. the runtime installer shows commands such as swagger and grpc which when we try to use does not work. Since these are related to platform installer we should not have them in the runtime installer 

```
     Available commands are:
         run        Run Ballerina program
         build      Compile Ballerina program
         install    Install packages to home repository
         pull       Download package from Ballerina Central
         push       Upload package to Ballerina Central
         init       Initialize Ballerina project
         search     Search for packages within Ballerina Central
         list       List dependencies of packages
         doc        Generate Ballerina API documentation
         grpc       Generate connector/service using protobuf   
                    definition
         swagger    Generate client/service using Swagger definition
                    or export Swagger file for a Ballerina service
         test       Test Ballerina program
         version    Print Ballerina version
         encrypt    Encrypt sensitive data

```

**Comment by hevayo** [comment]
No loner valid.
