### ISSUE TITLE
Need an example in Ballerina by Example for Regex

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10829]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Sunday Jun 10, 2018 at 17:29 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/808_

----

**Description:**
Original issue https://github.com/ballerina-platform/ballerina-lang/issues/4862

**Comment by davebaol** [comment]
Yep, we really need it 😃

**Comment by praneesha** [comment]
This will be added after https://github.com/ballerina-platform/ballerina-spec/issues/130 is done.

**Comment by hasithaa** [comment]
I am closing this issue since this is not planned for an immediate feature.
