### ISSUE TITLE
No sample for Anonymous struct support in Ballerina by example

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10825]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Sunday Jun 10, 2018 at 16:27 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/804_

----

**Description:**
Refer the original issue https://github.com/ballerina-platform/ballerina-lang/issues/3899

**Comment by pubudu91** [comment]
Closing since this was addressed in PR #12766
