### ISSUE TITLE
Provide detailed examples for the use of record-io

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10827]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Sunday Jun 10, 2018 at 17:13 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/806_

----

**Description:**
Refer original issue https://github.com/ballerina-platform/ballerina-lang/issues/4432 for more details.

**Comment by praneesha** [comment]
Done in [1].

[1] https://ballerina.io/learn/by-example/record-io.html
