### ISSUE TITLE
[Improvement] Provide the sample source file in the CharacterIO sample

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10826]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Sunday Jun 10, 2018 at 16:48 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/805_

----

**Description:**
Refer the original issue here. https://github.com/ballerina-platform/ballerina-lang/issues/4140

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/19539.
