### ISSUE TITLE
client-generation sample generates an error before starting up

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10824]
<a href="https://github.com/shavantha"><img src="https://avatars2.githubusercontent.com/u/6552100?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shavantha](https://github.com/shavantha)**
_Friday Apr 27, 2018 at 09:04 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/648_

----

client-generation sample generates an error before starting up

steps
1.C:\ballerina\ballerina-examples\examples\client-generation>ballerina run client_generation.bal

```
Client code was not generated: Error while compiling template
ballerina: initiating service(s) in 'client_generation.bal'
ballerina: started HTTP/WS endpoint 0.0.0.0:9090
```

**Comment by samgnaniah** [comment]
This works as expected for me so I'm closing this.
