### ISSUE TITLE
Add sample for SOAP 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10831]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Friday Jun 15, 2018 at 15:18 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/839_

----

**Description:**

Refer the discussion for more details. 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/K_Y9pPVpR-Q/ZvBw48OhBgAJ

**Comment by keizer619** [comment]
<a href="https://github.com/Seralahthan"><img src="https://avatars0.githubusercontent.com/u/20059053?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Seralahthan](https://github.com/Seralahthan)**
_Tuesday Jun 26, 2018 at 04:28 GMT_

----

Hi All,

I am working on the Ballerina By Guides doc on "Working with SOAP messages" 
I am planning to cover the following areas
 - Provide security for unsecured SOAP service (Username Token: WS-Security)
 - Create and add a JWT for SOAP request based on Username Token
 - Throttling based on SOAP action - throttle mediator
 - Role-based authorization for a particular user (identified by username) for specific SOAP Action

Let me know if there is any more content to be covered in the Guides.

**Comment by wggihan** [comment]
Move to the SOAP module repo.
