### ISSUE TITLE
Add sample for identifier literals

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10839]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Friday Aug 24, 2018 at 05:16 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/983_

----

**Description:**
$subject for BBE

**Comment by MaryamZi** [comment]
Added with #19152.
