### ISSUE TITLE
Explain about error with but key word in hello_world_service sample

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10834]
<a href="https://github.com/Susankha"><img src="https://avatars3.githubusercontent.com/u/6066040?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Susankha](https://github.com/Susankha)**
_Monday Jul 30, 2018 at 11:18 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/948_

----

**Description:**

In hello_world_service sample [1], we can see a usage of but keyword with an error. We need to add little information about that.

[1] - https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/hello-world-service/hello_world_service.bal#L14

**Comment by samgnaniah** [comment]
We don't use the but expression in this example anymore. It is changed to type test in the upcoming release. I'm closing this based on the above.
