### ISSUE TITLE
Table Queries sample is bit complex

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10837]
<a href="https://github.com/Susankha"><img src="https://avatars3.githubusercontent.com/u/6066040?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Susankha](https://github.com/Susankha)**
_Monday Jul 30, 2018 at 14:46 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/952_

----

**Description:**

In the "Table Queries sample" [1] we can see few complex queries together and that might get the use confuses. Can we split this into few samples?

[1] - https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/table-queries/table_queries.bal

**Comment by gimantha** [comment]
Table Queries will be re-designed and Samples will be rewritten as per https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/query/query.md in a minor release

**Comment by grainier** [comment]
Fixed in #19790
