### ISSUE TITLE
Secured-service-with-basic-auth should provide sample toml file

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10838]
<a href="https://github.com/ayomawdb"><img src="https://avatars3.githubusercontent.com/u/612458?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ayomawdb](https://github.com/ayomawdb)**
_Tuesday Aug 21, 2018 at 11:29 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/980_

----

**Description:**
Currently this example provides instructions on how to use basic auth with config based user store. However, the description only mentions about the toml file that store user information. 

Commands should be improved to provide instructions on how to create a sample user config fileand also it should be included in the GitHub folder.

**Comment by ayomawdb** [comment]
Fixed with latest releases.
