### ISSUE TITLE
Create sample to read CSV files and stream values to database

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10830]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Sunday Jun 10, 2018 at 17:33 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/809_

----

**Description:**
Refer https://github.com/ballerina-platform/ballerina-lang/issues/4929 for details.

**Comment by praneesha** [comment]
Closing since this use case can be derived out of existing BBEs such as [1] and [2].

[1] https://ballerina.io/learn/by-example/record-io.html
[2] https://ballerina.io/learn/by-example/jdbc-client-crud-operations.html
