### ISSUE TITLE
Add testerina example

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10832]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Tuesday Jun 26, 2018 at 05:44 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/866_

----

**Description:**

Refer for more details. 
Refer https://github.com/ballerina-platform/ballerina-lang/issues/9241

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Can we have more info on the exact scope of this issue? Is this something in addition to what we have in [1]?

[1] - https://ballerina.io/learn/how-to-test-ballerina-code/
