### ISSUE TITLE
Add reference to Elvis operator in Maps BBE

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10843]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Monday Sep 17, 2018 at 12:06 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/997_

----

**Description:**
[Line number 46](https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/maps/maps.bal#L46) in Maps BBE uses Elvis operator. 
`string index2 = stringMap["index"] ?: "";`
Shall we add a reference to the [Elvis BBE](https://ballerina.io/learn/by-example/elvis-operator.html) here to avoid the confusion.

**Comment by MaryamZi** [comment]
Closing this issue since it is now fixed by explaining the elvis operator in the maps BBE.

https://ballerina.io/learn/by-example/maps.html
