### ISSUE TITLE
Mention the reason why string to boolean is a always safe in the Type Conversion BBE.

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10846]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Monday Sep 17, 2018 at 12:41 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/1000_

----

**Description:**
Shall we add a comment to explain why [string to boolean conversion](https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/type-conversion/type_conversion.bal#L35) is always safe.
This will avoid the ambiguity if the type safe occurs because
1. string `true` always evaluates to boolean `true`. Or
2. string `false` always evaluates to boolean `false`

Therefore, shall we mention this is a safe conversion due to 1.

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/11863

**Comment by MaryamZi** [comment]
This was fixed, but it seems that the new type conversion BBE needs more comments. Closing this issue since we've created https://github.com/ballerina-platform/ballerina-lang/issues/12703 to track the improvements.
