### ISSUE TITLE
Mention Optional Type is also an Union Type

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10845]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Monday Sep 17, 2018 at 12:28 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/999_

----

**Description:**
This repo contains two BBEs for [Union Type](https://ballerina.io/learn/by-example/union-type.html) and [Optional Type](https://ballerina.io/learn/by-example/optional-type.html). As Optional Type is again an Union Type, shall we mention that in the Optional Type BBE.

**Comment by samgnaniah** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/11867

**Comment by MaryamZi** [comment]
Closing since this is now fixed.
