### ISSUE TITLE
Clarify more on nil explanation in Optional Type BBE

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10841]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Saturday Sep 15, 2018 at 20:27 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/995_

----

**Description:**
[Optional Type](https://ballerina.io/learn/by-example/optional-type.html)
Explain what `?` syntax means.
Explain its type syntax and value both can be `()`.
Add a reference to the [Values BBE](https://ballerina.io/learn/by-example/values.html), once the `nil` example is added there.

**Comment by MaryamZi** [comment]
Closing since the description is now updated as follows:
"You can syntactically represent this as `T?` or T|()`."

Adding `nil` to the values BBE is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/10840
