### ISSUE TITLE
Arrays BBE's use of "lengthof" is contrary to deprecation mentioned on specification

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10842]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Saturday Sep 15, 2018 at 20:44 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/996_

----

**Description:**
[Language specification](https://ballerina.io/res/Ballerina-Language-Specification-WD-2018-07-12.pdf) says  `lengthof` is removed under the changes from 0.970 to 0.980.
Still [Arrays BBE](https://ballerina.io/learn/by-example/arrays.html) uses `lengthof`.
Compiles fine in 0.981.0.
Update the BBE if `lengthof` is deprecated/removed.
Also, the [lengthof](https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/lengthof/lengthof.bal) example as well.

**Comment by MaryamZi** [comment]
`lengthof` has been removed from Ballerina 0.990.0 onward, and the new built-in method `.length()` has been introduced for `string`, `array`, `map`, `record`, `table`, `json`, `xml` and `tuple` types.

Both the [Arrays BBE](https://ballerina.io/learn/by-example/arrays.html) and the [Length BBE](https://ballerina.io/learn/by-example/length.html) (previously lengthof) have been updated to reflect the same.
