### ISSUE TITLE
Improve examples for data binding functionality with functions as entry points

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10849]
<a href="https://github.com/MaryamZi"><img src="https://avatars1.githubusercontent.com/u/8376983?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MaryamZi](https://github.com/MaryamZi)**
_Monday Oct 01, 2018 at 03:48 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/1055_

----

**Description:**
The [current example](https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/functions-as-entry-points) for functions as entry points does not include examples on how values need to be specified for all possible parameter types.

Examples may have to be included for:
- json, xml and typedesc
- arrays, maps, tuples and records

**Comment by hasithaa** [comment]
Closing this, since this feature has been removed in SwanLake.
