### ISSUE TITLE
Irrelevant use of optional type in Type Conversion BBE 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10844]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Monday Sep 17, 2018 at 12:19 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/998_

----

**Description:**
[Line 44](https://github.com/ballerina-platform/ballerina-examples/blob/master/examples/type-conversion/type_conversion.bal#L44) of Type Conversion BBE uses optional types as below.
`float? af = check <float>a;`

Shall we remove the `?` after `float`?

**Comment by MaryamZi** [comment]
This is fixed in 0.990.0 https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.0/examples/type-conversion/type_conversion.bal#L38.
