### ISSUE TITLE
Add examples for nil and blob types in Values BBE

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10840]
<a href="https://github.com/nipunthathsara"><img src="https://avatars1.githubusercontent.com/u/11774310?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nipunthathsara](https://github.com/nipunthathsara)**
_Saturday Sep 15, 2018 at 20:01 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/994_

----

**Description:**
Add example and type description for `nil` and `blob` types in Values BBE.

**Comment by MaryamZi** [comment]
The byte type is now mentioned in the values BBE and has its own BBE too (https://ballerina.io/learn/by-example/byte-type.html).

Keeping this issue open to add the `nil` type.

**Comment by MaryamZi** [comment]
Fixed with #12851
