### ISSUE TITLE
Add new example for compound operators

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#10850]
<a href="https://github.com/Shan1024"><img src="https://avatars3.githubusercontent.com/u/4003115?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Shan1024](https://github.com/Shan1024)**
_Monday Oct 01, 2018 at 09:17 GMT_
_Originally opened as https://github.com/ballerina-platform/ballerina-examples/issues/1058_

----

**Description:**
There isn't any example available which demonstrates the compound operator.

**Comment by MaryamZi** [comment]
This is already available, added with https://github.com/ballerina-platform/ballerina-lang/pull/12817.
