### ISSUE TITLE
HTTP server going OOM with a very fast client consuming a large payload

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#10868]
**Description:**
When a large payload > heap size is consumed by a very fast client (say a netty client that simply releases the http content), the server goes OOM. Note that in this case server is responding with a large file > heap size (1024 MB by default). 
This is caused by the event task queue getting filled faster than netty could handle in the following line:
https://github.com/wso2/transport-http/blob/835a65e0332155e7d60c21344695acd99a0679dd/components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java#L79

**Comment by shafreenAnfar** [comment]
This is a very rare event and almost impossible to happen in real world scenarios.

**Comment by ldclakmal** [comment]
Closing as per above comment.
