### ISSUE TITLE
Signed JWT Authentication with JWKs endpoint

### ISSUE THREAD

**Issue by mefarazath** [ballerina-platform/ballerina-lang#10908]
**Description:**
Refer: Discussion on ballerina-dev
https://groups.google.com/forum/#!topic/ballerina-dev/gONIDx1sk9o

**Suggested Labels (optional):**
Component/Auth, Type/Improvement

**Comment by ayomawdb** [comment]
Issue #11157 should also be addressed along with this requirement.

**Comment by ldclakmal** [comment]
Sub Tasks:
- [ ] Research on JWKs Implementation https://github.com/ballerina-platform/ballerina-lang/issues/22703
- [ ] Generate public key from JWKs attributes https://github.com/ballerina-platform/ballerina-lang/issues/22705
- [ ] Implement JWKs authentication
