### ISSUE TITLE
Add source gen for the symbolic string literal

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#10902]
**Description:**
Source gen should be added for the symbolic string literal

**Affected Versions:**
0.982.1 SNAPSHOT

**Related Pull Requests:**
https://github.com/ballerina-platform/ballerina-lang/pull/10712

**Comment by NipunaMarcus** [comment]
Support for the symbolic string literal has been added to source gen hence closing this issue.
