### ISSUE TITLE
[IDEA] Highlighting issue in xml

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#10907]
**Description:**
`$` character is highlighted as invalid (refer the screenshot below).

<img width="489" alt="constan 2018-10-19 10-48-25" src="https://user-images.githubusercontent.com/4003115/47198964-c2177700-d38c-11e8-8dab-d51642a9ebce.png">

**Comment by NipunaRanasinghe** [comment]
Closing the issue since fixed with #11110.
