### ISSUE TITLE
Cannot assign a byte value to a union typed variable

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#10923]
**Description:**
```ballerina
byte|float x = 4;
```
Compilation fails for the above with the following error:
```cmd
incompatible types: expected 'byte|float', found 'int'
```

**Affected Version**
0.982.0

**Comment by pranavan15** [comment]
Reopening the issue as the above-referenced PR would only fix the finite type assignability. Also, it only checks for the assignability without changing the actual type of the literal.

**Comment by MaryamZi** [comment]
Closing this since it will be fixed once we fix https://github.com/ballerina-platform/ballerina-lang/issues/14376.
