### ISSUE TITLE
checkType() in Types needs to be improved to allow more descriptive type checking errors

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#10945]
https://github.com/ballerina-platform/ballerina-lang/blob/9be35de0959d4a22e53243a548f2f1c4283a287c/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L158

In the above method, if type checking fails in `isAssignable()` the error message given is generic (e.g., `incompatible types: expected 'anydata', found 'Foo'`). This gives no indication of why the two types are incompatible. It would be better if we can improve this to capture more comprehensive information regarding the error.

**Comment by hasithaa** [comment]
This requires considerable revamp in current type checker. Won't fixed in Swan Lake.
