### ISSUE TITLE
Invalid error when running a non-existing file

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#10968]
**Steps to reproduce:**
Run a non existing file using `balerina run foo.bal`.

Below error message is logged. It has lot of unnecessary information. 
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: Ballerina is supported only on JDK 1.8
```

**Affected Versions:**
v0.982.1-SNAPSHOT

**Comment by NatashaWso2** [comment]
Couldn't reproduce this issue with the latest master, hence closing this issue.
