### ISSUE TITLE
Change error message when it has 0 as leading digit in int

### ISSUE THREAD

**Issue by lahirus** [ballerina-platform/ballerina-lang#10985]
**Description:**
I would get an error when defined,

`int a = 03454;`

> error: .::student_info_service.bal:47:14: extraneous input '3454'

Can we change the error message to show a meaningful message(e.g. integer literals cannot start with zero)?

**Affected Versions:**
0.982.0

**OS, DB, other environment details and versions:**
IntelliJ Idea

**Comment by dulvinw** [comment]
Already fixed with new parser

**Comment by hasithaa** [comment]
@dulvinw What is the error message getting now? Shall we add a test case, if not?

**Comment by mohanvive** [comment]
Issue is already fixed in new parser and test case is available at [1]. Hence, closing the issue.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/types/integer/BIntegerValueNegativeTest.java#L54
