### ISSUE TITLE
"extraneous input '' Error Occurred While running the ballerina http services on Windows environment

### ISSUE THREAD

**Issue by KasunAratthanage** [ballerina-platform/ballerina-lang#11014]
**Description:**

While running the ballerina http services on Windows environment, it is unable to find the exact path for certification key files. Please refer the following error message.

"extraneous input '\' expecting {'0', '\"', '\\', '\/', '\b', '\f', '\n', '\r', '\t', ALPHA, ' ', '-', '.', '"', '_', ':', ',', '/', ''', '=', '#', '[', ']', '{', '}', DIGIT19, BASICUNESCAPED, '+', '0x', '0o', '0b', 'e', 'inf', 'nan', 'true', 'false', 'T', 't', 'Z'}"

**Steps to reproduce:**
 1) Run the ballerina http service on Windows environment or run ballerina integration test suite(http services).

**Affected Versions:**
Ballerina 0.982.0 

**OS, DB, other environment details and versions:**
Windows

**Related Issues (optional):**

**Suggested Labels (optional):**
Ballerina Integration Tests

**Suggested Assignees (optional):**
Pubudu Fernando

**Comment by pubudu91** [comment]
Had a look at this with @KasunAratthanage. The issue here is with the TOML parser which doesn't seem to be able to handle the `\` character. Will have a look at this.

**Comment by pubudu91** [comment]
The fix given in PR #11181 is now merged to master. Hence closing this issue.
