### ISSUE TITLE
Cannot retrive reocord from table structure by passing parameter

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#11023]
**Description:**
It is not possible to retrieve a record from table data structure by passing a variable to the "WHERE" clause. It only works if the value is hard coded.

**Steps to reproduce:**
The following function returns a value successfully using the table data structure. 

` public function getEmployeeEmail() returns string{
        string WSO2_EMAIL;

        table<Employee> employeeTableCopyWithFilter = from tableEmployee where GITHUB_ID == "MadhukaHarith92" select *;

        json jsonTable = check <json>employeeTableCopyWithFilter;
        return jsonTable[0].WSO2_EMAIL.toString();
    }`

Note that here, "MadhukaHarith92" value is hard coded. Now try to have a parameter passed to the function.

` public function getEmployeeEmail(string GITHUB_ID_VALUE) returns string{
    string WSO2_EMAIL;

    table<Employee> employeeTableCopyWithFilter = from tableEmployee where GITHUB_ID == GITHUB_ID_VALUE select *;

    json jsonTable = check <json>employeeTableCopyWithFilter;
    return jsonTable[0].WSO2_EMAIL.toString();
}`

It returns an error as follows.

`error: ballerina/runtime:CallFailedException, message: call failed
    at org/wso2/org:0.0.1:GitHubStarsDetector.executeOperation(service.bal:40)
caused by ballerina/runtime:CallFailedException, message: call failed
    at org/wso2/org:0.0.1:getMissingIds(github_repository_scanner.bal:54)
caused by error, message: error in executing statement : CREATE TABLE TABLE_EMPLOYEE_3 AS select *  from (select * from TABLE_EMPLOYEE_1 where GITHUB_ID = id) error:Column "ID" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._0 AS
SELECT
    TABLE_EMPLOYEE_1.USER_ID,
    TABLE_EMPLOYEE_1.NAME,
    TABLE_EMPLOYEE_1.GITHUB_ID,
    TABLE_EMPLOYEE_1.WSO2_EMAIL
FROM PUBLIC.TABLE_EMPLOYEE_1
WHERE GITHUB_ID = ID [42122-197]
    at org/wso2/org:0.0.1:getEmployeeEmail(database_handler.bal:102)`

**Affected Versions:**
ballerina 0.982.0

**OS, DB, other environment details and versions:**
mysql 8.0.12

**Related Issues (optional):**

**Suggested Labels (optional):**

Improvement

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
Hi @MadhukaHarith92 
Table queries are supported by In-memory tables only. Underlying H2 in-memory tables are used for now (even though you use mysql, i don't think that it is being used)
Even in in-memory tables, as of the current implementation, ballerina expressions cannot be used in table queries except for literals. We understand that it is a bit less useful without expression support in table queries and This will be addressed in future. Will you be able to explain your full use-case, so that we can suggest you a workaround if possible?

**Comment by hasithaa** [comment]
Table syntax under review and will be revamped with ballerina-platform/ballerina-spec#354 in future spec.

**Comment by hasithaa** [comment]
Resolving since Old table query support has been removed from JBallerina-1.2.0.
