### ISSUE TITLE
defaultable string variables breaks diagram

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#11046]
**Description:**
When default values are present for string variables diagram won't render. The default error is shown

**Steps to reproduce:**
~~~ballerina
function test(string s="test") {

}
~~~

**Affected Versions:**
0.982.1-SNAPSHOT

**Comment by kaviththiranga** [comment]
This is fixed for old diagram code base at https://github.com/ballerina-platform/ballerina-lang/pull/11067

However, same could be reproduce in new diagram code base and will send a fix for that.

**Comment by kaviththiranga** [comment]
Fixed in new code base with https://github.com/ballerina-platform/ballerina-lang/pull/12813
