### ISSUE TITLE
[HTTP2] Handle exception scenario while writing contents

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#11045]
**Description:**
The `HttpContent`s are written asynchronously to the channel at `Http2OutboundRespListener` and `Http2TargetHandler`. If there will be any `Http2Exception` thrown while writing a single `HttpContent`, it is logged and notified to the listener. But the next `HttpContent` will be written to the channel eventhough there was an error in previous `HttpContent`. This should be handled properly.

```java
httpContent -> ctx.channel().eventLoop().execute(() -> {
    try {
        writer.writeOutboundResponse(outboundResponseMsg, httpContent);
    } catch (Http2Exception ex) {
        LOG.error("Failed to send the outbound response : " + ex.getMessage(), ex);
        inboundRequestMsg.getHttpOutboundRespStatusFuture().notifyHttpListener(ex);
    }
})
```

**Suggested Labels (optional):**
Component/stdlib
Component/HTTP
Type/Improvement

**Suggested Assignees (optional):**
@ldclakmal

**Comment by arukshani** [comment]
This is fixed. >> https://github.com/wso2/transport-http/blob/f389ead50eeb1117b0fa5206591c330aa125e650/components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java#L686
