### ISSUE TITLE
Ips without package path init in CPU

### ISSUE THREAD

**Issue by ChinthakaSenanayaka** [ballerina-platform/ballerina-lang#11050]
**Description:**
When debugging CPU Ips some Ips were caught without the package path in init. E.g. ".<init>" from docs.bal and annotations.bal.

**Steps to reproduce:**
Run any Testerina test with a source code outside the tests folder in the package level. Debug the CPU instructions.

annotations.bal without pkg init
![annotations bal without pkg init](https://user-images.githubusercontent.com/2564122/47631803-855a3580-db6d-11e8-8711-2597df741ce8.png)

docs.bal without pkg init
![docs bal without pkg init](https://user-images.githubusercontent.com/2564122/47631811-97d46f00-db6d-11e8-9a57-8739d589b950.png)

**Affected Versions:**
0.982

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
No longer valid with the jvm target
