### ISSUE TITLE
Full definition of a union type given in error messages related to union typed variables

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#11056]
Consider the following program:
```ballerina
type ValueType int|float|string|boolean|byte;
type DataType ValueType|table|json|xml|map|();

public function main() {
    map<DataType> m;
    map<int> m2 = m;
}
```
Running the above program results in the following compilation error:
```
error: .::test2.bal:6:19: incompatible types: expected 'map<int>', found 'map<int|float|string|boolean|byte|table|json|xml|map?>'
```
Instead of saying `map<int|float|string|boolean|byte|table|json|xml|map?>`, it should be saying `map<DataType>`.

**Comment by hasithaa** [comment]
The same requirement came for LS. This requires persists original typenode information into AST/symbols.

**Comment by rasika** [comment]
We need to prioritize this issue as the langserver generated codes are not intuitive. Related issue https://github.com/ballerina-platform/ballerina-lang/issues/28684

**Comment by MaryamZi** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/29362, the compilation error has been updated.

```ballerina
type ValueType int|float|string|boolean|byte;
type DataType ValueType|table<record {}>|json|xml|map<any>|();

public function main() {
    map<DataType> m;
    map<int> m2 = m;
}
```
now results in 
```cmd
ERROR [foo.bal:(6:19,6:20)] incompatible types: expected 'map<int>', found 'map<DataType>'
```

The original member types of a union type can be accessed via the BType using org.wso2.ballerinalang.compiler.semantics.model.types.BUnionType#getOriginalMemberTypes.

**Comment by pubudu91** [comment]
@MaryamZi Can this be closed now or are there other cases to consider?
