### ISSUE TITLE
Misleading error message when an option is included in invalid order when running a ballerina service

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#11098]
**Description:**
```bash
ballerina run data_backed_service -c ../ballerina.conf 
ballerina: arguments not allowed for services
Run 'ballerina help' for usage.
```
Here `-c ../ballerina.conf ` should have been placed before the package/balfile name to fulfill the intention. However, here with this error message user might misunderstand that "options" are not allowed for services where as it is the "arguments" that are not supported by the services.

**Affected Versions:**
0.982.1-SNAPSHOT

**Comment by pubudu91** [comment]
@Manuri Sorry, I edited my response. The edited response should clarify my point regarding why we can't suggest to the user to place `-c ../ballerina.conf` before the run command

**Comment by MaryamZi** [comment]
Adding to what @pubudu91 mentioned, even if it is by error, in order to provide an error message as suggested, we would have to specifically check if the arguments match any of the options.

IMO, this is unnecessary additional processing. 

Also, the order is specified in the help text:
```cmd
$ ballerina run --help
...
ballerina run [-e] [--offline] [--observe]
         [--sourceroot] [-c|--config] [-printreturn] [-B]
         <balfile | packagename | balxfile>[:function] [args...]
...
```

**Comment by Manuri** [comment]
Yes, I'm not suggesting to specifically check anything. In addition to the actual error message we just could provide a hint to let the user know where options should be placed, if that was his intention. 
Anyway, if it can be found in the help text may be we don't have to.

**Comment by warunalakshitha** [comment]
With 1.2.0 
ballerina run mod1 --b7a.config.file=ballerina.conf 

works fine. We have done improvements to messages as well. Also -c option is nolonger valid. Hence closing the issue.
