### ISSUE TITLE
Cannot specify options to the run command with VSCode run

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#11121]
**Description:**
With #9991, option/param order was enforced for the ballerina `run` command.

With these changes, the options/flags need to be specified before the source (bal/balx/package) to run, and all program args need to be specified after.

Any arguments specified after the source would be considered program args, even if they match an option/flag. Thus, with IDE plugins we may have to accept two separate maps/arrays for options and for program args.

Support for the above needs to be added.

**Description:**
0.982.1-SNAPSHOT

**Comment by rasika** [comment]
This will be available in 0.983.0 release. Please refer the relevant PR https://github.com/ballerina-platform/ballerina-lang/pull/10665. You can add them into `launch.json` as below;

```json
 "scriptArguments": ["foo", "bar"],
 "commandOptions": ["-e", "b7a.log.level=DEBUG"]
```
