### ISSUE TITLE
Improve AuthProvider chaining for JWT to index providers by issuer

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#11132]
When multiple AuthProviders using the JWT scheme are chained, it is possible to index AuthProviders against the issuer name. 

By doing so, it is possible to bypass the auth-chain-validation. This will prevent having to do the full JWT verification unnecessarily, against the AuthProvider for irrelevant "issuer" name.

Main thread: "[Authentication fails when more than one AuthProvider engaged to the same endpoint](https://groups.google.com/forum/#!topic/ballerina-dev/7kqqBsgyWOc)" (ballerina-dev@)

**Comment by ldclakmal** [comment]
This issue is fixed with the patterns introduced by https://github.com/ballerina-platform/ballerina-lang/pull/15363
