### ISSUE TITLE
endpoint documentation string is attached to the following node

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#11134]
**Description:**
When an endpoint has a documentation string, if an undocumented function follows, that documentation string is attached to the function

**Steps to reproduce:**
Put following in a test.bal.
~~~ballerina
import ballerina/file;

# This documentation is about this endpoint
endpoint file:Listener localFolder {
    path:"target/fs"
};

public function test(string str) {

}
~~~

`ballerina doc test.bal`

See the following doc is created

![image](https://user-images.githubusercontent.com/3872221/47774731-cd1ac180-dd13-11e8-97dd-9b16c76e179f.png)

**Affected Versions:**
0.982.1-SNAPSHOT

**Comment by Shan1024** [comment]
Closing the issue since the endpoint definition syntax has been changed.
