### ISSUE TITLE
Little inconsistency in error messages, while validating JWTs

### ISSUE THREAD

**Issue by prabath** [ballerina-platform/ballerina-lang#11142]
If the we directly hit a service with an expired JWT (before being added to the cache) - following is the error on the logs:

**_2018-10-31 06:08:46,174 DEBUG [ballerina/http] - Trying to authenticate with the auth provider: jwt-1
2018-10-31 06:08:46,348 ERROR [ballerina/http] - Error while validating JWT token  : {message:"JWT token is expired", cause:null}_**

If the JWT is in the cache - and try the same (JWT) after it expires - I don't see any error logs. 

**_2018-10-31 06:08:19,760 DEBUG [ballerina/http] - Trying to authenticate with the auth provider: jwt-1_**

**Comment by ldclakmal** [comment]
This is now fixed with the refactoring of the authn/authz framework [1] [2] for Ballerina 1.0. The inconsistency in error messages is also fixed along with that.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/15056
[2] https://github.com/ballerina-platform/ballerina-lang/pull/15696
