### ISSUE TITLE
Private types are allowed to be used in public type definitions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#11170]
Consider the following type defs in a package `foo`.
```ballerina
public type Foo int|float|string|Bar;
type Bar string|xml|json;
```
The above compiles fine and can be used in other packages without an issue. For example,
```ballerina
import ballerina/io;
import pubudu/foo;

public function main() {
	json j = {"a":25};
	foo:Foo f = j;
	io:println(f);
}
```
Running the above program prints `{"a":25}`.

Related issue: #11172

**Comment by hasithaa** [comment]
I don't see a problem with the above code. Foo refers to `xml|json`. If Someone can refer foo:Bar, then it is a problem.
