### ISSUE TITLE
Improve the table for type defs in API docs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#11174]
In the table for type defs in API docs, the column which lists the constituent types of the type is named as `Values`. 
![screenshot from 2018-11-02 10-13-15](https://user-images.githubusercontent.com/6260009/47895935-0298e980-de91-11e8-98e5-72856f17ea4a.png)

Is this the correct term to use, considering the fact that we commonly use the type names as well here as shown in the above pic?

Another issue is if there are string values in the def, shouldn't we put them within quotes in the docs? Otherwise it may give the wrong impression that that value is a type. 
![screenshot from 2018-11-02 11-19-52](https://user-images.githubusercontent.com/6260009/47896152-198c0b80-de92-11e8-81e7-9fe13a4202a7.png)

The values in the above case are all string literals.

**Comment by praneesha** [comment]
These are fixed in the new look and feel of the API docs as shown below.

![image](https://user-images.githubusercontent.com/11707273/61771005-43180900-ae0c-11e9-96f3-9e8f83850407.png)
![image](https://user-images.githubusercontent.com/11707273/61771010-4a3f1700-ae0c-11e9-958d-db568282b799.png)
