### ISSUE TITLE
Ballerina language server does not provide resolving for ballerina standard libraries

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#11179]
**Description:**
Current ballerina language server implementation does not have resolving support (goto definition) for the references of ballerina standard library related methods and types.

**Steps to reproduce:**
Please use the following code snippet in VSCode and try `Goto Definition` for `println()` method.
```ballerina
import ballerina/io;

public function main() {
    io:println("Hello World");
}
```

**Affected Versions:**
0.983.0 and below

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This has been implemented in the latest master. Hence closing the issue
