### ISSUE TITLE
IntelliJ plugin does not provide code highlighting for floating point numbers

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#11178]
**Description:**
In Ballerina IDEA Plugin, floating point numbers are not highlighed in the same way that the intergers are highlighted.

**Steps to reproduce:**
Please refer the following code.
![screenshot from 2018-11-02 15-42-37](https://user-images.githubusercontent.com/29032600/47909456-f7a48000-deb5-11e8-8eb1-78c99a158330.png)

**Affected Versions:**
0.983.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Fixed with #11159. Hence closing

**Comment by DimalChandrasiri** [comment]
Closing issue in regard with #11159
