### ISSUE TITLE
Private types defined in a package can be used outside of the package

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#11172]
Consider the following type def in a package `foo`.
```ballerina
type Bar string|xml|json;
```
The above type can be used outside of the `foo` package without a problem. For example:
```ballerina
import ballerina/io;
import pubudu/foo;

public function main() {
	json j = {"a":25};
	foo:Bar f = j;
	io:println(f);
}
```
Running the above program prints `{"a":25}`

Related issue: #11170

**Comment by rdhananjaya** [comment]
Reopening as previous PR was reverted in https://github.com/ballerina-platform/ballerina-lang/pull/17603
