### ISSUE TITLE
Set default trust store in the ballerina conf file

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#11198]
**Description:**
Currently, if the user hasn't configured a trust store in their client endpoint we set the ballerinaTruststore as the default trustStore internally from the code.

We need to move this to the ballerina conf file in a way that we can set any trustStore to be used as the default one.

**Comment by pubudu91** [comment]
What if the user isn't using a config file?

**Comment by Bhashinee** [comment]
Closing the issue, as this is not applicable now.
