### ISSUE TITLE
Record properties are being shadowed

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#11214]
**Description:**
Record properties are being shadowed

Code
```ballerina

string p;
type myRecord record { string p; int q; };
```
Error
```
error: .::test123.bal:2:24: redeclared symbol 'p'
```

**Comment by MaryamZi** [comment]
Closing this issue since it is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/12547 for both records and objects.
