### ISSUE TITLE
Ballerina init command should fail for pre-initialized project folders and it's modules

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#11239]
**Description:**
Two issues with the current `ballerina init` command.

1. Running `ballerina init` in a pre-initialized project folder.
    - Currently, if you run `ballerina init` in an already initialized project folder, it just skips creating `Ballerina.toml` silently. IMO the action of `ballerina init` of an already initialized folder should be avoided and the user should be notified of the existence of the `Ballerina.toml`.

2. Running `ballerina init` inside a module of a pre-initialized project folder.
    - Currently, this is allowed and a `Ballerina.toml` will be created inside the current module. This action is also not valid, and the `ballerina init` command should fail when it is in an already initialized project.

```
project                 <------ [1] "ballerina init" for pre-initialized project folder
├── Ballerina.toml
├── module1             <------ [2] "ballerina init" for a module of a 
│   ├── Ballerina.toml               pre-initialized project folder
│   └── hello_service.bal 
└── module2
```

**Comment by pubudu91** [comment]
In the first scenario, wouldn't it be better to give the choice to the user to re-initialize the project if that's what he really wants to do? i.e., prompt the user if it's an already initialized project saying it's already initialized and ask whether the user really wants to re-initialize the project

**Comment by rasika** [comment]
Yeah, For the **first case**, if the purpose is to re-initialize, we need to overwrite the `Ballerina.toml`(currently it is unchanged). The way of handling the first case is up to the discussion; 

- We can allow overwriting `Ballerina.toml` using an interactive message. Also `ballerina init -y` should be able to override the interactive behaviour as well. 

- Or if we decide not to change Ballerina.toml (as keeping it as it is now), At least we can convey a message `Ballerina project reinitialized` just like `git init` does.

Still, I don't think the **second case** is a valid use case. This can cause several issues for the tooling as well, because the only way of identifying the project root is traverse back parents folders looking for a `Ballerina.toml` or a `.ballerina` folder.

**Comment by NatashaWso2** [comment]
In the first case why do we need it overwrite the Ballerina.toml file? The purpose of the init command is to create a ballerina project and a project is defined if it has a '.ballerina' inside it. So I think overriding the existing Ballerina.toml will not be correct? @rasika we can give a message to the user saying that the project is already initialized as a ballerina project. WDYT?

**Comment by rasika** [comment]
@NatashaWso2 yes, for the first scenario we can just give a message to the user mentioning project is already initialized. If they really need to overwrite; they may need to remove Ballerina.toml first(just an idea).
