### ISSUE TITLE
SAP connector

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#11254]
**Description:**
Feature request. SAP connector for native SAP protocols: IDOC sender and listener. BAPI sender.

**Comment by MaryamZi** [comment]
@raj-rajaratnam SAP support will not be available as a standard library module, but the [wso2-ballerina/module-sap](https://github.com/wso2-ballerina/module-sap) module should support the required features. Please note that the module is currently WIP.
