### ISSUE TITLE
Document Highlighting capability is not supported by the ballerina language server

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#11272]
**Description:**
Current ballerina language implementation does not provide the above capability as mentioned. Please find a brief description of the requested capability below.

> The document highlight request is sent from the client to the server to resolve a document highlights for a given text document position. For programming languages, this usually highlights all references to the symbol scoped to this file.  Symbol matches usually have a DocumentHighlightKind of Read or Write whereas fuzzy or textual matches use Text as the kind.

**Affected Versions:**
0.983.0 and below

**Suggested Labels (optional):**
Type/Improvement, Component/LanguageServer

**Comment by IMS94** [comment]
Closing this since with the current state of Ballerina LS and VSCode plugin, there's no major requirement to implement document highlighting. Reopen if such a requirement arises.
