### ISSUE TITLE
[HTTP][AUTH] Refactor API with error in the signature

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#11284]
**Description:**
> The usage of `check` should properly handled to be returned as error. 
> https://github.com/ballerina-platform/ballerina-lang/blob/643010da15dcc5edc2fa69fa1458e45eeac36fe8/stdlib/http/src/main/ballerina/http/auth/authz_handler.bal#L134
> https://github.com/ballerina-platform/ballerina-lang/blob/ce4be90202a41adb1e0235e181101f569217c0af/stdlib/http/src/main/ballerina/http/auth/authn_filter.bal#L165

**Comment by ldclakmal** [comment]
This issue is not valid with the latest master branch as of today. Hence closing the issue.
