### ISSUE TITLE
Lock is not released when the trap is involved

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#11305]
**Description:**
Experiencing $subject in the error-refactor branch. Seems to be the Trap is not codegened properly. 

**Steps to reproduce:**
Run unit test -  testThrowErrorInsideLock() of LocksInMainTest.java class
Test hangs as the code inside lock in worker 2 is not executed.

**Comment by SupunS** [comment]
Closing this issue, since this will be tracked via #12213
