### ISSUE TITLE
Modify connector installation scripts to read ballerina_home 

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#11308]
**Description:**
Currently when installing a connector, it would be required from the user/developer to specify the ballerina home location. 

Given that the Ballerina_Home is specified as a system/environment variable this step would not be necessary. This could be rather read from the script itself

**Comment by shafreenAnfar** [comment]
Ballerina standard library team no longer responsible for connectors. Hence removing the label.

**Comment by Kishanthan** [comment]
Not valid.
