### ISSUE TITLE
ballerina-0.983.0 & jdbc

### ISSUE THREAD

**Issue by ponsilva** [ballerina-platform/ballerina-lang#11318]
**Description:**

error cannot resolve module 'ballerina/jdbc'

In ballerina-0.983.0\lib\repo\ballerina there is no jdbc folder (while in 0.982.0 there is)

**Steps to reproduce:**
* run ballerina-windows-installer-x64-0.983.0.msi
* write a file using import ballerina/jdbc
* execute ballerina run myfile.bal
error: cannot resolve module 'ballerina/jdbc'

**Affected Versions:**
0.983.0

**OS, DB, other environment details and versions:**
Windows

**Comment by ponsilva** [comment]
I saw it was moved to ballerinax/jdbc

**Comment by ponsilva** [comment]
Sorry, I was confused since ballerina/jdbc still appears in API docs page
https://ballerina.io/learn/api-docs/ballerinax/jdbc.html

**Comment by Manuri** [comment]
Thanks for reporting this issue. We'll remove the invalid page.

**Comment by keizer619** [comment]
Yes it should be ballerinax/jdbc and we have updated the document [1] and removed previous document ballerina/jdbc

[1] https://stage.ballerina.io/learn/api-docs/ballerinax/jdbc.html
