### ISSUE TITLE
Cannot read configuration value contain # sign in ballerina

### ISSUE THREAD

**Issue by nimanthag** [ballerina-platform/ballerina-lang#11357]
**Description:**
In ballerina.conf file there is a key-value pair as below
CONFIG="Nima#1234"
When I read that value using ballerina/config it gives following error.
"line 2:0 missing '"' at '<EOF>'"

**Steps to reproduce:**
Run the attached code herewith.

**Affected Versions:**
Ballerina 0.982.0
**OS, DB, other environment details and versions:**
macOS 10.13.6,linux

**Related Issues (optional):**

**Suggested Labels (optional):**

Type/Bug,Severity/Critical
[Archive.zip](https://github.com/ballerina-platform/ballerina-lang/files/2579246/Archive.zip)

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This is a known issue, tracked by #9778
