### ISSUE TITLE
Revisit literal visiting logic in TypeChecker

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#11378]
**Description:**
We do a `TypeTags.FINITE == expType.tag` check when visiting literals in `TypeChecker` to temporary fix an issue related to decimals. This needs to be removed once the original issue is fixed.

**Comment by Shan1024** [comment]
@pranavan15 - Was this fixed?

**Comment by pranavan15** [comment]
> @pranavan15 - Was this fixed?

@Shan1024 Yes; This is fixed via https://github.com/ballerina-platform/ballerina-lang/pull/11851.
