### ISSUE TITLE
Use of anonymous function  for debug logs, breaks the documentation.

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#11407]
**Description:**

The recommendation is to an anonymous function to add debug logs. However, when we add an anonymous function, it breaks the documentation.

For example, take the [http_cache.bal](https://github.com/ballerina-platform/ballerina-lang/blob/error_refactor/stdlib/http/src/main/ballerina/http/caching/http_cache.bal#L62) which results following warning in build time.

```
warning: ballerina/http::caching/http_cache.bal:22:5: no such documentable parameter 'cache'
warning: ballerina/http::caching/http_cache.bal:26:5: no such documentable parameter 'isShared'
warning: ballerina/http::caching/http_cache.bal:23:5: no such documentable parameter 'policy'
warning: ballerina/http::caching/http_cache.bal:62:28: undocumented return parameter
```

**Comment by praneesha** [comment]
Closing since this is not valid now with the new design of API docs[1].

[1] https://ballerina.io/learn/api-docs/ballerina/
