### ISSUE TITLE
OOM when running tests in AppVeyor

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#11408]
**Description:**
When the tests are enabled in AppVeyor, build fails with the fillowing error.
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
```
See the [log.txt](https://github.com/ballerina-platform/ballerina-lang/files/2587903/log.6.txt) for the full log.

**Comment by hasithaa** [comment]
AppVeyor is removed from the build, Now build uses GitHub workflows. Please create a new issue if the issue exists in GH workflows.
