### ISSUE TITLE
[JMS] Improve JMS Endpoint Initialization 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#11444]
**Description:**

The `username` and `password` fields are redundant in the ConnectionConfiguration record as they can be specified in the `providerUrl` as well (`    string providerUrl = "amqp://admin:admin@ballerina/default?brokerlist='tcp://localhost:5672'";`). Need to construct the provider url internally by taking the `username` and `password` separately. 

```ballerina
public type ConnectionConfiguration record {
    string initialContextFactory = "wso2mbInitialContextFactory";
    string providerUrl = "amqp://admin:admin@ballerina/default?brokerlist='tcp://localhost:5672'";
    string connectionFactoryName = "ConnectionFactory";
    string? username = ();
    string? password = ();
    map properties = {};
    !...
};
```

**Suggested Labels (optional):**
Component/jms, Type/Improvement 

**Suggested Assignees (optional):**
Arshika

**Comment by JensWalter** [comment]
Those fields are definitely not redundant since most providers don't support setting a username and password as URL.

**Comment by aashikam** [comment]
Yes agreed. But the username and password can also be given in the provider URL which makes the current design confusing. So we're hoping to improve this by allowing the user to provide the username and password only as separate parameters and we will internally construct the provider URL.

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#9 to get latest updates of this issue
