### ISSUE TITLE
Error on ballerina init

### ISSUE THREAD

**Issue by ponsilva** [ballerina-platform/ballerina-lang#11535]
**Description:**
Error: JAVA_HOME is not defined correctly
happens on ballerina init

**Steps to reproduce:**
Install ballerina using ballerina-linux-installer-x64-0.983.0.rpm
Execute
ballerina init
in a new folder

Error: JAVA_HOME is not defined correctly

I saw the /etc/profile.d/wso2.sh file contains: 
export BALLERINA_HOME=/usr/lib64/ballerina/ballerina-0.983.0
but ballerina is installed in 
/usr/lib64/ballerina/ballerina-platform-0.983.0/

I tried to manually modify the wso2.sh and after that it seems to work.

**Affected Versions:**
0.983.0

**OS, DB, other environment details and versions:**
Linux

**Comment by keizer619** [comment]
Thank you for reporting. We have already created an issue for this [1].
We will be releasing rpm installer release by fixing this.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/11496
