### ISSUE TITLE
Implement value equality (==/!=) for tables

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#11565]
**Description:**
#10904 changed the `==` and `!=` operators to be deep value equality checks for `anydata`.

This did not include an implementation for `table`s. Equality for tables needs to be defined and implemented.

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/23799 ...

**Comment by mohanvive** [comment]
Equality check fails for the case when we have a key specifier. We need to verify this.
