### ISSUE TITLE
Introduce necessary LS changes with the syntax change to object outside method definitions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#11629]
**Description:**
With #11298 object outside method definitions have been changed to use dots `.` instead of double colons `::`. 

### Example
For the following object definition
```ballerina
type PersonObject object {
    string name;

    new(name) {}

    function getName() returns string;
};
```
the outside function definition changes as follows:

**Previous Definition - (PersonObject::getName())**
```ballerina
function PersonObject::getName() returns string {
    return self.name;
}
```

**New Definition - (PersonObject.getName())**
```ballerina
function PersonObject.getName() returns string {
    return self.name;
}
```

**Affected Versions:**
0.985.0-SNAPSHOT

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged in the latest master
