### ISSUE TITLE
Ballerina module compilation will run forever when same module is imported within the module

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#11767]
**Description:**
Ballerina module compilation will run forever without returning an error when the same module is imported within the module.

> Apache Maven version - 3.5.3

**Steps to reproduce:**
Import own module in any `.bal` file of the same module. Build the module with `$ mvn clean install`. This will endup with compiling source forever.

Eg:
1. Import http module in any `.bal` of http module. `import ballerina/http`
2. Build http module with `$ mvn clean install`.
3. The compilation run forever after following output.
```
Compiling source
    ballerina/http
```

**Affected Versions:**
Ballerina 0.983.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Comment by SupunS** [comment]
This is a known issue: https://github.com/ballerina-platform/ballerina-lang/issues/4878, and don't think its a blocker. 
Closing this one, increased the priority of the original one.
