### ISSUE TITLE
[Feature] Writing Ballerina Byte and Stream messages to JMS broker

### ISSUE THREAD

**Issue by Seralahthan** [ballerina-platform/ballerina-lang#11807]
**Description:**
Currently, Ballerina JMS packages don't support writing ByteMessage or StreamMessage to the JMS broker. According to the current implementation, there is only **createTextMessage()** supported by the ballerina JMS package which is used to write text messages to the JMS broker. Similarly, we need to have a methods like **createBytesMessage()** and **createStreamsMessage()**.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Feature, Improvement

**Suggested Assignees (optional):**

**Comment by riyafa** [comment]
This is currently supported
