### ISSUE TITLE
[Spec Deviation] Incorrect results for reference equality checks with float NaN/NaN and -0.0/+0.0

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#11913]
**Description:**
Value equality checks for NaN/NaN and -0.0/+0.0 currently evaluate to true as follows:
```ballerina
NaN != NaN
```
```ballerina
-0.0 == +0.0
```

Reference equality checks for NaN/NaN and -0.0/+0.0 are expected to evaluate to true for:
```ballerina
NaN === NaN
```
```ballerina
-0.0 !== +0.0
```

Currently the reference equality checks fail since we consider the reference equality checks for simple basic types to be the same as value equality checks.

**Comment by MaryamZi** [comment]
As per the new spec (v0.990:2018-12-DD), evaluation needs to happen as follows:
```ballerina
NaN === NaN; // true
NaN == NaN; // true

-0.0 === +0.0 // false
-0.0 == +0.0 // true

```

**Comment by Anoukh** [comment]
decimal type should support division by zero as well

**Comment by hasithaa** [comment]
Duplicates #17977
