### ISSUE TITLE
Issue in inferRecordFieldType method

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#11995]
**Description:**
In the Types class, we can infer the type of a record field using `inferRecordFieldType` method. `anydata` is not considered in this method, `any` will be returned in such cases.

**Comment by hasithaa** [comment]
Looks like a bug to me and error-prone logic.

**Comment by gimantha** [comment]
looks both this and #19041 same .. need to verify

**Comment by rdhananjaya** [comment]
Same as #19041
