### ISSUE TITLE
Include test coverage report for Composer and VSCode modules

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#12006]
**Description:**
We need to include coverage report like Istanbul [1] for our node based modules. Then those coverage reports need to be included with codecov.

[1] https://istanbul.js.org/

**Comment by kaviththiranga** [comment]
@pahans does #12816 fix it for both composer modules & vscode module?

**Comment by pahans** [comment]
@kaviththiranga the above PR is only for vscode module

**Comment by pahans** [comment]
closing this because this is fixed in latest master.
