### ISSUE TITLE
Unused tokens in ballerina lexer definition

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#12030]
**Description:**
Current ballerina ANTLR lexer definition includes following unused lexer tokens, which were not removed along with the recent parser definition changes.
**i.e.** `some`, `timeout` and `but` keywords

**Steps to reproduce:**

**Affected Versions:**
0.983.1-SNAPSHOT (in branch `df_endpoint_changes`)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulvinw** [comment]
These lexer tokens are not available in the new parser. Hence could be closed.
