### ISSUE TITLE
Twitter component does not catch misconfiguration

### ISSUE THREAD

**Issue by christian-posta** [ballerina-platform/ballerina-lang#12086]
**Description:**
I misconfigured the twitter client on accident, and all the error messages indicated the calls to the twitter API could not be authenticated. 

As I debugged, i eventually found that I typed:

`clientSecret: config:getAsString("clientKey")` when in fact the correct key was `consumerSecret`.

In effect, the `clientSecret` parameter was not being set, and that caused the communications to fail.

I'd suggest catching any required fields and testing them for validity (i.e., not empty at least) to catch this kind of thing earlier. 

Using ballerina 0.983.0

ALSO: this repo seems like the main repo for things related to ballerina. if there's a better issue tracker to open up issues like this, please advise.

**Comment by anupama-pathirage** [comment]
@christian-posta Thanks for the suggestion and we will look into this. 

Yes. You can report twitter module related issues here in  [twitter repo](https://github.com/wso2-ballerina/module-twitter)

Repositories for Other similar modules can be found in [wso2-ballerina](https://github.com/wso2-ballerina) org.

**Comment by anupama-pathirage** [comment]
@christian-posta We have created the issue https://github.com/wso2-ballerina/module-twitter/issues/75 to track this in twitter module repo. Hence closing this issue.
