### ISSUE TITLE
Incorrect syntax in example for worker interaction

### ISSUE THREAD

**Issue by christian-posta** [ballerina-platform/ballerina-lang#12090]
From this guide:

https://ballerina.io/learn/by-example/worker-interaction.html

<img width="669" alt="image" src="https://user-images.githubusercontent.com/53201/49241163-46b1d800-f3c4-11e8-8d27-66c3fc404849.png">

Line #6 is incorrectly concatenating the string with `,` character instead of the right character which is `+`

**Comment by keizer619** [comment]
print allows pass an any[] array as a parameter and it prints all the elements in array. This is specified in the [ballerina/io module api docs](https://ballerina.io/learn/api-docs/ballerina/io.html#print).

```ballerina
import ballerina/io;

public function main (string... args) returns (int) {
    io:println("age",":", 23);
    return 0;
}
```
Output

```
age:23
```

**Comment by anupama-pathirage** [comment]
@christian-posta Please refer the previous comment for more details and we are closing this issue as this is the expected behavior. Feel free to reopen if you have further clarifications.
