### ISSUE TITLE
VSCode plugin fails when having empty "ballerina.home" value in settings.json

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#12099]
**Description:**
VSCode plugin fails to start when having empty "ballerina.home" value in settings.json 

**Steps to reproduce:**
Apply following entry into the **settings.json**
```json
{
    "ballerina.home": ""
}
```

**Comment by roonyh** [comment]
We treat this as not setting ballerina home at all. And plugin should try to auto detect ballerina installation in this case. On mac os use `which` command for this.

Could you give that output of `which ballerina`? and see what's the version of ballerina in that directory?

**Comment by pahans** [comment]
ballerina.home resolution is correct. This is a mac-homebrew specific issue where path we generate for langserver.sh is incorrect. Related 
https://github.com/ballerina-platform/ballerina-lang/issues/9724

**Comment by rasika** [comment]
This is due to an issue in Homebrew formula. It creates a symlink for the language server script as `/lib/resources`, but for the 0.983.0 has renamed it into the `/lib/tools`. Will fix in next release of the brew formula.

**Comment by pahans** [comment]
Added a fix to vscode plugin to ensure backward compatibility. https://github.com/ballerina-platform/ballerina-lang/pull/12322

**Comment by rasika** [comment]
Added a fix to brew plugin. https://github.com/Homebrew/homebrew-core/blob/master/Formula/ballerina.rb#L24:L27
