### ISSUE TITLE
Code analysis does not happen for lambda functions, if passed as arguments to unknown functions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#12122]
**Description:**
Code from the test file `fp-with-import-negative.bal`:

```ballerina
function test1() {
    // package streams is not imported.
    streams:Select select = streams:createSelect(outputProcess.process, function (string k) returns map<any> {
            int[2] arr = [12, 13];
            int index = 1;
            return {
                "val1": arr[3],
                "val3": 24
            };
        });
}
```

`streams` is not imported and `streams:createSelect` is thus unknown. 

Compilation was expected to fail with 6 errors, with the last one being `array index out of range: index: '3', size: '2'`, but only 5 errors are logged now.

**Comment by gimantha** [comment]
These error are logged now, hence considered fixed

error: .::dd.bal:3:5: undefined module 'streams'
error: .::dd.bal:3:5: unknown type 'Select'
error: .::dd.bal:3:29: undefined module 'streams'
error: .::dd.bal:3:29: undefined function 'createSelect'
error: .::dd.bal:3:50: undefined symbol 'outputProcess'
error: .::dd.bal:7:29: list index out of range: index: '3'
