### ISSUE TITLE
Issue in accessing local variables in a lambda function

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12158]
**Description:**
```ballerina
public function main() {
    string[] data = ["A", "B", "C"];

    int i = 0;
    data.foreach(function(string s){
        io:println(i, " : ", s);
    });
}
```
Output of the above program is -
```
0 : null
0 : null
0 : null
```

This only happens when accessing local variables in the lambda.

**Comment by pubudu91** [comment]
Possibly related to #10149

**Comment by NatashaWso2** [comment]
This issue is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/14614, hence closing this issue.
