### ISSUE TITLE
Import statements are not required per `.bal` file inside a module

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#12165]
**Description:**
Inside a Ballerina module, if we specify an import in a single `.bal` file, all the features of imported module can be used in other `.bal` files also. There is no need to do imports per `.bal` file.

**Steps to reproduce:**
1. Create 2 `.bal` files named `a.bal` and `b.bal`.

_a.bal_
```ballerina
import ballerina/io;
```

_b.bal_
```ballerina
public function main() {
    io:println("Hello");
}
```
2. Put them inside a single module named _sample_.
3. Run the module: `$ ballerina run sample`

**Affected Versions:**
Ballerina 0.983.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Comment by pubudu91** [comment]
Isn't this the expected/correct behaviour?
