### ISSUE TITLE
Issue in associated functions with future

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#12183]
**Description:**
$subject. Program hangs with below code.

**Steps to reproduce:**
```ballerina
function testAsyncNonNativeBasic6() returns boolean {
  future<float> f1 = start addSlower(5.0, 5.0);
  boolean a = f1.isDone();
  float v1 = wait f1;
  boolean b = f1.isDone();
  future<any> f2 = start infiniteFunc();
  boolean c = f2.isCancelled();
  boolean d = f2.cancel();
  future<any> f3 = start io:println("NATIVE ASYNC BLOCKING");
  boolean e = f3.cancel();
  future<any> f4 = start runtime:sleep(100);
  boolean f = f4.cancel();
  return !a && v1 == 10.0 && b && !c && d && !e && !f;
}
function infiniteFunc() {
  int i = 0;
  while (true) {
    i = i + 1;
  }
}
```
Test case BasicAsyncOperationsTest.testAsyncNonNativeBasic6 is disabled with https://github.com/ballerina-platform/ballerina-lang/pull/12184

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lankavitharana** [comment]
PR merged, hence closing
