### ISSUE TITLE
UniqueLengthWindow in Streams does not work in expected way

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#12197]
Please check the testcase below
https://github.com/ballerina-platform/ballerina-lang/blob/df_endpoint_change/tests/ballerina-unit-test/src/test/java/org/ballerinalang/test/streaming/BallerinaStreamsV2UniqueLengthWindowTest.java

The second testcase is not working in the expected way. It is commented for now.

**Comment by mohanvive** [comment]
Fixed by Lahiru in https://github.com/ballerina-platform/ballerina-lang/pull/12302 ..
