### ISSUE TITLE
Disallow naming a worker as default

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#12251]
**Description:**
Currently naming an explicit worker as `default` is allowed. This can be ambiguous as we also refer to the implicit worker as `default`. We need to disallow explicitly naming a worker as `default`.

**Suggested Labels (optional):**
Type/Improvement, Component/BVM

**Suggested Assignees (optional):**
@lankavitharana

**Comment by lankavitharana** [comment]
PR https://github.com/ballerina-platform/ballerina-lang/pull/12776 merged, hence closing
