### ISSUE TITLE
Ballerina scheduler metrics does not show statistics about worker waiting for lock, running worker count, paused worker count etc.

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#12259]
**Description:**
With the new changes done to the BVM, the ballerina scheduler metrics does not show statistics about worker waiting for lock, running worker count, paused worker count etc.

**Affected Versions:**
0.983.1-SNAPSHOT

**Comment by Kishanthan** [comment]
This is no longer valid with the new jBallerina based impl. Need to think along the line of strands and new scheduler.
