### ISSUE TITLE
Micro-transaction participants doesn't execute aborted function handler

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#12257]
**Description:**
Executing abort function handlers in transaction participants are disabled since they actually are rollback handlers for each transaction attempt. The current transaction coordinator is not aware of transaction re-try attempts hence can not differentiate between a rollback and a abort.

A abort being initiator aborting the whole transaction where as rollback is rolling back changes in previous failed transaction attempt.

**Affected Versions:**
0.990.0

**Comment by mohanvive** [comment]
No longer valid in new transaction implementation. Hence, closing the issue.
