### ISSUE TITLE
Current tracers will trace each and every VCALL instruction with the new changes to the BVM

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#12260]
**Description:**
With the new changes done to the BVM the current tracers will trace each and every VCALL instruction as well. This needs to be avoided.

**Affected Versions:**
0.983.1-SNAPSHOT

**Comment by Anoukh** [comment]
Only remote functions are traced with jBallerina. Hence closing this issue.
