### ISSUE TITLE
Provide ConstructFrom Support for Tables

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#12264]
**Description:**
At the moment, stamping support is not provided for tables in Ballerina. We have to provide this support for tables as well. 

**Affected Versions:**
0.985.0

**Comment by Kishanthan** [comment]
@Manuri, please close this if this is supported already.

**Comment by Manuri** [comment]
Calling `constructFrom` on table to convert a given value to table type, is not a requirement that has been recognized to be of use so far. 
However table -> JSON/XML conversion is possible by calling `constructFrom` on JSON/XML. Also the table type is under preview in the 2019R2 spec, and only identified necessary features have been implemented.

Please let us know the exact requirement to check whether it can be fulfilled with existing functionalities.
