### ISSUE TITLE
Explicit error conversion on creation not working properly

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#12279]
**Description:**
If you explicitly cast to error a newly created inline object you get an unexpected and cryptic error

**Steps to reproduce:**
````
// Explicit cast to json
any j = <json> {message: "..."};

// explicit cast to error of a preexisting object
any e1 = <error> j;

// explicit cast to error of a newly created inline object
any e2 = <error> {message: "..."}; // <-- error

public function main() {
    // Nothing to do here :)
}
````
**Affected Versions:**
0.983.0
0.983.1-SNAPSHOT (Dec 01, 2018)

**OS, DB, other environment details and versions:**
Windows 10

**Comment by rdhananjaya** [comment]
With new changes to `error` type and type conversion syntax 
```ballerina
any e2 = <error> {message: "..."};
```
is no longer a type conversion. 

New type conversion syntax: [https://ballerina.io/learn/by-example/type-conversion.html](https://ballerina.io/learn/by-example/type-conversion.html)

About type assertions: [https://ballerina.io/learn/by-example/type-assertion.html](https://ballerina.io/learn/by-example/type-assertion.html)

**Comment by MaryamZi** [comment]
With the new changes to the `error` type, `error` does not belong to `any` and how an error is created has also changed. 

For example the simplest case is as follows:
```ballerina
error e = error("error reason");
```

Refer https://ballerina.io/learn/by-example/error-handling.html for more details.

Thus creating an error now requires the error constructor `error(...)` to be used. If casting is used with an in-lined error, casting will be successful only if the created error belongs to the target type, if not casting would result in a panic.

```ballerina
const ERR_REASON = "reason";

type MyError error<ERR_REASON>;

error e1 = <error> error("different reason"); // <-- successful
error e2 = <error> error(ERR_REASON); // <-- successful
MyError e3 = <MyError> error(ERR_REASON); // <-- successful
MyError e4 = <MyError> error("different reason"); // <-- panics
``` 

Please note that the type cast related changes will be available with the next release of Ballerina.

Please do re-open this issue if you have further concerns.
