### ISSUE TITLE
Schema object returns null in generated swagger json 

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#12276]
**Description:**
When converting a ballerina file into swagger using the command `ballerina swagger export <ballerina-file>` the required schema definitions are not getting persisted to the created file. The schema object is available but is empty.

**Steps to reproduce:**
convert a standard ballerina file using the command `ballerina swagger export` and inspect the created file.

**Affected Versions:**
Ballerina 0.983.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Windows 10 Pro

**Comment by NipunaMarcus** [comment]
Closing this issue and attaching it to the newly created issue to track the new implementation of the OpenAPI tooling and to evaluate this issue once the new implementation is done.
