### ISSUE TITLE
test:assertEquals not working for decimal literals

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#12393]
**Description:**
`test:assertEquals` method not working for for decimal literals. This uses `reflect:equals` method underneath.

**Steps to reproduce:**
```ballerina
    decimal d = 23.4;
    test:assertEquals(d, d);
```
The above assertion fails with the below error message:
`error: Assertion Failed!: expected '23.4' but found '23.4' {}`

**Suggested Labels (optional):**
<Type/Bug>, <L1/L2 for December>

**Comment by rasika** [comment]
Might be related to the https://github.com/ballerina-platform/ballerina-lang/issues/10481
