### ISSUE TITLE
Reason is nullable for errors when used as a return type.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#12410]
**Description:**
As per the definition, an error must have a reason. i.e BLangErrorType. But when error is used as a return type for a function, the reason is nullable. Due to this reason API docs cannot be generated resulting a NullPointer exception. Null checks were added as a workaround in https://github.com/ballerina-platform/ballerina-lang/pull/12403

**Steps to reproduce:**
Generate docs with the following function signature:
```ballerina
public function sayHello() returns string|error {}
```

**Affected Versions:**
0.983.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Mac

**Comment by hasithaa** [comment]
The reason string is now removed with SLP1. Need to verify this new implementation

**Comment by hasithaa** [comment]
BLangNodes are internal now, hence closing this issue.
