### ISSUE TITLE
Arrow function wrapped in Parentheses fails at compile time

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#12489]
**Description:**
If an arrow function is wrapped with parentheses it fails at compile time.
```ballerina
public function main() {
    function (int) returns int lambda = ((x) => x);
}
```
The above results in in a `cannot infer types of the arrow expression with unknown invokable type` compile time error.

**Comment by NatashaWso2** [comment]
This issue is fixed in latest master, hence closing this issue.
