### ISSUE TITLE
Filter out anonymous records in API docs

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#12510]
**Description:**
$Subject
eg: In [buitin docs](https://ballerina.io/learn/api-docs/ballerina/builtin.html)

**Comment by pubudu91** [comment]
What do you mean by this? Do you mean not to document anonymous records at all? What about anonymous records used in function params? 

@hemikak thoughts?

**Comment by praneesha** [comment]
Closing since this will be addressed via https://github.com/ballerina-platform/ballerina-lang/issues/20024.
