### ISSUE TITLE
Issue in running packages

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12544]
**Description:**
Consider the folllowing project structure.

```
├── ma
│   └── main.bal
├── ma:in
│   └── main.bal
```

**ma/main.bal -**
```ballerina
import ballerina/io;

public function ^"in:test"(int i) {
    io:println("Test 2");
}
```

**ma:in/main.bal -**
```ballerina
import ballerina/io;

public function test(int i) {
    io:println("Test 1");
}
```
When we run the following command, `test` function in `ma:in/main.bal` will be executed.

`ballerina run ma:in:test 10`

There is no way to run the `in:test` function in `ma` package.

**Comment by MaryamZi** [comment]
This is no longer valid since we don't allow running any public function in a package now.
