### ISSUE TITLE
Crypto HMAC returns invalid result when there is escape characters in the base-string

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#12555]
**Description:**
Crypto HMAC function (`crypto:hmac`) returns invalid result when there is escape characters in the base-string. The alternative solution is to use escape character twice.
Eg: `\\n`, `\\t`

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/crypto;

public function main() {
    string baseString = "test\n message";
    string key = "key";
    string signature = crypto:hmac(baseString, key, crypto:SHA256);
    io:println(signature);
}
```
Expected Result: **EA2CD08B195434A0259B1AE32C15A7712E3FB4ABBFE82771EE97E508F3843BA7**
Actual Result: **AFACE9A85BB35B540D192147C823920916D03C5E4289200020BA713A9B5CD2E4**

**Suggested Labels (optional):**
Component/stdlib
Type/Bug

**Suggested Assignees (optional):**
@ldclakmal

**Comment by lafernando** [comment]
This change, breaks existing functionality. And yes, if you need the escape character in a string, you're simply suppose to escape it. That is, if you want the string "\n", you can just write it as "\\n". The change here does a Java escape there, how is that correct?.
