### ISSUE TITLE
Types.isSameType check doesn't validate for structural typing. 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#12557]
Right now it validates only the same type.

**Comment by warunalakshitha** [comment]
@hasithaa ATM, isSameType methods validates structural types by checking whether both types are refer to same type reference ( Records, Objects) . Here we do not do any deep field checking as we do for when checking isAssignbale or checkingStamping methods. 

So do we need to do deep field checking in isSameType methods as well? Can you provide some example for issue of structural isSameType check?

**Comment by hasithaa** [comment]
Fixed with e460cacb79bc8ad4dc7de5f6aacdca580e0c54bd
