### ISSUE TITLE
[Testerina] - Service ports does not gets down after test finishes

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#12553]
**Description:**
> I have multiple tests (unit and integration) in a project, with multiple modules. These modules use separate ports for their services, and unit test are running fine with it. But when it comes to the integration test, the test fails due to `address already in use` error. (I do not have any other services using this `address:port`)
>
> When I change the port number in the integration test or If I run the integration test alone, it does not throw this error. Hence this should be a bug where the service port is not closed after the test finishes.

**Steps to reproduce:**
> Try two service tests using the same ports.
>
> Used the BBG `Parallel Service Orchestration`

**Affected Versions:**
> Ballerina 0.999.0 RC1

**OS, DB, other environment details and versions:**
> OS: Mac OS

**Suggested Labels (optional):**
> type/bug, component/testerina

**Comment by ChinthakaSenanayaka** [comment]
@hasithaa 

It seems this is not a bug, nevertheless, this is an improvement. This works as the Testerina and Ballerina is finalized.

**Ballerina finalized way now**: When run "ballerina run" in project level, it starts up all the services defined in each of the module. User has to manually kill or stop each modules' services.
**Testerina finalized way now**: Testerina does not involve in starting up or stopping down any services from any module. It uses Ballerina internally to do so. Thus, to run module's tests, it uses already started up service from the same module. When running integration test in project level with mock service to mock 1 of the above service with the same port number, it will say the ports is already in use.

This is an other place where the tester wants services to start up and stop down manually as the tester wants.

**Comment by hevayo** [comment]
Fix with 1.0.0-alpha3 the services will shutdown after the tests.
