### ISSUE TITLE
Cryptic error message for incompatible data binding types in resource signature

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#12562]
Consider the following program:
```ballerina
import ballerina/http;

@http:ServiceConfig { basePath: "/echo" }
service echo on new http:Listener(9090) {

    @http:ResourceConfig {
        methods: ["POST"],
        consumes: ["application/json"],
        produces: ["application/json"],
        path: "/order"
    }
    resource function addOrder(http:Caller caller, http:Request req, json orderReq) {
        http:Response resp = new;
        resp.setJsonPayload(untaint orderReq);
        _ = caller->respond(resp);
    }

}
```
Running the above service results in the following runtime error.
```
error: incompatible resource signature parameter type {}
	at ballerina/http:register(<native>)
	   ballerina/http:__attach(service_endpoint.bal:43)
	   ..<init>(service.bal:4)
```
This error message doesn't point out neither the resource with the invalid signature nor the incompatible var name in the resource signature. The error points to the start of the service definition.

**Comment by chamil321** [comment]
We have moved aforementioned  run-time validation to HttpCompilerPlugin via https://github.com/ballerina-platform/ballerina-lang/pull/15979 and have made the error message descriptive by pointing out the particular resource location. Hence closing the issue
