### ISSUE TITLE
[Editor] [Improvement] File drag and drop support on File Explorer

### ISSUE THREAD

**Issue by gvasanka** [ballerina-platform/ballerina-lang#1256]
Its better to support file drag and drop support within File Explorer so that ballerina developer can restructure his project space without moving to file system.

![selection_157](https://cloud.githubusercontent.com/assets/3368635/22540169/89418472-e944-11e6-9bc3-2c3ce5f445fc.png)

**Comment by uthaiyashankar** [comment]
Moving back from https://github.com/ballerina-lang/composer/issues/240

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
