### ISSUE TITLE
Compile Error When Nesting Expressions

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#12612]
The below code's compilation fails with the message "error: .::test.bal:2:31: mismatched input '['. expecting {'is', ';', '?', '+', '-', '*', '/', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '===', '!==', '&', '^', '...', '|', '?:', '->>', '..<'}"
```ballerina
public function main(string ...args) {
        byte k = (check foo())[1][2];
        io:println(k);
}

function foo() returns (int, byte[]) | error {
        (int, byte[]) a =  (5, [1,2,3,4,5,6,7]);
        return a;
}
```

**Comment by SupunS** [comment]
This should be the same issue as https://github.com/ballerina-platform/ballerina-lang/issues/10736, where parenthesis-expressions are not allowed in some places by the grammar.
