### ISSUE TITLE
[IDEA] Formatting issue

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12617]
**Description:**
<img width="312" alt="privat 2018-12-07 10-31-30" src="https://user-images.githubusercontent.com/4003115/49628647-5906c400-fa0b-11e8-93d9-127612cec088.png">

**Comment by NipunaRanasinghe** [comment]
@Shan1024 This is fixed with #12579. Therefore requesting to close :)
