### ISSUE TITLE
Resource function return hangs http connection

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#12613]
**Description:**
With the new resource syntax, uses have the ability to return from resources at any point of execution.
And for 'check' expressions, they automatically return the function with 'error' when the 'check' expression found an error as it's operand. 

Anyhow if it comes to a place in resource functions where function returns before calling caller->respond(..) method, the HTTP connection seems to hang until timeout. 

**Steps to reproduce:**
```ballerina
import ballerina/http;

service hello on new http:Listener(9090) {
    resource function sayHello(http:Caller caller, http:Request request) returns error? {
        http:Response response = new;
        response.setTextPayload("Hello Ballerina!");

        // uncomment below 3 lines.
        if (1 == 1) {
            error e = error("The error");
            return e;
        }
        _ = caller -> respond(response);
        return;
    }
}
```
**Affected Versions:**
0.990.0

**Comment by pubudu91** [comment]
Possible duplicate of #12566

**Comment by rdhananjaya** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12614 and https://github.com/ballerina-platform/ballerina-lang/pull/12626
