### ISSUE TITLE
[Diagram] Adding a statement in to a function with return cause an error

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#12676]
**Description:**
Adding a statement to a function with a return statement will cause an error as there cannot be any code after return.  

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/9109762/49687345-ad06cb00-fb27-11e8-9d6b-70983044730b.gif)

**Steps to reproduce:**

1. Create a function with a return
2. try adding a statement to that function from the diagram

**Affected Versions:**
Current Version

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
