### ISSUE TITLE
CSV channel should support user-defined separators

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#12671]
Currently csv channel does not support semicolon separated csv, which are very common.
Only tab, comma and colon separator are supported.
Actually, the user should be free to specify any separator.

As a workaround I'm currently using a text record channel as suggested [here](https://groups.google.com/d/msg/ballerina-dev/la_PG5oeZQ0/Zl-Kc3dWDgAJ)

**Comment by jimk-osu** [comment]
+1 on this

**Comment by jimk-osu** [comment]
We have a use case that uses `~` as the separator and would agree with @davebaol  that use a defined separator would be the best route.

**Comment by wggihan** [comment]
@jimk-osu Unfortunately, we haven’t had a time to look into this new addition in 1.0 release. Our main priority was to minimize breaking changes in the existing features and stabilize those components. 

We will have another minor release in another 4-6 weeks time frame. We will add this to that release.

**Comment by wggihan** [comment]
This will be available with Ballerina 1.0.1 release.
