### ISSUE TITLE
HMAC Fails With Newline Characters

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#12681]
This cryto:hmac functionality has broken from 0.990 RC1 and RC2. Now a string like the following gives a different value:-

string xx = "AAA\nBBB";

This has been broken by the PR [1]. Where for some reason, we are now doing a Java string escape for the input string before doing the hmac operation. 

[1] https://github.com/ballerina-platform/ballerina-lang/pull/12576

**Comment by Bhashinee** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/12685
