### ISSUE TITLE
Remove JMS support from description in XA transactions BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#12712]
**Description:**
$subject from https://ballerina.io/learn/by-example/xa-transactions.html as it is not yet supported. Originally reported in https://github.com/ballerina-platform/ballerina-lang/issues/12517

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed as per #12830
