### ISSUE TITLE
VScode documentation preview function in the object is not appearing.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#12746]
**Steps to reproduce:**

Use below example to reproduce 
[ https://github.com/ballerina-platform/ballerina-lang/blob/master/examples/documentation/documentation.bal](https://github.com/ballerina-platform/ballerina-lang/blob/master/examples/documentation/documentation.bal)

**Comment by nadeeshaan** [comment]
Closing since the issue has been fixed
