### ISSUE TITLE
Inconstancies with function pointer

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#12768]
**Description:**
Please refer below example.

In this sample, the onPushSummaryTrigger function is defined within the object and it cannot refer as a function pointer. But the nonObjectTrigger function for the timer which is defined outside the object can refer as a pointer. This seems bit inconsistent.

```ballerina
import ballerina/task;
import ballerina/io;
import ballerina/runtime;

public type MyObject object {

    private task:Timer? timer = ();

    public function __init() {
        self.timer = new task:Timer(onPushSummaryTrigger, (), 3000, delay = 0);
        self.timer.start();
    }

    public function onPushSummaryTrigger() returns error? {
        io:println("Push Summary Triggered....");
        return ();
    }

    public function onPushSummaryError(error e) {
        io:println(e);
    }
};

function nonObjectTrigger () returns error?{
    io:println("Push Summary Triggered....");
    return ();
}

public function main() {
    MyObject test = new;
    runtime:sleep(10000);
}
```

**Comment by vinok88** [comment]
This is not a bug, this is not possible in ballerina syntax. We have to introduce new syntax to refer an attached function within the same object, which should come from the Ballerina Spec.

**Comment by hasithaa** [comment]
This is expected. This is intentionally disallowed in the spec. You will need to wrap that with a new lambda function in order to use an object method as a function pointer. e.g: 
`() => self.onPushSummaryTrigger();`
