### ISSUE TITLE
VS code show experimental features as errors

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#12763]
**Description:**
VS Code shows experimental features as syntax errors.

<img width="554" alt="screen shot 2018-12-13 at 3 53 46 pm" src="https://user-images.githubusercontent.com/1496990/49932688-ac877f00-feef-11e8-802c-9b55bc190f60.png">

**Affected Versions:**
0.990.0

**Comment by nadeeshaan** [comment]
Enable the Allow Experimental flag in VSCode plugin in order to support the experimental features in Language Server.

![selection_204](https://user-images.githubusercontent.com/1329674/49938846-14929100-ff01-11e8-855e-5ff3d46f19b7.png)

Hence closing the issue
