### ISSUE TITLE
Need to update API docs for the HTTP client endpoint

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#12781]
The doc comments for the HTTP client endpoint are not updated to reflect the new changes in the client.
https://github.com/ballerina-platform/ballerina-lang/blob/ec306775441b71061a6d57a4fdb4a945b4ccf6b1/stdlib/http/src/main/ballerina/http/client_endpoint.bal#L35

**Comment by VijithaEkanayake** [comment]
Fixed with : https://github.com/ballerina-platform/ballerina-lang/pull/12790
