### ISSUE TITLE
Formatting and syntax highlighting issue in ballerina IDEA plugin

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#12791]
**Description:**
Ballerina IDEA plugin grammar tree breaks for type check expressions inside the ternary expressions, as shown by the following example. Therefore the plugin is unable to recover formatting and some syntax highlightings.

**Steps to reproduce:**
Please refer the code snippet below.
![screenshot from 2018-12-14 14-53-24](https://user-images.githubusercontent.com/29032600/49994670-1bc4a800-ffb0-11e8-8f83-9c79448c0751.png)

**Affected Versions:**
0.990.0 and below

**Comment by Anoukh** [comment]
Closing the issue since the PR has been merged
