### ISSUE TITLE
Implement XA transaction JOIN logic

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#12803]
**Description:**
We always pass the TMNOFLAGS regardless of whether the current XAResource belongs to the same RM as any previous XAResource in the same XA transaction. Instead, in such a case need to pass TMJOIN flag.

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/7963

**Comment by mohanvive** [comment]
We may need to consider this with the new transaction implementation.

**Comment by kumarmpk** [comment]
@mohanvive  Does MySQL support JOIN/RESUME in XA START command?

**Comment by mohanvive** [comment]
In Swan Lake, we have introduced Atomokis based transactions for XA cases, thus above issue is avoided. Hence, closing the issue.
