### ISSUE TITLE
Intermittent build failures

### ISSUE THREAD

**Issue by shethdhvani** [ballerina-platform/ballerina-lang#12805]
**Description:**
Intermittent failures in Integration Test and Tools Integration Test while building Ballerina from source. 

Below are the errors. 

![image](https://user-images.githubusercontent.com/21231541/50024110-567a1080-ffaf-11e8-8c41-dd838751a3da.png)

![image](https://user-images.githubusercontent.com/21231541/50024158-7e697400-ffaf-11e8-9d51-9be3491edd50.png)

After this, I tried building Ballerina from source again. I resumed the build using *mvn install -rf :ballerina-integration-test* and it passed Integration Test but failed in Tools Integration test.

![image](https://user-images.githubusercontent.com/21231541/50024222-ac4eb880-ffaf-11e8-9da7-b59c75ae14cf.png)

Now, again I tried building Ballerina from source again. I resumed the build using *mvn install -rf :ballerina-tools-integration-test* and Ballerina got built successfully.

**Steps to reproduce:**

Referring to "Install from source" from https://github.com/ballerina-platform/ballerina-lang

**Prerequisites**
- Oracle JDK 8 or OpenJDK 8
- Maven 3.5.0 or later
- Node (v8.9.x) + npm (v5.6.0 or later)
- Docker

**Building the source**

1.  Clone this repository using the following command.
git clone --recursive https://github.com/ballerina-platform/ballerina-lang

    If you download the sources, you need to update the git submodules using the following command.
git submodule update --init 

2. Run the Maven command mvn clean install from the repository root directory.

Also, make sure that JAVA_HOME environment variable is set and that you have the latest version of the master.

**Affected Versions:**
0.990.0

**OS, DB, other environment details and versions:**
OS: macOS High Sierra version 10.13.6

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Regarding the remaining failures:
- the WebSocket ClientInitializationFailureTest.testClientEndpointFailureInResource test has been disabled for the time being and issue #13338 has been created to identify and fix the intermittent failure.
- we could not observe the failure with TracingTestCase.

Closing this issue since the test failures other than the TracingTestCase have been fixed/addressed. Will re-open if the failure is observed again.
