### ISSUE TITLE
Migrate JsonLogFormatter to use  json serializer

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#12833]
We need to do $subject in [JsonLogFormatter](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-logging/src/main/java/org/ballerinalang/logging/formatters/JsonLogFormatter.java)

**Comment by warunalakshitha** [comment]
We have removed the JsonLogFormatter hence this issue is no longer valid.
