### ISSUE TITLE
`io:sprintf` fails for `nil` values 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#12842]
**Description:**
In the [Sprintf implementation](https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.0/stdlib/io/src/main/java/org/ballerinalang/stdlib/io/nativeimpl/Sprintf.java), methods are called on `args.getRefValue(k)`. 

When the Ballerina value is `nil`, `args.getRefValue(k)` becomes `null` resulting in NPEs. We need to specifically handle `nil` scenarios.

**This issue also causes the following issue in testerina:**
Since testerina internally uses `io:sprintf` to format the error messages when panicking on failure for `test:assertEquals` and `test:assertNotEquals`, test failures currently have an incorrect reason.

e.g.,
```cmd
$ ballerina test values
Compiling tests
    ballerina-examples/values:0.0.1

Running tests
    ballerina-examples/values:0.0.1
        [fail] testFunc:
            error: {}
                at ballerina/io:sprintf(<native>)
                ballerina/test:assertEquals(assert.bal:74)
```

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main(string... args) {
    string s = io:sprintf("%s", ());
    io:println(s);
}
```
Fails with:
```cmd
$ ballerina run sprintf_bug.bal
error: {}        at ballerina/io:sprintf(<native>)
           main(sprintf_bug.bal:4)
```

**Affected Versions:**
0.990.0

**Comment by aashikam** [comment]
Fixed [#12867](https://github.com/ballerina-platform/ballerina-lang/pull/12867)
