### ISSUE TITLE
"function invocation on type 'typedesc' is not supported" error when trying to invoke some invalid function on a type

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#12854]
**Description:**
$Subject

eg:
```ballerina
string s = string.create(x);
```
```bash
function invocation on type 'typedesc' is not supported
```
Since `convert` function is available, I think the error message should be changed, because we can't say function invocations are *NOT* supported.

**Comment by gimantha** [comment]
For the above code, now the error message has changed to "undefined function 'create'"
