### ISSUE TITLE
Compiler allows creating multiple init functions

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#12859]
**Description:**
$Subject.Also its possible to execute the __init function without any compilation error if it was declared last(See example below).  However you can't call first __init function (with int params).

**Steps to reproduce:**
```
import ballerina/io;
import ballerina/config;

type Example object {
    string name="";
    public function __init(int x) {
        io:println("int init exec");
    }

    public function __init(string y) {
        io:println("String init exec");
    }

};

public function main(string... args) {
    Example x = new ("1");
}
```

**Affected Versions:**
0.990.0

**Comment by Anoukh** [comment]
Closing this issue since the fix has been merged
