### ISSUE TITLE
Unexpected error "invalid shift operator"

### ISSUE THREAD

**Issue by davebaol** [ballerina-platform/ballerina-lang#12911]
**Description:**
Code below should compile
````ballerina
any a = 1;
boolean lt = 3 < <int>a;
````
instead you get the compile time error `invalid shift operator`, but of course this is not a shift operator at all.

**Affected Versions:**
0.990.1-SNAPSHOT (Dec 20, 2018)

**OS, DB, other environment details and versions:**
Windows 10

**Suggested Labels (optional):**
Component/Compiler, Type/Bug

**Comment by Shan1024** [comment]
Seems like this issue occurred after adding `typeDescExpr` to `expression` rule. This has introduced an ambiguity in the parse tree. 

This might get fixed if we update the grammar to not allow spaces in the shift operators.

**Comment by davebaol** [comment]
> This might get fixed if we update the grammar to not allow spaces in the shift operators.

Yep and it would be quite normal.
For the same reason most languages treat operators like tokens, lexical units not admitting spaces in between.
Also notice that Ballerina itself does not allow spases between operators like `&&`, `==`, `!=`, `<=`, ... so it would be even more consistent.

BTW, by updating the grammar [this diagnostic check](https://github.com/ballerina-platform/ballerina-lang/blob/a4c9555575b9684fe6d56b10a04b141c406b2ab0/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/antlr4/BallerinaParserErrorStrategy.java#L70) would likely become pointless.

**Comment by dulvinw** [comment]
Already fixed with new parser enhancements

**Comment by hasithaa** [comment]
@dulvinw Shall we add a test case, if not?

**Comment by SupunS** [comment]
This we can close this. Parser tests includes a few test-cases relates to this: 
https://github.com/ballerina-platform/ballerina-lang/blob/aeb25da680ce72ba3f6cb4af05425f81067f5a20/compiler/ballerina-parser/src/test/java/io/ballerinalang/compiler/parser/test/syntax/expressions/BinaryExpressionsTest.java#L41-L46

**Comment by hasithaa** [comment]
Closing as per the above comment.
