### ISSUE TITLE
Lexicographical string comparison

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#12934]
**Description:**
Currently Ballerina only supports equality checks for string comparison.

However, as discussed in the following threads, there could be the requirement to perform advanced lexicographical string comparisons for cases such as sorting strings.
- [Lexicographical String Compare](https://groups.google.com/d/topic/ballerina-dev/rw94oeEZnNs/discussion)
- [How to compare two strings?](https://groups.google.com/d/topic/ballerina-dev/2siHWs9nl5c/discussion)

Additional details on language level plans discussed in [Lexicographical String Compare](https://groups.google.com/d/topic/ballerina-dev/rw94oeEZnNs/discussion).

**Comment by davebaol** [comment]
If at least there was a way to get the character code at a given position, one could easily implement a simple, locale-unaware string comparison.

**Comment by davebaol** [comment]
This should be set to Priority/Highest IMO.
Don't mean to be rude but this is the first time ever (in decades) that I find myself using a programming language that doesn't allow you to do or at least implement a simple string comparison.

**Comment by hasithaa** [comment]
We are yet to add codepoint support for Ballerina string. Right now we simply using Java string. This is one of the spec deviations we are working on right now. With this, we will able to provide a comparison based on codepoints, but it is not the correct as James pointed here https://groups.google.com/d/msg/ballerina-dev/rw94oeEZnNs/r7inygJ0DQAJ.

Another problem we need to sort out is, bringing locale support into Ballerina. This is not finalized yet.

**Comment by hasithaa** [comment]
`codePointCompare` lang lib method has been added with JBallerina 1.0. https://github.com/ballerina-platform/ballerina-lang/blob/6881b7afb01a2b98e2dac09681ef44ea8d8cb989/langlib/lang.string/src/main/ballerina/src/lang.string/string.bal#L80
