### ISSUE TITLE
Issue with "is" check's "unnecessary condition: expression will always evaluate to 'true'"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#12933]
**Description:**
We have currently disallowed always true `is` checks.

However in some scenarios this fails compilation incorrectly.

For example, consider the following scenario where a stamping is done to change the type:
```ballerina
public function main() {
    map<string|int> m = { one: 1 };
    map<string|int|float> m2 = map<string|int|float>.stamp(m);

    if (m is map<string|int>) {
        // this should be false since the type of `m` is changed!
    }
}
```

Currently this fails with 
```cmd
$ ballerina run is_test.bal
error: .::is_test.bal:5:9: unnecessary condition: expression will always evaluate to 'true'
```

This is wrong since the condition will in fact be false due to stamping!

**Comment by SupunS** [comment]
Stamp can also fail at certain scenarios. In that case the type of `m` will still be `map<string|int>`.
Also, one can stamp within an `if` block, then we can't determine the exact type of `m`. 

Therefore, I think we can mark this as an improvement, and may requires some dataflow analysis to determine the type.

**Comment by MaryamZi** [comment]
This should no longer be an issue anyway, since we do not support changing the type of a value itself now (stamping).
