### ISSUE TITLE
Issue in objects in type definitions

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12961]
**Description:**

Consider the following example.

```ballerina
import ballerina/io;

type T object { public string s = ""; }|error;

public function main() {
    object { public string s = ""; } o = new;
    T t = o;
    io:println(t);
}

```
This will produce the below error.

```
incompatible types: expected '|error', found '$anonType$0'
```
(Note that the error message is incomplete as well).

If the type definition is changed so that the error is in the type definition before the object type, it works without any issue. Eg-

```ballerina
type T error|object { public string g = ""; };
```

But if we define the object as a separate type like below, this works as well.

```ballerina
import ballerina/io;

type M object { public string s = ""; };

type T M|error;

public function main() {
    M o = new;
    T t = o;
    io:println(t);
}
```

**Steps to reproduce:**

**Affected Versions:**
0.990.1

**Comment by hasithaa** [comment]
Fixed in SLP1.
