### ISSUE TITLE
Code completion suggestions not given for chained iterable ops

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#12969]
For example, consider typing the below code snippet.
```ballerina
float[] fs = numbers.map(function(int value) returns float {
        return float.convert(value);
    }).filter(function (float value) returns boolean { 
        return value > 0;
    }); 
```
When you start to type `map`, you get the code completion suggestions. But when typing `filter`, you don't get the code completion suggestions.

**Comment by nadeeshaan** [comment]
Fixe in latest master and closing the issue
