### ISSUE TITLE
Record fields can be declared without initializing

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12962]
**Description:**
```ballerina
type K record { F f; };
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/12958

**Comment by pubudu91** [comment]
What's the issue with this? This is a valid type descriptor.

**Comment by Shan1024** [comment]
Seems like the issue was in the object definition which I was trying and mistook for the record definition which was in the union as well.
