### ISSUE TITLE
[DOCS] Undefined symbol `toUpper`: single lambda function required here.

### ISSUE THREAD

**Issue by 13Ax0** [ballerina-platform/ballerina-lang#12996]
**Description:**
I was reading the [Ballerina by Example: Functional Iteration](https://ballerina.io/learn/by-example/functional-iteration.html) section on the documentation and I found the following piece of code:

```ballerina
string[] animals = words.map(toUpper);
```

I tested it and got this error:

```
Undefined symbol `toUpper`: single lambda function required here.
```

Well, ok. So I searched for lambda functions in Ballerina and all I could find was a [broken link on Google](https://ballerina.io/learn/by-example/lambda.html).

**Steps to reproduce:**

1. Save this snippet to a `.bal` file:

```ballerina
public function main() {
    map<string> words = {
        a: "ant",
        b: "bear",
        c: "cat",
        d: "dear",
        e: "elephant"
    };

    string[] animals = words.map(toUpper);
}
```

2. Watch it fail:

```
$ ballerina run will_fail.bal
error: .::will_fail.bal:22:34: undefined symbol 'toUpper'
error: .::will_fail.bal:22:34: single lambda function required here
```

**Affected Versions:**
- Ballerina version: 0.990.2

**OS, DB, other environment details and versions:**
- OS: elementaryOS 5.0 Juno (Ubuntu-based)

**Comment by davebaol** [comment]
You're missing the `toUpper` function at the end of the example which takes a key/value pair
````ballerina
function toUpper((string, string) pair) returns string {
    var (key, value) = pair;
    return value.toUpper();
}
````

**Comment by 13Ax0** [comment]
@davebaol Oh... silly me. Thanks. I think we can close this issue now.

**Comment by pubudu91** [comment]
Closing this since this isn't an issue.
