### ISSUE TITLE
Improve global variable grammar

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13007]
Need to refactor global variable grammar since at the moment, we don't support var with listeners. But we should be able to support that.

_Originally posted by @hasithaa in https://github.com/ballerina-platform/ballerina-lang/pull/12673_

**Comment by MaryamZi** [comment]
As per the current spec, the grammar for listeners and module variable declaration is as follows:

**Listener declaration**
```
listener-decl :=
   metadata
   public? listener [type-descriptor] identifier = expression ;
```

**Module variable declaration**
```
module-var-decl :=
   metadata
   [final]
   typed-binding-pattern = expression ;
```

I guess what we need to support now is defining listeners without specifying the type.

**Comment by MaryamZi** [comment]
Created https://github.com/ballerina-platform/ballerina-lang/issues/18200 to track defining listeners without specifying the type.
