### ISSUE TITLE
Allow var in worker receive

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#13010]
**Description:**
Currently var is not allowed for worker receive. In the following sample the type of the worker receive expression 'y' should be of 'int' type.

```ballerina
function testFunc() {
    worker w1 {
	    int x = 50;
	    x -> w2;
    }
    worker w2 {
    	var y = <- w1;
    }
}
```

**Affected Versions:**
0.990.3-SNAPSHOT

**Comment by MaryamZi** [comment]
Related spec issue https://github.com/ballerina-platform/ballerina-spec/issues/373.

**Comment by MaryamZi** [comment]
This is valid and should be supported as per the spec issue.

**Comment by ushirask** [comment]
Deferred due to the current design of the compiler; To get the type for `var` in the receiver we need to maintain a list of receivers and their corresponding send actions at the TypeChecker stage and the receivers be dependent on the corresponding sender.

**Comment by hasithaa** [comment]
We are deferring this implementation, due to implementation complexities.
