### ISSUE TITLE
Config API produces incorrect result when reading keys which contain a "=" or " " that are provided as CLI parameters

### ISSUE THREAD

**Issue by hisanhunais** [ballerina-platform/ballerina-lang#13041]
**Description:**
When reading CLI parameters using the config API, if we provide a key-value pair such as a=b=abcd where "a=b" is the key and "abcd" is the value, and if we read the key a=b using the config:getAsString() method, it returns the empty string indicating that a=b key has not been defined. The reason is that it splits the key-value pair a=b=abcd using the first "=" such that the key becomes "a" and the value becomes "b=abcd".
Also, there is a problem when the key contains a space character.

**Steps to reproduce:**
```
import ballerina/config;
import ballerina/io;

function main(string... args) {
    string configValue1 = "a=b";
    string configValue2 = "a";
    string value1 = config:getAsString(configValue1);
    string value2 = config:getAsString(configValue2);
    io:println(value1);
    io:println(value2);
}
```
Running the above program using 
```
ballerina run sample1.bal -e a=b=abcd
```
produces the following result.
```

b=abcd
```

**Affected Versions:**
Ballerina 0.990.3-SNAPSHOT

**Comment by pubudu91** [comment]
Had a closer look at this. The only problem is the "=". Spaces work fine. But you need to escape them and should be within escaped quoted. For example `-e \"a\ b\"=foo`
