### ISSUE TITLE
cannot create a variable called 'query'

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#13098]
**Description:**
When I try to create a variable called 'query', an error is thrown. 

> error: .::client.bal:57:12: invalid token 'query'

The respective line 57.

>     string query = "q=book";

I am not sure whether query is a keyword. But intelIJ does not seem to recognize 'query' as a keyword.

**Steps to reproduce:**

Write a simple program and assign values to a variable called 'query'.

**Affected Versions:**
Ballerina 0.990.2
IntelIJ plugin 0.990.1

**Comment by pubudu91** [comment]
Yes, `query` is a keyword.

**Comment by arunans23** [comment]
Sure. Will do..
