### ISSUE TITLE
Taint analyzer should check taintedness of a service.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#13093]
**Description:**
Taint analyzer needs to analyze taintedness of field definitions in services.

**Affected Versions:**
0.990.2

**Suggested Assignees (optional):**
@ayomawdb

**Comment by hasithaa** [comment]
Related to #15242

**Comment by rdhananjaya** [comment]
Closing as this is no longer possible with removal of service level variables https://github.com/ballerina-platform/ballerina-lang/pull/17408
