### ISSUE TITLE
IntelIiJ does not recognize 'query' as a keyword

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#13107]
**Description:**
I was trying to create a variable called 'query', but it got failed. Found out that `query` is a keyword (#13098 ). But IntelliJ doesn't recognize it as a keyword, hence this creates a confusion.

**Affected Versions:**
Ballerina 0.990.2
IntelIJ plugin 0.990.1

**Comment by nadeeshaan** [comment]
@NipunaRanasinghe do we support diagnostics in intelliJIdea via LSP? If so, when we checked in the VSCode plugin, we get the diagnostic.

**Comment by arunans23** [comment]
@nadeeshaan no, I do not get a red underline showing a syntax error.

**Comment by NipunaRanasinghe** [comment]
@nadeeshaan yes we do, but it is **disabled by default** ATM since I'm working on some performance improvements. Anyway above mentioned error is related to the plugin side implementation for the keyword highlighting and working on fixing it :)

**Comment by NipunaRanasinghe** [comment]
As per the offline discussion with @mohanvive, `query` keyword will be removed as it is currently not used in the ballerina parser definition. I've also created a separate issue (#13248) to track that task. Hence closing.
