### ISSUE TITLE
Updated modules are not pulled automatically

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#13122]
**Description:**
I created a module and pushed it to ballerina central and used the module in another ballerina program. Afterwards I made changes to the module and pushed them. But the changes are not pulled from the ballerina central. 

**Steps to reproduce:**
Create a ballerina module. Push it ballerina central. Import the module in another ballerina program. Make changes to the module and version. Push it. Run the other program. Changes are not reflected.

**Affected Versions:**
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
MacOS

**Comment by pubudu91** [comment]
Did you update the module version of the dependency in the project which uses it?

**Comment by NatashaWso2** [comment]
@arunans23 to get the updated module:

- you can manually the pull the latest version of the module from Ballerina Central using the `ballerina pull` command and rerun the program
```bash
ballerina pull <org-name>/<module-name>:version
```
- you can uninstall the existing version of the module using the `ballerina uninstall` command and then pull the module again from Ballerina Central using the `ballerina pull` command. Then rerun the program.
```bash
// Uninstall the existing version of the module
ballerina uninstall  <org-name>/<module-name>:version

// Pull the latest version of the module
ballerina pull  <org-name>/<module-name>
```
-  you can specify the version of the dependent module in the Ballerina.toml in your project as given in 
[https://ballerina.io/learn/how-to-structure-ballerina-code/#modules](https://ballerina.io/learn/how-to-structure-ballerina-code/#modules) and then rerun the program. This will pull the mentioned version of the dependent module from Ballerina Central and use it when compiling.
```bash
[dependencies."natasha/foo"]
version = "3.0.1"
```

**Comment by arunans23** [comment]
Thanks @NatashaWso2 @pubudu91 

I will go with the 3rd approach. Earlier, I did not define dependencies in a separate file.

**Comment by NatashaWso2** [comment]
Closing this issue since it can be achieved as per the comment : https://github.com/ballerina-platform/ballerina-lang/issues/13122#issuecomment-453372985
