### ISSUE TITLE
Improve env/scope usage in ballerina streams

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#13127]
**Description:**
Currently, we define output stream fields, field aliases, stream aliases and some other variables in parent SymbolEnv. And, this can cause various issues. So we need to improve this to use SymbolEnvs which are unique to given scope (forever-block (parent), selector, having, etc...) (A tree like SymbolEnvs).

**Steps to reproduce:**
N/A

**Affected Versions:**
0.990.2

**OS, DB, other environment details and versions:**
N/A

**Related Issues/PRs (optional):**
#13015, #13126

**Suggested Assignees (optional):**
@gimantha, @mohanvive, @grainier

**Comment by gimantha** [comment]
Fixed with new streams typechecker refactoring
