### ISSUE TITLE
Add support for signing using RSA-SHA256 algorithm

### ISSUE THREAD

**Issue by shethdhvani** [ballerina-platform/ballerina-lang#13135]
**Description:**
Need functionality to get signature using string to sign, private key (in .pem format), and the RSA-SHA256 algorithm. This is required for Ballerina-OCI module.

Refer the below page for detailed information on how OCI (Oracle Cloud Infrastructure) authenticates when making REST API calls.
https://docs.cloud.oracle.com/iaas/Content/API/Concepts/signingrequests.htm#one

**Affected Versions:**
Latest

**OS, DB, other environment details and versions:**
Linux, OS X, Windows

**Related Issues (optional):**

**Suggested Labels (optional):**
Type/Improvement
Component/stdlib/crypto
RSA-SHA256

**Suggested Assignees (optional):**

Also, this is not working yet, however maybe this is useful for reference:
https://github.com/shethdhvani/ballerina-oci

Thanks!

**Comment by shethdhvani** [comment]
Hi,

Signing http GET requests using RSA-SHA256 and returning the authorization header is working now. Below is the link for reference: 
https://github.com/shethdhvani/ballerina-oci

Thanks!

**Comment by ayomawdb** [comment]
This request is resolved with #13254 

New improvements to crypto stdlib includes:

- making the library extensible
- introducing RSA signing support
- introducing keystore, privatekey and publickey usable across other stdlibs for crypto operations 
- introducing new encoding stdlib for performing encoding operations on top byte arrays (outputs of crypto operations)
- moving encoding operations placed in different stdlibs (stringlib/internal) into `encoding` stdlib

**Comment by ayomawdb** [comment]
One deviation is that the current implementation supports reading `PrivateKey` used for signing operations from `p12` archive files. Improving this to support directly reading `PrivateKey` from a `PEM` file is moved to a separate improvement #13293
