### ISSUE TITLE
int to float implicit cast in json to record conversion

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#13136]
**Description:**
Should float in ballerina always have decimal points? float f = 2; works, but when converting json to a record type, why is a float without decimal points are NOT considered as float and thus the conversion is failing

**Steps to reproduce:**
```
public type Position record {
    int account = 0;
    string symbol?;
    string currency?;
    int currentQty = 0;
    float avgEntryPrice = 0;
    float liquidationPrice = 0;
};
```

Following will pass

```
json j = {"account":12, "symbol":"AUDUSD", "currency":"USD", "currentQty":-212, "avgEntryPrice":0.34, "liquidationPrice": 2.0};
    Position|error position = Position.convert(j);
    io:println(position);
```

Following will fail

```
json j = {"account":12, "symbol":"AUDUSD", "currency":"USD", "currentQty":-212, "avgEntryPrice":0.34, "liquidationPrice": 2};
    Position|error position = Position.convert(j);
    io:println(position);
```

Second case has liquidationPrice without decimal places..

**Affected Versions:**
0.990.2

**Comment by riyafa** [comment]
Is it related to this issue? https://github.com/ballerina-platform/ballerina-lang/issues/12363

**Comment by warunalakshitha** [comment]
@riyafa Not actually. This is current behavior of the convert method since when we convert structure value It happens via stamping the value to new type. But during stamping we do not change any member values. But according to spec, we need to do numeric conversation when stamping the member values whenever required. So with fixing the numeric conversion in stamping this issue can be solved.

We can use this issue to track the spec deviation of stamping method.

**Comment by raj-rajaratnam** [comment]
@warunalakshitha is there a fix for this yet?

**Comment by raj-rajaratnam** [comment]
@anupama-pathirage @hasithaa @warunalakshitha any plan to fix this? This is very inconvenient use int|float as a record field to workaround this. Appreciate a fix for this. Int should be automatically converted to float during stamping.

**Comment by hasithaa** [comment]
@raj-rajaratnam I have put parent issue into 0.995 issue pool.

**Comment by MaryamZi** [comment]
`.convert()` is now (1.0.0-alpha) replaced with `.constructFrom()` and doing numeric conversions with `.constructFrom()` is being tracked by #13950.

Closing this issue since $title should be possible once #13950 is fixed.
