### ISSUE TITLE
IntelliJ does not show any errors for undefined variables

### ISSUE THREAD

**Issue by sajinieKavindya** [ballerina-platform/ballerina-lang#13145]
**Description:**

Even if there is an undeclared variable that has been initialized with some value (string, int, json, etc), IntelliJ doesn't show any errors (neither underlined nor highlighted)

<img width="212" alt="screen shot 2019-01-11 at 2 00 35 pm" src="https://user-images.githubusercontent.com/17607360/51022104-5880c080-15a9-11e9-93db-4d985b1b4a62.png">

**Affected Versions:**
Ballerina - v0.990.2
IntelliJ plugin - v0.990.1

**Comment by sajinieKavindya** [comment]
@NipunaRanasinghe I enabled language server semantic analyzing, but it still doesn't show any errors.

**Comment by NipunaRanasinghe** [comment]
If you enable semantic analyzer, it should show the error as shown below.
 
![screenshot from 2019-01-21 17-10-40](https://user-images.githubusercontent.com/29032600/51472506-aa8ec680-1d9f-11e9-9015-41a47b4c0d95.png)

Could you please specify your IntelliJ IDEA version and the OS type as well?

**Comment by sajinieKavindya** [comment]
IntelliJ IDEA version - 2018.3.2
mac OS version 10.14.2

**Comment by sajinieKavindya** [comment]
Now it works. Thanks.
