### ISSUE TITLE
'lengthof' does not return a value for string array

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#13140]
**Description:**
I tried to check the length of the args to the main function using the following code.

``` 
public function main(string... args) {
      if (lengthof args != 1) {
            io:println("Usage : <query>");
            return;
       }
}
```

But it threw the following error.

> error: .::client.bal:17:9: operator 'lengthof' not defined for 'string[]'

**Steps to reproduce:**
Copy the above code and run.

**Affected Versions:**
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
MacOS

**Comment by MaryamZi** [comment]
`lengthof` was replaced with the `.length()` built-in method from Ballerina 0.990.0 onward.

You can say:
```ballerina
import ballerina/io;
public function main(string... args) {
      if (args.length() != 1) {
            io:println("Usage : <query>");
            return;
       }
}
```

**Comment by arunans23** [comment]
Thanks for the tip. Did not know that.

**Comment by Shan1024** [comment]
Better to remove the `lengthof` operator if it is not being used anymore. Created https://github.com/ballerina-platform/ballerina-lang/issues/13144 to track this.
