### ISSUE TITLE
Error when passing the return from an aggregate function, as a parameter to another function

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#13151]
**Description:**
```
from inputStream
        select getAge(sum(inputStream.age)) as count
        => (TeacherOutput [] teachers) {
            foreach var t in teachers {
                outputStream.publish(t);
            }
        }

function getAge(int age) returns int{
    return age;
}
```
Here I have passed the return from sum() aggregate function to another function. This gives following error.

`ERROR: .::streamingv2-aggregate-with-groupby-test.bal:84:23:: undefined function 'sum'
`

**Affected Versions:**
0.990.2

**Suggested Assignees (optional):**
@mohanvive , @gimantha , @grainier

**Comment by hasithaa** [comment]
@mohanvive Can you have a look on this?

**Comment by gimantha** [comment]
> @mohanvive Can you have a look on this?

**Comment by gimantha** [comment]
> @mohanvive Can you have a look on this?

We will have a look
