### ISSUE TITLE
IntelliJ does not show any errors for redundant method signatures or methods

### ISSUE THREAD

**Issue by sajinieKavindya** [ballerina-platform/ballerina-lang#13155]
**Description:**
 

IntelliJ does not give any errors (neither underlined nor shown in red) for duplicate method signatures or methods

<img width="328" alt="screen shot 2019-01-11 at 5 33 31 pm" src="https://user-images.githubusercontent.com/17607360/51032721-10709680-15c7-11e9-97b9-792868945a5e.png">

**Affected Versions:**
Ballerina - v0.990.2
IntelIJ plugin - v0.990.1

**Comment by NipunaRanasinghe** [comment]
Please refer https://github.com/ballerina-platform/ballerina-lang/issues/13145#issuecomment-453488136 .

After enabling semantic analyzer, your code editor should be changed as follows.

![screenshot from 2019-01-22 12-17-08](https://user-images.githubusercontent.com/29032600/51517096-b03be900-1e3f-11e9-8ae2-7e1cc1639667.png)
