### ISSUE TITLE
[Spec Deviation] Support 0. syntax for floating point literals

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13168]
**Description:**
Following need to be supported:
```ballerina
float f1 = 0.;
float f2 = 0x0.;
decimal d1 = 0.;
decimal d2 = 0x0.;
```
**Affected Versions:**
0.990.2

**Comment by pranavan15** [comment]
Differing this issue as this syntax conflicts with the int `range` operations.
It seems we cannot use `modes` and `predicates` as well in the grammar to differentiate these two syntaxes.

**Comment by dulvinw** [comment]
Hi @SupunS can you please check this issue? :)

**Comment by SupunS** [comment]
Works in Swan Lake preview1
