### ISSUE TITLE
[Spec Deviation] Const is not supported when specifying array length

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13162]
**Description:**
When creating a fixed length array, the size should be able to be specified using a compile-time constant.
```ballerina
const len = 5;
function testFunction() {
    int[len] intArr = [1, 2, 3, 4, 5]; // Currently not supported
}
```

**Affected Versions:**
0.990.2

**Comment by sanjana** [comment]
Assigned to @suleka96
