### ISSUE TITLE
[Spec Deviation] Direct table type descriptor is not implemented

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13170]
**Description:**
As per the spec (v0.990:2019-01-16), the table type descriptor is not implemented
```
table-type-descriptor := table { column-type-descriptor+ }
column-type-descriptor := individual-column-type-descriptor | column-record-type-reference
individual-column-type-descriptor := [key] type-descriptor column-name ;
column-record-type-reference := * type-reference [key-specifier (, key-specifier)*] ;
key-specifier := key column-name
column-name := identifier
```
**Affected Versions:**
0.990.2

**Comment by hasithaa** [comment]
Table syntax under review and will be revamped with https://github.com/ballerina-platform/ballerina-spec/issues/354 in future spec. 

@grainier Please resolve this issue when we implement the new table implementation.

**Comment by hasithaa** [comment]
This is changed with https://github.com/ballerina-platform/ballerina-spec/issues/47. Hence resolving.
