### ISSUE TITLE
Compile time validation (dataflow analysis) is not done for frozen values

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#13188]
**Description:**
According to the spec (v0.990:2019-01-16 - page 17), "a container value can also be frozen at runtime or **compile time**, which prevents any change to its members"

Given that a value can be frozen at compile time, dataflow analysis could be done to identify operations on values that would definitely result in a panic since the value is frozen, and fail compilation. 

Currently this is not done: compilation would be successful and the operation would result in a panic at runtime.

**Comment by MaryamZi** [comment]
Removing the spec deviation label since this is no longer mentioned in the spec.

**Comment by hasithaa** [comment]
Closing this issue since it is no longer in the SL spec.
