### ISSUE TITLE
[Spec Deviation] Fix XML characters iteration

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#13190]
**Description:**

As per the spec (v0.990:2019-01-16 - page 23), "An XML value is iterable as a sequence of its items, **where each character item is represented by a string with a single code point** and other items are represented by a singleton XML value. " 

But in the current implementation, XML character items are also iterated as singleton XML values, as opposed to the expected single code point iteration.

```ballerina
import ballerina/io;

public function main(string... args) {
    xml xmlCharacters = xml `Hello, world!`;

    anydata[] arr = [];
    int index = 0;

    foreach xml|string item in xmlCharacters {
        arr[index] = item;
        index += 1;
    }
    
    foreach anydata item in arr {
        io:println(item);
    }
}
```

```cmd
$ ballerina run xmlTest.bal
Hello, world!
```

**Affected Versions:**
0.990.2

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/13893
