### ISSUE TITLE
Unable to run ballerina command in VS code terminal on Windows

### ISSUE THREAD

**Issue by Yadhu7686** [ballerina-platform/ballerina-lang#13195]
**Description:**
The ballerina command is not executable in VS Code terminal but I could execute the same using my windows CLI. Below is the message. Also the sequence diagram is not showing up in VS code editor and it fails with the error message **command 'ballerina.showDiagram' not found**

$ ballerina
bash: ballerina: command not found

**Steps to reproduce:**
Create a .bal project in VS code and try running the project in VS code terminal. 
Click on show diagram in VS code terminal

**Affected Versions:**
VS Code 1.30.2
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
Windows 10.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@roonyh Can you please look into this?

**Comment by roonyh** [comment]
@Yadhu7686 Sorry about the trouble. Could you let us know what method you used to install ballerina?
Did you download the windows installer msi or did you download the .zip?
We are aware of a bug that might prevent the .zip from working properly in windows but the msi should work. So if possible install from the windows installer and try again.

**Comment by Yadhu7686** [comment]
Hi @roonyh , I installed using the installer msi.

**Comment by rasika** [comment]
@Yadhu7686 Usually, VSCode terminal acts independently with regardless of its plugins. Did you meant only `ballerina` command is not working your integrated terminal? Have you try other commands such as `dir` as well? Check whether you are running on VSCode in [Compatibility Mode](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#integrated-terminal-exited-with-code-1-on-windows-10) as well.

For the issue of  **command 'ballerina.showDiagram' not found**; Have you set up any **"Ballerina : home"** path in your VSCode settings? if yes; you can try keeping it empty as the latest ballerina-home path will be auto-detected by the VSCode plugin itself.

**Comment by Yadhu7686** [comment]
@rasika Yes, only ballerina is not working. Other commands are working. VScode is not running in compatibility mode. That option is unchecked. The Ballerina:Home is not set in the VSCode settings.

I tried by reinstalling both ballerina and VSCode and end up with no luck.

**Comment by roonyh** [comment]
@Yadhu7686 Thanks for the info. Could you please do the following to give us the debug log of the plugin.
* Go to settiings (<kbd>Ctrl</kbd> + <kbd>,</kbd>) and check `Ballerina:Debug Log` (set it to true)
* Reopen vscode and open a `.bal` file
* Go to View  ->  Output and from the dropdown on the right, select "Ballerina"
* Take a screenshot or copy paste the log and give it us

Here's a screenshot if it helps.

![image](https://user-images.githubusercontent.com/3872221/51577649-8f77a000-1ee0-11e9-95d2-1822bbb3513b.png)

**Comment by Yadhu7686** [comment]
Hi @roonyh ,
I updated this in the user settings and both the issues are resolved.

"terminal.integrated.shell.windows": "C:\\WINDOWS\\system32\\cmd.exe"

Thanks,
Yadhu

**Comment by roonyh** [comment]
Glad everything is working!!. I'll close the issue, feel free to reopen if it occurs again.

I am still not sure how it didn't work the first time. Were you using a different terminal with vscode? Other than powershell?

**Comment by Yadhu7686** [comment]
Actually it was defaulted to bash.exe :-)
