### ISSUE TITLE
[Spec Deviation] Error type should have a stackTrace built in method

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13206]
**Description:**
As per the spec (v0.990:2019-01-16)
The following  built-in methods are provided on the error basic type:

reason: returns the error’s reason string
detail: returns the error’s detail record as a frozen mapping
**stackTrace: returns an object representing the stack trace of the error** (Needs to be implemented)

Example:
```ballerina
function testErrorTypeDescriptorsStackTraceBroken() {
    error error1 = error("Error One");
    io:println(error1.stackTrace());
}
```

**Comment by hasithaa** [comment]
This is fixed in JBallerina 1.0.0-Alpha. 
https://github.com/ballerina-platform/ballerina-lang/blob/6881b7afb01a2b98e2dac09681ef44ea8d8cb989/langlib/lang.error/src/main/ballerina/src/lang.error/error.bal#L49
