### ISSUE TITLE
[Spec deviation] Decimal implicit initial value taken as 0 instead of +0.0

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#13201]
**Description:**
According to the spec, "The implicit initial value for each floating point type is 0.0". Currently, decimal implicit initial value taken as 0 instead of +0.0.

**Suggested Labels (optional):**
<Type/Bug>, <Component/BVM>

**Suggested Assignees (optional):**
@pranavan15

**Comment by pubudu91** [comment]
Isn't it the same? Is there any difference in how it is represented?

**Comment by pranavan15** [comment]
> Isn't it the same? Is there any difference in how it is represented?

@pubudu91:  It is actually the same and there is no difference in the way it is represented as well. Only the way we print the value `zero` needs to be changed. It is just to adhere to the spec and to maintain the consistancy between float and decimal types.
