### ISSUE TITLE
Unused tokens in Ballerina lexer definition

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#13248]
**Description:**

Current Ballerina lexer definition contains the following unused lexer tokens as reserved  words.

- **into**
- **query**
- **expired**
- **current**

**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.990.3-SNAPSHOT and below.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Fixed. in https://github.com/ballerina-platform/ballerina-lang/pull/13315 ...
