### ISSUE TITLE
Ballerina compiler does not provide semantics for unused functions, variables, imports, etc.

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#13268]
**Description:**
Current ballerina compiler implementation does not provide semantic information related to unused entities such as functions, variables, imports, etc. Therefore ballerina plugins ( vscode and intellij ) are unable to notify the user about the above contexts.

**Steps to reproduce:**
N/A

**Affected Versions:**
Ballerina 0.990.3-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#13154 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
#3698 Add validation for unused imports, and https://github.com/ballerina-platform/ballerina-spec/issues/356 is created to track unused variables. 
However spec doesn't mention about the "unused functions", So this can be considered as an implementation-specific improvement.

**Comment by hasithaa** [comment]
We discuss this issue partially when discussing https://github.com/ballerina-platform/ballerina-spec/issues/724. The conclusion was to the compiler will adhere to the spec. We have created this issue to track in the spec side https://github.com/ballerina-platform/ballerina-spec/issues/738. Once the design is finalized we will add this support for the compiler.  Hence closing this issue.
