### ISSUE TITLE
TimeAccumulatingWindow test failing intermittently

### ISSUE THREAD

**Issue by LahiruJayasekara** [ballerina-platform/ballerina-lang#13271]
**Description:**
`testTimeAccumulatingQuery` test case in BallerinaStreamsV2TimeAccumulatingWindowTest fails intermittently in travis build.

**Affected Versions:**
0.990.2

**Suggested Assignees (optional):**
@mohanvive , @gimantha , @grainier

**Comment by Shan1024** [comment]
Reopening since this issue has occurred in https://github.com/ballerina-platform/ballerina-lang/pull/14576.

Complete log - [log-testTimeAccumulatingQuery.txt](https://github.com/ballerina-platform/ballerina-lang/files/2998960/log-testTimeAccumulatingQuery.txt)

**Comment by gimantha** [comment]
We are in the process of removing MB subscriptions from streams. Till then we will disable this test.
