### ISSUE TITLE
[Task] Formatting tool implementation

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#13280]
**List of Tasks**
- [x] Look in to implementation's code coverage decrease by 0.01% due to BVM path coverage issue
- [x] Formatting guideline https://github.com/ballerina-platform/ballerina-lang/issues/13862
- [x] Write spec for  the formatter.
- [x] Currently formatting support is added only for around 41 constructs in ballerina syntaxes. This issue is created to track the progress of the support impl for rest of the syntaxes. Find the list of nodes supported and yet to support in [this doc](https://docs.google.com/spreadsheets/d/1_Lom_9Py96NxKcplTbJOIOWqYmp1WnNvSPJw0T-Hzoc/edit?usp=sharing).
- [x] As initial impl is in Language server it is not possible for CLI users to use fomatter to format 
  their ballerina files. Hence pack the formatter as a Ballerina extension. - https://github.com/ballerina-platform/ballerina-lang/pull/15664

**Comment by kaviththiranga** [comment]
Meeting notes: 02.15.2019
Participants: @hevayo @NipunaMarcus @pahans @imesh @roonyh @rasika @kaviththiranga @NipunaRanasinghe 

reviewed the doc: https://github.com/ballerina-platform/ballerina-lang/blob/master/docs/style-guide.md

- get the doc in current state published to ballerina.io
- provide a cli tool for formatting (refer it from site)
- point 1 in doc: top level nodes : replace "indent with empty spaces" with "do not indent"
- do we need to reason out our decisions on formatting? 
- point 3 in doc: replace "Column" with "Characters"
- rethink on content structure in document

**Comment by nadeeshaan** [comment]
A couple of suggestions regarding the current Documentation

- Add `:` and `!..` under the specific characters
- Let's add an example case for ternary operator
