### ISSUE TITLE
[Spec Deviation] Object fields should not be able to be declared with default values

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13341]
**Description:**
As per the spec (v0.990:2019-01-16), object fields should not be able to declared with default values.
```ballerina
type NormalObjectBroken object {
    string fieldOne = "string value"; // Should fail at compile time
};
```
Any field not initialized within the __init() method of an object should take its implicit initial value.

**Affected Versions:**
0.990.2

**Comment by hasithaa** [comment]
2019R3 Spec allows object fields with default values. 
```
object-field-descriptor :=
   object-visibility-qual type-descriptor field-name [default-value];
```
