### ISSUE TITLE
Cannot get the string representation of `null`

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13384]
Consider the following function:
```ballerina
function testNullStringRepresentation() returns string|error {
    json j = null;
    return string.convert(j);
}
```
During run time, `()` is returned by the above function. The issue is with the following conditional check:
https://github.com/ballerina-platform/ballerina-lang/blob/3549d3205dcf15518c4fe9d86737e29fe1cd67ff/bvm/ballerina-core/src/main/java/org/ballerinalang/bre/bvm/BVM.java#L1142

This basically special cases `null`. But it shouldn't be in this case and should be considered for conversions.

**Comment by pubudu91** [comment]
This also applies to `io:sprintf()` function. 
```ballerina
function testNullStringRepresentation2() returns string {
    json j = null;
    return io:sprintf("%s", j);
}
```

**Comment by Kishanthan** [comment]
Fixed in jBallerina

```ballerina
import ballerina/io;
  
public function main(string... args) {
    string a = testNullStringRepresentation();
    io:println(a);
}

function testNullStringRepresentation() returns string {
    json j = null;
    return j.toString();
}

```
