### ISSUE TITLE
variable reference breaks swagger export

### ISSUE THREAD

**Issue by gregito** [ballerina-platform/ballerina-lang#13396]
if the ResourceConfig contains a variable reference instead of string literal, then the swagger export breaks with the following error:
`error: Error occurred when exporting swagger file for service file at date_service.bal. org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangLiteral.`

For example, **this breaks the swagger generate**:

const string APPLICATION_JSON = "application/json";
@http:ResourceConfig {
        methods: ["GET"],
        path: "/time",
        produces: [APPLICATION_JSON]
    }

**but this isn't:**

@http:ResourceConfig {
        methods: ["GET"],
        path: "/time",
        produces: ["application/json"]
    }

**Comment by NipunaMarcus** [comment]
Currently, in compile time, OpenAPI tools extract data from the annotations available for services and resources. But when annotations attributes are initialized with values passed using variable reference it is hard to know what is the value provided by the variable reference as these values are not available in compile time and available only in run time. 

To avoid this problem for now what we can do is provide the literal value to the attribute so OpenAPI tool can easily extract the details from annotations.

**Comment by NipunaMarcus** [comment]
As we revisited the design of the OpenAPI tooling and the annotation structure, which you can refer from specification available here, we fixed this issue by allowing only literal values in place where literals are allowed. We are closing this issue and attaching it to the new issue to track the progress and for evaluation purposes.
