### ISSUE TITLE
Code completion - Imported types unavailable for initializations with access modifiers 

### ISSUE THREAD

**Issue by Minoli** [ballerina-platform/ballerina-lang#13438]
**Description:**
$title

Without access modifier

<img width="549" alt="screen shot 2019-02-01 at 12 56 40 pm" src="https://user-images.githubusercontent.com/9837443/52108856-7037eb80-2621-11e9-8670-a4027744f369.png">

With access modifier

<img width="335" alt="screen shot 2019-02-01 at 1 03 40 pm" src="https://user-images.githubusercontent.com/9837443/52108952-d3298280-2621-11e9-9082-6e77de48c0ab.png">

**Affected Versions:**
Ballerina 0.990.3-SNAPSHOT

**Comment by nadeeshaan** [comment]
Closing since the use case is invalid according to the latest language spec.
