### ISSUE TITLE
Missing a comma when adding multi method resource using API Designer

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#13433]
**Description:**
When Adding a multi method resource using the api designer, the comma is missed in the updated source hence a syntax error is displayed.

**Steps to reproduce:**
- Click on add resource
- Type an existing name as resource name
- select all of the available methods and add
- check updated source code **MultiResourceInfo**

**Affected Versions:**
v.990.3

**OS, DB, other environment details and versions:**
MacOS Mojave

**Comment by kaviththiranga** [comment]
@DimalChandrasiri is this fixed in v0.991.0?

**Comment by DimalChandrasiri** [comment]
This issue is fixed in 0.991.0
