### ISSUE TITLE
Suggestions are not displayed after adding the first attribute in record creation

### ISSUE THREAD

**Issue by Minoli** [ballerina-platform/ballerina-lang#13434]
**Description:**
$title
<img width="478" alt="screen shot 2019-02-01 at 12 29 26 pm" src="https://user-images.githubusercontent.com/9837443/52108361-b3915a80-261f-11e9-9d81-d742f51af50e.png">

**Affected Versions:**
Ballerina 0.990.3-SNAPSHOT

**Comment by nadeeshaan** [comment]
Closing since this issue has been fixed v1.0.0 onwards
