### ISSUE TITLE
[gRPC] Generated code contains duplicate Empty record types

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#13432]
**Description:**
Generated ballerina source code contains duplicate record types causes compilation issue when building . Please eliminate generating duplicate record types. 
```proto
service aaa {
    rpc SendResponse (Response) returns (Empty) {}

}

message Empty {
}
```

**Affected Versions:**
0.990.3

**Comment by daneshk** [comment]
Fixed.

**Comment by BuddhiWathsala** [comment]
Still has the same issue. When we generate gRPC Ballerina files from a protobuf file where the protobuf file has two separate services that access `google.protobuf.Empty` data type, then the generated Ballerina file contained unwanted `Empty` records repetitively.

**Steps to reproduce:**

Generate Ballerina files using the following protobuf file. 

```proto
syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

service Handshake {
    rpc publishProgram (google.protobuf.StringValue) returns (google.protobuf.Empty);
    rpc linkApplication (google.protobuf.StringValue) returns (google.protobuf.Empty);
}
```

Use the following command to generate Ballerina files.

```sh
$ ballerina grpc --input sample.proto --output .
```

It will return the following Ballerina file that contains two Empty records.

```ballerina
import ballerina/grpc;

public type HandshakeBlockingClient client object {
    .....
};

public type HandshakeClient client object {
    .....
};

public type Empty record {|
    
|};


public type Empty record {|
    
|};
```

**Affected Versions:**
Ballerina 1.2.0-rc1
