### ISSUE TITLE
VSCode fails to parse @kubernetes:ConfigMap when the file path is relative

### ISSUE THREAD

**Issue by nirmal070125** [ballerina-platform/ballerina-lang#13444]
**Description:**

I'm trying k8s sample https://github.com/ballerina-guides/ballerina-demo/blob/master/5_demo_kubernetes.bal. When I open it up in VS Code getting an error "unable to read the content of the twitter.toml". But the project builds and runs from cmd line issue seems to be due to 
```
@kubernetes:ConfigMap{
ballerinaConf: "twitter.toml"
}
```

**Steps to reproduce:**
Check the description.

**Affected Versions:**
0.990.2

**OS, DB, other environment details and versions:**
OS X

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
This is an issue with k8s module so removing vscode plugin label.

**Comment by hemikak** [comment]
This is fixed in ballerinax/kubernetes module. Refer https://github.com/ballerinax/kubernetes/pull/282
