### ISSUE TITLE
Ballerina build command with tests fails for multiple modules

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#13464]
**Description:**
Consider the same project and source content as mentioned in #13460 
When the _**ballerina build**_ command executed without skipping tests then the build fails with the following error log.

```
Compiling source
    demo/pkg1:0.0.1
    demo/pkg2:0.0.1
error: failed to compile file: null
```

**Affected Versions:**
v0.992.0 at least

**Related Issues**
#13460

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced with latest master. Hence closing this issue.
