### ISSUE TITLE
Ballerina support for Secured Service With OAuth2

### ISSUE THREAD

**Issue by chewapathiranamitrai** [ballerina-platform/ballerina-lang#13486]
**Description:**
Ballerina user guide only provides implementing Secured Service With JWT and with Basic Auth.  Can OAuth2 also be considered when implementing services

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayomawdb** [comment]
This is a duplicate of issue #10474

@djkevincr Please note (since this has been self-assigned)

**Comment by ayomawdb** [comment]
@chewapathiranamitrai Thank you for reporting this. Please note that this is already tracked with #10474.
