### ISSUE TITLE
[gRPC] bidirectional example test fails intermittently

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#13483]
**Description:**
Running tests
    ballerina-examples/grpc-bidirectional-streaming:0.0.1
[ballerina/grpc] started HTTP/WS endpoint 0.0.0.0:9090
Initialized connection sucessfully.

2019-02-06 08:43:50,041 INFO  [ballerina-examples/grpc-bidirectional-streaming] - 982942240 connected to chat 
2019-02-06 08:43:50,046 INFO  [ballerina-examples/grpc-bidirectional-streaming] - Server received message: Sam: Hi 

	[fail] testBidiStreamingService:
	    error: Server message didn't receive.: expected 'true' but found 'false' {}
	    	at ballerina/test:createBallerinaError(assert.bal:42)
	    	ballerina/test:assertEquals(assert.bal:83)
	    	ballerina-examples/grpc-bidirectional-streaming:0.0.1:testBidiStreamingService(tests/grpc_bidirectional_streaming_test.bal:42)

	0 passing
	1 failing
	0 skipped

**Comment by daneshk** [comment]
Closing this issue, this is fixed in master. please reopen if you encounter this issue again

**Comment by Shan1024** [comment]
Reopening this since the issue has been encountered multiple times.

```
	[fail] testBidiStreamingService:
	    error: Server message didn't receive.: expected 'true' but found 'false' {}
	    	at ballerina/test:createBallerinaError(assert.bal:42)
	    	ballerina/test:assertEquals(assert.bal:83)
	    	ballerina-examples/grpc-bidirectional-streaming:0.0.1:testBidiStreamingService(tests/grpc_bidirectional_streaming_test.bal:42)

```

**Comment by Shan1024** [comment]
@daneshk - This is now failing more frequently. Can we make this a high priority?

https://api.travis-ci.org/v3/job/498256888/log.txt
https://api.travis-ci.org/v3/job/498014860/log.txt
