### ISSUE TITLE
ClientInitializationFailureTest.testClientEndpointFailureInResource test fails intermittently

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#13487]
**Description:**
This is disabled at the moment.

Please find the build error below.

java.lang.AssertionError: expected object to not be null at org.ballerinalang.test.service.websocket.ClientInitializationFailureTest.testClientEndpointFailureInResource(ClientInitializationFailureTest.java:54)

**Comment by NatashaWso2** [comment]
This is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/13338, hence closing this issue.
