### ISSUE TITLE
The test grpc.sample.BidiStreamingTestCase.testBidiStreamingClient fails intermittently 

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#13485]
**Description:**
Please find the error below.

java.lang.AssertionError: expected [Success: received valid responses from server] but found [Failed: invaild response from server] at org.ballerinalang.test.service.grpc.sample.BidiStreamingTestCase.testBidiStreamingClient(BidiStreamingTestCase.java:55)

**Comment by daneshk** [comment]
Closing this issue, this is fixed in master with PR #13500. please reopen if you encounter this issue again
