### ISSUE TITLE
AESCipherToolNegativeTest.testEncryptionAndDecryptionWithTwoCipherTools fails intermittently

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#13495]
**Description:**
Error:
"[ERROR] testEncryptionAndDecryptionWithTwoCipherTools(org.ballerinalang.stdlib.config.AESCipherToolNegativeTest)  Time elapsed: 0.503 s  <<< FAILURE!
java.lang.AssertionError: Should throw an error expected [true] but found [false]
	at org.ballerinalang.stdlib.config.AESCipherToolNegativeTest.testEncryptionAndDecryptionWithTwoCipherTools(AESCipherToolNegativeTest.java:43)"

**Comment by vinok88** [comment]
There seems to be no issue with this test case. I could reproduce the intermittent behavior by running the test within a loop (100). Look like there is a bug in the cipher tool.

**Comment by ldclakmal** [comment]
The reason for the issue is that we expect the test case should throw an exception since the decryption key is invalid. But in some cases, the given decryption key is able to decrypt the given encrypted string with the use of padding. But the output (decrypted text) does not match with the plain text. Therefore in the test case, no exception is thrown and assertion gets failed.

**Comment by vinok88** [comment]
@ldclakmal, you mean decryption key matches intermittently? Then that's a huge security issue. Correct me if I'm wrong.

**Comment by ldclakmal** [comment]
@vinok88 Decryption key does not match with encryption key intermittently. What happens is that the decryption key may end up in a key that the encoded byte array can be decrypted properly. But the result never matches with the original plain text.
In the test cases, it expected an exception each and every time. But in some cases, the exception does not occur. That is the reason why the test was failed intermittently. So, if the exception does not occur, the decrypted plain text should not be matched with the original plain text.
