### ISSUE TITLE
VSCode main function snippet suggestion is getting appear, when there is a main function already in the module.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#13508]
**Description:**
$Subject.

**Steps to reproduce:**
- Create a new bal file.
- Create a main function in the project. 
- Now try to create another main function using by typing "pu". It will suggest "public main function" again.

**Affected Versions:**
0.990.3

**Suggestions**
- One option is to don't show that when we already have the main function in the module.

**Comment by nadeeshaan** [comment]
This behaviour is expected and when the snippet added user will be notified with diagnostics
