### ISSUE TITLE
Allow having union type fields for record types as the constraints of tables returned from data client operations

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#13503]
**Description:**
```ballerina
// This is not supported
type Result record {
    int|float value;
}
```
Currently, a field of a record that is used as a constraint of a table returned from a data client operation cannot have the member count greater than 2 and when it is equal to two one member must be nil.

But the language type system suggests this is allowed and one might intuitively think it is supported.

**Comment by daneshk** [comment]
@niveathika please check whether this is still valid with the new design

**Comment by niveathika** [comment]
@daneshk Union types for columns is already addressed in the new design.
