### ISSUE TITLE
VSCode Improve content suggestions based on context.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#13512]
**Description:**

**Steps to reproduce:**
- See the attached image. 
![image](https://user-images.githubusercontent.com/1356214/52402187-a2e25800-2ae9-11e9-973f-fe6a27553b1b.png)
- Idealy it should suggest "new"
- Same problem can be applicable for other types such as record, array, error etc. 

**Affected Versions:**
0.990.3

**Comment by hasithaa** [comment]
Found that same problem appears in type-guars as well.

**Comment by nadeeshaan** [comment]
Fixed with #15789 and hence resolving the issues
