### ISSUE TITLE
[VSCode] `returns` keyword of the function doesn't suggest in VSCode

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#13515]
**Description:**
`returns` keyword of the function doesn't suggest in VSCode. Please check the attached screenshot.
<img width="921" alt="screen shot 2019-02-07 at 2 56 54 pm" src="https://user-images.githubusercontent.com/8402398/52408615-3ec79000-2af9-11e9-8f4f-7a0af91c5029.png">

**Comment by nadeeshaan** [comment]
Fix has been merged and shipped with v1.0.0
