### ISSUE TITLE
VSCode doesn't support gRPC service snippet

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#13514]
**Description:**
Current VSCode suggest snippet for http, websocket and websub. grpc snippet doesn't support yet. Please check attached screenshot below.

<img width="628" alt="screen shot 2019-02-07 at 4 48 09 pm" src="https://user-images.githubusercontent.com/8402398/52408197-59e5d000-2af8-11e9-87f1-e6cba3a9399e.png">

Shall we add gRPC snippet in VSCode.

**Comment by hevayo** [comment]
@daneshk can you specify what should be added as the snippet.

**Comment by daneshk** [comment]
@hevayo Please find the sample snippet below. Please let me know whether it ok

```bal
import ballerina/grpc;

service {{serviceName}} on new grpc:Listener(8080) {
    resource function {{newResource}}(grpc:Caller caller, {{inputType}} request) {
        
    }
}
```

**Comment by rasika** [comment]
@daneshk Thanks for the sample snippet. Will add this!
