### ISSUE TITLE
.convert() suggestion in VScode add extra semicolon

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#13523]
**Description:**
The suggestion should add only the `.convert()` part. It adds `.convert();`. This does not happen for other methods.
[convert_bug.zip](https://github.com/ballerina-platform/ballerina-lang/files/2844220/convert_bug.zip)

**Steps to reproduce:**
Please refer attached video.
**Affected Versions:**
0.990.3
**OS, DB, other environment details and versions:**
MacOS highSierra
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master, hence resolving the issue
