### ISSUE TITLE
Testerina - Hide passed test cases by default from printing to stdout. 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#13538]
**Description:**
Right now it shows all the passed test cases into the stdout. This list becomes annoying when a project has a large set of test cases. (See spec-conformance tests.)

Showing only the failed test names and passed count is sufficient. We can give the debug option if a user wants to see only passed test cases.

**Comment by NatashaWso2** [comment]
Closing this issue since it has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/13851
