### ISSUE TITLE
Revamp Language server compiler package cache

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#13530]
**Description:**
Revamp the language server internal package cache

**Affected Versions:**
v0.990.2 at least

**Comment by rasika** [comment]
Progress can be tracked in following branch [lscompiler-cache](https://github.com/ballerina-platform/ballerina-lang/tree/lscompiler-cache).

**Comment by nadeeshaan** [comment]
No longer valid, hence closing
