### ISSUE TITLE
Function invocation expand/collapse support for diagram

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13546]
Ability to visualize a function implementation (an embedded diagram) from where it's being invoked.

- [x] Add a method to extended lang client to get the sub tree of the called 
function
  - Use textdocument/definition LS request to fine function definition
  - Use extended language client's getAST method to compile the containing ballerina file into an AST

- [x] Render the AST sub tree of the function
- [x] Add a frame around the expanded function
- [x] Add expander and collapser
  - Decide on proper UX for expanding and collapsing icons
    - Can add an icon after the statement text
    - Can add a popup to the right of statement (using semantic)
- [x] Fix rendering return statements of expanded functions
- [x] Render workers and endpoints in expanded functions properly
- [x] Render actions to endpoints that are passed through parameters properly
- [x] Avoid allowing editting inside expanded functions

**Comment by roonyh** [comment]
Resolved by #14550
