### ISSUE TITLE
API docs design revamp

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13548]
This is an effort to improve the API documentation of ballerina. 

### Fixes for current Doc Generation
- [x] Fix construct categories (eg:Client , Errors)
- [x] improve TOC structure 
       - make categories prominent

### Improve Doc Generation
- [x] Come up with a [spec](https://docs.google.com/document/d/1eyiduNRrUtqoL_e9AksM8B3ClRW0T-RzTrH_qwJZZjU/edit?usp=sharing) on what to expect with docs
- [ ] Study [Docusaurus](https://docusaurus.io/) markdown format for adaptability.
- [ ] Generate MD before generating the actual HTML documents.

### Improve Navigation in API Docs
- [x] Make top level categories in the left hand menu prominent
- [x] Separate constructs based on their type.

**Comment by kaviththiranga** [comment]
Spec will be drafted at https://docs.google.com/document/d/1eyiduNRrUtqoL_e9AksM8B3ClRW0T-RzTrH_qwJZZjU/edit?usp=sharing

**Comment by kaviththiranga** [comment]
Reopening as there are more subtasks left - this was closed automatically due to PR comment.

**Comment by hevayo** [comment]
outdated
