### ISSUE TITLE
VSCode extension: Usability test

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13541]
A testing round with each member trying out developing a BBG from start to end. Find and report issues related language server, diagram and extension it self.

- [x] Test with Tooling team
- [x] Review identified issues
- [x] list possible improvements

**Comment by kaviththiranga** [comment]
Here is a list all issues found during the testing rount

**Comment by nadeeshaan** [comment]
Closing the issue since the task has been completed
