### ISSUE TITLE
Having two forever statements shows a semantic error

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#13554]
**Description:**
Having two forever nodes in the same file shows a semantic error `redeclared import module 'ballerina/streams'` 

![ezgif com-video-to-gif 11](https://user-images.githubusercontent.com/9109762/52548377-5e113680-2df3-11e9-92e8-ff261f19e247.gif)

**Affected Versions:**
0.990.2

**Comment by gimantha** [comment]
Compiler should show an error if two forever blocks are in the same function, because the forever block should be the last statement in a function. Issue above is fixed with #17675.
