### ISSUE TITLE
Debugger support for JBallerina

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13566]
Improve current debugger to support JBallerina implementation
- [ ] [DAP implementation](https://docs.google.com/document/d/1eMr0DOWblZbdlAaoA_V4JWtXuhBCVLoYcqRKKQ6fonQ/edit#heading=h.454ad9iy8g1q)
    - [ ] implement global variables for jBallerina
    - [ ] Add integration tests for debug adapter
    - [x] Add support for remote debugging 
    - [ ] implement strands - threads mapping, Fix services debug (https://github.com/ballerina-platform/ballerina-lang/issues/18427)
    - [x] Support json object values
    - [ ] Support xml values
    - [x] Add debugging support for `ballerina test`
    - [x] Filter out internal variables
    - [x] Fix issue https://github.com/ballerina-platform/ballerina-lang/issues/17476 (need to verify fix)
    - [x] Add integration tests
    - [x] Support json arrays
    - [x] Support Object type
    - [x] Fix debugger not working when breakpoints added to comments
    - [x] filter out unnecessary messages from ballerina launcher
    - [x] dynamically select a port when launching 
    - [x] add breakpoints during a debug session
    - [x] Add loggers
    - [x] sort Array index in variables
    - [x] Implement DAP server as a standalone app initially 
    - [x] Stepin, stepout, continue
    - [x] implement variables for DAP
    - [x] implement local variables for jBallerina
    - [x] fix multiple file breakpoints
    - [x] debugging for ballerina packages
    - [x] fix jballerina run 
       - [x] Fix address already in use issue
       - [x] Run single file
       - [x] Run modules 
       - [x] Run ballerina tests
       - [x] enable network logs
       - [x] Fix services debug
       - [x] Ballerina main debug
- [x] Migrate VSCode to use DAP

- [x] IntelliJ DAP client implementation

**Comment by nadeeshaan** [comment]
Closing since the task has been completed
