### ISSUE TITLE
Improve print representation of arrays with trailing nil elements

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#13576]
**Description:**
Consider following:
```ballerina
string?[5] a1 = ["a", "b", (), (), ()];
io:println(a1);
```

At the moment this prints: ["a", "b", (), (), ()] (after https://github.com/ballerina-platform/ballerina-lang/pull/13294)

But this should ideally print: ["a", "b", ...] as per [discussion here](https://groups.google.com/forum/#!msg/ballerina-dev/4QEGRga-nT4/7L2V1JfnAgAJ).

**Comment by MaryamZi** [comment]
`io:println(a1);` prints the result of `a1.toString()` which is defined in the spec now.

The output for
```ballerina
import ballerina/io;

public function main() {
    string?[5] a1 = ["a", "b", (), (), ()];
    io:println(a1);
    io:println(a1.toString());
    io:println(a1.toBalString());
}
```
is now
```
["a","b",null,null,null]
["a","b",null,null,null]
["a","b",(),(),()]
```
