### ISSUE TITLE
Unclear Error Message when Ballerina Package cannot be extracted

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#13580]
**Description:**
When I try to build a Ballerina application using the following command

ballerina build HelloService.bal

I get the following error thrown.

"error loading balo null"

This error was thrown because my Ballerina application (HelloService.bal) had custom package called utils which was located in the following path.

/usr/lib/ballerina/ballerina-0.990.2/lib/repo/wso2/utils/0.0.0/utils.zip

When debugging we found that the error is thrown because the zip file cannot be read by the ZipConverter class due to permission issue.
I believe there should be better error description so that we can find the cause for this issue easily.

**Steps to reproduce:**
Develop a custom Ballerina package. Deploy its zip file in the following path "/usr/lib/ballerina/ballerina-<version-number>/lib/repo". Then develop a Ballerina application (e.g., HelloService.bal ) which uses the custom package. Next, change the permission level of the zip file. Next, if you run the command ballerina build HelloService.bal you should get the above mentioned error.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by parkavi11** [comment]
This issue is no longer relevant with the current code base, hence closing.
