### ISSUE TITLE
Function declared within a Ballerina endpoint does not get executed

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#13598]
**Description:**
Function declared within a Ballerina endpoint does not get executed. The application execution hangs at the line of the function call.

**Steps to reproduce:**
Run the following Ballerina endpoint (BuggyService.bal) with the following command

ballerina run BuggyService.bal

```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/io;
import ballerina/config;

listener http:Listener helloWorldEP = new(9090);

@http:ServiceConfig { basePath:"/" }
service helloWorld on helloWorldEP {
    public function foo() {
            io:println("AAAAAAAAAAAAAAAAAAA");
    }

   @http:ResourceConfig {
        methods:["GET"],
        path:"/"
    }
   resource function sayHello(http:Caller caller, http:Request req, string name, string message) {
       foo();
       self.foo();
   }
}

public function foo() {
        io:println("BBBBBBBBBBBBBBBBBBBB");
}
```

Then you should see an output as follows on the application console.

Initiating service(s) in 'BuggyService.bal'
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:9090
BBBBBBBBBBBBBBBBBBBB

**Affected Versions:**
I have tested this with Ballerina 0.990.2

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Comment by MaryamZi** [comment]
Tested with the current master and observed the following output for `curl http://localhost:9090`

```cmd
$ ballerina run err_test.bal
Initiating service(s) in 'err_test.bal'
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:9090
BBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAA
```

Closing this issue since it is resolved on the current master, and will be fixed in the next release.
