### ISSUE TITLE
Issue in inferring the type of a nested ternary expression

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13601]
Consider the following ternary expression where `j` is a `json`.
```ballerina
string? s = (j.location == null ? () : <string>j.location) == null ? null : null;
```
Here, the type of the nested ternary expression cannot be inferred since the expressions given for the then and else branches are of two incompatible types. Therefore a compile error is given for it saying `incompatible types: expected '()', found 'string'`. 

We need to decide on whether to either,
1) Disallow it (i.e., the current behaviour). If disallowing, need to give a better error than saying "incompatible types". The current behaviour is to allow it if either of the two types is assignable to the other type. 
2) Infer the type using the types of both branches. e.g., for the above case, the type of the expression will be `string?`.

**Comment by hasithaa** [comment]
Fixed in SL.
