### ISSUE TITLE
Improve filler value check w.r.t. finite types

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13612]
**Description:**
Consider the following two unions:
```ballerina
const decimal ZERO = 0.0;
const decimal ONE_TWO = 1.2;
const decimal TWO_THREE = 2.3;

type DEC ZERO|ONE_TWO|TWO_THREE;

function testFiniteTypeArrayFill5(int index) returns DEC[] {
    DEC value = 1.2;
    DEC[] ar = [];
    ar[index] = value;
    return ar;
}
```
and
```ballerina
type LiteralsAndType 1|2|int;

function testUnionArrayFill4(int index) returns LiteralsAndType[] {
    LiteralsAndType value = 1;
    LiteralsAndType[] ar = [];
    ar[index] = value;
    return ar;
}
```
Both of the above cases result in compile errors saying there's no implicit initial value for the type. However, these actually do have implicit initial values. The check for implicit initial values need to be improved to consider finite types defined using constants and union types which have finite type constituents.

**Comment by MaryamZi** [comment]
This is still valid after the change to panic at runtime if the list does not have a filler value - now fails at runtime.

**Comment by vinok88** [comment]
@MaryamZi, @pubudu91 I'm trying to understand the issue here, 
With regard to the first example, what is the filler value should be?
How do we identify a filler value in such cases?
