### ISSUE TITLE
Number representation limit in json payload

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#13614]
**Description:**
It seems that when a number inside a json is a big value, getJsonPayload() method does not work properly. But when I print the request payload as a string, the value is there.

**Payload :** 

```
{
    "students": {
        "studentlist": {
                "Name": "Alice",
                "Id": 10000000000000000000000
            }
    }
}
```

**Code :** 
```
        json jsonpayload;

        io:println(req.getPayloadAsString());

        if (contentHeader == "application/json") {
            jsonpayload = <json> req.getJsonPayload();
            io:println(jsonpayload);

            if (jsonpayload.students.studentlist.Name == null) {
                responseJson = { "status": "error" };
            } else {
                responseJson = { "name" : jsonpayload.students.studentlist.Name,
                    "Age" : jsonpayload.students.studentlist.Id,
                    "status" : "accepted"};
            }


        }
```
**Terminal Output :** 

```
{"students":{"studentlist":{"Name":"Alice", "Age":100000000000000000}}}
error: {ballerina}TypeAssertionError {"message":"assertion error: expected 'json', found 'error'"}
{
	at echojson(SampleEP.bal:22)
    "students": {
        "studentlist": {
                "Name": "Alice",
                "Age": 10000000000000000000000
            }
    }
}
```

**Steps to reproduce:**
Follow the above code

**Affected Versions:**
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
That number is out of range of integers. So when you try to parse the string representation to JSON, it will try to convert that number to an integer, and will get the error. So the current behavior is correct. 

But may be we could improve the error message.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
