### ISSUE TITLE
[Spec Deviation] Named arguments need to be specified with ":", and not "="

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#13617]
**Description:**
As per the "Function call expression" section of the spec, named arguments to functions need to be specified with ":", and not "=" as with the current implementation.

```
function-call-expr := function-reference ( arg-list )
function-reference := variable-reference
arg-list :=
   [ individual-arg-list [, rest-arg]]
   | rest-arg
individual-arg-list := individual-arg (, individual-arg)*
individual-arg := [arg-name :] expression
arg-name := identifier
rest-arg := ... expression
```

Note "individual-arg := **[arg-name :]** expression"

**Affected Versions:**
0.990.3

**Comment by hasithaa** [comment]
@NatashaWso2 @MaryamZi 
This has been reverted back to "=". Hence closing this issue.
