### ISSUE TITLE
BallerinaStreamsV2HoppingWindowTest.testHoppingWindowQuery fails intermittently

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13613]
**Description:**
```
[ERROR] testHoppingWindowQuery1(org.ballerinalang.stdlib.streams.BallerinaStreamsV2HoppingWindowTest)  Time elapsed: 6.366 s  <<< FAILURE!
java.lang.AssertionError: Expected events are not received expected [2] but found [1]
	at org.ballerinalang.stdlib.streams.BallerinaStreamsV2HoppingWindowTest.testHoppingWindowQuery1(BallerinaStreamsV2HoppingWindowTest.java:51)
```

**Comment by MaryamZi** [comment]
Reopening since this failed on Travis again - https://api.travis-ci.org/v3/job/507758432/log.txt

**Comment by NipunaMarcus** [comment]
There is another failure in this test suit. it fails for BallerinaStreamsV2HoppingWindowTest.testHoppingWindowQuery3
https://api.travis-ci.org/v3/job/508786450/log.txt

**Comment by gimantha** [comment]
@NipunaMarcus Hi,
We are in the process of removing MB implementation and replace it with a simple queue implementation. With this change we hope, that the intermittent test failures in streams will be resolved. Till then we will disable this test.

**Comment by gimantha** [comment]
Please open if the test fails again. This has been fix with the MB fix
