### ISSUE TITLE
Introduce meaningful sub types to BType category in suggestions 

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13621]
For example, for http module, suggestions only have two categories - function & BType. 
<img width="920" alt="screen shot 2019-02-15 at 1 39 13 pm" src="https://user-images.githubusercontent.com/1505855/52843122-270a9000-3127-11e9-81d5-f8451ffae8a4.png">

But it (```http:Request```)is actually an Object. Similarly we should categorize them in align with language spec and api docs. For example, functions, records, objects, primitives, etc.

**Comment by NipunaMarcus** [comment]
+1 for adding more descriptive kinds ...
