### ISSUE TITLE
[HTTP/2] TPS is lower in HTTP/2 than HTTP/1.1 for passthrough scenario

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-lang#13705]
$subject can be observed in all concurrency levels(100, 300, 1000)

Perf Results >> https://docs.google.com/spreadsheets/d/1KfMXPbXbWIGbRNY4gtljRRIRqabhdUs8DHRLVaCM52k/edit?usp=sharing

**Comment by arukshani** [comment]
According to the AWS results https://github.com/ballerina-platform/ballerina-lang/blob/performance-test-162-2019-03-18_10-05-56/performance/benchmarks/summary.md, @subject is no longer true, hence closing.

![image](https://user-images.githubusercontent.com/12377918/54583405-08572c00-4a3a-11e9-8eb3-d39aece8fb14.png)

**Comment by arukshani** [comment]
According to the AWS results https://github.com/ballerina-platform/ballerina-lang/blob/performance-test-162-2019-03-18_10-05-56/performance/benchmarks/summary.md, @subject is no longer true hence closing.

![image](https://user-images.githubusercontent.com/12377918/54583405-08572c00-4a3a-11e9-8eb3-d39aece8fb14.png)

**Comment by ldclakmal** [comment]
The issue is fixed with [1] and the latest test results can be found at [2].

[1] https://github.com/wso2/transport-http/pull/308
[2] https://github.com/ballerina-platform/ballerina-lang/blob/performance-test-162-2019-03-18_10-05-56/performance/benchmarks/summary.md
