### ISSUE TITLE
Cannot get the typedesc of ()

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13726]
Consider the following program:
```ballerina
public function main(string... args) {
        typedesc t = ();
}
```
The above program gives the following compile error:
```
error: .::test.bal:2:15: incompatible types: expected 'typedesc', found '()'
```
Since we use `()` for the type of nil as well, we need to handle the above case.

**Comment by hasithaa** [comment]
This seems like a not a bug. Way to get typedesc of nil value is

```ballerina
public function main() {
        typedesc tt = typeof ();
}
```
