### ISSUE TITLE
Syntax highlighting broken for top level record variable initialization

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13729]
**Description:**
Syntax highlighting is not appearing for top level record variable initialization

![image](https://user-images.githubusercontent.com/10986966/53077608-57cc3a00-3518-11e9-98ac-387ce9e4507f.png)

```
import ballerina/http;

http:AuthProvider basicAuthProvider = {
    scheme: "basic",
    id: "basic1",
    authStoreProvider: "config"
};

http:ServiceSecureSocket secureSocket = {
    keyStore: {
        path: "${ballerina.home}/bre/security/ballerinaKeystore.p12",
        password: "ballerina"
    }  
};
```

**Sample**
https://github.com/ballerina-guides/api-gateway/blob/master/guide/api_gateway_service/order_service.bal

**Comment by hevayo** [comment]
fixed in latest master
