### ISSUE TITLE
[Spec Deviation] No way to get the implicit initial value of an object

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#13728]
Currently there is no way to provide the implicit initial value of an object since that requires running the initializer of the the object. After an offline discussion, decided to leave this for now.

**Comment by MaryamZi** [comment]
This is now possible with the jBallerina implementation and was fixed for `getZeroValue()` with https://github.com/ballerina-platform/ballerina-lang/pull/16509
