### ISSUE TITLE
Formatting Issue in Mock Ballerina Service Creation from Swagger

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#13723]
When creating mock services from a Swagger file, the generated return statements' indentation is done using tabs, rather than spaces. This looks mid-aligned in some text editors, due to the varying space count for tabs. It's better to fix it to use spaces in all the places.

**Comment by NipunaMarcus** [comment]
Closing this as we are revamping the OpenAPI CLI tools to a new design and this issue will be attached to the new issue to track and evaluate during the development.
