### ISSUE TITLE
[Diagram] An empty function should not have a request and response arrows

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13720]
**Description:**
An empty function should not have a request and response arrows

![image](https://user-images.githubusercontent.com/10986966/53070612-bf2cbe80-3505-11e9-9f04-8e215a1bada5.png)

**Steps to reproduce:**
Add a function from the source view or Diagram 
 - Function appearing in the diagram contains request and response arrows

**Suggested Labels (optional):**
Component/Diagram,
Component/VScode Plugin,
Type/Bug

**Comment by kaviththiranga** [comment]
I had a discussion with @hasithaa on this.
In runtime, when we call an empty function, new stack is created and gets returned immediately. 
Hence the current representation mimics how an empty function behaves in runtime.

**Comment by kaviththiranga** [comment]
Closing as per the above comment.
