### ISSUE TITLE
No suggestions for grpc:INTERNAL for caller->sendError 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13744]
**Description:**
Auto suggestion for grpc:INTERNAL for caller->sendError is not appearing

![image](https://user-images.githubusercontent.com/10986966/53155542-4ac84d00-35e3-11e9-898a-2d7834f7e3ba.png)

**Comment by nadeeshaan** [comment]
Duplicate of #13787
