### ISSUE TITLE
Ignore return code, and Assign to a var action feature needed

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13759]
**Description:**
Ignore return code, and Assign to a var action feature needed

"create a new local variable" whenever a function returns a variable(compiler shouts when you don't assign it).
int a = myFunctionReturnsInt();

Sometimes you may also need to ignore that return value;

_ = myFunctionReturnsInt();

Or you might need to assign that into a var like below;

var dealItLater = myFunctionReturnsUnion();

**Comment by kaviththiranga** [comment]
We will skip suggesting the ignore case (refer to ```please don't misuse "_" to ignore errors in resource functions / main!``` thread in ballerina-dev).
