### ISSUE TITLE
Code action does not appear when hovered over a specific area 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13757]
**Description:**

Create local variable action doesn't work when the cursor hovers over the code line, it works only if the cursor is placed on the specific text/code area

**Comment by rasika** [comment]
@srsharon @NipunaMarcus Is this related to ballerina or vscode? AFAIK hover doesn't show code actions available in VSCode editor. If this is something else, can you put a GIF explaining the issue.

**Comment by rasika** [comment]
Not reproducible in the latest.
