### ISSUE TITLE
Re-editing a import without removing semicolon, it adds another semicolon

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13753]
**Description:**
While updating or re-entering an exciting import, auto completions adds a new semicolon while completing the import type. 

![image](https://user-images.githubusercontent.com/10986966/53160681-73a20f80-35ee-11e9-974b-72aa093bdbda.png)

**Comment by nadeeshaan** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/14621 and hence closing
