### ISSUE TITLE
Formatter breaks union type in variable definition

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13766]
**Description:**
Formatter breaks union type in variable definition

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/10986966/53179093-13749300-3619-11e9-87db-82ac29d196f8.gif)

**Comment by NipunaMarcus** [comment]
Fixed with the PR: https://github.com/ballerina-platform/ballerina-lang/pull/13682
