### ISSUE TITLE
Confusing compilation error for incompatible union type arrays 

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#13762]
**Description:**
Following code,
```ballerina
function test() returns int|string?[] {
    (int|string?)[] y = [1, 2];
    return y;
}
```
results in the following error,
```bash
error: .::union-type-confusion-test.bal:10:12: incompatible types: expected 'int|string?[]', found 'int|string?[]'
```
Can we improve the error message in this case?

**Comment by MaryamZi** [comment]
Closing this issue since the error message has been updated and is the following with 1.0.0-alpha
```
error: .::test.bal:3:12: incompatible types: expected '(int|string?[])', found '(int|string)?[]'
```

Parentheses are used to group the union in the error messages now. Please reopen if still not clear.
