### ISSUE TITLE
Code action, create local variable fails for response variable.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13770]
**Description:**
Code action, create local variable fails for response variable.

var response = blockingEp->addOrder(orderinfo);
response;

**Comment by rasika** [comment]
Not reproducible in the latest. Followed [gRPC guide](https://ballerina.io/learn/by-guide/grpc-service/). Executing code action generated below;

```ballerina
 orderMgtBlockingClient blockingEp = new("");
 orderInfo orderReq = {id:"100500", name:"XYZ", description:"Sample order."};
 ((string, grpc:Headers)|error) a = blockingEp->addOrder(orderReq);
```
