### ISSUE TITLE
Resource snippet is capital should be simple to be consistent with service.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13779]
**Description:**
Maintain snippet typography consistency Service and Resource representation should the same. 

![image](https://user-images.githubusercontent.com/10986966/53185510-2a20e700-3625-11e9-89f1-7b555825425e.png)

![image](https://user-images.githubusercontent.com/10986966/53185553-3efd7a80-3625-11e9-846e-f96386e39221.png)

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
