### ISSUE TITLE
“test creation” code action does not work as expected for functions

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13774]
**Description:**

“test creation” code action does not work as expected for functions (adds multiple function invocations with the same arguments, instead of single invocation)

**Comment by rasika** [comment]
This issue is reproducible for the `error` type arguments. For example;
```ballerina
public function name(error s) {
  io:println("test");
}
```

generated code:
```ballerina
@test:Config
function testName() {
    // Invoke function with test values
    name(());
    name(());
    name(());
}
```
Need to add `error` type for test value generator.
