### ISSUE TITLE
Formatting issue when formatting JSON

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13784]
**Description:**
Formatting issue when formatting JSON 

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/10986966/53219051-8d8e3180-3684-11e9-907d-27f4ff92341e.gif)

**Sample code**
https://github.com/ballerina-guides/content-based-routing/blob/master/README.md

**Comment by NipunaMarcus** [comment]
Fixed with the PR: https://github.com/ballerina-platform/ballerina-lang/pull/13682
