### ISSUE TITLE
Auto completion not provided within the function arguments

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13787]
**Description:**

Auto completion not provided within the function arguments
eg : log:printError(endpointResponse.<cursor> , err = endpointResponse);

Extended completion support, when there is a record as an argument, then the fields should be supported including nested records
eg:
Completions inside a nested record

```
mysql:Client studentDb = new({
    host:"localhost",
    port: 5690,
    name: "testdb",
    username: "root",
    password: "",
    dbOptions: { useSSL: false }
});
```
useSSL is not suggested.

**Comment by nadeeshaan** [comment]
This issue should be addressed with the source pruning implementation
#14216

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
