### ISSUE TITLE
Error is shown when ballerina home is set in vscode settings.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13788]
**Description:**
When pulling docker module from central, success message is shown and a consecutive error is shown when ballerina home is set in vscode settings.

**Comment by kaviththiranga** [comment]
is this happening because we are not using configured Ballerina distro to pull the module?

**Comment by rasika** [comment]
We are using shell command execution `ballerina pull <module_name>` to execute the command. Usually installers should replace `ballerina` command with the latest.

@srsharon Can you check whether output of the `ballerina -v` is same as VSCode configured `ballerina.home`(it should be different in this case).

I suppose, we need to get VSCode configured `ballerina.home` through the LSP config changes inorder to execute `ballerina pull` command. WDYT?

**Comment by rasika** [comment]
Closing since not reproducible in the latest. Please re-open if needed.
