### ISSUE TITLE
Inside an annotation attribute value, suggestions are not context related, it shows additional values

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13791]
**Description:**
Inside an annotation attribute value, suggestions are not context related, it shows additional values which is not relevant to the specific annotation. (happened when for docker image name)

**Comment by kaviththiranga** [comment]
If we type colon inside a string value of an annotation attrib, completions are getting triggerred.

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
