### ISSUE TITLE
Completions inside nested record are not suggested.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13793]
**Description:**
Completions inside nested record 
```
mysql:Client studentDb = new({
host:"localhost",
port: 5690,
name: "testdb",
username: "root",
password: "",
dbOptions: { useSSL: false }
});
```

useSSL is not suggested.

**Comment by nadeeshaan** [comment]
This will be addressed with the completion within a function's arguments are supported and addressed with the following
#13787
