### ISSUE TITLE
IS check with field-based access won't convert to expected type

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#13826]
**Description:**
If we run withFieldAccess() in below snippet, person.age won't get converted to int properly.

**Steps to reproduce:**
```ballerina

import ballerina/io;

// Works
public function directAccess() returns () {
    int? y = ();
    if (y is int) {
        int i = y + 5;
    } else {
        io:print("nil");
    }
}

// Does not work
public function withFieldAccess() returns () {
    Person p = new;
    if (p.age is int) {
        int i = p.age + 5;
    } else {
        io:print("nil age");
    }
}

public type Person object {
    public int? age = ();

    public function __init() {
    }
};
```

**Affected Versions:**
0.990.4-SNAPSHOT

**Suggested Assignees (optional):**
@SupunS @lankavitharana

**Comment by SupunS** [comment]
As per the spec, type narrowing is only applied for local-variables and parameters. Hence this behavior is not a bug, rather is in-lined with the spec.
