### ISSUE TITLE
Ballerina byte type needs to be refactored to use long registry and should be treated as int during compile time

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#13821]
**Description:**
According to the spec, `"The byte type is an abbreviation for a union of the int values in the range 0 to 255 inclusive"`. 
Hence, we can use the same long registry which is used to store Ballerina `int` values to store `byte` as well. Also, we can treat the byte values as int during the compile time as it would be the optimum way.

**Comment by hasithaa** [comment]
Fixed with #14209
