### ISSUE TITLE
How to use filter with an array of tuples?

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#13823]
**Description:**
The following code (which was suggested by the VSCode plugin)

(float, float)[] contractsAtPrices = [];
contractsAtPrices = contractsAtPrices.filter(function((float, float) value) returns (boolean) {
        return true;
    });

fails with this error

too many variables are defined for iterable type '(float,float)[]'

**Comment by MaryamZi** [comment]
This works on 0.992.0-m8 and will be available with the next release.

Tested
```ballerina
import ballerina/io;

public function main(string... args) {
    [float, float][] contractsAtPrices = [[1.1, 1.2], [2.3, 2.2]];
    io:println("Before filter: ", contractsAtPrices);
    contractsAtPrices = contractsAtPrices.filter(
        function([float, float] value) returns boolean {
            [float, float][a, b] = value;
            return a > b;
        }
    );
    io:println("After filter: ", contractsAtPrices);
}
```

Output
```cmd
$ ballerina run test.bal
Before filter: 1.1 1.2 2.3 2.2
After filter: 2.3 2.2
```
