### ISSUE TITLE
Values

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#13852]
This task list will track **design** and **implementation** of how ballerina values will be represented and implemented in JBallerina runtime.

| Task | Items |Design | Implementation |
|---|---|:---:|:---:|
| Simple Values | int<br>float<br>decimal<br>string<br>boolean<br>byte<br>nil| ✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>✅|✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>✅
| Structured Values | Arrays<br>Tuples<br>Maps<br>JSON<br>Records<br>XML<br>Table<br>Error|✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>✅|✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>✅
|  Behavioral Values | Objects<br>Function Pointers<br>TypeDesc<br>Futures<br>Streams<br>Iterator<br>~Channels~<br>Finite Types|✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>❎<br>✅|✅<br>✅<br>✅<br>✅<br>✅<br>✅<br>❎<br>✅

**Comment by SupunS** [comment]
Closing this issue since all values are implemented
