### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#13855]
This task list will track how ballerina types will be handled in JBallerina runtime.

* [x] Value Types
   * [x] int
   * [x] float
   * [x] decimal
   * [x] string
   * [x] boolean
   * [x] byte
   * [x] nil
* [x] Structured types
   * [x] map
   * [x] json
   * [x] record
   * [x] lists (arrays, tuples)
   * [x] xml
   * [x] table
   * [x] error
   * [x] type desc
* [ ] Behavioral types
   * [x] object
   * [x] finite types
   * [x] function type
   * [x] futures
   * [x] streams
   * [ ] ~channels~
* [x] Other
   * [x] tuple type
   * [x] union type
   * [x] any
   * [x] anydata
   * [x] finite types

**Comment by SupunS** [comment]
Closing this issue as all the types are implemented.
