### ISSUE TITLE
Arithmetic operations on byte type need to be supported 

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#13865]
**Description:**
* Currently, we don't support arithmetic operations between two `byte` values. However, the definition of byte type as per the spec reads,
`The byte type is an abbreviation for a union of the int values in the range 0 to 255 inclusive`. 

* As `byte` values belong to the set of `int` values, we need to support the arithmetic operations between two byte values. Adding more to this, as per the comments from the mail thread "Clarification on allowing byte type arithmetic operations" on ballerina-dev@googlegroups.com, `For the dynamic(runtime) behaviour, there is absolutely no different between bytes and ints`. Hence, the result of any arithmatic operations on byte type would be `int` except bitwise operations.

* Further, we also need to allow arithmetic operations between int and byte for the same aforementioned reason.

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/14209
