### ISSUE TITLE
Run .jar in JBallerina

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#13869]
The ballerina run command can load and run the .jar file, but there should be an entry point to run the code, like the main function. Entry points in ballerina programs are main or services. We need a generic way to make the compiled jar an executable one using the ballerina run command.

**Design considerations**

- Code generate an entry point class with the compiled jar file. This entry point class can be a generic approach that is common to any jars that JBallerina will compile down. 
- The entry point class has to contain a main method so that it works with when using the java run command.
- The ballerina run command will take the arguments and parse them to the relevant JVM types/values and then call the entry point class and the entry method(s).
- If the case of fat jar, then using java run command to execute the jar would work as it packs all the required dependency. But if it’s the case of normal jar with user code only, then we have to use the ballerina run command to execute the jar.

  - Fat jar 	      : $ java -jar abc.jar
  - Normal jar : $ ballerina run abc.jar

**Comment by vinok88** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/15837

**Comment by Kishanthan** [comment]
Closing this as it is being covered from packerina point of view.
