### ISSUE TITLE
[HTTP/2] Improve HTTP/2 client connection pool

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#13877]
**Description:**
In passthrough scenarios for HTTP/2, downstream and the upstream uses different threads hence an unnecessary thread switch occurs for each request and only one thread has been used for all the client requests.

Design - Http2ConnectionManager will have a map of eventloop pools and each eventloop pool will maintain its own set of per route pools. This will ensure that in passthrough scenario when a connection is needed by the client, it can always acquire a connection that belongs to the same eventloop as its source, hence the routing of the content will happen in the same thread.

Sub-Tasks
https://github.com/ballerina-platform/ballerina-lang/issues/14187
https://github.com/ballerina-platform/ballerina-lang/issues/14189

**Comment by arukshani** [comment]
#14187

**Comment by arukshani** [comment]
Fixed with https://github.com/wso2/transport-http/pull/308
