### ISSUE TITLE
Arithmetic operations should be supported on union types made up of values that exactly belong to the same basic numeric type

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#13879]
**Description:**
Consider a union type made up purely of a subset of int values.

```ballerina
type T 1|2|3|4;
```

* As type T is a union of a subset of int values, dynamic behaviour(runtime) of T is exactly same as ints.
Hence, any arithmatic operation that int supports should be supported for the above union type as well. 

* Arithmetic operations between `T and T`, `T and int`, `T and byte` should be supported in the above case. Where all the operations would yield an `int` result except for bitwise operations. Bitwise operations that use singleton unions that are a subtype of byte should result `byte` type.

* Similarly, union type T1 made up purely of a subset of float values should allow all the arithmetic operations allowed on floats. Operations between `T1 and float` , `T1 and T1` should be allowed where the result would be a `float`.

**Related Issues (optional):**
#13865

**Comment by hasithaa** [comment]
Fixed in SL.
