### ISSUE TITLE
Implement Ballerina scenario Tests(End to End Tests) on Testgrid

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#13888]
**Description:**

1. We need to figure out and filter out what are the tests we need to run on TestGrid for Ballerina. In general, the TestGrid should be used specifically for the scenarios that require various infrastructure requirements. For example, a scenario that requires a specific load balancer, a backend, some commercial database that cannot be simply run on locally or Jenkins, can be tested on TestGrid. But a scenario such as running a set of tests on OpenJDK can be done with Jenkins.

2. Since Ballerina is a cloud native programming language, it would be better if we can run the tests on an environment like Kubernetes. (This is what we have done in the sample test job we created as well)

3. What are the scenarios in each domain that we need to have tests for in TestGrid? Need a way to structure them to decide things such as how to group a set of tests to be run in a single TestGrid job.

4. Do we need to run our integration tests on TestGrid? Need to filter a set of tests? How frequent it should be done? If we are doing it, need to refactor the tests so that same code can be run locally, Jenkins and TestGrid against an outside deployment.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shafreenAnfar** [comment]
TestGrid is no longer an active project. Hence, I am closing this issue.
