### ISSUE TITLE
Abstract object implementation chekcs only for function name

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#13930]
**Description:**
The concrete implementation of a abstract clients only checks for function names when referring an abstract object . They are not validated against the input parameters and the return types of the functions. Same issue exists with the abstract objects as well.

The below code doesn't give an compiler error, but it should as the function contains different input parameters and return types.
```ballerina
public type AbstractSQLClient abstract client object {
    public remote function update(string queryStr, int count) returns int|error;
};

public type Client client object {
    *AbstractSQLClient;

    public remote function update(string sqlQuery) returns string|error {
        return "test";
    }
};

```
Same issue is there with abstrct objects as well.
```ballerina
public type AbstractSQLObj abstract object {
    public function update(string queryStr, int count) returns int|error;
};

public type Obj object {
    *AbstractSQLObj;

    public function update(string sqlQuery) returns string|error {
        return "test";
    }
};
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16002
