### ISSUE TITLE
Numeric conversion with `.constructFrom()`

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#13950]
* [ ]  If the shape of v is not a member of the set of shapes denoted by t (i.e. v does not look like t), then stamp will attempt to modify it so that it is by using numeric conversions (as defined by the NumericConvert operation) on structure members in v. If this fails or can be done in more than one way, then stamp will return an error. Frozen structures will not be modified, nor will new structures be created.
* [ ]  At this point, v looks like t. Now stamp narrows the inherent type of v, and recursively of any members of v, so that the v belongs to t, and then returns v. Any frozen values in v are left unchanged by this.

**Comment by hasithaa** [comment]
@pranavan15 Can you verify this.

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/13136

**Comment by pranavan15** [comment]
@hasithaa: Yes; This is a spec deviation we have in the current behaviour of the stamp built-in method. Currently, stamping does not modify any values and look for the exact field matches. However, according to the spec, we should check whether the members are numerically convertible and inter-assignable.

Example:
```ballerina

type Person record {
    int age = 0;
    string name = "";
    float salary = 0.0;
};

type Employee record {
    float age = 0;
    string name = "";
    decimal salary = 0.0;
};

public function main() {
    Person p = {age: 21, name: "Alice", salary : 1000.00};
    Employee e = Employee.stamp(p); // Valid scenario
}
```

**Comment by hasithaa** [comment]
@MaryamZi Please verify, is this valid to 2019R3?

**Comment by MaryamZi** [comment]
This is still valid for `.constructFrom()` and needs to be fixed.

```ballerina
# Construct a value with a specified type by copying another value.
# + t - the type for the copy to be constructed
# + v - the value to be copied
# + return a new value that belongs to type `t`, or an error if this cannot be done
# 
# When `v` is a structural value, the inherent type of the value to be constructed
# comes from `t`. When `t` is a union, it must be possible to determine which
# member of the union to use for the inherent type by following the same rules
# that are used by list constructor expressions and mapping constructor expressions
# with the contextually expected type. If not, then an error is returned.
# The `constructFrom` operation is recursively applied to each member of `v` using
# the type descriptor that the inherent type requires for that member.
# 
# Like the Clone abstract operation, this does a deep copy, but differs in
# the following respects:
# - the inherent type of any structural values constructed comes from the specified
#   type descriptor rather than the value being constructed
# - the graph structure of `v` is not preserved; the result will always be a tree;
#   an error will be returned if `v` has cycles
# - immutable structural values are copied rather being returned as is; all
#   structural values in the result will be mutable, except for error values
#   (which are always immutable)
# - numeric values can be converted using the NumericConvert abstract operation
# - if a record type descriptor specifies default values, these will be used
#   to supply any missing members
public function constructFrom(typedesc<AnydataType> t, anydata v) 
            returns AnydataType|error = external;
```

Note "numeric values can be converted using the NumericConvert abstract operation"
