### ISSUE TITLE
Websocket breaks when using global client endpoint defn

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#13990]
**Description:**
Heard that it's a platform level bug, but still creating this issue so that my scenario will be validated with the fix. 

When we declare websocket client endpoint inside the main method, it connects with websocket server and receives updates.

```
import ballerina/io;
import ballerina/http;

public function main() {
    http:WebSocketClient wsClientEp = new("ws://echo.websocket.org", config = {callbackService: ClientService});
   checkpanic wsClientEp->pushText("hello");
}
service ClientService =@http:WebSocketServiceConfig {} service {

//This resource is triggered when a new text frame is received from the remote backend.
resource function onText(http:WebSocketClient conn, string text, boolean finalFrame) {
        io:println(text);
    }
};
```

But when I move that endpoint to global level, it doesn't work. Code just hangs.
```
http:WebSocketClient wsClientEp = new("ws://echo.websocket.org", config = {callbackService: ClientService});

public function main() {
    checkpanic wsClientEp->pushText("hello");
}
```

**Comment by riyafa** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/13900

**Comment by MaryamZi** [comment]
For the latter, with 0.991.0, I get the following error, which seems to be due to the issues with the annotation map variable.
```cmd
$ ballerina run err_test.bal
error: {}
        at ballerina/http:initEndpoint(<native>)
           ballerina/http:__init(websocket/websocket_client.bal:44)
           ..<init>(err_test.bal:3)
```

With, 0992.0-m, "hello" is printed as expected.

@riyafa, can you please verify?

**Comment by riyafa** [comment]
Closing the issue as it seems to have been resolved in master
