### ISSUE TITLE
Ballerina Intellij IDEA plugin error on Windows 10

### ISSUE THREAD

**Issue by Shehanka** [ballerina-platform/ballerina-lang#13992]
**Description:**
com.intellij.diagnostic.PluginException: action with the ID "LSPFindUsages" was already registered. Action being registered is  (null); Registered action is  (null) Plugin: Ballerina [Plugin: io.ballerina]

**Steps to reproduce:**

**Affected Versions:**
0.990.3

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**
intellij idea, jetbrains

**Suggested Assignees (optional):**
@Shan1024

**Comment by NipunaRanasinghe** [comment]
@Shehanka thanks for the information :) I'll work on it and let you know once it is fixed.

**Comment by NipunaRanasinghe** [comment]
@Shehanka Could you please check whether you have installed the `LSP Support` plugin in IntelliJ IDEA?? If so, would you please re-check after uninstalling it?

**Comment by Shehanka** [comment]
@NipunaRanasinghe I disabled `LSP Support` now there's no error.

**Comment by NipunaRanasinghe** [comment]
Hope you issue is resolved. :) We previously downloaded and used `LSP Support` plugin as a dependent plugin of the ballerina plugin, to connect to the ballerina language server. But since we've written out own language client library, you can simply uninstall it.
