### ISSUE TITLE
Autocomplete is triggered inside a string

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#14009]
**Description:**
Autocomplete is triggered even when a package is typed inside a string. An example is shown below.

<img width="637" alt="screen shot 2019-02-28 at 17 48 23" src="https://user-images.githubusercontent.com/11191791/53566136-62727900-3b81-11e9-899d-59d01f804310.png">

**Steps to reproduce:**
Add a string and type a relevant package to get the autocomplete. 

**Affected Versions:**
0.990.3

**OS, DB, other environment details and versions:**
MacOS Mojave

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/13524

**Comment by kaviththiranga** [comment]
Closing this in favor of https://github.com/ballerina-platform/ballerina-lang/issues/13524
