### ISSUE TITLE
Annotations are not suggested for half completed attribute names 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#14028]
**Description:**
Annotations are not suggested for half completed attribute names, also annotation complition support is only for the first attribute.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10986966/53616893-c725e600-3c0a-11e9-8c35-7a23d7dd078b.gif)

**Comment by nadeeshaan** [comment]
Duplicate of #12504
