### ISSUE TITLE
Support building modules with jvmTarget flag

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#14036]
Need to support building ballerina modules with jvmTarget flag and generate a jar file with the package for the module built.

Related to #13868

**Comment by shilpakarre** [comment]
hi, could you please explain me how to generate the jar files by including all the modules of the ballerina.

**Comment by Kishanthan** [comment]
> hi, could you please explain me how to generate the jar files by including all the modules of the ballerina.

@shilpakarre,  Be default, if you build a ballerina module or a ballerina file, an executable uber jar will be created which will include all the required dependencies. You don't have to do anything additional here and ballerina build will take care of including the required dependencies.
