### ISSUE TITLE
Ballerina init command is not working properly on Desktop

### ISSUE THREAD

**Issue by rnavagamuwa** [ballerina-platform/ballerina-lang#14079]
**Description:**
`ballerina init` should create a sample project which includes a file called `hello_service.bal`. But this `hello_service.bal` file is not created when the `ballerina init` command is executd on desktop.

**Steps to reproduce:**
Execute `ballerina init` command on desktop.

**Affected Versions:**
- Ballerina 0.990.3

**OS, DB, other environment details and versions:**
- OS
    - ProductName:    Mac OS X
    - ProductVersion: 10.14.3
    - BuildVersion:   18D109

**Comment by NatashaWso2** [comment]
@rnavagamuwa 'ballerina init' is designed to be like 'git init' where we initialize the current directory as a ballerina project. We do not explicitly create a project directory and initialize it. We just initialize the directory where 'ballerina init'  was executed as a ballerina project. So if you want to initialize a ballerina project using the 'ballerina init' command, first create a project directory and then run 'ballerina init' inside it.

**Comment by rnavagamuwa** [comment]
@NatashaWso2 thanks for the detailed explanation. Since desktop is also a directory my personal opinion is `ballerina init` should work properly on the desktop too. As per my understanding `hello_service.bal` will be created only if the directory is empty but in Mac OS there is a file called `.DS_Store` which stores custom attributes of its containing folder. Please correct me if I'm wrong here but due to this `.DS_Store` file, `hello_service.bal` will not be created.

**Comment by NatashaWso2** [comment]
@rnavagamuwa apologies for the late reply. Yes you are correct we need to ignore these hidden files. We will provide a proper fix for this since we will have to consider hidden files in other platforms as well.

**Comment by pubudu91** [comment]
Closing since this was fixed with #14139
