### ISSUE TITLE
[Spec Deviation] Revisit usage of `new-expr` 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#14088]
**Description:**
The "New expression" section of the spec defines `new-expr` as follows:

```
new-expr := new-value-expr | new-object-expr 
new-value-expr : new [type-descriptor]
new-object-expr := new [type-descriptor] ( arg-list )
```

Even though we support `new-object-expr`, `new-value-expr` is not yet supported.

```
A new-value-expr allocates storage for a reference type and initializes it with the
 implicit initial value for that type. It is a compile error if the type-descriptor for 
a new-value-expr, whether explicitly specified or not, is not a reference type
 with an implicit initial value.

If the type-descriptor in a new-expr specifies a type T, then the static type of a 
new-expr is T, except that, in the case of a new-object-expr, if the type of the 
__init method is E?, where E is a subtype of error, then the type of the 
new-object-expr is T|E.

If the type descriptor is omitted in either kind of new-expr, then the 
contextually expected type is used instead.
```

Also, even though `new` is allowed with streams and channels, it is also possible to say `new()` which is invalid according to the grammar (parentheses are only mentioned for `new-object-expr`).

**Comment by MaryamZi** [comment]
The spec now (2019r3) says 

```
new-expr := explicit-new-expr | implicit-new-expr
explicit-new-expr := new type-descriptor ( arg-list )
A new-expr constructs a new object.
```

However, we do allow `new` with streams too. The filler value table in the spec does mention `new stream<T>`, but it is not specified elsewhere. Need to validate if `new` can be allowed with streams, or what (if anything) needs to be used with streams.

**Comment by hasithaa** [comment]
@irshadnilam Can you work on this issue.

**Comment by irshadnilam** [comment]
> @irshadnilam Can you work on this issue.

Sure

**Comment by hasithaa** [comment]
It seems like there is nothing to fix with the latest changes. Stream related discussion https://github.com/ballerina-platform/ballerina-spec/issues/311
