### ISSUE TITLE
Introduce separate client for postgresql

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#14108]
**Description:**
Currently, interacting with a PostgreSQL database has to be done with JDBC client. Need to provide a separate client for PostgreSQL similar to MySQL, H2, along with the refactoring done to provide a richer feature set focusing on vendor-specific areas

**Comment by anupama-pathirage** [comment]
Refer the comment https://github.com/ballerina-platform/ballerina-lang/issues/13818
