### ISSUE TITLE
Introduce separate client for Oracle

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#14109]
**Description:**

Currently, interacting with a Oracle database has to be done with JDBC client. Need to provide a separate client for Oracle similar to MySQL, H2, along with the refactoring done to provide a richer feature set focusing on vendor-specific areas

**Comment by anupama-pathirage** [comment]
Refer the comment in https://github.com/ballerina-platform/ballerina-lang/issues/13818
