### ISSUE TITLE
Prefix errors returned by main with "error: " and all panics with "panic: "

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#14104]
**Description:**

With https://github.com/ballerina-platform/ballerina-lang/pull/13449 we print errors returned by the main function to std err, prefixed with `error: `.

As discussed in https://groups.google.com/d/msg/ballerina-dev/Yxy-qB-4e-I/oqN80ml9GQAJ, we need to prefix panics (also printed to the std err) with `panic: ` (which is currently also prefixed with `error: `).

**Comment by hasithaa** [comment]
This is no longer applicable. Return error, exit with non-zero status code, and printing toString() of the error value. Panics additionally print the stack trace.  Hence closing.
