### ISSUE TITLE
Write compiler plugin for resources without input parameters

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#14148]
**Description:**
> Currently, compiler plugin identifies a service using the input parameters of the resource. But we need a way to write a compiler plugin to a service which does not have an input parameter for the resource.
> A service cannot be identified by the compiler plugin if it does not have an input parameter, as of now.

__UPDATE:__

This acts as a bug in Ballerina task library. 

Currently ballerina task services have only one resource, `onTrigger()` which has no parameters, by default. But a user can pass parameters as an attachment as follows.

```ballerina
import ballerina/kafka;
import ballerina/task;

kafka:ConsumerConfig consumerConfig = {
    bootstrapServers: "localhost:9100",
    groupId: "test-group",
    clientId: "basic-consumer",
    offsetReset: "earliest",
    topics: ["test"]
};

public function main() {
    kafka:Consumer kafkaConsumer = new(consumerConfig);
    task:Scheduler timer = new({ intervalInMillis: 1000 });
    var attachResult = timer.attach(timerService, attachment = kafkaConsumer);
    var startResult = timer.start(); 
}

service timerService = service {
    resource function onTrigger(kafka:Consumer kafkaConsumer) {
        // implementation
    }
}
```

This will throw a compilation error, as the compiler identifies this as Kafka service, because of the parameter of the resource function, and it does not comply with the Kafka resource signature. We should have a way to identify the resources without looking at the resource function parameters.

**Comment by riyafa** [comment]
I think we need service typing for compile time validation: https://groups.google.com/forum/#!msg/ballerina-dev/AicMMCXL8kA/w9l1vNz1CAAJ

**Comment by hasithaa** [comment]
This related new service typing proposal in SL. With that, we don't need this feature anymore.
