### ISSUE TITLE
Revisit synchronous logic in document manager class

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#14153]
https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/workspace/WorkspaceDocumentManagerImpl.java

**Comment by nadeeshaan** [comment]
This has been addressed with the latest migration for the project API. See the new implementation with a cleaner locking mechanism https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java
