### ISSUE TITLE
websub documentation gaps

### ISSUE THREAD

**Issue by copenat** [ballerina-platform/ballerina-lang#14175]
**Description:**
A lot of new features have been added to the websub module. Excellent! But would be great to have examples on how to use them. I was trying to use the ExtensionConfig from the README but it is not detailed enough for it to be useful.

**Steps to reproduce:**
0.990.X

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
More information regarding the new features are now live at:
- https://ballerina.io/learn/api-docs/ballerina/websub.html 
- https://ballerina.io/learn/how-to-extend-ballerina/#create-webhook-callback-services

We hope these address the gaps identified.

An issue https://github.com/ballerina-platform/ballerina-lang/issues/13875 was also created to track adding a BBG for WebSub.

Please do re-open this issue if you come across further gaps or if the details are not sufficient.
