### ISSUE TITLE
Problem on configuring CORS in ballerina

### ISSUE THREAD

**Issue by SanojPunchihewa** [ballerina-platform/ballerina-lang#14194]
**Description:**
When I try to do a POST request to a ballerina service I get the error ```No 'Access-Control-Allow-Origin' header is present on the requested resource.``` on my web browser.
***Note*** Everything works fine when I send a POST request without sending the preflight

**Steps to reproduce:**
Start a ballerina service and do an AJAX POST request to it
**Ballerina Service:**
```
@http:ServiceConfig { 
    basePath: "/feedback",
    cors: {
        allowOrigins: ["*"],
        allowHeaders: ["*"]
    }}

service FeedbackCollection on httpListener {
    @http:ResourceConfig {
        methods: ["POST"],
        path: "/pushData"
    }
    resource function updateFeedback(http:Caller caller, http:Request req) {

        var reqPayload = req.getJsonPayload();
        //...
    }
}
```
**Ajax Request:**
```
let axiosConfig = {
        headers: {
            'Content-Type': 'application/json;charset=UTF-8'
        }
        };    
        axios.post('http://localhost:9090/feedback/pushData', {data: formdata}, axiosConfig)
            .then(response => {
              // ...
            })
            .catch(error => {});
```
**Affected Versions:**
Ballerina 0.990.3

**OS, DB, other environment details and versions:**
Ubuntu 18.04 LTS

**Related Issues (optional):**

**Suggested Labels (optional):**
Component/HTTP

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
@SanojPunchihewa Have you hosted your front end server(which does the ajax call)? If you do the operation locally, browser fails to identify the Origin  and set it before calling the ballerina server. That will lead to aforementioned error as Ballerina service does not treat any of the request as cors unless it includes Origin header.

Could you please give us an update on this?

**Comment by SanojPunchihewa** [comment]
@chamil321 No, I haven't hosted the front end, I just tried it locally. I'll host it and let you know whether it solves the problem

**Comment by chamil321** [comment]
@SanojPunchihewa Did you get any chance to test?

**Comment by SanojPunchihewa** [comment]
@chamil321 Sorry for taking a long time. When I hosted the front end it is working without any problem.

**Comment by chamil321** [comment]
Closing this issue, as per above comment

**Comment by chamil321** [comment]
Also, this issue is resolved when the ajax call happens via network IP.

Use 192.x.x.x:9000/call instead of localhost:9000/call
