### ISSUE TITLE
LS provide wrong completion items after first statement inside __init function of Object.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#14207]
**Description:**
LS provide wrong compilations belong to top level when trying to get completion after first statement inside the __init function of an Object.

**Steps to reproduce:**

![object reference completion](https://user-images.githubusercontent.com/9109762/54009064-55f8ac80-418f-11e9-8c77-a5d1dee0a7cb.gif)

**Comment by nadeeshaan** [comment]
This issue is due to #14573 which need to be fixed

**Comment by nadeeshaan** [comment]
Fixed in latest master with the source prune based completion implementation. Hence closing the issue.
