### ISSUE TITLE
[stdlib] [documentation review]  Review new task examples

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#14227]
**Description:**
> Ballerina task library is re-designed, and there are new examples added.
> These new examples should be reviewed.
> Related PR: #14484
> 
> Affected examples:
> - examples/task-service-appointment
> - examples/task-service-timer
> - examples/task-scheduler-appointment
> - examples/task-scheduler-timer

**Suggested Labels (optional):**
> Review

**Suggested Assignees (optional):**
@praneesha

**Comment by praneesha** [comment]
I have added review comments in [1].

We might need to create a new PR applying these review comments since [1] is already merged.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/13632/files
