### ISSUE TITLE
Error type definitions allowed with non-string reasons

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#14248]
**Description:**
$title.

**Steps to reproduce:**
Compilation does not fail for
```ballerina
type MyErr error<int>;
```

**Affected Versions:**
0.990.3

**Comment by Anoukh** [comment]
Type definition also allows any type for the `detail`. It should be limited to sub types of `record { }` (which is equivalent to map<anydata|error>)
