### ISSUE TITLE
[HTTP] A memory leak warning occurred while load testing data-binding

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#14249]
**Description:**

A memory leak occurred while load testing for data-binding with JSON.
Tested multiple combinations and found that this occurs only when sending JSON payload to service which accepts a XML payload. 
>Issue does not occur when an incorrect XML is sent to a service which accepts XML payload. 
>Issue does not occur when an XML is sent to a service which accepts JSON payload. 
>Issue does not occur when an incorrect JSON is sent to a service which accepts JSON payload. 
>Same with String payloads

Tested that when trying to parse the payload, blocking entity collector transform from `consumable` state to `consumed` state which is expected. Therefore no remnant HTTP content lies in the queue. 

The output of `ballerina-internal.log`

```
ERROR {io.netty.util.ResourceLeakDetector} - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:   
```

**Steps to reproduce:**

JMeter request URL: http://localhost:8080/nyseStock/stocks
Invoke the service with above URL, 100 concurrency and a 50bytes JSON payload for about 15 seconds.

```ballerina
import ballerina/http;
import ballerina/log;

listener http:Listener httpListener = new(8080);

@http:ServiceConfig {
    basePath: "/nyseStock"
}
service nyseStockQuote on httpListener {

    @http:ResourceConfig {
        path: "/stocks",
        body: "pay"
    }
    resource function stocks(http:Caller outboundEP, http:Request clientRequest, xml pay) {
        _ = outboundEP->respond(untaint pay);
    }
}
```

**Affected Versions:**
0.990.X

**Comment by chamil321** [comment]
Fix is available in https://github.com/ballerina-platform/ballerina-lang/pull/14666
Experiencing test failures due to content release

**Comment by arukshani** [comment]
We can close this right? Ballerina updated with the latest transport which includes this fix as well (https://github.com/wso2/transport-http/pull/365) and all the tests got passed.

**Comment by chamil321** [comment]
@arukshani In order to fix the memory leak, https://github.com/ballerina-platform/ballerina-lang/pull/18305 PR should get merged. 

I tested it against above scenario and issue has not reproduced.
> No mem leak warning in the internal log

##Sample 
```ballerina
import ballerina/http;

listener http:Listener httpListener = new(8080);

@http:ServiceConfig {
    basePath: "/nyseStock"
}
service nyseStockQuote on httpListener {

    @http:ResourceConfig {
        path: "/stocks",
        body: "pay"
    }
    resource function stocks(http:Caller outboundEP, http:Request clientRequest, xml pay) {
        checkpanic outboundEP->respond(<@untainted> pay);
    }

        @http:ResourceConfig {
        path: "/stocksXml",
        body: "pay"
    }
    resource function stocksXml(http:Caller outboundEP, http:Request clientRequest, json pay) {
        checkpanic outboundEP->respond(<@untainted> pay);
    }


    @http:ResourceConfig {
        path: "/stocks2"
    }
    resource function stocks2(http:Caller outboundEP, http:Request clientRequest) {
        var responsePayload = clientRequest.getXmlPayload();
        json responseJsonPayload = {};
        if (responsePayload is xml) {
            checkpanic outboundEP->respond(<@untainted> responseJsonPayload);
        } else {
            json errMsg = { "error": "expected response message not received" };
            checkpanic outboundEP->respond(errMsg);
        }
    }

    @http:ResourceConfig {
        path: "/stocksXml2"
    }
    resource function stocksXml2(http:Caller outboundEP, http:Request clientRequest) {
        var responsePayload = clientRequest.getJsonPayload();
        json responseJsonPayload = {};
        if (responsePayload is json) {
            checkpanic outboundEP->respond(<@untainted> responseJsonPayload);
        } else {
            json errMsg = { "error": "expected response message not received" };
            checkpanic outboundEP->respond(errMsg);
        }
    }
}
```

Tested with 100 concurrancy 50B payloads (both JSON and XML payloads respectively)
