### ISSUE TITLE
[Editor] Copy paste support for digram elements

### ISSUE THREAD

**Issue by gvasanka** [ballerina-platform/ballerina-lang#1425]
Developers may need to use the same logic on two functions and be interested in copy pasting the already prepared diagram.

Ex.
![selection_161](https://cloud.githubusercontent.com/assets/3368635/22637844/7589aa76-ec6a-11e6-9289-6990823a178b.png)

**Comment by uthaiyashankar** [comment]
Moved back from https://github.com/ballerina-lang/composer/issues/288

**Comment by hevayo** [comment]
Due to the new visualizing approach copy paste is not that significant for the diagram. If they prefer copy paste they can use the split view.
