### ISSUE TITLE
Have ballerina error values to represent client errors from different API

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-lang#14297]
**Description:**
From different third party APIs, we will get multiple error values as below. Need to have ballerina error values to represent client errors.
Eg: 
"errors": [
	{
	  "reason": string,
	  "location": string,
	  "debugInfo": string,
	  "message": string
	}
]
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@rdhananjaya / @hasithaa As per the discussion in https://github.com/wso2-ballerina/module-bigquery/pull/3#discussion_r264565147 it seems this is a compiler side improvement. Do we have that support now?

**Comment by shafreenAnfar** [comment]
Error design has changed and I don't think this is applicable anymore. Hence, closing this issue.
