### ISSUE TITLE
[HTTP/2] TPS is lower in HTTP/2 server downgrade scenario compared to HTTP/1.1

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#14301]
**Description:**
It is observed that TPS is lower in HTTP/2 server downgrade scenario compared to HTTP/1.1.

-- | h2_h2_server_downgrade | h1_h1_passthrough
-- | -- | --
Scenario | h1 -> h2_h2 -> h2 | h1 -> h1_h1 -> h1
Concurrency | 1000 | 1000
Payload | 1KB | 1KB
TPS | 8775.30 | 12242.40

More results: https://docs.google.com/spreadsheets/d/11O0UpAwAHHuGDi4Ui74VXxQjCEcnwwTMmOg4_FytYrs/edit?usp=sharing

**Comment by arukshani** [comment]
This cannot be recreated either in local or AWS. 

Local results - TPS
h1 -> h2_h2 -> h2  =  7604.9
h1 -> h1_h1 -> h1  =  7250.7

AWS results - TPS
h1 -> h2_h2 -> h2  =  12767.47
h1 -> h1_h1 -> h1  =  10928.88

AWS results location >> 
https://github.com/ballerina-platform/ballerina-lang/blob/performance-test-162-2019-03-18_10-05-56/performance/benchmarks/summary.csv
