### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#14325]
**Description:**
Remove unused dependencies from the project. Some of them are as follows.

- org.wso2.transport.jms
- andes-client
- org.apache.james
- org.wso2.orbit.net.sf.saxon
- commons-pool.wso2
- io.airlift

**Comment by wggihan** [comment]
We need commons-pool.wso2 for HTTP. The rest of the dependencies were already removed.
