### ISSUE TITLE
Refactor code to reflect package -> module rename

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#14329]
Still the implementation classes, methods, variables, etc. refers modules as packages. Should we keep it anylonger as it is or refactor them to use the name ```module```?

**Comment by hasithaa** [comment]
This is addressed in the Compiler API. Still Compiler internal part uses word package instead of module.

**Comment by hasithaa** [comment]
Not planning to fix this in Swan Lake. We will use the correct terminologies in the new implementation.
