### ISSUE TITLE
Introduce checkpanic expression

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14322]
There will still be cases where the programmer wants to ignore an error because they expect that a particular function or method call will not return error given the inputs or current state. In this case, it's a bug if, contrary to expectations, the call returns an error and so the program should panic in this case rather than silently continuing. This is the same semantic as check, except that instead it handles an error value by panicking rather than returning. We plan to add a checkpanic expression to handle this, which will be allowed in the same places check currently is. The syntax here is intentionally quite obtrusive to discourage inappropriate use.

Refer : https://groups.google.com/d/msg/ballerina-dev/_f--VkihvsY/OlOQbTzvBwAJ

**Comment by Anoukh** [comment]
This was introduced with PR  #14543. Hence, closing the issue
