### ISSUE TITLE
Shebang/binfmt_misc Bash Scripting

### ISSUE THREAD

**Issue by cawfeecoder** [ballerina-platform/ballerina-lang#14335]
**Description:**
Similar to how Scala, Kotlin, Python, etc support adding a shebag to the top of the file to make it executable, is there plans for Ballerina to do something similar? i.e. #!/bin/bash/env ballerina? Or could we get a similar functionality through binfmt_misc?

**Comment by anupama-pathirage** [comment]
This is currently not part of our plans or a priority, so we are closing the issue for now. We will reopen it if we decide to pursue this in the future.
