### ISSUE TITLE
[Enhancement] Sort function for array type

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#1433]
$subject please. This will help enable effective usage of arrays and quick inbuilt ability to sort an array.

**Comment by sameera-jayasoma** [comment]
We do have a sort function to sort an array of strings. But that is not enough.

**Comment by hasithaa** [comment]
This is added with the array lang library. https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.array/src/main/ballerina/src/lang.array/array.bal#L170
