### ISSUE TITLE
Soap response child access using XML access

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#14357]
**Description:**
I have a following soap response. I need to access particular child element from the soap response. When I tried it using the language supported feature [2], it returns empty values.

[1] - 
`<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns:validateKeyResponse xmlns:ns="http://org.apache.axis2/xsd">
         <ns:return xmlns:ax2129="http://keymgt.apimgt.carbon.wso2.org/xsd" xmlns:ax2131="http://api.apimgt.carbon.wso2.org/xsd" xmlns:ax2133="http://model.api.apimgt.carbon.wso2.org/xsd" xmlns:ax2134="http://dto.api.apimgt.carbon.wso2.org/xsd" xmlns:ax2137="http://dto.impl.apimgt.carbon.wso2.org/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax2137:APIKeyValidationInfoDTO">
            <ax2137:apiName>PizzaShackAPI</ax2137:apiName>
            <ax2137:apiPublisher>admin</ax2137:apiPublisher>
            <ax2137:apiTier xsi:nil="true" />
            <ax2137:applicationId>1</ax2137:applicationId>
            <ax2137:applicationName>DefaultApplication</ax2137:applicationName>
            <ax2137:applicationTier>Unlimited</ax2137:applicationTier>
            <ax2137:authorized>true</ax2137:authorized>
            <ax2137:authorizedDomains xsi:nil="true" />
            <ax2137:consumerKey>fLHfXumVxAN6b1BM9btNulbcV5Qa</ax2137:consumerKey>
            <ax2137:contentAware>false</ax2137:contentAware>
            <ax2137:endUserName>admin@carbon.super</ax2137:endUserName>
            <ax2137:endUserToken xsi:nil="true" />
            <ax2137:issuedTime>1551890185437</ax2137:issuedTime>
            <ax2137:scopes>default</ax2137:scopes>
            <ax2137:scopes>am_application_scope</ax2137:scopes>
            <ax2137:spikeArrestLimit>0</ax2137:spikeArrestLimit>
            <ax2137:spikeArrestUnit xsi:nil="true" />
            <ax2137:stopOnQuotaReach>true</ax2137:stopOnQuotaReach>
            <ax2137:subscriber>admin</ax2137:subscriber>
            <ax2137:subscriberTenantDomain>carbon.super</ax2137:subscriberTenantDomain>
            <ax2137:throttlingDataList>api_level_throttling_key</ax2137:throttlingDataList>
            <ax2137:tier>Unlimited</ax2137:tier>
            <ax2137:type>PRODUCTION</ax2137:type>
            <ax2137:userType>APPLICATION</ax2137:userType>
            <ax2137:validationStatus>0</ax2137:validationStatus>
            <ax2137:validityPeriod>9223372036854775807</ax2137:validityPeriod>
         </ns:return>
      </ns:validateKeyResponse>
   </soapenv:Body>
</soapenv:Envelope>`

[2] - https://ballerina.io/learn/by-example/xml-access.html

**Affected Versions:**
0.990.3

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by anupama-pathirage** [comment]
@Rajith90 Can you please share the piece of ballerina code which returns empty values?

**Comment by pubudu91** [comment]
You can access elements of the above response. I tried the following program:
```ballerina
import ballerina/io;
import ballerina/log; 

xmlns "http://schemas.xmlsoap.org/soap/envelope/" as soapenv;
xmlns "http://org.apache.axis2/xsd" as ns;
xmlns "http://dto.impl.apimgt.carbon.wso2.org/xsd" as ax2137;

public function main(string... args) returns error? {
    xml soap = check read("./soap.xml");
    io:println(soap[soapenv:Body][ns:validateKeyResponse][ns:^"return"][ax2137:apiName]);
}

function read(string path) returns xml|error {
    io:ReadableByteChannel rbc = io:openReadableFile(path);
    io:ReadableCharacterChannel rch = new(rbc, "UTF8");

    var result = rch.readXml();

    closeRc(rch);
    return result;
}

function closeRc(io:ReadableCharacterChannel rc) {
    var result = rc.close();
    if (result is error) {
        log:printError("Error occurred while closing character stream", err = result);
    }
}
```
And it gave the following output:
```
<ax2137:apiName xmlns:ax2137="http://dto.impl.apimgt.carbon.wso2.org/xsd">PizzaShackAPI</ax2137:apiName>
```

**Comment by pubudu91** [comment]
Closing this since this is not an issue.

**Comment by Rajith90** [comment]
Explicitly defining the namespaces solves the issue. Thanks @pubudu91 for the solution
