### ISSUE TITLE
Gradle build release process tasks

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#14378]
- [x] Migrate ballerinax/docker
- [x] Migrate ballerinax/kubernetes
- [x] #14411 Migrate ballerinax/jdbc
- [x] Migrate ballerinax/awslambda
- [x] Migrate ballerina-platform/ballerina-distribution
- [x] Publish all the repositories to nexus
- [x] Update release pipeline to support gradle

**Comment by keizer619** [comment]
@Manuri @hemikak 
Need help to migrate docker, k8 and jdbc extensions

**Comment by Manuri** [comment]
@Tharik I will include the jdbc module migration to the next week's sprint

**Comment by hemikak** [comment]
I'll look into docker and kubernetes repos.

**Comment by keizer619** [comment]
Close this issue as now everything is migrated to Gradle
