### ISSUE TITLE
[Editor] Shouldn't it support to interchange between the elements? Alignment modification is not possible in graphical view.

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#1437]
1. Could not move the elements between them. 
- Added elements in the program as in below image. Now I wanted to move created structs to top of the code (this is possible from the source view as cut and paste).
![align](https://cloud.githubusercontent.com/assets/15671620/22639733/7bffa134-ec75-11e6-99d5-72fc01dc0abe.jpeg)

2. Not supported to moving the statements inside the element. 
- Added statements as in below image. Now I wanted to move the 'system:println' statement to bottom of the function.
![align2](https://cloud.githubusercontent.com/assets/15671620/22639738/8293e7b2-ec75-11e6-9e00-be126ba987b5.jpeg)

Using build from master 5-Feb

**Comment by uthaiyashankar** [comment]
Moved back from https://github.com/ballerina-lang/composer/issues/292

**Comment by pahans** [comment]
Drag n drop editor is no longer supported in the composer.
