### ISSUE TITLE
count() and distinctCount() in streams do not work when passed into a function

### ISSUE THREAD

**Issue by RameshaKaru** [ballerina-platform/ballerina-lang#14387]
**Description:**
The count() and distinctCount() work in stream queries when assigned directly, but do not work when passed into a function. Error is produced as : unknown function distinctCount

**Steps to reproduce:**

from eligibilityStream
            window gateway:timeBatch(60000,0)
            where eligibilityStream.isEligible == true
            select printKey1(eligibilityStream.throttleKey) as throttleKey, getCount(distinctCount(eligibilityStream.messageID)) as eventCount, true as stopOnQuota, eligibilityStream.expiryTimestamp as expiryTimeStamp
            group by eligibilityStream.throttleKey
            => (gateway:IntermediateStream[] counts) {
            foreach var c in counts{
                io:println("elig", c);
            intermediateStream.publish(c);
            }
            }

Referred function

function getCount(int cx) returns int{
                io:println("Count ",cx);
                return cx;
            }

**Affected Versions:**
0.990.3

**Comment by gimantha** [comment]
fixed with #17104
