### ISSUE TITLE
The streams initialized inside a function are not working

### ISSUE THREAD

**Issue by RameshaKaru** [ballerina-platform/ballerina-lang#14383]
**Description:**
When streams were initialized inside the function which has the forever loop, the code did not work and did not produce an error either. When they were initialized out of the function, the streams worked.

**Steps to reproduce:**

function initSubscriptionSub_5Policy() {

stream<gateway:IntermediateStream> intermediateStream = new;
stream<gateway:GlobalThrottleStreamDTO> resultStream = new;
stream<EligibilityStreamDTO> eligibilityStream = new;
stream<gateway:RequestStreamDTO> reqCopy= gateway:requestStream;
stream<gateway:GlobalThrottleStreamDTO> globalThrotCopy = gateway:globalThrottleStream;
    
    forever {
            from reqCopy
            select printKey(reqCopy.messageID) as messageID, true as isEligible, printKey(reqCopy.subscriptionKey) as throttleKey, 0 as expiryTimestamp
            => (EligibilityStreamDTO[] counts) {
            foreach var c in counts{
                eligibilityStream.publish(c);
            }
            }

            from eligibilityStream
            window gateway:timeBatch(60000,0)
            where eligibilityStream.isEligible == true
            select printKey1(eligibilityStream.throttleKey) as throttleKey, distinctCount(eligibilityStream.messageID) as eventCount, true as stopOnQuota, eligibilityStream.expiryTimestamp as expiryTimeStamp
            group by eligibilityStream.throttleKey
            => (gateway:IntermediateStream[] counts) {
            foreach var c in counts{
                io:println("elig", c);
            intermediateStream.publish(c);
            }
            }
}
}
**Affected Versions:**
0.990.3

**Comment by gimantha** [comment]
public variable references cannot be imported directly. You have to expose them via a function. Define functions in the same module where the streams are defined, and use those functions to create the references.
