### ISSUE TITLE
Move authorization logic and authorization cache to "auth" module

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#14399]
**Description:**
Currently authorization logic resides in `http` module. Logic related to validating authorization should be move to `auth` module instead. 

`Http` module should send the expected `scopes` to the `auth` module and auth module should respond saying if access should be granted or not, based on the `authentication context`. 

Since authorization logic currently resides in `http` module, `authorization cache` also resides in `http` module. These caches should also be moved to `auth` package.

**Comment by ldclakmal** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18042
