### ISSUE TITLE
Cache http:Clients created by the hub for subscribers

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#14425]
**Description:**
With the current implementation, [the hub initiates a new `http:Client`](https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.3/stdlib/websub/src/main/ballerina/websub/hub_service.bal#L441) for a given subscriber, per content delivery request.

Given that content delivery requests could be sent to the same subscriber quite often, it could be beneficial to use a cache for the created clients, instead of initiating a new one per request.

The ballerina/transactions implementation does something similar: https://github.com/ballerina-platform/ballerina-lang/blob/v0.990.3/stdlib/transactions/src/main/ballerina/transactions/commons.bal#L34  

**Affected Versions:**
0.990.3

**Comment by chamil321** [comment]
Issue is fixed via https://github.com/ballerina-platform/ballerina-lang/pull/19546, hence closing
