### ISSUE TITLE
Diagram support for clients anywhere in a block

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#14479]
**Description:**
See Pubudu's comment in #14415.

**Comment by pubudu91** [comment]
It seems endpoints defined inside blocks within a function aren't getting drawn. 

![Screenshot from 2019-03-18 12-16-56](https://user-images.githubusercontent.com/6260009/54511724-d7162780-4977-11e9-9372-c5b3c85b5ce6.png)

**Comment by kaviththiranga** [comment]
We need to make vertical line of the client - only activated for the current scope - and dash out remaining parts of the line.
Eg: if the client object is initailized inside a ``` if ``` block, part of the line parallel to same worker segment will be solid while top and bottom parts will be dashed
