### ISSUE TITLE
Introduce a mechanism to perform cast operation (internally) without type checking

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#14497]
Currently is-check get sugared to a cast-operation internally. i.e:
```ballerina
any a = 5;
if (a is int) {
    int b = a;
}
```
get desguared to:
```ballerina
any a = 5;
if (a is int) {
    int b = <int>a;    // <---
}
```

And the cast operation goes to the runtime as a CHECKCAST, which will do a runtime type check and perform the cast. However, given that this is within the type-guard, the type checking is already done. So no need to perform the type checking once more before casting, as it is an overhead to check the types everytime.

Thus a simple cast is needed in such scenarios. This should be used in all other places as well, where a cast is added at the desugar phase.

**Comment by SupunS** [comment]
This is supported in jballerina side (backend-jvm) now. Whatever cast that gets added in desugar phace will omit the type checking.

However, there are still more places to check and skip the type checking (set the flag in the cast operator) at the type-checker phase.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
