### ISSUE TITLE
Invalid URL created when generating API docs.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#14539]
Refer: https://github.com/ballerina-platform/ballerina-www/issues/1356

**Description:**
While in the Api-Docs > ballerinax/kubernetes > [DeploymentConfiguration](https://ballerina.io/learn/api-docs/ballerinax/kubernetes.html#DeploymentConfiguration) the link for `env` data types 
```
map<string\|kubernetes:FieldRef\|kubernetes:SecretKeyRef\|kubernetes:ResourceFieldRef\|kubernetes:ConfigMapKeyRef>
-- | --
```

links to a 404 -> [here](https://ballerina.io/learn/api-docs/ballerinax/builtin.html#map)
Change `builtin.html#map` to `primitive-types.html#map`

Line reference: https://github.com/ballerina-platform/ballerina-www/blob/a4882a3ca4e9bb7dbc1f656d80193da6bcb064d1/api-docs/docs/ballerinax/kubernetes.html#L2016

I was going to do a PR, but unsure if that's the desired path for the fix. 😄

**Comment by praneesha** [comment]
Closing since this information is now available in the new API Docs in [1].

[1] https://ballerina.io/learn/api-docs/ballerina/kubernetes/records/DeploymentConfiguration.html
