### ISSUE TITLE
Bump swagger-parser from 1.0.34 to 1.0.42

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#14538]
**Description:**
Newest stable release for swagger-parser is available now. So bump the swagger-parser from 1.0.34 to 1.0.42.

There are some test failures when bumping the swagger-parser version to the newest. Need to fix them.

Dependabot PR: https://github.com/ballerina-platform/ballerina-lang/pull/13940

**Comment by nadeeshaan** [comment]
No longer valid, hence closing the issue
