### ISSUE TITLE
[Editor][Improvement] Provide tab closing operations as  IDE's provide

### ISSUE THREAD

**Issue by gvasanka** [ballerina-platform/ballerina-lang#1457]
When user opens many files and work on editor, Its better to provide close operations.

-Close
-Close Others
-Close All
-Close to Right
---etc

![selection_165](https://cloud.githubusercontent.com/assets/3368635/22643806/160855ae-ec86-11e6-9edc-e49627e0c974.png)

**Comment by uthaiyashankar** [comment]
Moved back from https://github.com/ballerina-lang/composer/issues/298

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
