### ISSUE TITLE
Incomplete migration when doing runtime -> runtime-api refactor

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14572]
$Subject in :
https://github.com/ballerina-platform/ballerina-lang/tree/master/stdlib/runtime/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl

New location:
https://github.com/ballerina-platform/ballerina-lang/tree/master/stdlib/runtime-api/src/main/java/org/ballerinalang/stdlib/runtime/nativeimpl

**Comment by Kishanthan** [comment]
Looks like it is already moved, but due to a merge conflict resolve process, this has been left behind.
