### ISSUE TITLE
[JBallerina] Tuple access not supported in BIR

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#14604]
**Description:**
Tuple access is not implemented in BIR gen.

**Steps to reproduce:**
Try building a .bal file with the following snippet to JVM target.
```
(int,int) kk = (100,200);
 int kl = kk[0];
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
This is now supported in jballerina
