### ISSUE TITLE
Language server provides completions including invalid syntax

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#14673]
**Description:**
Current ballerina language server implementation sends invalid texts including place holder syntax, when a language client which does't have snippet support sends a completion request.

**Steps to reproduce:**
Refer the snippet samples below.
![Screenshot from 2019-03-25 17-31-23](https://user-images.githubusercontent.com/29032600/54918353-03a3e380-4f24-11e9-8d7a-9c29f3b0369b.png)

**Affected Versions:**
0.990.4-SNAPSHOT and below.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
