### ISSUE TITLE
Generalize error constructors

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14670]
Refer https://github.com/ballerina-platform/ballerina-spec/issues/2

**Comment by rdhananjaya** [comment]
All error constructor/destructure changes have implemented.

**Comment by rdhananjaya** [comment]
Reopening as mistakenly closed.

**Comment by MaryamZi** [comment]
@rdhananjaya, this is no longer valid, right?

**Comment by rdhananjaya** [comment]
Yes let's close this
