### ISSUE TITLE
Unable to define an empty sealed record

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#14748]
**Description:**
Cannot seal a record with no fields. 

**Steps to reproduce:**
```ballerina
public type ExposeConfig record {||};
```

Output:
`error: ballerinax/docker:0.0.0::annotation.bal:71:34: invalid token '||'`

**Affected Versions:**
0.990.4-SNAPSHOT

**OS, DB, other environment details and versions:**
MAC

**Comment by pubudu91** [comment]
The above works when there's a space between `{|` and `|}`. I'm not sure whether we should support `{||}`.
