### ISSUE TITLE
Introduce LS changes related to external function change

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#14751]
**Description:**
External function definition will be changed with #14608. Creating this issue to track LS related changes required.

Current syntax:
```ballerina
extern function externFunction();
```

New syntax:
```ballerina
function externFunction() = external;
```

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/14596 
#15584

**Comment by NipunaMarcus** [comment]
@roonyh We need to fix the syntax highlighting as well for this ...

**Comment by MaryamZi** [comment]
@nadeeshaan, as discussed offline we've temporarily commented out the "suggestionAfterExtern" test with 56ae017.
