### ISSUE TITLE
Hex floating point literals are always float

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#14775]
**Description:**
Fix $subject in [1] and other places

[1] - tests/ballerina-spec-conformance-tests/S05_simple_values/tests/floating-point-types/decimal.bal

Please refer James response in  https://github.com/ballerina-platform/ballerina-spec/issues/50

**Comment by hasithaa** [comment]
Spec says, `The decimal type corresponds to a subset of IEEE 754-2008 128-bit decimal (radix 10) floating point numbers. Any decimal value can be represented by a DecimalFloatingPointNumber with an optional DecimalTypeSuffix.`

But following behaviour observed with 1.0.2 release. 

```ballerina
public function main() {
    decimal d1 = 0x12abc;    // Should fail, but no compiler errors.
    decimal d2 = 0xab.ce1;   // Correct. Fails with "incompatible types: expected 'decimal', found 'float'" 
}
```
