### ISSUE TITLE
[Task] Publish style guide on Ballerina.io

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#14864]
**Description:**
Need to publish ballerina guide line on ballerina.io website.
- [x] 1st Review Pre-Release
- [x] Review Style guide https://github.com/ballerina-platform/ballerina-lang/issues/15974

**Comment by NipunaMarcus** [comment]
# 1st Review Meeting notes
#### Readme.md
- [ ] swap the parentheses points
- [ ] Explain the Line break point 2 and 3 more to a point that user can understand it..
- [ ] Update line break point 4  example to have more example like function to explain it more
- [ ] make info in to a point in the line break
- [ ] spell check 4th point and fix
- [ ] Add parameter annotation example in annotation formatting section
- [ ] indent the documentation example to be under the point
- [ ] fix 2nd rule to say "after the #"
- [ ] fix 2nd rule spell "symnbol"
- [ ] in the example it should be "description" in the place of description
- [ ] fix rule 4 in documentation "Addonly" to be "add only"
- [ ] in rule 4 name the + to be "parameter marker" and - to be "divider"
- [ ] in documentation shorten the example to explain only what you are trying to say
- [ ] remove this "For more information on how to document Ballerina code, go to How to document 
  Ballerina code." for now
#### Top Level.md
- [ ] Remove "do not indent top level def" from the readme.md and add it to top-level-definitions page
- [ ] Import formatting section in rule #2 remove the "front" and replace it to say before
- [ ] Remove align from the 2nd rule of the function definition 
- [ ] Remove "front" with the related suitable word
- [ ] Fix the rule "Add a single space before the , comma, which separates the parameters." to say 
  "space after the comma"
- [ ] Add line break scenarios of each definitions inside the section belongs to each definition 
  (discussion point)
- [ ] remove Service definition rule 1 
- [ ] How a comma behaves in a list should be a common rule under line spacing section
- [ ]  Merge point 1 and point 2 of the resource definition
- [ ] Shorten the 3rd point of the resource definition
- [ ] Service definition there should be a rule to explain the new http:Listerner (9090) formatting 
- [ ] Remove 2nd rule of the service def
- [ ] Move the global variable rule to line spacing section in readme.md and remove the global variable 
  section.
- [ ] Shorten  3rd rule of the object definition
- [ ] Fix the seal record example in Record definition example
- [ ] Add a rule to service to say follow object def guide lines for function and field definition formatting 
- [ ] Add a rule to service to say resource function should be formatted as functions
- [ ] remove resource definition section
- [ ] remove the linking rule of type referencing from object and record definition
#### Statements.md
- [ ] fix spelling mistake in if statement rule 3 (statemnt)
- [ ] fix if statement rule 4 replace "previous" with matching and remove the symbol of closing brace
- [ ] Remove redundant rules from the if statement rule 4 (remove key word related formatting as it is 
  common rule)
- [ ] edit rule 3 to say if, else if ,and else's statement formatting and remove rule 4 subrule 2
- [ ] Remove rule 5 in if statement
- [ ] change the order of keyword to say "if, else if and else" in if statement empty section rule 2
- [ ] Simplify the if statement empty section rule 2 to say "if empty add an empty line between the 
  opening and closing braces"
- [ ] remove info and the example in the if statement empty section rule 2
- [ ] Remove the first rule of the match statement as it is already define in the block formatting in the 
  readme.md
- [ ] Ask in the ballerina dev google group whether the if statement can be written without the curly braces when the if has only one statement in the body
- [ ] Simplify the 4th rule of the match pattern to say "patten should block indent its statements" also simplify the example. (remove the function ... only match is enough)
- [ ] simplify the last rule of the match pattern to say if empty keep it as a empty block
- [ ] in transaction edit 2nd rule to say "if onretry, committed and aborted blocks are empty, add an 
  empty line between braces" 
#### expression.md
- [ ] in record literal expression simply the 1st rule to say if empty keep it as an empty block
- [ ] remove 2nd rule of the record literal expr
- [ ] remove field section in record literal and merge the rules to record literal expr
- [ ] 1st rule in the field section should be "In a record literal, fields can be arranged on a single line. 
  Then, add space after the comma and leave no spaces between braces and fields."
- [ ] You can define the fields in new lines if so make sure all the fields are in a separate line and they 
  are block indented.
- [ ] merge 2nd and 3rd rule of the record literal
- [ ] remove the last rule of record literal
- [ ] put a example for map literals (inline map and multiline map)
- [ ] in tuple literal if it exceed the line limit move the whole tuple to a new line and indent with four 
  spaces relative to the parent
- [ ] add how to handle function parameter line break
- [ ] Bring function invocation section to the top of the expression.md
- [ ] remove the first rule of function invocation
- [ ] rule 3 should say "argument separating comma should only have a single space after the comma"
- [ ] Order of linked titles should be "top level, operators, statements and expressions"
- [ ] move the 4th rule of the function invocation to the operators
- [ ] remove sub rules of the last rule of the function invo
- [ ] In array literal make subrules of rule 1 to be new rules and remove 3rd subrule and merge 1 and 2 
  subrules.
- [ ] fix "Exampole" spell in array literal
- [ ] remove comma related rule from the subrule of the second rule and write second rule to be similar 
  to the function scenario
- [ ] Fix "be be" in the type casting 
- [ ] Make the table literal formatting to be same as the record literal. just refer to the record literal
#### Operators.md
- [ ] operator 1st rule should be a generic so bring it to readme.md. (keyword always should be 
  followed by a single space.)
- [ ] remove 2nd rule and add dos and don't to the 1st rule modification
- [ ] move rule 3 and 4 as a exception to the modified 1st rule
- [ ]  "pipe should be surounded  by  single spaces if it is a union type"

**Comment by NipunaMarcus** [comment]
Finalizing review part 1
- [ ] Main description 

Ballerina Style Guide aims at maintaining a standard coding style among Ballerina community. 
Therefor Ballerina IDE plugins and tools follow this guide when providing code formatting and other features. 
If you want you can follow your own coding style when writing Ballerina source code. And plugins and tools can be configured to match your coding style.

- [ ] Change “Indentation and length of the lines” to “Indentation and line length”
- [ ] Remove “Spacing” and rename “inline spacing” to “line spacing” and move both this and blank line as main titles
- [ ] Add a simple example like a function and a vardef inside it and Add do and don’t to that  in inline spacing 1st rule
- [ ] Add a note to Blank lines rule saying tools and plugins can be configured to change the number of min and max blank lines. Add a note to the indentation and line length section also.
- [ ] Switch opening and closing rules in parentheses rule 1
- [ ] Edit separator example of the line break rule 2 to match the rule
- [ ] Simplify the rule 3 in line breaks section
- [ ] Line break rule 6 .. sub-rules should start with capitals and simplify the subrule 2
- [ ] Create a new page to include annotations, documentation, and comments and link it to the main page
- [ ] Replace the unnecessary code with “…” in annotation rule 2 example
- [ ] Change the rule 3 to say “Indent each annotation attribute (i.e., key-value pairs) should block indent on its own line.”
- [ ] Last rule in Annotation - Change inline annotation to say “if you are annotating a parameter or a return the annotation should be added inline to parameter or return.”
- [ ] Remove unnecessary example descriptions in last rule in the annotation
- [ ] Top level first rule example shouldn't be more descriptive to see the difference.. Add a comment
- [ ] Remove rule 2 in the Import section
- [ ] Remove separation parentheses for the symbol in first and second rule in the function definition
- [ ] Remove 2nd rule
- [ ] Remove 3rd rule
- [ ] Add symbol name in rule 4 of the function def
- [ ] Remove 5th rule from function def
- [ ] Change 1st rule of service def to say “Keep the listener inline to the service signature.”
- [ ] Change rule 2 example replace unnecessary codes with …
- [ ] 3 rule should be “When indenting function definition, resource definition, and field definitions inside service def should follow block guideline”.
- [ ] Object def - merge rule 1 and 2
- [ ] Add a rule saying “Init function should be defined first” in object def
- [ ] Remove rule in spacing about union type pipe operator 
- [ ] Simplify the example in the 1st rule in the keywords and types
- [ ] Add a proper example for the 2nd rule in the keywords and types
- [ ] Change rule 1 of operators to keep spaces around =
- [ ] Add example for rule 1 and 2 separately and remove int a= 0 from the example of rule 3
- [ ] Remove 2nd rule of keywords and types

**Comment by NipunaMarcus** [comment]
Finalizing Review Phase 2

- [ ] Add a rule for Blocks in ReadMe.md to say block opening brace should be inline and spaced with single space. And add dos and don’ts.
- [ ] In statements 1st rule of if def add dos and don’ts.
- [ ] Remove 2nd and 3rd rule.
- [ ] Simplify the match example string var def in the 4th rule.
- [ ] In expression.MD function invocation 1st rule change “Do not keep spaces between the function name and opening parentheses (.”
- [ ] Remove 2nd rule in function invocation.
- [ ] Add dos and donts example for the record literal last rule.
- [ ] Remove rule 7 in line break and move it to typecast example.
- [ ] New rule import def should be sorted first by the org name then the alias and sorted alphabetically.

**Comment by praneesha** [comment]
Doc review of the style guide is done in https://github.com/ballerina-platform/ballerina-lang/pull/16350.
