### ISSUE TITLE
Support Index Based Access Expressions in constants

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#14882]
**Description:**
In the https://github.com/ballerina-platform/ballerina-lang/pull/14185, only Field based access expressions is supported. Need to add support for Index Based Access expressions as well.

https://github.com/ballerina-platform/ballerina-lang/pull/14185/files/29e9f306d38a7ca170a20430323d2a1402fd24ac#diff-7123076514bbb67aa85076709d29ee0fR2065

**Comment by MaryamZi** [comment]
Support for index based access with map constants was added with https://github.com/ballerina-platform/ballerina-lang/pull/16622. 

With the introduction of the changes to field based access (https://github.com/ballerina-platform/ballerina-lang/pull/16340), it is no longer allowed when accessing maps.
