### ISSUE TITLE
Test failure in Windows due to new line.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14905]
$Subject Happening in following lines.

https://github.com/ballerina-platform/ballerina-lang/blob/b3511dd651b9236620f909917e396016026734aa/stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/request/RequestNativeFunctionNegativeTest.java#L176

https://github.com/ballerina-platform/ballerina-lang/blob/b3511dd651b9236620f909917e396016026734aa/stdlib/http/src/test/java/org/ballerinalang/stdlib/services/nativeimpl/response/ResponseNativeFunctionNegativeTest.java#L158

**Comment by chamil321** [comment]
Fixed by #14910, hence closing the issue
