### ISSUE TITLE
Metrics Does Not Work with the Kafka Connector

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#14927]
$subject, with either the client or the server connector. It gives an error log similar to the following:-

level=warn ts=2019-04-03T17:47:05.202595706Z caller=scrape.go:836 component="scrape manager" scrape_pool=prometheus target=http://196.168.10.12:9797/metrics msg="append failed" err="invalid metric type \"0.0:SimpleProducer_requests_total_value counter\""

With this, the metrics are not calculated to any aspect in the system.

**Comment by Anoukh** [comment]
Closing the issue since fix has been merged with master.
