### ISSUE TITLE
Inconsistent behaviour when building object-initializer BBE

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#14921]
When I add the following test file to the object-initializer module and try to build it, it results in an NPE at the native level when running the tests. However, when I copy the same two files into a new project created elsewhere and try to build, it runs fine. 
```ballerina
import ballerina/test;
import ballerina/io;

any[] outputs = [];
int counter = 0;

@test:Mock {
    moduleName: "ballerina/io",
    functionName: "println"
}
public function mockPrint((any|error)... s) {
    outputs[counter] = io:sprintf("%s", s[0]);
    counter += 1;
}

@test:Config
function testFunc() {
    main();
    //test:assertEquals(outputs[0], "{name:\"John\"}");
    //test:assertEquals(outputs[1], "Invalid name format {}");
}
```

**Comment by hemikak** [comment]
As of now placing with file at the level as "object_initializer.bal" does not make sense. You will need to make the object-initalizer as a module of the parent folder and have this test inside "tests" folder of "object-initalizer" folder.

**Comment by pubudu91** [comment]
What I meant was the tests dir of the object-initializer module. I think we'll first have to refactor the BBEs to conform to the new Packerina changes to verify this.

**Comment by Dilhasha** [comment]
This issue is not applicable anymore.
