### ISSUE TITLE
mysql->batchUpdate() doesn't return error messages?

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#14947]
**Description:**
Today I was running batchUpdate() on a table which doesn't exist in the database, and it was returning [-3]. Can't we provide more details on the error?

**Comment by anupama-pathirage** [comment]
Can you please check this API documentation.

- A number greater than or equal to zero - indicates that the command was processed successfully and is an update count giving the number of rows 
- A value of -2 : Indicates that the command was processed successfully but that the number of rows affected is unknown
- A value of -3 : Indicates that the command failed to execute successfully and occurs only if a driver continues to process commands after a command fails

[1] https://ballerina.io/learn/api-docs/ballerinax/jdbc.html#Client-batchUpdate

**Comment by raj-rajaratnam** [comment]
Thanks @anupama-pathirage, as discussed, please consider propagating DB level exceptions to ballerina.

**Comment by Manuri** [comment]
Addressed with https://github.com/ballerina-platform/ballerina-lang/pull/16642
