### ISSUE TITLE
Improve the optional types BBE

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#14943]
The optional types BBE is a bit outdated now, with the introduction of optional fields in records. Need to improve the optional types BBE to distinguish between the optional fields in records and optional types. Those two terms cannot be used interchangeably.

**Comment by MaryamZi** [comment]
The optional type BBE was updated with https://github.com/ballerina-platform/ballerina-lang/pull/17094. This BBE does not talk about optional fields in records now. 

The [optional field access BBE](https://github.com/ballerina-platform/ballerina-lang/tree/master/examples/optional-field-access) talks about optional fields and nillable fields in records, and how to access them.
