### ISSUE TITLE
Byte to int and byte[] to int[] assignments should be supported

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#14960]
**Description:**
According to the Ballerina specification,  `byte` is simply a finite subset of `int` values which contains values ranging from 0 to 255.  Hence, byte values should be assignable to int values, and byte arrays should be assignable to int arrays. 

```ballerina
public function main() {
    byte b = 2;
    int i = b; // case 1

    byte[] bArr = [1, 3, 4];
    int[] iArr = bArr; // case 2
}
```
 Both the above cases are expected to work. However, currently both fail with the below compile time errors:
```
incompatible types: expected 'int', found 'byte'
incompatible types: expected 'int[]', found 'byte[]'
```

**Comment by MaryamZi** [comment]
Shall we use https://github.com/ballerina-platform/ballerina-lang/issues/14366 to track this?

**Comment by pranavan15** [comment]
> Shall we use #14366 to track this?

+1. Closing this issue as it is a duplicate of #14366.
