### ISSUE TITLE
Review required for BBE doc change related PRs merged for 0.991.0

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#14969]
**Description:**
The following BBE doc change related PRs were/are being merged for the 0.991.0 release without doc reviews by @praneesha, due to time constraints.

- https://github.com/ballerina-platform/ballerina-lang/pull/14952
- https://github.com/ballerina-platform/ballerina-lang/pull/14920
- https://github.com/ballerina-platform/ballerina-lang/pull/14911
- https://github.com/ballerina-platform/ballerina-lang/pull/14922
- https://github.com/ballerina-platform/ballerina-lang/pull/14928
- https://github.com/ballerina-platform/ballerina-lang/pull/14917

Creating this issue to keep track of these PRs and introduce any improvements/changes required.

**Comment by praneesha** [comment]
Reviewed the below files for https://github.com/ballerina-platform/ballerina-lang/pull/14952.

**Comment by praneesha** [comment]
Reviewed the below files 

- examples/anydata-type/anydata_type.bal
- examples/anydata-type/anydata_type.description
- examples/clone/clone.bal
- examples/clone/clone.description
- examples/documentation/documentation.bal
- examples/elvis-operator/elvis_operator.bal
- examples/elvis-operator/elvis_operator.description
- examples/hello-world-client/hello_world_client.bal
- examples/hello-world/hello_world.description
- examples/immutable-values/immutable_values.bal
- examples/the-main-function/the_main_function.bal
- examples/type-check-expression/type_check_expression.description
- examples/type-guard/type_guard.bal
- examples/type-guard/type_guard.description
- examples/type-guard/type_guard.out
- examples/type-test-expression/type_test_expression.description
- examples/type-test-expression/type_test_expression.out
- examples/var/var.description
- examples/type-test-expression/type_test_expression.bal

**Comment by praneesha** [comment]
Reviewed the below files for #14911 via #.

examples/closures/closures.bal
examples/closures/closures.out
examples/constants/constants.bal
examples/constants/constants.description
examples/foreach/foreach.bal
examples/function-pointers/function_pointers.bal
examples/functional-iteration/functional_iteration.bal
examples/length/length.bal
examples/length/length.description
examples/locks/locks.bal
examples/locks/locks.descriptionexamples/match/match.balexamples/record-match-statement/record_match_statement.balexamples/record-match-statement/record_match_statement.description
examples/tuple-match-statement/tuple_match_statement.bal
examples/tuple-match-statement/tuple_match_statement.description
examples/tuple-type-binding-pattern/tuple_type_binding_pattern.bal
examples/xml-access/xml_access.bal
examples/xml-access/xml_access.descriptionexamples/xml-attributes/xml_attributes.balexamples/xml-attributes/xml_attributes.outexamples/xml-literal/xml_literal.balexamples/xml-literal/xml_literal.description
examples/xml-namespaces/xml_namespaces.bal
examples/xml-to-json-conversion/xml_to_json_conversion.description

**Comment by praneesha** [comment]
Reviewed the below files for #14922 via #15690.

- examples/abstract-objects/abstract_objects.bal
- examples/abstract-objects/abstract_objects.description
- examples/anonymous-objects/anonymous_objects.bal
- examples/object-assignability/object_assignability.bal
- examples/object-assignability/object_assignability.description
- examples/object-member-functions/object_member_functions.description
- examples/object-methods/object_methods.bal
- examples/object-methods/object_methods.description
- examples/object-methods/tests/object_methods_test.bal
- examples/object-type-reference/object_type_reference.bal
- examples/object-type-reference/object_type_reference.description
- examples/objects/objects.bal
- examples/objects/objects.description
- examples/record-optional-fields/record_optional_fields.bal
- examples/records/records.bal

**Comment by praneesha** [comment]
Reviewed the below examples for #14928 via #15690.

- [ ] examples/anonymous-functions/
- [ ] examples/any-type/
- [ ] examples/arrays/
- [ ] examples/async/
- [ ] examples/byte-io/
- [ ] examples/byte-type/
- [ ] examples/cache/
- [ ] examples/channels-workers/
- [ ] examples/character-io/
- [ ] examples/check/
- [ ] examples/client-generation/
- [ ] examples/compound-assignment-operators
- [ ] examples/csv-io/
- [ ] examples/data-io/
- [ ] examples/directory-listener
- [ ] examples/equality/
- [ ] examples/error-handling/
- [ ] examples/error-lifting/
- [ ] examples/fork-variable-access/
- [ ] examples/fork
- [ ] examples/functions-with-defaultable-parameters/
- [ ] examples/functions-with-rest-parameter/
- [ ] examples/functions/
- [ ] examples/h2-client/
- [ ] examples/hello-world-parallel/
- [ ] examples/hello-world-service/
- [ ] examples/http-client-endpoint/
- [ ] examples/http-redirects/
- [ ] examples/if-else/
- [ ] examples/integer-ranges/
- [ ] examples/jms-durable-topic-message-subscriber/
- [ ] examples/jms-headers-and-properties/
- [ ] examples/jms-queue-message-producer/
- [ ] examples/jms-queue-message-receiver-with-client-acknowledgment/
- [ ] examples/jms-queue-message-receiver/
- [ ] examples/jms-simple-topic-message-subscriber/
- [ ] examples/jms-synchronous-queue-message-receiver/
- [ ] examples/jms-topic-message-producer/
- [ ] examples/join-multiple-streams/
- [ ] examples/join-tables-and-streams/
- [ ] examples/json-arrays/
- [ ] examples/json-csv/
- [ ] examples/json-io/
- [ ] examples/json-record-map-conversion/
- [ ] examples/json-to-xml-conversion/
- [ ] examples/json/
- [ ] examples/local-transactions-with-participants/
- [ ] examples/local-transactions/
- [ ] examples/log-api/
- [ ] examples/maps/
- [ ] examples/match/
- [ ] examples/math-functions/
- [ ] examples/modules/
- [ ] examples/mysql-client/examples/nats-basic-client/
- [ ] examples/nil-lifting
- [ ] examples/object-initializer/
- [ ] examples/optional-type/
- [ ] examples/panic/
- [ ] examples/projection/
- [ ] examples/record-destructure-binding-pattern/
- [ ] examples/record-io
- [ ] examples/record-iteration/
- [ ] examples/record-type-binding-pattern/
- [ ] examples/record-type-reference/
- [ ] examples/simple-filtering/
- [ ] examples/stamp/
- [ ] examples/streams/
- [ ] examples/string-template/
- [ ] examples/strings/
- [ ] examples/table-queries/
- [ ] examples/table/
- [ ] examples/taint-checking/
- [ ] examples/task-scheduler-timer
- [ ] examples/temporal-aggregations-and-windows/
- [ ] examples/testerina-assertions/
- [ ] examples/testerina-before-and-after-suite/
- [ ] examples/testerina-before-and-after-test/
- [ ] examples/testerina-before-each-test/
- [ ] examples/testerina-data-driven-tests/
- [ ] examples/testerina-function-mocks/
- [ ] examples/testerina-group-tests/
- [ ] examples/testerina-guarantee-test-execution-order/
- [ ] examples/time/
- [ ] examples/trap/
- [ ] examples/tuple-destructure-binding-pattern/
- [ ] examples/tuple-type-binding-pattern/
- [ ] examples/tuple-type/
- [ ] examples/type-conversion/
- [ ] examples/union-type/
- [ ] examples/values/
- [ ] examples/variables/
- [ ] examples/websub-hub-client-sample/
- [ ] examples/websub-internal-hub-sample/
- [ ] examples/websub-remote-hub-sample/
- [ ] examples/websub-service-integration-sample/
- [ ] examples/while/
- [ ] examples/worker-interaction/
- [ ] examples/workers/
- [ ] examples/xa-transactions/
- [ ] examples/xml-functions/
- [ ] examples/xml-io/
- [ ] examples/xml/
- [ ]

**Comment by praneesha** [comment]
All the files of the examples/object-initializer that were changed in #14917 are already reviewed above.
