### ISSUE TITLE
Large decimal values using int literals are not supported

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#14983]
**Description:**
```ballerina
decimal d = 10000000000000000123;
```
Results in `Integer '10000000000000000123' too large` error.
This should not be the case since decimal can hold larger numbers than this.

However following does work.
```ballerina
decimal d = 10000000000000000123.0;
```
**Affected Versions:**
0.991

**Comment by SupunS** [comment]
In the new parser, integer values are parsed and returned as a string. string-to-int parsing is done in the BLangPackageBuilder/BLangNodeTransformer. 

This logic may needs to be moved to the semantic-analyzer/desugar phase to solve the mentioned issue.
