### ISSUE TITLE
Invalid data provider is generated from the Generate Test Code action

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#14996]
**Description:**
Consider the following source snippet
```
public function name(error s) {
  io:println("test");
}
```
When the "Generate Test" code action is invoked, following invalid data provider is generated.

```
function testName(error s) {
    name(s);
}

function testNameDataProvider() returns ((error)[]) {
    return [(0), (error("")), (error("")), (error(""))];
}
```
return statement has the following diagnostic
**_array element type 'error' does not have an implicit initial value, use 'error?'_**

**Comment by rasika** [comment]
Let's assume our source function is as below;
```ballerina
public function name(error s) {
  io:println("test");
}
```

Test generation for the above function would look like below;
```ballerina
@test:Config {
    dataProvider: "testNameDataProvider"
}
function testName(error s) {
    name(s);
}

function testNameDataProvider() returns ((error)[]) {
    return [(error("fff"))];
}
```
But above code gives error `array element type 'error' does not have an implicit initial value, use 'error?'`

However, below works fine.
```ballerina
@test:Config {
    dataProvider: "testNameDataProvider"
}
function testName(error s) {
    name(s);
}

function testNameDataProvider() returns ((error?)[]) {
    error r = error("fff");
    return [(r)];
}
```

Need to verify the correct-way.
