### ISSUE TITLE
Invalid "ballerina openapi gen-service" Code Generated

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#15001]
For example, it generates code similar to below:

```
    resource function getPetById (http:Caller outboundEp, http:Request _getPetByIdReq, string petId) returns error? {
        http:Response _getPetByIdRes = getPetById(_getPetByIdReq, petId);
        _ = outboundEp->respond(_getPetByIdRes);
    }

```
The return value from "respond" action is ignored here, where it can't be ignored now, since it is an error value, thus resulting in a compile error.

**Comment by lafernando** [comment]
Also, we need automated tests for this.

**Comment by DimalChandrasiri** [comment]
The PR has been sent to fix the issue to the ballerina master branch, and I have attached a patch for version 0.991.0 to fix this issue. Please extract and copy the `openapi-to-ballerina-generator-0.991.0.jar` to the following path replacing the current jar.

`$BALLERINA_HOME\bre\lib` 

[openapi-to-ballerina-generator-0.991.0.jar.zip](https://github.com/ballerina-platform/ballerina-lang/files/3147465/openapi-to-ballerina-generator-0.991.0.jar.zip)

**Comment by lafernando** [comment]
Thanks!.
