### ISSUE TITLE
Native implementations using function pointers not updated with the closure changes

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#15047]
With the recent changes to closures, now the first parameter of a lambda function is a `map<any|error>` value. Native functions which makes use of parameters of a lambda function should take this into account. 

Originally reported in Slack: https://ballerina-platform.slack.com/archives/C47EAELR1/p1555461582018400

**Comment by pubudu91** [comment]
This was fixed for `remove()` in tables with PR #15059. Need to verify other std lib functions using lambda functions don't have the same issue.

**Comment by vinok88** [comment]
This requires verification from standard library side.

**Comment by wggihan** [comment]
We are not using in the StdLib modules.
