### ISSUE TITLE
[NATS] Add missing connection options in endpoint configuration

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#15081]
**Description:**
$subject.

Currently we only support following options in endpoint configurations,
- connectWait
- maxPubAcksInFlight
- pubAckWait

Check other missing options and enable them in endpoint configurations.

**Affected Versions:**
0.991.0

**Comment by daneshk** [comment]
Refer https://nats.io/documentation/writing_applications/connecting/?lang=java

**Comment by Manuri** [comment]
These have been introduced with NATS connector resigning effort.
https://github.com/ballerina-platform/ballerina-lang/pull/16492
