### ISSUE TITLE
Syntax highlighting issue in IntelliJ IDEA

### ISSUE THREAD

**Issue by isharailanga** [ballerina-platform/ballerina-lang#15087]
**Description:**

There seems to be an issue in syntax highlighting (from line 69) 
![image](https://user-images.githubusercontent.com/14251853/56360918-aab62b00-6203-11e9-8104-74598af15592.png)

**Steps to reproduce:**
-
**Affected Versions:**
Ballerina 0.990.2

**OS, DB, other environment details and versions:**
IDE - IntelliJ IDEA Ultimate 

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
@isharailanga Could you please provide the intellij plugin version you are using?

**Comment by isharailanga** [comment]
@NipunaRanasinghe v0.990.1
