### ISSUE TITLE
Intermittent failure - Ballerina tools integration tests - ServicePackagingTestCase

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#15149]
**Description:**
Intermittent failure - [ServicePackagingTestCase ](https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/ballerina-tools-integration-test/src/test/resources/testng.xml#L43)
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by wggihan** [comment]
This is fixed now.
