### ISSUE TITLE
Need an option for HTTP client endpoint to disable the SSL Certificate Validation.

### ISSUE THREAD

**Issue by hejunchen** [ballerina-platform/ballerina-lang#15147]
**Description:**
I am coding in Ballerina to make HTTP request against an internal web services. The internal web service has self-signed SSL certificate.

I can add that self-signed certificate into my truststore.p12 file, but I want to see if there is an option to allow me disable the SSL validation?

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/6847102/56674390-cfc8f480-666e-11e9-886a-d173707b7456.png)

I don't want to attach the p12 file for each application written in Ballerina, neither I want to manually add each Self-Signed SSL Cert to Ballerina's Home directory's p12 truststore. There shall be an easy way to disable the SSL Cert. If we are writing Ballerina code for integration parts, there are a lot of chances that the code is only wiring up with the internal service. Self-Signed SSL Cert is widely used if the application is only implemented inside company's internal network. 

other languages such as Python allows to disable the SSL validation via an optional parameter

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
SSL, Self-Signed Certificate

**Comment by Bhashinee** [comment]
@hejunchen Thanks for reporting this issue. 
We are discussing [this](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/ballerina-dev/Disable$20SSL$20validation$20check%7Csort:date/ballerina-dev/lMG516IV6lM/YNU1mPGbAgAJ) with the team. Hopefully this feature will be added in a future release.
