### ISSUE TITLE
[Gradle] Code coverage reports are not generated for integration tests

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#15148]
**Description:**
Code coverage reports are not generated for integration tests. 
This is because main source dir for these projects are empty. Maven build overcome this by running a jacoco agent and aggregating results.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by azinneera** [comment]
We have integrated CodeCov, hence this issue can be closed.
