### ISSUE TITLE
Odd behavior with channels when receiver times out

### ISSUE THREAD

**Issue by chintana** [ballerina-platform/ballerina-lang#15156]
**Description:**
I'm trying out the basic channel example here - https://ballerina.io/learn/by-example/channels-correlation.html

After running the server, you can send and receive without any issue. Then if a receiver times out, subsequent sends will succeed but throws an error at the server side. Then any receive after that will not get any message.

**Steps to reproduce:**

1. Put the example here to a .bal file and start it - https://ballerina.io/learn/by-example/channels-correlation.html (I've changed the resource paths in below example)
2. Start the receiver and let it times out
```
$ curl localhost:9090/channelSvc/receive
Server time out
```
3. Then do a send
```
$ curl -X POST localhost:9090/channelSvc/send -H "Content-type: application/json" -d '{"message": "TestMe"}'
{"send":"Success!"}
``` 
4. Following error message can be observed at the server side
```
2019-04-25 14:13:54,352 ERROR [] - Error sending response : {ballerina/http}HTTPError {message:"Connection between remote client and host is closed"}
```
5. Now if you try to do the receive operation again, no messages are received

**Affected Versions:**
Ballerina 0.991.0

**OS, DB, other environment details and versions:**
macos Mojave

**Comment by vinok88** [comment]
Channels have been deprecated with the PR https://github.com/ballerina-platform/ballerina-lang/pull/16390
