### ISSUE TITLE
Syntax highlighting is not working for function pointers

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#15168]
Syntax highlighting is not working for function pointers

ballerina version : Ballerina 0.991.0

Use the following code to reproduce the issue and refer the image for more details.

![image](https://user-images.githubusercontent.com/16300038/56861295-2c087d00-69bd-11e9-9578-e5826b615434.png)

```ballerina
import ballerina/io;

// The `test` function acts as a variable function pointer in the `main` function
function test(int x, string s) returns float {
    return 10.5;
}

// Function pointer as a parameter. Use the `.call()` method to invoke the function using the function pointer.
function foo(int x, function (int, string) returns float bar) 
             returns float {
    return x * bar.call(10, "2");
}

public function main() {
    // Value `test` will serve as a function pointer to the `foo` function.
    io:println("Answer: " + foo(10, test));
}
```
Extension version: 0.991.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2162)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (0.20GB free)|
|Process Argv|bbetest/|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kaviththiranga** [comment]
@roonyh did we fix it?

I viewed above code snippet in 0.991.2 and looks fine to me.

<img width="1213" alt="Screen Shot 2019-06-10 at 10 01 16 AM" src="https://user-images.githubusercontent.com/1505855/59172633-bf110700-8b66-11e9-8da3-2f5d20ba3580.png">

**Comment by roonyh** [comment]
Its not fixed. The identifier `bar` from above should be highlighted in light blue.

**Comment by kaviththiranga** [comment]
@roonyh ah ok. But the things that @anupama-pathirage has highlighted in the screenshot are resolved right?
