### ISSUE TITLE
Match expression should support regex

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#15189]
**Description:**
It's a feature request. 

```
    match signal {
        "NOT.*" => signalId = "300";
        "CANCELLED" => signalId = "600";
        "SHIPPED" => signalId = "500";
        "MAKE" => signalId = "400";
        "DELAYED" => signalId = "1100";
    }
```

This NOT.* regex should match NOT_SHIPPED signal which is not happening right now.

**Comment by hasithaa** [comment]
@raj-rajaratnam Can you move/recreate this issue in the ballerina-spec repo? Language feature requests should be captured in ballerina-spec.

**Comment by hasithaa** [comment]
According to the spec following should work.  But this doesn't work with the current compiler. (This is captured in #15199)

```ballerina
match x {
  y if y is string && check y.matchesWithRegex("NOT.*") => signalId = "300";
  "CANCELLED" => signalId = "600";
}
```

**Comment by jclark** [comment]
I think it would also be coherent to have first-class support for regexes in the language including in match patterns (as JavaScript and Perl do).  We had this on our internal list. I have made an issue for it also.

https://github.com/ballerina-platform/ballerina-spec/issues/92

**Comment by hasithaa** [comment]
Closing this issue since we have captured this requirement in https://github.com/ballerina-platform/ballerina-spec/issues/92
