### ISSUE TITLE
Module Cannot Import Another Module in the Same Organization

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#15217]
When creating a module, that imports another module in the same organization, the import fails telling it cannot find the module.

The attached zip file contains a module that can be used for testing this scenario.

Version: 0.991.0

[test.zip](https://github.com/ballerina-platform/ballerina-lang/files/3146109/test.zip)

**Comment by hemikak** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/17671. Hence closing.
