### ISSUE TITLE
Windows test failures

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#15216]
**Description:**
$title
**Steps to reproduce:**
Run a build with tests in a windows environment
- [x] stdlib/filepath/PathTest
- [x] ballerina-integration-test/testAuthnWithJWTSignedWithExpiredTrustedCertificateWithNoExpiryValidation
- [x] ballerina-integration-test/testUnaryHelloWorldWithoutOutputPath
- [ ] stdlib/http/IdleTimeoutResponseTestCase
- [x] ballerina-integration-test/testUnaryHelloWorldWithoutOutputPath
- [ ] ballerina-integration-test/IdleTimeoutResponseTestCase
- [ ] ballerina-integration-test/HttpResiliencyTest
- [x] ballerina-integration-test/CancelledFuturesWithTrxTest
- [x] ballerina-integration-test/MicroTransactionTestCase
- [x] ballerina-integration-test/ClientInitializationFailureTest
- [x] ballerina-integration-test/ServiceUnavailableTestCase
- [x] ballerina-integration-test/ServerStreamingTestCase
- [x] ballerina-integration-test/StubGeneratorTestCase
- [x] ballerina-integration-test/ProtoMessageTestCase
- [x] ballerina-integration-test/TableToXMLStreamingTestCase

**Comment by riyafa** [comment]
Shall we attache the log file for these failing tests as well because most of us don't have Windows machine?

**Comment by pahans** [comment]
@riyafa We didn't collect logs because lots of tests are failing in windows. There are temporary windows machines available with the team or we can request for more if that is not enough.

**Comment by ldclakmal** [comment]
This is the updated list as of today. Logs are attached herewith.

- [ ] ServiceLevelAuthnTest/testAuthnWithJWTSignedWithExpiredTrustedCertificate
- [ ] ServiceLevelAuthnTest/testAuthnWithJWTSignedWithExpiredTrustedCertificateWithNoExpiryValidation
- [ ] TableToXMLStreamingTestCase
- [ ] TableToXMLStreamingTestCase
- [ ] CancelledFuturesWithTrxTest
- [ ] ArtemisTestCommons
- [ ] ServiceUnavailableTestCase/testUnavailableServiceInvoke
- [ ] IdleTimeoutResponseTestCase/test408Response
- [ ] HttpResiliencyTest
- [ ] ClientInitializationFailureTest/testClientEndpointFailureInResource
- [ ] MicroTransactionTestCase

[build.zip](https://github.com/ballerina-platform/ballerina-lang/files/3176161/build.zip)

**Comment by ldclakmal** [comment]
This is the updated list as of today. Logs are attached herewith. [reports-15-05-2019.zip](https://github.com/ballerina-platform/ballerina-lang/files/3180855/reports-15-05-2019.zip)

ArtemisTestCommons. start
IdleTimeoutResponseTestCase. test408Response
HttpResiliencyTest.
ClientInitializationFailureTest. testClientEndpointFailureInResource
SocketBaseTest. start

**Comment by riyafa** [comment]
I am not sure it is easy to figure out the reason why `IdleTimeoutResponseTestCase` is failing https://stackoverflow.com/questions/14304658/c-sharp-an-established-connection-was-aborted-by-the-software-in-your-host-machi

**Comment by chamil321** [comment]
The following test cases are outdated and no longer maintained in this repo. Hence closing the issue. 

- [ ] ArtemisTestCommons. start
- [ ] IdleTimeoutResponseTestCase. test408Response
- [ ] HttpResiliencyTest.

PS: Existing windows test failures are captured via [these issues](https://github.com/ballerina-platform/ballerina-standard-library/issues?q=is%3Aopen+is%3Aissue+label%3Amodule%2Fhttp+windows+tests)
