### ISSUE TITLE
Avoid using hardcoded jvm path in lang-server launcher script

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#15248]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/blob/a4adbce1ca032d2d27d635a946397624d6003554/distribution/zip/ballerina-tools/resources/language-server-launcher.sh#L110-L112

This breaks when the jvm packed in runtime get's changed. Use a wild card logic to fix this.

**Comment by rasika** [comment]
The old jre was `$BALLERINA_HOME/bre/lib/jre1.8.0_172`. new one is `$BALLERINA_HOME/bre/lib/jdk8u202-b08-jre`.

There's no name convention or pattern is naming for jvm. We can't write a wild card expression matching **jre1.8.0_172** and **jdk8u202-b08-jre**. Only **common thing** is that this is the only folder in `$BALLERINA_HOME/bre/lib/`.

I can think of below solutions;

1. Use a pattern recognition to detect the folder name of the `$BALLERINA_HOME/bre/lib/` (bit silly, though...).
2. Enforce a folder name pattern such as **jvm\<version>** eg. jvm1.8.0_172
3. Move the LS launcher script into `$BALLERINA_HOME/bin` folder so who ever change the JDK won't miss this.

**Comment by kaviththiranga** [comment]
We need to address below issue.

Runtime launcher scripts and jvm logic is in distribution repo.
LS scripts are in lang repo.
When the JVM is changed on distribution repo, LS scripts were not updated.

Either we also have to move the LS scripts there or add a test in distribution repo to make sure LS starts fine in each distribution - this will be tricky though as distribution should be tested on each different platform
