### ISSUE TITLE
[Spec Deviation] The `typedesc` returned by `typeof` is not in line with the spec

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#15278]
Pls refer https://github.com/ballerina-platform/ballerina-spec/issues/106

Currently typedesc only contain widen type, this also need to include the narrow type.

typedesc a = typeof 1;

Internally 'a' should contain both 'int' (1 is a int at this context) and singleton type '1' as the narrow type.

**Comment by MaryamZi** [comment]
There are a couple of deviations:

The 2019r3 spec says

```
typeof-expr := typeof expression

The result of a typeof-expr is a typedesc value for the runtime type of v, 
where v is the result of evaluating expression.

The runtime type of v is the narrowest type to which v belongs.
```


- When v is a **simple value**, the resulting typedesc will describe **a type consisting of a single shape**, which is the shape of the value. The typedesc will not have any annotations. **Each evaluation** of typeof with a simple value **produces a new typedesc value**.

```ballerina
import ballerina/io;

public function main() {
    int i = 1;

    typedesc<any> t1 = typeof i;
    typedesc<any> t2 = typeof i;

    io:println(t1 === t2);      // false
    io:println(t1.toString());  // typedesc int - should be 1
    io:println(t2.toString());  // typedesc int - should be 1
}
```

- When v is a reference value, **each evaluation** of typeof with an **identical reference value produces an identical typedesc value**. The **type descriptor resulting from typeof will be the same as the type descriptor used to construct the value**. For containers, this is the same as the inherent type;
```ballerina
import ballerina/io;

public function main() {
    Foo f = { s: "test" };

    typedesc<any> t1 = typeof f;
    typedesc<any> t2 = typeof f;
    typedesc<any> t3 = Foo;

    io:println(t1 === t2);      // false - should be true
    io:println(t2 === t3);      // false - should be true
}

type Foo record {
    string s;
};
```

- when the container is immutable, it will be a singleton type
```ballerina
import ballerina/io;

public function main() {
    map<string|int> f = { s: "only", t: "strings", u: "here" };
    any f2 = f.cloneReadOnly();

    typedesc<any> t = typeof f2;
    io:println(t.toString());    // false - should be map<string>
}
```
