### ISSUE TITLE
Diagram view for the project

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#15271]
**Description:**
We have been discussing some improvements to Diagram in a new specification https://docs.google.com/document/d/1zOF1lTMqzzrlufe92vqMm4LebV2bo_wE31ARw31rBJ8/edit?usp=sharing

This is to track implementation progress of the suggested new DIagram view per project.

Tasks:

- [x] Add LS extension ``` project/model ``` which returns a JSON model for the project
- [x] Create react components to render project view
- [x] Handle smooth transition from per file view to project view and vice versa

**Comment by nadeeshaan** [comment]
Closing since the changes have been completed
