### ISSUE TITLE
Boolean is written ad float in ConfigurationRegistry

### ISSUE THREAD

**Issue by dirkwall** [ballerina-platform/ballerina-lang#15284]
https://github.com/ballerina-platform/ballerina-lang/blob/1817fa2d0a74045ba2feb9398b93dab3514265c3/stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/SetConfig.java#L63

Should be:
```
CONFIG_REGISTRY.addConfiguration(configKey, ((BBoolean) configValue).booleanValue());
```

This could be the reason why I had troubles with setting and retrieving Boolean through `config:setConfig(...)` and `config:getAsBoolean(...)`

**Comment by pubudu91** [comment]
Closing this since the issue mentioned here is now resolved in master. 
https://github.com/ballerina-platform/ballerina-lang/blob/da4b569d5f99e55a9a93eb1a219a2c02f50d035f/stdlib/config-api/src/main/java/org/ballerinalang/stdlib/config/SetConfig.java#L40
