### ISSUE TITLE
Should we make the output destination of ballerina-internal.log configurable?

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#15290]
Recently, Raj raised some concerns regarding the ballerina-internal.log file. Currently we log anything internal related to the runtime (i.e., stuff the user doesn't have to worry about) to a file named ballerina-internal.log then and there. However, if we are considering a containerized deployment where the logs are collected and published to a separate log management tool, we will be missing out the logs contained in the ballerina-internal.log file. While the user doesn't have to worry about this file, it may be important for *us* if we are to troubleshoot what went wrong.

**Comment by hasithaa** [comment]
@hevayo @sameerajayasoma Do we need to prioritize this for SL? I guess we can move this after SL.

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/issues/31079
