### ISSUE TITLE
npm build fails on composer integration tests 

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#15344]
composer integration tests are disabled right now for [gradle build.]( https://github.com/ballerina-platform/ballerina-lang/blob/master/settings.gradle#L92)  
npm build command for composer integration tests returns 
![image](https://user-images.githubusercontent.com/1552869/57976086-32a37680-79f6-11e9-995a-7632be3abd14.png)
seems its missing typescript from dependencies but when I add it. 
It returns a different error
![image](https://user-images.githubusercontent.com/1552869/57976096-5c5c9d80-79f6-11e9-8f3d-382304f8c1cf.png)

**Comment by kaviththiranga** [comment]
@pahans I can see typescript in dev deps https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/composer-integration-test/package.json#L41

**Comment by kaviththiranga** [comment]
@pahans there is a prebuild script which needs to be executed in order to build to work fine
https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/composer-integration-test/package.json#L7

**Comment by kaviththiranga** [comment]
It takes care of linking local composer modules

**Comment by hevayo** [comment]
No longer relevent
