### ISSUE TITLE
Go to source support is not enabled for declaration statements. 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15388]
**Description:**
Go to source support is not enabled for declaration statements. 
 _eg_ : clicking on req to jump to source will not work

![image](https://user-images.githubusercontent.com/10986966/58231218-14ba7680-7d54-11e9-9abb-e0216f5bb0bb.png)

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
