### ISSUE TITLE
Tool tip doesn't have the full representation of the url  

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15386]
**Description:**
The tooltip for the bellow code will not appear correctly.
`http:Client clientEP = new("http://www.mocky.io");`

*- Reason*
SourceGen assumes that // in the code is a comment.

![image](https://user-images.githubusercontent.com/10986966/58230194-441bb400-7d51-11e9-8cf9-367a53b001d2.png)

**Steps to reproduce:**
Open Example  hello_world_client.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
