### ISSUE TITLE
IF/else in While statements is rendering incorrectly

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15389]
**Description:**
IF/else in While statements is rendering incorrectly

![image](https://user-images.githubusercontent.com/10986966/58231408-914d5500-7d54-11e9-8bc3-ccc9db311e50.png)

it should be represented like this 

![image](https://user-images.githubusercontent.com/10986966/58231591-0587f880-7d55-11e9-8732-f3363b767313.png)

**Steps to reproduce:**
- Add a while statement, and then 
- and a if statement inside the while statement

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by nadeeshaan** [comment]
FIxed in the latest master as per bellow. Hence closing the issue.

![Screenshot 2020-01-02 at 17 03 35](https://user-images.githubusercontent.com/1329674/71665186-ec7f0580-2d81-11ea-9803-07c673b8acee.png)
