### ISSUE TITLE
Namespace declaration is not supported

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15396]
**Description:**
Namespace declaration is not supported

![image](https://user-images.githubusercontent.com/10986966/58241604-eeec9c00-7d6a-11e9-932c-1e56fc3abcf1.png)

**Steps to reproduce:**
refer example : xml_namespace.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by kaviththiranga** [comment]
Namespace declaration statements are not shown in diagram in expanded mode

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
