### ISSUE TITLE
Remove function expand from invocation statements where expanding is not possible

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15392]
**Description:**
io:println statements should not have function expand option 
![image](https://user-images.githubusercontent.com/10986966/58237534-e8f2bd00-7d62-11e9-8a25-4c770acc2806.png)

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by kaviththiranga** [comment]
We cannot expand some invocation where we cannot get the parse tree. In such cases we should not display the expand icon.
As per the offline conversation with @roonyh, this is technically possible after the improvements done to AST for project level diagram view.

**Comment by roonyh** [comment]
This is fixed in 1.0.0-alpha with the new diagram overview feature
