### ISSUE TITLE
Error in the object name

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15395]
**Description:**
Error in the object name that is appearing
![image](https://user-images.githubusercontent.com/10986966/58241150-0a0adc00-7d6a-11e9-91d8-e5339c899c4c.png)

**Steps to reproduce:**
refer example anonymous_objects.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by kaviththiranga** [comment]
For anonymous objects, we can display the title as ```anonymous``` instead of the generated type name.

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
