### ISSUE TITLE
Return arrow placement within if/else blocks is incorrect

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15391]
**Description:**
refer screen dump 
![image](https://user-images.githubusercontent.com/10986966/58235188-f194c480-7d5d-11e9-8025-9ce960650d7b.png)

It should be like 
![image](https://user-images.githubusercontent.com/10986966/58235445-741d8400-7d5e-11e9-9ef0-7a1adbe270fd.png)

**Steps to reproduce:**
refer example union_type.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by kaviththiranga** [comment]
A simple function to reproduce

```ballerina
function checkTrue() returns string {
    if (true) {
        var isTrue = "true";
        return isTrue;
    } else {
        return "false";
    }
}
```

**Comment by kaviththiranga** [comment]
Error is not there when the return is taken out from else block or if there are no other statements within if body.

```ballerina
function checkTrue() returns string {
    if (true) {
        var isTrue = "true";
        return isTrue;
    } 
   return "false";
}

```ballerina
function checkTrue() returns string {
    if (true) {
        return isTrue;
    } else {
        return "false";
    }
}
```

**Comment by nadeeshaan** [comment]
This has been fixed in the master. Hence closing the issue
