### ISSUE TITLE
Destructing is not supported in the diagram. 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15397]
**Description:**
The mentioned destructure binding patterns are not supported in the diagram. 

- Tuple Destructure Binding Pattern
- Record Destructure Binding Pattern
- Error Destructure Binding Pattern

**Steps to reproduce:**
refer examples : 
tuple_destructure_binding_pattern.bal
record_destructure_binding_pattern.bal
error_destructure_binding_pattern.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by kaviththiranga** [comment]
When in expanded mode, some statements are not shown. Eg: below statement is not shown

```ballerina  (a1, (a2, a3)) = ("Ballerina", (453, false)); ```

**Comment by kaviththiranga** [comment]
https://github.com/ballerina-platform/ballerina-lang/blob/master/examples/tuple-destructure-binding-pattern/tuple_destructure_binding_pattern.bal#L8

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
