### ISSUE TITLE
Match statement is not rendered in diagram

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15390]
**Description:**
Match Statement is not supported, 

```ballerina
function basicMatch(any a) {
    match a {
        // This pattern check for tuple type of three variables and types can be of any.
        var (s, i, b) => io:println("Matched with three vars : "
                                    + io:sprintf("%s", a));
        // This pattern check for tuple type of two variables and types can be of any.
        var (s, i) => io:println("Matched with two vars : "
                                    + io:sprintf("%s", a));
        // This pattern check for single variable and type can be of any. This has to be last pattern.
        var s => io:println("Matched with single var : "
                                    + io:sprintf("%s", a));
    }
}
```

![image](https://user-images.githubusercontent.com/10986966/58232217-9d3a1680-7d56-11e9-8922-6e90f2656b80.png)

**Steps to reproduce:**
refer example tuple_match_statement.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by kaviththiranga** [comment]
<img width="631" alt="Screen Shot 2019-06-06 at 12 10 30 PM" src="https://user-images.githubusercontent.com/1505855/59012065-23c11e80-8854-11e9-89a0-a935b37940c0.png">

<img width="631" alt="Screen Shot 2019-06-06 at 12 10 42 PM" src="https://user-images.githubusercontent.com/1505855/59012079-2c195980-8854-11e9-9c04-db3dce1bc412.png">

We have to fix positioning logic for match body element.

**Comment by kaviththiranga** [comment]
The clattered items visible on left top is the statements that should be rendered inside match block

**Comment by nadeeshaan** [comment]
Fix has been merged in the latest master. Hence closing the issue
