### ISSUE TITLE
Representation error in the return arrow for fork example

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#15398]
**Description:**
Refer the screen dump

![image](https://user-images.githubusercontent.com/10986966/58243458-4dffe000-7d6e-11e9-867c-98a10cbf2810.png)

**Steps to reproduce:**
refer example fork_variable_access.bal

**Affected Versions:**
0.992.0-m2-SNAPSHOT

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
