### ISSUE TITLE
Unhandled NPE in LS compiler

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#15418]
**Description:**
$subject occurs in https://github.com/ballerina-platform/ballerina-lang/blob/6f4668641a29cb834b746f45de4e7eb0605e5639/language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompiler.java#L250 when trying to get the AST for a ballerina code with compilation errors. 
Please refer the stack trace below.
![Screenshot from 2019-05-27 11-46-30](https://user-images.githubusercontent.com/29032600/58399395-b2c08080-8075-11e9-8f0d-cb51a4cb7949.png)

**Steps to reproduce:**

Please refer the following sample code with one compilation error.

```ballerina
import ballerina/io;

public function main(string... args) {
    io:println("Hellow world");
}

foo
```
**Affected Versions:**
0.991.1 and below

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@NipunaRanasinghe this is expected since the current Ballerina Parser cannot handle this error scenario. In order to handle this particular use case either you need to use the source prune strategy or you have to handle within a try catch depending your usage logic.

**Comment by NipunaRanasinghe** [comment]
@nadeeshaan Yeah you are correct. I also had an offline discussion with @rasika and we thought of adding a NPE guard for this util method to avoid breaking the language server response for ast requests. WDYT?

**Comment by nadeeshaan** [comment]
@NipunaRanasinghe I would like to suggest not adding the guard at the util method. If we do so then we have to either return an optional or null. Also, I think null pointer guard should add where the usage is and then we can do a proper fallback as well based on the operation, if needed in the future. So shall we get it to the operation level as we have already done in https://github.com/ballerina-platform/ballerina-lang/blob/6f4668641a29cb834b746f45de4e7eb0605e5639/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java#L238

**Comment by rasika** [comment]
Yes. Ballerina compiler fails for this scenario. IMO we need to catch the NPEs for the sake of returning a valid response(even for the error) for the client. WDYT?

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe I would like to suggest not adding the guard at the util method. If we do so then we have to either return an optional or null. Also, I think null pointer guard should add where the usage is and then we can do a proper fallback as well based on the operation, if needed in the future. So shall we get it to the operation level as we have already done in
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/6f4668641a29cb834b746f45de4e7eb0605e5639/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaTextDocumentService.java#L238

@nadeeshaan I see your point :) +1

**Comment by rasika** [comment]
@nadeeshaan theoretically `LSCompiler.getBLangPackages()` should not throw any errors(rather we have a DiagnosticListener to capture all compiler related errors). This should be consistent with how we handle `LSCompiler.compileFile(...)`.

https://github.com/ballerina-platform/ballerina-lang/blob/6f4668641a29cb834b746f45de4e7eb0605e5639/language-server/modules/langserver-compiler/src/main/java/org/ballerinalang/langserver/compiler/LSCompiler.java#L131-L133

Thus, I am proposing both `LSCompiler.compileFile(...)` and `LSCompiler.getBLangPackages()` should return `LSCompilerException` on unexpected compiler runtime exceptions.

**Comment by nadeeshaan** [comment]
@rasika +1 for the approach. Then we can catch the exception at operation level and handle it properly

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
