### ISSUE TITLE
A bug in compound operator implementation

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#15459]
Consider the following code snippet:

```ballerina
a[f(i)] += y;
```
Here `f(i)` is not a side-effect free function. When I run this code, `f(i)` is executed twice. That is a bug.

**Comment by pubudu91** [comment]
Why shouldn’t it be executed twice (considering that it’s the same as `a[f(i)] = a[f(i)] + y;`)?
