### ISSUE TITLE
Refactor the constant names for HTTP response status codes

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#15536]
Currently, the HTTP response status code constant names take the following form: `<reason_phrase>_<status_code>`

This form is not ideal since this will cause the constants to be spread all over the place in documentation and in suggestions in tooling. Need to refactor this to conform to the best practices we follow (i.e., add a prefix to the names). 

Suggested format: `<prefix>_<status_code>_<reason_phrase>`

**Comment by shafreenAnfar** [comment]
This has been fixed by making those <prefix>_<reason_phrase>
