### ISSUE TITLE
Support new Error constructor syntax

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#15535]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/15457 changes error constructor syntax to be accordance with https://github.com/ballerina-platform/ballerina-lang/issues/15201 and https://github.com/ballerina-platform/ballerina-lang/issues/14670

This removes the `ErrorConstructorNode ` class and model error constructor a function invocation.

Provide tooling support to new error constructor syntax, `error-match-pattern` and `error-binding-pattern`

**Comment by rdhananjaya** [comment]
Please note PR https://github.com/ballerina-platform/ballerina-lang/pull/15967 disables following langserver-core formatting tests:
wait.bal
panic.bal
errorVariableDefinition.bal
errorVariableReference.bal
errorType.bal

**Comment by NipunaMarcus** [comment]
There are still formatting to be fixed and source gen to be checked hence reopening
