### ISSUE TITLE
[Annotations] Restrict constraints of maps/fields of records to be anydata and freeze the values

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#15533]
**Description:**
According to the v2019R1 spec, 

```
annotation-decl :=
   metadata
   [public] [const] annotation [type-descriptor] annot-tag 
   [on annot-attach-points]
annot-tag := identifier

The type-descriptor specifies the type of the annotation tag. The type must be 
a subtype of one of the following three types: true, map<anydata>, map<anydata>[].

If the annotation-decl for a tag specifies const, then a mapping-constructor-expr 
in annotations with that tag must be a const-expr and is evaluated at compile-time 
with the semantics of a const-expr. Otherwise, the mapping-constructor-expr is 
evaluated when the annotation is evaluated and the resulting value is automatically 
frozen.
```

In the initial iteration to introduce annotation changes the following is not done:
- restricting the constraints of maps/fields of records to be `anydata` - cannot be done at the moment since annotations currently have fields of types `service` (websocket), `function` (transactions), etc.
- freezing the annot value - cannot be done since the value may have non-anydata values

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/70

**Comment by pubudu91** [comment]
Related to spec: ballerina-platform/ballerina-spec#70
