### ISSUE TITLE
Fix worker test hanging issue

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#15541]
**Description:**
Jballerina worker unit tests are hanging and failing. Hence disabled the following package.
org.ballerinalang.test.worker.*

**Comment by SupunS** [comment]
Related: https://github.com/ballerina-platform/ballerina-lang/issues/15666

**Comment by SupunS** [comment]
related: https://github.com/ballerina-platform/ballerina-lang/issues/16171

**Comment by vinok88** [comment]
Fixed and enabled in Enabled in https://github.com/ballerina-platform/ballerina-lang/pull/17057.
