### ISSUE TITLE
Add IntelliJ plugin diagram feature in b7a.io learn page

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#15572]
**Description:**
$subject.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Documented via [1].

[1] https://github.com/ballerina-platform/ballerina-www/pull/1452
