### ISSUE TITLE
Improve codelens support to work with full document synchronization mode

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#15603]
**Description:**
Current ballerina language server based code lens implementation is designed to work with incremental synchronization mode and it is required to be revamped so that it can work in full document synchronization mode as well.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#15375 
#15376 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing the issue since this is invalid according to the latest language server implementation
