### ISSUE TITLE
Implement schema validation in JSON Schema -  (Request/response schema validator in Ballerina)

### ISSUE THREAD

**Issue by KasunAratthanage** [ballerina-platform/ballerina-lang#15654]
**Description:**
Currently ballerina does not have an approach to validate requests and responses using JSON schema. 

**Example**: **Schema validation use cases**
-  The schema is created from the url and its stored contents are validated against itself.
- An URL can point to a local file, where sub folder, current working directory.
- Schema created with a Map and call to json parse etc. 

Validating request/response based on a predefined json or xml API schema is helpful to     ensure whether the user have sent the request according to the schema and also to ensure whether the back-end have sent the correct response to the request.

**Comment by Asitha** [comment]
@KasunAratthanage Shall we open a separate issue to track XSD based validation?

**Comment by riyafa** [comment]
This can be achieved by providing data binding support for JMS

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#10 to get latest updates of this issue
