### ISSUE TITLE
Add options in IDE plugins to enable Lock and Siddhi runtime

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#15652]
**Description:**
Currently, we don't provide an option to user to enable siddhi runtime and lock which need to be pass to the compiler when compiling a  ballerina source. We need to add options in VSCode extension and IntelliJ IDEA plugin to enable these.

**Comment by NipunaRanasinghe** [comment]
Closing since the above options are no longer valid.
