### ISSUE TITLE
__init is not getting called from createObjectValue on jBallerina

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#15658]
**Description:**
$subject

**Comment by riyafa** [comment]
Global object variables are not getting initialized

**Comment by lankavitharana** [comment]
PR https://github.com/ballerina-platform/ballerina-lang/pull/15790 is merged which fixes this issue, however ideal fix would be to call the init method, (PR is only initializing fields) hence keeping the issue open

**Comment by lankavitharana** [comment]
PR merged, hence closing
