### ISSUE TITLE
Error: JAVA_HOME is not defined correctly

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-lang#15726]
**Description:**

When I run try to debug the program I get the following error
```
Error: JAVA_HOME is not defined correctly.
```

Plugin verison v0.991.1
Ballerina Version 0.991.0

**Comment by NipunaRanasinghe** [comment]
This is an IntelliJ IDE related issue which is already discussed and explained in this [SO question](https://stackoverflow.com/questions/30960103/intellij-java-home-variable/32998437).

According to that you can either,
- Start your intellij from terminal.
- Set JAVA_HOME as a global environment variable that applies to all programs, not only Bash sessions. 

```
launchctl setenv JAVA_HOME "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home"
```

Please let me know if it still does not solve your issue. :)

**Comment by NipunaRanasinghe** [comment]
Closing hence this is not occurred when using installers (bundled jre located within the distribution will be used). In addition, when using a distribution version extracted from its ZIP, users might have to follow the above steps, only if the $subject occurs.
