### ISSUE TITLE
Review Ballerina formatting CLI tool user messages and documentation

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#15720]
**Description:**
We need to review the user messages and documentation for the newest CLI tool for formatting ballerina source.

**Comment by praneesha** [comment]
The review is done in [1].

[1] https://docs.google.com/document/d/1toZrB-tGpBm_5wDixYWoMYzx01kL0ZsaEMBpLzXchC0/edit
