### ISSUE TITLE
Type Checking Issue with Type Test

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#15725]
```ballerina
import ballerina/io;

public function main() returns error? {
    error|int a = check int.convert(io:readln("Enter number 1: "));
    if (a is error) {
        return a;
    }
    error|int b = check int.convert(io:readln("Enter number 2: "));
    if (b is error) {
        return b;
    }
    io:println(a + b);
}
```
The above code gives the following compilation error:

error: .::connected-banking.bal:12:16: operator '+' not defined for 'error|int' and 'error|int'

But, according to the code, due to the return statements, we can be sure that "a" and "b" are both int values.

**Comment by hasithaa** [comment]
According to current language semantics, the `return` statement doesn't narrow the type.  But agree that is one possible improvement we can do. (That is captured here, https://github.com/ballerina-platform/ballerina-spec/issues/73)

**Comment by hasithaa** [comment]
Since improvement is captured in the spec issue, I am closing this issue.
