### ISSUE TITLE
Move JMS to jballerina with examples

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#15722]
**Description:**
Moving the JMS to jballerina org with examples (https://github.com/ballerinax/jms). This will prevent JMS module from getting tested by tooling.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
N/A

**Comment by wggihan** [comment]
JMS moved under [wso2-ballerina](https://github.com/wso2-ballerina/module-jms) org.
