### ISSUE TITLE
Implement schema validation in XSD Schema - (Request/response schema validator in Ballerina)

### ISSUE THREAD

**Issue by KasunAratthanage** [ballerina-platform/ballerina-lang#15756]
Description:
Currently ballerina does not have an approach to validate requests and responses using XML schema.

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#11 to get latest updates of this issue
