### ISSUE TITLE
[Test] BCompileUtil compilation does not schedule init and start method invocation

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#15754]
**Description:**
$Subject
https://github.com/ballerina-platform/ballerina-lang/blob/f5bf85dabec8387e7fb2f806e9cf2637248f9f1b/tests/ballerina-test-utils/src/main/java/org/ballerinalang/test/util/BCompileUtil.java#L597
ideally it should use a single scheduler throughout the test execution

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
This is fixed. Now init and start of BCompileUtil goes via scheduler now
