### ISSUE TITLE
Input read from STDIN is not considered tainted

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#15761]
**Description:**
The input read from STDIN should be considered as a tainted value at: https://github.com/ballerina-platform/ballerina-lang/blob/ca3a3f10e4e9cae4518790c77c9b2f7bc60ce0d9/stdlib/io/src/main/ballerina/io/read.bal#L21

Return values should be annotated as `@ tainted` here. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16141
