### ISSUE TITLE
Input read from a socket is not considered tainted

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#15763]
**Description:**

Data read from a socket is not returned with `@ tainted` annotation:
[1] https://github.com/ballerina-platform/ballerina-lang/blob/ca3a3f10e4e9cae4518790c77c9b2f7bc60ce0d9/stdlib/socket/src/main/ballerina/socket/client_socket.bal#L66

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16141
