### ISSUE TITLE
Remove error lifting operator '!' operator from the jBallerina 1.0

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#15787]
We have a plan to consider error lifting in a generic manner with [https://github.com/ballerina-platform/ballerina-spec/issues/195](https://github.com/ballerina-platform/ballerina-spec/issues/195).

**Comment by hasithaa** [comment]
Current Plan is for alpha is not to remove this from Runtime, but from the compiler, we give a warning saying this feature will be removed.

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16340
