### ISSUE TITLE
readln error when pipe is used.

### ISSUE THREAD

**Issue by JP3BGY** [ballerina-platform/ballerina-lang#15788]
**Description:**
When pipe is used, readln can't get line accurately.
It might ignore previous stdin buffer. So got EOF.

**Steps to reproduce:**
in.txt
```
A
B
```
test.bal
```
import ballerina/io;

public function main() {
    io:println(io:readln(""));
    io:println(io:readln(""));  #got error
}
```
and run `cat in.txt|ballerina run test.bal` or `ballerina run test.bal < in.txt` ,
and got error
```
A
error: No line found {}
	at ballerina/io:readln(<native>)
	   main(h.bal:5)
```
**Affected Versions:**
Ballerina 0.991.0
**OS, DB, other environment details and versions:**
Ubuntu 19.04 x64
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by wggihan** [comment]
@JP3BGY Thanks for the reporting this bug. We will fix this in the upcoming release, which happen in the end of July.
