### ISSUE TITLE
Cannot have main and a service in the same file

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#15817]
**Description:**
Unable to declare a main and a service in the same file. The main does not run. 

**Steps to reproduce:**
In the following main function does not run:
```
import ballerina/io;
import ballerina/http;

public function main() {
    io:println("hello");
}

service ClientService =@http:WebSocketServiceConfig {} service {

//This resource is triggered when a new text frame is received from the remote backend.
resource function onText(http:WebSocketClient conn, string text, boolean finalFrame) {
        io:println(text);
    }
};
```
The above is a blocker in testing WebSocket client.

and in the following the service starts, but the main function does not run:
```
import ballerina/http;
import ballerina/log;
service hello on new http:Listener(9090) {
    resource function sayHello(http:Caller caller, http:Request req) {
        var result = caller->respond("Hello, World!");
        if (result is error) {
            log:printError("Error sending response", err = result);
        }
    }
}

public function main() {
    log:printInfo("hello");
}
```
**Affected Versions:**
JBallerina master

**OS, DB, other environment details and versions:**
Ubuntu 19.04
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/13990

**Comment by SupunS** [comment]
Works on v0.992.0-m5
