### ISSUE TITLE
Migrate observability functionality to JBallerina

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#15820]
**Description:**
Since observability functionality is not migrated yet, standard library observability related code cannot be migrated to JBallerina.

**Comment by SupunS** [comment]
First cut of the migration is done with PR: https://github.com/ballerina-platform/ballerina-lang/pull/16119

Please let us know whether this is sufficient to proceed with he stdliib miration.

**Comment by Kishanthan** [comment]
@Manuri , could you verify this? observability is added.

**Comment by Anoukh** [comment]
Std lib has been migrated with https://github.com/ballerina-platform/ballerina-lang/pull/17079 hence closing the issue
