### ISSUE TITLE
When debugging Ballerina Module using Intellij plugin, debugger never connects to runtime 

### ISSUE THREAD

**Issue by wyldbill** [ballerina-platform/ballerina-lang#15835]
**Description:**
Every time Ballerina program is launched as debug, program runs on a different debug port. Debug window shows the debugger waiting to connect. Program runs and creates output, debugger never connects, programs never stops at breakpoints.

Note that this only occurs when the Main file is in a Module. If the Main is in the default(root) namespace, the debugger connects as expected.

**Steps to reproduce:**
Create a Project. Create a .bal with a main in the root (this exists in default project module). main( )should have at least two lines; assigning a string then printing works fine. Place a breakpoint on the first line. Right click the green "run" arrow next to the main() declaration, seclt debug. .bal file compiles, runs, debugger connects, execution halts at breakpoint. yay.

Create a Module inside that project by creating a sub directory. Create a .bal file with a main() in the module with a main(). Not that the plugin will not identify the new dir as a module with the Big Black B as a decoration, but compiling and running identifies it as a module. main( )should have at least two lines; assigning a string then printing works fine. Place a breakpoint on the first line. Right click the green "run" arrow next to the main() declaration, select debug. .bal file compiles, runs, debugger never connects, execution stops, but debug window indicates there is no connection to debugger. boo.

I have also managed to create a Module which is recognized and the Big Black B applied by doing a New->Module->Ballerina. In this case there is an Intellij .iml present. When trying to debug this module, the debugger never connects, and the execution doesn't stop at the breakpoint, put completes.

The same behavior occurs when using Run/Debug configurations.

**Affected Versions:**
Ballerina version: 0.991.0 (current)
Ballerina plugin version: 0.991.1 (current)
Intellij Version: 2019.1.3 (Ultimate)
OS: Windows 10

**Suggested Labels (optional):**
Component/IntellijPlugin

**Comment by NipunaRanasinghe** [comment]
Hi @wyldbill! Thanks for your interest on Ballerina and for reaching out with this, which could possibly be a bug. Right now, we are in the middle of revamping our ballerina debugger with adding DAP(Debugger Adapter Protocol) support and we are about to write a new DAP client for IntelliJ as well. Therefore hopefully after that effort, I'll be able to have a look on whether this issue still presents in our new debugger implementation and will get back back to you with a fix, if it does.

**Comment by NipunaRanasinghe** [comment]
@wyldbill We have finished our new debugger implementation in our **1.0.0-beta release** and tested in both unix and windows environments. Seems like the issue has been resolved with the revamping. Would you be able to check and verify?

**Comment by NipunaRanasinghe** [comment]
Closing since this is already fixed by the new DAP-based jBallerina debugger implementation. (Tested on Ubuntu, Windows and MacOS environments.) 

@wyldbill Please feel free to reopen/create new issue if you still experience any issues.
