### ISSUE TITLE
Cannot navigate to definition of Constants in VS Code 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#15842]
**Description:**

Define a constant as below

in file a.bal of module x : `public const PAYLOAD = "PAYLOAD";`
access it in a file b.bal of module x. 

`CMD + click `does not take you to the definition. 

**Steps to reproduce:**

Please refer above

**Affected Versions:**

0.991.2 VS code extension version

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
