### ISSUE TITLE
Fix negative file service test failures in jBallerina

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#15870]
**Description:**
Following tests are supposed to fail at compile time. It does not fail in compile time and fails in return an invalid error.

DirectoryListenerConnectorTest.testNegativeWithoutResource()
DirectoryListenerConnectorTest.testNegativeWithoutInvalidParamType()

There is an issue with the test cases as well. It did not fail if none of the errors got thrown.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by wggihan** [comment]
These tests are enabled again.
