### ISSUE TITLE
Error when creating an error to return 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#15875]
**Description:**

Following works

```
            error r = error("abcd", {reason:"xxvxd"});
            return r;
```

However, following does not. Syntactically it has same meaning

`return error("abcd", {reason:"xxvxd"});`

It gives following error. 

![image](https://user-images.githubusercontent.com/4967046/59825537-e8454a80-9351-11e9-863c-20cbcfdc1178.png)

**Steps to reproduce:**

**Affected Versions:**

0.991.2

**Comment by MaryamZi** [comment]
Duplicated by https://github.com/ballerina-platform/ballerina-lang/issues/17359.

Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/17316.
