### ISSUE TITLE
JMS module does not have connection.close()

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#15873]
**Description:**

JMS has two methods 

connection.stop() - temporarily stop connection [1]
connection.close() - close connection

But the JMS connector only provides stop method. There is no way to close a connection. 

[1]. https://docs.oracle.com/javaee/7/api/javax/jms/Connection.html#stop--
[2]. https://docs.oracle.com/javaee/7/api/javax/jms/Connection.html#close--

**Steps to reproduce:**

N/A

**Affected Versions:**

0.991.0

Suggested label: standard lib

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#4 to get latest updates of this issue
