### ISSUE TITLE
Directly referring to object in record does not work

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#15907]
**Description:**

I need to refer to a http:Client attached to a record passed into the method. 
However, directly referring to the variable does not compile. 

<img width="571" alt="Screen Shot 2019-06-21 at 8 41 50 AM" src="https://user-images.githubusercontent.com/4967046/59895553-9dcfd680-9402-11e9-9661-73bc6ef2af52.png">

Tried adding `()` but it also did not work. 

<img width="1221" alt="Screen Shot 2019-06-21 at 8 42 41 AM" src="https://user-images.githubusercontent.com/4967046/59895579-b213d380-9402-11e9-9bca-2b041dc0339e.png">

Assigning it to a new variable was the solution. But the language should support directly referring to the object in the record. 

**Steps to reproduce:**

Pls try above.

**Affected Versions:**

Ballerina : 0.991.0
VSCode : 0.991.2

**OS, DB, other environment details and versions:**

MAC OS Mojave

**Comment by MaryamZi** [comment]
IINM, this was initially done for diagram requirements. Need to recheck if the constraint still applies.

**Comment by KavinduZoysa** [comment]
This is working as expected in bal version 2201.3.0. Please check the below example. I think we can close the issue. @hasithaa WDYT?

```ballerina
import ballerina/http;

type Album readonly & record {
    string title;
    string artist;
};

type Config record {|
    http:Client c;
|};

public function main() returns error? {
    http:Client albumClient = check new ("localhost:9090");

    Config cofig = {
        c: albumClient
    };

    Album[] _ = check (cofig.c)->/albums;
}
```

**Comment by MaryamZi** [comment]
The equivalent to the original example is `Album[] _ = check (cofig.c)->post("/albums", "message");`, right? Either way, can you check if the diagram works? I'm seeing an error for

```ballerina
import ballerina/http;

type Album readonly & record {
    string title;
    string artist;
};

type Config record {|
    http:Client c;
|};

public function main() returns error? {
    http:Client albumClient = check new ("localhost:9090");

    Config config = {
        c: albumClient
    };
    Album[] _ = check (config.c)->post("/albums", "message");
}
```

```
A problem occurred while generating the diagram.
```

I'm not sure if this was allowed intentionally.

**Comment by hasithaa** [comment]
This has to be restricted. first expression is not part of the `action-or-expression`

**Comment by gimantha** [comment]
Closing for now, we will take this one later.
