### ISSUE TITLE
Tooling updates for annotation changes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#15947]
**Description:**

PR #15884 changes the annotation declaration syntax to

```
annotation-decl :=
   metadata
   [public] [const] annotation [type-descriptor] annot-tag 
   [on annot-attach-points] ;
```

and introduces the annotation access expression
```
annot-access-expr := expression .@ annot-tag-reference
```

Creating this issue to track the updates required for tooling.

The PR introduced the following tooling related code changes:
- [Updating attachment points in LSAnnotationCache](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-3ee6fe6e68d2d919a3341fdb670f6e6eR55)
- [Disabling resourceAnnotation1 and resourceAnnotation2 in AnnotationAttachmentsCompletionTest](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-66c19bd61dcde9fd89a5731c9d11105bR48), since annotations allowed on functions are also suggested for resources now (related issue - https://github.com/ballerina-platform/ballerina-lang/issues/15946)
- [Disabling externalKeywordSuggestion1 and externalKeywordSuggestion2 in FunctionDefinitionCompletionTest](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-ad2116803a63e9b590b6fe4c5cdf9a66R106) due to grammar changes extracting out external - https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-0e72b59e6b830c29e9c6161f3bb4177aR59
- [Disabling expectedAnnotation in FormattingTest](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-45c9467933a7044f82887ead9c751af4R117)
- [Disabling src_prune_config26 in SourcePruneTest ](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-391165f8ddd9661b593a7b9971e340a8R152)
- [Fixing iterableOperation4 for a language level iteration fix](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-beb09f02b1b41f5cccdf35903ed9078aR12)
- [Updating annotation syntax in allTopLevelItemSkip.bal](https://github.com/ballerina-platform/ballerina-lang/pull/15884/files#diff-b7ef2ba47f6b9839cd10b826447038d1R5)

**Comment by nadeeshaan** [comment]
closing since the Fix has been merged

**Comment by MaryamZi** [comment]
A `worker` attachment point has also been introduced, and such annotations could be used to annotate either workers or the start action. 

```ballerina
const annotation v1 on source worker;

public function main() {
    @v1
    worker w1 {
        
    }

    future<int> f = @v1 start foo();
}

function foo() returns int {
    return 1;
}
```

**Comment by NipunaRanasinghe** [comment]
Closing since the all the required tooling changes have been inroduced with  #16168, #16234, #16357, #16356, and #18611.
