### ISSUE TITLE
Update symbol resolver constrained type resolving to use symbol with actual constraint type for table type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#15945]
**Description:**
$title. This was incorrect for all constrained types (resolved type tsymbol was used) -  https://github.com/ballerina-platform/ballerina-lang/blob/v0.991.0/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java#L950.

PR #15884 updates this for other constrained types. Table type was not updated due to stream and language server (completion) test failures.

**Comment by mohanvive** [comment]
No longer valid for new table implementation in Swan Lake. Hence, closing the issue.
