### ISSUE TITLE
Disallow testerina annotations (BeforeXxx, AfterXxx, Config, etc.) on resource functions and object methods

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#15946]
**Description:**
$title.

The annotations are currently allowed on resource functions and object methods, even though they make no sense. 

These annotations are also suggested for resource functions/object methods.

**Affected Versions:**
0.991.0

**Comment by hevayo** [comment]
I guess this should be a generic validation that has to be done by the compiler. Compiler should throw an error if the annotation is attached to a resource or object function if annotation definition  only has function. 

```ballerina

public annotation TestConfig Config on function;

public annotation MockConfig Mock on function;

# Identifies beforeSuite function.
public annotation BeforeSuite on function;

# Identifies afterSuite function.
public annotation AfterSuite on function;

# Identifies beforeTest function.
public annotation BeforeEach on function;

# Identifies afterTest function.
public annotation AfterEach on function;
```

**Comment by hasithaa** [comment]
Related to https://github.com/ballerina-platform/ballerina-spec/issues/297

**Comment by hasithaa** [comment]
The conclusion in the spec issue is, this needs to be handled using a compiler extension. @hevayo @azinneera Please note.

**Comment by Dilhasha** [comment]
Even if we disallow adding these annotations on resource functions and object methods using a Compiler Extension,
this won't avoid suggesting the annotations by LS right?
