### ISSUE TITLE
Diagram arrrow heads are not positioned correctly

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#15961]
<img width="1282" alt="Screen Shot 2019-06-24 at 11 48 15 AM" src="https://user-images.githubusercontent.com/1505855/59997163-ef35cb00-9679-11e9-871c-95c08b14292f.png">

This is in ```jballerina``` branch - HEAD 8ee14d4f8619f63efe4ce3f3ad0319965e902400

Please close if it's fixed already in another branch.

**Comment by roonyh** [comment]
This was because caller was positioned to the right side of the resource. It should always be in the left. This is fixed in 1.0.0-alpha release.
