### ISSUE TITLE
support transaction statement in diagram, code lenses, etc.

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#15968]
Currently, transaction blocks are not getting rendered in Diagram.
Furthermore, inside transaction body, ```endpoint``` code lense is not working and even the endpoints declared there won't get rendered. 

It seems we need to update existing visitors of ours to visit transaction blocks.

**Comment by kaviththiranga** [comment]
We can use reflection to write a generic function which visits all block nodes
https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/CommandUtil.java#L560

**Comment by nadeeshaan** [comment]
Relevant Language server capabilities have been addressed. Hence removing the label

**Comment by mohanvive** [comment]
Diagramming capabilities are  no longer valid for Swan Lake release. Hence, closing it.
