### ISSUE TITLE
remove() and clear() in MapValue should take records in to consideration

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#16005]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
In the current master the remove() and removeAll() functions validate that it's not a record before removing elements. The remove() function can be improved a bit more by allowing to remove rest fields from the record

**Comment by hasithaa** [comment]
> In the current master the remove() and removeAll() functions validate that it's not a record before removing elements. The remove() function can be improved a bit more by allowing to remove rest fields from the record

@pubudu91 I have tested (JBallerina 1.2.2) your scenario with the following the program. It seems to be working as you mentioned

```ballerina 
import ballerina/io;
type foo record {
    int i;
};

public function main() {
    foo x = { i : 10, "y" : 3};
    _ = x.remove("y");
    io:print(x);
}
```

So I am resolving this issue. Please reopen if I missed anything.
