### ISSUE TITLE
Tooling effort on language syntax changes

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#16012]
All changes are mentioned here
https://htmlpreview.github.io/?https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/v2019R2/lang/spec.html#changes

#### LS

- [x] Tuple Union support
- [x] Tuple Related snippets

#### Formatter

- [x] Tuple Change -  Review & Merge - https://github.com/ballerina-platform/ballerina-lang/pull/15935
- [x] Error constructor change - https://github.com/ballerina-platform/ballerina-lang/issues/15535

#### IntelliJ Plugin
- [x] Tuple Union support
- [x] Error constructor change 
- [x] Tuple syntax change
- [x] Annotations change

####  text mate grammar
   
- [x] https://github.com/ballerina-platform/ballerina-grammar/pull/38

#### api docs

- [x] update docs to reflect ```( )``` to ```[ ]``` - PR https://github.com/ballerina-platform/ballerina-lang/pull/16015

## Annotation Change - https://github.com/ballerina-platform/ballerina-lang/issues/15947

- [x] LS 
- [ ] Syntax Highlighting
- [x] Formatting

## Errrors

Error detail object should match Detail object from lang lib.

- [x] LS
- [ ] Syntax Highlighting
- [x] Formatting

## Delimeter syntax change (https://github.com/ballerina-platform/ballerina-lang/issues/16398)
- [x] LS 
- [ ] Syntax Highlighting
- [x] Formatting

## Optional Field access - https://github.com/ballerina-platform/ballerina-lang/issues/16855
- [x] LS
- [x] Syntax Highlighting
- [x] Formatting
##  tuple rest descriptor  https://github.com/ballerina-platform/ballerina-lang/issues/17009
- [x] LS
- [x] Syntax Highlighting
- [x] Formatting

## Error binding patterns - https://github.com/ballerina-platform/ballerina-lang/issues/17418
- [x] LS
- [ ] Syntax Highlighting
- [x] Formatting
## Match pattern only has a statement body https://github.com/ballerina-platform/ballerina-lang/issues/17693

- [x] LS
- [ ] Syntax Highlighting
- [x] Formatting

## Fix abstract function impl change https://github.com/ballerina-platform/ballerina-lang/issues/18294

- [x] LS
- [ ] Syntax Highlighting
- [x] Formatting

**Comment by nadeeshaan** [comment]
Closing since the fixes have been merged
