### ISSUE TITLE
Compilation error in typeguard when `trap` is present

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#16037]
**Description:**
```ballerina
 var x = trap testDB->batchUpdate("Insert into CustData (firstName,lastName,registrationID,creditLimit,country)
                                     values (?,?,?,?,?)", parameters1, parameters2);
    if (x is int[]) {
        updateCount = x;
        if (updateCount[0] == -3 && updateCount[1] == -3) {
            returnVal = "failure";
        } else {
            returnVal = "success";
        }
    } else {
        returnVal = <string> x.detail().message; //<--This is the line compilation error points to
    }
```
compilation
```bash
ERROR: .::sql_actions_negative_test.bal:165:31:: function invocation on type 'error|error' is not supported
```
This goes away when
1.  `trap` is removed 
OR
2. x is assigned to an error type reference before accessing detail record.

Observed in jaballerina branch

**Comment by hasithaa** [comment]
When the trap is removed, the type-guard semantic gets change. That is why you see different results.  I have tested this on JBallerina 1.2.2, and it gives expected results. I have used the following program.  

```ballerina
public function main() {
    error|int[] x = trap foo();
    if (x is int[]) {
        
    }    
    else {
        var xxx = <string>( x.detail().message); //<--This is the line compilation error points to
    }
}

function foo() returns int[] {
    return [5];
}
```

Now the above line gives error `invalid operation: type 'record {| string message?; error cause?; (anydata|error)...; |}' does not support field access for non-required field 'message'` which is a correct error message.

Inorder to fix new compiler error, change that line as follows. 

`var xxx = <string>( x.detail()["message"]);`
