### ISSUE TITLE
Create a page to display all the shorcuts

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#1603]
Just get a reference to command manager, it's getCommands() method provides all the registered commands. Iterate through all the command defs and generate the shortcut list in a table. We need to add an additional property to command defs to carry a description about each command. ATM, a command def looks like below.

               command: {
                    id: "undo",
                    shortcuts: {
                        mac: {
                            key: "command+z",
                            label: "\u2318Z"
                        },
                        other: {
                            key: "ctrl+z",
                            label: "Ctrl+Z"
                        }
                    }
                }

**Comment by uthaiyashankar** [comment]
Moved back from https://github.com/ballerina-lang/composer/issues/351

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
