### ISSUE TITLE
Function Variable Scoping

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#16030]
**Description:**
Given a set of function parameters, all previous parameter symbols should be visible to the expression that is being evaluated for a default value of a defaultable parameter.

```ballerina
function test(int a, int b = 10, int c = a*2+b, int d = 10) { // valid

}

function test(int a, int b = 10, int c = a*2+b+d, int d = 10) { // invalid, undefined symbol d for default expression used for parameter c

}
```

**Comment by Shan1024** [comment]
Closing the issue since it is already fixed by #16030.
