### ISSUE TITLE
Documenting method is not suggested by VS code plugin

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16045]
**Description:**

Sometimes documenting method is not suggested by the tool. 
I had to copy paste a doc from somewhere else, paste and edit. 

__init() method of an object is not also suggested. 

please refer screenshot below for an example. 

![image](https://user-images.githubusercontent.com/4967046/60174811-842df500-982f-11e9-9d31-88004c9dad25.png)

**Comment by kaviththiranga** [comment]
@rasika seems this is because the method is not public. Should we provide this for all the methods irrespective of public/private? API docs are ATM gets generated only for public methods in a module. But we may have to rethink that too. @hevayo WDYT?

**Comment by nadeeshaan** [comment]
> @rasika seems this is because the method is not public. Should we provide this for all the methods irrespective of public/private? API docs are ATM gets generated only for public methods in a module. But we may have to rethink that too. @hevayo WDYT?

IMO, we should provide the documenting action for all the functions irrespective of the access modifier. Users document both public and private functions. If we opt to provide the support for the private functions user has to write a whole bunch of things which we can easily generate. When we do the feature comparison with other languages and IDEs, that was the same behaviour. WDYT?

**Comment by kaviththiranga** [comment]
@nadeeshaan yeah, it make sense to document private functions most of the time. We should remove the filter.

**Comment by nadeeshaan** [comment]
@kaviththiranga I'm currently working on a fix for this one, I'll send the PR so we can review

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
