### ISSUE TITLE
LS Signature Help does not work for unclosed parenthesis

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#16065]
**Description:**
Please note $subject. It seems like the issue with generated sub rule,  since it is not compilable in this context.

**Steps to reproduce:**

Please refer and use the following example.

```ballerina
public function main() {
    foo(
}
function foo() {
}
```

**Affected Versions:**
0.992.0-m2-SNAPSHOT 

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the Fix has been merged
