### ISSUE TITLE
Add data binding support for JMS

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#16088]
**Description:**
We need to have data binding support for xml and JSON validation in JMS.

**Steps to reproduce:**
Currently this feature is not supported. 

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/15654
https://github.com/ballerina-platform/ballerina-lang/issues/15756

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#12 to get latest updates of this issue
