### ISSUE TITLE
JMS Connector Issue when a message is created on a broken session 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16099]
**Description:**

Please consider below code

```ballerina
function tryToSendMessage(map<string> requestMessageMap) returns error? {
        //create a map message from message detail extracted 
        var messageToStore = self.jmsSession.createMapMessage(requestMessageMap);
        if (messageToStore is jms:Message) {
            // This sends the Ballerina message to the JMS provider.
            var returnVal = self.queueSender->send(messageToStore);
            if (returnVal is error) {
                //TODO: try to send to failover store if defined 
                string errorMessage = "Error occurred while sending the message to the queue " + self.queueName;
                log:printError(errorMessage, err = returnVal);
            }
        } else {
            log:printError("Error while creating message from ", err = messageToStore);
            return messageToStore;
        }
    }
```

**Steps to reproduce:**

1. Start the program. 
2. Verify message sending is working fine. 
3. Shutdown the broker
4. Try to send a message

When creating message on broken session it should return an `error`. Instead it returns a `jms:Message`. 

Need to fix it at [1]. 

[1]. https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/jms/src/main/java/org/ballerinalang/net/jms/utils/BallerinaAdapter.java#L75-L80

N/A

**Affected Versions:**

0.991.0

**Comment by daneshk** [comment]
This issue will fix after migrating to jballerina. @riyafa can you please check.

**Comment by aashikam** [comment]
This was fixed after the restructuring of the jms:Message object. #16669
