### ISSUE TITLE
Enable the metrics-extensions:ballerina-prometheus-extension build

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#16142]
**Description:**
$title. Was disabled on jballerina with #15884, since balx generation is not supported with BIR_GEN.

**Comment by nadundesilva** [comment]
Ballerina Prometheus Extension had been moved to https://github.com/ballerina-platform/module-ballerinax-prometheus repository in module-ballerinax-prometheus#1 and enabled in Ballerina Alpha. Hence closing the issue.
