### ISSUE TITLE
Incompatible lambda function types error when trying to use xml.foreach() function 

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#16183]
**Description:**
When trying to use xml.foreach() function ut gives following error.

```
incompatible lambda function types: expected 'xml', found 'xml|string'
```
<img width="702" alt="Screen Shot 2019-07-02 at 9 01 51 PM" src="https://user-images.githubusercontent.com/19742678/60527820-a7194700-9d10-11e9-8a62-7236c3223dc9.png">

This is the code I have used.
```ballerina
xml batches = xml `<batchInfoList xmlns="http://www.force.com/2009/06/asyncapi/dataload">
            <batchInfo>
                <id>751D0000000004rIAA</id>
                <jobId>750D0000000002lIAA</jobId>
                <state>InProgress</state>
                <createdDate>2009-04-14T18:15:59.000Z</createdDate>
                <systemModstamp>2009-04-14T18:16:09.000Z</systemModstamp>
                <numberRecordsProcessed>0</numberRecordsProcessed>
                <numberRecordsFailed>0</numberRecordsFailed>
                <totalProcessingTime>0</totalProcessingTime>
                <apiActiveProcessingTime>0</apiActiveProcessingTime>
                <apexProcessingTime>0</apexProcessingTime>
            </batchInfo>
            <batchInfo>
                <id>751D0000000004sIAA</id>
                <jobId>750D0000000002lIAA</jobId>
                <state>InProgress</state>
                <createdDate>2009-04-14T18:16:00.000Z</createdDate>
                <systemModstamp>2009-04-14T18:16:09.000Z</systemModstamp>
                <numberRecordsProcessed>800</numberRecordsProcessed>
                <numberRecordsFailed>0</numberRecordsFailed>
                <totalProcessingTime>5870</totalProcessingTime>
                <apiActiveProcessingTime>0</apiActiveProcessingTime>
                <apexProcessingTime>2166</apexProcessingTime>
            </batchInfo>
        </batchInfoList>`;

batches.foreach(function(xml v) {
    io:println(v);
});
```

**Steps to reproduce:**
N/A

**Affected Versions:**
Ballerina version: 0.991.0
Plugin version: 0.991.2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@pramodya1994, this error is because XML iteration can produce either `xml` or `string`.

An `xml` value in Ballerina is a sequence of zero or more of the possible items: elements, characters, processing instructions and/or comments.

Quoting from the spec, "An XML value is iterable as a sequence of its items, where each character item is represented by a string of length one and other items are represented by a singleton XML value"

Thus, since in the characters case iterating may result in strings, the parameter is expected to be of type `xml|string`.

For example, iteration happens character by character in the following case (and `v` is of type `string`):
```ballerina
import ballerina/io;

public function main() {
    xml xmlChars = xml `HI`;

    xmlChars.foreach(function(xml|string v) {
        io:println(v is string);
        io:println(v);
    });
}
``` 

Output:
```cmd
$ ballerina run test.bal
true
H
true
I
```

For non-character XML items, the iteration is as the singleton `xml` values:
```ballerina
import ballerina/io;

public function main() {
    xml xmlChars = xml `HI`;
    xml xmlElement = xml `<book>Harry Potter</book>`;

    xml xmlSeq = xmlChars + xmlElement;

    xmlSeq.foreach(function(xml|string v) {
        io:println(v is string);
        io:println(v);
    });
}
``` 

Output:
```cmd
$ ballerina run test.bal
true
H
true
I
false
<book>Harry Potter</book>
```

**Comment by pramodya1994** [comment]
@MaryamZi Thanks for the answer. Then the code completion in the VS code plugin should be changed? Because I didn't write this code snippet. it generated by the VS code. If it is not we can close this issue.

**Comment by nadeeshaan** [comment]
Snippet suggestions have been altered in the latest version where the language server does not generate the parameters. Hence closing the issue.
