### ISSUE TITLE
Issue when creating a task and start it in main function

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16201]
**Description:**

1. Create a ballerina module called `test`. Define a `ballerina task` and attach a `service` to it.
2. Compile the module using `ballerina build` and install it to local repo using `ballerina install`. 
3. Create another ballerina module and, in there write a ballerina program importing the above module. 

```
import wso2/test;
public function main(string... args) {

    //create the task 
   //call task.start()

}
```

Here you will see the main function exits even if the programmer expects the task would continue to run. 

**Affected Versions:**

Ballerina 0.991.0

**OS, DB, other environment details and versions:**

Mac OS

**Suggested Labels (optional):**

Ballerina runtime

**Comment by ThisaruGuruge** [comment]
This should be fixed in the language side. If there is a listener attached to a service, it should not exit.

**Comment by gimantha** [comment]
This is related to #18601 , hence closing
