### ISSUE TITLE
JBallerina does not recognize other modules packed

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#16235]
**Description:**
If we pack other modules like `jballerinax` it is not resolved by jballerina because of the check here: https://github.com/ballerina-platform/ballerina-lang/blob/7426a5c270d317a6e7681ca70d5d06e9f413d6e7/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/BootstrapRunner.java#L92

**Steps to reproduce:**
Try having a different org in the jballerina repo like ballerinax

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
N/A

**Comment by Kishanthan** [comment]
This is fixed.
