### ISSUE TITLE
Support for escape character '\f' (formfeed) on windows not working

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#1623]
Used below list of escape characters and found that "\f" not worked in windows but all are worked in ubuntu. Please see the code[1]
- escape character list
\n
\r
\t
\b
\f
\'
\"
\\

`function main(string[] args) {
system:println("Hello.. \"Good morning\"!");
system:println("Hi \'Ballerina\'!!");
system:println("File located at: \\HOME\\UBUNTU\\RUNTIME");
system:println("Please see the comments in next stage \nStage1");
system:println("You can see a gap here\tAre you?");
system:println("What happens as backspace??\bAh!");
system:println("Replaced me? Cariage return\rAh!");
system:println("What it is? formfeed!! \f Yeah!");
}`

**Comment by uthaiyashankar** [comment]
This is working as expected now.
