### ISSUE TITLE
[Editor] Shortcuts are not working in Safari

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#1625]
Browser: Safari 10.0.2 installed on Mac

1. New (Command + ^ + N) is not working. It is very difficult to press these 3 buttons at the same time as well.
2. Open File short cut is not working

**Comment by uthaiyashankar** [comment]
Moved back from https://github.com/ballerina-lang/composer/issues/361

**Comment by uthaiyashankar** [comment]
This issue is outdated, due to changes in composer. Resolving it. Please re-open if this problem is there in the new composer as well.
