### ISSUE TITLE
Remove untaint unary operator from tooling 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#16267]
**Description:**
`untaint` operator is removed and replaced with `<@untainted>` which is a annotation on a typecast operator where the type of the type cast is infered to be type of it's RHS operand.

This change will be introduced with https://github.com/ballerina-platform/ballerina-lang/pull/16200

Example: 
```ballerina
Obj a = <@untainted> getObj();
// Below is also allowed
Obj a = <@untainted Obj> getObj();
```

**Comment by NipunaMarcus** [comment]
@roonyh - can we confirm the syntax changes for this? 
@nadeeshaan @rasika - is there anything to do from the Completion and test generation?

**Comment by nadeeshaan** [comment]
@NipunaMarcus we won't support auto-completion for this syntax at this moment

**Comment by nadeeshaan** [comment]
Fix has been added to beta, hence closing the issue
