### ISSUE TITLE
Fix failing completion tests in language server module

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#16283]
**Description:**
The tests disabled in following commit are failing. Please fix and enable.
https://github.com/ballerina-platform/ballerina-lang/pull/16268/commits/2110328129f0112c39792197d3bf42af19def46a

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Duplicate
