### ISSUE TITLE
Wrong type created for constant symbols read from compiled sources

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#16308]
Consider the following definition:
```ballerina
public type SQLType TYPE_VARCHAR|TYPE_CHAR

public const TYPE_VARCHAR = "VARCHAR";
public const TYPE_CHAR = "CHAR";

public type Parameter record {|
    SQLType sqlType;
|};
```
If the above definitions are coming from a compiled source, and are used as follows, it gives a compile error saying incompatible types.
```ballerina
public function main() {
    Parameter p = {sqlType: TYPE_VARCHAR};
}
```
The above results in a compile error saying expected `SQLType` but found `string`. This is because the type of the symbol of `TYPE_VARCHAR` is read as `string` from CompiledPackageSymbolEnter. If we run the above in a single file, it goes through the normal symbol enter and the type of the symbol of `TYPE_VARCHAR` is set as a finite type.

**Comment by Kishanthan** [comment]
Cannot be reproduced. Please check and and close this.

**Comment by pubudu91** [comment]
Closing since this was due to an error in how the test was compiled. It was using an old util class which made use of the BVM.
