### ISSUE TITLE
Add annotation attachments to BIR

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#16379]
**Description:**
$title.

This was done for functions with https://github.com/ballerina-platform/ballerina-lang/pull/15784. Needs to be done for the rest of the attachment points.

**Comment by MaryamZi** [comment]
See https://docs.google.com/document/d/1ymUVMWYelQNahDrKCR7QgGlaXyHWSRpmv9CH_7Ulksg for initial thoughts.

**Comment by MaryamZi** [comment]
Also check https://github.com/ballerina-platform/ballerina-lang/issues/28543.

**Comment by gimantha** [comment]
This will be merged after update 1. Found an issue in Observability internal module

**Comment by MaryamZi** [comment]
> This will be merged after update 1. Found an issue in Observability internal module

This is when an import module is not available, which seems to happen often with ballerinai/observe. We've added a null check in the place where this failed, since we had assumed it to be non-null there.

**Comment by dulajdilshan** [comment]
Annotations in Functions: https://github.com/ballerina-platform/ballerina-lang/issues/36426
