### ISSUE TITLE
source is a keyword in ballerina

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#16384]
**Description:**
`source` is a keyword in Ballerina lang at the moment. This is a widely used variable name and it should not be a keyword.

**Steps to reproduce:**
```ballerina
public type FileConfig record {|
    string source;
    string target;
    boolean isBallerinaConf = false;
|};
```
will result in an error.

**Affected Versions:**
jballerina-0.992.0-m2-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
IMO, even though "source" is commonly used as a variable name, it makes sense to have "source" as a keyword to represent the source-only-ness of a construct (which is what it is used for now).

On the other hand, identifier literals are now easier to write (`'source`) compared to 0.991.0, so IMO having source as a variable/field name is still possible without much of a hassle. WDYT?

```ballerina
public type FileConfig record {|
    string 'source;
    string target;
    boolean isBallerinaConf = false;
|};

public function main() {
    FileConfig fc = { 'source: "s", target: "t" };
}
```

**Comment by MaryamZi** [comment]
Please raise an issue in https://github.com/ballerina-platform/ballerina-spec if you have further concerns regarding the same, or have suggestions for an alternate keyword.
