### ISSUE TITLE
Iterating an int[] where it has become null

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16399]
**Description:**

1. Define a record where an int[] intArray is optional. 
2. Write a code where you get this int[] field and iterate. 
3. When you do not specify a value to int[], Ballerina code crashes at the point of iterate. It does not give out an error or the codes below that point is not executed.

**Affected Versions:**
0.991.0

**Comment by rdhananjaya** [comment]
This issue is fixed in ballerina 1.0.0-alpha

Consider following:

```ballerina
import ballerina/io;
type RecordName record {
    int[] ar?;
};

public function main(string... args) {
    RecordName r = {};
    r.ar.forEach(function (any a) {
        io:println(a);
    });
}
```
This produces error: `invalid operation: type 'RecordName' does not support field access for non-required field 'ar'`
