### ISSUE TITLE
[Enhacement] Impement message dispatcher to facilitate Message Dispatcher pattern

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#1642]
Currently there is no mechanism to implement the message dispatcher pattern which needs a dispatcher that dispatches according to the speciality of a consumer. In order to support more integration space, this feature is needed.

**Comment by riyafa** [comment]
It is now possible to implement message dispatcher pattern `http:LoadBalanceClient` or using if else statements.
