### ISSUE TITLE
SMTP Connector

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#16443]
Can we have a general SMTP connector for Ballerina. This is a very useful connector to have, that is currently missing. Several users have also asked for this functionality. 

With jBallerina, we should be able to easily wrap the Java Mail functionality using a Ballerina connector and implement the functionality quickly. Long term effort would be to implement the protocol from scratch, so it can be used in the native Ballerine runtime as well.

**Comment by hemikak** [comment]
I published a library on central for this - https://central.ballerina.io/hemikak/smtp

**Comment by wggihan** [comment]
Basic client connector for receiving and sending email introduced with 1.2.0. This will further improve.
https://ballerina.io/v1-2/learn/by-example/send-and-receive-emails.html
