### ISSUE TITLE
LS fails to provide suggestions when cursor is at topline of an if statement

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#16450]
Please refer to below screen recording.
![ScreenRecording2019-07-11at1](https://user-images.githubusercontent.com/1505855/61023284-eefe3500-a3c6-11e9-819e-59f89d75df59.gif)

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master. Hence closing the issue
