### ISSUE TITLE
Consistent name + versioning scheme for standard libraries

### ISSUE THREAD

**Issue by chintana-zz** [ballerina-platform/ballerina-lang#16494]
**Description:**
Currently standard libraries in bre/lib doesn't have a consistent naming scheme. It's good to have a naming scheme + versioning to identify standard libraries. Looking at bre/lib it's not apparent what library dependencies are vs dependencies required for core runtime. For example, 

```
ballerina-core-0.992.0-m2-SNAPSHOT.jar
ballerina-auth-0.992.0-m2-SNAPSHOT.jar
ballerina-io-0.992.0-m2-SNAPSHOT.jar
ballerina-builtin-0.992.0-m2-SNAPSHOT.jar
cache.jar
builtin.jar
config.jar
io.jar
...
```

It'll be good to have a naming scheme identify libs. Will be useful with patching later as well.

Standard libs - lib&lt;name&gt;-&lt;version&gt;.jar
libcache-0.992.0.jar
libconfig-0.992.0.jar

Core runtime
runtime-&lt;depname&gt;-&lt;version&gt;.jar

etc...

**Comment by hevayo** [comment]
The io.jar, config.jar ... are generated from the ballerina library code so they should be in a jar cache in the distribution. Having them in the lib is a temporary thing we did till we get the build properly setup. 

And +1 to create a runtime uber jar.

**Comment by hevayo** [comment]
Obsolete. Module specific jar files will be kept in caches.
