### ISSUE TITLE
Add separate setter and getter methods for JMS mapMessage

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16505]
**Description:**

Currently, we have a method to construct a map with all the values and then set. 
Underlying there is an iteration, which makes it less performing.

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#13 to get latest updates of this issue
