### ISSUE TITLE
Add authentication for JMS connector

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16507]
**Description:**

When using JMS connector to write `messageStore` module for relaibe messaging for ballerina, noticed that there is no way to feed authentication details for a user when connecting to the message broker. 

```
 string? userName = storeConfig["userName"];
 string? password = storeConfig["password"];
```

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#14 to get latest updates of this issue
