### ISSUE TITLE
Add JMS connection close methods for JMS connector

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#16508]
**Description:**

We need to have methods equivalent to what is provided by JMS API of Java in Ballerina. 

queueSender.close()
queueSession.close()
queueConnection.close()

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#15 to get latest updates of this issue
