### ISSUE TITLE
Enable language server tests

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#16516]
**Description:**
#16504 introduce some new default param semantics, and that'll break some language server tests. Those were disabled in https://github.com/ballerina-platform/ballerina-lang/pull/16504/commits/211f01e253095ce3c5a11c397bf7f83a5a4f40be. Please fix lang server according to above change and re-enable those tests.

**Comment by NipunaMarcus** [comment]
Enabled all the tests mentioned here that are disabled in formatting tests.
