### ISSUE TITLE
Fix ArrayValue constructor which accepts BType

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#16765]
**Description:**
$Subject.
https://github.com/ballerina-platform/ballerina-lang/blob/5c5f0d4b92ac005d7c758618358f35b9476ef651/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/ArrayValue.java#L121

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
@chamil321 , what do we have to fix here?

**Comment by SupunS** [comment]
I beleive this is a cleanup task. current constructor `public ArrayValue(BType type)` is too generic as it allows to create an array with any given type. We should break it in to two, so that one accepts a `BArrayType` and the other accepts a `BTupleType`.
