### ISSUE TITLE
Diagnostic doesn't work

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#16779]
**Description:**
See below 

![image](https://user-images.githubusercontent.com/6178058/61280340-50fad800-a7d5-11e9-8b68-3fd7faa270bc.png)

**Comment by nadeeshaan** [comment]
Tried the sample and I could get the diagnostics. @shafreenAnfar could you confirm if you can get diagnostics for the syntax errors?

**Comment by nadeeshaan** [comment]
Checked with the latest master and could not reproduce the issue. Hence closing the issue. Please feel free to reopen if the issue can still be reproduced
