### ISSUE TITLE
VS code project overview only shows one file 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#16771]
**Description:**
see below. 

![image](https://user-images.githubusercontent.com/6178058/61278814-7e925200-a7d2-11e9-942d-4da4003db4bb.png)

**Comment by kaviththiranga** [comment]
This is fixed

**Comment by kaviththiranga** [comment]
Wrong comment: This is no longer valid as compiler doesnt allow files outside src folder within a ballerina project.
