### ISSUE TITLE
Project Overview doesn't get active when I click on my service 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#16775]
**Description:**
See below 

![image](https://user-images.githubusercontent.com/6178058/61279403-ae8e2500-a7d3-11e9-88ca-fd3b5c66cf8b.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/commit/2618f80a909f2abeb185eb519f1395d644ba8cb9
