### ISSUE TITLE
Auto completion doesn't work when the generated snippet is active

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#16781]
**Description:**
See below

![image](https://user-images.githubusercontent.com/6178058/61281353-20b43900-a7d7-11e9-9a4e-e9692f9639d3.png)

**Comment by nadeeshaan** [comment]
@shafreenAnfar this is handled by the VSCode itself editor itself. When we are within the tab-completion position VSCode doesn't trigger the completion request.

**Comment by rasika** [comment]
Since we are already in snippet completion mode(note that `baseP` is highlighted); we don't have any control over it. VSCode editor itself has to trigger the completions suggestions request.

One workaround is that you might press TAB to exit from the snippet completion mode.
