### ISSUE TITLE
Iterable operations are not support for table types

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#16805]
**Description:**
Iterable operations such as map(), filter(), select(), count() etc are not supported for tables and not defined in the spec as well.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
We are holding this feature since we are deprecating this table design from 1.2 release.
