### ISSUE TITLE
Type param calculated for records should be the broad type of all record fields

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#16824]
Consider the following example:
```ballerina
type Person record {
    string name;
    int age;
};

function testGet(string key) returns anydata {
    Person person = {name: "John Doe", age: 25};
    return person.get(key);
}
```
The return type of the function has to be `anydata` because the record is open. If it was closed, it could've been narrowed to `string|int`. Currently, the compiler only reduces the type param taking the rest field into account. This needs to be improved to take normal fields in to account as well. 

For example,
```ballerina
type Person record {
    string name;
    int age;
};

type Student record {
    *Person;
    string class;
};

type Teacher record {
    *Person;
    string subject;
};

type Foo record {|
    Person p;
    Student s;
    Teacher t;
|};

Foo foo = {p:<Person>, s:<Student>, t:<Teacher>};

function testGet(string key) returns Person {
    return foo.get(key);
}
```
In the above function, return type can be Person since `Student` and `Teacher` record types are subtypes of `Person`.

**Comment by grainier** [comment]
The original issue seems to be fixed. However, following not working;

```ballerina
type Person record {
    string name;
    int age;
};

Person person = {name: "John Doe", age: 25};

function testGet(string key) returns string|int {
    return person.get(key);
}
```

**Comment by MaryamZi** [comment]
> The original issue seems to be fixed. However, following not working;
> 
> ```ballerina
> type Person record {
>     string name;
>     int age;
> };
> 
> Person person = {name: "John Doe", age: 25};
> 
> function testGet(string key) returns string|int {
>     return person.get(key);
> }
> ```

The compilation error here is correct, right? Since `Person` is an open record here, `person.get(key)` can return `anydata`.

This works when `Person` is made a closed record.

```ballerina
type Person record {|
    string name;
    int age;
|};

Person person = {name: "John Doe", age: 25};

function testGet(string key) returns string|int {
    return person.get(key);
}
```

I believe we can close this now.

**Comment by hasithaa** [comment]
I am closing the issue as per the above comment.
