### ISSUE TITLE
Tooling updates for optional field access

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#16855]
**Description:**
Creating an issue to track $title.

Introduced with https://github.com/ballerina-platform/ballerina-lang/pull/16340

Syntax
```ballerina
    string? s = f?.name;
```

**Comment by kaviththiranga** [comment]
@nadeeshaan filter out optional fields in completions

**Comment by kaviththiranga** [comment]
suggestion by @rasika :

**Comment by NipunaMarcus** [comment]
Reopen as this will affect areas such as formatting, syntax highlighting, and other language server features.

**Comment by rasika** [comment]
@nadeeshaan can we close this now?

**Comment by nadeeshaan** [comment]
@rasika shall we wait for the syntax highlighting confirmation as well. @roonyh

**Comment by roonyh** [comment]
Syntax highlighting is unbroken. can be closed.

**Comment by NipunaMarcus** [comment]
Fix has been shipped with alpha hence closing the issue.
