### ISSUE TITLE
Issue in `constructFrom` with records

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#16922]
**Description:**
Consider the following code:
```ballerina
import ballerina/io;

type BRec record {
    int i;
};

type CRec record {
    int i?;
};

public function main() {
    CRec c = {  };
    var b = BRec.constructFrom(c);
    io:println(b is BRec);
    io:println(b is error);
}
```

The conversion should fail since `c` does not have the field `i`. But the conversion succeeds and prints true and false respectively.

The spec also says, "if a record type descriptor specifies default values, these will be used to supply any missing members", which we don't seem to be doing at the moment.

**Affected Versions:**
0.992.0-m8

**Comment by rdhananjaya** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/17568 add a test case verifying fist half of this issue is fixed now.
