### ISSUE TITLE
A VSCode command to restart lang server

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#16951]
There are common situations where lang server crashes occationally, Ideally we need to fix those cases but also it is important to give user a quick way to recover from it.

VSCode has an in built command to restart typescript lang server when it crashes - discussion on it can be found here https://github.com/microsoft/vscode/issues/22614

Shall we do something similar?

**Comment by nadeeshaan** [comment]
Similar functionality can be gained by using the **Reload Window** command. Hence closing the issue
