### ISSUE TITLE
Incorrect Record binding pattern syntax

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#16961]
**Description:**
ATM Following is supported.

```
 var {| var1 |} => return "Matched with closed pattern";
```

Above binding pattern syntax is invalid according to spec.

**Comment by warunalakshitha** [comment]
We need to refactor or remove the https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/statements/matchstmt/MatchStructuredRecordPatternsTest.java#L200 as well.

**Comment by pubudu91** [comment]
Reopening this since this was closed by PR #16984 by mistake
