### ISSUE TITLE
Fielt nbf input is not created into final JWT (missing in JWTIssuer/buildPayloadString)

### ISSUE THREAD

**Issue by gboege** [ballerina-platform/ballerina-lang#16962]
**Description:**
 nbf input defined in JwtPayload is not created into final JWT. input data does not get processed due to missing nbf element in function

**Steps to reproduce:**
Create a JwtPayload Payload with nbf element included, run issueJwt and check the JWT in jwt.io

**Affected Versions:**
0.9.9.1

**OS, DB, other environment details and versions:**
MacOS 

**Related Issues (optional):**
None

**Suggested Labels (optional):**
None

**Suggested Assignees (optional):**
JWT Team
![NBF missing in issueJWT](https://user-images.githubusercontent.com/44926950/61620310-ef24ed00-ac70-11e9-80b2-eab3a0859520.png)

**Comment by ldclakmal** [comment]
Hi @gboege,
Thanks for reporting the issue. It is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/17522 and will be available with Ballerina v1.0.0-beta
