### ISSUE TITLE
"tainted value passed to global variable" error throws when using a const fields for path in a GET request

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#16974]
**Description:**
$subject

**Steps to reproduce:**
Define a const filed as below.
```ballerina
const JOB = "job";
```
Then use it as the path for the get request.
```ballerina
string[] paths = [JOB];
string path = prepareUrl(paths);
http:Response | error response = self.httpClient->get(path, req);
```
You will get below error.
```
tainted value passed to global variable 'JOB'
```

**Affected Versions:**
Ballerina 0.992.0-m2-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
@pramodya1994  could you please share the implementation of `prepareUrl`.

**Comment by pramodya1994** [comment]
Implementation of prepareUrl function.
```ballerina
# Returns the prepared URL.
# + paths - An array of paths prefixes
# + return - The prepared URL
function prepareUrl(string[] paths) returns string {
    string url = EMPTY_STRING;

    if (paths.length() > 0) {
        foreach var path in paths {
            if (!path.startsWith(FORWARD_SLASH)) {
                url = url + FORWARD_SLASH;
            }
            url = url + path;
        }
    }
    return url;
}
```
