### ISSUE TITLE
SQL API Does Not Return Generated Keys in Batch Update

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#16986]
In the Ballerina SQL API, the "batchUpdate" operation does not return the list of generated keys. The general "update" operation provides this, but not the batch update. This is a blocking issue for the batch operations in Ballerina. The API needs to be updated to support this.

**Comment by anupama-pathirage** [comment]
Ack. Yes. This is a missing feature and a blocker. We will add this to 1.0 alpha release.

**Comment by lafernando** [comment]
Thanks!.
