### ISSUE TITLE
Local Transactions Creating 2PC Logs

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#16991]
When doing a local transaction using the "transaction" block in Ballerina, it prints the following logs:

2019-07-22 22:49:55,001 INFO  [ballerina/transactions] - Created transaction: 8421d732-766a-4551-85a2-74fce62f752a 
2019-07-22 22:49:55,021 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: 8421d732-766a-4551-85a2-74fce62f752a:$anon$.$1 

First of all, the actual behavior does not use 2PC, so this is misleading. And also, for every local transaction, we shouldn't log to stdout. If really required, we should log to a file, and rotate that log. Or else, if someone else redirects this to a file, this file will grow pretty quickly in high throughput scenarios. We should maybe only log any ERROR, or WARN situation, and put the above logs in a DEBUG level.

**Comment by anupama-pathirage** [comment]
We are planning to remove local transactions from the transaction coordinators path. So these logs will go away with that change

**Comment by lafernando** [comment]
Great, thanks for the info.

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/module-ballerinai-transaction/pull/6 in master.
