### ISSUE TITLE
[JMS] temporary destinations cannot be destroyed

### ISSUE THREAD

**Issue by JensWalter** [ballerina-platform/ballerina-lang#17002]
**Description:**
If I'm doing request-reply on JMS, I have to create temporary destinations for the reply message within the JMS session. 
Now, those destinations pile up, since there is no function to actually destroy those destinations.
The only solution I found so far is to regularly restart the whole ballerina process to terminate the session and therefore clear all temporary destinations.

**Steps to reproduce:**
Create a temporary destination though a JMS session.

**Affected Versions:**
all

**OS, DB, other environment details and versions:**

**Suggested Labels (optional):**
Component/JMS

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
I am closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository.
Please refer wso2-ballerina/module-jms#19 to get latest updates of this issue
