### ISSUE TITLE
Support tuple rest descriptor with tooling

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#17009]
**Description:**
$subject. With https://github.com/ballerina-platform/ballerina-lang/pull/17008, it introduced `restType` field to the `BTupleType` model. Please verify tooling with that change.

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/pull/17008
tests disabled in https://github.com/ballerina-platform/ballerina-lang/pull/17008/commits/8fb3aef0c7a848cde2e026798a9a6c69b080d31e

**Comment by nadeeshaan** [comment]
Closing since the changes have been verified
