### ISSUE TITLE
lambda's are not analyzed by the taint analyzer

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#17018]
**Description:**
Taintanalyzer does not analyze lambda and its body. For example the following will not produce any compilation errors.

```ballerina
public function main (string... args) {
    string[] words = [ "ant", args[0], "cat", "dear", "elephant" ];

    words.forEach(function (string word) { secureFunction(word, word);});
}

public function secureFunction (@untainted any secureIn, any insecureIn) {

}

```

**Comment by rdhananjaya** [comment]
Taint analyzing lambda functions are supported with https://github.com/ballerina-platform/ballerina-lang/pull/17499 except when they are passed into `extern` functions as function pointers.

Same goes for passing regular functions into `extern` functions as function pointers.

**Comment by rdhananjaya** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/18187 describe the missing taint flow analysis features needed in extern functions. When it's provided rest of this issue should be complete.
