### ISSUE TITLE
<string> findAll(string regex) - Not Returning Sub-Group

### ISSUE THREAD

**Issue by jimk-osu** [ballerina-platform/ballerina-lang#17013]
**Description:**
Using the string method `findAll(string regex)` for the following example:
--> [Doc Link](https://ballerina.io/learn/api-docs/ballerina/primitive-types.html#string)
![image](https://user-images.githubusercontent.com/26698712/61744178-a64e6080-ad64-11e9-9c2e-03066db90136.png)

```ballerina
string test = "ADV01_CIS_MS_SERVER_2016_Level_1_v1.0.0.audit";
string regex = "([A-Z\\d]*?)_CIS_([\\w\\d]*)(_Level_\\d|_L\\d)_*.*\\.audit";
var output = test.findAll(regex);

if (output is string[]){
    io:println(output);
}
```

output:

```shell
Initiating service(s) in 'hello_service.bal'
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:9090
["ADV01_CIS_MS_SERVER_2016_Level_1_v1.0.0.audit"]
```
Expecting `test.findAll(regex)`  to return`["ADV01", "MS_SERVER_2016", "Level_1"]`, but it is returning `ADV01_CIS_MS_SERVER_2016_Level_1_v1.0.0.audit` .

**Steps to reproduce:**

**Affected Versions:**
`Ballerina 0.991.0`
**OS, DB, other environment details and versions:**
`Darwin`
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
The `findAll()` method is not used for retrieving the sub groups. It returns all the sub strings which match the given regex.

**Comment by jimk-osu** [comment]
That makes sense. I would continue down this path and request that there is a function to return regex sub groups in a string array.

**Comment by pubudu91** [comment]
Can you open a separate issue for that? These regex functions have been removed now. Regex functionalities will most likely come as a module instead. We can take suggestions such as the above into consideration when designing the regex module.
