### ISSUE TITLE
"incompatible types" error when sending a tuple literal from one worker to another

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#17032]
**Description:**
Getting "incompatible types" error when sending a tuple literal from one worker to another.
The error goes away if the tuple is assigned to a variable before sending.

**Steps to reproduce:**
```ballerina
function name() {
    worker w1 {
        [1, 1.1] -> w2;
    }

    worker w2 {
        [int, float] value = <- w1;
    }
}
```

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3872221/61789867-65714d00-ae33-11e9-8699-48622e4397fa.png">

No errors for this code.

```ballerina 
[int, float] sentValue = [1, 1.1];
sentValue -> w2;
```

**Comment by rdhananjaya** [comment]
According to the spec `[1, 1.1]` should be inferred to a `(int|float)[]` as there is no contextually expected type.

**Comment by grainier** [comment]
like @rdhananjaya mentioned, since there's no contextually expected type`[1, 1.1]` will get inferred as `(int|float)[]`. To overcome, you'll have to explicitly define the type;  

```ballerina
function workerTest() {
    worker w1 {
        [int, float] x = [1, 1.1];
        x -> w2;
    }

    worker w2 {
        [int, float] value = <- w1;
        io:println(value);
    }
}
```
