### ISSUE TITLE
Error reported after running $ballerina init

### ISSUE THREAD

**Issue by deeteeakl** [ballerina-platform/ballerina-lang#17040]
**Description:**
I just installed Ballerina and was following the steps in the "Quick Tour".  I ran ballerina init and got an error.

**Steps to reproduce:**
run ballerina init

**Affected Versions:**
latest install version

**OS, DB, other environment details and versions:**
MacOS

[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3428406/ballerina-internal.log)

**Comment by pubudu91** [comment]
Do you have permission to write to the directory you’re trying to initialize the project in?

**Comment by deeteeakl** [comment]
I created a new directory and tried again and this time it succeeded. Thanks. 

David Taylor

07548 019759

**Comment by pubudu91** [comment]
Glad it worked. But if this indeed was a permission issue, then that shouldn't have crashed the runtime. It should've just simply said permission denied or something.

**Comment by hevayo** [comment]
From ballerina 1.0 we will be removing init command. Please use `new` command to create a new directory. 

Refer https://v1-0-0-alpha.ballerina.io/learn/quick-tour/ for more details. 

You can download the alpha from 
https://ballerina.io/downloads/

Will keep this open till we check if this issue handle in other commands.

**Comment by azinneera** [comment]
Closing this since the issue is no longer relevant with 1.2.x and SL versions.
