### ISSUE TITLE
Focus to the added element

### ISSUE THREAD

**Issue by sumuditha-viraj** [ballerina-platform/ballerina-lang#1706]
Currently when we add an element(service, function, connector) to the canvas, it will add at the end of the document and users doesn't get notices that it is added to the canvas.

We need to focus the added element once user drag and drop some elements.

**Comment by SupunS** [comment]
Closing this issue and reopning the same issue in the correct repo: https://github.com/ballerinalang/composer/issues/393

**Comment by pahans** [comment]
Closing this because drag n drop is no longer supported in composer.
