### ISSUE TITLE
BBE should have a page explaining a simple service

### ISSUE THREAD

**Issue by tharinduwijewardane** [ballerina-platform/ballerina-lang#17078]
**Description:**
[BBE](https://ballerina.io/learn/by-example) does not have a topic to explain a service.
`service`, `on` keywords and `@http:ServiceConfig`, `@http:ResourceConfig` anotations and `http:Listener` are not explained.

Even though a sample service available in [hello-world-service](https://ballerina.io/learn/by-example/hello-world-service.html) it is better to add a topic in "Working over the network" section explaining above points.

**Comment by praneesha** [comment]
This information is covered in Ballerina API Docs[1].

[1] https://ballerina.io/learn/api-docs/ballerina/http/index.html
