### ISSUE TITLE
Autocompletion not working in IntelliJ 2019.2

### ISSUE THREAD

**Issue by paramids** [ballerina-platform/ballerina-lang#17087]
**Description:**
Auto completion not working in IntelliJ 2019.2 with ballerina plugin 991.1

**Comment by nadeeshaan** [comment]
@paramids you don't get completions at all or is it only in some cases? If so will you be able to share a sample you are trying?

**Comment by NipunaRanasinghe** [comment]
@paramids Could you please also provide your ballerina SDK version to reproduce the issue? :)

**Comment by nadeeshaan** [comment]
Closing the issue as per the above comment.
