### ISSUE TITLE
Critical Error when using JMS & ActiveMQ

### ISSUE THREAD

**Issue by paramids** [ballerina-platform/ballerina-lang#17088]
Decription - /usr/lib/ballerina/ballerina-0.991.0/bin/ballerina run --sourceroot /home/parami/IdeaProjects/test1 test1.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

Process finished with exit code 1

`import ballerina/io;
import ballerina/jms;
import ballerina/http;

// Type definition for an order
type Order record {
    string customerID?;
    string productID?;
    string quantity?;
    string orderType?;
};

jms:Connection jmsConnection = new ({
initialContextFactory: "org.apache.activemq.jndi.ActiveMQInitialContextFactory",
           providerUrl: "tcp://localhost:61616"
           });
listener http:Listener httpListener = new (9090);

public function main() {
    io:println("Hello, World!");
}
`
Version - Ballerina 0.991.0
IntelliJ Plugin 0.991.1
IntelliJ 2019.2

OS- Linux 16.04 LTS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
I am closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#17 to get latest updates of this issue
