### ISSUE TITLE
Argument parser for the main function is outdated with the function argument change

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17092]
**Description:**
$title.

Would have to revisit/change
- how named arguments are identified/default values are set
- argument order
- passing required args as named args
- disallow varags with named args

**Affected Versions:**
0.992.0-m8

**Related PR:**
https://github.com/ballerina-platform/ballerina-lang/pull/16504

**Comment by vinok88** [comment]
Argument parser tests are enabled in PR https://github.com/ballerina-platform/ballerina-lang/pull/17158
