### ISSUE TITLE
Getting java.lang.VerifyError when using http->get asynchronously

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#17152]
**Description:**
$title

**Steps to reproduce:**
```
import ballerina/http;

http:Client clientEndpoint = new("https://postman-echo.com", {});

public function main() {
    future<http:Response|error> f3 = start clientEndpoint->get("/get?test=123");
}
```
Getting the following error printed on the console
```
error: invoking main method failed due to java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    irshadnilam/examples/main.main(Lorg/ballerinalang/jvm/scheduling/Strand;)V @174: aload
  Reason:
    Type top (current frame, locals[7]) is not assignable to reference type
  Current Frame:
    bci: @174
    flags: { }
    locals: { 'org/ballerinalang/jvm/scheduling/Strand', 'org/ballerinalang/jvm/values/FutureValue', 'org/ballerinalang/jvm/values/ObjectValue', 'java/lang/String', integer, null }
    stack: { 'org/ballerinalang/jvm/scheduling/Scheduler', '[Ljava/lang/Object;', '[Ljava/lang/Object;', integer }
  Bytecode:
```
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3446068/ballerina-internal.log)

**Affected Versions:**
Ballerina 0.992.0-m2-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**
MacOs 10.14.5
java version "1.8.0_212"

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

@vinok88

**Comment by MaryamZi** [comment]
Need to add back the aync example to the index.json (https://github.com/ballerina-platform/ballerina-lang/pull/17311/files#diff-eb29cd6279f866aad1b57f33d8659953L417) once this is fixed.

**Comment by MaryamZi** [comment]
Shall we add back the async example? https://github.com/ballerina-platform/ballerina-lang/pull/17311/files#diff-eb29cd6279f866aad1b57f33d8659953L417
