### ISSUE TITLE
[Enhancement] Provide capability to facilitate service activation for soap methods

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#1719]
Currently the soap methods has to be activated as rest in ballerina. Through the SOAP server connector it will be advantageous if soap representation of the soap backends can be allowed in ballerina

e.g. Similar to publishWSDL of proxy service

**Comment by riyafa** [comment]
There is a soap-connector that provides a different soap specific apis: https://github.com/wso2-ballerina/package-soap
Hope it fulfills your requirement. Please reopen if anything else is required.
