### ISSUE TITLE
Improve Record Variable Match Pattern Rest Parameter Type Inferrence

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17207]
**Description:**
Type of the rest parameter of a record variable pattern in a match statement should infer the type from the context. Currently, the type is either `map<anydata>` or `map<any>` depending on the context.
```ballerina
public function main() {
    match test() {
      var {x, ...y} => {
       // type of y is `map<anydata>`
       // it should be inferred as `boolean|string`  
       }      
    }
}

public function test() returns record {| int x; boolean y; string z?; |}  {
    return {x : 10, y : true};
}
```

**Comment by MaryamZi** [comment]
This sample crashes on slalpha1 - https://github.com/ballerina-platform/ballerina-lang/issues/28277
