### ISSUE TITLE
Error when accessing the detail field of an error

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#17266]
**Description:**
java.lang.NoSuchFieldError: when accessing the detail field of an `error`.

**Steps to reproduce:**
```ballerina 
public function main() {

    // Sends the subscription request for the subscriber service.
    websub:SubscriptionChangeRequest subscriptionRequest = {
        topic: "http://websubpubtopic.com",
        callback: "http://localhost:8181/websub",
        secret: "Kslk30SNF2AChs2"
    };

    var response = websubHubClientEP->subscribe(subscriptionRequest);

    if (response is websub:SubscriptionChangeResponse) {
        io:println("Subscription Request successful at Hub [" + response.hub +
                    "] for Topic [" + response.topic + "]");
    } else {
        string errCause = <string>response.detail().message;
        io:println("Error occurred with Subscription Request: " +
                                            <string>response.detail()?.message);
    }
}
```

error: invoking main method failed due to java.lang.NoSuchFieldError: $type$$anonType$builtin$0

ballerina-internal-log
[2019-08-01 10:53:16,256] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
java.lang.NoSuchFieldError: $type$$anonType$builtin$0
	at subscription_change_client.main(subscription_change_client.bal:24)
	at ___init.$lambda$main$(.)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:411)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:198)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:169)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hasithaa** [comment]
Syntax `response.detail().message` is not supported, because message is an optional field. I have verified this with a similar sample and it is working as expected. Hence I am resolving this issue.
