### ISSUE TITLE
I/O API Inconsistencies

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#17277]
The Ballerina I/O channel APIs has several inconsistent behaviors in its design. 

* io:ReadableByteChannel
  - public function read(@untainted int nBytes) returns @tainted [byte[], int]|Error = external;

If we are returning a byte[] here, why do we need the second int value for the number of bytes read?. This can be checked by looking at the size of the byte[].

* io:ReadableCharacterChannel

  - public function read(@sensitive int numberOfChars) returns @tainted string|error = external;

How do we know the difference between EOF and a read error?.

* io:WritableByteChannel
  - public function write(byte[] content, int offset) returns int|Error = external;

Probably should give a data length parameter also to write the data from the given buffer. Specially if the above "read" operation is correct, and we have buffer, and the number of valid data amount is different, then to keep up with the symmetry of the API of read/write, the length parameter must be here.

**Comment by wggihan** [comment]
> The Ballerina I/O channel APIs has several inconsistent behaviors in its design.
> 
> * io:ReadableByteChannel
>   
>   * public function read(@Untainted int nBytes) returns @tainted [byte[], int]|Error = external;
> 
> If we are returning a byte[] here, why do we need the second int value for the number of bytes read?. This can be checked by looking at the size of the byte[].

We have revamped the API for ballerina 1.0. Now it only returns byte[] or Error.

> 
> * io:ReadableCharacterChannel
>   
>   * public function read(@sensitive int numberOfChars) returns @tainted string|error = external;
> 
> How do we know the difference between EOF and a read error?.
> 

At the end of the stream io:EofError will be return and all other error cases io:Error will be return.

> * io:WritableByteChannel
>   
>   * public function write(byte[] content, int offset) returns int|Error = external;
> 
> Probably should give a data length parameter also to write the data from the given buffer. Specially if the above "read" operation is correct, and we have buffer, and the number of valid data amount is different, then to keep up with the symmetry of the API of read/write, the length parameter must be here.

But we can slice the array and make a appropriate array with desire size. So do we need the length additionally for that?

**Comment by lafernando** [comment]
> > The Ballerina I/O channel APIs has several inconsistent behaviors in its design.
> > 
> > * io:ReadableByteChannel
> >   
> >   * public function read(@Untainted int nBytes) returns @tainted [byte[], int]|Error = external;
> > 
> > If we are returning a byte[] here, why do we need the second int value for the number of bytes read?. This can be checked by looking at the size of the byte[].
> 
> We have revamped the API for ballerina 1.0. Now this only returns byte[] or Error.
> 
> > * io:ReadableCharacterChannel
> >   
> >   * public function read(@sensitive int numberOfChars) returns @tainted string|error = external;
> > 
> > How do we know the difference between EOF and a read error?.
> 
> At the end of the stream io:EofError will be return and all other error cases io:Error will be return.
> 
> > * io:WritableByteChannel
> >   
> >   * public function write(byte[] content, int offset) returns int|Error = external;
> > 
> > Probably should give a data length parameter also to write the data from the given buffer. Specially if the above "read" operation is correct, and we have buffer, and the number of valid data amount is different, then to keep up with the symmetry of the API of read/write, the length parameter must be here.
> 
> But we can slice the array and make a appropriate array with desire size. So do we need the length additionally for that?

Slicing an array is expensive (need to create a new copy), and we shouldn't let the user to do that. The API should correctly handle that. 

If the above read operation change is kept as it is, then to keep the API symmetry of read and write operations, we don't need this. Since the read operation fills up the full array, and we only need the offset for partial writes in the write operation. If the general becomes not this, and need a slice always for a read/write pattern, then we should have the length parameter also.

**Comment by lafernando** [comment]
The length parameter can also be considered to be put as a defaultable parameter, with default value of -1 (for full remaining array length). So in the non-standard scenario, users can give that value.

**Comment by wggihan** [comment]
Basically, we can cater 99% use cases without use slicing. IMO, it is a rare use case that someone wants to write fractions of the data from source array. So such an edge cases can cater using slice IMO.

```
import ballerina/io;

public function main() returns error? {
    io:ReadableByteChannel 'source = check io:openReadableFile("/somefile.txt");
    io:WritableByteChannel destination = check io:openWritableFile("/anotherfile.txt");
    while (true) {
        byte[] | io:Error content = 'source.read(1024);
        if (content is io:EofError) {
            break;
        } else if (content is io:Error) {
            io:println(content);
        } else {
            int totalWritten = 0;
            int arrayLength = content.length();
            while (totalWritten < arrayLength) {
                int written = check destination.write(content, totalWritten);
                totalWritten = totalWritten + written;
            }
        }
    }
    check 'source.close();
    check destination.close();
}
```

**Comment by lafernando** [comment]
Yes, provided that we keep the read operation with the new behavior, we can skip the length parameter from the write operation.

**Comment by lafernando** [comment]
It does look we do half of what is done in the slice operation though, with the offset. So this behavior is purely to keep in sync with the read operation's behavior. That's why I suggested the defaultable parameter earlier also. But true, the length will not be required practically in most of the situations.

**Comment by wggihan** [comment]
@lafernando I closing this issue since address the initial problem. Please reopen if you have any further queries.
