### ISSUE TITLE
CommentStmtTest and ObjectDocumentationTest are Disabled

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#17270]
**Description:**
Following jballerina-unit-test are disabled temporary due to intermittent test failures

org.ballerinalang.test.object.ObjectDocumentationTest
org.ballerinalang.test.statements.comment.CommentStmtTest

Related PR: #16945

**Comment by rdhananjaya** [comment]
`CommentStmtTest` is enabled with https://github.com/ballerina-platform/ballerina-lang/pull/17461

**Comment by daneshk** [comment]
Both tests are enabled now, hence closing this issue.
