### ISSUE TITLE
Need to implement HTTP2 header/body compression 

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#17279]
**Description:**
HTTP2 header and body compression is not supported from Ballerina. This needs to be implemented.

**Comment by Bhashinee** [comment]
Body compression has to go with Ballerina 1.0.0-beta

**Comment by arukshani** [comment]
Body compression is done with https://github.com/wso2/transport-http/pull/358. 

New ticket has been created to track header compression. https://github.com/ballerina-platform/ballerina-lang/issues/18044
