### ISSUE TITLE
XML related test are failing in windows due to resource bundle issue

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#17274]
**Description:**
org.ballerinalang.util.exceptions.BallerinaException: failed to create xml: Can't find bundle for base name META-INF\exceptions, locale en_US
        at org.ballerinalang.model.values.BXML.handleXmlException(BXML.java:279)
        at org.ballerinalang.model.values.BXMLItem.<init>(BXMLItem.java:98)

**Steps to reproduce:**

**Affected Versions:**
0.991.0, 1.0-Alpha

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
This occurs due to use of depricated BVM classes (eg: org.ballerinalang.model.values.BXMLItem)
