### ISSUE TITLE
Need to support list constructor when there is no contextually expected type.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#17320]
**Description:**
Need to support list constructor when there is no contextually expected type.
Spec says:
```
If there is no contextually expected type, then the inherent type will be T[], 
where T is the union of the broad types of the expressions in expr-list. 
It is an compile-time error if expr-list is empty and there is 
no contextually expected type. 
``` 

var x = [1, string];
x should be `(int|string)[]`

Currently this gives `invalid variable definition; can not infer the assignment type.`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Related https://github.com/ballerina-platform/ballerina-lang/issues/17032

**Comment by MaryamZi** [comment]
@rdhananjaya the var scenario works fine on 1.0.0-alpha. 

```ballerina
import ballerina/io;

public function main(string... args) {
    var x = [1, "string"];
    io:println(x is (int|string)[]); // unnecessary condition: expression will always evaluate to 'true'
}
```
So does using `any`.

Anything else that needs to be considered?

**Comment by rdhananjaya** [comment]
I think we can close this as current implementation comply with the spec.
