### ISSUE TITLE
[Packerina] Cannot init project if the folder structure already exist

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#17330]
**Description:**
if the src folder already exist, then cannot do ballerina init, it fails with msg "error: Error occurred while initializing project : scatter-gather-messaging/guide/src"

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Init command has been removed. Instead of that "new" and "add" commands has been added. "new" will create a new project. But you cannot create a new project inside another project. It will give the following error

> ballerina: Directory is already within a ballerina project :/private/tmp/org-test/proj1

Hence closing.
