### ISSUE TITLE
Review and update CLI info messages and help texts

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17332]
Need to review the info messages given for CLI commands. The following for example, contains typos.
```
$ ballerina init
Ballerina project initialised 

Next:
    Use `ballerina create` to create a ballerina module.
```
- initialised -> initialized
- ballerina module -> Ballerina module

**Comment by pubudu91** [comment]
Need to update the content of the CLI help texts as well. Many seems outdated.

**Comment by hevayo** [comment]
This was reviewed with 1.0 release
