### ISSUE TITLE
Ballerina build fail when giving source as file path

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#17349]
**Description:**
ex. ballerina build projects/hello/initiator.bal

**Comment by warunalakshitha** [comment]
sample bal

import ballerina/io;

public function main(string... args) {
    io:print("hello");
}

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/17562
