### ISSUE TITLE
Autocompletion for typedesc not working

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#17341]
**Description:**
Auto completion not working for `typedesc` constructs in vsCode

for example following does not auto complete:
 `typedesc<json>.constructFrom(ordersMap[orderId])`

**Steps to reproduce:**
Try typing ` typedesc<json>.`  and expect autocompletion.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
In the latest language implementation the particular code snippet generates the following diagnostic. Hence closing the issue assuming this is an invalidated case. Please reopen if there are any other concerns
