### ISSUE TITLE
http:Request.getJsonPayload() does not work for primitive type JSON

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#17364]
**Description:**
Here `httpEndpoint` refers to a service that responds a simple string-type JSON such as "Hello World!".

```ballerina
var response = httpEndpoint->post("/", request);
    if (response is http:Response) {
        var jsonResponse = response.getJsonPayload();
        if(jsonResponse is json){
            io:println("All good");
        } else {
            io:println(jsonResponse);
        }
    }
}
```

`getJsonPayload()` Returns the following error:
```
error {ballerina/http}GenericClientError message=Error occurred while retrieving the json payload from the request cause=error {ballerina/mime}ParsingEntityBodyFailed message=Error occurred while extracting json data from entity: unrecognized token 'Order' at line: 1 column: 7 cause=null
```

**Affected Versions:**
1.0-alpha

**Comment by arukshani** [comment]
When the string is serialized as json this works. But if we serialize it as string then the json parser throws this error. So the issue must be on the serializer or the parser. 

@gimantha I checked this against this PR https://github.com/ballerina-platform/ballerina-lang/pull/17300 as well, but still the issue exists.

**Comment by gimantha** [comment]
> When the string is serialized as json this works. But if we serialize it as string then the json parser throws this error. So the issue must be on the serializer or the parser.
> 
> @gimantha I checked this against this PR #17300 as well, but still the issue exists.

I checked the code seems Serializer is doing nothing other than writing it to the outputStream and from json parser it parses the exact string which is sent through outputstream. 
How does http module transform, a string to a json string?

Following is also failing. I believe in the below case, the string doesnt go through serializer.

```
clientRequest.setPayload("Hello");
io:println("json payload: ", clientRequest.getJsonPayload());
```
But the below code works.

```
clientRequest.setJsonPayload("Hello");
io:println("json payload: ", clientRequest.getJsonPayload());
```
This scenario doesn't work in 0.991.0 also.

**Comment by arukshani** [comment]
setPayload() method cannot distinguish a string from json when a string is assigned to a json variable.
```
      json jsonVal = "hello";
      req.setPayload(jsonValue);
```
setPayload here will send the payload as a string and not as json. If the user wants to send it as json then he/she has to specifically use setJsonPayload() method or set the content type method to "application/json". 

Since we don't have a fix for this, what we can do is to improve the setPayload() method's documentation so that the user is aware of this.

**Comment by arukshani** [comment]
Closing this with the doc improvements #17467
