### ISSUE TITLE
ballerina build command do not run tests in project/tests directory

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#17366]
**Description:**
Test .bal files in <project-dir>/tests do not get executed with build command, 

**Steps to reproduce:**

**Affected Versions:**
alpha test pack
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
We will provide this feature with a later release.

**Comment by hevayo** [comment]
No longer valid
