### ISSUE TITLE
Ballerina VS Code Plugin Shows two Show Diagram Menu Items

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#17387]
**Description:**
When we right click on the Ballerina VS Code editor we get a popup menu. There we can observe the same menu item "Show Diagram" appears twice.

**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.991.2 VS Code Plugin

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Related Issues (optional):**
NA

**Comment by kaviththiranga** [comment]
<img width="552" alt="Screen Shot 2019-08-06 at 4 04 49 PM" src="https://user-images.githubusercontent.com/1505855/62533294-f39df800-b863-11e9-9a49-4c8cd71b9498.png">

This is replaced with ```Project Overview``` diagram feature and fixed with 1.0.0-alpha.
