### ISSUE TITLE
Ballerina build command fail when passing file with full path

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#17390]
**Description:**
ballerina build  home/waruna/projects/main.bal

error: no ballerina source files found in module 'main.bal'

sample bal

import ballerina/io;

public function main() {
    io:print("hello");
}

**Affected Versions:**
1.0-alpha

**Comment by warunalakshitha** [comment]
run command works.

**Comment by warunalakshitha** [comment]
As a workround u can go to path and execute the build command .
cd /home/waruna/projects/
ballerina build  main.bal

**Comment by hevayo** [comment]
ballerina build --sourceroot home/waruna/projects/ main.bal will also work.
