### ISSUE TITLE
Add the missing implementations in lang lib functions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17395]
Some of the lang lib function implementations were left out for the alpha. For example, `removeAll()` in arrays. Need to provide implementations for these.

**Comment by pubudu91** [comment]
NaN definition and default expressions/values in the functions need to be added.

**Comment by pubudu91** [comment]
Related to #16005

**Comment by hasithaa** [comment]
Update langlib array functions as well. 
public function slice(Type[] arr, int startIndex, int endIndex = arr.length()) returns Type[] = external;

**Comment by pubudu91** [comment]
Also, see if functions like sorting need to be in-place sorting
