### ISSUE TITLE
Error when using nats example with NATS 2.0

### ISSUE THREAD

**Issue by paramids** [ballerina-platform/ballerina-lang#17407]
**Description:**
Produces an error in terminal : "Unable to connect to gnatsd server. {}
        at ballerina/nats:init(<native>)
           ballerina/nats:__init(connection/connection.bal:24)
           ballerina/nats:__init(consumer/listener.bal:30)" 
when reproducing the Nats example. Nats 2.0.0 release has a name change from gnatsd to nat-stream-server.

**Steps to reproduce:**
installed nats using docker as specified in new documentation

**Affected Versions:**
Using ballerina 0.991.0 with intelliJ idea plugin

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Related Issues (optional):**
Rename gnatsd server call to nats-streaming-server in the respective ballerina call to the jnats and/or java-nats-streaming.

**Suggested Labels (optional):**
nats, messaging

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
Please use NATS connector in Ballerina 1.0.0 alpha release. We have revamped our NATS connector in the latest release

**Comment by daneshk** [comment]
You can download Ballerina alpha distribution from [1]. You can find the latest examples in [1].
Please let us know if you find any issues in NATS connector in the latest alpha release.

1. https://ballerina.io/downloads/
2. https://github.com/ballerina-platform/ballerina-lang/tree/master/examples/nats-streaming-client

**Comment by paramids** [comment]
Migrated to ballerina-1.0.0-alpha and Idea plugin 1.0.0-alpha. 
Ballerina command init have been removed... Having trouble initializing the project and running tests from the project home folder.. Any references?

**Comment by daneshk** [comment]
Sorry, I would have mentioned it before. Ballerina project structure also gets change from 1.0.0 release. We are going to update those content in Ballerina website very soon and we are going to announce all those changes very soon.

Until then you can please refer to the following,
- Ballerina project structure[1]
- Quick tour guide[2]

1. https://v1-0-alpha.ballerina.io/learn/how-to-structure-ballerina-code/#projects
2. https://v1-0-alpha.ballerina.io/learn/quick-tour/

**Comment by paramids** [comment]
Very well then..I shall wait for the 1.0.0 release.. Thanks
