### ISSUE TITLE
Readable Channels Returning Incorrectly Returning an Error on Close

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#17424]
In readable channels, such as io:ReadableCharacterChannel, when it does "read" operations first, and after it hits EOF, if we try to do a "close" operation, it returns an invalid EOF error. It seems to be simply returning the context of the earlier read event that was processed through the channel. The close operation seems to be internally succeeding, but it is returning an older error value in the close operation. 

Following is an example:-
```ballerina
function toString(io:ReadableByteChannel input) returns string {
    string result = "";
    io:ReadableCharacterChannel charIn = new(input, "UTF-8");
    while (true) {
        var x = charIn.read(1);
        if (x is error) { break; }
        else { result = result + x; }
    }
    var ign = charIn.close();
    io:println("*** XXXX: ", ign);
    return <@untainted> result;
}

function testExecInUnixLike2() returns string|error {
    system:Process x1 = check system:exec("pwd", {}, "/");
    var x1out = x1.stdout();
    var result = toString(x1out);
    return result;
}
```
Running the function testExecInUnixLike2 will print an output similar to the following:-

    *** XXXX: error {ballerina/io}GenericError message=io.EOF cause=null

This is the last EOF error of "charIn.read" operation.

**Comment by lafernando** [comment]
Also, the below scenario also demonstrates the erroneous behavior:

```balleria
import ballerina/io;
import ballerina/system;
import ballerina/runtime;

public function main() returns error? {
    io:println("Start");
    var result2 = testExecInUnixLike2();
    io:println("Result2: ", result2);
    var result3 = testExecInUnixLike3();
    io:println("Result3: ", result3);
}

function testExecInUnixLike2() returns string|error {
    system:Process x1 = check system:exec("pwd", {}, "/");
    var x1out = x1.stdout();
    var result = toString(x1out);
    return result;
}

function testExecInUnixLike3() returns string|error {
    system:Process x1 = check system:exec("grep", {}, (), "BAL_TEST");
    io:WritableDataChannel ch = new(x1.stdin());
    var x = ch.writeString("BAL_TEST", "UTF-8");
    if (x is error) {
        io:println("E1:", x);
    }
    x = ch.close();
    if (x is error) {
        io:println("E2:", x);
    }
    var result = toString(x1.stdout());
    return result;
}

public function toString(io:ReadableByteChannel input) returns string {
    string result = "";
    io:ReadableCharacterChannel charIn = new(input, "UTF-8");
    while (true) {
        var x = charIn.read(1);
        if (x is error) { break; }
        else { result = result + x; }
    }
    var ign = charIn.close();
    return <@untainted> result;
}
```

The output of this is as below:

Start
Result2: /

E1:error {ballerina/io}GenericError message=io.EOF cause=null
E2:error {ballerina/io}GenericError message=io.EOF cause=null
Result3: BAL_TEST

If the call to "testExecInUnixLike2" is commented out, the E1 and E2 message will not be printed, and the invalid error messages will not come. So this shows this issues spans different I/O calls also.

**Comment by wggihan** [comment]
@lafernando I have fixed all the places this erronus situtation present. If it is possible, can you please check this with master since the PR got merged.
