### ISSUE TITLE
Error when using ballerinax/kubernetes

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#17428]
**Description:**

Trying to run the given code snippet after installing Ballerina 1.0.0 Alpha by the installer, it gives an error saying error: invoking main method failed due to java.lang.NoClassDefFoundError: ballerinax/kubernetes/___init

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerinax/kubernetes;

public function main() {
    io:println("Hello, World!");
}
```

**Affected Versions:**
Ballerina 1.0.0 Alpha

**Comment by keizer619** [comment]
This issue exists in the all extensions and we will be fixing this in next immediate release.
As a work around, you need to replace the .jar file manually.

These are steps
1. Download docker-extension-balo-1.0.0-alpha.zip file from nexus [1] and unzip it.
2. Copy docker-artifacts/docker.jar and paste at <B7A_HOME>/bre/lib

You need to do the same steps for k8 as well.

[1] http://maven.wso2.org/nexus/content/repositories/releases/org/ballerinax/docker/docker-extension-balo/1.0.0-alpha/docker-extension-balo-1.0.0-alpha.zip

**Comment by keizer619** [comment]
Following PRs will fix the above issue
https://github.com/ballerinax/kubernetes/pull/352
https://github.com/ballerinax/docker/pull/237
https://github.com/ballerinax/awslambda/pull/33
https://github.com/ballerina-platform/ballerina-distribution/pull/151
