### ISSUE TITLE
Improve `undefined function 'xxx'` error

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#17433]
**Description:**
I have a code as following. Following error is printed when compiled. How to get the length of a map?

```bash
$ ballerina build issue.bal
Compiling source
    issue.bal
error: .::issue.bal:24:48: undefined function 'length'
```

```ballerina
import ballerina/io;

public type Component record {|
    string name;
    map<TCPIngress | GRPCIngress > ingresses?;
|};

public type TCPIngress record {|
    int backendPort;
    int gatewayPort?;
|};

public type GRPCIngress record {|
    *TCPIngress;
    string protoFile?;
|};

public type CellImage record {|
	map<Component> components;
|};

function validateCell(CellImage cellImage) {
    foreach var component in cellImage.components {
        if (!(component["ingresses"] is ()) && component.get("ingresses").length() > 1) {
            io:println("length is more than 1");
        }
    }
} 
```
**Steps to reproduce:**
Compile the above Ballerina program.

**Affected Versions:**
```
Ballerina 1.0.0-alpha
Language specification 2019R2
Ballerina tool 1.0.0
```
**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
In this specific case, `component.get()` returns a value of `string| map<TCPIngress | GRPCIngress >` (or panic if the given key is not found).  This union type doesn't belong to the same basic type. Hence the compiler falls back to `lang.value` module and looks for the method `.length()` which is not defined there. Hence you see this error message. 

Spec says:
> the method-call-expr will be turned into a call to a function in the lang library m:method-name(expression, arg-list), where m is an automatically created module prefix for a module lang.M of the lang library, where M is selected as follows.

> If the static type of expression is a subtype of some basic type with identifier B, and the module lang.B contains a function method-name then M is B. The identifier for a basic type is the reserved identifier used in type descriptors for subtypes of that basic type, as listed in the Lang library section.
> Otherwise, M is value.

But I agree, we can improve the error message to give a better explanation. Hence keeping this issue open to track error message related improvement.

**Comment by pubudu91** [comment]
@anuruddhal @hasithaa The above currently gives the following error:
```
undefined function 'length' in type '(string|map<(TCPIngress|GRPCIngress)>)'
```
Is this clear enough as to why `length()` is undefined? 🤔

**Comment by hasithaa** [comment]
Verified it. This should be good enough for now. Hence closing.
