### ISSUE TITLE
Compile error when Ballerina.toml have additional fields.

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#17438]
**Description:**
I have a Ballerina project structred as below.
```
.
├── Ballerina.toml
└── src
    └── cellery
        └── natives.bal
```

My Ballerina.toml file looks as follow.
```toml
[project]
org-name = "celleryio"
version = "0.0.0"
license = "Apache 2.0"
```
When the project is compiled it prints the following error.
```
ballerina compile --skip-tests
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3471307/ballerina-internal.log)

If the following line is removed from Ballerina.toml file it compiles successfully.
```
license = "Apache 2.0"
```
**Steps to reproduce:**
Described in the description.

**Affected Versions:**
Ballerina 1.0.0-alpha
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by suganyasuven** [comment]
This issue is fixed with the ballerina-1.0.4 release. Hence closing this issue.
