### ISSUE TITLE
Error in the authentication handler interface validation

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#17436]
**Description:**
I have written new authentication handler. But when implementing the process method of the interface which accepts http:Request as a method parameter. If i written it as http:Request request then it gives the following error.
`mismatched function signatures: expected 'public function process(ballerina/http:Request req) returns (boolean|ballerina/http:AuthenticationError)', found 'public function process(ballerina/http:Request request) returns (boolean|ballerina/http:AuthenticationError)'`

Here is the interface implementation
`public function process(http:Request request) returns boolean|http:AuthenticationError`

But if I change it like below compilation error goes away
``public function process(http:Request req) returns boolean|http:AuthenticationError``
**Steps to reproduce:**

**Affected Versions:**
1.0.0-alpha
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
According to the Ballerina specification [1], this is not supported since the specification defines `object-type-reference` as follows:

```
object-type-reference :=
   * type-reference ;
The type-reference in an object-type-reference must reference an abstract object type. The object-member-descriptors from the referenced type are copied into the type being defined; the meaning is the same as if they had been specified explicitly.
```

Hence, closing the issue. Please reopen the ticket if there are any concerns.

[1] https://htmlpreview.github.io/?https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/v2019R2/lang/spec.html
