### ISSUE TITLE
jBallerina scheduler stability testing

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#17448]
**Description:**
jBallerina scheduler stability testing. Need long running and some load testing

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by manuranga** [comment]
Done by @ldclakmal , performances is consistent with pervious version.
