### ISSUE TITLE
Remove BVM and its references 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#17443]
**Description:**
Remove BVM and its references 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
The majority of the BVM classes have been removed. But there are few more which are used by the unit test classes. This requires a migration effort hence pushing this to post 1.0.

**Comment by manuranga** [comment]
left over sub tasks moved to #22075
