### ISSUE TITLE
Bad Sad error when there is a deadlock in workers

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#17474]
**Description:**
When workers are written so there is a deadlock when trying to run it the "Bad Sad" error comes.

**Steps to reproduce:**
```ballerina
public function main(string... args) {
    worker w1 {
        wait w2;
    }
    worker w2 {
        wait w1;
    }
}
```

can be reproduced with other deadlock scenarios like this as well

```ballerina
public function main(string... args) {
    worker w1 {
        wait w2;
        1 -> w2;
    }
    worker w2 {
        int a = <- w1;
    }
}
```

**Affected Versions:**
1.0.0-alpha

**Comment by MaryamZi** [comment]
This is not just for deadlocks - see https://github.com/ballerina-platform/ballerina-lang/issues/18024.

Compilations fails on 1.0.1 with 
```
error: .::xyz.bal:3:14: unsupported worker reference 'w2'
error: .::xyz.bal:6:14: unsupported worker reference 'w1'
```
