### ISSUE TITLE
Build tasks should not proceed to next, if the previous one failed

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#17475]
**Description:**
There are few build tasks (TaskExecutor) in the BuildCommand class. Currently if one of the task failed, still the task executor proceeds to the next, which can result in undesirable results. This should be fixed.

For example, if the CreateJarTask fails, then CopyModuleJarTask will surely fail as it depends on created jar.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Is there a way to reproduce this

**Comment by pramodya1994** [comment]
Tested with the following ballerina code.
```ballerina
import ballerina/io;
import ballerinax/java;

function createRandomUUID() returns handle = @java:Method {
    name: "randomUUID",
    class: "java.abc.UUID"
} external;

public function main() {
    io:println("Hello World!");
    var uuid = createRandomUUID();
    io:println(uuid);
}
```
After failing `CreateJarTask`, TaskExecutor existed without executing `CopyModuleJarTask`.

**Comment by hevayo** [comment]
Obseliete
