### ISSUE TITLE
Debug points in a different module are not getting hit

### ISSUE THREAD

**Issue by tharinduwijewardane** [ballerina-platform/ballerina-lang#17476]
**Description:**
When debugging with VS Code,
Its not possible to stop at a code line in a different file other than the focused file at the time of running the debugger.
Since the stepping into function does not work, there is no way to hit a debug point in a different file.

**Use case**
I need to debug a file in "module_1" and my main function is located in "module_2".
In order to get the dubber to run the main function its required to keep a file in module_2 focused when starting the debugger. That makes it impossible to debug a file in module_1.

**Affected Versions:**
1.0.0-alpha

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18085
