### ISSUE TITLE
Can't get the array sorted or lined-up with the map by map:keys(mapname)?

### ISSUE THREAD

**Issue by chaminda** [ballerina-platform/ballerina-lang#1749]
Output of the below is code[1] is as [2] and it is not lined up with the values stored in the map. Is there a way to get sorted out the map keys when store as the array (using map:keys() funtion)?

[1]
```
map newmap = {"test1":3,"test2":4,"test3":45};
    //getting map keys as an array
    string[] mapval = map:keys(newmap);
    //pring map values using keys;
    int i = 0;
    while(i<map:length(newmap)){
        system:println("map value "+string:valueOf(i)+" :"+mapval[i]);
        i = i +1;
     }
```
[2]
map value 0 :test2
map value 1 :test1
map value 2 :test3

**Comment by uthaiyashankar** [comment]
`import ballerina/io;

function main(string[] args){

    map newmap = {"test1":3,"test3":4,"test2":45};
    //getting map keys as an array
    string[] mapval = newmap.keys();
    //pring map values using keys;
    int i = 0;
    foreach s in mapval {
        io:println("map value "+ i +" :"+ s);
        i = i + 1;
    }

}`

Output: 
`map value 0 :test1
map value 1 :test3
map value 2 :test2`

@chaminda are you talking about getting the keys in sorted order?

**Comment by afkham** [comment]
It is not expected to have a sorted order by default for a map. If this is needed, we can create a different library which will contain a sorted map/linked map.
