### ISSUE TITLE
Process started by VSCode plugin takes 100% CPU

### ISSUE THREAD

**Issue by praminda** [ballerina-platform/ballerina-lang#17505]
**Description:**
Following process started by VS code plugin uses 100% CPU.
Process: `xxxx/jdk1.8.0_221.jdk/Contents/Home//bin/java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=xxxx/xxxx/language-server-heap-dump.hprof -Dballerina.home=xxxx/xxxx/ -Dballerina.debugLog= -Dexperimental=false -cp ::/xxxx/xxxx/bre/lib/*:/xxxx/xxxx/lang-server/lib/* org.ballerinalang.langserver.launchers.stdio.Main`

**Steps to reproduce:**
Install latest ballerina vscode plugin
Start working on a ballerina project.

**Affected Versions:**
1.0.0-alpha

**OS, DB, other environment details and versions:**
- MacOS Mojave
- jdk1.8.0_221

**Related Issues (optional):**

**Suggested Labels (optional):**

- Bug

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Fixed in latest master. Hence closing the issue
