### ISSUE TITLE
Compilation Crash for Service

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#17527]
While building the attached source file (order.txt), it gives the following error:
```
Compiling source
    order.bal
error: cannot find full qualified class for : OrderService$$service$0.getOrder
```

[order.txt](https://github.com/ballerina-platform/ballerina-lang/files/3483970/order.txt)
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3483971/ballerina-internal.log)

**Comment by SupunS** [comment]
Tested on top of PR https://github.com/ballerina-platform/ballerina-lang/pull/17613 (1.0.0-beta-SNAPSHOT), the sample compiled without any errors.
Hence closing.
