### ISSUE TITLE
Ballerina Diagram tasks for 1_0_0_beta

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#17578]
- [x] enable snapshot tests
- [ ] fix transaction rendering
- [x]  calculate depth numbers dynamically
- [ ]  activation line for endpoints needs somework to fix - in projector dot line appears
- [x] when dragging the diagram, if you click on accidentally click a goto source label, it goes to split mode, we need to prevent it while dragging
- [ ] action invocation and return line - two different colors - fix it
- [ ] zoom in via mouse pad on linux
- [ ] change cursor to pointer (grab icon) while dragging
- [ ] fit to width - add margin
- [ ] add a fill for expanded function box - do AB testing on fill vs rect
- [ ] Show Project overview context menu in editor - should we display index view or expand tree view upon click
- [x] tree view doesn't get cleared when all tabs are closed or when we switch to a non-ballerina tab

- [ ] show protocol in services
- [ ] On endpoint hover, show type
- [x] Hide if/while where interactions are not there.
- [ ] Shade out else lines where interactions are not there

**Comment by kaviththiranga** [comment]
Notes on review - 27th Aug 2019

- [ ] Activate project overview tree view upon a project folder opening - expand the tree view and show list of entrypoints for the diagram

**Comment by kaviththiranga** [comment]
- [ ] Avoid displaying comments in expanded function names
- [ ] Avoid redundant endpoint lines when a global endpoint is used in multiple places in same diagram

**Comment by kaviththiranga** [comment]
- [ ] Make [---] boxes which shows hidden code blocks less prominent
- [ ] When we change the depth, if the new diagram is not visible in the region where current viewbox is set, move the viewbox to 0,0

**Comment by kaviththiranga** [comment]
- [ ] Truncate signature text of expanded function to match width of the rendered function body - instead of picking max from body width vs label width

**Comment by kaviththiranga** [comment]
- [ ] Increase responsiveness of zoom in/out from mousepad

**Comment by kaviththiranga** [comment]
- [ ] Rename project overview to ballerina sequence view ( remove redundant index page)

- [ ] All params passed are marked as caller (check on it)

- [ ] can we make the look and feel of match box similar to collapsed func box, etc.?

- [ ] did we disable diagram editing? if not disable it.

**Comment by kaviththiranga** [comment]
- [ ] fork - join representation in diagram

**Comment by kaviththiranga** [comment]
- [ ] show full description of expanded function signature on hover

**Comment by kaviththiranga** [comment]
- [ ] disable match box in interaction mode when there are not interactions happening within match clauses

**Comment by kaviththiranga** [comment]
- [ ] test integration samples from beta test hackathon

**Comment by anupama-pathirage** [comment]
Closing this as these issues are captured by project dashboards now.
