### ISSUE TITLE
Disabled completion tests

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#17576]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/17575 disables lang server completion tests

- completionWithinInvocationArgs9.json
- completionWithinInvocationArgs10.json
- annotationBodyCompletion4.json

Note: This could be due to removing `public` flags from user defined types which are not marked as public.

**Comment by nadeeshaan** [comment]
Tests haver been enabled, hence closing the issue
