### ISSUE TITLE
Pushed modules are not visible in ballerina staging central

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#17580]
**Description:**
The modules pushed to ballerina staging central are not visible in Dashboard.

<img width="819" alt="Screen Shot 2019-08-12 at 10 01 46 AM" src="https://user-images.githubusercontent.com/38608578/62845749-3c343600-bce8-11e9-83d1-797bb2e07a64.png">

But once you search the module in search bar, the module is visible on search results.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
This has been fixed now.
