### ISSUE TITLE
Language Server is broken

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#17594]
**Description:**
Language Server is broken in the latest build. VSCode language client is receiving `\t<filename>Content-Length: ###` along with the content-length header. Thus, all functionalities are broken.

**Steps to reproduce:**
Try to start language server with a latest build.

**Affected Versions:**
1.0.0-beta-SNAPSHOT

**Comment by kaviththiranga** [comment]
Fixed with this https://github.com/ballerina-platform/ballerina-lang/pull/17595
