### ISSUE TITLE
Revisit __stop() method

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#17616]
**Description:**
Abstract listener's `__stop()` method is removed and 2 new method was introduced.
- `__gracefulStop()`
- `__immediateStop()`

Revisit stdlib `__stop()` method implementation to align expected behavior with these two methods. PR https://github.com/ballerina-platform/ballerina-lang/pull/17558 migrates `__stop()` implementation to `__immediateStop()`

**Comment by praneesha** [comment]
Need to check if API docs need to be updated WRT this.

**Comment by daneshk** [comment]
This change is already completed. Hense closing
