### ISSUE TITLE
Time parsing does not work properly for strings with time data only

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17610]
**Description:**
 Parsing a time  with HH:MM:SS will give incorrect time value.

**Steps to reproduce:**

```ballerina

import ballerina/io;
import ballerina/time;

public function main() {
    string timeFormatted = "";
    var timeRet = time:parse("09:46:22", "HH:mm:ss");
    if (timeRet is time:Time) {
        io:println(timeRet.time);
        string|error formattedRet = time:format(timeRet, "HH:mm:ss");
        if (formattedRet is string) {
            timeFormatted = formattedRet;
        }
    }
    io:println(timeFormatted);
}
```

**Expected Output:**
15382000
09:46:22

**Current Output:**
-62167203182000
09:46:22

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by wggihan** [comment]
This issue fixed with #17612.
