### ISSUE TITLE
Add tests for module init returning/panicking errors

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17633]
**Description:**
$title, once jBallerina changes are introduced for the same.

This should include tests for `check` at module level.

**Comment by MaryamZi** [comment]
Need to enable ServiceTest.testServiceInitNegativeTest or add a similar test too.

**Comment by lankavitharana** [comment]
PR https://github.com/ballerina-platform/ballerina-lang/pull/18215 adds tests related to this

**Comment by lankavitharana** [comment]
@MaryamZi I think test scenarios are covered now, please check on ServiceTest.testServiceInitNegativeTest you mentioned above and close the issue

**Comment by MaryamZi** [comment]
> @MaryamZi I think test scenarios are covered now, please check on ServiceTest.testServiceInitNegativeTest you mentioned above and close the issue

Yeah, sent https://github.com/ballerina-platform/ballerina-lang/pull/18448 to enable this.
