### ISSUE TITLE
BBEs are missing for lang lib operations

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#17648]
**Description:**
BBEs are missing for most of the newly introduced lang lib operations.

Example: arrays

**Comment by MaryamZi** [comment]
The plan was to improve the langlib Module.md files with examples on how to use each method/function. Keeping this issue open to track the improvement.

**Comment by MaryamZi** [comment]
Closing since this is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/15877.

Duplicates https://github.com/ballerina-platform/ballerina-lang/issues/15877 now.
