### ISSUE TITLE
How efficiently convert Ballerina data array (byte, int, float) to Java byte array? 

### ISSUE THREAD

**Issue by indikasampath2000** [ballerina-platform/ballerina-lang#17653]
**Description:**
The following method taking Ballerina byte array.
```
    # Set a byte array with the specified name.
    #
    # + return - Returns an error if it fails.
    public function setBytes(string name, byte[] value, int? offset = (), int? length = ()) returns error? {
        if(offset is int && length is int) {
            return setPortionOfBytes(self.jmsMessage, java:fromString(name), value, offset, length);
       } 
    }
```
 It invokes the Java inter-op function given below.
```
public function setPortionOfBytes(handle message, handle name, handle value, int offset, int length) returns error? = @java:Method {
    name: "setBytes",
    paramTypes: ["java.lang.String",{class:"byte", dimensions:1}, "int", "int"],
    class: "javax.jms.MapMessage"
} external;
```

How should I convert Ballerina data array to invoke Java inter-op function?

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by manuranga** [comment]
It will now pass a `ArrayValue`, it may internally have a `int[]` or `long[]` ect. Converting form that is anyway going to be inefficient and is up to the introp java developer to do so.
