### ISSUE TITLE
Grammar issue with rest parameter of nillable type

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#17670]
**Description:**

$title
I think this is due to introducing **?.** to access optional values of records.

**Steps to reproduce:**
```
public function main() {
  foo(1,2,3); 
}

function foo(int?... nums) {
    io:println("bar");
}
```
Error `invalid token '?.'`

But the following works

```
public function main() {
  foo(1,2,3); 
}

function foo((int?)... nums) {
    io:println("bar");
}
```

**Comment by dulvinw** [comment]
@SupunS can you please have a look?
