### ISSUE TITLE
Cannot resolve modules pushed to staging-central

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#17671]
**Description:**
Cannot resolve modules pushed to staging-central when the same org-name is used in Ballerina.toml of the project. This will be fixed when org-name is renamed to a different name.

Please find the internal log.

`[2019-08-14 12:36:29,478] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
error: 	 
	at ballerina:createError(module_pull.bal:56)
	   ballerina:pullPackage(module_pull.bal:141)
	   ballerina:main(module_pull.bal:101) 
`

**Steps to reproduce:**

**Affected Versions:**
Ballerina-1.0.0-alpha

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Fixed in 1.0.0-alpha3. https://github.com/ballerina-platform/ballerina-lang/pull/18121
