### ISSUE TITLE
HTTP caching is not working

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17686]
Currently HTTP caching is not working. Seems like a bug in the logic which adds responses to the cache. 
Problematic code block:https://github.com/ballerina-platform/ballerina-lang/blob/799db2e2caae022c32e21dd004975246eeb35932/stdlib/http/src/main/ballerina/src/http/caching/http_cache.bal#L53

**Comment by shafreenAnfar** [comment]
@pubudu91 Don't we have test-case for this ?

**Comment by pubudu91** [comment]
We don't. Will see about writing an integration test.
