### ISSUE TITLE
Ballerina constructs defined in test folder are visible across the module

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#17692]
**Description:**

$titles
**Steps to reproduce:**

_/project/src/module/main.bal_
```
import ballerina/io;
public function main() {
    beforeSuiteFunc();
    io:println(BALL);
}
```

_/project/src/module/tests/main_test.bal_
```
import ballerina/test;

const string BALL = "BALLERINA_TEST";

# Before Suite Function
@test:BeforeSuite
function beforeSuiteFunc () {
    io:println("I'm the before suite function!");
}
```

Output
```
I'm the before suite function!
BALLERINA_TEST
```

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**
MacOs 10.14.5
java version "1.8.0_212"

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Verified with a pre-1.0.2 pack. This issue is fixed.
