### ISSUE TITLE
Code action create local variable for jdbc client not working as expected

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17699]
**Description:**
Running the "add local variable" code action on the following ballerina code would result in two issues:
```ballerina
jdbcClient->update("INSERT INTO `events` (`date_time`) VALUES (?)");
```

1. Inserts an additional import to `import ballerinax/java.jdbc;`
2. Generates a local variable as follows:
```ballerina
(java.jdbc:UpdateResult|error) update = jdbcClient->update("INSERT INTO `events` (`date_time`) VALUES (?)");
```
Usage of the imported module should be `jdbc` instead of `java.jdbc` which results in a compilation error

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
VSCode Version: 1.36.1

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
