### ISSUE TITLE
Improve http service completion

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17690]
**Description:**
Autocomplete of http service is as follows:
```ballerina
service serviceName on new http:Listener(8080) {
    resource function newResource(http:Caller caller, http:Request request) {
        
    }
}
```

1. A suggestion to improve it as follows, so that it would look more complete
```ballerina 
service serviceName on new http:Listener(8080) {
    resource function newResource(http:Caller caller, http:Request request) {
        error? respond = caller->respond();
    }
}
```

2. Additionally, once the service is autogenerated, we only get the option to edit the service name, resource name and function param names of the resource, by switching using the tab. It would be better if the user can also edit the port value 8080

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
VSCode Version: 1.36.1

**Comment by mohanvive** [comment]
Closing the issue since it is outdated. There are some completion support are provided for services and we are working towards improving it.
