### ISSUE TITLE
Code suggestion shows duplicated function parameters for defaultable params

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17691]
**Description:**
The defaultable param message is shown twice. Refer image:
![Screenshot from 2019-08-15 10-00-43](https://user-images.githubusercontent.com/8677511/63072891-ba404900-bf43-11e9-848e-4f2345f6ab6d.png)

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
VSCode Version: 1.36.1

**Comment by nadeeshaan** [comment]
closing since the fix has been merged
