### ISSUE TITLE
Keywords are suggested after a keyword is typed

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#17702]
**Description:**
After typing a ballerina type or `public` keyword, if the suggestions is triggered it shows the same or a keyword as the suggestions list. Example is shown in the below screenshot.

![Screenshot (1)](https://user-images.githubusercontent.com/11191791/63076799-04312b00-bf54-11e9-9923-58ccb151acc2.png)

**Steps to reproduce:**
Type a keyword in a ballerina file and the trigger suggestions. 

**Affected Versions:**
1.0.0 Beta

**OS, DB, other environment details and versions:**
Windows 10
InteliJ Idea v2019

**Comment by mohanvive** [comment]
Issue is no longer valid in the latest VScode plugin. Hence, closing the issue.
