### ISSUE TITLE
Suggestions not given when defining a new error type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17708]
Refer to the image below
![Screenshot from 2019-08-15 12-11-51](https://user-images.githubusercontent.com/6260009/63077452-0a280b80-bf56-11e9-8bf7-121c847e83a5.png)

Shouldn't the constant `FOO_ERR_REASON` be suggested for the above case?

**Comment by pubudu91** [comment]
![Screenshot from 2019-08-15 12-16-49](https://user-images.githubusercontent.com/6260009/63077648-ab16c680-bf56-11e9-9a71-fb15560829ba.png)

Suggestions not working for the detail type either.

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master, after introducing the scope resolving based on the new syntax tree API. Hence closing the issue
