### ISSUE TITLE
[IDEA] Signature description is not properly shown when invoking constructor.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#17706]
**Description:**
Signature infobox for a new constructor is showing signature description which is cut off from the top.

<img width="1440" alt="Screen Shot 2019-08-15 at 12 00 42 PM" src="https://user-images.githubusercontent.com/9109762/63077198-1d86a700-bf55-11e9-80fd-c090c97f536b.png">

**Steps to reproduce:**
![8P5QCNiB36](https://user-images.githubusercontent.com/9109762/63077393-c59c7000-bf55-11e9-9751-c65def2de42c.gif)

**Affected Versions:**
1.0.0-beta-candidate

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with #18034.
