### ISSUE TITLE
Ballerina language server fails when installed for the first time

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#17700]
**Description:**
Ballerina language server fails when installed for the first time. It asks to restart the IDE after plugin installation. But getting an error. When restart again(for the second time), it works.

In 2019.2 IntelliJ it again breaks when the `main.bal` is already opened. Language server is not attached. Needed to close and reopen.

```
15/08/2019
07:05	BALLERINA_REPOSITORY was detected
			We've detected some packages from your BALLERINA_REPOSITORY.
			

07:05	Windows Defender might be impacting your build performance. IntelliJ IDEA checked the following directories:
			C:\Users\ballerina-dev\IdeaProjects\CLI Table Lib
			Fix...
			Don't show again
			Don't show again for this project

07:06	Windows Defender configuration updated

07:07	rawCommand : C:\Users\ballerina-dev\Desktop\ballerina-1.0.0-beta-SNAPSHOT\lib\tools\lang-server\launcher\language-server-launcher.bat 
			not initialized after 10s 
			Check settings 
```

**Steps to reproduce:**
Created a project through IntelliJ. When opening `main.bal` it asks to optimize Windows Defender for the folder. Then, getting 'rawCommand: C:\Users\ballerina-dev\Desktop\ballerina-1.0.0-beta\.... failed'.

**Affected Versions:**
ballerina-1.0.0-beta

**Comment by NipunaRanasinghe** [comment]
This issue is fixed in the latest IDEA language client release. Hence closing.
