### ISSUE TITLE
Typo in help command

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17709]
**Description:**
Typo in below section .

The word "sharable" should be changed to "shareable"

```
BALLERINA COMMANDS
    Available commands are:
        compile         Compile Ballerina module/project in-to a sharable
                        library(balo)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Compile command will be removed from 1.0.0-beta and will be replaces by build -c
