### ISSUE TITLE
Inner snippet indentation is missing

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#17705]
**Description:**
If a code snippet is generated and go to the beginning of the snippet ( beginning of the curly braces) and when hit enter, there should be an indentation inside the snippet, but the cursor starts from the beginning of the line. 

**Steps to reproduce:**
- Add a code snippet ( main function ) using suggestions. 
- Take the cursor to the starting curly brace and hit enter to go to a new line

**Affected Versions:**
1.0.0 Beta

**OS, DB, other environment details and versions:**
Windows 10
InteliJ Idea v2019

**Comment by nadeeshaan** [comment]
Closing since the issue has been fixed in v1.0.0
