### ISSUE TITLE
Typeguard auto complete not working as expected for union with error type

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17704]
**Description:**
![Screenshot from 2019-08-15 12-02-07](https://user-images.githubusercontent.com/8677511/63077052-af41e480-bf54-11e9-8770-dd59ccdeff48.png)
The type guard generated has an additional `else` keyword
```ballerina
        error? respond = caller->respond();
        if (respond is error) {
            
        } else  else {
            
        }
```

**Steps to reproduce:**
Click on the type guard option on any variable of union type which includes only two types from which one of them is error type
i.e.: type guard generation on `boolean|int|error x = true;` works but fails for `boolean|error x = true;`

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
VSCode Version: 1.36.1

**Comment by nadeeshaan** [comment]
Fix has been merged into beta release, hence closing the issue
