### ISSUE TITLE
Wrong suggestions given for unions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17703]
Refer to the image below:
![Screenshot from 2019-08-15 12-01-40](https://user-images.githubusercontent.com/6260009/63077035-a81ad680-bf54-11e9-9a72-7e61b72e55fd.png)

The function suggestions given for the above union are incorrect. It seems that the functions in `lang.value` module are suggested for any type of variable irrespective of their relevance to the variable in question. 

Following are similar such unions: `int|string|float`, `int|float`

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
