### ISSUE TITLE
Function docs are not shown for langlib function invocation chains

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#17718]
**Description:**
```ballerina
import ballerina/io;

function foo(string filePath) returns error? {
    io:ReadableCSVChannel rCsvChannel = checkpanic io:openReadableCsvFile(filePath);
    string [] columnHeaders = [];
    if (rCsvChannel.hasNext()) {
        // 'check' doens't filter all errors.!!!
        var titles = check rCsvChannel.getNext();
        if (titles is string[]) {
            io:println(titles);
            columnHeaders = titles;
        }
    }


    // Function docs are not shown for `toLowerAscii` and `indexOf`
    var s = columnHeaders.'map(s => s.toLowerAscii()).indexOf("district");
    io:println("Column number: " + s.toString());

    checkpanic rCsvChannel.close();
}
```

Nothing is shown when hovering over `toLowerAscii` and `indexOf` functions
**Steps to reproduce:**

**Affected Versions:**
1.0-beta
**OS, DB, other environment details and versions:**
VSCode 
Win10
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Same goes for within arrow functions
```ballerina
(function (string) returns boolean) spliter = p => math:random() > .5;
```

` math:random` doc is not shown when hovering over it.

**Comment by nadeeshaan** [comment]
In order to fix the issue we have to resolve https://github.com/ballerina-platform/ballerina-lang/issues/18278

**Comment by nadeeshaan** [comment]
Issue has been fixed in master. Hence closing the issue
