### ISSUE TITLE
<,> marks are rendered as &gt,&lt in api docs

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#17713]
**Description:**
Note the $subject.

**Steps to reproduce:**
Refer the https://v1-0-0-alpha.ballerina.io/learn/api-docs/ballerina/java.jdbc/index.html doc's **Creating tables** section.
**Affected Versions:**
v1-0-0-alpha docs
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
This is fixed in new API docs[1] as shown below.

<img width="1680" alt="Screenshot 2019-10-24 at 17 46 24" src="https://user-images.githubusercontent.com/11707273/67484765-627e3680-f686-11e9-81a7-bdfc091704a6.png">

[1] https://v1-0.ballerina.io/learn/api-docs/ballerina/java.jdbc/index.html
