### ISSUE TITLE
Wrong auto completion in fork block

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#17715]
**Description:**
In fork block, there is no auto-completion provided to add a worker. 
![akHSccZkkV](https://user-images.githubusercontent.com/9109762/63078507-50cb3500-bf59-11e9-82ef-bd242f5fe440.gif)

**Affected Versions:**
1.0.0-beta-candidate

**Comment by nadeeshaan** [comment]
This fixed in the beta, hence closing the issue
