### ISSUE TITLE
Wrong suggestions given for error constructor params

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17722]
Refer the below image. For the error constructor, it should ideally only be suggesting the available parameters of the constructor. The error constructor takes named args. Each arg is a field in the error detail record. If the record is open, the suggestions should ideally show that as well (i.e., show the type of the rest field. If the detail record is closed, then no need to show a rest field).

![Screenshot from 2019-08-15 12-30-20](https://user-images.githubusercontent.com/6260009/63081608-a73c7180-bf61-11e9-8a52-74ec7d8134e9.png)

**Comment by nadeeshaan** [comment]
Closing the issue since the syntax has been changed along with the resolving implementation
