### ISSUE TITLE
No suggestions/autocomplete for IntelliJ on Windows

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#17725]
**Description:**
Not getting any suggestions when implementing with intelli j plugin.

<img width="496" alt="Screen Shot 2019-08-15 at 1 38 13 PM" src="https://user-images.githubusercontent.com/4398820/63081979-a2c48880-bf62-11e9-88f2-ee68a6ab03eb.png">

**OS, DB, other environment details and versions:**
Windows Server 2019

**Comment by NipunaRanasinghe** [comment]
@hemikak As per the discussion we had, closing this issue since this scenario is tested and it works with the latest plugin release (1.1.0) on windows.
