### ISSUE TITLE
Source does not get updated in VSCode intermittently

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#17729]
**Description:**
`incremental source update` causes an issue where the source always shows a compiler error but the source can be built properly.
Re-opening the source will fix the issue

**Steps to reproduce:**
Intermittent

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT
VSCode Version: 1.36.1

**Comment by nadeeshaan** [comment]
@Anoukh we have moved from incremental update to full source sync mode. This fix has been merged into alpha-3 and hence closing the issue. If the issue still can be reproduced, please reopen
