### ISSUE TITLE
Code Action, "create Local variable" doesn't work for action invocation.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#17735]
**Description:**
Code action to create a local variable for an action invocation that has a return value doesn't work.
![hhuzfSKpU7](https://user-images.githubusercontent.com/9109762/63083478-714dbc00-bf66-11e9-98c6-a84b09f96f64.gif)

**Affected Versions:**
1.0.0-beta-candidate

**Comment by NipunaMarcus** [comment]
This doesn't work for the following scenario either

![W7E18Nrr66](https://user-images.githubusercontent.com/9109762/63083967-bcb49a00-bf67-11e9-85ba-1d0e37c47baa.gif)

**Comment by NipunaMarcus** [comment]
Common factor seems to be all the invoking methods returning a Union type.

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
