### ISSUE TITLE
VSCode diagrams do not work in Windows

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#17736]
**Description:**
VSCode diagrams do not work in Windows. 

The console output

<img width="1157" alt="Screen Shot 2019-08-15 at 2 18 46 PM" src="https://user-images.githubusercontent.com/2918812/63083929-a3abe900-bf67-11e9-89f7-d60f7fe9b39a.png">

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/17766
