### ISSUE TITLE
Invalid compiler error when dot operator is used for package alias

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#17730]
**Description:**
Invalid compiler error when using dot operator on package alias.

![Screenshot (2)](https://user-images.githubusercontent.com/11191791/63082913-1071b400-bf65-11e9-9bd0-d2f7eb7eeb8a.png)

**Steps to reproduce:**
Call a function in a package using `.` character

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows 10
InteliJ Idea v2019

**Comment by MaryamZi** [comment]
The error we get here is "undefined symbol 'io'".

IMO, this error is not invalid. With the `.`, it is assumed that this is a method call, resulting in the above error since there is no `io` variable defined.

This is the same error for any method call on an undefined variable.

**Comment by hasithaa** [comment]
There is another way to look at this issue. In this example, symbol `io` defined, but in a different symbol space. Only allowed operations is ":".  So we can fall back and say, `'.' operations not allowed here`

But this requires some change from the compiler side. So let's keep track of this improvement here.

**Comment by MaryamZi** [comment]
@hasithaa so when the symbol is not found, we'll have to look in other symbol spaces and if the symbol is available, provide an error message depending on the allowed operations for the particular symbol space? 

I guess this will mean the compiler has to be aware of what operations (operators) can be specified after a symbol in the particular symbol space? (e.g., `:` for imports, XML namespaces ?)

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
