### ISSUE TITLE
Snippet to add a public function

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#17734]
**Description:**
It will help if we had a snippet to add a public function. Currently there is a snippet to add a main function but I guess it is a common scenario that users need to add other public function as well. If we have a snippet that comes when user type "p.." in top level that will help.

**Affected Versions:**
ballerina-1.0.0-beta-SNAPSHOT

**Comment by nadeeshaan** [comment]
Current flow support was to add the completion support for public keyword and the completion support for valid snippets after the public keyword. Currently we suggest the function snippets after the public keyword as well. WDYT?

**Comment by nadeeshaan** [comment]
This has been addressed by providing suggestions for public keyword as well as function snippets after that. Earlier we had issues with suggestions after public keyword and now this has been fixed. Hence closing the issue
