### ISSUE TITLE
Code Action, create local variable not working for object fields 

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#17748]
**Description:**
Code Action, create local variable not working for object fields 

**Steps to reproduce:**
```ballerina
public type Table object {
    map<string> chars = {};

    function getChar(string name) {
        self.chars[name];
    }
};
```
**Affected Versions:**
1.0.0-beta-SNAPSHOT

**Comment by nadeeshaan** [comment]
From 1.0.1 onwards, for this particular use-case, the generated result is as follows, which is having a semantic error.
`map<string> a = self.chars[name];`
