### ISSUE TITLE
Documentation for pushing native library to central

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#17756]
**Description:**
We need to have documentation on interoperability support and pushing native library to central

**Steps to reproduce:**
N/A

**Affected Versions:**
jballerin 1.0 beta

**Comment by sameerajayasoma** [comment]
Java interoperability docs are here. https://v1-0-0-alpha.ballerina.io/learn/by-example/create-java-objects.html

**Comment by praneesha** [comment]
We need to add [1] to cover information on pushing native library to central.

[1] https://docs.google.com/document/d/1ljdeKI6IrTmxi5jKNgd8aNbLW4w-KSd8DwEHQOndmWs/edit#heading=h.re44vh45id9m

**Comment by praneesha** [comment]
Closing this as this will be done via [1].

[1] https://github.com/ballerina-platform/ballerina-lang/issues/19488
