### ISSUE TITLE
Improve error message when running multiple modules

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#17755]
**Description:**

In project there are 2 modules with 2 services. I build whole project. 

Then execute `ballerina run module1` and service1 will be running. Then if i try to do execute `ballerina run module2` in another terminal window, it will print following error which needs to be improved. 

`
error: unable to clean target'C:\Users\wso2\Desktop\beta-test\guaranteed-gateway\target': C:\Users\wso2\Desktop\beta-test\guaranteed-gateway\target`

**Comment by hevayo** [comment]
Obseliete
