### ISSUE TITLE
It is hard to figure out how to read a text file using docs

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#17762]
**Description:**
I want to read a text file in to a string. Search BBE and API docs for `file` didn't find any example on how to read a file. Then tried using the io package but it only gives a binary output. later on got to know that you have to use Charactor I/O. 

May be it will help to rename BBE Charactor I/O guide to `reading and writing to files`. And to provide a high level API to read and write files. 

**Affected Versions:**
ballerina-1.0.0-beta-SNAPSHOT

**Comment by praneesha** [comment]
Fixed via [1].

[1] https://github.com/ballerina-platform/ballerina-lang/pull/19618
