### ISSUE TITLE
internal:replaceAll causes an unexpected error.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#17765]
**Description:**
Error occurs when trying to replace backslash using internal module.

**Steps to reproduce:**
```ballerina
string reqPath = "/favicon.ico";
reqPath = internal:replaceAll(reqPath, "\\", "/");
```

This causes an error when running:
```
error: error Unexpected internal error near index 1
```

**Affected Versions:**
1.0.0-beta-snapshot

**OS, DB, other environment details and versions:**
Windows

**Comment by wggihan** [comment]
Ballerina/internal module will remove with beta. So this will not fix.
