### ISSUE TITLE
No clear example on how to read an entire file

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#17760]
**Description:**
There is no clear example on showing how to read an entire file which is read using `io:ReadableCharacterChannel`. 

**Steps to reproduce:**

**Affected Versions:**
1.0.0 beta

**OS, DB, other environment details and versions:**
Windows 10
InteliJ Idea v2019

**Comment by praneesha** [comment]
Now, this is covered in [1].

[1] https://ballerina.io/learn/by-example/character-io.html
