### ISSUE TITLE
No suggestions within [] for member access

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17770]
**Description:**
$title.

![no-suggestions-for-member](https://user-images.githubusercontent.com/8376983/63090537-3e60f380-bf79-11e9-99d7-4dcf87812503.png)

**Steps to reproduce:**
Incomplete code to reproduce
```ballerina
import ballerina/io;

type Foo record {
    string st;
};

map<Foo> m = {};

public function main(string... args) {
    Foo fv = { st: "string value" };
    m[f]
}
```

**Comment by nadeeshaan** [comment]
This Issue has been resolved with the latest revamp. Hence closing the issue
