### ISSUE TITLE
HTTP Library: Setting the payload after setting the content type overrides the content type.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#17772]
**Description:**
When the content type is set with "setContentType" function and then the payload is set with "setTextPayload", the content type gets overridden to text/plain.

**Steps to reproduce:**
```ballerina
string directoryContent = "<p>blah</p>";
res.setContentType("text/html; charset=utf-8");
res.setTextPayload(directoryContent);

// send request
```

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows

**Comment by arukshani** [comment]
This is as per the design. If you want to retain the content type pass that value as the optional para to setTextPayload method.

res.setTextPayload(directoryContent, contentType = ""text/html; charset=utf-8"");
