### ISSUE TITLE
Unable to build modules which use OpenAPI

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17776]
I generated a service using an OpenAPI file. When trying to build the module which has that service, I get the following error:
```
$ ballerina build file_server
Compiling source
	pubudu/file_server:0.1.0

Creating balos
	target/balo/file_server-2019r3-any-0.1.0.balo
error: unable to find the dependency jar from the distribution: /usr/lib/ballerina/ballerina-1.0.0-beta-SNAPSHOT/bre/lib/ballerina-openapi-1.0.0-beta-SNAPSHOT.jar
```
It seems in the distribution, the relevant JAR is misnamed. The file it's looking for is actually called `openapi.jar` in the distribution.

**Comment by NipunaMarcus** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18111/commits/02e4068b827adf0d538e9d8fcfd524dcb2e01cea

Hence closing the issue.
