### ISSUE TITLE
Can't get the custom websub subscriber to work when it runs as a module

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-lang#17788]
**Description:**
Mapping a resource based on the payload key gives an error "Value creator object is not available".
This happens when the project is run as a module instead of a file

**Steps to reproduce:**
Run the custom subscriber logic as a module

**Affected Versions:**
1.0 beta

**Comment by MaryamZi** [comment]
This seems to be due to a package name mismatch, for the value creation, when the webhook is in a module.

Until this is fixed, the implementation can be tested by having the webhook in a .bal file that is not part of a module.
