### ISSUE TITLE
Diagram fit to screen should bring the entire picture in to view

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#17787]
**Description:**
Currently fit to screen act as fit to width which only adjust the diagram to match width of the screen. And if the diagram is long it will be hidden from the bottom. Ideally fit to screen should bring the full diagram in to the screen.

**Affected Versions:**
ballerina-1.0.0-beta-SNAPSHOT

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
