### ISSUE TITLE
Top level suggestions are not working

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17789]
**Description:**
$subject with the below code. Suggestions for the `math:` are invalide

```ballerina
import ballerina/math;

const J2000 = 2451545;
const DEGREE = math:

```

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/16300038/63093374-85071b80-bf82-11e9-9d98-27c2e2ceb2ed.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
According to the [grammar](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/resources/grammar/BallerinaParser.g4#L119) above syntax is not supported.  So, we'll avoid this invalid suggestions
