### ISSUE TITLE
When Click and drag the diagram, cursor should change to grab

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#17783]
**Description:**
When you click and hold the diagram the cursor should change to grab cursor. Check the behavior on google maps.

**Affected Versions:**
ballerina-1.0.0-beta-SNAPSHOT

**Comment by kaviththiranga** [comment]
This is already captured in https://github.com/ballerina-platform/ballerina-lang/issues/17578, hence closing.
