### ISSUE TITLE
system:readDir lists files and folder in sub directories in windows.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#17786]
**Description:**
When using the `system:readDir` to get the directories of a folder it gives files and folders of subdirectories as well. Ideally it should only gives files and folders of the given path.

It also outputs the current folder as well.

Suggestion: May be we can pass in another arg stating recursive or not.

**Steps to reproduce:**
```ballerina
system:FileInfo[] files = check system:readDir(path);
foreach system:FileInfo file in files {
    string isDirectory = file.isDir() ? "true" : "false";
    log:printInfo(file.getName() + " - " + isDirectory);
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows

**Comment by pubudu91** [comment]
This is the same behaviour in Ubuntu as well.
