### ISSUE TITLE
Rephrase the error text for file not found error

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17781]
Consider the following:
```ballerina
system:FileInfo[] fileList = checkpanic system:readDir("invalid/path");
```
The error given for the above is:
```
error: error {ballerina/system}InvalidOperationError message=File doesn't exist in path ~/Downloads cause=null
```
Can't we just simply say `File not found: <file_path>`? "File doesn't exist in path" sounds odd.

**Comment by aashikam** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/17875
