### ISSUE TITLE
Suggestions are not working with return statement

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17793]
**Description:**

Suggestions are not working with `return` statement. With the below code, instead of suggestions for the math module, it gives suggestions in the current scope.

```ballerina
import ballerina/math;

function getDeclination() returns float {
    return math:
}
```

<img width="696" alt="image" src="https://user-images.githubusercontent.com/16300038/63093941-93563700-bf84-11e9-8c49-24872f925c26.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
closing since the fix has been merged
