### ISSUE TITLE
Formatting breaks for .concat(" ")

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#17799]
**Description:**
Formatting breaks for .concat(" ")

**Steps to reproduce:**
**Before formatting:**
```ballerina
string str = "";
foreach int i in 0 ..< 5 {
    str = str.concat(" ");
}
```

**After formatting:**
```ballerina
string str = "";
foreach int i in 0 ..< 5 {
    str = str.concat( " ");
}
```
**Affected Versions:**
1.0.0-beta-SNAPSHOT

**Comment by NipunaMarcus** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/17753
