### ISSUE TITLE
Doc commands generates invalid urls for primitive types and stdlib types

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#17802]
**Description:**

When we generate docs for custom project using `ballerina doc` as follows the urls generated for primitive types and types in stdlib are not correct.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/16300038/63099085-f69a9600-bf91-11e9-939e-fce57944c2ca.png">

For example the links highligted below are as follows. Which gives `File Not Found` error in browser
file://<PathToProject>/SunProject/target/api-docs/lang.annotations/UNKOWN/float.html
file:///<PathToProject>/SunProject/target/api-docs/time/records/Time.html

<img width="397" alt="image" src="https://user-images.githubusercontent.com/16300038/63099315-788abf00-bf92-11e9-8cf7-d4cdaa2c1954.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
This can be closed with the fix in https://github.com/ballerina-platform/ballerina-lang/issues/8535 and primitives won't have links in the new design.
