### ISSUE TITLE
Typo in the accepted completion

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17807]
Refer the image below:
![Screenshot from 2019-08-15 19-47-02](https://user-images.githubusercontent.com/6260009/63100938-b76e4400-bf95-11e9-8fcd-4c1505696711.png)
As it can be seen, the suggestion displays the correct completion. 
![Screenshot from 2019-08-15 19-47-08](https://user-images.githubusercontent.com/6260009/63101052-ec7a9680-bf95-11e9-82a5-3eacfd188fb9.png)
But when you accept the suggestion, the completed word contains a typo.

**Comment by nadeeshaan** [comment]
closing since the fix has been merged
