### ISSUE TITLE
Ballerina java interoperability with JNI is not supported

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#17805]
**Description:**
When java native code uses JNI it is not possible to use such functions in ballerina out of the box apart from by setting the `.so` file to the java jre path of ballerina.

**Steps to reproduce:**
Running the tdlib client: https://github.com/riyafa/ballerina-tdlib-client.git

**Affected Versions:**
Ballerina 1.0.0 beta
**OS, DB, other environment details and versions:**

**Comment by Ibaqu** [comment]
We need to implement the following : https://github.com/ballerina-platform/ballerina-lang/issues/20635

**Comment by anupama-pathirage** [comment]
This is currently not part of our plans or a priority, so we are closing the issue for now. We will reopen it if we decide to pursue this in the future.
