### ISSUE TITLE
Incorrect syntax in cache api doc

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#17811]
**Description:**
The following syntax gives a compilation error , which is in api-doc https://v1-0-0-alpha.ballerina.io/learn/api-docs/ballerina/cache/index.html

```
cache:Cache cache = new(capacity = 10, expiryTimeMillis = 60000, evictionFactor = 0.2);
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Manuri** [comment]
This is because the named params aren't made public.
