### ISSUE TITLE
Autocomplete doesn't add the final semicolon for objects

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#17813]
**Description:**
```ballerina
type Person object {

}
```
The final semicolon is not getting added in auto complete
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Can you check whether you are using the latest and use the snippet for object? This is working in latest master
