### ISSUE TITLE
incorrect snippet for typeguard 

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#17820]
**Description:**

**Steps to reproduce:**
add  variable named `a` type of `any|error`. add a type guard.
```
    if (a is error) {
        
    } else  else {
        
    }
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/17796
