### ISSUE TITLE
Cannot give relative paths to the OpenAPI file in the @openapi:ServiceInfo attribute

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17834]
Refer to the image below
![Screenshot from 2019-08-15 21-33-17](https://user-images.githubusercontent.com/6260009/63143409-c1cb2500-c00b-11e9-9678-9ab3c448914a.png)

**Comment by NipunaMarcus** [comment]
OpenAPI validator is a Compiler Plugin. In the compiler plugin context, there are no details available about source path hence it is not possible to provide relative path to the contract. As we are to refactor the compiler plugin layer these will be added as basic requirements for the API.

**Comment by NipunaMarcus** [comment]
Change sprint point to 3 as there are lots of functionality tests to be done manually regarding this change as we don't have a test framework yet for compiler plugin.
