### ISSUE TITLE
Need to Add Docs on Response Filters

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#17835]
**Description:**
The BBE section does not have proper details about ResponseFilters. Either we can add it to an existing BBE, write a new BBE about it, or add info about them in some other place in docs.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
This is documented in API docs in [1]. However, we might need to add the same either to an existing BBE or as a new BBE.

[1] https://kaviththiranga.github.io/ballerina-docs/http/objects/ResponseFilter.html
