### ISSUE TITLE
Field missing in record after call over gRPC 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17848]
**Description:**
$title. This was observed for records where field names are generated different from what are defined in the .proto (due to the field names being keywords).

**Steps to reproduce:**
Use https://github.com/MaryamZi/b7a-grpc-nats

Change `'channel` to `string_channel` at 
https://github.com/MaryamZi/b7a-grpc-nats/blob/master/src/eventstore/event_store_pb.bal#L90 and update wherever used.

Print the event at 
https://github.com/MaryamZi/b7a-grpc-nats/blob/master/src/orderservice/order_service.bal#L78 (`eventRec`) and https://github.com/MaryamZi/b7a-grpc-nats/blob/master/src/eventstore/event_store_sample_service.bal#L45 (`event`).

The `string_channel` field is not available at the event store. 

**Related issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/17764

**Comment by daneshk** [comment]
This issue is fixed in #17988
