### ISSUE TITLE
Cache not working between resources

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#17842]
**Description:**
Ballerina cache is defined as a global variable. When one service is adding to the cache try to get that value from another resource. The cache value is not available for the second resource.

**Steps to reproduce:**

**Affected Versions:**
1.0.0-Pre-Beta
**OS, DB, other environment details and versions:**
Windows,
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
I tried the following, and it's working properly for me though.
```ballerina
import ballerina/http;
import ballerina/cache;
import ballerina/io;

cache:Cache cache = new;

service hello on new http:Listener(9090) {
    resource function hi(http:Caller caller, http:Request req) {
        cache.put("FOO", "BAR");
        var x = caller->respond("Hello World!");
    }

    resource function bye(http:Caller caller, http:Request req) {
        string str = <string>cache.get("FOO");
        io:println(str);
        var x = caller->respond("Bye World!");
    }
}
```

**Comment by wggihan** [comment]
I tested with below sample and it worked as expected. Can you please share a reproducible code?

````
import ballerina/http;
import ballerina/cache;
import ballerina/io;

cache:Cache cache = new(1000 * 60 * 5);

listener http:Listener port = new(8080);
service hello on port {
    resource function hi1(http:Caller caller, http:Request request) {
        cache.put("hi1", 1);
        checkpanic caller->respond();
    }

    resource function hi2(http:Caller caller, http:Request request) {
        any? get = cache.get("hi1");
        io:println(get);
        checkpanic caller->respond();
    }
}

service hello1 on port {
    resource function hi1(http:Caller caller, http:Request request) {
        any? get = cache.get("hi1");
        io:println(get);
        checkpanic caller->respond();
    }
}
````

**Comment by vinok88** [comment]
Not working for the code at https://github.com/vinok88/bal_library_service/blob/master/src/services/services.bal
Am I missing something here?

**Comment by pubudu91** [comment]
https://github.com/vinok88/bal_library_service/blob/23f7f539d987beb4f332f0c49fee0ce54f230c93/src/services/services.bal#L22
The first param of `Cache` is the cache expiry time in milliseconds. So you've essentially set a cache expiry time of 1 second :)

**Comment by vinok88** [comment]
Oops, My bad, I thought it's cache size. Thank you.

**Comment by vinok88** [comment]
This miss understanding can be avoided by a minor doc improvement. In the doc [1], the named args are used in a different order than the API actually accepts them, when there are no names args (Even though the order is not important for named args.). This can be avoided if we can change the sample code as follows,
`cache:Cache cache = new(expiryTimeMillis = 60000, capacity = 10, evictionFactor = 0.2);`

Reopening this as a doc issue.

[1] - https://v1-0-0-alpha.ballerina.io/learn/api-docs/ballerina/cache/objects/Cache.html
