### ISSUE TITLE
string iterator function's return type should be a meaningful name

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#17843]
**Description:**
In API docs `string iterator` functions return type is listed as `$anonType$2`

It should be a meaningful name with explanation of the type 

**Affected Versions:**
api docs for 1.0.0-beta

**Comment by kaviththiranga** [comment]
@rdhananjaya As discussed offline, lets add a separate abstract object to describe the return type of iterator function instead of an inline abstract object.

https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.string/src/main/ballerina/src/lang.string/string.bal

**Comment by rdhananjaya** [comment]
@kaviththiranga @sameerajayasoma 
When the anonymous type uses more anonymous types I think extracting this abstract object become too verbose, please consider following example on array iterator.

```ballerina
// inner most anon type
public type NextValue record {|
    Type value;
|};

// extracted abstract obj
public type AbstractArrayIterator abstract object {
    // we need to extract this again?
    public function next() returns NextValue?;
};

# Returns an iterator over the members of `arr`
#
# + arr - the array
# + return - iterator object
public function iterator(Type[] arr) returns AbstractArrayIterator {
    ArrayIterator arrIterator = new(arr);
    return arrIterator;
}
```

Original type
```ballerina
public function iterator(Type[] arr) returns abstract object {
    public function next() returns record {|
        Type value;
    |}?;
    } {
    ArrayIterator arrIterator = new(arr);
    return arrIterator;
}
```

**Comment by shehan360** [comment]
This issue is fixed on the latest version.
https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.string/functions.html#iterator
