### ISSUE TITLE
Ballerina Router Tool support for IDE plugins

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#17851]
- [x] Fix VSCode ballerina home detection logic to use ``` ballerina home ``` command unless a home is configured in settings.
- [x] Do above for intellijidea as well.

**Comment by kaviththiranga** [comment]
Added VSCode support and ballerina home command with https://github.com/ballerina-platform/ballerina-lang/pull/17859

**Comment by NipunaRanasinghe** [comment]
Add IntelliJ plugin support with #18036.
