### ISSUE TITLE
Tests do not run with Data Providers

### ISSUE THREAD

**Issue by isuruuy429** [ballerina-platform/ballerina-lang#17865]
**Description:**
When the Testarina tests are written with Data Providers included, tests do not get executed. 

**Steps to reproduce:**
Run the example [1]
[1] - https://ballerina.io/learn/by-example/testerina-data-driven-tests.html

**Affected Versions:**
Priority/Highest
Severity/Blocker
Component/Testerina
BetaTesting
Type/Bug

**Comment by hevayo** [comment]
Fixed with ballerina-1.0.0-alpha3
