### ISSUE TITLE
JDBC driver installation related info missing in JDBC api doc

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#17862]
**Description:**
Subject please in doc https://v1-0-0-alpha.ballerina.io/learn/api-docs/ballerina/java.jdbc/index.html

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via [1].

[1] https://github.com/ballerina-platform/ballerina-lang/pull/17872
