### ISSUE TITLE
Remove gson dependency from JsonLogFormatter

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#17878]
**Description:**
Due to this we need to pack gson library with ballerina-log module which is dependency for runtime. So ballerina runtime jar also contain the gson jar.

This was added as a part of network logs in tools.

**Comment by kaviththiranga** [comment]
Let's remove gson dep from log module to lang-server module. We need to modify ballerina.sh classpath along with it too.

**Comment by kaviththiranga** [comment]
@warunalakshitha BTW can we know the reason for removing?

**Comment by warunalakshitha** [comment]
We need to pack gson dependency to ballerina runtime because of this issue. We need to minimise the no of external jars packed in runtime jar since that jar will be packed to each user project final jar(uber jar). That will grow up the final executable specially size of the executable is considerable when we run them in docker  environments.

**Comment by pahans** [comment]
We don't have an alternative at the moment. vscode "http network logs" will become unstable if we remove this. -1 for this change.

**Comment by sameerajayasoma** [comment]
We are packaging the Google GSON library with any Ballerina program, just for serializing a java.util.logging.LogRecord as a JSON string. Can we implement this by ourselves or copy the relevant code from the GSON library?

**Comment by hasithaa** [comment]
@warunalakshitha @nadeeshaan @kaviththiranga is this valid now, if not shall we remove this dependency?

**Comment by kaviththiranga** [comment]
+1

**Comment by nadeeshaan** [comment]
We still use gson within the LS, but I think we can remove this from other components' usages. +1

**Comment by warunalakshitha** [comment]
We have removed the JsonLogFormatter hence closing this issue.
