### ISSUE TITLE
Expose console logger for downstream modules

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#17884]
**Description:**
Current logger logs to the ballerina-internal.log. Since this is specific to the crash log, we need another logger for console logging for jballerina and StdLib modules.

**Comment by riyafa** [comment]
Please refer this [mail](https://groups.google.com/d/msg/ballerina-dev/fQSuX2k-AR8/VHb57_EKFwAJ) on this topic
