### ISSUE TITLE
What are the .keep files created when creating a ballerina projects?

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#17898]
"resources" folders in ballerina project contains a .keep file in each "resources" folder. What are they used for? Better if we can add a small description to docs explaining the use of them.

**Comment by hevayo** [comment]
We will remove .keep files copying to generated code

**Comment by gimantha** [comment]
Fixed in 1.00

**Comment by praneesha** [comment]
Checked this in the below and verified that the .keep files aren't being created now.

Ballerina 1.0.0-beta-SNAPSHOT
Language specification 2019R2
Ballerina tool 1.0.0
