### ISSUE TITLE
Closed record to map assignment not working

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17892]
Consider the following:
```ballerina
public function main() {
    Person p = {};
    map<anydata> m = p;
}

type Person record {|
    string name = "bar";
|};
```
The above issue is because of the following line. The rest field type is NoType for closed records. But isAssignable() doesn't handle NoType.
https://github.com/ballerina-platform/ballerina-lang/blob/ddc523ee406ed575e769442c6cd99a5b9d329614/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L691

**Comment by rdhananjaya** [comment]
We need to rebase #20083 to master branch
