### ISSUE TITLE
Incompatible open array to tuple (without rest field) assignment should be disallowed

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17891]
**Description:**
$title. Currently allowed as a side-effect of allowing langlib invocations on lists.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    int[] i = [1];
    [int, int] j = i;
    io:println(j[0]);
    io:println(j[1]); // panics
}
```

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT - 15th August build

**Comment by grainier** [comment]
Fixed in #18333, https://github.com/ballerina-platform/ballerina-lang/pull/18391
