### ISSUE TITLE
ballerina run dont work if unless we navigate to the directory where the bal fil exist and execute run command

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#17902]
Say I have a ballerina project called ChatRoom. Now from inside the ChatRoom directory I execute the following command.

`ballerina run src/chat_service/chat_service.bal.`

This give me the following error
`error: no ballerina source files found in module 'chat_service.bal'`

Now navigate to chat_service folder and execute the following command, it works.
`ballerina run chat_service.bal.`

**Comment by hevayo** [comment]
Fixed with ballerina-1.0.0-alpha3

**Comment by gimantha** [comment]
Seems this is not fixed in 1.1.0-beta2
