### ISSUE TITLE
Improve Secured Service with JWT BBE

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#17907]
**Description:**
$subject. Following the guide to will give result in;

```
error: ballerina-dev/server_core:0.1.0::core.bal:48:5: undefined field 'certificateAlias' in record 'ballerina/jwt:JwtValidatorConfig'
error: ballerina-dev/server_core:0.1.0::core.bal:49:5: undefined field 'trustStore' in record 'ballerina/jwt:JwtValidatorConfig'
error: ballerina-dev/server_core:0.1.0::core.bal:49:17: invalid literal for type 'other'
```

**Steps to reproduce:**
```ballerina
jwt:InboundJwtAuthProvider jwtAuthProvider = new({
    issuer: "ballerina",
    audience: "ballerina.io",
    certificateAlias: "ballerina",
    trustStore: {
        path: "${ballerina.home}/bre/security/ballerinaTruststore.p12",
        password: "ballerina"
    }
});
```
[1] https://v1-0-0-alpha.ballerina.io/learn/by-example/secured-service-with-jwt.html

**Affected Versions:**
v1-0-0-alpha

**Comment by praneesha** [comment]
Tried [1] out and it works fine now as follows.

<img width="1680" alt="Screenshot 2019-10-24 at 13 49 16" src="https://user-images.githubusercontent.com/11707273/67466694-1ff83200-f665-11e9-8128-5588a9865c0a.png">

[1] https://v1-0-0-alpha.ballerina.io/learn/by-example/secured-service-with-jwt.html
