### ISSUE TITLE
[Tooling] Add methods from referenced abstract objects?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17900]
**Description:**
When an abstract object is referenced from a non-abstract object, all the methods declared in the abstract object need to be defined. 

Currently, tooling only suggests making the referring object to also be marked as abstract, as the solution. Instead can't we offer to add the empty implementations for the methods to be implemented?

**Affected Versions:**
Ballerina 1.0.0-beta-SNAPSHOT - 15th August build
Language specification 2019R2
Ballerina tool 1.0.0

**Comment by IMS94** [comment]
On swan lake, we are now suggesting individual methods to be implemented via code actions. Within`StudentImpl` below, implement method code actions are now suggested.
```
type Student object {
    function name();
};

class StudentImpl {
    *Student;
}
```

**Comment by IMS94** [comment]
The rest will be tracked under #30749
