### ISSUE TITLE
[Spec Deviation] Future and typedesc constraints should be optional in type descriptors 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17922]
**Description:**
According to the 2019r3 spec, the constraint is optional for stream, future and typedesc type descriptors. 

```
future-type-descriptor := future [type-parameter]

stream-type-descriptor := stream [type-parameter]

typedesc-type-descriptor := typedesc [type-parameter]
```

But the implementation mandates the constraint right now.

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Comment by hasithaa** [comment]
Note: The stream type-descriptor has been changed since 1.2.
