### ISSUE TITLE
[Tooling] Invalid/inaccurate suggestions for annotation access

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17935]
**Description:**
$title.

![annot-suggestions](https://user-images.githubusercontent.com/8376983/63221734-021cd580-c1bb-11e9-878f-017f4ea8bc9c.png)

**Steps to reproduce:**
```ballerina
type Foo record {
    string kind;
};

annotation Foo foo on type;

@foo {
    kind: "record"
}
type Bar record {
    int i;
};

public function main() {
    typedesc<record{}> t = Bar;
    // or even `Bar.@`
    Foo? f = t.@
}
```
It would be better to suggest annotation tags here. 

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/15947

**Comment by MaryamZi** [comment]
Reopening to check if we could improve on the suggestion. Ideally what should be suggested is the annotation tag. 

For example, there should be a suggestion for `http:ServiceConfig` in the following scenario
![annot_access](https://user-images.githubusercontent.com/8376983/64161390-318a3e00-ce5b-11e9-871e-bc831a5b5a94.png)

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
