### ISSUE TITLE
Add Local type definitions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#17946]
**Description:**

Local type definition statement
```
local-type-defn-stmt :=
   [annots] type identifier type-descriptor ;
```

A local-type-defn-stmt binds the identifier to a type descriptor within the scope of the current block. The type-descriptor is resolved when the statement is executed.

**Comment by hasithaa** [comment]
The tracking issue for https://github.com/ballerina-platform/ballerina-spec/issues/590

**Comment by hasithaa** [comment]
Closing this issue, since it is tracked in the spec.
