### ISSUE TITLE
Restore CLI support for "Ballerina init" functionality

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#17947]
**Description:**
Since the CLI support for `ballerina init` is replaced with `ballerina new <project_name>` and `ballerina create`, AFAIK there is no way to convert exiting project to a ballerina project (except by creating the manifest and the src directory manually). So it would be better if we can preserve the previous init capability by serving it through  "ballerina new" command when user user gives something like `ballerina new .`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
We have introduced the init command in SLP8. hence, closing this issue.
