### ISSUE TITLE
[Idea-plugin] Improve usability of module view

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#17958]
**Description:**
![image](https://user-images.githubusercontent.com/1356214/63243509-65b90880-c278-11e9-8448-fae1f59012f7.png)

- This view requires some styling to identify functions and modules. 
- Navigation between functions requires close and reopening of the diagram view.    

**Affected Versions:**
- Ballerina 1.0.0 - pre Beta pack

**OS, DB, other environment details and versions:**

IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 4
Registry: ide.windowSystem.autoShowProcessPopup=true
Non-Bundled Plugins: com.github.b3er.idea.plugins.arc.browser, io.ballerina, org.antlr.intellij.plugin

**Comment by kaviththiranga** [comment]
This was kept as a workaround until we get the project overview - tree view similar to VSCode, implemented in Idea. Shall we focus on getting it implemented instead of improving this one? WDYT?

**Comment by NipunaRanasinghe** [comment]
@hasithaa As per the offline discussion we had, we will be restoring the previous diagram viewer so that there will be no indexed view and all the constructs of the file will be shown directly.
