### ISSUE TITLE
Improve CLI error message provided when trying to run ballerina files in src directory

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#17955]
**Description:**
When we try to run a ballerina file which resides directly under src directory, the error message that the CLI tool provides is as follows.

![Screenshot from 2019-08-19 11-25-19](https://user-images.githubusercontent.com/29032600/63243000-e1b25100-c276-11e9-8bbe-fcfd6d250ddc.png)

Shall we improve the error message to notify user that we don't allow src level bal files?

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This structure and the error messages are changed after introducing Ballerina Packages in SLP8. Please open an issue if there is any ambiguity in the current outputs
