### ISSUE TITLE
[Spec Deviation] Certain floating point numerical comparisons return incorrect results

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17977]
**Description:**
$title, according to the spec floating point numerical comparison should return false if either operand is NaN. Float comparisons return true for < and <= atm.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    float f1 = 1.0;
    float f2 = 0.0;

    float nan = f2/f2;

    io:println(nan);
    io:println(nan > nan);  // false
    io:println(nan >= nan); // false
    io:println(nan < nan);  // true - should be false
    io:println(nan <= nan); // true - should be false
}
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Comment by MaryamZi** [comment]
Similarly, for decimal, checks between +0.0 and -0.0 are incorrect.

```ballerina
import ballerina/io;

public function main(string... args) {
    decimal d1 = 0.0;
    decimal d2 = -0.0;

    io:println(d1 < d2);    // true - should be false
    io:println(d1 <= d2);   // false - should be true
}
```

**Comment by hasithaa** [comment]
Found duplicates #11913 #28340 #28284

**Comment by HindujaB** [comment]
Currently, the implementation of float type comparison depends on java `double` which does not consider `NaN` as a special case.  
The Type Checker implementation should be revisited considering this. 

``` ballerina
float nan = 0.0 / 0.0 ;
println(nan1 == nan1);
    println(nan1 === nan1);
    


```

**Comment by HindujaB** [comment]
Closed by mistake. Hence reopening it.

**Comment by gabilang** [comment]
Created https://github.com/ballerina-platform/ballerina-lang/issues/32111 to clarify and work on the checks for `NaN`s resulted from decimal operations.
