### ISSUE TITLE
[Spec Deviation] Reference equality checks incorrect for equal decimal values with different precision

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17984]
**Description:**
According to the 2019r3 spec
"For the decimal type, the operators differ in whether they consider the precision of the value. For example, 1.0 == 1.00 is true but 1.0 === 1.00 is false."

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main(string... args) {
    decimal d1 = 1.0;
    decimal d2 = 1.00;

    io:println(d1 == d2);   // true
    io:println(d1 === d2);  // also true, but should be false
}
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/11913

**Comment by HindujaB** [comment]
This is fixed in the ballerina slbeta5. Hence closing this issue.
