### ISSUE TITLE
No completion/suggestions for the `remote` keyword

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17989]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo client object {
    
    rem
};
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18005
