### ISSUE TITLE
[Spec Deviation] Actions nested inside other actions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#17993]
**Description:**
The 2019r3 spec says

"Actions are an intermediate syntactic category between expressions and statements. Actions are similar to expressions, in that they yield a value. However, an action cannot be nested inside an expression; **it can only occur as part of a statement or nested inside other actions**. This is because actions are shown in the sequence diagram in the graphical syntax."

**Steps to reproduce:**
The following is not allowed though.
```ballerina
type Foo client object {
    
    remote function abc() returns int {
        return 1;
    }

    remote function def(int i) returns string {
        return "str";
    }
};

public function main() {
    Foo f = new;
    string s = f->def(f->abc());
}
```

```cmd
$ ballerina run test.bal 
error: .::test.bal:14:23: action invocation as an expression not allowed here
```

**Affected Versions:**
1.0.0-beta-SNAPSHOT - 15th August build

**Comment by pubudu91** [comment]
Just realized, the above scenario cannot be allowed according to the spec right? The remote method call is defined as follows:
>remote-method-call-action := expression -> method-name ( arg-list )

And the arg-list is defined as follows:

>arg-list :=
   positional-args [, other-args]
   | [other-args]
positional-args := positional-arg (, positional-arg)*
positional-arg := expression
other-args := named-args | rest-arg
named-args := named-arg (, named-arg)*
named-arg := arg-name = expression
arg-name := identifier
rest-arg := ... expression

An action invocation cannot be an argument according to the above right?

**Comment by MaryamZi** [comment]
Yeah, according to the current spec grammar this doesn't seem valid. But should we check on the possibility of allowing this, as discussed offline?

**Comment by pubudu91** [comment]
Yeah, +1. IIRC, this issue was created because someone asked about nesting and chaining.

**Comment by pubudu91** [comment]
Since the specific scenario is not allowed as per the spec, left it out. A limited number of of actions that can be nested, was left allowed.
