### ISSUE TITLE
Transitive dependencies of the modules need to be given explicitly

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#18040]
**Description:**
All the transitive dependencies of the modules need to be given explicitly, in order to build a module.

Suspected code: https://github.com/ballerina-platform/ballerina-lang/blob/master/gradle/birTestableProject.gradle#L35
```gradle

configurations {
    birJar
    bir
    birJarCompile { transitive false }
}

...

    doLast {
        configurations.bir.each { artifact ->
            copy {
                from artifact
                into "$buildDir/bir-cache/"
            }
        }
    }
```

**Comment by azinneera** [comment]
This is related to stdlibs and so not valid for the lang repo now. Closing since this is tracked by https://github.com/ballerina-platform/ballerina-standard-library/issues/789
