### ISSUE TITLE
Absence of rest field marked with null in BTupleType

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18074]
For tuples, `null` is used to identify the absence of a tuple-rest-descriptor. Ideally, NoType should've been used to indicate this, as is done with records.

**Comment by hasithaa** [comment]
NoType is used for inferring, Ideally, we should use NIL type here.

**Comment by pubudu91** [comment]
But that’s a type itself. Adding setting the rest descriptor to nil would mean that the tuple has a nil rest descriptor

**Comment by MaryamZi** [comment]
We can now use `never`.

**Comment by MaryamZi** [comment]
> We can now use `never`.

But if we do this we wouldn't be able to differentiate between the absence of a rest descriptor and explicitly using `never` as the rest descriptor. IMO, using `null` here may be OK.
