### ISSUE TITLE
Refactor logic of setting default truststore without using ballerina home property

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#18096]
**Description:**
In setDefaultTrustStore in HttpUtil, we are using ballerina.home to get default truststore. This will break when running with java -jar since we do not have ballerina home. We need to provide proper config and read from it or read from the current directory. Else return proper error.

**Comment by Bhashinee** [comment]
Fixed from: https://github.com/ballerina-platform/ballerina-lang/pull/18277
