### ISSUE TITLE
Remove ballerina.home property from examples

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#18097]
**Description:**
In many BBEs, when setting keystore and truststore we use ballerina.home property.

ex.
examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal

 secureSocket: {
        keyStore: {
            path: "${ballerina.home}/bre/security/ballerinaKeystore.p12",
            password: "ballerina"
        }
    }

That will break when we running java -jar to test BBEs since we do not have property called ballerina.home.

**Comment by daneshk** [comment]
This issue is already fixed in #21921 and merge to the `stage` branch. Hence closing this issue
