### ISSUE TITLE
Panics generated from langlib string cause 'ballerina run' command to break

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18141]
**Description:**
```ballerina
public function main(string... args) {
    var k = "k".substring(4, 6);
}
```
 This result in a bad sad.

[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3528547/ballerina-internal.log)

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.0-alpha
**OS, DB, other environment details and versions:**
Mac
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
This fixes the same issue https://github.com/ballerina-platform/ballerina-lang/pull/18151
