### ISSUE TITLE
LS- Delimited Identifier suggestions need to be encoded back

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#18156]
**Description:**
try the following;

```ballerina
const 'T_\(  = "(" ;

function testX() {
  string x =   // <- try suggestions here. It shows the symbol "T_(".
  string y = T_(   // <- This is how it generated (Decoded symbol). But actually it should be "T_\("
}
``` 

Fix: When generating symbols, re-generate encoded symbol. 

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.0-Alpha3 on VSCode

**Comment by nadeeshaan** [comment]
Language Server, extracts the symbol name from the particular symbol and the name property of the symbol contains **T_(** . In order to reflect this to the user, symbol should contain the original value.

**Comment by nadeeshaan** [comment]
The issue #28567 is a duplicate for this. Hence closing this one.
