### ISSUE TITLE
VSCode Hover suggestions on Langlib method invocation needs to be improved with bound type

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#18150]
**Description:**
Right now it shows actual type.  e.g:
```
string[] a = [];
a.push();   // <- Suggestions say any|error, but actually it should be a string.  
```

**Comment by pubudu91** [comment]
Had an offline chat regarding this and decided to go ahead and try to implement this for at least for the straight forward cases such as the above.
