### ISSUE TITLE
[Spec Deviation] Inferred type for final variables declared with var should be the precise type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18166]
**Description:**
According to the spec:

**Local variable declaration statements**
If the typed-binding-pattern uses var, then the type of the variable is inferred from the static type of the action-or-expr; if the local-init-var-decl-stmt includes final, the precise type is used, and otherwise the broad type is used.

**Module variable declaration**
If the typed-binding-pattern uses var, then the type of the variable is inferred from the static type of expression; if the module-var-decl includes final, the precise type is used, and otherwise the broad type is used.

But the following doesn't work.

**Steps to reproduce:**
```ballerina
const ONE = 1;

public function main() {
    final var v1 = ONE;
    ONE v2 = v1; // incompatible types: expected '1', found 'int'
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-alpha3
Language specification 2019R2
Ballerina tool 1.0.0
```

**Comment by MaryamZi** [comment]
Related issues: https://github.com/ballerina-platform/ballerina-lang/issues/30585, https://github.com/ballerina-platform/ballerina-lang/issues/24489

**Comment by SandaruJayawardana** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/22959 was fixed by https://github.com/ballerina-platform/ballerina-lang/pull/34371.

**Comment by KavinduZoysa** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/36538
