### ISSUE TITLE
Need a way to specify taintedness propagation of native functions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18187]
**Description:**
As we can't analyze the taint flow through a extern function, we use a annotation based approach to indicate taintedness after that extern function is executed, that is the taintedness of return value and parameters specified by annotations are used to determine the taint flow of extern functions. 

This approach does not specify how the taint propagation happen when each arg to function is tainted and when it's not.

We need to have a mechanism where we can specify the taint table of a extern function manually.

**Comment by hasithaa** [comment]
We are removing the Current taint analysis implementation with #30981, Hence closing this issue.
