### ISSUE TITLE
Ballerina Remote debugging is not working properly

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#18196]
**Description:**
Ballerina remote debugging hasn't been working properly after rewriting the debugger implementation using DAP. Client side implementation of the ballerina plugins (IntelliJ and VScode) should be fixed in order to support the new debugger implementation.   

**Steps to reproduce:**

**Affected Versions:**
plugin versions - 1.0.0-alpha

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pahans** [comment]
Fixed this for vscode.

**Comment by NipunaRanasinghe** [comment]
Fixed for IntelliJ plugin by #19108. Hence closing.
