### ISSUE TITLE
[Spec Deviation] Not all annotation attach points are supported

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18207]
**Description:**
$title. 

Need to support
- [ ] local-type-defn-stmt - depends on https://github.com/ballerina-platform/ballerina-lang/issues/17946
- [ ] anonymous-function-expr
- [ ] local-var-decl-stmt
- [x] named-worker-decl, start-action - partial support - see https://github.com/ballerina-platform/ballerina-lang/issues/18002

Related PRs:
https://github.com/ballerina-platform/ballerina-lang/pull/15884

**Comment by MaryamZi** [comment]
The user can now attach annotations at these attach points with the new parser, but the compiler does not validate or make use of them. 

Need to at least log a "not supported yet" error until we support this.

**Comment by pubudu91** [comment]
Annotations don't seem to be working when used in a function type descriptor either. In a function type descriptor, annotations need to be supported for params and the return type descriptor.

**Comment by MaryamZi** [comment]
Also see https://github.com/ballerina-platform/ballerina-lang/issues/32809.
