### ISSUE TITLE
Can not build modules with async functions

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#18201]
**Description:**
I have written a module that contains following code line
`future<()> ftr = start initializeThrottleSubscription();`

It gives the following error when building the module with ballerina build command.

`Compiling source
	wso2/gateway:3.1.0

Creating balos
	target/balo/gateway-2019r3-any-3.1.0.balo
error: cannot find full qualified class for : wso2/gateway/wso2_gateway_3_1_0__init_ 
	at ballerina.compiler_backend_jvm:lookupFullQualifiedClassName(jvm_package_gen.bal:57)
	   ballerina.compiler_backend_jvm.TerminatorGenerator:genAsyncCallTerm(jvm_terminator_gen.bal:508)
	   ballerina.compiler_backend_jvm.TerminatorGenerator:genTerminator(jvm_terminator_gen.bal:54)
	   ballerina.compiler_backend_jvm:generateBasicBlocks(jvm_method_gen.bal:761)
	   ballerina.compiler_backend_jvm:genJMethodForBFunc(jvm_method_gen.bal:206)
	   ballerina.compiler_backend_jvm:generateMethod(jvm_method_gen.bal:35)
	   ballerina.compiler_backend_jvm:generatePackage(jvm_package_gen.bal:212)
	   ballerina.compiler_backend_jvm:generateJarBinary(main.bal:73)
	   ballerina.compiler_backend_jvm:main(main.bal:48)`

When I commented the above code line, it builds successfully.

I think this is a **blocker** . Please assign the correct labels to do this issue.

**Steps to reproduce:**

**Affected Versions:**
1.0.0-alpha3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lankavitharana** [comment]
Will provide a fix for this soon, meanwhile, if you are blocked with this, as a workaround, can you try wrapping the async invocation with another function as follows, 

```ballerina
future<()> ftr = wrapperFunc();

function wrapperFunc() returns future<()> {
future<()> ftr = start initializeThrottleSubscription();
return ftr;
}
```
above should work.
