### ISSUE TITLE
Update tool Tasks

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#18203]
**Description:**
- [x] Current distribution is not highlighted *
- [x] When listing remotes show locals and remote distribution. Separate out local with remote with a different markings. *
- [x] Need to clear ballerina home caches during distribution switch ( Here we only clear bir and jar caches ) *
- [x] Sort out how to resolve java dependency.*
- [x] Update command need to be implemented.* 
- [ ] Ballerina use will give "Permission denied" *
- [x] Updating update tool
- [ ] Keep distribution in user home
- [x] Help text are not update ( ie --remote)
- [x] Separate tool jar 
- [x] Need a progress bar for pack download. 
- [ ] Check what happen when you uninstall the ballerina tool it should clear home distribution cache.

**Comment by keizer619** [comment]
Closing this issue as revamped update tool has been delivered with 1.1.0 release
