### ISSUE TITLE
Review public API's (jBallerina runtime value classes)

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#18220]
**Description:**
Do a API review on the user facing public methods from jBallerina runtime value classes. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
Refer to the doc [1] for design details.
[1] - https://docs.google.com/document/d/1TU9jpL3_e6KCM2bW6e5d2_4KLo7Suwx07qCQONua2Pg/edit?usp=sharing
