### ISSUE TITLE
Ballerina.lock file changes after every build

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-lang#18257]
**Description:**

ballerina.lock file changes after every build with just the changes to the order of dependencies.
This is shown as a change after every build in git.

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.0-alpha3

**Comment by hemikak** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/18401
