### ISSUE TITLE
Ballerina network logs doesn't show the payload

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18263]
**Description:**
if the payload is application/octet-stream, trace logs doesn't show the payload, which is fine. But better to have something like <content-cannot-be-displayed> or something like that instead of leaving it blank as below.

![image](https://user-images.githubusercontent.com/6178058/63839649-49664b80-c99d-11e9-9dac-1bbced8e43d6.png)

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19082
