### ISSUE TITLE
Rename Ballerina network logs to have word "HTTP"

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18262]
**Description:**
At the moment, it looks like below. 

![image](https://user-images.githubusercontent.com/6178058/63839350-bcbb8d80-c99c-11e9-8cdb-197a8b7cc6a4.png)

Better to rename it to say "Ballerina HTTP trace logs" because only works for HTTP.

**Comment by pahans** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18268
