### ISSUE TITLE
Fit to screen doesn't work

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18273]
**Description:**
See below.

![aaa-1](https://user-images.githubusercontent.com/6178058/63844378-c3023780-c9a5-11e9-8685-943893f779f3.gif)

**Comment by roonyh** [comment]
This is because fit to screen actually works as fit to width. And its already fit to width. This is a duplicate of #17787. Closing since we are tracking it there.
