### ISSUE TITLE
Else block formatting get messed up

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18282]
**Description:**
![aaa-2](https://user-images.githubusercontent.com/6178058/63852985-319bc100-c9b7-11e9-9d37-929aa9aa9438.gif)

**Comment by kaviththiranga** [comment]
this needs to be fixed along with matching brace pair highlighting fix for vscode grammar

**Comment by kaviththiranga** [comment]
This will be fixed with https://github.com/ballerina-platform/ballerina-lang/issues/15959

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-grammar/pull/46
