### ISSUE TITLE
No suggestions are given when inside io:println()

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18283]
**Description:**
You have to type it and then hit escape. Hitting enter won't work either.

![aaa-6](https://user-images.githubusercontent.com/6178058/63853713-074b0300-c9b9-11e9-94e3-0520f9eed30e.gif)

**Comment by nadeeshaan** [comment]
This is because the cursor is still under the snippet place holder. You can get completion for the same context after pressing esc and exiting from placeholder. Hence closing the issue
