### ISSUE TITLE
Support method invocation on braced expressions

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#18298]
**Description:**

Method invocation on braced expression is currently not allowed by the grammar.

e.g.-
```ballerina
int i = 5;
string s = (i + 1).toString();
```

If this is supported, developer experience can be improved.

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/17797

**Comment by grainier** [comment]
Tracking in #20238
