### ISSUE TITLE
VSCode does not suggest returns 

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#18306]
**Description:**
VSCode does not suggest the `returns` part of the function signature and when trying to return an error it tries to create an error object.

**Steps to reproduce:**
![error-return](https://user-images.githubusercontent.com/8238078/63917036-4891f000-ca57-11e9-85db-8a1b6dc56285.gif)

**Affected Versions:**
Ballerina 1.0.0 alpha 3

**Comment by nadeeshaan** [comment]
Fixed with https://github.com/nadeeshaan/ballerina/commit/2105ea96bcbe4f85ff976069b6b378f5b76af54b hence closing the issue
