### ISSUE TITLE
Heap dump is not saved 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18359]
**Description:**
I get the below error.

java.lang.OutOfMemoryError: Java heap space
Dumping heap to /usr/lib/ballerina/ballerina-1.0.0-alpha3/distributions/jballerina-1.0.0-alpha3/heap-dump.hprof ...
Unable to create /usr/lib/ballerina/ballerina-1.0.0-alpha3/distributions/jballerina-1.0.0-alpha3/heap-dump.hprof: Permission denied

**Comment by mohanvive** [comment]
Shall we close this issue? Anything more to explore on this?

**Comment by pramodya1994** [comment]
Since the above PR only handling `bal run <jar-file>` case, reopening this issue to handle the following cases as well:
- `bal run`
- `bal build`

In both cases, the dump file should be added to the current directory.

**Comment by pramodya1994** [comment]
Can use the following ballerina program to reproduce this.
https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/jvm/runtime-oom-error.bal
