### ISSUE TITLE
[Tooling] Suggesting object __init function when invoking outside of self

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#18369]
**Description:**
With https://github.com/ballerina-platform/ballerina-lang/pull/18317 

Object '__init' method invocation is only allowed within the type descriptor

While the following is valid
<img width="705" alt="Screen Shot 2019-08-30 at 3 01 15 PM" src="https://user-images.githubusercontent.com/24229626/64010470-79495680-cb37-11e9-9ad6-a79ab6a373b2.png">

this is not
<img width="656" alt="Screen Shot 2019-08-30 at 2 59 26 PM" src="https://user-images.githubusercontent.com/24229626/64010512-8f571700-cb37-11e9-822c-d0cf04614209.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Area/Tooling

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
