### ISSUE TITLE
TypeParam Analyzer Fails with NPE with streaming quires. 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#18363]
**Description:**
StreamsQuerySemanticAnalyzer doesn't set the type to invocation node, which leads to NPE. This is checkInvocationExpr.

```
        if (typeSymbol == aggregatorTypeSymbol || typeSymbol == windowTypeSymbol) {
            invocationExpr.typeChecked = true;
            invocationExpr.argExprs.forEach(arg -> analyzeNode(arg, env));
            invocationExpr.requiredArgs = invocationExpr.argExprs;
            return true;
        }
```
This is fixed temporally, by adding a null check. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
We have reduced priority since old stream implementation has been removed with #20663

**Comment by hasithaa** [comment]
@gimantha Can you verify whether we have the same problem with new Stream implementation?

**Comment by gimantha** [comment]
> @gimantha Can you verify whether we have the same problem with new Stream implementation?

@hasithaa null check is removed from the TypeParamAnalyzer in new stream implementation and this situation will not arise in new implementation. We can close this issue
