### ISSUE TITLE
Ballerina logs printed in the internal log file

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#18378]
**Description:**
When there is a runtime error happens like null casting issue the ballerina stack trace[1] is printed on the ballerina internal log file, instead of the standard error.  

[1] - `[2019-08-30 14:50:08,751] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
error: {ballerina}TypeCastError message=incompatible types: '()' cannot be cast to 'string'
	at wso2.gateway:sendErrorResponseFromInvocationContext(utils/utils.bal:282)
	   wso2.gateway.PreAuthnFilter:filterResponse(filters/pre_authn_filter.bal:38)
	   ballerina.http.Caller:respond(http_connection.bal:45)
	   wso2.gateway:sendErrorResponse(utils/utils.bal:273)
	   wso2.gateway:doAuthnFilterRequest(filters/pre_authn_filter.bal:97)
	   wso2.gateway.PreAuthnFilter:filterRequest(filters/pre_authn_filter.bal:33)`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Is it possible to share a sample or a link to the code?

Tried a simple scenario with alpha-3 but it does not write to the internal log.

```ballerina
public function main() {
    any a = ();
    string s = <string> a;
}
```

```cmd
$ ballerina run abc.bal error: {ballerina}TypeCastError message=incompatible types: '()' cannot be cast to 'string'
        at abc:main(abc.bal:3)
```

**Comment by Rajith90** [comment]
`# Default error response sender with json error response
public function sendErrorResponseFromInvocationContext(http:Response response) {
    runtime: InvocationContext context = runtime:getInvocationContext();
    string errorDescription = <string>context.attributes[ERROR_DESCRIPTION];
    string errorMessage = <string>context.attributes[ERROR_MESSAGE];
    int errorCode = <int>context.attributes[ERROR_CODE];
    response.statusCode = <int>context.attributes[HTTP_STATUS_CODE];
    response.setContentType(APPLICATION_JSON);
    json payload = { fault: {
        code: errorCode,
        message: errorMessage,
        description: errorDescription
    } };
    response.setJsonPayload(payload);
}`

The error happens when trying to cast this value **context.attributes[ERROR_DESCRIPTION]** to string. If the value is nil then the error happens

**Comment by vinok88** [comment]
This should have been fixed in https://github.com/ballerina-platform/ballerina-lang/pull/18323. Please check in 1.0-beta pack. Feel free to reopen if the issue persists.
