### ISSUE TITLE
It takes considerable amount of time to generate balos while project is being built

### ISSUE THREAD

**Issue by isuruuy429** [ballerina-platform/ballerina-lang#18371]
**Description:**
When a project is being built, it takes approximately 20+ seconds to create a balo. This affects the total build time when it comes to build set of projects. 

**Steps to reproduce:**
1. Build the following project. 
https://github.com/wso2/ballerina-integrator/tree/master/docs/learn/integration-tutorials/exposing-several-services-as-a-single-service
`ballerina build tutorial`

**Affected Versions:**
ballerina-1.0.0-alpha3

**Suggested Labels (optional):**
priority/normal
severity/minor

**Comment by Ibaqu** [comment]
Closing since we will be handling it in the following issue : https://github.com/ballerina-platform/ballerina-lang/issues/30084
