### ISSUE TITLE
gRPC client generation is broken on the lang branch

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18397]
**Description:**
$title. With the latest lang changes, a public function returning a non-public type results in an error. 

e.g.,
```
ERROR: .::07_unary_nonblocking_client.bal:148:5:: attempt to expose non-public symbol 'Request'
```

The generated gRPC clients seem to be having public remote methods, but the types returned seem to have module level visibility. Client generation needs to be updated to mark such types public.

Several tests in the StubGeneratorTestCase are commented out on the lang branch with ff78e96c147cb8ce01c7d39136f2a167b925f323 due to the same, and these changes are expected to be merged to master with https://github.com/ballerina-platform/ballerina-lang/pull/18391.

**Comment by daneshk** [comment]
Fixed in 81c0aa2d703193a28f686f35a617d8f89c5c374b
