### ISSUE TITLE
[StdLib] Migrate thrown java exceptions to ErrorValue

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#18411]
**Description:**
StdLibs should stick to a consistent error throwing and log routing standard. There are multiple locations where just the java exception is thrown upon a panic situation. This should be refactored as it leads to a Bad Sad moment to the user while logging the stack trace on the ballerina-internal-log. However the behavior should get properly verified.

1. Return ErrorValue - Single line of error gets printed on the console
2. Panic ErrorValue - Error and the stack trace get printed on the console
3. Panic Java exception - Bad Sad printed on the console, log exception on the internal log

**Comment by chamil321** [comment]
Fixed HTTP related exceptions in https://github.com/ballerina-platform/ballerina-lang/pull/18647

**Comment by wggihan** [comment]
We migrated almost all standard library modules.
