### ISSUE TITLE
Improve type inferring of union type including 2 or more object types

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#18414]
**Description:**
As per https://github.com/ballerina-platform/ballerina-lang/pull/18239/files#diff-1f0acc81bd72ee2f8368b0a25cd59e9cR1679 only unions with a single object type will be inferred properly when using `new()`. This is so as to support nillable object types. Need to support having 2 or more assignable object types in a union.

**Related Issues (optional):**
#18239

**Comment by MaryamZi** [comment]
Sub-task of https://github.com/ballerina-platform/ballerina-lang/issues/23595.

**Comment by gimantha** [comment]
Will take this later, for the moment we will be closing this issue
