### ISSUE TITLE
Stepping over async call lines is broken 

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#18427]
This is working if we set a debug point to next line. But breaks when stepping over.

**Comment by kaviththiranga** [comment]
BTW, As per the discussion, we have two options to handle it

1. fix it from jballerina side so normal JDI step over works fine for those lines (Accoring to Manu and Rajith this is not straight forward) 
2. Add a dynamic break point from debug client implicitly when stepping over those lines (this is hacky)

**Comment by NipunaRanasinghe** [comment]
Closing since this is fixed with #19289 and #25775
