### ISSUE TITLE
Ballerina staging central shows incorrect latest version for modules 

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#18420]
**Description:**
The version shown as the latest version in modules and module templates is not the latest version (the oldest version is shown).
https://staging-central.ballerina.io/irushi/module0

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/18174

**Comment by hevayo** [comment]
Fixed with 1.0 release
