### ISSUE TITLE
Improve handling missing semicolon in LS

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#18445]
**Description:**
Consider following program. 

```
import ballerina/io;

type A record {|
    string name;
    int age;
|}; 

public function main() {
    string name = "name";
    A a = {}   // <- ; Missing here
    io:println(a);
}
```

When missing semicolon, it will match to `expr token expr` rule. There are lot of valid tokens here. `; + - / * ` and more. This leads to broke LS suggestions. 

I am just wondering whether we can prioritize the `;` here because mismatched input error happens between two lines. From parser, we can know we are in a statement context.

**Comment by nadeeshaan** [comment]
This issue has been resolved with migrating to the new parser and the new auto-completion engine. Hence closing the issue
