### ISSUE TITLE
Frames array size in jBallerina should be validated

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#18444]
**Description:**
ATM, this size is 100. This should be properly handled.

**Steps to reproduce:**

**Affected Versions:**
1.0-beta
**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/12807

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35034.
