### ISSUE TITLE
Invalid JAVA_HOME path picked when running ballerina command

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18457]
The JAVA_HOME the tool is picking up seems to be wrong. I have set JAVA_HOME to the JDK I'm using. But it picks the following invalid path:
```
/usr/lib/ballerina/ballerina-1.0.0-beta/bre/lib/jdk8u202-b08-jre
```
The actual path should've been 
```
/usr/lib/ballerina/ballerina-1.0.0-beta/dependencies/jdk8u202-b08-jre/
```

Tested on: Ubuntu 16.04

**Comment by keizer619** [comment]
Fix is available in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/18482/files
