### ISSUE TITLE
Update command fails with insufficient privillages

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18455]
**Description:**

```
➜  ~ ballerina dist update
Current user does not have write permissions to /Library/Ballerina/ballerina-1.0.0-beta/distributions directory
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Error message has been improved in 1.1.0 hence closing the issue. Please fell free to open if you observe the issue again.
