### ISSUE TITLE
[CLI] Usage of double quotes in unknown command message

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#18456]
**Description:**

$title
It would be better if we use single quotes here
<img width="705" alt="Screen Shot 2019-09-03 at 1 58 18 PM" src="https://user-images.githubusercontent.com/24229626/64157305-1cf67780-ce54-11e9-8ba5-b5258d4d95b9.png">

**Steps to reproduce:**

`➜ ballerina abc`

**Affected Versions:**
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Duplicate #18809
