### ISSUE TITLE
Misleading update notification

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18454]
**Description:**

Following is the output of ballerina -v command soon after new installation (beta)

```
➜  ~ ballerina -v


New Ballerina 1.0.0-beta2 version is available
Please use "ballerina dist update" command to update

Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
➜  ~
➜  ~ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
➜  ~ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
```

IMO this behavior (the notification message) is bit misleading as it says only in the first command. 

Shall we change the message to make it more self explanatory.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
We will only add the update notification to build and version commands. In the version command the latest available will be displayed all the time.

**Comment by keizer619** [comment]
We have decided to keep this message only for build command. 
Fix is available in following PR
Fix is available in the following PR
https://github.com/ballerina-platform/ballerina-lang/pull/18704
