### ISSUE TITLE
`ballerina dist xxx` command help texts are inconsistent

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18477]
**Description:**
$title.

"$ ballerina dist update -h
NAME
    Ballerina update - Update to latest distribution version

SYNOPSIS
    ballerina update

DESCRIPTION
     Ballerina update command will update to provided version.

OPTIONS
     Ballerina update command takes no options.

EXAMPLES
     Update current distribution to latest.
     $ ballerina update"

"$ ballerina dist use -h
NAME
    Ballerina **dist** use - Use a given distribution version

SYNOPSIS
    ballerina **dist** use <distribution-version>

DESCRIPTION
     Pull and use a given Ballerina version from project repository.

OPTIONS
     Ballerina dist use command takes no options.

EXAMPLES
     Install Ballerina 1.0.0 version
     $ ballerina dist use jballerina-1.0.0

     This use jballerina-1.0.0 distribution"

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
```

**Comment by keizer619** [comment]
These has been improved in following commit
https://github.com/ballerina-platform/ballerina-lang/commit/25738670ed8bdc0d42e96a21f190ba10fc54cf22
