### ISSUE TITLE
[VSCODE] Private fields are suggested

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#18483]
**Description:**

$title
<img width="629" alt="Screen Shot 2019-09-03 at 5 05 40 PM" src="https://user-images.githubusercontent.com/24229626/64170248-4ff93500-ce6d-11e9-81ca-f462efce5dbf.png">

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by irshadnilam** [comment]
Private functions are also suggested
<img width="637" alt="Screen Shot 2019-09-03 at 5 20 52 PM" src="https://user-images.githubusercontent.com/24229626/64171024-3527c000-ce6f-11e9-8c0c-3720dc3ea742.png">

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
