### ISSUE TITLE
Escaping - is not working for identifiers.

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#18480]
**Description:**
When `-` is used in an identifier literal and escaped using `'\` escape combination, there is a diagnostic error saying `Identifier literal only supports alphanumeric characters` 

<img width="924" alt="Screen Shot 2019-09-03 at 15 20 47" src="https://user-images.githubusercontent.com/11191791/64169585-b9784400-ce6b-11e9-8da3-b4fdd5681170.png">

**Steps to reproduce:**
Write an identifier containing the character `-`. Escape it with the characters `'\`.

**Affected Versions:**
version 1.0.0 alpha3

**OS, DB, other environment details and versions:**
MacOs Mojave
VSCode

**Comment by grainier** [comment]
Duplicate: https://github.com/ballerina-platform/ballerina-lang/issues/18720
