### ISSUE TITLE
Optional fields are suggested with field access when attempted on a record union

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18494]
**Description:**
$title. 

This happens only for a union - for a single record type only the required fields are suggested.

![optional_field_sugg](https://user-images.githubusercontent.com/8376983/64183057-de2de500-ce86-11e9-8891-7573bdec3a06.png)

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Foo record {
    string s;
    int i?;
};

type Bar record {
    string s;
    int i?;
};

public function main() {
    Foo f = { s: "hello world", i: 1 };
    Foo|Bar fb = f;

    io:println(fb.);
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
```

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
