### ISSUE TITLE
Incompatible object types suggested as object type references

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18491]
**Description:**
$title.

The following constraints apply for object type references:
1. the referenced object has to be an abstract object - currently suggests non-abstract objects
2. when referencing across modules
   - the referenced object has to be public - currently suggest those that are not public
   - the referenced object's fields and methods should be public

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
```

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
