### ISSUE TITLE
Should the main function snippet not have parameters?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18497]
**Description:**
$title. The current snippet is as follows:

```ballerina
public function main(string... args) {
    
}
```

IMO, the `args` parameter is not used most of the time and is often an unused variable.

Should we change this to
```ballerina
public function main() {
    
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-beta
Language specification 2019R3
Ballerina tool 1.0.0
```

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
