### ISSUE TITLE
Old swagger-parser-v3 version is in use

### ISSUE THREAD

**Issue by praminda** [ballerina-platform/ballerina-lang#18509]
**Description:**

openapi tools are is still using old unstable version of swagger-parser-v3 
`io.swagger.parser.v3:swagger-parser:2.0.0-rc3`.

Should be possible to migrate to latest version. `2.0.14`

**Steps to reproduce:**
N/A

**Affected Versions:**
1.0.0-alpha3

**OS, DB, other environment details and versions:**
N/A

**Comment by DimalChandrasiri** [comment]
Closing issue since fixed with #18617
