### ISSUE TITLE
Bad sad error when using interop

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#18526]
**Description:**
This exception throws when running following code.
```
Type 'java/lang/String' (current frame, stack[0]) is not assignable to 'org/ballerinalang/jvm/values/HandleValue'
```
Code:
```ballerina
import ballerinax/java;

public function main(string... args) {
    string[] parts = split("hello world", " ");
    io:println(parts);
}

public function split(string receiver, string delimeter) returns string[] {
    handle res = splitExternal(receiver, delimeter);
    return [];
}

function splitExternal(string receiver, string delimeter) returns handle = @java:Method {
    name: "split",
    class: "java.lang.String",
    paramTypes: ["java.lang.String"]
} external;
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
The issue was `splitExternal(string receiver, string delimeter)` having a wring signature. it should be: `splitExternal(handle receiver, handle delimeter)`.

This should be validated by the compiler.

**Comment by SupunS** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19068
