### ISSUE TITLE
Java interop annotation suggestions are not working 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#18538]
Here is a sample code:
```ballerina
function name() = @java:Method {
    name: "dfadfa",
    class: "a.b.Foo"
} external;
```

Please note the formatting as well.

**Comment by nadeeshaan** [comment]
Language Server Completion support has been added

**Comment by NipunaMarcus** [comment]
@roonyh  can we check syntax highlighting for this scenario? it doesn't highlight annotation as it does in other places.

**Comment by roonyh** [comment]
@NipunaMarcus Yeah, we now highlight annotations everywhere properly. https://github.com/ballerina-platform/ballerina-grammar/pull/46

<img width="274" alt="image" src="https://user-images.githubusercontent.com/3872221/64483903-41719b80-d228-11e9-83e1-6d5f8c43714b.png">

**Comment by nadeeshaan** [comment]
closing the issue based on above comments
