### ISSUE TITLE
Revisit error match pattern un-reachability 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18553]
**Description:**
With introduction of direct/in-direct error match patterns we need to revisit error match pattern reachability check.

Also related to https://github.com/ballerina-platform/ballerina-lang/issues/18511
**Steps to reproduce:**

**Affected Versions:**
1.0-beta
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@KavinduZoysa, @rdhananjaya, we can close this now, right?

**Comment by MaryamZi** [comment]
Closing this since we also have https://github.com/ballerina-platform/ballerina-lang/issues/31126 as a generic check.
