### ISSUE TITLE
Testering output is having null

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18560]
**Description:**
Check the below sample : https://github.com/ballerina-platform/ballerina-lang/blob/master/examples/testerina-assertions/testerina_assertions.bal

There are two issues with the output

1. File name is printed as null
2. Status of each test is not printed
   i.e. ` [pass] testAssertFail` etc

Expected Output:
```
Compiling tests
    testerina_assertions.bal

Running tests
    testerina_assertions.bal
    [pass] testAssertFail
    [pass] testAssertFalse
    [pass] testAssertTrue
    [pass] testAssertNotEqualsJson
    [pass] testAssertNotEqualsString
    [pass] testAssertFloatArrayEquals
    [pass] testAssertIntArrayEquals
    [pass] testAssertStringArrayEquals
    [pass] testAssertBooleanEquals
    [pass] testAssertJsonEquals
    [pass] testAssertStringEquals
    [pass] testAssertFloatEquals
    [pass] testAssertIntEquals

    13 passing
    0 failing
    0 skipped
```

Current Output:

```
Compiling source
        test2.bal

Running tests
    null
        13 passing
        0 failing
        0 skipped
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Issue is resolved with #20874
