### ISSUE TITLE
Incorrect formatting of less than and greater than characters in api docs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18651]
**Description:**
$subject in api docs

Refer [1] for example

`->` is displayed as `-&gt`
`<string>` is displayed as `&lt;string&gt;`

[1] https://v1-0-0-alpha.ballerina.io/learn/api-docs/ballerina/java.jdbc/index.html#clients

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
Fixed with 97feed9b3f2c9f4980b03500d9ae826b8a2f3abd

**Comment by kaviththiranga** [comment]
Will be merged with https://github.com/ballerina-platform/ballerina-lang/pull/18578/
