### ISSUE TITLE
Stack and queue method invocations on fixed length arrays/tuples not compile time checked

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18662]
Consider the following code snippets:
```ballerina
function testPushInTuples() returns [int, string, float...] {
    [int, string] tup = [10, "Ballerina"];
    tup.push(12);
    return tup;
}

function testPushInFixedLengthArrays() returns int[] {
    int[5] sealedArray = [2, 15, 200, 1500, 5000];
    sealedArray.push(10);
    return sealedArray;
}
```
Both of the above cases should result in compile errors as per the spec.
https://github.com/ballerina-platform/ballerina-spec/blob/6e405f7fce4a4d5ab250c53f292cc42daacd4c5e/lang/lib/array.bal#L150
But at the moment, these compile fine and crashes during run time.

**Comment by rdhananjaya** [comment]
Also refer https://github.com/ballerina-platform/ballerina-spec/issues/345#issuecomment-534938475
