### ISSUE TITLE
Improve worker nodes structure so that we can performe flow related analysis in compiler 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18680]
**Description:**
As we currently rewrite workers using lambda and async invocation at package builder level, with this we loose information that are needed for semantic validations of worker usage.

We have used some ad-hock methods to partially pass around the information that we loose in the rewrite process. Example (https://github.com/ballerina-platform/ballerina-lang/pull/18498)

We need to improve the worker node structure so that we don't loose those information, either we need to alter node structure or maybe use some auxiliary bag of information to preserve the program structure.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
