### ISSUE TITLE
Ballerina maps

### ISSUE THREAD

**Issue by 7slcode7** [ballerina-platform/ballerina-lang#18683]
**Cannot define maps by giving types for value and keys**

map<string,string>  a;  
**Error says invalid token  ,   **

**Affected Versions: Ballerina 0.991.0**

**Comment by pubudu91** [comment]
In Ballerina, the key of a map entry is always a string. So the constraint you specify is the constraint of the value of the entry. The correct way to define the above is,
```ballerina
map<string> a;
```

**Comment by 7slcode7** [comment]
Thank you for the clarification.
