### ISSUE TITLE
Allow resources to return only error or nil at language level

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#18698]
**Description:**
The resources are supposed to return only `error?`, but this is not enforced by the language. Other libraries need to have a compile time validation to ensure that this is the case. For example [AbstractTransportCompilerPlugin](https://github.com/ballerina-platform/ballerina-lang/blob/927433b2af4ee3cb5cb32ed988db86cdfe7275d5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/AbstractTransportCompilerPlugin.java#L37) has been written explicitly to make this validation in http module. Similar code would be required in other modules as well for this validation. 

This is too much duplication of code. It would be far better if this validation is made at the top core level.

**Steps to reproduce:**
Create a resource in a module that returns anything other than `error?` and it would be allowed if there are no compiler plugin validation for that.

**Affected Versions:**
Ballerina 1.0.0-beta

**OS, DB, other environment details and versions:**

**Comment by MaryamZi** [comment]
This was enforced at language level with https://github.com/ballerina-platform/ballerina-lang/pull/18213 and should be available in 1.0.0-beta too. https://github.com/ballerina-platform/ballerina-lang/issues/18259 was created to track removing the std lib specific validations where it is a direct duplicate.

Can you share the code for which this is not enforced?

**Comment by riyafa** [comment]
Okay. Noticed compiler plugin validations in several places and created the issue. Closing as it is mentioned in #18259
