### ISSUE TITLE
Tables with defaulable record fields are not working properly

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#18712]
**Description:**

It seems record default-able fields are not properly working with in-memory tables

```
import ballerina/io;

type Person record {
    int id;
    int age = -1;
    float salary;
    string name;
    boolean married;
    float amount = 55.0;
};

public function main() {
    table<Person> personTable = table{
        { key id, age, salary, name, married, amount },
        [ { 1, 30,  300.5, "Mary", true },
          { 2, 20,  300.5, "John", true }
        ]
    };

    io:println(personTable);
}
```
Current Output: Empty

Expected Output: 
```
id=1 age=30 salary=300.5 name=Mary married=true amount=55.0 id=2 age=20 salary=300.5 name=John married=true amount=55.0
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19440
