### ISSUE TITLE
The builtin service type symbol is incorrectly defined

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#18717]
**Description:**
$title 

https://github.com/ballerina-platform/ballerina-lang/blob/068d219290b2661f03c325cbe29815860ebd8359/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java#L202

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This will be changed with the new service type proposal in SL. Hence this change is no longer needed.
