### ISSUE TITLE
QuotedIdentifier supports only alphanumeric chars and .

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#18720]
**Description:**
Related PR - https://github.com/ballerina-platform/ballerina-lang/pull/18246. 

JVM Code generations fail for certain chars. Tooling requires additional support from the compiler side in order to render the original identifier. Due to these limitations, it was decided to support only alphanumeric chars and `.` for JBallerina 1.0.0 release.

**Comment by HindujaB** [comment]
Regarding this task, various character sequences were tested as quoted identifiers on standalone ballerina programs with the new parser. These combinations were created according to the language specifications. The results show that all the expected char sequences are supported by the current compiler except the unicode type characters.  

Please find the results here [1].

[1] https://docs.google.com/spreadsheets/d/19Kpl8CMLKfYITN6K5yL7SazndeuMbpdNQOGU_dK8AJI/edit?usp=sharing
