### ISSUE TITLE
Reenable failing jballerina unit tests

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#18746]
**Description:**
- [x] Fix ModuleExecutionFlowTests https://github.com/ballerina-platform/ballerina-lang/pull/18722/commits/f8b90d7d47dd5913c41fd2e06cf6432bc6c1e19b
- [x] Fix intermittent test failures in WorkerFailTest https://github.com/ballerina-platform/ballerina-lang/pull/18722/commits/1e8140cc655ca8f364bc0d715d48dafed1825348

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
These tests are enebaled.
