### ISSUE TITLE
Ballerina VSCode plugin usability issue in generated service annotation fields

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#18759]
**Description:**
The fields generated by the VSCode plugin for the Kafka service annotation generates a comment for every field requiring a union type, which IMO is irritating for the user. Since it is a comment, I either have to delete it or add a new line at the end of the comment. 

**Steps to reproduce:**
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/39673615/64470864-6a7e2780-d167-11e9-9a13-e0ed997990be.gif)

**Affected Versions:**
Ballerina 1.0.0-beta
Ballerina-1.0.0-rc1-SNAPSHOT

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
