### ISSUE TITLE
Wrong position is printed when undefined object field is detected

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18758]
**Description:**
```ballerina
type Ob object {
    string a;
    int b;
...
}

function f() {
    Ob o = new();
    o.z();
}
```
When undefined field 'z' is referred, error is shown in position of the method receiver 'o'.

![Screen Shot 2019-09-07 at 12 02 54 PM](https://user-images.githubusercontent.com/1496990/64470873-7e298e00-d167-11e9-9b32-54fef30ce9c6.png)

In the above screenshot only first letter is squiggly lined for the same error.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/issues/18758
