### ISSUE TITLE
Weird behavior with Mac installer continue and go back

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#18767]
**Description:**
Following things happened in macOS installer,

1. In destination select window, installation type was shown (blue strip with text install for all users)
2. In the Installation Type window, there was the change destination button and when clicking it, it returned back to Destination select window with blue strip.
3. If we continue again to Installation Type window, that button was gone.
4. Now cannot go to Installation Type window, by clicking continue go back buttons.

**Steps to reproduce:**

**Affected Versions:**
1.0-beta
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Not observed in the latest installation. Hence, closing the issue.
