### ISSUE TITLE
Suggests a wrong set of properties in ServiceConfig

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#18768]
**Description:**
- Versioning 
![serviceVersioningError](https://user-images.githubusercontent.com/11239305/64471349-55f15d80-d16e-11e9-9f82-76f6759a7333.png)

- Auth
![authError](https://user-images.githubusercontent.com/11239305/64471360-76b9b300-d16e-11e9-8281-3d63d9a58570.png)

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
