### ISSUE TITLE
Auto complete does not work for the some of the properties in HTTP client

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-lang#18760]
Auth, trustStore, keyStore

![image](https://user-images.githubusercontent.com/12377918/64470914-2fc8bf00-d168-11e9-8d60-c5472f7c8ac6.png)

![image](https://user-images.githubusercontent.com/12377918/64471191-eda17c80-d16b-11e9-9f63-1586e5a983cd.png)

**Comment by nadeeshaan** [comment]
For the second case, type of the record literal of keystore value is Semantic error type, therefore cannot get the required fields for the autocompletion items calculation. But, following similar case works without any issue

crypto:KeyStore ks = {
        <cursor>
};

**Comment by grainier** [comment]
If we try to write `trustStore: {},` it will show an error saying `invalid literal for type 'ballerina/crypto:TrustStore?'`. From the compilers pespective, I think this is the correct behaviour. Then, one can ask why `cache: {},` doesn't show any errors. The reason for that is, if you look closely at both the records, `CacheConfig` is a closed record with default values for its fields. So `{}` is actually a valid assignment for that. However, `TrustStore` doesn't have default values for its fields, so we cannot assign `{}` to a `TrustStore`, and it's mandatory to have all the fields initialized.

```ballerina
public type TrustStore record {|
    string path;
    string password;
|};

public type CacheConfig record {|
    boolean enabled = true;
    boolean isShared = false;
    int expiryTimeInMillis = 86400;
    int capacity = 8388608; // 8MB
    float evictionFactor = 0.2;
    CachingPolicy policy = CACHE_CONTROL_AND_VALIDATORS;
|};
```

@nadeeshaan Therefore, I think we have to come up with a different mechanism to get fields of a record regardless of whether it has default values or not, and fix this from tooling end. WDYT?

**Comment by hasithaa** [comment]
Resolving since the fix is merged to patch release branch.
