### ISSUE TITLE
Suggests a wrong set of properties in ResourceConfig

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#18776]
**Description:**
-auth
![resourceAuth](https://user-images.githubusercontent.com/11239305/64471418-28f17a80-d16f-11e9-932f-60c93bf8689e.png)

-cors
![resourceCors](https://user-images.githubusercontent.com/11239305/64471994-ad46fc00-d175-11e9-9925-396fc5b10779.png)

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
