### ISSUE TITLE
Completing a record literal with the semi colon based on the context

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18783]
Consider the following case, where I'm defining a record type variable and trying to create a record.
![Peek 2019-09-07 14-19](https://user-images.githubusercontent.com/6260009/64472371-e6359f80-d17a-11e9-9a5d-cfa6d707e726.gif)

As it can be seen, since the code is broken without the semi colon at the end of the literal, the suggestions are not working. I have to add the semi colon manually and come back to get the suggestions to work. Instead of that, if the plugin can generate the literal with the semi colon (if it's a place where the semi colon is required, like in the above case), the user can simply go about filling in the details of the record with the help of the suggestions.

**Comment by nadeeshaan** [comment]
This issue was resolved after migrating to the new parser and revamping of the completion engine. Hence closing this issue.
