### ISSUE TITLE
Wrong suggestions + add all attributes completion not working for a nested record

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18788]
Refer to the following gif
![Peek 2019-09-07 14-29](https://user-images.githubusercontent.com/6260009/64472438-06199300-d17c-11e9-8df1-a5be9a056552.gif)

When I try to use the "add all attributes" completion from within the nested record literal, it completes the record with the fields of the enclosing record type.

**Comment by pubudu91** [comment]
Code sample:
```ballerina
public function main() {
    Person p = {name: "Pubudu", age: 28, address: {}};
}

type Address record {|
    string street = "";
    string city = "";
    string country = "";
    record {
        int countryCode = 0;
        int phoneNo = 0;
    } phone = {

    };
|};

type Person record {
    string name = "John Doe";
    int age = 0;
    Address address = {};
};
```

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master. Hence closing the issue
