### ISSUE TITLE
Lines with wait keyword appears outside the function box in Diagram view

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#18787]
**Description:**
Please refer to the attached image.
<img width="1209" alt="Screen Shot 2019-09-07 at 2 30 05 PM" src="https://user-images.githubusercontent.com/1875994/64472447-32351400-d17c-11e9-8865-6bb2e29df712.png">

**Steps to reproduce:**

**Affected Versions:**
1.0-rc1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
