### ISSUE TITLE
Add a completion for closed record definitions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18781]
Currently, in type definition completions, you only get open records. It would be good if we can have an option for completing a closed record definition as well. 
![Screenshot from 2019-09-07 14-07-13](https://user-images.githubusercontent.com/6260009/64472243-edf44480-d178-11e9-9ed3-4af26388011c.png)

Maybe we can have the record completions like the following:
```ballerina
type <RecordName> record { }
type <RecordName> record {| |}
```

**Comment by nadeeshaan** [comment]
Now we have added a new snippet for the closed records with this fix, hence closing the issue
