### ISSUE TITLE
Using "add all attributes" completion for a default value of a record param breaks the formatting

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18796]
As it can be seen below, it breaks the record literal into multiple lines, messing up the formatting of the function
![Peek 2019-09-07 15-00](https://user-images.githubusercontent.com/6260009/64472861-411ec500-d182-11e9-9af2-76957f5c5a23.gif)

**Comment by nadeeshaan** [comment]
Currently, we do not support on-type formatting in the language server, and this will be a future improvement

**Comment by IMS94** [comment]
This is handled properly on swan lake's implementation of filling record fields. Hence closing.
