### ISSUE TITLE
No completion for the `function` keyword within a function

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18792]
**Description:**
$title.

This is a valid scenario with anonymous function expressions.

```ballerina
public function foo() {
    function() bar = function () {
        
    };
}
```

![anon_func_sugg](https://user-images.githubusercontent.com/8376983/64472587-585bb380-d17e-11e9-981b-015926ef959a.png)

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-rc1-SNAPSHOT
Language specification 2019R3
Ballerina tool 1.0.0
```

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged with https://github.com/nadeeshaan/ballerina/commit/8c99c8e61bce16b20505c67e8516280acb25012b
