### ISSUE TITLE
Record type doesn't get listed under suggestions inside select remote function

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#18806]
**Description:**
<img width="670" alt="Screen Shot 2019-09-07 at 4 05 42 PM" src="https://user-images.githubusercontent.com/1335271/64473838-7da1ef00-d189-11e9-9439-7c37ca9cca8b.png">

**Steps to reproduce:**

**Affected Versions:**
1.0.0-rc1-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
You need to add the semicolon at the end, in order to get the completions, since where the error is different from where the cursor is. This is currently a limitation in the source pruner

**Comment by nadeeshaan** [comment]
This issue has been fixed in 1.0.0 hence closing the issue.
