### ISSUE TITLE
Function info given in the completion only contains the return type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18807]
Consider the below case. In the function info, only the return type info is shown. As I got to know, param info is shown only if there are doc comments. This seems inconsistent and misleading. If we are showing function info, should show the complete signature info, including the params.
![Peek 2019-09-07 15-39](https://user-images.githubusercontent.com/6260009/64473800-fa809900-d188-11e9-92ac-22a5f24097e8.gif)

**Comment by nadeeshaan** [comment]
With the added fix, it will show all the parameters without descriptions if the particular documentation entry is not added. Closing since the fix has been merged.
