### ISSUE TITLE
VS Code plugin can't detect Ballerina installation

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#18826]
![VirtualBox_win7_07_09_2019_17_47_47](https://user-images.githubusercontent.com/1686124/64474808-a5984f00-d197-11e9-8ba5-00d5b0507793.png)

**Comment by mohanvive** [comment]
Issue is not observed in the latest VScode release. Hence, closing the issue. Please reopen if you encountered the issue again.
