### ISSUE TITLE
A module import through Ballerina.toml not resolving syntax in the VS code

### ISSUE THREAD

**Issue by indikasampath2000** [ballerina-platform/ballerina-lang#18821]
**Description:**
I import a module through `Ballerina.toml` as below.
```
[project]
org-name= "indika"
version= "0.1.0"

[dependencies]
"wso2/gsheets4"= {path="/home/indika/dev-zone/wso2-ballerina/fork/module-googlespreadsheet/target/balo/gsheets4-2019r3-any-0.8.24.balo"}
```

When I use the import statement in the ballerina program as below, it marked as an error with the message `cannot resolve module wso2/gsheets4`.

![module-import-errors](https://user-images.githubusercontent.com/3735291/64474564-25bcb580-d194-11e9-8128-8b41493ec08a.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@indikasampath2000 did you pull the module or added it to the project repo?

**Comment by nadeeshaan** [comment]
Closing the issue, based on the above comment, if the issue resides further, please reopen
