### ISSUE TITLE
Fix the formatting of the `ballerina build` output

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#18858]
<img width="503" alt="Screen Shot 2019-09-07 at 5 09 34 PM" src="https://user-images.githubusercontent.com/2637328/64481566-bb574580-d192-11e9-9f12-9fa4a342adbe.png">

Refer the attached image: The output of Running test should be formatted properly to be consistent with other lines.

**Comment by hemikak** [comment]
@sameerajayasoma This is not a blocker right ?

**Comment by Kishanthan** [comment]
This is fixed with above PR.
