### ISSUE TITLE
Changing the Depth setting does not affect invocations inside hidden blocks

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#18871]
**Description:**
In the diagram changing the Depth setting does not affect invocations inside hidden blocks

**Steps to reproduce:**
```ballerina 
function test() {
    firstLevel();
}

function firstLevel() {
    secondLevel();
}

function secondLevel() {
    thirdLevel();
}

function thirdLevel() {
}
```
Click on hidden block icon in test(). And change Depth.
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
