### ISSUE TITLE
[Spec Deviation] lang.array module functions which modify the value are disallowed on tuples

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18874]
With the introduction of the rest descriptor to tuples, we can allow some of the functions like push() on tuples as well. Also, functions like sort can be allowed on tuples which have the same element type for all the elements.

**Comment by MaryamZi** [comment]
Push is now supported on tuples - https://github.com/ballerina-platform/ballerina-lang/pull/19348.

However the following (sort) fails with "incompatible types: expected '[int,int...]', found 'int[]'"

```ballerina
public function main() {
    [int, int...] x = [2, 1];
    int[] y  = x.sort(function(int i, int j) returns int {
        return i - j;
    });
}
```

**Comment by MaryamZi** [comment]
`array:sort` can now be used with tuples, and creates a new array anyway.
