### ISSUE TITLE
Unable to convert json into record

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#18883]
**Description:**
When trying to convert a json to a record following error appears.
`{ballerina}ConversionError {"message":"incompatible convert operation: 'json' value cannot be converted as 'celleryio/cellery:0.0.0:CellMeta’"}`

**Steps to reproduce:**
1. Create the following records.

`public type CellMeta record {
string org?;
string name?;
string ver?;
map<ComponentMeta> components?;
};`

`public type ComponentMeta record {
DependencyMeta dependencies?;
};`

`public type DependencyMeta record {
map<CellMeta> components?;
};`

2. Convert the following json into CellMeta record.
`{
  "org": "myorg",
  "name": "hr",
  "ver": "1.0.0",
  "schemaVersion": "0.1.0",
  "kind": "Cell",
  "components": {
    "hr": {
      "dockerImage": "wso2cellery/sampleapp-hr:0.3.0",
      "isDockerPushRequired": false,
      "labels": {},
      "ingressTypes": [
        "HTTP"
      ],
      "dependencies": {
        "cells": {
          "employeeCellDep": {
            "org": "myorg",
            "name": "employee",
            "ver": "1.0.0",
            "schemaVersion": "0.1.0",
            "kind": "Cell",
            "components": {
              "employee": {
                "dockerImage": "wso2cellery/sampleapp-employee:0.3.0",
                "isDockerPushRequired": false,
                "labels": {
                  "team": "HR"
                },
                "ingressTypes": [
                  "HTTP"
                ],
                "dependencies": {
                  "cells": {},
                  "composites": {},
                  "components": [
                    "salary"
                  ]
                }
              },
              "salary": {
                "dockerImage": "wso2cellery/sampleapp-salary:0.3.0",
                "isDockerPushRequired": false,
                "labels": {
                  "owner": "Alice",
                  "team": "Finance"
                },
                "ingressTypes": [
                  "HTTP"
                ],
                "dependencies": {
                  "cells": {},
                  "composites": {},
                  "components": []
                }
              }
            },
            "buildTimestamp": 1567761713,
            "buildCelleryVersion": "0.4.0-SNAPSHOT",
            "zeroScalingRequired": false,
            "autoScalingRequired": false
          },
          "stockCellDep": {
            "org": "myorg",
            "name": "stock",
            "ver": "1.0.0",
            "schemaVersion": "0.1.0",
            "kind": "Cell",
            "components": {
              "stock": {
                "dockerImage": "wso2cellery/sampleapp-stock:0.3.0",
                "isDockerPushRequired": false,
                "labels": {},
                "ingressTypes": [
                  "HTTP"
                ],
                "dependencies": {
                  "cells": {},
                  "composites": {},
                  "components": []
                }
              }
            },
            "buildTimestamp": 1567761696,
            "buildCelleryVersion": "0.4.0-SNAPSHOT",
            "zeroScalingRequired": false,
            "autoScalingRequired": false
          }
        },
        "composites": {},
        "components": []
      }
    }
  },
  "buildTimestamp": 1567761731,
  "buildCelleryVersion": "0.4.0-SNAPSHOT",
  "zeroScalingRequired": false,
  "autoScalingRequired": false
}`

**Affected Versions:**
ballerina 0.991.0

**OS, DB, other environment details and versions:**
Mac OS

**Suggested Labels (optional):**
Bug

**Comment by SupunS** [comment]
This JSON doesn't match the expected record. Theres a `"components": []` field under the `dependencies` element, which is not compliant to the `DependencyMeta` record.
