### ISSUE TITLE
Rest params inconsistently appear both as array and varargs 

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#18900]
During function name completion it appear as var-args but during function argument completion it appear as array.
![VirtualBox_win7_08_09_2019_14_09_50](https://user-images.githubusercontent.com/1686124/64485882-6d4e4a80-d243-11e9-9270-c2f279f72777.png)

**Comment by rasika** [comment]
Fixed in the latest master
<img width="566" alt="Screenshot 2020-03-04 at 10 00 50" src="https://user-images.githubusercontent.com/1448489/75845432-18108180-5dff-11ea-84f7-d62b88ff1466.png">
