### ISSUE TITLE
No completion/suggestion for the `public` keyword for function parameters

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18930]
**Description:**
Function parameters can now have the `public` visibility qualifier, but $title.

![no_public_sugg](https://user-images.githubusercontent.com/8376983/64487881-143fe000-d25e-11e9-8737-47875a834942.png)

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-rc1-SNAPSHOT
Language specification 2019R3
```

**Comment by nadeeshaan** [comment]
No longer valid for the latest spec, Swan Lake preview 2021-01-12. Hence closing the issue
