### ISSUE TITLE
`returns` keyword is not suggested when there is a defaultable parameter

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18931]
**Description:**
$title.

![no_sugg_return](https://user-images.githubusercontent.com/8376983/64487950-f2932880-d25e-11e9-90fc-ecf9dc5afca3.png)

**Steps to reproduce:**
```ballerina
public function bar(int i, public float f = 1.0) re {
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-rc1-SNAPSHOT
Language specification 2019R3
```

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
