### ISSUE TITLE
Debugger jumps to the end of file when there are defaultable params with function invocations

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#18943]
**Description:**
When debugging sample code below, it jumps to end of file in between default param expression evaluations(doing step into)
and also it tries to open io bal files when tries to do a step into in the println lines

**Steps to reproduce:**

sample code
```ballerina
import ballerina/io;

int val1 = 9;
# Prints `Hello World`.

public function main() {
    io:println("Hello World!");
    io:println(test());
    io:println(test(8));
    io:println(test(8, 10));
}

public function test(int b = abc(), int c = cde(b)) returns int {

    int res = b - c;

    return res;
}

public function abc() returns int {
    int val = 9;
    return val;
}

public function cde(int a) returns int {
    int sam = a * 7;

    return sam;
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pahans** [comment]
looks like part of the problem is a line numbers mapping. I added a breakpoint to `int val = 9` and it's never even though it is executed.

**Comment by warunalakshitha** [comment]
I did a debug with step into and continue with given code. Seems working fine for me except  open io bal files.

**Comment by pahans** [comment]
step into issue describe is captured in https://github.com/ballerina-platform/ballerina-lang/issues/18949
