### ISSUE TITLE
No method suggestions in statement RHS

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#18946]
**Description:**
No method suggestions appear in rhs expressions

**Steps to reproduce:**
time:Time startTime = time:
in the above line, no method suggestions appear.

**Affected Versions:**
RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18950
