### ISSUE TITLE
Incorrect API descriptions are shown in VSCode auto-complete

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#18944]
**Description:**

See the below sample:

![image](https://user-images.githubusercontent.com/7834839/64503527-1307c500-d2e9-11e9-8a0d-0e3cb344625a.png)

The actual return type of the `get()` method should be `json` in this scenario. However VSCode plugin shows it as `any|error`

**OS, DB, other environment details and versions:**

ballerina-1.0-RC1

**Comment by nadeeshaan** [comment]
This relevant information is extracted from the symbols and this is the current information we receive from the compiler. So this is the expected behaviour and hence will be closing the issue.
