### ISSUE TITLE
Elements overlap in the diagram view

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#18958]
**Description:**
Sample function:
```ballerina
function mergeSort(int[] array, int startIndex, int endIndex) returns int[] {
    int len = endIndex - startIndex;
    if (len == 0) {
        return [array[startIndex]];
    }

    int mid = (startIndex + endIndex)/2;
    worker w1 returns int[] {
        return mergeSort(array, startIndex, mid);
    }
    worker w2 returns int[] {
        return mergeSort(array, mid + 1, endIndex);
    }
    record{ int[] w1; int[] w2; } results = wait {w1, w2};
    return merge(results.w1, results.w2);
}
```

Diagram view:

![image](https://user-images.githubusercontent.com/7834839/64514422-342bde00-d308-11e9-864f-38f613afa3c8.png)

You can see some text nodes are overlapped in the diagram view.

**Affected Versions:**
ballerina-1.0-RC1

**OS, DB, other environment details and versions:**
MacOS - High sierra

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
