### ISSUE TITLE
the diagram for the example code  "access-mutual-java-fields" is not available

### ISSUE THREAD

**Issue by shehand** [ballerina-platform/ballerina-lang#18961]
**Description:**
The sequence diagram for the example code (access-mutual-java-fields) is not available in the file overview.

**Steps to reproduce:**
```ballerina
import ballerinax/java;
import ballerina/io;

// Define a Ballerina function which will act as a Java field getter.
public function pi() returns float = @java:FieldGet {
    name:"PI",
    class:"java/lang/Math"
} external;

public function main() {
    float r = 4;
    // If a field is an instance field, the receiver instance has to be provided as the first parameter.
    float l = 2 * pi() * r;
    io:println(l);
}
```

**Affected Versions:**
1.0.0 rc1
**OS, DB, other environment details and versions:**
OS : Ubuntu 18.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
