### ISSUE TITLE
Comments are shown in the tooltip of expanded function title

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#18964]
**Description:**

Comments are shown in the tooltip of expanded function title.
![2](https://user-images.githubusercontent.com/27485094/64518172-5543fd00-d30f-11e9-89a1-3c2c97591fef.png)

**Steps to reproduce:**
``` ballerina
function test() {
    //this is the test function
    firstLevel();
}

function firstLevel() {
    //this is the firstLevel function
        secondLevel();
}

function secondLevel() {
     }

```
**Affected Versions:**
1.0.0-RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
