### ISSUE TITLE
Changing the Depth setting doesn't alter the diagram for hidden blocks

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#18963]
**Description:**

Changing the Depth setting doesn't alter the diagram for hidden blocks.

**Steps to reproduce:**

**Affected Versions:**
1.0.0-RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
