### ISSUE TITLE
Interaction mode doesn't show statements in the else block

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#18962]
**Description:**
When the diagram is drawn, statements in the else block are not displayed in Interaction mode.

![1](https://user-images.githubusercontent.com/27485094/64517518-1eb9b280-d30e-11e9-9008-5cd2a2af7d1d.png)

**Steps to reproduce:**

**Affected Versions:**
1.0.0-RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
