### ISSUE TITLE
Invalid runtime error on chained method calls for type int

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#18968]
**Description:**

$title

**Steps to reproduce:**
```ballerina
public function main() {
    var e = 0;
    int a = e.max(1).min(2);
}
```
Runtime Error
```
error: {ballerina/lang.array}InherentTypeViolation message=incompatible types: expected 'int', found 'int[]'
        at irshadnilam.linkedmap:main(linked_map.bal:3)
```
**Affected Versions:**
Ballerina 1.0.0
Language specification 2019R3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
@hasithaa  Shouldn't this give a compile error? shouldn't `max()` or `'min()'` be called as a normal function rather than a type-attached function, like below?

```ballerina
import ballerina/lang.'int as langInt;

public function main(string... args) {
    var e = 0;
    int a = langInt:max(e);
}
```

**Comment by SupunS** [comment]
Anyway the desugar seems to be wrong for `int a = e.max(1).min(2);`. Below is what resulted after desugar phase:

```ballerina
int a = <int> <int> e.max(e, 1).min(e.max(e, 1), 2);
```

**Comment by MaryamZi** [comment]
Fails on slalpha1 with `error: casting is not supported from 'int[]' to 'int'`.

**Comment by grainier** [comment]
similar to https://github.com/ballerina-platform/ballerina-lang/issues/25783
