### ISSUE TITLE
Keywords are not suggested in worker

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#18974]
**Description:**
$title

**Steps to reproduce:**
```ballerina
fork {
        worker w1 returns json {
            return invokeEndpoint(clientEP1, payload);
        }
}
```
The "returns" and "json" keywords are not suggested.

**Affected Versions:**
Ballerina 1.0.0
Language specification 2019R3

**OS, DB, other environment details and versions:**
Visual Studio Code
Version: 1.38.0

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
Fixed with Fix completion issue in fork workers #19074
