### ISSUE TITLE
For worker send, tooltip does not show up and go to source does not work

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#18976]
**Description:**

For worker send, tooltip does not show up and go to source does not work.
![3](https://user-images.githubusercontent.com/27485094/64528895-305b8400-d327-11e9-81fb-edee1620ee44.png)

**Steps to reproduce:**
```ballerina
function square(int n) returns int {
    return n * n;
}

function cube(int n) returns int {
    return n * n * n;
}

function squarePlusCube(future<int> f) returns int {
    worker w1 {
        int n = wait f;
        int sq = square(n);
        sq -> w2;
    }
    worker w2 returns int {
        int n = wait f;
        int cb = cube(n);
        int sq;
        sq = <- w1;
        return sq + cb;
    }
    // Waits for the worker `W2` to complete.
    return wait w2;
}
```
**Affected Versions:**
1.0.0-RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19121
