### ISSUE TITLE
ASCII 160 (non-breaking space) is not recognized as a space character by the parser

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#18987]
**Description:**

Currently ASCII 160 is not considered as a space. Hence any non-breaking-space is combined with the immediate next token, resulting symbol not found issues.

sample:
```
wso2/sfdc46:0.10.0::salesforceBulk/sf_bulk_data_mappings.bal:33:35: undefined module ' jsonutils'
```
Note the whitespace at the start of the symbol name of the module (`' jsonutils'`).

Not sure if this is a bug or the correct behavior. But I think all the chars in the space category ASCII 32 and ASCII 160 should be treated as a whitespace.

**Comment by SupunS** [comment]
The common approach in C family languages is to treat these other characters in the unicode 'space separator' category as an invalid character. We can follow a similar approach where,
- Any invalid character is reported at the lexer. Lexer goes to the invalid token processing state.
- Processing an invalid token should terminate when a valid token start character is reached.
  - In the above sample, leading  `&nbsp` will be reported as an invalid character. 
  - The following `jsonutils` token will be treated as a valid identifier token.

**Comment by hasithaa** [comment]
@lochana-chathura @rdulmina Could you please check, whether this with the new parse?

**Comment by lochana-chathura** [comment]
Currently, only ASCII 32 is considered to be a space character.

Other space characters are treated as invalid from the lexer. 
However, `isEndOfInvalidToken()` logic should be improved to end the invalid token process to terminate whenever a valid char is reached. (There's a `TODO` for that in the codebase.)

For example, the following are

![Screenshot from 2021-02-21 14-44-59](https://user-images.githubusercontent.com/39232462/108620644-7fca3d00-7453-11eb-99e0-7b73eed01e26.png)

```
int  month = 10;
int  month = 10;
int  month = 10;
int  month = 10;
```
parsed as `int  MISSING[] INVALID[ month] = 10;`

Once improved can get,  `int  INVALID[ ] month = 10;`
