### ISSUE TITLE
Cannot concatenate strings and immediately use its string operations inline

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#19020]
Below sample code:

```ballerina
 string x = "1234";
 byte[] bs = ("A" + x).getBytes();
```

The above fails in compilation, and gives the following error:

```
Compiling source
        test.bal
error: .::test.bal:16:26: mismatched input '.'. expecting {'is', ';', '?', '+', '-', '*', '/', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '===', '!==', '&', '^', '...', '|', '?:', '->>', '..<'}
```

**Comment by grainier** [comment]
#20234 Partially fixes the issue. However, still cannot use expressions within the group (i.e `("A" + x).length()`, `(<PersonObj>(dataMap)["a"]).getName()`) due to current grammar limitations.

**Comment by lafernando** [comment]
Shall we fix the grammar limitation?.

**Comment by dulvinw** [comment]
Can be closed since already fixed

**Comment by hasithaa** [comment]
@dulvinw Shall we add test case and close this?

**Comment by hasithaa** [comment]
This is fixed in SLP1.
