### ISSUE TITLE
JVM code and module restructure with proper phases

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#19027]
**Description:**
JVM code and module restructure with proper phases for each major activity.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19027

**Comment by manuranga** [comment]
new `BackendDriver.java` (`ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BackendDriver.java`) addresses this
