### ISSUE TITLE
Finalize BIR model spec

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#19025]
**Description:**
Finalize the BIR model tree.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24771
