### ISSUE TITLE
Add BBE for XSLT support

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#19032]
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kalaiyarasiganeshalingam** [comment]
Closing the issue as XSLT BBE added in #22508
