### ISSUE TITLE
Issue while building a WSO2 Microgateway project

### ISSUE THREAD

**Issue by SushantWankhede** [ballerina-platform/ballerina-lang#19034]
**Description:**
Issue while building a WSO2 Microgateway project

**Steps to reproduce:**
1. The Microgateway toolkit initialized at a location. 
2. The Microgateway project is initialized and built.
3. After building the error in the attached log file came. 

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows 10
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3606791/ballerina-internal.log)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praminda** [comment]
This is a wso2 microgateway issue. I'll transfer the issue to mgw repo

**Comment by praminda** [comment]
@SushantWankhede Please refer to wso2/product-microgateway#793
