### ISSUE TITLE
No syntax checking or code suggestions in VS Code

### ISSUE THREAD

**Issue by Ninja243** [ballerina-platform/ballerina-lang#19038]
**Description:**
Syntax checking (the red lines under code that does not make much sense to Ballerina) and code completion suggestions (the autocorrect-like boxes that pop up to help you write code) do not seem to work anymore. This problem has been reported to me by others who run Windows 10 too, however I have not had the time to attempt to reproduce that. Syntax highlighting still works.

**Steps to reproduce:**
* Download and install Ballerina 0.991 from ballerina,io
* Install VS Code extension
* Open a folder you can write in with VS Code
* Use Control - J to open the terminal
* Run `ballerina init`
* Open the example service generated
* Change some of the code to something that should throw an error
* Hit save to make sure syntax checking should be happening

**Affected Versions:**
Ballerina Extension for VS Code version 16.104

**OS, DB, other environment details and versions:**
Pop_OS! 19.04, Windows 10

**Comment by Ninja243** [comment]
A potential solution is downgrading by downloading the older VS Code extension from [this link]("https://ballerina.gallery.vsassets.io/_apis/public/gallery/publisher/ballerina/extension/ballerina/0.991.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) and installing it using the instructions found [here.](https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/
)

**Comment by nadeeshaan** [comment]
@Ninja243 Can you verify what is the Plugin version you are using?

**Comment by roonyh** [comment]
@Ninja243 At the moment the vscode extension is not backward compatible. You have to install the matching version of the vscode extension. Installing a specific version is now built into vscode. (Update your vscode editor to latest). See https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545

**Comment by roonyh** [comment]
When installing from the marketplace vscode always installs the latest extension version. At the moment latest is 1.0.0. So it won't work with ballerina 0.991. You'll have to install extension version 0.991.x too. I'll close the issue since this is expected.
