### ISSUE TITLE
Creating a table results in an error

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19053]
**Description:**
Creating an empty table in a ballerina service results in following error:
`error: error {ballerina}TableOperationError message=error in getting connection for table db : No suitable driver found for jdbc:h2:mem:TABLEDB;DB_CLOSE_DELAY=-1`

Now please not that I don't have H2 driver included in my project also.

**Steps to reproduce:**

Consider following code:
`
public type Application record {|
    string id;
    string name;
    string description;
|}; 

 table<Application> applications;
// more code
applications = table{};
`
above code will throw the error when written in a service / resource.

**Affected Versions:**
v 1.0.1
**OS, DB, other environment details and versions:**
MacOs, JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**

bug
**Suggested Assignees (optional):**

@SupunS @anupama-pathirage @Manuri

**Comment by anupama-pathirage** [comment]
This is an issue with Uber jar creation. Issue can be reproduced by simply having a module with some jdbc driver dependancy in the .toml file and in memory table within the code.

Reproduce the issue by : 

**hello_service.bal**

```ballerina
// A system module containing protocol access constructs
// Module objects referenced with 'http:' in code
import ballerina/http;
import ballerina/io;

public type Application record {|
    string id;
    string name;
    string description;
|};


# A service is a network-accessible API
# Advertised on '/hello', port comes from listener endpoint
service hello on new http:Listener(9090) {

    # A resource is an invokable API method
    # Accessible at '/hello/sayHello
    # 'caller' is the client invoking this resource 

    # + caller - Server Connector
    # + request - Request
    resource function sayHello(http:Caller caller, http:Request request) {

        table<Application> applications = table{};

        // Send a response back to caller
        // -> indicates a synchronous network-bound call
        error? result = caller->respond("Hello Ballerina!");
        if (result is error) {
            io:println("Error in responding", result);
        }
    }
}

```

**Toml file:**

```
[project]
org-name= "test"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "lib/mysql-connector-java-8.0.17.jar"
    groupId = "mysql"
    modules = ["myservice"]
```

**Project Structure:**
<img width="348" alt="image" src="https://user-images.githubusercontent.com/16300038/65747294-b8f76400-e11e-11e9-8fda-fb39d86063f0.png">


**Run the service**

ballerina build -a
java -jar target/bin/myservice.jar

**Comment by warunalakshitha** [comment]
Root cause for this issue is when we creating uber jar, spi service implementation definition files will be get replace instead of merging them. Therefore h2 driver implementation will be replaced by other jdbc driver implementation.
