### ISSUE TITLE
[Idea Plugin] Diagram view doesn't work for some samples

### ISSUE THREAD

**Issue by arukshani** [ballerina-platform/ballerina-lang#19059]
$subject won't work for https://v1-0.ballerina.io/learn/by-example/different-payload-types.html sample. 

![image](https://user-images.githubusercontent.com/12377918/65011720-2db5eb80-d932-11e9-94f2-3774c9ba12af.png)

**Comment by NipunaRanasinghe** [comment]
@roonyh Shall we have a look? :)

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
