### ISSUE TITLE
Can't invoke a function passed as an argument to a function union parameter

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19061]
**Description:**
$title. Compilation fails with `undefined function`.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function testFuncAsParam(function()|function() returns any|error func) {
    // io:println(func); // this works
    var result = func(); // undefined function 'func'
}

public function main() {
    testFuncAsParam(function() {
        io:println("test value");
    });
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0
Language specification 2019R3
```

**Comment by irshadnilam** [comment]
@MaryamZi @hasithaa 
Although the above code snippet doesn't work, the following compiles without any problem.
```ballerina
public function testFuncAsParam(function()|function() returns any|error func) {
        if (func is function () returns ()) {
	    func();
	} else {
	    var result = func();
	}
}

public function main() {
    testFuncAsParam(function() returns int{
       return 1;
    });
}
```
Should we allow invoking union types without knowing the type (return types) ?

Consider a scenario like the following. 

```ballerina
public function testFuncAsParam(string|function() returns any|error foo) {
    foo();
}

public function main() {
    testFuncAsParam(function() returns int{
       return 1;
    });
}
```
___
Shall we print a proper error message instead of `undefined function` for this scenario?
Thoughts?

**Comment by MaryamZi** [comment]
In a scenario where we have a function union 
`(function(int i) returns int)|(function(int i, string s = "hello")) foo`

IMO an invocation like `foo(1)` is valid, since invoking either one of the function with an `int` as an (and only) argument is valid. The return type could be the union of the individual return types `int?`.

The spec says "The variable-reference must refer to a variable with function type." though. 

Given the complexities I'm OK with either fixing or disallowing. 

Regarding your second example though, that would not be possible anyway, since one member of the union is not a function.
