### ISSUE TITLE
Code action, pull module not working in windows

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#19065]
**Description:**
Code action, pull module not working in windows.

**Steps to reproduce:**
Try to execute code action for a module that hasn't pulled before.

```ballerina
import wso2/github4
```

**Affected Versions:**
1.0.0

**Comment by kaviththiranga** [comment]
Fix is merged https://github.com/ballerina-platform/ballerina-lang/pull/19066
