### ISSUE TITLE
Stack trace is not logged during a casting error in b7a service

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#19064]
**Description:**
Ballerina does not print the stack trace if the , runtime error happens during a casting.

any a = "abcd";
int x = <int>a;

This does not print the stack trace when used in ballerina services. But seems to print the stack trace when used in main function

**Steps to reproduce:**

**Affected Versions:**
1.0.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
This occured only in http services due to logging error without stack trace.

**Comment by wggihan** [comment]
This will be fixed with 1.0.1.
