### ISSUE TITLE
Runtime error in compound assignment of a tuple

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#19079]
**Description:**
I am running the following bal code.
```ballerina
public function main() {
    Foo foo = {};
    [[int, int], [int, int]] a = [[3, 10], [20,30]];
    a[f(1, foo)][0] += 10;
}

function f(int i, Foo f) returns (int) {
    f.age += 1;
    return 0;
}

type Foo record  {
    int age = 0;
};
```
When I am trying the ballerina run command, a runtime error is occurring.

**Steps to reproduce:**
Run the above code.

**Affected Versions:**
1.0.0

**OS, DB, other environment details and versions:**
Visual Studio Code
Version: 1.38.0

**Comment by SupunS** [comment]
A minified version of the program:
```ballerina
public function main() {
    [[int, int], [int, int]] a = [[3, 10], [20,30]];
    a[foo()][0] += 10;
}

function foo() returns (int) {
    return 0;
}
```

**Comment by KavinduZoysa** [comment]
This issue has been fixed in new versions.
