### ISSUE TITLE
Inconsistent parameter names in stringutils API

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#19073]
**Description:**
Names of the first and the second parameters are inconsistent for the below three methods. Since all three methods are different variants of the same functionality, the parameters should also be consistent.

```ballerina
public function replace(string originalText, string textToReplace, string replacement);

public function replaceAll(string originalString, string regex, string replacement) returns string;

public function replaceFirst(string originalString, string stringToReplace, string replacement) returns string;
```

**Affected Versions:**
1.0.0

**Comment by sprinkle24** [comment]
Created a pull request for this: https://github.com/ballerina-platform/ballerina-lang/pull/19368
