### ISSUE TITLE
IntelliJ plugin formatting related issues with workers and interaction

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#19077]
**Description:**
I have following bal program.
![image](https://user-images.githubusercontent.com/4163165/65029117-c82a2500-d95a-11e9-8996-c7728b9b314c.png)

After formatting

![image](https://user-images.githubusercontent.com/4163165/65029218-fad41d80-d95a-11e9-9984-3a85d1b9b739.png)

When I format the above program, 
1) spaces between 'worker' and worker name didn't get removed.
2) There should be a space between worker names in wait actions. ex wait {w1, w2}
3) If i select a specific line and format didn't work as well.

**Comment by NipunaMarcus** [comment]
About the 3rd issue... formatter doesn't work for a selected line for now as we need partial parsing support from the compiler side... now its only works for the whole document. 

Will send fixes for the other two issues.
