### ISSUE TITLE
Auto Completion doesn't work for xml indexing

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#19086]
**Description:**
```ballerina
xml bookXML = xml `<book>
                <name>Sherlock Holmes</name>
                <author>
                    <fname title="Sir">Arthur</fname>
                    <mname>Conan</mname>
                        <lname>Doyle</lname>
                </author>
                <!--Price: $10-->
                </book>`;
string name = bookXML["name"].<cursor position>
```

In the above scenario, intellij plugin doesn't support code completion.

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
