### ISSUE TITLE
AWS Lambda Integration Instructions Outdated

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#19089]
The current AWS Lambda extension functionality is outdated in Ballerina 1.0. It still shows the custom Ballerina Lambda Layer based approach to do it. We should now be able to directly use the default support Java functionality in AWS Lambda to get our one working. This will change our usage string when building the Ballerina source with lambda annotations.

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerinax/awslambda/pull/68

Still we need to publish layers with bootstrap file and no need to publish layers with each release

**Comment by lafernando** [comment]
Ack.
