### ISSUE TITLE
XML sequence equality checks fail when the sequence has text items

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19092]
**Description:**
$title. 

Seems to be happening due to the following
- to check sequence equality, we iterate over the sequence members by size https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLFactory.java#L448
- but `.size()` seems to be returning a modified size and not the actual sequence size 
https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/XMLSequence.java#L495
- thus iteration fails with an index out of range error, and false is returned as the result for the equality check

This could happen for other combinations (if sizes are different) too.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    xml xmlElement = xml `<book status="available">The Lost World</book>`;
    xml xmlCharacters = xml `Book Store`;

    xml xmlSequence1 = xmlElement + xmlCharacters;
    xml xmlSequence2 = xmlElement + xmlCharacters;

    io:println(xmlSequence1 == xmlSequence2);
}
```

```cmd
$ ballerina run abc.bal 
false
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0
Language specification 2019R3
```

**Comment by rdhananjaya** [comment]
Fixed in 1.2.0
