### ISSUE TITLE
Secured unary gRPC web page document error

### ISSUE THREAD

**Issue by 7slcode7** [ballerina-platform/ballerina-lang#19107]
**Description:** Client implementation part mistakenly noted as service's implementation. 

**Correction:** Highlighted area should be corrected as client.

Page link -: https://v1-0.ballerina.io/learn/by-example/grpc-secured-unary.html
![Screenshot_2019-09-18 Ballerina - Cloud Native Programming Language - Ballerina by Example Secured Unary](https://user-images.githubusercontent.com/40932779/65169104-80db8b80-da63-11e9-9f29-96363226f597.png)

**Comment by anupama-pathirage** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19134
