### ISSUE TITLE
Additional docs for exaplaining concept of 'error' and its contructors

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19104]
**Description:**
I know there is some documentation on custom error types ( in Learn by Example section).
However, there is no documentation on following (at least I could find) explaining below constructor ( and variations related to that).

`error e = error("error reason", message = "detail message", cause = causeError, mycustomField = "one", intField = 2); `

Its worth while explaining how to chain errors, and recommended conventions such as 'module-qualified reason string's ( refer : https://v1-0.ballerina.io/spec/lang/v2019R3/#section_5.2.5) ) 

**Steps to reproduce:**

**Affected Versions:**
v 1.0.0
**OS, DB, other environment details and versions:**
MacOs, JDK 1.8 

**Suggested Assignees (optional):**

@hevayo @hasithaa @MaryamZi

**Comment by rdhananjaya** [comment]
Updated the error BBEs to reflect this issue.
