### ISSUE TITLE
LHS expression cannot be a function invocation in compound assignment

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#19116]
**Description:**
$subject

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    Bar ba = {};

    foo(ba).bar += 10;
    io:println(ba);
}

function foo(Bar b) returns Bar {
    b.bar += 1;
    return b;
}

type Bar record {
    int bar = 0;
};
```
Above code runs without throwing an error.

**Affected Versions:**
Ballerina 1.0.0
Language specification 2019R3

**Comment by SupunS** [comment]
Why should we fail this? isn't `foo(ba).bar += 10;` a valid statement?

**Comment by KavinduZoysa** [comment]
> Why should we fail this? isn't `foo(ba).bar += 10;` a valid statement?

Since `foo(ba)` is function invocation and basically function invocations cannot be in left-handed side of a statement.

**Comment by SupunS** [comment]
I am wondering whats the reason behind not allowing it?

```ballerina
foo(ba).bar += 10;
```
is equivalent to
```ballerina
Bar b = foo(ba);
b.bar += 10;
```

If we allow the second, then why not the first?

**Comment by rdhananjaya** [comment]
I think this is more about aligning with the spec.
```
assignment-stmt := lvexpr = action-or-expr ;
compound-assignment-stmt := lvexpr CompoundAssignmentOperator action-or-expr ;
CompoundAssignmentOperator := BinaryOperator =
BinaryOperator := + | - | * | / | & | | | ^ | << | >> | >>>

lvexpr :=
   variable-reference-lvexpr
   | field-access-lvexpr
   | member-access-lvexpr

variable-reference-lvexpr := variable-reference
field-access-lvexpr := lvexpr . field-name
member-access-lvexpr := lvexpr [ expression ]
```

**Comment by SupunS** [comment]
Ack.
