### ISSUE TITLE
Ability to register a error handlers for services

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19117]
**Description:**
I propose there has to be a way to register (global and/or per service) error-handlers for ballerina 'service' construct.
Reason: I need to be able to control the behavior (and content) of how errors are transmitted back to client. For example: if I'm running my ballerina service in a local/dev environment I should be able send a descriptive message about the error that occurred while if I'm running in production I probably don't want to reveal too much information to the client.

Now I can do the same thing by checking for each error condition with-in the 'resource'. But reality of that is, amount of 'boiler-plate' code written becomes higher than code written for 'business-logic'.

As per my understanding, programmer can't customize the default behavior.

**Affected Versions:**
v 1.0.0

**OS, DB, other environment details and versions:**
Mac, Jdk 1.8

@sameerajayasoma

**Comment by sameerajayasoma** [comment]
@ramith I created the following issue a few days ago. It is related to your requirement

https://github.com/ballerina-platform/ballerina-spec/issues/337

**Comment by bruno-garcia** [comment]
Ideally this would be made available to dependencies so services like sentry.io can hook and capture per/request and/or global errors.

**Comment by mohanvive** [comment]
We can achieve the requirement now using the on-fail clause support in Ballerina. Hence, closing the issue. Please reopen if you need any further clarification on this.
