### ISSUE TITLE
Improve error when trying to retrieve the payload when there is no payload

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19126]
**Description:**
$title.

**Steps to reproduce:**
Consider the following example.

foo_service.bal
```ballerina
import ballerina/http;
import ballerina/log;

type Person record {
    string name;
    int age;
};

service foo on new http:Listener(8080) {

    @http:ResourceConfig {
        methods: ["POST"],
        body: "person",
        consumes: ["application/json"]
    }
    resource function bar(http:Caller caller, http:Request req, Person person) {
        var result = caller->accepted("Accepted!");
        if (result is error) {
            log:printError("Error!", result);
        } else {
            log:printInfo("Success!");
        }
    }
}
```

client.bal
```ballerina
import ballerina/http;
import ballerina/io;

public function main() {
    http:Client httpClient = new("http://localhost:8080/foo");

    json jsonData = "{ name: \"John\", age: 20 }"; // jsonData is a string
    var response = httpClient->post("/bar", jsonData);
    
    if (response is http:Response) {
        io:println("Response Text Payload: ", response.getTextPayload());
    } else {
        io:println("Error: ", response);
    }
}
```

Invoking the service with a non-JSON object payload results in the following error:
```cmd
$ ballerina run client.bal 
Response Text Payload: error {ballerina/http}GenericClientError message=Error occurred while retrieving the text payload from the response cause=error {ballerina/mime}ParsingEntityBodyFailed message=Error occurred while extracting text data from entity : error Empty content
```

Can we mention that the error was in fact an incompatible payload? We can (and probably should) still include how/where it went wrong.

On the other hand, an incompatible JSON object as the payload mentions that data binding failed:
```
Response Text Payload: data binding failed: error {ballerina/lang.typedesc}ConversionError message='map<json>' value cannot be converted to 'Person'
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0
Language specification 2019R3
```

**Comment by MaryamZi** [comment]
Related to https://ballerina-platform.slack.com/archives/C47EAELR1/p1568907341033300?thread_ts=1568905338.028700&cid=C47EAELR1

**Comment by chamil321** [comment]
**Scenario 1: Sending non-JSON Object payload.**
HTTP client send payload as a text
```
POST /foo/bar HTTP/1.1
content-type: text/plain
host: localhost:8080
user-agent: ballerina/1.0.0
connection: keep-alive
content-length: 25  
```
Backend resource is restricted to "application/json" by consumes config. Hence you will obviously get the 415 response. 
```
HTTP/1.1 415 Unsupported Media Type
content-type: text/plain
content-length: 0
server: ballerina/1.0.0
date: Fri, 20 Sep 2019 08:15:45 +0530, 0B 
```
This is not a data binding issue. User is getting proper response. 
@arukshani Have we handled this behavior during the client payload serialization? I.e JSON is being serialized to a text payload

**Scenario 2: Sending incompatible JSON object**
Known issue(https://github.com/ballerina-platform/ballerina-lang/issues/18376). Shoild be fixed at lang level

**Comment by MaryamZi** [comment]
Ah, this is the restriction where we need to explicitly use `.setJsonPayload()` to set a JSON string as the payload right? 

Sorry, missed that the content type was being set as "text/plain". Getting a proper data binding error when the content type is set as "application/json".

However, I personally still find the error a bit unclear.

**Comment by MaryamZi** [comment]
As discussed offline with @arukshani and @Bhashinee the plan is to refine the MIME error and the subsequent HTTP error to emphasize that there is no payload.

Updated the title.
