### ISSUE TITLE
Improve the HTTP data binding BBE to make use of all the fields in the bound record

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19127]
**Description:**
$title as mentioned in https://ballerina-platform.slack.com/archives/C47EAELR1/p1568910584038800 - 
https://github.com/ballerina-platform/ballerina-lang/blob/master/examples/http-data-binding/http_data_binding.bal#L7 is not used. 

Would be useful to demonstrate chained access using the map (or maybe we could make that a record too).

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/19661, hence closing
