### ISSUE TITLE
Ballerina central very slow when pulling wso2/jms connector

### ISSUE THREAD

**Issue by indikasampath2000** [ballerina-platform/ballerina-lang#19123]
**Description:**

It takes a long time for `ballerina pull wso2/jms`. The jms balo file size is around 4.4MB. The pull command is showing the wrong data as well.

![ballerina-pull-start](https://user-images.githubusercontent.com/3735291/65233679-d9a53580-daf0-11e9-9b87-598e2d3fb8ad.png)

![ballerina-pull-end](https://user-images.githubusercontent.com/3735291/65233695-e0cc4380-daf0-11e9-9cf6-46623e910e4d.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Closing as PR is merged
