### ISSUE TITLE
vscode extension should fail gracefully when custom ballerina home is set and java home isn't available.

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#19128]
**Description:**
vscode extension should fail gracefully when custom ballerina home is set and java home isn't available.
Extension logs.
![](https://www.evernote.com/l/AK8Sf-g0R0tPToySTONQIM5QzuZUcbVk3NYB/image.png)

output for ballerina home command
"Error: Ballerina is supported only on JDK 1.8"
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19130
