### ISSUE TITLE
Possible spec deviation when a worker terminates with pending messages to be sent

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19125]
**Description:**
The spec says
"If a worker W is about to terminate normally and there are messages still to be sent in a queue (which must be the result of executing an async-send-action), then the worker waits until the messages have been received or some receiving worker terminates."

But the current implementation seems to have a different behaviour.

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/runtime;

public function main() {
    worker w1  returns string {
        5 -> w2;
        io:println("w1 almost done");
        return "done"; 
    }

    worker w2 {
        runtime:sleep(5000);
        io:println("two receiving");
        int x = <- w1;
    }

    string p = wait w1;
    io:println("wait: ", p);
}
```

```cmd
$ ballerina run abc.bal 
w1 almost done
wait: done # expected this to be after "two receiving"
two receiving 
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0
Language specification 2019R3
```

**Comment by vinok88** [comment]
Will be fixed after the resolution of https://github.com/ballerina-platform/ballerina-spec/issues/358

**Comment by Nadeeshan96** [comment]
Currently the plan is to keep the fire-and-forget nature in async send for the Swan Lake version.

For the Nutcracker version, we should implement as said in the spec. That is to wait until all the messages are passed before the worker returns. In addition to that, to implement the fire-and-forget nature, add a function to lang.runtime that terminates the current worker without waiting for queued messages to be flushed, as said in https://github.com/ballerina-platform/ballerina-spec/issues/358#issuecomment-1125941782.
