### ISSUE TITLE
Running/Disabling test groups in should be supported in ballerina 1.0.0

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#19137]
**Description:**
--group and --disable-group flags have been removed from ballerina 1.0.0 which was available upto 0.991. These flags should be added back to make use of test groups.

**Comment by hevayo** [comment]
Duplicate #18772

**Comment by azinneera** [comment]
Closing since its a duplicated issue. This would be tracked by #18772
