### ISSUE TITLE
file:readDir returned entries does not contain the path component

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#19149]
In "file:readDir", returned values' file:FileInfo only has a "getName()" method, which only contains the file name, but not the full subpath from the passed in directory path to "readDir". Due to this, we cannot identify where a certain file is located. 

The only workaround to iterate files is to always list files with readDir with max depth "1" and recursively call it to get it done.

**Comment by lafernando** [comment]
This is definitely a bug, the current functionality is useless without fixing this. @anupama-pathirage why was the "bug" tag removed from this?. This is reported in Sept, and it's still not fixed.

**Comment by pitou35** [comment]
bug confirmed

**Comment by anupama-pathirage** [comment]
@lafernando Seems the `Type/Bug` lable was removed by a mistake. 
@wggihan Shall we prioritize this issue for an upcoming release?

**Comment by wggihan** [comment]
Will try to fix this in upcoming 1.1.5 release.

**Comment by praveennadarajah** [comment]
@lafernando ,

We have planned to introduce a method **getRelativePath()** in [1] which will give the relative path from file:readDir().

The API design is as follows:

```
    # Returns the relative path
    #
    # + return - the relative path.
    public function getRelativePath() returns string {
        return self.relativePath;
    }
```
We believe the above will cater your requirement. WDYT?

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/file/src/main/ballerina/src/file/file_info.bal

**Comment by lafernando** [comment]
Shall we have the full path instead?. Because, after we do this operation and get individual FileInfo values, they need to have all the information, and not dependent on another value (base path) if we need to get the full path. Also, if we move around FileInfo values, and with the existence of "getRelativePath", someone can ask, what is this in relation to?. So in the context of the FileInfo structure, having the full path will make sense. If someone needs to get the subpath in relation to the base path, we need separate utils to do that.

**Comment by praveennadarajah** [comment]
@lafernando 
+1 for the full path. We agree that from the context of Fileinfo structure, having a full path is more meaningful than the relative path. We will proceed with the full path implementation.

The API design for the full path will be as follows:
```
    # Returns the path
    #
    # + return - the path.
    public function getPath() returns string {
        return self.path;
    }
```

**Comment by lafernando** [comment]
Looks good!.
