### ISSUE TITLE
file:readDir does not function properly

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#19148]
The following code:

```ballerina
import ballerina/io;
import ballerina/file;

public function main() returns error? {
    file:FileInfo[] files = check file:readDir("/home/laf/Desktop/ABC");
    foreach var file in files {
        io:println(file.getName());
    }
}
```

The above directory has two files "1.txt" and "2.txt", but it prints the following:-

$ ballerina run x1.bal 
ABC
1.txt
2.txt

Basically it prints the passed in directory itself. But its suppose to list the files and directories inside the given directory only.

**Comment by aashikam** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/19156
