### ISSUE TITLE
Can I used ballerina with Python?

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-lang#19141]
Can Ballerina call Python or vice versa?

thanks

**Comment by sameerajayasoma** [comment]
This is not possible at the moment. We also haven't explored Jython as well. Any ideas on that?

Ballerina only supports Java interoperability at the moment.

**Comment by scheung38** [comment]
Any examples with Java in that case thanks, but if python is available in the future that's going to be even more popular as more and more corporate clients prefer Python from my experience.

**Comment by SupunS** [comment]
You can find the samples at: https://v1-0.ballerina.io/learn/by-example/ under the category "Java Interoperability"

**Comment by SupunS** [comment]
I am closing this issue since answers have been provided for the queries raised.

If you have any further questions or need any further clarifications please feel free to re-open the issue or create a new issue.
