### ISSUE TITLE
Bad sad error - please report

### ISSUE THREAD

**Issue by chippyash** [ballerina-platform/ballerina-lang#19145]
**Description:**
Trying to run attached code I get the bad.sad error. Don't know why

**Steps to reproduce:**
IntelliJ Community

Files attached.
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3639637/ballerina-internal.log)
[src.zip](https://github.com/ballerina-platform/ballerina-lang/files/3639640/src.zip)

. Click run service file.

**Affected Versions:**
1.0.0 2019R3
**OS, DB, other environment details and versions:**
Win 10

**Comment by chamil321** [comment]
@chippyash Thanks for reporting the issue. This is due to a missing resource function validation during the resource registration. We have fixed it and will be available in the ballerina 1.0.1 release.
