### ISSUE TITLE
Add examples for accessing XML elements with namespaces

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19146]
**Description:**
$title.

e.g.,
```ballerina
    xml x1 = payload[ns:Body];

    xml x2 = payload["{http://org.apache.synapse/xsd}Body"];
```

https://ballerina.io/learn/by-example/xml-access.html does not demonstrate usage with namespaces.

**Comment by praneesha** [comment]
Fixed via [1].

[1] https://github.com/ballerina-platform/ballerina-lang/pull/19437
