### ISSUE TITLE
Improve error messages to support recursive checks (anon-records)

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#19161]
**Description:**
$title

**Steps to reproduce:**
```
public function main() returns error? {
    int x = 10;
    record { int i; record { string name;}j;} a = { i : 10, j : { name : "a"}};
    a = x;
}
```
The above code shows the compiler error as bellow
`
main.bal:5:9: incompatible types: expected 'record {| int i; $record0 j; anydata...; |}', found 'int'
`
instead of showing `$record0`, this can be improved to display the exact type. 

**Affected Versions:**
Ballerina 1.0.0
Language specification 2019R3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Area/Compiler
Type/Improvements

**Suggested Assignees (optional):**

@irshadnilam

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19191
