### ISSUE TITLE
Run command args getting printed on console

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#19177]
**Description:**
The arguments passed to run command when running a jar file gets printed on the console before the jar runs.

**Steps to reproduce:**
`ballerina.bat run hello_world_client.jar`

**Affected Versions:**
1.0.1-SNAPSHOT

**Comment by anupama-pathirage** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19176
