### ISSUE TITLE
Code completion does not work as expected inside function invocation arguments

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#19188]
**Description:**
$subject.

**Steps to reproduce:**

Please refer the below sample. Code completion is not functional after adding first parameter to the function invocation of `foo`.

![Peek 2019-09-25 13-46](https://user-images.githubusercontent.com/29032600/65582792-b02a5500-df9b-11e9-9347-52cfa0311fad.gif)

**Affected Versions:**
jBallerina 1.0.0 and below.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
