### ISSUE TITLE
Improve the formatting/styling of "ballerina run" output

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#19182]
**Description:**

Please refer the sample output for a ballerina program below.

![Screenshot from 2019-09-25 11-45-50](https://user-images.githubusercontent.com/29032600/65574094-21610c80-df8a-11e9-8b0c-91d8a8d2f890.png)

1. It would be nice if we can have a separation (may be an empty line?) between
    **Running executables** and the actual program output.

2. Shall we have a consistency for the separation between the phases? 
(`Compiling source` , `generating executables` and `running executables`)

**Affected Versions:**
jBallerina 1.0.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
**Update:** It seems that the running phases related outputs have been moved to the std error channel, which will be shown as follows in the intellij run window.

![Screenshot from 2019-10-22 14-16-41](https://user-images.githubusercontent.com/29032600/67270606-a3374d80-f4d6-11e9-8537-51e51d217df8.png)

As per the offline discussion we had with @hemikak, @jo and @pubudu91, shall we move these back to the std out and add --quiet flag support so that users can have only the program output when building/running ballerina programs?

**Comment by praneesha** [comment]
@NipunaRanasinghe - The output of running a BAL file is now displayed as follows. Do we need any further improvements to this?

<img width="451" alt="Screenshot 2020-10-07 at 14 30 37" src="https://user-images.githubusercontent.com/11707273/95310380-f81bd180-08a9-11eb-92ec-1513ff1ce5d8.png">

**Comment by praneesha** [comment]
Now, we have added new lines to separate the output from the running phases and each phase.

However, still the running phases are printed as an error stream (in red) as shown below. Instead, they should be printed as normal strings/text.

<img width="1440" alt="Screenshot 2020-10-07 at 18 17 51" src="https://user-images.githubusercontent.com/11707273/95332830-923f4200-08c9-11eb-8e61-397451c09278.png">

**Comment by pramodya1994** [comment]
Here we needed separation between starter logs and application logs. That was the reason to implement this using the std error channel for starter logs. Since we no longer support the IntelliJ plugin this is no longer issue because vs code shows all std errors and out errors logs in the same manner.
