### ISSUE TITLE
Removed breakpoints are getting hit again in IDEA debugger

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#19194]
**Description:**
Removed breakpoints are getting hit again in IDEA debugger

**Steps to reproduce:**
Add a break point inside a loop and run the program with the debugger. Once the break-point got it,  remove the break point and continue. The removed breakpoint is getting hit indefinitely.

**Affected Versions:**
1.0.0

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
