### ISSUE TITLE
Formatting improvements

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#19209]
**Description:**

Seems like when we format the code, the empty lines between the imports are not removed. This is same for the other parts of the code as well.

So I think it is better to remove the spaces between the imports unless the space is separating packages in two different organizations.

Also, we can replace multiple empty newlines with a single(or double) newlines.

@NipunaMarcus WDYT?

### Before -

```ballerina
import ballerina/auth;

import ballerina/http;
import mno/xyz;
import abd/def;

import mno/pqr;



function test() {




    int i = 10;



    int j = 20;




}
```

### After - 

```ballerina
import abd/def;

import ballerina/auth;
import ballerina/http;

import mno/pqr;
import mno/xyz;

function test() {

    int i = 10;

    int j = 20;

}
```

**Comment by NipunaMarcus** [comment]
@Shan1024 yes this is an improvement that we are planning to do in the future ... for now, we save the new lines added by the Ballerina developer ...

**Comment by sanjana** [comment]
Tested on version **SLP5**. 
And this issue is fixed (the grouping of imports is not being implemented as per new formatter design review).

**Comment by SupunS** [comment]
Created a separate issue to track organize imports: https://github.com/ballerina-platform/ballerina-lang/issues/26617
