### ISSUE TITLE
All logs of commands(packerina) needs to be pointed to error stream

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#19206]
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**
1.0.0, 1.0.1

**Comment by pubudu91** [comment]
This should be brought up in the dev group. There seems to be mixed opinions on this since adding these to the std err gives a different experience to the users when they are using it through the terminals in their IDEs.

**Comment by azinneera** [comment]
This is done in Swan Lake.
