### ISSUE TITLE
Variable type is incorrect in debug mode

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#19207]
**Description:**

I noticed that the type of some variables are getting displayed as `Object`. Type of the `messageId` should be `json|error` and the type of the responsePayload should be `json` if I'm not mistaken.

Not sure whether these details are retrieved from the Language Server now.

![eab19b17-eae6-4a16-a3b1-8aa93871e501](https://user-images.githubusercontent.com/4003115/65661297-e6cba280-e063-11e9-8feb-5e95bd9f6644.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
@Shan1024 Current ballerina debugger implementation is based on [Debugger Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) and therefore the both plugins are getting debug information from the ballerina debugger adapter... We have captured some of the aforementioned issues and already started working on improving debug information, which will be shipped with the 1.0.2 release.

**Comment by Shan1024** [comment]
@NipunaRanasinghe Awesome. Looking forward to the new release 😃

**Comment by NipunaRanasinghe** [comment]
Closing since variable implementation/presentation has been enhanced with #23411.
