### ISSUE TITLE
Look at the possibility of using TOML v0.5

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19212]
We currently use toml4j library to parse TOML files. However, the toml4j library doesn't seem like it's being maintained and it only supports TOML v0.4. 

As an alternative, can we take a look a look at using [Night Config](https://github.com/TheElectronWill/Night-Config)? It seems like a well established project and it also supports TOML v0.5. The question is whether its license is compatible with ours. There's another project called [TomlJ](https://github.com/tomlj/tomlj). It's licensed under the Apache license. But it's a brand new project. 

Thanks @ramith for pointing out these projects! :)

**Comment by ramith** [comment]
My motivation for suggesting v 0.5 is the ability to use '.' in configuration names! :)

**Comment by hevayo** [comment]
Current plan is to move to a custom toml parser and will support 1.0-rc1
