### ISSUE TITLE
Support for compiling/building just the specified modules

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19223]
Currently, with `ballerina build`, you can give a module name or you can give the `-a` flag. So either you can compile/build a single module or you can build all the modules. If I want to build just a few modules, then there's no option for it. It'd be great if I can,
1. Specify a list of modules that I want to compile/build.
    e.g., `ballerina build foo bar baz`
2. Exclude one or more modules from compilation/build
    e.g., `ballerina build -x bar -x baz foo`

**Comment by azinneera** [comment]
With the introduction of Ballerina Packages, the unit of sharing/execution is the package, and hence building or running one or more modules is not allowed. The build command is updated in SL versions (from SLP8) to accept a package.

https://github.com/ballerina-platform/ballerina-spec/blob/master/project/proposals/packages/packages.md
