### ISSUE TITLE
Search Templates not working in Ballerina Central

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#19231]
**Description:**
The `Advanced Search` option in Ballerina Central does not filter out templates when the `Search Templates` tick is selected. Keywords option also does not seem to be working properly.

**Steps to reproduce:**
For instance, https://central.ballerina.io/search?org=wso2&module=&description=&keywords=&template=true does not filter out templates added by the wso2 organization.

**Affected Versions:**
Ballerina Central

**Suggested Assignees (optional):**
@hemikak

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2-enterprise/ballerina-central/issues/558 to track this Hence closing the issue
