### ISSUE TITLE
Type is not set correctly for StreamingJsonValue

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19230]
**Description:**
$title.

The array type should be `map<json>[]` - currently set as `json[]` - https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/values/StreamingJsonValue.java#L48

The type of each individual element should be `map<json>` - currently set as `json` https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableJSONDataSource.java#L99 - causes `foreach` to fail. May result in other failures too, once https://github.com/ballerina-platform/ballerina-lang/issues/19217 is fixed.

**Affected Versions:**
1.0.1

**Comment by vinok88** [comment]
@MaryamZi , in https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableJSONDataSource.java#L99 item is defined as  `new MapValueImpl<>(BTypes.typeJSON)`. IMO, this already implements a `map<json>`. Am I missing something here?

**Comment by MaryamZi** [comment]
> @MaryamZi , in https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/TableJSONDataSource.java#L99 item is defined as `new MapValueImpl<>(BTypes.typeJSON)`. IMO, this already implements a `map<json>`. Am I missing something here?

@vinok88 a map type needs to be set - `new BMapType(BTypes.typeJSON))` instead of `BTypes.typeJSON` since `BTypes.typeJSON` represents `json`, not just `map<json>`.
