### ISSUE TITLE
Desugar java interop code in jballerina side

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#19247]
**Description:**
The current implementation is customized for interop operations, instead, we can simply desugar that to normal function calls. (which will address all non-blocking and defaultable parameter passing issues)
This was done for extern functions already, need to do this for interop as well.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Added with #19667 and #19810
