### ISSUE TITLE
xmlns snippet invalid for attribute suggestion

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19259]
**Description:**
The `xmlns` snippet suggested for attributes is invalid.

Adds the following 
```ballerina
xml x = xml `<foo xmlns "" as ns;>hello world</foo>`;
```
whereas ideally only the `xmlns` keyword is required to do something like
```ballerina
xml x = xml `<foo xmlns:ns="http://abc.def">hello world</foo>`;
```

**Steps to reproduce:**
```ballerina
public function main() {
    xml x = xml `<foo xmln>hello world</foo>`; // accept xmlns here
}
```

**Affected Versions:**
1.0.0

**Comment by nadeeshaan** [comment]
This is a false positive we are having at the moment. Currently we do not have a way to identify that the cursor is within the xml. Will update the progress with the latest source pruner revamp
