### ISSUE TITLE
Rename typed binding pattern BBEs?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19258]
**Description:**
Currently
- Tuple Type Binding Pattern
- Record Type Binding Pattern
- Error Type Binding Pattern

Should we rename these to
- Tuple Type**d** Binding Pattern
- Record Type**d** Binding Pattern
- Error Type**d** Binding Pattern

**Comment by praneesha** [comment]
Adding @sameerajayasoma @shafreenAnfar @anupama-pathirage .

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/19431.
