### ISSUE TITLE
Ballerina project build fails, running with tests due to error in sql connector

### ISSUE THREAD

**Issue by Sithumini** [ballerina-platform/ballerina-lang#19267]
**Description:**
Ballerina project build fails, running with tests due to error in sql connector. Getting the below error trace when building the project with test running mode.
Note project builds successfully with --skip-tests option. 

```
fail] Error while initializing test suite: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to initialize pool: Communications link failure

The last packet successfully received from the server was 100 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.:Communications link failure

The last packet successfully received from the server was 100 milliseconds ago.  The last packet sent successfully to the server was 96 milliseconds ago.
        at ballerinax.java_jdbc:createClient(jdbc_client.bal:88)
           ballerinax.java_jdbc.Client:__init(client_endpoint.bal:27)
```

**Steps to reproduce:**
Build the project without --skip-tests option. 

**Affected Versions:**
Ballerina 1.0.0

**OS, DB, other environment details and versions:**
MacOS 10.14
mysql  Ver 14.14 Distrib 5.7.21
mysql-connector-java-8.0.17.jar

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Seems a related issue https://github.com/ballerina-platform/ballerina-lang/issues/19069
