### ISSUE TITLE
Return statement in if block is not honored when type checking union types

### ISSUE THREAD

**Issue by tharinduwijewardane** [ballerina-platform/ballerina-lang#19265]
**Description:**
```
string? name = getName(info);
if (name is ()) {
    return;
} 
someFuncAcceptsString(name);
```
Even though the above code is logically correct the compiler throws an error because the type of name is "string?". But the compiler recognizes that the "name" is a "string" if we use it inside an else block as follows.
```
string? name = getName(info);
if (name is ()) {
    return;
} else {
    someFuncAcceptsString(name);
}
```
As a result when we have multiple validations the happy-path code tends to move to a highly indented nested else block.

**Affected Versions:**
1.0.0

**Comment by MaryamZi** [comment]
The current behaviour is inline with what's defined in the 2019r3 spec.

Please see https://github.com/ballerina-platform/ballerina-spec/issues/73 for the spec issue regarding the same.

**Comment by hasithaa** [comment]
Resolving this issue, as this is expected behavior as per spec. This improvement already captured in https://github.com/ballerina-platform/ballerina-spec/issues/73
