### ISSUE TITLE
Compiler Plugin not invoked when resource does not have input parameters 

### ISSUE THREAD

**Issue by MalshaL** [ballerina-platform/ballerina-lang#19276]
**Description:**

For Ballerina FTP connector, I tried to create a compiler plugin to give an error when the input parameter is not mentioned in the resource as below:

**No compiler error scenario (1):**
```
service smbServerConnector on remoteServer {
    resource function onFileChange(WatchEvent event) {
         // resource def
    }
}
```

**Error scenario (2):**
```
service smbServerConnector on remoteServer {
    resource function onFileChange() {
        // resource def
    }
}
```

This should ideally give a `One parameter expected` error, but when compiling the code as in (2), the `init()` method is invoked but the [`process()`](https://github.com/wso2-ballerina/module-ftp/blob/master/ftp-compiler-plugin/src/main/java/org/wso2/ei/b7a/ftp/plugin/FTPCompilerPlugin.java#L62) method of the compiler plugin is not invoked. The service compiles and runs without showing a compilation error.

**Affected Versions:**
FTP, Samba and JMS Ballerina connectors in [wso2/ballerina](https://github.com/wso2-ballerina).

**Suggested Labels (optional):**
Component/Compiler, Priority/Blocker

**Comment by pubudu91** [comment]
This is probably the same issue as https://github.com/ballerina-platform/ballerina-lang/issues/19131
