### ISSUE TITLE
[Packerina Spec] Dependency jars getting packed to balo

### ISSUE THREAD

**Issue by ThishaniLucas** [ballerina-platform/ballerina-lang#19271]
**Description:**
When a jar file is used as a dependency in a Ballerina module (via platform.libraries in the toml), that jar is getting packed with the balo. If the jar is proprietary (eg : SAP JCO jars), it's illegal to re-distribute like this. If we don't add this under platform.libraries in toml, the building of the module fails with CLASS_NOT_FOUND, since there're inter-op methods. 

It's better if we can have an attribute like 'scope' under platform.libraries, so that the jars are used only in the compile time and not packed with the balo.

**Comment by hevayo** [comment]
This requirement here is to provide some additional jars to be packed with the final uber jar without packing them in to balo. The current spec do not support such a feature hence we will open a spec issue for this.

**Comment by hevayo** [comment]
Section copied from "New SQL Connector for Ballerina" Design doc 

**Managing** non-redistributable dependencies
Could we use hashes (e.g. SHA-1) for this (similar to how git works)? Scheme would be like this:

* Module declares that it has a non-redistributable dependency
* There is a entry on Ballerina central for that dependency that
    * has human-readable page on what it is and where to get it from
    * has SHA-1 hash of jar file(s) that can satisfy the dependency
* ballerina has command "lib"
    * takes jar file (or other binary asset) as argument computes the hash of the file and stores it in a library directory so it is accessible using the hash
* When running/compiling something that needs an external dependency
    * ballerina command knows for sure whether it has the needed dependencies based on hashes
    * if it doesn't, it can point the user to a link explaining what is needed
    * if it does, it can put the right file in the classpath/uber jar

**Comment by BuddhiWathsala** [comment]
@suganyasuven, I'm still getting this issue when I test it with Ballerina stdlibs. For example, I test this module https://github.com/ballerina-platform/module-ballerina-socket.

**What I did**

1. Build ballerina stdlib which is another ballerina project
2. Pack it to the ballerina final pack. But I do not pack the test utils since I use this `testOnly` scope
3. Then try to use it
The building was successful but in the runtime, it fails.

The configuration of the YAML file is as follows:

```toml
    [[platform.libraries]]
    artifactId = "socket"
    version = "@project.version@"
    path = "../socket-test-utils/build/libs/socket-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.socket"
    modules = ["socket"]
    scope = "test"
```
It throws the following error.

```
Generating executables
error: unable to create the executable: /Users/buddhi/Documents/MyWork/Ballerina/ballerina-distribution/ballerina/build/distributions/ballerina-macos-1.3.0-SNAPSHOT/distributions/jballerina-2.0.0-SNAPSHOT/bre/lib/socket-test-utils-2.0.1-SNAPSHOT.jar
```
