### ISSUE TITLE
.clone() completion suggestion should only appear to anydata

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#19284]
**Description:**
.clone() completion suggestion should only appear to anydata.

**Steps to reproduce:**
Below is not supported, but tooling suggests;

```ballerina
type Fruit object {};

public function main() {
    Fruit[] fruitArr1 = [];
    Fruit[] fruitArr2 = fruitArr1.<cursor>
}
```
**Affected Versions:**
1.0.1

**Comment by nadeeshaan** [comment]
Tried on top of 1.0.1 and when checked, clone() is not suggesting for the particular example. Will be closing the issue based on that and if the issue can reproduce further, please re-open
