### ISSUE TITLE
Add global variable table for jBallerina

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#19298]
**Description:**
We need the $title to implement global variables in debugger.

*Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
@warunalakshitha , shall we take this up?

**Comment by warunalakshitha** [comment]
This will be fixed with https://github.com/ballerina-platform/ballerina-lang/issues/19451 since now instead of id and var name will be added as fields to class. Those fields can be obtained by debugger api.
