### ISSUE TITLE
Http services hangs on to the connection even if a filter rejects the request.

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19292]
**Description:**
I observed that even if an filter attached to the Http listener reject the request, server still hangs on to the connection. 
say I have a custom authentication filter or anomaly ditection logic written in the filter I want the server to drop the connection.
In my opinion such behaviour from the server is permitted when we refer to following text in [2]  
> Note that a server might reject traffic that it deems abusive or characteristic of a denial-of-service attack, such as an excessive number of open connections from a single client.

[1] https://v1-0.ballerina.io/learn/by-example/http-filters.html
[2] https://tools.ietf.org/html/rfc7230
[3] https://en.wikipedia.org/wiki/HTTP_persistent_connection

Thoughts?

**Steps to reproduce:**
1)Implement a http-filter to return 'false' following the example in [1].
2) use curl to invoke the rest api.

**Affected Versions:**
1.0.1 / 1.0.0
**OS, DB, other environment details and versions:**
MacOS/ JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**

suggestion/improvement/idea

**Suggested Assignees (optional):**
@shafreenAnfar

**Comment by shafreenAnfar** [comment]
I checked the issue with @ramith and was able to sort it out. Following example worked as expected.

https://v1-0.ballerina.io/learn/by-example/http-filters.html

**Comment by wggihan** [comment]
The solution is provided hence close this.
