### ISSUE TITLE
User Defined HTTP Headers should not be promoted

### ISSUE THREAD

**Issue by FrankLeymann** [ballerina-platform/ballerina-lang#193]
The sample [StockExchangeRouterService](ballerina/samples/message_routing/header_based_routing/StockExchangeRouterService.bal) uses user defined HTTP headers to route based on them.  User defined HTTP headers are not appreciated in REST because they reduce "visibility" of messages.  Thus, we shouldn't use them in examples because this means that we are blessing them.

**Comment by uthaiyashankar** [comment]
Same issue is there in https://github.com/ballerina-lang/ballerina/blob/master/docs/ballerina-by-example/examples/header-based-routing/header-based-routing.bal

**Comment by afkham** [comment]
This is just an example which is demonstrating HBR, so I think we can close this issue. The RESTful resource may be the one to which the router is routing the request to. The router will be transparent in a RESTful interaction.
