### ISSUE TITLE
Cannot build when module depend on another module

### ISSUE THREAD

**Issue by hiranthaR** [ballerina-platform/ballerina-lang#19303]
[ball.zip](https://github.com/ballerina-platform/ballerina-lang/files/3692918/ball.zip)

**Description:**
I created 2 modules for ballerina central and when i try to use them, i got an compile error.I tried manually pull them and rebuild.then also got the error.
then i cleaned the caches in .ballerina and added my modules in dependencies section.then compiler pull them him self and again got fail.

```
[2019-10-04 10:12:28,581] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:51)
	at org.ballerinalang.packerina.writer.BirFileWriter.writeBIRToPath(BirFileWriter.java:100)
	at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:79)
	at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:84)
	at org.ballerinalang.packerina.task.CreateBirTask.execute(CreateBirTask.java:53)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:286)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
```
 
**Steps to reproduce:**

1- Create new project
2- Create a test module
3- import my modules in main (hirantha/firebase_core,hirantha/firebase_auth)
4- sample code
```ballerina
import ballerina/io;
import hirantha/firebase_auth as auth;
import hirantha/firebase_core as core;

# Prints `Hello World`.

public function main() {
    var firebaseapp = new core:Firebase({
        apiKey: "foo",
        authDomain: "foo",
        databaseURL: "foo",
        projectId: "foo",
        storageBucket: "foo",
        messagingSenderId: "foo",
        appId: "fooo"
    });
    if (firebaseapp is error) {
        io:println(firebaseapp.reason());
    }
    if (firebaseapp is core:Firebase) {
        auth:FirebaseAuth auth = new (firebaseapp);
        var res = auth.signUpWithEmailAndPassword("example@gmail.com", "123456S");
        io:println(res);
        io:println(firebaseapp.firebaseConfig);
    }

}

```
note:do not need real values.this should print FirebaseError

5- add them in dependencies
```
"hirantha/firebase_core"= "0.1.1"
"hirantha/firebase_auth"="0.1.2"
```
6. build and run.log will gengerate

**I found why this happens.firebase_auth module has dependency firebase_core.only the fireabse_auth is generating the error.** when i run only with core it works.then should be the import of core, in auth module is the generater of the error

simplly-
firebase_core - no error
normal project depend with core - no error
firebase auth depend with core - no error
normal project depend with core and auth - auth generate error

**Affected Versions:**
Ballerina 1.0.0

**OS, DB, other environment details and versions:**
Ubunutu 18.04

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
dependency error,

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Possibly the same issue as #19266

**Comment by hiranthaR** [comment]
> Possibly the same issue as #19266

yes I think too.I have attached zip for reproduce the error ayya.

**Comment by Kishanthan** [comment]
This should be fixed with #19334. Tried the attached project as well. It compiles fine.

**Comment by Kishanthan** [comment]
@hiranthaR , please verify with upcoming 1.0.2 release.

**Comment by hiranthaR** [comment]
> @hiranthaR , please verify with upcoming 1.0.2 release.

sure ayye i will

**Comment by hiranthaR** [comment]
> @hiranthaR , please verify with upcoming 1.0.2 release.

@Kishanthan  It worked ayya
