### ISSUE TITLE
Remove @test:Mock annotation

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#19307]
**Description:**
ATM, the mock functionality is not implemented. But the `@test:Mock` annotation is allowed. This results in giving irrelevant errors.

**Steps to reproduce:**
Try testing a program with following test bal.
`import ballerina/test;

any[] outputs = [];
int counter = 0;

// This is the mock function which will replace the real function
@test:Mock {
    moduleName: "ballerina/io",
    functionName: "println"
}
public function mockPrint(any... s) {
    outputs[counter] = s[0];
    counter += 1;
}

@test:Config{}
function testFunc() {
    // Invoking the main function
    main();
    test:assertEquals(outputs[0], "Hello, World!");
}`

It gives a test failure with error `{ballerina/lang.array}IndexOutOfRange message=array index out of range: index: 0, size: 0`
**Affected Versions:**
1.0, 1.0.1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
We will be fixing mock functions with https://github.com/ballerina-platform/ballerina-lang/issues/18780. Hence closing this issue
