### ISSUE TITLE
Need to update the description of the plugin in IntelliJ plugin marketplace

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19313]
Need to update the text in the plugin's page to align with the current messaging. 
![Screenshot from 2019-10-05 23-16-13](https://user-images.githubusercontent.com/6260009/66258740-6aa12f80-e7c6-11e9-87cb-1960929d400f.png)
The first sentence in particular, where it refers to Ballerina as a simple programming language.

**Comment by NipunaRanasinghe** [comment]
@pubudu91 +1 :)
 
Could you please be more specific with what you mean by current messaging? Are you suggesting what we have in the new website, which is `Ballerina is an open source programming language and platform for cloud-era application programmers to easily write software that just works.
` ?

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with #19500
