### ISSUE TITLE
Issue in resetting the type for type narrowed variables

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19312]
**Description:**
I'm trying to figure out why following code fragment never compiles:
```ballerina
public type XYZ record {
    string x;
    string y;
    int z;
};

function sample() returns XYZ | error {

    XYZ | error sampleValue = {x: "X", y :"Y", z: 1 };

    if ( sampleValue is XYZ) {
        if (isZpositive(sampleValue)){
            sampleValue = error("this line compiles");
        } else if isXNotEmpty(sampleValue) {
              sampleValue = error("above line never compiles");
        } else if isYEmpty(sampleValue) {
              sampleValue = error("above line never compiles");
        }
    }

    return sampleValue;
}

function isZpositive(XYZ xyz) returns boolean {
    return xyz.z > 0;
}
function isXNotEmpty(XYZ xyz) returns boolean {
    return xyz.x.length() > 0;
}

function isYEmpty(XYZ xyz) returns boolean {
    return xyz.y.length() == 0;
}
```

**Steps to reproduce:**
Copy and paste above code fragment on a .bal file  and see compile error in IntelliJ 
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
Mac OS, JDK 1.8

**Suggested Assignees (optional):**
@MaryamZi

**Comment by MaryamZi** [comment]
The errors here are "incompatible types: expected 'XYZ', found '(XYZ|error)'", because the `sampleValue` variable's type is no longer the narrowed type once it is assigned to.

This is in-line with the spec 
```
the narrowed type for a variable x no longer applies as soon as there is a 
possibility of x being assigned to
```

This is to avoid scenarios such as the following
```ballerina
function sample() returns XYZ | error {

    XYZ | error sampleValue = {x: "X", y :"Y", z: 1 };

    if (sampleValue is XYZ) {
        if (isZpositive(sampleValue)){
            sampleValue = error("this line compiles");
        } 
        
        // `sampleValue` is assigned to within the previous if block.
        // so it could even be an `error` now.
        // Type narrowing should no longer apply.
        if isXNotEmpty(sampleValue) {
            sampleValue = error("above line never compiles");
        }
    }

    return sampleValue;
}
```


But yeah, in your example, this might not make sense since the if-else-if blocks are mutually exclusive.

This could be an improvement to type narrowing.

**Comment by a5anka** [comment]
> The errors here are "incompatible types: expected 'XYZ', found '(XYZ|error)'", because the `sampleValue` variable's type is no longer the narrowed type once it is assigned to.
> 
> This is in-line with the spec
> 
> ```
> the narrowed type for a variable x no longer applies as soon as there is a 
> possibility of x being assigned to
> ```

Hmm. I don't think the behavior we see is in line with the spec. What @ramith has used is an if-else-if block. Therefore there is no logical path that could do the assignment to sampleValue and execute `isXNotEmpty(sampleValue)`. Therefore "there is no possibility of x being assigned to". 

> 
> This is to avoid scenarios such as the following
> 
> ```ballerina
> function sample() returns XYZ | error {
> 
>     XYZ | error sampleValue = {x: "X", y :"Y", z: 1 };
> 
>     if (sampleValue is XYZ) {
>         if (isZpositive(sampleValue)){
>             sampleValue = error("this line compiles");
>         } 
>         
>         // `sampleValue` is assigned to within the previous if block.
>         // so it could even be an `error` now.
>         // Type narrowing should no longer apply.
>         if isXNotEmpty(sampleValue) {
>             sampleValue = error("above line never compiles");
>         }
>     }
> 
>     return sampleValue;
> }
> ```
> 
> But yeah, in your example, this might not make sense since the if-else-if blocks are mutually exclusive.
> 
> This could be an improvement to type narrowing.

**Comment by MaryamZi** [comment]
@a5anka - sorry, what I meant was that resetting of the type could happen. Like I said, agreed that the current behaviour for @ramith's example doesn't seem to make sense.

All, this does not work even for the following scenario atm,

```ballerina
public function main() {
    string|int val = "hello";

    if (val is string) {
        if (false) {
            string s = val;
            val = 1;
        } else {
            foo(val); // incompatible types: expected 'string', found '(string|int)'
        }
    } else {
        int i = val;
    }
}

function foo(string s) {
}
```

We recursively reset the type for the applicable previous environments once a variable is assigned to. Thus resetting it for `if (val is string) {}` seems to apply to the inner else block too.

We may have to revisit the concept of regions of code and how we've modeled it for type narrowing alongside the spec - see https://v1-0.ballerina.io/spec/lang/v2019R3/#section_7.11.

Design doc for type narrowing - https://docs.google.com/document/d/12stYd4PWSK3yauFdcvueOju2BkF0krWbYtJA6DvTqKw/edit
