### ISSUE TITLE
Windows tests failures in jballerina-integration-tests module

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#19310]
**Description:**
please refer following build scan.
https://scans.gradle.com/s/qzivs3c3twlfw/tests/failed

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
The http tests are failing, hence assigning stdlib folks

**Comment by chamil321** [comment]
The failed HTTP test cases are outdated and no longer maintained in the repo. Hence closing the issue. 

PS: Existing windows test failures are captured via [these issues](https://github.com/ballerina-platform/ballerina-standard-library/issues?q=is%3Aopen+is%3Aissue+label%3Amodule%2Fhttp+windows+tests)
