### ISSUE TITLE
Include a summary for Module.md generated by Ballerina Add

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#19324]
**Description:**
Include a summary for Module.md generated by Ballerina Add

**Steps to reproduce:**
Execute `Ballerina add` command and generated module has following content. 

```
# Hello World

Prints "hello world" to command line output
```

**Affected Versions:**
1.0.1

**Comment by praneesha** [comment]
This is added now as shown below.

<img width="1440" alt="Screenshot 2020-10-09 at 13 45 23" src="https://user-images.githubusercontent.com/11707273/95559749-e1a28100-0a35-11eb-80a5-402c189fe98d.png">
