### ISSUE TITLE
[Proposal] Ballerina Compiler Plugin Architecture

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#19325]
# Ballerina Compiler Plugins

Ballerina Compiler provides an event-based extension mechanism, that allows developers to write custom plugins to the Ballerina compiler. A Compiler plugin could be used to do the following.

- Add extra compile-time checks. 
- Provide customized analysis of source code
- Generate artifacts based on source code.

A Ballerina Compiler plugin is a ballerina module, which implements the Compiler plugin SPI. Usually, these modules available at Ballerina central. 

The initial version of the compiler plugin architecture versioned as v0.5. With the introduction of new compiler plugin architecture, it depreciates the existing native (java based) compiler plugins. 

## Plugin SPI

Plugin SPI contains two parts,
- Annotations
- Plugin Implementation.

A Plugin should define a set of non-source annotations, that plugin needs to be engaged on annotation attachment on a node. 

A plugin implementation is a ballerina object that implements `ballerina/compiler.plugin:spi` abstract object. (Details TBD)

`SupportedAnnotation` (Details TBD) annotation can be used to define which annotation needs to be processed using the plugin.

Compiler Plugin SPI has the following behavior.
- A plugin can support only annotations defined with in the same module.
- A plugin can support multiple annotations.
- A module can have multiple plugins.

## Compiler Events

Compiler Plugins are engaged in mainly two different phases
- After successful completion of the Semantic & Code analysis phase:
    In this phase, the Compiler generates events for selected AST nodes, which attached to a registered annotation. Two sperate events generated to mark the start and the end of this phase.
- After the successful completion of code generation:
   Developers can use this phase to create artifacts.

## Plugin Installation

There is no installation step. However, the developer must explicitly enable compiler plugins using `ballerina ext` command. 

Ballerina ext command provides the following subcommands.
- `enable <module-name>`: Enable plugins in the given module.
- `disable <module-name>`: Disable plugins in the given module.
- `list`: List all enabled plugins

Once module plugins are enabled, they are enabled globally for all module versions. Mostly used compiler plugins (i.e., http, docker, k8s) enabled by default.

The following example explains the development flow.

1) Assume module `myorg/mymod` version 1 has a compiler plugin, which registered to `Foo` Annotation. 
    source.bal 
  ```ballerina
import myorg/mymod;

@mymod:Foo {
    name : ""
}
service on new mymod:Listener () {
 ...
}
  ```

2) Then, the developer builds the ballerina source, without enabling plugins in `myorg/mymod`. Compilation continues with a warning. 
  ```
$ ballerina build myproj
Compiling myproj.

Warning...! Compiler plugins in module 'myorg/mymod' are not enabled.
Semantics for the following annotations will not work as expected.  
        - myorg/mymod:Foo

Generating artifacts myproj
  ```
3) Now developer enables compiler plugin using `ballerina ext` command.
  ```
# installing myorg/mymod compiler plugins.
$ballerina ext enable myorg/mymod

# list installed compiler plugins
$ ballerina ext list

ballerina/http
ballerina/ws
ballerina/docker
ballerina/Kubernetes
myorg/mymod
  ```
4) Now developer rebuilds the same project. Now Compiler plugin runs.

```
$ ballerina build myproj
Compiling myproj.
Compilation contains error:
error: source.bal:4:5 : name can't be empty. 
```

## AST support.

In the initial implementation, the AST model is immutable and supports a minimal set of nodes. Initially, it supports the following module-level declaration.

- import-decl
- listener-decl
- service-decl
- function-defn
- module-type-defn
- annotation-decl

Further, implementation adds support for the following type-descriptors and expressions.

- object-type-descriptor
- service-constructor-expr

AST model available at `ballerina/compiler.ast`. 

## Compiler APIs

The initial implementation provides basic APIs to interact with the native compiler. This API includes the following APIs.  

### Compiler Context API

Compiler Context API provides information about compilation. i.e., Project name, target folder path. This API is available at `ballerina/compiler.context`.

### Diagnostic API

Diagnostic API provides functionality for logging diagnostics. (info, warn, error) This API is available at `ballerina/compiler.diagnostic`.

**Comment by jclark** [comment]
Should a project be able to indicate which plugins it requires?

**Comment by hasithaa** [comment]
> Should a project be able to indicate which plugins it requires?

Yes, it is handled using module import. Only plugins that in imported modules will engage during the compilation time. However,  the user has to enable plugin modules using explicitly using `ballerina ext` command. As an alternative, we can use `ballerina.toml` file to enable plugins per project.

**Comment by jclark** [comment]
I think the toml project file should be able to enable particular plugins. For many scenarios, I think there will be some plugins that should always be enabled for a project.

**Comment by hasithaa** [comment]
> I think the toml project file should be able to enable particular plugins. 
Yes, I also think it will be useful for many cases. 

> For many scenarios, I think there will be some plugins that should always be enabled for a project.

Even with the current architecture, plugin engagement is explicit. A user has to use annotations. But I agree there can be an advanced scenario, where the user has to engage some plugins always. But being explicit about the plugin engagement is good IMO. So same code will produce the same compilation behavior in different environments. 
This discussion raises the question of what is the best place to enable the particular plugin; globally or per project. IMO, the project is the best place to mentioned enabled plugins.

**Comment by sanjiva** [comment]
Few small comments:
- `ballerina/compiler.plugin:spi` should be `ballerina/compiler.plugin:SPI` probably?
- if the AST is immutable that will restrict the plugins a lot .. for e.g. I can't add a K8s health method automatically
- if we call these after semantic analysis then are you saying a plugin can't do sem analysis? Or that a plugin only adds to the built in sem analysis and so runs after?
- I don't like the "ballerina ext" approach .. IMO we should recognize compiler plugins as standard concepts and not extensions. In that case it would be:
`ballerina plugin list | add | remove ...`. And `plugin list` will list out built-in plugins too.
- I agree that we will probably need a way to list plugins in the TOML - otherwise building a shared module without extra instructions could be come impossible.

**Comment by hasithaa** [comment]
@sanjiva 
> Few small comments:
> 
> * `ballerina/compiler.plugin:spi` should be `ballerina/compiler.plugin:SPI` probably?

Yes, Sorry, it should be SPI. 

> * if the AST is immutable that will restrict the plugins a lot .. for e.g. I can't add a K8s health method automatically

Yes, it is the ideal thing to do, but there are several reasons behind making AST is immutable. 
- If AST is mutable, then type checking has to be re-run against modified AST for the correctness.
- If a compiler plugin modifies the AST, changes are not visible to the user.
- To modify the AST, the plugin developer requires to learn how the compiler works, how type checking works, AST structure, etc. This involves a lot of learning.

But there is an alternative solution, by keeping AST immutable. That is, to let the compiler generates code to a target/generated-code directory and make it part of the module. A similar mechanism is used by Java Compiler plugin too.

Having mutable meta-data (Annotation attachment, documentations, etc.) is useful in some cases. So we can make them mutable. 

> * if we call these after semantic analysis then are you saying a plugin can't do sem analysis? Or that a plugin only adds to the built in sem analysis and so runs after?

It is the latter case; Plugin can do semantic analysis after the built-in semantic analysis completes. The reason behind doing this is, the AST must have information like types, constants, and symbols, etc., before running plugins.

> * I don't like the "ballerina ext" approach .. IMO we should recognize compiler plugins as standard concepts and not extensions. In that case it would be:
>   `ballerina plugin list | add | remove ...`. And `plugin list` will list out built-in plugins too.
> * I agree that we will probably need a way to list plugins in the TOML - otherwise building a shared module without extra instructions could be come impossible.

Ack. We need to figure out details on this, will schedule a meeting on this.

**Comment by hasithaa** [comment]
This proposal is a bit old. @sameerajayasoma is working on a new proposal, hence closing this issue.
