### ISSUE TITLE
Type not reset for destructuring assignment within a type guard

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19352]
**Description:**
```ballerina
function foo() returns [string?, int] {
    return [(),1];
}

function bar() returns [string?, int] {
    return [(),1];
}
public function main() {

    var [str, num] = foo();
    if ( str is string){
        [str, num] = bar();// This line never compiles 
    }
}
```
**Steps to reproduce:**
compile above progrAM
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
MacOs, JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**
**Suggested Assignees (optional):**
@Rajith90 @MaryamZi

**Comment by MaryamZi** [comment]
The compilation error here is 
"incompatible types: expected '[string,int]', found '[string?,int]'".

The type does not seem to be reset when assigning to destructured variables within a typeguard.

Fails for record destructure too

```ballerina
function foo() returns record { string? s; int i; } {
    return { s: (), i: 1 };
}

function bar() returns record { string? s; int i; } {
    return { s: (), i: 2 };
}

public function main() {

    var { s, i }  = foo();
    if (s is string) {
        { s, i } = bar(); // incompatible types: expected 'string', found 'string?'
    }
}
```

**Comment by MaryamZi** [comment]
Moving this issue to the minor release since fixing this could break existing code.
