### ISSUE TITLE
Use simple foreach instead of unnecessary streamed foreach in build tasks

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#19353]
**Description:**
There are few build tasks (eg : BTestRunner.java) that uses streamed foreach which is unnecessary. This has to be improved to use simple foreach.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sprinkle24** [comment]
I can work on this
