### ISSUE TITLE
Dump the content of ballerina-internal.log during an error

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19367]
**Description:**
Could we have at least a command-line switch to have 
1) not create ballerina-internal.log
2) dump it's content to sysout

Rationale is it's not straightforward to read this file when ballerina crashes in a containerized envirnments and makes the users/devOps life painful.

This is a blocker for us.

**Steps to reproduce:**

**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
Kubernetes, AWS, JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**
Blocker
**Suggested Assignees (optional):**
@sameerajayasoma @hasithaa

**Comment by vinok88** [comment]
How about you configure your Dockerfile to echo the content of the internal.log if there is an error exit?
This crash log is intended for internal users, it contains java stack traces, hence it's not good to dump it to console.
Maybe we can include this option via our default docker template. WDYT?

**Comment by ramith** [comment]
@vinok88 we ended up with a similar approach. but like I explained it spoils the user experience.

**Comment by warunalakshitha** [comment]
Now crash logs are dump into sysout with https://github.com/ballerina-platform/ballerina-lang/pull/31109
