### ISSUE TITLE
Securing the /metric endpoint

### ISSUE THREAD

**Issue by ShanJayaweera** [ballerina-platform/ballerina-lang#19378]
**Description:**
The default port which we use to publish metric data is not a secured port. Hope it should be secured at least by using BasicAuth or by using a token. Otherwise, if some external authority uses this observability feature they will face a problem with their security. 

**Steps to reproduce:**

**Affected Versions:**
all

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
Prometheus supports Authorization using both basic auth and bearer token. However, the endpoint exposed in Ballerina isn't secured. So, what you can do is, simply wrap the  `/metric` endpoint with another service, which supports basic auth or bearer token, and then use that with Prometheus. Finally, you can manually block access (i.e using a firewall)  to the default `/metric` endpoint from outside.
