### ISSUE TITLE
java.io.tmpdir directory does not get created for "ballerina docker" command. (remove the entry)

### ISSUE THREAD

**Issue by sajhak** [ballerina-platform/ballerina-lang#1937]
Following property is defined in bin/ballerina script
     -Djava.io.tmpdir="$BALLERINA_HOME/tmp" \
But "$BALLERINA_HOME/tmp" directory gets created only at "ballerina service" command.
For container support commands we are using /tmp directory and that directory does not get created for the "ballerina docker" command, hence giving an exception. (Since that property is defined, Java detects the $BALLERINA_HOME/tmp as the temp directory and since its not available, it throws an exception )

As discussed offline, since tmp directory is not used for ballerina runtime,  -Djava.io.tmpdir="$BALLERINA_HOME/tmp" \ entry need to be removed from /bin/ballerina script.

**Comment by samisawso2** [comment]
"ballerina docker" is deprecated now.  Docker is an annotation. Need to check if this issue still there with new model.

**Comment by afkham** [comment]
With the latest k8s stuff and so on, this is no longer an issue.

**Comment by lakwarus** [comment]
Yes. we are no longer use $BALLERINA_HOME/tmp. We can close this issue
