### ISSUE TITLE
getting 95% percentile for the Ballerina Observability.

### ISSUE THREAD

**Issue by ShanJayaweera** [ballerina-platform/ballerina-lang#19371]
**Description:**
For the ballerina observability section, there are APIs to collect data. Gauge-Based Metrics play a major role in there as it can store a single numerical value that can arbitrarily go up and down, and also based on the statistics configurations provided to the Gauge, it can also report the statistics such as max, min, mean, percentiles, etc. For the default configurations this calculates percentiles for 33% 50% 66% 99% and for 99.9%. But it will be more useful if it can also return the 95% percentile also as it is statistically more important for certain types of decision making.

**Steps to reproduce:**

**Affected Versions:**
for all

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/19379
