### ISSUE TITLE
Debug logs are visible in tracing tool although they are not enabled

### ISSUE THREAD

**Issue by ShanJayaweera** [ballerina-platform/ballerina-lang#19375]
**Description:**
We use Debug logs to track events that occur in the project. Although we haven't enabled the debug mode, those debug logs are visible in the tracing tool when we enabled the configurations for tracing. 

![Screenshot from 2019-10-14 10-49-13](https://user-images.githubusercontent.com/51467737/66730629-91b7cb00-ee70-11e9-8de3-9a1e5c0b4387.png)

![Screenshot from 2019-10-14 10-51-16](https://user-images.githubusercontent.com/51467737/66730615-7ea4fb00-ee70-11e9-9e5a-149ca16750c5.png)

**Steps to reproduce:**

**Affected Versions:**
all

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/19406
