### ISSUE TITLE
Issue in giving [b7a.observability] configurations in a .TOML file

### ISSUE THREAD

**Issue by ShanJayaweera** [ballerina-platform/ballerina-lang#19373]
**Description:**
I m using ballerina's default observability configurations to observe the performance of my project. If we use the flag "--b7a.observability.enabled=true" it enables both metric and tracing default configurations. But if we use the same configurations and pass them by a .toml file observability will not get enabled.

![Screenshot from 2019-10-14 10-26-54](https://user-images.githubusercontent.com/51467737/66730144-55cf3680-ee6d-11e9-8696-a5d1b2bc8f5f.png)

But if we enable the metric and tracing seperately it will enable the observability default configuration.

![Screenshot from 2019-10-14 10-27-11](https://user-images.githubusercontent.com/51467737/66730163-8911c580-ee6d-11e9-8738-1d0ceb21feea.png)

**Steps to reproduce:**

**Affected Versions:**
all

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/19398
