### ISSUE TITLE
Text auto format wrongly formats <@untainted <type>>

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#19380]
**Description:**
IntelliJ IDEA wrongly formats `<@untainted `*`<type_name>`*`>` when trying to auto format the code.

**Steps to reproduce:**

Try to auto-format the following code snippet in IntelliJ:

```ballerina
public function main() {
    string text = "Sample String";
    int number = 34;
    string anotherText = <@untainted string>text;
    int anotherNumber = <@untainted int>number;
}
```

This will remove the space between `@untainted` and the `string`. It also removes the space between `@untainted` and the `int`.

**Affected Versions:**
* Ballerina 1.0.1
* IntelliJ Plugin 1.0.1
* IntelliJ IDEA (Community Edition) 2019.2.3

**OS, DB, other environment details and versions:**

* OS: MacOS Catalina

**Comment by NipunaMarcus** [comment]
Issue has been fixed with above PR.
