### ISSUE TITLE
XML namespace declarations should be in scope only in the source part in which they occur, as with import declarations.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#19384]
**Description:**
$subject.

Similar to import statements, xml namespace declarations are scoped to file.

Refer https://github.com/ballerina-platform/ballerina-spec/commit/47c67eeeb3825ed8732709bcf9f75224cc40346d in the spec

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
closed this in #21343
