### ISSUE TITLE
Comply Source code Lexical structure with Spec 2019R3

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#19381]
Spec says following.

> 
> After the sequence of octets is decoded from UTF-8, the following two transformations must be performed before it is parsed using the grammar in this document:
> 
> - if the sequence starts with a byte order mark (code point 0xFEFF), it must be removed
> - newlines are normalized as follows:
>   - the two character sequence 0xD 0xA is replaced by 0xA
>   - a single 0xD character that is not followed by 0xD is replaced by 0xA
> 
> The sequence of code points must not contain any of the following disallowed code points:
> 
> - surrogates (0xD800 to 0xDFFF)
> - non-characters (the 66 code points that Unicode designates as non-characters)
> - C0 control characters (0x0 to 0x1F and 0x1F) other than whitespace (0x9, 0xA, 0xC, 0xD)
> - C1 control characters (0x80 to 0x9F)
> 

This has to be fixed in both compiler (parser) and tools (like formatter) etc.

**Comment by hasithaa** [comment]
@NipunaMarcus Please note.

**Comment by NipunaMarcus** [comment]
@hasithaa will check the formatter for possible failure ...

**Comment by hasithaa** [comment]
We have fixed this with the new parser implementation. @lochana-chathura @rdulmina Please create new issues, if there any spec deviations.
