### ISSUE TITLE
Enable all tests for streams module

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#19403]
**Description:**
Some tests were disabled in 8b1e0c021229cabf0b8cbf47128d52193489516b. Need to enable them after properly fixing them.

**Comment by gimantha** [comment]
Tests hangs in windows build only. Also they pass when the tests are run from streams modules in all builds.

**Comment by hasithaa** [comment]
Resolving since we have removed old stream implementation with https://github.com/ballerina-platform/ballerina-lang/pull/20663
