### ISSUE TITLE
Suggestion to improve `jdbc:Parameter` to detect errors at compile time

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#19404]
**Description:**
Currently the `jdbc:Parameter` record is defined as follows

```ballerina
public type Parameter record {|
    SQLType sqlType;
    anydata value = ();
    Direction direction = DIRECTION_IN;
    typedesc<record{}> recordType?;
|};
```

If a user defines a `Parameter` value with a mismatch between the `sqlType` and the `value`, this would result in a runtime error.

e.g., `TYPE_INTEGER` as `sqlType` and a string as `value`

Instead we can combine `sqlType` and `value` to define a finite type, which will validate at compile time the allowed values.

Just as an example

```ballerina
public type Parameter record {|
    Value value;
    Direction direction = DIRECTION_IN;
    typedesc<record{}> recordType?;
|};

public type Value [TYPE_VARCHAR, string]|[TYPE_INTEGER, int]; // and so on

public function main() {
    Parameter param = {
        value: [TYPE_INTEGER, "not an int"] // would now fail at compile time
    };
}
```

@anupama-pathirage, @Manuri FYI, as discussed offline.

**Comment by daneshk** [comment]
@niveathika please check whether this is still valid in new SQL syntax

**Comment by niveathika** [comment]
@MaryamZi, @daneshk 
This is not valid in the new design. Since we have introduced subtypes for variable types which indicates the SQL data type as below, https://ballerina.io/swan-lake/learn/api-docs/ballerina/sql/index.html#objects
