### ISSUE TITLE
JDBC Module API docs exposes private functions and types

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#19447]
**Description:**
$subject for

-  JDBC Client object `JdbcClient client object `
- Close function `function close(JdbcClient jdbcClient) returns error? = external;`
- Global pool container `type GlobalPoolConfigContainer object`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Closing this since this issue seems to be fixed in 1.0.2 by PR #19446
