### ISSUE TITLE
Initializing a project in an existing directory

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19449]
The option you have for creating projects is `ballerina new`. However, this command doesn't allow initializing a project in an already existing directory. For example, I created a new directory manually and wanted to initialize a new Ballerina project in it. The CLI complains saying the directory already exists.
```
$ ballerina new 18449
ballerina: destination '/home/pubudu/testing/ballerina/issues/18449' already exists

USAGE:
    ballerina new <project-name>

For more information try --help
```
Wouldn't it be better if the user is warned that the specified directory already exists and whether the user wants to proceed or not and prompt the user to enter yes or no?

**Comment by Dilhasha** [comment]
This feature is supported now.
