### ISSUE TITLE
Tries to resolve non-standrad packages from ~/.ballerina/repo folder

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#19444]
**Description:**
When resolving non-standard Modules are resolved from the ~/.ballerina/repo before ~/.ballerina/balo_cache folder. The ~/.ballerina/repo folder shouldn't be considered when resolving modules.

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.0.1
Language specification 2019R3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Fixed with mentioned PR.
