### ISSUE TITLE
Unable to see the error in IntelliJ

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19461]
**Description:**
Please refer to the screenshot I was writing following code in IntelliJ 
```ballerina
   http:Response response = new;
            response.statusCode = http:STATUS_OK;
            _ = outboundEp->respond(response);

```
I get an error meeesage (as shown in screen shot) which  I can't read. 
Moreover the tool tip flickers when I slightly move the time mouse pointer.

**Steps to reproduce:**
explained above 
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
Mac OS, IntelliJ Idea
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@hevayo 
<img width="1680" alt="bug" src="https://user-images.githubusercontent.com/3402882/67068010-34848800-f196-11e9-9f14-e17ec29c8bd5.png">
<img width="634" alt="IntelliJ-version-info" src="https://user-images.githubusercontent.com/3402882/67068011-351d1e80-f196-11e9-8262-a2c6f7f30c4c.png">

**Comment by NipunaRanasinghe** [comment]
Closing this as this is fixed after migrating to the latest language client version, which includes few hover related enhancements.
