### ISSUE TITLE
Langlib string.length() does not return number of codepoints

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#19466]
**Description:**
It should return number of codepoints but at the moment it returns java's string.length()

**Steps to reproduce:**

**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
@manuranga, With your string refactoring, will this issue be resolved?

**Comment by hasithaa** [comment]
@manuranga Can we resolve this issue ?

**Comment by manuranga** [comment]
Yes, this is fixed with BString migration.
