### ISSUE TITLE
Information captured in the ballerina-internal.log is not sufficient

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19460]
When the compiler/runtime crashes, the ballerina-internal.log will contain a log of the exception with its stack trace. In the case of the compiler, this stack trace is pretty much useless on its own to figure out what went wrong. You can only get an idea of what sort of thing might have gone wrong, but you can't really tell which part in the user's source code caused the exception, nor do you have the state of the relevant context. It would be much more useful if we can capture the portion of source code which caused the exception, and maybe even the state info of the relevant objects (e.g., the symbols, types, nodes).

Currently, we have to get the user's source code and compile it and debug to find out the issue.

**Comment by SupunS** [comment]
If the runtime crashes, the ballerina-internal.log it will contain the stacktrace of the user's code. Wouldn't that be sufficient? During runtime, the source code is also not available.

**Comment by Shan1024** [comment]
I think what @pubudu91 meant was a Memory/Heap Dump kind of functionality where it would contain detail of symbols, etc help to recreate the scenario without the user code. We would often see this kind of dump/output when applications crash. This kind of functionality will help to recreate the scenario and fix bugs faster because the language developers don't have to wait until the users provide the source code.

**Comment by pubudu91** [comment]
I'm not sure about the runtime side, hence why I only mentioned the compiler in the above description. Labelled as JBallerina as well since the ballerina-internal.log is used by the runtime as well. 

And yes, @Shan1024 is correct. I meant we need to capture the contextual details related to that particular crash. Otherwise, the ballerina-internal.log is not exactly useful. We've run into situations where we tried to reproduce a particular crash by writing a simpler version of the portion which led the program to crash, but it didn't crash. It turned out that the crash was due to an issue with something else (e.g., incorrectly read config, issues in a particular type of DB). It would be really time consuming to be recreating these exact environments to debug the issue, and as @Shan1024 mentioned, we often end up asking the user for the project itself.

**Comment by SupunS** [comment]
Im trying to understand what is actually need from the runtime perspective.

Ballerina-runtime crashes are only possible if theres a bug in the runtime (VM) code (for example a NPE, IndexOutOfBound, etc). To identify these we need the stack-trace and the source code. If the VM ran into a memory related issue like an OOM, then the heap-dump will get created anyway by the JVM, I believe.

So whats missing is any context information, such as a dump of the current strand. It will contain all the runtime data, including the values of the variables in the current context. But those can contain user sensitive data (even passwords), so we can't persist or dump such data.

**Comment by hasithaa** [comment]
Not planning to fix it in Swan Lake.
