### ISSUE TITLE
Getting error: 2049 when building Ballerina Module

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#19470]
**Description:**
When I try to build the Ballerina module named "issuer" located in ([blockchain-iam-group-chat.zip](https://github.com/ballerina-platform/ballerina-lang/files/3716150/blockchain-iam-group-chat.zip)) I get an error message "2049" and the compiler terminates without proceeding further.

```
miyurud@miyurud:~/git/blockchain-iam-group-chat$ ballerina build issuer
Compiling source
	wso2/issuer:0.1.0
error: 2049
```

**Steps to reproduce:**
Download and extract the attached zip file ([blockchain-iam-group-chat.zip](https://github.com/ballerina-platform/ballerina-lang/files/3716150/blockchain-iam-group-chat.zip)) , change directory to "blockchain-iam-group-chat" folder, and issue `ballerina build issuer`. You may also have to change the path of the platform.libraries entry of the Ballerina.toml file to match with your environment. The corresponding "utils.jar" is located on the directory "utils-dir".

**Affected Versions:**
Ballerina 1.0.2-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 16.04
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
There seems to be an issue with the existing cached wso2/etherum BIR file. Removing that from cache will solve this. Can you remove that file which should be under - 
/Users/<HOME>/.ballerina/bir_cache/wso2/ethereum

**Comment by miyurud** [comment]
Thanks. After removing the existing cached wso2/ethereum BIR file the module was built successfully.
