### ISSUE TITLE
Need to give a proper error message when incompatible Ballerina modules are used

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19484]
Currently, if an incompatible binary is imported and used, the compiler crashes. Instead, we should have a mechanism for detecting whether the imported binary was compiled using a compatible Ballerina version and if not, give a proper compile error and exit.

**Comment by hasithaa** [comment]
@pubudu91 Can you verify whether this is still valid? This should be fixed with 1.1.x versions.

**Comment by hevayo** [comment]
Not relevant any more

**Comment by pubudu91** [comment]
Yes, this is not applicable anymore. Currently it's giving the following error:
```
error: failed to load the module 'ballerina/io:0.6.0-beta.1' from its BIR due to: unsupported program file version 60
```
This is good enough for now.
