### ISSUE TITLE
Missing Artifacts or development docs

### ISSUE THREAD

**Issue by RobRMackay** [ballerina-platform/ballerina-lang#19488]
**Description:**
Attempting to build a java native extension to Ballerina 1.0.1
Instructions from last year detail using Maven Plugin 
org.ballerinalang.codegen.BallerinaAnnotationProcessor
But cannot find any artifact containing that class or package in Maven Central

Could not find artifact org.ballerinalang:ballerina-lang:pom:1.0.1 in central (https://repo.maven.apache.org/maven2)

**Steps to reproduce:**
Build a maven based jar project for Ballerina

**Affected Versions:**
1.x.x
**OS, DB, other environment details and versions:**
Mac/Linux

**Related Issues (optional):**

I can't tell if I am just missing the latest doc on how to develop in Java or if there is something wrong with the maven deployments. 

Mvnrepository shows all the ballerina artifacts but none are usable or found in the actual repo.

Is there a separate WS02 or Ballerina repository I should setup ?

**Suggested Labels (optional):**

Java, JAR, Annotations, POM

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
You don't need to use MavenPlugin now. We have introduced the Java Interoperability feature which allows you to easily integrate ballerina programs with java libraries. 
Please refer to the [Ballerina by example](https://v1-0.ballerina.io/learn/by-example/) on Java Interoperability. 
I agree that there should be documentation on native extension development. Will work on that.

However, FYI, we do push our artifacts to the Maven Central after every release.

**Comment by praneesha** [comment]
As per [1], Java interoperability docs are in [2] and we need to add [3] to cover information on pushing a native library to Ballerina Central.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/17756
[2] https://v1-0-0-alpha.ballerina.io/learn/by-example/create-java-objects.html
[3] https://docs.google.com/document/d/1ljdeKI6IrTmxi5jKNgd8aNbLW4w-KSd8DwEHQOndmWs/edit#heading=h.re44vh45id9m

**Comment by IrushiL** [comment]
The complete guide on calling Java code from Ballerina can be found here [1]. This includes a section on **Packaging Java Libraries with Ballerina Programs** as well.

[1] https://ballerina.io/learn/calling-java-code-from-ballerina/
