### ISSUE TITLE
Inaccurate  max/min aggregators implementations in stdlib streams 

### ISSUE THREAD

**Issue by chethiya** [ballerina-platform/ballerina-lang#19483]
**Description:**
Intended algorithm doesn't work accurately the way items are removed currently from the sorted linked list when "EXPIRED" events are fired.

For instance current implementation produces incorrect output for following input:

```
Stream of numbers: 2, 3, 2, 1, 1
Moving window length: 3
Expected output:   2, 3, 3, 3, 2
Returned output:   2, 3, 3, 3, 1
```

Test program can be found here: https://github.com/chethiya/ballerina-lang/commit/441e273788f571d367b3a662d06edd16cd5716c9#diff-a56f53b60b17792644f6159d87be1e73

Suggested fix - https://github.com/chethiya/ballerina-lang/commit/441e273788f571d367b3a662d06edd16cd5716c9

_Note: Also note that the intended algorithm works only when the "EXPIRED" events are fired in the same order as the "CURRENT" events were fired for same the values. So I assume that gurantee is there when process() function is called in the Max class._

I'll send the pull request later on, if I get a change to build it and test.

BTW I noticed there is another interesting issue with this implementation. When float values are searched to be removed, it does that by comparing for equality of floats.
i.e.
```
                    float a = <float>self.fMaxQueue.next();
                    if (a == value) {
                        self.fMaxQueue.removeCurrent();
                    }
```

Not sure how reliable float equality comparison in this case. Therefore this can potentially make current implementation inaccurate!

In Ballerina, if assigning a float to another float variable (which seems to be triggered by `event.copy()`) guarantees having the same binary representation, then this might be okay. Not sure how ballerian works when it comes to float assigns.

If that's not the case then probably an event ID needs to be stored together with the value as the linked list items, and do the comparios using the event ID instead of value.

I'm not sure how easy it's to do that given the function signature` public function process(anydata value, EventType eventType) returns anydata`
**Steps to reproduce:**
See above

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
Hi @chethiya Thank you for reporting the issue and providing the fix, we will fix it ASAP.

**Comment by chethiya** [comment]
@gimantha not sure whether the solution I provided above is the correct one given the above mentioned problem with float equality comparison. 

At least it won't work when values are `NaN`. i.e. `NaN==NaN`is `false`. Anyway `NaN` can be handled separately by not considering it for max and min. 

Not sure about other cases though, have to look how float assignment/copy works at language core.

**Comment by hasithaa** [comment]
@mohanvive, Can you have a look into this. ?

**Comment by mohanvive** [comment]
Stream processing implementation was an experimental feature in 1.x.x release. We have identified some limitations/bugs in it and it is removed in the latest Swan Lake release. We are planning to redesign the stream processing feature in early next year. We'll consider the above feedback for that. 

I am closing the issue for now since it is no longer valid for latest Swan Lake release.
