### ISSUE TITLE
Can't add template to project

### ISSUE THREAD

**Issue by markokocic** [ballerina-platform/ballerina-lang#19511]
**Description:**
Tried to add a template to project as explained in Quick start guide

**Steps to reproduce:**
ballerina new quick-start-guide
// success
ballerina pull wso2/healthcare_service  
//success
ballerina add -t wso2/healthcare_service healthcare_service 
// error
// ballerina: Oh no, something really went wrong. Bad. Sad.

**Affected Versions:**
1.0.1

**OS, DB, other environment details and versions:**
Windows 10 x64

**Additional Info
Similar error when calling:
ballerina add --list

Attached log file.
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3751834/ballerina-internal.log)

**Comment by MaryamZi** [comment]
Probably the same issue as https://github.com/ballerina-platform/ballerina-lang/issues/19337 which seems to have been fixed for the upcoming release. 

Tagging @hevayo, @hemikak for confirmation.

**Comment by hemikak** [comment]
Yes, this is the same issue mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/19337. This will be fixed in the next patch release as https://github.com/ballerina-platform/ballerina-lang/pull/19366 PR is merged.

**Comment by hemikak** [comment]
Hence closing.

**Comment by ahmedamer85** [comment]
Guys i am getting the same issue, how can i fix it (I just installed Visual Studio Cod with Ballerina extension yesterday)
