### ISSUE TITLE
Error calling ballerina without arguments

### ISSUE THREAD

**Issue by markokocic** [ballerina-platform/ballerina-lang#19512]
**Description:**
Seems like ballerina commands require at least one argument. It fails when invoked without arguments. I would expect that it displays usage information when invoked without arguments

**Steps to reproduce:**
C:\Users\Marko>ballerina
"if" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

**Affected Versions:**
1.0.1

**OS, DB, other environment details and versions:**
Windows 10 x64

**Comment by keizer619** [comment]
I was trying to reproduce same issue in my windows machine. i just "ballerina" in the cmd and go the help message as expected as follows

<img width="491" alt="Screen Shot 2019-11-29 at 2 52 12 PM" src="https://user-images.githubusercontent.com/2918812/69858418-f6f83c00-12b7-11ea-991b-a0cf59ac0b99.png">

**Comment by Shan1024** [comment]
@keizer619 you provided the `-v` argument 😅

**Comment by keizer619** [comment]
@Shan1024 first command is with -v to show the version. 2nd command with without -v, right?

**Comment by hevayo** [comment]
We are unable to reproduce this with SL beta1 please re-open if you came across this issue again.
