### ISSUE TITLE
Suggestion: Ability to attach @resources to a service

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19523]
**Description:**
It would be nice to do a variation of following code fragment.
```
serviceBuilder.when("GET","sample input").respond("sampleOutput")
	        .when("POST", "sample input").respond("sample Output")
	        .when("HEAD", inputProviderFunction()).respond(outputProviderFunction());
service myService = serviceBuilder.build();

http:Listener server = new (9091);
server.__attach(myService, "MyService");
server.__start();
```

If I can do above that mean I can write mock services every easy for my unit tests.
@lankavitharana suggest a similar approach can be done tests requiring a data bases.

**Steps to reproduce:**
N/A
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
MacOS, JDK 1.8
**Related Issues (optional):**
**Suggested Labels (optional):**
Improvement
**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This is not a language feature, but rather specific to service connectors. @shafreenAnfar is this make sense to move this under the http module? If not we will close the issue.

**Comment by hasithaa** [comment]
Closing this issue, due to inactivity.

**Comment by ramith** [comment]
so having such a functionality doesn't help writing testcases? @shafreenAnfar
