### ISSUE TITLE
Improvement to data flow analysis and test automation

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19522]
**Description:**
```ballerina
@test:Config {}
function testFuntion() {
    http:Client endpoint = new("http://localhost:9091");
    http:Response | http:ClientError result = endpoint->get("/sample/resource");
    test:assertTrue(result is http:Response, "received an error response from the service");
    http:Response response = <http:Response> result; // <-- It would be nice, not having to do this.
    test:assertEquals(response.getTextPayload(), "some text", "Invalid text received from the service");
}
```

In above I believe `http:Response response = <http:Response> result` is redundant.
**Steps to reproduce:**
N/A
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
MacOS, JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**
Improvement
**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
There are improvements to type narrowing in the language with Swan Lake Beta4 which addresses this issue. Please refer https://ballerina.io/downloads/swan-lake-release-notes/swan-lake-beta4/#type-narrowing-following-an-if-statement-without-an-else-block-if-the-if-statement-block-cannot-complete-normally

**Comment by azinneera** [comment]
The code can be improved as following:
```
@test:Config {}
function testFuntion() returns error? {
    http:Client endpoint = check new("http://localhost:9091");
    http:Response result = check endpoint->get("/sample/resource");
    test:assertTrue(result is http:Response, "received an error response from the service");
    test:assertEquals(result.getTextPayload(), "some text", "Invalid text received from the service");
}
```
