### ISSUE TITLE
Difficulty resolving local module

### ISSUE THREAD

**Issue by RobRMackay** [ballerina-platform/ballerina-lang#19578]
**Description:**
Creating two seperate modules, 1 child, 1 parent, importing the child into the parent, when building module cannot be resolved.

**Steps to reproduce:**
Create new app
_______________________________

```bash
ballerina add Address
```

Add this `schema.bal`

```ballerina
public type Address record { 
    string postal;
    string country;
};
```
______________________________

```bash
ballerina add Contact
```
add this `schema.bal`

```ballerina
import Address;
public type Contact record { 
    string Name;
    Address address;
};
```

---------------------------

```bash
ballerina build Contact
Compiling source
   builder/Contact:0.1.0
error: builder/Contact:0.1.0::schema.bal:4:5: unknown type 'Address'
```

**Affected Versions:**
Building with 1.0.1
**OS, DB, other environment details and versions:**
MAC OS, typical environment
**Related Issues (optional):**
Generating from the openapi cli command 

**Suggested Labels (optional):**
Local Modules,  import Modules, hierarchy of modules

**Comment by SupunS** [comment]
You have to use the package-qualified name when accessing a type coming from an imported module.
eg:
```ballerina
import Address;

public type Contact record { 
    string Name;
    Address:Address address;
};
```

Also since you are having both the package name and the type name as `Address` (and `Contact`), I would suggest to change the package name to a different one, to avoid any confusion. Something like:

```ballerina
import adrs;

public type Contact record { 
    string Name;
    adrs:Address address;
};
```

**Comment by RobRMackay** [comment]
Excellent
  Thanks for the fast response, the Ballerina team is great.
