### ISSUE TITLE
Cannot execute a ballerina test file without a ballerina project

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#19579]
**Description:**
Before 1.x.x it was possible to run a ballerina test by invoking the file directly as `ballerina test tests.bal` without having to create a ballerina project. Ballerina 1.x.x does not seem to have this support. Is it possible to add this back? 

**Suggested Labels (optional):**
Improvement

**Comment by Dilhasha** [comment]
@Ibaqu @azinneera 
This is the same issue as in https://github.com/ballerina-platform/ballerina-lang/issues/20885 right? Shall we close this?

**Comment by Dilhasha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/issues/20885
