### ISSUE TITLE
Error declaring/using map type

### ISSUE THREAD

**Issue by knightbeat** [ballerina-platform/ballerina-lang#19596]
**Description:**
Errors when running the example of Map type in [https://ballerina.io/learn/by-example/maps.html](https://ballerina.io/learn/by-example/maps.html)
    

> Compiling source
> 	test.bal
>     error: .::test.bal:11:27: invalid operation: type 'map' does not support field access
>     error: .::test.bal:14:5: invalid operation: type 'map' does not support field access
>     error: .::test.bal:18:25: incompatible types: expected 'boolean', found 'any'
>     error: .::test.bal:22:20: invalid operation: type 'map<string>' does not support field access

**Steps to reproduce:**

1. Copy the source code given on [https://ballerina.io/learn/by-example/maps.html](https://ballerina.io/learn/by-example/maps.html)
2. Create a new *.bal file with it
3. Run it using `ballerina run *.bal`

**Affected Versions:**
Version 1.0.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This unfortunately seems to be an issue with the site. It seems to be linking to an old version of the example. The example is up-to-date in 1.0.1 - https://github.com/ballerina-platform/ballerina-lang/blob/v1.0.1/examples/maps/maps.bal

**Comment by pubudu91** [comment]
@knightbeat This is fixed now. Can you check and verify?

**Comment by knightbeat** [comment]
@pubudu91 Yes, the doc has been updated correctly. Thank you.
