### ISSUE TITLE
No BBE for table remove operation.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#19592]
**Description:**
$subject.

The table BBE [1] does not contains the details about the table remove operation,.
[1] https://v1-0.ballerina.io/learn/by-example/table.html

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via [1].

[1] https://github.com/ballerina-platform/ballerina-lang/pull/19593
