### ISSUE TITLE
Following code doesn't compile (Unable to create services dynamically)

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19608]
**Description:**
Consider following ballerina code:
```ballerina

function build(string resourcePath) returns service {
        return @http:ServiceConfig {
            basePath: serviceBuilder().basePath
        }
        service {
            @http:ResourceConfig {
                path: resourcePath // <--- This line doesn't compile
            }
            resource function myResource(http:Caller outboundEp, http:Request req) returns error? {
            }
        };
    }
```
So the underlying problem is annotation related to `service` can't be specified at runtime (which seems to be the only way to create a service at the moment).
if above looks weird, why not expose an separate API to create services.
suggestion:
```

resource resource1 = resourcebuilder().methods(http:HTTP_GET, http:HTTP_POST)).produces(mime:MIME_APPLICATION_JSON).body(myfunction).build();

service myservice = servicebuilder().name("myservice").basepath("/myservice").resource(resouce1).resource(anotherResource).build();
```
**Steps to reproduce:**

Put above code fragment in an IDE and check

**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
blocker ( <- the code we wrote to workaround this is issue looks super weird! and we don't want to write such code)
**Suggested Assignees (optional):**
@chamil321

**Comment by hasithaa** [comment]
It seems like there is no workaround with the current implementation.

**Comment by hasithaa** [comment]
Duplicates https://github.com/ballerina-platform/ballerina-lang/issues/9144

**Comment by hasithaa** [comment]
Duplicates #9144
