### ISSUE TITLE
Invalid retry count results in cascading errors

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19614]
Consider the following example, with an invalid retry count.
```ballerina
function functionWithATransactionStmt() returns string {
    string ss = " in func";

    transaction with retries = "2" {
        ss += " in-trx";
    } onretry {
        ss += " retry-func-trx";
    } committed {
        ss += " committed-fun-trx";
    }

    ss += " after-fun-trx";
    return ss;
}
```
When compiling the above code, two compile errors are given. 
```
error: .::transaction.bal:8:32: incompatible types: expected 'int', found 'string'
error: .::transaction.bal:8:32: invalid transaction retry count
```
The first error alone is enough in this case. The check at https://github.com/ballerina-platform/ballerina-lang/blob/4968ce1d65dc6a7222cb34f43378b31f0db10aea/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java#L2299 seems redundant now, with the type checking done in the previous line.

**Comment by hasithaa** [comment]
Closing this issue. This has been removed with New Transaction design in SL.
