### ISSUE TITLE
Need to analyze and support the taint flow from panic and checkpanic when the error is tainted

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#19613]
**Description:**
$subject.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
We will consider this after SL.

**Comment by hasithaa** [comment]
We are removing the Current taint analysis implementation with #30981, Hence closing this issue.
