### ISSUE TITLE
Fix Formatting in Displaying Lists in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#19616]
**Description:**
There is a formatting issue as shown below in displaying the list in [1], which is displayed properly in [2].

<img width="1263" alt="Screenshot 2019-10-28 at 14 47 14" src="https://user-images.githubusercontent.com/11707273/67666529-fce5bf00-f991-11e9-8a72-dd428bbeef8a.png">

<img width="974" alt="proper" src="https://user-images.githubusercontent.com/11707273/67666541-02dba000-f992-11e9-96af-70a34b5b7803.png">

[1] https://ballerina.io/learn/api-docs/ballerina/io/index.html
[2] https://ballerina.io/learn/api-docs/ballerina/io/functions.html#sprintf

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Need to verify the fix.

**Comment by praneesha** [comment]
Closing since this has been verified when sending the PR.

**Comment by praneesha** [comment]
Reopening as this is not fixed yet. Now, the list is not rendered at all in the index page[1] as shown below.

<img width="1673" alt="Screenshot 2020-04-19 at 00 56 25" src="https://user-images.githubusercontent.com/11707273/79669392-c66a5d80-81d8-11ea-9532-f397e3113b0c.png">

[1] https://ballerina.io/learn/api-docs/ballerina/io/index.html

**Comment by shehan360** [comment]
> Reopening as this is not fixed yet. Now, the list is not rendered at all in the index page[1] as shown below.
> 
> <img alt="Screenshot 2020-04-19 at 00 56 25" width="1673" src="https://user-images.githubusercontent.com/11707273/79669392-c66a5d80-81d8-11ea-9532-f397e3113b0c.png">
> 
> [1] https://ballerina.io/learn/api-docs/ballerina/io/index.html

This is due to a new logic introduced in 1.2.2 release to limit the descriptions in tables to first sentence only. This was introduced as there were some formatting issues due to descriptions containing code snippets.

However, the above is only applicable for the 1.2.2 branch and is fixed on the master branch.
![Capture](https://user-images.githubusercontent.com/33398983/79683074-1848cd00-8245-11ea-9d4c-f38a78704064.PNG)

**Comment by praneesha** [comment]
Closing as per the above comment.
