### ISSUE TITLE
Need a way to invoke a java function which accepts an enum value

### ISSUE THREAD

**Issue by tharinduwijewardane** [ballerina-platform/ballerina-lang#19629]
**Description:**
At the moment we cannot invoke a java function which accept an enum value as a parameter.

**Steps to reproduce:**

**Affected Versions:**
1.0.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Java Interoperability 
Feature request

**Suggested Assignees (optional):**
@Kishanthan

**Comment by Kishanthan** [comment]
Can you try as follows to use enums? The example used here is TimeUnit#MILLISECONDS. Enums are basically static fields in the class so we can access it using field access approach with java interop.

```ballerina

public function getMillisTimeUnit() returns handle = @java:FieldGet {
    class: "java.util.concurrent.TimeUnit",
    name: "MILLISECONDS"
} external;

public function waitFor(handle receive, int timeout, handle timeUnit) returns boolean = @java:Method {
    class: "java.lang.Process"
} external;
```
