### ISSUE TITLE
Ballerina executable jar creates internal jars with type inflated

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#19639]
**Description:**
Some of the external jars we add in the Ballerina.toml file may contains set of jar files inside its lib folder. But once this jar is included in the executable jar using ballerina build the JarEntry.getMethod() returns the jars inside the lib folder as deflated, even though still they are compressed jars. I think we need to handle this case when building the self executable jar.

**Steps to reproduce:**

**Affected Versions:**
1.0.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
This was due to limitation in java 8 where ZIPFileSystem default using DEFLATED method to compress so even STORED method jars are compress with DEFLATED method. Works well with java 11 after passing no compression flag but java 8 does not support it.
