### ISSUE TITLE
404 when trying to open learn more page for debugger limitations

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#19633]
<img width="279" alt="Screen Shot 2019-10-29 at 12 57 00 PM" src="https://user-images.githubusercontent.com/1505855/67746018-9d4bea00-fa4b-11e9-9176-1535fa1ee883.png">

https://ballerina.io/learn/tools-ides/vscode-plugin/run-and-debug/

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
