### ISSUE TITLE
Need of an API Documentation for Ballerina Central

### ISSUE THREAD

**Issue by SabinaPrasadhi** [ballerina-platform/ballerina-lang#19647]
**Description:**
I faced some difficulty, to find out information about the Ballerina API in order to pull a module published in the ballerina central according to the user specification provided in the OpenAPI Definition.

**Steps to reproduce:**

**Affected Versions:**
Ballerina version 1.0.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-lang/issues/8535.

**Comment by hemikak** [comment]
Please find the OpenAPI specification attached. This is not publicly available yet -https://github.com/wso2-enterprise/ballerina-registry/blob/1.1.0-update/src/registry_module_api/resources/openapi/ballerina-registry-openapi-spec.yml

[ballerina-registry-openapi-spec.txt](https://github.com/ballerina-platform/ballerina-lang/files/4107595/ballerina-registry-openapi-spec.txt)
