### ISSUE TITLE
XML namespaces changes

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#19669]
**Description:**
Namespace support in the compiler and runtime

- Xml text to string (implicit conversion)
- Serialization

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21343
