### ISSUE TITLE
Implement XML Parser and node tree

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#19668]
**Description:**
Parse xml into an in-memory tree

- Tree design
- Parser impl (Stax?)

Refer xml proposal https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Issue is continued and fixed in https://github.com/ballerina-platform/ballerina-lang/issues/19832
