### ISSUE TITLE
Uninitialized var detection fails with while

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#19679]
Consider the following code.

```ballerina
import ballerina/io;

public function main(string... args) {

    int a;
    boolean e = true;
    while(e) {
        if (e) {
            break;
        } else {
            a = 5;
        }
    }
    io:println(a);
}
```
Affected version 1.0

at the point where a is printed, a is not yet initialized, hence should give a compilation error. But this prints 0, which is not the correct behavior

**Comment by gimantha** [comment]
@hasithaa this produces a wrong answer, hence can be moved to patch compatible, but this breaks existing code.. so moved it to minor compatible

**Comment by MaryamZi** [comment]
This is an issue with while in general. Even the following doesn't fail atm.

```ballerina

public function main(string... args) {
    int a;
    boolean e = true;
    while(e) {
        if (e) {
            a = 1;
        } else {
            a = 5;
        }
    }
    int j = a; // may be uninitialized
}
```
