### ISSUE TITLE
[Kafka] Add Kafka Avro support for Kafka library

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#19695]
**Description:**
Apache Avro is widely used for data serialization. Avro is used in Kafka due to its fast serializing. 

Currently we only support default byte array serializer for Kafka messages. We do not provide a way to developers to add different serializers. This should be added.

**Comment by nirmal070125** [comment]
Hi Team, 

When are we planning to implement the Avro message support?

**Comment by ThisaruGuruge** [comment]
Hi Nirmal,

Sorry for the later response. Currently, there's an [ongoing discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/4hZQXlo5EIo/jhHuvyYvDAAJ) about this.
Will update soon about the progress.

**Comment by IainAdamsLabs** [comment]
Any news on this topic? I need to use AVRO with Kafka.

**Comment by ThisaruGuruge** [comment]
Hi guys, this is currently on hold, due to priorities. Will update soon about the matter.
