### ISSUE TITLE
Title of the tabs shows "null/<module_name>" in the stdlib module API docs 

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#19696]
**Description:**
Safari Tabs shows API Documentation page title as null/<module_name>.

To reproduce, open two tabs in safari, and open an API documentation page of a stdlib module. This is how it looks:
<img width="844" alt="64609267-3b2b1d00-d3ea-11e9-8972-a9b5af36df1e" src="https://user-images.githubusercontent.com/11707273/68010839-ab984100-fcab-11e9-8fd0-43c2baf3d5aa.png">

The original issue is [1].

[1] https://github.com/ballerina-platform/ballerina-www/issues/1597
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Is this a Docerina issue?

**Comment by praneesha** [comment]
Closing since this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/61.
