### ISSUE TITLE
Match statement - something went wrong

### ISSUE THREAD

**Issue by hrennau** [ballerina-platform/ballerina-lang#19720]
**Description:**
Match statement triggered "ballerina: Oh no, something really went wrong. Bad. Sad."

**Steps to reproduce:**
Code:
``` ballerina
import ballerina/io;

public function main() {
    map<anydata> r = {x: "abc", y:1};
    demomatch(r);
}

public function demomatch(anydata v) {
    match v {
        {yin: _, yim: _} => {io:println("yin yim");}
        var z => {io:println("Default branch");}
    }
}
```
Log: see attachment
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3799889/ballerina-internal.log)

**Comment by gimantha** [comment]
I changed the line `map r = {x: "abc", y:1};` to `map<anydata> r = {x: "abc", y:1};`, hence the former case is not allowed in 1.0. Still the issue can be reproduced

**Comment by MaryamZi** [comment]
This produces a "pattern will not be matched" error on sl-alpha1 for `{yin: _, yim: _}`.

**Comment by KavinduZoysa** [comment]
The issue is fixed in PR https://github.com/ballerina-platform/ballerina-lang/pull/28215
