### ISSUE TITLE
Method call on parenthesized expression

### ISSUE THREAD

**Issue by hrennau** [ballerina-platform/ballerina-lang#19731]
**Description:**
The expression
   ("abc").length()

causes a compiler error message. Is this a parser error, or do I misread the spec?

As the static type of
   ("abc")

is string, a call of function length() from library lang.string is expected (per 6.20 Method call expression). The expression
   "abc".length()

on the other hand, works as expected.

**Steps to reproduce:**
Complete source code:

import ballerina/io;
public function main() {
    var len = ("abc").length();
    io:println("len: ", len);
}

**Comment by MaryamZi** [comment]
@hrennau yes this should work, but I'm afraid the implementation does not support this at the moment.

Closing this issue since it is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/19020. Please do reopen if you have further concerns.
