### ISSUE TITLE
Match statement production - correct?

### ISSUE THREAD

**Issue by hrennau** [ballerina-platform/ballerina-lang#19743]
**Description:**
If I read the production match-pattern correctly, the following match-pattern would be valid:
{x: "abc", y: var y}

In particular, I refer to:

match-pattern := var binding-pattern | ... | mapping-match-pattern | ...
mapping-match-pattern := { field-match-patterns }
field-match-patterns := field-match-pattern (, field-match-pattern)* [, rest-match-pattern] | ...
field-match-pattern := field-name : match-pattern

However, running the code triggers error messages:
error: .::match_experiment_01.bal:20:23: invalid token 'var'
error: .::match_experiment_01.bal:20:23: extraneous input 'var'

Version info:
Ballerina 1.0.0
Language specification 2019R3

**Comment by hasithaa** [comment]
Duplicates #https://github.com/ballerina-platform/ballerina-lang/issues/15962

**Comment by hasithaa** [comment]
Duplicates #15962, Hence resolving this issue. Please track progress here #15962.
