### ISSUE TITLE
Error when using field access for parenthesised expression

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#19759]
```
import ballerina/io;

type recordType record {|
    string name;
    int age;
|};

public function main() {
    recordType|() value = {name:"ballerina", age:3};
    
    io:println((<recordType>recordValue).name); //Fails
}
```
In the above example it is not possible to  directly use the type-casted value. According to the spec, this should be possible since, `(` expression `).` field-name is a valid expression. 

Versions affected : 
Ballerina 1.0.2
Language specification 2019R3

**Comment by MaryamZi** [comment]
Yes, this should be possible, but this is not yet supported by the implementation.

Closing this issue since the same is being tracked by https://github.com/ballerina-platform/ballerina-lang/issues/19020.
