### ISSUE TITLE
Find and fix bugs in java interop

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#19757]
**Description:**
The current implementation has some suspicious points(marked with TODOs) which may lead to bugs in interop, analyze those locations and fix them(include tests as well)

**Comment by SupunS** [comment]
All the identified bugs were fixed and the TODOs in the interop gen methods were addressed with #20097. 

Needs to cleanup the cast methods added for interop (jvm_cast_gen.bal)

**Comment by Kishanthan** [comment]
Closing as bugs identified previously and TODOs are removed.
