### ISSUE TITLE
Cleanup Variable references for function pointers in desugar

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#19760]
When the SimpleVarRefs are properly desugared, there should **not** be FunctionVarRefs. Right now we create invokableSymbols without incorrect SymTags and that leads to create FunctionVarRefs in Desugar and NPE in BIROptimizer. A function pointer has to be desugared into a Local variable reference (BLangLocalVarRef)

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
