### ISSUE TITLE
Support for incremental build process

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#19782]
**Description:**
Currently in a multi-module Ballerina project if we update only one module (or subset of modules) we have to build all the modules again. It is because there is no way in current Ballerina distribution to build only that updated module(s) rather than rebuilding the entire project. It consumes lot of time for developing such multi-module projects because of having to rebuild the entire project from the scratch.

For example, in a project having four Ballerina modules (chat, holder, issuer, and webserver) we can build the complete project as follows. Here the '--skip-tests' flag is used to skip tests.

`ballerina build --skip-tests -a`

This results in four jar files in the target/bin folder. However, later if we modify only webserver module and try to build only that updated module as,

`ballerina build --skip-tests webserver`

this deletes the jar files of the other three modules from the target/bin directory. We can find only a single jar named as webserver.jar at the end of the execution of above command inside the target/bin folder. It may be nice to have the compiler to conduct incremental build process so that it does not require to rebuild all the four modules in such situation. Similarly it might be good to have the feature to build a subset of modules (for example 2 out of 4 in the above example) by issuing a build command as follows,

`ballerina build --skip-tests issuer webserver`

**Steps to reproduce:**
N/A

**Affected Versions:**
Ballerina 1.0.3

**OS, DB, other environment details and versions:**
N/A

**Comment by Ibaqu** [comment]
Closing since Per-module compilation is not supported in swan-lake
