### ISSUE TITLE
BBE for RabbitMQ Client

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#19786]
Subject

**Comment by aashikam** [comment]
Hi @sameerajayasoma, we already have around 7 BBEs for the RabbitMQ client. I have added a few links below. Is there any specific use case you're looking for?
https://github.com/ballerina-platform/ballerina-lang/tree/master/examples/rabbitmq-consumer-with-client-acknowledgement
https://github.com/ballerina-platform/ballerina-lang/tree/master/examples/rabbitmq-consumer-with-data-binding
https://github.com/ballerina-platform/ballerina-lang/tree/master/examples/rabbitmq-consumer-with-qos-settings
