### ISSUE TITLE
Enabling connection timeouts in ballerina gRPC

### ISSUE THREAD

**Issue by 7slcode7** [ballerina-platform/ballerina-lang#19791]
**Description:**

Is there a possibility to enable connection timeouts in gRPC ballerina client ?
According to below page we can enable it using Java.
[https://grpc.io/blog/deadlines/](url)

**Comment by daneshk** [comment]
In Ballerina, we can enable connection timeout in client configuration which is default set to 60000 milliseconds. This is just an HTTP timeout. This not serves the deadline requirement in gRPC.

We already have an open issue #10959 to enable deadline support in gRPC. We will enable deadline support as soon as possible.

**Comment by daneshk** [comment]
Closing this issue since this is duplicate with the issue #10959. We will keep updating the requirement in the issue #10959.
