### ISSUE TITLE
[Docerina] Need to Make the Type Field Public in Lang Library Modules

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#19799]
**Description:**
We need to make the "Detail" variable public in the file of each lang lib module (as applicable) as follows to display the error detail in API docs. 

<img width="1221" alt="Screenshot 2019-11-06 at 14 58 13" src="https://user-images.githubusercontent.com/11707273/68285764-e2a09500-00a5-11ea-9b5d-5c1f440cbe57.png">

```
@typeParam
type Type any|error;
```

Currently, "Type" is a broken link, which gives a 404 error.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
`Type` is purposely on private. Making them public is not the correct way to handle this. @kaviththiranga Shall we have a chat on how to handle this in API doc generation.

**Comment by praneesha** [comment]
As discussed with @kaviththiranga and @hasithaa we need to handle this from the API doc generation tool (by removing the links when a reference is not found).
