### ISSUE TITLE
Printing a table from select query returns a null when passed to json utils

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#19809]
**Description:**
When the return value of a select statement is printed before passing to the `jsonutils:fromTable` function the `fromTable` function returns empty object.

**Steps to reproduce:**
Print a  return value of a select statement (possibly using a for loop) then pass to the `jsonutils:fromTable` function and then print the result. The result is always an empty object.

**Affected Versions:**
1.0.2
**OS, DB, other environment details and versions:**
Mysql 8.0.17

**Comment by wggihan** [comment]
This is an expected behavior. Table paramerter that pass to fromTable function is an database pointer. So once you consume it there will be no records available. So this is not a bug.
