### ISSUE TITLE
Re-enable support for using mapping constructors with record binding patterns

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#19804]
Support for using record binding patterns with mapping constructors was removed with https://github.com/ballerina-platform/ballerina-lang/pull/11053/commits/009046794e35f5ea8ab3c986176b2248734be762

Need  to re-enable this. I had a quick look at this, with the check added here to disable the support removed. It seems to be working. Need to test more and re-enable.

**Comment by dulajdilshan** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/40283/ only enables destructuring assignments.
