### ISSUE TITLE
VS code fails to format jvm codegen module ballerina code

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#19812]
**Description:**
Cannot use format functionality with jvm codegen module

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This issue is resolved, with the latest implementation of the formatter and the earlier implementation was blocked due to the compiler usage of the language server. Hence closing the issue
