### ISSUE TITLE
[IntelliJ Plugin] Invalid brace pairs are matched for string template expressions

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#19831]
**Description:**
Please refer the sample code below. Closing brace of the first expression inside the string template is matched with the opening brace of the main function.

![Screenshot from 2019-11-08 10-30-57](https://user-images.githubusercontent.com/29032600/68451023-1fd66580-0213-11ea-9e2c-adabfde6f387.png)

**Steps to reproduce:**
Use the above sample and move the cursor to the closing brace of the first expression inside the string template or the opening brace of the main function.

**Affected Versions:**
IDEA plugin version - 1.0.3 and below

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Closing this since this seems to have been fixed by #19831
