### ISSUE TITLE
->select not returning connections to the Hikari pool.

### ISSUE THREAD

**Issue by RobRMackay** [ballerina-platform/ballerina-lang#19856]
**Description:**
failed to execute select query: error while getting the connection for ClientConnector. HikariPool-1 - Connection is not available, request timed out after 30013ms.

My select call against a database table was working recently, now it returns nothing, an object that is of the right table type but nothing in it and no error.

->update functions working for insert, update and delete 

[address.zip](https://github.com/ballerina-platform/ballerina-lang/files/3838896/address.zip)

behaves the same regardless if running from ballerina run command or java -jar

Change pool size from 5 to 10 connections, no data returned, ran out of connections when I reached 10 requests - same Hikari error. Evidence suggests that connections not being returned to the pool, am I missing some new pool config parameters ?

jdbc:Client dbClient = new({
     url: dbUrl, username: username, password: password, 
     poolOptions: { maximumPoolSize: poolsize }
});

**Steps to reproduce:**
This function fails to return any data, does not return an error, it essentially returns nothing.

function selectAddressRecord(int id)  returns  @tainted  json {
table<addressRecord>|error addrtn = dbClient->select("select * from address ", addressRecord);
		if (addrtn is table<addressRecord>) {
		    io:println("Returning  data: ");
		 }else {
			 io:println("Not Returning  data rtn was not a table ");
		 }
}

The log output shows **"Returning data:"** - but nothing is returned. 

Seems to be pool related: I have 5 connections configured in the pool and after 5 requests have been made to select from the table I receive the following error:

error {ballerinax/java.jdbc}DatabaseError sqlState= message=failed to execute select query: error while getting the connection for ClientConnector. HikariPool-1 - Connection is not available, request timed out after 30013ms.. sqlErrorCode=0
**Not Returning  data rtn was not a table**

Select failed: failed to execute select query: error while getting the connection for ClientConnector. HikariPool-1 - Connection is not available, request timed out after 30013ms..
2019-11-12 17:59:51,187 INFO  [address] - failed to execute select query: error while getting the connection for ClientConnector. HikariPool-1 - Connection is not available, request timed out after 30013ms

I ran the POST operation and inserted records 20 times in a row.

**Affected Versions:**
Ballerina 1.0.3

java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

**OS, DB, other environment details and versions:**
Mac OS 10.15
Postgres DB running in docker
postgresql-4.2.2.8.jar driver

**Suggested Labels (optional):**
Hikari Pool,. ballerinax/java.jdbc,  HikariPool-1, select query

**Comment by anupama-pathirage** [comment]
In ballerina, the tables returned from the database will have a physical DB connection associated with that.  That connection will get released only after the table data is fully used or table is closed. 

In ballerina, the tables returned from the database will get closed automatically only if you have consumed the data.  That means either you have to 
- iterate the table fully using foreach or while loop
- convert to json or xml and consume that payload in client-side

If none of the above is doing (i.e. if you are partially iterating the table or not using the table at all) , you have to close it explicitly using the close function as follows.

```ballerina
tableValue.close() ;
```


By looking at your code it seems following code is doing the data select from db.

```ballerina
function selectaddressRecord(int id)  returns  @tainted  json{
string querystr = "SELECT  id, street1, street2, unitnumber, city, state, postal, country  FROM address  WHERE id = ?";
          json rtnStr = {};
        io:println(querystr.toString());
        table<addressRecord>|error rtn = dbClient->select("select * from address ;", addressRecord);
        io:println(rtn.toString());

        if (rtn is table<addressRecord>) {
           rtnStr = rtn.toString();
                    io:println(rtn);
            io:println("Returning  data: ");
            io:println(rtnStr);
         }else {
             io:println("Not Returning  data rtn was not a table ");
         }

        if(rtn is jdbc:ApplicationError || rtn is jdbc:DatabaseError){
            error err = rtn;
            io:println("Insert failed: ", <string> err.detail()["message"]);
          rtnStr = <string> err.detail()["message"];
           }
     return rtnStr;
}

```

It seems your json conversion is incorrect in this case. That’s why the table is not fully consumed and the associated db connection remains as it has not closed in any of the above-mentioned ways.

So can you please change the code within the if block as follows by importing `ballerina/jsonutils;` and check.

```ballerina
if (rtn is table<addressRecord>) {
    rtnStr = jsonutils:fromTable(rtn);
}
``

**Comment by RobRMackay** [comment]
Thank you for the quick response, of course this solved my issue, I do like the type conversion when inside a test block patter, just taking a little practice to get good with it. Once again the ballerina team responding quickly and professionally - your team is great.

Working perfectly now.
