### ISSUE TITLE
Doc command doesn't include version in the URL

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#19852]
**Description:**
Currently the generated docs from doc command does not include the version in the directory structure or the urls in the html files.\.

**Steps to reproduce:**

**Affected Versions:**
1.0.3

**OS, DB, other environment details and versions:**
MAC

**Comment by kaviththiranga** [comment]
@hemikak , do we need the version per module or per project?

For example, per project it will look like below.
```
target/api-docs/<x.x.x>/index.html
target/api-docs/<x.x.x>/mod1/index.html
```

Per module, it will look like below.
```
target/api-docs/index.html
target/api-docs/mod1/<x.x.x>/index.html
```

**Comment by hemikak** [comment]
This way would work: target/api-docs/mod1/<x.x.x>/index.html

**Comment by kaviththiranga** [comment]
@hemikak  this is only required for docs generated for Ballerina projects with ```ballerina doc``` command or is it not? I mean do we have to do same for the docs packed in distribution?

**Comment by hemikak** [comment]
This is for doc command only.

**Comment by hevayo** [comment]
Fixed with central doc support
