### ISSUE TITLE
Add feature of specifying .balo paths in dependencies as a web link

### ISSUE THREAD

**Issue by shethdhvani** [ballerina-platform/ballerina-lang#19922]
**Description:**
When adding module dependencies in Ballerina.toml file, add support so as to support web links to .balo files. Example: link to a github repo (full path to the folder) that contains .balo files.

**Steps to reproduce:**
NA

**Affected Versions:**
NA

**OS, DB, other environment details and versions:**
NA

**Related Issues (optional):**
NA

**Suggested Labels (optional):**
Type/feature

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Closing since providing a path to bala in swan-lake is not supported
