### ISSUE TITLE
ballerina-1.0.3 brew upgrade failed

### ISSUE THREAD

**Issue by chenrui333** [ballerina-platform/ballerina-lang#19923]
**Description:**

Relates to https://github.com/Homebrew/homebrew-core/pull/46702

Jenkins console log, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/51731/version=catalina/console

Local error log:
```
$ brew test ballerina
Testing ballerina
/usr/local/Cellar/ballerina/1.0.3/libexec/bin/./ballerina: fork: Resource temporarily unavailable2-1e0u
Error: ballerina: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<128>.
```

**Steps to reproduce:**

**Affected Versions:**

All latest three MacOS versions, Catalina, Mojave, HighSierra. 

**OS, DB, other environment details and versions:**

Mac

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
These seems to be  now working in brew CI tests https://github.com/Homebrew/homebrew-core/pull/192197
Hence closing this issue
