### ISSUE TITLE
Issue in Task Scheduler Timer example

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#19928]
**Description:**

[Task Scheduler Timer](https://ballerina.io/learn/by-example/task-scheduler-timer.html) example does not exit after the execution.

```
Compiling source
	timer.bal

Generating executables
Running executables

Hi Sam you are 1 years old now.
Hi Sam you are 2 years old now.
Hi Sam you are 3 years old now.
Hi Sam you are 4 years old now.
Hi Sam you are 5 years old now.
Sam started schooling
Hi Sam you are 6 years old now.
Hi Sam you are 7 years old now.
Hi Sam you are 8 years old now.
Hi Sam you are 9 years old now.
Hi Sam you are 10 years old now.
End.
```

Program hangs after this point.

**Steps to reproduce:**
Run the code at [Task Scheduler Timer](https://ballerina.io/learn/by-example/task-scheduler-timer.html).

**Affected Versions:**
1.0.3

**Comment by aashikam** [comment]
Even though the main function execution exits, the callback services are not stopped. This is the expected behavior. Hence closing this issue.
