### ISSUE TITLE
[Question] How does Ballerina compares to Terraform or AWS CDK?

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-lang#19925]
Is Ballerina essentially doing the same deployment steps that Terraform and AWS CDK is doing?

**Comment by keizer619** [comment]
There is a fundamental difference between Ballerina and Terraform or CDK. Both Terraform and CDK handles deployment part of cloud infrastructure. 

On the other hand Ballerina is a general purpose language designed to write distributed network applications efficiently. You can simply write a service application and run itself as a service. When it comes to deployment Ballerina generates docker and kubernetes artifacts which could be deployed in preferred Cloud infrastructure.

You can read [how to deploy and run ballerina programs article](https://ballerina.io/learn/how-to-deploy-and-run-ballerina-programs/) for more information.

**Comment by wggihan** [comment]
I'm closing this git issue now. Please feel free to reopen if you need further clarification.
