### ISSUE TITLE
CLASS_NOT_FOUND error when a module uses another module calling native java lib

### ISSUE THREAD

**Issue by hayaofr** [ballerina-platform/ballerina-lang#19921]
**Description:**

In my multi module project attached, the mycalc module is using native java dependency myjavalib referenced in Ballerina.toml file. 
Module mymodule is using module mycalc function.
The project builds properly but I get a CLASS_NOT_FOUND error when running module mymodule
**Steps to reproduce:**
Sample project to reproduce error :
[myproject.zip](https://github.com/ballerina-platform/ballerina-lang/files/3853210/myproject.zip)

**Adjust path to** myjavalib-1.0-SNAPSHOT.jar in Ballerina.toml
**Build the project** : ballerina build -a
**Run module mymodule** : ballerina run mymodule

error: hayao:mycalc:main.bal:4:1: {ballerinax/java}CLASS_NOT_FOUND message=org.hayao.myjavalib.Calculator

**Affected Versions:**
1.0.3
**OS, DB, other environment details and versions:**
Ubuntu 19.10
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
With ballerina 1.2.13 I was able to build the project by providing the relative path for jar file
```
    [[platform.libraries]]
    artifactId = "myjavalib"
    version = "1.0-SNAPSHOT"
    path = "lib/myjavalib-1.0-SNAPSHOT.jar"
    groupId = "org.hayao.myjavalib"
    modules = ["mymodule","mycalc"]
```

Also change java import from `ballerinax/java` to `ballerina/java`

I will be closing the issue please reopen if it still exists.
