### ISSUE TITLE
[QUESTION] Any AWS lambda Aurora or Athena dB examples?

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-lang#19924]
**Description:**

Are there any AWS Lambda Aurora / Athena or any of the AWS RDS services examples showing how to ingest data

**Comment by keizer619** [comment]
AFAIK currently there are no Aurora or Athena dB integration scenarios. When it comes AWS Lambda, Ballerina has an extension where as you can deploy Ballerina functions as AWS Lambda functions. 

I hope from that point onwards you can integrate AWS Lambda function to Aurora or Athena DB. Please refer our [AWS Lambda Deployment Ballerina Example](https://ballerina.io/learn/by-example/awslambda-deployment.html). Once you build above code it will generate a zip file which can be used to create the function. For the AWS Lambda Layer please use following ARN.

`arn:aws:lambda:<REGION_ID>:141896495686:layer:ballerina:2`

**Comment by scheung38** [comment]
@keizer619 so Ballerina does the generation of artefacts like Dockers etc but to deploy to AWS we still need to goto aws cli for the actual deploy.

**Comment by keizer619** [comment]
@scheung38 Yes you need to AWS cli or Kubernetes cli for deployment.

**Comment by wggihan** [comment]
I'm closing this issue. Please feel free to reopen if you need further help.
