### ISSUE TITLE
In the resourceConfig, Path Parameters with a suffix is not supported

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#19957]
**Description:**
In the resource config, including a path parameter with a suffix is not supported.

- Ex: /pet/{petId}.api

**Steps to reproduce:**
Create a service with a resource.
Provide path param with a suffix
Invoke the API

**Affected Versions:**
0.990.5

**Related Issues (optional):**

**Suggested Labels (optional):**
Improvement

**Comment by VirajSalaka** [comment]
created a relevant issue in the microgateway repository as well.
[https://github.com/wso2/product-microgateway/issues/884](https://github.com/wso2/product-microgateway/issues/884)

**Comment by chamil321** [comment]
Fixed by https://github.com/ballerina-platform/ballerina-lang/pull/20239
