### ISSUE TITLE
[API] Create different actions for HTTP status codes

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#19977]
**Description:**
At the moment we only support below actions 

caller->ok()
caller->created()
caller->accepted()

We need to continue adding more actions like,

caller->noContent(); 
caller -> badRequest();
caller -> internalServerError(); 

This would help improve the readability of the code and make the language more expressive.

**Comment by chamil321** [comment]
Will be adding ```caller -> notFound();``` as well

**Comment by chamil321** [comment]
Fixed by #22522, hence closing the issue
