### ISSUE TITLE
Implement table type validations

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#19970]
**Description:**

Current table type validations have deviations from the spec. Need to properly implement the new table type validations in both compile time and runtime.

Example:
```ballerina
public type Application record {|
    string id;
    string name;
    string description;
    string user_id;
|};

public type ApplicationResponse record {|
    string id;
    string name;
    string description;
|};

function foo() {
    table<ApplicationResponse> appResp =  ...;
    table<Application> app = appResp;   // should fail at compile time
}
```

Originating from https://github.com/ballerina-platform/ballerina-lang/issues/19802

**Comment by mohanvive** [comment]
Not valid in latest table implementation
