### ISSUE TITLE
Java inter-op with varargs

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#19980]
**Description:**
It seems java inter-op won't accept the varargs and fail to compile.

B7a code
```
function printExtern((any|error)... values) = @java:Method {
    name: "print",
    class: "org.ballerinalang.stdlib.io.nativeimpl.PrintUtils"
} external;
```

Java method signature
```
public static void print(ArrayValue values)
```

Error
```
error: ballerina:io:print.bal:25:1: {ballerinax/java}METHOD_SIGNATURE_DOES_NOT_MATCH message=No such Java method 'print' with method argument type 'interface org.ballerinalang.jvm.values.ArrayValue' found in class 'class org.ballerinalang.stdlib.io.nativeimpl.PrintUtils'
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
I think the java method signature should be `public static void print(Object... values)`. Here the type of var-arg is `Object` since thats the java-type matches to ballerina `union-type`.

However, there is a ClassCastException once we change the method signature. We'll fix that.
