### ISSUE TITLE
Tooling support to improve semantic analyzing support in documentations

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#19985]
Related to #19253 .
Issue #9704 .

We have added support in the compiler front end to validate Documentation References. We send a warning to  the user for invalid documentation references.

**Comment by nadeeshaan** [comment]
Fix has been reflected in the tool and show the warnings accordingly. Hence closing the issue.

**Comment by nadeeshaan** [comment]
Reopening since the tooling need to provide capabilities such as definition, references, rename and completions

**Comment by IMS94** [comment]
Closing this since there's no plan to provide such a feature for swan lake. Please reopen if needed.
