### ISSUE TITLE
[Tooling] Support for function pointer rest params

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#19999]
**Description:**
With https://github.com/ballerina-platform/ballerina-lang/pull/19976 ballerina supports rest parameter in function pointers. Hence the following code snippets are valid.

```ballerina
function (string a, int... b) returns string jar = foo;
```
```ballerina
 var a = function(int, string, int...) returns int {
                return 1;
            }
```

This has to be supported via tooling once the above PR is merged.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Fixed in the latest master. Hence closing the issue.
