### ISSUE TITLE
Build is hanging due to websub module's tests

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#20001]
**Description:**
Build is hanging in travis when the websub tests are enabled. When the tests are disabled, the build passes.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
@gimantha Do we have any logs related to failed WebSub tests? If so please post.

**Comment by gimantha** [comment]
> @gimantha Do we have any logs related to failed WebSub tests? If so please post.

Here is the log.. https://api.travis-ci.com/v3/job/256935408/log.txt
Coudlnt find any specific issues in the log

**Comment by chamil321** [comment]
> > @gimantha Do we have any logs related to failed WebSub tests? If so please post.
> 
> Here is the log.. https://api.travis-ci.com/v3/job/256935408/log.txt
> Coudlnt find any specific issues in the log

Thanks!!
