### ISSUE TITLE
Cannot install ballerina using mac installer in MacOs Catelina 

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#20012]
**Description:**
Get the following error while trying to install Ballerina using the ballerina installer for MacOs in MacOs Catelina. 

<img width="424" alt="Screenshot 2019-10-21 at 11 12 49" src="https://user-images.githubusercontent.com/11191791/69317428-f250d980-0c60-11ea-96bc-5ce14ec4a05b.png">

**Steps to reproduce:**
(_Should update to the latest MacOs version Catelina_)
Download the latest installer from Ballerina website for MacOs.
Install using the executable to get the message. 

**OS, DB, other environment details and versions:**
MacOs Catelina (10.15.1)

**Comment by n-jay** [comment]
I recently tried installing 1.1.2 but was confronted with the same error.
![image](https://user-images.githubusercontent.com/24616975/74627885-23667a80-517a-11ea-9dd1-44b1ebbc8a48.png)
Assuming its unresolved, are there any workarounds?

**Comment by DimalChandrasiri** [comment]
> I recently tried installing 1.1.2 but was confronted with the same error.
> ![image](https://user-images.githubusercontent.com/24616975/74627885-23667a80-517a-11ea-9dd1-44b1ebbc8a48.png)
> Assuming its unresolved, are there any workarounds?

As a workaround, try right clicking on the package and install from the context menu. It should work where this warning is able to bypass.

**Comment by n-jay** [comment]
> > I recently tried installing 1.1.2 but was confronted with the same error.
> > ![image](https://user-images.githubusercontent.com/24616975/74627885-23667a80-517a-11ea-9dd1-44b1ebbc8a48.png)
> > Assuming its unresolved, are there any workarounds?
> 
> As a workaround, try right clicking on the package and install from the context menu. It should work where this warning is able to bypass.

Hi @DimalChandrasiri 
I tried it out and it worked. 
![image](https://user-images.githubusercontent.com/24616975/74720039-1e2d2c80-525b-11ea-8f30-511b8608c5c4.png)
Thanks so much for the workaround!

**Comment by keizer619** [comment]
This has been fixed by beta1 as now sign jar contents and notarize the entire pkg installer
