### ISSUE TITLE
Refactor cursor table

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#20019]
**Description:**
$title.

ref: https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/table/table.md#sql-interop

**Steps to reproduce:**
N/A

**Affected Versions:**
1.0.x

**OS, DB, other environment details and versions:**
N/A

**Comment by hasithaa** [comment]
This issue is captured in multiple sub-tasks. Hence Closing the old issue.

**Comment by hasithaa** [comment]
Ref https://github.com/ballerina-platform/ballerina-lang/issues/22533 https://github.com/ballerina-platform/ballerina-lang/issues/22668
