### ISSUE TITLE
Docerina doc generation fails to identify Listener Objects

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#20023]
**Description:**
Docerina doc generation fails to identify Listener Objects

https://ballerina.io/learn/api-docs/ballerina/http/objects/Listener.html

**Affected Versions:**
v1.0.0 at least

**Comment by praneesha** [comment]
The below links in API docs which are redirected to [1] break due to this as shown below.

<img width="1680" alt="Screenshot 2019-11-22 at 14 02 45" src="https://user-images.githubusercontent.com/11707273/69410436-11b73780-0d31-11ea-9e05-e782bf87784f.png">
