### ISSUE TITLE
 Docerina fails to generate type name for anon/inline records

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#20024]
**Description:**
 Docerina fails to generate type name for anon/inline records

**Steps to reproduce:**

**Affected Versions:**
v1.0.0 at least

**Comment by praneesha** [comment]
The "$anonType$0" link in API docs[1] breaks due to this as shown below.

<img width="1183" alt="Screenshot 2019-11-22 at 14 14 10" src="https://user-images.githubusercontent.com/11707273/69411150-64ddba00-0d32-11ea-855b-92de9a2b3161.png">

[1] https://ballerina.io/learn/api-docs/ballerina/nats/types.html#Content

**Comment by praneesha** [comment]
Reopening this as there are more 404 links with anon type to be fixed as shown below.

<img width="1083" alt="Screenshot 2020-05-04 at 14 22 00" src="https://user-images.githubusercontent.com/11707273/80950106-dc039800-8e12-11ea-8df4-33930dc4aa52.png">

**Comment by praneesha** [comment]
This is correct in the source code of the module as shown in [1] for example.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/3efbede896eda6b660e85ad704309e7cf4fef704/stdlib/messaging/nats/src/main/ballerina/src/nats/commons.bal#L21

**Comment by praneesha** [comment]
Now, we have these anonymous values as "T" values as shown below, which is also incorrect.

<img width="1149" alt="Screenshot 2020-07-13 at 22 22 23" src="https://user-images.githubusercontent.com/11707273/87331383-7e4ca400-c557-11ea-8c25-d4b1b04bb2c1.png">

@aashikam - Can you explain why this is wrong?

**Comment by shehan360** [comment]
This is a screenshot from the latest master build. Can you recheck? @praneesha 
![Screenshot from 2020-07-13 22-36-20](https://user-images.githubusercontent.com/33398983/87332607-72fa7800-c559-11ea-9e72-d4d6faff93e6.png)

**Comment by praneesha** [comment]
Closing as this fix will be applied from the next release onwards.

**Comment by aashikam** [comment]
@praneesha Hi all, why are some fields in that screenshot shown as `$anonType$`?

**Comment by shehan360** [comment]
@aashikam Hi, this is a known issue #24578
