### ISSUE TITLE
Revisit final jar creation task logic

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#20020]
**Description:**
There is a considerable time increase with final jar creation task in 1.0.4 release. This is possibly due to the fix introduced with #19783

**Steps to reproduce:**
Compare the build times between 1.0.3 and 1.0.4

**Affected Versions:**
1.0.4

**OS, DB, other environment details and versions:**
Mac, Windows

**Suggested Assignees (optional):**
@warunalakshitha

**Comment by NipunaRanasinghe** [comment]
Closing since this is fixed with #20797 and #20862.
