### ISSUE TITLE
Problem with soap:soapClient not conforming to signature

### ISSUE THREAD

**Issue by drrallen** [ballerina-platform/ballerina-lang#20050]
**Description:**
soap:Soap11Client - 
The soapAction parameter for sendReceive is advertised as a string but providing a string produces an error from the compiler.

**Steps to reproduce:**
E.g. using sample code for a rest to soap service:

import ballerina/http;
import ballerina/jsonutils;
import wso2/soap;

soap:Soap11Client soapEP = new("http://localhost:9000/services/SimpleStockQuoteService");

@http:ServiceConfig {
    basePath: "/stockQuote"
}
service stockQuote on new http:Listener(9090) {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/quote/{symbol}"
    }
    resource function getQuote(http:Caller caller, http:Request request, xml symbol) {
        xmlns "http://services.samples" as m0; 
        xml payload = xml `<m0:symbol>${symbol}</m0:symbol>`; 

        soap:SoapResponse soapResponse = checkpanic soapEP->**sendReceive("urn:getQuote", payload);** 
        xml responsePayload = checkpanic soapResponse.httpResponse.getXmlPayload(); 
        http:Response response = new;
        response.setJsonPayload(<@untainted>checkpanic jsonutils:fromXML(responsePayload.Body.getQuoteResponse,
            {preserveNamespaces: false}));        
        error? respond = caller->respond(response);
    }

Gives error:
incompatible types: expected '(xml|ballerina/mime:Entity[])', found 'string'

**Affected Versions:**
1.04

**OS, DB, other environment details and versions:**
Windows 10 64bit

**Related:**
Fix issue #65 by changing the order of API arguments. - This fix on Github:
https://github.com/wso2-ballerina/module-soap/commit/38c046e8fe007a5eda559a95d2f928864fda9536 
Relates to changing the order of the arguments.
Supplying the SOAP body first,then the Action works. 
Looks like the documentation is running behind the fix implemented for ballerina version 1.04

**Comment by daneshk** [comment]
Closing this issue, since this is moved to wso2-ballerina/module-soap repo. Please check the issuewso2-ballerina/module-soap#68 to track the status.
