### ISSUE TITLE
Some of the names does not show in the web page correctly

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#20067]
**Description:**
Some of the constant names displayed in the site does not show completely. It shows them with three dots!
<img width="595" alt="Screen Shot 2019-09-10 at 4 36 24 PM" src="https://user-images.githubusercontent.com/40016057/64608890-45005080-d3e9-11e9-851b-aac67eda9ddc.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ThisaruGuruge** [comment]
Closing as per the above comment

**Comment by shehan360** [comment]
This is expected behavior as strings that are too long are truncated. 
Hovering the cell will display the whole string.

**Comment by ThisaruGuruge** [comment]
IMHO, we should find a better way to show those longer strings. This way is not that appealing.
