### ISSUE TITLE
Field types and the default values are not readable

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#20066]
**Description:**
The type and the default value of a record type is not showing properly in the website. 
See below example:
<img width="633" alt="Screen Shot 2019-09-11 at 2 08 58 PM" src="https://user-images.githubusercontent.com/40016057/64682521-3aa08e00-d49f-11e9-8d0e-ee59c2f46fff.png">

Here the field name is `attributePrefix`, type of the field is `string` and the default value of the field is `@`. But it does not seems that way.

These three categories should be easily differentiate.

**OS, DB, other environment details and versions:**    
OS:         MacOS Mojave
Browser: Safari

**Steps to reproduce:**
Check [this link](https://v1-0.ballerina.io/learn/api-docs/ballerina/jsonutils/records/XmlOptions.html)

**Related Issues:**

**Comment by shehan360** [comment]
This issue is fixed as below in the latest master branch.

![Screenshot from 2020-07-16 12-52-56](https://user-images.githubusercontent.com/33398983/87639728-4dd95580-c763-11ea-989e-8bd2a987ad05.png)
