### ISSUE TITLE
'path' Parameter in the resource config does not allow to use a defined const 

### ISSUE THREAD

**Issue by DeveloperLK** [ballerina-platform/ballerina-lang#20062]
**Description:**

As the `path` value of the resource function config, a constant is used (`path: RESOURCE_PATH`).  It gives the following error:

_invalid resource parameter(s): cannot specify > 2 parameters without specifying path config and/or body config in the resource annotation_ 

**Steps to reproduce:**
```
import ballerina/http;
import ballerina/io;

const string RESOURCE_PATH = "/{id}";

service SampleService on new http:Listener(8080) {
    
    @http:ResourceConfig {
        methods: ["GET"],
        path: RESOURCE_PATH
    }

    resource function sampleResource(http:Caller caller, http:Request request, string id) {
        io:print("sampleResource");
        var x = caller->respond("Hello from sampleResource");
    }

}
```
**Affected Versions:**
Ballerina v1.0.3

**OS, DB, other environment details and versions:**
Ubuntu 18.04(Linux)

**Quick Fixes:**
When the string value(`"/{id}"`) is directly assigned to the `path` parameter (`path: "/{id}"`)the problem resolves.

**Comment by chamil321** [comment]
This is language level bug. Required change is tracked by https://github.com/ballerina-platform/ballerina-lang/issues/20733. Hence closing the issue
