### ISSUE TITLE
typedesc won't work with java inter-op

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#20063]
**Description:**

Ballerina syntax: 
```
function getTable(typedesc<record {}> structType) returns @tainted table<record {}>|Error
```

Java syntax:
```
public static Object getTable(ObjectValue csvChannel, TypedescValue typedescValue) 
```

Error:
```
{ballerinax/java}METHOD_SIGNATURE_DOES_NOT_MATCH message=No such Java method 'getTable' with method argument type 'class org.ballerinalang.jvm.values.TypedescValue' found in class
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/20097
