### ISSUE TITLE
Response is delayed when a ballerina service is invoked from a remote network

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#20085]
**Description:**
When A request is sent from a remote network to a ballerina service, the service takes some time (~15s) to complete the read operation. Due to this, the response is delayed. The reason behind this issue has been a reverse DNS lookup performed by the ballerina service.

**Steps to reproduce:**

**Affected Versions:**
0.990.5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**

**Comment by wggihan** [comment]
This is fixed in 1.1.0.
