### ISSUE TITLE
Redesign Match statement according to the Spec R3

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#20084]
According to the spec 

```
match-pattern :=
  var binding-pattern
   | wildcard-match-pattern
   | const-pattern
   | list-match-pattern
   | mapping-match-pattern
   | error-match-pattern
```
Currently, Some cases which are actually binding patterns/wildcard match patterns goes through the mapping match pattern. (as mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/19743, https://github.com/ballerina-platform/ballerina-lang/issues/19720)

**Comment by hasithaa** [comment]
Duplicates https://github.com/ballerina-platform/ballerina-lang/issues/15962
