### ISSUE TITLE
[Utils] Migrate to java interoperability

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#20131]
**Description:**
Migrate the native implementation of the utils module to java interoperability.

**Comment by daneshk** [comment]
This is not possible due to implicit dependency in java module. It causes cyclic dependency when trying to add ballerina-java dependency to utils.

**Comment by ldclakmal** [comment]
Yes. IMO the existing functionalities should be provided by the language itself. Currently, all the modules depend on the ballerina/utils module. So, the `ballerina/utils` module should be revisited. https://github.com/ballerina-platform/ballerina-lang/issues/20245 is created to track this. Hence closing this issue.
