### ISSUE TITLE
Parent module's dependency is not resolved when it comes to sub module

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#20173]
**Description:**
There is a parent ballerina module with a dependency jar file. It compiles with no errors. Then there is another module, which uses that previously mentioned ballerina parent module. During the compilation of submodule, it gives a compilation error. In our case, it looks like this.
`error: wso2:gateway:native/compression.bal:32:1: {ballerinax/java}CLASS_NOT_FOUND message=org.wso2.micro.gateway.core.compression.Compress`

This behavior is not observed in ballerina v1.0.0, v1.0.2. I tried adding the dependency to the submodule's ballerina.toml file as well. But it did not resolve the problem.

**Steps to reproduce:**
Build a module with a dependent jar. (Dependency should be in the ballerina.toml)
Then create another ballerina module using the previously created jar. During the compilation phase, the error should be visible.

**Affected Versions:**
v1.0.3, v1.0.4

**OS, DB, other environment details and versions:**
Mac OS Mojave

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**

**Comment by suganyasuven** [comment]
Could not able to reproduce the above issue. I attached the ballerina project which tried to reproduce. Can you please check the scenario used here is the same as your one? 

[SampleProjects.zip](https://github.com/ballerina-platform/ballerina-lang/files/4629508/SampleProjects.zip)

**Comment by VirajSalaka** [comment]
For microgateway, architecture has been changed since it is not recommended to use the thin jar by that time. So the fix is no longer required. Hence closing this issue.
