### ISSUE TITLE
[Java] Migrate to java interoperability

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-lang#20178]
**Description:**
Migrate the native implementation of the java module to java interoprability

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by wggihan** [comment]
Java module is the root of java interoperability. Hence this will be used annotation based mapping.
