### ISSUE TITLE
Need to imporove uninitialized value reference detection with respect to transaction block

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#20194]
**Description:**
```ballerina
import ballerina/io;

public function testAssignmentToUninitializedVariableOfOuterScopeFromTrxBlock() returns int|string {
    int|string s;
    transaction with retries = 1 {
      //s = "init-in-transaction-block";
    } onretry {
        s = 1;
    } aborted {
        //s = 1;
    }
    return s;
}

public function main() {
    var v = testAssignmentToUninitializedVariableOfOuterScopeFromTrxBlock();
    if (v is int) {
        io:println("int");
    } else {
        io:println("string");
        any p = v;
        if (p is string) {
            io:println("string - 2");
        } if (p is ()) {
            io:println("string - yet - nil");
        }
    }
    io:println(v);
}
```

Need to improve the dataflow analysis for transaction bock.
There is no static guarantee that any assignment to a variable will be successful when the transaction block exits.

```ballerina
int|error v;
transaction {
    v = panicThisFuncEveryTime();
} aborted {
   // aborted
}
``` 

Above `v` will not be initialized when the transaction statement finishes executing. 
The only way to guarantee variable init is to initialize the variable in both committed and aborted blocks.

Current impl would not emit an error when variable is initialized in any of the transaction blocks.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
@gimantha Can you verify this issue with new implementation?

**Comment by mohanvive** [comment]
Respective issue is no longer valid in new transaction implementation because there is no multiple blocks in the new impl, such as onretry and aborted. Hence, closing the issue.
