### ISSUE TITLE
NoSuchElementException intermittently when invalid-imports are tested on some systems

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#20215]
**Description:**
This was discovered on https://github.com/ballerina-platform/ballerina-lang/pull/20151

On some systems (Linux `travis` and MacOs `local` in this case) when running tests for invalid imports

A `NoSuchElementException` is thrown in line 
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/packaging/RepoHierarchy.java#L58

This is temporarily handled with a try catch on this PR: https://github.com/ballerina-platform/ballerina-lang/pull/20151

But needs to be fixed properly.

**Comment by hevayo** [comment]
Outdated issue the implementation has changed in SL beta1
