### ISSUE TITLE
Invalid position for error destructuring patterns

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#20226]
**Description:**
Consider the following example,

`var error(reason, message = msg, cause = errCause, ...rest) = err;`

in the above snippet, following position mismatches can be found

- Start location of the reason is provided as the start of **_error_** keyword
- Start location of msg is provided as the start position  of **_message_**
- Same applies to the other two as well

**Affected Versions:**
v1.0.0 at least

**Comment by hasithaa** [comment]
@nadeeshaan Can you verify this again.

**Comment by MaryamZi** [comment]
This seems to be fixed now. Please reopen if not.

Verified via error diagnostics too.

```ballerina
public function main() {
    error<record {| string message; error cause; |}> err = error("", message = "", cause = error(""));
    var error(reason, message = msg, cause = errCause, ...rest) = err;
}
```

```ballerina
public function main() {
    error err = error("");
    var error(reason, message = msg, cause = errCause, ...rest) = err;
}
```
