### ISSUE TITLE
Cannot use field/index/invocation access on grouped expressions

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#20238]
**Description:**
#20234 Partially fixes the issue. However, still cannot use expressions within the group (i.e ("A" + x).length(), (<PersonObj>(dataMap)["a"]).getName()) due to current grammar limitations.

**Steps to reproduce:**
```ballerina
# Fails because `("string " + x)` is not supported within group invocation.
 function testGroupedLangLibInvocationRef() returns boolean {
     string x = "value";
     return (("string " + x)).length() == 12;
 }

# Fails because `<PersonObj>(dataMap)["a"]` is not supported within group invocation.
 function testNestedGroupedInvocationRef() returns boolean {
     PersonObj p = new;
     map<PersonObj> dataMap = {"a": p};
     return p.getName() === (<PersonObj>(dataMap)["a"]).getName();
 }

# Fails because `isNaN()` invocation on (0.0/0.0) expression is not supported.
function testGroupedBuiltInInvocationRef() returns boolean {
    float f = 0.0/0.0;
    return f.isNaN() && (f).isNaN() && (0.0/0.0).isNaN();
}
```

**Affected Versions:**
1.0.5, 1.1.0

**Related Issues:**
- https://github.com/ballerina-platform/ballerina-lang/issues/18298
- https://github.com/ballerina-platform/ballerina-lang/issues/19020

**Comment by dulvinw** [comment]
Looks like this is fixed in the new parser. Hence we can close the issue.

**Comment by hasithaa** [comment]
@dulvinw Shall we add a test case.

**Comment by pubudu91** [comment]
Although this seems to be fixed in the parser, this still crashes in the compiler. Need to fix the compiler as well. See #24603 for examples. A user raised this issue in Slack as well.

**Comment by SupunS** [comment]
Removed the 'parser' label since this is fixed in the parser.
