### ISSUE TITLE
Improve bir by removing unwanted basic blocks

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#20249]
**Description:**
current bir contains some unwanted basic blocks with just GOTO instructions, we can simply remove them and improve bir

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
This is done by new BirBasicBlock optimizer.
