### ISSUE TITLE
Refactor jvm codegen

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#20250]
**Description:**
Current jvm code gen is a big program without proper organizing, we can organize the code by breaking everything to proper phases. (like compiler front end)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19027
