### ISSUE TITLE
Cannot start Language Server in debug mode

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#20272]
**Description:**
`LSDEBUG=true` is not honored with the new CLI commands for language server.

**Steps to reproduce:**
1. Open `vscode` folder in vscode.
2. Change LSDEBUG parameter in launch.json  into TRUE
3. Start the extension in debug mode.
4. Even though debug log says started in debug mode, language server starts without suspending in debug mode.

**Affected Versions:**
1.1.0

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
