### ISSUE TITLE
[IDEA Plugin] Indentation error on braces when using autocomplete.

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#20289]
**Description:**
Auto completion for object methods is broken in 1.1.0-alpha

**Steps to reproduce:**

**Affected Versions:**
1.1.0-alpha
**OS, DB, other environment details and versions:**
MacOsX (10.15.1)

**Suggested Assignees (optional):**
@NipunaRanasinghe 

<img width="400" alt="Screenshot 2019-12-09 at 15 26 47" src="https://user-images.githubusercontent.com/25750106/70426396-fc643c00-1a98-11ea-87b9-a40f7c598f71.png">

**Comment by dulvinw** [comment]
This issue seems to be there for everywhere we start a function with an indentation

**Comment by NipunaRanasinghe** [comment]
@dulvinw Thanks for the observations. Started working on the fix which will be available with the next plugin release :)

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
