### ISSUE TITLE
[Packerina Spec]  Add libraries to Single bal file

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#20281]
**Description:**
In some cases like  using interops, database drivers we need to use external libraries and include them in the final executable. In a ballerina project we can add external libraries to project ballerina.toml.  ATM we do not have a way to  add them when using single bal file.

We can have another flag to ballerina build and run command ( ex.--libs) to add thsoe external libraries.

ex. ballerina run --libs driver.jar main.bal

current workaround is to add it to bre/lib but IMO accessing bre/lib for third party jars is not the proper way.

**Comment by warunalakshitha** [comment]
There are some scenarios we need to clarify for --libs command.

1)  Are we going to include those libraries in final executable. As an example interop case we need to pack it. but for some third party jars like driver we do not need to pack.

2) Do we need that support in "ballerina run jar". If we support that "java -jar" and "ballerina run jar" will have different behavior.

**Comment by azinneera** [comment]
Single file is only recommended to use to get started. If the user needs to use external libraries, then you can convert it to a package can be created simply using the `bal init` command. This will create the Ballerina.toml where the required external libraries can be added.
