### ISSUE TITLE
`ballerina run` doesn't terminate when a module is pulled from central?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#20291]
**Description:**
$title. Terminates when the module is available locally (i.e., subsequent runs).

**Steps to reproduce:**
Use `ballerina run` with a bal file that requires pulling a module from central.

**Affected Versions:**
1.1.0-alpha

**Comment by parkavi11** [comment]
Seems this is working fine now, hence closing
<img width="1368" alt="Screen Shot 2020-04-02 at 13 33 04" src="https://user-images.githubusercontent.com/28732894/78224681-9176bf00-74e6-11ea-9437-1779520c701e.png">
