### ISSUE TITLE
[IDEA Plugin] Go to definition is not working for objects between modules of same project

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#20297]
**Description:**
Idea ballerina plugin does not jump to definitions when clicked on a definition which is defined on an imported module of the same project

**Steps to reproduce:**
/*Module1.bal*/
import ballerina/http;
import ballerina/io;

public type Person object {
    string name;
    private int id;
    int age;

    public function __init(string name, int id, int age) {
        self.name = name;
        self.id = id;
        self.age = age;
    }

    public function getId() returns int {
        return self.id;
    }
};

/*Module2.bal*/
import ballerina/io;
import dulvin/module1 as importMod;

public function main() {
    importMod:Person newPerson = new("TestPerson", 100, 50);
    importMod:Lecturer newLecturer = new(newPerson, "Maths", 5);

    io:println(newLecturer.getAgeNotPublic());
}

**Affected Versions:**
ballerina -v
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha

**OS, DB, other environment details and versions:**
MacOSX (10.15.1)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@NipunaRanasinghe

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
