### ISSUE TITLE
Misleading information in code completion when importing a module

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#20294]
**Description:**
When we try to import a module in a ballerina file, using code completion, we expect a module import statement, and only import statement. But it also adds the module name in the next line, which is misleading.

This behaviour is totally okay, when we type a module name inside a function block. But when we type it in the first lines, we expect it to add only the import statement.

If we add `import` first, and then type the package name, it works as expected.
There should be a way to identify the difference. 

**Steps to reproduce:**
Open a ballerina file, and type `io`, and hit Enter.
![Screenshot 2019-12-09 at 17 05 06](https://user-images.githubusercontent.com/40016057/70432828-2e2fcf80-1aa6-11ea-9bc3-98aca556fc30.png)

It will add the import statement and another line of `io`.
![Screenshot 2019-12-09 at 17 05 15](https://user-images.githubusercontent.com/40016057/70432896-47d11700-1aa6-11ea-90e6-24ef39004bbf.png)

**Affected Versions:**
1.1.0-Alpha

**Comment by nadeeshaan** [comment]
This is by design to maintain the consistency of module usages and auto imports in both the block level as well as top level. Hence closing this issue.
