### ISSUE TITLE
Ctrl + hover shows irrelevant content?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#20292]
**Description:**
$title.

![hover](https://user-images.githubusercontent.com/8376983/70431595-6681de80-1aa3-11ea-8fd6-fbae22a749fe.png)

**Steps to reproduce:**
```ballerina
import ballerina/io;

int[] i = [1, 2];

[int, string, boolean] x = [1, "hi", true];

public function main() {
    i.push(3);
    foreach var item in i {
        io:println(item);
    }

    int a = i[0];

    string s = foo(); // hover over s
}

const FOO = "foo";

function foo() returns string {
    return FOO;
}
```

**Affected Versions:**
1.1.0-alpha

**Comment by nadeeshaan** [comment]
This feature is a VSCode specific custom implementation based on the existing definition provider. We will create an issue for VSCode editor check whether there is a solution which can be done through the extension.

**Comment by nadeeshaan** [comment]
Closing since this is a VSCode behavior which is not controlable from the extension.
