### ISSUE TITLE
Fields are not suggested under dbOptions of jdbc:Client 

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#20304]
**Description:**
```
jdbc:Client testDB = new({
    url: "jdbc:mysql://localhost:3306/testdb",
    username: "test",
    password: "test",
    poolOptions: { maximumPoolSize: 5 },
    dbOptions: { }
});
```
It does not suggest any fields under the **dbOptions** field.

**Steps to reproduce:**
Press the ctrl + space inside the {} of **dbOptions** field

**Affected Versions:**
Plugin version: 1.0.5
Ballerina version: j1.1.0-alpha

**OS, DB, other environment details and versions:**
linux 16.04

**Comment by nadeeshaan** [comment]
@KavinduZoysa dbOptions expects a map and in that case, we do not provide suggestions because the fields cannot be predicted. Hence closing the issue
