### ISSUE TITLE
Complete a mapping constructor if the contextual type is a record/map

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20302]
Refer to the following:
![Peek 2019-12-09 17-41](https://user-images.githubusercontent.com/6260009/70434859-5f5ece80-1aab-11ea-867c-ef00e59ebb5b.gif)

To get the suggestions for the record, I have to manually complete the mapping constructor (including the semi colon) and go back inside the mapping constructor. Instead, if it automatically completed the mapping constructor by adding `};` once I type `{`, it would be a much better user experience.

**Comment by nadeeshaan** [comment]
This issue has been resolved, after adding the auto-closing pairs for `{` via the vscode plugin. Hence closing the issue
