### ISSUE TITLE
Record is not completed for anonymous records

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20308]
Refer to the following:
![Peek 2019-12-10 10-10](https://user-images.githubusercontent.com/6260009/70496399-70542200-1b35-11ea-9bfa-e3a5a6f339e2.gif)
As it can be seen, when defining an anonymous record, it doesn't add the closing brace (`}`) at the end. We have to manually add it. It would be great if the plugin can automatically add the closing brace in the next line, along with the ability to navigate to the end of the record where the variable name is given.

**Comment by nadeeshaan** [comment]
this has been solved with the latest snippets added. Hence closing the issue
