### ISSUE TITLE
Opening quote of a string literal not visible until you type another character

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20312]
**Description:**
Refer to the following. Notice how the opening quote is not visible in the editor until you type the next character in the string. Not sure if this is an issue in the plugin or an issue in VS Code itself.
![Peek 2019-12-10 10-37](https://user-images.githubusercontent.com/6260009/70497570-9a0f4800-1b39-11ea-92f3-43f0cdf6e0e2.gif)

**OS, DB, other environment details and versions:**
VS Code 1.40.2
Windows 10

**Comment by nadeeshaan** [comment]
This is fixed in v1.1.0 with https://github.com/ballerina-platform/ballerina-lang/commit/cb6b8143679fa3773c0140edebc39a1f3252fdd3#diff-5f863dc8b57b2349508e03471421b37c
Hence closing the issue
