### ISSUE TITLE
Optional record fields not shown in completion

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20316]
Refer to the following:
![Peek 2019-12-10 11-28](https://user-images.githubusercontent.com/6260009/70499962-54a24900-1b40-11ea-9c8b-be7890f7bca2.gif)
Note that `contact` is an optional field in the record. It is not suggested in completions. We should show optional fields as well in completions. But there should also be a distinction between required fields and optional fields in the completion list, so that it's clear to the user at a glance whether a field is required or not.

**Comment by nadeeshaan** [comment]
Optional fields are suggested if you use the optional field access operator `?.`. Hence this is done by design. One improvement we can do is to suggest the optional fields with `.` operator and automatically convert the `.` to `?.` .

**Comment by pubudu91** [comment]
Had a chat with @MaryamZi regarding this. The `?.` operator is not valid for LHS side (as is the case here). You can assign a value to optional fields using the `.` operator. Therefore, the optional fields should also be suggested when you say `p.`

**Comment by pubudu91** [comment]
However, it's better if we can distinguish between required fields and optional fields in the completion list
