### ISSUE TITLE
Goto Definition/ Code Actions does not work when anonymous functions are involved. 

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#20310]
**Description:**
$title

**Steps to reproduce:**
Goto definition doesn't work for `basicClosure`, `gimmeanint` or `k` (function pointer)
Code actions also seems not to be working with these. 

But go to definition for `basicClosure` works when anonymous function is removed from  the `basicClosure` function body. 

```ballerina
public function main() {
	 var joidsf = basicClosure();
}

function basicClosure() returns (function (int) returns int) {
    function (int) returns int k = function(int j) returns int {
        var aef = gimmeanint();
        return j;
    };

    var j = k(1);
    return k;
}


function gimmeanint() returns  int {
    return 12;
}
```

**Affected Versions:**
1.1.0-alpha

**OS, DB, other environment details and versions:**
MacOs

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Working in the latest 1.1.0 release. Hence Closing the issue
