### ISSUE TITLE
Editor should be scrolled up when the debug line goes down

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#20317]
**Description:**
Under the debug mode, when the debug line goes down, the editor should be scrolled up. Otherwise, we cannot see the debug line until we scrolled up manually.

**Steps to reproduce:**
Debug a code until the debug line goes down. 

**Affected Versions:**
Plugin version: 1.0.5
Ballerina version: j1.1.0-alpha

**OS, DB, other environment details and versions:**

**Comment by NipunaRanasinghe** [comment]
Closing since this cannot be reproducible in the latest VSCode plugin
