### ISSUE TITLE
[BBE] Typed binding patterns vs de-structure patterns are not easily distinguishable.

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#20323]
**Description:**
https://ballerina.io/learn/by-example/tuple-typed-binding-pattern.html
https://ballerina.io/learn/by-example/tuple-destructure-binding-pattern.html

For example, the above two BBEs does not clearly distinguish between the tuple-typed binding pattern vs tuple-destructure binding pattern.

**Comment by rdhananjaya** [comment]
I think we need to remove all `typed-binding-pattern` samples from this BBE (including `var` typed-binding-pattern) only leaving destructuring assignments. And move type-binding-pattern with `var` to tuple-typed-binding-pattern.html

**Comment by praneesha** [comment]
Closing since these BBEs are removed in the BBE revamp done in Swan Lake Beta1.
