### ISSUE TITLE
Default org name doesn't work when the login username is "ballerina"

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#20321]
**Description:**

Say you have a username as ballerina on your machine. 

Now, do the following.

ballerina new project
ballerina add module -t service
ballerina build -a 

Above sequence results in weird state because the org name is ballerina.

**Comment by IrushiL** [comment]
We have handled the org name validation in Swan Lake, therefore, this issue should be fixed now.

**Comment by IrushiL** [comment]
Verified the issue with `ballerina` as the organization name and the issue seems to be fixed now, hence closing the issue.
