### ISSUE TITLE
Code completion does not work inside forever block

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#20330]
**Description:**
$title.

**Steps to reproduce:**
```ballerina

function initFilterQuery() {
    forever {
        // code completion doesn't work here
    }
}

```
**Affected Versions:**
1.1.0-alpha

**OS, DB, other environment details and versions:**
VS code, Mac

**Comment by nadeeshaan** [comment]
Closing the issue, since this is no longer a valid syntax.
