### ISSUE TITLE
Issues with Ballerina and Ballerina Plugin in VSCode

### ISSUE THREAD

**Issue by Sumathi243** [ballerina-platform/ballerina-lang#20338]
**Description:**
I am new to Ballerina and Ballerina Integrator, I am trying the samples which are given by Ballerina Integrator Tutorials. while running file integration samples with ftp and all i am facing the following issues with command prompt console and also VSCode console. Please help me to sort out the issues.

![1](https://user-images.githubusercontent.com/52318181/70683528-aaa1f880-1cc8-11ea-9709-999062c6c4d3.png)
![2](https://user-images.githubusercontent.com/52318181/70683529-ab3a8f00-1cc8-11ea-9f6c-f205509ffe10.png)

Checked with Ballerina 1.0.3 and 1.0.5
In VSCode Ballerina Integrator Plugin 0.12.4

**Comment by NipunaRanasinghe** [comment]
@Sumathi243 It seems this issue is related to [vscode extension for ballerina integrator](https://github.com/wso2/ballerina-integrator) and therefore shall we move this issue into https://github.com/wso2/ballerina-integrator? :)

**Comment by Sumathi243** [comment]
![image](https://user-images.githubusercontent.com/52318181/70699271-df28ab00-1cee-11ea-926a-d942d79f1d35.png)
In VSCode itself getting same error like Command prompt console error

**Comment by Sumathi243** [comment]
@NipunaRanasinghe Yeah Move that issue and give solution

**Comment by nadeeshaan** [comment]
Created an issue in integrator repo (https://github.com/wso2/ballerina-integrator/issues/746), hence closing the issue
