### ISSUE TITLE
Cannot run a singe .bal file by giving the path to the file

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20339]
**Description:**
When you try to run a `.bal` file from outside the directory in which the file resides in, you get the following error:
```
~/wso2/ballerina/examples (release-stage)$ ballerina run records/records.bal 
error: no ballerina source files found in module 'records.bal'
```

**Steps to reproduce:**
Try to run a BBE from the root directory of the BBEs (<BALLERINA_REPO>/examples)

**Comment by Bhashinee** [comment]
The same issue is reported here as well: https://github.com/ballerina-platform/ballerina-lang/issues/20454
