### ISSUE TITLE
Compile error in  Range Expressions BBE

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#20333]
**Description:**
$subject

**Steps to reproduce:**
Run the [Range Expressions](https://ballerina.io/learn/by-example/range-expressions.html) BBE

**Affected Versions:**
Plugin version: 1.0.5
Ballerina version: j1.1.0-alpha

**Comment by praneesha** [comment]
Gets the below error when tried with 1.1.0-alpha.

<img width="1672" alt="Screenshot 2019-12-12 at 13 02 12" src="https://user-images.githubusercontent.com/11707273/70691683-af25db80-1cdf-11ea-9b73-c46e4d607b4c.png">
