### ISSUE TITLE
@tainted annotation requirement for main function return type

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#20337]
**Description:**

Consider the following code snippet. 

```ballerina
import ballerina/io;

public function main() returns error? {
    string srcPath = "./files/ballerina.jpg";
    io:ReadableByteChannel srcCh = check io:openReadableFile(srcPath);
}
```
This shows the following compilation error.
`functions returning tainted value are required to annotate return signature @tainted: 'main'`

Since the tainted error value is not passed to any other functions, do we need the taint annotation check for `main` function return type?

**Affected Versions:**
1.1.0-alpha

**Suggested Assignees (optional):**
@rdhananjaya

**Comment by MaryamZi** [comment]
The `main` function is similar to any other function, and could be called explicitly too. So IMO, we need to mark tainted returns even for the `main` function.
