### ISSUE TITLE
Goto definition is not working for stream

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#20331]
**Description:**
$title.

**Steps to reproduce:**
```ballerina

stream<Person> personStream = new;
stream<Child> childrenStream = new;

function initFilterQuery() {
    forever {
        from personStream where ... // goto definition on personStream is not working
    }
}

```
**Affected Versions:**
1.1.0-alpha

**OS, DB, other environment details and versions:**
VS code, Mac

**Comment by nadeeshaan** [comment]
This is because we did not support definition within the forever blocks. Since this syntax is no longer valid on the latest spec, we are closing the issue.
