### ISSUE TITLE
Error in  Config BBE

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#20355]
**Description:**
$subject and the content is not clear. 

**Steps to reproduce:**
Run the BBE [Config](https://ballerina.io/learn/by-example/config-api.html).

**Affected Versions:**
Plugin version: 1.0.5
Ballerina version: j1.1.0-alpha

**Comment by pubudu91** [comment]
#20362 needs to be fixed for this to work

**Comment by pubudu91** [comment]
Had a chat with Kavindu about this. The description in the .out file needs to be improved to avoid confusion.
