### ISSUE TITLE
Issues in Style guideline 

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#20352]
**Description:**
Found the following bugs in the Ballerina Style Guide.

_In /style-guide/definitions,_
**1) Top Level definitions**

Code block showing incorrect indentation is not indented at all.
Variable 'repititions' to be corrected as 'repetitions'.
![5](https://user-images.githubusercontent.com/27485094/70687694-e55e5d80-1cd5-11ea-945e-2b9efe7c80c2.png)

**2) Object definition**

Required parameter not allowed after defaultable parameters.
![6](https://user-images.githubusercontent.com/27485094/70687957-9e249c80-1cd6-11ea-9353-1702e83e1a84.png)

_In style-guide/statements,_
**3) Match statement**

Missing curly braces surrounding the return statement in line 3.
![7](https://user-images.githubusercontent.com/27485094/70688104-f360ae00-1cd6-11ea-961b-d0415b204c32.png)

_In style-guide/expressions,_
**4) Map literal**

Incompatible types in the variable mapOfString. Expected 'string', found 'int'.
![9](https://user-images.githubusercontent.com/27485094/70688315-7f72d580-1cd7-11ea-8816-39d579b4e9e2.png)

**5)Tuple**

Invalid token. Replace with square brackets.
![10](https://user-images.githubusercontent.com/27485094/70688473-e4c6c680-1cd7-11ea-95e9-7bd3abf466b5.png)

**6) Table literal**

Redeclared symbol 'employee3' in line 22.

_In style-guide/,_
**7) Line spacing**

Variable arrayOfString contains an array of integers. Also missing a semicolon at the end.
![1](https://user-images.githubusercontent.com/27485094/70688931-ddec8380-1cd8-11ea-9bf3-952e909ed7ae.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/161
