### ISSUE TITLE
Encrypted configs not working

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-lang#20362]
**Description:**
Secret key prompt is passed over when using an encrypted value in ballerina.conf. Doesn't read from secret.txt either (both ballerina build and ballerina run).

**Steps to reproduce:**
"Configure Secrets as Configuration Items" in https://ballerina.io/learn/how-to-deploy-and-run-ballerina-programs/

**Affected Versions:**
1.1.0-rc2

**Comment by pubudu91** [comment]
Tested this and this seems to happen only when trying to run a `.bal` file or a module. Running the JAR file using `ballerina run program.jar` or `java -jar program.jar` is working.

**Comment by pubudu91** [comment]
Closing this since this issue was fixed in #20371

**Comment by pubudu91** [comment]
Reopening this since this problem is still there for the default config file (ballerina.conf).

**Comment by warunalakshitha** [comment]
This happen when you have ballerina.conf file in same directory path. Workaround is to pass the config file with --b7a.config.file=<path> without keeping ballerina.conf file in same root path when you have encrypted values.

BTw original issue needs to be fix. It requires an api change.

**Comment by warunalakshitha** [comment]
This issue is fixed with latest refactor with creating jars with same compiler process. Verified in ballerina 1.2.0. Hence closing issue.
