### ISSUE TITLE
AWS Lambda Deployed function fails executing

### ISSUE THREAD

**Issue by Samuelvdc** [ballerina-platform/ballerina-lang#20375]
**Description:**
When deploying Ballerina build to AWS Lambda, the lambda function is correctly created on AWS. But fails when executing the function:
`Error: &{0xc000092240 map[error:Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] invoke_id:a180f948-3643-47a2-a8c6-b087aa34f7fe sandbox_id:0] `

**Steps to reproduce:**
```bash
ballerina --version # Ballerina 1.0.5
ballerina build lambda-example.bal  # Content see below

export FUNCTION_NAME=ballerina-test-2
export LAMBDA_ROLE_ARN=arn:aws:iam::xxxxxxxx:role/lambda_basic_execution

aws --version  # aws-cli/1.16.292 Python/3.7.5 Darwin/18.7.0 botocore/1.12.253
aws lambda create-function --function-name $FUNCTION_NAME --zip-file fileb://aws-ballerina-lambda-functions.zip --handler lambda-example.$FUNCTION_NAME --runtime provided --role $
LAMBDA_ROLE_ARN --timeout 10 --memory-size 1024

aws lambda invoke --function-name $FUNCTION_NAME out --log-type Tail --query 'LogResult' --output text | base64 -D
```
Following error when excecuting lamdbda function:
```
START RequestId: a180f948-3643-47a2-a8c6-b087aa34f7fe Version: $LATEST
END RequestId: a180f948-3643-47a2-a8c6-b087aa34f7fe
REPORT RequestId: a180f948-3643-47a2-a8c6-b087aa34f7fe  Duration: 34.43 ms      Billed Duration: 100 ms Memory Size: 1024 MB    Max Memory Used: 11 MB
RequestId: a180f948-3643-47a2-a8c6-b087aa34f7fe Error: &{0xc000092240 map[error:Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap] invoke_id:a180f948-3643-47a2-a8c6-b087aa34f7fe sandbox_id:0] 2019-12-12 15:41:11.652590122 +0000 UTC m=+0.005949908 panic <nil> Failed to locate runtime bootstrap <nil> }
Runtime.ExitError
```

Used following test ballerina code:
```
import ballerinax/awslambda;

@awslambda:Function
public function echo(awslambda:Context ctx, json input) returns json|error {
   return input;
}
```
**Affected Versions:**
Ballerina version 1.0.5

Tested on 
* MacOS version 10.14.6
* AWS CLI version aws-cli/1.16.292 Python/3.7.5 Darwin/18.7.0 botocore/1.12.253

**

**Comment by lafernando** [comment]
Hi,

You've actually missed one step of associating the lambda layer with the function. This is the execution runtime required to run the lambda function. This is done with a "aws lambda update-function-configuration" command again -- this actually can be merged to the "create-function" command also though. Basically, you need the following command to be run:-

aws lambda update-function-configuration --function-name $FUNCTION_NAME --layers arn:aws:lambda:$REGION_ID:141896495686:layer:ballerina:2

Put the respective $REGION_ID value, e.g. "us-east-1".

Cheers,
Anjana.

**Comment by wggihan** [comment]
@Samuelvdc I am closing issue now. Please reopen again if you need further assistance.
