### ISSUE TITLE
Node parent getting null for function parameters

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#20381]
**Description:**

I'm using the LSModuleCompiler. When the compiler returns the BLang packages, the parent node of BLangSimpleVariable typed variables in function parameters is null.

This is the code I tried.
`function f2(string str, int i) {
    int y = i;
}
`

This is the debug value I've got.
![image](https://user-images.githubusercontent.com/16335290/70768877-38dfb280-1d8d-11ea-90f3-e919c88d21da.png)

**Steps to reproduce:**

1. Paste the code
2. Get BLang packages of the file using LSModuleCompiler

**Affected Versions:**
1.0.5

**Comment by NipunaMarcus** [comment]
This issue currently blocking the Ballerina Linter feature which needs to be sent on 1.2.0 release as it is already completed and awaiting a fix for this issue. So it is an L1 for us.

**Comment by gigara** [comment]
This issue is affecting to annotation attachments also.
![image](https://user-images.githubusercontent.com/16335290/74718196-b9bc9e00-5257-11ea-9bba-de42ae563175.png)

**Comment by gigara** [comment]
Fixed by d689737
