### ISSUE TITLE
Failed to build Ballerina program on AWS

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#20388]
**Description:**
`ballerina build` command fails to execute on AWS without java installed.

![image](https://user-images.githubusercontent.com/9639050/70776189-61be7280-1da2-11ea-9a57-9da375206cc4.png)

![image](https://user-images.githubusercontent.com/9639050/70776197-67b45380-1da2-11ea-9a58-890a63c20060.png)

![image](https://user-images.githubusercontent.com/9639050/70776205-6f73f800-1da2-11ea-8818-6904faf898dc.png)

**Affected Versions:**
Ballerina 1.1.0-alpha

**OS, DB, other environment details and versions:**
Ubuntu 19.04

**Comment by lankavitharana** [comment]
PR merged, hence closing
