### ISSUE TITLE
BType doesn't contain type name 

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#20386]
```ballerina
public type MyRecord record {
    Type1  myField;
};

const TYPE1_CONST = "type1";
public type Type1 TYPE1_CONST;
```

For above source, in ast node for field "myField",  the type name "Type1" is missing in BType node (But it is there in BLangType node).

<img width="604" alt="Screenshot 2019-12-13 at 11 39 49" src="https://user-images.githubusercontent.com/1505855/70773436-7ba98680-1d9d-11ea-8ee2-88d356f10e55.png">

**Comment by hasithaa** [comment]
@pubudu91 This is a duplicate, Could you please link the current issue and close it.

**Comment by pubudu91** [comment]
The root cause is #26284 I believe. An updated/relevant issue of this is #27190
