### ISSUE TITLE
Compilation error when the importing ballerina module is provided using a local balo 

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#20404]
**Description:**
When a user follows the steps mentioned in the below section, he will get a Sad Bad Error.
```
[2019-12-13 13:43:10,941] SEVERE {b7a.log.crash} - ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)V
java.lang.NoSuchMethodError: ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)V
at wso2.petstore.___init.$moduleInit(petstore:65535)
at wso2.petstore.___init.$lambda$$moduleInit$(petstore)
at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:426)
at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:218)
at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:191)
at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**
Create three ballerina modules and let's call them A, B and C.
C imports B and B imports A.
First, build the module A. Then refer to module A, inside module B's Ballerina.toml file using the locally create balo file. Then build module B.
Finally, build the module C. 

**Affected Versions:**
v1.0.5

**OS, DB, other environment details and versions:**
MacOS-Mojave

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Can you explain what do you mean by `Then refer to module A, inside module B's Ballerina.toml file using the locally create balo file.`?
Is it adding a platform dependency to the previously build jar?

**Comment by SupunS** [comment]
As per the stacktrace, this is most probably caused due to the dependency (A) was built by one version of ballerina, and the dependent (B/C) is being built by another version of ballerina. Then the generated bytecodes (methods) does not match with each other.

Try cleaning up any cashes, and build all three modules form the same ballerina version.

**Comment by VirajSalaka** [comment]
When all local caches (<HOME>/.ballerina) have been updated manually it started to work with no issue. This scenario has not been tested recently as there was no requirement to refer to the module using the balo path as ballerina central was updated with the required changes.

**Comment by SupunS** [comment]
Great! I will close this issue then, assuming this was a problem due to old caches.

Please do reopen, if you came across this issue once again.
