### ISSUE TITLE
ballerina run dont work if unless we navigate to the directory where the bal fil exist and execute run command

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#20454]
Please check the below output.

```ballerina
➜   ✗ ballerina run iterable-objects/iterable_objects.bal 
error: no ballerina source files found in module 'iterable_objects.bal'
➜   ✗ ballerina -v
jBallerina 1.1.0-beta2
Language specification 2019R3
Command 0.8.0
```

**Comment by hemikak** [comment]
This happens when you run from the root of a ballerina project. I think we still need to handle it.

**Comment by gimantha** [comment]
> This happens when you run from the root of a ballerina project. I think we still need to handle it.

i simply created a pack from the source.. extracted it, created a new folder in bin then put a bal file inside that new folder.. then got out of that folder and executed 
`./ballerina run <new folder>/<bal-file.bal>.
`
Still it gives me the same error
