### ISSUE TITLE
io:readln won't work as expected with ballerina single file run

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#20456]
**Description:**
Run the below code. Println won't print.

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    string st = io:readln("enter: ");
    io:println(st);
}
```

**Affected Versions:**
1.1.0-beta

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Checked this in 1.1.0-beta2, it's working as expected.
