### ISSUE TITLE
Config values not being read when deployed to Docker

### ISSUE THREAD

**Issue by dinuish94** [ballerina-platform/ballerina-lang#20460]
**Description:**
When a ballerina project is deployed to Docker, the values in the configuration file cannot be read. It returns an empty string.

**Steps to reproduce:**
1. Create a ballerina project and create below service.

```
import ballerina/http;
import ballerina/config;
import ballerina/docker;

@docker:Config {
    push: true,
    registry: "index.docker.io/$env{DOCKER_USERNAME}",
    name: "testconfig",
    tag: "v2.0.0",
    username: "$env{DOCKER_USERNAME}",
    password: "$env{DOCKER_PASSWORD}"
}
@http:ServiceConfig {
    basePath:"/"
}
service serviceName on new http:Listener(8000) {

    @http:ResourceConfig {
        path: "/test",
        methods: ["GET"]
    }
    resource function test(http:Caller caller, http:Request request) {
        http:Response response = new();
        response.setPayload("Test configuration Value: " + config:getAsString("TEST"));
        var result = caller->respond(response);
    }
}
```

2. Create a ballerina.conf file in root directory of the project and configure the following.

```
TEST="Hello World"
```
3. Build the project and run on docker. Following response is observed with an empty string for the configuration value.

```
Test configuration Value: 
```

It can be observed that when it is deployed on JVM, it returns the expected result as below.

```
Test configuration Value: Hello World  
```

**Affected Versions:**
Ballerina 1.0.2

**Comment by warunalakshitha** [comment]
Can you check with adding below config to bal file.

@docker:CopyFiles {
files: [
        { sourceFile: "ballerina.conf", target: "/home/ballerina/ballerina.conf", isBallerinaConf: true }
]
}

**Comment by warunalakshitha** [comment]
I have tested the bal file with above config. Closing the issue. Please reopen if you need further clarification on this.
