### ISSUE TITLE
Build time increased

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#20462]
Tested on 1.0.2, 1.0.5 and 1.1.0-beta2 versions on Windows (
Microsoft Windows [Version 10.0.18363.535])

Time measured for ballerina build command by compiling [hello.bal.txt](https://github.com/ballerina-platform/ballerina-lang/files/3978963/hello.bal.txt)

The following are the results.

1.0.2 - 32.7397424 s
1.0.5 - 47.6342059 s
1.1.0-beta2 - 66.6935305 s

**Comment by hasithaa** [comment]
Here is the task break down. The following are average values on 3 test runs. 

  | 1.0.2 | 1.0.5 | 1.1.0-beta2
-- | -- | -- | --
CreateTargetDirTask | 4 | 5 | 6
CompileTask | 1915 | 2041 | 2014
CreateBirTask | 8 | 9 | 8
CopyNativeLibTask | 224 | 94 | 88
CreateJarTask | 3242 | 3212 | 6882
CopyModuleJarTask | 110 | 54 | 58
CreateExecutableTask | 6801 | 17878 | 18708
CopyExecutableTask | 254 | 232 | 208
PrintExecutablePathTask | 1 | 2 | 0
RunCompilerPluginTask | 9 | 12 | 11
CleanTargetDirTask | 42 | 11 | 11
Total | 12610 | 23549 | 27995

**Comment by Kishanthan** [comment]
This table no longer valid as we have improved compilation time of codegen phase significantly with 1.2.x releases.

**Comment by mohanvive** [comment]
Closing the issue because details are outdated now.
