### ISSUE TITLE
ballerina help version description has typos when trying in Solaris

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#20473]
Refer to the below screenshot.

![image](https://user-images.githubusercontent.com/9362271/71163655-91262100-2273-11ea-832d-2fa2722be191.png)

This can only reproduced in Solaris. In other OSes, it shows the correct command `ballerina --version`

Affected Tool version 0.8.1

**Comment by MaryamZi** [comment]
Fixed with #20474.
