### ISSUE TITLE
A code statement wrapped in parenthesis and followed by a period gives a compilation error

### ISSUE THREAD

**Issue by DeveloperLK** [ballerina-platform/ballerina-lang#20475]
**Description:**
(`code statement`).`code statement` gives the following compilation error:
 
_error: mismatched input '.'. expecting {'is', ';', '?', '+', '-', '*', '/', '%', '==', '!=', '>', '<', '>=', '<=', '&&', '||', '===', '!==', '&', '^', '...', '|', '?:', '->>', '..<'}_

**Steps to reproduce:**
```
public function main() returns  error? {
    
    var x = (getNumber()).toString();
    io:println(x);

}

function getNumber() returns float{
    return 2.0;
}
```
**Affected Versions:**
Ballerina v1.0.3
**OS, DB, other environment details and versions:**
Ubuntu 18.04(Linux)

**Comment by MaryamZi** [comment]
This particular scenario is fixed, and the fix will be available with 1.1.0.

Issue https://github.com/ballerina-platform/ballerina-lang/issues/19020 tracks fixing this for all scenarios.
