### ISSUE TITLE
rabbitmq_consumer.bal copy clip board option copies invalid source

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#20472]
**Description:**
$title, when pasted, added a block comment at the end of the source giving compilation errors

**Steps to reproduce:**
Copy to clip board and paste it on the editor

**Affected Versions:**
v1.1.0-alpha at least

**Comment by aashikam** [comment]
As per the discussion with @kaviththiranga this is an issue in the site. i have checked this issue with several other examples and few other examples also have this same issue.
