### ISSUE TITLE
Ballerina installing error in linux 

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#20484]
**Description:**
I've tried to installed `ballerina-linux-installer-x64-1.1.0.deb` and got the following error.

![image](https://user-images.githubusercontent.com/16335290/71231618-c46cbc80-2314-11ea-9499-1e8e21e1bd42.png)

It seems like the previous installation directory is conflicting with the new one and cannot update the previous files through the installer.

**Steps to reproduce:**
Download ballerina-linux-installer-x64-1.1.0.deb and install

**Affected Versions:**
Ballerina 1.1.0

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by MaryamZi** [comment]
IINM, this is the same as https://github.com/ballerina-platform/ballerina-distribution/issues/244. @keizer619?

**Comment by keizer619** [comment]
yes its same issue, hence closing this
