### ISSUE TITLE
How to map varargs for java inter-op

### ISSUE THREAD

**Issue by reidlai** [ballerina-platform/ballerina-lang#20497]
I know Ballerina can use varargs to call java class like the example in Ballerina by Example using asList funtction of "java.util.Arrays".

Now I need to call Jedis hdel method like this
```java
  /**
   * Remove the specified field from an hash stored at key.
   * <p>
   * <b>Time complexity:</b> O(1)
   * @param key
   * @param fields
   * @return If the field was present in the hash it is deleted and 1 is returned, otherwise 0 is
   *         returned and no operation is performed.
   */
  @Override
  public Long hdel(final String key, final String... fields) {
    checkIsInMultiOrPipeline();
    client.hdel(key, fields);
    return client.getIntegerReply();
  }
```

So i have defined a external function to map jedis hdel like below:

```ballerina
function hdel(handle receiver, handle key, handle... fields) returns int = @java:Method {
    class: "redis/clients/jedis/Jedis",
    paramTypes: ["java.lang.String", "java.util.Arrays"]
} external;
```

I got this error when i build my project:

{ballerinax/java}METHOD_NOT_FOUND message=No such public method 'hdel' that matches with parameter types '(java.lang.String,java.util.Arrays)' found in class 'class redis.clients.jedis.Jedis'

I don't know which java class can help me map varargs.  Any help there?

**Comment by SupunS** [comment]
@reidlai Whats the ballerina version you are using?

Seems your ballerina function has 3 parameters and the java function has only 2 parameters. You might have to correct that first.

With respect to the varargs type, if  the java `hdel` method has no overloaded methods, then you can simply use:
```ballerina
function hdel(handle key, handle... fields) returns int = @java:Method {
    class: "redis/clients/jedis/Jedis"
} external;
```

Else, you can specifically mention the parameter type as follow:
```ballerina
function hdel(handle key, handle... fields) returns int = @java:Method {
    class: "redis/clients/jedis/Jedis",
    paramTypes: ["java.lang.String", {class:"java.lang.String", dimensions:1}]
} external;

**Comment by reidlai** [comment]
> @reidlai Whats the ballerina version you are using?
> 
> Seems your ballerina function has 3 parameters and the java function has only 2 parameters. You might have to correct that first.
> 
> With respect to the varargs type, if the java `hdel` method has no overloaded methods, then you can simply use:
> 
> ```ballerina
> function hdel(handle key, handle... fields) returns int = @java:Method {
>     class: "redis/clients/jedis/Jedis"
> } external;
> ```
> 
> Else, you can specifically mention the parameter type as follow:
> 
> ```ballerina
> function hdel(handle key, handle... fields) returns int = @java:Method {
>     class: "redis/clients/jedis/Jedis",
>     paramTypes: ["java.lang.String", {class:"java.lang.String", dimensions:1}]
> } external;
> ```

It is great coz Ballerina 1.0 keeps on to complain me about paramTypes mapping...really thx

**Comment by Kishanthan** [comment]
@reidlai , since the question is answered, we are closing this issue. Please do reopen, if you have further queries.
