### ISSUE TITLE
Invalid suggestions inside documentation

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#20572]
**Description:**
Please refer the sample below. IMO it would be better if we can only suggest variable references which are available within the scope as completion items.

![Screenshot from 2020-01-13 11-31-47](https://user-images.githubusercontent.com/29032600/72235530-b0a53500-35f8-11ea-942b-30b710e10961.png)

**Steps to reproduce:**
Please use the sample code snippet above.

**Affected Versions:**
jballerina 1.1.0 and below

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
While #21067 avoid the suggestions within the doc comments, with a proper design we should provide the function argument suggestions later.

**Comment by NipunaRanasinghe** [comment]
> While #21067 avoid the suggestions within the doc comments, with a proper design we should provide the function argument suggestions later.

@nadeeshaan Ack and +1. So shall we create and maintain a separate issue to track adding auto completion support for ballerina documentation?

**Comment by nadeeshaan** [comment]
> > While #21067 avoid the suggestions within the doc comments, with a proper design we should provide the function argument suggestions later.
> 
> @nadeeshaan Ack and +1. So shall we create and maintain a separate issue to track adding auto completion support for ballerina documentation? :)

@NipunaRanasinghe, created a new issue to track it separately. #21116
