### ISSUE TITLE
Java interop error gives a wrong line number in the stacktrace

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/ballerina-lang#20576]
**Description:**
Invalid line of code is given in error messages

Eg: 

java.lang.ClassCastException message=org.wso2.mongo.MongoDBDataSource cannot be cast to org.ballerinalang.jvm.values.HandleValue
                at wso2.mongodb:insertData(endpoint.bal:**65535**)
                wso2.mongodb.Client:insert(endpoint.bal:53)
                wso2.mongodb.tests.main_test:testInsertData(tests/main_test.bal:35)

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by irshadnilam** [comment]
Hi @dulanjalidilmi 
Would you be able to share the code snippet that produces this error?
