### ISSUE TITLE
It's difficult to find what makes a function return tainted value

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#20573]
**Description:**
Consider the error message:
`functions returning tainted value are required to annotate return signature @tainted:`

When we get this error in a long function it's diffucult to figureout which return/check statement made this function retun a tainted value. It's would be better if which functions inside the considered function originated the tainted values.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Note: We have made taint analysis experimental again in SL. This is one of the pain points we see in the current implementation.

**Comment by hasithaa** [comment]
We are removing the Current taint analysis implementation with #30981, Hence closing this issue.
