### ISSUE TITLE
Red underline with code taken from youtube and online

### ISSUE THREAD

**Issue by thepowderriverfarrier** [ballerina-platform/ballerina-lang#20585]
**Description:**
A copy and paste of:  string body = check request.getTextPayload();
does not appear to work on Windows 10 using Ballerina 1.1.0

Following the online examples the code is listed below:
```
import ballerina/http;

@http:ServiceConfig {
    basePath:"/"
}

service annotated on new http:Listener(9898){

    @http:ResourceConfig {
        path:"/annotationspath",
        methods: ["POST "]
    }
    resource function beenAnnotated(http:Caller caller, http:Request request){
        var headerNames = request.getHeaderNames();
        string body = check request.getTextPayload()
        error? result = caller -> respond("You've been annotated from " + body);
    }
}
```

**Comment by pubudu91** [comment]
May we know from where you got this code? There's a missing semi colon and a few semantic errors in the above code. Given below is a version of it, updated to work with 1.1.0.
```ballerina
import ballerina/http;

@http:ServiceConfig {
    basePath:"/"
}

service annotated on new http:Listener(9898){

    @http:ResourceConfig {
        path:"/annotationspath",
        methods: ["POST "]
    }
    resource function beenAnnotated(http:Caller caller, http:Request request) returns error? {
        var headerNames = request.getHeaderNames();
        string body = check <@untainted> request.getTextPayload();
        error? result = caller -> respond("You've been annotated from " + body);
    }
}
```

**Comment by thepowderriverfarrier** [comment]
It was on one of the youtube videos.

**Comment by thepowderriverfarrier** [comment]
Even with the semicolon correctly placed it was generating the red underscore.

**Comment by pubudu91** [comment]
Yes, as I mentioned above, there were semantic errors in the code as well, apart from the syntax error. Did you try the corrected code above? Also please note that YouTube videos, blog posts you come across may be outdated, especially if they are from pre 1.0.0.

**Comment by MaryamZi** [comment]
@thepowderriverfarrier, hope the updated sample @pubudu91 shared worked with 1.1.0.

Please feel free to reopen the issue if you have further concerns.
