### ISSUE TITLE
[Packerina Spec] Passing java command options, system properties from ballerina script to executable process

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#20635]
**Description:**
When we execute 'ballerina run module ' , module will be executed as follows.

1) build the module and create executable
2) run the executable with new java process to use separate class loader. 

ATM we do not pass any java command options like  initial and maximum size of the heap, heap dump path which are specified in ballerina startup script. Since executable run via packerina code, there is no way to pass those options as well. 

Hence IMO we need to pass all options to new java process from its parent process which are specified through ballerina startup script.

**Comment by anupama-pathirage** [comment]
This is currently not part of our plans or a priority, so we are closing the issue for now. We will reopen it if we decide to pursue this in the future.
