### ISSUE TITLE
Invalid worker identifier position in flush action

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#20639]
**Description:**
Consider the following code example,

```
function testFlush() {
    worker w1 {
        int x = 2;
        x -> w2;
        error? e = flush w2;
    }

    worker w2 {
        int s = <- w1;
    }

    _ = wait {w1, w2};
}
```

In the `error? e = flush w2;` statement, when we try to get the position of w2, it gives the position of the whole statement

**Affected Versions:**
v1.1.0 at least

**Comment by MaryamZi** [comment]
`flushExpr.workerIdentifier.pos` seems to be `(4:25,4:27)(0,0)` on master.

@nadeeshaan, anything else that needs to be fixed here?

**Comment by nadeeshaan** [comment]
> `flushExpr.workerIdentifier.pos` seems to be `(4:25,4:27)(0,0)` on master.
> 
> @nadeeshaan, anything else that needs to be fixed here?

This issue has been fixed in the latest master. Hence closing the issue
