### ISSUE TITLE
[Packerina Spec]  Getting ballerina home at runtime

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#20634]
**Description:**
Ballerina examples use ${ballerina.home} to get the location of the ballerina home. ex 
https://ballerina.io/v1-1/learn/by-example/config-api.html

**ballerina.home** java property is set by ballerina startup script. This will work only for bal files since we use same jvm with those java properties when running bal. But same example code will not work when we run with modules. ex. ballerina run module. This is because internally we create child process to execute the build executable. So ballerina.home will not pass to the child process.

Same example will not work when we run as self contained jar. ( java -jar exectable.jar)
IMO we need to get rid of with ballerina home property and replace those with proper ballerina configs.

```
ex --ballerina.home=<ballerina home path> and then you need to change the ballerina file as follows.
 path: config:getAsString("ballerina.home") + "/bre/security/ballerinaKeystore.p12"

```

**Comment by azinneera** [comment]
This is not applicable for Swan Lake.
