### ISSUE TITLE
Ballerina run, runs files inside a ballerina module

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#20648]
**Description:**
If you run a bal file which is in a ballerina module it runs without an error. 

**Steps to reproduce:**
- Create a new ballerina project and a main module. 
- Move in to the created module ie. <project-dir>/src/myModule/
- Try running a bal file.  ie. $ballerina run main.bal

Also if you try to run the same bal file in a different location it gives the following error which is difficult to understand.
`error: no ballerina source files found in module 'main.bal'`

Suggested change 
'main.bal' is part of  a ballerina module and cannot be run directly. Try running ballerina run 'module-name' from the root of the project directory. 

**Affected Versions:**
1.1.0

**OS, DB, other environment details and versions:**
Ubuntu

**Comment by warunalakshitha** [comment]
Also if you try to run the same bal file in a different location it gives the following error which is difficult to understand.
error: no ballerina source files found in module 'main.bal'

This error will be fix with https://github.com/ballerina-platform/ballerina-lang/issues/18786. But we need to check whether we can avoid running bal files inside module.
