### ISSUE TITLE
__init method of objects are highlighted as a keyword in IntelliJ

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20641]
Refer to the screenshot below. The `__init()` method should not be highlighted as a keyword. It's just another method in the object. 
![Screenshot from 2020-01-16 17-03-03](https://user-images.githubusercontent.com/6260009/72521891-69ca7000-3882-11ea-9e0e-71342c5091c8.png)

**Comment by NipunaRanasinghe** [comment]
@pubudu91 Yeah you are correct in a way and on the other side, `__init` has a special purpose and also **declared as a reserved word** in ballerina grammar definitions as well. Therefore IMO it would be better if developers will be aware that the it deviate from the other functions. 

WDYT? should we think of another approach to let the users know that it's a reserved word?

**Comment by NipunaRanasinghe** [comment]
Closing w.r.t offline discussion with @pubudu91.
