### ISSUE TITLE
[IntelliJ] Error in auto-generated subscription config field in NATS

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#20654]
**Description:**
Error when individual NATS streaming subscription config fields are generated by the IDEA plugin. 

**Steps to reproduce:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39673615/72593229-7acebc00-392a-11ea-844e-02c1ebd1ebdd.gif)

**Affected Versions:**
Ballerina version 1.1.0
IDEA plugin version 1.1.0

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with #21027.
