### ISSUE TITLE
Implement langlib.xml functions to support new xml proposal.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#20666]
**Description:**
We need to implement the xml langlib functions to support the [xml proposal.](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md)

Proposed langlib functions [https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.bal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.bal)

This is a part of https://github.com/ballerina-platform/ballerina-lang/issues/19570

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by irshadnilam** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21603
