### ISSUE TITLE
Implementing semantic syntax highlighting for Ballerina VScode plugin

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#20669]
**Description:**

Aim of implementing semantic syntax highlighting is to enrich the syntax highlighting using the information in the ballerina AST and the vscode's DocumentHighlightProvider API. 

- Backend implementation - Develop a language server extension that provides the smart syntax highlighting information.
- Frontend implementation - Develop a syntax highlighting provider using vscode's DocumentHighlightProvider API. 

The proposed language server implementation specification for Semantic Syntax Highlighting can be found [here](https://github.com/microsoft/vscode-languageserver-node/blob/5a9b33c23de84c3341e011e79221795a8059375b/protocol/src/protocol.semanticHighlighting.proposed.md).
The specification document for the Ballerina vscode plugin can be found [here](https://docs.google.com/document/d/1abu9tPDYbIQUeo_0eFHDbx7huO1aMNj3JtayBHe92r0/).

**Comment by nadeeshaan** [comment]
Implementation for highlighting the endpoint variables are done and merged with https://github.com/ballerina-platform/ballerina-lang/pull/20200.

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
