### ISSUE TITLE
Need more helpful compiler error message

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#20675]
**Description:**
So I wrote following code:
```ballerina
http:Listener httpListener = new (9090, ());

service hello on httpListener {
 // some other stuff.
}

```
VS Code complained me with a message `invalid listener attachment`. 
In my opinion this message doesn't give me an indication/direction on where I made the mistake.
how about if we rephrase the message along the lines of `httpListener` is not of a type `listener` therefore you can't attach.
That would have made me look at why is my `httpListener` is not a `listener`.
which is exactly my second question:
why is `httpListener` is not a listener? 

**Steps to reproduce:**
put above code in a bal file and compile
**Affected Versions:**
1.1.0
**OS, DB, other environment details and versions:**
MacOs
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
I think the mistake here is, missing listener declaration.  I agree that the error message should be improved here. 

```ballerina
listener http:Listener httpListener = new (9090, ());

service hello on httpListener {
 // some other stuff.
}
```

**Comment by ramith** [comment]
@hasithaa having to write **listener** http:Listener seems redundant isn't it ?

**Comment by MaryamZi** [comment]
`listener http:Listener l = new (8080)` is a "listener declaration". For such listener declarations, the listener life-cycle methods (`__attach()`, `__start()`, `__xxxStop()`) are invoked automatically during module init, stop, etc.

But with just `http:Listener l = new (8080)`, these are not invoked automatically. A developer could define such a variable and use it to explicitly attach a service(s) and start when required.

```ballerina
import ballerina/http;

public function startService() {
    http:Listener l = new (8080);

    service s = 
    @http:ServiceConfig {
        basePath: "/foo"
    }
    service {
        resource function bar(http:Caller caller, http:Request request) {
            checkpanic caller->respond("Hello World");
        }
    };
    
    checkpanic l.__attach(s);
    checkpanic l.__start(); // the listener is only started here
}
```

**Comment by gimantha** [comment]
Closing the issue for the moment, we will be revisiting the issue later
