### ISSUE TITLE
HANA DB error for create/update statements - "Invalid argument autoGeneratedKeys"

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#20673]
**Description:**
SQL updates/create statements report an error when interfacing with sap HANA DB - "Invalid arguemnt autoGeneratedKeys". This is reproduced after being reported on slack.

**Steps to reproduce:**

1. CREATE
`CREATE TABLE student(id INT, age INT, name VARCHAR(255), insertedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP`

`Create student table failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

2. INSERT
`INSERT INTO student(age, name) values (?, ?)`

`Insert to student table with variable parameters failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

3. UPDATE statement
`UPDATE student set name = 'jane' WHERE age = ?`

`Update a row in student table failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

4. DELETE statement
`DELETE FROM student WHERE age = ?`

`Delete a row from student table failed: failed to execute update query: Invalid argument autoGeneratedKeys, use NO_GENERATED_KEYS..`

**Affected Versions:**
jBallerina 1.1.0
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
macOS Catalina : v10.15.2(19C57) 
HANA DB : v2.00.040.00.1553674765 (HDB -v)

**Suggested Labels (optional):**
Area/StandardLibs, Component/Data, Type/Bug,

**Suggested Assignees (optional):**
KRVPerera

**Comment by daneshk** [comment]
This issue is already addressed in the latest releases. Hense closing
