### ISSUE TITLE
[gRPC][Stub generator] Error downloading protoc executor file - protoc-linux-x86_64.exe

### ISSUE THREAD

**Issue by JasonMiesionczek** [ballerina-platform/ballerina-lang#20691]
**Description:**
Trying to generate gRPC service stubs, getting the following error:
Error while generating protoc executable. Error while downloading the file: protoc-linux-x86_64.exe.download

**Steps to reproduce:**
ballerina grpc --input file.proto --output dir --mode service

**Affected Versions:**
jBallerina: 1.1.0
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
Ubuntu 19.04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
@JasonMiesionczek Thanks for reporting the issue

This is to the change in protoc executable download URL. When we execute the stub generation command, It downloads the protoc executable from URL[1]. but recently mvn central repository is moved to HTTPS. Please check the article[2] for more information.
We already identify the issue [3] and fixed it and It will come in the next release(1.1.1) which is due next week.

1. http://repo1.maven.org/maven2/com/google/protobuf/protoc/3.9.1/protoc-linux-x86_64.exe
2. https://blog.sonatype.com/central-repository-moving-to-https
3. https://github.com/ballerina-platform/ballerina-lang/issues/20623

Until we release the next version, As a workaround, you can download the executable manually from the URL [4] and copy it to the Linux temp(/tmp) directory and change the name to `protoc-linux-x86_64.exe` and then execute the command again to generate the stubs.

4. https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.9.1/protoc-linux-x86_64.exe

Sorry for the inconvenience. Please let us know if you find any issues when following the workaround.

**Comment by JasonMiesionczek** [comment]
Great to hear! the work around, worked :) Thanks.
