### ISSUE TITLE
Add support for some functional aspect to annotations.

### ISSUE THREAD

**Issue by NCPlayz** [ballerina-platform/ballerina-lang#20719]
**Description:**
What I am trying to do is to be able to add an annotated function to a `MyRecord[]`, but currently this is not possible as you can only assign fields to a record. 

Perhaps allow annotations to be objects as well.
Example:
```bal
import ballerina/io;

final Annot[] annotatedInstances = [];

type Annot object {
    public string s;
    public function(string) f;

    function __init(any instance, string s) { // instance is always passed
        self.s = s;
        self.f = <function(string)>instance;
        annotatedInstances[annotatedInstances.length()] = self;
    }
};

annotation Annot ann on function;

@ann ( "hello" )
function hello(string s) {
    io:println(s);
}
```
This would then allow for something like:
```bal
foreach var instance in annotatedInstances {
    instance.f(instance.s); 
}
```
Another solution is to allow functions, to become Python-like decorators.

**Comment by hasithaa** [comment]
This improvement request is marked as "Deferred" and will be revisited in the future when resources are available.
