### ISSUE TITLE
Tooling changes for variable name as mapping constructor field

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#20756]
**Description:**
Issue to track $title.

```ballerina
type Foo record {|
    string s;
    int i;
|};

const i = 100;

public function main(string s) {
    Foo f = {s, i}; // equivalent to saying `{s: s, i: i}`
}
```

**Related Issues (optional):**
Compiler FE issue - #20706

**Comment by MaryamZi** [comment]
Some changes have been done with https://github.com/ballerina-platform/ballerina-lang/pull/20751/commits/3d6abc527676e87315bf93d3420bf7ef1cda4f62.

Several tests are being disabled temporarily with https://github.com/ballerina-platform/ballerina-lang/pull/20751/commits/41ca6a2fc1c00dddc6338811ef85344ceb82c635.

**Comment by NipunaRanasinghe** [comment]
Reopening since the Intellij plugin support for the new syntax is WIP.

**Comment by NipunaRanasinghe** [comment]
Closing since these support is already added by #21561.
