### ISSUE TITLE
Need to fix formatting and IntelliJ plugin grammar for the new function changes

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20771]
PR #20770 modifies the grammar related to functions and methods. This breaks the formatter in the tooling side. The formatting logic needs to be updated accordingly.

**Comment by NipunaRanasinghe** [comment]
@pubudu91 Kindly note that the ballerina grammar definition changes affects IDEA plugin as it requires to update the plugin grammar definitions accordingly. Therefore shall we keep this issue opened till the plugin side fixes are done?

**Comment by pubudu91** [comment]
+1

**Comment by NipunaRanasinghe** [comment]
Closing since the required changes for IntelliJ plugin and formatting are added with the referred PRs.
