### ISSUE TITLE
Support inject properties/build time inputs to toml file

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#20786]
**Description:**
```
[project]
org-name = "ballerina"
version = "0.0.0"

[[platform.libraries]]
version = "${myjar.version}"
path = "./lib/myjar-${myjar.version}.jar"
```

Here "myjar.version" should be replaces by environment property or any other external build input

**Comment by azinneera** [comment]
Closing since this is being discussed in https://github.com/ballerina-platform/ballerina-spec/issues/1192
