### ISSUE TITLE
[Packerina Spec] Ballerina module stage/dev push support to central 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#20788]
**Description:**
Currently Ballerina Central does not have a stage/dev mode for modules. 

When two modules are being developed separately and one is depending on other. Only way to get latest changes to dependent module is specifying path. 

This could be fine as long as 2 modules have been developed in the same machine. When 2 modules are developed by 2 or more people. Therefore we need to support following;

1. Latest development support - This is just like java SNAPSHOT versions being pushed to nexus. Developers can push latest changes or even  CI/CD automation can push changes.

2. Stage support - This is before released to the public, there has to be a stage for modules. So dependent projects use a staging url and test. Developers and release jobs can push to stage. Finally they can release to public when required testings are being done.

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2-enterprise/ballerina-central/issues/563 to track this.
