### ISSUE TITLE
Improve mapping constructor support in select clause

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#20812]
Related to #20737 

Query expression should support queries like below.

```ballerina
var x =
   from var { firstName, lastName, country } in personList
   where country == "UK"
   select { firstName: firstName, lastName: lastName };

```

**Comment by mohanvive** [comment]
Added more test cases and fixes to comply with this.
- https://github.com/ballerina-platform/ballerina-lang/pull/21160
- https://github.com/ballerina-platform/ballerina-lang/pull/21194
