### ISSUE TITLE
Command sequence for compiling modules

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#20815]
**Description:**
I tried to build the Ballerina [Salesforce module](https://github.com/wso2-ballerina/module-salesforce) using the following command.

`ballerina build -a --skip-tests=true`

Then I get the following error message.

```
Compiling source
        wso2/sfdc46:0.10.1

Creating balos
        target/balo/sfdc46-2019r3-any-0.10.1.balo
error: no entry points found in any of the modules.
Use `ballerina build -c` to compile the modules without building executables.
```
Then I tried only to compile the module as follows.

`ballerina build -c --skip-tests=true`

Then I get an error as follows,

```
ballerina: 'build' command requires a module name or a Ballerina file to build/compile. use '-a' or '--all' flag to build/compile all the modules of the project.

USAGE:
    ballerina build {<ballerina-file> | <module-name> | -a | --all}
```
But when I execute the following command the Salesforce module was built successfully.

`ballerina build -c -a --skip-tests=true`

the output I got after running the above command was as follows,

```
Compiling source
        wso2/sfdc46:0.10.1

Creating balos
        target/balo/sfdc46-2019r3-any-0.10.1.balo
```

Hence I believe that the error message 

> Use `ballerina build -c` to compile the modules without building executables.

should be changed to 

>Use `ballerina build -c -a` to compile the modules without building executables.

If not `-c` has to be added as a compilation option to `ballerina build`.

**Steps to reproduce:**
Please see the above description.

**Affected Versions:**
I found this issue on both Ballerina 1.0.3 and 1.1.0 versions

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
This is fixed in Swan Lake, the command options have been changed in Swan Lake.
