### ISSUE TITLE
Implement stream constructor version 2 (error support, new syntax)

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#20810]
There is a new basic type stream<T,E>, which represents a sequence that may be constructed lazily and is iterable a sequence of values of type T with error type E; stream<T> is short for stream<T,never>.

```ballerina
var x = new stream<xml,error>(foo);

stream<xml,error> x = new(foo);
```

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21524 ...
