### ISSUE TITLE
Cleaning up artifacts of a particular module using `ballerina clean`

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20822]
**Description:**
The current behaviour of the `clean` command is to just simply delete the `target` directory inside the project. Instead of this, would it be possible (and better) to allow the `clean` command accept a list of module names as an arg? Then, only the artifacts of the named modules will be cleaned.

**Affected Versions:**
1.1.0

**Comment by azinneera** [comment]
With SL releases, we create artifacts per package (one for all modules).
