### ISSUE TITLE
[Taint Analysis - Proposal] Have a way to mark a client as untainted, where all remote actions would then be considered to return untainted data

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#20826]
**Description:**
$title. 

Basically the requirement is that even if the remote methods are marked to be returning tainted values, if the client itself is marked as trusted, the return values should also be considered as trusted.

Based on https://github.com/ballerina-platform/ballerina-lang/issues/20530#issuecomment-571444592

**Comment by hasithaa** [comment]
We can make this work, iif client is final. Otherwise, static code analysis will not work.

**Comment by rdhananjaya** [comment]
I think we can make this work, as @hasithaa said the `final` constraint needs to be there.

On top of that `final` guarantee, we need to have another guarantee that this client method does not touch any other data apart from the data coming from the client. I.E. this method can't read a file and somehow combine that information with the information coming from the client. 

Analyzing this is also possible, actually, we already do that, that's how we produce that _return type is not annotated error_. And then we need to extend the taint table to track that this method may or may not produce a tainted value on its own.

@ayomawdb what do you think about this?

**Comment by hasithaa** [comment]
Duplicates https://github.com/ballerina-platform/ballerina-lang/issues/19843
