### ISSUE TITLE
proto to Ballerina converter creates duplicate records when two message definitions contains the same field name of type map

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#20842]
**Description:**
When two message definitions in a proto file contains fields with the same name of type map, two records with the same name is generated. This creates a compilation error.

**Steps to reproduce:**
1. Write a proto file with two message definitions with the same field name of type map
   ```proto
   message Metric {
       ....
       map<string, string> tags = 4;
       ....
   }
   
   message TraceSpan {
       ....
       map<string, string> tags = 5;
       ....
   }
   ```

**Affected Versions:**
Ballerina 1.0.1

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
@daneshk

**Comment by daneshk** [comment]
We are going to use anonymous records for proto maps as shown below,
```ballerina
public type Metric record {|
    record {| int key; string value; |}[] tags = [];
|};

public type TraceSpan record {|
    record {| int key; string value; |}[] tags = [];
|};
```
This will fix the issue of creating duplicate records
