### ISSUE TITLE
Provide java API to get Ballerina reserved literal names 

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#20856]
**Description:**
We don't have a way to get Ballerina reserved literal names. but it is useful to have a Java API to retrieve those reserved words for the tools like grpc,openAPI which is used to generate Ballerina code.

**Comment by hevayo** [comment]
We need this for bindgen tool as well.

**Comment by hasithaa** [comment]
We can add this as part of the new Compiler API.

**Comment by hasithaa** [comment]
@dulajdilshan how are we supporting this requirement now in the LS?
