### ISSUE TITLE
Move default values to the runtime 'type'

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#20851]
**Description:**

Currently default values are part of the 'value' and are populated during the initialisation of the value, by generating code. (e.g: records, objects) This design has several issues:
- There are situations where one can create a value using a type (e.g.: constructFrom, etc). In such cases the default value info is not available at the runtime, in the current model.
- Types can have closures. So the default value (expressions) should be evaluated at the point where the type is initialised, but not the value.

The solution is to make the default value info a part of the runtime type. 

This may also require to separate the type in to two parts as 'shape' and the 'type-descriptor'. Here the 'shape' will only have the type information (such as field names and their types) where as the 'type-descriptor' would have other information such as annotations, default values, etc. Every time a new value is created, a new type-descriptor will also be created. But the 'shape' is common across all instances of that type.
This way, we can make the runtime type checking faster, as it will only have to check for the equality of the 'shape'.

Currently this is a blocker for implementing the record/object default values with expressions (spec deviation).

**Comment by manuranga** [comment]
```
public function main() {
   int x = 20;

   record {
       string name;
       int age = x;
   } person = { name: "Pubudu" };
}
```

Above sample should work after the proper fix. Got it form @pubudu91

**Comment by manuranga** [comment]
# Sample Code:
```ballerina
public function main() returns (error?){
   int x = 20;
   record {
       string name;
       int age = x; 
   } person1 = { name: "Pubudu" };

   var personType = typeof person1;
  
   x = 2;

   var person2 = check personType.constructFrom({ name: "Manu" });


   io:println(person2.age);
}
```

# Solution:
convert `x` to a map representation like we do for lambdas
pass the created map to `NewMap` instruction just like we do for `NewFP`
```
...
        %2 = NewMap map<any | error{string, $anonType$builtin$0}>;
        %6 = ConstLoad 20;
        %5 = <any | error> %6;
        %8 = ConstLoad x;
        %2[%8] = %5;
        %12 = NewMap $anonType$0(%2);
...
```
Values(eg: `person1`) has to keep a reference to the map, because it now needs that value to create type desc when called `typeof`
`TypedescValue` will have an addition value to keep default value map
`BallerinaValues.createRecordValue` should accept additional map to get default values.

**Comment by SupunS** [comment]
I prefer the solution 2, with some minor adjustment. 

Reason for option 2  - Theres another scenario, where people get the 'type' and use it for different purposes in the native code - could be use to create values out of it, or even pass it back to the ballerina code as a typedesc. In that case, if the default values are not with the 'type' that info may not available in these scenarios.

Adjustment -  IIUC, we would not need to keep the map as a closure like in lambdas. What we need to keep is the value of the evaluated-expression. That means once the type is created, changing the value of the refered expressions wouldn't have an impact on the type that created type. Means, in the sample code, `io:println(person2.age);`  should give `20`.

**Comment by manuranga** [comment]
I though `io:println(person2.age)` should be `2`.
@hasithaa @pubudu91 @sameerajayasoma What do you guys think?

btw, we can even simplify last line of above BIR as follows
```
        %9 = NewTypeDesc(%2);
        %12 = NewMap %9;
```

**Comment by pubudu91** [comment]
I also prefer option 2. Option 1 wouldn't work in scenarios like the following right?
```ballerina
public function main() returns (error?){
   int x = 20;
   record {
       string name;
       int age = x; 
   } person1 = { name: "Pubudu" };

   var personType = typeof person1;
  
   x = 2;

   var res = foo(personType);
}

function foo(typedesc<record { string name; int age; }> personType) returns error? {
   var person2 = check personType.constructFrom({ name: "Manu" });
   io:println(person2.age);
}
```

And I think we need to pass the closure map. The spec says the following regarding default values for fields:

> A default-value specifies a default value for the field, which is used when the record type descriptor is used to construct a mapping value but no value is specified explicitly for the field. The type descriptor contains a 0-argument function closure for each default value. The closure is created from the expression when the type descriptor is resolved. The closure is evaluated to create a field value each time the default is used in the construction of a mapping value. The default value does not affect the type described by the type descriptor.

According to this, we have to evaluate the closure each time a new record is created.

**Comment by manuranga** [comment]
Had a discussion with @SupunS @hasithaa @pubudu91 
### Conclusions: 
- Closure have to be used, ie: result of above  println should be `2`.
- Will use above 'Solution 2' with following additions.
   - Change _all_ `NewMap` instructions to accept a typedesc as the arg.
   - Move init function from generated type class to typedesc class.

@pubudu91 kindly offered to implement the front-end closure-ization of complex expressions.
