### ISSUE TITLE
"JVM generation is not supported for type none" for invalid global types

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#20864]
**Description:**
It looks like the below code fails to compile but prints a stack trace rather than an actual compiler error.

#### Code
```Ballerina
var myVar = 1 | 2 | 3 | 4 ;
myVar x = 7;
```

#### Output
```
error: JVM generation is not supported for type none
	at ballerina.compiler_backend_jvm:generateField(jvm_method_gen.bal:2173)
	   ballerina.compiler_backend_jvm:generatePackageVariable(jvm_package_gen.bal:247)
	   ballerina.compiler_backend_jvm:generatePackage(jvm_package_gen.bal:186)
	   ballerina.compiler_backend_jvm:generateJarBinary(main.bal:86)
	   ballerina.compiler_backend_jvm:main(main.bal:60)
error: error: JVM generation is not supported for type none
	at ballerina.compiler_backend_jvm:generateField(jvm_method_gen.bal:2173)
	   ballerina.compiler_backend_jvm:generatePackageVariable(jvm_package_gen.bal:247)
	   ballerina.compiler_backend_jvm:generatePackage(jvm_package_gen.bal:186)
	   ballerina.compiler_backend_jvm:generateJarBinary(main.bal:86)
	   ballerina.compiler_backend_jvm:main(main.bal:60)
```
**Steps to reproduce:**
Run above code in Ballerina

**Affected Versions:**
jBallerina 1.1.1
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**
MacOs

**Related Issues (optional):**
Looks similar to #10865 but this does not compile

**Suggested Labels (optional):**
Area/Language Type/Bug Component/Compiler

**Comment by KavinduZoysa** [comment]
According to the spec, this should be a compiler error (`unknown type 'myVar'`). Tested with PR #20681 and it works as expected which means it throws compile error `unknown type 'myVar'`.
