### ISSUE TITLE
Logging does not work when used with interop

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#20875]
**Description:**
I have written a sample interop function to log a string. But the log is not printed in the console

**Steps to reproduce:**
Please find the attached project
[mgwexample.zip](https://github.com/ballerina-platform/ballerina-lang/files/4163240/mgwexample.zip)

**Affected Versions:**
1.1.0 and 1.1.1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
This works fine when the "ballerina" logger is used.
ie. private static final Logger log = LoggerFactory.getLogger("ballerina");
