### ISSUE TITLE
Add XML element name expression

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#20880]
**Description:**
https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#element-name-access

This is a part of https://github.com/ballerina-platform/ballerina-lang/issues/19570

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Closing this issue, since this is not part of the Spec.
