### ISSUE TITLE
CLI tool for autogenerating jBallerina interop functions

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#20902]
**Name:**
`ballerina interop-gen` - A CLI tool for autogenerating jBallerina interop functions from Java libraries.

**Description:**
A CLI tool for autogenerating jBallerina interop functions for a specified Java class residing inside standard Java libraries, libraries used by the Ballerina SDK (`bre/lib`), dependencies specified in a project’s `Ballerina.toml` (if the tool is run inside a project) or from a specified `.jar` file.

**Synopsis:**
```bash
ballerina interop-gen (<module-name>|<bal-file-path>) -cn=<class-name> [ Options ]
```
```bash
ballerina interop-gen <-h|--help>
```

**Arguments:**
`<module-name>`
The module to which the interop code is to be added. This argument could be given when running the interop-gen tool inside a project.

`<bal-file-path>`
The path of the .bal file to which the interop code is to be added. This argument could be used to generate interop code inside a single .bal file. The interop functions generated would be appended to the file.

**Options:**
`-cn|--class-name=<class-name>`
The fully qualified name of the class to be used in the interop generation.

`-m|--method=<method-name>...`
The list of comma-delimited methods to be used for the interop generation.

`-f|--field=<field-name>...`
The list of comma-delimited fields to be used for the interop generation.

`-c|--constructor`
The option to generate interop code for constructors.

`--alias=<alias-name>`
The alias that is used to represent the fully qualified name of a class in interop functions. This alias will be used as a prefix in each interop function name.

`--jar=<jar-path>`
The path to the .jar file from which the interop functions are to be generated.

`-h, --help`
Print usage details of the command.

**Code Generation:**
* If a single .bal file is given, all the generated content will be placed at the end of the 
same .bal file. 
* If a module is given, generated content will be placed inside the module according to the 
following project structure. Here, a directory will be created by the name `interop-gen` 
inside the module to store all the interop code. Inside the `interop-gen` directory, the interop 
functions generated for each Java class will be grouped inside directories depicting the 
Java package. 
```
    project-dir
	├── Ballerina.toml
	├── src
    	└── myModule
        	├── interop-gen
            	        ├── <package-name>
            		        └── <class-name>.bal
            	        └── java.util
	            	        └── ArrayDeque.bal
        	├── main.bal
        	├── Module.md
        	├── resources
        	└── tests
            	       ├── main_test.bal
            	       └── resources
```
* If the interop tool is run multiple times, 
   * For single .bal files, it will keep on appending to the end of the file. This can result in duplicates if you have already generated interops for a specific class previously.
   * For a module, the interop code will be appended to each .bal file representing the class. This can also result in duplicates if you have already generated interops for a specific class previously.

**Specifying Java Classes:**
* Standard Java libraries will be automatically available for interop code generation.
* Any libraries used by the Ballerina SDK (`bre/lib`) will be available automatically for interop generation. 
* All the dependencies specified in the project’s `Ballerina.toml` will be available for interop code generation, if the interop tool is run inside a project.
* Any other jar can be provided to the interop tool with the `--jar` flag.

**Interop Function Names:**
Multiple classes can have the same method name and there could be overloaded methods/constructors. To avoid function name conflict in Ballerina code, the following could be implemented.
* Using the FQN of a Java method for the generated interop function name. This will, however, make the use of a generated library cumbersome. 
i.e. 
   `org.apache.activemq.jndi.ActiveMQInitialContextFactory.getInitialContext()`
* Providing an option to give an alias to the fully qualified class name in the interop-gen command. This alias could be prepended when generating the method name.
i.e. 
   `<alias>GetInitialContext()`
* If an overloaded method/constructor is present, the name could have the parameter types appended to it. Furthermore, overloaded method names and their derived interop function names will be logged in the console.
i.e. 
   `java.lang.StringBuffer.append(StringBuffer str)` -> `<alias>AppendStringBuffer`
   `java.lang.StringBuffer.append(String str)` -> `<alias>AppendString`

**Sample Use Cases:**
* Adding interops to a single .bal file using a standard Java library.
   ```
   $ ballerina interop-gen main.bal -cn=java.util.UUID -m=randomUUID --alias=uuid
   ```
   ```ballerina
   public function uuidRandomUUID() returns handle = @java:Method {
      name: "randomUUID",
      class: "java.util.UUID"
   } external;
   ```
* Generating interop code from a standard Java library into a module.
   ```
   $ ballerina interop-gen module1 -cn=java.lang.Math -f=PI --alias=math
   ```
   ```ballerina
   public function mathPi() returns float = @java:FieldGet {
      name:"PI",
      class:"java.lang.Math"
   } external;
   ```
* Generating interop code for for an entire Java class.
   ```
   $ ballerina interop-gen module1 -cn=java.security.cert.Certificate
   ```
* Generating interop code from an external jar file
   ```
   $ ballerina interop-gen module1 -cn=org.apache.activemq.jndi.ActiveMQInitialContextFactory -m=getInitialContext --jar=lib/activemq-all-5.15.11.jar --alias=contextFactory
   ```
   ```ballerina
   public function contextFactoryGetInitialContext(handle param1) returns handle = @java:Method {
       name: "getInitialContext",
       class: "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
   } external;
   ```

**Implementation Specification:**
https://docs.google.com/document/d/1sWfJcdi0ttNFql_DVMqrGoORuA_P5LuY-skUMr-LO8k/edit?usp=sharing

**Documentation:**
https://docs.google.com/document/d/1Fp2xSFxiNUQl_u4LHMn6Av8EjzYzU5KjbAR-bM8DEBE/edit?usp=sharing

**Suggested Labels:**
Type/NewFeature, Area/BuildTools

**Comment by sameerajayasoma** [comment]
This is the design document of the Java interoperability design. I haven't updated it to match the latest changes, but it is a good starting point. 

https://docs.google.com/document/d/1hlKSd-tQQfr8tJVvHUor7zOIqHbztqu2jqihnK7IUhw/edit#heading=h.qoq48bdk38wi

**Comment by sameerajayasoma** [comment]
The following document is the draft of the Ballerina how-to guide that I've been working on. 

https://docs.google.com/document/d/140jc9PQ46monSr8boVaqhBwCERQznH6ZLtVqnBqgOXk/edit#heading=h.csj6shbvsth

**Comment by sameerajayasoma** [comment]
I think this design should focus on mapping a Java class to a Ballerina object instead of mapping all the methods of a Java class into module-level functions.  Here is a section that I copied from the how-to guide that I've been working on. 

### Map Java classes into Ballerina objects

The following pattern is useful If you want to present a nicer Ballerina API that calls to Java code underneath. This pattern creates wrapper Ballerina objects for each Java class that you want to expose via your API. 

Imagine that you want to design an API to manipulate a stack of string values by using the Java `ArrayDeque` utility. You can create a Ballerina object type as follows. 
```
public type StringStack object {
   private handle jObj;

   public function __init() {
       self.jObj = newArrayDeque();
   }

   public function push(string element) {
       push(self.jObj, java:fromString(element));
   }

   public function pop() returns string {
       handle handleEle = pop(self.jObj);
       // Let's talk about error handling and null satefy later in this guide
       // This example uses an empty string for now.
       return java:toString(handleEle) ?: "";

   }
};

function newArrayDeque() returns handle = @java:Constructor {
   class: "java.util.ArrayDeque"
} external;

function pop(handle receiver) returns handle = @java:Method {
   class: "java.util.ArrayDeque"
} external;

function push(handle receiver, handle element) = @java:Method {
   class: "java.util.ArrayDeque"
} external;
```
This object presents a much nicer API compared to the previous API. Here is a sample usage of this object. 

```
public function main() {
   StringStack stack = new();
   stack.push("Ballerina");   
   string element = stack.pop();
}
```
-----------------------------------------------

Issues:

- Mapping static methods of a  Java class
- Mapping overloaded constructors and methods
- Mapping public static/instance fields of a Java class

**Comment by IrushiL** [comment]
**Notes:**

- This tool could be designed to make the .bal file generation independent of a project, similar to what is done in gRPC.

- Mapping could be done from a Java object to a Ballerina object, instead of mapping at function level.

- If an object mapping is done, the overloaded constructors will have to be mapped accordingly. Maybe use the factory method design pattern.

- Getters and setters for fields.

**Comment by IrushiL** [comment]
The changes suggested have been updated in the documentation [1]. Please refer to it for the latest design of the CLI tool for autogenerating jBallerina interop functions.

[1] https://docs.google.com/document/d/1Fp2xSFxiNUQl_u4LHMn6Av8EjzYzU5KjbAR-bM8DEBE/edit?usp=sharing
