### ISSUE TITLE
All attributes must initialized before calling a functions inside __init

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#20907]
**Description:**
Let say I have a very simple ballerina client object like below.

```ballerina
public type Person client object {
    private string name;
    private string dob;

    public function __init(string nic) {  
        self.name = "";
        self.dob = "";
        self.dob = self.calculateDob(nic);
    }

    public function calculateDob(string nic) returns string {
        return "DOB";
    }
};
```

Here I've noticed that we cannot call any other external such as `self.calculateDob` without initializing all attributes(`name` and `dob`) in Person object.

For example, if I change the init function like below it gives an error.

#### Program 1
```ballerina
public type Person client object {
    private string name;
    private string dob;

    public function __init(string nic) {  
        self.dob = "";
        self.dob = self.calculateDob(nic);
        self.name = "";
    }

    public function calculateDob(string nic) returns string {
        return "DOB";
    }
};
```

#### Error 1

```sh
Client.bal:9:20: field(s) 'name' not initialized
```

Or even I couldn't directly assign a return value of a function to an attribute. It also gives an error.

#### Program 2

```ballerina
public type Person client object {
    private string name;
    private string dob;

    public function __init(string nic) {  
        self.name = "";
        self.dob = self.calculateDob(nic);
    }

    public function calculateDob(string nic) returns string {
        return "DOB";
    }
};
```

#### Error 2

```sh
Client.bal:9:20: field(s) 'dob' not initialized
```

Is this an expected behavior or did something go wrong?

**Steps to reproduce:**
- Run the above Program 1 and Program 2 using ballerina version 1.1.0.

**Affected Versions:**
ballerina version 1.1.0

**Comment by MaryamZi** [comment]
This is the expected behaviour, in line with the spec. 

The spec says
```
At any point in the body of a __init method, the compiler determines which fields 
are potentially uninitialized. A field is potentially uninitialized at some point if 
that field does not have a default value and it is not definitely assigned at that 
point. It is a compile error if a __init method:

- accesses a field at a point where it is potentially initialized, or
- at a point where there is any potentially uninitialized field
  - returns nil, or
  - uses the self variable other than to access or modify the value of a field.
```

Since you are attempting to call a method on `self` before all fields are initialized, it results in an error (**uses the self variable other than to access or modify the value of a field**). 

(The particular method could try to access the uninitialized field - enforcing the need for all the fields to be initialized helps prevent this.) 

Please reopen if you have further concerns.
