### ISSUE TITLE
Values and Types : BBEs needs improvement

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#20903]
**Description:**
#### Union
BBE regarding [union type ](https://ballerina.io/v1-1/learn/by-example/union-type.html)is not complete. It only shows a scenario where the return type of a function is a union. There are more usages of the union type.  A different BBE shows the usage [Constant BBE](https://ballerina.io/v1-1/learn/by-example/constants.html). This confuses users on how to create a union on Ballerina. 

eg: 
```Ballerina
type myUnion 1 | 2 | 3;
type myUnion2 1 | "Hello" | ();
```

#### Singleton
No BBE is created specifically for singleton type
```Ballerina
type mySingleton 1;
```

**Suggested Labels (optional):**

Component/Example Area/Language Type/UX

**Comment by MaryamZi** [comment]
Fixing https://github.com/ballerina-platform/ballerina-lang/issues/11195 would cover this right?

**Comment by pubudu91** [comment]
Not really. The union type BBE doesn't really show defining unions like the following:
```ballerina
type Foo int|string;
```
In the union type BBE, the following code fragment is pretty much it for demonstrating unions:
```ballerina
string|error valueOrError1 = getValue("name");    
 io:println(valueOrError1); 
string|error valueOrError2 = getValue("");     
io:println(valueOrError2);
```

**Comment by hasithaa** [comment]
It looks like we have covered these with the new BBE revamp. Hence Closing this issue.
