### ISSUE TITLE
Interop functions do not identify specific overloaded methods

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#20918]
**Description:**
When there is a call for an overloaded method, Java finds the most specific overloaded method to execute. But Ballerina java interop functions does not identify this. Instead, it throws an error at the build, stating 
```
{ballerinax/java}OVERLOADED_METHODS message=More than one public methods <method_name> that match with the parameter types '<paramter_types>' found in class '<class_path>'.
```
But ideally, if there are more than one matching function, it should select the most specific method to execute.
```

**Steps to reproduce:**

create two ballerina interop functions:

```ballerina
function foo(handle str) returns any {
    name: "foo",
    class: "org.sample.interop.MyClass",
    paramTypes: ["java.lang.String"]
} external;

function bar(any val) returns any {
    name: "foo",
    class: "org.sample.interop.MyClass",
    paramTypes: ["java.lang.Object"]
} external;
```

Define the java class accordingly, and try to build this. It will throw the above mentioned error.

**Affected Versions:**
Master branch.

**Comment by HindujaB** [comment]
The issue is already fixed for current master.
