### ISSUE TITLE
Ballerina 1.1.1 Hello World project build command fails with an encrypted string in the ballerina.conf file

### ISSUE THREAD

**Issue by tj800x** [ballerina-platform/ballerina-lang#20932]
This occurred in my main project, but I've also duplicated it in a brand new HelloWorld project.

I created a new project with ballerina new hello5; ballerina add hello.  Changed main.bal to read greeting.sayWhat setting from ballerina.conf file.  That worked fine.  

Then I encrypted the text using ballerina encrypt.  I then pasted the @encrypted:{} value into the ballerina.conf file.  

When I rebuilt the project with ballerina build -a it prompts me for the secret.  After I type it the build proceeds until near the end when two ballerina: null messages appear.

```
[hello5]$ ballerina clean
[hello5]$ ls target
ls: target: No such file or directory
[hello5]$ ballerina build -a
ballerina: enter secret for config value decryption:
MYSECRET
Compiling source
        trj/hello:0.1.0

Creating balos
        target/balo/hello-2019r3-any-0.1.0.balo
ballerina: enter secret for config value decryption:
ballerina: null
error: ballerina: enter secret for config value decryption:
ballerina: null
[hello5]$ ls target
balo    caches
```

For more details see gist at https://gist.github.com/tj800x/88874ad4210adb936b2da84fe6aa4dc8

I'm running Ballerina 1.1.1 on OSX 10.14.6.

**Comment by hasithaa** [comment]
This looks like a bug. Related to https://github.com/ballerina-platform/ballerina-lang/issues/20362 @warunalakshitha @keizer619 Could you please verify?

**Comment by warunalakshitha** [comment]
@hasithaa Yes. Same issue and we are working on fixing that.  Workaround is to pass the config file with --b7a.config.file= without keeping ballerina.conf file in same root path when you have encrypted values.

**Comment by warunalakshitha** [comment]
I am closing this issue we will fix this with https://github.com/ballerina-platform/ballerina-lang/issues/20362
