### ISSUE TITLE
Error: ballerina: unknown command 'init' with ballerina-cli

### ISSUE THREAD

**Issue by JimLynchCodes** [ballerina-platform/ballerina-lang#20939]
**Description:**

I downloaded the ballerina cli from here on macOs: 
https://ballerina.io/learn/installing-ballerina/

When I run `ballerina -v` I get some output in the console making me think it is working:
```
jBallerina 1.1.1
Language specification 2019R3
Ballerina tool 0.8.0
```

I am trying to run the "hello world" example on exercism.io for the ballerina track, but the first step is to run `ballerina init` in the project. When I do that, however, I get this error in the command line:
```
ballerina: unknown command 'init'
Run 'ballerina help' for usage.
```

Any advice on how I can get this to work?

Thanks! 🙏 💃

**Steps to reproduce:**

 ^

**Affected Versions:**

**OS, DB, other environment details and versions:**

jBallerina 1.1.1
Language specification 2019R3
Ballerina tool 0.8.0

System
  platform           darwin                                                  
  arch               x64                                                     
  cpu                12 cores      Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz  
  directory          hello-world   /Users/jim/Exercism/ballerina/hello-world 

JavaScript
  node               8.17.0       /Users/jim/.nvm/versions/node/v8.17.0/bin/node 
  npm                6.13.4       /Users/jim/.nvm/versions/node/v8.17.0/bin/npm  
  yarn               1.21.1       /Users/jim/.nvm/versions/node/v8.17.0/bin/yarn 

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@JimLynchCodes I'm afraid the Exercism track for Ballerina has not yet been updated to 1.0.0 and later versions. 

The `init` command was removed with Ballerina 1.0.0.

Instead, you can now use the `ballerina new` command to create a new Ballerina project.

```cmd
$ ballerina new my-project
Created new Ballerina project at my-project

Next:
    Move into the project directory and use `ballerina add <module-name>` to
    add a new Ballerina module.
```

You can then move into the newly created project and add a new module using the `ballerina add` command.

```cmd
$ cd my-project/
/my-project$ ballerina add foo
Added new ballerina module at 'src/foo'
```

This will create a new module with the given name in the src/ directory of the project (in pre-1.0.0 version a project did not have a src/ directory, and the modules were created in the project root).

The structure should now be

```cmd
/my-project$ tree
.
├── Ballerina.toml
└── src
    └── foo
        ├── main.bal
        ├── Module.md
        ├── resources
        └── tests
            ├── main_test.bal
            └── resources

5 directories, 4 files
``` 

The [How to Structure Ballerina Code](https://ballerina.io/v1-1/learn/how-to-structure-ballerina-code/) guide is the official documentation describing the same.

**Comment by JimLynchCodes** [comment]
@MaryamZi Thank you! However, I don't think `ballerina new` is the correct command for me here. 

I have an already created project here: https://github.com/JimLynchCodes/Exercism-Solutions/tree/master/ballerina/hello-world

The guide I was given with this project instructs me to do `ballerina init` which does not work for me with this newer ballerina cli.

Running `ballerina new` doesn't work for me either. Instead, it gives the error:
```
ballerina: The following required arguments were not provided:
    <project-name>

USAGE:
    ballerina new <project-name>
```

And when I pass arguments like this `ballerina new hello-world` I get this error:
```
ballerina: Directory is already within a Ballerina project :/Users/loaner/Exercism/ballerina/hello-world/hello-world
```

When I try to run the command given by the project creator, `ballerina test hello-world-service`, I get this error:
```
ballerina: invalid Ballerina project

USAGE:
    ballerina test  <module-name> | -a | --all
```

Can you please help me to run this exist project's tests?

Thanks! 🙏 ❤️

**Comment by warunalakshitha** [comment]
@JimLynchCodes We have introduced few changes to project structure with ballerina 1.x.

You can execute following steps to run the tests.

1. Go to hello-world project directory which has the Ballerina.toml.
2. run 'ballerina add <moduleName>' command to add module. Here I have used 'module'.
3. Copy tests and run ballerina test module.

```
**Exercism-Solutions/ballerina/hello-world$** cd hello-world/
**Exercism-Solutions/ballerina/hello-world/hello-world$** ls
Ballerina.toml
**Exercism-Solutions/ballerina/hello-world/hello-world$** ballerina add module
Added new ballerina module at 'src/module'
**Exercism-Solutions/ballerina/hello-world/hello-world$** cp ../tests/hello_world_test.bal src/module/tests/
**Exercism-Solutions/ballerina/hello-world/hello-world$** ballerina test module
```

Here is the project structure. I have removed the default main_test.bal added through ballerina command.

```
├── Ballerina.toml
├── src
│   └── module
│       ├── main.bal
│       ├── Module.md
│       ├── resources
│       └── tests
│           ├── hello_world_test.bal
│           └── resources


```

Anyway mock functions are not working with 1.x and we are working on fixing that.
hello_world_test.bal
```
import ballerina/test;

any[] outputs = [];
int counter = 0;


@test:Config{
}
function testFunc() {
    // Invoking the main function
    main();

}

```

**Comment by azinneera** [comment]
@JimLynchCodes We have re-introduced the `bal init` command in Ballerina Swan Lake. Please update your distribution to the latest as described [in our website](https://ballerina.io/downloads/). You can check for the [Learn Page](https://ballerina.io/learn/) to get started and join our [Slack channel](https://ballerina.io/community/slack/) for any queries and updates on Ballerina.
