### ISSUE TITLE
Cleanup Ballerina Central and split it into Production and Test

### ISSUE THREAD

**Issue by tj800x** [ballerina-platform/ballerina-lang#20938]
There are a bunch of junk modules in Ballerina Central.  For someone evaluating the platform it projects an image of low quality.

By my count there are at least 25 Hello World projects, not including pre 1.0 packages:
https://central.ballerina.io/search?q=Hello%20world

**Comment by tj800x** [comment]
I removed my suggested fix as there are probably plenty of ways to fix this.

**Comment by hemikak** [comment]
Thanks @tj800x , we will look into this matter.

**Comment by anupama-pathirage** [comment]
Closing this issue as it is tracked via https://github.com/ballerina-platform/ballerina-lang/issues/20938
