### ISSUE TITLE
Consider .bal files in the target/ directory during the compilation time

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#20958]
**Description:**
When it comes to automatic gRPC stub file creation in ballerina, it will eventually create those stub files in a separate directory inside the `target/` directory according to [this feature requirement](https://github.com/ballerina-platform/ballerina-lang/issues/20843). In that case, ballerina build needs to have the capability to consider those stub files`*.pb.bal` files during the compilation phase.

**Related Issues:**
#20843
https://github.com/ballerina-platform/ballerina-lang/issues/20957

**Suggested Labels:**
Type/Improvement

**Comment by azinneera** [comment]
We can generate sources in memory using a compiler plugin using a code generators.

**Comment by pramodya1994** [comment]
Closing this issue after having an offline discussion to use code generator compiler plugin to generate sources in memory using the files in `target`.
