### ISSUE TITLE
[AST node generator] Define the node structures for a subset of grammar

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#20955]
**Description:**

$subject for a subset of grammar.
e.g.: 
- What are the types of nodes needed?
- What are the relationship between the nodes? 
- What information are needed in each node?
- How to handle erroneous nodes?

**Comment by tharindulak** [comment]
The initial implementation is as follows.
https://github.com/ballerina-platform/ballerina-lang/tree/astImpl/compiler/ast-node-gen
