### ISSUE TITLE
Problem with isElement() when using readXml()

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-lang#20968]
**Description:**
When loading xml documents with ReadableCharacterChannel::readXml(), there is a bug with isElement() method: it returns false on xml objects coming from this document and consisting of a single element node. Filtering elements only with elements() doesn't help.

This is a problem since other methods require isElement to be true (getChildren).

This problem doesn't occur when creating a document with a xml litteral. 

A workaround is to rebuild a xml object by using xml:fromString()

**Steps to reproduce:**

Run the ballerina module given
The line `io:println(doc.isElement());` prints false

[src.zip](https://github.com/ballerina-platform/ballerina-lang/files/4182921/src.zip)

**Affected Versions:**

Version 1.1.1

**OS, DB, other environment details and versions:**

openjdk 8 debian buster

**Comment by rdhananjaya** [comment]
This issue should be fixed by https://github.com/ballerina-platform/ballerina-lang/pull/20778 and will be delivered in 1.1.2 release.

**Comment by rdhananjaya** [comment]
This is fixed in 1.1.2
