### ISSUE TITLE
Intellij IDEA plugin snippet format issue for auto completed mapping fields

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#20986]
**Description:**
Consider the following source

```
function testFunction(string field1) {
       TestRecord1 testRec = {
             <cursor>
       };
}

type TestRecord1 record {
         string field1;
         int field2;
};
```

When we get the completions and select the field2 from the list, expected text to be inserted is `field1: 0` and instead of that we get `0field1:` causing a syntax error

**Steps to reproduce:**

**Affected Versions:**
v1.1.0 at least

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with #21027.
