### ISSUE TITLE
Incorrect formatting for client init

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#21025]
**Description:**

Please use below code to reproduce the issue.

**Steps to reproduce:**

The code after formatting: 

```ballerina
import ballerina/http;

public function main() {
    http:Client clientEndpoint = new ("http://localhost:9090", {
        compression: http:COMPRESSION_ALWAYS
    });
}
```

But it should be:

```ballerina
import ballerina/http;

public function main() {
    http:Client clientEndpoint = new ("http://localhost:9090", {
            compression: http:COMPRESSION_ALWAYS
        }
    );
}
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sanjana** [comment]
Tested on version: **SLP5**. 
And this issue is fixed (The formatting is performed as per modifications added in the new formatter implementation design).
