### ISSUE TITLE
jsonutils:fromXML() return type is wrong

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-lang#21032]
**Description:**

jsonutils:fromXML() signature specifies it returns a json|error but on runtime, there is a case where it returns a `handle` : when passing a text node xml object

```json|error j = jsonutils:fromXML(xml `aaa`);```

The problem is not that it fails in that case, the real problem is that the runtime type is different than compile-time type

**Steps to reproduce:**

Insert the line above in a simple ballerina program and run it, it will cause an error (cannot cast "handle" to "json|error")

**Affected Versions:**
1.1.1

**OS, DB, other environment details and versions:**
openjdk 8, debian buster

**Comment by rdhananjaya** [comment]
Seems to be an issue with jsonutils:fromXML functions returning java `strings` rather than `StringValues` instances.
