### ISSUE TITLE
Implement Ballerina slack connector

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#21064]
**Description:**
Finalize the design and implement it.

**Comment by Bhashinee** [comment]
The design got changed, so removing from the Sprint 5 and adding to sprint 6

**Comment by Bhashinee** [comment]
Committed to this repository https://github.com/Bhashinee/module-slack 

Need to finalize a place to put the source code in Ballerina org.

**Comment by wggihan** [comment]
This is done now. The connector is available via ballerina central.
