### ISSUE TITLE
Record cannot be documented with type referenced record fields

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#21082]
**Description:**
$subject. Hence API docs cannot be generated for referenced fields. Without fixing this, Feature cannot be integrate to Stdlib records where API docs are essential

**Steps to reproduce:**
```ballerina
# Represents some record.
#
# + url - URL of the service
# + timeoutInMillis - The maximum time to wait
public type SomeRecord record {
    string url = "";
    *SomeOtherRecord;
}

type SomeOtherRecord record {
    int timeoutInMillis = 60000;
}
```
Result a warning 
```
no such documentable field 'timeoutInMillis'
```
**Affected Versions:**
v.1.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Since now metadata is allowed on object and record fields, to allow this, we need to copy the metadata as well when a record/object is type referenced.

**Comment by MaryamZi** [comment]
As @pubudu91 mentioned we should copy the metadata for referenced fields.

But if you want to overwrite the docs for `timeoutInMillis` in `SomeRecord`, you will have to override the field itself.

```ballerina
# Represents some record.
public type SomeRecord record {
    *SomeOtherRecord;
    # URL of the service
    string url = "";
    # timeoutInMillis - The maximum time to wait in SomeRecord
    int timeoutInMillis = 60000;
};

# Represents some other record.
public type SomeOtherRecord record {
    # timeoutInMillis - The maximum time to wait SomeOtherRecord
    int timeoutInMillis = 60000;
};
```
