### ISSUE TITLE
Make `...` work with a mapping value (closed record) in a function call

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#21097]
**Description:**
See https://github.com/ballerina-platform/ballerina-spec/issues/399#issuecomment-577515940.

**Comment by jclark** [comment]
This is now a separate spec issue https://github.com/ballerina-platform/ballerina-spec/issues/455

**Comment by hasithaa** [comment]
Implementation design notes are captured [here](https://docs.google.com/document/d/1hnvWui5uLIuzuFmR4ONqrMQjq2tGn0Fpw0953uAYHGg/edit).
