### ISSUE TITLE
Duplicate imports in BPackageSymbol class imports field

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#21100]
**Description:**
In BPackageSymbol class use array list to store imports as below.

https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/symbols/BPackageSymbol.java#L42

![image](https://user-images.githubusercontent.com/4163165/74622533-3754b100-5167-11ea-9865-9bc11fbe630f.png)

Because of this ballerina tool  code needs to loop through same imports multiple time. We need to use hashset to hold those imports.

**Comment by hasithaa** [comment]
@rdhananjaya This should be fixed with the new package API. will you able to check this?

**Comment by rdhananjaya** [comment]
Since we programmatically add items to this list I think there could be duplicates. In some places we have manual checks to detect duplicates too.
