### ISSUE TITLE
Enable "testThrowErrorInsideLock" test

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#21110]
**Description:**
Above testcase is disabled with https://github.com/ballerina-platform/ballerina-lang/pull/21109/commits/4ef6099472f1993b6153e23ab985ef4bec74fc0d due to failing intermittently.
Should be enabled after fixing. 

**OS, DB, other environment details and versions:**
Branch - ballerina-1.1.x

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This test seems to have been removed in https://github.com/ballerina-platform/ballerina-lang/commit/056b5a108a972bee0996d91f1c722c0aff33e4a5, but was enabled then also.
