### ISSUE TITLE
cannot find redis connector from Ballerina Central

### ISSUE THREAD

**Issue by reidlai** [ballerina-platform/ballerina-lang#21125]
**Description:**
Cannot find redis connector from Ballerina Central.  It exists before 1.0

**Steps to reproduce:**
N/A

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by wggihan** [comment]
@reidlai Unfortunately we couldn't do that yet. We started this and now PR in the reviewing stage and we might able to finish this and publish within today or tomorrow. 
https://github.com/wso2-ballerina/module-redis/pull/42

**Comment by MadhukaHarith92** [comment]
Redis connector is added to Ballerina central.
https://central.ballerina.io/wso2/redis

**Comment by daneshk** [comment]
Closing this issue, since we have published the new Redis connector version to Ballerina central. Please reopen if you still find any issue
