### ISSUE TITLE
Propagating constants in mapping-constructor is not handled via constructor propagation phase

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#21127]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/20995 introduces constant propagation to support using constants in annotations values. 

```ballerina
import ballerina/http;

const string RESOURCE_PATH = "/{id}";

service SampleService on new http:Listener(8080) {
    
    @http:ResourceConfig {
        methods: ["GET"],
        path: RESOURCE_PATH
    }

    resource function sampleResource(http:Caller caller, http:Request request, string id) {
     
    }

}

```

https://github.com/ballerina-platform/ballerina-lang/pull/20751 introduced using variables as constructor mapping. 

But this is not supported in compiler propagation phase. Hence the following code will result in a compilation error. 

```ballerina
import ballerina/http;

const string path = "/{id}";

service SampleService on new http:Listener(8080) {
    
    @http:ResourceConfig {
        methods: ["GET"],
        path
    }

    resource function sampleResource(http:Caller caller, http:Request request, string id) {
     
    }

}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Area/Language

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
We need to recheck this with the newer compiler plugins/semantic API.
