### ISSUE TITLE
Support protobuf any field in Ballerina

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#21146]
**Description:**
Please refer to [1] for more info about any field support in the proto file. Currently, this is not supported in Ballerina. we can support this using `anydata` type in Ballerina.
This task consists of changes in Ballerina code generation and changes marshaling and unmarshalling logic.

1. https://developers.google.com/protocol-buffers/docs/proto3#any

**Comment by BuddhiWathsala** [comment]
@daneshk, what would be the better design decision for the default value of the `any` type?

For example, make the default value as `()`,

```ballerina
public type Metric record {|
    any? tags = ();
|};
```

OR

assign some other value.

**Comment by daneshk** [comment]
> @daneshk, what would be the better design decision for the default value of the `any` type?
> 
> For example, make the default value as `()`,
> 
> ```ballerina
> public type Metric record {|
>     any? tags = ();
> |};
> ```
> 
> OR
> 
> assign some other value.

The `anydata` type would be better matched for this because `anydata` represents all serializable data types in Ballerina. And also nil value is part of `anydata`. Shall we create like below,

```ballerina
public type Metric record {|
    anydata tags = ();
|};
```
WDYT?

**Comment by BuddhiWathsala** [comment]
Yes, according to the specifications and the usage of `anydata` type, I'm also +1 for using `anydata` type. The main reason is, here we mainly focused on the serialization and deserialization of data.
