### ISSUE TITLE
Templating API docs for the B.io

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#21152]
**Description:**
Current docerina generate API docs for Ballerina std libs available in Ballerina. This same generated content goes to the B.io. When this shown on the website we need to apply the same menus and footer. There are two ways we can do that. We can write a JS script on website level to push menus and footer to API docs as it does for now Or we can use Jekyll templating. But to use Jekyll templating we need to add the front matter to each API doc on generation. to do that we have to add that functionality to Docerina. 

Can we evaluate what is the best way to do this?

**Comment by keizer619** [comment]
To solve these kind of issues there was an effort to convert api docs as a react app
https://ballerina.io/swan-lake/learn/api-docs/ballerina/#/auth

Hence i will be closing this issue and please feel free to open if there are any concerns
