### ISSUE TITLE
Null pointer exception, when there is no certificate under the given alias

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#21181]
**Description:**
In the JWT authentication scenario, when there is no public certificate under the given alias, the service will return a 500 response with null pointer exception.

https://github.com/ballerina-platform/ballerina-lang/blob/5a42f042aae200e61c91d593c9f54e1955a7eeaf/stdlib/crypto/src/main/java/org/ballerinalang/stdlib/crypto/nativeimpl/Decode.java#L68

Needs to check if this object is null.

**Steps to reproduce:**
N/A

**Affected Versions:**
ballerina 1.1.1

**OS, DB, other environment details and versions:**
MacOS Mojave

**Related Issues (optional):**
https://github.com/wso2/product-microgateway/issues/1020

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
This is already fixed with following PRs and will be available with 1.1.4 and 1.2.0 releases.
https://github.com/ballerina-platform/ballerina-lang/pull/21190
https://github.com/ballerina-platform/ballerina-lang/pull/21189
