### ISSUE TITLE
Rest detail node is missing in an errorMatchPattern node

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#21180]
**Description:**
When there is a errorMatchPattern with a rest detail param, Rest detail node is null hence unable to process the node level details using the AST.

**Steps to reproduce:**
Sample Code.
```ballerina
ER err1 = error("Error Code", message = "Msg");
match err1 {
    ER ( message = m, ...var rest) => {
        return <string>m;
    }
}
```

**Affected Versions:**
1.2.0-SNAPSHOT (Master)

**Comment by rdhananjaya** [comment]
The issue seems to be not having BLangParserListener method to capture the `...var rest` part of the parse tree.

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/26197 to contain `error-field-match-patterns` for slalpha1.

The following works now.

```ballerina
import ballerina/io;

type ER error<record {string message;}>;

public function main() {
    ER err1 = error ER("Error Code", message = "Msg", code = 1234);
    match err1 {
        error (var message, message = var m, ...var rest) => {
            io:println(message);
            io:println(m);
            io:println(rest);
        }
    }
}
```

```cmd
Error Code
Msg
{"code":1234}
```
