### ISSUE TITLE
Resource function parameters getting wrong position

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#21218]
**Description:**
```
import ballerina/http;
import ballerina/openapi;

listener http:Listener ep0 = new(80, config = {host: "petstore.openapi.io"});

listener http:Listener ep1 = new(443, config = {host: "petstore.swagger.io"});

@openapi:ServiceInfo {
    contract: "petstore.yaml",
    tags: [ ]
}
@http:ServiceConfig {
    basePath: "/v1"
}
service GigaClient on ep0, ep1 {

    @http:ResourceConfig {
        methods:["GET"],
        path:"/pets"
    }
    resource function listPets(http:Caller caller, http:Request req) returns error? {

    }
}
```
In the above example, the position of function parameters' are getting wrong and every time it gets incremented. The line number is correct but the start and end column are getting incremented every time it runs.

**Steps to reproduce:**

1. Paste the above code
2. Use LSModuleCompiler.getBLangPackages method to get bLangPackages

**Affected Versions:**
1.1.0 at least

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by hasithaa** [comment]
Fixed with new parser rewrite.
