### ISSUE TITLE
Module can be pushed to staging-central without having `Module.md`

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#21231]
**Description:**
$Title

**Steps to reproduce:**
1. Create a Ballerina project.
```
ballerina new testProject
```

2. Add a module.
```
ballerina add module1
```

3. Remove `module1/Module.md` file.
```
rm src/module1/Module.md
```
The project structure will be like:
```
.
├── Ballerina.toml
└── src
    └── module1
        ├── main.bal
        ├── resources
        └── tests
            ├── main_test.bal
            └── resources
```

4. Build the module.
```
ballerina build module1
```

5. Push the module.
```
ballerina push module1
```
Will see the following output in the terminal:
```
bpmmendis94/module1:0.1.0 [project repo -> central]
```
Website:
<img width="1208" alt="Screenshot 2020-02-25 at 14 45 07" src="https://user-images.githubusercontent.com/19742678/75232552-6f9a6600-57dd-11ea-9d9f-6ac4046f099d.png">

**Affected Versions:**
jBallerina 1.1.3
Language specification 2019R3
Ballerina tool 0.8.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
As per the discussion with the team this behavior is fine hence closing the issue.
