### ISSUE TITLE
Multi repo build pipeline for ballerina stdlib modules

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#21313]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

SameeraW

**Comment by BuddhiWathsala** [comment]
The `ballerina/websub` module uses annotations during the unit tests and integration tests, however, because of this issue(https://github.com/ballerina-platform/ballerina-lang/issues/23043), it is hard to migrate these tests into a separate repository.
