### ISSUE TITLE
Mutation of the containers during iteration is not handled as per the spec

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#21329]
Please refer to https://htmlpreview.github.io/?https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/v2019R3/lang/spec.html#built-in_abstract_object_types under **Iterator**.

> Mutation of the container during iteration is handled as follows. At any point during the execution of a program, a container has a set of valid keys; these are keys for which the container has a member; a key has type int for lists and type string for maps. A call to next() must panic if the set of valid keys is not the same as the set of valid keys when the iterator was created, with the following exception: it is allowed to remove a key if the member for that key has already been returned by next(). The value that a container associates with a particular key may change during the iteration; next() must return the value associated with the key at the point when next() is called.

**Comment by jclark** [comment]
Spec has been changed in https://github.com/ballerina-platform/ballerina-spec/issues/485 to the following:

> Mutation of a structured value during iteration is handled as follows. A call to next() must panic if there has been any mutation to the structured value since the iterator was created other than the following:
> * removing a member of the structured value that a preceding call to the iterator has already returned;
> * changing the member associated with an existing key.
>
> In the latter case, next() must return the value associated with the key at the point when next() is called.

This formulation is intended work with tables as well as mappings and arrays.
