### ISSUE TITLE
Validate the tests of the Ballerina installer

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#21349]
**Description:**
The $subject in different environments.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
there is an issue already
https://github.com/ballerina-platform/ballerina-lang/issues/9307
