### ISSUE TITLE
[vscode] ballerina: unknown command 'start-debugger-adapter'

### ISSUE THREAD

**Issue by enihcam** [ballerina-platform/ballerina-lang#21369]
**Description:**

Unable to debug ballerina code in VSCode.

`ballerina: unknown command 'start-debugger-adapter'`

**Steps to reproduce:**
Install ballerina
Install ballerina plugin for vscode
Run HelloWorld.bal

**Affected Versions:**
1.1.4

**OS, DB, other environment details and versions:**
Windows

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing since this issue has been fixed with #24254 and #24255.
