### ISSUE TITLE
Allow a way to skip the authorisation filter in ballerina auth module

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#21376]
**Description:**
Ballerina enforces the authorisation filter after the authentication filter. But when using custom auth validation external servers, it would not require to perform the scope validation from ballerina authz filter, because it is already done by the external server. It is better if there is a way to skip this filter.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
The fix will be available in Ballerina 1.1.5. Please reopen the ticket if there is any issue.
