### ISSUE TITLE
[HTTP2] Mutual SSL status is not passed in the request

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [ballerina-platform/ballerina-lang#21381]
**Description:**

Mutual SSL is not working with http 2.0

request.mutualSslHandshake["status"] is null always.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

https://github.com/wso2/product-microgateway/issues/1054

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Bhashinee** [comment]
@AmaliMatharaarachchi I changed the subject as it is misleading. Mutual SSL is working with HTTP2 and only the status is not passed along with the request, which is a feature that needs to be added in the HTTP2 request.

**Comment by daneshk** [comment]
@Bhashinee can we close this issue. since we have done the fix in master branch

**Comment by Bhashinee** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21629 and https://github.com/wso2/transport-http/pull/405

@daneshk closed the issue.
