### ISSUE TITLE
Fix "brokenOnJBallerina" unit and integration tests 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#21433]
**Description:**
Following tests were disabled during the migration effort. Need to fix them.

https://github.com/ballerina-platform/ballerina-lang/pull/21425
https://github.com/ballerina-platform/ballerina-lang/pull/21432
https://github.com/ballerina-platform/ballerina-lang/pull/21437

Integration tests to be fixed are :
- org.ballerinalang.test.packaging.*
- org.ballerinalang.testerina.test.*
- org.ballerinalang.test.transaction.*

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Closing this as all three issues are fixed

**Comment by Kishanthan** [comment]
There are few more integration tests to be fixed i think.
