### ISSUE TITLE
Unused parser rule "anonymousFunctionExpr" found in ANTLR definitions

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#21468]
**Description:**
Parser rule for `anonymousFunctionExpr`  is unused in ballerina ANTLR parser definition.

**Affected Versions:**
1.2.0-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Closing, since we are no longer using ANTLR.
