### ISSUE TITLE
Bir jar is generated based on the module name only and hence couldn't have two modules with same name and different orgs

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21462]
**Description:**
I'm working on the new JDBC module with name - ballerina/java.jdbc. The previous version of that module is ballerinax/java.jdbc. Until we mature the new module - ballerina/java.jdbc, we want to have both modules included in the distribution. But since the both modules have the same bir jar name, the jars are replaced in the final distribution.

**Comment by sinthuja** [comment]
This is blocker for this - https://github.com/ballerina-platform/ballerina-lang/pull/21272

**Comment by manuranga** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21543
