### ISSUE TITLE
Can't push new module version with ballerina push 

### ISSUE THREAD

**Issue by praminda** [ballerina-platform/ballerina-lang#21478]
**Description:**

Trying to push new version of an existing ballerina module to ballerina central. But it always fails saying version already exist. But the version in the error is already pushed to ballerina central and that is the old version. I've updated the `Ballerina.toml` file with new version and built the module before I tried push command.

```
error: module 'sample/module:0.2.0' already exists in remote repository(https://api.central.ballerina.io/1.0). build and push after update the version in the Ballerina.toml.
```

**Steps to reproduce:**
1. Create and push a ballerina module to [central](https://central.ballerina.io)
1. Update the version in `Ballerina.toml`
1. Build the module and try to push again
**Affected Versions:**
1.1.4
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
Tested this with the latest master branch, and the issue is not reproducing. Should check whether this happens intermittently.
