### ISSUE TITLE
Tooling changes to support metadata on record/object fields

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#21530]
**Description:**
Creating this issue to track $title.

Lang issue - #21512
Lang PR - #21529

**Comment by MaryamZi** [comment]
Need to consider any changes required to Docerina too.

**Comment by nadeeshaan** [comment]
This issue has been fixed and now provide the completions for annotations for the object and record fields in latest master build. Hence closing the issue.
