### ISSUE TITLE
Verify whether the cloned envs are required for desugared trx functions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#21547]
In the desugar phase we desugar the transaction block in to lambda functions. We assign a clone of the env to the `capturedClosureEnv` in the lambda function (https://github.com/ballerina-platform/ballerina-lang/blob/5c58aa07c40d9fa1a39f5cd6908103cf72b6a7c5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java#L1048). I think we don't need to clone it due to the reason explained in https://github.com/ballerina-platform/ballerina-lang/pull/21520/files#r390098631. Need to verify this.

**Comment by pcnfernando** [comment]
Transaction statement being desugared to a lambda function was removed with #27245. Hence, cloning env was also removed.
