### ISSUE TITLE
Add tooling support for XML navigation expressions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#21540]
**Description:**
$title.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Original issue https://github.com/ballerina-platform/ballerina-lang/issues/20667

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
@nadeeshaan Can you verify, whether we support this in LS?

**Comment by nadeeshaan** [comment]
XML navigation is not supported yet.
