### ISSUE TITLE
Block statement scope position resolver does not work properly when function parameters have not-null parents

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#21584]
**Description:**

Following is a sample test code

``` ballerina
function sampleFunction([string, float, string] g) returns (function (string, [string, float, string]) returns (string)){
    return function (string x, [string, float, string] y) returns (string) {
       var [i, j, k] = y;
       var [l, m, n] = g;
       return x + i + j + k + l + m + 
    };
}
```

After applying #20589 , parent nodes are assigned for function params. However, #20923 occurs because `BlockStatementScopeResolver` doesn't resolve scopes properly when variables in function parameters have not-null parents.

See the following screenshots. They shows the value of  `treeVisitor.getSymbolEnv()` in the `isCursorBeforeNode` method in `BlockStatementScopeResolver` class.

![not-applied-20589](https://user-images.githubusercontent.com/25485997/76301931-24a44680-62e5-11ea-9ebc-a9363b70f4fb.png)
#20589 is not applied

![applied-20589](https://user-images.githubusercontent.com/25485997/76301968-37b71680-62e5-11ea-9403-391da96da272.png)
#20589 is applied

**Steps to reproduce:**
1. Apply #20589 
2. Debug `BlockStatementScopeResolver` using the sample test code above
3. Get the visible entries of the scope in the line no 5 of the above test code

**Affected Versions:**
V 1.1.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#20381 , #20923 

**Suggested Assignees (optional):**
@nadeeshaan

**Comment by rdhananjaya** [comment]
@nadeeshaan  I just assigned you as it was suggested in the issue under `Suggested Assignee`.
Please assigned to correct person.

**Comment by hasithaa** [comment]
@dulajdilshan Could you please verify this with the current master?

**Comment by hasithaa** [comment]
@dulajdilshan Could you please verify this issue? Should be fixed with recent changes.

**Comment by dulajdilshan** [comment]
Closing as this is invalid
