### ISSUE TITLE
Docerina changes to support record/object field level documentation

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#21599]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/21529 allows field level documentation for records/objects.

```ballerina
# Docs for this record.
public type Foo record {

    # Docs for this field.
    string bar;
};

# Docs for this object.
public type Baz record {

    # Docs for this field.
    string qux;
};
```

Doc generation needs to be updated to consider such documentation.

**Comment by pramodya1994** [comment]
Created separate issue for **Area/BuildTools**
https://github.com/ballerina-platform/ballerina-lang/issues/22307
This will issue will cover **Area/Tooling** aspects

**Comment by shehan360** [comment]
This is currently supported in Docerina, hence closing the issue.
