### ISSUE TITLE
Add the Missing Descriptions of the Java.JDBC Module in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#21625]
**Description:**
We need to add the below missing descriptions of the Java.JDBC Module in API Docs.

- https://ballerina.io/v1-1/learn/api-docs/ballerina/java.jdbc/clients/Client.html(Constructor)
- https://ballerina.io/v1-1/learn/api-docs/ballerina/java.jdbc/constants.html

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by daneshk** [comment]
The fix is merged to the patch release branch and this module will be removed from the master branch. Hense closing this issue
