### ISSUE TITLE
Add the Missing Descriptions of the Kubernetes Module in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#21628]
**Description:**
We need to add the below missing descriptions of the Kubernetes Module in API Docs.

https://ballerina.io/v1-1/learn/api-docs/ballerina/kubernetes/index.html#constants

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Closing as PR with fix is merged.
