### ISSUE TITLE
Not all linked symbols are collected in getAllVisibleInScopeSymbols method

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#21637]
**Description:**
Symbols with same name are kept in a linked list, so that we can have a Type named `foo` and a variable named `foo`. When we define a new symbol we define that symbol as the head of the list, where this list contain symbol with the same name.

In `getAllVisibleInScopeSymbols` method only the first symbol from it's linkedlist is collected, hence only most recently defined symbol is visible in lang-server completions.

https://github.com/ballerina-platform/ballerina-lang/blob/6e40487a24b112e43a47fe3adf7f90678940fb5c/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolResolver.java#L1202

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This is fixed with the new compiler API.
