### ISSUE TITLE
Re-enable lang-server tests cases disabled in 21598

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#21639]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/21598

It seems the reason for this test failure is https://github.com/ballerina-platform/ballerina-lang/issues/21637

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Closing this issue. The code is out of sync now.
