### ISSUE TITLE
Fix the MockListener and StreamingListener Broken Links

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#21648]
**Description:**
We need to fix the below 2 broken links:

- https://ballerina.io/v1-1/learn/api-docs/ballerina/nats/listeners/StreamingListener.html
- https://ballerina.io/v1-1/learn/api-docs/ballerina/http/listeners/MockListener.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
The fix is done to jackyl files this seems to be not a problem with the Docs.

**Comment by praneesha** [comment]
Closing as this as the links are fixed in V1-2 also.
<img width="1680" alt="Screenshot 2020-03-23 at 17 31 12" src="https://user-images.githubusercontent.com/11707273/77315107-f4b96200-6d2c-11ea-8305-8f4d2b66b62c.png">
<img width="1680" alt="Screenshot 2020-03-23 at 17 30 53" src="https://user-images.githubusercontent.com/11707273/77315141-03077e00-6d2d-11ea-8025-064e745da6bf.png">
