### ISSUE TITLE
Optimize imports code action removes license header comments

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#21667]
**Description:**
Optimize imports code action removes license header comments

**Steps to reproduce:**
```ballerina
//
//
//
//
import ballerina/http;
import ballerina/io;

public type BaseConnector abstract object {
    public function pushText1(string text) returns error?;
};
```
Execute 'Optimize Imports' code action.

**Affected Versions:**
1.2.0-SNAPSHOT`

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
