### ISSUE TITLE
Create Local Variable code action issue with user defined types

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#21698]
**Description:**
Please consider the following source snippet

```
import ballerina/http;

public type MY_TYPE int;

function name() {
    <invoke code action here>getUnion();
}

function getUnion() returns MY_TYPE|http:Client {
    return 12;
}
```

When invoke the **create local variable** following is generated
`int|http:Client union = getUnion();`
But, expected value should be
`MY_TYPE|http:Client union = getUnion();`

**Affected Versions:**
v1.2.0-SNAPSHOT at least

**Comment by rasika** [comment]
This is still not possible since we cannot get the original constant from the AST.

**Comment by rasika** [comment]
Blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/26284

**Comment by nadeeshaan** [comment]
This issue has been fixed in latest master. Hence closing the issue
