### ISSUE TITLE
Improvement documentation: ballerina.lang.messages

### ISSUE THREAD

**Issue by mynecker** [ballerina-platform/ballerina-lang#2170]
Documentation of ballerina.lang.messages is a bit ambiguous:

Example:
```
function getXmlPayload(message m) (xml )
Gets the message payload in XML format
...
The XML representation of the message payload
```
It should be stated clearly that there is no implicit casting in place. If message is of type application/json it will not result in an XML representation, it will fail instead. Same applies to other functions accordingly.

**Comment by afkham** [comment]
message is no longer there
