### ISSUE TITLE
Need a better fix for error building modules with periods in the module name without replacing $$$

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#21711]
**Description:**
$Title
Issue: https://github.com/ballerina-platform/ballerina-lang/issues/20868
Fixed PR by replacing Qualified class name by `$$$`: https://github.com/ballerina-platform/ballerina-lang/pull/21442

**Steps to reproduce:**
Steps are described in the Issue https://github.com/ballerina-platform/ballerina-lang/issues/20868

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This is fixed in Swan Lake. The period character (`.`) is allowed in module names
