### ISSUE TITLE
Signature Help not provided for the langlib functions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#21740]
**Description:**
Consider the following source snippet

```
function testFunction() {
   http:Client testClient = new("http://localhost:9090");
   testClient.toString(<cursor>)
}
```

Do not get the signature help at the cursor position

**Affected Versions:**
v1.2.0-SNAPSHOT at least

**Comment by rasika** [comment]
when invoking toString() on a any value there is no pending parameter to be passed thus signatureHelp is not shown. However when there's langlib functions with more than one parameter it is correctly shown omitting first parameter.

<img width="917" alt="Screenshot 2020-09-23 at 13 52 28" src="https://user-images.githubusercontent.com/1448489/93986744-53c36680-fda4-11ea-91b0-c7ca0da61098.png">

thus i think this is the correct behaviour. wdyt?

**Comment by nadeeshaan** [comment]
This issue has been resolved with the latest implementation revamp. Hence closing the issue
