### ISSUE TITLE
Need a mechanism to serialize and deserialize records into bytes

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#21756]
**Description:**
The protobuf `Any` type represents data in [bytes [1]](https://developers.google.com/protocol-buffers/docs/proto3#any). Currently, in Ballerina, we can send data types like strings since strings have mechanism to convert it to bytes. In gRPC, we represent messages as records. 

Hence, we need a mechanism to serialize and deserialize these record types into bytes in order to support record as an `Any` data type. 

[1] : https://developers.google.com/protocol-buffers/docs/proto3#any

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/21146

**Comment by hasithaa** [comment]
Seem the original issue is fixed with the `anydata` type.
