### ISSUE TITLE
Ballerina dist list fails with null

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#21759]
**Description:**
$Subject. 

**Steps to reproduce:**
```
C:\Users\Hasitha\git\hasithaa\gist\wintests>ballerina dist list

Use 'ballerina help dist' for more information on specific commands.
null
```

**Affected Versions:**
jBallerina 1.2.0-RC1
Language specification 2020R1
Ballerina tool 0.8.2

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363

**Comment by keizer619** [comment]
Fixed in this PR
https://github.com/ballerina-platform/ballerina-update-tool/pull/17
