### ISSUE TITLE
Test should return non-zero exit code when fail

### ISSUE THREAD

**Issue by Urahara** [ballerina-platform/ballerina-lang#21762]
**Description:**
When assertion fail the output code of process is always 0.

**Steps to reproduce:**
Create a simple test that fails.
```
Running tests
	urahara/example:0.1.0

	[fail] testParse1:
	    Assertion Failed!: expected '3 2 6' but found '3 2 1' 
	    	at ballerina.test:createBallerinaError(assert.bal:41)
	    	ballerina.test:assertEquals(assert.bal:82)
	    	urahara.example.test.parser_tests:testParse1(test/parser_tests.bal:8)

	[pass] testParse7
	[pass] testParse6
	[pass] testParse5
	[pass] testParse4
	[pass] testParse3
	[pass] testParse2

	6 passing
	1 failing
	0 skipped
$ echo $?
$ 0
```

**Affected Versions:**
All.

**OS, DB, other environment details and versions:**
*nix.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
This might be fixed with https://github.com/ballerina-platform/ballerina-update-tool/pull/16

**Comment by Ibaqu** [comment]
> This might be fixed with [ballerina-platform/ballerina-update-tool#16](https://github.com/ballerina-platform/ballerina-update-tool/pull/16)

Can confirm that this fixes the issue. Exit code 1 is returned on test failure. 
Hence closing issue.
