### ISSUE TITLE
Formatting error in Object Assignability BBE

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#21785]
**Description:**
$subject. Please check the BBE https://ballerina.io/v1-1/learn/by-example/object-assignability.html

**Affected Versions:**
1.2.0

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/21838.

**Comment by praneesha** [comment]
Reopening as this is not fixed yet.
