### ISSUE TITLE
Ballerina build command does not show all the semantic errors for a project

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#21878]
**Description:**
Consider the following project structure

project
-------|---src
------------|--mod1
----------------|--test1.bal
------------|--mod2
----------------|--test2.bal

In the above case, test2.bal has a semantic error.
test1.bal has an import statement for mod2 as `import mod2;`

This import is an unused import.
When executing the `ballerina build -a` command it should prompt both errors. But, the observed behaviour is, it only prompts the semantic error in test2.bal.

**Affected Versions:**
v1.2.0-SNAPSHOT at least

**Comment by hasithaa** [comment]
@hevayo @warunalakshitha seems like this is broken from the packerina side.

**Comment by parkavi11** [comment]
Compilation does not allow to move to the next phase if typechecker has errors. Unused import is checked in dataflow analyser and it skips the type checker errors.
