### ISSUE TITLE
Introduce a fail-safe mechanism for the parser and error recorvery

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#21882]
**Description:**

Currently both the parser and error recovery have paths that are not supposed to be reached. Such invalid states cause runtime errors at the moment. i.e.: parser get crashed.

However, for some unforeseen reason, if the parser/error-recovery comes to a such an unhandled-state, the parser would crashed, and this is not an acceptable behaviour from a user's perspective. Therefore, instead of throwing a runtime error, implement a mechanism to recover from a unhandled path as well.

This is more of a fail-safe. Hence the requirement is only to be able to produce a valid tree, without the parser getting crashed. The recovered tree doesn't need to be the optimal one.

**Comment by lochana-chathura** [comment]
Considering the worst case scenario,

- I am thinking may be we can replace all the `throw new IllegalStateException("cannot find the next rule for: " + currentCtx);` in the error handler with `assert true;` and use an appropriate rule as the next rule in that context, thus error handler will never crash in the production.  

- I have done this in one small place, 

https://github.com/ballerina-platform/ballerina-lang/blob/ef94a2b65dbe5ba6a50f16c22319fb2b0283bd42/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParserErrorHandler.java#L3443-L3446

- But that way, it tends to create an inconsistency between parser and error handler, when trying to parse for such scenario. 

- But, with the combination of other fail-safe-mechanism we introduced in PR #24242, in case of inconsistency that token will be dropped. 

- Worst comes to the worst; if both fail-safe-mechanisms keep continue triggering, we can consider giving a parser timeout?

**Comment by SupunS** [comment]
You could also let the exception be thrown, then catch and handle it. Two places to handle:
- Like you've said, when visiting alternative paths, one path could be throwing an exception. Can catch the exception there (where the alternatives are visited) and simply ignore that path. The best alternative path would get picked from the remaining contenders.
- At the entry point (exception can be thrown without going for alternative paths) - Catch the exception and provide the solution as a REMOVE. That guarantees the parser won't get stuck at the same place.

Nice idea to have the `assert fail` in such cases. +1 for that.
Could add it to the places where the exception is caught.
