### ISSUE TITLE
Align langlib versions with the spec

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#21892]
**Description:**
$title
refer https://github.com/ballerina-platform/ballerina-spec/commit/858311776dfa5c30ef7d0b79ea0727cb43ed0018

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/21898.
