### ISSUE TITLE
Goto Def does not work for error keyword

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#21902]
**Description:**
$subject

**Steps to reproduce:**
Click the error keyword. 

```
public function main(string name) returns error? {
    if (name.length() < 5) {
        error e = error("InvalidName", message = "invalid length");
        return e;
    }
}
```

**Affected Versions:**
1.2.0

**Comment by hasithaa** [comment]
Since this is a built-in constructor this should be ok. @KavinduZoysa @nadeeshaan Please reopen if you think otherwise.
