### ISSUE TITLE
No signature help after check keyword

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#21912]
**Description:**

Consider the following source snippet,
`mysql:Client mysqlClient5 = check new (<cursor>)`

Signature help is not working at the cursor position.

**Affected Versions:**
v1.2.0-rc2

**Comment by rasika** [comment]
With the latest code changes sample code snippet would be;
```
import ballerinax/mysql;
function name() returns error?{
    mysql:Client mysqlClient5 =  check new();
}
```
