### ISSUE TITLE
Document This code action is suggested for the function within foreach

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#21915]
**Description:**
Consider the following source snippet and the "Document This" Code action should not support at the foreach line

```
resultStream.forEach(function(record {} result) {
        io:println("Customer full details: ", result);
        io:println("Customer first name: ", result["FirstName"]);
        io:println("Customer last name: ", result["LastName"]);
    });
```

**Affected Versions:**
v1.2.0-rc2 at least

**Comment by rasika** [comment]
We need to revamp the "Document This" code action. Instead of processing tokens in the current line need to detect top-level nodes from the AST. WDYT?

**Comment by nadeeshaan** [comment]
> We need to revamp the "Document This" code action. Instead of processing tokens in the current line need to detect top-level nodes from the AST. WDYT?

@rasika exactly, that would be the best option as you mentioned. Since we are using the old implementation for this, let's revamp. +1 for the effort
