### ISSUE TITLE
Shift operator formatting don't work

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#21938]
**Description:**
Formatting of the shift operators( <<, <<<, >> and >>) needs to have a space around the operators.

**Steps to reproduce:**
`int i = a<<2;`
After formatting using VSCode it should be as follows:
`int i = a << 2;`

**Affected Versions:**
1.2 RC2

**OS, DB, other environment details and versions:**
Linux

**Comment by sanjana** [comment]
Tested on version: **SLP5**. 
And this issue is fixed.
