### ISSUE TITLE
Go to definition opens file in same tab

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#21931]
When you use the go to definition feature, it opens the relevant file in the same editor tab you were on. Wouldn't it be better to open the file in a new tab?

**Comment by pubudu91** [comment]
For some, it opened in a new tab actually.

**Comment by nadeeshaan** [comment]
@pubudu91 This is the behaviour of VSCode editor in which you can configure it by yourself. Search for enablePreview and remove the check box.
