### ISSUE TITLE
Underscore field not included in the error detail node

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#21971]
**Description:**
```
function testLetExpressionRecordConstrainedErrorBinding() {
    string msg = let var error (_,detailMsg = detailMsg, isFatal = isFatal) = getRecordConstrainedError() in detailMsg;
}
```
In the above code, the '_'  is not getting in the detail node in the error variable node

![image](https://user-images.githubusercontent.com/16335290/77039830-be05e380-69dc-11ea-8c5b-382ec22ad201.png)

**Steps to reproduce:**

1. Copy-paste the above code
2. Run the ballerina formatter

**Affected Versions:**
1.2.0

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by rdhananjaya** [comment]
What this underscore does is ignore the first argument in the destructuring, and the first argument of the error constructor is message/reason that is not a part of error detail record.

**Comment by gigara** [comment]
I think it should be accessed by somehow because otherwise, we can't format that part correctly.

**Comment by rdhananjaya** [comment]
I think the item called `reason` just before the `detail` item in the json value is the one that represents the underscore. 

Now the error type has changes and the first argument which used to be `reason` is now `message`.

**Comment by gigara** [comment]
@IrushiL @NipunaMarcus is this issue still exists? Or you can close the issue.

**Comment by IrushiL** [comment]
Now the underscore symbol is identified as a `WildcardBindingPatternNode`. Closing this issue since the formatting is now possible.
