### ISSUE TITLE
[Test][UI] Self referring links in test report

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#21986]
**Description:**

Links are shown below referring to themself. But it should point to each module's header in the report. 
![image](https://user-images.githubusercontent.com/1356214/77063132-31bae700-6a03-11ea-80c4-797ba6e758e6.png)

**Steps to reproduce:**

**Affected Versions:**
JBallerina 1.2.0-RC2

**Comment by azinneera** [comment]
Resolved by pr #22351
