### ISSUE TITLE
Goto Definition not working for record fields

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#22009]
**Description:**
Consider the following source

```
function getPerson(string name, int age) returns Person? {
    if (name == "" || age == 0) {
        return;
    } else {
        // Defines a `Person` record.
        Person p = {
            <cursor>name: name,
            age: age,
            addr: {
                line01: "No. 61",
                line02: "Brandon street",
                city: "Santa Clara",
                state: "CA",
                zipcode: "95134"
            }
        };
        return p;
    }
}
```

**Steps to reproduce:**
Execute goto definition at the given cursor position.

**Affected Versions:**
v1.2.0-rc2 at least

**Comment by pubudu91** [comment]
@nadeeshaan Is this an issue in the Semantic API? If so, what's the limitation?

**Comment by nadeeshaan** [comment]
> @nadeeshaan Is this an issue in the Semantic API? If so, what's the limitation?

This was mainly due to a concern on whether we are able to capture the symbol of a field in a record literal expression and the field of the actual type definition.
