### ISSUE TITLE
Description on hover is blank for some test annotations in IDEA plugin

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#22017]
**Description:**
In IDEA plugin, the description of @BeforeSuite, @AfterSuite, @ BeforeEach and @AfterEach that is expected to show on CTRL+Hover are blank. Please refer the image below.

![image](https://user-images.githubusercontent.com/18344003/77160899-63e54b00-6ace-11ea-935d-7e2d346cde1f.png)

For some annotations, the expected description is shows. Please refer image below for a proper one.
![image](https://user-images.githubusercontent.com/18344003/77161055-c0486a80-6ace-11ea-9a64-2a0afd894015.png)

**Affected Versions:**
1.2.0

**Comment by nadeeshaan** [comment]
This has been fixed in latest master. Hence closing the issue.
