### ISSUE TITLE
Slow unit test execution due to network access

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22043]
**Description:**
Unit test execution is really slow down to 131 tests for 14 minutes. Also, note the second attempt at running unit tests show failed network calls when the network was unavailable at the second attempt.
<img width="1378" alt="Screen Shot 2020-03-21 at 1 36 47 PM" src="https://user-images.githubusercontent.com/1496990/77226953-205c1100-6ba2-11ea-9ecc-f1d0560c89aa.png">

Visual vm profiling
<img width="1462" alt="Screen Shot 2020-03-21 at 1 37 05 PM" src="https://user-images.githubusercontent.com/1496990/77226962-2f42c380-6ba2-11ea-8fa7-50a43b8d11aa.png">

**Steps to reproduce:**

**Affected Versions:**
1.2.0
MacOs
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/22118
