### ISSUE TITLE
Need a sample how to use http client connector with http cookie

### ISSUE THREAD

**Issue by muharihar** [ballerina-platform/ballerina-lang#2204]
Hi Team,

We need a sample how to use http client connector with http cookie. 

Thanks

**Comment by sameera-jayasoma** [comment]
Hi Muharihar,

Can you please elaborate more on your use case? May be provide a sample..

**Comment by chamil321** [comment]
@muharihar Ballerina is yet to add the cookie support for both client and service endpoints. Issue[1] is to track the requirement. Please follow the issue for the implemetation status. Hence closing this issue

[1] https://github.com/ballerina-platform/ballerina-lang/issues/7068
