### ISSUE TITLE
Suggesting just the relevant metadata for services and resources

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22049]
Refer to the images below. When you try to add an annotation, it seems to suggest all possible annotations from across the whole std lib. Instead of doing that, can't we suggest just the applicable annotations for that particular construct? In this case, only relevant HTTP annotations need to be shown. 
![Peek 2020-03-22 00-22](https://user-images.githubusercontent.com/6260009/77234374-d1c76a80-6bd3-11ea-8e60-6990949d8d0c.gif)
![Peek 2020-03-22 00-23](https://user-images.githubusercontent.com/6260009/77234376-d724b500-6bd3-11ea-992f-3dac82aec4d2.gif)

**Comment by MaryamZi** [comment]
But how would you know what kind of a service it is? While right now resources with an `http:Caller` param and an `http:Request` param would mean either an HTTP or WebSocket service, it's not always guaranteed right? 

Ideally anyone should be able to introduce any service with any type of parameter including HTTP.

IMO, this could be work when we have service typing, but I'm not sure if we can do that right now?

**Comment by pubudu91** [comment]
What I had in mind was filtering out the suggestions based on the type of listener to which the service attached. That should be possible right?

**Comment by nadeeshaan** [comment]
Since we can define annotations and attach, we can only decide from the type of attachment point. That particular capability has been added in the SwanLake release and we are closing the issue.
