### ISSUE TITLE
Incorrect terms in HTTP API docs

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22041]
**Description:**
The docs for `.getHeader()` and `.getHeaders()` on `http:Response` say "**An exception is thrown** if no header is found.".

https://ballerina.io/v1-2/learn/api-docs/ballerina/http/objects/Response.html#getHeader

Same for `http:Request`.

We should be saying "Panics" instead of "An exception is thrown". 

May have to check all docs.

**Affected Versions:**
1.2.0

**Comment by chamil321** [comment]
The issue is by https://github.com/ballerina-platform/ballerina-lang/pull/22396, hence closing
