### ISSUE TITLE
[Testerina] AssertEquals function fails when checking array equality

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#22048]
**Description:**
Please refer to the following sample codes. These test cases are failing with the misleading error messages.

```ballerina
@test:Config {}
function test1() {
    string[] keys = ["A"];
    test:assertEquals(keys, ["A"]);
}

@test:Config {}
function test2() {
    int[] arr = foo();
    test:assertEquals(arr, [1]);
}

function foo() returns int[] {
    int[] arr = [1];
    return arr;
}
```

_Output_
```shell
[fail] test1:
    Assertion Failed!: expected 'A' but found 'A' 
        at ballerina.test:createBallerinaError(assert.bal:41)
        ballerina.test:assertEquals(assert.bal:82)

[fail] test2:
    Assertion Failed!: expected '1' but found '1' 
        at ballerina.test:createBallerinaError(assert.bal:41)
        ballerina.test:assertEquals(assert.bal:82)
```

**Affected Versions:**
Checked with Ballerina 1.2.0

**Comment by MaryamZi** [comment]
Seems like improving the failure message is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/12892.

As for the tests themselves though the following would pass.
```ballerina
@test:Config {}
function test1() {
    string[] keys = ["A"];
    var expected =  ["A"]; // no contextually expected type, so the type is set as `[string]`
    test:assertEquals(keys, expected);
}
```

But IMO getting a comparison with an in-line definition to pass would be useful.

The current logic for `test:assertEquals` is as follows.

```ballerina
public function assertEquals(any|error actual, any|error expected, public string msg = "Assertion Failed!") {
    boolean isEqual = false;
    if (actual is anydata|error && expected is anydata|error) {
        isEqual = actual == expected;
    } else {
        isEqual = actual === expected;
    }

    if (!isEqual) {
        string expectedStr = io:sprintf("%s", expected);
        string actualStr = io:sprintf("%s", actual);
        string errorMsg = string `${msg}: expected '${expectedStr}' but found '${actualStr}'`;
        panic createBallerinaError(errorMsg, assertFailureErrorCategory);
    }
}
```

For something like `test:assertEquals(keys, ["A"])` the second parameter's type `any|error` is set as the contextually expected type for `["A"]`. Thus `["A"]`'s type is set as `any[]`.

This results in `expected is anydata|error` to evaluate to `false` which in turn results in a reference equality check `===` for this test (which then results in `false`).

IMO, we can improve this a bit by introducing separate test functions to assert based on value equality vs reference equality.

For example,
1. `public function assertValueEquals(anydata|error actual, anydata|error expected, public string msg = "Assertion Failed!")` - `test:assertValueEquals(keys, ["A"])` will pass.
2. `public function assertReferenceEquals(any|error actual, any|error expected, public string msg = "Assertion Failed!")`

Maybe we can have the current `assertEquals` also as a convenience function for those who want the current behaviour.

@hevayo @azinneera FYA please.

**Comment by janihur** [comment]
At minimum I'd like to see the value vs. reference equality explained in:

- Assertions chapter in https://ballerina.io/v1-2/learn/how-to-test-ballerina-code/
- https://ballerina.io/v1-2/learn/by-example/testerina-assertions.html
- https://ballerina.io/v1-2/learn/api-docs/ballerina/test/functions.html#assertEquals

When one knows that's the problem then one might be able to find equality comparison explanation in https://ballerina.io/v1-2/learn/by-example/equality.html

**Comment by Dilhasha** [comment]
### Anydata compatible types - pure values(except error)

**()
Boolean
Int
Float
Decimal
String
Byte**

Straightforward value comparison

**Tuple**

```
[string|int, float, boolean] t1 = [1, 1.0, false];
[int, float|string, boolean] t2 = [1, 1.0, false];

```
assertEquals(t1,t2) → true

Type along with the values are being checked.

```
[string|int, decimal, boolean] t1 = [1, 1.0, false];
[int, float|string, boolean] t2 = [1, 1.0, false];

```
assertEquals(t1,t2) → Assertion Failed!

**(anydata|error)[]**

```
float a = 1.1;
decimal b = 1.1;
(anydata|error)[] arr1 = ["wwjdsd","dds",a];
(anydata|error)[] arr2 = ["wwjdsd","dds",b];

```
assertEquals(arr1,arr2) → Assertion Failed!

**map<anydata|error>**

```
map<string> testMap1 = {code:"hello", action: "print"};
map<string> testMap2 = {code1:"hello", action: "print"};
```

assertEquals(testMap1,testMap2) → Assertion Failed!

Key and values both are compared.


**Xml**

```

xml x1 = xml `<book>The Lost World</book>`;
xml x2 = xml `Hello, world!`;
xml x3 = xml `<!--I am a comment-->`;
xml x4 = xml `<?target data?>`;
xml x5 = x1 + x2 + x3 + x4;

xml x6= xml `<book>The Lost World</book>` + xml `Hello, world!`+ xml `<!--I am a comment-->`+ xml `<?target data?>`;

```
assertEquals(x5,x6) → true

```
xml x5 = x1 + x2 + x3 + x4;
xml x6= xml `<book>The Lost World</book>` + xml `Hello, world!`+xml `<!--I am a comment-->`+ "<?target data?>";

```
assertEquals(x5,x6) → Assertion Failed!

**Table**

Assertion checks are failing. (ballerina 1.2.6)
TODO: Need to check in Swanlake with the new readonly option.


```
table<Employee> tbEmployee = table {
   {key id, name, salary},
   [
       {1, "Mary", 300.5},
       {2, "John", 200.5},
       {3, "Jim", 330.5}
   ]
};
table<Employee> tbEmployeeTest = table {
   {key id, name, salary},
   [
       {1, "Mary", 300.5},
       {2, "John", 200.5},
       {3, "Jim", 330.5}
   ]
};


```
assertEquals(tbEmployeeTest, tbEmployee);

Tries to do a value comparison but fails.

**Json**

checked by traversing through the json objects’ fields

```
    json a = {"name": "Ballerina"};
    json b = {"name": "Ballerina"};

```
assertEquals(a, b) → true

Record with type of each individual field is a subtype of anydata

```
Student anne = {
   name: "Anne",
   age: 18,
   grades: {
       maths: 70,
       physics: 80,
       chemistry: 55
   },
   ...address
};

Student anne1 = {
   name: "Anne",
   age: 18,
   grades: {
       maths: 70,
       physics: 80,
       chemistry: 55
   },
   "city": "Colombo",
   "country": "Sri Lanka"
};

```

test:assertEquals(anne, anne1) → true

Does a value comparison

**Comment by Dilhasha** [comment]
In other test frameworks such as Junit5, following functionalities are available.

- AssertEquals → class loading to support all available data types(deep value checks)
- AssertArrayEquals → class loading to support arrays of all available data types
- AssertSame → Assert whether it’ s the same object.

Based on these frameworks, the usual expectation from an "AssertEquals" function is to have deep value equality check. 
I suggest that we have the following options.

**assertEquals** - deep value equality for (any|error) i.e. for all available types in Ballerina

Also, as @MaryamZi mentioned we can have the following too.

**assertReferenceEquals** - check whether expected and actual refer to same object/record/table etc.

@hevayo @azinneera @Ibaqu 
Appreciate your thoughts.

**Comment by Dilhasha** [comment]
Based on the current specification, we are unable to support value equality for behavioral values. So, we are planning to introduce the following functions instead of "assertEquals".

> 1. public function assertValueEquals(anydata|error actual, anydata|error expected, public string msg = "Value Assertion Failed!")
> 
> 2. public function assertExactEquals(any|error actual, any|error expected, public string msg = "Exact Assertion Failed!")
> 

Until there is a way to support value equality for behavioral values, we plan to remove the "assertEquals" function. See the discussion at [[1]](https://groups.google.com/g/ballerina-dev/c/hNlQLAu3b4M/m/wOiRvJhvBAAJ).

Following is the list of tasks.

- [ ] Implement "assertValueEquals", "assertValueNotEquals", "assertExactEquals",  "assertExactNotEquals" and replace "assertEquals", "assertNotEquals" with the relevant function based on expected behavior.
- [ ] Write test cases to cover every data type using the new functions
- [ ] Update the website test guide [[2]](https://ballerina.io/learn/testing-ballerina-code/)
- [ ] Update BBE for testing [[3]](https://ballerina.io/learn/by-example/testerina-assertions.html)
- [ ] Update API docs [[4]](https://ballerina.io/learn/api-docs/ballerina/test/index.html)
- [ ] Update the spec [[5]](https://github.com/ballerina-platform/ballerina-spec/blob/master/test/test-framework-spec.md)

[1] https://groups.google.com/g/ballerina-dev/c/hNlQLAu3b4M/m/wOiRvJhvBAAJ
[2] https://ballerina.io/learn/testing-ballerina-code/
[3] https://ballerina.io/learn/by-example/testerina-assertions.html
[4] https://ballerina.io/learn/api-docs/ballerina/test/index.html
[5] https://github.com/ballerina-platform/ballerina-spec/blob/master/test/test-framework-spec.md

**Comment by Dilhasha** [comment]
Test specification updated with https://github.com/ballerina-platform/ballerina-spec/pull/587
