### ISSUE TITLE
Issues with XML subtypes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22069]
**Description:**
**Case I**
The spec says "A shape belongs to type `xml<T>` if all of its constituent items belong to T. So, for example, `xml<xml:Element>` is the type for xml values containing only elements.".

But this validation does not seem to happen atm. For example, the following does not fail.

```ballerina
import ballerina/lang.'xml;

public function main() {
    xml<'xml:Element> e = xml `<!--I'm a comment-->`;
}
```

**Case II**
The spec also says "Note that `xml<xml<T>>` is the same as `xml<T>` and that `xml<xml:Text>` is the same as `xml:Text`.".

So shouldn't the following be allowed?

```ballerina
import ballerina/lang.'xml;

public function main() {
    'xml:Comment e = xml `<!--I'm a comment-->`;
}
```

Currently results in a compilation error.
```cmd
$ ballerina run test.bal 
Compiling source
        test.bal
error: .::test.bal:4:27: incompatible types: expected 'xml:Comment', found 'xml'
```

**Affected Versions:**
1.2.0

**Comment by rdhananjaya** [comment]
Also note `xml:Text also allows the empty xml value.` from the spec.
