### ISSUE TITLE
Typeguard completion code snippet is not listed top

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#22079]
**Description:**
Typeguard completion code snippet for the `b` union is not sorted and listed top. Type guard code snippet is suggested way below after the module suggestions starting with 'ballerina/...' as well.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    string city = "Colombo";
    string country = "Sri Lanka";
    string codeLiteral = "code";

    map<string> addrMap = {

        line1: "No. 20",
        line2: "Palm Grove",

        city: "Colombo 03",

        country,

        [codeLiteral]: "00300"
    };
    io:println(addrMap);

    string? b = addrMap["country"];

    b<cursor>
}
```
**Affected Versions:**
1.2.0

**Comment by mohanvive** [comment]
Above issue is fixed in the latest VScode plugin. Type guard suggestion is listed as the 1st option. Hence, closing the issue.
