### ISSUE TITLE
Create Functionality and Implementation spec for Testerina

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#22094]
**Description:**
Functionality and Implementation spec needs to be generated for Testerina. 
This needs to take into consideration the newly implemented features

**Comment by Ibaqu** [comment]
Rough Draft : https://docs.google.com/document/d/1Rjbvi3pr9Wlc1EW9gcIunThEHkFfFNqZY5dsmVopKZo/edit?usp=sharing

**Comment by hevayo** [comment]
Action Items:
- [ ] Add mocking API design 
- [ ] Overall review second pass
- [ ] Add to the spec repo

**Comment by azinneera** [comment]
The functional spec is completed and merged to https://github.com/ballerina-platform/ballerina-spec
Link to document: https://github.com/ballerina-platform/ballerina-spec/blob/master/test/test-framework-spec.md
