### ISSUE TITLE
Need to stop scheduler when the cache life-time is over

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#22115]
**Description:**
At the moment there is no way to stop the `task:Scheduler` which is used internally in `ballerina/cache` module.

The following 2 PRs disabled the test cases which starts the internal `task:Scheduler`.
https://github.com/ballerina-platform/ballerina-lang/pull/22114
https://github.com/ballerina-platform/ballerina-lang/pull/22113

Because of this there may be OOM situations as follows:
```shell
Task :ballerina-cache:test

ballerina-test-suite > ballerina-cache-test-suite > org.ballerinalang.stdlib.cache.CacheTest > testCreateCache STANDARD_ERROR
Exception in thread "QuartzScheduler_QuartzSchedulerThread" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by kalaiyarasiganeshalingam** [comment]
These tests are enabled in [#1](https://github.com/ballerina-platform/module-ballerina-cache/pull/1).
