### ISSUE TITLE
Remove dependency on Axiom library as Ballerina xml no longer depend on it

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22151]
**Description:**
Remove dependency on Axiom library as Ballerina XML no longer depend on it.

This issue depends on https://github.com/ballerina-platform/ballerina-lang/issues/20064

Removing Axiom dependency would decrease the generated Ballerina JAR file by few megabytes.

**Steps to reproduce:**

**Affected Versions:**
1.2.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
