### ISSUE TITLE
XML literal should be able to directly declare XML named subtypes.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22155]
**Description:**
'xml:Element e = xml `<element>content</element>`; should be allowed.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by irshadnilam** [comment]
This is mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/22069 
Please refer to case 2. 

Shall we close this issue?

**Comment by rdhananjaya** [comment]
Are you planing to fix both of the issues in the same PR?

**Comment by irshadnilam** [comment]
> Are you planing to fix both of the issues in the same PR?

Yes. I think it is related.

**Comment by MaryamZi** [comment]
@rdhananjaya, seems like this was fixed with https://github.com/ballerina-platform/ballerina-lang/pull/22323? Shall we close this issue?
