### ISSUE TITLE
Parameter defaults should not be added if there is a rest arg

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22204]
**Description:**
$title.

The [spec](https://ballerina.io/spec/lang/2020R1/#function_call) says "If there is rest-arg, then no parameter defaults are added.".

**Steps to reproduce:**
But the following works at the moment.

```ballerina
public function main() {
    string[] x = ["hello", "world"];
    foo(1, ...x);
}

function foo(int i, float f = 1.0, string... s) {
}
```

**Affected Versions:**
1.2.0

**Comment by hasithaa** [comment]
Yes, This is a bug.
