### ISSUE TITLE
Documentation generation doesn't seems to support for public constant documentation

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22238]
**Description:**
Consider the generated documentation for constants in langlib xml module. https://github.com/ballerina-platform/ballerina-lang/blob/dcbd58423b37330246186a72ff5b7c3cbf0429e9/langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal#L17
Generated doc: https://ballerina.io/v1-1/learn/api-docs/ballerina/lang.xml/constants.html#XML_ELEMENT

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.1.x

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
The below links are broken due to this as reported in https://github.com/ballerina-platform/ballerina-lang/issues/22237:

- https://ballerina.io/v1-1/learn/api-docs/ballerina/lang.xml/constants.html#XML_ELEMENT
- https://ballerina.io/v1-1/learn/api-docs/ballerina/lang.xml/types.html#XMLType

**Comment by pramodya1994** [comment]
We cant see the description of these constants since they are not documented in the source [1].

```ballerina
public const XML_ELEMENT = "element";
public const XML_SEQUENCE = "sequence";
public const XML_TEXT = "text";
public const XML_COMMENT = "comment";
public const XML_PI = "pi";
```
@praneesha  Shall we add `Area/StandardLibs` label and remove `Component/Docerina` label?

[1] https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.1.x/langlib/lang.xml/src/main/ballerina/src/lang.xml/unstable.bal#L17

**Comment by hasithaa** [comment]
These constants are deprecated and removed with 1.2.0 release.

**Comment by praneesha** [comment]
> These constants are deprecated and removed with 1.2.0 release.

What about the types https://ballerina.io/v1-1/learn/api-docs/ballerina/lang.xml/types.html#XMLType?

**Comment by rdhananjaya** [comment]
It's also gone https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal

**Comment by praneesha** [comment]
Closing this since the respective constants and types has been removed from 1.2.0 onwards as per the above comments.
