### ISSUE TITLE
Observability : Memory leak when an gRPC client is available

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#22233]
**Description:**
When there is a gRPC client is available and the observability is enabled, the response from the metrics endpoint grows linearly based on the gRPC calls made by the gRPC client. When we observe the response from metrics endpoint, we can see that the grpc_message_content is also there as a key. In other words, there is a record for each and every gRPC event we send.

**Steps to reproduce:**
Include a gRPC Client inside the ballerina project. Enable observability metrics. Run the project such that the gRPC client is invoked a few times. And call the metrics endpoint.

**Affected Versions:**
1.1.4

**OS, DB, other environment details and versions:**
MacOS-Mojave

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**
@grainier

**Comment by VirajSalaka** [comment]
@nadundesilva Please add if there is anything missing.

**Comment by daneshk** [comment]
This issue was due to gRPC message content is added as metrics value.
