### ISSUE TITLE
Not possible to access json payload when payload is a json array

### ISSUE THREAD

**Issue by rmsamitha** [ballerina-platform/ballerina-lang#22247]
**Description:**
I have a POST resource and I want to pass a JSON array as the request payload.
````java
   @http:ResourceConfig {
        methods: ["POST"],
        path: "/news-articles/validatetest",
        cors: {
            allowOrigins: ["*"],
            allowHeaders: ["Authorization, Lang"]
        },
        produces: ["application/json"],
        consumes: ["application/json"]
    }
    resource function validateArticlesTest(http:Caller caller, http:Request req) {
        var x = req.getJsonPayload();
        io:println(x);
        io:println("test");
    }
````
But seems when run this and invoke, var x becomes allways null.

````
curl -X POST http://localhost:9090/news-articles/validatetest -H "Content-Type: application/json" --data '[{"aaa":"amaval", "bbb":"bbbval"},{"ccc":"amaval", "ddd":"bbb  val"}]'

````

**Affected Versions:**
1.1.3

**Comment by rmsamitha** [comment]
I could get this work by below approach by casting.

```
resource function validateArticlesTest(http:Caller caller, http:Request req) {
        json[]|error jsonarray = <json[]>req.getJsonPayload();
        io:println(jsonarray);
}
```
Hence closing the issue.

**Comment by MaryamZi** [comment]
@rmsamitha, when casting, the resultant value is always the target type if successful.

So the following (without `error`) will work.
```ballerina
json[] jsonarray = <json[]>req.getJsonPayload();
```

But if unsuccessful, it will result in a panic. 

For example, in case `req.getJsonPayload()` could evaluate to an error or could even be a `json` payload but not a JSON array (e.g., JSON object, digit, null, etc.) the cast to `json[]` will result in a panic, which in an HTTP resource will result in a 500 internal server error.

If that's not the intended behaviour, and you want to specifically handle the error scenarios, it would be better to do something like
```ballerina
        json|error x = req.getJsonPayload();
        
        if x is json[] {
            // Valid, received a JSON array.
        } else if x is json {
            // Invalid - JSON, but not an array.
        } else {
            // Invalid - `error`
        }
```

**Comment by rmsamitha** [comment]
Thank you very much for the insight @MaryamZi
