### ISSUE TITLE
Improve leading and trailing trivia capturing

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#22246]
- Whitespaces and comments should be part of the token. They can be part of the leading trivia or trailing trivia of a token.

Let's follow the C# way of capturing trivia. https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#syntax-trivia.  There are some advantages to this approach.  Comments will always be attached to the correct token.  This approach also produces the best results in the incremental compiler.

**Comment by SupunS** [comment]
Fixed with  #22272
