### ISSUE TITLE
Default arguments are not considered in taint analyzer

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22273]
**Description:**
```ballerina
public function main() {
    foo();
}

function foo(@untainted int i = bar()) { // This probably shouldn't be allowed.
    k(i); // tainted value from 'bar' is passed to i.
}

function bar() returns @tainted int {
    return 0;
}

function k(@untainted int i) {
    
}
```

With the current implementation of default arguments in the compiler, I don't see a straight forward way to support this in the taint analyzer.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
We are removing the current taint analysis implementation with #30981, Hence closing this issue.
