### ISSUE TITLE
Cannot access files packed inside the tests/resources folder

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#22296]
**Description:**
When the .jar of a module is created, the resource files placed inside the tests/resources folder is not available/packed inside the .jar.

**Affected Versions:**
Ballerina 1.2.0

**Comment by IrushiL** [comment]
Closing this issue, since https://github.com/ballerina-platform/ballerina-lang/issues/18881 tracks a similar issue.
