### ISSUE TITLE
`.slice()` on a tuple with a rest-descriptor fails at runtime

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22350]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    [int, string...] x = [1, "hello", "world"];

    (int|string)[] a = x.slice(1);
}
```

```cmd
$ ballerina run xyz.bal 
Compiling source
        xyz.bal
Running executables

error: {ballerina/lang.array}InherentTypeViolation message=incompatible types: expected 'int', found 'string'
        at ballerina.lang_array:slice(array.bal:106)
           xyz:main(xyz.bal:4)
```

This is because the type of the sliced array is only computed based on the members, and does not consider the rest-descriptor.

https://github.com/ballerina-platform/ballerina-lang/blob/v1.2.0/langlib/lang.array/src/main/java/org/ballerinalang/langlib/array/Slice.java#L82

So, in this scenario, the sliced array is created as an `int[]`, to which we then try to add strings.

**Affected Versions:**
1.2.0

**Comment by pubudu91** [comment]
Closing since this was fixed with #22373
