### ISSUE TITLE
[System] Casting issue when there is an error while executing a process

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#22363]
**Description:**
Following error comes when there is an error while executing a process. Due to specific error doesn't handle correctly.
```
error: {ballerina}TypeCastError message=incompatible types: 'error' cannot be cast to 'system:Process|system:InvalidOperationError|system:PermissionError|system:FileSystemError|system:FileNotFoundError'
        at ballerina:nativeExec(system.bal:85)
           ballerina:exec(system.bal:82)
           daneshk.system_exec:main(main.bal:5)
```

**Affected Versions:**
1.2.0

**OS, DB, other environment details and versions:**
All environments

**Comment by MaryamZi** [comment]
The error reason used seems to be incorrect https://github.com/ballerina-platform/ballerina-lang/blob/v1.2.0/stdlib/system/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Exec.java#L60 which seems to result in the created error not belonging to the return type specified for the function.
