### ISSUE TITLE
Allow a query-expr to construct a stream

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#22379]
This works lazily: the stream has a closure that returns the next result when the closure is called. Errors are also returned lazily through the stream's iterator's termination value: this includes errors in the source iterator or from check expressions in the where and select clauses.

Because of the above difference in semantics, queries returning streams are prefixed with the `stream` keyword.

```
stream-query-expr := "stream" query-expr
```

Example

```
function myMap(string) returns int|Error1;

function foo(string[] source) returns int[]|Error1
{
   return from s in source select check myMap(s);
}

function foo(stream<string,Error2> source)
   returns stream<int,Error1|Error2>
{
   return stream from s in source select check myMap(s);
}
```

**Comment by pcnfernando** [comment]
Closing hence duplicated in https://github.com/ballerina-platform/ballerina-lang/issues/21789
