### ISSUE TITLE
Replace the use of semantic errors with never type in type calculation logic

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22426]
In our type checker we have various types of logic written for calculating types (intersections, unions etc). Currently these use semantic error to indicate if a calculation results in zero matching types (e.g., no intersection between two types). Need to see if we can use `never` type instead.

**Comment by hasithaa** [comment]
Depends on https://github.com/ballerina-platform/ballerina-lang/issues/22099

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
