### ISSUE TITLE
Skip running tests if build fails at CreateJarTask level

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#22440]
**Description:**
If there are any interop related issues, the compilation fails at CreateJarTask level. But the test task is still getting executed regardless of this failure as below.

```
$ ballerina build --all
Compiling source
	kishanthan/foo:0.1.0

Creating balos
	target/balo/foo-2020r1-java8-0.1.0.balo
error: kishanthan/foo:0.1.0::main.bal:10:1: {ballerina/java}OVERLOADED_METHODS 'Overloaded methods 'getResource' with '0' parameter(s) in class 'class redis.clients.jedis.JedisSentinelPool', please specify class names for each parameter with 'paramTypes' field in the annotation'

Running Tests
error: failed to load init class :kishanthan.foo.___init

Generating Test Report
	target/test_results.json

	View the test report at: file:///Users/kishanthan/WSO2/work/bal-test/test/interop-test/proj1/target/test_results.html
error: there are test failures

```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by parkavi11** [comment]
This issue is fixed now.
<img width="1392" alt="Screenshot 2020-06-15 at 15 23 23" src="https://user-images.githubusercontent.com/28732894/84644000-30bf2600-af1c-11ea-828d-0a6805b7543d.png">

**Comment by Ibaqu** [comment]
Closing since handled in SL
