### ISSUE TITLE
VSCode Plugin Not Detecting Home Directory

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-lang#22450]
**Description:**
When there is a space in a user's home directory (for example, mine was "SamWeeras 1"), the VSCode plugin doesn't automatically detect Ballerina home. Output can be seen in the below image:

![Ballerina-home-auto-detection-error-VSCode](https://user-images.githubusercontent.com/11717039/78338689-d6672800-75b0-11ea-978c-046331477572.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
As per the output log, this seems to be a CLI issue when executing `ballerina home` command.

**Comment by NipunaRanasinghe** [comment]
Closing along with #27
