### ISSUE TITLE
NPE when running openapi gen-client

### ISSUE THREAD

**Issue by mghaigh** [ballerina-platform/ballerina-lang#22460]
**Description:**

Get NPE  when trying to generate client stubs from a 3rd party's open-api spec. See attached files (1st one is actually a .yaml file)
[acrocredit.txt](https://github.com/ballerina-platform/ballerina-lang/files/4430016/acrocredit.txt)
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/4430033/ballerina-internal.log)
The openapi yaml file appears to be valid but because the generator crashes, with no indication of what caused the crash, it's hard to review the yaml. I suggest the generator could do with more error reporting/logging.
** Update **
Having used the OpenAPI a bit more I noticed that some of it uses nested object definitions, rather than defining types in the schema section. That is legal OpenAPI, but that could be the cause of the problem. You may have already fixed the bug but thought I would point this out. 
**Steps to reproduce:**
ballerina openapi gen-client acrocredit acrocredit.yaml

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Hi @mghaigh  We were able to reproduce the issue will update on a fix.
