### ISSUE TITLE
Erroneous cyclic module imports errors in VS Code

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-lang#22487]
**Description:**

When working on a project with multiple modules, the VS Code plugin show these errors sometimes although there are no cyclic dependencies (module A uses module B but module B does not use module A).
It happens quite often, sometimes multiple times a day. The problem has always been there, from when i started using ballerina in 1.1.1 and still happens in 1.2.
The workaround is to restart VS Code. I'd like to know if there is another way to refresh the plugin analysis without restarting VS Code

**Steps to reproduce:**

Have a project with 2 or more modules (one has to use elements from the other), edit files in both modules, it will happen occasionally.

**Affected Versions:**

**OS, DB, other environment details and versions:**
Ubuntu 19

jBallerina 1.2.0
Language specification 2020R1
Ballerina tool 0.8.0

**Comment by rasika** [comment]
Closing this since this behavior is not observed in latest release of jBallerina 1.2.x. Feel free to reopen if the problem still exists.
