### ISSUE TITLE
Add support for fork statement

### ISSUE THREAD

**Issue by m36dot** [ballerina-platform/ballerina-lang#22485]
Add support for fork statement in incremental parser

<code>fork-stmt := fork { named-worker-decl+ }</code>

https://ballerina.io/spec/lang/2020R1/#fork-stmt

**Comment by SupunS** [comment]
I just realised we might have a put this on hold for now, since worker-decl is not yet supported.

**Comment by m36dot** [comment]
> I just realised we might have a put this on hold for now, since worker-decl is not yet supported.

noted

**Comment by m36dot** [comment]
Done. https://github.com/ballerina-platform/ballerina-lang/pull/22860
