### ISSUE TITLE
Module prefixes are referred to as 'alias' in module BBE

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22481]
**Description:**
In spec what’s called `module-prefix` is referred to as module alias in module BBE https://ballerina.io/v1-2/learn/by-example/modules.html
Spec reference: https://ballerina.io/ballerina-spec/spec.html#section_8.1

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via [1] & [2].

[1] https://github.com/ballerina-platform/ballerina-lang/pull/26245
[2] https://github.com/ballerina-platform/ballerina-distribution/pull/859
