### ISSUE TITLE
Build/run prints an additional error "error: compilation contains errors"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22484]
**Description:**
$title.

We've avoided printing this error by special-casing `BLangCompilerException`. See https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-tool/src/main/java/org/ballerinalang/tool/Main.java#L62

But the `CompileTask` throws a `BLauncherException` with this error, and thus it is printed. https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-packerina/src/main/java/org/ballerinalang/packerina/task/CompileTask.java#L79

The exception thrown here hasn't changed recently though. Seems like some other change has caused this previously un-executed code to execute now.

If that is intended, we should be able to fix this by simply changing the exception thrown.

**Comment by MaryamZi** [comment]
This happens on 1.2.1 too as @warunalakshitha pointed out offline.

**Comment by hevayo** [comment]
Can you please send the `ballerina -v` output to check the update tool version.

**Comment by MaryamZi** [comment]
**Sample**
```ballerina
public function main() {
    int i = "s";
}
```

**Output**
```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:2:13: incompatible types: expected 'int', found 'string'
error: compilation contains errors

$ ballerina -v
jBallerina 1.2.1
Language specification 2020R1
Ballerina tool 0.8.5
```
