### ISSUE TITLE
Incorrect error message for missing record fields

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22492]
Consider the program below:
```ballerina
public function main() {
    Foo f = {};
    int x = f.x;
}

type Foo record {|
|};
```
For the above program, the following error is given:
```
invalid operation: type 'Foo' does not support field access for non-required field 'x'
```
As it can be seen, `Foo` is a closed record. Therefore, this should've given an error message like `undefined field 'x' in record 'Foo'`. The same issue is there for optional field access (`?.`).

**Comment by MaryamZi** [comment]
For field access the error is now `undeclared field 'x' in record 'Foo'`.

For optional field access it still says `invalid operation: type 'Foo' does not support optional field access for field 'x'` though.
