### ISSUE TITLE
Bug in checking expression in parser

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#22505]
**Description:**
`checking expression` error recovery is incomplete. Right now error handler will not look into `checking expression` when it encounters an  `expression` type error recovery. It should be added to `ParserRuleContext[] EXPRESSIONS` and do corresponding changes if necessary.  

**Suggested Labels:**
Component/Parser, Priority/Low

**Comment by SupunS** [comment]
This is fixed in the latest code. Hence closing the issue.
