### ISSUE TITLE
OAuth2 Authentication fails for Azure Log Analytics API

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#22543]
**Description:**
I used OAuth2 with the client credentials grant type to call the [Azure log analytics API](https://dev.loganalytics.io/). It seems the provided OAuth2 token is not valid for the requested resource.

Bellow is the error log from log analytics API:
```
error=message=The provided authentication is not valid for this resource
code=InvalidTokenError innererror=code=InvalidTokenError
message=Could not validate the request. Challenge failed: SignatureVerificationFailed
```

**Affected Versions:**
Ballerina 1.2.0

**Suggested Assignees:**
@ldclakmal

**Comment by madushajg** [comment]
The audience is incorrect in the OAuth2 token which sends to the log analytics API. This caused maybe because of the [Azure log analytics OAuth2 ](https://dev.loganalytics.io/documentation/Authorization/OAuth2) spec is different from the OAuth2 spec referred by Ballerina.

**Comment by tharinduwijewardane** [comment]
Its better if the user can optionally set custom parameters of the request sent to token url.
Azure expects a parameter named `resource`. some other party may require something else.

**Comment by ldclakmal** [comment]
Yes. This fails because of the `resource` parameter send in the POST body. But I couldn't find such thing (custom parameters) in client credentials grant type of OAuht2 RFC [1].

[1] https://tools.ietf.org/html/rfc6749#section-1.3.4

**Comment by tharinduwijewardane** [comment]
Its actually called "endpoint parameters"
check https://tools.ietf.org/html/rfc6749#section-8.2

**Comment by ldclakmal** [comment]
Thanks @tharinduwijewardane. We will fix this.
