### ISSUE TITLE
constructFrom() doesnt work as expected with Union types

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#22541]
**Description:**
Using `constructFrom()` function for a Union type by passing a string value shows compilation issues. This is not reproducible in 1.1.0.

**Steps to reproduce:**
`jwt:JwtSigningAlgorithm` is a union type of strings. 

Using the following code to construct the union type
```
jwt:JwtSigningAlgorithm | error jwtAlg = jwt:JwtSigningAlgorithm.constructFrom(config:getAsString("SIGNING_ALG"));
``` 

Causes the following compilation error
```
error: registry/registry_auth_interceptor_api:0.0.0::auth_interceptor_service.bal:381:46: undefined symbol 'JwtSigningAlgorithm'
``` 

**Affected Versions:** 1.2.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Closing since `constructFrom` function has been removed.
