### ISSUE TITLE
[Spec Deviation] Actions allowed in default values and module level declarations

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22610]
In the spec, only expressions are allowed in module-level declarations, default values for fields in records and objects and in default values for function parameters.

The spec says the following regarding the module-level declarations:

- Listener declaration
> listener-decl :=
   metadata
   [public] listener [type-descriptor] variable-name = expression ;

- Module variable declaration
> module-var-decl :=
   metadata
   [final]
   typed-binding-pattern = expression ;

- Module constant declaration
> module-const-decl :=
   metadata
   [public] const [type-descriptor] identifier = const-expr ;

But currently the following are valid:
```ballerina
Foo mF = new("module_level");

string mV1 = mF->test(); // Should be compile error

int mV2 = start bar(); // Should be compile error

public function main() {
}

function bar() returns int {
    return 10;
}

type Foo client object {

    string name;

    function __init(string name) {
        self.name = name;
    }

    remote function test(string s = "") returns string {
        return s == "" ? self.name : self.name + "->" + s;
    }

    remote function getInt() returns int => 100;
};
```
The same is true regarding using actions for default values of params and record/object fields since the spec defines default values as follows:
> default-value := = expression

```ballerina
function actionsInParams(string p1 = mF->test()) { // Should be compile error
    io:println(p1);
}

type Person record {|
    string name;
    int age = mF->getInt(); // Should be compile error
|};
```

**Comment by MaryamZi** [comment]
Errors are now logged as expected.

The following changes were done to the original sample:
- the type of `mV2` was changed from `int` to `future<int>`
- parentheses were introduced in the ternary expression in the body of the `test` method

```ballerina
Foo mF = new("module_level");

string mV1 = mF->test();

future<int> mV2 = start bar();
public function main() {
}

function bar() returns int {
    return 10;
}

client class Foo  {

    string name;

    function init(string name) {
        self.name = name;
    }

    remote function test(string s = "") returns string {
        return s == "" ? self.name : (self.name + "->" + s);
    }

    remote function getInt() returns int => 100;
}
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:3:14: action invocation as an expression not allowed here
error: .::qwe.bal:5:19: action invocation as an expression not allowed here
```

Errors are also logged for 
```ballerina
function actionsInParams(string p1 = mF->test()) { // action invocation as an expression not allowed here
}

type Person record {|
    string name;
    int age = mF->getInt(); // action invocation as an expression not allowed here
|};
```
