### ISSUE TITLE
Lang server support for nested actions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22625]
We'll be addressing #17993 through PR #22602 and the corresponding lang server support needs to be provided as well.

**Comment by nadeeshaan** [comment]
Definition tests are being addressed with https://github.com/pubudu91/ballerina/pull/19

**Comment by rasika** [comment]
@nadeeshaan can we close this issue now?

**Comment by nadeeshaan** [comment]
> @nadeeshaan can we close this issue now?

@rasika Yes this is supported now. Hence I'm closing the issue.
