### ISSUE TITLE
PositionalArgument expression method throws ClassCastException

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#22633]
**Description:**
PositionalArgument expression method throws ClassCastException due to inconsistent object classes returned.

**Steps to reproduce:**

As per the contract it should return an `Expression`. But for the below code it returns a `Token`;
```ballerina
import ballerina/io;
public function main (string... args) {
   io:println("Hello world!");
}
```
<img width="1174" alt="Screenshot 2020-04-15 at 15 25 13" src="https://user-images.githubusercontent.com/1448489/79324670-9186ae00-7f2d-11ea-94df-27338f720c9b.png">

Below returns a BinaryExpression;
```ballerina
import ballerina/io;
public function main (string... args) {
   io:println("Hello world!" + "rasika");
}
```
<img width="1176" alt="Screenshot 2020-04-15 at 15 26 15" src="https://user-images.githubusercontent.com/1448489/79324687-99465280-7f2d-11ea-9432-5d8548aaf5eb.png">

```java
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.Token cannot be cast to io.ballerinalang.compiler.syntax.tree.Expression
```
**Affected Versions:**
1.3.0-SNAPSHOT

**Comment by SupunS** [comment]
Fixed in preview1
