### ISSUE TITLE
Ballerina run requires a jdk

### ISSUE THREAD

**Issue by chipsmaster** [ballerina-platform/ballerina-lang#22643]
**Description:**

Ballerina tool requires jdk/jre installed although not specified in installation procedure and although a jdk is already included in ballerina distribution

"ballerina run <module>" will fail, but "ballerina compile <module>" works fine
Also, "ballerina run target/module.jar" works fine

Use the jdk bundled in ballerina for every ballerina tool command or fix the installation procedure https://ballerina.io/v1-2/learn/installing-ballerina/

**Steps to reproduce:**

From a fresh linux (debian) server or docker container, install ballerina from a debian package, make a project/module "x" and run "ballerina run x"
It will say
"error: Error occurred while running the executable java.io.IOException: error=2, No such file or directory"

If another jdk is installed in the system at the wrong version, there will a warning
"WARNING: Incompatible JRE version '11.0.6' found. This ballerina program supports running on JRE version '1.8.*'"

**Affected Versions:**

1.1.x 
1.2.x

**Comment by keizer619** [comment]
This fix will be available from 1.2.9 and swan lake preview 5 releases
https://github.com/ballerina-platform/ballerina-lang/issues/26404
