### ISSUE TITLE
Compile time Type Checking improvements for table

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#22665]
**Description:**
Have to consider below cases for type checking,

- Readonly related validation for table
- Constant validation for table record literal
- Negative test cases

**Comment by mohanvive** [comment]
Added through below PRs,
- https://github.com/ballerina-platform/ballerina-lang/pull/22857
- https://github.com/ballerina-platform/ballerina-lang/pull/22832
- https://github.com/ballerina-platform/ballerina-lang/pull/22792
- https://github.com/ballerina-platform/ballerina-lang/pull/22736
- https://github.com/ballerina-platform/ballerina-lang/pull/22735

**Comment by mohanvive** [comment]
Also below PRs,

- https://github.com/ballerina-platform/ballerina-lang/pull/22928
- https://github.com/ballerina-platform/ballerina-lang/pull/22912
- https://github.com/ballerina-platform/ballerina-lang/pull/22892
