### ISSUE TITLE
Improve error message of BFM documentation analysis

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#22672]
**Description:**
Currently the error just says invalid reference. Need to improve it to give more context.

**Steps to reproduce:**

**Affected Versions:**
since 1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Area/Language

**Suggested Assignees (optional):**
@dulvinw

**Comment by SupunS** [comment]
I think these reference should be validated at the document analyzer phase.
Parser does all the syntax validations.
