### ISSUE TITLE
Module which compiles across Ballerina specifications throws bad sad error while running

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#22679]
**Description:**
I get a bad sad error when running an app developed using the [module-jira](https://github.com/ballerina-platform/module-jira). I built my app using Ballerina 1.2.1. However, the latest [module-jira](https://github.com/ballerina-platform/module-jira) [binaries (version 0.9.1)](https://central.ballerina.io/wso2/jira7/0.9.1) currently available in Ballerina Central have been built using a 2019r3 Ballerina version. Ballerina 1.2.1 implements 2020r1 language specification. Note that I do not get any build time errors when building my app with [module-jira](https://github.com/ballerina-platform/module-jira)  [binaries (version 0.9.1)](https://central.ballerina.io/wso2/jira7/0.9.1) .

I was able to eliminate the bad sad error by locally building the [module-jira](https://github.com/ballerina-platform/module-jira) using Ballerina 1.2.1 and then linking the newly built balo with my app via its Ballerina.toml file. When building [module-jira](https://github.com/ballerina-platform/module-jira) locally I did not do any code changes. Since I did no code changes while building the connector module with Ballerina 1.2.1, I think I should not get such bad sad error while running the app which was built using [module-jira](https://github.com/ballerina-platform/module-jira)  [binaries (version 0.9.1)](https://central.ballerina.io/wso2/jira7/0.9.1) .

**Steps to reproduce:**
- Create new sample Ballerina app
    - Run `ballerina new sample`
    - Run `cd sample`
    - Run `ballerina add app`
    - Add the following sample code to `main.bal`

```
import ballerina/auth;
import ballerina/http;
import ballerina/jira7;
import ballerina/log;

auth:OutboundBasicAuthProvider outboundBasicAuthProvider = new ({
    username: "testusername",
    password: "testpassword"
});

http:BasicAuthHandler outboundBasicAuthHandler = new (outboundBasicAuthProvider);
jira7:JiraConfiguration jiraConfig = {
    baseUrl: "https://testhost/jira/rest/api/2",
    clientConfig: {
        auth: {
            authHandler: outboundBasicAuthHandler
        }
    }
};

jira7:Client jiraConnectorEP = new (jiraConfig);


public function main() {
    jira7:ProjectCategory projectCategory_test = {};   
    string projectCategory = "10670";
    var output = jiraConnectorEP->getProjectCategory(projectCategory);
    if (output is jira7:ProjectCategory) {
        projectCategory_test = <@untainted>output;
        log:printInfo(projectCategory_test.toString());
    } else {
        log:printInfo(<string>output.detail()?.message);
    }
}
```
- Build the sample app using the command `ballerina build -a --skip-tests=true`
- Run the sample app using the command `ballerina run target/bin/app.jar`
- This should result in the following Bad Sad error.
```
[2020-04-16 15:17:00,437] SEVERE {b7a.log.crash} - $type$$anonType$builtin$0 
java.lang.NoSuchFieldError: $type$$anonType$builtin$0
	at miyurud.app.main.main(main.bal:32)
	at miyurud.app.___init.$lambda$main$(app)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:482)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:263)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:231)
	at java.lang.Thread.run(Thread.java:748)
```

- Next, clone [module-jira](https://github.com/ballerina-platform/module-jira)
- Build it using the command `JAVA_OPTS="-DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true" ballerina build -a -c --skip-tests=true`
- Edit the `Ballerina.toml` file of the sample project and add the newly built module-jira Balo file as follows
```
[project]
org-name= "miyurud"
version= "0.1.0"

[dependencies]
"ballerina/jira7" = { path = "/home/miyurud/git/module-jira/target/balo/jira7-2020r1-any-0.9.2.balo", version = "0.9.2"}
```
- Next, rebuild the sample project using `ballerina build -a --skip-tests=true`
- Run the sample app using the command `ballerina run target/bin/app.jar`
- This should result in sample app running and printing an error message which is the expected outcome.
``
2020-04-16 16:03:10,167 INFO  [miyurud/app] - Error occurred while invoking the JIRA REST API
``

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
Ubuntu 18.04, Ballerina 1.2.1, [module-jira](https://github.com/ballerina-platform/module-jira)  [binaries (version 0.9.1)](https://central.ballerina.io/wso2/jira7/0.9.1) 

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The issue is not present in Swan Lake releases. Please download the latest distribution from https://ballerina.io/downloads/
