### ISSUE TITLE
Add support for &, |,  ^, <<, >>, >>> operators in compound-assignment statement

### ISSUE THREAD

**Issue by m36dot** [ballerina-platform/ballerina-lang#22678]
Add support for &, |,  ^, <<, >>, >>> operators for 

compound-assignment-stmt := lvexpr CompoundAssignmentOperator action-or-expr ;
CompoundAssignmentOperator := BinaryOperator =
BinaryOperator := + | - | * | / | & | | | ^ | << | >> | >>>

in incremental parser

**Comment by SupunS** [comment]
Added in preview1
