### ISSUE TITLE
Create a design document for an improved Log API

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#22683]
**Description:**
Ballerina Log API needs to be improved. The design document should include:
1. New API functions/ changes to existing API functions
2. New logging pattern
3. Sample codes and outputs.

**Suggested Labels (optional):**
Improvement, Design

**Suggested Assignees (optional):**
Madhuka

**Comment by MadhukaHarith92** [comment]
The design document can be found here.
https://docs.google.com/document/d/1WBmA_Kr-qWWirMVQKytXTnOwDFTf3z10Gjf8uAP583Q/edit#heading=h.pm5zlxyitxcg

**Comment by daneshk** [comment]
Closing the issue, Since we completed design phase.
