### ISSUE TITLE
Create workflows for remaining operating systems

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#22711]
**Description:**
Currently we have implemented installer test framework and included workflow for ubuntu OS[1]. Need to include workflows for following operating systems

- Windows
- MacOS
- CentOS

[1] https://github.com/ballerina-platform/ballerina-release/blob/master/.github/workflows/ballerina-test-installers.yml

**Comment by hevayo** [comment]
duplicate
