### ISSUE TITLE
Fix the Displaying of Anonymous Issues in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#22715]
**Description:**
Currently, anonymous records are displayed as shown below in API Docs. We need to fix this or add descriptions.

<img width="1554" alt="Screenshot 2020-04-17 at 14 34 57" src="https://user-images.githubusercontent.com/11707273/79553303-e820f300-80b9-11ea-8cac-6a147ec5e33a.png">

These links are there in the below links.

[1] http://dev.ballerina.io/learn/api-docs/ballerina/lang.string/index.html
[2] http://dev.ballerina.io/learn/api-docs/ballerina/lang.stream/index.html
[3] http://dev.ballerina.io/learn/api-docs/ballerina/lang.xml/index.html

**Affected Product Version:**

- 1.2.x
- Swan Lake

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/24915

**Comment by shehan360** [comment]
Anonymous objects and records are no longer displayed in the module page with the latest changes.

![stream](https://user-images.githubusercontent.com/33398983/87639304-ab20d700-c762-11ea-85c8-da0c53f0128f.png)

However the pages are still generated and they are linked from their relevant functions.

**Comment by praneesha** [comment]
Although, these are not displayed in the module index page, they are linked and the pages can be accessed via the links.

When those pages are accessed, they are still shown as "T" values, which are not meaningful. 

Therefore, we need to discuss and come up with a proper way to denote these values in API Docs.

**Comment by praneesha** [comment]
The solution we finalised was to print the complete definition instead of the "T" and instead of navigating,
showing the type when hovering over that definition.
