### ISSUE TITLE
Create supporting blogs for Ballerina Testing Guide

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#22729]
**Description:**
Write blogs to support the documentation describing best practices for writing tests.

Draft content:
Link : https://docs.google.com/document/d/1GMHa6POsD1atqzrBPq9oC1H-rr1PzXwcY6_9NGpHC7Q/edit?usp=sharing

**Comment by azinneera** [comment]
Draft content: https://github.com/Ibaqu/CodeBlogs/

**Comment by Dilhasha** [comment]
Note
--
- Mention the version of Ballerina this is applicable
- Revist the blogs periodically and publish updated versions - if applicable
- Publish how to guides in own Medium blogs
- Publish guidelines / best practices content to ballerina.io
- Use attractive titles - REMEMBER to include keywords - keep SEO in mind.   General guidelines https://sites.google.com/wso2.com/wso2rockstar/home?authuser=0#h.628zipq20u0k
- Link other relevant articles from your articles (Would help in creating more views)
- For blogs we can break down the content and publish as multiple parts
- Publish to programs like rockstar and get the help of that team to publish in sites like DZone/InfoQ
&nbsp;
- We'll be planning all the blog posts around a single use case i.e. an Airline reservation Project.
All the blogs would be linked to complete the best practices for writing tests in Ballerina.

</google-sheets-html-origin>

**Comment by Dilhasha** [comment]
Topics to cover 
--

- [ ] Best practices to follow when writing Ballerina tests | @azinneera 
- [ ] Writing unit tests - enabling code coverage, using configurables, using mocking | TBD
- [ ] Writing integration tests | TBD
- [ ] Integrate to CICD workflow | TBD
- [ ] How to write tests for a [Topic] in Ballerina | TBD
- [ ] How to configure a Ballerina project with CodeCov | @Dilhasha 
- [ ] How to use mocking for testing ballerina code (Function mocking / Object mocking) | @Ibaqu

**Comment by Ibaqu** [comment]
We have created a new repository to keep track of the blogs henceforth

https://github.com/Ibaqu/testerina-demos

`AirlineReservationProject` has been added and will be updated as necessary for different scenarios

**Comment by Ibaqu** [comment]
> Draft content: https://github.com/Ibaqu/CodeBlogs/

All content from `CodeBlogs` repo will be edited/moved to the new repo if required.

**Comment by Dilhasha** [comment]
Service testing blog is tracked at https://github.com/ballerina-platform/ballerina-lang/issues/32024

**Comment by Ibaqu** [comment]
Mocking blog is tracked at https://github.com/ballerina-platform/ballerina-lang/issues/32027
