### ISSUE TITLE
Fix the Types.isSubTypeOfBaseType() method

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#22732]
The `Types.isSubTypeOfBaseType()`, method needs to be improved to properly handle subtypes. Currently, it will match any type with XML, if the base type tag is XML.

**Comment by hasithaa** [comment]
Seems to be fixed https://github.com/ballerina-platform/ballerina-lang/blob/bb491c0115f406b02902d229f2f601584b72eef5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L599 Reopen if not.
