### ISSUE TITLE
Bad Sad Error for shift operation on same type union of lists

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#22765]
**Description:**
### Case 1
Here in the below code, `arr` is resolved to be an array (non-fixed length). But we cannot call shift operation on the array.

##### Code
```Ballerina
import ballerina/lang.array;
public function main() {
    int[2]|int[] arr = [1, 7, 5];
    var x = 'array:shift(arr);
}
```

##### Output
```LogTalk
error: .::t1.bal:5:13: attempt to refer to non-accessible symbol 'Type'
error: compilation contains errors
```

**Affected Versions:**
jBallerina 1.2.2
Language specification 2020R1
Ballerina tool 0.8.5

**OS, DB, other environment details and versions:**
macOS Catalina

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-spec/issues/474

**Suggested Labels (optional):**
Area/Language Type/Bug

**Comment by KavinduZoysa** [comment]
This is working in slp5, @hasithaa can we close this issue?

**Comment by MaryamZi** [comment]
Seems to have been fixed by slp1.
