### ISSUE TITLE
java.jdbc query with % parameter does not work

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#22763]
A query similar to the following:
```ballerina
var rs = check dbClient->select("SELECT id, description FROM ECOM_INVENTORY WHERE description LIKE '%?%'", (), query);
```
In execution time, it gives the following error:

failed to execute select query: SQL String cannot be empty.

The only alternative is to put the parameter in the query itself, but this cannot be done always, and is not a good practice.

**Comment by lafernando** [comment]
@daneshk this has been open for sometime, can we please fix this for the next release?

**Comment by niveathika** [comment]
@lafernando I have verified this and the error was due to the quotes in the SQL statement.
```ballerina
string quotedQuery = "%" + query + "%";
var rs = check dbClient->select(
                  "SELECT id, description FROM ECOM_INVENTORY WHERE description LIKE ?", (), quotedQuery);
```
The above code snippet should work in this use case.

**Comment by lafernando** [comment]
Great, thank you for the clarification!
