### ISSUE TITLE
Union of same basic types should resolve to valid lang.lib method at compile time

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#22771]
**Description:**
I am testing if the union of integer lists (tuples and arrays). When compiling the below-mentioned union compiler always resolve to a single type based on RHS expression. Even without RHS expression, type alone is a single basic type list. While both are integer type lists I expect compiler to find a valid lang.lib function. This can panic at run time.
Refer section: https://ballerina.io/spec/lang/2020R1/#section_6.20

##### Code 
```Ballerina
public function main()
{
    int[1]|[int, int...] arr = [1, 2, 3];
    var x = arr.shift();
}
```
##### Output
```LogTalk
error: .::mixArrUnion2.bal:4:17: undefined function 'shift' in type '(int[1]|[int,int...])'
error: compilation contains errors
```

**Affected Versions:**
jBallerina 1.2.2
Language specification 2020R1
Ballerina tool 0.8.5

**OS, DB, other environment details and versions:**
macOS Catalina

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-spec/issues/472

**Suggested Labels (optional):**
Area/Language 
Type/SpecDeviation

**Comment by MaryamZi** [comment]
Need to try and incorporate changes suggested in https://github.com/ballerina-platform/ballerina-lang/pull/22318#discussion_r411511179.

**Comment by KRVPerera** [comment]
notes:
When we are fixing #22771, I think we should refactor checkIllegalStorageSizeChangeMethodCall and this method a bit.

At L1873 if the invocationName is shift we can call something like

```Java
private boolean isShiftValidOnLists(BType varRefType) {
     int tag = varRefType.tag;

     if (tag == TypeTags.ARRAY) {
         return !isFixedLengthList(varRefType);
     }

     if (tag == TypeTags.TUPLE) {
         return !hasDifferentTypeThanRest((BTupleType) member);
     }

     // Union type here.
    BUnionType unionVarRef = (BUnionType) varRefType;
    for (BType member : unionVarRef.getMemberTypes()) {
        if (!isShiftValidOnLists(member)) {
            return false;
        }
    }
    return true;
}
```
