### ISSUE TITLE
Not enough space to display function names / types in API docs

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#22787]
**Description:**
Look at the following screenshot which is taken from [http API docs](https://ballerina.io/v1-2/learn/api-docs/ballerina/http/index.html)

<img width="1675" alt="Screen Shot 2020-04-10 at 14 17 36" src="https://user-images.githubusercontent.com/40016057/78977633-10e33e80-7b36-11ea-96a6-6bdf84d487ba.png">

This has a large empty space left in the right side of the screen, while shortening the type name. Showing `...` is not very pleasing. Better to show the full name there, and try to figure out a way to use the space wisely. It's okay to use another two - three lines for the description.

Also, better if we can show the keywords in a monospace font.

Related: ballerina-platform/ballerina-dev-website#369 ballerina-platform/ballerina-dev-website#355

**Comment by shehan360** [comment]
Closing as this issue is resolved.
