### ISSUE TITLE
Lists are Displayed in a Different Font in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#22788]
**Description:**
Lists are rendered and displayed in a different font in API Docs. For example, the list in [1] looks as shown below.

[1] https://ballerina.io/v1-2/learn/api-docs/ballerina/nats/index.html
<img width="888" alt="Screen Shot 2020-04-09 at 1 44 12 PM" src="https://user-images.githubusercontent.com/11707273/78876954-c39b9a00-7a6d-11ea-874d-790ce0e3d5b8.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shehan360** [comment]
This issue seems to be fixed now. https://ballerina.io/swan-lake/learn/api-docs/ballerina/nats/index.html

**Comment by shehan360** [comment]
Seems to be fixed. Hence closing the issue.
