### ISSUE TITLE
Styling Issue in Descriptions of the HTTP Module

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#22793]
**Description:**
Some descriptions of the HTTP module are not styled properly in API Docs as shown below.

This happened as a result of moving the common client configs to a different record and not having a way to document those common fields properly. This  was proposed as a workaround until the doc inheritance issue is fixed.  The common client fields should inherit the docs.

The styling of the below should be fixed.

<img width="1680" alt="Screenshot 2020-04-20 at 20 49 40" src="https://user-images.githubusercontent.com/11707273/79768566-993cbd00-8348-11ea-844d-b6eea02ea632.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shehan360** [comment]
This issue is now fixed:
https://ballerina.io/swan-lake/learn/api-docs/ballerina/#/ballerina/http/1.0.6/http/records/LoadBalanceClientConfiguration

Hence closing the issue.
