### ISSUE TITLE
Calling the consumeToken twice results a NPE in incremental  parser

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#22807]
**Description:**
 Issues is here: https://github.com/ballerina-platform/ballerina-lang/blob/incremental-parser/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/incremental/HybridNodeStorage.java#L83

Another related issue is, calling `peekToken(k)` followed by a `consumeToken()` will also result in a NPE, since [peek(k)](https://github.com/ballerina-platform/ballerina-lang/blob/incremental-parser/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/incremental/HybridNodeStorage.java#L102) doesn't update the `currentToken`.

**Comment by SupunS** [comment]
This is fixed. `consumeToken()` always checks whether the currentToken is null, and is so, it peeks and returns it.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
