### ISSUE TITLE
[IDEA] Syntax highlighting error when string literals are used

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#22826]
**Description:**

Please refer the below image.

![image](https://user-images.githubusercontent.com/25750106/79944258-b37db480-8488-11ea-81e3-2eab8cb97868.png)

**Steps to reproduce:**

**Affected Versions:**
1.2.2
**OS, DB, other environment details and versions:**
MacOSX
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@NipunaRanasinghe

**Comment by NipunaRanasinghe** [comment]
Closing since the relevant fix has already been added.
