### ISSUE TITLE
Improve the lexer to handle the newline normalization described in the spec

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#22894]
https://ballerina.io/spec/lang/2020R1/#lexical_structure

After the sequence of octets is decoded from UTF-8, the following two transformations must be performed before it is parsed using the grammar in this document:

- if the sequence starts with a byte order mark (code point 0xFEFF), it must be removed
newlines are normalized as follows:
- the two character sequence 0xD 0xA is replaced by 0xA
- a single 0xD character that is not followed by 0xD is replaced by 0xA

**Comment by sameerajayasoma** [comment]
Added a fix with the following logic. 

Ballerina spec 2020R1/#lexical_structure section says that you should normalize newline chars as follows.
- the two character sequence 0xD 0xA is replaced by 0xA
- a single 0xD character that is not followed by 0xD is replaced by 0xA

This implementation does not replace any characters to maintain the exact source text as it is, but it does not count `\r\n` as two characters. Therefore, we have to specifically send the width of the lexeme when creating the Minutia node.

**Comment by SupunS** [comment]
@sameerajayasoma Do we have anything else to work on this?

**Comment by sameerajayasoma** [comment]
This is now fixed. I'll close this.

**Comment by sameerajayasoma** [comment]
We decided to preserve newline characters in the parser. I updated the Lexer to support this but missed updating the issue.
