### ISSUE TITLE
Cannot connect to unsecured smtp servers using the ballerina/email module

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#22939]
**Description:**
ATM it is mandatory to use TLS or SSL when using ballerina/email module to connect to an smtp server. Due to this, it is unable to connect to internal smtp servers which are not secured. It is possible to support connecting to unsecured servers as well?

**Comment by Maninda** [comment]
Added the functionality to add custom SMTP properties to the SMTP Client Config in PR [1]. Setting `mail.smtp.starttls.enable` property to `false` as given in the example of the PR should solve this issue.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/22949
