### ISSUE TITLE
Const maps are not properly type checked

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#22959]
**Description:**
Please consider the following code snippet. 

```ballerina
const map<int> M = {
    a: 1
};

public function test() returns boolean {
    var y = {
                      b: 3
                  };
    M v2 = y;
    return false;
}
```
Since, M acts as a type here, the above should produce a compile error. 
Currently this does not produce any errors.

**Suggested Labels (optional):**
Area/Language

**Comment by MaryamZi** [comment]
Doesn't fail even when an explicit type is used for the source.

```ballerina
const map<int> M = {
    a: 1
};

public function test() returns boolean {
    record {|
        int b;
    |} a = {b: 3};
    M v1 = a;

    map<int> b = {b: 3};
    M v2 = b;

    return false;
}
```

**Comment by irshadnilam** [comment]
Once this is fixed, we can add `mapping-constructor-expression` to infer precise type for `final` maps declared using `var`. Please refer to https://github.com/ballerina-platform/ballerina-lang/pull/22971

**Comment by SandaruJayawardana** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34371.
