### ISSUE TITLE
openapi issue with 2 parameters in path

### ISSUE THREAD

**Issue by scivray47** [ballerina-platform/ballerina-lang#22960]
**Description:**
Use 2 parameters in a path

**Steps to reproduce:**
Consider the following spec : 

```
openapi: 3.0.1
info:
  title: test 2 or more uri parameters
  description: test 2 or more uri parameters
  version: 1.0.0
servers:
- url: http://localhost/api/v1
paths:
  /{param1}/{param2}:
    get:
      operationId: test2Params
      parameters:
        - name: param1
          in: path
          required: true
          schema:
            type: string
            description: param1
        - name: param2
          in: path
          required: true
          schema:
            type: string
            description: param2
      responses:
        '200':
          description: test
```

Then use the comand to generate service : 
ballerina openapi gen-service

It produces the following : 

```
import ballerina/http;
import ballerina/openapi;
listener http:Listener ep0 = new(80, config = {host: "localhost"});
@openapi:ServiceInfo {
    contract: "resources/test_2_params.yaml"
}
@http:ServiceConfig {
    basePath: "/api/v1"
}
service test on ep0 {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/{param1}/{param2}"
    }
    // resource function 'test2Params (http:Caller caller, http:Request req,  string &#x27;param1,  string &#x27;param2) returns error? {
    resource function 'test2Params (http:Caller caller, http:Request req,  string param1,  string param2) returns error? {
    }
}
```

Had to correct the param1 and param2.
The try to build and you get the error : 

> Couldn't find 'param2' parameter in the Ballerina service resource for the method 'get' of the path '/{param1}/{param2}' which is documented in the OpenAPI contract

**Affected Versions:**
jBallerina 1.2.2
Language specification 2020R1
Ballerina tool 0.8.5
**OS, DB, other environment details and versions:**
Ubuntu 18.04.4 LTS
**Related Issues (optional):**

**Suggested Labels (optional):**

Bug, openapi
**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Closing since the PR to ballerina-1.2.x branch is merged.
