### ISSUE TITLE
Cannot configure multiple versions of balo in Ballerina.toml

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#22984]
**Description:**
ATM we can configure as below.

[dependencies]
"waruna/module1" = { version="1.0.0", path = "../TestProject1/target/balo/module1.balo"}

But if we cannot add multiple versions of same module with balo path.

suggestion

[dependencies]
"waruna/module1" = [ {version="1.0.0", path = "../TestProject1/target/balo/module1-v1.balo"}, 
{version="2.0.0", path = "../TestProject2/target/balo/module1-v2.balo"}]

**Comment by hevayo** [comment]
Implementation has change and we do not support importing multiple versions.
