### ISSUE TITLE
Enable failing packerina tests

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#22996]
**Description:**
Following packerina tests are currently disabled due to intermitant failures and should be re-enabled once fixed.

- LockFileTestCase -> testBuildTestProject2
- LockFileTestCase -> testRebuildTestProj2WithLockRemovedAndOffline
- PackagingTestCase -> testPull
- PathDependencyTestCase -> testBaloPathCase4

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Fixed in master
