### ISSUE TITLE
Discuss and finalize HTTP Header passing behaviour

### ISSUE THREAD

**Issue by isudana** [ballerina-platform/ballerina-lang#23]
- Do we need to pass all the headers from incoming request to the backend ? 
No.
- There are two types of headers (connection/protocol related, custom headers). Need to discuss how to handle them, looks like we need to handle them separately.

**Comment by samisawso2** [comment]
@isudana can we resolve this?

**Comment by pubudu91** [comment]
The current implementation adheres to the HTTP spec with regards to which headers to forward and which headers to remove. Hence closing this.
