### ISSUE TITLE
Add Error Nodes Handling for the BLangNodeTransformer

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#23017]
**Description:**
Currently, BLangNodeTransformer does not address the error nodes such as MissingTokens into consideration.

In the early ANTLR based implementation Compiler just halts on such syntax error without proceeding. In here, since we need to keep parsing process continues; We need to design and come-up with a plan to how to address scenarios such as MissingTokens.

One option might be in the event of missing token for a variable name will be "generate a valid name". Likewise, need to think about all possible scenarios and finalize the design.

**Comment by SupunS** [comment]
**Samples:**

[n] - Places where something is missing. Replace these [n] with a blank-space for the source.

**Function signature:**
```ballerina
function [1](int [2], [3] [4]= "hello", int age = [5]) returns [6] {
}
```

[1], [4] - func name
[2] - param name
[3] - param type-desc
[5] - default value
[6] - return type-desc



**Variable decl:**
```ballerina
int [1]=[2];
```
[1] variable name
[2] value

**Comment by rasika** [comment]
Are these propose changes? Or have done any changes from Compiler FE to ack variable names with spaces? How about two variable declarations missing var name and replacing it with space causing syntax already defined error?

**Comment by SupunS** [comment]
Umm no, these are some sample scenarios to consider when designing/implementing the feature.
