### ISSUE TITLE
Documentation: Need a SQL tutorial

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#2303]
Can we please add a step-by-step tutorial on working with databases: create a table, write data, read data into some structure that can be traversed and used?

**Comment by anupama-pathirage** [comment]
More details on SQL connector and actions can be found in below samples.
https://ballerinalang.org/docs/by-example/sql-connector
https://ballerinalang.org/docs/by-example/datatables

**Comment by uthaiyashankar** [comment]
https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/table
https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/mysql-client

These examples show the SQL operations.

**Comment by anupama-pathirage** [comment]
Following sample describes the full capabilities of the ballerina data connectors.
https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/jdbc-client
