### ISSUE TITLE
error can not be used as a filed name in a record

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#23045]
**Description:**
Refering https://ballerina-platform.slack.com/archives/C47EAELR1/p1588155489154500

> I get redeclared builtin symbol 'error' when I have a record with field as string 'error; . But I can have string 'int;

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MadhukaHarith92** [comment]
We are planning to update the `printError()` method signature in `log` module to `public isolated function printError(string msg, *KeyValues keyValues, error? 'error = ())`

Blocker for https://github.com/ballerina-platform/ballerina-standard-library/issues/949

**Comment by hasithaa** [comment]
Code example to reproduce the issue. 

```
type Foo record {|
    error 'error;
|};
```
