### ISSUE TITLE
Implement Integration test scenarios for jBallerina debugger

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#23068]
**Description:**
We have to implement different Integration test scenarios for jBallerina debugger.

Details of the integration test scenarios can be found in [1].

[1] https://docs.google.com/document/d/1eizIA3Pd_WJ0u80aSXo0kMl8-2WligTmx9lM_IVT1IM/edit?usp=sharing

**Comment by hevayo** [comment]
Action Items 
- [ ] Come up with a set of testcases
- [ ] Cover all the identified test cases

**Comment by NipunaRanasinghe** [comment]
Closing since jballerina debugger based test scenario implementation is completed in `ballerina-lang` and `ballerina distribution` repositories.
