### ISSUE TITLE
Maven resolver support for Java libraries

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#23065]
**Description:**
Currently java libraries have been included by specifying the jar file paths. 
We need to have a feature to resolve java dependencies from maven repositories. We can consider following user scenarios for this feature

1. Specify maven dependencies
    1. User/Bindgen tool requires to specify maven dependencies in the Ballerina.toml
    2. Group id, Artifact id and version needs to be specified. Specified version can be a stable, pre-release or even a snapshot
    3. Specify the classifier is an optional parameter
2. Specify maven repositories
    1. Bindgen tool needs to refer maven central and maven local repositories when generating
    2. Users may need to specify custom repositories. This is very important specially staging repositories can be added and also third party repositories like Github packes.
        1. Some of these repositories may require to be authenticated
        2. In maven repositories can be specified in settings.xml other than the pom.xml
    3. When loading repositories we need to consider default settings.xml file in ~/.m2/settings.xml
Users may need to pass custom settings.xml (In maven we pass this like -s <path>)

**Comment by hevayo** [comment]
Action Items 
[ ] Implement the maven resolving task 
[ ] Implement a library that will use by bindgen

**Comment by keizer619** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/23324/files

Above PR will has completed following tasks

- Implement the maven resolving task
- Implement a library that will use by bindgen

**Comment by keizer619** [comment]
Unit tests are added in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/23404/

**Comment by keizer619** [comment]
Local repo support added in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/23492/

**Comment by keizer619** [comment]
Progress bar support is fixed in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/23514/files

**Comment by keizer619** [comment]
Closing this issue as all the fixes have been merged to master
For integration tests i have created another task
https://github.com/ballerina-platform/ballerina-lang/issues/23598
