### ISSUE TITLE
Displaying files under tests/ dir in code coverage report

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#23123]
**Description:**
As per the current implementation, the code coverage report contains the files under tests/ directory as well. We should figure out if these necessary to display and if so, if it should be excluded for code coverage calculation.

**Comment by Ibaqu** [comment]
This is removed. Needs revaluation

**Comment by Dilhasha** [comment]
We do not need to display the test sources as they are only used to get the coverage information.
