### ISSUE TITLE
Code coverage for Java dependant Ballerina code

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#23121]
**Description:**
When using Java interop with Ballerina, it is difficult to figure out if the Java code is being covered using the Ballerina tests and the code coverage report.  

One possible solution would be an improvement to the report which covers the Java code as well. 

Currently, it is advised to write separate Unit tests in Java and generate a separate coverage report 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
We can pass the jacoco agent to the ballerina process and generate the code coverage without having to depend on the `--code-coverage` flag. Steps to follow:

1. Pass the jacocoagent.jar when running the ballerina command 
E.g.:  `JAVA_OPTS="-javaagent:/usr/lib/ballerina/distributions/ballerina-slp3/bre/lib/jacocoagent.jar=destfile=/home/asma/test/foo/ballerina.exec,includes=asma.bar.*" ballerina build module1`

> `destfile=/home/asma/test/foo/ballerina.exec` - This part in the example specifies where to create the ballerina.exec file which contains the code coverage information
> `includes=asma.bar.*` - This part in the example specifies the class files to be included for generating the coverage.

2. [Download the jacoco distribution](https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.5/jacoco-0.8.5.zip) and extract the **_jacococli.jar_**

3. Generate the coverage report using the extracted jacoco cli jar
E.g.:  `java -jar <path-to-jacococli.jar> report /home/asma/test/foo/ballerina.exec --classfiles <path-to-interops-jar> --html jacoco-report --name myReport --sourcefiles <path-to-interop-java-src-files>`

**Comment by azinneera** [comment]
This issue was tracked and resolved by #28642
