### ISSUE TITLE
Issue with assignment statement recovery

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#23122]
**Description:**
With `let-expr` support following code recovers as a let expression.
```java
function foo() {
    a =
    int b =
    int a = 6;
}
```
For now test case changed to: 
```java
function foo() {
    a =
    b =
    int a = 6;
}
```

test case: https://github.com/ballerina-platform/ballerina-lang/blob/incremental-parser/compiler/ballerina-parser/src/test/resources/statements/assignment-stmt/assignment_stmt_source_12.bal

**Suggested Labels (optional):**
Component/Parser, Priority/Low

**Comment by SupunS** [comment]
This is already fixed. Can add a test-case and close.

**Comment by lochana-chathura** [comment]
> This is already fixed. Can add a test-case and close.

A test case is already there. I have posted the link in the description. Can close this now.

**Comment by SupunS** [comment]
Test case added with #24468
