### ISSUE TITLE
GenerateBalo.java class file error 

### ISSUE THREAD

**Issue by shilpakarre** [ballerina-platform/ballerina-lang#23136]
In GenerateBalo.java

   BPackageSymbol buitlinSymbol = symbolTable.builtInPackageSymbol;
        if (saveBuiltin && buitlinSymbol != null && buitlinSymbol.compiledPackage != null) {
            writer.writeLibraryPackage(buitlinSymbol, Names.BUILTIN_PACKAGE.getValue());

There is an error when trying to build with gradle

There is no symbol existing for builtInPackageSymbol in SymbolTable class and there is no BUILTIN_PACKAGE in the Names class,

The error that is displayed is builtInPackageSymbol cannot be resolved or is not a field
and BUILTIN_PACKAGE cannot be resolved or is not a field

could anyone please help me how to resolve this issue and what values to be assigned for the same.

Thank you in advance

**Comment by manuranga** [comment]
Hi,
https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview1-M1/misc/lib-creator-milestone/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java#L133

Above file was used to bootstrap, but is not currently being used in the build.
Even if you comment two `:lib-creator-milestone` lines from the `settings.gradle` file, the build should still pass.

Just cloning the repo and running `./gradlew build` should build the ballerina zip file, you shouldn't need to do any changes.
(You can use `./gradlew jballerina-tools:createZip -x check` to get a faster build with just the zip file)

Can you please let me know what is the exact gradle command you are running and where you are running it from ?
Also please provide the stack trace form the failing build.

**Comment by warunalakshitha** [comment]
I am closing this issue with above explanation. Please reopen the issue if you need more clarification and help on this.
