### ISSUE TITLE
Support for stream keyword with new-expr in incremental parser

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#23183]
**Description:**
Only the object type descriptor is supported along with the new-expr. Need to support stream type descriptor as well.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
@dulvinw is this issue still valid? 
Can you give a sample code?

**Comment by dulvinw** [comment]
I think this is already fixed when I look at https://ballerina.io/learn/by-example/streams.html. 

For example ` var oddNumberStream = new stream<int, error>(oddGen);`
