### ISSUE TITLE
Automate Github Action 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#23187]
**Description:**
We have a ballerina [github action ](https://github.com/ballerina-platform/ballerina-action). This needs to be updated after each release and publish to market place. Currently this is been done manually. We can automate this as we have automated VSCode extension publishing when website is updated with new release.

**Comment by prabushi** [comment]
Will be fixed with https://github.com/ballerina-platform/plugin-vscode/issues/81
