### ISSUE TITLE
testGlobalVariableInitWithInvocationNegative is failing intermittently.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#23211]
This test-case is failing intermittently. Shall I disable it for now? Can you create an issue for this?

_Originally posted by @hasithaa in https://github.com/ballerina-platform/ballerina-lang/pull/22818/review_comment/create_

**Comment by MaryamZi** [comment]
Enabled in https://github.com/ballerina-platform/ballerina-lang/pull/23215.
