### ISSUE TITLE
Test `testOOTBTracingWithWorkers` intermittently fails

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#23232]
**Description:**
Below is the error log. More details can be found in [scans.gradle](https://scans.gradle.com/s/k3jc2vukyi2q6) (not sure for long it will be retained though)

![image](https://user-images.githubusercontent.com/6178058/81890521-cc7b1080-95c3-11ea-9ee4-c79cd8ef964e.png)

I have also attached the complete log file.
[logs_7124.zip](https://github.com/ballerina-platform/ballerina-lang/files/4625949/logs_7124.zip)

**Comment by nadundesilva** [comment]
Dependencies between Observability Test Cases had been removed and waits had been added in worker related test cases in #24949. Hence this issue is fixed.
