### ISSUE TITLE
Test `largeForkCreationTest` intermittently fails

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#23233]
**Description:**
Below is the error log. More details can be found in [scans.gradle ](https://scans.gradle.com/s/hwhe6ywdqqrfm)(not sure for long it will be retained though)

This seems like an issue in implementation to me. Hence, didn't disable the test-case for the time being.

```
Exception: org.testng.internal.thread.ThreadTimeoutExceptionMethod org.ballerinalang.test.worker.NotSoBasicWorkerTest.largeForkCreationTest() didn't finish within the time-out 120000
at sun.misc.Unsafe.park(Native Method)
•••
at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:407)
at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1391)
at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:162)
at org.ballerinalang.test.worker.NotSoBasicWorkerTest.largeForkCreationTest(NotSoBasicWorkerTest.java:131)
•••
```
I have also attached the complete log file.
[logs_7134.zip](https://github.com/ballerina-platform/ballerina-lang/files/4626139/logs_7134.zip)

**Comment by shafreenAnfar** [comment]
This test fails intermittently quite frequently.

**Comment by riyafa** [comment]
This can be reproduced only with the group based scheduling annotation. Hence it is after PR https://github.com/ballerina-platform/ballerina-lang/pull/21781 If we remove the `@strand{thread:"any"}` from the workers the issue is resolved.
