### ISSUE TITLE
Use type parameter node in parameterized type descriptor node.

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#23253]
**Description:**
Use type parameter node in parameterized type descriptor node, error type desc node, and in type cast expression.

**Suggested Labels (optional):**
- Component/Parser

**Suggested Assignees (optional):**
- @rdulmina

**Comment by m36dot** [comment]
Can only use TypeParameter in ParameterizedTypeDescription, the other two are of a slightly different structure.
