### ISSUE TITLE
Debug points are being skipped when remote debugging ballerina programs with services

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#23261]
**Description:**
We have following ballerina module [1]

[1] - https://github.com/wso2/product-microgateway/tree/master/components/micro-gateway-core/src/main/ballerina/src/gateway
Which exposes set of ballerina services. When we try to remote debug this, the debugger is not getting hit when we invoke a request.

**Steps to reproduce:**
1. Follow the in [2] to start and running the gateway
2. Start the gateway with setting bal java debug parameter by setting it as env varibale
3. Start the gateway and connect to the debugger
4. Try to debug the file[3]
[2] - https://docs.wso2.com/display/MG310/Quick+Start+Guide+-+Binary
[3]- https://github.com/wso2/product-microgateway/blob/master/components/micro-gateway-core/src/main/ballerina/src/gateway/filters/pre_authn_filter.bal

**Affected Versions:**
1.1.5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing as we have improved remote debugging support for services with Swan Lake versions. Feel free to reopen or create a new issue, if you encounter any limitations when using the debugger in SwanLake versions.
