### ISSUE TITLE
Test `waitTest17` intermittently fails

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#23279]
**Description:**
Below is the error log. More details can be found in [scans.gradle](https://scans.gradle.com/s/d35naa2p4khui) (not sure for long it will be retained though)

![image](https://user-images.githubusercontent.com/6178058/82009402-da489880-968c-11ea-8240-7988090a1b05.png)

I have also attached the complete log file.
[log.txt](https://github.com/ballerina-platform/ballerina-lang/files/4632136/log.txt)

**Comment by manuranga** [comment]
@ruvi-d will take a look

**Comment by ruvi-d** [comment]
Looks like the offending `jballerina-bstring-unit-test` project was removed in #23466 (May 25)
Safe to close this issue.

**Comment by manuranga** [comment]
but a copy of that tests still lives here: https://github.com/ballerina-platform/ballerina-lang/blob/5b1cb8205e7fa9015b495d0e647f4c2ac18ffdcc/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WaitForAllActionsTest.java#L239

just to be sure we need to test that before closing

**Comment by ruvi-d** [comment]
`jballerina-unit-test:test` runs without any issues and I didn't notice the `worker/WaitForAllActionsTest` in the excluded test list. Anything else that I can help to validate?

**Comment by MaryamZi** [comment]
This still fails. Failed for the build of https://github.com/ballerina-platform/ballerina-lang/pull/34295 also.

**Comment by HindujaB** [comment]
Error Log 
https://scans.gradle.com/s/f5bn24swl7y7g/tests/overview?outcome=failed

**Comment by HindujaB** [comment]
A temporary improvement is added to gather more information on this issue. Hence, closing this issue. 
This can be reopened when we get this failure again.
