### ISSUE TITLE
Add Distinct type support 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#23283]
Sub Tasks
- [ ] Add Antlr Grammar support
- [ ] Add Basic Semantic recognition support 
- [ ] TBA

**Comment by rdhananjaya** [comment]
`distinct` classes were added with https://github.com/ballerina-platform/ballerina-lang/issues/25361

**Comment by rdhananjaya** [comment]
distinct object type definitions will be added with https://github.com/ballerina-platform/ballerina-lang/issues/26110

**Comment by rdhananjaya** [comment]
distinct error support was added with https://github.com/ballerina-platform/ballerina-lang/issues/23098

**Comment by rdhananjaya** [comment]
Langlib functions to access type-ids https://github.com/ballerina-platform/ballerina-lang/issues/25544
