### ISSUE TITLE
Issue in annotation attachment validation of enums

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#23308]
**Description:**
The spec says the attachment point for `module-enum-decl` is type.

But this seems to be matching for consts now.

```ballerina
public annotation X on type;
public const annotation Y on source const;

@X // should work, doesn't
@Y // should fail, doesn't
public enum Color {
    RED,
    BLUE
}
```
___

Also there is an issue with grammar. 
Spec says at least one enum-member is required.
Hence the grammar should be changed from:
```(enumMember (COMMA enumMember)*)? RIGHT_BRACE```

to 

``` enumMember (COMMA enumMember)* RIGHT_BRACE```

**Comment by MaryamZi** [comment]
The issue with annotations is still present with slp4.

But, the issue in the grammar (not requiring at least one member) has been fixed with the new parser.

The following fails with `error: .::qwe.bal:1:19: missing enum member`.

```ballerina
public enum Color {
}
```

**Comment by MaryamZi** [comment]
May have to fix https://github.com/ballerina-platform/ballerina-lang/issues/25872 to properly validate annotations.

**Comment by MaryamZi** [comment]
This seems to work as expected now, keeping the issue open to add some tests.
