### ISSUE TITLE
Tooling support for intersection/readonly types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23313]
**Description:**
$title.

Intersection types are supported with readonly at - `T & readonly x`

Record fields can also be marked `readonly` in the type-descriptor

```ballerina
type Foo record {
   readonly Bar b;
};
```

See https://github.com/ballerina-platform/ballerina-lang/pull/22519, https://github.com/ballerina-platform/ballerina-lang/pull/22965

**Comment by nadeeshaan** [comment]
Definition and the completion support has been added

**Comment by sameerajayasoma** [comment]
Can we close this?

**Comment by mohanvive** [comment]
Closing the issue since completion and definition support is provided.
