### ISSUE TITLE
Table updates can be done using `member-access-lvexpr`s

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23325]
**Description:**

$title, but the current spec says for `member-access-lvexpr`

> The static type of lvexpr must be either a subtype of the mapping basic type or a subtype of the list basic type.

**Steps to reproduce:**

```ballerina
type Employee record {
    readonly int id;
    string name;
};

public function main() {
    table<Employee> key(id) tbEmployee = table [
        {id: 1, name: "Mary"}
    ];

    tbEmployee[2] = {id: 2, name: "Anne"};
}
```

**Comment by hasithaa** [comment]
@mohanvive @gimantha Supporting this is incorrect. The reason is the table can have a key or set of keys.  So we can't represent this using a member-access-lvexpr.
