### ISSUE TITLE
Add Raw templates support

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#23336]
Spec Issue : https://github.com/ballerina-platform/ballerina-spec/issues/442
Make backtick strings usable for SQL parameters

**Comment by sinthuja** [comment]
@hasithaa , this is a blocker for SQL connector. We need this support for execute and batch execute operations as per doc - https://docs.google.com/document/d/1J_5gzUDopvqMJRGz04tCre79lwKLj0DtKumE7S34nlw/edit#. 

I appreciate if this is added into the language ASAP. @niveathika please note.
