### ISSUE TITLE
Support for referencing local vars in default value expressions of object fields

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#23332]
Following code should work without an issue. Related to #20851
``` ballerina
public function main() returns (error?){
   int x = 20;
   object {
       string name;
       int age = x; 

       public function __init(string name) {
           self.name = name;
       }

   } person1 = new("pubudu");
}
```

**Comment by manuranga** [comment]
@Kishanthan @riyafa please take note.

**Comment by manuranga** [comment]
@pubudu91 this will be a blocker for SL. I think we need to look into this.

**Comment by pubudu91** [comment]
I think @KRVPerera is planning on looking in to this. Will check and see.

**Comment by KRVPerera** [comment]
Working on closure support for object-type-descriptors via issue : https://github.com/ballerina-platform/ballerina-lang/issues/9144.

**Comment by KRVPerera** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/issues/9144
