### ISSUE TITLE
Improve error message for invalid path dependency

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#23357]
For an invalid path dependency specified in the `Ballerina.toml` file, I get an error message of the following format:
```
error: balo file for dependency [pubudu/bar] does not exists: <absolute_path_to_balo_file>
```
What's the correct way to refer to `.balo` files? The https://ballerina.io/learn/how-to-structure-ballerina-code/ guide refer to them as BALO files. I think here also we either need to use that or `.balo` form. 

Also, it should be be rephrased in a better way. How about something like,
```
.balo file for the 'pubudu/bar' module not found: <specified_path>
```

**Comment by suganyasuven** [comment]
This is related to https://github.com/ballerina-platform/ballerina-lang/issues/20821 and it's fixed now. Hence closing the issue.
