### ISSUE TITLE
ValueInconsistentError when updating a table with a constrained type that has optional fields

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23368]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Employee record {|
    int id;
    string name;
    int age?;
    float salary?;
|};

public function main() {

    table<Employee> tb = table [
        {id: 2, name: "Jo"},
        {id: 1, name: "Mary"}
    ];

    Employee e = {id: 3, name: "Jane", salary: 200.0, age: 18};
    tb.put(e);
}
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
Running executables

error: {ballerina/lang.table}ValueInconsistentError message=value type inconsistent with the inherent table type
        at ballerina.lang_table:put(table.bal:74)
           qwe:main(qwe.bal:16)
```

On a separate note, can we not reuse "[**InherentTypeViolation**](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/util/exceptions/BallerinaErrorReasons.java#L64)" here instead of "**ValueInconsistentError**"? That's what we've used across mappings, lists, etc.

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/23852 by @lasinicl
