### ISSUE TITLE
Ballerina build fail for large modules

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#23376]
**Description:**
I have attached a ballerina module [gen.zip](https://github.com/ballerina-platform/ballerina-lang/files/4651488/gen.zip). When I try to build it with command [1], it gives me the error [2].
Seems like there is an limitation when generating java byte code from ballerina, when the ballerina module is too large.

Please find the attached libs required 
[lib.zip](https://github.com/ballerina-platform/ballerina-lang/files/4681410/lib.zip)
. Please edit the ballerina.toml with correct paths

[1] - 
```
ballerina build --experimental EndpointReferenceProject
```

[2] - 
```
Compiling source
	wso2/EndpointReferenceProject:3.1.0

Creating balos
	target/balo/EndpointReferenceProject-2019r3-java8-3.1.0.balo
error: wso2:EndpointReferenceProject:EndpointReferenceProject:1:1: method is too large: 'wso2/EndpointReferenceProject:3.1.0.<init>'
error: error: wso2:EndpointReferenceProject:EndpointReferenceProject:1:1: method is too large: 'wso2/EndpointReferenceProject:3.1.0.<init>'
```
**Steps to reproduce:**

**Affected Versions:**
1.1.5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
Can you also share the dependencies that is required to build the project here?

**Comment by Rajith90** [comment]
Hi @Kishanthan ,
I have attached the lib zip file with necessary jars and balos. Please edit the ballerina.toml file with correct paths.

**Comment by riyafa** [comment]
@Rajith90 What is the version of the ballerina that is used in your project?

**Comment by riyafa** [comment]
We have done some major improvements in later versions of ballerina. If your project is currently on version 1.1.x version of Ballerina can you please update to 1.2.x version of ballerina and update if the issue persists. Also please upload the modified project files for the syntax changes.

**Comment by riyafa** [comment]
This particular issue has been fixed in https://github.com/ballerina-platform/ballerina-lang/pull/23919 . Further improvements are planned through bir optimization. Some relevant issues are https://github.com/ballerina-platform/ballerina-lang/issues/23914 and  https://github.com/ballerina-platform/ballerina-lang/issues/24619

**Comment by menakaj** [comment]
Hi @Kishanthan, @riyafa The same issue is observed for the main method as well.
