### ISSUE TITLE
Improve the implementation of the `Node.toString()` method

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#23379]
We are working on a new syntax tree API with the new parser implementation. This tree model maintains everything in the source code, even the minutiae of nodes such as newlines, comments, and whitespaces. Therefore you can always get the original source text from the syntax tree. 

```java
TextDocument textDocument = TextDocuments.from("function add(int a, int b) returns int {return a + b;}");
SyntaxTree syntaxTree = SyntaxTree.from(textDocument);
ModulePartNode modulePartNode = syntaxTree.modulePart();
System.out.println(modulePartNode);
```

The implementation of the current `toString()` method is a sub-optimal one that creates `StringBuilder` instances recursively when descending the tree. Ideally, we should be using a single `StringBuilder` instance.

https://github.com/ballerina-platform/ballerina-lang/blob/b43871b5d3987742df7f0d4b635fa61c310dcc64/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/syntax/tree/Node.java#L128

**Comment by isurunuwanthilaka** [comment]
Lets create a singleton in STNode
[https://github.com/ballerina-platform/ballerina-lang/blob/b43871b5d3987742df7f0d4b635fa61c310dcc64/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/tree/STNode.java#L86](url)
