### ISSUE TITLE
Enable formatting test for streams

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#23370]
**Description:**
$title for streaming queries, which got disable in https://github.com/ballerina-platform/ballerina-lang/pull/23252.

**Steps to reproduce:**
n/a

**Affected Versions:**
n/a

**OS, DB, other environment details and versions:**
n/a

**Related PR:**
https://github.com/ballerina-platform/ballerina-lang/pull/23252
commit: https://github.com/ballerina-platform/ballerina-lang/pull/23252/commits/a455ac067fa802812aafa0f429c3494004ad274d

**Comment by nadeeshaan** [comment]
This task has been completed with the latest implementation. Hence closing the issue.
