### ISSUE TITLE
Enable command execution tests

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#23371]
**Description:**
$title for streaming queries, which got disable in https://github.com/ballerina-platform/ballerina-lang/pull/23252.

**Steps to reproduce:**
n/a

**Affected Versions:**
n/a

**OS, DB, other environment details and versions:**
n/a

**Related PR:**
https://github.com/ballerina-platform/ballerina-lang/pull/23252
commit: https://github.com/ballerina-platform/ballerina-lang/pull/23252/commits/a4ffb16c4c3fff283b9d92717a042451a7eddbac

**Comment by nadeeshaan** [comment]
Closing since this issue has been addressed.
