### ISSUE TITLE
enable blockstmt test for jballerina with new-parser

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#23409]
**Description:**
$title

**Suggested Labels (optional):**
Component/parser

**Suggested Assignees (optional):**
@dulvinw

**Comment by SupunS** [comment]
Block stmt tests are added in parser. However, block-stmt was not supported in the rest of the compiler phases.

jballerina-unit-tests needs to be added when the block-stmt support is added to the compiler

**Comment by SupunS** [comment]
Seems these are added.
