### ISSUE TITLE
Provide functionality to package tests in testerina

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#23418]
**Description:**
When I tried to implement websub related tests, it occurs to me that having the $subject would be an ideal case to implement advanced tests. For example, handling this kind of configurations.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-integration-test/src/test/resources/testng.xml#L251

**Steps to reproduce:**
The functionality would be ideal when we try to implement this [2] kind of test in testerina. The reason is websub only contains a static hub and we cannot test different configurations of websub hub within a single packaged test cases.

[2] https://github.com/ballerina-platform/ballerina-lang/tree/master/tests/jballerina-integration-test/src/test/resources/websub/publisher/src

**Affected Versions:**
1.3.0-SNAPSHOT

**Comment by azinneera** [comment]
In ballerina, a module is considered a test suite and the user can give configurations inline with the test cases which is similar to the testng.xml in TestNG in Java. There are also options to enable/disable groups or to execute a certain set of tests with the CLI. Refer `bal test --help` for more information.
