### ISSUE TITLE
Implement Update tool Admin API

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#23426]
**Description:**
- A new service to be developed which can be used to update release versions in the update tool database. 
- This will be secured with mutual auth.
- Admin API will have POST “/distribution”. This should update following
  - New distribution released
  - New dependency of the release 

**Action Items:**
- Create a dummy service to add distribution. -> Will return 200 “API Works”
- Create a new AdminAPI service in ballerina-registry repository - it will be a new module
- Move the implementation of add Distribution into admin API
- Get the functionality to work 
- Write unit tests for the service

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
close this item as we have another issue
