### ISSUE TITLE
Issue of declaring module-var using new parser

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#23457]
**Description:**
$subject
Please refer [spec issue](https://github.com/ballerina-platform/ballerina-spec/issues/424)
 
**Steps to reproduce:**
Run below code.

`int muduleLevelVar;`

Output: 
`xxx.bal:0:0:assignment required`

**Comment by SupunS** [comment]
According to the spec (https://ballerina.io/ballerina-spec/spec.html#module-var-decl), module var-decl always needs to be initialised.

**Comment by KavinduZoysa** [comment]
AFAIK the discussion about the spec issue is on mapping object initialization with module-var initialization. The current compiler supports this. This is the PR.  
https://github.com/ballerina-platform/ballerina-lang/pull/22818
