### ISSUE TITLE
Need a mechanism for testing constructs coming from BIR in unit tests

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#23470]
Currently, we don't have a way to test the semantic checking path coming through the `BIRPackageSymbolEnter`. We need a way to provide a BIR source path to the package loader so that we can explicitly tell the compiler to get it from the BIR source.

**Comment by MaryamZi** [comment]
@pubudu91, is this something in addition to the current bala tests that use `org.ballerinalang.test.BCompileUtil#compileAndCacheBala`?

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
