### ISSUE TITLE
Syntax error in default keyword

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#23476]
**Description:**
In this [test case](https://github.com/ballerina-platform/ballerina-lang/blob/4a2a71fffa167992843dfb43e7b70a6b79912731/tests/jballerina-unit-test/src/test/resources/test-src/workers/invalid-usage-of-default.bal), `default` keyword is used for negative tests cases. But in the new parser it is identified as invalid token. Therefore this test needs to be changed.

**Steps to reproduce:**
example source:
```
function test3() {
    string default = "Hello World!!!";
}
```
new parser output:
```
xxx.bal:0:0:missing variable
xxx.bal:0:0:invalid token 'default'
__________________________________________________
function test3() {
    string  MISSING[]= "Hello World!!!";
}
```

**Comment by hasithaa** [comment]
`default` is only valid in `peer-worker`parser rule. 

```
peer-worker := worker-name | default
```

Let's say we allow it as a identifer, But `default` symbol is already defined in the function scope. So we can keep it is a reserved word. IMO.

**Comment by lochana-chathura** [comment]
"default" is no longer a reserved keyword. Plus one can now define a worker with the name default. Therefore the negative test no longer makes any sense. @MaryamZi in this kind of situation do we keep the residuals or we need to wipe out the test case with a PR?
https://github.com/ballerina-platform/ballerina-lang/blob/e40c5e467333c15a9a74218a98c745ea78de9a02/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/WorkerFailTest.java#L255-L265

**Comment by MaryamZi** [comment]
IMO, this test made sense only when we had a special keyword specifically for workers. +1 to remove this.

**Comment by lochana-chathura** [comment]
Also, clean up if there are other places where `DEFAULT_WORKER_NAME` is hanging. Ref https://github.com/ballerina-platform/ballerina-lang/pull/28636#discussion_r580474616 in PR #28636

**Comment by MaryamZi** [comment]
The `invalidUsagesOfDefault` test will be removed by 12458ec in https://github.com/ballerina-platform/ballerina-lang/pull/30594.

**Comment by MaryamZi** [comment]
> The `invalidUsagesOfDefault` test will be removed by [12458ec](https://github.com/ballerina-platform/ballerina-lang/commit/12458ecf98696cd7af6877d454c53498f7575088) in #30594.

Closing since this was merged.
