### ISSUE TITLE
Typo in package name

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#23483]
**Description:**
The following Ballerina package has typo in its name.

[org.wso2.ballerinalang.compiler.util.diagnotic](https://github.com/ballerina-platform/ballerina-lang/tree/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/diagnotic)

It should be corrected as follows,

org.wso2.ballerinalang.compiler.util.diagnostic

**Steps to reproduce:**
N/A

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Thank you for noticing this issue. Since this is an internal API, the impact is minimal. Hence closing this issue.
