### ISSUE TITLE
Invalid syntax highlighting when defaultable array parameter in a function

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#23516]
**Description:**
When a ballerina function have a nullable and dafaultable array as a parameter, the next parameter is highlighted incorrectly. See below image:
![Screenshot 2020-05-26 at 19 56 55](https://user-images.githubusercontent.com/40016057/82912766-1502d880-9f8b-11ea-8e4b-50fa952bf0cd.png)

Same behaviour is observed when the first parameter is a `string[]?` and have a default value of `()`.

**Steps to reproduce:**
Try below code:

```ballerina
public function sample(int[]? sampleArray = (), int sampleValue = 0) {

}
```

If you remove the default value from the function parameter, this works as expected:
```ballerina
public function sample(int[]? sampleArray, int sampleValue = 0) {

}
```

**Affected Versions:**
VSCode plugin 1.2.4
Ballerina 1.2.4

**Comment by nadeeshaan** [comment]
This issue is associated with the VSCode plugin. Since a separate issue has been created, closing this issue
