### ISSUE TITLE
Need to support equality operator for readonly type

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#23521]
**Description:**

```ballerina
function assertValueEquality(anydata|readonly expected, anydata|readonly actual) {
    if expected == actual {
        return;
    }

    panic error(ASSERTION_ERROR_REASON,
                message = "expected '" + expected.toString() + "', found '" + actual.toString () + "'");
}
```

Compiler returns:
```
operator '==' not defined for '(anydata|readonly)' and '(anydata|readonly)'
```

When I use type guards to narrow the types to `readonly`
```ballerina
function assertValueEquality(anydata|readonly expected, anydata|readonly actual) {
    if (expected is anydata && actual is anydata) {
        if expected == actual {
            return;
        }
    }
    if (expected is readonly && actual is readonly) {
        if expected == actual {
            return;
        }
    }

    panic error(ASSERTION_ERROR_REASON,
                message = "expected '" + expected.toString() + "', found '" + actual.toString () + "'");
}
```

Compiler emits:
```
operator '==' not defined for 'readonly' and 'readonly'
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Deep equality checks are only allowed with `anydata`.

The spec says

> For both == and !=, both operands must have a static type that is a subtype of anydata. 

See https://ballerina.io/ballerina-spec/spec.html#section_6.30

So the error here is expected.

**Comment by rdhananjaya** [comment]
Got it, thank you.

**Comment by MaryamZi** [comment]
Given that we have quite a few behavioural types that fall under `readonly`  (service, function, handle, etc.) IMO it's not straightforward to support this either, and it wouldn't make sense in some, if not most, cases (e.g., service, function).
