### ISSUE TITLE
Add plugin settings to configure diagnostics options

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#23531]
**Description:**
As per the current language server implementation, we are compiling the ballerina project (all the modules) on each text change, to compute diagnostics. But for a fairly large project with this might consume a considerable time and will fail even if the module which user is working has no compilation errors. So it would be better if we can provide a plugin option to limit diagnostics for the current module in such contexts.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This was due to the performance impact of language server's internal package instance caching due to the compiler limitations. This issue has been fixed with the latest compiler APIs and the project APIs. Hence we will be closing this issue. Please reopen if further clarification is needed.
