### ISSUE TITLE
Issue in syntax highlighting when we pass two string parameters

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#23577]
**Description:**
Here two parameters are passed.  But it is treated as a single string.
<img width="452" alt="highlightingIssue" src="https://user-images.githubusercontent.com/30232477/83126638-b9555e00-a0f6-11ea-8e67-5c7da655bd30.png">

**Steps to reproduce:**

**Affected Versions:**
ballerina-1.2.4
Idea plugin - 1.2.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by parkavi11** [comment]
This also occurs when passing string objects inside a json.

<img width="623" alt="Screenshot 2020-05-28 at 17 23 49" src="https://user-images.githubusercontent.com/28732894/83138192-0e4da000-a108-11ea-8ea5-0d1a38c899d9.png">

**Comment by pubudu91** [comment]
@NipunaRanasinghe Can you check and close this if this was fixed in 1.2.6?

**Comment by NipunaRanasinghe** [comment]
> @NipunaRanasinghe Can you check and close this if this was fixed in 1.2.6?

Yeah this is fixed in 1.2.6. Lets close
