### ISSUE TITLE
java.jms Connection class throws nullPointer exception when used without main function

### ISSUE THREAD

**Issue by shraddha786** [ballerina-platform/ballerina-lang#23588]
**Description:**
I tried implementing the message producer example without main function. I created a service with resource function which will send the message to the queue. I have created the connection, session and producer variable gloabally. When I run the module, it throws the below error: 

error: java.lang.NullPointerException
error: there are test failures

There is no test failures. When tried debugging, found the error is thrown at the step of initialising the connection variable.

**Steps to reproduce:**
@MaryamZi  asked me to build the project by adding --skip-tests flag. It worked. But in long term, -skip-test is not a good solution, so want to know how to fix this issue?

Without requiring to add the --skip-tests flag, would be a good solution to my problem in long term. Please make these as high priority and fix this issue.

**Affected Versions:**
Ballerina version: 1.2.3
JMS connector version : 0.8.1

**Suggested Labels (optional):**
Priority/Blocker , Improvement

**Suggested Assignees (optional):**
@MaryamZi , @anuruddhal

**Comment by MaryamZi** [comment]
Yeah, we tried with `--skip-tests` juts to confirm if the issue was with the source itself or with testerina. Running the JAR created by skipping tests works as expected.

The following sample can be used to reproduce the issue.

```ballerina
import ballerina/log;
import ballerina/java.jms;

jms:Connection connection = check jms:createConnection({
                   initialContextFactory: "org.apache.activemq.jndi.ActiveMQInitialContextFactory",
                   providerUrl: "tcp://localhost:61616"
              });
jms:Session session = check connection->createSession({acknowledgementMode: "AUTO_ACKNOWLEDGE"});
jms:Destination queue = check session->createQueue("MyQueue");
listener jms:MessageConsumer jmsConsumer = check session->createConsumer(queue);
service messageListener on jmsConsumer {
   resource function onMessage(jms:Message message) {
       if (message is jms:TextMessage) {
           var val = message.getText();
           if (val is string) {
               log:printInfo("Message received: " + val );
           } else {
               log:printInfo("Message received without text");
           }
       } else {
           log:printInfo("Message received.");
       }
   }
}
```

**Comment by Ibaqu** [comment]
The issue seems to be a case of not handling the internal error properly. And it can be traced back to the `formatErrorMessage90` function in `BTestRunner`. 

```
private String formatErrorMessage(Throwable e) {
        String message;
        if (e.getCause() instanceof ErrorValue) {
            try {
                message = ((ErrorValue) e.getCause()).getPrintableStackTrace();
            } catch (ClassCastException castException) {
                throw new BallerinaException(e);
            }
        } else if (e instanceof BallerinaException) {
            throw (BallerinaException) e;
        } else {
            throw new BallerinaException(e);
        }
        return message;
    }
```

When the instance is a Ballerina exception, the error is thrown without any formatting and is caught in the `executeTests()` function in `TesterinaUtils`. 

This `executeTests()` function simply prints `error : e.getMessage()` without logging the message. 

https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/util/TesterinaUtils.java#L79

**Comment by Ibaqu** [comment]
A simple fix would be to simply add a line in TesterinaUtils where the stack trace is printed to the 'ballerina-internal.log'. 

```
} catch (BallerinaException e) {
            errStream.println("error: " + e.getMessage());
            RuntimeUtils.silentlyLogBadSad(e);     //This prints the log
            throw e;
        } catch (Throwable e) {
            RuntimeUtils.silentlyLogBadSad(e);
            throw new RuntimeException("test execution failed due to runtime exception");
        }
```

However, the issue still remains that the error gets printed in the console as `error: java.lang.NullPointerException`

@hevayo Should I proceed with simply logging the entire stack trace or should the issue be handled in a different approach?
