### ISSUE TITLE
Rewrite object init matching type identification with unions as done for mapping/list constructor expressions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23595]
**Description:**
Currently, when there's a union as the contextually expected type with a new-expr, there's a separate logic to identify matching types - [`findMembersWithMatchingInitFunc`](https://github.com/ballerina-platform/ballerina-lang/blob/6e06a7c74de25409d53ecef95d31ad82e739ddcb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L2558)

Instead it would be better to follow what's done for mapping/list constructor expressions where we do a non-error logging check against each member type and then identify the matching type(s).

See [`checkMappingConstructorCompatibility`](https://github.com/ballerina-platform/ballerina-lang/blob/6e06a7c74de25409d53ecef95d31ad82e739ddcb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L1384)

The current approach also opens up room for error, where we might miss updating some new type-checking rules in `findMembersWithMatchingInitFunc`. And we obviously have to duplicate some checks.

**Comment by MaryamZi** [comment]
The current union type matching member check logic causes a compilation error for the following.

```ballerina
type Foo object {
    int i;

    function __init(int i) {
        self.i = i;
    }
};

type Bar abstract object {
    
};

public function main() {
    Foo|Bar fb = new (1); // cannot initialize abstract object ''
}
```

This could be avoided by the suggested change.

Note the incorrect error message too.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
