### ISSUE TITLE
Fix and align error destructuring binding pattern

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#23591]
**Description:**
Add support for error cause destructuring.
Fix failing unit tests.
Add test cases for cause destructuring.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@rdhananjaya, can we close this also?

**Comment by rdhananjaya** [comment]
> @rdhananjaya, can we close this also?

Seems to be this is good to close.
