### ISSUE TITLE
Improve debug guide

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#23600]
**Description:**
Need to improve the debug guide with more details including 
- How to remote debug
- Clear instruction on how to add the debug configs

**Comment by praneesha** [comment]
@hevayo @NipunaRanasinghe - Please provide the content to be included in the guide.

**Comment by NipunaRanasinghe** [comment]
Closing since the debug guide is updated with remote debugging instructions and debug configs support
