### ISSUE TITLE
ballerina: unknown command 'dist'

### ISSUE THREAD

**Issue by chenjianxin** [ballerina-platform/ballerina-lang#23627]
os:win10

why???
```
ballerina -v
jBallerina 1.2.2
Language specification 2020R1
```
```
ballerina dist update
ballerina: unknown command 'dist'
Run 'ballerina help' for usage.

```

**Comment by keizer619** [comment]
These `ballerina dist` commands are included by ballerina update tool.. Seems you are using jballerina zip distribution (Which is produced by ballerina-lang repository as well). This does not include ballerina update tool. This is been packed by ballerina-distribution [1] repository. 

You can get the Installer for windows or ballerina zip file from the ballerina website which include ballerina update tool.

[1] https://github.com/ballerina-platform/ballerina-distribution

[2] https://ballerina.io/downloads/

**Comment by keizer619** [comment]
I am closing this issue hoping above answer helps you. Please feel free to reopen if you have further issues.
