### ISSUE TITLE
Ballerina toml version not support SNAPHOT versions

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#23657]
**Description:**
According to the recent offline discussions, we are going to use the version specified in the `Ballerina.toml` as the module version for Stdlibs. 

As long as Stdlibs reside inside ballerina-lang, we do not need to maintain `SNAPSHOT` versions. However, when we move Stdlibs out, it is essential to maintain a `SNAPSHOT` versions for each Stdlib, but `SNAPSHOT` versions are not supported in these `Ballerina.toml` version.

When I specified a version as `0.6.0-SNAPSHOT` version, it gives the following error.

```sh
error: invalid Ballerina.toml file: 'version' under [project] is not semver
```

As far as I understand, that happens because of the TOML parser.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/ManifestProcessor.java

**Affected Versions:**
ballerina 2.0.0-SNAPSHOT

**Comment by azinneera** [comment]
Teste with SL Beta1 and this issue is not present. Any version that is SemVer compatible can be used
