### ISSUE TITLE
Tooling support for raw template literals

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#23785]
PR #23705 adds support for raw template literals. Need to check and add any tooling support required for it.

**Comment by pubudu91** [comment]
It looks like tooling support is required for custom defined raw template types. See the following:
![Peek 2020-09-21 17-49](https://user-images.githubusercontent.com/6260009/93765589-c6143980-fc32-11ea-9e44-73fd9e9958a6.gif)

**Comment by rasika** [comment]
Ack, will check on this. Will create sub issues for below action items;

- [ ] Completion support for raw template literals
- [ ] Code Action support for raw template literals
- [ ] Signature support for raw template literals

**Comment by pubudu91** [comment]
The raw template is just another object. So I think it should've worked like how it works for any other object works right?

**Comment by rasika** [comment]
Oh this is an old one. I thought we introduced another node. BLangRawTemplateLiteral node and template literal in the spec is already covered. This might be a bug.

**Comment by pubudu91** [comment]
Ok, I just checked again, I think this could be an issue with giving completions for an index-based access expr. For example, it gives completions correctly for the following.
```ballerina
Query q = `INSERT INTO Details VALUES (${"Pubudu"}, ${10})`;
queries[0].<cursor>
```

**Comment by nadeeshaan** [comment]
@pubudu538 can you elaborate more on the issue to pin point the actual failing case?

**Comment by pubudu91** [comment]
This seems to be working in the latest master. Hence closing this.
