### ISSUE TITLE
Incorrect parser error for invalid nodes in between other module-level declarations

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#23818]
Sample code:
```java
String source = "import ballerina/io; adfad; public function foo() returns int {} adfadfa;";
TextDocument textDocument = TextDocuments.from(source);
SyntaxTree syntaxTree = SyntaxTree.from(textDocument);
syntaxTree.diagnostics().forEach(System.out::println);
```

Output:
```
xxx.bal:0:0:imports must be declared before other declarations
ERROR [:(0:21,0:21)] ERROR_MISSING_IMPORT_KEYWORD
ERROR [:(0:65,0:65)] ERROR_MISSING_IMPORT_KEYWORD
```

As you can see, the parser assumes the second  "adfadfa" as an import node.

**Comment by SupunS** [comment]
Thats actually a limitation in the current error recovery. 

Reason is, it is not possible to determine whether user actually has written an import with some errors, or is it some other invalid node. So we can't rule out the possibility of import-decl when going for recovery.

But, considering the fact that import-decls are less probable to occur, I have reduce the priority of the import decl, at the error recovery (#23834). So the recovered node will more likely to be some other module-level decl (var-decl in this scenario). 

This solution is kind of delegation of the problem to a lesser probable case. 
for e.g: in below sample.
```ballerina
foo;
import ballerina/io;

function someFunc() {
}

bar;
```

both `foo;` and `bar;` will be recovered as var-decl.

**Comment by SupunS** [comment]
We can actually further improve this, by selectively prioritising import-decl, depending on the current context.
