### ISSUE TITLE
Enable Github plugin for Code Climate

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#23817]
We have added the ballerina-lang repo to [Code Climate](https://codeclimate.com/github/ballerina-platform/ballerina-lang), but don't seem to be making any use of it. I think it would be good to enable the Github plugin for Code Climate. This way, we'll know of quality issues when the PR sent and can fix it then and there.

**Comment by keizer619** [comment]
I am closing this as we have now integrated CodeCov for coverage reportings
