### ISSUE TITLE
Parser fails to report the presence of required params after an defaultable params

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#23820]
How to reproduce:
```java
        String source = "import ballerina/io; public function foo(int a, int b = 5, int a) returns int {}";
        TextDocument textDocument = TextDocuments.from(source);
        SyntaxTree syntaxTree = SyntaxTree.from(textDocument);
        syntaxTree.diagnostics().forEach(System.out::println);
```

**Comment by SupunS** [comment]
I think this validation is there: https://github.com/ballerina-platform/ballerina-lang/blob/494f6ae74daf08f0bf9bf282d90f8ed37d97267f/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/BallerinaParser.java#L1961

We may need to migrate it to the new diagnostic API.

**Comment by SupunS** [comment]
Fixed in preview 1
