### ISSUE TITLE
BType.toString() need to display pkg version information.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#23851]
**Description:**
With the support for multiple versions of the same module being used, we need to add that version information when we display runtime errors.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Since we can have only one version now, we don't need this, do we? @rdhananjaya @warunalakshitha
