### ISSUE TITLE
Fix lang server tests failures due to new transaction implementation

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#23865]
Following tests are disabled, as they fail due to the new transaction implementation syntax changes. These are disabled in the org.ballerinalang.langserver.completion.definitions.FunctionDefinitionCompletionTest class

{"completionWithinWorkersInResource.json", "function"},
{"completionBeforeIfElse.json", "function"},
{"completionWithinIf.json", "function"},
{"completionWithinElse.json", "function"},
{"completionWithinElseIf.json", "function"},
{"completionBeforeWhile.json", "function"},
{"completionWithinWhile.json", "function"},
 {"completionWithinTransaction.json", "function"},
{"completionWithinTransactionOnRetry.json", "function"},
{"completionWithinTransactionAborted.json", "function"},
{"completionWithinTransactionCommited.json", "function"},

**Comment by nadeeshaan** [comment]
Changes have been incorporated in the master branch, hence closing the issue.
