### ISSUE TITLE
Treat a lone basic-literal at statement level as an expression

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#23877]
**Description:**
Basic literals are mapped as LHS of the var-declr.

**Steps to reproduce:**
```
function latestVars() {
    1;
    "";
    true;
}
```
<img width="966" alt="Screenshot 2020-06-10 at 12 50 33" src="https://user-images.githubusercontent.com/1448489/84252070-c711d700-ab2b-11ea-949f-0ddc067f1dda.png">

As a suggestion; Can try reading next token to decide what it should be. Basically if we have `;`  as nextToken, it means RHS otherwise we treat it as LHS of the var-declr?`

1. `Token` //<----- at this point we don't know whether this is T or expr. We go with T.
2. `Token` `;` //<----- this is definetly not a T, we go with expr

**Affected Versions:**
2.0.0-Preview1

**Comment by SupunS** [comment]
@rasika What are the other cases that we need to treat as expressions? 
There are several combinations that have the ambiguity between a type-desc and an expression:
1) An identifier 
  eg: `x ;`  --> Singleton type-desc vs binding-pattern vs expression

2) A Basic literal `"foo";`
  eg: `"foo";`  --> Singleton type-desc vs expression

3) Union of (1), (2), and (4)
  eg: `"foo" | 4 | x ;` --> Union type-desc vs binary-expr

4) Intersection of (1), (2), and (3)
  eg: `"foo" & 4 & x ;` --> Intersection type-desc vs binary-expr

**Comment by rasika** [comment]
Seems covering the basic cases. Will go through the tests cases for code-actions to check if we missed anything. What about this? `[[1,2,3][4,5,6]];`

**Comment by rasika** [comment]
Some more tests;
```
    [[1, 2, 3], [10, 20, 30], [5, 6, 7]];
    [[1, "", 3], [10, "", 30], [5, "", 7]];
    [[1, "", 3], [true, 1.1]];
    [1, ""];
    [1, 2, 3];
```
