### ISSUE TITLE
Getting a "Bad. Sad." when using "cloneWithType()" & "fromJsonString()" langlib methods

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#23915]
**Description:**
I am getting a "Bad. Sad" When I run the following code with the current master.

```ballerina
public function main() {
    string anArray = "[\"hello\", \"world\"]";
    json j = <json> anArray.fromJsonString();
    string[]|error k = j.cloneWithType(string[]);
}
```

This happens due to a casting `java.lang.String` to `BString` in `ArrayValueImpl.addRefValue` 
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/4762725/ballerina-internal.log)

**Comment by MaryamZi** [comment]
This seems to be happening due to the `String` to `BString` conversion not happening with the particular `JSONParser.parse()` method used in the `fromJsonString()` native implementation. 

Also, if certain `JSONParser` methods are not expected to be used externally, shall we look at making them private?

**Comment by riyafa** [comment]
I am trying to build the provided code in the current master and getting the error:
```
error: .::json_conv.bal:7:47: missing key expr in member access expr
```
and am unable to reproduce the error

**Comment by MaryamZi** [comment]
The new parser disallows using `string[]` as an expression, in line with the spec.

Please check with

```ballerina
type StringArray string[];

public function main() {
    string anArray = "[\"hello\", \"world\"]";
    json j = <json> anArray.fromJsonString();
    string[]|error k = j.cloneWithType(StringArray);
}
```

**Comment by dulajdilshan** [comment]
Hi @riyafa 

I did these change to `fromJsonString()` langlib method to overcome this issue for now: https://github.com/ballerina-platform/ballerina-lang/pull/24057/files#diff-4181894dfb92af369b865567307e2d2e

However, it worked. If you want to check this - this is my PR https://github.com/ballerina-platform/ballerina-lang/pull/24057

**Comment by riyafa** [comment]
I think there's still an issue in the `JSONParser` though your change might fix this particular issue.
