### ISSUE TITLE
Runtime api to access the strand instance for native functions

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#23932]
**Description:**
ATM developers use "Scheduler.getStrand()" to retrieve the strand instance. We need to review this as IMO accessing scheduler is not a good practice. It should not expose any apis. All the apis should be expose from BRuntime

**Comment by manuranga** [comment]
it is decided (in #23189) to be accessed (maybe indirectly) using the BalEnv. will be done under #25254 .
