### ISSUE TITLE
Disallow `distinct` with non object/error types.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#23999]
**Description:**
distinct types are only supported with object types and error types. We need to emit an error when distinct is used with other types.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
The following seems to result in a compilation error.

```ballerina
type Foo distinct record {
    
};
```

```
distinct typing is only supported for object type and error type
```

@rdhananjaya, any other specific scenarios we need to handle here?

**Comment by rdhananjaya** [comment]
I think we need to handle inline type declarations such as below, it results in runtime crash.

```ballerina
import ballerina/io;
public function main() {

    distinct record { int i = 0; } r = {};
    io:println(r);

}
```
