### ISSUE TITLE
Issue in xml process instruction parsing

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#24065]
**Description:**
source code:

`<?foo  aaa11bbb22ccc?>`

The target should be parsed as `foo ` (extra white space), but that white space has been moved to the data part (` aaa`).

**Comment by SupunS** [comment]
To add a bit more context, the issue is, WS is not propagated to runtime for XML. BLandNodes ignore WS when creating XMLs.

This issue may in other places of the xml, such as WS between attributes etc.
