### ISSUE TITLE
Map as record and record as map allowed at compile-time but not allowed at runtime

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24079]
**Description:**
$title, seems like the "is-type" checks allowed between maps and records have only been introduced at compile-time.

**Steps to reproduce:**
**Map to Record**
```ballerina
import ballerina/io;

type Foo record {|
    int i?;
    int...;
|};

public function main() {
    map<int> mp = {
        i: 1,
        j: 2
    };
    Foo f = mp; // allowed

    any a = mp;

    // io:println(mp is Foo); // Compilation error - expression will always evaluate to 'true'

    io:println(a is Foo); // false!
}
```

**Record to Map**
```ballerina
import ballerina/io;

type Foo record {|
    int i?;
    int...;
|};

public function main() {
    Foo f = {
        i: 1,
        "j": 2
    };
    map<int> mp = f; // allowed

    any a = f;

    // io:println(f is map<int>); // Compilation error - expression will always evaluate to 'true'

    io:println(a is map<int>); // false!
}
```

**Affected Versions:**
Current master.

**Comment by pubudu91** [comment]
Related issue for the compile time checking #17202. I've enabled the above at compile time in PR #22292, not sure why the runtime checks weren't added with that though. :sweat_smile:

**Comment by MaryamZi** [comment]
Record to map assignability seems to be working on the current master. #26533 will fix map to record assignability.

**Comment by dulajdilshan** [comment]
Getting `BLangRecordLiteral cannot be cast to class BLangVariableReference at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2463)`

for 

```ballerina
type Alpha record {|
    int a;
|};

public function main() {
    Alpha rec = {a: 3;
    map<int> mm = {..rec}};
}
```

Will this also be solved with this ?

**Comment by MaryamZi** [comment]
> ```ballerina
> type Alpha record {|
>     int a;
> |};
> 
> public function main() {
>     Alpha rec = {a: 3;
>     map<int> mm = {..rec}};
> }
> ```

No, this is a compile-time issue due to the syntax errors. Works when those are fixed.

```ballerina
type Alpha record {|
    int a;
|};

public function main() {
    Alpha rec = {a: 3};
    map<int> mm = {...rec};
}
```

Can you please create a separate issue for this?

**Comment by dulajdilshan** [comment]
Created #26544
