### ISSUE TITLE
Test `testBindgenMvnCmd` intermittently fails

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#24071]
**Description:**
Following is an excerpt of the log file. I have attached the full log file as well.

![image](https://user-images.githubusercontent.com/6178058/84573885-d65d8280-adc0-11ea-9694-b3f57d4f7a19.png)

[m6bwbgh2s2mmq-console-log.txt](https://github.com/ballerina-platform/ballerina-lang/files/4774968/m6bwbgh2s2mmq-console-log.txt)

**Comment by hevayo** [comment]
The said test is enabled in master
