### ISSUE TITLE
Support `readonly object`s

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24076]
**Description:**
$title. 

https://github.com/ballerina-platform/ballerina-lang/pull/23795 will introduce support for `readonly object`s. 

```ballerina
public type Foo client readonly object {
};
```

#23795 is implemented on the antlr parser and only allows `readonly` immediately before `object`, but as mentioned in https://github.com/ballerina-platform/ballerina-spec/issues/535#issuecomment-643059000 this can be allowed in any combination as with the current [object-type-quals `abstract` and `client`](https://ballerina.io/spec/lang/2020R1/#section_5.4.2). 

e.g.,
```ballerina
public type Foo readonly client object {
};
```

I guess this would be another object-type-qual and would need another case in `io.ballerinalang.compiler.internal.parser.BallerinaParser#parseObjectTypeQualifiers(io.ballerinalang.compiler.syntax.tree.SyntaxKind)`.

**Comment by MaryamZi** [comment]
We can enable org.ballerinalang.test.object.ReadonlyObjectTest on the new parser (which was disabled with https://github.com/ballerina-platform/ballerina-lang/pull/23795/commits/c9b99bcb74708bd1f7bf7a4763627dcc2c8330a9#diff-bae1685cb6faf73239d1383a92ec31c9R34) when fixing this.

**Comment by SupunS** [comment]
Also need to enable `ReadOnlyObjectBaloTest`

**Comment by MaryamZi** [comment]
Need to also enable ReadonlyObjectFieldTest's testReadonlyObjectFields. Disabled in https://github.com/ballerina-platform/ballerina-lang/pull/24107/commits/d875439364cd0f238223688330da3b98237e075b#diff-04c03ee79ed553d73d2b9bea8eabc0f5R36
