### ISSUE TITLE
Intersection type validation should look at the default value specified for a field

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24077]
**Description:**
$title.

See the suggested rule at https://github.com/ballerina-platform/ballerina-spec/issues/544#issuecomment-643069011.

**Steps to reproduce:**
The following should result in a compilation error since the default value of `details` is of type `Details` and is mutable (i.e., not `Details & readonly`).

```ballerina
type Details record {
    string name;
};

Details det = {name: "Maryam"};

type Employee record {
    Details details = det;
};

public function main() {
    Employee & readonly emp = {}; // `Employee & readonly` is not a valid intersection type
}
```

This currently fails at runtime when creating the value, but should actually fail at compile-time.

```cmd
$ ballerina run xyz.bal 
Compiling source
        xyz.bal
Running executables

error: {ballerina/lang.map}InherentTypeViolation message=invalid value for record field 'details': expected value of type '(Details & readonly)', found 'Details'
        at xyz:main(xyz.bal:12)
```

**Comment by MaryamZi** [comment]
This is currently not possible since we don't have any details about the default value in the type/symbol. We need at least the type of the default value.

**Comment by MaryamZi** [comment]
On hold until https://github.com/ballerina-platform/ballerina-spec/issues/544#issuecomment-655671466 is decided upon.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available. We will attend this once the spec issue is resolved.

**Comment by gimantha** [comment]
Now we are giving the following error for the default value
`ERROR [main.bal:(8:23,8:26)] invalid access of mutable storage in the default value of a record field`
![Uploading image.png…]()

**Comment by MaryamZi** [comment]
I guess the code should now be 

```ballerina
isolated function getDetails() returns Details => {name: "Maryam"};

type Employee record {
    Details details = getDetails();
};
```

We now use `cloneReadOnly` with the default value to make this work.
