### ISSUE TITLE
Revisit ambiguity in expr: a/<b>c

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24099]
**Description:**

First half of the below code matches to xml-step-expr 
```
a/<b>c
```

Revisit parsing above, to see if it can be correctly identified by parsing the remainder of the expression to resolve ambiguity.

**Comment by manuranga** [comment]
reenable tests/jballerina-unit-test/src/test/resources/test-src/expressions/lambda/iterable/iterable-arrow-expression.bal after fixing

**Comment by SupunS** [comment]
This seems to be an extremely hard case to tackle do the ambiguity of the grammar. In order to solve this, we need to:
- Parse the first part `a/<b>` keeping all options available.
  - `b` could be either an xml-name-pattern or a type-desc
- If `b` is a definite xml-name-pattern - Then parse the expr as xml-step expr
- If `b` is a definite type-desc - Then parse expr as a binary expr (division), having a type-cast-expr as the denominator
- if `b` is ambiguous (e.g:) - Then look at the node to follow and then decide.
  - The node to follow can again be ambiguous: eg:
    - `a /<b> [c]` - [c] could be an expression or an index of a index-access expr
    - `a /<b> +5` - Here `<b> +5` could be a type-cast expression, or can treat entire

**Comment by SupunS** [comment]
Another ambiguous scenario: 
````
from var x in bookStore/<book>/<author>
let string authorDetails = "John"
```
