### ISSUE TITLE
Different font size and line spacing used in the key concepts page under : Functions

### ISSUE THREAD

**Issue by maheshika** [ballerina-platform/ballerina-lang#2412]
Different font size and lined spacing within the Key Concepts page under key concepts. http://ballerinalang.org/docs/user-guide/0.8/key-concepts/

**Comment by appellj** [comment]
This is a stylesheet issue that I reported a while back. Bullets should be the same font size as paragraphs, but bullets that include <p> tags are being increased in size relative to the bullets (if you increase the bullet font size, the bullets with <p> tags are increased even more). I am not a CSS expert, but I think I've figured out how to fix this. Please test on various browsers and platforms.

**Comment by uthaiyashankar** [comment]
User guides are not there now. Hence, resolving.
