### ISSUE TITLE
Enable annotation Body Completion test cases

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#24131]
**Description:**

annotationBodyCompletion1,2,6 are disabled by commit https://github.com/ballerina-platform/ballerina-lang/pull/23473/commits/098f22154c4b12fdc384a03961e14c01301bd30a.

Looks like completion for a `readonly & recordType` is changed from `{}` to `()`. Looks like this is no longer recognized as a record type.

**Related Issues (optional):**

Issue: #15533

**Suggested Labels (optional):**
Component/LanguageServer

**Comment by MaryamZi** [comment]
Possibly related to https://github.com/ballerina-platform/ballerina-lang/issues/23313.

**Comment by nadeeshaan** [comment]
Tests have been enabled, hence closing the issue
