### ISSUE TITLE
Invalid positions are output from parser

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24130]
**Description:**
Consider the following source snippet.

```
public type ErrorTypeDesc1 error<TestReason, TestDetail>;

public type ErrorTypeDesc3 error<REASON_CONST, TestDetail>;

public type TestReason string;

public const string REASON_CONST = "Test Reason";

type TestDetail record {|
    string message?;
    error cause?;
|};
```

**Steps to reproduce:**
In the above source snippet, positions are invalid for `TestReason`. This is only happening when the following line is present.
`public type ErrorTypeDesc3 error<REASON_CONST, TestDetail>;`

**Comment by SupunS** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/24010 andhttps://github.com/ballerina-platform/ballerina-lang/issues/23869

**Comment by SupunS** [comment]
@nadeeshaan The positions seems to be correct (on latest master branch). can you check whether you still getting the issue?

**Comment by nadeeshaan** [comment]
Fixed in latest master. Hence closing the issue
