### ISSUE TITLE
Unable to generate API docs

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#24180]
**Description:**
- Generating api docs from docker and k8s module fails with following error. 
```
Compiling source ballerina/docker:1.0.0 error: module not found for: ballerina/docker:1.0.0_java8 error: no modules found to compile.
```

**Comment by shehan360** [comment]
Running the command:
`export JAVA_OPTS=-DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true`
before running `ballerina doc docker` should fix this issue.

**Comment by pramodya1994** [comment]
Closing the issue after verifying the fix.
