### ISSUE TITLE
Moving desugared code to separate methods

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#24187]
**Description:**
This is to avoid resource functions, for instance, growing in size with added statements (and in turns, the number of byte code instructions).

The main reason we end up with a large method is how we transform the actual source to various intermediate representations. Even before we reach the bytecode generation phase, previous phases add more information (basically more statements are added) to the AST.

A simple helloService resource like the below

```ballerina
    resource function sayHello(http:Caller caller, http:Request request) {
        error? result = caller->respond("Hello Ballerina!");
        if (result is error) {
            io:println("Error in responding: ", result);
        }
    }
```

will have around ~30 statements after it is desugared like the below AST.

```
BLangFunction: [ATTACHED, RESOURCE] sayHello ([ballerina/http:1.0.0:Caller caller, ballerina/http:1.0.0:Request request]) {
	ballerina/http:1.0.0:FilterContext _$$_filterContext = ballerina/http:1.0.0:FilterContext 
	$obj$ = BLangTypeInit: new ([self, hello, sayHello]); 
	$init$(); 
	caller[filterContext] = <ballerina/http:1.0.0:FilterContext?> _$$_filterContext; 

	(ballerina/http:1.0.0:RequestFilter|ballerina/http:1.0.0:ResponseFilter)[] $data$ = caller[config][filters]; 
	object { public function next () returns (record {| (any|error) value; |}?); } 
	$iterator$ = <object { public function next () returns (record {| (any|error) value; |}?); }> $data$.iterator($data$); 
	record {| (any|error) value; |}? $result$ = <record {| (any|error) value; |}?> next(); 

	While: ($result$ is )  {
		ballerina/http:1.0.0:RequestFilter _$$_filter = <ballerina/http:1.0.0:RequestFilter> <record {| (any|error) value; |}> $result$[value]; 
		$result$ = <record {| (any|error) value; |}?> next(); 
		if (boolean $result$; if (<ballerina/http:1.0.0:RequestFilter> _$$_filter is http:RequestFilter) $result$ = ! RequestFilter.filterRequest() else $result$ = false) 
		Return: ()
	}; 

	error? result = <error?> respond(); 
	if (result is error<>) 
		io:println(Error in responding: , result); 
	Return: ()
}
``` 

And at the bytecode generation phase, we transform this method to a single java method where we have to handle all the possible non-blocking invocations and generate code accordingly (eg: switch cases are generated to support yield and resume) which is why we see the method size (i.e the number of instructions) growing. 

One possible thing we can do is, we can try and move the newly added code by the desugared phase, to one or more methods based on logical grouping of statements.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
