### ISSUE TITLE
Function Mocking doesnt work properly with Multiple Modules

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#24185]
**Description:**
When attempting to use Mock Functionality with multiple modules present in the Ballerina project, we get an invocation error

```
org.ballerinalang.jvm.util.exceptions.BallerinaException message=invocation failed: mohamedaquibzulfikar.MockScoping.0_1_0.tests.null
                at ballerina.test.0_0_0:mockHandler(mock.bal:369)
               mohamedaquibzulfikar.TestingStuff.0_1_0.tests.main_test:test1(tests/main_test.bal:17)
```

**Steps to reproduce:**
1. Create a ballerina project
2. Create 2 new modules
3. Write test code using the mocking functionality
4. Build 

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
The issue lies in the way the `callFunction()` picks up the packageName from the `projectJarCachePath`

https://github.com/ballerina-platform/ballerina-lang/blob/ec1bd23da8abc3ea21b0846704eaad43c8a7a7dc/misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/natives/test/FunctionMock.java#L75

The `packageName` ends up being whatever module that was created first. So every subsequent module fails to mock the function properly.

**Comment by azinneera** [comment]
We should change the implementation to get the org name, module and version from the stacktrace
