### ISSUE TITLE
Add more tests for cyclic typedef

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-lang#24201]
**Description:**
This PR: https://github.com/ballerina-platform/ballerina-lang/pull/24106 adds support for cyclic union type-def, it has only covered basic tests. More tests needs to be added.

**Comment by MaryamZi** [comment]
@KRVPerera, can we close this issue now?

**Comment by KRVPerera** [comment]
Test cases are added via https://github.com/ballerina-platform/ballerina-lang/pull/26371
Also `anydata` and `json` types are also defined as cyclic types.
