### ISSUE TITLE
Increase the minimum-matching threshold

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24239]
**Description:**

In the below line:
https://github.com/ballerina-platform/ballerina-lang/blob/fc34e7ad5e2bec97dc2372d442da3606c21f3e92/compiler/ballerina-parser/src/main/java/io/ballerinalang/compiler/internal/parser/AbstractParserErrorHandler.java#L86

Consider increasing the threshold. That will help to remove junk tokens, as opposed to trying to match them to a possible grammar-rule. It will act as a noise filtering.

Some possible threshold: 20% matches out of total traversed distance.

**Comment by SupunS** [comment]
Requires to add
```java
case EOF:
    return ParserRuleContext.EOF;
```

For XML parser's getNextRule() method.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
