### ISSUE TITLE
Handle recovered nodes coming from the parser at the compiler front end

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24240]
**Description:**

Related to: https://github.com/ballerina-platform/ballerina-lang/issues/23017

Issues mentioned in #23017 are handled. For things like variables, func-names, etc. are handled in the NodeTransformer as well and in the SemanticNalayzer place.

However, there are few more other places we need to figure out and fix.
This is a blocker for enabling resilient parsing (doing semantic validations even with syntax errors).

**Comment by SupunS** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/24226

**Comment by SupunS** [comment]
Another sample:
```ballerina
import ballerina io;

public main(int ,string  = "hello") 
    int = 5
    int = 6;
    io:println("Hello, world!");

    Foo f new(3, "John");
    io:println(f);
}

type record {
    int a;
    string b;
}

type Foo {
    int a;
    string b;

    function __init(int a string b) {
        self.a = a;
        self.b = b;
    }
}


function  () 
}

function  () 
}
```

**Comment by SupunS** [comment]
Consider this as well: https://github.com/ballerina-platform/ballerina-lang/issues/24273#issue-640554115

**Comment by KavinduZoysa** [comment]
Another example:
import ballerina/http;
import ballerina/log;
service hello on new http:Listener(9090) {
    resource function sayHello(http:Caller caller, http:Request req) {
        var result = caller-->respond("Hello, World!");
        if (result is error) {
            log:printError("Error sending response", result);
        }
    }
}
