### ISSUE TITLE
Enable readonly object checks for annotation value

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#24246]
**Description:**
This issue depends on StandardLibs changes: https://github.com/ballerina-platform/ballerina-lang/issues/24217

**Steps to reproduce:**
Create an object with invalid `readonly` values and try to use it in an annotation value. The compiler does not complain.

**Affected Versions:**
all

**Related Issues (optional):**
#24217 #24245

**Suggested Labels (optional):**
Area/Language

**Comment by MaryamZi** [comment]
```ballerina
annotation record {| Foo f; |} annot on type;

class Foo {
    int i = 0;
}

@annot {
    f: new ()
}
type Bar record {|
    
|};
```

**Comment by MaryamZi** [comment]
I believe we can fix this now since the stdlib scenarios were fixed. This may be a breaking change though.

**Comment by MaryamZi** [comment]
Although https://github.com/ballerina-platform/ballerina-standard-library/issues/74 was fixed, seems like there are other mutable fields in HTTP annotations now - https://github.com/ballerina-platform/ballerina-standard-library/issues/4300.
