### ISSUE TITLE
Update help sections for remote debugging flags in CLI

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#24275]
**Description:**
Few suggestions were made by @praneesha while we were adding a help section for a different flag which is related to `--debug` flag.

* https://github.com/ballerina-platform/ballerina-lang/pull/24252#discussion_r441505820
* https://github.com/ballerina-platform/ballerina-lang/pull/24252#discussion_r441506034

Since I am not familiar about the context and the meaning of the help text seemed to slightly differ with the suggestions, I have created this issue. Please do the needful regarding this.

**Comment by NipunaRanasinghe** [comment]
@nadundesilva Please find my suggestions on the requested changes below.
- https://github.com/ballerina-platform/ballerina-lang/pull/24252#discussion_r441686909 
- https://github.com/ballerina-platform/ballerina-lang/pull/24252#discussion_r441689851

**Comment by NipunaRanasinghe** [comment]
Closing since this is already resolved in https://github.com/ballerina-platform/ballerina-lang/pull/24252
