### ISSUE TITLE
Improve syntax errors generated by the new parser

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#24286]
**Description:**
[This file](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-parser/src/main/resources/syntax_diagnostic_message.properties) lists all syntax errors generated by the new parser. 

Most of them are not descriptive enough. We need to spend cycles on updating them.

**Comment by SupunS** [comment]
For invalid token errors, should we also print what the token is?
eg:
```ballerina
public function foo()) returns int {
}
```
Above program currently gives below error: 
```
error: .::testMain.bal:1:24: invalid token
```
Nice to have:
```
error: .::testMain.bal:1:24: invalid token ')'
```

**Comment by sameerajayasoma** [comment]
@SupunS I've updated the invalid token reporting with this [PR](https://github.com/ballerina-platform/ballerina-lang/pull/24284) a few hours ago. Now you get invalid token errors as you've mentioned.

**Comment by rasika** [comment]
Currently, for the local variable assignment missing cases, parser returns `invalid expression statement` which is a more generic error. Can't we have the more intuitive error such as `variable assignment is required` which the old parser / compiler had?

Few sample cases;
```ballerina
function foo(){
    1;
    "";
    true;
}
```

**Comment by SupunS** [comment]
A related issue quoted from https://github.com/ballerina-platform/ballerina-lang/issues/24549:

> Consider the following snippet:
> 
> function foo(typedesc<anydata> td = <>) {
>     
> }
> Trying to compile the above results in the following error messages:
> ```
> error: pubudu/fizz:0.1.0::main.bal:15:38: missing type desc
> error: pubudu/fizz:0.1.0::main.bal:15:39: missing identifier
> ```
> I think the first error message should either say "type descriptor" or "typedesc".

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
