### ISSUE TITLE
Fix conditional expressions in all places

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24294]
When there is `expr1 ? ident : expr2`, parser needs to termination without treating `ident:` as a qualified identifier.

Currently this scenario works. However, this middle-expr can be many other things as well such as `check ident`, `<T> ident`, etc. So we need to fix this for any expression that can ends with a n identifier.

Some of the issues were fixed in https://github.com/ballerina-platform/ballerina-lang/pull/24279/commits/63c5f08e8bfb1264361cf96f78769034492de40d. But need to find and fix remaining ones.

**Comment by MaryamZi** [comment]
As discussed on Slack, the following fails atm.

```ballerina
public function main() {
    json j = {a: 1, b: "str"};
    string s = j.a is string ? <string> j.a : "";
}
```
Fails with

```
error: .::test.bal:4:45: missing colon token
error: .::test.bal:4:47: invalid token ':'
```

Had to add parentheses around `<string> j.a` to get this working.

```ballerina
public function main() {
    json j = {a: 1, b: "str"};
    string s = j.a is string ? (<string> j.a) : "";
}
```
