### ISSUE TITLE
Compile error shown even after the error is fixed

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24305]
Refer to the following. Even after fixing a compile error, it doesn't stop highlighting the error until another error occurs. 
![Peek 2020-06-18 14-38](https://user-images.githubusercontent.com/6260009/85001803-bf78b080-b171-11ea-9220-45724c7b6079.gif)

**Comment by manuranga** [comment]
I am facing the same. looks like a bug.

**Comment by KRVPerera** [comment]
Same here: https://github.com/ballerina-platform/ballerina-lang/issues/24303

**Comment by manuranga** [comment]
Here is the log https://gist.github.com/manuranga/f9daeacc1676c24b6728edb029c7e521

**Comment by nadeeshaan** [comment]
This has been fixed with the docker change. Hence closing the issue
