### ISSUE TITLE
No error given for assigning new values to a function's identifier

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24315]
Consider the following:
```ballerina
import ballerina/io;

public function main() {
    foo = function(string s, int i) returns string => "Bar"; // Not complaining about this
    io:println(foo("", 10));
}

function foo(string s, int i) returns string => "Foo";
```
The above compiles and runs fine. It doesn't print `Bar`, which means the function `foo` points to remains unchanged. But that assignment should've caused a compile error since IINM, we consider function names as final.

**Comment by MaryamZi** [comment]
Also see https://github.com/ballerina-platform/ballerina-lang/issues/30577. Need to verify all kinds of constructs.
