### ISSUE TITLE
Cannot cast JSON to map<anydata>

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24319]
Consider the following:
```ballerina
import ballerina/io;

public function main() {
    json j = {"name":"Foo", age: 20};

    map<json> mj = <map<json>>j; // this is allowed

    map<anydata> m = <map<anydata>>j; // incompatible types: 'json' cannot be cast to 'map<anydata>'
}
```

The problem may be not limited to JSON -> map<anydata> here. The spec says the following:
> Let T be the static type described by type-descriptor, and let TE be the static type of expression. Then the static type of the type-cast-expr is the intersection of T and TE', where TE' is TE with its numeric shapes transformed to take account to the possibility of the numeric conversion specified in the previous paragraph.
>
> The contextually expected type for expression is the intersection of the contextually expected type of the type-cast-expr and the type described by the type-descriptor.

Need to ensure the casting behaviour is in-line with this.

Related issue: #24322

**Comment by MaryamZi** [comment]
This is allowed now. https://github.com/ballerina-platform/ballerina-lang/issues/24559 tracks the generic issue.

Keeping this open to add a test.

**Comment by MaryamZi** [comment]
Tests added in https://github.com/ballerina-platform/ballerina-lang/pull/35505.
