### ISSUE TITLE
Error in one line cause the suggestions to stop

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#24326]
**Description:**
Having an error in the next line cause the suggestions to stop. This is not the case for java in intellij.

**Steps to reproduce:**
Consider the following code:
![Peek 2020-06-18 18-51](https://user-images.githubusercontent.com/8238078/85025435-04faa500-b195-11ea-81ec-3b7648ddab46.gif)
This is the behavior of similar scenario in intellij for java code:
![Peek 2020-06-18 18-52](https://user-images.githubusercontent.com/8238078/85025527-222f7380-b195-11ea-8d94-687aef0e2331.gif)
Code completion is supported even if there's an error.

**Affected Versions:**
Swan Lake Preview1 

**OS, DB, other environment details and versions:**
Kubuntu 20.04

**Comment by nadeeshaan** [comment]
Fixed with the latest syntax tree API migration. Hence closing the issue.
