### ISSUE TITLE
"missing question mark token" error when there's a comma missing in a mapping-constructor-expr

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24330]
**Description:**
$title.

The error is for the next line.

**Steps to reproduce:**
```ballerina
type Foo record {
    int i;
    string s;
};

public function main() {
    Foo f1 = {
        i: 1 // missing a comma here
        s: "str"
    };
}
```

```cmd
$ ballerina run xyz.bal 
Compiling source
        xyz.bal
error: .::xyz.bal:9:1: missing question mark token
```

**Affected Versions:**
Preview1-M6

**Comment by SupunS** [comment]
Missing/adding a question-mark is also syntactically correct ;)

**Comment by MaryamZi** [comment]
> Missing/adding a question-mark is also syntactically correct ;)

Yes, yes! Was thinking of this more as an improvement. :smiley:
