### ISSUE TITLE
Possible tooling improvements related to the `error` type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24382]
**Description:**
$title. Should we consider doing the following?

I. Snippet for error similar to record/object.

![1_error_no_snippet](https://user-images.githubusercontent.com/8376983/85197490-def11400-b2fe-11ea-9f2d-db60ce52cfd5.png)

II. An error can be defined as a `distinct error` now, but the `distinct` keyword is not suggested.

`type MyError distinct error<MyErrorDetails>;`

![2_error_no_distinct](https://user-images.githubusercontent.com/8376983/85197723-80c53080-b300-11ea-8bfd-2791a27a5df8.png)
 
III. For a user-defined error type, the name serves as an error constructor. But there are no suggestions for the same atm.

```ballerina
type MyErrorDetails record {|
    int code;
|};

type MyError error<MyErrorDetails>;

public function main() {
    MyError err = MyError("error message", code = 123);
}
```

![3_err_constr](https://user-images.githubusercontent.com/8376983/85197801-1365cf80-b301-11ea-8481-e6b73c5dc71a.png)

IV. When a record is specified as the detail type of a user-defined error, can we suggest the names of the fields in the detail as the named args in the error constructor?

![4_detail_sugg](https://user-images.githubusercontent.com/8376983/85197846-66d81d80-b301-11ea-996e-8d8686b88d5b.png)

**Comment by mohanvive** [comment]
Above improvements are available in the latest VScode plugin. Hence closing the issue.
