### ISSUE TITLE
Parent node should be accessible in some scenarios

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#24410]
**Description:**
I'm currently implementing the formatter and using the tree visitor. 
```import ballerina/io;
public function main() {
    int a = 10;
    int b = 0;
    if (b < 0) {
        io:println("b < 0");
    } else if (b > 0) {
        io:println("b > 0");
    } else {
        io:println("b == 0");
    }
}
```
In the above code block, when we are going to format the elseIf's block node, we need to get its parent node. Since the elseIf node is already modified, there is no way to access its parent node in the current implementation. Without those parent information, we are unable to modify the inner nodes according to the parent indentation.

There should be a way to modify the node without losing the parent node for the formatter implementation.

![image](https://user-images.githubusercontent.com/16335290/85283298-bd349000-b4aa-11ea-9e52-34833d70a38a.png)

![image](https://user-images.githubusercontent.com/16335290/85278317-6cb93480-b4a2-11ea-8874-5c0a181f136d.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@sameerajayasoma

**Comment by SupunS** [comment]
Syntax API now provides a `parent()` method to get the parent.
