### ISSUE TITLE
Incorrect position for `BLangRestArgsExpression` with the new parser

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24415]
**Description:**
$title, when it is specified after other arguments.

**Steps to reproduce:**
For the following snippet 

```ballerina
public function main(int i, boolean b1, boolean b2) {
    boolean[] bArr = [b1, b2];
    bar(i, ...bArr);
}

function bar(@untainted int i, @untainted boolean... b) {
}
```

note the invalid pos for the vararg.
```cmd
error: .::qwe.bal:3:10: tainted value passed to untainted parameter 'b'
```

`3:10` is at the comma after the first argument.

**Related Issues**
https://github.com/ballerina-platform/ballerina-lang/issues/24130

**Affected Versions:**
Swan Lake Preview1

**Comment by SupunS** [comment]
Seems this is fixed in the latest master.
Error is currently gives as:
```
error: .::testMain.bal:3:9: tainted value passed to untainted parameter 'i'
error: .::testMain.bal:3:12: tainted value passed to untainted parameter 'b'
```
