### ISSUE TITLE
Too generic disagnostic error message when var-declr required

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#24439]
**Description:**
Consider following code snippet. Currently the error message provided by the parser is too generic  `invalid expression statement` error. Instead need more intuitive error such as `variable assignment is required` which the old parser / compiler had.

This is a critical requirement for suggesting  code actions such as 'create variable' which solely depends on the diagnostic messages.

```ballerina
function latestVars() {
    1;
    "";
    true;
}
```

**Affected Versions:**
2.0.0

**Comment by SupunS** [comment]
Closing this issue, since this is already captured in https://github.com/ballerina-platform/ballerina-lang/issues/24286
