### ISSUE TITLE
Compiler plugins needs to be run when it is necessary

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#24434]
**Description:**
There are some scenarios that compiler plugins is not needed to compile when the source code is compiled.

**Comment by hasithaa** [comment]
This is fixed from Project API. Hence lowered the priority. But this needs to be addressed in the new design.

**Comment by hasithaa** [comment]
Closing this, since old compiler extension support is deprecated in SL
