### ISSUE TITLE
Need a flag to indicate a packageNode is from the source project

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#24441]
**Description:**
In the following code snippet from the DataMapper compiler plugin we need a way of identifying whether the package nodes we encounter while traversing the AST are from the same source project. The package nodes can be either from the bal files located on the src folder of a particular Ballerina project or from the balos imported by the project.

One solution for the above problem would be to create a flag/function API call in the packageNode to decide whether it is from the source project or from an imported balo file. 

```
    @Override
    public void process(PackageNode packageNode) {
        for (TopLevelNode node : ((BLangPackage) packageNode).topLevelNodes) {
            if (node instanceof BLangTypeDefinition) {
                if ((((BLangTypeDefinition) node).getTypeNode().type.flags & Flags.CLIENT) == Flags.CLIENT) {
                    clientFlag = true;
                    break;
                }
            }
        }

        if (clientFlag) {
            String pkgRoot = ((BLangPackage) packageNode).repos.resolve(((BLangPackage) packageNode).packageID).inputs.
                    get(0).toString();
            projectSourceFolder = pkgRoot.substring(0, pkgRoot.lastIndexOf("/"));
```

**Steps to reproduce:**
N/A

**Affected Versions:**
Ballerina Swan Lake Preview 1

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by rdhananjaya** [comment]
I think this is as same as https://github.com/ballerina-platform/ballerina-lang/issues/24434
