### ISSUE TITLE
Oauth2 introspection claims are not cached.

### ISSUE THREAD

**Issue by menakaj** [ballerina-platform/ballerina-lang#24462]
**Description:**
During the Oauth2 token introspection, only username, and scopes are added to Authentication cache. The claims are not cached. Hence the principal object does not have the claims map when authentication is done via the cache.

In the micro gateway scenario, the clientId is required for authentication. (clientId comes in the introspection response claims) Authentication passes in the first API invocation but fails in subsequent invocations.

https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/oauth2/src/main/ballerina/src/oauth2/inbound_oauth2_provider.bal#L144

**Steps to reproduce:**

**Affected Versions:**
1.2.5-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ldclakmal** [comment]
Fixed with the linked PR. Hence closing the issue.
