### ISSUE TITLE
Check on the possibility of using `Flags.ANONYMOUS` to identify anonymous types when deciding to use the shape for `toString()` instead of the auto-generated name

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24471]
**Description:**
Currently, to identify if a type is anonymous when building the `toString()` representation we check if the name starts with `$`. Need to check on the possibility of using `Flags.ANONYMOUS` to identify anonymous types instead.

We would especially need this when we allow quoted identifiers to have non-alphanumeric characters which will allow a user to define a type with a name starting with `$`.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
