### ISSUE TITLE
When Ballerina.toml changed after lock creation, lock should be updated

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#24483]
**Description:**
When `Ballerina.toml` is changed after the `Ballerina.lock` creation, `Ballerina.lock` file should be updated with the changes done to the `Ballerina.toml`.

**Steps to reproduce:**
1. Build a ballerina project with a dependency module and it will create a `Ballerina.lock` file.
2. Change dependency module in the `Ballerina.toml`.
3. Rebuild the project.
4. `Ballerina.lock` file is not updated with the changes done to the `Ballerina.toml`.

**Affected Versions:**
master

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
No longer valid
