### ISSUE TITLE
Make stream be a subtype of object

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#24539]
Ref: https://github.com/ballerina-platform/ballerina-spec/issues/434

**Comment by grainier** [comment]
Current implementation adheres to the usage of `StreamImplementor<T,C>`[1], and supports empty streams by allowing `new` as a valid constructor for `stream` [2]. Hence, closing the issue.

[1] 
```ballerina
    object {
        public next() returns record {| T value; |}|C;
    }
    | object {
        public next() returns record {| T value; |}|C;
        public close() returns C?;
    }
```
[2] https://github.com/ballerina-platform/ballerina-lang/pull/26259
