### ISSUE TITLE
[Parser] Improve error message for missing typedescs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24549]
Consider the following snippet:
```ballerina
function foo(typedesc<anydata> td = <>) {
    
}
```
Trying to compile the above results in the following error messages:
```
error: pubudu/fizz:0.1.0::main.bal:15:38: missing type desc
error: pubudu/fizz:0.1.0::main.bal:15:39: missing identifier
```
I think the first error message should either say "type descriptor" or "typedesc".

**Comment by SupunS** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/24286

**Comment by SupunS** [comment]
Included this to a single issue where we capture all diagnostic related issues: https://github.com/ballerina-platform/ballerina-lang/issues/24286

Hence closing this one
