### ISSUE TITLE
Invalid static type for type-cast-expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24559]
**Description:**
The spec says

```
type-cast-expr := < type-cast-param > expression
type-cast-param := [annots] type-descriptor | annots
```

Let T be the static type described by type-descriptor, and let TE be the static type of expression. Then the static type of the type-cast-expr is the intersection of T and TE', where TE' is TE with its xml shapes and numeric shapes transformed to take account to the possibility of the implicit conversion and numeric conversion specified in the previous paragraph.

**Steps to reproduce:**
Thus, according to the spec, the following is valid.

```ballerina
boolean b = true;
boolean x = <json> b;
```

But in the implementation, `T` is considered to be the static type.

**Affected Versions:**
slp1

**Comment by MaryamZi** [comment]
See https://github.com/ballerina-platform/ballerina-spec/issues/564

**Comment by lasinicl** [comment]
Will revisit once https://github.com/ballerina-platform/ballerina-lang/issues/24078 is fixed
