### ISSUE TITLE
Multiple worker receive action needs tooling support

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#24561]
**Description:**
The Worker Multiple Receive action #18163 has been fixed at #24556 
This requires tooling support.

**Related Issues:**
#18163

**Suggested Labels:**
Component/LanguageServer, Area/Tooling 

**Suggested Assignees:**
@nadeeshaan

**Comment by nadeeshaan** [comment]
Getting the following when tried the the multiple worker receive.
<img width="889" alt="Screenshot 2021-09-23 at 11 20 38" src="https://user-images.githubusercontent.com/1329674/134460055-aaec52fe-5e46-4127-a608-97864ef5f253.png">

**Comment by IMS94** [comment]
Closing this since the multiple receive action is not yet supported. We can create a new issue when that support is implemented.
```
public function main() {
    worker A {
        1 -> function;
    }

    worker B {
        2 -> function;
    }

    int i = <- {A, B};
}  
```
