### ISSUE TITLE
Getting compiler output from a mid compiler phase for doc generation

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#24578]
**Description:**
Currently the BLangPackage used for doc generation in standard library goes through all the compiler phases(up to codegen).
https://github.com/ballerina-platform/ballerina-lang/blob/a2756b9b7c65eb84acaaa2227272835e80353698/misc/lib-creator/src/main/java/org/ballerinalang/stdlib/utils/GenerateBalo.java#L117

Some unnecessary variables for doc generation are added in the desugar compiler phase. So it is required to get a compiler output before running this phase.

**Steps to reproduce:**

**Affected Versions:**
Swan lake

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment]
Example of some unnecessary variables.
![Screenshot from 2020-07-13 22-36-20](https://user-images.githubusercontent.com/33398983/87385734-6eb37680-c5bc-11ea-8c56-ec00d48d3dcd.png)

**Comment by shehan360** [comment]
Seems like these init functions in the http module are also a result of this.
![Screenshot from 2020-08-18 10-06-20](https://user-images.githubusercontent.com/33398983/90471862-d8cfb600-e13c-11ea-9430-5942bbed79b2.png)

**Comment by pubudu91** [comment]
This issue is because API docs are generated after finishing up the compilation process. I think we'll have to rethink this. In the compiler FE, we were planning on allowing desugaring at any phase. I guess that'll complicate things further for doc generation. Will raise with the rest of the team and see.

**Comment by shehan360** [comment]
Closing as no longer relevant.
