### ISSUE TITLE
XML to json conversion of empty elements is wrong

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#24585]
**Description:**
```ballerina
xml x = xml `<foo><bar>2</bar><car></car></foo>`;
var j = checkpanic jsonutils:fromXML(x);
io:println(j)
```

prints:
```
{"foo":{"bar":"2", "car":"car"}}
```

This output is the converted value of xml `<foo><bar>2</bar><car>car</car></foo>`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Seems to have been fixed for 1.2.5 in https://github.com/ballerina-platform/ballerina-lang/pull/24586.

Tested the following.

```ballerina
import ballerina/io;
import ballerina/jsonutils;

public function main() {
    xml x = xml `<foo><bar>2</bar><car></car></foo>`;
    var j = checkpanic jsonutils:fromXML(x);
    io:println(j);
    io:println(j.toJsonString());
}
```

Output on 1.2.4
```cmd
foo=car= bar=
{"foo":{"car":"", "bar":{}}}
```

Output on 1.2.5 and 1.2.13
```cmd
foo=bar=2 car=
{"foo":{"bar":"2", "car":""}}
```

Output on sl-alpha
```cmd
{"foo":{"bar":"2","car":""}}
{"foo":{"bar":"2", "car":""}}
```
