### ISSUE TITLE
Module loader API rewrite - Make changes to work with the Language Server

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#24597]
**Description:**
$Title
Also need to fix all the failing LS tests.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Will be implemented by project API
