### ISSUE TITLE
All the build cmd options should be configurable through Ballerina.toml

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#24592]
**Description:**
Currently 'observability-included=true' flag can be used in ballerina toml to configure compiler options. We should have the capability to configure all the build command options through Ballerina.toml.

- [x] Work out a design
- [x] Select the options we need to allow configuring 
- [x] Implement the feature

**Comment by azinneera** [comment]
The command validation model has to be revisited and re-designed to match the Project API implementation.

**Comment by azinneera** [comment]
Resolved by #27078
