### ISSUE TITLE
Commented test cases in language server

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#24601]
**Description:**
In the PR #24528 `completionWithinInvocationArgs7` and `completionWithinInvocationArgs7` language server test cases in `FunctionDefinitionCompletionTest` class are commented due to future refactoring.

**Suggested Assignees (optional):**
@nadeeshaan

**Comment by nadeeshaan** [comment]
These test cases have been migrated to a new test suite. Therefore this is no longer valid. Hence closing the issue.
