### ISSUE TITLE
JarResolver related build tool refactor

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#24606]
**Description:**
JarResolver was introduces to resolve all the native dependencies of modules. We need to refactor the other places of the build tasks to use the JarResolver.

- [x] Run Test task as to use the JarResolver 
- [x] Copy Native lib will go away
- [x] Copy module jar task will go away 
- [x] Remove executable jar data holder
- [x] Remove bre/lib loading in RunExecutable task

**Comment by suganyasuven** [comment]
- [ ] CreateExecutableTask has to use the JarResolver
- [ ] Modify createJarTask according to the above changes
- [ ] Add methods to get allTestDependecies and getRuntimeJar in jarResolver
- [ ] Validate balo dependencies during compile task
