### ISSUE TITLE
Use only a single set of threads in a ballerina program

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#24616]
**Description:**
Currently three sets of threads(jballerina-strand-exe) are created during the execution of a ballerina program. During module init, module execution and module stop. There should be only one set of threads created and run throughout the period. 

**Steps to reproduce:**
Profiling a ballerina program

**Affected Versions:**
Swan lake preview

**Comment by riyafa** [comment]
Fixing https://github.com/ballerina-platform/ballerina-lang/issues/23654 will fix this

**Comment by HindujaB** [comment]
Currently, we use two `Scheduler` objects at runtime,
1. To handle `module init`, `module start`, and `main` executions.
2. To handle `module stop` execution

Both of these executions need to be run on separate threads as the `module stop` should be run independently from the other thread (eg. in case of panic etc.). Therefore we can keep the current behavior as it is with a minimum of two threads at runtime. 

Hence, closing this issue.
