### ISSUE TITLE
Class cast exception when try to get the expressions from ServiceDeclarationNode

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24626]
**Description:**
Getting the following exception when try to call the expression API.

```io.ballerinalang.compiler.syntax.tree.ExpressionListItemNode cannot be cast to io.ballerinalang.compiler.syntax.tree.ExpressionNode```

**Steps to reproduce:**
Consider the following source and try to call the expression API for the ServiceDeclarationNode

```
import ballerina/http;

public listener http:Listener l1 = new(9090);

RecordName rec = {};

service tests on new 

type RecordName record {
    http:Listener list = new(9090);
};

function hello() returns @tainted http:Listener {
    return l1;
}
```

**Comment by SupunS** [comment]
Seems this is working on SLP3-SNAPSHOT.

**Comment by nadeeshaan** [comment]
@SupunS will check and update

**Comment by SupunS** [comment]
I will close the issue for now, since this seems to be fixed in the latest code.
Please do reopen if it happens to be otherwise.

**Comment by nadeeshaan** [comment]
According to the latest implementation, this particular context is identified as `ImplicitNewExpressionNode`. This is a proper node where we can access the service and define the completions properly
