### ISSUE TITLE
Support executing a single test function

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#24628]
**Description:**

Running single test cases in the current test framework is not possible. It may be brought about by including groups or disabling tests but this is a cumbersome task.

**Comment by Dilhasha** [comment]
Suggested command:
Ballerina test mod_name test_function_name

Approach: 

- There is no change to the compilation, only selected function gets executed at runtime.
- BeforeSuite, AfterSuite functions will not be run, but beforeEach and afterEach function will run.

**Comment by Dilhasha** [comment]
Updated the docs for executing tests. 
https://github.com/ballerina-platform/ballerina-dev-website/pull/1089
