### ISSUE TITLE
Issue with pos of a start-action

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24641]
**Description:**
With a start-action, say `start func()`, the pos for the function-call-expr (`func()`) seems to be set as the pos of the start-action.

**Steps to reproduce:**
```ballerina
public function main() {
    future<int> s = start func();
}

function func() returns string => "foo";
```

The error is logged as follows:
```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:2:27: incompatible types: expected 'future<int>', found 'future<string>'
```

But the pos should actually be `2:21`, since it is `start func()` itself that evaluates to `future<string>`, not `func()`.

The same behaviour was present with the old parser too.

**Affected Versions:**
slp1

**Comment by SupunS** [comment]
I think this has to be fixed in the AST. Because currently the `start` keyword get converted to a flag, and only the `func()` is preserved. If we consider the position of `func()` that is correct.
