### ISSUE TITLE
Running test cases in parallel

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#24643]
**Description:**
We should investigate the need for running tests in parallel and support if it will be useful.

**Comment by niveathika** [comment]
+1 for the above feature. For instance, if one has independent groups of test cases then we can run them parallelly. Else it will consume so much build time.

**Comment by Thevakumar-Luheerathan** [comment]
Design doc :- https://docs.google.com/document/d/1f9VpdyAXvPNL_jfmQdcAiG_y_POyGVsLmajmvWBX4Uk/edit?usp=sharing

**Comment by Thevakumar-Luheerathan** [comment]
Repo status : https://docs.google.com/spreadsheets/d/1zINoTY9ubpiJA7JDNGKDQsheV15-lMC25-sYa74YYkQ/edit?usp=sharing
