### ISSUE TITLE
vs code "internal error" when debug hello.bal in windows10

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [ballerina-platform/ballerina-lang#24656]
**Description:**

With the following launch.json, vs code "internal error" popup window occurred when starting debug hello.bal.
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ballerina",
            "request": "launch",
            "name": "Ballerina Debug",
            "script": "${file}",
            "networkLogs": true
        },
...
}
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
windows10, vs code 1.46.1
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
This has been already fixed with #24735 and #24745 and the fix with be available with the Swan Lake preview 3 and 1.2.7 releases.

**Comment by starsmall-xiaoqq** [comment]
＞Swan Lake preview 3 and 1.2.7 releases.
Thanks, I am waiting for the extensions of  vscode to become available soon. 
No debugger, I do now know how to develop application with ballerina code although i think it is a great new language.
