### ISSUE TITLE
Informational response codes are not recieved by Ballerina

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#2467]
When a back end server is sending informational response codes as 100, 101 those are not recieved by Ballerina even though the bal program just passes the response to the client

**Comment by riyafa** [comment]
In the case WebSocket protocol switching WebSocket client handles the 101 response correctly

**Comment by pubudu91** [comment]
100-continue scenarios are working in v0.970.2-SNAPSHOT. Hence closing this.
