### ISSUE TITLE
Anonymous object's variable values are incorrectly visible

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#24678]
**Description:**
Anonymous object's variable values are incorrectly visible and some of the grandchild variables are not visible at all.

**Steps to reproduce:**

```
public type AnonPerson record {
    string name;
    int age;
    object {
        public string city;
        public string country;

        public function init(string city, string country) {
            self.city = city;
            self.country = country;
        }

        public function value() returns string {
            return self.city + ", " + self.country;
        }
    } address;
};

public function main() {
    AnonPerson v17_anonObjectVar = {
        name: "John Doe",
        age: 25,
        address: new ("Colombo", "Sri Lanka")
    };
}
```

When we add a debug point at the last line of the main method, the variable values are visible as follows
![image](https://user-images.githubusercontent.com/11292766/87031707-259ca480-c201-11ea-9219-891fda8d98f9.png)

**Identified issues:**

1. Type of v17_anonObjectVar should be object, not record.
2. Type of address should be record, not object.
3. Appropriate value should be shown for address instead of $anonType$0.
4. Child variables of address are not visible.

Above identified issues need to be fixed.

**Comment by NipunaRanasinghe** [comment]
Closing since anonymous objects are not supported with the latest language changes.
