### ISSUE TITLE
HTTP 307 temporary redirection fails when invoking POST method

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#24681]
**Description:**
On Ballerina HTTP client when a POST request is invoked if the server responds with a HTTP 307 status code, the redirection does not happen from the HTTP client. 

**Steps to reproduce:**
This can be reproduced using the [BBE on redirects](https://ballerina.io/learn/by-example/http-redirects.html).

**Affected Versions:**
Ballerina Swan Lake Preview 1

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by chamil321** [comment]
Current redirect logic checkes for `HTTP_GET` and `HTTP_HEAD` verbs to allow redirection for status code 307. But the [spec](https://tools.ietf.org/html/rfc7231#section-6.4.7) specifies that

> A POST request should be repeated using another POST request, that it does not allow changing the request method from POST to GET

Hence this issue is a bug which is a HTTP spec deviation.
