### ISSUE TITLE
findToken API throws Illegal argument exception

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24694]
**Description:**
Consider the following code snippet

```
import ls_org1/module1;


function testFunction() {
}

public type TestRecord1 record {
    int field1 = 1;
    int field2 = 2;
};

<cursor>
```

**Steps to reproduce:**
Try to invoke the `findToken` API given the position as the position of the cursor as shown. Doing that will throw `java.lang.IllegalArgumentException`

**Affected Versions:**
Swan Lake Preview1

**Comment by sameerajayasoma** [comment]
This is fixed with the following PR. 
https://github.com/ballerina-platform/ballerina-lang/pull/24965
