### ISSUE TITLE
[VS Code] [Debugger] Internal error when running a ballerina program in debug mode

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#24716]
**Description:**
An Internal Error is occurring when running a ballerina program in debug mode using VS Code. This is not reproducible in IntelliJ IDEA.

**Steps to reproduce:**
Run the following ballerina code in debug mode using the VS Code. Before running, add a breakpoint inside main method.
```
import ballerina/io;

 public function main() {
     io:println("Hello world!!!!");
 }
```
The following error message will be popped.
"Internal error."

![image](https://user-images.githubusercontent.com/11292766/87379820-bfbc6e00-c5ae-11ea-857c-b27d4717c26a.png)

**Affected Versions:**
jBallerina 1.2.6
Language specification 2020R1
Ballerina tool 0.8.5

**Comment by scheung38** [comment]
Debug mode also not working in IDEA too.
