### ISSUE TITLE
getCookies() in http throws 'IndexOutOfRange' for cookies with no value 

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#24724]
**Description:**
When there is no value for cookie key, the `getCookies()` function throws `IndexOutOfRange`.
sample cookie:
```
key=;
```
or
```
key
```
Error:
```
error: {ballerina/lang.array}IndexOutOfRange message=array index out of range: index: 1, size: 1
        at ballerina.http.1_0_0.cookie.cookie:parseCookieHeader(cookie/cookie.bal:233)
           ballerina.http.1_0_0.Request:getCookies(http_request.bal:565)
```

**Steps to reproduce:**
use `getCookies()` function to read cookie header with one of the above cookies.

**Affected Versions:**
Swan Lake Preview 1

**Comment by chamil321** [comment]
As per the [cookie spec](https://tools.ietf.org/html/rfc6265#section-4.1.1), the syntax is as follows

> set-cookie-header = "Set-Cookie:" SP set-cookie-string
 set-cookie-string = cookie-pair *( ";" SP cookie-av )
 cookie-pair       = cookie-name "=" cookie-value
 cookie-name       = token
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash

Hence the `key=;` is a valid use case. therefore it should be handled by the cookie parser
