### ISSUE TITLE
Users cannot call rollback after a commit action fails.

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#24736]
Consider the following code

```ballerina
transaction {
    var result = commit;
    if (var is error) {
      rollback;
    }
}
```

This code should compile. But fails. Also the following BBEs need to be updated accordingly with these fixes
https://ballerina.io/swan-lake/learn/by-example/local-transactions.html
https://ballerina.io/swan-lake/learn/by-example/local-transactions-with-handlers.html

Right now, the result from the commit is not checked in these BBEs.

**Comment by pcnfernando** [comment]
As clarified (ref: https://github.com/ballerina-platform/ballerina-spec/issues/569), according to spec, regardless of the result of the commit-action the strand is not in transaction mode. Hence, the compilation failure is expected.
