### ISSUE TITLE
Interpretation of http 509 "Bandwidth Limit is Exceeded" in Ballerina

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#2474]
This is to query on how $subject is supported in Ballerina. In a case where such a status code reaches ballerina, ideally it should handle it as per the orginial intended manner. But currently when 509 reaches ballerina, the code is interpreted as a "server-error".

**Comment by shafreenAnfar** [comment]
IMO, that is okay. Because in ballerina level there is nothing much we can do.

**Comment by riyafa** [comment]
This is not a very standard status code and there's no requirement in the [http spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1) to "understand the meaning" all the status codes that is available. The requirement is mainly to "understand the class of any status code, as indicated by the first digit, and treat any unrecognized response as being equivalent to the x00 status code of that class". We support most of the standard codes in the spec and also some more and understand the classes of the status code correctly. Currently 509 being understood as "server-error" is quite acceptable.
