### ISSUE TITLE
Enable tests cases with functional/error binding patterns

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24755]
**Description:**

Currently functional/error binding patterns are not properly supported in the compiler. 
Below are a list of tests disabled due to usage of functional/error binding patterns:

- Langlib-tests
  - LangLibErrorTest.testErrorDestructureWithCause
  - ForeachErrorBindingPatternsTests.testArrayWithErrors
  - ForeachErrorBindingPatternsTests.testMapWithErrors
  - ForeachErrorBindingPatternsTests.testNegativeForEachWithErrors
- JBallerina-unit-tests
  - ErrorVariableReferenceTest
  - AssignStmtTest
  - ErrorVariableDefinitionTest
  - LetExpressionTest.testLetExpressionErrorBindingSimple
  - LetExpressionTest.testLetExpressionErrorBindingVar
  - LetExpressionTest.testLetExpressionRecordConstrainedErrorBinding

**Comment by hasithaa** [comment]
Most of the test cases have outdated semantics. This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
