### ISSUE TITLE
Incorrect position is given for an invalid node

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24765]
**Description:**

Sample:
```ballerina
private function foo() {
}
```

The compiler error for the above is:
```
error: .::testMain.bal:1:9: invalid token 'private'
```

Note the column-position is given as `9`, where the actual position of the invalid token is `1`. This is the position of the valid node to which the invalid-node-minutiae is attached.

VSCode shows the error like this:

<img width="450" alt="Screenshot 2020-07-15 at 18 37 17" src="https://user-images.githubusercontent.com/7834839/87548651-6ba6ac00-c6ca-11ea-8936-4c5340ff4e20.png">

---
Currently below tests are disabled due to this (in JBallerina-unit-tests)
- FunctionSignatureInBaloTest.testNegativeFunctionInvocations
- FunctionSignatureNegativeTest
- ClientObjectTest.testRemoteBasicsNegative
- ServiceTest.testServiceBasicsNegative
- WorkerFailTest.invalidUsagesOfDefault

**Comment by xlight05** [comment]
Please note that this issue exists in Toml Parser as well.

**Comment by lochana-chathura** [comment]
@xlight05 shall we create a separate issue to do the same for toml parser?
