### ISSUE TITLE
Process application/x-www-form-urlencoded request 

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#2476]
Currently when $subject is sent to a ballerina service, it's interpreted as it is. There is very limited operations on such data and it's hard to process those with the existing functions. Hence there should be a way to automatically convert such requests to readable and processable formats.
![x-url-form](https://cloud.githubusercontent.com/assets/15624590/26797307/1e9631d8-4a4a-11e7-8fda-cf91a58ec648.png)

**Comment by shafreenAnfar** [comment]
We provide a function to get a map.
