### ISSUE TITLE
Move NATS module from ballerina-lang

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#24801]
**Description:**
$title

**Comment by aashikam** [comment]
Repo: https://github.com/ballerina-platform/module-ballerinax-nats

**Comment by BuddhiWathsala** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/21313

**Comment by aashikam** [comment]
https://github.com/ballerina-platform/module-ballerinax-nats/pull/1
