### ISSUE TITLE
Move file module to a separate repo

### ISSUE THREAD

**Issue by ThishaniLucas** [ballerina-platform/ballerina-lang#24803]
**Description:**
This is a part of Standard Library Repo migration

Based on other dependencies: https://thisaruguruge.github.io/ballerina_dependencies/

**Comment by daneshk** [comment]
We couldn't remove this repo from ballerina-lang, since our HTTP module depends on this module. We have to hold this effort till HTTP module move out

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by ThishaniLucas** [comment]
Closed with https://github.com/ballerina-platform/module-ballerina-file/pull/1 and https://github.com/ballerina-platform/ballerina-lang/pull/25500
