### ISSUE TITLE
No balo tests for object sybtyping 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#24825]
**Description:**
We don't seem to be having balo tests for object subtyping, but we need them since subtyping depends on whether or not the objects are from the same module.

Some tests (for objects in different modules with fields with module-level visibility) will be added when fixing https://github.com/ballerina-platform/ballerina-lang/issues/24752. But, need to verify and add tests for other scenarios.

**Comment by MaryamZi** [comment]
There seem to be some tests in `org.ballerinalang.test.jvm.ObjectSubtypingTest`. Need to validate if all the scenarios are covered.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
