### ISSUE TITLE
Locally available distribution list is not properly sorted in dist list cmd output

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#24826]
**Description:**
$subject. Refer the image below.

Also it will be more clear if we can have channel seperation for `Distributions available locally:` section as well. (Similar to `Distributions available remotely:` section)

<img width="508" alt="image" src="https://user-images.githubusercontent.com/16300038/87847090-bc005280-c8f2-11ea-934c-f4f5d145b286.png">

**Affected Versions:**
Ballerina Swan Lake Preview 2
**OS, DB, other environment details and versions:**

**Comment by hevayo** [comment]
IMO having the local dist separated for channels will complicate the output. Instead we can simply sort it based on the release dates and channel.
