### ISSUE TITLE
Adding `@strand` annotation in workers seems to mess up line numbers

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#24837]
**Description:**
In workers, adding `@strand` annotation seems to mess up line numbers. Commenting out the `@strand` annotation, fixes the line number. This is reflected in Observability data, IDE as well.

**Steps to reproduce:**
1. Create a project and add the following code to it.
   ```ballerina
   import ballerina/io;
   
   public function main() {
       runWorker();
   }
   
   function runWorker() {
       worker w1 {
           io:println("Hello from Worker");
       }
       @strand {
           thread: "any"
       }
       wait w1;
   
       // Test panic to check positions
       error e = error("Test Error");
       panic e;
   }
   ```
2. Build and run the project and check the stack trace in the output.
   ```
   Hello from Worker
   error: Test Error
   	at nadun.temp.0_1_0:runWorker(worker.bal:16)
   	   nadun.temp.0_1_0:main(worker.bal:4)
   ```
   Ideally, the line 16 printed in the stack trace should be line 17.
3. Comment out the `@strand` annotation without removing the code and the line number in the stack trace becomes 17 again.

**Affected Versions:**
Ballerina Swan Lake Preview 2

**OS, DB, other environment details and versions:**
Ubuntu 18

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by MaryamZi** [comment]
The `@strand` annotation is only allowed on named worker declarations and start actions. slp4 seems to have fixed this, disallowing `@strand` on wait actions.

The original example results in an error now.
```
annotations attached to expression
```

After changing the source as follows
```ballerina
import ballerina/io;

public function main() {
    runWorker();
}

function runWorker() {
    @strand {
        thread: "any"
    }
    worker w1 {
        io:println("Hello from Worker");
    }
    wait w1;

    // Test panic to check positions
    error e = error("Test Error");
    panic e;
}
```
the line number is as expected.

```
Hello from Worker
error: Test Error
        at maryam.proj.0_1_0:runWorker(main.bal:17)
           maryam.proj.0_1_0:main(main.bal:4)
```
