### ISSUE TITLE
Evaluate the need for mock service skeletons for testing

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#24847]
**Description:**

We a set of functions in the test module [1] to generate a service skeleton using a swagger file (OpenAPI definition). This has been created for integration tests, where the tester can spin up a mock service using the swagger file and test the integration functionalities of a module.

We need to re-evaluate the use cases and check how the mocking API can be improved to facilitate this feature.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/635a5c1e5596a022a7e10fb8b0343c190d282165/misc/testerina/modules/testerina-core/src/main/ballerina/src/test/natives.bal

**Comment by Dilhasha** [comment]
This feature is not required anymore.
