### ISSUE TITLE
Add support for handling syntactically incorrect programs in the compiler phases

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24840]
The current compiler phases have been written under the assumption that it will always be working on an AST built off a syntactically correct program. However, with the new parser, syntactically incorrect programs can also go through the compiler phases up to Desugar. Therefore, need to modify the compiler to handle these type of programs as well.

**Comment by pubudu91** [comment]
Issues that fall under this:
#24846
#24893 
#24839 
#24886 
#24889

**Comment by hasithaa** [comment]
Closing since all mentioned issued are closed.
