### ISSUE TITLE
Ballerina Http/2 service does not respond to the request made from the browser

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#24845]
**Description:**
When there is a secure listener is available with the version http/2, all the invocations from the browser fails. But when it is invoked from curl with the option --http1.1 it works with no issue. 

Further information can be found on https://github.com/wso2/product-microgateway/issues/1302

**Steps to reproduce:**
Implement and build the code in  https://ballerina.io/learn/by-example/https-listener.html with http2 

**Affected Versions:**
ballerina 1.1.5, 1.2.6

**OS, DB, other environment details and versions:**
MacOS Mojave
Browser: Chrome, Safari

**Related Issues (optional):**

https://github.com/wso2/product-microgateway/issues/1302

**Suggested Labels (optional):**

Bug

**Suggested Assignees (optional):**

@chamil321 , @shafreenAnfar , @daneshk

**Comment by Bhashinee** [comment]
Tried the scenario with chrome and firefox. The issue seemed to be with the ciphers. When connecting with HTTP 2, browsers only accept a filtered set of ciphers. So when trying to make an HTTPS connection over HTTP2 with browsers, you should configure an acceptable cipher.

I tried with "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" configured as the cipher and the connection was successfully made. 

Ballerina service
```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/io;

http:ListenerConfiguration helloWorldEPConfig = {
httpVersion: "2.0",
    secureSocket: {
        keyStore: {
            path: "/home/bhashinee/ballerina_home/bre/security/ballerinaKeystore.p12",
            password: "ballerina"
        },
        ciphers: ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]
    }
};

listener http:Listener helloWorldEP = new (9097, config = helloWorldEPConfig);

@http:ServiceConfig {
    basePath: "/hello"
}
service helloWorld on helloWorldEP {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/"
    }
    resource function sayHello(http:Caller caller, http:Request req) {
        http:Response res = new;
        res.setHeader("content-encoding", "gzip");
        res.setPayload("Hello World");
        var response = caller->respond(res);
        if (response is error) {
            log:printError("Error in responding ", response);
        }
    }
}
```

Chrome output

![image](https://user-images.githubusercontent.com/11239305/88661734-a0692900-d0f6-11ea-9555-d061c66be556.png)

However, there was a problem with content-encoding in HTTP2. Without setting the ```content-encoding``` header, it was not working. 
Created an issue to track this: https://github.com/ballerina-platform/ballerina-lang/issues/24977

@VirajSalaka Can you also check this?
