### ISSUE TITLE
Ballerina Tool gRPC Command Has Incorrect Mode Option in Help

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#24871]
Currently, when we type "ballerina grpc --help" we get the following:

```bash
$ ballerina grpc --help
NAME
       ballerina-grpc - Generate Ballerina sources for the given protobuf
                        definition

SYNOPSIS
       ballerina grpc --input <proto-file-path> [--output <path>]
                        [--mode client | server | proxy]
```

The --mode here mentions "server", but this should be "service", where it now silently executes the default behavior if "server" is given. 

version: slp2

**Comment by daneshk** [comment]
Fix is already merged to 1.2.x and master branch. hence closing the issue
