### ISSUE TITLE
Typed-binding-patterns are not allowed for module level variable declarations

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24878]
**Description:**

```ballerina
var [a , b] = [4, 5];   // not allowed.  ----(1)

function foo() {
    var [x , y] = [4, 5];   // allowed
}
```
(1) is not allowed by the parser in the old ANTLR4 based parser. 

With the new parser, even-though it can be parsed, the AST does not support holding a typed-binding-patetrn in the module var decl.

Related section in spec: https://ballerina.io/ballerina-spec/spec.html#module-init-var-decl

**Related Issues:**
- #24473
- #24833
- #24367

**Comment by rdulmina** [comment]
Related issue #25125
