### ISSUE TITLE
[Parser] Error for incorrect expression statement

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24897]
Consider the following program:
```ballerina
public function main() {
    new Person("Pubudu");
}

type Person object {
    string name;

    function init(string name) {
        self.name = name;
    }
};
```
The following errors are given for the above:
```
error: .::test2.bal:3:5: invalid expression statement
error: .::test2.bal:3:5: variable assignment is required
```
The first error is a parser error. The concern here is "expression statement" is an internal construct of the compiler implementation. Therefore should we be using such terms in the compiler/parser error messages? Wouldn't it be better to phrase it as something like `'new Person()' is not a statement`, or `expected a statement, found an expression: 'new Person()'`?

**Comment by SupunS** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/24439
