### ISSUE TITLE
Taint Analysis not working correctly for service and object functions

### ISSUE THREAD

**Issue by TruthNZ** [ballerina-platform/ballerina-lang#24902]
**Description:**
Taint Analysis of functions declared inside a service or object is not working, and results in a compile error "tainted value passed to untainted parameter 'input'".
See example below:

**Steps to reproduce:**
```
import ballerina/http;
import ballerina/io;

listener http:Listener httpListener = new(8080);

@http:ServiceConfig {
    basePath: "/"
}
service interface on httpListener {

    @http:ResourceConfig {
        methods:["GET"],
        path:"/taintTest/{stringInput}",
        produces: ["application/json", "application/json; charset=utf-8"]
    }
    resource function taintTest(http:Caller caller, http:Request req, string stringInput) returns error? {
        string sanitisedInput = self.sanitise(stringInput);
        self.taintCheck(sanitisedInput);
        _ = check caller->accepted();
    }

    function taintCheck(@untainted string input) {
        io:println("Untainted Input: " + input);
    }

    function sanitise(string input) returns @untainted string {
        return input;
    }
}
```
error: main.bal:18:25: tainted value passed to untainted parameter 'input'

**Affected Versions:**
1.2.6

**Suggested Labels (optional):**
Component/Compiler, Type/bug

**Comment by rdhananjaya** [comment]
Fixed in master branch, will be available in Swanlake alpha release.
Please note after alpha taint checking is optional and need to enable using `--taint-check` CLI flag or via Ballerina.toml by providing `taintCheck = true` as a build option.
