### ISSUE TITLE
Execute SQL StoredProcedure exception thrown

### ISSUE THREAD

**Issue by georgecookeIW** [ballerina-platform/ballerina-lang#24903]
**Description:**
Ballerina code fails to get the resultset for the select statement present after the insert statement in the SQL server stored procedure.

Ballerina code that executes the storedproc breaks while getting the resultAndNoUpdateCount for the statements after the first statement in the storedprocedure

Line 203 – executeStoredProc() https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/CallStatement.java
```
resultAndNoUpdateCount = stmt.getMoreResults(Statement.KEEP_CURRENT_RESULT);
```
throws the “com.microsoft.sqlserver.jdbc.SQLServerException: This operation is not supported.”
 
Driver Code: https://github.com/microsoft/mssql-jdbc/blob/v8.2.2/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java
```
@Override
public final boolean getMoreResults(int mode) throws SQLException {
    if (loggerExternal.isLoggable(java.util.logging.Level.FINER))
    loggerExternal.entering(getClassNameLogging(), "getMoreResults", mode);
    checkClosed();
    if (KEEP_CURRENT_RESULT == mode) {
        SQLServerException.throwNotSupportedException(connection, this);
    }
}
```

**Suggested Fix:**
Line 203 – executeStoredProc() https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/jdbc/src/main/java/org/ballerinax/jdbc/statement/CallStatement.java
```
resultAndNoUpdateCount = stmt.getMoreResults();
```

**Steps to reproduce:**
The following repository contains the files to reproduce (https://github.com/georgecookeIW/ballerinasqlissue); the database script, ballerina code, jdbc driver used and toml file.

1. apply database script to MSSQL instance
2. using the TOML, main.bal and jdbc driver; run the Ballerina code attached.

**Affected Versions:**
Ballerina Version – 1.2.6

**OS, DB, other environment details and versions:**
Ballerina Version – 1.2.6
Java Version – 8
Database Server – MSSQL Server

**Comment by georgecookeIW** [comment]
Apologies; here are the mentioned attached files: https://github.com/ballerina-platform/ballerina-lang/issues/24903

**Comment by niveathika** [comment]
@georgecookeIW Tank you for reporting this. This will be fixed with the PR https://github.com/ballerina-platform/ballerina-lang/pull/25120

Please note, while fixing this issue I came across a design constraint where we cannot return multiple result sets for MSSQL procedure call. Please refer [discussion](https://groups.google.com/g/ballerina-dev/c/ur8sekIxPqg/m/znAW22tmBgAJ) for more details. This will be addressed in the connector depended on Ballerina Swan Lake version.
