### ISSUE TITLE
Invalid Token is return from findToken API

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24905]
**Description:**
Consider the following snippets,

```
import ballerina/http;
import ballerina/lang.'object as lang;

// http:<cursor>
// http:L<cursor>
// http<cursor>:L


```

**Steps to reproduce:**
Consider each of the commented lines alone and for each of the cases, we do not get a single token such as `:`, `http`.

**Comment by sameerajayasoma** [comment]
I am working on a fix for this issue. The solution is to return the EOF token.

**Comment by SupunS** [comment]
@nadeeshaan can we close this?

**Comment by nadeeshaan** [comment]
For each of the cases added there, I get the EOF as the token. When we get the parent of the token, we get module part node. In that case don't have a direct way to get the ModuleVariableDeclarationNode.

**Comment by sameerajayasoma** [comment]
The behavior of the API is correct. Do we need to rethink how we use the API? 

The case `// http<cursor>:L` gives the correct token, which is the `:`. As you said, in the first two cases, you are getting the EOF token.

**Comment by nadeeshaan** [comment]
@sameerajayasoma Yes, I think we might need to rethink the API usage. Currently what we are doing is, trying to find the node at the given cursor position and that particular search starts from the token we found at this position. We get the token and goes up the parent ladder. Currently we are trying some approaches to achieve these particular cases.

**Comment by sameerajayasoma** [comment]
Can we close this issue in that case?

**Comment by nadeeshaan** [comment]
Closing the issue since we need to rectify the API usage.
