### ISSUE TITLE
Change the Titles of All Modules in API Docs to Denote the GitHub Org

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24914]
**Description:**
We need to change the titles of all the modules in the API Docs to denote the GitHub org (i.e., whether it is "ballerina" or "ballerinax").

<img width="1680" alt="Screenshot 2020-07-23 at 13 26 40" src="https://user-images.githubusercontent.com/11707273/88263821-488e8480-cce8-11ea-9653-dd8a70cdf810.png">

For example, they should be:

- Module: ballerina/auth
- Module: ballerinax/docker

This should be done in both 1.2.x & Swan Lake releases.

**Related Issues (optional):**

- https://github.com/ballerina-platform/ballerina-lang/issues/24908
- https://github.com/ballerina-platform/ballerina-dev-website/issues/1097

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment]
Closing as this issue is fixed.
