### ISSUE TITLE
cannot debug in vs code

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [ballerina-platform/ballerina-lang#24921]
**Description:**

With a simple hello-world ballerina file and  the default launch.json, the "internal error" pop up window occurred.
The problem can be regenerated in multiple windows 10 machines.
The  launch.json is :
{
   "version": "0.2.0",
    "configurations": [
        {
            "type": "ballerina",
            "request": "launch",
            "name": "Ballerina Debug",
            "script": "${file}",
            "networkLogs": true
        },
      .....
    ]
}

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    
windows 10, vscode 1.46.1
**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing as this has been already fixed with #24735 and #24745.
