### ISSUE TITLE
Compilation differences found in tests between `ballerina build` and `ballerina test` commands

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-lang#24957]
**Description:**
There are differences when compilation when running tests with `ballerina build -a` and `ballerina test -a` followed by building with the project with gradle.

**Steps to reproduce:**
1. Checkout https://github.com/ballerina-platform/module-ballerinax-aws.ses
2. Build the project with `./gradlew clean build`. It will build and run tests correctly.
3. Then go to <module_home>/ses-ballerina directory and execute `ballerina test -a`. It will successfully run tests without any issue.
4. Now from the same directory location execute `ballerina build -a`. It will build successfully but fail the tests due to AWS Signature failure.
This is due to the line in https://github.com/ballerina-platform/module-ballerinax-aws.ses/blob/534cff6808bdc6a70f142804e90c3150f493a083/ses-ballerina/src/ses/ses.bal#L425 the character `\n` in variable `canonicalRequest` is not correctly converted to the newline character when that is called in line 427.

**Comment by azinneera** [comment]
Resolved by #24964
