### ISSUE TITLE
Invalid token at cursor is captured

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24961]
**Description:**
Consider the following source snippet,

```
import ballerina/http;
function testConditionFunction() {
    string|boolean test = "hello";
    
    if (test is http:<cursor>) {
        
    }
}
```

In the above cursor position, when we call the findToken API, it returns the `(`. Instead, is it possible to get the `:` token, since the user's writing pattern need to prioritise.

**Affected Versions:**
Swan Lake Preview3 at least

**Comment by sameerajayasoma** [comment]
Here is the same example that you've used without the curser marker. 
```
import ballerina/http;
function testConditionFunction() {
    string|boolean test = "hello";
    
    if (test is http:) {
        
    }
}
```
As you can see, the curser at the `)` token and from the syntax tree point of view, it is not correct to give the `:` token.
