### ISSUE TITLE
Unable to use external ballerina stdlibs that are not available in central 

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#24975]
**Description:**
We have set of stdlibs that are dependent on each other. For example, the `ballerina/jwt` and `ballerina/websub` stdlibs use `ballerina/encoding` as a dependency.

During the development time, we are not relying on released stdlibs, and instead, we are using `-SNAPSHOT` versions pushed to GitHub packages. For example, when we use `encoding` version `1.0.1-SNAPSHOT` [1] that not available in Ballerina central, the JWT module fails with the following error.

```
> Task :jwt-ballerina:ballerinaBuild
Compiling source
        ballerina/jwt:1.0.1
error creating directory for balo file
error: ballerina/jwt:1.0.1::jwt_issuer.bal:18:1: cannot resolve module 'ballerina/encoding'
error creating directory for balo file
error: ballerina/jwt:1.0.1::jwt_validator.bal:19:1: cannot resolve module 'ballerina/encoding'
error creating directory for balo file
error: ballerina/jwt:1.0.1::tests/unit-tests/jwt-issuer-and-validator-test.bal:18:1: cannot resolve module 'ballerina/encoding'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:92:54: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:92:54: undefined function 'encodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:100:54: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:100:54: undefined function 'encodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:108:54: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:108:54: undefined function 'encodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:167:29: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:167:29: undefined function 'encodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:215:12: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_issuer.bal:215:12: undefined function 'encodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_validator.bal:141:27: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_validator.bal:141:27: undefined function 'decodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_validator.bal:161:28: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_validator.bal:161:28: undefined function 'decodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_validator.bal:181:12: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_validator.bal:181:12: unknown type 'Error'
error: ballerina/jwt:1.0.1::jwt_validator.bal:181:39: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_validator.bal:181:39: undefined function 'decodeBase64Url'
error: ballerina/jwt:1.0.1::jwt_validator.bal:182:22: undefined module 'encoding'
error: ballerina/jwt:1.0.1::jwt_validator.bal:182:22: unknown type 'Error'
.....

```

[1] https://github.com/ballerina-platform/module-ballerina-encoding/packages/286810
[2] https://github.com/ballerina-platform/module-ballerina-jwt/blob/b07bfbbcb0ce0589f7b8c6aa377158cb2fc29346/gradle.properties#L5

**Note that**, when I use `--offline` build it successfully builds.

**Affected Versions:**
- ballerina/encoding 1.0.1-SNAPSHOT
- ballerina/jwt 1.0.1-SNAPSHOT
- ballerina-lang 2.0.0-Preview3-SNAPSHOT

**Comment by BuddhiWathsala** [comment]
Further, check this log [3]. Even though I specified to use `ballerina/encoding: 1.0.1-SNAPSHOT` version, it pulled `ballerina/encoding: 1.0.0` version from ballerina central and built.

[3] https://github.com/ballerina-platform/module-ballerina-jwt/runs/918024268

**Comment by ldclakmal** [comment]
Please note that, the `--offline` flag no longer support with `Ballerina 2.0.0-Preview4-SNAPSHOT`.

**Comment by niveathika** [comment]
@hevayo Noticed when we marked the versions as not SNAPSHOTS too. For instance, even if the pack contains a higher version of socket 0.6.8. However, this still resolves for 0.6.7 which is in the BC. I have to lock the versions using toml file. 

However, if a user wants to run just a bl file this will be a blocker.

**Comment by hevayo** [comment]
@niveathika for single bal files also you can specify the version inline `import ballerina/jwt version 1.0.1` anyway this has to be resolved.

**Comment by niveathika** [comment]
@hevayo Seems the latest distribution builds are passing successfully without mentioning version. However, I think its best we verify the behaviour before SLP$.

**Comment by hevayo** [comment]
How can we test this if we build the distribution will it contain those updated modules ?

**Comment by niveathika** [comment]
Yes. As of now, the distribution packs the latest SNAPSHOT versions.

**Comment by hevayo** [comment]
Can we try with the local repository support we have available since slalph3 ?

**Comment by BuddhiWathsala** [comment]
Since the current stdlibs are using intermediate versions which are not available in central, it seems this issue is fixed. Further, all the stdlibs currently use specific stdlib dependencies specified in the `Dependency.toml`.
