### ISSUE TITLE
Support soft assertions in Testerina

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#24976]
**Description:**

In the current Testerina test framework, we only support hard assertions. We need to support soft assertions as well. That is test function should be able to proceed with an assertion failure and throw the assertion exceptions at the end of the test function. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
We can achieve this using `trap`. See the example below:
```bal
@test:Config {}
function testFuntion() returns error? {
    never|error var1 = trap test:assertFail();
    io:println("message after assert fail statement");
    return var1;
}
```
