### ISSUE TITLE
Broken Links in the "Lang.Query" Module in Swan Lake API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24982]
**Description:**
The broken links below can be identified in the "lang.query" module in Swan Lake API Docs[1] when the link checker [2] is run.

<img width="1086" alt="Screenshot 2020-07-28 at 18 09 52" src="https://user-images.githubusercontent.com/11707273/88666379-9f87c580-d0fd-11ea-8304-2e6a8ffa4689.png">
<img width="1089" alt="Screenshot 2020-07-28 at 18 10 01" src="https://user-images.githubusercontent.com/11707273/88666400-a6163d00-d0fd-11ea-8bbf-8e2414717709.png">

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.query/index.html
[2] https://www.brokenlinkcheck.com/broken-links.php#status

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by grainier** [comment]
Fix require: https://github.com/ballerina-platform/ballerina-lang/issues/25069

**Comment by grainier** [comment]
With above fix(#25069), Since `Lang.Query` is an internal module, it won't be visible in API docs.
