### ISSUE TITLE
Broken Links in the Deployment Modules in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24987]
**Description:**
The links below can be identified as broken when we run the link checker[1].

<img width="1080" alt="Screenshot 2020-07-28 at 18 28 03" src="https://user-images.githubusercontent.com/11707273/88668397-305fa080-d100-11ea-861a-b332e9b9645a.png">
<img width="1084" alt="Screenshot 2020-07-28 at 18 28 39" src="https://user-images.githubusercontent.com/11707273/88668403-348bbe00-d100-11ea-99fe-ac7943de7c8d.png">

[1] https://www.brokenlinkcheck.com/broken-links.php#status
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
I tested generating API docs for `docker` module with slp2 and slp3. Following are the files in `target/apidocs/docker`.
```
target/apidocs/docker
├── annotations.html
├── docker.json
├── index.html
├── records
│   ├── DockerConfiguration.html
│   ├── FileConfig.html
│   └── FileConfigs.html
└── search.json
```

When I build with slp1, I get the following files
```
target/apidocs/docker
├── annotations.html
├── docker.json
├── index.html
├── records
│   ├── DockerConfiguration.html
│   ├── ExposeConfig.html
│   ├── FileConfig.html
│   └── FileConfigs.html
└── search.json
```

It seems with slp2 and slp3 is dropping `ExposeConfig.html` file with doc command.

**Comment by hemikak** [comment]
The generated API docs also gives an invalid url for the following link:

<img width="382" alt="Screenshot 2020-08-25 at 22 04 34" src="https://user-images.githubusercontent.com/4398820/91202234-22ad3300-e71f-11ea-85dc-3e7fbe7405ec.png">

**Comment by hemikak** [comment]
Please merge the following to fix the missing files except for 66.
https://github.com/ballerina-platform/module-ballerina-docker/pull/481
https://github.com/ballerina-platform/module-ballerina-kubernetes/pull/605
https://github.com/ballerina-platform/module-ballerina-kubernetes/pull/606

**Comment by praneesha** [comment]
Merged the above PRs and created an issue[1] to fix the "ExposeConfig" (66) broken link.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/25417
