### ISSUE TITLE
Broken Link in the "lang.transaction" Module in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24990]
**Description:**
The "error?" link[1] below is fixed in the "lang.transaction" module in API Docs[2].

<img width="1081" alt="Screenshot 2020-07-28 at 20 14 32" src="https://user-images.githubusercontent.com/11707273/88681238-fb0e7f00-d10e-11ea-935d-c0e312172441.png">

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/null/types.html#error?
[2] https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.transaction/functions.html

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Should [3] and [4] generate docs, they look like module init functions, even if they are, why do we have 2 modules init functions.

[3] https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.transaction/functions.html#ballerina/lang.transaction:0.0.1.%3Cinit%3E0
[4] https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.transaction/functions.html#ballerina/lang.transaction:0.0.1.%3Cinit%3E1

**Comment by mohanvive** [comment]
@rdhananjaya We'll check this issue.

**Comment by mohanvive** [comment]
There are two objects; seems like inits are belongs to them.

**Comment by praneesha** [comment]
Reopening as the issue still exists in the Swan Lake version[1].

**Link checker broken link result:**

<img width="1084" alt="Screenshot 2020-08-16 at 20 19 36" src="https://user-images.githubusercontent.com/11707273/90337109-f8ac9000-dffd-11ea-8f7d-c3c5db9f1478.png">

**Broken links:**

<img width="1676" alt="Screenshot 2020-08-16 at 20 19 50" src="https://user-images.githubusercontent.com/11707273/90337124-17128b80-dffe-11ea-923d-7e2564f43e13.png">

Maybe, the broken link [2] should be directed to [3].

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.transaction/functions.html
[2] https://ballerina.io/swan-lake/learn/api-docs/ballerina/null/types.html#error?
[3] https://ballerina.io/swan-lake/learn/api-docs/ballerina/lang.transaction/types.html#Error

**Comment by praneesha** [comment]
This is what it looks when API docs are generated with the latest lang updates.

![lang-transaction-module](https://user-images.githubusercontent.com/11707273/90338221-a7a09a00-e005-11ea-9ee5-695c0c615622.png)

**Comment by grainier** [comment]
@hevayo, @shehan360 We have removed all the unnecessary public constructs from `lang.transaction` module. However, there's two inits (ballerina/lang.transaction:0.0.1.<init>0, ballerina/lang.transaction:0.0.1.<init>1) being appeared in under functions. Any idea why this can happen?

**Comment by shehan360** [comment]
@grainier There seems to be two init functions in the BLangPackage.
![Screenshot from 2020-08-17 21-25-48](https://user-images.githubusercontent.com/33398983/90416653-61643d00-e0d0-11ea-8c7d-ec29acb76d91.png)

**Comment by grainier** [comment]
As per debugging session with @shehan360, we found out that following two module-level map initialization [1], [2] internally get put into 2 separate module init methods. And that causes docs to show two init methods under functions.
@rdhananjaya @KavinduZoysa @MaryamZi @pubudu91 is this the correct behaviour? If so, couldn't that be private? I'm just trying to figure out at which level this needs to be fixed (compiler/docs)?

![Screenshot from 2020-08-17 21-55-11](https://user-images.githubusercontent.com/3824254/90420225-4cd67380-e0d5-11ea-89a1-19e34e4dee82.png)
![Screenshot from 2020-08-17 21-54-50](https://user-images.githubusercontent.com/3824254/90420237-519b2780-e0d5-11ea-9a98-cf67fada234a.png)

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.transaction/src/main/ballerina/src/lang.transaction/internal.bal#L35
[2] https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.transaction/src/main/ballerina/src/lang.transaction/internal.bal#L482

**Comment by pubudu91** [comment]
I don't think we should be documenting generated module init functions. Or even the user written module init functions for that matter. And the multiple init functions are due to the module init being broken up to multiple functions in desugar to avoid the method too large error.

**Comment by shehan360** [comment]
If the multiple functions are being added in the desugar phase, I think this issue is related to #24578

**Comment by pubudu91** [comment]
Yes, I guess this is the same issue as that

**Comment by hasithaa** [comment]
Ideally, API doc generation has to rely on Semantic API & Syntax API, to avoid implementation-related details getting populated into the docs. With SL we are restricting access to Compiler internal implementation, so this issue needs to be fixed from the API doc gen tool.

**Comment by shehan360** [comment]
This issue seems to be resolved, hence closing the issue.
