### ISSUE TITLE
Function source file information not available

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#25002]
**Description:**
The Ballerina source file in which the function is defined is not accessible. The `source` attribute is not initialized and is always null during compile time.  

The source information, ie the .bal file in which the function is defined is required for validation during runtime. In order to validate the function, the class loader is used to get the function list :

` Method[] methodList = FunctionMock.class.getClassLoader().loadClass(packageName).getDeclaredMethods();`

Here the `packageName` needs to include the source information in order to successfully load the right class.

**Steps to reproduce:** 
Debugging the BLangPackage functionList should show the `source` as null.

**Affected Versions:**

**OS, DB, other environment details and versions:**
1.2.x branch

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by riyafa** [comment]
Constant propagation is not valid in the current BIR. Possible optimizations have already been implemented.

**Comment by riyafa** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/25144
