### ISSUE TITLE
Implement new transaction spec for service interaction

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#25034]
This issue is divided into two issues.

- [x] #25271 Check the possibility of using Atomikos REST service for Ballerina distributed transactions.

- [x] #25270 Check the possibility of using Atomikos REST services to support our distributed transaction protocol in few standalone Java programs

**Comment by mohanvive** [comment]
Closing the issue since all the sub-tasks are completed.
