### ISSUE TITLE
Improve parser performance

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25042]
**Description:**

Currently new parser outperforms the old antlr4 parser when it comes to large programs/projects.
However for small programs, antlr4 seems to performs better.

new parser seems to take ~200ms to parse an empty bal file, which suggests that theres a considerable time consumed to bootup the parser.

**Comment by SupunS** [comment]
Causes for the issues were:
- switch-cases on a large enum (enum with large number of entries). Such enums are:
  - ParserRuleContext
  - SyntaxKind
- Large number of static methods in the NodeFactory()

Solution:
- Make switch-case to use integers. i.e: replace enums with integer constants
- Replace static methods with a instance methods

**Comment by lochana-chathura** [comment]
Can we consider making second level parsers static? (e.g. Documentation parser, XML parser)
