### ISSUE TITLE
Handling password and token in Ballerina.toml

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#25074]
**Description:**
If we have to specify a password or token in the toml, How we are going to handle it?

Sample toml file:
```[project]
org-name= "foo"
version= "0.1.0"

[platform]
target = "java8"

    [[platform.repositories]]
       id="wso2-releases"
       url="http://maven.wso2.org/nexus/content/repositories/releases/"
       username="foo"
       password="*****"
```

**Comment by anupama-pathirage** [comment]
This is currently not part of our plans or a priority, so we are closing the issue for now. We will reopen it if we decide to pursue this in the future.
