### ISSUE TITLE
Map reduce in JDK 11 fails

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#25072]
**Description:**
In the `jdk_11_migration` branch, the following type of example test will not be executed successfully. 

```
function test() {
    map<byte> m = {
            a: 3,
            b: 5,
            c: 1
        };

        int f = m.reduce(function (byte x, byte y) returns byte {
                             int res = x * y;
                             return <byte> res;
                         }, 2);
}
```

- The gradle execution would be stuck at some point when this test case is being executed. 
- If only one key-value pair is included in the `map<byte> m`, the build would be successful. 

**Steps to reproduce:**

1. Place only the above mentioned example code in the [`type_param_bound_type_as_cet.bal`](https://github.com/ballerina-platform/ballerina-lang/blob/jdk_11_migration/langlib/langlib-test/src/test/resources/test-src/type-param/type_param_bound_type_as_cet.bal) file (remove/comment out all the other functions within it).

2. In the [`TypeParamTest.java`](https://github.com/ballerina-platform/ballerina-lang/blob/07b2d55ae712086bb41c777a15429f815a4ac40e/langlib/langlib-test/src/test/java/org/ballerinalang/langlib/test/TypeParamTest.java#L89) file, place only one new test case as following (remove/comment out all the other functions within it): 

```
@Test(description = "Tests for the bound type as the contextually expected type for arguments")
public void testBoundTypeAsCET() {
    CompileResult result = BCompileUtil.compile("test-src/type-param/type_param_bound_type_as_cet.bal");
    Assert.assertEquals(result.getErrorCount(), 0);
    BRunUtil.invoke(result, "test");
}
```

3. Execute the following gradle command in order to build and test, only the above test case. 
```
./gradlew :ballerina-langlib:test:test -x :composer-library:npmBuild -x :composer-library:npmInstall --tests TypeParamTest
```

**Affected Versions:**
Executed on the `jdk_11_migration` branch

**OS, DB, other environment details and versions:**
Executed on Ubuntu 20.04

**Related Issues (optional):**
#25041 

**Suggested Labels (optional):**
Area/jBallerina, Priority/Blocker, Type/Bug 

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
@rdhananjaya @sanjana , refrenced PR should fix this issue.
