### ISSUE TITLE
Move `database` modules to another repo

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25085]
**Description:**
This is a part of Standard Library Repo migration

- [x]  JDBC module(module-ballerina-jdbc)
- [x] SQL module(module-ballerina-sql)
- [x]  Mysql module(module-ballerinax-mysql)

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by daneshk** [comment]
Related issue: #24950

**Comment by niveathika** [comment]
All three modules are migrated.
