### ISSUE TITLE
Move `cache` module to another repo

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25088]
**Description:**
This is a part of Standard Library Repo migration

Based on other dependencies: https://thisaruguruge.github.io/ballerina_dependencies/

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by kalaiyarasiganeshalingam** [comment]
Blocked due to the #25309

**Comment by kalaiyarasiganeshalingam** [comment]
Moved in [#1](https://github.com/ballerina-platform/module-ballerina-cache/pull/1)
