### ISSUE TITLE
Move `filepath` module to another repo

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25091]
**Description:**
This is a part of Standard Library Repo migration

Based on other dependencies: https://thisaruguruge.github.io/ballerina_dependencies/

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by ThishaniLucas** [comment]
Closed with https://github.com/ballerina-platform/module-ballerina-filepath/pull/3 and https://github.com/ballerina-platform/ballerina-lang/pull/25498
