### ISSUE TITLE
Move `stringutils` module to another repo

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25099]
**Description:**
This is a part of Standard Library Repo migration

Based on other dependencies: https://thisaruguruge.github.io/ballerina_dependencies/

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by BuddhiWathsala** [comment]
Fixed with https://github.com/ballerina-platform/module-ballerina-stringutils/pull/1
