### ISSUE TITLE
Move `java arrays` module to another repo

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25092]
**Description:**
This is a part of Standard Library Repo migration

Based on other dependencies: https://thisaruguruge.github.io/ballerina_dependencies/

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by BuddhiWathsala** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/21313

**Comment by BuddhiWathsala** [comment]
Blocking due to this issue https://github.com/ballerina-platform/ballerina-lang/issues/25301
