### ISSUE TITLE
Move `system` module to another repo

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#25101]
**Description:**
This is a part of Standard Library Repo migration

Based on other dependencies: https://thisaruguruge.github.io/ballerina_dependencies/

**Comment by daneshk** [comment]
Related issues: #23559, #23527, #23506

**Comment by Bhashinee** [comment]
Blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/25301

**Comment by Bhashinee** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/issues/25101
