### ISSUE TITLE
Error while trying to format a ballerina file with a record referring to another record 

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#25142]
**Description:**
Following error was thrown when trying to format a file with a record type value defined with reference to another record value.

`$ ballerina format src/formattest/main.bal `
`error: .::main.bal:8:36: unknown type 'PlaceOrderRequest'`

**Workaround:**
Format the complete module as follows.

`$ ballerina format src/formattest`

**Steps to reproduce:**

1. create a new ballerina project and create a module.
2. Add new.bal to the module with following code.

```
public type Address record {|
    string street_address = "";
    string city = "";
    string state = "";
    string country = "";
    int zip_code = 0;

|};

public type PlaceOrderRequest record {|
    string user_id = "";
    string user_currency = "";
    Address? address = ();
    string email = "";

|};

```

3. Add the following code to main.bal file

```
import ballerina/io;

public function main() {
    io:println("req is:", getOrderRequest());
}

function getOrderRequest() returns PlaceOrderRequest {
    Address shipping_address = {street_address: "", city: "", state: "", country: "", zip_code: 0};
    PlaceOrderRequest request = {
        user_id: "001",
        address: shipping_address,
        email: "test@gmail.com"
    };
    return request;
}
```

4. Try to format the file main.bal using below command.

`$ ballerina format src/formattest/main.bal `

**Affected Versions:**

**OS, DB, other environment details and versions:**

Ballerina version:
Ballerina Swan Lake Preview 2

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Fixed in slp5
