### ISSUE TITLE
Dead code elimination

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#25159]
**Description:**

> Remove code which does not affect the program results. Removing such code has several benefits: it shrinks program size, an important consideration in some contexts, and it allows the running program to avoid executing irrelevant operations, which reduces its running time. It can also enable further optimizations by simplifying program structure. Dead code includes code that can never be executed (unreachable code), and code that only affects dead variables (written to, but never read again), that is, irrelevant to the program. 
(from [wikipedia](https://en.wikipedia.org/wiki/Dead_code_elimination))

Unreachable code is already identified in ballerina, but assignment to dead variables has to be removed.

**Steps to reproduce:**
In the following code the first assignment to variable `b` an be eliminated:
```
function foo() returns int {
   int a = 24;
   int b = 25; // Assignment to dead variable 
   b = a * 4;
   return b;
 }
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by riyafa** [comment]
Suppose we have an example like this 
```

public function main() {
    decimal d1 = 0.0;
    decimal|boolean d2 = 1.0/d1;
    int i = <int> d2;
}
```
Currently this throws an error because of integer division. But with dead code elimination the line with the cast `int i = <int> d2;` is removed. This cause no error to be thrown at runtime if the variable is not used. What should be the correct behavior?

**Comment by Kishanthan** [comment]
I think we should fail this at runtime as it is what expected. But why this casting is being ended up as a dead code is a question?

**Comment by riyafa** [comment]
> I think we should fail this at runtime as it is what expected. But why this casting is being ended up as a dead code is a question?

Because the variable `i` is not used anywhere following this assignment. This variable is written to but never read again. 

As a workaround we can identify casting instructions and make them as exceptions so that they don't become dead code. But is it a good solution?

**Comment by riyafa** [comment]
There are other occasions similar to the above like the following  
```
public function main() {
 int val = -1;
 int val1 = getPowerof(-2, 63);
 int k = val1/val;
}
```
This function needs to throw a NumberOverflow error which is not thrown because of dead code elimination of assignment to k. These expressions cannot be determined except at runtime.

**Comment by Kishanthan** [comment]
> There are other occasions similar to the above like the following
> 
> ```
> public function main() {
>  int val = -1;
>  int val1 = getPowerof(-2, 63);
>  int k = val1/val;
> }
> ```
> 
> This function needs to throw a NumberOverflow error which is not thrown because of dead code elimination of assignment to k. These expressions cannot be determined except at runtime.

So in here, assignment to k is removed or the complete statement ?

**Comment by riyafa** [comment]
@Kishanthan the instruction with assignment to dead code is removed unless it is a terminating statement (such as function calls).

**Comment by Kishanthan** [comment]
Which means assignment to k is not a deadcode and it is expected to fail at runtime.

**Comment by riyafa** [comment]
> Which means assignment to k is not a deadcode and it is expected to fail at runtime.

By the definition of dead code (mentioned in the first comment for the issue) it is a dead code, removing it has no consequence other than failing to throw an exception. This is because the variable k is not used anywhere afterwards.

**Comment by riyafa** [comment]
There are three ways to go ahead with this issue:

1. Add this optimization because although there are inconsistencies with the exceptions there will not be usability issues because the removed code is already dead
2. Make this optimization configurable while mentioning the possible side effects if enabled.
3. Do not support dead code elimination in ballerina

**Comment by riyafa** [comment]
To show how much code reduction could be achieved at the bir level by dead code elimination, consider the following code:
```
public function main() {
    int a = 3;
    int c = a + 2;
    int d = c + 1;
}
```
The bir of main method before optimization is as follows:
```

public main function() -> () {
    %0(RETURN) ();
    %0(RETURN) ();
    %1(LOCAL) int;
    %3(LOCAL) int;
    %5(TEMP) int;
    %7(LOCAL) int;

    bb0 {
        %1 = ConstLoad 3;
        %5 = ConstLoad 2;
        %3 = %1 + %5;
        %5 = ConstLoad 1;
        %7 = %3 + %5;
        %0 = ConstLoad 0;
        GOTO bb2;
    }
    bb1 {
        GOTO bb2;
    }
    bb2 {
        return;
    }
}
```
Bir of the main method after the optimization:
```
public main function() -> () {
    %0(RETURN) ();
    %0(RETURN) ();

    bb0 {
        %0 = ConstLoad 0;
        GOTO bb2;
    }
    bb1 {
        GOTO bb2;
    }
    bb2 {
        return;
    }
}
```

**Comment by riyafa** [comment]
This is not feasible because removing of instructions at the bir level shall break the debugger. The plan is to support identification of unused variables at the IDE level.
