### ISSUE TITLE
REPL support for Balleirna 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#25150]
**Description:**
Feasibility study of JREPL and look at how we can implement in jBallerina. Also look at how to support this at debugger level for expression evalution API.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by manuranga** [comment]
covered by ballerina shell feature in #27797
