### ISSUE TITLE
Runtime error occures when function parameter containing error value is referenced inside a transaction statement

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25166]
**Description:**
```ballerina
public function main() {
    createUpdateDeleteTransaction(error("theError"));
}

function createUpdateDeleteTransaction(error? dbOperation) {
    transaction {
        error? queryResult = dbOperation; 
    }
}
```

```
error: {ballerina/lang.map}InherentTypeViolation message=invalid map insertion: expected value of type 'any', found 'error'
        at main:createUpdateDeleteTransaction(main.bal:5)
           main:main(main.bal:2)
```

The workaround is to assign these parameters which could contain error values to local variables before the transaction block.

Above sample with workaround applied.
```ballerina
public function main() {
    createUpdateDeleteTransaction(error("theError"));
}

function createUpdateDeleteTransaction(error? dbOperation) {
    error? er = dbOperation; // assign to intermediate local variable
    transaction {
        error? queryResult = er; 
    }
}
```

Note:
This looks like a bug in the closure var map calculation, it seems that the parameters are not considered when type of closure var map is calculated.

**Steps to reproduce:**

**Affected Versions:**
1.2.6
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Fixed from #27245
