### ISSUE TITLE
Debugger Test Automation

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#25179]
**Description:**
Automate All debugger tests

Debugger Tests
- Testing if the debugger engages in all possible cases.
    - Commands
        - [x] Run
            - [x] Ballerina run moduleName 
            - [x] Ballerina run fileName.bal
            - [x] Ballerina run executable.jar
        - [x] Build - Only debug when running tests
        - [x] Test 
    - Two flows can be find in above cases 
        - [x] Module code get hit ( run - module, executable jar, single file)
        - [x] Module + Test Code get hit ( build, test )
- Source Structure 
    - [x] Module with multiple files 
    - [x] Files inside subdirectories in a module 
- Language Constructs - Will be tested with run command and check if we can get a debug hit inside each construct. Validate variable visibility
    - [x] Main function
    - [x] Service 
    - [x] Function 
    - [x] Object method 
    - [x] Object __init method 
    - [x] Workers
    - [x] Remote object
    - [x] Remote function
- Control flow - Will be tested with run command and check if we can get a debug hit inside each construct. Validate variable visibility. Check if the continue works with the correct flow.
    - [x] If else 
    - [ ] Actions
    - [x] Method invocation
    - [x] Loops 
    - [x] lambda expression
    - [x] Non-blocking calls
- Test related case - Will be tested with test command
    - [x] Test function
    - [x] Service inside tests
    - [x] Mocked functions 
    - [x] Before suite and after suite 
- Debug operation - Will be tested with run command
    - [x] Debug hit 
    - [x] Stepin
    - [x] Stepout
    - [x] Step over
    - [x] Continue
- Variables  - Will be tested with run command
    - [x] Primitives 
    - [x] Objects
    - [x] Json
    - [x] String 
- On the fly debug
    - [x] Add
    - [x] Remove
- IDE integration tests
    - [x] VSCode

**Comment by NipunaRanasinghe** [comment]
Closing since the debugger integration test suite has covered all of the above scenarios.
