### ISSUE TITLE
Port the API Docs to generate from Syntax Tree

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#25176]
**Description:**
Currently the API Docs are generated with the AST. We need to port it to the new syntax tree. This effort is dependent on the Semantic API.

**Comment by shehan360** [comment]
- [ ] Implement the basic code to generate the Doc Model from Syntax Tree

- [ ] Use the Semantic API to resolve the references

- [ ] Incorporate the Project API to finalize
