### ISSUE TITLE
Ballerina Debugger Expression Evaluator 

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#25178]
**Description:** 
Implement expression evaluation support for ballerina debugger.

**Progress:** 
- Expressions
  - [x] Literal expression
  - [x] Multiplicative expression
  - [x] Additive expression
  - [x] Numerical comparison expression
  - [x] Variable reference expression
  - [x] Field access expression
  - [x] Function call expression
  - [x] Method call expression
  - [x] Group expression
  - [x] String template expression
  - [x] Optional field access expression
  - [x] Member access expression
  - [x] Typeof expression
  - [x] Unary expression
  - [x] Shift expression
  - [x] Equality expression
  - [x] Binary bitwise expression
  - [x] Logical expression
  - [x] Conditional expression
  - [x] Checking expression
  - [x] Type test expression
  - [x] Type cast expression
  - [x] Trap expression
  - [x] Query expression
  - [x] XML navigation expression (Planned)
  - [x] XML template expression
  - [x] New expression
  - [x] XML attribute access expression
  - [x] Annotation access expression (Planned)
  - [x] Range expression
  - [x] Error constructor
  - [x] Anonymous function expression
  - [x] Let expression

**Comment by NipunaRanasinghe** [comment]
Closing as completed
