### ISSUE TITLE
NATS related language server tests disabled

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#25183]
**Description:**
NATS module is moved from ballerina-lang to its own repository at: https://github.com/ballerina-platform/module-ballerinax-nats
The tests are commented in PR: https://github.com/ballerina-platform/ballerina-lang/pull/25143 
Edited files: 
`ConnectorTest.java`
                     `ASTModifyTest.java`
                     `SyntaxTreeModifyTest.java`

**Comment by nadeeshaan** [comment]
This issue is invalidated since these tests have been removed and replaced. Hence closing the issue
