### ISSUE TITLE
Add error constructor expression snippets to the expression completion list

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#25181]
**Description:**
Currently we only support the error keyword in the expression contexts. We need to support the error constructor snippets for this context.

**Steps to reproduce:**
Ex: return <cursor>

Here the cursor is within the expression context where we can suggest the error constructor expression.

**Affected Versions:**
SwanLake-Preview3-SNAPSHOT

**Comment by IMS94** [comment]
Has been fixed in master
