### ISSUE TITLE
Undocumented field warning for records defined in test file

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#25198]
**Description:**
Undocumented field warning is shown when a record type variable is defined in a test file.

**Steps to reproduce:**

1. Create a new Ballerina project
2. Add a new module
3. Define a record type "Employee" in main_test.bal file as follows and use it inside a testFunction.

```
type Employee record {
    readonly int id;
    string name;
    float salary;
};
```

4. **ballerina build** the module. You will notice the following warning.

```
warning: dilhashanazeer/documentationproj:0.1.0::tests/main_test.bal:6:5: undocumented field 'id'
warning: dilhashanazeer/documentationproj:0.1.0::tests/main_test.bal:7:5: undocumented field 'name'
warning: dilhashanazeer/documentationproj:0.1.0::tests/main_test.bal:8:5: undocumented field 'salary'
```

**Affected Versions:**
Ballerina Swan Lake Preview 2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Cannot seem to reproduce this on slp2 or sl-alpha.

Is it possible that documentation was added for `Employee`? If so these errors are expected.
e.g.,
```ballerina
# Docs for the record, but not the fields.
type Employee record {
    readonly int id;
    string name;
    float salary;
};
```

**Comment by MaryamZi** [comment]
@Dilhasha, any update on this?

**Comment by Dilhasha** [comment]
@MaryamZi 
You are correct. This happens only when documentation is added for `Employee` as you mentioned. Hence, it is expected, we can close this issue.
