### ISSUE TITLE
Ballerina Package Implementation

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#25209]
### Description
Following is the implementation plan for the Ballerina package design which can be found [here](https://github.com/ballerina-platform/ballerina-spec/blob/master/project/proposals/packages/packages.md).

### Specifications to finalize 
- [ ] Balo Specification
- [ ] Project API ( Design )
    - [ ] Internal API
    - [ ] Public API
- [ ] Ballerina Project User Guide
- [ ] Project Specification ( Update the existing one )
    - [ ] Target Directory Organization
    - [ ] Cache directory Organization
- [ ] Central API - 2.0v

### Sprint 17 - August 26
- [ ] Build a multi module project 
    - without tests
    - generate an executable
- [ ] Finalize the balo spec 
- [ ] Finalize Central API
- [ ] Integrate Package Loader 
- [ ] Will load modules of the same project
- [ ] Will load modules from distribution

### Sprint 18 - September 9
Goals: Build multi module project

### Sprint 19 - September 23
- [ ] LS Project integration

### Sprint 20 - October 7
Goals: Work with new central API

### Project API Components 

![project-api](https://www.plantuml.com/plantuml/png/VP312i8m38RlVOhGez23Bo1ZU54c31GyXpMCQbqXxS37jtFPj1wyvV_-9EsVAYRaD3wyQZdSg4kWjnesni05kQUqOcDsq297uWATWXqzDG7jZt545gewZp52FJflbmvw9Xfi1D7Iqfp_-pNwS6MNyb81ZWkT7nKjOFvU8GvxDHSGSigLVV8F-krCTv1ncM-nksDFnQMcpeKhARuMgoh7oDTz0G00 "project-api")
```plantuml
@startuml
Project "1" *-- Target
Project --> Parser
Project --> ModuleLoader
Project --> JarLoader

class BuildProject extends Project
class LSProject extends Project
class BaloWriter
class BirWriter
class JarWriter

class Module
class ModuleID
Module o-- ModuleID

Project "n" o-- "1" Module

class Package
Project "1" o-- Package

Package o-- Module
@enduml
```

**Comment by sameerajayasoma** [comment]
Related issue is: https://github.com/ballerina-platform/ballerina-spec/issues/230

**Comment by hevayo** [comment]
Outdated
