### ISSUE TITLE
Improve the error when an invalid named argument is used

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25230]
**Description:**
When an invalid named argument is used, atm the error is something like `undefined defaultable parameter 'i'`.

But now that we can use named arguments with positional params too, IMO the error should just be `undefined parameter 'i'`.

**Steps to reproduce:**
```ballerina
public function main() {
    // error: .::xyz.bal:4:9: undefined defaultable parameter 'i'
    // error: .::xyz.bal:4:5: missing required parameter 's' in call to 'foo'()
    foo(i = 1);

    // error: .::xyz.bal:7:9: undefined defaultable parameter 'i'
    bar(i = 1);
}

function foo(string s) {
    
}

function bar(string s = "hello") {
    
}
```

**Affected Versions:**
slp2

**Comment by Suraj-kumar00** [comment]
Hi @MaryamZi, How are you doing?
Is this issue is till open to work on, can you please let me know so that I can work on this issue!

**Comment by MaryamZi** [comment]
@Suraj-kumar00, I'm doing well, hope you are too.

Yes, you can work on this issue.

To help you get started, here are some resources that may help you get started with Ballerina:

1. Understanding Ballerina Platform:
Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)

2. How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)

3. Learn Ballerina:
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)

4. Get Help and Connect:
Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by Suraj-kumar00** [comment]
Hi @MaryamZi thanks for assigning this issue to me, can I know like how much time I have to work on this issue? And should I create a draft pull request for the conversation regarding this issue or do that here only?

**Comment by MaryamZi** [comment]
> Hi @MaryamZi thanks for assigning this issue to me, can I know like how much time I have to work on this issue? And should I create a draft pull request for the conversation regarding this issue or do that here only?

Anything that works for you would be okay.

**Comment by MaryamZi** [comment]
The error message is defined in [compiler.properties](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/resources/compiler.properties#L919), where this needs to be updated.

Since the key is already `undefined.parameter` we wouldn't in any changes there or to [DiagnosticErrorCode.java](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java#L73).

The errors are logged via [BLangDiagnosticLog.java](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLog.java#L100) which you can debug to identify the flow as required.

**Comment by Suraj-kumar00** [comment]
> The error message is defined in [compiler.properties](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/resources/compiler.properties#L919), where this needs to be updated.
> 
> Since the key is already `undefined.parameter` we wouldn't in any changes there or to [DiagnosticErrorCode.java](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java#L73).
> 
> The errors are logged via [BLangDiagnosticLog.java](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLog.java#L100) which you can debug to identify the flow as required.

Hi @MaryamZi, How are you doing?
So I was hoping you could help me understand this issue, as of now I understand that I have to the correct parameter names when calling the functions, the named argument i, which is not a valid parameter name for either foo or bar.
So should I do this 
 
foo(s = "example");

bar(s = "world");

Did I get it wrong or should I do this?

**Comment by MaryamZi** [comment]
> So I was hoping you could help me understand this issue, as of now I understand that I have to the correct parameter names when calling the functions, the named argument i, which is not a valid parameter name for either foo or bar. So should I do this
> 
> foo(s = "example");
> 
> bar(s = "world");
> 
> Did I get it wrong or should I do this?

The requirement is to stop saying 

```bash
undefined defaultable parameter 'i'
```

and say

```bash
undefined parameter 'i'
```

for code like the examples from the original description. So basically, remove the term "defaultable". Hope this is clear.

> And also the code that you have provided above I never found them in the location that you provide me below of that code like in the three locations...

Sorry, this is not clear. Do you mean you cannot find the files when you check the code out locally?

**Comment by Suraj-kumar00** [comment]
> > So I was hoping you could help me understand this issue, as of now I understand that I have to the correct parameter names when calling the functions, the named argument i, which is not a valid parameter name for either foo or bar. So should I do this
> > foo(s = "example");
> > bar(s = "world");
> > Did I get it wrong or should I do this?
> 
> The requirement is to stop saying
> 
> ```shell
> undefined defaultable parameter 'i'
> ```
> 
> and say
> 
> ```shell
> undefined parameter 'i'
> ```
> 
> for code like the examples from the original description. So basically, remove the term "defaultable". Hope this is clear.
> 
> > And also the code that you have provided above I never found them in the location that you provide me below of that code like in the three locations...
> 
> Sorry, this is not clear. Do you mean you cannot find the files when you check the code out locally?

Yeah the three file location you have provided above I haven't found there!!!

**Comment by Suraj-kumar00** [comment]
yes let me check and i'll inform you...

**Comment by Suraj-kumar00** [comment]
Hello @MaryamZi, How are you doing?
Actually, I'm facing a lot of errors. I don't know why. Can you please help me with this?
![Screenshot (198)](https://github.com/ballerina-platform/ballerina-lang/assets/123288511/9309e4d0-5401-4992-9a18-7bd7c81a0370)

**Comment by Suraj-kumar00** [comment]
Hello @MaryamZi, How are you doing?
Can you please tell me about the above error I'm getting?

**Comment by MaryamZi** [comment]
Can you please share what exactly the errors are?

Are you trying to add tests? Just updating the existing tests (e.g., in jballerina-unit-tests) should be enough.

**Comment by Suraj-kumar00** [comment]
> Can you please share what exactly the errors are?
> 
> Are you trying to add tests? Just updating the existing tests (e.g., in jballerina-unit-tests) should be enough.

As I shared in the screenshot above you can see the errors in the folders itself and in the right side of the screenshot you can see what the errors are?

**Comment by MaryamZi** [comment]
> > Can you please share what exactly the errors are?
> > Are you trying to add tests? Just updating the existing tests (e.g., in jballerina-unit-tests) should be enough.
> 
> As I shared in the screenshot above you can see the errors in the folders itself and in the right side of the screenshot you can see what the errors are?

Can only see the red line and not an actual error? Is it just an unresolved modue error?

Anyway, are you seeing this after following the guide for building from source?

- https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md 
- https://github.com/ballerina-platform/ballerina-distribution/blob/master/docs/build-ballerina-from-source.md#build-only-the-ballerina-runtime-with-the-tools

**Comment by Suraj-kumar00** [comment]
Okay let me try this

**Comment by keizer619** [comment]
@Suraj-kumar00 Are you still working on this issue?

**Comment by Suraj-kumar00** [comment]
Hi @keizer619, actually I'm working on this but facing some errors I'll try to solve this by week and after that i'll let you know.

**Comment by Suraj-kumar00** [comment]
Hello @MaryamZi, how are you doing?
Pardon me for not be active here form few days but here I'm and working on it.
So I get this while fetching the updated from the main branch and I never changed anything here but it's showing untracked files i don't know why? can you please help me in this?

![Screenshot from 2023-11-19 18-39-26](https://github.com/ballerina-platform/ballerina-lang/assets/123288511/27fc1cae-6115-4c83-a736-da76a525d114)

**Comment by MaryamZi** [comment]
> Hello @MaryamZi, how are you doing? Pardon me for not be active here form few days but here I'm and working on it. So I get this while fetching the updated from the main branch and I never changed anything here but it's showing untracked files i don't know why? can you please help me in this?
> 
> ![Screenshot from 2023-11-19 18-39-26](https://user-images.githubusercontent.com/123288511/284257571-27fc1cae-6115-4c83-a736-da76a525d114.png)

Is this after doing a build? You do a [`git clean`](https://git-scm.com/docs/git-clean) to remove unnecessary untracked files too.

**Comment by keizer619** [comment]
@Suraj-kumar00 Are you working on this issue?

**Comment by Aviral0702** [comment]
Hi, @keizer619 Can I work on this issue ?

**Comment by gimantha** [comment]
> Hi, @keizer619 Can I work on this issue ?

Hello @Aviral0702
I have assigned the issue to your name. You can start working on this issue.

To help you get started, here are some resources that may help you get started with Ballerina:

Understanding Ballerina Platform:
Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)

How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)

Learn Ballerina:
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)

Get Help and Connect:
Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by areebniyas** [comment]
Hi @gimantha @Aviral0702 @keizer619, apologies was working on this and sent a PR. If there are anymore changes, do let me know and maybe we can work on it together.

**Comment by gimantha** [comment]
@Aviral0702 Have you already started working on this issue?

**Comment by gimantha** [comment]
> Hi @gimantha @Aviral0702 @keizer619, apologies was working on this and sent a PR. If there are anymore changes, do let me know and maybe we can work on it together.

@areebniyas Please make sure that in future, you pick  issues which are not assigned to anyone as we cannot split the number of credits between multiple assignees. Let's keep your pull request open for the moment. Thank you for understanding!
