### ISSUE TITLE
Create Variable Code Action should honour unions with error with check expression conversion

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#25246]
**Description:**
Consider the following source snippet,

```
public function main() returns @tainted error? {
	http:Client clientEP = new("");

	clientEP->get("/");
}
```

For the above, create variable code action will be suggested for the `clientEP->get("/");`. When executed we get the following,

`http:Response|error getResult = clientEP->get("/");`

Here, we can avoid the error with the following syntax,

`http:Response getResult = check clientEP->get("/");`

We can provide two code actions to convert a union with the error to check expression and also another one along with the  create local variable code action

**Comment by rasika** [comment]
Can also provide another option with `checkpanic` with requires no changes to enclosing function signature. WDYT?

**Comment by nadeeshaan** [comment]
> Can also provide another option with `checkpanic` with requires no changes to enclosing function signature. WDYT?

@rasika yes, +1. We should consider the any checking expression related to that
