### ISSUE TITLE
Improve parser recovery for object-constructor-expr

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#25284]
**Description:**
Front-end Changes are still in PR https://github.com/ballerina-platform/ballerina-lang/pull/25302

### Example Code we cannot recover still
```Ballerina
    var x = object {
        int n = 0;
        function inc() returns { // no return type
            self.n += 1;
        }
    };
```

### Example code

```Ballerina
import ballerina/io;

type MO object {
    int x = 0;
};

type MOO object {
    *MO;
    int n = 0;

    public function init() {
        self.x = 5;
    }
};

var objVariable = object MOO {
    int n = 20;

    public function init() {
        self.x = 4;
    }
};

var objMo = new MOO();

public function main() {

    io:println(objVariable.n);
    io:println(objVariable.x);

}
```

### Example output
```LogTalk
20
4
```

**Steps to reproduce:**
new feature

**Affected Versions:**
slp4

**Related Issues (optional):**
#25043

**Suggested Labels (optional):**
Area/Language

**Suggested Assignees (optional):**
@lochana-chathura

**Comment by SupunS** [comment]
Added with  #25511
