### ISSUE TITLE
Implement the Project loading API to work with the new Package implementation

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#25281]
**Description:**

Tasks to be done:

- [x] Load single Ballerina file 
- [x] Load a Ballerina project 
- [x] Implement validation 
- [x] Implement the target directory creation

**Comment by sameerajayasoma** [comment]
Can we decouple the logic and the API that identify the kind of Project from the `Project` model? 

Here is the initial idea:
- There are different kinds of projects: `BuildProject`, `LSProject`, `SingleFileProject`.
- Each project kind defines a way to load itself: `BuildProject.load`, `SingleFileProject.load()`
- These methods offer a way to load a kind directly: Use these APIs only when you know what you want to create
- We should provide another way to load a project from a given project path when someone doesn't know what kind of a project to load. This API should also offer APIs to check whether a given path is a single ballerina file or a project. This API will be useful for LS impl.

**Comment by hevayo** [comment]
+1 we can use a factory pattern easily. Name for the factory class can be "ProjectLoader", "ProjectFactory"..
