### ISSUE TITLE
Getting a message saying vscode plugin and Ballerina version do not match

### ISSUE THREAD

**Issue by Ayodhya94** [ballerina-platform/ballerina-lang#25295]
**Description:**
When I open vscode with the new ballerina SLP3 plugin while Ballerina SLP3 is installed, I get the following error message.
![Screen Shot 2020-08-14 at 12 51 27 PM](https://user-images.githubusercontent.com/40056203/90350605-4e635580-e05b-11ea-8e99-fbb19805bc77.png)

Following are the Ballerina version and vscode plugin version:
<img width="646" alt="Screenshot 2020-08-14 at 13 06 11" src="https://user-images.githubusercontent.com/40056203/90350662-73f05f00-e05b-11ea-8161-df7d566bd6f0.png">
<img width="400" alt="Screenshot 2020-08-14 at 13 06 05" src="https://user-images.githubusercontent.com/40056203/90350667-76eb4f80-e05b-11ea-98e8-568066b5f2c3.png">

**Comment by prabushi** [comment]
Will be addressed with https://github.com/ballerina-platform/plugin-vscode/issues/8
