### ISSUE TITLE
Parser error recovery seems to be adding invincible nodes with semantic errors.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25307]
**Description:**
```ballerina
type ObjectName object {
    function foo() {
        int i = 0;
    }
};

// extra token `abstract`
abstract type ObjectT object {
    *ObjectName;
};


public function main() returns error? {
}
```

```
error: .::main.bal:8:23: invalid token 'ObjectT'
error: .::main.bal:8:23: invalid token 'type'
error: .::main.bal:10:2: missing identifier
```

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1496990/90489133-830a0680-e15a-11ea-8aae-cbddc15caf2b.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
What do you mean by an invincible node?

**Comment by SupunS** [comment]
In the above example, what happens is, since `abstract` keyword is a valid type starting token (abstract object - before the object change), the parser starts parsing that code snippet as a module var-decl, which starts with an object type.

**Comment by rdhananjaya** [comment]
> What do you mean by an invincible node?
`$missingNode$12` in screenshot.
If a user didn't type that he shouldn't be getting this error right.

**Comment by SupunS** [comment]
Parser sometimes insert nodes to create a resilient tree, upon syntax errors. 
We should not log errors for those inserted nodes at the compiler front end.

**Comment by SupunS** [comment]
btw, when I run this on the latest master I only get below errors:
```
Compiling source
	testMain.bal
error: .::testMain.bal:8:23: invalid token 'ObjectT'
error: .::testMain.bal:8:23: invalid token 'type'
error: .::testMain.bal:10:2: missing identifier
```

**Comment by rdhananjaya** [comment]
Sorry forgot to specify the issue was detected on slp-preview3.

**Comment by SupunS** [comment]
What puzzles me is why the errors logged on the console are different from the errors shown on vscode.

@nadeeshaan any idea?

**Comment by lochana-chathura** [comment]
> What puzzles me is why the errors logged on the console are different from the errors shown on vscode.

The test case is now outdated and couldn't observe this behavior.

We will suppress all the semantic diagnostics causing on top of missing node names with issue #29168. Hence closing this issue.
