### ISSUE TITLE
[VS Code] language features do not work when errorneous projects are opened

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#25319]
**Description:**
$subject.

When erroneous project(s) is opened in the **workspace of VS Code** and separate bal file is loaded, language features are not working for all files opened in the workspace.

After checking the output of the VS Code, it can be seen that the errors which were thrown for the erroneous project(s) 

**Affected Versions:**
slp3

**Comment by nadeeshaan** [comment]
Can you elaborate on what's the erroneous project?
