### ISSUE TITLE
Ability to engage a Ballerina compiler extension via a CLI option

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#25315]
**Description:**
In the current model, a developer can engage a compiler extension by importing a Ballerina module in the source code. But in the new code-to-cloud design, there is a requirement to enable an extension via an option to the `ballerina build` command. Here is a sample command. 

```
ballerina build -cloud=k8s
```

**Affected Versions:**
Swan Lake Preview 3

**Comment by azinneera** [comment]
We no longer have to add an import to generate cloud artifacts.  User can simply run `bal build --cloud=docker`.
