### ISSUE TITLE
Missing semicolon is not identified properly

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#25317]
**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    json j = from var r in reportStream select r.toJson()
    io:println(j.toJsonString());
}
```
Output:
```
error: sameera/temp:0.1.0::main.bal:7:1: missing plus token
error: sameera/temp:0.1.0::main.bal:6:28: undefined symbol 'reportStream'
error: sameera/temp:0.1.0::main.bal:7:16: self referenced variable 'j'
```

Can we improve these errors?

**Affected Versions:**
Swan Lake Preview 3

**Comment by SupunS** [comment]
This is very tricky. Above sample has a structure similar to below without newlines:
```
json j = expr1 expr2;
```
 Therefore recovering with a missing binary-operator is sort of correct :)

**Comment by hasithaa** [comment]
Saying `missing plus token` is incorrect IMO. Even though parser thinks it is a binary expression, semantically it is not. May be saying `missing token` is correct here.

**Comment by SupunS** [comment]
Catch is, we need to insert some token to get the resilient parsing. So even if we change the error message, we will still have to insert a binary-op (or some sort of a token) to complete the tree, and that inserted token could still result in a regression semantic error for some cases.

On the other hand, upon a missing token, IMO we need to give a precise error saying what is missing. That error message  works for like 90% cases, except for some edge cases like these. So if we decided to give a generic error, then we are losing out on the 90% case.

**Comment by hasithaa** [comment]
I agree with your point. But we can improve the logic by inserting an `error token` instead of a valid token. With that, we can handle this case in semantic analysis.

**Comment by SupunS** [comment]
In that case, what would be the node-structure (or the ballerina construct) to represent the `json j = expr1 expr2;` part?

That structure/node strictly depends on the type of the inserted `error token`.

**Comment by SupunS** [comment]
This was concluded to give a better error message (something like: "missing binary operator"), and keep the recovery (tree) as it is.

**Comment by rdulmina** [comment]
What if we recover `;` over `binary-op` here since the missing semicolon scenario is the common one
