### ISSUE TITLE
[Testerina][Mocking] Error while creating default mock object

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#25343]
**Description:**

When trying to create a default mock object and stub the functions, the below line throws an error.

`dbClient = test:mock(jdbc:Client);`

Error:

`incompatible types: expected 'ballerinax/java.jdbc:0.0.0:Client', found 'object { }'`

This works without an issue in swanlake release, but fails in 1.2.7.
 
**Steps to reproduce:**

Try the example specified in section "Stubbing to do nothing" in the mocking guid [[1]](https://ballerina.io/learn/testing-ballerina-code/mocking/)

[1] https://ballerina.io/learn/testing-ballerina-code/mocking/

**Affected Versions:**
1.2.7

**Comment by azinneera** [comment]
We need to cast the mock object to the relevant type. Please try `dbClient = <jdbc:Client>test:mock(jdbc:Client);`. The casting was removed in Swan Lake Previews after the introduction of dependently-typed function signatures but the 1.2.x versions still has to have the cast. @Ibaqu we should fix the website guides  for 1.2.x.

**Comment by Dilhasha** [comment]
> We need to cast the mock object to the relevant type. Please try `dbClient = <jdbc:Client>test:mock(jdbc:Client);`. The casting was removed in Swan Lake Previews after the introduction of dependently-typed function signatures but the 1.2.x versions still has to have the cast. @Ibaqu we should fix the website guides for 1.2.x.

Yeah, I was able to get through that with casting. Let's fix the website guide.

**Comment by Ibaqu** [comment]
I have updated the website so we can close this issue.
