### ISSUE TITLE
Need a way to get the entry points of a module

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25368]

**Comment by pubudu91** [comment]
Does entry points refer to main function and listeners? While there aren't dedicated APIs for that, I think a user can get these info using the current APIs 🤔

**Comment by nadeeshaan** [comment]
@pubudu91 Yes, current APIs allow to get the top level nodes including the functions and the listeners. If we are to have a separate API, then it is a wrapper which returns only these constructs.

**Comment by hasithaa** [comment]
We can add this later. Shall we differ this for now ?

**Comment by nadeeshaan** [comment]
@hasithaa +1. This API is a value addition for the current set of APIs, therefore I think we can differ it for now. Let's use the iterative approach for now.
