### ISSUE TITLE
Support iterating through the list of imports of a module

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25367]
**Description:**
This is required to generate JAR with dependencies.

**Comment by pubudu91** [comment]
Do we need to do anything extra for this? Currently the `visibleSymbols()` API returns all module level symbols, including the module symbols for any imports used. A user can simply filter the list for module symbols to get the imports.

**Comment by mohanvive** [comment]
Closing the issue since requirement could be achieve with existing APIs.
