### ISSUE TITLE
Need to Automate Generating API Docs for Deployment Modules for 1.2.x Releases

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25373]
**Description:**
Currently, we have to manually generate and add API Docs (of each of the deployment modules) below to 1.2.x releases. These modules reside in independent repos and ATM, they do not get packed to the "ballerina-distribution" repo.

1. AWS Lambda
2. Azure Functions
3. Docker
4. Istio
5. Openshift
6. Knative
7. Kubernetes

This should be automated and added to the build pipeline/workflow for future 1.2.x releases as already done in Swan Lake.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Since swan lake is primary release and 1.2.x releases will be done for patches  there is no need to generate api docs. Hence i am closing this issue
