### ISSUE TITLE
Fix "ExposeConfig" Broken Link in the Docker Module

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25417]
**Description:**
We need to fix the Doc Gen Tool to fix the broken link below, which is caused as per [1].

<img width="1080" alt="expose-config" src="https://user-images.githubusercontent.com/11707273/91251636-7ea4a580-e779-11ea-828a-893b9a955355.png">

[1] https://github.com/ballerina-platform/ballerina-lang/issues/24987#issuecomment-680134956

**Affected Versions:**

Should be fixed in both 1.2.x and Swan Lake.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Refer https://github.com/ballerina-platform/ballerina-lang/issues/24987#issuecomment-680134956 for more info.

**Comment by praneesha** [comment]
Reopening as we need to send the fix to the "ballerina-1.2.x" branch as well.
