### ISSUE TITLE
Revisit `toString`

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#25456]
$title. Ref: [1].

[1] https://github.com/ballerina-platform/ballerina-spec/issues/499

**Comment by gimantha** [comment]
When it comes to implementation,  there should be 2 different implementation as per the spec. One is represented by the langlib function toString() which is the direct style of toString(), other one is the langlib function toBalString(), which is the expression style of toString().

Informal style comes into play if we call the toString() on some basic types but direct style of toString() doesn't make sense.  For example, 

an array of xml: [<d>t</d>, <d>t</d>];

The expression style toString of this array is
[ xml`<d>t</d>`, xml`<d>t</d>`]

The informal and direct style of this array is
[`<d>t</d>`, `<d>t</d>`]

**Comment by mohanvive** [comment]
Incorporated with
- https://github.com/ballerina-platform/ballerina-lang/pull/25738
- https://github.com/ballerina-platform/ballerina-lang/pull/25753
