### ISSUE TITLE
Add @deprecated annotation support for class definitions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25487]
**Description:**

$subject.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Added in https://github.com/ballerina-platform/ballerina-lang/commit/8e503b06f5e7162315e3616148747a24f0168c40.
