### ISSUE TITLE
Introduce `final` fields and remove `readonly` fields for objects

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25491]
**Description:**
$title.

See https://github.com/ballerina-platform/ballerina-spec/issues/580

**Comment by lochana-chathura** [comment]
Failing jballerina unit tests due to this change were disabled with https://github.com/ballerina-platform/ballerina-lang/pull/25623/commits/e729ffe2c0e4114c1dd8d5a76694a8866a952e19 in PR #25623
