### ISSUE TITLE
Fix the Version Label of the Azure Functions Module

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25507]
**Description:**
Need to fix the Swan lake API Docs pages showing different version labels as shown below.

<img width="1680" alt="Screenshot 2020-08-28 at 14 39 18" src="https://user-images.githubusercontent.com/11707273/91544439-62e9fc80-e93d-11ea-846b-47434bc3d083.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
If this is the module version, shouldn't we start from 1.0.0?

**Comment by lafernando** [comment]
@anuruddhal Shall we please update the module with the proper version?
