### ISSUE TITLE
Replace the email connector related integration tests

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-lang#25514]
**Description:**
I have commented some testarena tests in https://github.com/ballerina-platform/ballerina-lang/tree/master/tests/testerina-integration-test directory as they were using email connector. Have to enable them later.

**Comment by Dilhasha** [comment]
Email connector related tests have been enabled in distribution repo at https://github.com/ballerina-platform/ballerina-distribution/tree/master/stdlib-integration-tests/email/tests
Hence, closing.
