### ISSUE TITLE
Allow using `isolated` with `function-type-descriptor` and `anonymous-function-expr`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25563]
**Description:**
The proposal for `isolated` says

> A function can be declared as isolated, by using the isolated keyword before the function keyword in the following syntactic constructs:
> 
> - function-type-descriptor
> - function-defn
> - method-decl
> - method-defn
> - service-method-defn
> - anonymous-function-expr

https://github.com/ballerina-platform/ballerina-lang/pull/25423 allows this for the above except for `function-type-descriptor` and `anonymous-function-expr`.

Need to add support for these two.

IMO, it will make sense to go ahead and allow qualifierList similar to the other function constructs, and specifically allow only `isolated` for the time-being, since other qualifiers may be allowed in the future.

**Comment by rdulmina** [comment]
Fixed with #25763
