### ISSUE TITLE
Parser changes for `readonly` to `final` object field changes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25568]
**Description:**
Need to do the following:
- allow `final` fields in object constructors and class definitions, and remove `readonly` fields
- remove `readonly` field from object type descriptors (i.e., object-field-descriptor)

See https://github.com/ballerina-platform/ballerina-spec/issues/580

**Comment by lochana-chathura** [comment]
@SupunS in the error handler there was no path with `readonly` in object-field. Is it intentional? Shall I implement it now for `final`?

**Comment by MaryamZi** [comment]
Changes by @lochana-chathura that fixed this were merged with https://github.com/ballerina-platform/ballerina-lang/pull/25784.
