### ISSUE TITLE
Add debugger expression evaluation test for bitwise operators

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#25574]
**Description:**
Add debugger expression evaluation test for the following bitwise operators

- [x]  AND - x & y
- [x]  OR - x | y
- [x]  XOR - x ^ y

**Comment by praveennadarajah** [comment]
Closing the issue with the PR  https://github.com/ballerina-platform/ballerina-lang/pull/25555

**Comment by NipunaRanasinghe** [comment]
Closing since the required tests are added with https://github.com/ballerina-platform/ballerina-lang/commit/67ed9577cd902c7a1a51aea5ca88476d5a4208ef.
