### ISSUE TITLE
[Testerina] Support mock object reset functionality

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#25588]
**Description:**
Support mock object reset functionality for object mocking. 
Use case: If one needs to set the mock behavior prior to a test case and reset it for other cases, the current mocking implementation doesn't support it.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The test framework has before and after methods that can be used to achieve this
