### ISSUE TITLE
Disable stdlib dependent docerina tests

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25596]
**Description:**
As a part of stdlib migration(https://github.com/ballerina-platform/ballerina-lang/issues/21313), we had to disable the following docerina tests which depend on stdlibs.

https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/e10ac3fca738a9d42928daf3dfedd0d5f271f731

**Comment by shehan360** [comment]
Closing as this issue is resolved.
