### ISSUE TITLE
Disabled stdlib dependent function invocation tests

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25595]
**Description:**
As a part of stdlib migration(https://github.com/ballerina-platform/ballerina-lang/issues/21313), we had to disable the following function invocation tests which depend on stdlibs.

https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/3691d0c0e31750230d781ae874d7956d25ac9145

**Comment by MaryamZi** [comment]
Enabled in https://github.com/ballerina-platform/ballerina-lang/commit/08638fc66a1fde0cd9a3bde39bd48033423981ec and https://github.com/ballerina-platform/ballerina-lang/commit/cfce4ee3734bb42eb7c92bb5ebe6d448f86ed4fd.
