### ISSUE TITLE
Disable stdlib dependent testerina tests

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25597]
**Description:**
As a part of stdlib migration(https://github.com/ballerina-platform/ballerina-lang/issues/21313), we had to disable the following testerina tests which depend on stdlibs.

https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/1684f8e4236e6b4e8b43340a0fb03065416c3d82
https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/01f03a69c5a50dfc3e06549f7f1b184fd21f4a5b
https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/4786377abb9fcafc1179c3495f4fb288340aa597

**Comment by Dilhasha** [comment]
Tracked in https://github.com/ballerina-platform/ballerina-lang/issues/26065
