### ISSUE TITLE
Disabled stdlib dependent XML literal tests

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25601]
**Description:**
As a part of stdlib migration(https://github.com/ballerina-platform/ballerina-lang/issues/21313), we had to disable the following XML literal tests which depend on stdlibs.

https://github.com/ballerina-platform/ballerina-lang/pull/25567/commits/c3dfbfca39e05bc936e32ccc846eda55cc4a7b70

**Comment by MaryamZi** [comment]
Enabled in https://github.com/ballerina-platform/ballerina-lang/commit/ff83b761c69a17a3b0b86897b9c9d4769b168813.
