### ISSUE TITLE
Disable stdlib dependent test cases in ballerina lang

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#25602]
Description:
As a part of stdlib migration(#21313), we had to disable the following tests which depend on stdlibs.

https://github.com/ballerina-platform/ballerina-lang/issues/25592
https://github.com/ballerina-platform/ballerina-lang/issues/25593
https://github.com/ballerina-platform/ballerina-lang/issues/25594
https://github.com/ballerina-platform/ballerina-lang/issues/25595
https://github.com/ballerina-platform/ballerina-lang/issues/25596
https://github.com/ballerina-platform/ballerina-lang/issues/25597
https://github.com/ballerina-platform/ballerina-lang/issues/25598
https://github.com/ballerina-platform/ballerina-lang/issues/25600
https://github.com/ballerina-platform/ballerina-lang/issues/25601

**Comment by niveathika** [comment]
Closing this as all tests cases are enabled now or moved to distribution repository.
