### ISSUE TITLE
Re-enable disabled interop test case

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25631]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/javainterop/basic/object_test.bal#L105

This is disabled in `class-change` branch and when it's merged with master we need to re-enable this test case.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
This is enabled in the master
