### ISSUE TITLE
Add language server support for module-class-defn and object constructor expressions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25643]
**Description:**
$title. This may also include removing support for old object type definitions and abstract object definitions.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing the issues since the support has been added
