### ISSUE TITLE
Add Ballerina debugger support for module-class-defn and object constructor expressions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25644]
**Description:**
$subject.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Please note VariableVisibilityTest is disabled with https://github.com/ballerina-platform/ballerina-lang/pull/25637/commits/bb8ab74d5df43f04d340e68814d56f450d800876

**Comment by NipunaRanasinghe** [comment]
> Please note VariableVisibilityTest is disabled with [bb8ab74](https://github.com/ballerina-platform/ballerina-lang/commit/bb8ab74d5df43f04d340e68814d56f450d800876)

@rdhananjaya Ack! will look into it
