### ISSUE TITLE
Change the URL of the Deployment API Docs Modules to Reflect BallerinaX

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25671]
**Description:**
We need to change the URL of the Deployment API Docs Modules to indicate that they are from the "BallerinX" GitHub organisation as shown below.

<img width="1680" alt="Screenshot 2020-07-23 at 11 16 35" src="https://user-images.githubusercontent.com/11707273/88256348-b92da500-ccd8-11ea-91e3-202716eb837f.png">

This should be done for both 1.2.x and Swan Lake versions.

**Suggested Labels:**

**Suggested Assignees:**

**Related Issues:**

- https://github.com/ballerina-platform/ballerina-lang/issues/24908
- https://github.com/ballerina-platform/ballerina-lang/issues/24914

**Comment by shehan360** [comment]
The new URL structure contains the orgName. Hence closing this issue.
