### ISSUE TITLE
Feature request - enhance variable casting

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#25689]
**Description:**
I would like to write following piece of code in ballerina:
```ballerina
int xyz =  ( <MyRecord> myVar).myField; 
```

**Steps to reproduce:**
N/A
**Affected Versions:**
1.2.8
**OS, DB, other environment details and versions:**

**Comment by MaryamZi** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/29453. Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/30031.
