### ISSUE TITLE
Control how json is encoded/decoded from/to records

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#25681]
**Description:**
This a feature request.
We need more control over how json values are encoded/decoded from/to records:
following are useful customisations:

- field name of json payload and record could be different.
- data type of json payload and record could be different.
- If the field is empty we should be able to omit from the encoded json ( e.g. please check what `omitempty` tag does in golang)
- better control over how date/time are serialised.
- ability to ignore fields in a record (even if it has a value) when encoding a json.
- ability to transform/format values when encoding a json. (e.g. `apointment.dayOfWeek = 6 -> {"dayOfWeek":"Saturday"}`)
 
**Steps to reproduce:**
N/A
**Affected Versions:**
1.2.8
**OS, DB, other environment details and versions:**
N/A
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This is beyond language design. We need projection API (a new stdLib) to support this. 
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.

**Comment by ramith** [comment]
But these are important features for practical use of data seriazliation regardless its coming from lang or stdlib.
