### ISSUE TITLE
Request support for compiler extension execution via build args

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#25687]
**Description:**
As per the new code2cloud spec we need to able to trigger compile extensions via build args. 
For instance, `ballerina build -a --cloud=k8s` command should trigger the kubernetes compiler extension. The args should be configurable to match the extension to trigger.

```
ballerina build -a --cloud=k8s 
ballerina build -a --cloud=lambda
```

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This is done with https://github.com/ballerina-platform/ballerina-lang/pull/27949
