### ISSUE TITLE
Feature request - Enhance how we can invoke functions

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#25686]
**Description:**
I would like to write following piece of code in ballerina:
``` ballerina 
    int x = function() returns int {
        return 0;
    }();
```

**Steps to reproduce:**
N/A
**Affected Versions:**
1.2.8
**OS, DB, other environment details and versions:**
N/A

**Comment by hasithaa** [comment]
This is not supported in the spec. Hence we deprioritize this for now. This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
