### ISSUE TITLE
Builtin symbols defined for different types of maps

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#25688]
See https://github.com/ballerina-platform/ballerina-lang/blob/2d85ecc6a3817026bf83976f25f8ec8f8de198c3/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java#L232

There are arbitrary map types created and defined as builtin symbols. Do we need to do that? Having them for convenience is fine. But is there a need to define the symbol? Also what's the default builtin type to be used for maps? Is it `map<any|error>`?

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
