### ISSUE TITLE
Error when pulling balleirna slp1 using update tool

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#25717]
**Description:**

I installed ballerina version `1.2.8` using `homebrew` and used to the update tool command `ballerina dist pull slp1` to get the ballerina version `Swan Lake Preview 1`. The distribution got pulled successfully and got set as my current ballerina version. When I try to build a ballerina module with tests I get the following error. 

<img width="833" alt="Screen Shot 2020-09-10 at 4 03 04 PM" src="https://user-images.githubusercontent.com/39673615/92718197-21b30d00-f37f-11ea-92d1-d1e0007a31df.png">

```
Running Tests
error: unable to run the tests: Cannot run program "/usr/local/Cellar/ballerina/1.2.8/libexec/bin/../distributions/ballerina-slp1/../../dependencies/jdk8u202-b08-jre/bin/java": error=2, No such file or directory
```

**Comment by suganyasuven** [comment]
As of now, could you please remove the java dependencies inside the dependencies directory?

**Comment by aashikam** [comment]
I don't have this anymore. :) I removed this and installed 1.2.8 from the pkg installer on the same day.

**Comment by suganyasuven** [comment]
> I don't have this anymore. :) I removed this and installed 1.2.8 from the pkg installer on the same day.

Did you encounter any issue with the mac installer? In StackOverflow, someone found an issue with the installer. https://stackoverflow.com/questions/64287049/ioexception-when-trying-to-run-new-ballerina-project/64375579?noredirect=1#comment113871423_64375579

**Comment by aashikam** [comment]
No. It worked fine for me.

**Comment by suganyasuven** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-update-tool/pull/49. Hence closing the issue.
