### ISSUE TITLE
Type definitions can override eachother when one type definition is a alias to a built-in type

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25742]
**Description:**
```ballerina

import ballerina/io;

type A int;

type A record { // This overrides the previous 'A' type 
    int i = 0;
};

public function  main() {
    A a = { i: 33 };
    io:println(a);
}
```

Cause of this is for the `isRedeclaredSymbol` function, first A has a different owner (annotation pkg), and second A have the current pkg as the owner.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed on slbeta3. Now results in a redeclared symbol error.
