### ISSUE TITLE
Add an example to show off how json/xml content could be asserted.

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#25754]
**Description:**
Given that ballerina natively supports json, it would make sense to show off how json content can be asserted.
please have a look at below for inspiration: 
``` https://godoc.org/github.com/stretchr/testify/assert#JSONEq ```

Probably we could improve the existing example:
``` https://ballerina.io/learn/by-example/testerina-assertions.html ```

**Steps to reproduce:**
N/A
**Affected Versions:**
1.2.8

**Comment by Dilhasha** [comment]
Also added BBE improvements and latest improvements to assertion diff functionality for the Swan Lake release.
