### ISSUE TITLE
Implement error-match-pattern in parser

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#25759]
**Description:**
$subject. It is currently implemented under the functional match pattern.

**Affected Versions:**
swan lake

**Comment by KavinduZoysa** [comment]
According to spec, this kind of pattern should be parsed.

ex:
```
    match v {
        error MyError ("Message", var a) => {
            return "match1";
        }
    }
```

But it does not parse properly.
![match-error](https://user-images.githubusercontent.com/28332708/94184616-cb3ae800-fec1-11ea-9f1c-8d676d7725c6.png)

**Comment by rdulmina** [comment]
> According to spec, this kind of pattern should be parsed.
> 
> ex:
> 
> ```
>     match v {
>         error MyError ("Message", var a) => {
>             return "match1";
>         }
>     }
> ```
> 
> But it does not parse properly.
> ![match-error](https://user-images.githubusercontent.com/28332708/94184616-cb3ae800-fec1-11ea-9f1c-8d676d7725c6.png)

Yes, this will be fixed along with this issue.
