### ISSUE TITLE
Add tests for predeclared langlibs

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#25757]
**Description:**
Currently, there is no usage of following predeclared langlibs. Need to add predeclared tests for those langlibs when introducing new functions. 
- error
- map
- object
- stream
- table
- typedesc
- xml

https://github.com/ballerina-platform/ballerina-lang/pull/25480#discussion_r485518428

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
