### ISSUE TITLE
Tooling support for isolated functions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25771]
**Description:**
`isolated` functions will be introduced with https://github.com/ballerina-platform/ballerina-lang/pull/25761.

With this, the `isolated` qualifier can be used with functions, object methods, service resources, etc.

e.g.,
```ballerina
isolated function foo() {
}
```

https://github.com/ballerina-platform/ballerina-lang/pull/25763 will add it for function type descriptors and anonymous functions.

Lang issue - https://github.com/ballerina-platform/ballerina-lang/issues/24907

**Comment by nadeeshaan** [comment]
Fixed in latest master. Hence closing the issue
