### ISSUE TITLE
Debugger: Stepping over at the last statement ends the debugging session abruptly 

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#25775]
**Description:**
I don't know if I'm the only one experienced this one.
But it seem if I keep stepping over statements in  a function and If I step over last line (e.g. return statement in the function) instead of returning/continuing to the function which invoked current function; debugger will resume the program. 
This is not consistent with common behaviour (which we enjoy in other languages/debuggers) and is really annoying if you are in middle of a debugging session.

**Steps to reproduce:**
This happens intermittently for a simple code fragment things seems to work as expected.

**OS, DB, other environment details and versions:**
MacOS, Visual Code Plugin, Ballerina 1.2.8

**Related Issues (optional):**

**Suggested Labels (optional):**
**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Hi @ramith can you share the code a snippet to reproduce.

**Comment by NipunaRanasinghe** [comment]
@ramith This seems to be already discussed in the ballerina google group mail thread "Fixing stepping over async call lines issue in ballerina debugger" as well as https://github.com/ballerina-platform/ballerina-lang/issues/18427, as an effect of dynamic breakpoints used by the debugger to handle stepping over codes lines with asynchronous calls. 
This is already added in our debugger road map for the swan lake release (https://github.com/ballerina-platform/ballerina-lang/issues/24971) and we'll try to provide a fix in a coming milestone release.

**Comment by ramith** [comment]
what are the chances of seeing this in ballerina 1.2.X series? ( that is if we are shipping a new version in 1.2.x)
