### ISSUE TITLE
Add/Improve BBEs for new integration features

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#25805]
We have to consider adding BBEs for below cases
- limit clause
- order by clause
- on-fail clause 
- Do statement
- fail expression

**Comment by pcnfernando** [comment]
Added fail statement bbe in https://github.com/ballerina-platform/ballerina-distribution/pull/833
Added on fail bbe in https://github.com/ballerina-platform/ballerina-distribution/pull/832
Improved transaction bbe in https://github.com/ballerina-platform/ballerina-distribution/pull/819
