### ISSUE TITLE
Add trasactional support to func type desc and anon func.

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#25807]
**Description:**
(https://github.com/ballerina-platform/ballerina-spec/issues/597)

**Suggested Assignees (optional):**
@rdulmina

**Comment by rdulmina** [comment]
Added parser support with  #25808

**Comment by lasinicl** [comment]
Added tests to verify this in https://github.com/ballerina-platform/module-ballerinai-transaction/pull/4
