### ISSUE TITLE
if .. is ..{} statements not working for records with same properties.

### ISSUE THREAD

**Issue by whizsid** [ballerina-platform/ballerina-lang#25830]
**Description:**

I have defined two `record`s with same properties. But I can not check for their types with `if .. is..` statement. After that I used different property names as a boilerplate. But I think the record name should also be added to the token.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public type Github record {
    int bar;
    string foo;
};

public type Twitter record {
    int bar;
    string foo;
};

public function main() {
    Twitter twitter = {bar: 20, foo: "asa"};

    Twitter | Github twitterOrGithub = twitter;

    if twitterOrGithub is Github {
        io:println("Github");
    } else {
        io:println("Twitter");
    }
}
```
https://play.ballerina.io/?gist=06500ef4c555034b08a1316ecd172482&file=play.bal

Error:-

```
Compiling source
        app.bal
error: .::app.bal:18:8: unnecessary condition: expression will always evaluate to 'true'
```

**Affected Versions:**

```
jBallerina 1.2.0
Language specification 2020R1
Ballerina tool 0.8.5
```

**Comment by rdhananjaya** [comment]
Ballerina is a structurally typed language hence this is the expected behavior. 
Ballerina does not consider name of the type as part of the type.

In Ballerina swanlake track there is a new feature that allow us to distinguish type by name. This is called `distinct` types and only supported for `object` and `error`.

**Comment by whizsid** [comment]
Thank you @rdhananjaya for the response. I will close this. Because I can handle it by using different property names and this is not a bug.
