### ISSUE TITLE
Add support to new VarKind SYNTHETIC in the jvm backend

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#25855]
**Description:**

With #25695 we have introduced a new VarKind SYNTHETIC to identify the compiler generated variables in the backend.

Need to support this new varkind all the places where we use LOCAL except in debug variable generation.

**Steps to reproduce:**
N/A

**Affected Versions:**
slp4

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
#24973

**Comment by riyafa** [comment]
This does not affect the BirVariableOptimizer as it optimizes for temp variables and optimizations cannot be done for synthetic variables as they behave like local variables in the BIR
