### ISSUE TITLE
Stored Procedure call fails for low privileged users in SLP-03

### ISSUE THREAD

**Issue by Shairam** [ballerina-platform/ballerina-lang#25869]
**Description:**
The following error is thrown when a low privileged user tries to call a Stored procedure in a MySQL DB. 

```
[2020-09-17 12:10:15,153] SEVERE {b7a.log.crash} - ABORTED: Register stored proc failed: Error while executing SQL query: {CALL Register( ? ,  ? ,  ? ,  ? ,  ? ,  ? )}. Unable to parse SQL call query to get metadata for OutParameters of procedure, 'Register', Illegal operation on empty result set. 
io.grpc.StatusRuntimeException: ABORTED: Register stored proc failed: Error while executing SQL query: {CALL Register( ? ,  ? ,  ? ,  ? ,  ? ,  ? )}. Unable to parse SQL call query to get metadata for OutParameters of procedure, 'Register', Illegal operation on empty result set.
```

Below is how the client connection is made: 
```
function createJdbcClient() returns jdbc:Client|sql:Error {
    jdbc:Client|sql:Error jdbcClient =
          check new (url = io:sprintf("jdbc:mysql://%s:%d/%s?noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true",
            testDbHost, testDbPort, DbName),
            user = dbUserName,
            password = dbUserPassword,
            connectionPool = {maxOpenConnections: 50},
            options = {properties: {"useSSL": false}}
          );
    return jdbcClient;
}
```
Following are the GRANTS given for the low privileged user:
```
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON `test_db`.* TO 'testUser'@'%';
```
Also to highlight, the stored procedure is created by the root user. And when the procedure is called by the root user, it seems to work fine.

**Affected Versions:**
Ballerina [SLP-03].

**OS, DB, other environment details and versions:**
MySQL version 5.7 is used.

**Comment by Shairam** [comment]
Below are some findings. 
When the following function is called `java.sql.DatabaseMetaData.getProcedureColumns` from ballerina side by a low privilege user, an empty result set is returned since the user has no access to `mysql.proc` database.

**Comment by niveathika** [comment]
Background into this issue, When using OutParameters in SQL Procedurecalls, user have to define the SQL Type of the parameter explicitly, However, in order for the higher usability for a ballerina user, we tried to fetch this type information using a MetaDataCall before actually executing the procedure call.

I have looked into it and there are few solutions that I tried,
1. Using `noAccessToProcedureBodies` flag [[1](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html)]
    This would not work for the use case, since this will return data type of all the parameters as VARCHARS. We need actual datatypes of the parameters.

2. Requesting user to have access to `mysql`.`proc` table.
    This table consists of metadata information of procedure calls from all databases. This is a very serious security flaw since we do not want the user to know anything about any other databases procedure calls.

3. Not using metadata fetch at all & specifying the user to define the SQL type in the OutParameter type
   Option1: Having multiple subtypes of out parameter
```ballerina
     public class CharOutParameter {
          public isolated function get(typedesc<anydata> td) returns td|Error external;
    }
     public class VarcharOutParameter {
           public isolated function get(typedesc<anydata> td) returns td|Error external;
     }
 ```

  Option 2: Similar to InoutParameter, make user mandatory to initialise out parameter with a SQL Value
```ballerina
     public class OutParameter {
    Value out;

    public isolated function init(Value out) {
        self.out = out;
    }

    public isolated function get(typedesc<anydata> td) returns td|Error external;
}

 ```
Usage
```
sql:OutParameter paramId = new sql:OutParameter(new sql:VarcharValue)
sql:OutParameter paramId = new sql:OutParameter(1)  // This will be marked as SQL INTEGER type
```

@daneshk @jclark Your thoughts on this? 

Please find the design [document](https://docs.google.com/document/d/1d0-yLkJdvI4rZo4mKd5ckizWCGT3wPRZqRHEWpxz75I/edit#) for further information into the design of procedures API.

**Comment by niveathika** [comment]
@all As per the offline discussion, we have decided to go ahead with the Option 1 and remove metadata fetch in the call() API
