### ISSUE TITLE
Improve how workers are modeled in the compiler

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#25875]
Currently, a worker gets modeled as a lambda function and its invocation.
```ballerina
worker w1 {
      io:println("In worker w1");
}
// gets modeled as 
function () 0w1 = function () {
     io:println("In worker w1");
};
future w1 = start 0w1();
```
The issue with this is in the compiler, it makes it hard to figure out the relationship between these nodes as a worker. Need to be improve this to be able to figure out the other related components given any single component of the above model. e.g., given the lambda function, figure out that this is the body of the worker `w1` and get the symbol of `w1`.

**Comment by hasithaa** [comment]
Even though this is not the correct way to model this, This design works without an issue. Hence this issue has been marked as "Deferred" and will be revisited in the future when resources are available.
