### ISSUE TITLE
Migrate OpenApi code 

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#25888]
**Description:**
As Ballerina OpenApi depends on std libs, these need to be migrated to a new repo
- [x] Remove it from ballerina-lang jdk11 branch
- [x] Migrated to a new repo

**Comment by lnash94** [comment]
- [ ] Create new repository  ballerina-platform/ballerina-openapi
- [ ] Move components  (ballerina/openapi module in stdlib, Ballerina-validator , Ballerina openapi cli , Integration tests, OpenAPI LS extension)
- [ ] Remove any dependencies with other modules
- [ ] OpenAPI LS support remove and existing code from LS
- [ ] After the migration will create an Language Server Extension
- [ ] Github actions for pushing artifacts to GitHub packages using 
- [ ] Update the distribution repo with OpenAPI artifacts
- [ ] Add an integration test to verify if OpenAPI features got packed
