### ISSUE TITLE
Move observability extensions

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#25887]
**Description:**
As observability extensions depend on std libs, these  need to be migrated to a new repo
- [x] Remove it from ballerina-lang jdk11 branch
- [x] Migrated to a new repo

**Comment by nadundesilva** [comment]
Observability extensions had been moved to separate repositories.
* https://github.com/ballerina-platform/module-ballerinax-prometheus
* https://github.com/ballerina-platform/module-ballerinax-jaeger
Hence closing the issue.
