### ISSUE TITLE
Integrate Katacoda to the Playground

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25897]
**Description:**
Currently, the Ballerina Playground[1] looks neglected. We need to check on integrating Katacoda[1] to our Playground[2] because Katacoda even has plugins to integrate with VSCode.

[1] https://play.ballerina.io/
[2] https://www.katacoda.com/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing this as the playground direction has changed with swanlake.
