### ISSUE TITLE
Fix the Lag in Loading API Docs Home Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25895]
**Description:**
There is a lag in loading the API Docs after clicking on its link[1]. This causes to load only a part of the website and breaks the user experience by giving the impression that that's the end of the page.

[1] https://ballerina.io/v1-2/learn/api-docs/ballerina/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shehan360** [comment]
Outdated.
