### ISSUE TITLE
Tooling support for `final` fields in an object

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#25909]
**Description:**
$title. This replaced `readonly` fields with https://github.com/ballerina-platform/ballerina-lang/pull/25784.

For records, we still have `readonly` fields - https://github.com/ballerina-platform/ballerina-lang/issues/23313.

Allowed with classes and object constructor expressions, but not object type descriptors.

```ballerina
class Foo {
   final int i;

   function init(int i) {
      self.i = i;
   }
}
```

**Comment by nadeeshaan** [comment]
This has been addressed in the master. Hence closing the issue
