### ISSUE TITLE
Represent runtime modules as JVM modules with JDK 11 support

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#25916]
**Description:**
With JDK 11 support with SLP5, we need to look at how we can represent runtime modules (executable jar) as JVM modules.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#22804

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by riyafa** [comment]
Refer to the [mail](https://groups.google.com/g/ballerina-dev/c/5CHew7Ahhtk/m/X45ssdmLCgAJ) for the discussion on the topic. It has been concluded to stick with the uber jar for now.
