### ISSUE TITLE
Add more granular set of APIs for the semantic model

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25934]
**Description:**
Some suggestions:

Symbols Related:
- [x] visibleSymbols(fileName, linePosition)
- [ ] visibleSymbols(fileName, linePosition, symbolKind)
- [x] symbol(fileName, linePosition)
- [x] moduleLevelSymbols()
- [ ] moduleLevelSymbols(fileName, linePosition)

Diagnostic related:
- [x] diagnostics()
- [ ] diagnostics(fileName)
- [ ] diagnostics(diagKind)
- [ ] diagnostics(fileName, diagKind)
- [x] diagnostics(lineRange)
- [ ] diagnostics(lineRange, diagKind)

**Comment by pubudu91** [comment]
Provide another API for filtering out symbols based on the context. May have to consider providing a public API for Types. For example, for an assignment statement, providing suggestions for completion in the RHS. To filter out symbols based on the expected type in the LHS, need to be able to basically type check the symbol types against the expected type.

**Comment by mohanvive** [comment]
We are no longer considering above requirement.
