### ISSUE TITLE
TextRange and LineRange information is incorrect in diagnostic locations

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#25933]
See https://github.com/ballerina-platform/ballerina-lang/blob/ee83d258a4a7e95d1e397dcc334793e9fe4c9603/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/diagnostic/BLangDiagnosticLocation.java#L38

The values set for the columns in line range and the offsets set in text range are incorrect. The text range is supposed to be the absolute position as an offset from (0, 0).

**Comment by SupunS** [comment]
LineRange and TextRange distinguishes as follows:
```
LineRange --> Verbose line number information
|_ filename
|_ startLine
|    |_line (line number)
|    |_offset (column of the line)
|_ endLine
     |_line (line number)
     |_offset (column of the line)

TestRange --> Offsets relative to the (0,0) location of the file
  |_startOffset
  |_endOffset
  |_length
```
