### ISSUE TITLE
Interop method in Object mapping to overloaded instance methods 

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#25943]
**Description:**
When an interop method in an object maps to instance methods of which one accepts self and another that doesn't then there's a confusion on which is the correct method. Hence currently it gives an error. But to support both it should be possible to specify the desired method by using the `paramTypes` field in the interop method annotation. This `paramType` for method accepting self could be `self`.

**Steps to reproduce:**
consider following instance methods in the `InstanceMethods` class:
```
  public int getInt(int x) {
        return x;
    }
    public int getInt(ObjectValue objectValue, int x) {
        return ((Long) objectValue.get(new BmpStringValue("age"))).intValue();
    }
```
If it is used in the `Person` class as follows:
```
public class Person {
    public function getInt(handle h, int x) returns int = @java:Method{
        'class:"org/ballerinalang/nativeimpl/jvm/tests/InstanceMethods"
    } external;
}
```
Then this will give the following error:
```
{ballerina/java}OVERLOADED_METHODS 'Overloaded methods cannot be differentiated. Please specify the parameterTypes for each parameter in 'paramTypes' field
```
But we cannot specify `self` in the `paramTypes` field currently and it needs to be supported or any other solution needs to be provided to allow having such two such methods.

**Affected Versions:**
SP4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
N/A

**Comment by manuranga** [comment]
this is there to support, be able to wrap sanded java objects as ballerina objects without changing java code to have `ObjectValue`

opt 1
====
`getInt(ObjectValue objectValue, int x)` should get the precedence, `getInt(int x)` should get mapped only if first one is not available. if both are missing it's an error.

opt2
===
add a flag form ballerina side to send `ObjectValue`.
