### ISSUE TITLE
Improve taint analysis for object method delegates

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25962]
**Description:**
```ballerina
Obj o = new();
function () returns int delegate = o.foo;
```

In a scenario like above, since we are capturing the receiver `o` in the closure, there is no way for us to keep on track of the tainted status of return values of the `delegate` function.  

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
We are removing the current taint analysis implementation with #30981, Hence closing this issue.
