### ISSUE TITLE
Completions don't group related constructs together

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#25975]
See the following:
![Peek 2020-09-21 15-43](https://user-images.githubusercontent.com/6260009/93755726-65c8cc00-fc21-11ea-94aa-3e46e0986128.gif)

In the above case, `a` and `b` are grouped together while to find `c`, you have to scroll down.

**Comment by nadeeshaan** [comment]
This has been addressed and changes were merged to master (to be reflected in sw-alpha1). Hence closing the issue
