### ISSUE TITLE
Formatting removes intended line spacing

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#25976]
**Description:**
Consider the following source snippet and when we format it, formatter removed the intended line spacing as shown in the second snippet.

Original Source
```
import ballerina/io;

public function main() {
    int[] a = [];
    io:println(a.length());

    int[] b = [1, 2, 3, 4, 5, 6, 7, 8];
}

```

Source After format
```
import ballerina/io;

public function main() {
    int[] a = [];
    io:println(a.length());
    int[] b = [1, 2, 3, 4, 5, 6, 7, 8];
}


```

**Affected Versions:**
SLP4-SNAPSHOT at least

**Comment by SupunS** [comment]
Fixed with #26391
