### ISSUE TITLE
Suggestions support for predeclared modules.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#25983]
With https://github.com/ballerina-platform/ballerina-lang/issues/25463, all lang lib module which ends with a keyboard now Predeclare as module prefixes. 

This has to support in code suggestions in Language Server implementation. 
![vscode-1600689355121](https://user-images.githubusercontent.com/1356214/93764126-38374f00-fc30-11ea-8027-ec023b0ffdf7.gif)

**Comment by nadeeshaan** [comment]
Will be addressed along with #26243
