### ISSUE TITLE
JBallerina Compiler failed to generate BIR for the negate operator testcase.

### ISSUE THREAD

**Issue by shubhamnarlawar** [ballerina-platform/ballerina-lang#25982]
**Description:**
While compiling below neg.bal testcase, jballerina compiler failed to produce BIR

-----------------------------------------------neg.bal----------------------------------------------------------------------
public function main () {
int a;
int b = 2;
a = -b;
}
-------------------------------------------------------------------------------------------------------------------------------

**Steps to reproduce:**
a. Extract the jballerina distribution - https://drive.google.com/file/d/1Z8t157ddnPFp3nUOn6qjpjUSIkr41BLB/view?usp=sharing

b. Generate BIR from above testcase

**Affected Versions:**
Ballerina Swan Lake Preview 2
Language specification v2020-06-18

**OS, DB, other environment details and versions:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Java version used for setting $JAVA_HOME = java-1.8.0-openjdk-amd64

**Comment by rdhananjaya** [comment]
This is fixed in Swan Lake beta-1

**Comment by rdhananjaya** [comment]
```ballerina
import ballerina/io;
public function main() {
    int a;
    int b = 2;
    a = -b;

    io:println(a);
}
```
prints `-2` as expected

**Comment by rdhananjaya** [comment]
This looks like something to do with generating BIR for nBallerina backend.
Verified that --dump-bir work fine.

**Comment by shubhamnarlawar** [comment]
The fix was added in later phase of jballerina distribution!

**Comment by rdhananjaya** [comment]
@shubhamnarlawar then is it ok to close this issue?

**Comment by shubhamnarlawar** [comment]
> @shubhamnarlawar then is it ok to close this issue?

Yes Please!
