### ISSUE TITLE
Autocompletion for @strand and @java annotations do not work

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#25980]
**Description:**
Autocompletion for `@strand` and `@java` annotations do not work in the VSCode IDE plugin

**Steps to reproduce:**

Try typing the following examples and look for autocompletion for the `@strand` and `@java` annotations
- https://ballerina.io/swan-lake/learn/by-example/threads-and-strands.html
- https://ballerina.io/swan-lake/learn/by-example/create-java-objects.html

**Affected Versions:**
SP4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
N/A

**Comment by nadeeshaan** [comment]
Fixed in slp5. Hence closing the issue.
