### ISSUE TITLE
[Query Expressions] Formatting not works in VSCode Plugin

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#25988]
**Description:**
Code formatting not works for query expressions and streams in VSCode plugin.

**Steps to reproduce:**
Please checkout the Query and streams examples.
- https://ballerina.io/swan-lake/learn/by-example/query-expression.html
- https://ballerina.io/swan-lake/learn/by-example/query-expression-to-stream.html
- https://ballerina.io/swan-lake/learn/by-example/query-expression-to-string.html
- https://ballerina.io/swan-lake/learn/by-example/query-expression-to-table.html
- https://ballerina.io/swan-lake/learn/by-example/query-expression-to-xml.html
- https://ballerina.io/swan-lake/learn/by-example/query-action.html
- https://ballerina.io/swan-lake/learn/by-example/query-join.html
- https://ballerina.io/swan-lake/learn/by-example/streams.html

**Comment by IrushiL** [comment]
Fixed with PR: https://github.com/ballerina-platform/ballerina-lang/pull/26391
