### ISSUE TITLE
Incorrect mandatory requirement for the qualifier in EnumDeclarationNode

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26019]
**Description:**
The `qualifier` is specified as a mandatory attribute in the parser's `EnumDeclarationNode`. But according to the specification [1], it should be made optional.

[1] https://ballerina.io/ballerina-spec/spec.html#module-enum-decl

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Preview 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Need to make the qualifiers a list, similar to other places where qualifiers are allowed
