### ISSUE TITLE
Disabled failing LS tests for completion support of isolated/function keyword

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#26017]
**Description:**

Failing isolated/function keyword completion support LS tests were disabled with following commits. 

- ebb4f58 in PR #25778
- 3a29197 in PR #26888

**Summary of disabled tests are as follows.**

org.ballerinalang.langserver.completion.latest.ClassDefContextTest

- config12.json
- config13.json

org.ballerinalang.langserver.completion.latest.TypeDescContextTest

- function_typedesc16.json
- function_typedesc17.json
- function_typedesc18.json
- function_typedesc19.json

org.ballerinalang.langserver.completion.latest.ExpressionContextTest
- anon_func_expr_ctx_config1a.json
- anon_func_expr_ctx_config1b.json
- object_constructor_expr_ctx_config1.json

**Comment by nadeeshaan** [comment]
Will be addressed along with #26455

**Comment by lochana-chathura** [comment]
Issue description updated.

**Comment by malinthar** [comment]
Blocked by: https://github.com/ballerina-platform/ballerina-lang/issues/31382

**Comment by lochana-chathura** [comment]
We can use the following API introduced in #31762 to access the leading invalid tokens.
https://github.com/ballerina-platform/ballerina-lang/blob/1dc0f3d9dcef94a4bad7a01a997f071f6b7bc687/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/Node.java#L156

i.e. `node.leadingInvalidTokens()` will give the qualifier list.

**Comment by malinthar** [comment]
subtask of https://github.com/ballerina-platform/ballerina-lang/issues/30685
