### ISSUE TITLE
Predeclared langlibs are not work properly with testerina

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#26049]
**Description:**
Give an error as `redeclared symbol 'int'`
when declaring below function in ballerina test
```ballerina
import ballerina/lang.'int;
    
function value() {
    int|error i2 = 'int:fromString("100");
}
```

**Comment by MaryamZi** [comment]
I believe this is already being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/25990.
