### ISSUE TITLE
Cannot assign nil to error cause

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#26056]
**Description:**
$subject.

According to spec, 

```
error-constructor-expr := error [error-type-reference] ( error-arg-list )
error-arg-list := positional-arg [, positional-arg] (, named-arg)*
```
and

`The first positional-arg is of type string and specifies the error message; the second positional-arg, if present, is of type error?, with a default of nil, and specifies the cause.`

**Steps to reproduce:**
`error e = error("Message", ());`

compile error :
incompatible types: expected 'error', found '()'

**Affected Versions:**
slp3

**Comment by lochana-chathura** [comment]
Related issue: #26341

**Comment by mohanvive** [comment]
Closing the issue since it is fixed in master now.
