### ISSUE TITLE
Move integration tests for Testerina which use standard libs to distribution repository

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#26065]
**Description:**
Move integration tests for Testerina which use standard libs to distribution repository

- [x] Basic Cases Test - Config Api Test
- [x] Services Test

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
https://github.com/ballerina-platform/ballerina-distribution/pull/922

**Comment by Ibaqu** [comment]
https://github.com/ballerina-platform/ballerina-distribution/pull/948
