### ISSUE TITLE
tsymbol of BObjectType is wrong for classes from external modules

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#26071]
**Description:**
tsymbol in BObjectType should be BClassSymbol if the variable is a class. This works for classes defined in the same module, but when the class is defined in another module the tsymbol is BObjectTypeSymbol.

**Steps to reproduce:**

1. Have the following code in a bal file.

```
import ballerina/cache;

# Test function
#
# + prsn - The stream
# + cacheCls - The cache class from cache module
public isolated function testPerson(Person prsn, cache:Cache cacheCls) returns string?|Person {
}

# Represents a person object
#
# + name - Name of the person
# + age - Age of the person in years
# + address - Address of the person
public class Person {
    public string name = "";
    public int age;
    public string address;

    # Get address of the person
    #
    # + return - New address of the person
    public function getAddress() returns string {
        return "new" ;
    }
}
```
2. Get the BLangPackage
3. Check functions->requiredParams->cacheCls->type->tsymbol which is BObjectTypeSymbol
4. Check functions->requiredParams->prsn->type->tsymbol which is BClassSymbol

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
@SupunS @pubudu91 Shall we fix this problem in the semantic API?

**Comment by pubudu91** [comment]
Had a quick glance at this and from the looks of it, the issue seems to be because we are creating the class type symbol with the `OBJECT` sym tag. Sort of looks like the BIR is not quite up-to-date with the class change. So when it reads a class symbol back from a BIR, it just sees an object type symbol and creates it.
