### ISSUE TITLE
Fix the Broken Links WRT Abstract Objects

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#26073]
**Description:**
We need to fix the broken links below WRT "Abstract Objects" in the IO, SQL, & HTTP modules.

<img width="1076" alt="Screenshot 2020-09-24 at 10 43 59" src="https://user-images.githubusercontent.com/11707273/94137214-b3447380-fe83-11ea-8c3a-5d8256766ac3.png">

<img width="1071" alt="Screenshot 2020-09-24 at 10 44 28" src="https://user-images.githubusercontent.com/11707273/94137234-ba6b8180-fe83-11ea-9f1a-d93ddc318678.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment]
This is the cause of the broken links: https://github.com/ballerina-platform/ballerina-lang/issues/26071

**Comment by praneesha** [comment]
@hasithaa - Can we check this as this needs to be fixed in the Compiler.

**Comment by praneesha** [comment]
@hevayo @shehan360 - This is fixed from the compiler side via #26071.

**Comment by praneesha** [comment]
This is fixed in the new API Docs design[1] now.

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/index.html#/
