### ISSUE TITLE
Change `Abstract Object` term to `Object types` in Module API docs

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#26086]
**Description:**
![Selection_191](https://user-images.githubusercontent.com/8381003/94220740-4bd00780-ff07-11ea-8d54-a40656055293.png)

https://dev.ballerina.io/swan-lake/learn/api-docs/ballerina/http/index.html#absobjects

**Affected Product Version:**
slp4

**Comment by shehan360** [comment]
This is fixed with: https://github.com/ballerina-platform/ballerina-lang/pull/28757
