### ISSUE TITLE
JDK11 disabled test cases

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#26082]
Following test classes have been disabled by PR https://github.com/ballerina-platform/ballerina-lang/pull/26077. 
These needs to be enabled/moved to relevant repository

Dev Tools
 - [x] AddCommandTest.java
 - [x] BuildCommandTest.java
 - [x] CompileFlagWithBuildCommandTest.java
 - [x] DependencyScopeTest.java
 - [x] ResolvingMavenDependenciesTest.java
 - [x] MavenSupportTest.java
 - [x] MavenResolverTest.java
 - [x] jballerina-debugger-integration-test/src/test/resources/testng.xml
 - [x] VariableVisibilityTest.java
 - [x] BasicCasesTest.java 
 - [x] InvalidDataProviderTestCase.java
 - [x] DisableTestsTestCase.java
 - [x] RerunFailedTest.java
 - [x] GroupingTest.java
 - [x] AnnotationAccessTest.java
 - [ ] TestReportTest.java

Language & Runtime
 - [x] CompilerPluginTest.java
 - [x] AnnotationAccessViaReflectTest.java
 - [x] AnnotationRuntimeTest.java
 - [ ] IconAnnotationTest.java
 - [x] LocalAnnotationTest.java
 - [x] AnnotationTests.java
 - [ ] FunctionPointersTest.java
 - [ ] FunctionSignatureInBaloTest.java
 - [x] VariableReturnTypesBaloTest.java
 - [ ] ObjectInBaloTest.java
 - [ ] RemoteObjectBaloTest.java
 - [x] DataflowAnalysisTest.java
 - [ ] MarkdownDocumentationTest.java
 - [x] ErrorTest.java
 - [ ] CheckedExprNegativeTest.java
 - [x] QuotedIdentifierTest.java
 - [x] ErrorVariableReferenceTest.java
 - [x] RecordVariableReferenceTest.java
 - [x] VariableReturnTypeTest.java
 - [x] HandleRefersNullTest.java
 - [ ] JavaCastTest.java
 - [x] ObjectTest.java
 - [ ] PrimitiveConversionsInFunctionParamsTest.java
 - [x] JavaVarargsTest.java
 - [x] BuiltinMethodTest.java
 - [ ] ObjectDocumentationTest.java
 - [ ] InvalidSyntaxParserTest.java
 - [x] AnonymousOpenRecordTest.java
 - [ ] RecordDocumentationTest.java
 - [ ] CommentStmtTest.java
 - [x] MatchStructuredRecordPatternsTest.java
 - [ ] PackageImportTest.java
 - [ ] ReturnStmtNegativeTest.java
 - [ ] VarDeclrSemanticTest.java
 - [ ] ErrorVariableDefinitionTest.java
 - [x] RecordVariableDefinitionTest.java
 - [ ] ListenerServiceTaintedStatusPropagationTest.java
 - [ ] TaintedStatusPropagationTest.java
 - [x] AnydataTest.java
 - [ ] FinalAccessTest.java
 - [ ] ServiceTypeTest.java
 - [ ] XMLLiteralWithNamespacesTest.java
 - [x] NotSoBasicWorkerTest.java
 - [ ] WaitActionsNegativeTest.java
 - [x] WaitForOneActionsTest.java
 - [ ] WorkerCallingFunction.java

Language Server & VSCOde
 - [x] tool-plugins/vscode build.gradle test task is skipped   -> No need as vscode is moved
 - [ ] langserver-core/src/test/resources/testng.xml

Standard Library
 - [x] HttpClientTest.java
 - [x] IOBasicTest.java
 - [x] jballerina-unit-test/src/test/resources/testng-jballerina.xml
 - [x] jballerina-unit-test/src/test/resources/testng-new-parser.xml

Following tests were disable when merging to master

https://github.com/ballerina-platform/ballerina-lang/commit/6d8b5c77f1a20f9a100f1c9f16b4c6f88463d55e

 - [x] LangLibArrayTest
 - [x] LangLibTableTest
 - [x] LangLibValueTest
 - [ ] ExpressionEvaluationNegativeTest
 - [ ] ExpressionEvaluationTest
 - [ ] ReadOnlyObjectBaloTest
 - [ ] BirVariableOptimizationTest
 - [ ] AccessTest
 - [ ] FieldAccessTest
 - [ ] OptionalFieldAccessTest
 - [ ] ListConstructorExprTest
 - [ ] MappingConstructorExprTest
 - [ ] RawTemplateLiteralTest.java
 - [ ] IsolationAnalysisTest
 - [ ] javainterop/RefTypeTests
 - [ ] VariableReturnTypeTest
 - [ ] JavaVarargsTest.java
 - [ ] FinalObjectFieldTest
 - [ ] ObjectEquivalencyTest 
 - [ ] ReadonlyObjectTest
 - [ ] ReadonlyRecordFieldTest 
 - [ ] ByteAsIntTest
 - [ ] MatchStmtConstPatternTest
 - [ ] MatchStatementSyntaxErrorsTest
 - [ ] CaptureBindingPatternTest
 - [ ] MatchStatementOnFailTest
 - [ ] LocksWithOnFailTest
 - [ ] LocksInServicesTest
 - [ ] TestReportTest.java

**Comment by keizer619** [comment]
This PR has enabled maven resolver issues, but packing does not happen properly. Need to revisit
https://github.com/ballerina-platform/ballerina-lang/pull/26150/files

**Comment by chiranSachintha** [comment]
- Have been enabled all the tests which are under the subject of `Following tests were disable when merging to master` (6d8b5c7)
- Have been enabled all the tests which are under the subject of `Language & Runtime` except
  - CompilerPluginTest
  - AnnotationAccessViaReflectTest
  - AnnotationRuntimeTest
  - LocalAnnotationTest
  - AnnotationTests
  - VariableReturnTypesBaloTest
  - DataflowAnalysisTest
  - ErrorTest
  - QuotedIdentifierTest
  - ErrorVariableReferenceTest
  - RecordVariableReferenceTest
  - VariableReturnTypeTest
  - ObjectTest
  - MatchStructuredRecordPatternsTest
  - RecordVariableDefinitionTest
  - AnydataTest
  - NotSoBasicWorkerTest
