### ISSUE TITLE
[Formatter] Implement the support for range formatting

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26090]
**Description:**
The core formatting implementation needs to support range formatting. As of now, only full document formatting is supported.

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Preview 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Added with https://github.com/ballerina-platform/ballerina-lang/commit/3c348be35952e47f39f21a90d71c48818ee31378
