### ISSUE TITLE
Formatting `function` with inline `record` return fails

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#26103]
**Description:**
Consider following code snippet for formatting;

**Before**
```ballerina
public function next() returns record {|int value;|} {
    return {};
}
```
**After:**
```ballerina
public function next() returns record {|
int value;
|} {
    return     {};
}
```

**Affected Versions:**
2.0.0-SLP4

**Comment by IrushiL** [comment]
Fixed with PR: https://github.com/ballerina-platform/ballerina-lang/pull/26391
