### ISSUE TITLE
Need to Fix the Workflow to Generate the Links Properly in MD Files of 1.2.x Release Tags

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#26124]
**Description:**
Need to fix the workflow to generate the "Overview of jBallerina", "Bugs" & "Improvements" links correctly in the MD File of the Tags (e.g.,[1]) for 1.2.x versions.

Currently, the links were fixed manually by editing the file but they were generated broken from the workflow as shown below.

<img width="1440" alt="Screenshot 2020-09-28 at 10 02 19" src="https://user-images.githubusercontent.com/11707273/94394051-08c99a80-017a-11eb-9fba-a230cf8549cd.png">

This was fixed manually for 1.2.8 
[1] https://github.com/ballerina-platform/ballerina-lang/releases/tag/v1.2.8

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Now release notes are not included for 1.2.x
https://github.com/ballerina-platform/ballerina-lang/releases/tag/v1.2.21

**Comment by praneesha** [comment]
+1 Even if it is required to add release notes, better if we can link to them on B.io[1] rather than duplicating them here.

[1] https://ballerina.io/downloads/1.2.x-release-notes/1.2.23/
