### ISSUE TITLE
Parser changes for included record parameter feature

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#26123]
**Description:**
Please refer https://github.com/ballerina-platform/ballerina-spec/issues/578#issue-671556255

**Comment by lochana-chathura** [comment]
@chiranSachintha I guess we can link this to the pull request.

**Comment by chiranSachintha** [comment]
Need to introduce a separate node and parser error handling for `INCLUDED_RECORD_PARAM`. And also need to fix review suggestions relate to parser changes(https://github.com/ballerina-platform/ballerina-lang/pull/26882).
