### ISSUE TITLE
Need public access to bType in BallerinaTypeReferenceTypeDescriptor 

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#26133]
**Description:**
bType in BallerinaTypeReferenceTypeDescriptor which is inherited from AbstractTypeDescriptor, needs to be accessed from docerina in order to figure out weather the symbol is a Record, Class, Object, Error etc.

**Suggested Assignees (optional):**
@pubudu91

**Comment by pubudu91** [comment]
Wouldn't checking the typedesc kind of the type do for this? If you have a type descriptor, you can call the `kind()` method. You can compare and see if the returned value is equivalent to the expected typedesc kind value.

**Comment by pubudu91** [comment]
@shehan360 Did you try calling `typeDescriptor()` on this and checking its kind?

**Comment by shehan360** [comment]
It returns as a TYPE_REFERENCE. 
![Screenshot from 2020-09-28 17-51-47](https://user-images.githubusercontent.com/33398983/95239629-d62e3a80-0828-11eb-8980-0e6a4d334310.png)
But I need to know whether its a record, class, object, constant, error etc.
I think this can be achieved by checking the instanceof bType mentioned above.

**Comment by shehan360** [comment]
Using the command `typeDescriptor().get().typeDescriptor().get().kind()` returns the needed type. Hence, closing the issue.
