### ISSUE TITLE
typeDefs null for Qualified name references

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#26134]
**Description:**
In the symbol returned by the sematicModel.symbol, typeDefs are null for qualified name references.
![Screenshot from 2020-09-28 15-08-20](https://user-images.githubusercontent.com/33398983/94416467-84d4da00-019c-11eb-97f2-16a78b2bf479.png)

**Steps to reproduce:**
1. Have the following code
```
import ballerina/test;

# Test function
#
# + classImport - The java abstract obj from java module
public isolated function testPerson(test:MockObject classImport) returns string? {
}
```
2. Use the semantic api to get the symbol of classImport.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
What's the need to add `+1` to the line and offset?

**Comment by shehan360** [comment]
> What's the need to add `+1` to the line and offset?

Hi, this seems to be bug. The values returned by node.lineRange().startLine().line() and node.lineRange().startLine().offset() are off by 1 compared to the bal file.

**Comment by nadeeshaan** [comment]
You don't need to add +1 because the position representation within the parser is zero based indexed.

**Comment by shehan360** [comment]
> You don't need to add +1 because the position representation within the parser is zero based indexed. Can you try without adding the +1?

I tried and without the +1 a null value is returned

**Comment by pubudu91** [comment]
@shehan360 Can you please check this again and see? I just tested the following and I correctly got the variable symbol for the variable.
```ballerina
import testorg/foo;

# Test function
#
# + classImport - The java abstract obj from java module
public isolated function testPerson(foo:Person <cursor_pos>person) returns string? {
    return "";
}
```

**Comment by pubudu91** [comment]
Checked this with Shehan a bit more. It seems he's getting an incorrect cursor position as the position of `classImport`. Hence, a symbol is not returned for that position. Getting an incorrect position could be a bug in the parser/node transformer which calculates these positions.

**Comment by pubudu91** [comment]
@shehan360 Is this fine now? Also, please note that with #26338, we'll be moving to 0-based numbering for positions in the compiler as well.

**Comment by shehan360** [comment]
@pubudu91 Just tried with a latest pull, it's still not working. :/

**Comment by shehan360** [comment]
The issue was due to using the position of `test:MockObject`. When the position of `classImport` was used the issue resolved.
