### ISSUE TITLE
Inconsistent behavior when generating byte code for ballerina constant definitions

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#26139]
**Description:**
As a part of adding debugging support for ballerina global scope variables (https://github.com/ballerina-platform/ballerina-lang/issues/25275), debugger implementation is accessing the JVM runtime (`$_init` class), in order to fetch and display ballerina global variable/constant declarations. But as per the current codegen implementation, ballerina constants definition information for primitive types are not available in the generated byte code (defined, but not initialized). 

**Steps to reproduce:**
Decompile and observe the `$_init` class of the generated bytecode of the code sample below, to see how these constants are represented in the runtime, 

```ballerina 
const nameWithoutType = "Ballerina";    // Not accessible in runtime
const string nameWithType = "Ballerina"; // Not accessible in runtime
const map<string> gv02_nameMap = {"asd":"abc"};   // Accessible in runtime

public function main() {
    
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
There's a similar requirement in #25841. Probably unifying the behaviour for all constant types at the compile time would solve this.
