### ISSUE TITLE
Node lineRange() values are off by 1

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#26140]
**Description:**
The values returned by node.lineRange().startLine().line() and node.lineRange().startLine().offset() are off by 1 compared to the bal file.

Refer to the red boxes below.
![Screenshot from 2020-09-28 18-03-21](https://user-images.githubusercontent.com/33398983/94433122-71823880-01b5-11eb-875d-faa0ddeb96a0.png)

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Now all internal components and the semantic API use 0-based positioning. Hence the position given above is correct.
