### ISSUE TITLE
Improve toBalString() result when distinct types are not used with the object and error basic type values

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#26178]
**Description:**
The toBalString() result for 
- error is `error D1&D2 (M,C,F1=V1,F2=V2)` 
- object without `toString` method is `object D1&D2 U` 

where D1,D2 are `type-ids`. `type-ids` are associated with `distinct types`.
The spec [1] doesn't clearly mention what the result should be when distinct types are not used with object and error basic type values. ATM name of the type is used for this scenario.  This needs to be improved.

[1] https://ballerina.io/spec/lang/master/#ToString

**Comment by rdhananjaya** [comment]
IMO since non-distinct error and object types have empty set of type-ids D1&D2 will be empty string.
https://ballerina.io/spec/lang/master/#error-type-descriptor

**Comment by rdhananjaya** [comment]
Created spec issue https://github.com/ballerina-platform/ballerina-spec/issues/688
