### ISSUE TITLE
Add parser recovery for transactional worker keyword

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#26176]
Parser recovery  is not added for transactional workers. As of the current implementation, The below code snippets can break the parser .

 if there are additional tokens like:
```ballerina
transactional someJunkToken worker w1 {

}
```
or if the worker keyword is missing like:

```ballerina
transactional  w1 {

}
```

**Comment by lochana-chathura** [comment]
Related to #26014. Should be fixed with the PR changes of that issue.
