### ISSUE TITLE
Compiler fails with a Bad Sad error when resource method has `return` instead of `returns`

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#26175]
**Description:**
Compiler fails with a Bad Sad error when resource method has `return` instead of `returns`. Ideally, we need to show a proper error and fail without causing a Bad Sad error.

**Steps to reproduce:**
Compiler the following code
```
import ballerina/http;
service echo_service on new http:Listener(8090) {
    resource function test1(http:Caller caller, http:Request req) return error? {
        var result = caller->respond("Hello World!");
        if (result is error) {
        }
    }
}
```

Ballerina Internal Log - [ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/5315937/ballerina-internal.log)

**Affected Versions:**
Ballerina Swan Lake Preview 4

**OS, DB, other environment details and versions:**
Ubuntu 20

**Comment by lochana-chathura** [comment]
Fixed in current master/alph2.
