### ISSUE TITLE
Refactor and update public java API package names to io.ballerina.* 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#26177]
**Description:**
Currently, we have used various naming conventions as below for public java API packages.

Component | Current package name
-- | --
Parser | io.ballerinalang.compiler.*
Tools API | io.ballerina.tools.*
Compiler API | org.ballerina.compiler.*
Project API | io.ballerina.projects.*
Runtime API | org.ballerinalang.jvm.*

We should be using a single naming convention across all the API modules (i.e `io.ballerina.<api>.*`).

Can the owners of these modules take care of this change and refactor accordingly? 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Ack. I'll look in to the compiler API.

**Comment by riyafa** [comment]
The Runtime api has been migrated. Hence removing the jballerina label

**Comment by pubudu91** [comment]
All the APIs are now migrated right?

**Comment by pubudu91** [comment]
Closing this since all the APIs are now in `io.ballerina.*`
