### ISSUE TITLE
Move packerina tests which depends on stdlibs to distribution repo

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#26199]
**Description:**
$title
- [x] Test building and running modules that use standard libs. 
- [x] Test pushing and pulling modules from central. 
- [x] Test SingleBalFile With JDBC Usage.
- [ ] Test resolving ballerina modules from central.
- [x] Test for ballerina project having different components in toml (external libs, dependencies).

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
This will be handle by the new project API work.

**Comment by suganyasuven** [comment]
It is blocked as the build is failing due to the run-time API changes.

**Comment by Ibaqu** [comment]
Going forward, we will use TestNG for the integration tests.
