### ISSUE TITLE
Change the run and compile in ballerina to use module path

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#26198]
**Description:**
The run commands as used in ballerina uses class paths. With the jdk 11 migration to java modules running in the classpath puts all the classes into the unnamed module instead of their respective modules. This will invalidate the intention of using java modules.
This is noticed particularly in the `RunCommand` class and in the `ballerina` sh file. 

Example of the command for running a jar using module path:

`java -p path/to/jar/files -m modulename/io.ballerina.Main`

**Steps to reproduce:**
N/A
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by hevayo** [comment]
This is no longer relevant. from SL on-wards you can only run a package
