### ISSUE TITLE
Load Balo project should support lazy loading without reading the zip

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#26196]
**Description:**
Ideally, we should do lazy loading without reading the ZIP. In a cached state what we want are the modules so we should load only that in `loadProject(...)` method in `BaloProject` class.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
We keep the extracted bala in repositories now. Hence this can be closed.
