### ISSUE TITLE
The link to the api docs shows wrong version in left side pane.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#26208]
**Description:**
$subject when use the [link [1] ](https://ballerina.io/learn/api-docs/ballerina/) without version.
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/16300038/73122232-7f3d4980-3fa8-11ea-8659-5afb23970f99.png">

The issue is not there when we use the versioned [link](https://ballerina.io/v1-1/learn/api-docs/ballerina/) [2] 
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/16300038/73122249-b57ac900-3fa8-11ea-86fb-142382bdc4f2.png">

[1] https://ballerina.io/learn/api-docs/ballerina/
[2] https://ballerina.io/v1-1/learn/api-docs/ballerina/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shehan360** [comment]
Closing as this issue is fixed.
