### ISSUE TITLE
Support service declarations

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26238]
**Description:**

```ballerina
service / on new http:Listener(8080) {

}

```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Closing since this was added.
