### ISSUE TITLE
Support declaring service object types

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26239]
**Description:**
```ballerina
type ServiceType service object {

};
```

We need to make the service type to be a subtype of object type.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Closing since this was added.
