### ISSUE TITLE
Support service class declarations 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26240]
**Description:**
```ballerina
service class {
   *ServiceType;

}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Closing since this was added.
