### ISSUE TITLE
Symbol at cursor functionality for type inits is incomplete

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26251]
It seems the functionality of the symbol at cursor API for type inits is not entirely correct. If the cursor is at an explicitly stated type reference, it should return the symbol for the init method. The current behaviour doesn't consider the init method at all. Even if the init method is considered, there's the case where there may not be a user-defined init method.

**Comment by SupunS** [comment]
As per the latests discussions, we can always return the type-descriptor symbol.
User of the symbol can decide what information to use - Either can directly use the type information or can use init function's information if available.

**Comment by pubudu91** [comment]
Checked this. Currently this doesn't seem to work properly. Will address this when introducing class symbols
