### ISSUE TITLE
TypeDescriptor signature() is invalid for typedescs map<T>, xml<T>, table<T>, stream<T,C>, future<T>

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#26260]
**Description:**
TypeDescriptor signature() is invalid for typedescs with constrain types such as map, xml, table, stream, future

Consider the `FunctionTypeDescriptor` of the below function `foo()`. When invoking `signature()` in TypeDescriptor of the returnType it just returns `map` instead of `map<string>`. Same behavior is noticed for `xml<T>, table<T>, stream<T,C>, future<T>`.

```ballerina
public function main() {
    foo(true, 1.0);
}

function foo(boolean a, float b) returns map<string> {
    return {};
}
```

**Affected Versions:**
2.0.0-SLP5-SNAPSHOT

**Comment by pubudu91** [comment]
I checked this, and seems to work as expected for `map` and `future` types. Not working for `xml` and `table` since we currently don't have model classes for those types. For `stream`, it seems to be dropping the `C`. Will fix these with #26587
