### ISSUE TITLE
checkstyleTest task has unnecessary dependencies

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26285]
When I try to run the `checkstyleTest` task on a module, it runs the `updateVersion`, `npmInstall` and `npmBuild` tasks of libraries like composer-library, report-tools. Is there a reason for this? Note that this doesn't happen when running the `checkstyleMain` task.

**Comment by keizer619** [comment]
Now this should not happen as above modules removed (some have moved) from ballerina-lang repo. Hence i am closing this issue.
