### ISSUE TITLE
Type aliases for builtin types gets effectively discarded

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26284]
Consider the following:
```ballerina
type Foo int;
Foo x = 10;
```
For the above, a type `Foo` gets defined and there's a type symbol. But since it's an alias for a builtin type, it gets handled differently when resolving. When defining the variable, we resolve the type node, `Foo`. But when resolving, we don't keep track of the symbol it resolved to. Only the type of the symbol. Since the type is `int` and it's builtin, whenever we refer to `type.tsymbol`, it returns the type symbol for the builtin type `int`, instead of the type symbol for `Foo`. To fix this, we may need to refactor how the symbol resolver works. Currently it returns a type, although it's named SymbolResolver. I think we can resolve this issue if we return the symbol itself from it.

Issue: #26283 is sorta similar to this, but the difference is it's dealing with more complex and user defined types, therefore we create individual type symbols for each of those. Here we can't change the type symbol for `int`.

**Comment by MaryamZi** [comment]
This was also raised in https://github.com/ballerina-platform/ballerina-lang/issues/26470#issuecomment-725295493

**Comment by rdhananjaya** [comment]
Probably the root cause is same for this one too https://github.com/ballerina-platform/ballerina-lang/issues/25742

**Comment by pubudu91** [comment]
To fix this issue, we need to do the following:
- Introduce a separate BSymbol (e.g., BTypeDefinitionSymbol) for type definitions instead of relying on BTypeSymbol for type definitions. 
- Introduce the type reference type descriptor for representing usages of types defined using type definitions, constants etc. This means introduction of a new type tag and modifying the usages of the type tag.

**Comment by pcnfernando** [comment]
Compiler changes added to https://github.com/ballerina-platform/ballerina-lang/tree/type_ref_type_impl
