### ISSUE TITLE
Disabled Maven Test case

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#26292]
**Description:**
As Maven Resolver is broken in JDK 11, we had to disable ResolveMavenDependenciesTask. Thus, we have disabled maven test case(https://github.com/ballerina-platform/ballerina-lang/pull/26145/commits/08d685f768daf39f34615aae684e8d683481e29c).

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The test case is enabled in latest master (Beta.6-SNAPSHOT)
