### ISSUE TITLE
Semantic API captures invalid symbols

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#26301]
**Description:**
Consider the following source snippet,

```
import ballerina/module1;

module1:Client = <cursor>
```

When we call the `visibleSymbols` API it returns the symbol with the name  `$missingNode$0`, which should be a VIRTUAL symbol

**Comment by pubudu91** [comment]
What kind of AST node are you getting at the cursor position? I tried a similar example, and getting a simple var ref for it. And the symbol for it is null, so it doesn't get exposed publicly
