### ISSUE TITLE
Semantic API's visibleSymbols API drops valid symbols

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#26309]
**Description:**
Consider the following source snippet

```
import ballerina/module1;

public listener module1:Listener l1 = new(9090);

function testFunction() {
    module1:TestObject1 testValue;
    testValue = <cursor>
}

```

In the above snippet `testValue` is dropped, and it will be included if we add a new line before `testValue = <cursor>`

**Comment by pubudu91** [comment]
Could this be due to the line number conversion we have to do in some places? I tried the following in a test case and it works.
```ballerina
function test() {
    int v1;
    v1 = <cursor>
}
```

**Comment by nadeeshaan** [comment]
> Could this be due to the line number conversion we have to do in some places? I tried the following in a test case and it works.
> 
> ```ballerina
> function test() {
>     int v1;
>     v1 = <cursor>
> }
> ```

Yes, and when we try offsetting the positions given for the API, it works
