### ISSUE TITLE
Coverage report is not generated when the module name has "." in it

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#26326]
**Description:**
The test coverage report is not generated when the module name has a full stop in it. I get the following error:
<img width="1641" alt="Screenshot 2020-10-13 at 11 46 05" src="https://user-images.githubusercontent.com/28732894/95822517-b5467780-0d49-11eb-95f0-7dafa38fd1c9.png">

**Steps to reproduce:**

**Affected Versions:**
1.2.8
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Component/Testerina, Team/TestFramework

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
This is for Ballerina 1.2.8 right?

**Comment by parkavi11** [comment]
> This is for Ballerina 1.2.8 right?

Yes, updated the Description

**Comment by Dilhasha** [comment]
Will be fixed with https://github.com/ballerina-platform/ballerina-lang/issues/26431
