### ISSUE TITLE
Update Docs for the JDK 11 Migration

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#26337]
**Description:**
Update README files, and installation instructions in docs for the JDK 11 migration.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
@keizer619 - This is left to be updated: https://github.com/ballerina-platform/ballerina-distribution/blob/master/resources/tools/INSTALL.txt#L8

**Comment by keizer619** [comment]
Above part has been updated in following PR
https://github.com/ballerina-platform/ballerina-distribution/pull/973
