### ISSUE TITLE
Align the error constructor with SwanLake spec version

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26341]
**Description:**
After the removal of functional constructors, the current implementation is no longer aligned with the one specified in the spec.

New error constructor is on the grammar:
```
error-constructor-expr := error [error-type-reference] ( error-arg-list )
error-arg-list := positional-arg [, positional-arg] (, named-arg)*
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in #27516, merged via #27652.
