### ISSUE TITLE
Error in how an `xml-template-expr` is handled with a sequence

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26340]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    xml x1 = xml `<foo>foo</foo><!--bar-->baz`;
    xml x2 = xml `<foo>foo</foo>`;
    io:println(x1);
    io:println(x1);
    io:println(x1 == x2);
}
```

This currently prints
```cmd
<foo>foo</foo>
<foo>foo</foo>
true
```

**Affected Versions:**
slp4

**Comment by rdhananjaya** [comment]
Seems to be an issue with the xml sequence literal. Does not occure when xml sequence is constructed using `xml:concat` function.

**Comment by rdhananjaya** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/26589
