### ISSUE TITLE
Set contextually expected type as return type and update documentation of `ensureType` function

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#26355]
**Description:**
```ballerina
function ensureType(any|error value, typedesc<any> t = <>) returns t|error {
  trap<t>check value;
}
```
https://github.com/ballerina-platform/ballerina-spec/issues/487#issuecomment-673868649
https://github.com/ballerina-platform/ballerina-lang/pull/25935#discussion_r500437548

**Comment by MaryamZi** [comment]
Re-opening this to track changing the typedesc param to be a defaultable param with an inferred-typedesc-default.
