### ISSUE TITLE
Parser node `ObjectFieldNode` has incorrect attributes

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26379]
**Description:**
Parser node `ObjectFieldNode`, which represents the [object-field-descriptor](https://ballerina.io/ballerina-spec/spec.html#object-field-descriptor) in the Ballerina Swan Lake Specification, contains the incorrect attributes `equalsToken` and `expression`. This results in an incorrect node formation. 

**Sample:**
```ballerina
typedesc<object { int i = 1; }> b = g;
```

**Affected Versions:**
Swan Lake Preview 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
What do you mean by incorrect node formation?

Note that `ObjectFieldNode` not only represents [object-field-descriptor](https://ballerina.io/ballerina-spec/spec.html#object-field-descriptor) , but also [object-field](https://ballerina.io/ballerina-spec/spec.html#object-field).

For the given example it parses as `typedesc<object { int i  INVALID[=]  INVALID[1]; }> b = g;`

One should not get `equalsToken` and `expression` an object-field-descriptor in the syntax tree, as we don't allow them to be parsed in the BallerinaParser.

Anyway before the swan lake new object change one was able to initialize an object-field in the object-type-descriptor.
But I guess we shipped the new object change with slp4.

**Comment by IrushiL** [comment]
Closing this issue since the above sample is invalidated with the latest object changes.
