### ISSUE TITLE
Return errors from the functions in the 'files' packages.

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerina-platform/ballerina-lang#2637]
e.g.

native function write (blob content, File file) (Error)

**Comment by uthaiyashankar** [comment]
This might not be valid anymore. We have to validate and resolve.

**Comment by wggihan** [comment]
Please note this is no longer valid. We have moved Path related functionalities to internal packages and these kind of function will not available for external users until we properly implement the file related functionalities.
