### ISSUE TITLE
[Formatter] Fix indentation of comments attached to closing braces

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26380]
**Description:**
In the new formatter design implementation, comment minutiaes are attached to the trailing token and will inherit the indentation of this token. However, in cases where the trailing token is a closing brace, the indentation should be realigned so that it would appear to be an element inside the block.

Expected:
```ballerina
function bar() {
    int a = 9;
    // hello
}
```

Actual:
```ballerina
function bar() {
    int a = 9;
// hello
}
```

**Steps to reproduce:**
Swan Lake Preview 4

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Moe82** [comment]
Hi @IrushiL. I'd like work on this issue. Can you tell me which files exactly are affected? Thank you.
