### ISSUE TITLE
Updating to swan-lake-preview4 documentation incomplete instructions

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#26402]
**Description:**
When trying to update from ballerina *stable release 1.2.8* to *swan-lake-preview4*, the documentation mentions the steps to update as follows.
```bash
$ ballerina update
$ ballerina dist pull slp4
```
Although the distribution is pulled successfully the version did not get updated only with these commands in an Ubuntu 20.04 OS.

The command, 
```bash
$ ballerina dist use slp4
```
had to be used to set slp4 as the active distribution. But the documentation does not mention the use of the command.
[https://ballerina.io/downloads/swan-lake-release-notes/#for-existing-users](https://ballerina.io/downloads/swan-lake-release-notes/#for-existing-users)
[https://ballerina.io/downloads/](https://ballerina.io/downloads/)

How ever in windows 10 Home 2004 version the ballerina version is updated to slp4 only with the commands in the documentation.

**Steps to reproduce:**
1. Download and install ballerina *stable release 1.2.8* using the .deb package. 
2. Update ballerina to swan-lake-preview4* with commands in the documentation.
```bash
$ ballerina update
$ ballerina dist pull slp4
```
3. Check ballerina version. It displays the version as 1.2.8
4. Use command,
```bash
$ ballerina dist use slp4
```
5. Check ballerina version.
```bash
$ ballerina --version
Ballerina Swan Lake Preview 4
Language specification v2020-09-22
Update Tool 0.8.8
```

**Affected Versions:**
*swan-lake-preview4*

**OS, DB, other environment details and versions:**
OS - Ubuntu 20.04(LTS)
Shell - bash

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
 Type/Docs

**Comment by praneesha** [comment]
The Update Tool should be fixed instead of updating docs for this.

**Comment by keizer619** [comment]
Actual behavior should be set slp4 when dist pull is executed. In that case we will treat this as a bug in update tool

**Comment by suganyasuven** [comment]
I also encountered the same issue. Could you please try the same after issuing ```sudo su```?

**Comment by suganyasuven** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-update-tool/pull/55
