### ISSUE TITLE
Making annotation values readonly has being commented out in JDK11 migration and needs to be re-enabled

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26408]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java#L1086

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Reopening since the fix was reverted with https://github.com/ballerina-platform/ballerina-lang/pull/26476 due to https://github.com/ballerina-platform/ballerina-lang/issues/26478. 

We can fix this when fixing https://github.com/ballerina-platform/ballerina-lang/issues/26478.

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/28447.
