### ISSUE TITLE
NoSuchFileException when generating code coverage 

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#26431]
**Description:**
$subject, module name with a dot

https://github.com/ballerina-platform/module-ballerina-java.jdbc/runs/1280724516

**Comment by niveathika** [comment]
https://github.com/ballerina-platform/module-ballerina-java.jdbc/pull/19 is blocked due to this.

**Comment by Dilhasha** [comment]
@niveathika 
@Ibaqu will look into this. We didn't prioritize this bug previously because "ballerina add" did not support "."

**Comment by niveathika** [comment]
@Dilhasha This has always had issues. We had to enable & disable couple of times after migration.

**Comment by Dilhasha** [comment]
@niveathika until we provide a proper fix, we have temporarily disabled the problematic feature. Can you check whether you are able to proceed?

**Comment by niveathika** [comment]
The build is successful now.

**Comment by hemikak** [comment]
Closing issue. Refer to https://github.com/ballerina-platform/ballerina-lang/issues/26479
