### ISSUE TITLE
Change `Set<Object>` to `Set<String>`  at CodeAnalyzer>visit(BLangRecordLiteral recordLiteral)

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#26442]
**Description:**

Change the following `Set<Object>` to `Set<String>` at https://github.com/ballerina-platform/ballerina-lang/blob/eb2f681267eb3808cceb98bfaf494e3000dc9c5d/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L2270

and 
https://github.com/ballerina-platform/ballerina-lang/blob/eb2f681267eb3808cceb98bfaf494e3000dc9c5d/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java#L2271

Link for the discussion: https://github.com/ballerina-platform/ballerina-lang/pull/26396#discussion_r508690503

Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/26396

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@dulajdilshan

**Comment by KavinduZoysa** [comment]
In the current implementation, those are available in L:2224 and L:2225
