### ISSUE TITLE
NodeFactory.createSeparateNodeList accepts the wrong type of parameter

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#26440]
**Description:**
`SeparatedNodeList` constructor takes a non-terminal node with an odd number of buckets.
And the constructor expects that every odd position of the buckets contain a separator.

```java
SeparatedNodeList(NonTerminalNode node) {
   // The list size is always an odd number
   // E.g., If the list size is 7, then there are 4 nodes and 3 separators
   super(node, (node.bucketCount() + 1) / 2);
   this.separatorSize = size != 0 ? size - 1 : 0;

   // TODO check whether the given node is a node list with separator
}
```

So, when creating the separator node list, we have to pass in the separators(eg: comma tokens) as well.

However, in the `NodeFactory.createSeparatedNodeList()` it directly passes the node list to the constructor after creating the node list node. 

```java
public static <T extends Node> NodeList<T> createSeparatedNodeList(T... nodes) {
   STNode[] internalNodes = new STNode[nodes.length];
   for (int index = 0; index < nodes.length; index++) {
      T node = nodes[index];
      Objects.requireNonNull(node, "node should not be null");
      internalNodes[index] = node.internalNode();
   }
   return new SeparatedNodeList<>(STNodeFactory.createNodeList(internalNodes).createUnlinkedFacade());
}
```

However, since the `SeparatedNodeList` constructor expects separator tokens between every 2 nodes, the callee of this function will have to pass in those as well. But in the for loop, each node has to be cast into the same type `T`. (Which token can't be cast into) So this method call cannot be used.

**Steps to reproduce:**

- Attempt to recreate `function main(){ f(a, b); }` via Syntax API. With the current method calls, this doesn't seem to be possible. Nodes related to this string is as follows,

```
FunctionDefinitionNode
   | Token[FUNCTION_KEYWORD]
   | IdentifierToken("main")
   | FunctionSignatureNode
   |   | Token[OPEN_PAREN_TOKEN]
   |   | Token[CLOSE_PAREN_TOKEN]
   | FunctionBodyBlockNode
   |   | Token[OPEN_BRACE_TOKEN]
   |   | NodeList*
   |   |   | ExpressionStatementNode[CALL_STATEMENT]
   |   |   |   | FunctionCallExpressionNode
   |   |   |   |   | SimpleNameReferenceNode
   |   |   |   |   |   | IdentifierToken("f")
   |   |   |   |   | Token[OPEN_PAREN_TOKEN]
   |   |   |   |   | SeparatedNodeList              <- THIS
   |   |   |   |   |   | PositionalArgumentNode
   |   |   |   |   |   |   | SimpleNameReferenceNode
   |   |   |   |   |   |   |   | IdentifierToken("a")
   |   |   |   |   |   | Token[COMMA_TOKEN]         <- TOKEN
   |   |   |   |   |   | PositionalArgumentNode
   |   |   |   |   |   |   |  SimpleNameReferenceNode
   |   |   |   |   |   |   |   |  IdentifierToken("b")
   |   |   |   |   | Token[CLOSE_PAREN_TOKEN]
   |   |   |   | Token[SEMICOLON_TOKEN]
   |   | Token[CLOSE_BRACE_TOKEN]
```

- However, `createFunctionCallExpressionNode`'s `SeparatedNodeList` parameter only accepts `SeparatedNodeList<FunctionArgumentNode>`.
    
- But, since the commas inside the parameter list has to be included in the node list but cannot be cast into function argument node, that factory call cannot be used.

**Comment by kdsuneraavinash** [comment]
I think this can be fixed by simply changing the parameter type of the `createSeperatedNodeList()` to Node instead of T.

```java
public static <T extends Node> SeparatedNodeList<T> createSeparatedNodeList(Node... nodes) {
   STNode[] internalNodes = new STNode[nodes.length];
   for (int index = 0; index < nodes.length; index++) {
      Node node = nodes[index];
      Objects.requireNonNull(node, "node should not be null");
      internalNodes[index] = node.internalNode();
   }
   return new SeparatedNodeList<>(STNodeFactory.createNodeList(internalNodes).createUnlinkedFacade());
}
```

I can submit a pull request if needed.

**Comment by SupunS** [comment]
Can we keep the parameter as it is to use the generic type, and do something similar to this: https://github.com/ballerina-platform/ballerina-lang/blob/f9065da6fafe01c7a934a44bb1b2acb6a4ecf186/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/TreeModifier.java#L3183

**Comment by kdsuneraavinash** [comment]
I am not sure about the approach I should take. I can't accept separators inside the nodes parameter because of its constraint to T. So I'm not sure how changing the internal check would help me in this issue. :thinking:
