### ISSUE TITLE
Needs to clean up how method names get defined in object scope

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26452]
**Description:**
Currently, a method `foo` on a type `bar` is defined as `bar.foo`. We need to make this defined as only `foo`. And remote methods should have its own scope, separate from methods and fields.

Related PR https://github.com/ballerina-platform/ballerina-lang/pull/26447
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Duplicates #37363
