### ISSUE TITLE
[Formatter] Handle errors in the code and format the rest

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26450]
**Description:**
The formatter should be able to format a source code by ignoring the nodes that contain errors and by formatting the rest of the code.

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Might be partially fixed with https://github.com/ballerina-platform/ballerina-lang/pull/26566
