### ISSUE TITLE
Add context aware resource snippet suggestions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#26466]
**Description:**
Add the context aware resource snippet suggestions for the standard libraries such as http and ws

**Comment by IMS94** [comment]
@nadeeshaan Could you elaborate more on this idea?

**Comment by nadeeshaan** [comment]
> @nadeeshaan Could you elaborate more on this idea?

Consider an http service and we need to provide completions for the http resources such as GET, PUT, POST and etc. Currently, we have to include these as static templates and cannot find a generic way. These should be able to provide as the extensions as we are doing with the Code Actions extensions for the standard libraries.

**Comment by IMS94** [comment]
This was addressed to a reasonable level with #33571. Hence closing this. If there is a request for further improvement, we can create a new issue.
