### ISSUE TITLE
Remove constant propagator

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26470]
In the current compiler the constant refs are replaced with their actual values  during the constant propagation phase. Due to this, we lose the semantic information about the usages of the constants.

**Comment by MaryamZi** [comment]
In the constant propagation phase, we seem to be replacing `BLangSimpleVarRef`s that refer to a constant of type `int`, `byte`, `float`, `decimal`, `string`, `boolean`, or nil, with a `BLangConstRef` (see https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java#L1035).

[`BLangConstRef`](https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/tree/expressions/BLangConstRef.java) extends `BLangSimpleVarRef`, but also implements `LiteralNode`, which allows compiler plugin authors to retrieve the actual value by calling `getValue()` (which I believe was the original issue the constant propagation phase solved). However, `BLangConstRef` still contains a symbol, which would be the original `BConstantSymbol` (https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/ConstantPropagation.java#L1039).

Is this replacement itself an issue, or is it possible to extract the required information from `BLangConstRef`?

The `BLangConstRef` is subsequently rewritten by the literal only at desugar.

**Comment by pubudu91** [comment]
I verified what Maryam said above with a test for the semantic API with the compilation phase set to `COMPILER_PLUGIN`. For the following snippet, it correctly returned the constant symbol when given the position of the usage of the constant.
```ballerina
const HELLO = "hello";

function test() {
    string s = HELLO;
}
```

**Comment by MaryamZi** [comment]
@pubudu91, @rasika, any further update on this? Do we still need this to be removed?

**Comment by rasika** [comment]
Sorry for the delay. Please have a look in below sample;

```ballerina
public type MY_TYPE int;

function name() {
   <cursor>getUnion();
}

function getUnion() returns MY_TYPE {
    return 12;
}
```

If you look at return type of the `getUnion` function you are getting `int` instead of `MY_TYPE`. This is the issue I am referring.

**Comment by MaryamZi** [comment]
Ah, yes, I believe that is due to https://github.com/ballerina-platform/ballerina-lang/issues/26284? 

I think we can keep the constant propagator, since that is not causing any issues?

**Comment by pubudu91** [comment]
Yes, +1 for keeping the constant propagator since it doesn't seem to be an issue for us. Closing this.
