### ISSUE TITLE
Fix Multi-module coverage for modules with 'dot .' in the name

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#26479]
**Description:**
Muti-module coverage does not work with modules that have a dot in the name. 

The `ISourceFileCoverage` class used in CodeCoverage report returns a package name which has the dot `.` replaced with an underscore `_`.

```
  String sourceFileModule = sourceFileCoverage.getPackageName().split("/")[1];

ModuleCoverage.getInstance().updateSourceFileCoverage(jsonCachePath, sourceFileModule,
                                    sourceFileCoverage.getName(), coveredLines, missedLines);
```

This causes the path to the source files to be resolved incorrectly, thus resulting in a NoSuchFileException.
This can be seen for modules such as java.jdbc which inturn becomes java_jdbc. 

Simply replacing the `_` with `.` in sourceFileModule will not work as this can interfere with modules that contain `_` originally in their name.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/26477
https://github.com/ballerina-platform/ballerina-lang/issues/26431

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
It is worth noting that since `_foo` and `.foo` can exist simultaneously in a project, the .foo is converted to _foo and can result in some conflicts.

**Comment by Dilhasha** [comment]
@Ibaqu I did a bit of debugging and the issue is from the jar files generated during ballerina build that get added to "target/caches/jar_cache".

For example path for the main.class is as follows for "diffmod.dil" module when I extracted and check the above jar,
dilhashanazeer/**diffmod_dil**/0_1_0/main.class

**Comment by Ibaqu** [comment]
Once the "Improve code gen methods to reduce clashes" has been finalized :
https://github.com/ballerina-platform/ballerina-lang/issues/26346 

We _should_ be able to use the following function `decodeIdentifier` : https://github.com/ballerina-platform/ballerina-lang/blob/70c5342829156da8525211726b1548d2ad018271/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/IdentifierUtils.java#L88 to get the original module name.

**Comment by Ibaqu** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/26683
