### ISSUE TITLE
Invalid 'will not be matched to' error for readonly types

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26481]
**Description:**
```ballerina
import ballerina/io;
type R0 record {|
    int i;
|};

type R1 record {
    int i;
    // any optional fields 
    string s?;
};

public function main() {
    R1 & readonly r1 = { i: 0};
    boolean a = (<any> r1) is R0; // without casting to any: "incompatible types: '(R1 & readonly)' will not be matched to 'R0'"
    io:println(a);
}
```

Type-test `r1 is R0` is falsely reported as an error while it does evaluates to true in the runtime.

**Steps to reproduce:**

**Affected Versions:**
SLP4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This is a part of https://github.com/ballerina-platform/ballerina-lang/issues/24451. Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/22785

**Comment by rdhananjaya** [comment]
Closing as there is a broader issue covering this.
