### ISSUE TITLE
Disable the maven resolving component in the bindgen tool

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26489]
**Description:**
Disable the maven resolving component in the bindgen tool until the following issue [1] is fixed.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/26219

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 5 SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
The mentioned issue is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26219. Hence closing
