### ISSUE TITLE
Semantic API returns variables as Function symbols

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#26491]
**Description:**
Consider the following source snippet, 

```
function basicClosure() returns (function (int) returns int) {
    int a = 12;
    var foo1 = function (int b) returns int {
        int c = 12;
        if (b == 3) {
            
        }

        return 12;
    };

    return fo<cursor>
}
```

If we consider the symbol `foo` it is being identified as a FunctionSymbol instead of a Variable Symbol.
When suggesting completions at cursor, do we need to support `foo1( )` and `foo` as well?

**Comment by pubudu91** [comment]
I just checked this. Looks like this is how it has been before as well. If the variable is referring to a function, the symbol created for it is an invokable symbol. Does this create any complications?

**Comment by pubudu91** [comment]
@nadeeshaan Since both `foo()` and `foo` are acceptable, it's fine to suggest both in completions right? Or does this cause any issues?

**Comment by IMS94** [comment]
Now `foo1` is suggested as expected on master. Closing this.
