### ISSUE TITLE
Formatting adds unnecessary new line

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26522]
Refer to the following:
![Peek 2020-10-22 17-11](https://user-images.githubusercontent.com/6260009/96866944-ad917c00-1489-11eb-92a2-d29c755d6c87.gif)

The new line at the end of the doc is unnecessary

**Comment by nadeeshaan** [comment]
This issue should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/26484

**Comment by pubudu91** [comment]
Yeah, it's the same issue addressed by the above PR. Hence closing this.
