### ISSUE TITLE
Ballerina format wrongly formats @untainted function parameter

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#26531]
**Description:**
Ballerina format wrongly formats @untainted function parameter

**Steps to reproduce:**
Try "ballerina format" below code snippet.

```
import ballerina/http;

public client class MockHttpClient {
    public remote function get(@untainted string path, http:RequestMessage message = (), http:TargetType targetType = 
                               http:Response) returns @tainted http:Response|http:Payload|http:ClientError {

        http:Response res = new;
        res.statusCode = 500;
        return res;
    }
}
```

It will remove the space between @untainted and string as **@untaintedstring**.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
Fixed via #26529
