### ISSUE TITLE
Anonymous functions formatted relative to the starting column of the anon function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26530]
Refer to the following:
![Peek 2020-10-22 19-57](https://user-images.githubusercontent.com/6260009/96886461-3cf65980-14a1-11eb-9016-08e41d3bf7e0.gif)

Formatting like this leads to code aligned too much to the right

**Comment by SupunS** [comment]
+1. 
I think table constructor behaves like this. May be we could follow the same this.

**Comment by pubudu91** [comment]
Also, should the formatter be removing that new line after `map(`?

**Comment by SupunS** [comment]
Its hard to determine whether to add a newline after `map(`, because it's yet another function argument. But if the argument exceeds the max line-length, then it should go in to the next line.

@IrushiL I think what we have done for table-constructor needs to be generalized. I mean, it should happen at the statement level, rather than the table-constructor/anon-function/etc.

**Comment by SupunS** [comment]
A similar scenario is to when there is a function call that exeeds max-length.:
```ballerina
public function main() {
    var foo = bar("aaaaa", "bbbbb", "cccc", "ddddd", "eeeee","aaaaa", "bbbbb", "cccc", "ddddd", "eeeee","aaaaa", "bbbbb", "cccc", "ddddd", "eeeee","aaaaa", "bbbbb", "cccc", "ddddd", "eeeee","aaaaa", "bbbbb", "cccc", "ddddd", "eeeee");
}
```

Formmatered Output:
```ballerina
public function main() {
    var foo = bar("aaaaa", "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", 
    "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", "bbbbb", "cccc", "ddddd", 
    "eeeee");
}
```
Expected output:
```ballerina
public function main() {
    var foo = bar("aaaaa", "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", 
        "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", "bbbbb", "cccc", "ddddd", "eeeee", "aaaaa", "bbbbb", "cccc", "ddddd", 
        "eeeee");
}
```

**Comment by IrushiL** [comment]
A related issue with a similar behavior: https://github.com/ballerina-platform/ballerina-lang/issues/27247

**Comment by IrushiL** [comment]
Note: Check this behavior in query expressions.
