### ISSUE TITLE
Return value of `lang.error.detail` should be immutable

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#26545]
**Description:**
According to the spec, the return value of `lang.error.detail` should be immutable.
https://github.com/ballerina-platform/ballerina-spec/blob/1b6cc59c5cd52375ae6ba4747c8a7716f30ccf5a/lang/lib/error.bal#L50

**Affected Versions:**
Swan Lake preview-5

**Comment by chiranSachintha** [comment]
We need to set detail map as immutable [here](https://github.com/ballerina-platform/ballerina-lang/blob/60570d63d22aed53af2a609ad613029337657f15/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/ErrorCreator.java#L112).

**Comment by MaryamZi** [comment]
Re-opening this since the static type of `lang.'error:detail()` has to change.

**Comment by MaryamZi** [comment]
@gimantha, we can close this also, right?

**Comment by gimantha** [comment]
> @gimantha, we can close this also, right?

Yes. we can close it
