### ISSUE TITLE
Getting a Bad. Sad :`BLangRecordLiteral cannot be cast to class BLangVariableReference

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#26544]
**Description:**
Getting a bad sad :`BLangRecordLiteral cannot be cast to class BLangVariableReference at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2463)`

for 

```ballerina
type Alpha record {|
    int a;
|};

public function main() {
    Alpha rec = {a: 3;
    map<int> mm = {..rec}};
}
```

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Parser output:
```ballerina
type Alpha record {|
    int a;
|};

public function main() {
    Alpha rec = {a: 3 MISSING[}];
    map<int> mm = { MISSING[}]. MISSING[].rec}};
}
```

**Comment by lochana-chathura** [comment]
Fixed in current master/ alpha2.
