### ISSUE TITLE
Ballerina slp4 `ballerina run` command throws an error without installing java externally

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#26558]
**Description:**

In *swan-lake-preview4*, installation, the `ballerina run` command gives the following error when no jdk is installed in the OS. 
```bash
error: Error occurred while running the executable java.io.IOException: error=2, No such file or directory
```
When jdk 1.8 is installed system-wide the ballerina run command works perfectly.

**Steps to reproduce:**
1. Install ballerina slp4 with no jdk/jre installed system-wide.
2. Create a simple ballerina program hello.bal
``` ballerina
import ballerina/io;
public function main() {
    io:println("Hello world");
}
```

3. Run command ballerina run hello.bal
```bash
$ ballerina run hello.bal
error: Error occurred while running the executable java.io.IOException: error=2, No such file or directory
```
3. Install java 1.8 globally and set path variable.

4. Run command ballerina run hello.bal
```bash

$ ballerina run hello.bal

Compiling source
	hello.bal
Running executables

Hello world
```

**Affected Versions:**
*swan-lake-preview4*

**OS, DB, other environment details and versions:**
OS - Ubuntu 20.04
Shell- Bash
Openjdk version(which fixed the error)- 1.8.0_265

**Comment by suganyasuven** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/26535.
