### ISSUE TITLE
XMLValueUtil still depends on OMNodes

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26577]
**Description:**
We need to remove this dependency on `OMNode`.

https://github.com/ballerina-platform/ballerina-lang/blob/a9a0095e15f5cbe8a3549d1a8bde54bf43f05dc6/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/XMLValueUtil.java#L10

**Steps to reproduce:**

**Affected Versions:**
SLP5
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
No such file is available in the current implementation (bca1ce39ad9da45824f7129d1e7ddb782513601a).
