### ISSUE TITLE
XML template expressions provides incorrect results in some contexts

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#26589]
**Description:**
Please refer the below code sample, where the value of `x6` is different from the expected result.

![Screenshot from 2020-10-26 10-39-14](https://user-images.githubusercontent.com/29032600/97136794-1a529200-177a-11eb-9bc6-8d07ecd89f3b.png)

**Steps to reproduce:**

Use the code sample below and try printing/debugging the value of `x`.
```ballerina
public function main() {
    xml x = xml `<book>The Lost World</book>Hello, world!<!--I am a comment--><?target data?>`;
}
```

**Affected Versions:**
2.0.0-M5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Duplicates https://github.com/ballerina-platform/ballerina-lang/issues/26340
