### ISSUE TITLE
[Testerina] TypeCastError during function mocking in Ballerina 1.2.8

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#26621]
**Description:**

TypeCastError is thrown during function mocking.

**Steps to reproduce:**

See the below original function & mock code.

```
function getCurrentUser() returns string|error {
    string test = "test";
    return test;
}
```

```
@test:Mock { functionName: "getCurrentUser" }
test:MockFunction getCurrentUserMockFn = new();

@test:Config {}
function testFunction(){
test:when(getCurrentUserMockFn).thenReturn("hello test");
test:assertEquals(getCurrentUser(),"hello test");
}
```

This throws the below error.

`{ballerina}TypeCastError message=incompatible types: 'handle' cannot be cast to 'string|error'`

**Affected Versions:**
1.2.8

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Let's look at all the functions in function mocking. Looks like most of them are not working as expected.

**Comment by Ibaqu** [comment]
> Let's look at all the functions in function mocking. Looks like most of them are not working as expected.

Currently the test cases cover string, int and float. Along with imports and varargs as well.
