### ISSUE TITLE
Issue in `cloneWithType` and `fromJsonWithType` with numeric values

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26633]
**Description:**
With a union target type, if the value already belongs to the target type without any conversion, no additional checks need to be done (https://github.com/ballerina-platform/ballerina-spec/issues/556#issuecomment-651498370).

**Steps to reproduce:**
Thus, in the following scenario since `x` is `int` and the target type has `int` the conversion should succeed. 

```ballerina
import ballerina/io;

type Foo record {|
    int|float x;
|};

public function main() {
    map<json> m = {x: 1};
    io:println(m.cloneWithType(Foo));
}
```

Currently fails since the conversion is considered to be ambiguous. 
```cmd
$ ballerina run test.bal 
Compiling source
        test.bal
Running executables

error("{ballerina/lang.typedesc}ConversionError",message="'map<json>' value cannot be converted to 'Foo'")
```

**Affected Versions:**
slp5

**Comment by lasinicl** [comment]
This is fixed in the current master. Hence closing the issue.
