### ISSUE TITLE
Contradicting diagnostic shown for classes

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#26675]
**Description:**
Consider the following source snippet,

```
public class testClass {
    isolated remote function testFunc() {
        
    }
}
```

For the remote function the compiler gives the following error diagnostic,

`a remote function in a non client object`

Shouldn't this be corrected to address the actual construct which is `class`?

**Affected Versions:**
SLP5 at least

**Comment by MaryamZi** [comment]
The error is now

```
remote qualifier only allowed in client and service objects
```

IMO, saying object is OK, since that's what a class creates.

**Comment by KavinduZoysa** [comment]
Closing the issue because the current error message is OK.
