### ISSUE TITLE
No error when using `isolated` in a module-no-init-var-decl

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26738]
**Description:**
The grammar for `module-no-init-var-decl` is 

`module-no-init-var-decl := metadata [final] type-descriptor variable-name ;`

**Steps to reproduce:**
So the following should result in an error.

```ballerina
isolated int[] val;
```

**Affected Versions:**
Current master

**Comment by lochana-chathura** [comment]
```bal 
INVALID[isolated] int[] val;
```
Parsed as above. But, syntax tree seems to have no diagnostics.
