### ISSUE TITLE
Restrict binding pattern to captureBP in isolated-module-int-var-decl 

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#26735]
**Description:**
Spec says,

> _If a module-init-var-decl includes an isolated-qual, then the variable declared is isolated. In this case, the binding-pattern in the typed-binding-pattern must be just a variable-name._

- Right now only capture-binding-pattern is supported in the compiler.
- When adding other binding pattern support, we need to log an error when other binding pattern are used with isolated-module-init-var-decl.  

**Suggested Labels (optional):**
Team/CompilerFE, Component/Compiler

**Comment by MaryamZi** [comment]
Using non-capture binding patterns with `isolated` variable declarations result in errors as expected.

```ballerina
isolated int i = 1; // OK

isolated [int, string] [a, b] = [1, ""]; // only a simple variable can be marked as 'isolated'
isolated record { int c; } {c, ...d} = {c: 1, "d1": ""}; // only a simple variable can be marked as 'isolated'
isolated error error(e) = error(""); // only a simple variable can be marked as 'isolated'
```
