### ISSUE TITLE
Runtime type of the function/method types needs to preserve the parameter names

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26749]
**Description:**
As parameter names are part of function type we need to bring that information into runtime type as well.

This is a blocker for GraphQL implementation
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Why do we need the parameter names in the type? 🤔

**Comment by rdhananjaya** [comment]
With the new service proposal, `listener` authors are incontrol of deciding how a resource function is to be interpreted.
And we also try to minimize the usage of annotations as much as possible.

**Comment by rdhananjaya** [comment]
Closing as the parameter name was added to `ResourceFunctionType`, and the StdLib team didn't require this on normal functions.
