### ISSUE TITLE
Stored resources are no longer supported

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26746]
**Description:**
`resource` qualifier only apply to resouce functions now.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
@rdhananjaya Can we have other qualifiers when resource qualifier is present in a function? 
e.g.
```bal 
isolated resource function foo() { }
```

**Comment by rdhananjaya** [comment]
> @rdhananjaya Can we have other qualifiers when a resource qualifier is present in a function?
> e.g.
> 
> ```ballerina
> isolated resource function foo() { }
> ```

It seems so, https://github.com/ballerina-platform/ballerina-lang/issues/26835
