### ISSUE TITLE
Improve absolute resource path in service decl

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26745]
**Description:**
We need to differentiate between empty (`/`) absolute resource path and resource path being absent.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
@rdhananjaya Can you provide an example? absolute-resource-path is already optional in the service-decl.
For,
```bal
service on listner { }
```
AST has an empty list.

For,
```bal
service / on listner { }
```
AST has a list with slash token.

**Comment by rdhananjaya** [comment]
Closing as per above comment we can differentiate absolute path being absent vs an '/' as an absolute path.
