### ISSUE TITLE
Anonymous record type def is created twice at nodetransformer

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#26774]
**Description:**
$title
When the detail type of a `ErrorTypeDescriptorNode` is analyzed two type defs for the same anonymous type is created. This is done in the `deSugarTypeAsUserDefType` and `createTypeNode` both. Need to check and remove one definition

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Checked this is fixed now.
