### ISSUE TITLE
Unexpected with Error Destructuring

### ISSUE THREAD

**Issue by AlexisUCL** [ballerina-platform/ballerina-lang#26809]
**Description:**
The typed error desctructuring described in https://medium.com/ballerina-techblog/ballerina-error-handling-part-iii-error-binding-patterns-b6521fd866ac does not seem to work with inherited error types (which is to say, parent error types).

**Steps to reproduce:**
See attached main.bal.
[main.bal](https://github.com/ballerina-platform/ballerina-lang/files/5505193/main.bal.txt)
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/5505191/ballerina-internal.log)

**Affected Versions:**
jBallerina 1.2.8
Language specification 2020R1
Update Tool 0.8.8

**OS, DB, other environment details and versions:**
WSL2 Ubuntu

**Related Issues (optional):**

**Suggested Labels (optional):**

error, destructure, inheritance 

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
There seems to be an issue when the error type is a union of other error types. If the detail type is the same, one workaround would be to define the error type as a separate error type with the union of the reasons as the reason of the new type.

e.g.,

```ballerina
public type MainError error<ErrorType, ErrorData>;
```

[Swan Lake Preview versions] Changes have been introduced to the error type and error typed binding patterns in Swan Lake Preview versions resulting in certain compilation errors for this code, but the compiler still seems to crash.

**Comment by rdhananjaya** [comment]
After doing the porting for new error constructor change and error binding pattern change. Could not reproduce this.

Code used:
```ballerina
import ballerina/io;

# Prints `Hello World`.

public type ErrorData record {|
    string message;
    error cause?;
    string uuid;
|};


public type DatabaseError distinct error<ErrorData>;

public type RequestError distinct error<ErrorData>;

public type MainError DatabaseError|RequestError;

public function getError(anydata|error rslt=(), string? mssg=())
                                                        returns MainError {
    string message = (mssg is string ? mssg : "An error occurred");
    string uuid = "test-uuid"; // system:uuid();

    if (rslt is error) {
        return <MainError> error("etype", uuid=uuid, cause=rslt, message=message);
    }
    else {
        return <MainError> error("etype", uuid=uuid, message=message);
    }
}

public function main() {
    error syserr = error RequestError("re", message="SYSERR", uuid="test-uuid");
    MainError err = getError(syserr);

    // this works..
    //error error(_, message=message, cause=cause, uuid=uuid) = err;

    // this works..
    //RequestError RequestError(message=message, cause=cause, uuid=uuid) =
    //                                                            <RequestError> err;

    // this does not..
    error error MainError(message=message, cause=cause, uuid=uuid) = err;
    if (cause is error) {
        io:println(cause.toString());
    } else {
        io:println(cause.toString());
    }
}
```
