### ISSUE TITLE
Type including anonymous record array

### ISSUE THREAD

**Issue by AlexisUCL** [ballerina-platform/ballerina-lang#26811]
**Description:**
Seems to break when a type is defined that includes an anonymous record array. An anonymous record is fine and, obvs, named arrays are fine.

**Steps to reproduce:**
type Payload record{}[];
public function main() {}

**Affected Versions:**
jBallerina 1.2.8
Language specification 2020R1
Update Tool 0.8.8

**OS, DB, other environment details and versions:**
Windows 10 WSL2 Ubuntu
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/5505302/ballerina-internal.log)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@AlexisUCL, this seems to be a bug that has been fixed in later (Swan Lake Preview) versions. This works as expected on [Swan Lake Preview 5](https://ballerina.io/downloads/swan-lake-release-notes).

Like you mentioned, using an array of a separately defined type would work on 1.2.x versions.

**Comment by mohanvive** [comment]
Closing the issue as per the above comment. Please reopen if you need any further clarification on this.
