### ISSUE TITLE
langlib array returning functions fail at runtime for tuple type

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#26820]
**Description:**
As tuples are a sub type of arrays in ballerina, it is expected certain lang.array function  to support tuple types. 
The following functions (not array specific) does not have proper implementation to support tuple type, which causes failure at runtime. 
- filter
- reverse

**Steps to reproduce:**
```ballerina
[int, string, float] tupleArr = [2,  "abc", 2.4];
any[] y = tupleArr.reverse();
```
This fails with the following exception
```
error: java.lang.ClassCastException {"message":"class io.ballerina.runtime.types.BTupleType cannot be cast to class io.ballerina.runtime.api.types.ArrayType (io.ballerina.runtime.types.BTupleType and io.ballerina.runtime.api.types.ArrayType are in unnamed module of loader 'app')"}
        at ballerina.lang_array.1_1_0:reverse(array.bal:191)
```

**Affected Versions:**
slp5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#18874

**Suggested Labels (optional):**
Team/jballerina, Type/Bug

**Suggested Assignees (optional):**

**Comment by jclark** [comment]
Tuples are arrays: a tuple type `[int, string, float]` is a subtype of the array type `(int|string|float)[]`. Values belonging to the tuple type and to the array type are the same basic type but differ only in their inherent type.

`reverse` is a generic function defined on an array type. So the behaviour should be that at compile-time you find the most precise array type (in this case  `(int|string|float)[]` and you then instantiate a generic function with that type. So the static type of the reverse function call in this case should be `(int|string|float)[]`, as should the inherent type of the returned list value. The list value will have three members.

**Comment by riyafa** [comment]
Since these functions crash at runtime for tuple types, we need to fix this. Hence reopening the issue.

**Comment by jclark** [comment]
Sorry, I got confused about which repo I was in.

**Comment by riyafa** [comment]
@jclark no worries. Thank you for the suggestions 🙂
