### ISSUE TITLE
`lang.array:reverse()` shouldn't create a new array

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26843]
**Description:**
See https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/array.bal#L145

**Steps to reproduce:**
But the following prints `false` atm.

```ballerina
import ballerina/io;

public function main() {
    int[] x = [1, 2, 3, 4];
    int[] y = x.reverse();
    io:println(x === y);
}
```

**Affected Versions:**
slp5

**Comment by warunalakshitha** [comment]
Assigned to @gabilang

**Comment by jclark** [comment]
See https://github.com/ballerina-platform/ballerina-spec/issues/749

Some of the comments in langlib got copied over from the implementation at one point, and I didn't catch this.

**Comment by MaryamZi** [comment]
> See [ballerina-platform/ballerina-spec#749](https://github.com/ballerina-platform/ballerina-spec/issues/749)
> 
> Some of the comments in langlib got copied over from the implementation at one point, and I didn't catch this.

Noted, thank you. Created an issue to track fixing this https://github.com/ballerina-platform/ballerina-lang/issues/28514.
