### ISSUE TITLE
[Tooling] Code snippets for tables and streams 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26848]
**Description:**
I believe it is a good idea to add code snippets for stream and table declarations. It will help end-users to use that syntax effortless manner.

Proposed code snippets.

```ballerina

type Test table<FullName> key<string>;

type TestA table<FullName> key(firstName);

type TestB table<FullName>;

stream<Person, error> personStream = new;

stream<Person> personStream = new;

```

**Comment by nadeeshaan** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/27646

**Comment by mohanvive** [comment]
@nadeeshaan I couldn't find code snippets for streams and tables in SL preview-9 vscode plugin. Is this know issue?
