### ISSUE TITLE
Transaction validates if rollback command is used with if condition, commit should happen in else block

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#26854]
**Description:**
$subject
This becomes an issue when we try to use statements within the loop, we have to wait till loop exit to commit, however, the transaction compiler does not allow that

**Comment by niveathika** [comment]
```
for var count in countArray{
    var queryResult = dbClient->query();
    if(queryResult is error) {
        rollback;
    }
}
commit;
```
The above is not allowed

**Comment by pcnfernando** [comment]
Need to restrict commiting/rollback within loops

**Comment by pcnfernando** [comment]
In order to commit/rollback, you have to have it outside the loop. We have restricted the usage from #27418.
Furthermore, moving into a transactional code path from a non-transactional code path is also restricted. 
eg:
Here commit is not  allowed
```
transaction {
          fooTx();
          if something() {
             rollback;
             // not in transaction mode
             bazNonTx();
             // not in transaction mode
          }
          check commit;
        }
```
