### ISSUE TITLE
Using an error constructor with a user-defined type as the contextually-expected type does not work as expected

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26856]
**Description:**
The [Error constructor](https://ballerina.io/spec/lang/master/#error-constructor-expr) section of the spec says

> An error constructor constructs a new error value. If an error-type-reference is specified, it must denote a type that is a subtype of error; the effect is the same as making the contextually expected type be that specified by the error-type-reference. If there is no applicable contextually expected type, then it is the same as if there were a contextually expected type of error.

**Steps to reproduce:**
But the following doesn't work.

```ballerina
type MyError error<record {int code;}>;

public function main() {
    MyError err = error("error!", code = 100);
}
```

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:4:19: incompatible types: expected 'MyError', found 'error'
```

**Affected Versions:**
slp5

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/26341

**Comment by rdhananjaya** [comment]
@29059 fixes when the contextually expected type is an error, we further need to improve the handling of error constructor when the contextually expected type is a union containing error types.
