### ISSUE TITLE
[Tooling] Duplicated code snippet suggestions 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26863]
**Description:**
Please refer the below code snippet. 

```ballerina
type Student record {
    string firstName;
    string lastName;
    int intakeYear;
    float gpa;
};

type Report record {
    string name;
    string degree;
    int graduationYear;
};

type Test rec

public function main() {

}
```

It provides below duplicated suggestions.

<img width="729" alt="Screenshot 2020-11-11 at 15 17 26" src="https://user-images.githubusercontent.com/7523274/98796300-3c623a80-2431-11eb-95ce-36b171135109.png">

**Comment by nadeeshaan** [comment]
This is fixed in latest master. Hence closing the issue.

<img width="886" alt="Screenshot 2021-01-04 at 11 48 30" src="https://user-images.githubusercontent.com/1329674/103506491-d4edc780-4e82-11eb-8ccc-30eabf47b080.png">
