### ISSUE TITLE
Code suggestion not works for variables within query expression

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26861]
**Description:**
Please refer the below code snippet. In that when accessing student variable, vscode does not provide code suggestions.

```ballerina
Report[] reportList = from Student student in studentList
       where student.gpa >= 2.0
       let string degreeName = "Bachelor of Medicine",
       int graduationYear = calGraduationYear(student.intakeYear)
       order by student.firstName descending
       limit 2
       select {
              name: student.firstName + " " + student.lastName,
              degree: degreeName,
              graduationYear: graduationYear
       };

```

**Comment by nadeeshaan** [comment]
Associated with #28702

**Comment by nadeeshaan** [comment]
The visible symbols does not include the `student` variable in the following cursor postion.

type Student record {
    string firstName;
    string lastName;
    int intakeYear;
    float gpa;
};

```
public function main() {
    Student s1 = {
        firstName: "Michelle",
        lastName: "Sadler",
        intakeYear: 1990,
        gpa: 3.5
    };

    Student[] studentList = [s1];
    var reportList = from Student student in studentList
                    where s<cursor>
}
```

**Comment by IMS94** [comment]
Relates to #28199

**Comment by IMS94** [comment]
@mohanvive @nadeeshaan I tested this on master branch after the merging of https://github.com/ballerina-platform/ballerina-lang/pull/29386/. Completions are now shown within query related constructs.
