### ISSUE TITLE
[Tooling] Intermittent inconsistent behaviour in VSCode error notifications

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26862]
**Description:**
I have tried the query given in the example [1], and VSCode shown a invalid error message. I had to restart the VSCode to recover from this (and to show correct results).

<img width="1062" alt="Screenshot 2020-11-11 at 15 09 58" src="https://user-images.githubusercontent.com/7523274/98795815-aaf2c880-2430-11eb-8695-6b71d1223a3e.png">

[1] https://ballerina.io/swan-lake/learn/by-example/query-expression-to-stream.html

**Comment by nadeeshaan** [comment]
This issue has been fixed with the internal locking implementation in language server. Hence closing this issue. If this issue can be still reproduced, please reopen.
