### ISSUE TITLE
Closure vars not visible to lambdas defined as param default values

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#26893]
Consider the following:
```ballerina
function testLambdaInParam() {
    int a = 10;

    var fn1 = function () {
                                                                         // compiler complains about the reference here
        var fn2 = function (function (int) returns int p = function (int x = a) returns int => x * 2) {
            // do something
        };
    };
}
```
`a` is not visible in the lambda defined as the default value of the param `p`.

**Comment by pubudu91** [comment]
Once fixed, need to enabled the commented test case in `FindRefsInLambdasTest`

**Comment by MaryamZi** [comment]
@chiranSachintha, can you please check this also with the function default value changes?

**Comment by chiranSachintha** [comment]
> @chiranSachintha, can you please check this also with the function default value changes?

Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31589 PR
