### ISSUE TITLE
Let expressions don't seem to be using the contextually-expected type for type-checking

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26906]
**Description:**
$title. Results in the actual expression being type-checked with `noType`, resulting in errors later on.

**Steps to reproduce:**
```ballerina
public function main() {
    record {
        int i;
        int j?;
    } rec = let int v = 1 in {i: v};
}
```

Compilation fails for this with

```cmd
$ ballerina run qwe.bal 
Compiling source
        qwe.bal
error: .::qwe.bal:5:13: incompatible types: expected 'record {| int i; int j?; anydata...; |}', found 'record {| int i; |}'
```

**Affected Versions:**
slp5

**Comment by MaryamZi** [comment]
See https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L2727

**Comment by IMS94** [comment]
@MaryamZi While testing this recently with @dulajdilshan, found out that this issue isn't present in `slalpha1`. It has been addressed in #27596 by checking assign ability. Therefore, seems like #28011 PR is no longer required. Can you verify.

**Comment by MaryamZi** [comment]
#27596 fixed a bug in assignability when the target type has an optional field for which the source type does not have a field, which has fixed this particular error.

But the following now panics at runtime.
```ballerina
public function main() {
    record {
        int i;
        int j?;
    } rec = let int v = 1 in {i: v};

    rec.j = 2; // try assigning a value to the optional field
               // that was not specified when creating the value 
}
```

```cmd
$ bal run qwe.bal 

Compiling source
        qwe.bal

Running executable

error: {ballerina/lang.map}KeyNotFound {"message":"invalid field access: field 'j' not found in record type '$anonType$_1'"}
        at qwe:main(qwe.bal:7)
```

We still need to use the contextually expected type when type-checking to set the proper type when constructing the value.

**Comment by IMS94** [comment]
@MaryamZi I see. Thanks for pointing that out.
