### ISSUE TITLE
[Improvement] Provide an API to create 'readonly' type at runtime

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#26919]
**Description:**
As it is a possible future requirement, it is better to provide an API at TypeCreator to create types with `readonly` flag.  

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#26114 

**Suggested Labels (optional):**
Type/Improvement 
Team/jBallerina

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
I think there are two possible scenarios where a user would need to create a type with its `readonly` flag set.

**Case I**

When creating a new type, the user may need to pass the `readonly`-ness to the relevant method in `TypeCreator`.

I believe this is already present for most types.

e.g.,
- io.ballerina.runtime.api.creators.TypeCreator#createArrayType(io.ballerina.runtime.api.types.Type, boolean)
- io.ballerina.runtime.api.creators.TypeCreator#createMapType(io.ballerina.runtime.api.types.Type, boolean)

Maybe we should go through the current methods and for selectively immutable types allow passing a boolean to indicate `readonly`-ness, for methods that don't support it already. The constructors already support this, so it should be a matter of exposing it via the `TypeCreator`.

**Case II**
The user may need to get a copy of a type, with the `readonly` flag set.

There's a method in `ReadOnlyUtils` to do this - see https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ReadOnlyUtils.java#L73. 

If a method is needed in `TypeCreator`, we should use the logic from `ReadOnlyUtils`.

**Comment by riyafa** [comment]
Currently the support for creating readonly types is present in the TypeCreator apis, hence closing the issue
