### ISSUE TITLE
Project API crashes with `Compile the module first!` when accessing SemanticModel

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#26918]
**Description:**
This issue happens when trying to put several text edits for the project instance and trying to access the SemanticModel through `module.getCompilation().getSemanticModel()`.

Initial debugging found that the **Compile the module first!** is thrown when the BLangPackage is not available in `ModuleContext`.

Further debugging relieved that when we keep on adding changes Project API loads the module compilation state from the BIR cache in https://github.com/ballerina-platform/ballerina-lang/blob/prj_api_module_refactor/compiler/ballerina-lang/src/main/java/io/ballerina/projects/ModuleContext.java#L220.

Eventually this results compilation state to be set `MODULE_SYMBOL_LOADED` and the `BLangPackage` is NULL.

**Affected Versions:**
2.0.0-SLP6-SNAPSHOT

**Comment by sameerajayasoma** [comment]
@rasika, I couldn't reproduce your issues with the following code. please use the `PackageCompilation`, because the `ModuleCompilation` is not yet complete.

```
public void testUpdates() {
        Path projectPath = RESOURCE_DIRECTORY.resolve("single-file").resolve("update.bal");
        SingleFileProject project = null;
        try {
            project = SingleFileProject.load(projectPath);
        } catch (Exception e) {
            Assert.fail(e.getMessage());
        }

        DocumentId documentId = project.currentPackage().getDefaultModule().documentIds().iterator().next();
        PackageCompilation compilation1 = project.currentPackage().getCompilation();

        Document document1 = project.currentPackage().getDefaultModule().document(documentId);
        document1.modify().withContent("public function main() {\n" +
                "\n" +
                "}\n");
        PackageCompilation compilation2 = project.currentPackage().getCompilation();

        Document document2 = project.currentPackage().getDefaultModule().document(documentId);
        document2.modify().withContent("public function main() {\n" +
                "   f\n" +
                "}\n");
        PackageCompilation compilation3 = project.currentPackage().getCompilation();
        SemanticModel semanticModel = compilation3.getSemanticModel(
                project.currentPackage().getDefaultModule().moduleId());

        for (Diagnostic diagnostic : semanticModel.diagnostics()) {
            System.out.println(diagnostic);
        }
    }
```

**Comment by sameerajayasoma** [comment]
Please reopen if you are still having this issue.
