### ISSUE TITLE
The `readonly` flag needs to be set recursively in selectively immutable types created at runtime

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26991]
**Description:**
Consider the following `BMapType` constructor.

```java
public BMapType(String typeName, Type constraint, Module pkg, boolean readonly) {
    super(typeName, pkg, MapValueImpl.class);
    this.constraint = constraint;
    this.readonly = readonly;
} 
```

Here, in addition to setting the `readonly` flag of the `BMapType`, we should recursively set the `readonly` flag to the constraint type too. 

```java
this.constraint = ReadOnlyUtils.setImmutableTypeAndGetEffectiveType(constraint);
```

For example, if a `map<int[]>` is created with `readonly` set to true,
- the constraint type has to be `int[] & readonly`
- the map type should thus be `map<int[] & readonly> & readonly`

Otherwise, the initial values of the map may not be validated to be immutable.

The types are set correctly for values in the ballerina source, since we set this type recursively at compile-time. The issue is for types created in external code.

Related discussion - https://ballerina-platform.slack.com/archives/CAXS256RX/p1605633734138700

**Affected Versions:**
slp5

**Comment by manuranga** [comment]
related issue #27029
