### ISSUE TITLE
Calling Java Code from Ballerina doc does not have mapping to arrays, maps

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#27017]
**Description:**
It seems https://ballerina.io/learn/calling-java-code-from-ballerina/ missing how user can map ballerina arrays,map, record and other types to java classes when writing interop methods. IMO we can improve the doc with those data.

**Comment by gabilang** [comment]
https://github.com/ballerina-platform/ballerina-dev-website/pull/1739
Above PR will provide the requirements.
