### ISSUE TITLE
Compilation error which says Failed to Read Markdown Documentation

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#27021]
**Description:**
A compilation error is thrown saying `error: failed to read Markdown Documenation` when building a newly created Ballerina module or even a single .bal file with slp6 latest SNAPSHOT.

**Steps to reproduce:**
First, we need to build a Ballerina slp6 SNAPSHOT distribution using the latest code in ballerina-lang master branch.
Then add that distribution's bin folder to the system PATH variable.
Then issue the following sequence of commands.

```
ballerina new proj1
cd proj1
ballerina add mod1
cd src/mod1
ballerina build -a -c
```
Execution of the final command should throw the following error. Note that here the error message also has a typo `Documenation`.

```
error: failed to read Markdown Documenation
```
The same error gets thrown even if we try to build a simple Hello World `.bal` file with the following command.

`ballerina build main.bal`

**Affected Versions:**
I have used the latest code from Ballerina lang master branch which will be release as slp6 near future.

**OS, DB, other environment details and versions:**
Ubuntu 18.04, Balerina slp6 latest SNAPSHOT

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by MaryamZi** [comment]
Can you please try with a clean build from the master? If there are any standard library imports/other dependencies those also need to have been built using the ballerina-lang master.

There were few changes to the BIR and this could be due to dependencies compiled on a previous version.

**Comment by miyurud** [comment]
After following the steps @MaryamZi mentioned I was able to build a Ballerina distribution which does not throw such error. However, the typo on the error message needs to be fixed.
