### ISSUE TITLE
Need to way to get Package.md, Module.md and resources from a Project through Project API.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#27032]
**Description:**
Currently there is no way of getting the Package.md, Module.md(s) and resources through a `io.ballerina.projects.Project`(parent of BuildProject or BaloProject) object. The implementations are different for each type of project if we want to get the mentioned files. If there is a way to get these mentioned files from within `io.ballerina.projects.Project` object then it would be satisfied. 

Example requirement: https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/docerina/src/main/java/org/ballerinalang/docgen/docs/BallerinaDocGenerator.java#L561-L592

Suggested fix:
`Package.getAdditionalDocument(Type.Package_MD)`

**Steps to reproduce:**

**Affected Versions:**
SLP6-Snapshot
**OS, DB, other environment details and versions:**
Mac

**Comment by hevayo** [comment]
This is implemented
