### ISSUE TITLE
A warning is printed when running tests using testerina

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#27047]
**Description:**
When we run the tests after the new Package API change, there is a warning printed:

```
Could not write to Rerun Test json. Rerunning tests will not work:<rpoject_source>/target/caches/json_cache/ballerina/reflect/0.5.2/rerun_test.json (No such file or directory)
```

The tests are passing even this warning is printed. 

You can check the log from here:
https://github.com/ballerina-platform/module-ballerina-reflect/pull/24/checks?check_run_id=1430679466

Building [ballerina-reflect module](https://github.com/ballerina-platform/module-ballerina-reflect) can reproduce this issue.

**Comment by Ibaqu** [comment]
Fixed with : https://github.com/ballerina-platform/ballerina-lang/pull/27081
