### ISSUE TITLE
Configurable and Isolated qualifiers doesn't work together 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#27092]
```ballerina
configurable isolated int x = ?;

public function main() {
   
}
```

Get following error, 
```
ERROR [test.bal:(1:1,1:33)] an uninitialized module variable declaration cannot be marked as 'isolated'
```

**Comment by rdulmina** [comment]
The isolated qualifier is not allowed with configurable.
>module-init-var-decl := metadata [public] module-init-var-quals typed-binding-pattern = module-var-init ;
module-init-var-quals := (final | isolated-qual)* | configurable
