### ISSUE TITLE
Make timeout and thread pool sizes configurable for workers

### ISSUE THREAD

**Issue by chanakaudaya** [ballerina-platform/ballerina-lang#2709]
In the current implementation, worker timeout is hard coded within the ballerina native code. This needs to be configured through ballerina program. 

Thread pool size for workers is currently hard coded. It is better to make this configurable.

**Comment by hasithaa** [comment]
In the current design, workers don't require a timeout as we are waiting till workers to complete itself. 

But the requirement of the thread pool configuration is not addressed yet. It will get added with new worker scheduler.

**Comment by lafernando** [comment]
The worker thread pool size can be now given by setting the Ballerina environment property "b7a.runtime.scheduler.threadpoolsize". This is set to 100 by default.
