### ISSUE TITLE
Add a BIR test for custom raw template types

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27145]
PR #27062 fixed an issue where when there was a subtype of `RawTemplate` defined in a module, and this module was imported in a source file through its BIR form, you couldn't assign raw templates to vars of that type. Need to add a BIR test for this once #27049 is fixed.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
