### ISSUE TITLE
Providing access to an expression's actual type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27143]
Consider the following:
```
int a = true;
```
In the above case, the RHS expr's type gets set to semantic error. This is because we type check it against the contextually expected type (LHS type) for it. 

Need to see instead of doing that, whether we can independently determine the type of the RHS expr.

If not, at least provide a way to have access to the actual type of the RHS expr.

**Comment by MaryamZi** [comment]
@pubudu91, isn't this what `determinedType` was introduced for?
