### ISSUE TITLE
Debugger needs to be aligned with the service changes

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27157]
**Description:**
Currently `:jballerina-debugger-integration-test:test`s are failing in `service-typing` branch.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
@rdhananjaya Is this issue still valid or was this fixed?

**Comment by rdhananjaya** [comment]
Currently all the debugger tests seems to be running, but not sure if debugger is aligned with the service changes or not.

**Comment by NipunaRanasinghe** [comment]
@rdhananjaya We have moved all the service related debugging tests into the distribution repo and all the tests are currently enabled. Hence closing the issue.
