### ISSUE TITLE
Align language-server with service type change

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27150]
**Description:**
$title.

Note: Some code in the language-server were commented out in https://github.com/ballerina-platform/ballerina-lang/commit/0276b16d08fa72ba18093000a89dbe8664652c36

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Fixed
