### ISSUE TITLE
Ambiguous Compilation Error Messages

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#27178]
**Description:**
Since the new Project API changes, the compilation error messages are changed. The new format is somewhat ambiguous when it shows the file name in which the error occurred.

Consider a scenario where two or more modules have a file with the same name, similar to the following:

```
foo
├── Ballerina.toml
├── Package.md
├── main.bal
├── modules
│   └── bar
│       ├── bar.bal
│       └── utils.bal
└── utils.bal
```

When there is a compilation error, the error message simply says 

```
ERROR [utils.bal:...] ...
```

This does not express the which `utils.bal` file is having the error. It should print the path to the file, instead of just printing the name.

**Comment by azinneera** [comment]
Closing since this was resolved by #27705
