### ISSUE TITLE
Instructions on how run a package aren't clear

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27181]
I tried to create a new project and run it. But the instructions I got from the CLI weren't clear. This is what I did:
- Create a new project named `slp6-proj`
- Navigate to the project directory and added a new module named `foo`
- Tried to run it by running `ballerina run slp6-proj` and `ballerina run slp6_proj`. But it didn't work. Got the following error:
```
ballerina: The directory does not exist: /home/pubudu/b7a-projects/slp6-proj/slp6_proj
```
- Then tried to run the generated `main.bal` file using `ballerina run main.bal`. Didn't work either:
```
ballerina: The source file '/home/pubudu/b7a-projects/slp6-proj/main.bal' belongs to a Ballerina package.
```
- Navigated outside the project directory and tried `ballerina run slp6-proj` and it worked.
- Again, inside the project directory, tried `ballerina run` and it gave the following:
```
$ ballerina run
ballerina: no project path provided.

USAGE:
    ballerina run {<ballerina-file | project-name> | <executable-jar>} [--] [(--key=value)...]
```
- But finally, what worked was running `ballerina run .`

This needs to be properly documented.

**Comment by azinneera** [comment]
We have made the run command similar to the buil command and updated the CLI help text. Please refer to help text of SLAlpha3 and reopen this issue if anything is unclear
