### ISSUE TITLE
[SLP6] Failed to load test init class when module name contains `bal` or `ballerina`

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#27201]
**Description:**
$subject

**Steps to reproduce:**
- Create a ballerina project with the name of `balPraject`
- Add a module to it with the name of `balModule`
- Add a test file to the module.
- Add the following to the test file

> import ballerina/test;
> 
> @test:Config {}
> public function testFunc() {
>     string testString = "test";
>     test:assertEquals(testString, "test");
> }

- Compile the project with the command `ballerina build` or run the test with the command `ballerina test`

The following error will occur
`error: failed to load Test init class :praveen.balProject$0046balModule.0_1_0.balProject$$$balModule`

Complete console output:

> Compiling source
>         praveen/balProject:0.1.0
> 
> Creating balos
>         target/balo/praveen-balProject-any-0.1.0.balo
> 
> Running Tests
>         balProject.balModule
> error: failed to load Test init class :praveen.balProject$0046balModule.0_1_0.balProject$$$balModule
> 
>         balProject
>         No tests found
> error: there are test failures

This is happening when the module name contains `bal` or `ballerina` etc.
eg: `balModule` or `ballerinaModule`

The above scenario is not reproducible if the module name is something like `myModule`

**Affected Versions:**
`Ballerina Swan Lake Preview 6`

**Comment by jclark** [comment]
I just ran into this.

**Comment by warunalakshitha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/27234
