### ISSUE TITLE
No init var declaration is allowed with any binding pattern in parser

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#27259]
**Description:**
According to  [spec](https://ballerina.io/ballerina-spec/spec.html#module-no-init-var-decl) no init var declaration is only allowed with capture binding pattern, but parser allows for any binding pattern. Need to fix this for both local and module variable declaration.

Address TODO in DataflowAnalyzer at `L348`

**Suggested Labels (optional):**

- Area/Parser
- Type/Bug
- Team/CompileFE

**Comment by SupunS** [comment]
We can parse them as we do now, but validate once parsed

**Comment by rdulmina** [comment]
Local uninitialized var validation is added in #26599

**Comment by MaryamZi** [comment]
@rdulmina, as discussed let's check and disallow the following too.

```ballerina
public function main() {
    [int, int] [x, y]; // invalid
    x = 1;
    y = 2;
}
```
