### ISSUE TITLE
Forced to connect multiple times when debugging ballerina tests in a multimodule project

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#27250]
**Description:**
For a multi-module project, add tests for each module and build the multimodule project in debug mode using the command `ballerina build --debug 5005`. For each module tests, we have to connect to the debug server separately. The expected behaviour is all module tests have to be run with the single debug server connect.

**Steps to reproduce:**
- Create a multimodule project.
- Add tests for each module
- Build the multimodule project using the command `ballerina build --debug 5005`

Sample multimodule structure:
![image](https://user-images.githubusercontent.com/11292766/100568124-4967a080-32f0-11eb-9337-440f7d9dbb8d.png)

- We have connect to the debug server separately for each module tests.

The following would be the console out after connecting separately for each module test:

> praveen:balProject praveen$ /Users/praveen/Desktop/ballerina-swan-lake-preview6-SNAPSHOT/bin/ballerina build --debug 5005
> 
> Compiling source
>         praveen/balProject:0.1.0
> 
> Creating balos
>         target/balo/praveen-balProject-any-0.1.0.balo
> 
> Running Tests
>         balProject
> **Listening for transport dt_socket at address: 5005**
> 
>         [pass] testFunc
> 
>         1 passing
>         0 failing
>         0 skipped
> 
>         balProject.mymodule
> **Listening for transport dt_socket at address: 5005**
> 
>         [pass] testModuleFunc
> 
>         1 passing
>         0 failing
>         0 skipped
> 
> 
> Generating executable
>         target/bin/balProject.jar

**Affected Versions:**
`Ballerina Swan Lake Preview 6`

**Comment by NipunaRanasinghe** [comment]
Closing since this is already fixed with the latest Testerina runtime improvements.
