### ISSUE TITLE
[Testerina] Enable Testerina tests

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#27271]
**Description:**
Testerina tests keep failing because of the Process getting killed during PR checks. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Limitations of Logleacher will be addressed with https://github.com/ballerina-platform/ballerina-lang/issues/27683
