### ISSUE TITLE
[Formatter] - Improper indentation  

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#27293]
**Description:**
The indentation of the below code for payload changes when do formatting.

```
json jsonPayload = {
        "errors": [
                {
                    "index": 0,
                    "statusCode": 400,
                    "message": "Invalid token"
                }
            ]
    };
```
The braces inside `errors` filed are not indented correctly after doing `ballerina format`.

**Steps to reproduce:**
- Apply the above code inside a function
- Do `ballerina format`

**Affected Versions:**
1.2.x

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Component/Formatting

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
This is fixed in slp versions. Following is the formatted output:
```ballerina
public function foo() {
    json jsonPayload = {"errors": [{
            "index": 0,
            "statusCode": 400,
            "message": "Invalid token"
        }]};
}

```
