### ISSUE TITLE
Documentation when hovering over a function seems to be rendered with broken formatting

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27296]
Refer to the following image:
![cap1](https://user-images.githubusercontent.com/6260009/100850668-284aaf80-34aa-11eb-8008-5d30d51cf5c3.jpg)
Note how the the sample code is rendered. In the actual documentation in the code, it looks like the following:
```ballerina
# Prints `any` or `error` value(s) to the STDOUT followed by a new line.
#```ballerina
#io:println("Start processing the CSV file from ", srcFileName);
#```
#  
# + values - The value(s) to be printed
public isolated function println((any|error)... values) = @java:Method {
    name: "println",
    'class: "org.ballerinalang.stdlib.io.nativeimpl.PrintUtils"
} external;
```

**Comment by prabushi** [comment]
This is fixed in SLP9.
<img width="591" alt="Screenshot 2021-01-21 at 12 30 29" src="https://user-images.githubusercontent.com/5234623/105315003-b444a200-5be4-11eb-8050-33ada28896dd.png">
