### ISSUE TITLE
Re-enable observability integration tests after service typing change

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27300]
**Description:**
Commit: https://github.com/ballerina-platform/ballerina-lang/commit/4c1d0f489684e03f2d4db13048d84c50f8b521f7

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadundesilva** [comment]
Depends on #27402

**Comment by nadundesilva** [comment]
Closing as the test cases had been enabled.
