### ISSUE TITLE
Re-enable disabled ModuleExecutionFlowTests

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27306]
**Description:**
Commit: https://github.com/ballerina-platform/ballerina-lang/commit/4c1d0f489684e03f2d4db13048d84c50f8b521f7

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
Some of the observability test are disabled with the mentioned PR. The disabled packaging test case is enabled already.

**Comment by rdhananjaya** [comment]
There is a separate issue[1] for disabled observability tests.
[1] - https://github.com/ballerina-platform/ballerina-lang/issues/27300
