### ISSUE TITLE
Introduce TimeStamp object to deal with timestamps in Transactions

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#27334]
Please refer to this (https://github.com/ballerina-platform/ballerina-spec/issues/267#issuecomment-737944898)

**Comment by jclark** [comment]
"timestamp" is one word in English, so it should be `Timestamp` rather than `TimeStamp` cf https://docs.oracle.com/javase/7/docs/api/java/sql/Timestamp.html
