### ISSUE TITLE
Unable to install ballerina (ballerina-macos-installer-x64-1.2.10.pkg) on Mac OS Big Sur

### ISSUE THREAD

**Issue by vm2600** [ballerina-platform/ballerina-lang#27331]
**Description:**

Unable to install ballerina (ballerina-macos-installer-x64-1.2.10.pkg) on Mac OS Big Sur. It reports the following error when double-clicking it to install:
“ballerina-macos-installer-x64-1.2.10.pkg” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
We are working on it by notarizing the installer with Apple.
Here its not possible to continue the installation as there is only "OK" button as below

![Screenshot 2021-04-19 at 14 29 41](https://user-images.githubusercontent.com/2918812/115210029-ce2a4e00-a11b-11eb-8aa1-b11e06bce6d1.png)

However there is a temporary workaround in mac where you need to right click and click open. Then you will get "Open" button as below 
![Screenshot 2021-04-19 at 14 29 55](https://user-images.githubusercontent.com/2918812/115210130-ef8b3a00-a11b-11eb-9bde-101a2a10f26f.png)

**Comment by keizer619** [comment]
This has been fixed from swan lake beta1 onward by notarizing the installers
