### ISSUE TITLE
Support variable forward referencing for a variable declared with `var`

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#27354]
**Description:**
Consider the following code
```
int a = b;
var b = 6;
public function main() {

}
```
Gives the error `incompatible types: expected 'int', found 'other'` which is less informative. Need to improve the  error msg to something like ` variable declared with 'var' does not support variable forward referencing`

**Suggested Labels (optional):**

- Type/Improvement
- Team/CompilerFE

**Comment by MaryamZi** [comment]
Why should this result in a compilation error anyway?

**Comment by rdulmina** [comment]
> Why should this result in a compilation error anyway?

Yes, we can support this from the implementation
