### ISSUE TITLE
Json to record conversion fails when json has a dot in the key

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#27364]
**Description:**
$Subject.  Compiler gives a nullpoint exception when the following code is executed. 
```
error: java.lang.NullPointerException
        at ballerina.lang$0046value.1_0_0:cloneWithType(value.bal:75)
           anjana.bal_json.0_1_0:main(main.bal:8)
```

**Steps to reproduce:**
Execute the following Code.
```ballerina
import ballerina/io;

public function main() {
    json j1 = {
        "System.AreaPath": "FabrikamCloud"
    };

    Hello|error hello = j1.cloneWithType(Hello);
    if (hello is error) {
        io:println("Parsing fails");
    } else {
        io:println(hello);
    }

}

type Hello record {|
    string 'System\.AreaPath;
|};
```
**Affected Versions:**
SLP7

**OS, DB, other environment details and versions:**
Ubuntu 20.04

**Comment by MaryamZi** [comment]
Seems like the key is not decoded when retrieving the field at https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeConverter.java#L331, returning null and thus resulting in an NPE in the next line.
