### ISSUE TITLE
Enable tests disabled in #27284

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#27361]
**Description:**
Two unit tests are disabled in #27284 because those errors cannot reproduce and should try to enable or change them

**Affected Versions:**
slp7

**Comment by MaryamZi** [comment]
@KavinduZoysa, can you please mention the disabled tests here?

**Comment by KavinduZoysa** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/27284/commits/f85f088a95ac1748f178e0b24fdb244ae4cdafb4#diff-bdfbda56a184b93158269850b971a366eb5f69cc4f7e056af7b2a623439043e3R57

This is the disabled test and it is enabled now.
