### ISSUE TITLE
Detect dependency cycles in package dependencies and modules within a package

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#27371]
**Description:**
$subject.

**Comment by azinneera** [comment]
At the moment having cycles between two modules produces incorrect diagnostic `cannot resolve module` for one of the 
modules.

**Actual Output**
```
Compiling source
	asmaj/proj1:0.1.0
ERROR [main.bal:(2:1,2:30)] cannot resolve module 'asmaj/proj1.mod1 as _'
error: compilation contains errors
```

**Expected Output**
```
Compiling source
	asmaj/proj1:0.1.0
ERROR [main.bal:(1:1,1:25)] cyclic module imports detected 'asmaj/proj1 -> asmaj/proj1.mod1'
error: compilation contains errors
```
The above output can be produced by making a module import its own self. A similar diagnostic should be reported for cycles between different modules as well.

**Steps to reproduce:**

1. Create a new ballerina package and add another module using `bal new` and `bal add`:
```bash
proj1
├── Ballerina.toml
├── main.bal
└── modules
    └── mod1
        └── mod1.bal
```
2. Update main.bal content and add an import to `mod1` module:
```ballerina
import asmaj/proj1.mod1 as _;

public function main() {
}
```

3. Update mod1.bal content and add an import to the default module: 
```ballerina
import asmaj/proj1 as _;

public function hello() {
}
```
4. Build the package using `$ bal build`

**Comment by MaryamZi** [comment]
Need to enable org.ballerinalang.test.imports.ImportsTest#testCyclicImports when fixing this.
