### ISSUE TITLE
Validate Ballerina.toml

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#27370]
**Description:**
Interoperate JSON schema validator to Ballerina.toml.

- [ ] Define JSON Schema to toml
- [ ] Validate dependencies platform libs 
- [ ] Validation errors should be added to diagnostics and showed in VSCode.

**Comment by pramodya1994** [comment]
This issue fixed with the following PRs
- https://github.com/ballerina-platform/ballerina-lang/pull/28464
- https://github.com/hevayo/ballerina-lang/pull/10
