### ISSUE TITLE
Client responseLimit configs are not applying for the failover and loadbalance clients

### ISSUE THREAD

**Issue by chashikajw** [ballerina-platform/ballerina-lang#27389]
**Description:**

As $subject client responseLimit which are,

```
responseLimits : {
        maxStatusLineLength : 50,
        maxHeaderSize : 1000,
        maxEntityBodySize: 50
        }
```

not applicable for the failover and loadbalance clients. it's only applying for the normal http client.

**Steps to reproduce:**

1.  Configure a b7a service with a loadbalance or failover client with following configs
`    responseLimits : {
        maxStatusLineLength : 50,
        maxHeaderSize : 10,
        maxEntityBodySize: 50
        }`

2. Set the backend which is responding with a resoonse haeder which is larger than given configs.
3. You will receive the response without having any erros, that means configs are not applying correctly.

**Affected Versions:**
1.2.11

**Related Issues (optional):**

https://github.com/ballerina-platform/ballerina-lang/issues/27251

**Comment by chamil321** [comment]
LB and FO use specific configuration records other than the common client config internally. Newly added `responseLimits` config has not been manually passed to them. 

https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/http/src/main/ballerina/src/http/resiliency/load_balance_client_endpoint.bal#L349

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/27578, hence close the issue
