### ISSUE TITLE
Two same worker name breaking ballerina.

### ISSUE THREAD

**Issue by ASMohamedFaheemAnver** [ballerina-platform/ballerina-lang#27403]
Take a look at this code :

```
import ballerina/io;
public function main() {
    @strand {thread: "any"}
    worker w1 {
        io:println("Hello, World! #n1");
    }

    @strand {thread: "any"}
    worker w2 {
        io:println("Hello, World! #n2");
    }

    @strand {thread: "any"}
    worker w1 {
        io:println("Hello, World! #n3");
    }
}

```

I think this exception has not been handled.

**Comment by rdhananjaya** [comment]
@ASMohamedFaheemAnver can you specify the Ballerina version you faced this error with.

I tried this on Swanlake preview 7 and it doesn't seem to break the compiler, however it prints an error message.

```
dhananjaya Samples $ ballerina run main.bal

Compiling source
        main.bal
ERROR [main.bal:(14:12,14:14)] redeclared symbol '0w1'
ERROR [main.bal:(14:12,14:14)] redeclared symbol 'w1'
error: compilation contains errors
```

**Comment by ASMohamedFaheemAnver** [comment]
I have tried this code in **UBUNTU 18.04 LST** .

When I type `ballerina --version`, 
It returns
```
jBallerina 1.2.11
Language specification 2020R1
Update Tool 0.8.10
```

**Comment by rdhananjaya** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/25875

**Comment by rdhananjaya** [comment]
Closing as this is a Ballerina 1.x issue and there is an issue #25875 to improve this further
