### ISSUE TITLE
Add support to read Service Base Path from the BIR Service Type

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#27402]
**Description:**
At the moment, Compiler Automated Observability Instrumentation is done at the Compiler Backend by modifying the BIR. We need a user readable service name / base path (this won't be available for anonymous services), that can be included in the Observability data.

Currently since only the generated service names are available (eg:- `$anonType$_0`), we can only provide this name in the Observability Data. The generated names does not make a lot of sense for the users since this cannot be mapped to the source code. Therefore, we need the base path or any other useful data about the service in the BIR as well.

**Affected Versions:**
SLP8 Snapshot

**Comment by rdhananjaya** [comment]
By design service base path is not a part of service declaration. We might need to discuss this further.
