### ISSUE TITLE
Need to Update the CLI Outputs of the Update Tool

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#27407]
**Description:**
Need to update the CLI Outputs of the Update Tool to have an uppercase "T" for the "Ballerina Tool". This is connected with [1].

**Steps to reproduce:**

**Affected Versions:**

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1585#discussion_r538034601

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/28588/files
