### ISSUE TITLE
Task :ballerina-lang:annotations:ballerinaLangLibBuild failing

### ISSUE THREAD

**Issue by n-jay** [ballerina-platform/ballerina-lang#27437]
**Description:**
`Task :ballerina-lang:annotations:ballerinaLangLibBuild` failing when trying to run unit tests.
Initially was unsure if it was due to code changes in my feature branch, but the failure persists in the **unedited local master** branch as well which has been updated from the upstream.

**Steps to reproduce:**
Can be reproduced by 2 ways;

- Run a unit test one of the CLI features, eg; `NewCommandTest.java`
![image](https://user-images.githubusercontent.com/24616975/101775044-ec03f880-3b14-11eb-83d4-9db9591d7612.png)
- Run `./gradlew build -x test`
![image](https://user-images.githubusercontent.com/24616975/101775091-fc1bd800-3b14-11eb-8e26-8a8eb7ac763b.png)

**OS, DB, other environment details and versions:**
Ubuntu 20.04
Java 11.0.9 2020-10-20 LTS

**Comment by hevayo** [comment]
I am unable to recreate this issue in latest master. Can you please try building after a `git clean`.

**Comment by n-jay** [comment]
Upon further investigation, I've isolated that this particular build failure;  `Task :ballerina-lang:annotations:ballerinaLangLibBuild FAILED` happens whenever I do a change to the classes I'm working on. The classes being **NewCommand.java** and **ProjectUtils.java**

At the moment, the bit of additional code I've written is only a mere variable declaration and nothing more, as shown below
![image](https://user-images.githubusercontent.com/24616975/110986984-72d6a480-8394-11eb-9b54-ac5d626d3aee.png)
It's very confusing to me how this simple addition can cause the build to fail

> Can you please try building after a `git clean`.

Tried this as well as a `./gradlew clean build`, made no difference.
Would love a solution to this as I'm unable to make any changes atm.

**Comment by Ibaqu** [comment]
I have tested additions to the NewCommand class as described in the issue along with running all the tests that were failing and it seems that it cannot be reproduced in Swan-lake Beta. 

To my knowledge, since then new options have been added and existing ones modified without this test failure popping up. 

@n-jay  Would you consider getting a new fork and giving this a go in the latest master?

**Comment by n-jay** [comment]
Yes, I'll try that. Closing this issue for the time being
