### ISSUE TITLE
Improve the description of ballerina help command

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#27445]
**Description:**

The output of `ballerina help` command is as follows. Is it correct to say `The Ballerina build tool`?  It is not only for `build`. So shall we consider reword it?

```sh
ballerina help
NAME
       The Ballerina build tool

```

**Comment by keizer619** [comment]
I think we can include `The Ballerina tool` to represent all

**Comment by keizer619** [comment]
This is fixed in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/28186
