### ISSUE TITLE
Included record parameters are getting iterated in the reverse order

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#27447]
**Description:**
$Subject

**Steps to reproduce:**
Run the following sample.
```
import ballerina/io;

public type Value anydata;

public type KeyValues record {|
    never msg?;
    Value...;
|};

public function main() {
    foo("hello world", id = 1234, name = "alpha", pass = true);
}

function foo(string msg, *KeyValues keyValues) {
    string message = msg;
    foreach [string, Value] [k, v] in keyValues.entries() {
        message = message + ", " + k + " = " + v.toString();
    }
    io:println(message);
}
```

The output is:

```
hello world, pass = true, name = alpha, id = 1234
```
However, the expected output is"

```
hello world, id = 1234, name = alpha, pass = true
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
It's not exactly in reverse, right? Even the following prints the same for me.

```ballerina
foo("hello world", pass = true, id = 1234, name = "alpha");
```

Mappings (maps and records) in Ballerina are not ordered. So we can't expect an order to be preserved. 

The spec does say

> A mapping is iterable: the iteration sequence consists of the members of the mapping and the iteration completion value is always nil. The order of the iteration sequence is implementation-dependent, but implementations are encouraged to preserve and use the order in which the fields were added.

But this is not a must. So there is no error in the current behaviour.

**Comment by rdhananjaya** [comment]
Closing as mapping does not required to be ordered
