### ISSUE TITLE
Introduce a symbol for type defs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27462]
Currently, we don't create a separate symbol for type defs in the compiler. We use the resolved type's type symbol itself during symbol enter. Because of this, we can't add meta info about the type def to the symbol in some cases like the following:
```ballerina
type Foo int;
```
Fixing this is a prerequisite for #27461

**Comment by pubudu91** [comment]
Related issues: #26283, #26284, #27190, #27461

**Comment by KavinduZoysa** [comment]
![Screenshot from 2023-03-03 12-52-46](https://user-images.githubusercontent.com/28332708/222657423-4cf96093-ca3a-4e55-b82a-e0be7570a89e.png)
Now we have a separate symbol for this.
