### ISSUE TITLE
Inconsistent behaviour with `lang.value:substring` when the effective end index is less than the start index

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#27474]
**Description:**
`lang.value:substring` creates a substring from the start index (inclusive) to the end index (exclusive).

https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.string/src/main/ballerina/string.bal#L63

But the behaviour seems to be inconsistent for different scenarios where the effective end index is less than the start index. 

When "effective end index - startIndex"
- is `-1` - returns empty string
- is < `-1` - panics

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    string str = "ABCDEF";
    
    io:println(str.substring(1, 3)); // "BC"
    io:println(str.substring(1, 2)); // "B"
    io:println(str.substring(1, 1)); // empty string - start index 1, effective end index - 0
    io:println(str.substring(2, 1)); // panics - "message":"invalid substring range. Length:'6' requested: '2' to '1'"
                                     //            start index 2, effective end index - 0
}
```

**Affected Versions:**
slp7

**Comment by Nadeeshan96** [comment]
Current behaviour is correct according to [this spec issue](https://github.com/ballerina-platform/ballerina-spec/issues/1061) answer. Hence closing this issue.
