### ISSUE TITLE
Improve the toString functions in the java module

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#27470]
**Description:**
Currently, the java module constitutes of two functions for the `toString` capability, namely `toString` [1] and `jObjToString` [2] to retrieve the object value of a java representation. We could combine these 2 by eliminating the latter.

[1] https://ballerina.io/swan-lake/learn/api-docs/ballerina/index.html#/java/functions#toString
[2] https://ballerina.io/swan-lake/learn/api-docs/ballerina/index.html#/java/functions#jObjToString

**Steps to reproduce:**

**Affected Versions:**
SLP7

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Added Team/JBallerina as this is about java interop.
