### ISSUE TITLE
No Diagnostics are displayed when a function with a missing relative resource path is compiled

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#27485]
**Description:**
The following code sample compiles without any diagnostic errors.

```
import ballerina/http;

service hello on new http:Listener(9090) {
    resource function get () {

    }
}
```

The relative resource path is missing in the above resource function.

**Steps to reproduce:**

- Compile the above source code using `ballerina build filename.bal`

**Affected Versions:**

- _SLP-7_

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

- _Area/Diagnostics_ 

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
I think we didn't ship new service change with slp7. So with slp7 grammar we can define a resource function like above.

**Comment by lochana-chathura** [comment]
@sanjana we can close this issue right?

**Comment by sanjana** [comment]
@lochana-chathura yes, since the issue has been resolved and the current `Ballerina Swan Lake Alpha 1` version does not produce this issue anymore, I'll be closing it.
