### ISSUE TITLE
Support intersection types as a type reference in an object type inclusion

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#27501]
**Description:**
Following sample throws an incompatible type exception: `incompatible types: 'Timestamp' is not an object`.

**Steps to reproduce:**
Sample:
```ballerina
public type Timestamp readonly & object {
    public function toMillisecondsInt() returns int;
    public function toString() returns string;
};

class TimestampImpl  {
    *Timestamp;
    public function toMillisecondsInt() returns int {
        return 0;
    }
    public function toString() returns string {
        return "test";
    }
}

```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Spec discussion - https://github.com/ballerina-platform/ballerina-spec/issues/649#issuecomment-745788381 onward.

**Comment by MaryamZi** [comment]
Even though inclusion will be allowed with a `readonly` and object intersection, according to the spec, this will
- not be allowed in an object type descriptor
- will be allowed in a class only if the class is also `readonly`
