### ISSUE TITLE
Annotations should be in a separate symbol space hence same named annot value and annot tag name should be allowed

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27500]
**Description:**
Spec says: `An annotation-decl declares an annotation tag. Annotations tags are in a separate symbol space and cannot conflict with other module level declarations and definitions. The annotation tag symbol space is also distinct from the symbol space used by module prefixes and XML namespace prefixes.`

Hence following should be possible:
```ballerina

type T record {|
    int i = 0;
|};

annotation T T on function; //error: annotation declaration requires a subtype of 'true', 'map<anydata|readonly>' or 'map<anydata|readonly>[]', but found 'T'

@T {}
public function main() {
    
}
```

**Steps to reproduce:**

**Affected Versions:**
SLP7
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Seems to happen only when the type-descriptor and the tag are the same.

The following works even though there is both an annotation and a type definition with the same name.

```ballerina
type Foo record {|
    int i = 0;
|};

type Bar record {|
    int i = 0;
|};

annotation Bar Foo on function;

@Foo {}
public function main() {
    
}
```
