### ISSUE TITLE
'array' and 'value' lang library module symbols are missing in the new semantic API visible symbols response

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#27520]
**Description:**
While using the new semantic APIs to retrieve visible lang lib function definitions as a part of debugger expression evaluation,
I've noticed only few of the lang library module symbols are missing in the visible symbols response, like `lang.array` and `lang.value`.

**Steps to reproduce:**
Try to invoke `semanticModel.visibleSymbols(fileName,position)` in a function scope.

**Affected Versions:**
SLP8-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
If these modules weren't explicitly imported, then this behaviour is correct. Only lang libraries which have names corresponding to keywords are predeclared. See https://ballerina.io/spec/lang/master/#predeclared-prefix

**Comment by NipunaRanasinghe** [comment]
> If these modules weren't explicitly imported, then this behaviour is correct. Only lang libraries which have names corresponding to keywords are predeclared. See https://ballerina.io/spec/lang/master/#predeclared-prefix

Ack. For now I will try using injected imports as a workaround, as per the offline discussion we had.

In the meantime, IMO it would be great if we can have an API to retrieve all the visible lang lib symbols.

**Comment by pubudu91** [comment]
Had a chat with @azinneera as well regarding this. What if we add a new method to `SemanticModel` which will return a `LangLibrary` instance? e.g., `public LangLibrary langLibrary();`

Can be the same instance or a modified version of this: https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/LangLibrary.java

@hasithaa @nadeeshaan @mohanvive

**Comment by NipunaRanasinghe** [comment]
Closing since this requirement becomes invalid with https://github.com/ballerina-platform/ballerina-lang/pull/30205.
