### ISSUE TITLE
`remote function` snippet still has the `public` access modifier

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#27557]
**Description:**
With the service changes, a `remote` method can no longer have an access modifier, but the `remote function` snippet still has the `public` access modifier.

Accepting the snippet thus results in compilation errors.

**Steps to reproduce:**
```ballerina
import ballerina/http;

service /foo on new http:Listener(8080) {
    public remote function f1() {
        
    }
}

client class Foo {
    public remote function f2() {
        
    }
}
```

**Affected Versions:**
slp8-SNAPSHOT

**Comment by nadeeshaan** [comment]
This issue has been fixed in latest master. Hence closing the issue. Changes are reflected on SLP9-snapshot
