### ISSUE TITLE
Ballerina run with observability-included is not working

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#27555]
**Description:**
The following command doesnot work.
`ballerina run <package-path> --observability-included --b7a.observability.enabled=true --b7a.observability.provider=choreo`

**Steps to reproduce:**

**Affected Versions:**
SLP8-snapshot

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadundesilva** [comment]
@hevayo in the current implementation, Observability symbol collector is not called as it does not reach that section in the JBallerinaBackend [1]. Is there a way to get over this issue ?

[1] https://github.com/ballerina-platform/ballerina-lang/blob/11ea90dc0fd2faed6e68fea806dac3adfcccd7a1/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java#L487-L491

**Comment by azinneera** [comment]
As suggested by @hevayo offline, you can revert this implementation and generate a separate jar containing the ST json and return it in `JarResolver.getJarFilePathsRequiredForExecution` [1]. This way it will be added to the classpath when running with sources and also to the executable jar.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JarResolver.java#L58.

**Comment by nadundesilva** [comment]
This should be available with Ballerina Swan Lake Beta 2
