### ISSUE TITLE
Inconsistency in how build and run commands function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27553]
With the new project API changes, the build and run commands work as follows:

Assuming we are at the project root,
- To build a package: `$ ballerina build`
- To run a package: `$ ballerina run .`

As it can be seen, to run, we need to explicitly specify `.`. Wouldn't it be better if both these commands behaved similarly, in terms of how they treat arguments?

**Comment by azinneera** [comment]
Resolved by
