### ISSUE TITLE
[Debugger] Unable to STEP_IN inside object init() method

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#27550]
**Description:**
Unable to `STEP_IN` inside object `init()` method

**Steps to reproduce:**
- Consider the below code snippet:

```public client class Person {
    public int age;
    public string firstName;
    public string lastName;

    function init(int age, string firstName, string lastName) {
        self.age = age;
        self.firstName = firstName;
        self.lastName = lastName;
    }

    function getFullName() returns string {
        return self.firstName + " " + self.lastName;
    }
}

public function main() {
    Person person = new Person(30, "Jack", "Sparrow");
    string personFullName = person.getFullName();
}
```
- Add debug point in object initialization line in `main()` method. 
 -- In front of `Person person = new Person(30, "Jack", "Sparrow");`
- Start the program in debug mode.
- When the debug point get hit in object initialization line, do a `STEP_IN` 

We can observe that the debug navigator is unable to `STEP-IN` inside the object `init()` method

**Affected Versions:**
```
Ballerina Swan Lake Preview 7
Language specification v2020-09-22
Update Tool 0.8.10
```

**Comment by praveennadarajah** [comment]
Unable to STEP_IN inside object init() method is only observed when we create an object for the first time. This behaviour is `not` observed when we create an object for the 2nd or 3rd time.

Consider the below code segment:
```
class Person {
    public  string name;

    function init(string name) {
        self.name = name;
        panic error("Error!!!");
    }

    function getName() returns string {
        return self.name;
    }
}

public function main() {
    Person person1 = new("Praveen");
    Person person2 = new("David");
}
```

When we create an object for the 2nd or 3rd time(In the above example person2 object), the following stack trace is observed from debug- adapter:
![image](https://user-images.githubusercontent.com/11292766/104870838-7c80f480-596f-11eb-8ce4-cf393d39306a.png)

But when we create an object for the first time(In the above example person1 object), the following stack trace is observed from debug- adapter:
![image](https://user-images.githubusercontent.com/11292766/104871162-5e67c400-5970-11eb-8180-d81fe8ea9007.png)

From the above stack trace, it seems like by the time we STEP_IN, the person1 object not created and it is in the class loading phase.

**Comment by NipunaRanasinghe** [comment]
Closing since a similar issue is reported in https://github.com/ballerina-platform/ballerina-lang/issues/30739.
