### ISSUE TITLE
Make transaction handlers isolated

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#27569]
**Description:**
Refer https://github.com/ballerina-platform/ballerina-spec/issues/267#issuecomment-745703543

**Comment by pcnfernando** [comment]
Transaction module tests are updated in https://github.com/ballerina-platform/module-ballerinai-transaction/pull/60
SQL module tests are updated in https://github.com/ballerina-platform/module-ballerina-sql/pull/66
JDBC module tests are updated in https://github.com/ballerina-platform/module-ballerina-java.jdbc/pull/46
MYSQL module tests are updated in https://github.com/ballerina-platform/module-ballerinax-mysql/pull/42
