### ISSUE TITLE
Functions with tuple return types are not generated properly in api docs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#27575]
**Description:**

Refer the following function in [1].

```ballerina
public isolated function extractUsernameAndPassword(string credential) returns [string, string]|Error
```

In API Docs it is displayed as returning `undefined` which is incorrect and not useful for the end user.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/16300038/102585207-fd10c300-412d-11eb-8c9c-9e0f6f307f12.png">

[1] https://github.com/ballerina-platform/module-ballerina-auth/blob/147e7f1b39799c119262091360bce4490af49672/auth-ballerina/utils.bal#L55
[2] https://ballerina.io/swan-lake/learn/api-docs/ballerina/#/auth/functions#extractUsernameAndPassword

**Comment by shehan360** [comment]
This issue is now fixed. Hence closing the issue.
![Uploading Screenshot from 2021-01-08 11-29-30.png…]()
