### ISSUE TITLE
Formatting separates start from strand annotation

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#27601]
**Description:**
This 
```
 future<int> f1 = @strand {thread: "any"} start multiply(1, 2);
```
is formatted as
```    
    future<int> f1 = @strand { thread: "any" }
    start multiply(1, 2);
```
Note the `start` at the next line. I think this need not move to a new line. This is because the annotation is for the `start` call.

**Affected Product Version:**
Slp5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Format the above code using VSCode plugin

**Comment by SupunS** [comment]
@sanjana Can you check whether this issue is still there in the latest preview-version?

**Comment by sanjana** [comment]
@SupunS yes, this issue is still present in the latest preview-version as well as in the current master.
I'll send a fix for this as well.
