### ISSUE TITLE
ballerina: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V

### ISSUE THREAD

**Issue by junetigerlee** [ballerina-platform/ballerina-lang#2760]
Command :

ballerina swagger connector http://petstore.swagger.io/v2/swagger.json -d server/petstore/ -p wso2.carbon.test
 or
ballerina swagger skeleton <swaggerFile> [-d <output directory name>] [-p <package name>] 
Error:
ballerina: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V

**Comment by SupunS** [comment]
Moved this issue to relevant repo: https://github.com/ballerinalang/tool-swagger-ballerina/issues/76

**Comment by lankavitharana** [comment]
Reopening this issue as the tool swagger repository is moved into ballerina repository

**Comment by uthaiyashankar** [comment]
This might not be valid anymore. Please check and resolve.

**Comment by praminda** [comment]
We have rewritten the entire component. Issue is not reproducible anymore. Tested with same swagger definition  http://petstore.swagger.io/v2/swagger.json
