### ISSUE TITLE
Issue with match guards

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#27603]
**Description:**
$title, no errors for always true/unreachable patterns with match guard.

**Steps to reproduce:**
No "unnecessary condition: expression will always evaluate to 'true'" error and "unreachable pattern" errors for the following.

```ballerina
public function main() {
    string a = "foo";
    
    match a {
        "foo" => {
        }

        var p if p is string => { // always true
        }

        var x => { // unreachable
        }
    }
}
```

The "unnecessary condition: expression will always evaluate to 'true'" error is logged on 1.2.x versions.

**Affected Versions:**
slp7, current master

**Comment by KavinduZoysa** [comment]
`always true` warning is there in current implementation.
