### ISSUE TITLE
Project API requires write access to project directory which is not possible in certain environments

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#27612]
**Description:**
Currently, Ballerina Project API requires write access to Ballerina project folder. The `load()` method of `io.ballerina.projects.directory.BuildProject` fails due to not having write permissions. Specifically, a `ProjectException` gets thrown saying `Insufficient privileges to path:` (see the [source location](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/ProjectFiles.java#L183) where the exception gets thrown).

**Steps to reproduce:**
* First, run `ballerina new proj1` and create a new Ballerina project with Ballerina SLP8 release compiler
* Next, `ballerina build proj1` will build this project without any issues
* Run `chmod -R 555 proj1`
* Then again run `ballerina build proj1`
* This will throw the message `ballerina: Insufficient privileges to path: proj1`

**Affected Versions:**
Ballerina Swan Lake Preview 8

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by azinneera** [comment]
The build command creates the target directory and hence it needs to have write privileges. So getting the exception for the build command is the correct behavior.

Nonetheless, in the Project API implementation, we check for write permissions when loading the project. IMO, this should be checked only after the package compilations, the point after which a user would want to write to the file system.
