### ISSUE TITLE
Project API is failed to resolve semvar library dependency in debug server runtime

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#27610]
**Description:**
After removing the uber jar creation from the debug server core build, Project API usages inside the debug server throw  `ClassNotFoundException`s. After some debugging it could be observed that these exceptions are thrown due to the missing library `com.github.zafarkhaja:java-semver` although this dependency is already declared as a compile time + runtime dependency in the project API module.

We have defined this library as a dependency in the debug server core build as a temporary fix (https://github.com/ballerina-platform/ballerina-lang/pull/27608/) and these redundant declarations should be removed once this issue is fixed.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gayaldassanayake** [comment]
ProjectAPI is programatically called by the debug server. The error is thrown in the run time and not in the compile time. The projectAPI dependencies should be passed to the classpath. Hence the current implementation of adding the dependencies is fine.
