### ISSUE TITLE
macOS BigSur "ballerina run" permissions

### ISSUE THREAD

**Issue by kkeker** [ballerina-platform/ballerina-lang#27639]
**Description:**
This issue is seen in macOS 11 for Intel and M1.
Regardless of the installation, through HomeBrew or DMG, when trying to make the "ballerina run", the error of the rights "error: unable to create target directory: ..../BallerinaProjectDir/target" appears. At the same time, there is definitely access to this folder, because it is located in the user's derrictor in ~. After the error is displayed, the folder is still created, but the program does not run:

```
ls target
balo bin caches
```

**Steps to reproduce:**
ballerina run --sourceroot ./ main

**OS, DB, other environment details and versions:**
uname -a
Darwin MBP.lan 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 x86_64

ballerina -v
jBallerina 1.2.12
Language specification 2020R1
Update Tool 0.8.10

**Comment by kkeker** [comment]
If you have additional questions, then I'm in your Slack (ballerina-platform) - @k.keker

**Comment by kkeker** [comment]
I found how to fix this, but still it's weird.

1. You need to execute "sudo ballerina run ..." once.
2. Then you need to change the permissions on the folder "sudo chown -R $USER ~/.ballerina".

For some reason, if you execute "ballerina run ..." from your user, you get the problem I described above.

**Comment by keizer619** [comment]
We have introduce notarizaiton process for installers. This will be done from swan lake beta1 release onwards

**Comment by suganyasuven** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-update-tool/pull/150. Hence closing this issue.
