### ISSUE TITLE
```ballerina ``` sections in markdown contains '#' at the beginning of each line

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#27658]
**Description:**
$subject

**Steps to reproduce:**
1. Have the following code as documentation
```
# Prints `any` or `error` value(s) to the STDOUT.
#```ballerina
# io:print("Start processing the CSV file from ", srcFileName);
#```
# 
# + values - The value(s) to be printed
public isolated function print((any|error)... values){
}
```

2. Get the syntax tree.
3. The above ballerina code section will get parsed as follows.
```
```ballerina
# string s8 = io:sprintf("%s scored %d for %s and has an average of %.2f.", name, marks, subjects[0], average);
# ```
```
Notice the # not removed in new lines.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Re-opening as Docerina is using new Syntax API. Not old AST. Need to think about how to store those Hash Tokens in the ST as we should preserve whole user input.

**Comment by lochana-chathura** [comment]
Solution: Replace `MARKDOWN_CODE_DOCUMENTATION_LINE` with a list where each member has a hash token and a description token.
