### ISSUE TITLE
Changes needed to the ValueCreator

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#27651]
**Description:**
readonly arrays of simple basic types can't be created via the `io.ballerina.runtime.api.creators.ValueCreator`

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/27029

**Comment by riyafa** [comment]
A readonly array can be created in java as follows using the `ValueCreator`:
```
    public static BArray createArray() {
        // Create a readonly array type
        ArrayType arrayType = TypeCreator.createArrayType(PredefinedTypes.TYPE_INT, true);
        Integer[] numbers = {1, 2, 3};
        // Use the readonly arrayType to create a readonly array
        return ValueCreator.createArrayValue(numbers, arrayType);
    }
```
this returns an `int[]` array.

**Comment by MaryamZi** [comment]
> A readonly array can be created in java as follows using the `ValueCreator`:
> 
> ```
>     public static BArray createArray() {
>         // Create a readonly array type
>         ArrayType arrayType = TypeCreator.createArrayType(PredefinedTypes.TYPE_INT, true);
>         Integer[] numbers = {1, 2, 3};
>         // Use the readonly arrayType to create a readonly array
>         return ValueCreator.createArrayValue(numbers, arrayType);
>     }
> ```
> 
> this returns an `int[]` array.

But this calls [the `ArrayValueImpl` constructor](https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-Preview8/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/ArrayValueImpl.java#L77) that sets the array passed to `refValues` right? Whereas a Ballerina `int[]` would be an `ArrayValueImpl` which would internally use `intValues` and not `refValues`?
