### ISSUE TITLE
Component/Composer: I want to add a feature like `graphics editor` for go code

### ISSUE THREAD

**Issue by hitzhangjie** [ballerina-platform/ballerina-lang#27673]
Could you show a road I could carry on?

Parsing the go code is easy for me.

I don't know how to generate the interactive diagrams.

If I learn the code in vscode, that's ok. Is there any easier and quicker way to achieve this ?

**Comment by rdhananjaya** [comment]
@hitzhangjie  shall we use the slack channel [1] if you want to contact the developers.

[1] - https://ballerina-platform.slack.com/archives/C9WMA6QDC

**Comment by rdhananjaya** [comment]
Closing as this is not an issue in Ballerina.
