### ISSUE TITLE
Rename "ballerina" command name to "bal"

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#27680]
The current command name "ballerina" is too long. 

Proposed by @sanjiva

**Comment by keizer619** [comment]
Currently `ballerina` command is set by installers to points ballerina executable. We will update installers to add another alias for that.

**Comment by sameerajayasoma** [comment]
We decided to rename the "ballerina" command name to "bal" during the previous lang design meeting.  This has a significant impact on the documentation, website, help texts, etc.

**Comment by hevayo** [comment]
Given the significance I guess we have to do this for SL alpha.

**Comment by keizer619** [comment]
We need to complete following tasks to achieve this

- [ ] Update Ballerina distribution shell files and internal references
- [ ] Update Ballerina tool shell files and handling new `bal` command and previous `ballerina` command internally
- [ ] Update installers to set environment variables frpm `ballerina` to `bal` command
- [ ] Update all the website references of `ballerina` command

**Comment by keizer619** [comment]
@hevayo @sameerajayasoma  @sanjiva  @Kishanthan @anupama-pathirage @hasithaa

We have done command change in the distributions and now we figure how to provide this change to existing users who has already installed Ballerina and using `ballerina` command

**Approach 1 : Handle everything seamlessly with Ballerina Update Tool** 
- User first need to update the ballerina tool  using`$ ballerina update`
- The new tool version will be downloaded and we will print out the following 
```
The ‘ballerina’ command was changed to ‘bal’. Please use ‘bal’ command for all the ballerina tools. 
Ie : $ bal build
     $ bal dist list
Use list command to see the available distributions
$ bal dist list
Use dist pull to fetch the alpha
$ bal dist pull sla1
```

**Approach 2 : Re-install Ballerina**
- Install ballerina-swan-lake-alpha installer
- All the commands can be executed with the `bal` command
- The active dist will be Swan Lake alpha
- We can allow the previous versions (1.x) to work under `bal` command. But the help text of those commands will have `ballerina` command in examples
    - Alternatively we can only show distributions after sl alpha.

For both above approaches we will not list new releases for previous update tool versions up to 0.8.10. User has to update the tool for approach 1 or User needs reinstall for approach 2

**Possible Swan lake release short codes**

- [sla1] Swan lake - alpha 1
- [sla2] Swan lake - alpha 2
- [slb1] Swan lake - beta 1
- [slrc1] Swan lake - rc1
- [sl] Swan lake (GA Release)
- [slu1] Swan lake - update 1
- [slu1] Swan lake - update 2

**Comment by KRVPerera** [comment]
Still launcher exceptions use `ballerina`

```
ballerina: unknown command ''
Run 'ballerina help' for usage.
```

**Comment by keizer619** [comment]
@KRVPerera This PR should fix it
https://github.com/ballerina-platform/ballerina-lang/pull/28588/files

**Comment by hevayo** [comment]
We will create a separate issue for home-brew
