### ISSUE TITLE
An API to execute Ballerina stream next function in standard libraries 

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#27707]
**Description:**
Ballerina gRPC library has a requirement to execute `next` function in a stream at native level. ATM, a stream comes to the native side as a `StreamValue` object. The `StreamValue` is an internal object, and hence it is not accessible to the stdlib native code. 

Therefore, it would be better to have a direct API to execute the `next` function in a stream. Perhaps as a synchronous API and asynchronous API.

**Related Discussions**
[1] https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1609926111194400
[2] https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1609856798190700

**Affected Versions:**
- SLP9

**Comment by daneshk** [comment]
@manuranga @warunalakshitha Can you prioritize this and add support to read the next value from the stream object, please.

**Comment by warunalakshitha** [comment]
BStream already have a api to get iterator object and then you can call next method using Runtime.invokeMethodAsync method. ATM we do not have a synchronous api. @manuranga Shall we add sync api to so it will be direct call to object method without scheduler.  But we need to make sure object method doe not have any async code.

**Comment by manuranga** [comment]
@BuddhiWathsala @daneshk is this still a high priority ? is Buddhi's current approach working ?

**Comment by BuddhiWathsala** [comment]
Yes, it is working as expected ATM. We can proceed with it.

**Comment by warunalakshitha** [comment]
I am closing this as per the last comment.
