### ISSUE TITLE
No space left on device error because temporary caches are not removed on exit

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#27711]
**Description:**

Temporary compilation caches/projects created when using project API are not removed on exit. As a result, the `/tmp` directory gets filled with cache directories which eventually leads to a `no space left of device` error because inodes run out.

```
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
tmpfs            409600  409594        6  100%   /tmp
```

After deleting all directories starting from ballerina-project* and ballerina-compilation-cache*

```
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
tmpfs            409600     357   409243    1%   /tmp
```

**Steps to reproduce:**

Run `ballerina run FILE` command and in the`/tmp` directory the cache directory is not removed.

```bash
$ ls | grep -n "ballerina"                                                                                                                 (base) 
$ ballerina run main.bal                                                                                                                   (base) 

Compiling source
        main.bal

Running executable

$ ls | grep -n "ballerina"                                                                                                                 (base) 
2:ballerina-compilation-cache742592251140246503854206936630542
3:ballerina-project742592135503796175100363881549321

```

**Affected Versions:**

Swan Lake (slp8)

**OS, DB, other environment details and versions:**

OS: Manjaro Linux (Kernal 5.4.80-2)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
The temporary compilation caches/projects created during `bal run` and `bal test` are cleared from `/tmp` directory now.
Hence, closing.
