### ISSUE TITLE
debuggeePort isn't killed with terminateRequest intermittently 

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#27729]
**Description:**
It seems the **debuggeePort** of the launch request is still up after with terminateRequest. This happens intermittently on Mac env. Since the debuggeePort is not properly terminated, debugger tests run in VSCode doesn't exit (Tests are hanging though all the tests have passed) until the port is closed.

**Steps to reproduce:**
Run VSCode plugin tests and check for the debuggeePorts. (https://github.com/ballerina-platform/plugin-vscode/blob/master/test/debugger/debugger.test.ts)

**Affected Versions:**
SLP8

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
This is related to https://github.com/ballerina-platform/plugin-vscode/issues/94

**Comment by NipunaRanasinghe** [comment]
@prabushi This should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28549. Can you please confirm whether this is resolved in SLP-alpha2, so that we can close the issue?

**Comment by NipunaRanasinghe** [comment]
Closing since this is fixed with #28549.
