### ISSUE TITLE
[Semantic API] Need package name of a symbol

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#27728]
**Description:**
Currently getting the symbol through Semantic API allows us to get the module name, version, orgName. Going forward we will need to get the package name for API Docs.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Had a chat with @shehan360 regarding this. The requirement here is they want to link to the relevant page in docs when a construct from another package is referred in the current package. For example,
```ballerina
public type Foo record {
    http:Client ep;
};
```
When generating docs for the above, they want to be able to know in which package `http:Client` is in.

**Comment by shehan360** [comment]
Currently we are using the module name to get the package name by splitting using `.`

Example - 
Take a package named `test_prj`. Lets assume it has two modules named `mod1` and `mod2`.
mod1 will be names as `test_prj.mod1` and mod2 will be `test_prj.mod1`. By splitting using the `.` we can get the package name as `test_prj`. 

However, this is no longer possible with new changes as there can be `.` in package names and module names. (jballerina.java)

**Comment by pubudu91** [comment]
This will have to be passed down to the AST from the Package API. And then maybe we can persist the package name in the module symbol 🤔 @azinneera This should be possible right?

**Comment by azinneera** [comment]
We can add the `ModuleContext` to the `BLangPackage` IMO. The `ModuleContext` has a reference to the bLangPackage and also adding the other way around would facilitate switching between the Project API and other compiler APIs seamlessly. This will also address #29251.

Similarly, we can refer to `DocumentContext` in `BLangCompilationUnit`
@pubudu538 @hasithaa WDYT?

**Comment by pubudu91** [comment]
+1 from me. Will it be possible to make some of the methods like `descriptor()` in `ModuleContext` public (to get the package name)?

**Comment by sanjana** [comment]
Ran into a concern regarding, what can be used as the default module name. 

https://ballerina-platform.slack.com/archives/CAXS256RX/p1621323131008400
