### ISSUE TITLE
Clean up `TestSuite` class to remove duplicated information

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#27737]
**Description:**
Currently, the class '[Testsuite](https://github.com/ballerina-platform/ballerina-lang/blob/604e9ca5573a3890ffdeec2b6baea3313e70d716/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TestSuite.java#L29)' contains fields that hold the similar information that are used in multiple occasions. 
Eg : package ID , org name, package name, version etc.

It would be efficient to have a common (object or other) field that holds this information instead of these string fields. 

**Steps to reproduce:**
N/A

**Affected Versions:**
slp8

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@hinduja

Currently we are converting the class 'Testsuite' to json and vice versa. So, we are unable to use an object such as "ModuleDescriptor" instead of keeping the string fields package ID , org name, package name, version.
