### ISSUE TITLE
[Debugger] $stream$anon$constaint$ is shown as the type

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#27749]
**Description:**
Here title/type is $stream$anon$constaint$ is shown as the type as following screenshot

<img width="525" alt="Screenshot 2021-01-07 at 15 48 26" src="https://user-images.githubusercontent.com/2918812/104026613-321fab00-51ec-11eb-921f-d70830c1c642.png">

Sample Code
https://gist.github.com/keizer619/19e84eb3462f65ba6bd79a53ee865012#file-main-bal-L48

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/30611
