### ISSUE TITLE
[Debugger] Cannot evaluate object method and self inside method

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#27747]
**Description:**
 Cannot evaluate object method and self inside method in VSCode. This happens in methods and init method
<img width="677" alt="Screenshot 2021-01-08 at 11 57 58" src="https://user-images.githubusercontent.com/2918812/104025846-39928480-51eb-11eb-8ca0-17ed1502f8c2.png">

<img width="501" alt="Screenshot 2021-01-08 at 11 49 21" src="https://user-images.githubusercontent.com/2918812/104025840-37c8c100-51eb-11eb-8eaf-61566e184ee0.png">

<img width="523" alt="Screenshot 2021-01-08 at 11 49 00" src="https://user-images.githubusercontent.com/2918812/104025819-33040d00-51eb-11eb-9fec-e9cd323b3776.png">

Sample code to reproduce

https://gist.github.com/keizer619/19e84eb3462f65ba6bd79a53ee865012#file-main-bal-L81

**Comment by NipunaRanasinghe** [comment]
This is happening due to https://github.com/ballerina-platform/ballerina-lang/issues/27747 where we can not retrieved the value of `self` instance, as it does not get added into the variable table during the codegen.
