### ISSUE TITLE
Unable to evaluate a function of an class/object in the debugger

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#27740]
**Description:**
$subject. I have created an object instance out of a class and while debugging it I have invoked a function of the object. The evaluator shows the function is undefined.

<img width="453" alt="Screenshot 2021-01-08 at 14 45 08" src="https://user-images.githubusercontent.com/4398820/104006996-443e2100-51cd-11eb-9325-24e057ab8512.png">

**Steps to reproduce:**
[github-main.txt](https://github.com/ballerina-platform/ballerina-lang/files/5786730/github-main.txt)

**Affected Versions:**
SLP8

**OS, DB, other environment details and versions:**
MAC

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/30331
