### ISSUE TITLE
[VSCode] There is an intermittent slowness when showing errors

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#27752]
**Description:**
This happened sometimes where there is a slowness in VSCode plugging. Even when we did the fixes error keeps showing when hovering over it shows previous error message and loading as following screenshot.

<img width="706" alt="Screenshot 2021-01-08 at 11 35 38" src="https://user-images.githubusercontent.com/2918812/104027456-6d6ea980-51ed-11eb-9b73-6af292bd76af.png">

This one took around 30 to 40 seconds and got updated. At that point i have already remove `+` operator.

**Comment by nadeeshaan** [comment]
@keizer619 what's the version used?

**Comment by keizer619** [comment]
it was slp8

**Comment by nadeeshaan** [comment]
SLP8 had an issue regarding a sudden CPU spike and we fixed it with https://github.com/ballerina-platform/ballerina-lang/pull/27644. This fix has been merged to latest master. Hence shall we close the issue and reopen if we can observe the same in slp9 as well?

**Comment by nadeeshaan** [comment]
Closing the issue based on https://github.com/ballerina-platform/ballerina-lang/issues/27752#issuecomment-762624442
