### ISSUE TITLE
Redeclared symbol error

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#27759]
**Description:**
UUID standard library module[[1]](https://github.com/ballerina-platform/module-ballerina-uuid) build is failing with the following error. But this `Uuid` record[[2]](https://github.com/ballerina-platform/module-ballerina-uuid/blob/main/uuid-ballerina/constants.bal#L30) is declared only once.

```
Compiling source
	ballerina/uuid:0.9.1
ERROR [constants.bal:(30:13,30:17)] redeclared symbol 'Uuid'
```

**Steps to reproduce:**
1.  Take a clone of the UUID module repository[[1]](https://github.com/ballerina-platform/module-ballerina-uuid).
2. Build the UUID module by running `./gradlew clean build`

[1] https://github.com/ballerina-platform/module-ballerina-uuid
[2] https://github.com/ballerina-platform/module-ballerina-uuid/blob/main/uuid-ballerina/constants.bal#L30

**Comment by MaryamZi** [comment]
Seems to happen due to the changes introduced in https://github.com/ballerina-platform/ballerina-lang/pull/26770.

Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/27758
