### ISSUE TITLE
Remove Ballerina core dependency to carbon transport

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-lang#2777]
There are transport dependencies from Ballerina core to JMS and HTTP Netty packages. Ideally, there shouldn't be any dependencies to carbon transport. 

[1] https://github.com/ballerinalang/ballerina/blob/71bbe9d8ac31387a77cb14e21c13390a49eb49e3/modules/ballerina-core/pom.xml#L46

**Comment by SupunS** [comment]
Ballerina core and lang modules no longer have any transport related dependencies
