### ISSUE TITLE
Platform distribution repository should only contain packages in "ballerina" organization 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#27795]
During a recent discussion, we talked about having only the packages in `ballerina` organization in the distribution repository.

**Comment by keizer619** [comment]
We have removed ballerinax extensions from the pack and those will be released separately,

We did not removed Azure Functions and AWS Lambda extensions as they are not pushed to central yet.  For those tasks there are separate issues to track [1][2]. Hence i am closing this issue.

[1] https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/208
[2] https://github.com/ballerina-platform/module-ballerinax-aws.lambda/issues/366
