### ISSUE TITLE
Docerina documentation is not automatically generated for remote functions.

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-lang#27800]
**Description:**
When I add documentation comments in to the remote functions in client class file, the expected documentation does not generate automatically by ballerina. 

**Steps to reproduce:**
``` ballerina
import ballerina/io;
# Client class
# 
public client class Client {
    # Hello World function 
    # 
    # + return - A string.      
    remote function helloWorld() returns string {
        return "Hello World!";
    }
}
public function main() {
    Client clientInstance = new();
    var result = clientInstance -> helloWorld();
    io:println(result);
}
```
**Affected Versions:**
Ballerina Swan Lake Preview 8

**OS, DB, other environment details and versions:**
Ubuntu 20.04.1 LTS
openjdk 11.0.9.1 2020-11-04

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment]
Hi this issue has been identified and resolved. It should work with the next release. 
REF: https://github.com/ballerina-platform/ballerina-lang/issues/27693
