### ISSUE TITLE
Symbols are dropped from the visibleSymbols API

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#27816]
**Description:**
Consider the following source snippet,

```
type TestRec record {|
    
|};

annotation TestRec test1 on function;

# Description
#
# + test - test Parameter Description 
# + boo - boo Parameter Description 
# + return - Return Value Description
public function test1(int test, int boo) returns int {
    <cursor>
    return 12;
}
```

**Steps to reproduce:**
When we get the visible symbols at the given cursor position, only the `test1` annotation is captured and the function `test1` has been dropped.

**Affected Versions:**
SLP8. at least

**Comment by dulajdilshan** [comment]
Related Discussion: https://github.com/ballerina-platform/ballerina-lang/discussions/27968

Symbols are dropped from the `visibleSymbols` API, because we have modelled the entries of the scope to have only single entry per key.

**Comment by pubudu91** [comment]
+1 for moving this to post-alpha considering that this change needs to be done to the core design of the symbol related logic

**Comment by dulajdilshan** [comment]
Merging is paused due to checks failure. Issue to track this https://github.com/ballerina-platform/ballerina-lang/issues/28629
