### ISSUE TITLE
Allow public qualifier for module-level variables

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#27855]
With https://github.com/ballerina-platform/ballerina-spec/issues/324 `public` qualifier is now allowed on module-level vars. Need to update the compiler to reflect this.

**Comment by hasithaa** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/27982

**Comment by hasithaa** [comment]
@rdulmina can you add https://github.com/ballerina-platform/ballerina-lang/issues/27855 as well.

**Comment by rdulmina** [comment]
> @rdulmina can you add [ballerina-platform/ballerina-spec#741](https://github.com/ballerina-platform/ballerina-spec/issues/741) as well.

Sure
