### ISSUE TITLE
OutOfMemoryError: Java heap space Issue in test suite

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#27856]
**Description:**
One of the reasons for the $subject is the number of `CompileResult` object kept alive during a particular time.

- [ ] Switching to local variables for their `CompileResult` for negative test cases.
- [ ] Tear down `CompileResult` in unit test
- [ ] Tear down `CompileResult` in long run test suite

<img width="948" alt="Screenshot 2021-01-14 at 12 46 44 AM" src="https://user-images.githubusercontent.com/2173530/104504343-51fa0900-5608-11eb-98b7-302c46801f09.png">

## Heap usage

<img width="1312" alt="Screenshot 2021-01-13 at 11 49 33 PM" src="https://user-images.githubusercontent.com/2173530/104547859-89db6d80-5655-11eb-9ec1-edbc89ee0641.png">

**Steps to reproduce:**
>gw :jballerina-unit-test:test --fail-fast -x createJavadoc --max-workers=1 --no-daemon

**Affected Versions:**
master branch

**OS, DB, other environment details and versions:**
all

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
It looks like this is an issue with how TestNG works. See https://github.com/cbeust/testng/issues/1461. Apparently the test class instances are kept around, even after the test completes.

**Comment by KRVPerera** [comment]
I think we should also optimize our heap usages. As an example does every BInvokableSymbol symbol needs 10 spaces for params? Or we can lazily initialize space only when needed.

```Java
public BInvokableSymbol(int tag,
                            long flags,
                            Name name,
                            PackageID pkgID,
                            BType type,
                            BSymbol owner,
                            Location pos,
                            SymbolOrigin origin) {
        super(flags, name, pkgID, type, owner, pos, origin);
        this.tag = tag;
        this.params = new ArrayList<>();					// may be initially 3 is fine.
        this.annAttachments = new ArrayList<>();			// may be initially 1 is fine
        this.dependentGlobalVars = new HashSet<>();			// may be initially 0/1 is fine or need to lazily initialize.
        this.paramDefaultValTypes = new HashMap<>();		// may be initially 3 is fine or need to lazily initialize.
    }
```

**Comment by rdhananjaya** [comment]
Can we do this https://github.com/ballerina-platform/ballerina-lang/pull/27857#issuecomment-768068246

**Comment by KRVPerera** [comment]
Yes. We can set all field to null.

```java
public class BaseTest {

    @AfterClass(alwaysRun = true)
    public void destroy() {
        for (Field field : getClass().getDeclaredFields()) {
            if (field.get(this) != null) {
                field.set(this, null);
            }
        }
    }
}
```

**Comment by KRVPerera** [comment]
I faced many issues implementing automatic cleaning. One example is programmers cannot create a private `CompileResult` object because they cannot be set to `null`. 
One plan was to specifically search for `CompileResult` type class and warn if they are private fields. So the programmer can remove private qualifier to let them clean automatically.

**Closing the issue and will reopen this as a discussion.**
