### ISSUE TITLE
Generate differentiated syntax and semantic diagnostics from the compiler API

### ISSUE THREAD

**Issue by SumayyaZiyad** [ballerina-platform/ballerina-lang#27858]
**Description:**
Implement $subject as a solution to retrieve diagnostics that can be classified as syntactic and semantic.

**Comment by pubudu91** [comment]
Can you elaborate the requirement a bit? Is it to be able to filter out the diagnostics by their category (i.e., syntax errors, semantic errors etc.)?

**Comment by SumayyaZiyad** [comment]
> Can you elaborate the requirement a bit? Is it to be able to filter out the diagnostics by their category (i.e., syntax errors, semantic errors etc.)?

Yes. This was a post-discussion improvement suggestion made since currently we have no way to categorize them as mentioned.
