### ISSUE TITLE
Align lang libs in the compiler with the ones in the spec.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#27899]
**Description:**
We need to go through and update langlibs with the spec.

Things to consider:
- Addition or removal of functions.
- Signature or data type changes.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
Related to 
https://github.com/ballerina-platform/ballerina-lang/issues/25446

**Comment by KRVPerera** [comment]
Related to Update param and return types for clone, cloneReadOnly 
https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+CloneReadOnly

**Comment by KRVPerera** [comment]
Need to fix this issue along with this issue:
https://github.com/ballerina-platform/ballerina-lang/issues/24336

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/28714 and https://github.com/ballerina-platform/ballerina-lang/pull/29636.
