### ISSUE TITLE
[Syntax API] fieldName includes comment when the field is preceded by a comment in SpecificFieldNode

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#27904]
**Description:**

When retrieving field name from SpecificFieldNode in the syntax API , it includes comment when the field is preceded by a comment.

**Steps to reproduce:**

Consider the following test case with a preceding comment in test configuration.

```
@test:Config {
    // The `jsonDataProvider` function provides the dataset to this function.
    dataProvider: jsonDataProvider
}
function testJsonObjects(json fValue, json sValue, json result) {
    json a = { "a": "a" };
    json b = { "b": "b" };
    json c = { "c": "c" };
    test:assertEquals(fValue, a, msg = "json data provider failed");
    test:assertEquals(sValue, b, msg = "json data provider failed");
    test:assertEquals(result, c, msg = "json data provider failed");
}
```

This returns the value including the preceding comment when the fieldName is retrieved from SpecificFieldNode.

value for field name at https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java#L417 is as follows.

```
// The `jsonDataProvider` function provides the dataset to this function.
    dataProvider
```

I think this needs to be fixed from Syntax API itself, rather than each user handling it.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
This is not a syntax API bug. Closing the issue as we fixed Testerina `SpecificFieldNode`  field name to use `text()` instead of `toString()` with PR #34590.
