### ISSUE TITLE
`value:Cloneable` can be assigned to `any`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#27944]
**Description:**
$title. Shouldn't be allowed since `value:Cloneable` contains `error`.

**Steps to reproduce:**
```ballerina
import ballerina/lang.value;

public function main() {
    value:Cloneable x = error("x");
    any y = x; // Should fail since `value:Cloneable` includes `error` and `x` can hold an error.
}
```

**Affected Versions:**
slp9-SNAPSHOT

**Comment by KRVPerera** [comment]
This may break some existing codes. Below is allowed before. 
eg:
```Ballerina
public function main() {
    readonly x = "sd";
    any y = x; 				// incompatible types: expected 'any', found 'readonly'
}
```

This also requires updating several `AssertEqual` helper methods argument in test suite from `any|error` to `any|readonly|error`.
ToString method should also be changed to accept `any|readonly`
