### ISSUE TITLE
Completion Response takes longer time when suggestions are requested for the last line of the document

### ISSUE THREAD

**Issue by sajeerAhamed15** [ballerina-platform/ballerina-lang#27992]
**Description:**
Completion request takes a considerable amount of time when the completions are requested from the last line of the document. This is mostly noticed in API trigger

**Steps to reproduce:**
Use the below code
```
import ballerina/http;

service on new http:Listener(8090) {
    resource function get hello(http:Caller caller, http:Request req) {
        string temp = "hello";
        int temp2 = 23;

        var temp3 =  ;
    }
}
```
Request completion from the location in between `=` and `;` of `temp3` (Leave one space after `=` sign and trigger completion)

> Here is a screenshot from [choreo-console](https://console.choreo.dev/)
![image](https://user-images.githubusercontent.com/26720235/105130207-960b7300-5b0c-11eb-9a65-f771b8f50210.png)

Related issue: [#2149](https://github.com/wso2-enterprise/choreo/issues/2149)

**Comment by nadeeshaan** [comment]
@sajeerAhamed15 tested in the VSCode plugin, and could not observe a similar issue

**Comment by sajeerAhamed15** [comment]
> @sajeerAhamed15 tested in the VSCode plugin, and could not observe a similar issue

@kaviththiranga @NipunaMarcus, Can you think of any reason for this issue appearing only in Choreo console

**Comment by NipunaMarcus** [comment]
Not sure why.. coz we are not changing anything when we request for completions. We are getting completion for code editor using normal LS client .. so ... there shouldn't be any changes ... only difference is the usage of LS ... VSCode has a single LS per instance... We use a Monolithic ...

**Comment by NipunaMarcus** [comment]
As i remember line before last statement get completions faster.

**Comment by NipunaMarcus** [comment]
BTW this is SLP8

**Comment by sajeerAhamed15** [comment]
> As i remember line before last statement get completions faster.

+1

**Comment by nadeeshaan** [comment]
@sajeerAhamed15 do you get the slowness for text editor as well?

**Comment by kaviththiranga** [comment]
@nadeeshaan yeah, same for code editor.

**Comment by nadeeshaan** [comment]
There were improvements for the compilation time for alpha2 lately and can we check on alpha2 as well?

**Comment by IMS94** [comment]
@sajeerAhamed15 Can you check if this issue is still there?

**Comment by sajeerAhamed15** [comment]
This is fixed. Sorry, I forgot to close this issue.
