### ISSUE TITLE
Support reading configurable variables from isolated functions

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#27994]
```
import ballerina/io;

configurable boolean b = ?;

isolated function a() {
    io:println(b);
}

public function main() {
    io:println(b);
}
```

```
Compiling source
	config.bal
ERROR [config.bal:(6:16,6:17)] invalid access of mutable storage in an 'isolated' function
```

**Comment by MaryamZi** [comment]
This error is correct. Variables outside an `isolated` function can be accessed within the function only if 

1) the variable is a `final` variable and the type is a subtype of `readonly`. 

In this case, marking `b` as `final` will fix this.

```ballerina
import ballerina/io;

final configurable boolean b = ?;

isolated function a() {
    io:println(b);
}

public function main() {
    io:println(b);
}
```

2) the variable is an `isolated` variable and the access is done within a lock statement

```ballerina
import ballerina/io;

isolated configurable boolean b = ?;

isolated function a() {
    lock {
        io:println(b);
    }
}

public function main() {
    lock {
        io:println(b);
    }
}
```

However, using `isolated configurable` variables with `?` isn't supported yet and is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/27092.

**Comment by rdulmina** [comment]
Closing the issue as per the above comment.
