### ISSUE TITLE
Add a test case to verify the taint errors being emitted based on toml configuration.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#28015]
**Description:**
$title.

At the moment we have tests to verify that compiler option is set, based on the `toml` config.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
We are removing the current taint analysis implementation with #30981, Hence closing this issue.
