### ISSUE TITLE
Validate Config.toml based on the default value availability

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#28018]
**Description:**
Currently the runtime is not aware if the default value is provide in the source code for a given configurable variable. this limits the amount of validation we can perform on the toml file.

Persist that information in the BIR (frontend change may needed) and then validate the toml agains the it at program start.

**Comment by HindujaB** [comment]
This issue restricts configurables from giving detailed error messages for some error cases.  Now it gives the error `Value not provided for required configurable variable` for those errors. 
The fix of this issue will cover the following error scenarios.
- No config file provided
- Empty config file
- No module name provided in toml table - 
    Eg:
    ```toml
    [pkgName] #if this is not provided
    variable = "value"
    ```
- Wrong module name/org name provided
