### ISSUE TITLE
 Language server code action test MarkUntaintedTest  is disabled.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#28016]
**Description:**
$title in https://github.com/ballerina-platform/ballerina-lang/pull/28014
This is because taint analysis is now a build option that user needs to supply which defaults to false.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This code action has been disabled

**Comment by hasithaa** [comment]
We are removing the current taint analysis implementation with #30981, Hence closing this issue.
