### ISSUE TITLE
[Testerina] Improve mock config to accept function pointers

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#28013]
**Description:**

Improve mock config to accept function pointers.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
We need to wait for the any function implementation (https://github.com/ballerina-platform/ballerina-lang/issues/27742) to proceed with this task.

**Comment by Dilhasha** [comment]
This is addressed as part of https://github.com/ballerina-platform/ballerina-lang/issues/29331

**Comment by Ibaqu** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/29833

**Comment by Dilhasha** [comment]
Tracked in https://github.com/ballerina-platform/ballerina-lang/issues/32138
