### ISSUE TITLE
Enum Symbols should have a method to know the original enum name

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#28039]
**Description:**
If an enum is defined with expression values, enum elements' type signature would be the expression. However, this should instead be the original enum name. Or, there should be a way to know the original enum name.

**Steps to reproduce:**
```ballerina
enum Language {EN="english", TA="tamil", SI="sinhala"}
// Type signature of variable would be `english` but should instead be `EN`.
// Or there should be a way to get the `EN` symbol name.
EN variable = "english" 
```

**Related Issues (optional):**
#28037

**Comment by pubudu91** [comment]
I believe this is the same as #27190

**Comment by pubudu91** [comment]
Closing since this is a duplicate
