### ISSUE TITLE
Triple backtics to recognize ballerina code sections not parsing correctly at some instances

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#28046]
**Description:**

**Steps to reproduce:**
1. Have the following code
```
# Write an array of lines to a file.
# During the writing operation, a newline character `\n` will be added after each line.
# ```ballerina
# string[] content = ["Hello Universe..!!", "How are you?"];
# io:Error result = io:fileWriteLines("./resources/myfile.txt", content);
# ```
# + path - The path of the file
# + content - An array of string lines to write
# + return - The null `()` value when the writing was successful or an `io:Error`
public function fileWriteLines(@untainted string path, string[] content) returns int? {
 return 0;
}
```
2. Ballerina code section wont be correctly recognized. It will be parsed as follows.
```
Write an array of lines to a file. During the writing operation, a newline character \n will be added after each line. MISSING[`]```ballerina

string[] content = ["Hello Universe..!!", "How are you?"];
io:Error result = io:fileWriteLines("./resources/myfile.txt", content);
```
```

**Comment by lochana-chathura** [comment]
We need to update the `\n` to `\\n` in the place we have this.

**Comment by shehan360** [comment]
When we add an extra `\`, the documentation gets parsed as follows.
```
Write an array of lines to a file.
During the writing operation, a newline character `\\n` will be added after each line.
```ballerina
# string[] content = ["Hello Universe..!!", "How are you?"];
# io:Error result = io:fileWriteLines("./resources/myfile.txt", content);
# ```
```
Shouldn't we remove the extra `\` in the final output to show what the writer intended?

**Comment by lochana-chathura** [comment]
Had a look. We can use \n in the normal documentation.
eg. `# During the writing operation, a newline character \n will be added after each line.` parsing as expected.
 
Problem is inside the single backticks we capture identifier tokens and "\n`" gets identified as an identifier there.

Checked compiling following code and apparently we can define an identifier like that. 
```bal
var \n` = 10;
```

But, according to the specs \n` is not supposed be parsed as an identifier right? @rdulmina
