### ISSUE TITLE
Temporary disable toml based code-actions language deldegator

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#28056]
**Description:**
Need to disable toml based code-actions language decelerator since the project-api does not support toml file updates yet.

**Affected Versions:**
2.0.0-sLP9-SNAPSHOT

**Comment by prabushi** [comment]
Removed the VSCode extension support with https://github.com/ballerina-platform/plugin-vscode/pull/151/commits/1e933cca48b0991e58036b5b378214143781141f

**Comment by rasika** [comment]
@prabushi please revert the above https://github.com/ballerina-platform/plugin-vscode/pull/151/commits/1e933cca48b0991e58036b5b378214143781141f. We are shipping this with alpha to support C2C case
