### ISSUE TITLE
'int' variables are initialized to 0 by default in debug variables 

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28064]
**Description:**
int varibales are initialized to 0 in the debug variables view before the varible is actualled assigned with any value, which is misleading to the user.
<img width="1631" alt="Screenshot 2021-01-21 at 16 28 41" src="https://user-images.githubusercontent.com/5234623/105343984-57f37980-5c08-11eb-9fcf-14c3b7744b13.png">

<img width="1399" alt="Screenshot 2021-01-21 at 16 31 32" src="https://user-images.githubusercontent.com/5234623/105344001-5f1a8780-5c08-11eb-98ac-a24ff606abb7.png">

**Steps to reproduce:**

**Affected Versions:**
SLP9

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
Boolean is assigned with false. May be we can avoid showing the variable until it's actually assigned.
<img width="1630" alt="Screenshot 2021-01-21 at 23 08 43" src="https://user-images.githubusercontent.com/5234623/105389393-cbfc4480-5c3d-11eb-9443-58f5984b69b4.png">

**Comment by praveennadarajah** [comment]
The ideal fix should be variable and its value should not be visible at the breakpoint. It should be visible when the user `STEP_OVER` to the next line.
