### ISSUE TITLE
using Rosetta emulator for launching  app crashes openjdk1.8.0_275-b01 jvm  on Mac ARM 

### ISSUE THREAD

**Issue by shankha88** [ballerina-platform/ballerina-lang#28070]
**Description:**
Launching standard Notes application crashes open-jdk1.8.0_275-b01 jvm

**Steps to reproduce:**  Installed Rosetta emulator in Mac ARM Big sur os.
Launch standard Notes application and it crashes

Attaching the java core dump with it
[javacore.20201214.102200.1006.0002.txt](https://github.com/ballerina-platform/ballerina-lang/files/5849530/javacore.20201214.102200.1006.0002.txt)

**Comment by rdhananjaya** [comment]
@shankha88  please provide a link or reference to "standard Notes application".

**Comment by rasika** [comment]
@rdhananjaya I think he is referring the "Notes" text-editor application that's being shipped with Mac OS. @shankha88 Since this is not related to BallerinaLang closing the issue. Feel free to re-open the issue if you need further help on this.
