### ISSUE TITLE
'Step Into' in project's test works as 'Step Over'

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28071]
**Description:**
'Step Into' on the `test:assertEquals` behaves as 'Step Over' only within the ballerina project's test files. However, this works fine in a single file project.

**Steps to reproduce:**

1. Source (projectname/tests/main_test.bal)
 ```
import ballerina/test;

// The `assertEquals()` function allows you to compare primitive types (e.g., int) against composite objects.
// Compares values of the type `int`.
@test:Config {}
function testAssertIntEquals() {
    int answer = 0;
    int a = 5;
    int b = 3;
    answer = intAdd(a, b);
    test:assertEquals(answer, 8, msg = "int values not equal");
    int c = 6;
}

function intAdd(int a, int b) returns (int) {
    return (a + b);
}

```
2. Run `Ballerina Test`
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing since this behaviour is fixed with #28708
