### ISSUE TITLE
Global variable values aren't shown in debug view

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28075]
**Description:**
Global variables are shown as `()` in the debug `Variables` view. Even the evaluation of a global variable result in `()`.
<img width="952" alt="Screenshot 2021-01-21 at 23 30 08" src="https://user-images.githubusercontent.com/5234623/105392182-edaafb00-5c40-11eb-9528-07c79a33f05e.png">

**Steps to reproduce:**

**Affected Versions:**
SLP9

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Probably this is happening due to #https://github.com/ballerina-platform/ballerina-lang/issues/26139.

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/30619
