### ISSUE TITLE
Multiple threads on the call stack

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28089]
**Description:**
There are multiple threads on the call stack each with play, pause, etc. buttons. And, the debug flow continues on the play action of each thread, which is a bit confusing. 

<img width="729" alt="Screenshot 2021-01-22 at 09 44 36" src="https://user-images.githubusercontent.com/5234623/105447971-5aeb7a00-5c9b-11eb-8ed3-efc61de7a16b.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
Similar issue https://github.com/ballerina-platform/ballerina-lang/issues/27913
