### ISSUE TITLE
Not seeing varible suggestions for global variables

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#28094]
**Description:**
I have global variables as follows and expected to get suggestions when trying to use them in constructor 
![suggestions](https://user-images.githubusercontent.com/8238078/105431302-5adb8200-5c7b-11eb-861a-b81a1f2e6750.gif)
But didn't see any suggestions

**Comment by nadeeshaan** [comment]
This issue has been fixed with #28670. Hence closing the issue. Please reopen if the issue still exist.
