### ISSUE TITLE
[Ballerina Shell] Update shell version to 0.6.0

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#28114]
**Description:**
The current Ballerina shell version is 0.0.1. This should be updated to 0.6.0
The approach should be to either change the module version using Gradle versioning.
However, since all module versions are set as the project version, it might be required to put the ballerina shell in a separate repo instead of having it in the ballerina lang repo.

**Comment by mohanvive** [comment]
Reopening the issue because this was mistakenly closed.
