### ISSUE TITLE
Need to deprecate PositionDetails.matchedExprType

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#28124]
**Description:**
Need to deprecate PositionDetails.matchedExprType since it the semantic-api is restrictive for the expressions.
Alternative way is to get it through the diagnostic properties.

Related issue https://github.com/ballerina-platform/ballerina-lang/issues/28123

**Steps to reproduce:**

**Affected Versions:**
2.0.0-SLP9-SNAPSHOT

**Comment by nadeeshaan** [comment]
Closing since this is no longer valid
