### ISSUE TITLE
Address the review suggestions regarding the CLI output of bal command

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#28138]
**Description:**
The following review suggestions were made regarding the CLI output of the `bal help` command at [Update ballerina command to bal in Using the CLI Tools of Learn pages PR of ballerina-dev-website repo](https://github.com/ballerina-platform/ballerina-dev-website/pull/1705)

1. Change `The bal build tool` to `The Ballerina build tool`
  - https://github.com/ballerina-platform/ballerina-dev-website/pull/1705#discussion_r562513298

2. Change the description of `init`
  - https://github.com/ballerina-platform/ballerina-dev-website/pull/1705#discussion_r562514053

3. Use the word **Add** instead of **Create** in the description
  - https://github.com/ballerina-platform/ballerina-dev-website/pull/1705#discussion_r562514484

4. Use **statically-typed** instead of **statically typed** within the description
  - https://github.com/ballerina-platform/ballerina-dev-website/pull/1705#discussion_r562670709

**Steps to reproduce:**

**Affected Versions:**
2.0.0-sLP9-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Type/Improvement

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
1. Already fixed.
