### ISSUE TITLE
Error when formatting match binding pattern

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28154]
Tested with a pre-Alpha pack. It removes `,` character and makes the source code invalid. 

```ballerina
import ballerina/io;

function test1(any v) {
    match v {
        [var a , ...var b] => { // Bug
            io:println("match");
            return;
        }
    }
    io:println("no match");
    return;
}

function test2(any v) {
    match v {
        var [a, ...b] => { // Works
            io:println("match");
            return;
        }
    }
    io:println("no match");
    return;
}
```

![stats-1611544566963](https://user-images.githubusercontent.com/1356214/105657426-5963c100-5eea-11eb-8c5e-369eb85a9c9e.gif)

**Comment by IrushiL** [comment]
Related Issue: https://github.com/ballerina-platform/ballerina-lang/issues/26421

**Comment by IrushiL** [comment]
Closing this issue since it is fixed with the relevant Parser PR.
