### ISSUE TITLE
Transaction is not pre-declared  lang-lib import.

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#28157]
**Description:**
```
predeclared-prefix :=
   boolean
   | decimal
   | error
   | float
   | future
   | int
   | map
   | object
   | stream
   | string
   | table
   | transaction
   | typedesc
   | xml
```
`transaction` can not be used as predeclared langlib import

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Parser fails when trying to use transaction lang lib without quoted module prefix. It seems we have to improve handling transaction module separately since transaction is not type compared to other pre-declared modules. @rdulmina 

```ballerina
 public function main() {
    transaction:Info info;
}
```

**Comment by lochana-chathura** [comment]
> Parser fails when trying to use transaction lang lib without quoted module prefix. It seems we have to improve handling transaction module separately since transaction is not type compared to other pre-declared modules. @rdulmina
> 
> ```ballerina
>  public function main() {
>     transaction:Info info;
> }
> ```

@pcnfernando PR merged for this fix.
