### ISSUE TITLE
ballerina-internal.log file created for failing tests

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#28151]
**Description:**
A ballerina-internal.log file is created with the following log when a test run using testerina fails:
```
[2021-01-25 07:12:03,074] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:78)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:70)
	at org.ballerinalang.test.runtime.Main.main(Main.java:54)
 
```
This is not necessary because ballerina-internal.log  is for logging crashes during compilation and this is not a crash, but is something that happens and the test output actually shows this failure

**Steps to reproduce:**
Create a failing ballerina test case in package and run it using `bal test`

**Affected Versions:**
Swan lake alpha

**OS, DB, other environment details and versions:**
Ubuntu 20.04

**Comment by Dilhasha** [comment]
This will be properly handled with https://github.com/ballerina-platform/ballerina-lang/issues/29632. Hence closing.
