### ISSUE TITLE
Previously shown errors disappear when I move along tabs

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28168]
**Description:**
Assume I have two bal files open. Let them be `A` and `B`. `B` file had few errors showing. I move to `A` file and do a change and move back to the `B` file; all errors disappear until I do a change in file `B`.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
This implementation is by design to flush the diagnostics for the relevant project. This issue does not happen if you switch between the source files in the same project. If you switch between two projects, this is the by design behaviour. We might need to rethink this approach.

**Comment by prabushi** [comment]
Diagnostics are removed if we switch to the stdlibs via the go-to definition option. 
Reported in https://github.com/wso2/ballerina-plugin-vscode/issues/84
