### ISSUE TITLE
[Debugger] Step-in instruction is not working on async calls

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#28166]
**Description:**
Step-in instruction does not work properly when trying to stepping into aync calls (start expressions). 

**Steps to reproduce:**

```ballerina 
import ballerina/http;

public function main() {
    // Call the 'calculate' function asynchronously.
    future<int> f1 = start calculate("365*24");
}

function calculate(string expr) returns int {
    http:Client httpClient = checkpanic new ("https://api.mathjs.org");
    string response = <string> checkpanic
        httpClient->get(string `/v4/?expr=${expr}`, targetType = string);
    return checkpanic int:fromString(<@untainted>response);
}
```

**Affected Versions:**
Swan Lake - Alpha

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
@NipunaRanasinghe 
In the above example, a new strand will be created for the `start` action, and that strand will be attached to the same thread as the current strand. This newly created strand will start to execute once the current strand is finished its execution or when it turns to yield state. 

When we do a `STEP_IN` in `start` action, the newly created strand is not in the running state. This strand will only become to running state when the current strand finishes its execution or when it turns to yield state. Therefore we cannot `STEP_IN` to `calculate()` method at this point. 

Please refer the below link to understand the strand behaviour better:
https://ballerina.io/swan-lake/learn/by-example/threads-and-strands.html
