### ISSUE TITLE
Methods supported for `error` type values are not suggested for a error value belonging to a union of error types in a different module

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#28163]
**Description:**
![Screenshot from 2021-01-23 11-27-24](https://user-images.githubusercontent.com/19838787/105570478-aff8c000-5d6f-11eb-9147-45a4157ba1a5.png)

https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/grpc-ballerina/grpc_errors.bal#L84

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lasinicl** [comment]
You can find the sample project in https://github.com/lasinicl/order-management-system
Please check
https://github.com/lasinicl/order-management-system/blob/main/order_service/OrderMgt_sample_service.bal#L24

**Comment by dulajdilshan** [comment]
The issue has been fixed. Tested on the latest distribution.
