### ISSUE TITLE
When debugging a line uses a library, step in behavior seems stuck in the same line

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#28176]
**Description:**
Since we can't show decompiled lib code, step in seems stuck in the same line even steps are actually going through the lib code.

**Steps to reproduce:**
Clone https://github.com/pramodya1994/hierarchical-package-project
Add debug breakpoint in L24 in `googleapis_sheets.bal`
Try to use step in.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with #28708
