### ISSUE TITLE
On Fail variable definition not suggested within the clause

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28189]
**Description:**
![onFailVar](https://user-images.githubusercontent.com/15815199/105671096-292b1b00-5f08-11eb-82ae-4ea588a27bc1.gif)

On fail variable definition is visible within its clause. Atm, the reference is not among the suggestions.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Swan Lake Alpha

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pubudu91** [comment]
Had a look at this. Looks like a symbol is not getting defined for the on fail var internally. When are collecting the visible symbols, the on fail var symbol is missing in the scope.
