### ISSUE TITLE
Special casing Langlib in API Docs.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28208]
With  https://github.com/ballerina-platform/ballerina-spec/issues/507, we have removed langlib module versions. But we need to put some versions in the langlib projects in the implementation. These are getting rendered in API docs. 

![Screenshot 2021-01-25 193046](https://user-images.githubusercontent.com/1356214/105716195-81800e00-5f44-11eb-8fde-d9b298ebad2f.png)

I think the following are options we have : 
1) Remove the version from the doc. 
2) Maintain the implementation version and Show it in the API Docs. 

@sameerajayasoma @hevayo , thoughts?

Affected: Swanlake Alpha.

**Comment by sameerajayasoma** [comment]
I can't see the version when I visit this page. https://ballerina.io/swan-lake/learn/api-docs/ballerina/#/

**Comment by hasithaa** [comment]
This is in the dev site, https://dev.ballerina.io/swan-lake/learn/api-docs/ballerina/#/ which will be merged into production soon.

**Comment by shehan360** [comment]
Closing as this issue is now resolved.
![Screenshot from 2021-05-18 15-48-40](https://user-images.githubusercontent.com/33398983/118634831-98e34f80-b7f0-11eb-8e80-f43b8515927f.png)
