### ISSUE TITLE
Query action is not suggested

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28202]
**Description:**
![doAction](https://user-images.githubusercontent.com/15815199/105699235-09f2b480-5f2d-11eb-9a22-7ff8164b9106.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by IMS94** [comment]
This hasn't previously been solved completely. Will be fixed by #29761
