### ISSUE TITLE
"invalid Ballerina.toml file" error when there's an empty 'Dependencies.toml' file

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28200]
**Description:**
$title. The error is not observed when the 'Dependencies.toml' file is removed.

```
invalid Ballerina.toml file: cannot find [package]
```

**Affected Versions:**
sl-alpha

**Comment by azinneera** [comment]
I tried creating a simple project created using the `bal new` command and added an empty Dependencies file using `touch Dependencies.toml`. There were no errors observed. @MaryamZi Is this happening for a specific scenario?

**Comment by MaryamZi** [comment]
This happened with a simple project (same steps as you have mentioned) on alpha1. Seems to work on a pack built from the current master though.

**Comment by azinneera** [comment]
This is reproducible with SL Alpha1 and has been fixed by https://github.com/ballerina-platform/ballerina-lang/pull/28464/. Therefore closing the issue.
