### ISSUE TITLE
Capture compiler plugin failure information with the diagnostics

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28216]
**Description:**
Currently, in the diagnostics generated for the compiler plugin failures does not include information to isolate the particular plugin which failed.

**Affected Versions:**
slalpha at least

**Comment by hasithaa** [comment]
This issue was created for the old compiler plugin implementation. However, we have added this with
 https://github.com/ballerina-platform/ballerina-lang/pull/29148 for the new implementation. Hence closing this issue.
