### ISSUE TITLE
Suggest only lists or records for the rest argument of a function/method call expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28213]
**Description:**
Can we $subject? Only a list (array or tuple) or a record (not a map) can be passed as the rest arg. But this can be via a variable, function call, etc. 

**Steps to reproduce:**
Currently there seems to be no filtering.

```ballerina
public function main() {
    int intVal = 1;
    int[2] intArr = [1, 2];

    foo(...i<cursor>);
}


function foo(int i, int j) {

}
```

![rest_arg](https://user-images.githubusercontent.com/8376983/105799069-a9f61f80-5fb9-11eb-92e8-095641aa2dc5.png)

**Affected Versions:**
sl-alpha

**Comment by nadeeshaan** [comment]
Fixed with #28530. Hence closing the issue. Please reopen if the issue persist
