### ISSUE TITLE
OpenTelemetry Support

### ISSUE THREAD

**Issue by vanjikumaran** [ballerina-platform/ballerina-lang#28222]
**Description:**
OpenTelemetry is the merging project of OpenTracking and OpenCencus.

https://github.com/open-telemetry/opentelemetry-java
https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0

**Comment by nadundesilva** [comment]
Tracing section of OpenTelemetry will be implemented in #28351

We are only moving to OpenTelemetry now as The OpenTelemetry Spec is now in the process of going to Public Beta and soon will be in GA.

**Comment by keizer619** [comment]
Closing this as Ballerina uses OpenTelemetry
