### ISSUE TITLE
Invalid formatting for mapping match patterns

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28224]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
function foo(any v) {
    match v {
    {a: "hello", b: "world"} => {
    }
    {a: var x} => {
    }
    }
}
```

After formatting
```ballerina
function foo(any v) {
    match v {
        { a:"hello", b:"world" } => {
        }
        { a:var x } => {
        }
    }
}
```

Note 
- spaces added after `{` and before `}` which we do not do for mappings
- space removed after `:`

**Affected Versions:**
sl-alpha

**Comment by IrushiL** [comment]
Closing this issue since it has been fixed by #28522.
