### ISSUE TITLE
Retrieve formatting options from the VS Code plugin 

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#28234]
**Description:**
Currently, the VS Code plugin formatter uses the default formatting options and does not support customizability. This should be made configurable through the VS Code plugin and the Language Server. 

The formatting APIs support these options through the [FormattingOptions](https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingOptions.java) class.

Action Items:
* Retrieve formatting options through the VS Code plugin and pass them through the Language Server to the formatter.
* Evaluate other formatting options that need to be supported (could be tracked in a separate issue once finalized).

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
Closing this based on https://github.com/ballerina-platform/ballerina-lang/issues/38296#issuecomment-2372887614
