### ISSUE TITLE
Testerina Searching for Tests in a Non-Existing Module

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#28239]
**Description:**
I noticed that when the I run the tests in `ballerina graphql` module,  it prints the following message.

> graphql.graphql
        No tests found

But there isn't a module named `graphql.graphql` inside the GraphQL module. Even though this does not affect the functionality, it should be removed.

To check, you can run the [ballerina graphql](https://github.com/ballerina-platform/module-ballerina-graphql) module build.

**Comment by ThisaruGuruge** [comment]
This seems to happen because of the datamapper extension. The Datamapper extension creates a directory named `graphql` inside the `modules` directory. When running the tests, testerina then searches inside this directory for tests.

**Comment by Dilhasha** [comment]
We changed the output for test execution with Alpha3 and this redundant log is no longer present. Hence, closing this issue.
