### ISSUE TITLE
Parameter defaults aren't used as expected in function/method calls

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28248]
**Description:**
Couldn't find an issue tracking this.

For the function call expression, the spec says

> The function-reference must refer to a variable with function type. The type descriptor of that function type is used to construct an argument list from the specified arg-list. **Note that it is the type descriptor of the declared type of the variable that is used for this purpose, rather than the runtime type descriptor of the referenced function value.** 

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Foo object {
    function func(int i = 1234, string s = "hello");
};

class Bar {
    *Foo; // Even without.

    function func(int i, string s) {
        io:println(i);
        io:println(s);
    }
}

public function main() {
    Foo foo = new Bar();
    foo.func();
}
```

Prints
```
0

```
Expected
```
1234
hello
```
**Affected Versions:**
slalpha1

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/10639

**Comment by MaryamZi** [comment]
Also see

```ballerina
import ballerina/io;

type Foo object {
    function func(int i = 1234, string s = "hello");
};

class Bar {
    *Foo; // Even without.

    function func(int i = 5678, string s = "world") {
        io:println(i);
        io:println(s);
    }
}

public function main() {
    Foo foo = new Bar();
    foo.func();
}
```

Prints
```
5678
world
```
Expected
```
1234
hello
```

**Comment by rdhananjaya** [comment]
Being able to access the default values is also a requirement from Ballerina GraphQL impl.
See comment: https://github.com/ballerina-platform/ballerina-lang/pull/27443#issuecomment-744231066
