### ISSUE TITLE
Refactor Commit/Rollback Handler invocation logic

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#28249]
This refactoring is required in order to fix https://github.com/ballerina-platform/ballerina-lang/issues/26187
The solution is to invoke the handlers from ballerina (currently they are invoked from Java)

**Comment by pcnfernando** [comment]
Related issues: 
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/28551
