### ISSUE TITLE
Bad Sad Error for GraphQL service when building with cloud=k8 build option

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#28263]
**Description:**
@all I am getting a weird behavior when running ballerina build with cloud=k8 build option.

1. When there's no `Kubernetes.toml` it runs smoothly and generates k8 `.yaml` files.
2. When there's default `Kubernetes.toml` file, it throws a 'Bad, Sad' with below error

**Affected Versions:**
2.0.0-ALPHA

This is reproducible with the sample project [hello.zip](https://github.com/ballerina-platform/ballerina-lang/files/5882385/hello.zip)

**Comment by anuruddhal** [comment]
This is fixed in SL Beta3.
