### ISSUE TITLE
[Configurable] Revisit `Config.toml` file location for configurables

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#28260]
**Description:**

Currently, `Config.toml` file  is located for program execution in the following ways. 
-  Path is given in an environment variable `BALCONFIGFILE`
-  look for `Config.toml` in the current working directory (where the CLI command is executed)

It would be better to have an option to locate the file at the project root before looking at the current working directory. 

**UPDATE**
The current spec for configurables mentions some new changes
https://github.com/ballerina-platform/ballerina-spec/blob/master/configurable/spec.md#locating-toml-files

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/plugin-vscode/issues/132

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by manuranga** [comment]
> It would be better to have an option to locate the file at the project root before looking at the current working directory.

Not before current working directory, we should only pick the project root config for development time tasks.
current working dir will be used for jar execution.

**Comment by HindujaB** [comment]
We need to find the location for single bal file scenario

**Comment by manuranga** [comment]
I feel like having it next to source is better for user experiences for the development tasks. When we are working via VSCode, we'll anyway have to enforce it. Otherwise there has to be a UI in VSCode to specify it.

 So I think it's better to enforce it from the language itself.

WDYT @sameerajayasoma
related issues was pointed by @prabushi
