### ISSUE TITLE
Ballerina shell shows wrong column for errors

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28266]
```
=$ int x = i\-like\-hyphens                                                                       took 88 ms

=$ i\-\like\-hyphens                                                                             took 216 ms
| Tree parsing failed: invalid escape sequence '\l'
| i\-\like\-hyphens;
| ^
| Parsing aborted because of errors.
```

The caret is in the wrong column.

**Comment by kdsuneraavinash** [comment]
Ballerina shell actually shows only the starting position of the error.
For the above error it spans across the whole name, so maybe the best approach would be to show carets like following?

```
=$ i\-\like\-hyphens 
| Tree parsing failed: invalid escape sequence '\l'
| i\-\like\-hyphens;
| ^^^^^^^^^^^^^^^^^
| Parsing aborted because of errors.
```
or 
```
=$ i\-\like\-hyphens 
| Tree parsing failed: invalid escape sequence '\l'
| i\-\like\-hyphens;
| ^---------------^
| Parsing aborted because of errors.
```

**Comment by jclark** [comment]
Yes, it would be much better for the shell to display the whole span. This would be less confusing for the user and would also be helpful for testing.  In this case, the span that the compiler has reported is not ideal: the span should be `\`.

**Comment by jclark** [comment]
You are providing readline-like command-line editing, which needs to know about terminals. So there's probably a library providing terminal support that you could use to highlight the span in the terminal using e.g. inverse video or underlining.
