### ISSUE TITLE
Ballerina shell should allow redefining module level functions and variables

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28272]
In the shell, this gives an error about redeclaring `add`:

```
function add(int x, int y) returns int => x * y;
add(1, 1)
function add(int x, int y) returns int => x = y;
```

But in a REPL, you often want to develop code interactively, which involves redefining functions that are wrong.

A good start would be to allow redefining the last thing you defined.

**Comment by kdsuneraavinash** [comment]
How would the shell react to any errors causing from old invalidated snippets. For example consider following session,
```ballerina
=$ int i = 100   

=$ i    
100

=$ string i = "Hello" // This is ok 

=$ i                          
Hello

=$ function f() returns string { return i; } 

=$ f()  
Hello

=$ int i = 100 // What would happen to f()
```

By #28432 the result would be follows, disallowing user to redefining variables that were used by another declaration until the other declaration is redefined.
 
```ballerina
// Continuation from above session

=$ int i = 100 
| incompatible types: expected 'string', found 'int?'
| function f() returns string { return i; }
|                                      ^
| Compilation aborted because of errors.

=$ function f()  {  }        

=$ int i = 100     

=$ i  
100
```

However, IMO the ideal behavior would be to follow a similar approach as jshell, allow redefining and not show the error until absolute necessary.

```java
jshell> String s = "Hello"
s ==> "Hello"

jshell> String f() { return s; }
|  created method f()

jshell> f()
$3 ==> "Hello"

jshell> int s = 100
s ==> 100

jshell> f()
|  attempted to call method f() which cannot be invoked until this error is corrected: 
|      incompatible types: int cannot be converted to java.lang.String
|      String f() { return s; }
|                          ^
```

Any thoughts?

**Comment by jclark** [comment]
The jshell behaviour looks good to me. If that’s too hard to implement, perhaps you could provide e.g.

```
/delete f, g, h
```

to allow me to explicitly remove definitions (multiple args to allow removing mutually recursive definitions).
