### ISSUE TITLE
Incorrect error with 'is'

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28285]
This correct program:

```
import ballerina/io;

public function main() {
   boolean b = "str" is string;
   io:println(b);
}
```

gets rejected with the error:

```
ERROR [demo8.bal:(4:16,4:31)] unnecessary condition: expression will always evaluate to 'true'
```

**Comment by hasithaa** [comment]
Related to https://github.com/ballerina-platform/ballerina-spec/issues/724

**Comment by jclark** [comment]
@hasithaa I’m not using this in a condition, so it’s clearly not an error regardless of https://github.com/ballerina-platform/ballerina-spec/issues/724

**Comment by hasithaa** [comment]
@jclark This is one of the root cause for ballerina-platform/ballerina-spec#724, That is why I liked it.
