### ISSUE TITLE
Positive and negative float zero are not ===

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28284]
This program gives the wrong output:

```
import ballerina/io;

public function main() {
   io:println("Should be false: ", +0.0 === -0.0);
}
```

From https://ballerina.io/spec/lang/master/#section_5.2.4.1:

> Positive and negative zero of a floating point basic type are distinct values

**Comment by hasithaa** [comment]
Duplicates #17977
