### ISSUE TITLE
Issue when modifying ListMatchPatternNode and MappingMatchPatternNode

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#28281]
**Description:**
The match pattern nodes `ListMatchPatternNode` and `MappingMatchPatternNode` contain a `RestMatchPatternNode` attribute which could be included inside the separated node list of match pattern nodes itself.

When modifying a match pattern node of this sort, there exists a difficulty in handling the `,` separator which is after the list of binding pattern nodes and before the rest match pattern node.

Fixes: https://github.com/ballerina-platform/ballerina-lang/issues/28154

**Steps to reproduce:**

ListMatchPatternNode:
```bal
function test1(any v) {
    match v {
        [var a , ...var b] => { // Bug
            return;
        }
    }
}
```
**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
code snippet for the `MappingMatchPatternNode`
https://github.com/ballerina-platform/ballerina-lang/blob/3359afb47ef6e6767531d7b40bd42bf73eebbbb0/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L13485-L13532

**Comment by lochana-chathura** [comment]
code snippet for the ListMatchPatternNode
https://github.com/ballerina-platform/ballerina-lang/blob/3359afb47ef6e6767531d7b40bd42bf73eebbbb0/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L13364-L13412
