### ISSUE TITLE
Need to recognize character references in attributes in XML literals

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28305]
For example:

```
import ballerina/io;

public function main() returns error? {
   var x = xml`<p att="x&amp;y"/>`;
   string att = check x.att;
   io:println("Expected 3 Got: ", att.length());
}
```

It does not seem to be parsing character references at all.  For example:

```
io:println(xml`<p att="x&amp;y"/>`.toString());
```

prints

```
<p att="x&amp;amp;y"/>
```

**Comment by rdhananjaya** [comment]
It seems the XML parser does not perform `Attribute-Value Normalization`[[1](https://www.w3.org/TR/2006/REC-xml11-20060816/#AVNormalize)] 

[1] - [https://www.w3.org/TR/2006/REC-xml11-20060816/#AVNormalize](https://www.w3.org/TR/2006/REC-xml11-20060816/#AVNormalize)

**Comment by jclark** [comment]
This is fairly critical to XML support.

**Comment by rdhananjaya** [comment]
@jclark do we need to normalize the interpolated parts too?
```ballerina
    var x = xml`<p att="a${"\u{D}"}b"/>`;
```

**Comment by jclark** [comment]
No.

**Comment by rdhananjaya** [comment]
Ack. Thanks.
