### ISSUE TITLE
Indexing should work on sequences (string and xml)

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28312]
v[i] on a string or xml value should give the singleton item at index i, but it doesn't work for either string or xml.

If I do this in the shell

```
"abc"[0]
```

I get a compile-error. Similarly for

```
xml`abc`[0]
```

(which should result in xml`abc`). It also doesn't work if I assign to variables first.

Iteration (with `foreach`) does work: this should be consistent with iteration.

**Comment by kdsuneraavinash** [comment]
Reproducible outside the shell as well,
```ballerina
import ballerina/io;

public function main() {
    io:println("abc"[0]);
}
```
Gives
```
ERROR [sad.bal:(4:16,4:21)] invalid expression: 'abc' does not support index access
```

**Comment by lasinicl** [comment]
Partially fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28833

**Comment by rdhananjaya** [comment]
XML case should be fixed in https://github.com/ballerina-platform/ballerina-lang/pull/28556

**Comment by lasinicl** [comment]
Closing this since both the PRs have been merged.
