### ISSUE TITLE
Identity for xml:Text is wrong

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28310]
Identity (===) for xml:Text items is like string: they are === if they contain the same characters.

But if I try:

```
 xml`abc` === xml`abc`
```

in the shell, I get `false`. I should get `true`.

**Comment by kdsuneraavinash** [comment]
Reproducible even outside the shell,
```
import ballerina/io;

public function main() {
    io:println("Should get true: ", xml `abc` === xml `abc`);
}
```

will output `Should get true: false`.
