### ISSUE TITLE
Support configurable values to be read from env

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#28327]
**Description:**
We need to support reading configurable values from environment variables as many Cloud applications depend on configurations via env. 

Please refer https://12factor.net/

**Steps to reproduce:**

**Affected Versions:**
swan-lake-alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by manuranga** [comment]
We are supporting specifying toml path using a env variable. But as per the 12factor best practice this seems to be not enough. Please create an issue on the ballerina spec repo, and tag Sanjiva, James, Hasitha, Sameera. If this is needed for beta we need to decide on this quickly.

(removing blocker tag until spec is finalised)

**Comment by warunalakshitha** [comment]
Closing this issue as per the https://github.com/ballerina-platform/ballerina-spec/issues/723#issuecomment-786882219
