### ISSUE TITLE
[VSCode] Code completion/suggestion does not work when tooltip active

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#28332]
**Description:**
Observed $subject. Is this expected or a bug?

**Steps to reproduce:**

```ballerina
import ballerina/io;

class Teacher {
    public string name;
    private int age;

    function init(string name, int age){
        self.name = name;
        self.age = age;
    }

    function test() returns string {
        return "Aiyo";
    }
}

public function main() {
    Teacher teacher = new Teacher("Mohan" , 22);
    io:println(teacher)
}
```

<img width="833" alt="Screenshot 2021-02-01 at 13 01 40" src="https://user-images.githubusercontent.com/7523274/106427713-d7493e80-648d-11eb-8376-917062a6f62f.png">

**Comment by nadeeshaan** [comment]
This is the default VSCode behaviour when the cursor is within a snippet's placeholder. This can be handled by adding the following configuration to the user settings. 
`"editor.suggest.snippetsPreventQuickSuggestions": false`. From the latest plugin release onwards, this config will be added by default. Hence closing the issue.
