### ISSUE TITLE
Restriction of null to json type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28342]
In alpha1, this gets a compile-error:

```
int? x = null;
```

This is a correct program according to the spec, since the spec says:

> the use of null should be restricted to JSON-related contexts

Note this is **should**, and it does not say `json` type.

This is not a helpful restriction. For example, I wanted to copy and paste some data from a JSON file and use it as the initializer of a user-defined record type (to see whether my data-binding would work), but I couldn't because of this.

**Comment by lasinicl** [comment]
@jclark  
Can `map<json|Foo>` (where `Foo` is an object), `map<int|Foo>` considered JSON contexts?

**Comment by jclark** [comment]
The spec says "the use of null *should* be restricted to JSON-related contexts". Note that it is *should* not *must*: that means it is a recommendation for the user, not something that the compiler is supposed to enforce.
