### ISSUE TITLE
[VSCode Plugin] Invalid error message as redeclared import

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#28341]
**Description:**
Even though there is no any redeclared imports and compilation successful, editor shows an error message. I had to restart the VSCode editor to get rid of the error message.

<img width="723" alt="Screenshot 2021-02-01 at 14 37 33" src="https://user-images.githubusercontent.com/7523274/106437934-cdc6d300-649b-11eb-8f57-0ed0cd672987.png">

**Comment by nadeeshaan** [comment]
Duplicate of #28395. Hence closing the issue
