### ISSUE TITLE
Relational expressions are not supported with all ordered types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28352]
**Description:**
The spec says for relational expressions https://ballerina.io/spec/lang/master/#section_6.27

> A relational-expr tests the relative order of two values. There must be an ordered type to which the static type of both operands belong.

But we currently seem to allow them only for numeric values.

**Steps to reproduce:**
The following aren't allowed atm.
```ballerina
import ballerina/io;

public function main() {
    string a = "a";
    string b = "b";
    io:println(a >= b);

    boolean c = true;
    boolean d = false;
    io:println(c < d);
}
```

**Affected Versions:**
slalpha1

**Comment by daneshk** [comment]
We need these relational expressions to support ordered tuple values to compare two time values represented in UTC format. for example, 

```
type Utc readonly & [int,decimal];

public function main() {
   Utc timeOne = [59215, 9945];
   Utc timeTwo = [59283, 24345];
   io:println(timeTwo >= timeOne);
}
```
