### ISSUE TITLE
STEP_OVER works as STEP_IN when there is a breakpoint inside object init() method

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#28362]
**Description:**
`STEP_OVER` debug operation works as `STEP_IN` when there is a breakpoint inside object `init()` method.

**Steps to reproduce:**
- Consider the below code segment:
```
class Person {
    public int age;
    public string firstName;
    public string lastName;

    function init(int age, string firstName, string lastName) {
        self.age = age;
        self.firstName = firstName;
        self.lastName = lastName;
    }

    function getFullName() returns string {
        return self.firstName + " " + self.lastName;
    }
}

public function main() {
    Person person = new Person(30, "Jack", "Sparrow");
    string personFullName = person.getFullName();
    
}
```
- Add breakpoint inside object init() method. (Here add a breakpoint in front of the line `self.age = age;`)
- Add a breakpoint in front of object creation line. (Here add a breakpoint in front of the line `Person person = new Person(30, "Jack", "Sparrow");`)
- Run the program in debug mode.
- Program will break in object creation line. Now do a `STEP_OVER` here.
- We can observe that the debug navigator hits inside object init() method instead of going to the next line.

**Affected Versions:**
```
Ballerina Swan Lake Alpha 1
Language specification v2020-12-17
Update Tool 0.8.14
```

**Comment by NipunaRanasinghe** [comment]
Closing since this is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/29267
