### ISSUE TITLE
Debug breakpoint does not get hit in wait action

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#28363]
**Description:**
Debug breakpoint does not get hit in `wait` action(asynchronous calls).

**Steps to reproduce:**
- Consider the below code segment:
```
public function main() {
    future<int> f1 = start addition(4, 5);
    map<int> results = wait {f1};
}

function addition(int x, int y) returns int {
    return x + y;
}
```
- Add breakpoint in front of `wait` action (Here in front of the line `map<int> results = wait {f1};`)
- Run the program in debug mode.
- We can observe that the debug point doesn't get hit.

**Affected Versions:**
```
Ballerina Swan Lake Alpha 1
Language specification v2020-12-17
Update Tool 0.8.14
```

**Comment by praveennadarajah** [comment]
- Consider the below code segment:

![image](https://user-images.githubusercontent.com/11292766/116953590-49a70600-acab-11eb-9c7e-4fa1295e3e7c.png)

- When we debug `configureUserBreakPoints` method of class `JDIEventProcessor` [1], `referenceType.allLineLocations()` does not contain location information regarding `wait` keyword. In the above code example,  `referenceType.allLineLocations()` does not contain `line 4` location information (Refer below image). Due to unavailability of `wait` location information, `wait` action debug point is getting skipped during the debug session.

![image](https://user-images.githubusercontent.com/11292766/116953627-5f1c3000-acab-11eb-8dc9-9c1880c5f20b.png)

[1] https://github.com/ballerina-platform/ballerina-lang/blob/release-2.0.0-alpha6/misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/JDIEventProcessor.java#L205

**Comment by warunalakshitha** [comment]
Ficed with https://github.com/ballerina-platform/ballerina-lang/pull/32551
