### ISSUE TITLE
Filter out iterable symbols from document

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#28373]
**Description:**
In a case of like Foreach the given type for the list is Iterable and we need a way to filter out iterable symbols available in the document or module which can be applicable to a place like this. This is more like a language server completion use case.

**Comment by pubudu91** [comment]
I think this can be achieved using the current APIs as follows:
- Use `visibleSymbols()` to get the symbols visible at the cursor pos
- Filter and get the `ModuleSymbol` for `lang.object`
- Use `typeDefinitions()` to get the type defs and find the `Iterable` object type def
- Again, take the originally taken visible symbols list and filter out the var symbols out of it
- Iterate through these var symbols and check if the type of each var is assignable to the `Iterable` object type. The `assignableTo()` method can be used for this.

**Comment by mohanvive** [comment]
Closing the issue with the comment provided by Pubudu.
