### ISSUE TITLE
Incompatible type error when &'ing byte and int

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#28386]
Consider the following example.

```ballerina
function foo() {
	int x = 0xDEADBEEF;

	// OK because byte & int
	// will be byte 
	byte b = x & 0xFF;
} 
```

The result type is `byte`, So there should not be a compile error. But currently it gives the following error

```
Compiling source
        gimantha/myProj:0.1.0
ERROR [test.bal:(10:10,10:18)] incompatible types: expected 'byte', found 'int'
error: compilation contains errors
```

**Comment by pcnfernando** [comment]
As per spec; https://ballerina.io/spec/lang/2020R1/#section_5.1.3

> The byte type is a subtype of int

Hence, the following is allowed.

```ballerina
byte tempByte = 0xFF;
int byteAsInt = tempByte;
```
But, not this.
```ballerina
int byteAsInt = 0xFF;
byte tempByte = byteAsInt;
```

Bitwise operation should be updated as;
```ballerina
function foo() {
   byte x = 12;
   //both of the following are allowed
   byte a = x & 0xFF;
   int b = x & 0xFF;
} 
```

**Comment by gimantha** [comment]
@hasithaa Clarification regarding this issue, 
We know that the result of bitwise & between an integer and a byte is always a byte. So In that case, assigning to a byte type variable should be allowed. Isnt it?

**Comment by hasithaa** [comment]
Yes, This should be allowed. I suspect we need to improve the logic of https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java#L652 accordingly

**Comment by pcnfernando** [comment]
It seems it's a matter of casting the hex literal as a byte. The hex literal is resolved as an int which causes the incompatible type issue.
Please refer to the test added in https://github.com/ballerina-platform/ballerina-lang/pull/28911

**Comment by hasithaa** [comment]
Does the user has to put a cast ? or is it at the desugar level?

**Comment by pcnfernando** [comment]
As per the offline discussion will handle it at compiler. 
Bitwise operator symbol resolving is being done at TypeChecker. Hence, casting in desugar would not work.
