### ISSUE TITLE
VSCode doesn't provide suggestions after some time

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#28397]
Related to #28396

Issue 1: I am getting completely unrelated diagnostics now 
<img width="535" alt="Screen Shot 2021-02-02 at 1 51 10 PM" src="https://user-images.githubusercontent.com/2637328/106667383-b6501e80-655d-11eb-8437-b5672c3171dc.png">

<img width="591" alt="Screen Shot 2021-02-02 at 1 49 38 PM" src="https://user-images.githubusercontent.com/2637328/106667298-97ea2300-655d-11eb-92aa-fd2bafa1d003.png">

Issue 2: Now I am not getting any suggestions
<img width="565" alt="Screen Shot 2021-02-02 at 1 51 43 PM" src="https://user-images.githubusercontent.com/2637328/106667453-cbc54880-655d-11eb-8263-6140681e8ec7.png">

No logs in the output tab

**Comment by nadeeshaan** [comment]
This could be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28568

**Comment by nadeeshaan** [comment]
This fix has been merged. Hence closing the issue, if the issue exists still, please reopen
