### ISSUE TITLE
Diagnostics are not cleared even after fixing the code

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#28395]
This issue is related to #28394

I removed the duplicate import declarations, but I can still see invalid diagnostics in the VSCode.

<img width="857" alt="Screen Shot 2021-02-02 at 1 23 33 PM" src="https://user-images.githubusercontent.com/2637328/106664422-e4cbfa80-6559-11eb-8c38-9962d9d2d10f.png">

**Comment by nadeeshaan** [comment]
Could be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28568 where the initial observation was a `redeclared import` diagnostic.

**Comment by nadeeshaan** [comment]
The fix has been merged. Hence closing the issue and if the issue exists still, please reopen
