### ISSUE TITLE
Toml parser gives an error for valid content

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#28399]
Here is the sample toml:

<img width="262" alt="Screen Shot 2021-02-02 at 4 19 27 PM" src="https://user-images.githubusercontent.com/2637328/106679977-8e1eea80-6572-11eb-9c6d-bd8c2aef79cb.png">
<img width="682" alt="Screen Shot 2021-02-02 at 4 19 43 PM" src="https://user-images.githubusercontent.com/2637328/106679982-90814480-6572-11eb-9e43-80cde34b2f84.png">

**Comment by xlight05** [comment]
I'm unable to reproduce this issue. Is this using our own toml parser?  error messages seems bit different.

**Comment by HindujaB** [comment]
I couldn't reproduce this issue with vscode. 
And, we didn't add the `Config.toml` to our tooling support yet. So, this error message seems unlikely. 
Could this be coming from a different toml plugin that uses TOML(version 0.4 that doesn't support dotted keys)?

**Comment by sameerajayasoma** [comment]
Closing this as I also can't reproduce this anymore. I will re-open if it appears again
