### ISSUE TITLE
Support DiagnosticLog.logDiagnostic() to be compatible with project API's PackageId

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#28406]
**Description:**
Currently `logDiagnostic()` uses internal representation of PackageID as a parameter (`org.ballerinalang.model.elements.PackageID`)

https://github.com/ballerina-platform/ballerina-lang/blob/73976d00cbba57562fd541221a6e5e1c82648b87/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticLog.java#L49

We need to change this to support to Package ID, the project API returns 
i.e: `io.ballerina.projects.ProjectId`

**Steps to reproduce:**

**Affected Versions:**
slalpha3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This looks like a blocker for Beta, since this is an API change.

**Comment by hasithaa** [comment]
@dulajdilshan let's deprecate the existing API and add a new API for Alpha3. I guess we can migrate code usages after Beta.
