### ISSUE TITLE
Completion items icons should be redesigned

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#28412]
**Description:**
Completion items icons should be redesigned.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This has been addressed in the latest implementation. Hence closing the issue
