### ISSUE TITLE
Annotation access doesn't work with bound methods

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28439]
**Description:**
$title.

When `io.ballerina.runtime.internal.AnnotationUtils#processFPValueAnnotations` is called for the bound method, the name of the method is something like "$annon$method$delegate$0" while the entry in the annotation map is "ObjectName.MethodName" (e.g., "Foo.bar" below).

**Steps to reproduce:**
```ballerina
import ballerina/io;

annotation record {int i;} X on function; 

class Foo {
    @X {i: 101}
    function bar(int i) returns string => i.toString();
}

public function main() {
    Foo f = new;
    typedesc t = typeof f.bar;

    io:println(t.@X is ()); // prints `true`
}
```

**Affected Versions:**
slalpha1

**Comment by KRVPerera** [comment]
Adding an example related to this.

#### Output

```LogTalk
error: {ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'HSC'"}
	at t2:main(t2.bal:39)
```

#### Ballerina code

```Ballerina
public type HSC record {|
    string hostRecField = "default_host_name";
    boolean boolRecField = true;
|};

public annotation HSC HSCfa on object field;
public annotation HSC HSCfm on object function;
public annotation HSC HSCsa on class;

@HSCsa {
        hostRecField : "sadf"
    }
service class C1 {

    final string xField = "fields";

        @HSCfm {
            hostRecField : "methods"
        }
        public function getSum() returns int {
            return 1 + 3;
        }
}

function createService(string hosty, decimal maxAgeMy, boolean allowCredentials) returns service object {
    string xField;
    public function getSum() returns int;
} {

    var httpService = new C1();
    return httpService;
}

public function main() {
    var obj = createService("hostKRv", 200, true);
    assertValueEquality("fields", obj.xField);

    typedesc<any> t = typeof obj.getSum;
    HSC annotationVal = <HSC>t.@HSCfm;
}

type AssertionError distinct error;
const ASSERTION_ERROR_REASON = "AssertionError";

function assertValueEquality(anydata expected, anydata actual) {
    if expected == actual {
        return;
    }
    panic error(ASSERTION_ERROR_REASON,
                message = "expected '" + expected.toString() + "', found '" + actual.toString () + "'");
}
````

**Comment by MaryamZi** [comment]
> ```ballerina
> public type HSC record {|
>     string hostRecField = "default_host_name";
>     boolean boolRecField = true;
> |};
> 
> public annotation HSC HSCfa on object field;
> public annotation HSC HSCfm on object function;
> public annotation HSC HSCsa on class;
> 
> @HSCsa {
>         hostRecField : "sadf"
>     }
> service class C1 {
> 
>     final string xField = "fields";
> 
>         @HSCfm {
>             hostRecField : "methods"
>         }
>         public function getSum() returns int {
>             return 1 + 3;
>         }
> }
> 
> function createService(string hosty, decimal maxAgeMy, boolean allowCredentials) returns service object {
>     string xField;
>     public function getSum() returns int;
> } {
> 
>     var httpService = new C1();
>     return httpService;
> }
> 
> public function main() {
>     var obj = createService("hostKRv", 200, true);
>     assertValueEquality("fields", obj.xField);
> 
>     typedesc<any> t = typeof obj.getSum;
>     HSC annotationVal = <HSC>t.@HSCfm;
> }
> 
> type AssertionError distinct error;
> const ASSERTION_ERROR_REASON = "AssertionError";
> 
> function assertValueEquality(anydata expected, anydata actual) {
>     if expected == actual {
>         return;
>     }
>     panic error(ASSERTION_ERROR_REASON,
>                 message = "expected '" + expected.toString() + "', found '" + actual.toString () + "'");
> }
> ```

There seems to be a different issue here. When we access the annotations of the method what we seem to get is that of the method in the return object type of `createService`, rather than the actual method.

For example, with the fix for the original issue we get `{"i":1}` for the following, but it should be `{"i":2}`.

```ballerina
import ballerina/io;

type Rec record {|
    int i;
|};

annotation Rec annot on function;

object {
    @annot {
        i: 1
    }
    function fn();
} ob = object {
    @annot {
        i: 2
    }
    function fn() {

    }
};

public function main() {
    typedesc t = typeof ob.fn;
    io:println(t.@annot);
}
```

Shall we create a separate issue for this? I think we need to revisit the entire approach.
