### ISSUE TITLE
Code action that generates a missing function

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#28444]
Here is an example: 
<img width="483" alt="Screen Shot 2021-02-04 at 12 56 47 PM" src="https://user-images.githubusercontent.com/2637328/106954406-96009b00-66e8-11eb-9a49-0c7478ba138d.png">

How about a code action that allows me to generate this `add` function? It should infer the param types and the return type.

**Comment by nadeeshaan** [comment]
Duplicate of #27424. Hence closing this issue.
