### ISSUE TITLE
Inconsistency in 'Document this' with deprecated keyword

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#28449]
**Description:**
`Document this` code action on `function` keyword adds docs to the function. But on `@deprecated` keyword, it adds class level docs.

And, once docs are added to the function level, it results in the following error.
<img width="440" alt="Screenshot 2021-02-05 at 11 41 55" src="https://user-images.githubusercontent.com/5234623/106996610-4f25aa80-67a7-11eb-9aeb-7e995a64f90d.png">

**Steps to reproduce:**
```
class className {
    public int name = 10;

    @deprecated
    function nameIt(int b) {

    }
}
```

**Affected Versions:**
SL-Alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rasika** [comment]
This is blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/28873
