### ISSUE TITLE
Do not suggest the variable that is being initialized in the init expression

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#28443]
Check this sample. The variable `xy` is in the completion list.

<img width="831" alt="Screen Shot 2021-02-04 at 12 38 17 PM" src="https://user-images.githubusercontent.com/2637328/106952498-09ed7400-66e6-11eb-9467-6efd5be53f5c.png">

**Comment by pubudu91** [comment]
Duplicate of #25607

**Comment by pubudu91** [comment]
Closing since it's a dupicate of #25607
