### ISSUE TITLE
Issue Tip pop-up window shows half of the error message in vs code

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-lang#28452]
**Description:**
In vs code, if some issue messages are too long, you can not see the full error message in the issue tip pop up window. 

**Steps to reproduce:**
Hover the mouse pointer over an error code line, you may see the pop-up window is showing half of the error message.

![image](https://user-images.githubusercontent.com/5174183/107011304-79826280-67bd-11eb-82e5-f5d52479fa6d.png)

**Suggested Labels (optional):**
Area/LanguageServer

**Comment by nadeeshaan** [comment]
Currently the intellisense window allows to scroll text in the window. can you try scrolling? If it does not work, please reopen the issue
