### ISSUE TITLE
Formatter does not add space after colon in mapping BP

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#28472]
**Description:**
$subject

**Comment by IrushiL** [comment]
@rdulmina It will be helpful if you can add a code snippet with the current output and the expected output.

**Comment by rdulmina** [comment]
> @rdulmina It will be helpful if you can add a code snippet with the current output and the expected output.

```bal
type myRecord record { int a; };
// current
myRecord {a:myvar};
// expected (note space after colon)
myRecord {a: myvar};
