### ISSUE TITLE
Random file gets created when trying to build

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#28471]
**Description:**
File with a random name (eg: `0c0fe1c7-c3c2-4f95-aef5-a093aacd98da`) gets created when running `bal build` from the cli

**Steps to reproduce:**
<img width="803" alt="Screenshot 2021-02-08 at 10 08 16 AM" src="https://user-images.githubusercontent.com/1686124/107176867-745c2800-69f6-11eb-94a2-ccf9c1a92d80.png">

[rootmoddemo.zip](https://github.com/ballerina-platform/ballerina-lang/files/5941334/rootmoddemo.zip)

**Affected Versions:**
Ballerina Swan Lake Alpha 1
Language specification v2020-12-17
Update Tool 0.8.12

**OS, DB, other environment details and versions:**
Mac

**Comment by keizer619** [comment]
This has been fixed in following PR
https://github.com/ballerina-platform/ballerina-update-tool/pull/75
