### ISSUE TITLE
Optional field accessor doesn't work for XML elements in Query expressions

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#28485]
Consider the following code.
```ballerina
import ballerina/io;
public function main() {
    xml x1 = xml `<name><fname>supun</fname><fname xmlns="thh">thilina</fname><lname>setunga</lname></name>`;
    xml d = from var fname in x1.<fname>
          where fname?.xmllns == "thh"
          select fname;
   io:print(d);       
}
```

The above code gives the following errors when compiling
```
ERROR [test.bal:(5:17,5:30)] invalid operation: type '(xml|string)' does not support optional field access
ERROR [test.bal:(6:18,6:23)] incompatible types: expected 'xml', found '(xml|string)'
error: compilation contains errors
```

Affected versions: SL alpha 1

**Comment by lasinicl** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28539. Hence closing the issue. 
A test has been added via https://github.com/ballerina-platform/ballerina-lang/pull/28643/files#diff-e19ab0a8660915d784fa3a57e6e4a07c2cec490041b414cad0cb33bdf14d3394R561
