### ISSUE TITLE
Update documentation quick fix not working for fields in a service decl

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#28509]
See the following. The documentation for the field is not getting added.
![Peek 2021-02-08 22-12](https://user-images.githubusercontent.com/6260009/107252036-faaa5580-6a5a-11eb-8a7c-4b36ef619584.gif)

**Comment by IMS94** [comment]
This issue will be temporarily avoided with #28710. 
Need #27493 to implement a proper fix.
