### ISSUE TITLE
Need configurable support for additional field in open records

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#28504]
**Description:**
Currently the `configurable` variable of record type does not support user to include additional fields through the config file.
This is due to some TOML mapping inconsistencies. 

| TOML type      | Ballerina type |
| ----------- | ----------- |
| Integer      | int, byte |
| Float   | float, decimal |
| Array   | array, tuple |
etc.

We must provide a way for user to add new fields to open records. 

 **Steps to reproduce:**

**Affected Versions:**
alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#28091 

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sameerajayasoma** [comment]
We are not planning to support mapping value support in TOML or command-line argument syntaxes in the near future. Refer to the spec for more details. 
[https://github.com/ballerina-platform/ballerina-spec/tree/master/configurable](https://github.com/ballerina-platform/ballerina-spec/tree/master/configurable
)

**Comment by warunalakshitha** [comment]
I am reopening this issue since we support mapping values through toml syntax and this can occur with open records.

**Comment by warunalakshitha** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/30390
