### ISSUE TITLE
No suggestion given for record fields

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#28526]
**Description:**
Check the below attachment. 
<img width="601" alt="Screen Shot 2021-02-09 at 2 22 09 PM" src="https://user-images.githubusercontent.com/690559/107339310-916e2500-6ae2-11eb-9853-c43b5b7530ad.png">

I don't get the suggestion for the record type fields when trying to create one with the map.

**Steps to reproduce:**

**Affected Versions:**
ballerina-swan-lake-alpha1 (both Ballerina and VSCode plugin versions)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
I am not sure whether the following issue, on if block is not suggesting the var name, is also related here.

<img width="719" alt="Screen Shot 2021-02-09 at 2 51 13 PM" src="https://user-images.githubusercontent.com/690559/107343918-db0d3e80-6ae7-11eb-90bc-2b8e25383d62.png">

**Comment by nadeeshaan** [comment]
@Kishanthan When I tried the second case, locally with sl-alpha I get the next variable as a suggestion. 
<img width="836" alt="Screenshot 2021-02-09 at 17 31 28" src="https://user-images.githubusercontent.com/1329674/107361130-e61e9980-6afc-11eb-8839-d6a11146b32c.png">

Do you have the same issue even after reloading the window?
