### ISSUE TITLE
Validate Table keys before table constructor

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#28528]
**Description:**
The validations for the key fields specified for a table are done at the type checking of a table constructor.
Eg: key should be a readonly  & required field.
https://github.com/ballerina-platform/ballerina-lang/blob/e3d345165bd81a7ce6cdf9d9191508355414ffe9/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L1137

Due to this, the errors are thrown only when we initialize a table.

As we have the required information at the table type definition, we should check the key fields earlier (at type definition) to reduce issues from imported types and fail early. 

**Steps to reproduce:**
![Screenshot from 2021-02-09 13-39-05](https://user-images.githubusercontent.com/28644893/107342983-e01dbe00-6ae6-11eb-9047-9ec72ec7f60e.png)
![Screenshot from 2021-02-09 13-39-45](https://user-images.githubusercontent.com/28644893/107342988-e14eeb00-6ae6-11eb-8657-b71e213d2602.png)

**Affected Versions:**
alpha1

**OS, DB, other environment details and versions:**
vscode 

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdulmina** [comment]
This issue still exists for no-init var declaration with table type
```bal
type Person record {|
    int id;
    string name;
|};

public function main() {
    table<Person> key(id) tableVar; // `id` is not readonly, no error at compile time
    table<Person> key(invalidField) tableVar2; // No field name `invalidField`, no error at compile time
}
```

**Comment by rdulmina** [comment]
Related issue  #30985
