### ISSUE TITLE
Duplicate code fixes suggestions

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#28531]
**Description:**
Check the below attached image where you get duplicate suggestions.

<img width="663" alt="Screen Shot 2021-02-09 at 5 19 24 PM" src="https://user-images.githubusercontent.com/690559/107359988-5cba9780-6afb-11eb-8e5c-a4616345e510.png">

**Steps to reproduce:**

**Affected Versions:**
ballerina-swan-lake-alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This can be caused due to caching issue. Hence we need to check this again after the #28568 merged.
