### ISSUE TITLE
Invalid suggestion for code fixes

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#28532]
**Description:**
Check the below attached image where you an invalid suggestion. The suggestion was to change type of the variable. But that is wrong as the variable already of the same type being suggested.

<img width="710" alt="Screen Shot 2021-02-09 at 12 35 26 PM" src="https://user-images.githubusercontent.com/690559/107360369-d81c4900-6afb-11eb-99ca-3e8800ee44c1.png">

**Steps to reproduce:**

**Affected Versions:**

Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Here's another one. It shouldn't be suggesting type casts when there are error types in the expression's type since it will result in a compile error.
![Screenshot from 2021-02-10 02-17-06](https://user-images.githubusercontent.com/6260009/107426630-7b924b80-6b46-11eb-8d35-c7aaa7552327.png)

**Comment by rasika** [comment]
@Kishanthan yeah that we'll fix. @pubudu91 yes shouldn't suggest quickfix when there's a error member type of an union
