### ISSUE TITLE
Invalid code snipet generated for code fix suggestion

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#28534]
**Description:**
Check the below two images. The code sniped generated lastly is not valid and it is missing a type from the expected union type.

1.
<img width="677" alt="Screen Shot 2021-02-09 at 5 28 45 PM" src="https://user-images.githubusercontent.com/690559/107361555-8ffe2600-6afd-11eb-917f-0b6056173df6.png">

2.
<img width="666" alt="Screen Shot 2021-02-09 at 5 28 53 PM" src="https://user-images.githubusercontent.com/690559/107361561-94c2da00-6afd-11eb-9ca6-48a44983269f.png">

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Alpha 1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rasika** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/28654

**Comment by IMS94** [comment]
@Kishanthan @nadeeshaan This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/29650. Now the `Create variable and check error` code action will add the following:
```
string[]|() next = check channel.getNext();
```

**Comment by nadeeshaan** [comment]
Closing based on the previous comment
