### ISSUE TITLE
Change the Command Output for Creating BALA File

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#28541]
**Description:**
Ned to change the command output for creating BALA File as per [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1807#discussion_r572998527

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Closing since the website is updated.
