### ISSUE TITLE
Auto-imports and module prefixes for langlibs use quoted identifiers unnecessarily

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28542]
**Description:**
Only the langlibs that have names that are keywords need to use quoted identifiers in the imports.

Module prefixes do not have to be quoted for any of the the langlib imports now.

**Steps to reproduce:**
![auto_import](https://user-images.githubusercontent.com/8376983/107394511-fb59ef00-6b21-11eb-9b05-65469e2fe5fb.png)

adds
```ballerina
import ballerina/lang.'array;
public function main() {
    'array
}
```

But this can just be
```ballerina
import ballerina/lang.array;
public function main() {
    array
}
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/28155

**Affected Versions:**
slalpha1

**Comment by nadeeshaan** [comment]
Fixed with #28405. Hence closing the issue
