### ISSUE TITLE
Add documentation support for function type descriptor

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#28557]
**Description:**
$title.
```ballerina
# Docs.
# + a - docs for a
public function foo(function a) {
    
}
```

**Comment by shehan360** [comment]
Documentation supports function type descriptors.
Hence, closing the issue.
![Screenshot from 2021-05-19 11-03-46](https://user-images.githubusercontent.com/33398983/118761420-fc718980-b891-11eb-806d-d6123984fdcb.png)
