### ISSUE TITLE
Single quoted variables are missing the quote in the name

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28567]
**Description:**
Consider the following source snippet,

`string 'string = "Hello World!";`

If we get the symbol name, the name does not include the `'`, instead the literal is returned.

**Related Issues**
#18156

**Comment by jclark** [comment]
What's wrong with that? The symbol name is `string`, and you should quote it when printing.

These are the same:

```
string 'string;
string \u{73}tring;
```

These are also the same:

```
int x;
int 'x;
```

Same thing with `x\-y`: the symbol name is `x-y`, but on output it should be converted to `x\-y`.

Same concept as string escaping.

**Comment by sameerajayasoma** [comment]
I guess we need to have a flag in the symbol name in the implementation which indicates that the identifier is a quoted identifier or we can preserve the original quoted identifier.

**Comment by jclark** [comment]
@sameerajayasoma Are you going to preserve that when it is written as `\u{73}string`? You need a list of reserved keywords, then when you have an identifier that is a reserved keyword, you quote it. Just as with a string, you store the result of processing escapes (things starting with a backslash) and then add backslashes when you output as necessary.

**Comment by sanjana** [comment]
Related to #29462

**Comment by pubudu91** [comment]
@nadeeshaan Isn't this the same as #29462? If so, shall we close this as well? With the fix done for #29462, we now get the quoted identifier from the symbols names when looking them up through the Semantic API.

**Comment by nadeeshaan** [comment]
> @nadeeshaan Isn't this the same as #29462? If so, shall we close this as well? With the fix done for #29462, we now get the quoted identifier from the symbols names when looking them up through the Semantic API.

@pubudu91 yes, this is the same one. Let's close this as well.

**Comment by pubudu91** [comment]
Closing this as per the above comment. This was fixed using the approach James suggested above.
