### ISSUE TITLE
Propagate source annotations til BIR

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#28566]
**Description:**
At the moment most of the `source` only annotations are not propagated to the BIR. We only seems to support this for function and type-defs in the BIR, we need to support other attached points too.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
We actually need to add all annotations, right? This is captured in https://github.com/ballerina-platform/ballerina-lang/issues/16379.

**Comment by rdhananjaya** [comment]
Closing in favor of https://github.com/ballerina-platform/ballerina-lang/issues/16379
