### ISSUE TITLE
Project API is not getting updated a file is deleted in workspace

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#28624]
**Description:**
Project API is not getting updated a file is deleted in workspace. This affects code to cloud tooling as it keeps track of all the documents in the project to give diagnostics. 

**Steps to reproduce:**
Create a ballerina project with two .bal files. 
Open the project in vscode debug mode.
Remove one bal file.
Evaluate expression and see the the Project object in lang server.  It should contain old(deleted) bal file as well.

**Affected Versions:**
slalpha1

**Comment by azinneera** [comment]
I checked the Project API implementation on `Module.modify().removeDocument()` and it seems to work fine. @nadeeshaan can there be an issue in the language server in calling the correct API?

**Comment by nadeeshaan** [comment]
This issue is addressed in latest master with #28650. Hence closing the issue. Please reopen if the issue still exists
