### ISSUE TITLE
[Testerina] Skip tests and Group tests show inconsistent output

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#28629]
**Description:**
The following tests :

`SkipTestsTestCase` > `testSkipWhenDependsOnFunctionFails`
`SkipTestsTestCase` > `testSkipWhenAfterGroupsFails`
`GroupingTest` > `testListingOfTestGroups`
`GroupingTest` >`beforeGroupsAfterGroups2`

have very inconsistent output which causes them to fail. This is intermittent, as there are cases when all of them pass, some of them pass, and even cases where all of them fail.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Related to this particular PR : https://github.com/ballerina-platform/ballerina-lang/pull/28581

**Comment by Dilhasha** [comment]
@Ibaqu 

We need to fix the test cases to ensure that a particular order is always preserved. Let's use dependsOn to ensure it for the above test cases and anywhere else it's applicable.

**Comment by Ibaqu** [comment]
@Dilhasha 

I applied `dependsOn` and tried controlling the execution order, but the problem stems from the changes to the semantic model change. Even individually, the tests exhibit unusual behaviour in the output. 

For example, `--list-groups` flag lists the groups in random orders, which makes it difficult to assert the logs. Also, `skip-tests` sometimes doesnt skip certain tests, so the assertion for the passing tests fails. 

We are still investigating this one to see what is the root cause. Note that this only happens with the changes in : https://github.com/ballerina-platform/ballerina-lang/pull/28581.

**Comment by Dilhasha** [comment]
Noted @Ibaqu

**Comment by Dilhasha** [comment]
We will be sorting the lists getting added to test suite to make sure that a certain order is preserved despite the underlying API implementation.
