### ISSUE TITLE
Incorrect formatting with test config annotations

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#28647]
**Description:**
Incorrect formatting for annotation attributes in test config

**Steps to reproduce:**

Consider below code. 

```
import ballerina/io;
import ballerina/test;

// A test function.
@test:Config { 
    groups: ["g1"]
}
function testFunction1() {
    io:println("I'm in test function 1!");
    test:assertTrue(true, msg = "Failed!");
}
```

When formatted it updates to,

```
import ballerina/io;
import ballerina/test;

// A test function.
@test:Config {groups: ["g1"]}
function testFunction1() {
    io:println("I'm in test function 1!");
    test:assertTrue(true, msg = "Failed!");
}

```

note the incorrect formatting of annotation attributes.

**Affected Versions:**
slp Alpha1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
For mapping constructor expression nodes, the convention used by the formatter is to keep blocks containing zero or one field as inline blocks. Therefore, based on the standard formatting conventions, this can be considered as the accepted behavior, and expanding would be more of a personal preference.

Hence, I will be closing this issue.
