### ISSUE TITLE
Generate XML code coverage report using Jacoco in Testerina

### ISSUE THREAD

**Issue by anjaleeps** [ballerina-platform/ballerina-lang#28642]
**Description:**

- [x] Generate XML code coverage report using Jacoco in Testerina 
- [ ] Manipulate the coverage numbers to consider partially covered numbers as fully covered
- [ ] Include coverage information of Java native libraries

**Comment by azinneera** [comment]
#28635 only generates coverage information of bal files. We need to add the information native jars as well. Hence reoepening the same to track.
