### ISSUE TITLE
Semantic API signature of the error type symbol is invalid

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#28654]
**Description:**
Semantic API signature of the error type symbol is invalid. For instance return type symbol of the below is a union of error member types and it generates an invalid signature;

**Function Invocation**
```ballerina
import ballerina/io;
io:openReadableCsvFile("");
```

**Expected**
```ballerina
import ballerina/io;
io:ReadableCSVChannel|io:GenericError|io:ConnectionTimedOutError|io:AccessDeniedError|io:FileNotFoundError|io:TypeMismatchError|io:EofError|io:ConfigurationError openReadableCsvFile = io:openReadableCsvFile("");
```

**Actual / Current**
```ballerina
import ballerina/io;
io:ReadableCSVChannel|GenericError|ConnectionTimedOutError|AccessDeniedError|FileNotFoundError|TypeMismatchError|EofError|ConfigurationError openReadableCsvFile = io:openReadableCsvFile("");
```

Seems like we are not honoring package prefixes since default `getModule()` always return empty in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaErrorTypeSymbol.java#L63

**Affected Versions:**
2.0.0-alpha2

**Comment by sameerajayasoma** [comment]
@daneshk I think we have a plan to introduce a single generic error instead of 10 different errors. Please correct me if I am wrong.

**Comment by shafreenAnfar** [comment]
Yeah. We are planning to have one generic error for each package and then branch out from that to more granular errors.

**Comment by rasika** [comment]
@shafreenAnfar so the plan is to moving away from unions as in https://github.com/ballerina-platform/module-ballerina-io/blob/f7ef7f816aab8a53483a6a24117fbea765d1dc69/io-ballerina/io_error.bal#L39 ?

**Comment by shafreenAnfar** [comment]
Yeah and build the error hierarchy as in https://ballerina.io/learn/by-example/user-defined-error.html.
