### ISSUE TITLE
No semantic error captured

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28660]
**Description:**
Consider the following source snippet.

<img width="404" alt="Screenshot 2021-02-15 at 16 58 23" src="https://user-images.githubusercontent.com/1329674/108042111-672de180-7065-11eb-9a64-a86b3bb9101b.png">

If we write the variable definition, or assignment as follows, then the diagnostic is resolved.

`int test = int:MAX_VALUE;`

Doesn't this means that the snippet shown in the picture should have the `variable assignment required diagnostic`?

**Comment by MaryamZi** [comment]
`int:MAX_VALUE` is a constant which can also be used as a type. For example, the following is valid.

```ballerina
public function main() {
    int:MAX_VALUE x;
}
```

The error here seems to be for a missing identifier in a variable declaration. 

This is the same error we get with a normal type too.

```ballerina
public function main() {
    Foo;
}

type Foo record {||};
```

**Comment by nadeeshaan** [comment]
@MaryamZi true. We were hoping to provide the create variable code action for the constants as well. On a related note, when we consider this particular scenario, we can consider both of the use-cases. In that case, do we have a baseline for giving the priority for the missing identifier diagnostic (And AFAIU that is a parser diagnostic?). If we consider the general usage behaviour, isn't the most common use-case to use the constant as a value itself? Therefore we can provide the prominence for the variable assignment required diagnostic. WDYT?
