### ISSUE TITLE
Symbol at Cursor not captured for the langlib method

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28661]
**Description:**
Consider the attached source snippet,

<img width="404" alt="Screenshot 2021-02-16 at 14 33 59" src="https://user-images.githubusercontent.com/1329674/108042626-0eab1400-7066-11eb-88ba-37e6a1aef8aa.png">

In the above, there are two issues,
1. Cannot get the symbol for the `length` method via the semantic API. It returns empty
2. Does not show the `variable assignment required` diagnostic similar to #28660.

**Comment by pubudu91** [comment]
This is working in master right? Didn't debug to see, but when I hover over `string:length()`, I get the docs of the function and the relevant code actions for this.

**Comment by pubudu91** [comment]
Checked this again in slalpha5. When hovering over `length()`, it shows the docs of the function. Which implies that it was able to get the symbol of `length()`. Closing this since the mentioned issue seems to be fixed.
