### ISSUE TITLE
Configurable support in Ballerina Shell

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#28662]
**Description:**
Ballerina Shell currently supports configurable that are only set in `$userDir/Config.toml`. A better way to support `configurable` is required. A possible approach is to use `Config.toml` at the cwd of the shell and switch to the default location if there is no config file at that location.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
`Area/Shell`

**Suggested Assignees (optional):**

**Comment by HirumalPriyashan** [comment]
@kdsuneraavinash 

> Ballerina Shell currently supports configurable that are only set in `$userDir/Config.toml`

What is meant by `$userDir` in this case? 
I have tried with home directory and it didn't work.

**Comment by kdsuneraavinash** [comment]
It was previously loading from `user.dir` variable, so the issue message is with reference to that. 
https://github.com/ballerina-platform/ballerina-lang/blob/3c05fa7fac8a5ca5adafbde97ff2132388b560ec/ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/invoker/ShellSnippetsInvoker.java#L74

But I guess afterwards it was refactored away. (https://github.com/ballerina-platform/ballerina-lang/commit/8ea8618b4657779b01b7d803baad46f50656717f#)

So now it seems that configurables are completely unsupported, but I might be wrong on that

**Comment by mohanvive** [comment]
Will not be focusing this issue immediately.
