### ISSUE TITLE
Code actions not given for langlib method invocation without initial quote

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#28678]
**Description:**
Consider the bellow image

![Screenshot from 2021-02-16 23-32-59](https://user-images.githubusercontent.com/26381349/108103110-76d21800-70af-11eb-8401-26a7c5f38dbf.png)

Code actions not given for langlib method invocation without initial quote. It works for langlib methods with initial quote.

![Screenshot from 2021-02-16 23-36-13](https://user-images.githubusercontent.com/26381349/108103336-cf091a00-70af-11eb-8838-0373ac3f68a4.png)

**Affected Versions:**
Swan Lake Alpha2

**Comment by nadeeshaan** [comment]
Create variable code action is suggested based on the `variable assignment required` diagnostic, and in this particular case we do not get the particular diagnostic.

**Comment by hasithaa** [comment]
@lochana-chathura, @MaryamZi Could you please check whether this is allowed in the spec. 

```
int:sum()
```

IIRC, this is allowed, because `int` is a built-in prefix.

**Comment by nadeeshaan** [comment]
> @lochana-chathura, @MaryamZi Could you please check whether this is allowed in the spec.
> 
> ```
> int:sum()
> ```
> 
> IIRC, this is allowed, because `int` is a built-in prefix.

@hasithaa this is allowed, since we treat `int` as a predeclared module, and for the API consumers this should be seamlessly visible as yet another module alias

**Comment by MaryamZi** [comment]
> @lochana-chathura, @MaryamZi Could you please check whether this is allowed in the spec.
> 
> ```
> int:sum()
> ```
> 
> IIRC, this is allowed, because `int` is a built-in prefix.

Yeah, for function-call-expr the only requirement is that "The function-reference must refer to a variable with function type.".

```
function-call-expr := function-reference ( arg-list )
function-reference := variable-reference
```

In this scenario variable-reference is a qualified-identifier `qualified-identifier := module-prefix : identifier` and the spec says regarding the module-prefix
> A reserved keyword t that is a predeclared-prefix is predeclared as referring to the lang.t lang library module, but this can be overridden by an import-decl that imports a module using that prefix. A predeclared-prefix can be used as a module-prefix without using a QuotedIdentifier.
