### ISSUE TITLE
No suggestions for langlib imports

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28674]
**Description:**
$title.

![no_suggestion_for_langlib_import](https://user-images.githubusercontent.com/8376983/108084749-990d6b00-709a-11eb-9002-6f21cb77156e.png)

**Affected Versions:**
slalpha2

**Comment by nadeeshaan** [comment]
This is fixed in latest master with #28405. Hence closing the issue
