### ISSUE TITLE
Semantic API signature of an anonymous record type symbol is invalid

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#28682]
**Description:**
Consider the following anonymous record.
```
    record {
      string recField = "";
    } testRec = someFunction();
```
For the create function code action, we need to determine the type the LHS. However, the signature returned by the `typeSymbol.signature()` is ` string recField; anydata...; }` while the expected value is `{| string recField; anydata...; |}`. 

**Steps to reproduce:**
See the above description

**Comment by pubudu91** [comment]
@IMS94 Is this issue still valid in the current master or slalpha2?

**Comment by pubudu91** [comment]
The above produces the following in the current master:
```ballerina
function someFunction() returns record {| string recField; anydata...; |} {
    
    return {};
}
```
The original issue seems resolved right? However, have some concerns regarding the mapping constructor expr generated for the return statement. It's not a valid value for the return type. Shouldn't it have been a valid one, ideally?

**Comment by IMS94** [comment]
@pubudu91 With ##28989, original issue should be fixed. Regarding the mapping constructor, agreed that it is not correct. Need to support setting default values for fields within that in future. We did not put more effort into fixing that now due to other priorities. Can you create an issue so that we can fix this eventually?

**Comment by pubudu91** [comment]
Ack. Will do. Shall we close this then?

**Comment by IMS94** [comment]
@pubudu91 Yes. Will close this.
