### ISSUE TITLE
Code actions for `isolated` constructs

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28681]
**Description:**
Few suggestions for potential code actions for `isolated` constructs, 

- A non-final `isolated` variable can only be accessed within a `lock` statement. 
```ballerina
isolated int i = 1;

function increment() {
    i += 1;
}
```

This fails with `invalid access of an 'isolated' variable outside a 'lock' statement`, and can be fixed using a `lock` statement. Can we provide a code action to do the same?

```ballerina
isolated int i = 1;

function increment() {
    lock {
        i += 1;
    }
}
```

This is also the case for accessing `self` in an `isolated` class.
```ballerina
isolated class Foo {
    private int i = 1;

    function increment() {
        self.i += 1; // error: invalid access of a mutable field of an 'isolated' object outside a 'lock' statement
    }
}
```

- A field in an `isolated` class that is not `final` and/or does not have a type that is a subtype of `readonly` needs to be `private`.

```ballerina
isolated class Foo {
    int i = 1; // invalid non-private mutable field in an 'isolated' object
}
```
 can be fixed by making it a `private` field.

```ballerina
isolated class Foo {
    private int i = 1;
}
```

- An `isolated` function can access variables defined outside the function only if it is either an `isolated` variable or if it is a variable that is both `final` and has a subtype of `readonly`.

Can we provide a code action for at least marking a variable as an `isolated` variable?

```ballerina
int[] arr = [];

isolated function length() returns int {
    return arr.length();
}
```

Can be fixed either by doing
```ballerina
isolated int[] arr = [];

isolated function length() returns int {
    lock {
        return arr.length();
    }
}
```
or
```ballerina
final int[] & readonly arr = [];

isolated function length() returns int {
    return arr.length();
}
```

**Affected Versions:**
slalpha2

**Comment by nipunayf** [comment]
The progress of supporting code actions for isolated constructs is tracked with the following issues:

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/31630
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/42314
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/34431
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/42324
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/42331
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/42333
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/42335

**Comment by nipunayf** [comment]
Closing this issue as all the code actions are added to U10.
