### ISSUE TITLE
Stack trace printed when the program panics contains $anonType$_0

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#28686]
**Description:**
When a ballerina program panics, the stack trace it returns contains something like `$anonType$_0`. The users won't be able to map it with his/her source code.

**Steps to reproduce:**
Add a panic statement to the code and run the program. It will print a stack like the following.

```
error: Test Error
        at janesmith.pkg.0_1_0.$anonType$_0:$get$sayHello(svc.bal:14)        
```

**Affected Versions:**
Ballerina Swan Lake Alpha 1

**Comment by manuranga** [comment]
I think uses will be able to map because `svc.bal:14` part will point to the correct location.
Anyway it's better if we can avoid `$anonType$`, but I don't have a good suggestion on how it should look.
