### ISSUE TITLE
Completion in foreach breaks due to an issue in semantic analyzer

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#28709]
**Description:**
Semantic analyzer throws a `NoSuchElementException` for the particular scenario where we try to get completion for following snippet.

```
foreach var item in <cursor> {

}

```
**Steps:**
Sample Code snippet
(<cursor> is where we suppose to set the cursor. it is not part of the code.)
```
foreach var item in <cursor> {

}

```
1. Move the cursor to <cursor> location in the snippet.
2. ctrl+space on that location.

**Affected Versions:**
slp8

**OS, DB, other environment details and versions:**
macOS

**Comment by nadeeshaan** [comment]
For the given cursor position, the semantic analyzer fails with an exception

**Comment by hasithaa** [comment]
@lochana-chathura This is related to making node transformer resilient work.

**Comment by rdulmina** [comment]
This issue is fixed in master

**Comment by rdulmina** [comment]
Closing with the above comment. Please feel free to reopen if needed.
