### ISSUE TITLE
[LS] Inconsistency in module prefixes  

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28717]
See attached Screenshot. 

![Screenshot 2021-02-17 180627](https://user-images.githubusercontent.com/1356214/108205552-39bb6380-714b-11eb-9fc4-135cddb5deca.png)

It should be `file`, not `file-alpha3`

**Comment by rasika** [comment]
This was due to use of new versioning for modules eg. `1.0.0-alpha3`. Will fix it.
