### ISSUE TITLE
Warning gets thrown with the message compiler plugin crashed

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#28722]
**Description:**
When we have a different type of attribute for a sample data file specified for data mapper compiler extension we get a warning thrown as follows.

`WARNING [github.webhook:(1:1,1:1)] compiler plugin crashed`

**Steps to reproduce:**
- Clone github connector and add a sample data json file named `Assignee_data.json` with the following content.
- Build the connector using the following command
``ballerina build --skip-tests``
- Here we should get a warning as follows.
```
Compiling source
        ballerinax/github:0.99.11
WARNING [github.webhook:(1:1,1:1)] compiler plugin crashed

Creating balo
        target/balo/ballerinax-github-any-0.99.11.balo

Generating executable
        target/bin/github.jar
```

**Affected Versions:**
This was observed with Ballerina Swan Lake Preview 8.1

**OS, DB, other environment details and versions:**
Ubuntu 18.0.4

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by isuruRuhu** [comment]
This is fixed with https://github.com/ballerina-platform/module-ballerinax-datamapper/pull/56
