### ISSUE TITLE
Add an API to  Compiler API to get the configurable fields in a project

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28745]
@pubudu91 We need to support this in semantic API

**Comment by pubudu91** [comment]
Do we need a separate API for this? This can be done using the `moduleSymbols()` API to get the module level constructs and then filtering for var symbols with the `configurable` qualifier.

**Comment by hasithaa** [comment]
I think We need a separate API because We need to get it for a project, including transitive configurable fields.
