### ISSUE TITLE
Config lang lib  and configurable keyword are not showing as suggestions

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#28747]
**Description:**
When I type config in the vscode plugin it does not show any import to lang.config module. But for runtime module suggestions are showed as import ballerina/runtime. 

Once I manually add import ballerina/'lang.config then when I type conf, it shows the config module and its functions.

![image](https://user-images.githubusercontent.com/4163165/108320360-b7817c80-71e8-11eb-8831-e8b83725db2b.png)

Also, there are no suggestions for the configurable keyword as well.

**Test Environment:**
Ubuntu , Sl alpha 2 pack, and vs code plugin

**Comment by warunalakshitha** [comment]
It seems ballerina/lang.runtime also does not suggest if you type runtime

**Comment by nadeeshaan** [comment]
Fixed with #28657. Hence closing the issue
