### ISSUE TITLE
[Doc] [Configurable Variables] Configurable variables with packages

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#28741]
**Description:**
When working with `configurable` variables in packages, we have to group the key-value pairs under the module name when providing configurations in `Config.toml`.

Sample Config.toml:
```
[testbal]
hostName = "192.0.1.2"
port = 9090
```

Here `testBal` is the name of the module.

This information is not there in the current documentation [1]. It would be great if we add this.

[1] https://ballerina.io/learn/by-example/configurable.html

**Comment by HindujaB** [comment]
The related information is now available in a separate learn page from beta1.
https://ballerina.io/learn/user-guide/configurability/providing-values-to-configurable-variables/#providing-values-through-toml-syntax

Hence closing the issue.
