### ISSUE TITLE
LS support stops when there is an syntax error in the 'Settings.toml' file

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#28764]
**Description:**
This happens due to `BLangCompilerException` thrown from `SettingsProcessor`.

**Steps to reproduce:**
1. Add a wrong syntax to `Settings.toml` and save.
```toml
[central]
accesstoken="xxxxxxx3c3-38ff-8d26-cdXXXX"
1234
```
2. Create a new bal project and open with vs code.
3. Check Ballerina output in the vs code. You won't see any diagnostics due to this error.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rasika** [comment]
Does the project-api reads Settings.toml during project load?

**Comment by pramodya1994** [comment]
> Does the project-api reads Settings.toml during project load?

Currently, it does when building the `Environment`, That causes this issue.

**Comment by rasika** [comment]
Okay, then this should be resilient as other toml files from the project-api
