### ISSUE TITLE
[LS] Duplicate document this suggestion 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28777]
![image](https://user-images.githubusercontent.com/1356214/108495962-73b57280-72cf-11eb-9d2d-c0b2c9a22a04.png)

This is observed in SL-alpha2 pack.

**Comment by rasika** [comment]
Any specific way to reproduce this?

**Comment by hasithaa** [comment]
Here are the instructions I execute:

```
D:\test  
λ bal new test256
Created new Ballerina package 'test256' at test256.


D:\test  
λ cd test256\

D:\test\test256  
λ bal add mod1
Added new ballerina module at 'modules\mod1'

D:\test\test256  
λ code . 
```

Once you open this project open `mod1/hello.bal` in the navigation.

**Comment by nadeeshaan** [comment]
Tested with the same sequence and could not reproduce this in the latest master. Hence I'm closing this issue. If the issue can still be reproduced, please reopen
