### ISSUE TITLE
No suggestions for variables defined in match patterns of a match statement

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28780]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
public function main() {
    any v = {x1: 1, b: true};
    match v {
        var  {x1, b: x2} => {
            any|error a = x<cursor>
        }
    }
}
```
![match_vars](https://user-images.githubusercontent.com/8376983/108501246-03aaea80-72d7-11eb-8a49-4a2ea53652fa.png)

```ballerina
public function main() {
    error v = error("err", code = 1001);
    match v {
        error(var x1, code = var x2) => {
            any|error a = x<cursor>
        }
    }
}
```

![match_vars_2](https://user-images.githubusercontent.com/8376983/108501878-ee828b80-72d7-11eb-871c-4e6b4c7639c9.png)

**Affected Versions:**
slalpha2

**Comment by nadeeshaan** [comment]
The issue is, that the semantic API has not implemented the match statement visit.
