### ISSUE TITLE
Migrate homebrew formula from ballerina to bal

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#28800]
**Description:**
Currently we have[ homebrew formula](https://formulae.brew.sh/formula/ballerina) as `ballerina` this needs to changed to `bal` as we have renamed the command after alpha1 release

 - [ ] Migrate the formula
 - [ ] Update the website by including updated formula link

**Comment by keizer619** [comment]
Attempted to switch but seems like `alpha` keyword is not allowed and we need to wait until GA or come up with alternative approach
https://github.com/Homebrew/homebrew-core/pull/72412/files

**Comment by chenrui333** [comment]
@keizer619 I have included the alias and update the formula in [this PR](https://github.com/Homebrew/homebrew-core/pull/80776), can you take a look from your perspective?
