### ISSUE TITLE
Providing sample blocks at the API doc it self

### ISSUE THREAD

**Issue by nuwanbando** [ballerina-platform/ballerina-lang#2882]
In javaocs you get more method details, with bit of usage samples. in ballerina docs for some methods you get very minimal help on usage. For a new developer its bit tricky find out the usage.

We did this in jaggery sometime back - http://jaggeryjs.org/documentation.jag?api=rdb

can we have something similar.

**Comment by afkham** [comment]
Please open issues against specific APIs that have problems. This is too generic, hence closing it.
