### ISSUE TITLE
[Semantic API] Add support for getting the annotation attachment values at source-only attach points

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#28856]
Currently when you get the annotations of a particular symbol, it only gives the symbol(s) of the annotation(s) attached to that construct. Need to improve this to be able to provide the value of the annotation at the attach points.

**Comment by MaryamZi** [comment]
FE changes will be introduced in https://github.com/ballerina-platform/ballerina-lang/pull/35189. The annotation value will be available (as a constant symbol) for all `const` annotations (not only source-only annotations).
