### ISSUE TITLE
Ballerina pushing to the central fails when Package.md is content is too large.

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-lang#28889]
**Description:**
The google sheet connector (in swan lake alpha2) was failed to push to the central and there was no specific reason in the error message. When the content is reduced is pushed to the central successfully. 

Error message :
```ballerina: failed to push the package: 'ballerinax/googleapis_sheets:0.99.6' to the remote repository 'https://api.central.ballerina.io/2.0/registry/packages'```

 Github workflow build:
 https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/runs/1974066553?check_suite_focus=true

**Steps to reproduce:**
1) Add the large content to Package.md  (Eg: there were more than 1774 lines in the Package.md of sheet connector and some helpful images also were there. https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/master/Package.md)

2) Push to the central

**Affected Versions:**
Affected: Google sheet 0.99.6 release in Ballerina - Swan Lake Alpha2

**OS, DB, other environment details and versions:**
Ubuntu, JAVA JDK 11,  Ballerina - Swan Lake Alpha2 latest

**Comment by hemikak** [comment]
Refer: https://github.com/wso2-enterprise/ballerina-registry/issues/666

**Comment by hemikak** [comment]
This is fixed now.
