### ISSUE TITLE
Missing valid diagnostics

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28888]
**Description:**
Consider the following source snippet,

<img width="426" alt="Screenshot 2021-02-25 at 11 15 49" src="https://user-images.githubusercontent.com/1329674/109110044-60d1f080-775c-11eb-80ca-fa486e9b675a.png">

This should provide the diagnostic, `variable assignment required`.

**Affected Versions:**
sl-alpha2 at least

**Comment by mohanvive** [comment]
The below code segment produces the expected diagnostic. In that case we have to escape `string` as `'string`. I think it makes sense to consider it as keyword and recover in that way.

```ballerina
import ballerina/lang.'string as string;

function testFunction() {
    byte[] byteArray1 = [5, 24, 56, 243];
    'string:fromBytes(byteArray1);
}
```
@nadeeshaan WDYT? 
@lochana-chathura do you see any other options?

**Comment by lochana-chathura** [comment]
> The below code segment produces the expected diagnostic. In that case we have to escape `string` as `'string`. I think it makes sense to consider it as keyword and recover in that way (as above) if keyword is not escaped.

@mohanvive Actually `string:fromBytes(byteArray1);` is a valid grammar same as https://github.com/ballerina-platform/ballerina-lang/issues/29328#issuecomment-802123924. We should not go to recovery. It's a bug in the parser. I fixed it locally. Didn't send the PR yet though.

**Comment by mohanvive** [comment]
OK, in that case I'm assigning this issue to you.

**Comment by nadeeshaan** [comment]
> The below code segment produces the expected diagnostic. In that case we have to escape `string` as `'string`. I think it makes sense to consider it as keyword and recover in that way (as above) if keyword is not escaped.
> 
> ```ballerina
> import ballerina/lang.'string as string;
> 
> function testFunction() {
>     byte[] byteArray1 = [5, 24, 56, 243];
>     'string:fromBytes(byteArray1);
> }
> ```
> 
> @nadeeshaan WDYT?
> @lochana-chathura do you see any other options?

IIRC, there was another issue specifically identifying this use case as well. @lochana-chathura let's tag that here as well

**Comment by lochana-chathura** [comment]
> IIRC, there was another issue specifically identifying this use case as well. @lochana-chathura let's tag that here as well

Do you mean https://github.com/ballerina-platform/ballerina-lang/issues/29328#issuecomment-802123924? That issue is already closed.

**Comment by lochana-chathura** [comment]
> IIRC, there was another issue specifically identifying this use case as well. @lochana-chathura let's tag that here as well

#28678. thanks!
