### ISSUE TITLE
[Debugger] Incorrect enum variable values in global variable scope

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#28884]
**Description:**
Enum variables are not visible in debug mode.

**Steps to reproduce:**
- Consider the below code segment:
```
enum Language {
    EN = "English",
    TA = "Tamil",
    SI = "Sinhala"
}

public function main() {
    int x = 5;
}
```
- Run the above program in debug mode by adding a breakpoint at the last line of `main()` method.
- We could observe that the enum variables are not visible in debug mode

![image](https://user-images.githubusercontent.com/11292766/109098892-28c0b280-7748-11eb-8349-2e163ce80cec.png)

**Comment by NipunaRanasinghe** [comment]
I guess this is related with https://github.com/ballerina-platform/ballerina-lang/issues/26139 as the enum values are considered as ballerina constant values during the runtime. Since this should be fixed with the runtime changes which fixes the mentioned issue.
