### ISSUE TITLE
Creating error catalog for runtime errors

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#28891]
**Description:**
1. Create comprehensive list of runtime errors 
2. Identify unused runtime errors

**Steps to reproduce:**

**Affected Versions:**
slalpha2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gabilang** [comment]
An error catalog of ballerina runtime error has been created and shared via `ballerina-dev google group`.  
https://docs.google.com/document/d/1qjQTIMjpedZTGTNVXRg3WggmmjcAS23SkY4yxn_teDQ/edit?usp=sharing

**Comment by HindujaB** [comment]
The error catalog is created in the above doc. 
Hence closing issue.
