### ISSUE TITLE
Implement compiler plugin invocation

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#28898]
**Description:**
Plugin design: https://docs.google.com/presentation/d/1xIS6PGaiAcPe6zL6naVtk3G_zrkKeFWHaIVBg7V4rms/edit#slide=id.gbbbc215f8c_0_10

APIs: https://github.com/sameerajayasoma/ballerina-lang/tree/compiler-plugin/compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This support is added with https://github.com/ballerina-platform/ballerina-lang/pull/29101
