### ISSUE TITLE
Fix suggestions for `#28556`

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#28905]
**Description:**
$title

**Comment by rdhananjaya** [comment]
Also check and fix this `readonly` intersection in error messages. https://github.com/ballerina-platform/ballerina-lang/pull/28556/files/fcb48bcfb663bd11e7c0845ae9480865b17a7ef6#diff-873756d6ae830d824605cd6ee3cb8925b014987a9e9384ed4ddea0c1b33e7ecdR236
