### ISSUE TITLE
Ballerina JSON String Value Invalid String Representation 

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#28906]
Consider the following code:
```ballerina
import ballerina/io;

public function main() {
    json x = "XXXX";
    io:println(x.toJsonString());
}
```
```shell
$ bal run demo2.bal 

Compiling source
	demo2.bal

Running executable

XXXX
```

The output of this should have been "XXXX" (with quotes). The string JSON value's string representation must contain double-quotes. 

If we change the above code's last line to "io:println(x.toJsonString().fromJsonString());" it fails, which proves this situation.

**Comment by lafernando** [comment]
@grainier Why is the priority level of this issue reduced? These are issues in basic functionality that should be fixed immediately.

**Comment by grainier** [comment]
@lafernando Sorry. This happened when we sort blockers for alpha4/5. I'll add blocker again.
