### ISSUE TITLE
runtime:getStackTrace should be isolated

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#28902]
Tracking Issue for https://github.com/ballerina-platform/ballerina-spec/issues/743

**Comment by rdhananjaya** [comment]
This is already isolated in current master https://github.com/ballerina-platform/ballerina-lang/blob/acdad3149a8f595d09ce170462ae75ea2cc0c800/langlib/lang.runtime/src/main/ballerina/runtime.bal#L65
