### ISSUE TITLE
Langlib methods that accept a typedesc don't work with intersection types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#28912]
**Description:**
$title. For example cloneWithType and fromJsonWithType.

On slalpha2 it is not possible to pass an intersection typedesc as the argument - https://github.com/ballerina-platform/ballerina-lang/issues/28910, but with the fix for https://github.com/ballerina-platform/ballerina-lang/issues/28910 the following error was observed at runtime.

**Steps to reproduce:**
```ballerina
type ImmutableIntArray int[] & readonly;

public function main() {
    anydata[] x = [1, 2];
    ImmutableIntArray y = checkpanic x.cloneWithType(ImmutableIntArray);
}
```

Fails at runtime with
```
$ bal run qwe.bal 

Compiling source
        qwe.bal

Running executable

error: {ballerina}ConversionError {"message":"'json[]' value cannot be converted to '(int[] & readonly)'"}
        at ballerina.lang.value.1_0_0:fromJsonWithType(value.bal:214)
           qwe:main(qwe.bal:5)
```

**Affected Versions:**
slalpha2

**Comment by rdhananjaya** [comment]
Enable commented out tests after fixing this https://github.com/ballerina-platform/ballerina-lang/pull/28915/files#diff-31c8e17ece225fb6fd3d1372fa6a7eb313bed03cbb968c6485477f3516f43fbbR205
