### ISSUE TITLE
1..2 is validated for a iterable 

### ISSUE THREAD

**Issue by sajeerAhamed15** [ballerina-platform/ballerina-lang#28928]
**Description:**
![image](https://user-images.githubusercontent.com/26720235/109487139-d534c880-7aa9-11eb-9f88-f43a1370ebbd.png)
The above code snippet doesn't show any diagnostics. Please note `1..2` is not the correct expression. `1...2` is the correct expression.

```
foreach var item in 1..2 {
            
}
```

**Comment by nadeeshaan** [comment]
Checked this in latest master, and the diagnostics are shown without issues. Please verify with the latest and then we can close this

**Comment by NipunaMarcus** [comment]
Sure will do

**Comment by nadeeshaan** [comment]
Closing as per https://github.com/ballerina-platform/ballerina-lang/issues/28928#issuecomment-788575394 and reopen if the issue still exist
