### ISSUE TITLE
Cannot use a Direct Certificate File for Service Listener Configuration

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#28939]
Consider the following code:

Target: Ballerina Swan Lake Alpha 2

```ballerina
import ballerina/http;
import ballerina/websocket;
 
websocket:ListenerConfiguration wsConf = {
  secureSocket: {
      certFile: "/home/laf/cert.pem",
      keyPassword: "pass1"
  }
};

service /ws on new websocket:Listener(8443, config = wsConf) {
 
   resource function get .(http:Request req)
                           returns websocket:Service|
                                   websocket:Error {
       return new WsService();
   }
 
}
 
websocket:Caller[] callers = [];
 
service class WsService {
 
   *websocket:Service;
 
   remote function onTextMessage(websocket:Caller caller,
                                 string text) returns error? {
       check caller->writeTextMessage("Echo: " + text);
   }
 
}
```

I created a self-signed cert using "openssl req -x509 -newkey rsa:4096 -out cert.pem". Trying to run the above service gives the below error:

```bash
bal run demo.bal 

Compiling source
	demo.bal

Running executable

error: {ballerina}TypeCastError {"message":"incompatible types: 'error' cannot be cast to 'websocket:WsConnectionClosureError|websocket:WsInvalidHandshakeError|websocket:WsPayloadTooBigError|websocket:WsProtocolError|websocket:WsConnectionError|websocket:WsInvalidContinuationFrameError|websocket:WsGenericError|websocket:UpgradeError|websocket:WsGenericClientError|websocket:ReadTimedOutError|websocket:HandshakeTimedOut|()'"}
	at ballerina.websocket.1_2_0-alpha4:externInitEndpoint(service_endpoint.bal:127)
	   ballerina.websocket.1_2_0-alpha4.Listener:initEndpoint(service_endpoint.bal:92)
	   ballerina.websocket.1_2_0-alpha4.Listener:init(service_endpoint.bal:88)
	   ballerina.websocket.1_2_0-alpha4.Listener:$init$(service_endpoint.bal:30)
```

**Comment by lafernando** [comment]
The actual error is masked here with a cast error, this must be fixed too.

**Comment by Bhashinee** [comment]
For the listener side to enable SSL via certs and keys, we should provide the configurations `keyFile` and `certFile`. Ballerina supports key files in the format of `pkcs8`. 

The steps to generate necessary keys and certs
1. `openssl req -x509 -newkey rsa:4096 -out cert.pem` 
This will generate a private key and a public certificate. (If you don't see a generated private key file in the location where you run the command, copy-paste the content appearing in the terminal starting with `-----BEGIN ENCRYPTED PRIVATE KEY-----` and ending with `-----END ENCRYPTED PRIVATE KEY-----` to a file named `privkey.pem`. Make sure you don't copy additional spaces/new lines).

2. `openssl pkcs8 -topk8 -nocrypt -in privkey.pem -out pkcs8_key.pem`
Above command will convert the private key into pkcs8 format and save the key in a file named `pkcs8_key.pem`

3. Configure the above-created keys and certs accordingly in the listener and client configurations.

server code
```
import ballerina/http;
import ballerina/websocket;
 
websocket:ListenerConfiguration wsConf = {
  secureSocket: {
      keyFile: "path/to/pkcs8_key.pem",
      certFile: "path/to/cert.pem"
  }
};

service /ws on new websocket:Listener(8443, config = wsConf) {
 
   resource function get .(http:Request req) returns websocket:Service|websocket:Error {
       return new WsService();
   }
 
}
 
websocket:Caller[] callers = [];
 
service class WsService {
 
   *websocket:Service;
 
   remote function onTextMessage(websocket:Caller caller, string text) returns error? {
       check caller->writeTextMessage("Echo: " + text);
   }
 
}
```
client code
```
import ballerina/io;
import ballerina/websocket;

public function main() returns error? {
   websocket:Client wsClient = check new("wss://localhost:8443/ws", config = {
    secureSocket: {
      trustedCertFile: "path/to/cert.pem"
  }});

   check wsClient->writeTextMessage("Text message");

   string textResp = check wsClient->readTextMessage();
   io:println(textResp);
}
```

**Comment by Bhashinee** [comment]
> The actual error is masked here with a cast error, this must be fixed too.

Thanks for reporting. This will be fixed with the following task.
https://github.com/ballerina-platform/ballerina-standard-library/issues/923

**Comment by lafernando** [comment]
Thanks, that worked! Please update the documentation page as well with the above information.

**Comment by Bhashinee** [comment]
Closing the issue as per the above comment.
