### ISSUE TITLE
Lang server tests failures due to function type descriptor implementation

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#28946]
**Description:**
The following tests are broken due to the new function type descriptor syntax.
```
function-type-descriptor :=  [isolated-qual] function

All function values belongs to a function-type-descriptor function; 
a function value belongs to the function-type-descriptor isolated function if and only if it is an isolated function. 
```
broken tests are
```
org.ballerinalang.langserver.completion.FunctionDefinitionTest

(config15.json, function_def)
(config17.json, function_def)
(config16.json, function_def)

org.ballerinalang.langserver.completion.StatementContextTest

(elseif_stmt_ctx_config2.json, statement_context)
(elseif_stmt_ctx_config1.json, statement_context)
```
Please refer https://github.com/ballerina-platform/ballerina-lang/pull/28233#

**Comment by malinthar** [comment]
This is resolved in the latest master
 https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/StatementContextTest.java
https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/FunctionDefinitionTest.java
