### ISSUE TITLE
Error occurs passing a decimal to a ballerina remote function

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#28959]
**Description:**
Tried to pass a `decimal` to a ballerina function as follows.
Ballerina function
```ballerina
remote isolated function close(int? statusCode = 1000, string? reason = (), decimal timeout = 60) returns Error? {}
```

Error
`error: jVM generation is not supported for type decimal`

**Comment by HindujaB** [comment]
This happens for a normal function with defaultable parameter with decimal type. 
```ballerina
public function main() {
     testFunc();
}

function testFunc(decimal timeout = 60) {
}
```
