### ISSUE TITLE
Cannot distinguish constants and Enum members

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28969]
**Description:**
In the current compiler implementation we cannot distinguish enum members from the constants.

Related discussion: https://github.com/ballerina-platform/ballerina-lang/discussions/28967

**Comment by pubudu91** [comment]
As per the discussion in #28967, the plan is to use the `ConstantSymbol` for enum members, but to return `ENUM_MEMBER` as the symbol kind from the `kind()` method. This change should be ok for the beta right?

**Comment by nadeeshaan** [comment]
> As per the discussion in #28967, the plan is to use the `ConstantSymbol` for enum members, but to return `ENUM_MEMBER` as the symbol kind from the `kind()` method. This change should be ok for the beta right?

+1
