### ISSUE TITLE
Compilation error for the parameter name with the special characters

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#28974]
**Description:**
Received following compilation error, when the resource function has function parameter name with a special character.  
output
>Compiling source
        hansani/response:0.1.0
ERROR [main.bal:(6:70,6:70)] missing equal token
ERROR [main.bal:(6:71,6:75)] undefined symbol 'next'
ERROR [main.bal:(8:17,8:21)] undefined symbol 'next'
error: compilation contains errors

**Steps to reproduce:**
ballerina code that can be used to reproduce the issue.
```ballerina
import ballerina/http;

service /hello on new http:Listener(9090) {

   
   resource function get ping(@http:Header {name: "x-next"} string 'x-next) returns string  {
       
      return 'x-next;
          
    }
} 
```

**Affected Versions:**
Swan Lake Alpha2
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
Can we use `'x\-next` as the parameter name? As per the spec, quoted identifiers can have special characters only with a preceding `\` .

**Comment by rdulmina** [comment]
> Can we use `'x\-next` as the parameter name? As per the spec, quoted identifiers can have special characters only with a preceding `\` .

Yes, `'x-next` is invalid syntax for identifier. We can use either `'x\-next ` or `x\-next` as valid syntax

**Comment by lochana-chathura** [comment]
Parsing as,

```bal
import ballerina/http;

service /hello on new http:Listener(9090) {

   
   resource function get ping(@http:Header {name: "x-next"} string 'x MISSING[=] - next) returns string  {
       
      return 'x - next;
          
    }
}
```

which is the correct behavior. Hence, closing this issue.
