### ISSUE TITLE
[Conditional breakpoints] Notify user when they add a non boolean expression for conditional breakpoints

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#28992]
**Description:**
We need to notify the user with a pop message when they add a non-boolean expression for conditional breakpoints.

Similar to shown in the below images:

![image](https://user-images.githubusercontent.com/11292766/109913731-7dc67080-7cd4-11eb-860b-d2ef0b874711.png)

![image](https://user-images.githubusercontent.com/11292766/109913757-87e86f00-7cd4-11eb-8fdb-3e26d67ef424.png)

**Comment by NipunaRanasinghe** [comment]
Closing as we have added a warning in the debug console for non-boolean results in breakpoint expressions.
