### ISSUE TITLE
Enable type definition completion test case

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#28990]
**Description:**
$title.
Type definition completion test is disabled by commit https://github.com/ballerina-platform/ballerina-lang/pull/28233/commits/dc2016f634075600e095d3ad1c527e7f8276bfac

**Comment by malinthar** [comment]
Has been resolved https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/TypeDefinitionTest.java
