### ISSUE TITLE
Migrate langserver project loading logic to support BaloProject Type

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29004]
**Description:**
Currently, langserver specifically supports single-file and build project types. With the upcoming changes for the project-api to support BaloProjects with extracted sources, need to migrate langserver project loading logic to support BaloProject Type.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by IMS94** [comment]
This is fixed by the usage of `ProjectLoader.loadProject(projectRoot, options);` with workspace manager to load projects.
