### ISSUE TITLE
Improve the consistency of breadcrumbs of API docs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29026]
See the following image
<img width="1134" alt="Screenshot 2021-03-05 at 12 53 14" src="https://user-images.githubusercontent.com/6260009/110082198-0ca9ba80-7db3-11eb-8080-cd80402f5742.png">
How packages are illustrated in the breadcrumbs is not consistent with how the other constructs are rendered in the breadcrumbs. For other constructs, we seem to have followed the convention: `Construct-Type > Construct-Name`. For packages, it's `Packages > <pkg_name> Package`. I think it'd be better if we follow the same convention as others for packages: `Packages > http` instead of `Packages > http Package`.

**Comment by shehan360** [comment]
Closing as this issue is fixed now.
