### ISSUE TITLE
Compilation error with dependently-typed functions when the return type is a record type with a dependently-typed field

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29025]
**Description:**
$title. Fails with an "unknown type" error.

**Steps to reproduce:**
```ballerina
function foo(typedesc<any|error> td) returns map<td> = external; // Works.

function bar(typedesc<any|error> td) returns record {| td x; |} = external; // ERROR [test.bal:(3:56,3:58)] unknown type 'td'
```

**Affected Versions:**
slalpha2

**Comment by pubudu91** [comment]
This is the same as #23491. Affects objects and errors as well.

**Comment by MaryamZi** [comment]
> This is the same as #23491. Affects objects and errors as well.

Thanks, missed this.

Closing this issue since it is a duplicate of #23491.
