### ISSUE TITLE
[Testerina] Object mocking throws a validation error on using the when().thenReturn() sequence

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#29037]
**Description:**
For the following sample code, Object mocking throws a validation error

`return value provided does not match the return type of function post()`

mock client :
```
http:Client httpClient = <http:Client>test:mock(http:Client);
test:prepare(httpClient).when("post").thenReturn(getMockResponseInvalidKey());
```

function :
```
function getMockResponseInvalidKey() returns http:Response|http:PayloadType|http:ClientError {}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
This happens for the ballerina distribution built from current changes in master. 

Need to improve the error messages too.

**Comment by Ibaqu** [comment]
This issue arises during the validation of return types in the ObjectMock class.  

For the HTTP module, a change to the API has been made that makes use of `Dependently Typed Signature`. 

```
remote isolated function post(@untainted string path, RequestMessage message, string? mediaType = (),
            map<string|string[]>? headers = (), TargetType targetType = Response) 
            returns @tainted targetType|ClientError = @java:Method
```            

This has a return type signature of `@tainted targetType | ClientError`.  When debugging the value for `MethodType[] 
 attachedFunction.getType().getReturnParameterType()).getMemberTypes()`, this ends up being `null | ClientError` which fails the validation.
