### ISSUE TITLE
Enable `testServiceAnnotAccess1` in AnnotationRuntimeTest

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29033]
**Description:**
$title

**Describe your task(s)**
`testServiceAnnotAccess1` in https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/annotations/AnnotationRuntimeTest.java#L87 is disabled ATM since it was failing. Need to fix and re-enable it. 

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/28699

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
I think we can remove or update this test. 

At https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal#L148 we previously seem to have tested accessing the annotation on the service declaration at https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal#L134 which we can't do now (we can't use annotation access to access the annotations of a service delcaration).

Now when we do `typeof ser` we get the type of https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/resources/test-src/annotations/annot_access.bal#L125 which has no annotations. So we can either remove this test or update it to test the annotations on the service type.
