### ISSUE TITLE
Invalid "pattern will not be matched" error for match of tuple against json

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#29041]
AFAICS this is correct, but it gets a "pattern will not be matched error". This is with slalpha2.

```
import ballerina/io;

function foo(json j) {
   match j {
      var [x, y] => {
        io:println(x, ", ", y);
      }
   }
}

public function main() {
  io:println("Try 1");
  foo([1, 2, 3]);
  io:println("Try 2");
  foo([1, 2]);
}
```

**Comment by jclark** [comment]
Similar problem with records. This also gets "pattern will not be matched":

```
import ballerina/io;

public function main() {
  foo({x: 1, y: "str", "x-abc": "abc", "x-def": "def" });
}

function foo(json j) {
   match j {
      var {x, y, ...rest} => {
        io:println(x, ", ",
                   y, ", ",
                   rest);
      }
   }
}
```

If I changed argument type of `foo` to `any` it works (but changing to `anydata` does not work.)

**Comment by jclark** [comment]
@hasithaa This bug should get a high priority: it makes `match` useless for one of its most important  use cases.

**Comment by hasithaa** [comment]
> @hasithaa This bug should get a high priority: it makes `match` useless for one of its most important use cases.

Ack James,
