### ISSUE TITLE
[Testerina] Passing JSON as a string to the TestRunner needs to be implemented

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#29045]
**Description:**
The test suite information needs to be passed over to the TestRunner in the form of a JSON string. This was implemented in the following commit but removed due to an exception arising in windows : https://github.com/ballerina-platform/ballerina-lang/pull/28853/commits/1eeb85abf57b61a5af778180bb54b581fd0ef2eb

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The test suit json is written to a file and there is no specific requirement for this issue. Hence closing.
