### ISSUE TITLE
Field access completions doesn't work when text ends with 'from' or 'start'

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29060]
**Description:**
Consider the following scenario:

```ballerina
public function main() {
    string sampleStr = "Sample";
    sampleStr.start<cursor>
    sampleStr.from<cursor>
}
```
when the cursor is at one of the 2 positions mentioned above and if we type `Ctrl+C` for completions,
1. `start` - suggestions are wrong
2. `from` - No suggestion

**Steps to reproduce:**
See description

**Affected Versions:**
SLA 2

**Comment by malinthar** [comment]
I could reproduce the issue only for `sampleStr.from`. Seems that the syntax tree is not correct in this case. Following are the syntax trees for both cases.

1. `sampleStr.from`
<img src="https://user-images.githubusercontent.com/35211477/122731646-222aed80-d299-11eb-97ba-c13711241794.png" width=500/>

In this case the parser behavior seems to be incorrect. @IMS94 WDYT?

2. `sampleStr.start`

    Syntax tree
<img src="https://user-images.githubusercontent.com/35211477/122731081-8e592180-d298-11eb-9c57-98a1377b68e0.png" width=500/>

    Completion

<img src="https://user-images.githubusercontent.com/35211477/122731683-29ea9200-d299-11eb-8a3d-dadbf18406fa.png" width=500/>

**Comment by lochana-chathura** [comment]
Related #31311

**Comment by IMS94** [comment]
Case 1 `str.start<cursor>` is working now. Closing this issue since the solution for case 2 is not straightforward and not a major concern. Please reopen if a concern is reported.
