### ISSUE TITLE
`service` attach-point is allowed for `service class` declarations

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#29073]
**Description:**
Annotation attachment poin `service` should only allowed on `service-decl` and `service constructor expression`s.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in #29074, merged with #29119.
