### ISSUE TITLE
Invalid WARNING message when function has a parameter with a hyphen

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#29076]
**Description:**
$Subject

**Steps to reproduce:**
Run the following sample.

```
import ballerina/io;

public function main() {
    error e = error("bad sad");
    foo(e);
}

# + 'error - The error struct to be logged
function foo(error 'error) {
    io:println('error);
}
```

The following WARNING appears.
```
Compiling source
	error.bal
WARNING [error.bal:(8:5,8:11)] no such documentable parameter ''error'
```

**Affected Versions:**
Current master

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/23045

**Comment by KRVPerera** [comment]
Due to the quote is not removed and documentation is parsed as pure text. Need to specially handle this on the document analyzer. 

```
# + 'example - The error struct to be logged
function foo(error 'example) {
    io:println('error);
}
```
