### ISSUE TITLE
Temporary handle worker send CCE at BLangNodeTranformer

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#29089]
**Description:**
$subject.

CCE reported for worker send are as follows.
#24944
#28521
#28424
#28077

**Comment by rdulmina** [comment]
Temporary handled via #29099. shall we keep this issue open until the original issue is fixed?

**Comment by lochana-chathura** [comment]
> Temporary handled via #29099. @lochana-chathura shall we keep this issue open until the original issue is fixed or is there an existing issue for that?

We have #24849. Can close this.
