### ISSUE TITLE
Add Clonable support for worker send

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#29103]
**Description:**
Currently, the compiler supports only `anydata` type as the expression in worker send. Need to support for `value:Clonable` as in the spec.

**Comment by KRVPerera** [comment]
This is already fixed. Sent a PR with a test case

**Comment by KRVPerera** [comment]
This is already fixed by https://github.com/ballerina-platform/ballerina-lang/issues/24338
