### ISSUE TITLE
Improve import module detection logic in Ballerina Shell type signature parser

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#29109]
**Description:**
Import statement parser in shell uses a regex to find required imports. But this logic can be improved to use the moduleIds of the types.

**Suggested Labels (optional):**
`Area/Shell`

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
No need for a visitor. Just need to get the module symbol from the given type symbol and derive the import statement from that. For unions, will need to consider the module symbols of individual member types instead.
