### ISSUE TITLE
Improve error message for uninitialized configurable

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#29156]
**Description:**
```ballerina
configurable string name;
public function main() {
    panic error("good");
}

```
```
ERROR [main.bal:(1:25,1:25)] configurable variable must be initialized
```

**Describe your problem**
Above error can be misleading. User will think variable has to be initialized.

**Describe your solution**
We should have a message that indicate users can put `?` **or** initialize.

**Comment by MaryamZi** [comment]
Fixed in #29273, merged with #29119.
