### ISSUE TITLE
Suggesting foreach code-snippet for iterable variables in same file

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29159]
**Description:**
It would be better for if we can suggest foreach iterator for the iterables such as `lines` in the same file.
```ballerina
class Foo {
  public function print() {
    string[] lines = self.getPrintText();
    <cursor>
  }
}
```

Then we can suggest generate a specially crafted foreach like below(without using `var`);
```ballerina
foreach string line in lines {
      <cursor>
}
```

**Further we can also suggest an indexed loop:**
```ballerina
foreach int i in 0..< lines.length() {
    string line = lines[i];
    <cursor>
}
```

**Affected Versions:**
2.0.0-SLP3-SNAPSHOT

**Comment by IMS94** [comment]
We have added these completions support at `lines.<cursor>`. Therefore closing this.
