### ISSUE TITLE
Equality check doesn't work for tables

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29154]
== and != checks are disallowed for table values. Need to be allowed

**Comment by pcnfernando** [comment]
```ballerina 
type EmployeeTable table<Employee> key(id);

EmployeeTable employeeTab1 = table [
      {id: 1, name: "John", salary: 300.50},
      {id: 2, name: "Bella", salary: 500.50},
      {id: 3, name: "Peter", salary: 750.0}
    ];

    EmployeeTable employeeTab2 = table [
      {id: 1, name: "John", salary: 300.50},
      {id: 2, name: "Bella", salary: 500.50},
      {id: 3, name: "Peter", salary: 750.0}
    ];

    boolean res = employeeTab1 == employeeTab2;
```
Seems this is already allowed. Need to add tests and improve type checking removing obsolete flows in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L3732

**Comment by lasinicl** [comment]
Equality check doesn't seem to work as expected with keyless tables
Consider the following example
```ballerina
    var a = table [{"id":1234, "aa":12},{"id":4567, "aa":12}];
    var b = table [{"id":1234, "aa":12},{"id":4567, "aa":12}];
    boolean x = a == b; // this is false ATM
```
The value of `x` should be `true`
