### ISSUE TITLE
Value match fails for negative integer values

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#29178]
**Description:**
Value match fails with negative integers.

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/lang.'string as strings;

public function main() {
    int x = strings:codePointCompare("hello", "ballerina");
    match x {
        -1 => {
            io:println("foo");
        }
        _ => {
            io:println("bar");
        }
    }
}
```

This will endup with following error message:
`ERROR [hello.bal:(7:9,7:11)] unsupported match pattern`

**Affected Versions:**
Swan Lake Alpha2

**Comment by MaryamZi** [comment]
The spec allows this as a `const-pattern`.

The workaround is to define a constant and use that.

```ballerina
import ballerina/io;
import ballerina/lang.'string as strings;

const NEGATIVE_ONE = -1;

public function main() {
    int x = strings:codePointCompare("hello", "ballerina");
    match x {
        NEGATIVE_ONE => {
            io:println("foo");
        }
        _ => {
            io:println("bar");
        }
    }
}
```

**Comment by MaryamZi** [comment]
Works on slalpha3, we can add tests and close this issue.

**Comment by MaryamZi** [comment]
Tests added in https://github.com/ballerina-platform/ballerina-lang/pull/30143/commits/cff04c96fa0c3bcde9c9ba5082d990d7abd432e0.
