### ISSUE TITLE
Remove unused error for module-level binding pattern support

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29187]
We cannot code a binding pattern in module level. For example, the following code will give compile error

`[int, int] [a, a] = [54, 54];`

The error is 
`'list' binding pattern not yet supported in module variable declaration`

**Comment by MaryamZi** [comment]
@rdulmina, this error is no longer logged with slalpha3-SNAPSHOT right? Shall we check and remove it?

**Comment by rdulmina** [comment]
Support for all module-level typed binding patterns was added via #27824. This error is no longer in master

**Comment by MaryamZi** [comment]
@rdulmina, we still seem to have the BINDING_PATTERN_NOT_YET_SUPPORTED_IN_MODULE_VAR_DECL error code and the relevant entry in compiler.properties though. Shall we remove them?

**Comment by rdulmina** [comment]
> @rdulmina, we still seem to have the BINDING_PATTERN_NOT_YET_SUPPORTED_IN_MODULE_VAR_DECL error code and the relevant entry in compiler.properties though. Shall we remove them?

sure

**Comment by MaryamZi** [comment]
Removed in #29273, merged with #29119.
