### ISSUE TITLE
VS Code Plugin fails to highlight syntax when adding display annotation for a return statement of a function within a class

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-lang#29185]
**Description:**

When adding display annotation for a return statement and there is a json variable just after the method signature, 
the VS Code plugin fails to highlight the syntax. 
This issue happens only for functions within a class.
But still code compiles and works fine.

**Before adding display annotation:**

<img width="751" alt="1" src="https://user-images.githubusercontent.com/32201965/111034260-c4396f00-843a-11eb-89d6-4a9b300c1eb0.png">

**After adding display annotation:**

<img width="857" alt="2" src="https://user-images.githubusercontent.com/32201965/111034267-cb607d00-843a-11eb-961d-0594f4b2aa0c.png">

**Affected Product Version:**
Alpha 2

**OS, DB, other environment details and versions:**   
Mac OS

**Steps to reproduce:**
1. Create a class in ballerina.
2. Add a function which has a return statement.
3. Add a display annotation for the return statement.
4. Add a json variable after the method signature.

Following is a sample code

```
class Bar {
    function k() returns @display {label: "k method"} string {
        json x = {"test": ""};
        return "";
    }
}
```

**For a function not within a class**
<img width="457" alt="6" src="https://user-images.githubusercontent.com/32201965/111035425-88a1a380-8440-11eb-9e4a-9511c5bf5572.png">

**For a function within a class**
<img width="467" alt="4" src="https://user-images.githubusercontent.com/32201965/111034481-e089db80-843b-11eb-8452-903259bc01f2.png">

**Links about the display annotation:**
https://github.com/ballerina-platform/ballerina-spec/issues/681
https://github.com/ballerina-platform/ballerina-lang/pull/27626

**Related issues:**
https://github.com/ballerina-platform/plugin-vscode/issues/282

**Comment by prabushi** [comment]
This is addressed with https://github.com/ballerina-platform/plugin-vscode/issues/282
