### ISSUE TITLE
Record literals are not supported in record binding patterns/ destructuring

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29193]
Consider the following code.
```ballerina

{ name, age } = { name: "Peter", age: 28, country: "Sri Lanka",
                      "occupation": "Software Engineer" };
```

This gives the following error
`
record literal is not supported for record binding pattern`

**Comment by MaryamZi** [comment]
Related issues: https://github.com/ballerina-platform/ballerina-lang/issues/19804, https://github.com/ballerina-platform/ballerina-lang/issues/29166
