### ISSUE TITLE
Non public types are exposed with type-references

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29191]
Spec says that, `"It is an error if the induced set of type-ids includes a non-public type-id from another module"` in Type-Reference section.

I added the following code to a module

```ballerina
public type DDD SSS|int;

class SSS {
    public string name = "";
    public int age = 0;
    private string email = "default@abc.com";
    string address = "No 20, Palm Grove";

    // Private methods can only be called from within the class;
    private function getDomainName() returns string => "abc.com";

    // Methods can update fields.
    // Module-level visible methods can only be called from within the same module.
    function setEmail(string username) {
        self.email = string `${username}@${self.getDomainName()}`;
    }

    // Public methods can be called from anywhere.
    public function getEmail() returns string => self.email;
}
```
Then imported the above module and created another type reference like below

`type EEE foo:DDD|string;`

This compiles successfully, But should give a compile error as it tries to expose a non-public type reference.

**Comment by pubudu91** [comment]
> Spec says that, `"It is an error if the induced set of type-ids includes a non-public type-id from another module"` in Type-Reference section.

This applies for distinct types IINM.

**Comment by gimantha** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/18342
