### ISSUE TITLE
Unused import without module prefix gives a compile error

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29190]
Spec says "_It is an error for a source-part to import a module using a module-prefix and then not to use that module-prefix._"
In current implementation, Compiler gives an error even if we import a module without using a module prefix.

Without module prefix
`import ballerina/io;`

With module prefix
`import ballerina/io as foo;`

**Comment by MaryamZi** [comment]
I guess we'll have to get this clarified in the spec.

```
import-decl := import [org-name /] module-name [as import-prefix] ;
```

When there is no `import-prefix`, the last part of the module-name becomes the module-prefix. IMO, the current behaviour is correct.
