### ISSUE TITLE
Object state variables are not shown in the local variable scope when debugging ballerina object methods

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#29207]
**Description:**
Please refer the code sample below and also note that the state variables of the object is not shown in the `variables` tab in the debug view.

![Screenshot from 2021-03-15 13-43-42](https://user-images.githubusercontent.com/29032600/111122885-aa13a400-8594-11eb-9c27-6deea17530c5.png)

**Steps to reproduce:**

**Affected Versions:**
SL-Alpha3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
I am closing this issue since https://github.com/ballerina-platform/ballerina-lang/pull/30126 fix that. Please reopen if you have further queries on this.
