### ISSUE TITLE
larger integer assignments to float variables cause compiler to crash

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29200]
consider the following code. It works fine.

```ballerina
import ballerina/io;
public function main() {

    float d = 324897481274;
    io:println(d);

}
```

But if you replace the integer with below value, the compiler crashes.

```ballerina
import ballerina/io;
public function main() {

    float d = 324897481274891274891724891274891468192642324242482832382482478238273827328428734287392739274927492749274927492742974294729472947;
    io:println(d);

}
```

But if you use decimal point at the end of the number like below it will compile successfully. 

`float d = 324897481274891274891724891274891468192642324242482832382482478238273827328428734287392739274927492749274927492742974294729472947.0`

**Comment by pcnfernando** [comment]
Too large numbers are already blocked. Getting the below error.
```
ERROR [test.bal:(4:15,4:144)] Integer '324897481274891274891724891274891468192642324242482832382482478238273827328428734287392739274927492749274927492742974294729472947' too large
```

Hence, closing the issue.
