### ISSUE TITLE
[Project API] Project version validation does not allow hyphens in pre release identifiers

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#29203]
**Description:**
$subject, as per the Semvar spec the prerelease identifier following the patch version with the hyphen can include alpha numeric characters and hyphens.

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

Refernce : [Semver spec](https://semver.org)

However, when building a ballerina project following versions are shown as not Semver compatible,
`0.6.0-alpha2-20210311-184300-688245e`

Further trial and error shows only valid version as `0.6.0-alpha`

**Steps to reproduce:**
Build a ballerina project with above version in toml.

**Affected Versions:**
Swanlake-alphax

**Comment by sameerajayasoma** [comment]
Can you post the error or exception trace?

**Comment by sameerajayasoma** [comment]
I used a third-party library to parse pre-release versions here: It supports such versions

I have added several test cases to verify semvar parsing. But I’ve missed to add a pre-release version with hyphens. Just added one test case. 

https://github.com/sameerajayasoma/ballerina-lang/blob/semvar-tests/compiler/ballerina-lang/src/test/java/io/ballerina/projects/SemanticVersionTests.java#L45

**Comment by niveathika** [comment]
<img width="1074" alt="Screenshot 2021-03-16 at 06 11 38" src="https://user-images.githubusercontent.com/27669465/111239194-b04e6280-861e-11eb-8df1-553c5ba0bad2.png">

Compiler justs says "Ballerina.toml invalid version under [package]"

This is based on 2.0.0-alpha5 of ballerina lang. Was this changed recently?

**Comment by sameerajayasoma** [comment]
This happens at the Ballerina.toml schema validation layer. 

https://github.com/ballerina-platform/ballerina-lang/blob/d990b390eef1c6ef632dff0020d479279409fad9/compiler/ballerina-lang/src/main/resources/ballerina-toml-schema.json#L28

@pramodya1994 Please have a look
