### ISSUE TITLE
overriding `toString` suggests two separate `toString` items

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29201]
**Description:**
overriding `toString` suggests two separate `toString` items.

<img width="1021" alt="Screenshot 2021-03-15 at 12 02 51 PM" src="https://user-images.githubusercontent.com/1448489/111112613-716cce00-8586-11eb-8c96-a3bf072fe206.png">

```ballerina
public class Lorry {
    *Vehicle;
    public string color = "red";
    public function toString() returns string {
        return self.color;
    }
}

public class Car {
    public string color = "green";
    *Vehicle;
    public function toString() returns string {
        return self.color;
    }
}

public type Vehicle object {
    public string color;
    public function toString() returns string;
};
```

**Affected Versions:**
2.0.0-SLP3-SNAPSHOT

**Comment by IMS94** [comment]
@nadeeshaan @rasika I had a look at this. Here, the function coming from the langlib is `isolated` while the one you have created is not. In that case, can we consider those 2 functions are equal?

**Comment by nadeeshaan** [comment]
> @nadeeshaan @rasika I had a look at this. Here, the function coming from the langlib is `isolated` while the one you have created is not. In that case, can we consider those 2 functions are equal?

Since this is overriding the toString method, I feel it should suggest only one. Also, this issue comes because we extract the langlibs separately. In order to make this consistent we have to provide a way to access the methods of a symbol - including the langlibs - via the symbol.

@pubudu91 @hasithaa @dulajdilshan thoughts?

**Comment by IMS94** [comment]
@nadeeshaan If we are looking for a temporary fix at LS side, we can modify the `FieldAccessCompletionResolver.getVisibleEntries(TypeSymbol symbol)` method's `OBJECT` case as follows:
```java
       case OBJECT: // add class field access test case as well
                ObjectTypeSymbol objTypeDesc = (ObjectTypeSymbol) rawType;
                visibleEntries.addAll(objTypeDesc.fieldDescriptors().values());
                boolean isClient = SymbolUtil.isClient(objTypeDesc);
                // If the object type desc is a client, then we avoid all the remote methods
                List<MethodSymbol> methodSymbols = objTypeDesc.methods().values().stream()
                        .filter(methodSymbol -> (!isClient || !methodSymbol.qualifiers().contains(Qualifier.REMOTE))
                                && !methodSymbol.qualifiers().contains(Qualifier.RESOURCE))
                        .collect(Collectors.toList());
                visibleEntries.addAll(methodSymbols);

                typeSymbol.langLibMethods().stream()
                        .filter(langLibMethod ->
                                methodSymbols.stream().noneMatch(classMethod -> {
                                   // Equality check needs to be done here.
                                })
                        )
                        .forEach(visibleEntries::add);
                break;
```
This is not ideal since we have a nested iteration (n*m complexity -> will affect if a class has a lot of methods).

**Comment by IMS94** [comment]
According to https://github.com/ballerina-platform/ballerina-spec/issues/543, `lang.value` functions are not available on expressions of type object. Therefore, closing this.Removing langlib suggestions from object field accesses will be tracked under #29870

**Comment by nadeeshaan** [comment]
Closing based on the previous ccomment.
