### ISSUE TITLE
Issue in creating recursive struct type

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#2922]
```
import ballerina.lang.system;

function main (string[] args) {
    Node root = {value:1};
    Node child = {value:2, parent:root};
    root.child = child;
    system:println(root);
}

struct Node {
    int value;
    Node child;
    Node parent;
}
```
If we run the above code, it will result in the following error.

```
error: ballerina.lang.errors:Error
	at println(<native>:0)
	at main(main.bal:7)
```

**Comment by Shan1024** [comment]
Checked how the GO Language handle this situation using the sample program below.

```
package main

import (
	"fmt"
)

func main() {
	root := Node{value: 1}
	child := Node{value: 2, parent: root}
	root.child = child
	fmt.Println(root)
}

type Node struct {
	value  int
	parent Node
	child  Node
}
```
It will give the following error at the compile time.

 `main.go:19: invalid recursive type Node`

**Comment by uthaiyashankar** [comment]
Still we have issues in defining recursive structure. It goes in an infinite loop

**Comment by SupunS** [comment]
This is fixed now.

A test case can be found at: https://github.com/ballerina-platform/ballerina-lang/blob/v0.970.0-beta12/tests/ballerina-test/src/test/java/org/ballerinalang/test/object/ObjectTest.java#L456

Hence closing the issue.
