### ISSUE TITLE
Create function code action for object types generate a function with invalid return type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29224]
Consider the following:
```ballerina
object {
        string name;
        int age;
    } person = foo();
```
When using the create function code action for the above, the following is generated:
```ballerina
function foo() returns object {string name;int age} {
    
    return new();
}
```
The object typedesc in the return type signature is invalid.

**Comment by pubudu91** [comment]
This seems to be addressed in #28714

**Comment by KRVPerera** [comment]
Is the solution actually correct? Isn't the best places to solve this is client-side (eg: Language Server). Because even though fields are not public they are part of the signature.

**Comment by pubudu91** [comment]
> Is the solution actually correct? Isn't the best places to solve this is client-side (eg: Language Server). Because even though fields are not public they are part of the signature.

Which solution? You mean the generated function? Didn't quite get your concern. Is it the object type descriptor in the return type?
