### ISSUE TITLE
Avoid `ballerinai` packages and injected `observability` packages getting added to dependency-graph.json

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#29235]
**Description:**
If a package is built with `observabilityIncluded` set to true, the bala file that gets created contains the observability packages in the generated _dependency-graph.json_ file. We should avoid persisting observability packages and `ballerinai` packages in general in the _dependency-graph.json_.

But observability packages should be added to _dependency-graph.json_ if they are coming as a transitive dependency.

**Comment by pramodya1994** [comment]
Reverted this PR because of https://github.com/ballerina-platform/ballerina-lang/issues/31724
Need to add the fix again with the following changes:
- `observe` package should be skipped if they are injected only.

**Comment by pramodya1994** [comment]
After the new package resolution design, this has changed to add all the dependencies to the `dependency-graph.json` including `ballerinai` and injected observability packages. Hense closing this issue.
