### ISSUE TITLE
[Semantic API] Different behavior between distinct errors and errors

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#29232]
**Description:**

**Describe your problem(s)**
1. Have the following code
```
# Represents an error that occurs when sending an email fails.
public type SendError error;

# Represents an error that occurs when the email store access fails.
public type ReadClientInitError error;

# Represents an error that occurs an email read operation fails.
public type ReadError error;

# Represents email related errors.
public type EmailError SendError|ReadClientInitError|ReadError;


# Represents the operation canceled(typically by the caller) error.
public type CancelledError distinct error;

# Represents unknown error.(e.g. Status value received is unknown)
public type UnKnownError distinct error;

# Represents client specified an invalid argument error.
public type InvalidArgumentError distinct error;

# Represents gRPC related errors.
public type Error CancelledError | UnKnownError | InvalidArgumentError

```
2. Get the symbol of SendError in EmailError. `.getModule()` function on the symbol will return `ballerina/lang.annotations:1.0.0`
3. Get the symbol of CancelledError in Error. `.getModule()` function on the symbol will return the package details of the above bal file.
4. Can we get the same behavior as 3 from 2?

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Unfortunately this is not possible due to #26284. IINM for distinct errors the behaviour is correct because we seem to be creating a new error type for each distinct error type(@rdhananjaya please correct me if I'm wrong).

**Comment by pubudu91** [comment]
Checked with Chiran's PR, this seems to get resolved with it.
