### ISSUE TITLE
Unexpected behavior for closure variables in module level defined with `var`

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#29243]
**Description:**
For closures defined with `var`, the function is identified as undefined sometimes, even if it is defined.

**Steps to reproduce:**
```
function p() returns function () returns () {
    return function() {
           };
}
var f = p();
public function main() {
    f();
}
```
This will cause `undefined function 'f'` error even if `f` is defined.

**Affected Versions:**
At least alpha 2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Let's use https://github.com/ballerina-platform/ballerina-lang/issues/31850 to track this.
