### ISSUE TITLE
Ballerina parser drop extra positional arguments from SyntaxTree

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#29247]
**Description:**
When there are more than two positional arguments provided to error constructor arguments after first 2 are dropped.

Also add type-checking logic for those extra arguments.
https://github.com/ballerina-platform/ballerina-lang/pull/29059/files/781a817288212b1d417d806a7c8fb8cd354879b0#diff-f4fbb6e8ffab357b74e188781ad3f6e3235f8e48b64fba8dfb6ad72bf9ccaf93R2837
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
@rdhananjaya as per the spec, [error-arg-list](https://ballerina.io/ballerina-spec/spec.html#error-arg-list) := `positional-arg [, positional-arg] (, named-arg)*`; maximum of two positional-args are allowed right?. So we perform validation on top of parsed positional arguments at the parser. If there are additional ones we mark them as invalid.

**Comment by rdhananjaya** [comment]
I far as I see we can't just drop user provided construct just because grammar doesn't match it.
error e = error("hi", error("hi"), 1 + "s");
In this case we should also display diagnostics for `1 + "s"`

**Comment by lochana-chathura** [comment]
> I far as I see we can't just drop user provided construct just because grammar doesn't match it.
> error e = error("hi", error("hi"), 1 + "s");
> In this case we should also display diagnostics for `1 + "s"`

Ok. we can log the parser error and add the arg to the list.
