### ISSUE TITLE
Symbol lookup for incomplete query expression misses symbols

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#29262]
**Description:**
$subject.

symbolsForOrderBy assertion in testSymbolLookupInQuery test commented out with c4c93cd in PR #29181 due to some symbols are not visible in that scope. 

when enabling the following top-level construct resides inside the function def can also be taken out.

https://github.com/ballerina-platform/ballerina-lang/blob/02fbdd0e6027e437241e5c1953789fe01faff5eb/tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_lookup_in_query.bal#L40-L44

**Comment by pcnfernando** [comment]
@lochana-chathura can you please add the recovery diff before and after the change if you have

**Comment by lochana-chathura** [comment]
screenshot attached with the diff. 

![Screenshot from 2021-03-13 19-33-08](https://user-images.githubusercontent.com/39232462/111423745-bd4e7d00-8716-11eb-92cc-4d7cce05167b.png)
