### ISSUE TITLE
[Testerina] Restrict the allowed return value types to the user specified type

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#29261]
**Description:**
For functions that accept different types, the return type needs to be restricted to what the user specifies inorder to prevent casting issues. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Closing the issue due to lack of clarity. We have not come across any issues as such in the test framework.
