### ISSUE TITLE
Suggestions for function-typed variables aren't accurate

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29275]
**Description:**
$title.

I was trying to do
```ballerina
function foo() {

}

function () f = foo;
```

but `foo` wasn't suggested.

![function_suggestion_1](https://user-images.githubusercontent.com/8376983/111443756-b1bb8000-872f-11eb-841c-798a6b371b49.png)

**Version:**
slalpha3-SNAPSHOT

**Comment by malinthar** [comment]
Fixed by https://github.com/ballerina-platform/ballerina-lang/pull/30432
