### ISSUE TITLE
Code Generation support for Compiler Extensions

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#29283]
**Description:**
Currently, Compiler Extensions only supports code analyzers. In order to avoid using BlangPackage Nodes in Azure Functions and Lambda Functions modules we need the functionality in the new compiler extensions to add new documents to the `Project`. 
These generated documents will contain intermediate function that gets called every function invocation. that intermediate function then routes the request to the appropriate functions developer has defined.

**Comment by xlight05** [comment]
Blocked by ballerina-platform/ballerina-lang#29283

**Comment by ThisaruGuruge** [comment]
@sameerajayasoma Can we add the generated resources as an annotation to a service? I think it will be easier for the libraries.

**Comment by sameerajayasoma** [comment]
This issue covers your request. https://github.com/ballerina-platform/ballerina-standard-library/issues/2715
