### ISSUE TITLE
Cannot get the type for the node

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#29285]
**Description:**
Consider the following example

```
service / on new http:Listener(8080) {
    resource function get getResource(http:Caller caller, http:Request req) {
        http:Client cc = checkpanic  new("http://localhost:9090");
        cc -><cursor>
    }
}
```

Try to invoke the `type(node)` API in semantic analyzer for `cc` in the line of cursor and it returns empty.

**Affected Versions:**
slp-alpha3-snapshot

**Comment by pubudu91** [comment]
Fixed with #29288 hence closing this.
