### ISSUE TITLE
Compilation stops with unsupported bala file.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29299]
I was testing the following, I have pulled `bash/soap` before testing this.
```
import ballerina/io;
import bash/soap;

public function main() {
    io:println("Hello World!") // Missing semicolon
}
```

This fails with the following error. 
```
Compiling source
        hasitha/bar:0.1.0
error: compilation failed: Invalid bala file: C:\Users\Hasitha\.ballerina\repositories\central.ballerina.io\bala\bash\soap\0.1.0\any
```

But the compilation should continue, This breaks the LS experience.

**Comment by IrushiL** [comment]
Blocked on https://github.com/ballerina-platform/ballerina-lang/issues/31211.

**Comment by pramodya1994** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31310
