### ISSUE TITLE
[LS] Method signatures shown for stdlib function completions are wrong

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29305]
**Description:**
Suppose we have a string variable defined like `string myStr = "sample"` and if we type a dot after the variable as in `myStr.<cursor>`, the suggestions shown for methods are ones coming from the string module which has the string itself as the 1st parameter. Need to fix those suggestions to show without the 1st parameter.

**Steps to reproduce:**
See description

**Affected Versions:**
SLA 2

**Suggested Labels (optional):**
Language Server, Priority/High

**Suggested Assignees (optional):**
IMS94

**Comment by IMS94** [comment]
Same for `array` functions.

**Comment by nadeeshaan** [comment]
This issue has been fixed in latest master. Hence closing the issue
