### ISSUE TITLE
The `Create Variable and Check` code action not working

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#29312]
**Description:**
Consider the following source snippet

```
import ballerina/observe;
import ballerina/http;

service / on new http:Listener(9234) {
    resource function get getResource(http:Caller caller, http:Request req) {
        http:Response res = new;
        observe:startSpan("MyFirstLogic");
    }
}

```

The code action in $title not working for `observe:startSpan("MyFirstLogic");`

Code action should generate the `int startSpan = check observe:startSpan("MyFirstLogic");` and instead generate int|error startSpan = observe:startSpan("MyFirstLogic");

**Affected Versions:**
sl-alpha3-SNAPSHOT at least

**Comment by IMS94** [comment]
@nadeeshaan What's the output you are getting? Does it create a variable at least?

**Comment by nadeeshaan** [comment]
Yes this creates the variable. But does not add the check keyword.

**Comment by pubudu91** [comment]
It doesn't add the `returns error` part to the method signature as well.

**Comment by IMS94** [comment]
I just built the master branch of lang repo and built a distribution. The issue is still reproducible. Seems like #29288 hasn't fixed that.

**Comment by pubudu91** [comment]
> I just built the master branch of lang repo and built a distribution. The issue is still reproducible. Seems like #29288 hasn't fixed that.

Yeah, don't think that was the issue here. Isn't this an issue with the code action itself? I tried the following, and it behaves the same way as above.

```ballerina
class Foo {
    function bar() {
        observe:startSpan("MySpan");
    }
}
```

**Comment by IMS94** [comment]
Yes. It's an issue in the `CodeActionUtil.getEnclosedFunction()` method:
```ballerina
private static Optional<FunctionDefinitionNode> getEnclosedFunction(Node matchedNode) {
        FunctionDefinitionNode functionDefNode = null;
        Node parentNode = matchedNode;
        while (parentNode.kind() != SyntaxKind.FUNCTION_DEFINITION || parentNode.kind() != SyntaxKind.MODULE_PART) {
            parentNode = parentNode.parent();
            if (parentNode == null) {
                break;
            }
            if (parentNode.kind() == SyntaxKind.FUNCTION_DEFINITION &&
                    parentNode.parent() != null && parentNode.parent().kind() == SyntaxKind.MODULE_PART) {
                functionDefNode = (FunctionDefinitionNode) parentNode;
                break;
            }
        }
        return Optional.ofNullable(functionDefNode);
    }
```
It doesn't support functions within class defs. Will updated that.
