### ISSUE TITLE
1.2.14 Release tasks

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#29310]
**Description:**

- [x] Fix Packerina server connection logic (PR https://github.com/ballerina-platform/ballerina-lang/pull/29246)
- [x] Fix Update Tool server connection logic (PR https://github.com/ballerina-platform/ballerina-update-tool/pull/137)
- [x] Migrate ballerina-distribution to support `bal`
- [x] Update website `ballerina` to `bal` change in 1.2.x
- [x] Migrate vscode plugin

**Comment by anupama-pathirage** [comment]
@keizer619 Can we close this now?
