### ISSUE TITLE
Create GitHub Action to automatically update the distribution versions for Observability module version bumps

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#29353]
**Description:**
Since we are currently updating the Observability module versions manually in the distribution repository, we need to implement a way to automatically update the correct versions.

**Describe your task(s)**
We need to create a GitHub action to do this automatically.
Similar GitHub action for Standard Libraries: https://github.com/ballerina-platform/ballerina-standard-library/blob/main/.github/workflows/update_dependencies.yml

**Comment by madushajg** [comment]
We can use a GitHub workflow similar to https://github.com/ballerina-platform/ballerina-standard-library/blob/main/.github/workflows/update_dependencies.yml#L60. 
Ideally, the workflow should be triggered when there is a change in the version at any of the observability repository.
Ex: https://github.com/ballerina-platform/module-ballerinax-jaeger/blob/main/gradle.properties#L16

**Comment by nadundesilva** [comment]
Closing the issue as observability extensions are no longer packaged into the distribution.
