### ISSUE TITLE
Should we avoid adding the empty mapping constructor for annotations?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29355]
**Description:**
With https://github.com/ballerina-platform/ballerina-lang/pull/28938 the mapping constructor expression is now optional in an annotation if the empty mapping constructor is a valid constructor for that type.

```ballerina
annotation record {| int i?; int j = 10; |} x on function;

annotation record {| int i; |} y on function;

@x // valid - same as `@x {}`
@y // invalid, because `i` is a required field
function func() {

}
```

**Describe your problem(s)**
Currently, accepting the suggestion for such an annotation adds the empty mapping constructor expression too.

```ballerina
annotation record {| int i?; int j = 10; |} x on function;

@x<cursor>
function func() {

}
```

![annotation](https://user-images.githubusercontent.com/8376983/111764847-adc36580-88c9-11eb-87e4-429eb113ea9e.png)

**Describe your solution(s)**
Should the default be to not add it instead? If the fields are optional, IMO, it's quite likely that the common case would be to not specify values for them?

**Comment by nadeeshaan** [comment]
@malinthar
