### ISSUE TITLE
Need a way to escape new lines in string templates

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#29352]
**Description:**
Need to escape newlines in string templates.

**Describe your problem(s)**
Please check the following sample:
```ballerina
import ballerina/io;

public function main() {
    string name = "John Smith";
    string company = "ABC";

    string template1 = string `Hello my name is ${name}, and I'm working as a software engineer at ${company}`;
    io:println(template1);

    string template2 = string `Hello my name is ${name}, and I'm working as a 
    software engineer at ${company}`;
    io:println(template2);
}
```
In certain cases such as BBEs, we have hard restrictions to have a specific number of characters. In order to follow that rule, we have to convert string templates like `template1` to `template2`. However, when we do that, it returns an extra new line which is unnecessary.

**Describe your solution(s)**
To solve that, it is better if we can support an escape character, perhaps as described [here](https://stackoverflow.com/questions/46371591/multi-line-template-string-with-no-newline-characters).

**Comment by MaryamZi** [comment]
@BuddhiWathsala, shall we create a spec issue for this?
