### ISSUE TITLE
"Document this" code action doesn't work for resource methods

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29360]
See attached image.

![proj01-1616325730087](https://user-images.githubusercontent.com/1356214/111903103-8fdf3780-8a66-11eb-9be0-810094f69dc3.gif)
Observed with SL-Alpha3.

**Comment by hasithaa** [comment]
@nadeeshaan @imesh @rasika

**Comment by rasika** [comment]
This works for resource methods, you need to click on signature of the resource method. Ideally this shouldn't suggested for the resource function body. Thus, will send a fix for that.
