### ISSUE TITLE
Issues with default Package.md files

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29377]
I have generated the default `Package.md` file using the command. ` bal new proj01 -t lib`. It generates following output. 

```
Prints "Hello World!" with a hello function.
[//]: # (above is the package summary)

# Package Overview
Prints "Hello World!" as the output to the command line using a hello function.
```

This has a summary section. with a comment (Coming from Old implementation), the Comment is getting rendered in doc.

![image](https://user-images.githubusercontent.com/1356214/111965713-0ab65a00-8b1c-11eb-92ef-9bff139a0e6f.png)

**Comment by hemikak** [comment]
This is fixed now. The fix will affect newly pushed packages only.
