### ISSUE TITLE
Ballerina Central is not showing all the available versions of the package ballerinax/kafka 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#29370]
**Description:**
When I search for the Kafka package, all the available versions show up in the search results. When I click the version `ballerinax/kafka:2.1.0-alpha5`, it is redirected to the `2.1.0-alpha3` version page and only `2.0.5` and `2.1.0-alpha3` is shown in the dropdown. 

<img width="1406" alt="Screenshot 2021-03-22 at 11 55 56" src="https://user-images.githubusercontent.com/39673615/111949410-b81e7300-8b06-11eb-9623-30323045cdb0.png">
<img width="621" alt="Screenshot 2021-03-22 at 11 56 07" src="https://user-images.githubusercontent.com/39673615/111949421-ba80cd00-8b06-11eb-9550-e852326b2d82.png">

**Comment by hemikak** [comment]
Fixed with https://github.com/wso2-enterprise/ballerina-registry/pull/816
