### ISSUE TITLE
Code snippets in API Doc comments are not rendered properly in VSCode

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#29390]
**Description:**
please check the screen shot attached herewith,

<img width="913" alt="Screen Shot 2021-03-23 at 10 51 03 AM" src="https://user-images.githubusercontent.com/8402398/112097635-64735e80-8bc6-11eb-9ca3-8146ee7d9fec.png">

**Comment by niveathika** [comment]
<img width="1087" alt="Screenshot 2021-03-23 at 12 14 51" src="https://user-images.githubusercontent.com/27669465/112105376-575c6c80-8bd2-11eb-8ad8-795aac677459.png">

**Comment by prabushi** [comment]
Will be addressed with https://github.com/ballerina-platform/ballerina-lang/issues/29547
