### ISSUE TITLE
Missing reference .gitignore file for Ballerina pacakges 

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-lang#29393]
**Description:**

I'd like to suggest to add Ballerina.gitignore to https://github.com/github/gitignore
Also, the existing PR for Ballerina appears to be out dated: https://github.com/github/gitignore/pull/3014/files

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

Ballerina Swan Lake - Alpha3

**Suggested Assignees (optional):**

**Comment by Ramith-D-Rodrigo** [comment]
New PR for this issue : [Add Ballerina.gitignore](https://github.com/github/gitignore/pull/4431)

**Comment by Ramith-D-Rodrigo** [comment]
@Dilhasha @azinneera FYA, the above-mentioned PR is merged now

**Comment by Dilhasha** [comment]
> @Dilhasha @azinneera FYA, the above-mentioned PR is merged now

Nice. Thanks for following up.
I'll close the issue since it's completed.
