### ISSUE TITLE
Latest ballerinax/stan and ballerinax/nats versions are not shown in Ballerina Central 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#29405]
**Description:**
The latest version of `ballerinax/nats` and `ballerinax/stan` is `1.1.0-alpha5`. But Ballerina central is only showing `1.0.2` for `ballerinax/stan` and `1.1.0-alpha3` for `ballerinax/nats`.

**Comment by hemikak** [comment]
This is fixed now:

<img width="449" alt="Screenshot 2021-03-25 at 7 23 21 PM" src="https://user-images.githubusercontent.com/4398820/112484087-a3104100-8d9f-11eb-8ba2-e7bd89ff9969.png">
<img width="431" alt="Screenshot 2021-03-25 at 7 22 48 PM" src="https://user-images.githubusercontent.com/4398820/112484097-a5729b00-8d9f-11eb-9ea2-9ef18d8a5fc2.png">
