### ISSUE TITLE
http:Client is not appearing in suggestions

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#29404]
**Description:**

![image](https://user-images.githubusercontent.com/26381349/112103444-c5ebfb00-8bcf-11eb-9fa3-ad7838f752b3.png)

Even though I type `http:C` it gives the suggestion as `http:client` not the `http:Client` (note the upercase). Had to manually type `Client`.

**Comment by nadeeshaan** [comment]
This issue has been fixed in latest master from alpha4 onwards. Hence closing the issue
