### ISSUE TITLE
No completions are provided at top level

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#29406]
**Description:**
Consider the following source snippet and at the cursor position, completions are invalid.

```
import ballerina/io;
import ballerina/http;
import ballerina/websocket;

http:C<cursor>

public function main() {
    
}
```

`import ballerina/websocket a<cursor>`

`ws:Client wsCl = check n<cursor>` - No implicit new constructor

```
public function print(map<any> valueMap) returns error? {
    foreach var item in valueMap {
        json j = {};
        anydata cloneWithType = check j.cloneWithType(R<cursor>);
    }
}

type RecordName record {|
    
|};
```
Record Type is not suggested

**Affected Versions:**
sl-alpha3 at least

**Comment by lochana-chathura** [comment]
Related issue #29404
