### ISSUE TITLE
Diagnostics of the Config.toml not visible in VSCode

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29401]
**Description:**
Add following Config.toml file into a multi-module project and try to compile. It will show some diagnostics that won't appear in VSCode.

**Config.toml**
```toml
watch_file_path = "/Users/rasika/Downloads/watch";
```

**Affected Versions:**
2.0.0-SLA3

**Comment by nadeeshaan** [comment]
Related #29512

**Comment by azinneera** [comment]
For diagnostics to be visible in VSCode, the `Config.toml` has to be recognized in the compile-time via the Project API. ATM, Config.toml is not supported as a `Document` in the Project API since it is a runtime-specific file.

**Comment by nadeeshaan** [comment]
Since the `Config.toml` is resolved at runtime, this cannot be handled at the compile time. Hence closing the issue.
