### ISSUE TITLE
Check error is not suggesting when called function returns error? in VSCode

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#29407]
When I called [`fileWriteString`](https://github.com/ballerina-platform/module-ballerina-io/blob/master/io-ballerina/file_string_io.bal#L76) which returns `error?`, VSCode is not suggesting to check the error. Please check the screenshot attached herewith

<img width="1198" alt="Screen Shot 2021-03-23 at 12 15 22 PM" src="https://user-images.githubusercontent.com/8402398/112105115-08aed280-8bd2-11eb-8ca9-9f25d0217926.png">

**Comment by IMS94** [comment]
We now suggest the `Create variable and check error` code action which does exactly this. Therefore, closing.
