### ISSUE TITLE
Function signature looks weird for io:openReadableCsvFile

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#29403]
**Description:**
![Screenshot 2021-03-23 at 12 00 06](https://user-images.githubusercontent.com/1496990/112103677-17948580-8bd0-11eb-86cd-5a2b383a265e.png)

This is because of the union here https://github.com/ballerina-platform/module-ballerina-io/blob/master/io-ballerina/constants.bal#L43

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
That issue is due to #27190. Need to fix #11056 as well to completely fix this.

**Comment by mohanvive** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/29451

**Comment by mohanvive** [comment]
Another related issue: https://github.com/ballerina-platform/ballerina-lang/issues/29416

**Comment by rdhananjaya** [comment]
@mohanvive this issue is about the param type `,| |string fieldSeparator` (marked with a red line in the screenshot)

**Comment by mohanvive** [comment]
> @mohanvive this issue is about the param type `,| |string fieldSeparator` (marked with a red line in the screenshot)

OK, then weird code example is another issue then 😄  . Thanks
