### ISSUE TITLE
Type check is not working for the module variables.

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#29400]
I am getting the following error while compiling the below code, but I am checking the type before passing the variable.

code snippet:
```
import ballerina/crypto;
import ballerina/io;

crypto:PrivateKey? privateKey = ();

public isolated function fileReadString(string path) returns string|error {
    string fileReadStringResult = check io:fileReadString(path);
    if (privateKey is crypto:PrivateKey) {
        byte[]|crypto:Error decryptRsaEcb = crypto:decryptRsaEcb(fileReadStringResult.toBytes(), privateKey);
        if (decryptRsaEcb is byte[]) {
            return string:fromBytes(decryptRsaEcb);
        }
    } else {
        return error("Private Key is not initialized properly");
    }
}
```

error:
```
ERROR [file.bal:(25:98,25:108)] incompatible types: expected '(ballerina/crypto:1.1.0-alpha5:PrivateKey|ballerina/crypto:1.1.0-alpha5:PublicKey)', found 'ballerina/crypto:1.1.0-alpha5:PrivateKey?'
```

VSCode screenshot

<img width="1102" alt="Screen Shot 2021-03-23 at 11 42 37 AM" src="https://user-images.githubusercontent.com/8402398/112101899-71e01700-8bcd-11eb-929a-1a7adf475bd7.png">

**Comment by gimantha** [comment]
You can assign the module level variable to a local variable and do the typecheck to workaround the issue, I think the error shown here is misleading

**Comment by MaryamZi** [comment]
Type narrowing happens only for local variables and parameters. It is not safe to narrow the type of module-level variables such as that in the example since a value of a different type may be assigned to the variable between when the `is` check is done and when the value is used.



> You can assign the module level variable to a local variable and do the typecheck to workaround the issue, I think the error shown here is misleading

Doesn't the error indicate it's of the wrong type?
