### ISSUE TITLE
Create variable and check error not working inside resource func

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29412]
**Description:**
Try to execute `Create Variable and Check Error` for `io:openReadableFile()`.

```ballerina
service / on new http:Listener(8080) {
    resource function get getResource(http:Caller caller, http:Request req) {
        io:openReadableFile("");
    }
}
```
**Affected Versions:**
2.0.0-SLA3

**Comment by IMS94** [comment]
@rasika This too is fixed by #29337. Just tested with master locally. Will be available in SLA4.
