### ISSUE TITLE
Can not bind standard Java classes using bal bindgen command

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-lang#29413]
**Description:**

$Subject when trying to run bal bindgen command.

**Steps to reproduce:**
 run bal bindgen java.utils.ArrayDeque in terminal at ballerina module path

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

```terminal
lahiru@lahirumal:test_hackathon_packaging$ bal bindgen java.utils.ArrayDeque

Note: This is an experimental tool.

Ballerina project detected at: /home/lahiru/wso2/testing/test-hackathon/test_hackathon_packaging

No classpaths were detected.

Generating bindings for: 

Bindings for 'java.utils.ArrayDeque' class could not be generated.
        java.lang.ClassNotFoundException: java.utils.ArrayDeque

```

**Suggested Labels (optional):**

Version/SLAlpha3

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
The fully qualified class name used in this scenario is incorrect. It should be ` java.util.ArrayDeque` and not ` java.utils.ArrayDeque`.

Therefore, this `java.lang.ClassNotFoundException` error is expected. 

Bindings for the correct class name were generated as expected when tested with `Ballerina Swan Lake Beta 2`, please reopen this issue if the issue still exists.
