### ISSUE TITLE
Code Samples Shown when Hovering is Jumbled

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#29416]
**Description:**
When hovering over a function definition that has a sample code snippet, shows a jumbled text.

![Screenshot 2021-03-23 at 12 49 39](https://user-images.githubusercontent.com/40016057/112108879-d2c01d00-8bd6-11eb-8c37-70d77ff8b7c8.png)

**Comment by nadeeshaan** [comment]
Duplicate of #29547. Hence closing the issue
