### ISSUE TITLE
Better to have a direct way to find the length of a JSON array

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#29415]
**Description:**
Consider the following scenario. 
```
import ballerina/http;

http:Client myEndpoint = check new ("https://api.github.com");
var response= myEndpoint->get("/foo/bar");

if responseGit is http:Response {
    var jsonPayload = response.getJsonPayload();
    if jsonPayload is json {
        if jsonPayload is json[] {
        int count = jsonPayload.length();
        }
    }
}
```

As you can see there needs to be an additional check to see if the object is a `json[]` before getting its length. IMO, it would be better if this step could be bypassed.

Also there arent any documentation related to JSON operations in [API docs](https://ballerina.io/learn/api-docs/ballerina/#/). The [xmldata](https://github.com/ballerina-platform/module-ballerina-xmldata) module only has 2 APIs (To convert JSON to XML and vice versa).

**Comment by MaryamZi** [comment]
> Consider the following JSON array.
> 
> ```
> json j = [{"a": "b"}, {"c": 2}];
> ```
> 
> There is no way to find the length of this JSON array j. IMO there should be a straightforward way to achieve this since it is a basic and a common requirement.
> 

A variable of type `json` can hold not only JSON arrays and objects but also numeric, string, and boolean values for which the concept of length does not apply. So you cannot directly call `.length()` on a `json`-typed variable. You need to use the type test first to check if `j` is a `json[]` and then call `.length()`.

> Also there arent any documentation related to JSON operations in [API docs](https://ballerina.io/learn/api-docs/ballerina/#/). The [xmldata](https://github.com/ballerina-platform/module-ballerina-xmldata) module only has 2 APIs (To convert JSON to XML and vice versa).

The language examples for JSON are available as BBEs. From a language perspective, the JSON related operations are available across the lang library (lang.map for JSON objects, lang.array for JSON arrays, lang.value for specific lang library methods allowed with `json`).

**Comment by MadhukaHarith92** [comment]
> A variable of type `json` can hold not only JSON arrays and objects but also numeric, string, and boolean values for which the concept of length does not apply. So you cannot directly call `.length()` on a `json`-typed variable. You need to use the type test first to check if `j` is a `json[]` and then call `.length()`.

Thanks for the response. However, irrespective of the data type it holds, a variable of `json` could be either a JSON element or a JSON array, isn't it? For example.
```
json j1 = {"a": "apple"}
json j2 = {"b": 12}
json j3 = {"c": true}
json j4 = [{"a": "apple"}, {"b": 12}, {"c": true}]
```
It would reduce an additional step if `j1.length() = 1` and `j4.length() = 2`. But I presume that it might not be permitted from the language spec to perform `.length()` on a `json` element.

**Comment by MaryamZi** [comment]
> > A variable of type `json` can hold not only JSON arrays and objects but also numeric, string, and boolean values for which the concept of length does not apply. So you cannot directly call `.length()` on a `json`-typed variable. You need to use the type test first to check if `j` is a `json[]` and then call `.length()`.
> 
> Thanks for the explanation. However, irrespective of the data type it holds, a variable of `json` could be either a JSON element or a JSON array, isn't it? For example.
> 
> ```
> json j1 = {"a": "apple"}
> json j2 = {"b": 12}
> json j3 = {"c": true}
> json j4 = [{"a": "apple"}, {"b": 12}, {"c": true}]
> ```
> 

In addition to these a `json`-typed variable can also hold numeric, string, and boolean values and for numeric and boolean values length doesn't quite make sense.

```ballerina
json j5 = 1;
json j6 = true;
```

**Comment by MadhukaHarith92** [comment]
Closing since this is the correct behavior according to the spec.
