### ISSUE TITLE
@test:Config is not suggested in auto completion

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#29420]
**Description:**
$subject
![Screenshot from 2021-03-23 11-35-47](https://user-images.githubusercontent.com/28644893/112101563-e070a500-8bcc-11eb-8058-eb221fc23acd.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
@lochana-chathura @rdulmina at the given cursor position, the node is not identified as the `AnnotationNode`. What's possibility of handling that?

**Comment by lochana-chathura** [comment]
> @lochana-chathura @rdulmina at the given cursor position, the node is not identified as the `AnnotationNode`. What's the possibility of handling that?

IIRC, the conclusion on the last conversation we had back then, was to have a well-defined algorithm to go through invalid token minutiae as well. But, now that we sort of flattening the invalid node when attaching it as an invalid minutiae, I doubt if it is possible.

This problem exists only at the EOF. As a solution, we can attach the annotations to a top-level construct when forming ST. The simplest top-level construct is `module-no-init-var-decl`. 

With that,
```bal
@test:Co
```
will be recovered as,
```bal
@test:Co
MISSING[Identifer] MISSING[Identifer] MISSING[;]
```

Would that solve the problem @nadeeshaan?

**Comment by rdulmina** [comment]
> > @lochana-chathura @rdulmina at the given cursor position, the node is not identified as the `AnnotationNode`. What's the possibility of handling that?
> 
> IIRC, the conclusion on the last conversation we had back then, was to have a well-defined algorithm to go through invalid token minutiae as well. But, now that we sort of flattening the invalid node when attaching it as an invalid minutiae, I doubt if it is possible.
> 
> This problem exists only at the EOF. As a solution, we can attach the annotations to a top-level construct when forming ST. The simplest top-level construct is `module-no-init-var-decl`.
> 
> With that,
> 
> ```ballerina
> @test:Co
> ```
> 
> will be recovered as,
> 
> ```ballerina
> @test:Co
> MISSING[Identifer] MISSING[Identifer] MISSING[;]
> ```
> 
> Would that solve the problem @nadeeshaan?

+1 for the approach. We should support this in parser rather than invalidating the annotations

**Comment by nadeeshaan** [comment]
> > @lochana-chathura @rdulmina at the given cursor position, the node is not identified as the `AnnotationNode`. What's the possibility of handling that?
> 
> IIRC, the conclusion on the last conversation we had back then, was to have a well-defined algorithm to go through invalid token minutiae as well. But, now that we sort of flattening the invalid node when attaching it as an invalid minutiae, I doubt if it is possible.
> 
> This problem exists only at the EOF. As a solution, we can attach the annotations to a top-level construct when forming ST. The simplest top-level construct is `module-no-init-var-decl`.
> 
> With that,
> 
> ```ballerina
> @test:Co
> ```
> 
> will be recovered as,
> 
> ```ballerina
> @test:Co
> MISSING[Identifer] MISSING[Identifer] MISSING[;]
> ```
> 
> Would that solve the problem @nadeeshaan?

When we get the annotation node, we extract the parent of it, and based on the parent kind we filter the annotations. In this particular case, the parent would be `module-no-init-var-decl`. In such case, we should be able to do a validation against the parent and ignore. If we are going with this approach, I would say that we should make sure the parent is set with the `isMissing` to true. If so, +1 for this approach.

Given the current behaviour we shouldn't drop the annotations and we can either attach it to an existing top level node or introduce a dummy node.

**Comment by lochana-chathura** [comment]
>If we are going with this approach, I would say that we should make sure the parent is set with the `isMissing` to true.

@nadeeshaan this requires a small change in syntax API implementation. currently `isMissing` can only be true for the tokens. not for the nodes.

How about using diagnostics to make the decision. 
e.g. checking if  "Missing annotation attachment node" present in diagnostics? Similar to what we do in creating variable code action

**Comment by nadeeshaan** [comment]
> > If we are going with this approach, I would say that we should make sure the parent is set with the `isMissing` to true.
> 
> @nadeeshaan this requires a small change in syntax API implementation. currently `isMissing` can only be true for the tokens. not for the nodes.
> 
> How about using diagnostics to make the decision.
> e.g. checking if "Missing annotation attachment node" present in diagnostics? Similar to what we do in creating variable code action

@lochana-chathura that will not work for the completion engine. Since we rely upon the nodes.

**Comment by lochana-chathura** [comment]
> @lochana-chathura current implementation does not consider the diagnostics attached to the nodes. If this is the only option, at the moment we will check whether we can alter the resolving at LS.

What `isMissing()` does is simply return `instanceof STMissingToken;`. I was thinking, if we can modify this to support nodes as well. i.e. When all tokens that belong to the node are missing tokens `node.isMissing()` will be true. But, doing so does not solve the problem here as metadata is a part of the created `module-var-decl` node. 

In conclusion, this is not feasible to address via syntax API.

**Comment by IMS94** [comment]
Blocked by #31356
