### ISSUE TITLE
1st symbol of re-declared will not get diagnosed as a re-declared symbol.

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#29429]
**Description:**
$title. Follow the below steps to re-produce. Note: this can happen due to the compilation order. However, it's nice to highlight all the re-declared symbols or last declared symbol.

**Affected Product Version:**
alpha3

**OS, DB, other environment details and versions:**    
n/a

**Steps to reproduce:**
1. create a module.
2. add `y.bal` with a `main()` method inside.
3. add `x.bal` with a `main()` method inside.
4. at this point `x.bal`s main method will get highlighted as a re-declared symbol.
5. now format code.
6. after that, `y.bal`s main method will get highlighted as a re-declared symbol (not `x.bal`s main method anymore).

**Related Issues:**
n/a

**Comment by KavinduZoysa** [comment]
I tried this in `v3.3.11` and always it shows this error at `y.bal`
