### ISSUE TITLE
AIDataMapperCodeAction failed for incomplete check expression

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#29421]
**Description:**

![image](https://user-images.githubusercontent.com/26381349/112108284-ffc00000-8bd5-11eb-82bc-0b18f08e39e8.png)

AIDataMapperCodeAction failed with IllegalStateException

**Comment by isuruRuhu** [comment]
Issue is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/29668

**Comment by nadeeshaan** [comment]
Closing the issue based on the last comment
