### ISSUE TITLE
[Language Server] Hover view is cluttered when the documentation has code samples

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#29425]
**Description:**
Please refer the below scenario and note that the hover view is cluttered when the documentation has code samples.
![Screenshot from 2021-03-23 13-27-33](https://user-images.githubusercontent.com/29032600/112113323-ac04e500-8bdc-11eb-8bdd-e69e92343a27.png)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
We haven't identified this issue in the recent past after the fix introduced by Compiler FE team. Hence, closing the issue.
