### ISSUE TITLE
Invalid or irrelevant code action suggestion 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29428]
**Description:**
For the code below, it suggests an irrelevant code action to type cast it. 
<img width="1218" alt="Screenshot 2021-03-23 at 13 40 11" src="https://user-images.githubusercontent.com/690559/112114020-917f3b80-8bdd-11eb-9734-d79826270478.png">

Applied code action
<img width="344" alt="Screenshot 2021-03-23 at 13 42 51" src="https://user-images.githubusercontent.com/690559/112114140-b673ae80-8bdd-11eb-9978-275f0338740d.png">

<img width="427" alt="Screenshot 2021-03-23 at 13 42 58" src="https://user-images.githubusercontent.com/690559/112114162-bbd0f900-8bdd-11eb-8544-7c6bffcc83c4.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Currently the typecast code action is generated based on the diagnostic message. In order to support the contextual type cast we need an API via the SemanticAPI/ Compiler to check the assignability

**Comment by pubudu91** [comment]
Related discussion https://github.com/ballerina-platform/ballerina-lang/discussions/29009

**Comment by IMS94** [comment]
In this scenario, we can update the `TypeCastCodeAction` to check if the RHS side has an error subtype union. If yes, it will not show any type cast code action. Then we can implement #29582, which will propose a `check` instead. WDYT?

**Comment by nadeeshaan** [comment]
> In this scenario, we can update the `TypeCastCodeAction` to check if the RHS side has an error subtype union. If yes, it will not show any type cast code action. Then we can implement #29582, which will propose a `check` instead. WDYT?

+1 for this approach. That will resolve the hassle. Let's proceed with that

**Comment by IMS94** [comment]
#29650 will fix this. But the discussed alternative approach requires to be implemented for #29582
