### ISSUE TITLE
Unrelated error with unknown file appearing in "Problems" tab

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29437]
**Description:**
While trying out the below code, I am observing an unrelated error with unknown file appearing in "Problems" tab.
<img width="433" alt="Screenshot 2021-03-23 at 14 01 26" src="https://user-images.githubusercontent.com/690559/112116417-47e42000-8be0-11eb-8df8-73d175c20456.png">

Unrelated error is : function 'onMessage' can be marked as an 'isolated' function

<img width="634" alt="Screenshot 2021-03-23 at 13 58 39" src="https://user-images.githubusercontent.com/690559/112116431-4ca8d400-8be0-11eb-883b-4e23d265f19b.png">

Unknown file is types.bal 
<img width="521" alt="Screenshot 2021-03-23 at 13 58 46" src="https://user-images.githubusercontent.com/690559/112116448-4fa3c480-8be0-11eb-9b6f-755dccfb7801.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@Kishanthan  does this file exist on the disk?

**Comment by IMS94** [comment]
Relates to #29994

**Comment by nadeeshaan** [comment]
This issue has been fixed in sl-alpha5. Hence closing the issue
