### ISSUE TITLE
No suggestion to add error? return to enclosing function

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29431]
**Description:**
When adding `check` expr for an invocation, there is no suggestion from LS to update enclosing method signature to have error? return type.

<img width="1176" alt="Screenshot 2021-03-23 at 13 46 37" src="https://user-images.githubusercontent.com/690559/112114753-6ba66680-8bde-11eb-8fef-088486ea780b.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment]
If we had 
```
json fileReadJson = io:fileReadJson("");
```
VSCode would suggest `Add 'check' error` code action which will add the `check` and the error return as well. This specific code action is still not available.

**Comment by sameerajayasoma** [comment]
@IMS94 I don't get the `add check` suggestion for your example in SL Beta4. 

I tried with the HTTP client as well. 

<img width="808" alt="Screen Shot 2021-11-17 at 3 18 10 PM" src="https://user-images.githubusercontent.com/2637328/142298819-d8356b26-e4c8-4be1-86bf-5a0d6fce1123.png">

**Comment by sameerajayasoma** [comment]
Btw, we shouldn't suggest a typecast here. Such casts lead to panics.  See the following code after executing the action.
<img width="890" alt="Screen Shot 2021-11-17 at 3 18 27 PM" src="https://user-images.githubusercontent.com/2637328/142299097-e1d6451d-9448-463f-96d8-de400a732b6d.png">

We should remove the typecast suggestion completely.

**Comment by hasithaa** [comment]
In some cases Cast is useful, but not in this case and it shouldn't be the first suggestion.

**Comment by IMS94** [comment]
> @IMS94 I don't get the `add check` suggestion for your example in SL Beta4.
> 
> I tried with the HTTP client as well.
> 
> <img alt="Screen Shot 2021-11-17 at 3 18 10 PM" width="808" src="https://user-images.githubusercontent.com/2637328/142298819-d8356b26-e4c8-4be1-86bf-5a0d6fce1123.png">

@sameerajayasoma Seems like it's not shown. Need to have look. `Add check` code action isn't suggested for cases like `string[][] lines = io:fileReadCsv("");` as well.

**Comment by IMS94** [comment]
Just checked this on master. `Add 'check' error` code action is working for both cases. See below:
![add_check_codeaction](https://user-images.githubusercontent.com/11285165/143439873-da412e0c-d734-4c89-b04a-d3cb651ee516.gif)

Up to SL Beta 4 this code action doesn't work when the returned union type has user defined error types instead of `error` itself. This is fixed in master. Will be available in Beta 6.

**Comment by IMS94** [comment]
> Btw, we shouldn't suggest a typecast here. Such casts lead to panics. See the following code after executing the action. <img alt="Screen Shot 2021-11-17 at 3 18 27 PM" width="890" src="https://user-images.githubusercontent.com/2637328/142299097-e1d6451d-9448-463f-96d8-de400a732b6d.png">
> 
> We should remove the typecast suggestion completely.

Type cast code action is no longer shown here. See the gif above.

**Comment by IMS94** [comment]
The case of not suggesting the `Change return type to error?` inside a `main()` function is now resolved. Therefore closing this issue.
![Screenshot from 2023-02-02 08-14-54](https://user-images.githubusercontent.com/11285165/216218608-c67de248-e0c7-4981-a285-741c4bd2657f.png)
