### ISSUE TITLE
nats:Error is not shown in suggestion

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29435]
**Description:**
Check the image below. I did not get the completion for nats:Error and had to manually type the whole thing. 

<img width="1006" alt="Screenshot 2021-03-23 at 13 54 36" src="https://user-images.githubusercontent.com/690559/112115740-89c09680-8bdf-11eb-86cd-79c4a1f4ca85.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@lochana-chathura @rdulmina Consider the following code segment
`m:Type|m:<cursor> test = new();`
In this scenario, the node at the cursor is not identified as `QualifiedNameReference`. In order to provide the completions at this point, we should identify the `QualifiedNameReference` context.

**Comment by rdulmina** [comment]
> @lochana-chathura @rdulmina Consider the following code segment
> `m:Type|m:<cursor> test = new();`
> In this scenario, the node at the cursor is not identified as `QualifiedNameReference`. In order to provide the completions at this point, we should identify the `QualifiedNameReference` context.

Will have a look
