### ISSUE TITLE
Goto def not working for std lib functions

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29445]
**Description:**
![goto_def_error](https://user-images.githubusercontent.com/15815199/112122046-e1fa9700-8be5-11eb-9ef4-0ca3838167ff.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
Duplicate of #29526. Hence closing the issue
