### ISSUE TITLE
"cannot resolve module" doesn't go away even when you can build successfully

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-lang#29447]
**Description:**

In the following GIG the red squiggly lines are for : `cannot resolve module 'ballerinax/rabbitmq'(BCE2003)`
![Peek 2021-03-23 14-17](https://user-images.githubusercontent.com/6542630/112119637-90510d00-8be3-11eb-981e-477d06dce9e7.gif)
In the screen capture you can see that I am resolving the dependency by running `bal pull` and then doing a build via the VS code plugin. However the "cannot resolve module" doesn't get resolved till I make a code change.

Expectation: The "cannot resolve module" error to go away after the build via the plugin is successful. 

**Suggested Labels:**

Version/SLAlpha3

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
`bal pull` command is not sync with the IDE. If you pull a module, you have to reload the editor window to take them effect

**Comment by ruvi-d** [comment]
> `bal pull` command is not sync with the IDE. If you pull a module, you have to reload the editor window to take them effect

@nadeeshaan : you might be able to notice that I ran the Ballerina build command from the IDE. I was expecting that that would be enough for the vscode plugin to pick up the change.

**Comment by nadeeshaan** [comment]
@ruvi-d Language server's project reloading is based on the file events sent from the client. Which are not synced with the terminal commands. Language server protocol depends on the text document related events. In order to support this, we will have to implement a watcher from the server side, which is not planned at the moment.

**Comment by ruvi-d** [comment]
@nadeeshaan : just to clarify, it wasn't a terminal command that I ran. It was `ctrl+shift+p` -> `Ballerina: Build` from VScode

**Comment by nadeeshaan** [comment]
@ruvi-d that is still the same. Commands are independent from the Language Server at the moment

**Comment by IMS94** [comment]
One alternative to this will be introducing #30757

**Comment by nadeeshaan** [comment]
This is facilitated with the pull module code action. Hence closing the issue.
