### ISSUE TITLE
When the close brace is missing in a function the suggestions won't work

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29449]
**Description:**
$title
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19838787/112122003-d9a25c00-8be5-11eb-98df-ccca0fd9f420.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
@lochana-chathura in this case, parser cannot identify the context

**Comment by lochana-chathura** [comment]
```bal
function sendMail() {
    string host = "127.0.0.1";
    string username = "user1";
    string password = "abc";
    string subject = "Secret Message";
    str //<cursor>
}
```
Above is parsed as,
```bal
function sendMail() {
    string host = "127.0.0.1";
    string username = "user1";
    string password = "abc";
    string subject = "Secret Message";
    str MISSING[] MISSING[;] // Recover as a local varaible decl.
}
```

Which I think is the expected behavior?
