### ISSUE TITLE
Formatting issue in code suggestion message - regex stdlib

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#29451]
**Description:**
It seems like, there are some formatting issue in code suggestion message. 

**Steps to reproduce:**

Refer, below screenshot.
<img width="782" alt="Screenshot 2021-03-23 at 15 06 38" src="https://user-images.githubusercontent.com/7523274/112125871-e3c65980-8be9-11eb-81db-f0764be8a09d.png">

**Comment by mohanvive** [comment]
Related issue: #29416

**Comment by mohanvive** [comment]
Another related issue https://github.com/ballerina-platform/ballerina-lang/issues/29425

**Comment by mohanvive** [comment]
Another related issue https://github.com/ballerina-platform/ballerina-lang/issues/29547

**Comment by nadeeshaan** [comment]
Closing since duplicated
