### ISSUE TITLE
Code samples in API docs are shown in an unattractive manner

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#29457]
**Description:**
When you hover over a util function where there is a code sample given in the API docs it shows in the vs code as follows,
![apidocs](https://user-images.githubusercontent.com/11239305/112129348-584ec780-8bed-11eb-82b8-8acbf6a7c4a1.png)

And when we look for suggestions also it shows like this
![apidocs2](https://user-images.githubusercontent.com/11239305/112129439-6d2b5b00-8bed-11eb-97ef-1e87ae234615.png)

**Comment by prabushi** [comment]
Will be addressed with https://github.com/ballerina-platform/ballerina-lang/issues/29547
