### ISSUE TITLE
Ordering of suggestions

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29458]
**Description:**
If I am typing `str<cursor_pos>` I would expect string to be the first entry in the suggestions as it is used mostly, but currently it is not the case.

<img width="558" alt="Screenshot 2021-03-23 at 15 45 54" src="https://user-images.githubusercontent.com/690559/112131005-0f980e00-8bef-11eb-94ca-3679871e1e3b.png">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
In the current implementation, we prioritize the type snippets over the builtin types. We haven't done heuristic/ usage-based ordering of the completion items  yet.

**Comment by IMS94** [comment]
@gayalkuruppu did you report a similar issue recently?

**Comment by malinthar** [comment]
Closing as fixed 
![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/666493a0-8acd-4506-b491-34eb0705748d)
