### ISSUE TITLE
[LS Code Actions] "Document All" code action does not work for ballerina class method definitions

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#29461]
**Description:**
Please refer the session below and note that the [LS Code Actions] "Document All" code action does not add documentation for the ballerina class/object method definition.
![Peek 2021-03-23 15-59](https://user-images.githubusercontent.com/29032600/112132980-36574400-8bf1-11eb-9d80-89e0266843e6.gif)

**Steps to reproduce:**
Use the sample code below and invoke "Document All" code action on top of the `partition` method.

```ballerina
import ballerina/io;

# Description  
class Partitioner {

   
    # Description
    #
    # + criterias - Parameter Description  
    # + datasetFilePath - Parameter Description  
    public function partition(string datasetFilePath, function... criterias) {
        stream<string[], io:Error>|error csvStream2 = io:fileReadCsvAsStream(datasetFilePath);
        // Loop through the stream and print the content.
        if (csvStream2 is error) {

        } else {
            error? e = csvStream2.forEach(function(string[] val) {
                                              io:println(val);
                                          });
        }
    }
}

# Description
# + return - Return Value Description  
public function main() returns error? {

}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
`Document all` should only be suggested for top level constructs
