### ISSUE TITLE
For variables named with ' prefix; ' is missed during suggestion

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29462]
**Description:**
<img width="849" alt="Screenshot 2021-03-23 at 15 42 10" src="https://user-images.githubusercontent.com/15815199/112130731-ccd63600-8bee-11eb-8978-d4a40358f7a6.png">

Sample code:

```ballerina
function rate(Currency 'from, Currency to) {
    string fromCurrency = 'from;
    string toCurrency = to;
    string responseKey = fr
}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sanjana** [comment]
As per a related discussion at https://github.com/ballerina-platform/ballerina-lang/issues/28567#issuecomment-779040893 and a suggestion made at https://github.com/ballerina-platform/ballerina-lang/issues/28567#issuecomment-779521353, will be updating the PR https://github.com/ballerina-platform/ballerina-lang/pull/29964 with an approach similar to https://github.com/ballerina-platform/ballerina-lang/pull/29701.
