### ISSUE TITLE
`IllegalArgumentException` in output window when using `->`

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29469]
**Description:**
$title 
![Screenshot from 2021-03-23 16-06-55](https://user-images.githubusercontent.com/19838787/112302655-53f3de80-8cc1-11eb-9c7b-edb94d9d1f62.jpg)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Getting the same exception when I type the `.` in the following snippet
```ballerina
    resource function get books(int? 'limit) returns Books|Error {
        stream<record {| anydata...; |}, sql:Error> result = db->query("SELECT * from books");
        result.
    }
```

**Comment by lochana-chathura** [comment]
Couldn't reproduce the issue with all 3 samples with alph3 and alph4.

**Comment by dulajdilshan** [comment]
Working fine. Tested with alpha5
