### ISSUE TITLE
`bal build` prints SLF4J loger warning

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#29460]
**Description:**
when running any `bal` command, it prints a warning message.
```
/Users/manu/proj/key-val-bal> bal run
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Library/Ballerina/distributions/ballerina-slalpha3/bre/lib/ballerina-rt-2.0.0-alpha6-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Library/Ballerina/distributions/ballerina-slalpha3/bre/lib/ballerina-rt-2.0.0-alpha6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]

Compiling source
	manu/key_val_bal:0.1.0
```

**Steps to reproduce:**
run any valid `bal` cmd

**Affected Versions:**
```
Ballerina Swan Lake Alpha 3
Language specification v2020-12-17
Update Tool 1.3.1
```
**OS, DB, other environment details and versions:**
MacOs
<!-- 
**Related Issues (optional):**
Any related issues such as sub tasks, issues reported in other repositories (e.g component repositories), similar problems, etc.

**Suggested Labels (optional):**
Optional comma separated list of suggested labels. Non committers can’t assign labels to issues, so this will help issue creators who are not a committer to suggest possible labels

**Suggested Assignees (optional):**
Optional comma separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, so this will help issue creators who are not a committer to suggest possible assignees

**Comment by pubudu91** [comment]
Did you remove the previously installed SNAPSHOT build before installing the released version of alpha3? I think the issue here is since we don't name the internal pack used in the distribution as SNAPSHOT versions, when you pull the released version using the update tool, it'll merge the `ballerina-slalpha3` directories.

**Comment by manuranga** [comment]
Manually deleting `/Library/Ballerina/distributions/ballerina-slalpha3` and re-installing worked.
I actually installed using the installer.
Should we fix this by deleting before installing? might solve other issues like wrongly cached files. Or is ok to close this?

**Comment by pubudu91** [comment]
Hmm.. I'm ok with that. But we'll only get this for instances like these, where we mix SNAPSHOT builds with the actual release build. That too because we don't have a separate SNAPSHOT version for that internal distribution. @keizer619 WDYT?

**Comment by manuranga** [comment]
If it only happens for SNAPSHOTs let's close this. What I meant was, If a use re-install a (released) ballerina dist thinking it will fix some wired caching issues ect, will it actually do that ?

**Comment by keizer619** [comment]
Yes this would happens for `SNAPSHOT` releases and also releases during releases candidates as internal libs will have several copies with different timestamps.

**Comment by keizer619** [comment]
As we do not share internal releases with public or publish to Ballerina Update server  i think we can close this issue :) Please feel free to open if there are any concerns
