### ISSUE TITLE
Code completion does not work intermittently 

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#29465]
**Description:**
The below snap shows how completion is not working even though it works most of the time. This happens probably when adding a line in between. 

https://user-images.githubusercontent.com/28732894/112122442-4b7aa580-8be6-11eb-8791-85aac26050e6.mov

**Suggested Labels:**

**Suggested Assignees:**
Version/SLAlpha3, Area/AutoCompletion 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
Does this occur when you reload the window as well?

**Comment by parkavi11** [comment]
No, when I restarted VSCode it worked as expected

**Comment by nadeeshaan** [comment]
This was a caching issue and has been fixed in latest master. Apart from this, there is a CPU usage issue which is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/32020. Hence closing this issue.
