### ISSUE TITLE
Suggestions not available at client-remote-method-call-action

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#29470]
**Description:**
Consider the below sample.

![Screenshot from 2021-03-23 16-03-32](https://user-images.githubusercontent.com/39232462/112134679-fbeea680-8bf2-11eb-8113-58efebb7fe56.png)

Suggestions like `get`, `post`, etc are not available here.

</details>
<details>
  <summary><b>code sample</b>  (<i>click to expand</i>)</summary>

```bal
http:Client mockyClient = check new ("https://run.mocky.io/v3");

public function getGETResponse(string relativePath) returns http:Response|error {
    return mockyClient->ge //<cursor>
}
```
</details>

**Comment by nadeeshaan** [comment]
Similar to #29476, instead there the type is empty
