### ISSUE TITLE
Remote methods of a client in a standard library module are not suggested

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29476]
**Description:**
Better if suggestions can be provided for above.
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/19838787/112138454-86d1a000-8bf7-11eb-9f22-f594911356d3.gif)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
We call the `type(node)` API to get the symbol's type. In this particular scenario, the type of `popClient` at the cursor `CompilationErrorType`. Therefore we fail to access the methods.
