### ISSUE TITLE
"Document this" code action for function, creates a comment with out of order parameters

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29475]
**Description:**
I believe the `toCurrency` and `fromCurrency` order should be swapped in the comments syncing with the parameter order.

<img width="979" alt="Screenshot 2021-03-23 at 16 18 25" src="https://user-images.githubusercontent.com/15815199/112135303-a6ff6000-8bf3-11eb-902a-0125f3e899b5.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
Related Issue #29402
