### ISSUE TITLE
Error is shown in an incorrect line

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29473]
**Description:**
$title
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/19838787/112136881-95b75300-8bf5-11eb-8e91-54f94c6bba93.gif)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Related to #29418.

**Comment by lochana-chathura** [comment]
Duplicate of #29418
