### ISSUE TITLE
Invalid WARNING message when function has a parameter with a hyphen in VSCode

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#29489]
**Description:**
$Subject

**Steps to reproduce:**
Add the below code to the VSCode.

```
import ballerina/io;

public function main() {
    error e = error("bad sad");
    foo(e);
}

# + 'error - The error struct to be logged
function foo(error 'error) {
    io:println('error);
}
```
It would have a warning message like below.
<img width="516" alt="image" src="https://user-images.githubusercontent.com/39085607/112146479-9f46b800-8c01-11eb-8a3d-b5b9b1ca447e.png">

**Affected Versions:**
SLAlpha3

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/29076

**Comment by prabushi** [comment]
This is fixed in Swan Lake Beta1.
