### ISSUE TITLE
Make all configurable variable declarations with invalid types result in a compilation error

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29484]
**Description:**
Currently fails only at runtime, but we should ideally restrict these at compile-time. 

**Describe your problem(s)**
```ballerina
type Foo record {|
    int i;
|};

type Bar record {
    string s;
};

configurable readonly & Foo|Bar x = ?;
```

Results in a runtime error.
```cmd
$ bal run test.bal 

Compiling source
        test.bal

Running executable

error: configurable variable '.:x' with type '(Foo & readonly)|(Bar & readonly)' is not supported
```

**Affected Version:**
slalpha3

**Comment by HindujaB** [comment]
This is fixed in beta2 with https://github.com/ballerina-platform/ballerina-lang/pull/30668. 
Hence, closing the issue.
