### ISSUE TITLE
Improve error on empty Config.toml file

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29482]
**Description:**
The current error is

> error: an empty configuration file is found in path '/path/to/config/file/Config.toml'. Please provide values for configurable variables

Since we have two sentences, we should have a period at the end of the second sentence too.

Also since we include the file name in the error shouldn't we say

> error: empty configuration file found at '/path/to/config/file/Config.toml'. Please provide values for configurable variables.

**Affected Version:**
slalpha3

**Comment by HindujaB** [comment]
This error message is no longer valid after fixing https://github.com/ballerina-platform/ballerina-lang/issues/30160.
Hence, closing this.
