### ISSUE TITLE
Relative path is calculated differently when bal run/build is executed with-in module vs out-side of module.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#29480]
**Description:**

[P.zip](https://github.com/ballerina-platform/ballerina-lang/files/6189176/P.zip)

Extract the ballerina project.
When we run `bal run` within the module `P` this works.
If I run `bal run P` from parent of the `P` directory, the relative path is calculated from the parent directory.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This is the expected behavior. All relative paths will be resolved relative to the present working directory (the directory in which the command is executed). So when you run the project from a directory outside of the project, it will resolve the paths from that particular working directory and not the package root. 

This is the same behavior you would expect if you run the program using the executable jar.

**Comment by rdhananjaya** [comment]
Is there a preferred place to be used as PWD when executing Ballerina command? The debugger always consider the package root as the PWD.

**Comment by azinneera** [comment]
> Is there a preferred place to be used as PWD when executing Ballerina command? The debugger always consider the package root as the PWD.

What is the method you used for debugging? If it is remote debug, the expected working directory is the directory in which the command is run. If you are running the `Ballerina Debug` from VSCode, then the working directory is the package root.

**Comment by rdhananjaya** [comment]
I was following the https://ballerina.io/learn/tooling-guide/visual-studio-code-extension/run-and-debug/
@NipunaRanasinghe and debugger team, shall we add this working directory information to the debug guide, saying that when debugger is started through VS Code, the working directory will always be the package root and if the user want some other place to be their working directory they have to use remote debugging.

**Comment by NipunaRanasinghe** [comment]
@rdhananjaya Sure we'll update the debugger guide with this information. Thanks for the input! :slightly_smiling_face:
