### ISSUE TITLE
Functions with ' prefix is missed in the suggestions

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29494]
<img width="999" alt="Screenshot 2021-03-23 at 18 33 29" src="https://user-images.githubusercontent.com/15815199/112150627-504f5180-8c06-11eb-8648-4151035444c8.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This is possibly the same as #30242. @dulajdilshan please confirm

**Comment by dulajdilshan** [comment]
Yeah, this the same as #30242. This is a result of the NPE comes with the quoted identifiers
