### ISSUE TITLE
Bal push command giving not working URL details.

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-lang#29499]
**Description:**

```
lahiru@lahirumal:excel-ballerina$ bal push
ballerina: package 'malepathirana/ballerina_excel_library:0.1.0' already exists in remote repository(https://api.central.ballerina.io/2.0/registry). build and push after updating the version in the Ballerina.toml.
```
![image](https://user-images.githubusercontent.com/5174183/112149044-93a8c080-8c04-11eb-8eab-03dc10605d5e.png)

**Suggested Labels:**

Version/SLAlpha3

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hemikak** [comment]
The above error shows the URL(https://api.central.ballerina.io/2.0/registry) of the said `remote repository`.

**Comment by azinneera** [comment]
@hemikak is this the API endpoint? Would it make more sense to show the Ballerina Central url https://swanlake.central.ballerina.io/ ?

**Comment by hemikak** [comment]
@azinneera , yes that would make sense.
