### ISSUE TITLE
No option to delete users own organizations created in ballerina central

### ISSUE THREAD

**Issue by lahirusamith** [ballerina-platform/ballerina-lang#29498]
**Description:**

$Subject . 

seems that option is needed as basic functionality when it comes to manage organizations in ballerina central. 

**Suggested Labels:**

Version/SLAlpha3

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hemikak** [comment]
Currently we are not allowing to delete packages or organizations in ballerina central as it can have drastic affects on other packages that uses them.. If you can specify the organization or package that needs to be deleted through an email to the ballerina organization or by a github issue, we check for package usages and delete the package.

Please reopen if needed.
