### ISSUE TITLE
Incorrect documentation order for record

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#29506]
**Description:**
![Selection_214](https://user-images.githubusercontent.com/8381003/112164570-ff465a00-8c13-11eb-8ad1-12775c44255f.png)

**Comment by MaryamZi** [comment]
@chamil321, can you elaborate more on the issue please?

This now adds
```ballerina
# Description
#
# + id - Field Description  
# + name - Field Description  
# + description - Field Description
public type Pet record {|
    string id;
    string name;
    string description;
|};
```

Please note that the recommended approach is to use field-level documentation anyway.

**Comment by KavinduZoysa** [comment]
Closing the issue, because documentation adds properly.
