### ISSUE TITLE
Import completion doesn't work for lang modules after dot

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#29501]
**Description:**
Import completion dropdown disappear as soon as you type `.`

https://user-images.githubusercontent.com/1686124/112156317-26009280-8c0c-11eb-99ec-3622428af288.mov

**Comment by malinthar** [comment]
Could not reproduce on slbeta2
![ezgif com-gif-maker(9)](https://user-images.githubusercontent.com/35211477/122415372-7ab27000-cfa5-11eb-8e45-053214742c61.gif)

**Comment by IMS94** [comment]
Closing this as this is no longer reproducible on master
