### ISSUE TITLE
[LS Code Actions] "Fix Return Type" code action is not working for object methods

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#29505]
**Description:**
Please refer the sample code below and note that the "Fix Return Type" code action is not working for the `partition` object method.

```ballerina 
# Description  
class Partitioner {

    # Description
    #
    # + datasetFilePath - file path of the input dataset (in CSV format) 
    # + criterias - Parameter Description    
    # + return - Return Value Description
    public function partition(string datasetFilePath, function... criterias) returns int {
       
            return 5.5;
        
    }
}

```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This is fixed in latest master as per bellow. Hence closing the issue.


https://user-images.githubusercontent.com/1329674/112261925-bda8c400-8c92-11eb-81ff-e87fc17d8486.mp4
