### ISSUE TITLE
Bal Push command unable to find bala file for the package

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#29500]
**Description:**
The following error is thrown when executing the `bal push` command.
```
ballerina: cannot find bala file for the package: stargazer. Run 'bal build' to compile and generate the bala.
```

**Steps to reproduce:**
1. Create a simple project.

The following is the Ballerina.toml
```
[package]
org = "madhuka"
name = "stargazer"
version = "0.1.0"
```
2. Build it by executing `bal build`
3. Add the access token to the `~/.ballerina/Settings.toml` file

```
[central]
accesstoken="<ACCESS_TOKEN>"
```
4. Push it by executing `bal push`

**Affected Versions:**
SLAlpha3

**OS, DB, other environment details and versions:**
MacOS

**Comment by hemikak** [comment]
This issue comes because the `bala` file is not built. Need to use `bal build -c` command to build the flag. The error shown may be wrong.

**Comment by azinneera** [comment]
Duplicate of #29347
