### ISSUE TITLE
Internal node name shown in error

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29514]
**Description:**
<img width="507" alt="Screenshot 2021-03-23 at 22 19 23" src="https://user-images.githubusercontent.com/15815199/112185319-1e4de780-8c26-11eb-8f47-3a60edc33060.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
This is a duplication of this: https://github.com/ballerina-platform/ballerina-lang/issues/29168
