### ISSUE TITLE
Incorrect terminology in error message for Config.toml entry

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29518]
Got the following error because the format of my Config.toml file was wrong. 
```
error: [Config.toml:(1:1,2:19)] invalid module structure found for module 'bookstore'. Please provide the module name as '[bookstore]'
```
Here, it's referring to `bookstore` as a module when in fact it's the package itself.

**Comment by HindujaB** [comment]
This is fixed in current master branch. Hence, closing this.
