### ISSUE TITLE
No documentable parameter for parameters with ' prefix

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29511]
**Description:**
Shows `no documentable parameter` warning for documented parameters with `'` prefix

<img width="764" alt="Screenshot 2021-03-23 at 22 06 30" src="https://user-images.githubusercontent.com/15815199/112183585-68ce6480-8c24-11eb-81f6-b2f0bbb74ede.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Fixed in #29078
