### ISSUE TITLE
Cast gets added to the wrong position

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29515]
Refer to the following. Please note that in the video, it should be `Book[]`.

https://user-images.githubusercontent.com/6260009/112188098-b6e56700-8c28-11eb-87a8-71515bef92f1.mp4

The expected end result was:
```ballerina
Book[] books = [];
        sql:Error? forEach = result.forEach(function (record{} row) {
            io:println(row);
            books.push(<Book>row);
        });
```

**Comment by nadeeshaan** [comment]
This issue has been fixed in latest master. Hence closing the issue. Please reopen if the issue can still observed
