### ISSUE TITLE
Not getting completions within a mapping constructor in an expr bodied function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29525]
Consider the following:
```ballerina
function mapToBook(record {int book_id; string title; string first_name; string last_name;} book) returns Book => {
    id: book.book_id;
    name:  <cursor>
};
```
At the illustrated cursor position, it should suggest the `book` var.

**Comment by pubudu91** [comment]
Just realized that the above is a syntactically invalid program. So maybe it's ok for this to not have completions?

**Comment by nadeeshaan** [comment]
> Just realized that the above is a syntactically invalid program. So maybe it's ok for this to not have completions?

@pubudu91 yes, the identified context is not valid due to the parser resolution logic. Since this is an unpredictable scenarios, the completions either can be invalid or not getting any completions. Hence closing the issue
