### ISSUE TITLE
Getting invalid completions for a record typed var

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29527]
See the following syntactically invalid code snippet:
![issue1](https://user-images.githubusercontent.com/6260009/112199536-45abb100-8c34-11eb-8d50-015c61bdb679.png)

All the completions suggested are module level constructs defined in another file.

**Comment by nadeeshaan** [comment]
This is due to the same issue mentioned as in https://github.com/ballerina-platform/ballerina-lang/issues/29549#issuecomment-805437578
