### ISSUE TITLE
No import module suggestion is shown for stan modules pulled from central

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29529]
**Description:**
<img width="462" alt="Screenshot 2021-03-24 at 00 05 11" src="https://user-images.githubusercontent.com/690559/112199937-b521a080-8c34-11eb-9f5e-591576797d0f.png">

Ideally, there should be a code action or suggestion to import stan module as it is already been used in another bal file within the same project.

**Affected Versions:**
sl-alpha3 at least

**Related Issues (optional):**
#29555

**Comment by nadeeshaan** [comment]
In order to support this capability we need to have a solution for https://github.com/ballerina-platform/ballerina-lang/issues/29555. Currently we can access only the distribution repo modules.

**Comment by jclark** [comment]
Some things I would find useful:

- help to remove unused imports (or perhaps just comment them out)
- with multi-file modules, if I import something with some prefix `p` in one file, and I use `p:` in another module, just add the import (nobody is going to use inconsistent prefixes within the files of a single module)
- if I type e.g. `io:foo` and there is only one module in the standard library with a final name component of `io`, (i.e. ballerina/io) then assume I mean that module, particularly if I say io:println, you can notice that the candidate module contains a function `println`

**Comment by nadeeshaan** [comment]
> Some things I would find useful:
> 
> * help to remove unused imports (or perhaps just comment them out)
> * with multi-file modules, if I import something with some prefix `p` in one file, and I use `p:` in another module, just add the import (nobody is going to use inconsistent prefixes within the files of a single module)
> * if I type e.g. `io:foo` and there is only one module in the standard library with a final name component of `io`, (i.e. ballerina/io) then assume I mean that module, particularly if I say io:println, you can notice that the candidate module contains a function `println`

@jclark please find my comments below.
1. In the current implementation we have provided a code action to optimize the imports. 
![Feb-21-2022 15-51-27](https://user-images.githubusercontent.com/1329674/154936735-6dc3c8ad-b8e6-4d0d-ad42-455b813c5016.gif)
2. This we have to implement and think of an approach. We will focus on this one
3. Currently, we have a code action to import such a module. 
![Feb-21-2022 15-52-27](https://user-images.githubusercontent.com/1329674/154936956-73b21e1c-70fa-4fcb-b6bb-64caaa04fb61.gif)

Please share your thoughts on the current implementations as mentioned earlier.

**Comment by nadeeshaan** [comment]
@jclark I agree that we need to revisit the `optimize imports` code action. We are revisiting this code action and we will track this in a separate issue.
