### ISSUE TITLE
Suggestion for on-fail clause quick fix for check expression

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29534]
**Description:**
When no matching error return type for `check` expression; an on-fail clause quick fix can be suggested.

<img width="1155" alt="Screenshot 2021-03-24 at 00 18 54" src="https://user-images.githubusercontent.com/15815199/112201961-d8e5e600-8c36-11eb-83d9-63cf946a0fb0.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gayalkuruppu** [comment]
@pcnfernando shall we suggest following quick fix for the above scenario?
```
function name() {
    do {
        decimal aa = check decimal:fromString("hello");
    }
    on fail var e {
        <cur>
    }
}
```

**Comment by pcnfernando** [comment]
Yes. Btw, seems this is one of the tasks mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/31004.

**Comment by gayalkuruppu** [comment]
#31004 suggests,

1. Adding `returns error` when there is a `fail error(" ");` statement inside a function body and 
2. Adding on fail clause only for the statements that support having an on-fail clause

In which the second suggests following 
```
function test1() {
    do {
        int i = check checkError();
    }
}

function checkError() returns int|error {
    return error("");
}
```
to change to this,
```
function test1() {
    do {
        int i = check checkError();
    } on fail error e {
        
    }
}

function checkError() returns int|error {
    return error("");
}
```
Would you suggest following 
```
function test1() {
    int i = check checkError();
}
``` 
to get the same end result as the above too? Thanks!

**Comment by pcnfernando** [comment]
Yes. Wrapping a statement that can cause a possible failure with a do-with-on-fail-clause would resemble the try-catch behavior. 

```ballerina
function test1() {
    int i = check checkError();
}
```
would changed to 

```ballerina
function test1() {
   do {
      int i = check checkError();
   } on fail var e {

   }
}
```
