### ISSUE TITLE
Bad Sad thrown when enabling an unused import

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29530]
**Description:**
Open parser.bal and try to enable and disable `ballerina/io` import in line 2. Then try to compile it.

![compilation](https://user-images.githubusercontent.com/1448489/112243559-cd64e000-8c73-11eb-965d-3a6bbf063550.gif)

**Steps to reproduce:**
Project is attached 
[bal-order-processing.zip](https://github.com/ballerina-platform/ballerina-lang/files/6192000/bal-order-processing.zip)

**Affected Versions:**
2.0.0-SLA3

**Comment by lochana-chathura** [comment]
As per the gif attached, crashing occurs at Desugar.  Also tired parsing the bal file no issue saw related parser.

**Comment by KavinduZoysa** [comment]
This is fixed in Ballerina 2201.0.0 (Swan Lake), hence closing.
