### ISSUE TITLE
Updating undocumented parameter document breaks the existing document

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29541]
**Description:**
Check the images before and after applying the update documentation suggestion.

<img width="738" alt="Screenshot 2021-03-24 at 01 18 28" src="https://user-images.githubusercontent.com/690559/112209076-15b5db00-8c3f-11eb-9b1b-aa9146c49ca2.png">

<img width="637" alt="Screenshot 2021-03-24 at 01 18 46" src="https://user-images.githubusercontent.com/690559/112209098-1a7a8f00-8c3f-11eb-8f08-35e7a9c43d14.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment]
This happens when the existing documentation has several lines. Working on it.
