### ISSUE TITLE
`Type guard variable` code action adds `if-else` with parentheses

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29548]
**Description:**
$title
In ballerina, the best practice is to avoid using parentheses in `if-else`.
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/19838787/112231898-9d124700-8c5d-11eb-99a6-24d5ceb67f44.gif)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Fixed by #29337. Hence closing the issue
