### ISSUE TITLE
Incorrect error message for string concat in select clause

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#29546]
Here is the sample code:
```
        map<anydata> keyValsMap = {foo:"sss", bar:"ffff"};
        var x = from var k in keyValsMap.keys()
                let var v = keyValsMap[k]
                select k+"dd"

        io:println(x);
```

The screenshot with the diagnostic:
<img width="785" alt="Screen Shot 2021-03-23 at 3 57 46 PM" src="https://user-images.githubusercontent.com/2637328/112229753-d06abc80-8bf0-11eb-8ae8-a90617719031.png">

**Comment by gimantha** [comment]
This is fixed in beta1
