### ISSUE TITLE
`Couldn't find the invocation symbol!` in output window with `if` having empty brackets

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29549]
**Description:**
$title
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/19838787/112232760-224a2b80-8c5f-11eb-8da7-05dd1e35feaa.gif)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This has been done intentionally. The client triggers the signature help request when it sees a `(`. If the server cannot identify a valid invocation node at such scenarios (for example,  in this case the `if ()`), the server throws an exception. As a solution, we can avoid throwing the Exception here.
