### ISSUE TITLE
Question on inter-worker message passing 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#29556]
Doing so gives me a compilation error (which is expected)
```ballerina
public function main() {
    worker w1 {
        1 -> function;
        2 -> function;
    }

    int value1 = <- w1;
}
```
but not 
```ballerina
public function main() {
    worker w1 {
        foreach int i in 1 ..< 3 {
            i -> function;
        }
    }

    int value1 = <- w1;
}
```
Is that the expected behavior ?

**Comment by rdhananjaya** [comment]
At the moment we only support worker send from the toplevel (this is a spec deviation) of the worker-decl, but seems like we have not considered the `foreach` construct.

**Comment by rdhananjaya** [comment]
Second sample now emit ` worker send statement position not supported yet, must be a top level statement in a worker`.

**Comment by rdhananjaya** [comment]
Let's keep this open as we do need to support this worker send position as it's allowed in the spec.
