### ISSUE TITLE
Add support to access project repositories via the Project API

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#29555]
**Description:**
$title.

We need to access the various project repositories to get the modules imported in each repository such as modules pulled from central, local repository and distribution repository. Currently we can only access the distribution repository.

**Comment by pramodya1994** [comment]
Added a PR[1] by adding utils to get packages from each repo in DependencyUtils.
@nadeeshaan We can either use those utils, or you can do the same on the lang server side. WDYT?

[1] https://github.com/ballerina-platform/ballerina-lang/pull/33839

**Comment by nadeeshaan** [comment]
> Added a PR[1] by adding utils to get packages from each repo in DependencyUtils. @nadeeshaan We can either use those utils, or you can do the same on the lang server side. WDYT?
> 
> [1] #33839

@pramodya1994 I think it is better to have the utils, since the other tools also can access the content via a common utility API.

**Comment by azinneera** [comment]
@nadeeshaan As @pramodya1994 suggested you can access the packages in the central cache and local repo as follows:

```java
BallerinaUserHome ballerinaUserHome = BallerinaUserHome.from(project.projectEnvironmentContext().environment());
// Get packages in remote repo
Map<String, List<String>> remoteRepoPackages = ballerinaUserHome.remotePackageRepository().getPackages();
// Get packages in local repo
Map<String, List<String>> localRepoPackages = ballerinaUserHome.localPackageRepository().getPackages();
```

There won't be any changes to these APIs in SL, and so it's safe to use these APIs directly. We can provide a util in the future if a need arises.

**Comment by nadeeshaan** [comment]
@azinneera thank you. We will have a look at this approach.

**Comment by azinneera** [comment]
Closing since the solution suggested in https://github.com/ballerina-platform/ballerina-lang/issues/29555#issuecomment-979700615 is implemented.
