### ISSUE TITLE
Showing multiple diagnostics with `graphql` not found

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#29566]
**Description:**
$title
![Peek 2021-03-24 12-22](https://user-images.githubusercontent.com/25485997/112267817-06b14600-8c9c-11eb-80ac-743daa28f3a3.gif)

Code used:
```ballerina
service graphql:Service / on new graphql:Listener(9000) {

    resource function get litrailft(string id) returns string|(){
        return "Value";
    }
}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hasithaa** [comment]
@rdhananjaya looks like this is coming from the compiler side.

**Comment by rdhananjaya** [comment]
Also happens for record and class type inclusions, type-ref in object constructor.
