### ISSUE TITLE
Showing similar code-actions for `graphql` not found

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#29568]
**Description:**
$title
![Peek 2021-03-24 12-29](https://user-images.githubusercontent.com/25485997/112268210-a1118980-8c9c-11eb-9f78-5127f35dabd2.gif)

Code Snippet used:
```ballerina
service graphql:Service / on new graphql:Listener(9000) {

    resource function get litrailft(string id) returns string|(){
        return "Value";
    }
}
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
 #29566

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Here, there are duplicated diagnostics as well. That's the reason for duplicating the same code action.

**Comment by nadeeshaan** [comment]
Related Issue #29566

**Comment by dulajdilshan** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30295. Tested on beta-1
