### ISSUE TITLE
Support to control the order of test execution by group

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29567]
**Description:**
Can this be supported? The requirement is to basically have one group run only after the other.

Related discussion: https://ballerina-platform.slack.com/archives/CAYCPFRHQ/p1616516106004900

**Comment by azinneera** [comment]
There can be multiple groups for a test case and so this cannot be achieved. If we are to support this, the design has to be revisited which will not be done for Swan Lake.
