### ISSUE TITLE
Completions/SignatureHelp help-text seems to be broken for bal code snippets

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29562]
**Description:**
Completions/SignatureHelp help-text seems to be broken for bal code snippets. Please refer below;
<img width="867" alt="Screenshot 2021-03-24 at 10 07 48 AM" src="https://user-images.githubusercontent.com/1448489/112255962-428ee000-8c89-11eb-93e8-86e431f6d27c.png">

**Affected Product Version:**
2.0.0-SLA3

**Comment by nadeeshaan** [comment]
Duplicate #29547. Hence closing
