### ISSUE TITLE
Type cast didn't work properly between int and string

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#29564]
**Description:**
$Subject

Please refer the following images:

<img width="400" alt="Screenshot 2021-03-24 at 10 28 31 AM" src="https://user-images.githubusercontent.com/12771261/112258660-dd3cee00-8c8c-11eb-9946-9477dfc4d67e.png">

Even after applied the type cast between int and string, got the following error

<img width="622" alt="Screenshot 2021-03-24 at 10 28 44 AM" src="https://user-images.githubusercontent.com/12771261/112258673-e463fc00-8c8c-11eb-8688-55af697cfeb9.png">

**Steps to reproduce:**
Apply the type cast to this variable
```ballerina
public function test(string value) {
    int count = "5";
}
```
**Affected Versions:**
SLAlpha3

**Comment by pubudu91** [comment]
I believe this is the same limitation discussed in https://github.com/ballerina-platform/ballerina-lang/discussions/29009. Basically a type cast action shouldn't have been suggested in the above scenario.
