### ISSUE TITLE
Wrong fix in code action: `Add type cast to assignment` in function call

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#29576]
**Description:**
$title

![Peek 2021-03-24 14-00](https://user-images.githubusercontent.com/25485997/112279007-6c57ff00-8ca9-11eb-9ba8-95760ba020f5.gif)

Code to use:
```ballerina
public function runThis(string name) returns int{
    var kk = "kk";
}

function runSomething() {
    _ = runThis(34);
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Checked in latest master and this issue has been fixed. Hence closing the issue.
