### ISSUE TITLE
View variables doesn't show the variable correctly

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29577]
Refer to the following image. As it can be seen, the book var doesn't show the correct fields for the record. It's showing the global vars.

![issue2](https://user-images.githubusercontent.com/6260009/112288590-7f6fcc80-8cb3-11eb-8b26-2b118ecd956e.png)

In the previous frame of the call stack, the fields are shown correctly. But it seems to have nested the var in a weird way? Maybe showing it with the name of the param in the callee function?

![issue3](https://user-images.githubusercontent.com/6260009/112289180-13da2f00-8cb4-11eb-9396-561de754d03f.png)

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/30745
