### ISSUE TITLE
Renaming a symbol at the point of use doesn't work within service decls

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29578]
For example,
```ballerina
listener http:Listener ep = new http:Listener(9090);

service / on ep {
    resource function get getResource(http:Caller caller, http:Request req) {
        
    }
}
```
Try renaming `ep` at the point it is used. It doesn't work. However when I try to rename `cl` in the following at the point of use, it works.
```ballerina
function init() {
    var cl = new mysql:Client("localhost", dbUser, dbPassword, "bookstore", 3306);
    if (cl is error) {
        panic cl; // renaming cl here works
    } else {
        db = cl;
    }
}
```

**Comment by nadeeshaan** [comment]
This is caused since the semantic API cannot get the `ep` symbol from the `symbol()` API when we give the cursor position as `ep<cursor>`. In this case the symbol identified is the service symbol. @pubudu91 @dulajdilshan We might need to have a fix for this as well.

**Comment by pubudu91** [comment]
> This is caused since the semantic API cannot get the `ep` symbol from the `symbol()` API when we give the cursor position as `ep<cursor>`. In this case the symbol identified is the service symbol. @pubudu91 @dulajdilshan We might need to have a fix for this as well.

Why use `ep<cursor>` as the position to lookup the symbol though? 🤔

**Comment by nadeeshaan** [comment]
This is the position we get from the client with the rename request.

**Comment by dulajdilshan** [comment]
I think [#29586](https://github.com/ballerina-platform/ballerina-lang/issues/29586)  (plugin-vscde) is also due to this.

**Comment by nadeeshaan** [comment]
> I think [#29586](https://github.com/ballerina-platform/ballerina-lang/issues/29586) (plugin-vscde) is also due to this.

Yes. This also have the same issue

**Comment by IMS94** [comment]
@pubudu91 If a user highlights a variable and do a rename, the cursor position sent by the client will be the position next last character of the var name. But with https://github.com/ballerina-platform/ballerina-lang/pull/28754, we did a temporary hack to fallback to `cursor - 1`. Not sure why it has not come into play if the cause is what @nadeeshaan mentions. :thinking:

**Comment by nadeeshaan** [comment]
@IMS94 the fall back fix we did only works when we do not get a valid symbol (Optional.empty). But in these scenarios the node finder encloses the parent symbol and return it, in the sense we get a symbol instance, but incorrect.
