### ISSUE TITLE
Typechecker doesn't handle target types with a Parameterized type in a union

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#29589]
**Description:**

This occurs when we try to use the the checkIsType[[1]](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L604) method with the following parameters.

**sourcetype** : http:ClientError|http:Response
**targetType** : http:ClientError|(a parameterized type with member type http:Response)

When debugged, I could notice that this fails when trying to use the **isUnionTypeMatch** method.

The existing logic in **isUnionTypeMatch** method[[2]](https://github.com/ballerina-platform/ballerina-lang/blob/9abcd93400f4c9942bac8e97502897ff901a1042/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L842) is as follows.

```
    private static boolean isUnionTypeMatch(BUnionType sourceType, Type targetType, List<TypePair> unresolvedTypes) {
        for (Type type : sourceType.getMemberTypes()) {
            if (!checkIsType(type, targetType, unresolvedTypes)) {
                return false;
            }
        }
        return true;
    }
```
Shouldn't we change it to traverse through each memberType for targetType as well? Similar to the following?

```
    private static boolean isUnionTypeMatch(BUnionType sourceType, Type targetType, List<TypePair> unresolvedTypes) {
        if (targetType instanceof BUnionType) {
            targetType = getUpdatedUnionType((BUnionType) targetType);
        }
        if (sourceType instanceof BUnionType) {
            sourceType = getUpdatedUnionType(sourceType);
        }
        for (Type type : sourceType.getMemberTypes()) {
            if (!checkIsType(type, targetType, unresolvedTypes)) {
                return false;
            }
        }
        return true;
    }

    private static BUnionType getUpdatedUnionType(BUnionType targetType) {
        BUnionType updatedTargetType = new BUnionType();
        for (Type targetTypeMember : targetType.getMemberTypes()) {
            if (targetType.getTag() == TypeTags.PARAMETERIZED_TYPE_TAG) {
                Type bObjectType = ((ParameterizedType) targetTypeMember).getParamValueType();
                updatedTargetType.addMembers(bObjectType);
            } else {
                updatedTargetType.addMembers(targetTypeMember);
            }
        }
        return updatedTargetType;
    }
```

WDYT?

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Since this isn't specific to unions, let me use a simple example with a single type. Note that I've used compile-time analysis for the example, but it applies similarly at runtime.

```ballerina
class Source {
   function func(typedesc<Foo> td) returns Foo => new Baz();
}

class Target {
   function func(typedesc<Foo> td) returns td = external;
}

class Foo {
   int i = 1;
}

// Subtype of `Foo` but not of `Baz`.
class Bar {
   int i = 1;
   float f = 1;
}

// Subtype of `Foo` but not of `Bar`.
class Baz {
   int i = 1;
   string f = "1";
}
```

Here if we type-checked as proposed, the following will be allowed.
```ballerina
Target t = new Source();
```

But now consider a method call for the particular method. This is valid since `Bar` is a subtype of `Foo`.
```ballerina
Bar bar = t.func(Bar);
```

Even though we expect a `Bar` value here, the actual method at this point (`func` of `Source`) returna a `Baz` value which is not a subtype of `Bar` leading to incorrect state at runtime. So we do not consider `Source.func` to be a subtype of `Target.func`. 

Related spec discussion: https://github.com/ballerina-platform/ballerina-spec/issues/633

**Comment by Dilhasha** [comment]
Ok makes sense @MaryamZi. Thanks for the explanation.
