### ISSUE TITLE
Rename doesn't work with graphQL resource function name

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#29586]
**Description:**
$title
![Peek 2021-03-24 12-33](https://user-images.githubusercontent.com/25485997/112268762-7d027800-8c9d-11eb-8a3a-e4d46f61eed1.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment]
Related Issue #29578

**Comment by pubudu91** [comment]
Does rename make sense in this particular case? Here, you are attempting to rename a resource path segment. That's basically just an identifier. It's not a symbol.

**Comment by pubudu91** [comment]
Renaming feature seems to work on symbols. Not entirely sure whether it's by design or whether it's constrained to just work with symbols. @nadeeshaan Would appreciate your input on this.

**Comment by nadeeshaan** [comment]
> Renaming feature seems to work on symbols. Not entirely sure whether it's by design or whether it's constrained to just work with symbols. @nadeeshaan Would appreciate your input on this.

Yes, renaming should be done over associated symbols since we cannot find associated references. In this case we can ignore renaming the path segment.

**Comment by pubudu91** [comment]
@nadeeshaan @dulajdilshan What was the conclusion for this? This is not a blocker right?

**Comment by dulajdilshan** [comment]
> @nadeeshaan @dulajdilshan What was the conclusion for this? This is not a blocker right?

@pubudu91 The conclusion was to keep this behaviour as it is. Am I right?. However, Will remove the 'blocker' tag

**Comment by pubudu91** [comment]
Yeah, that's what I recall as well. Do we still need this issue in that case?

**Comment by nadeeshaan** [comment]
> Yeah, that's what I recall as well. Do we still need this issue in that case?

We can close this issue since this is by design.

**Comment by dulajdilshan** [comment]
We will close this.
