### ISSUE TITLE
Code action for adding the check expr in a var decl/assignment

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29582]
Currently, there's a code action which allows us to add a check expr if the expression typed contains an error type. But there's no code action for adding the check expr when it's a var decl or an assignment. e.g.,
```ballerina
function bar() {
    int x = foo();
}

function foo() returns int|error {
    return 10;
}
```
Expected output from code action
```ballerina
function bar() returns error? {
    int x = check foo();
}

function foo() returns int|error {
    return 10;
}

**Comment by IMS94** [comment]
This will be introduced by #29827
