### ISSUE TITLE
Global variable renaming does not work correctly with vscode plugin

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#29585]
**Description:**
I have a global variable as below.
```
public configurable string directoryPath = ?;

```

I have used it in other modules as below.
```
string directoryPath = config:directoryPath;

```

If I rename the directory path in the config module, other module usages are not getting renamed.

**Comment by nadeeshaan** [comment]
When we consider the location of the `directoryPath` reference, we get the range spreading to the `config:directoryPath` and renames the whole qualified name reference.
