### ISSUE TITLE
No suggestion for `external` keyword

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29592]
**Description:**
$title.

**Describe your problem(s)**
```ballerina
function func(typedesc td) returns td = e<cursor>
```

![no_external_suggestion](https://user-images.githubusercontent.com/8376983/112417383-86e3b400-8d4d-11eb-9706-9dc5539ce616.jpg)

**Affected version:**
slalpha3

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master. Hence closing the issue.
