### ISSUE TITLE
Update documentation code action is not working for records

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#29598]
**Description:**
When an additional record field is added to a record that previously had the documentation generated, the warning and the code action to update the documentation is provided, however, nothing happens when you click it. 

**Steps to reproduce:**
<img width="323" alt="Screen Shot 2021-03-25 at 2 13 36 PM" src="https://user-images.githubusercontent.com/17268934/112445040-b6f27d80-8d74-11eb-93fd-91879193ad94.png">

**Affected Versions:**
SLA3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This issue is fixed in latest master. Hence closing the issue.
