### ISSUE TITLE
Doesn't suggest build options in Ballerina.toml

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#29601]
**Description:**
Suggestions for available build options are not given by the plugin.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
Not only build options we should suggest all attributes for Ballerina.toml  Dependancies.toml. We have a similar implementation in Could.toml which suggest possible attributes based on a JSON schema. We should be able to reuse the same implementation here.

**Comment by malinthar** [comment]
Blocked by https://github.com/wso2/ballerina-plugin-vscode/issues/111
