### ISSUE TITLE
[Debugger] "Copy Value" functionality fails for ballerina string variables in the debug variable view

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#29602]
**Description:**
Please refer the example below and note that the "Copy value" functionality fails only for ballerina variables which contain string values.

![Peek 2021-03-19 15-16](https://user-images.githubusercontent.com/29032600/111761808-51ab1200-88c6-11eb-9acf-3a22da192f7f.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praveennadarajah** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31606
