### ISSUE TITLE
Add Ballerina command to create Config.toml

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29603]
**Description:**
Add Ballerina command to create Config.toml. This will be beneficial for the new users since they don't need to look sample Config.toml from the web.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.0.0-SL-Alpha3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Dilhasha** [comment]
We've introduced a flag `generate-config-schema` to generate a JSON schema with the configurable details that can be used to generate the `Config.toml`
Please refer https://github.com/ballerina-platform/ballerina-lang/issues/32585
