### ISSUE TITLE
[Debugger] Debug points not deployed correctly for a grpc service

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#29621]
**Description:**
Debugging points not deployed correctly for an grpc service

**Suggested Labels (optional):**
Type/Bug
Component/Debugger, 
Component/VScode Plugin

**Sample**
https://github.com/ballerina-guides/backend-for-frontend/blob/master/README.md/

**Comment by NipunaRanasinghe** [comment]
Closing since cannot reproduce with the latest Ballerina SwanLake release (SLAlpha4)
