### ISSUE TITLE
Wrong error message when user is not given permission to create Settings.toml

### ISSUE THREAD

**Issue by JayaniH** [ballerina-platform/ballerina-lang#29716]
**Description:**
When the user does not have permission to create the Settings.toml file, the error message displayed is "ballerina: unable to create the file system cache of Ballerina Central repository". An error message similar to "failed to create /home/user/.ballerina/Settings.toml: permission denied" should be displayed instead.

**Steps to reproduce:**

Revoke permissions from the user for '/home/user/.ballerina/'
Run ballerina code using the _bal run_ command.

**Comment by suganyasuven** [comment]
https://github.com/ballerina-platform/ballerina-update-tool/issues/147
