### ISSUE TITLE
bal grpc --input grpc_unary_blocking.proto --output stubs - --illegal-access?

### ISSUE THREAD

**Issue by miriam-z** [ballerina-platform/ballerina-lang#29721]
**Description:**

**Steps to reproduce:**

```
syntax = 'proto3';
import "google/protobuf/wrappers.proto";
service HelloWorld {
    rpc hello (google.protobuf.StringValue) returns (google.protobuf.StringValue);
}
```

Output:

bal grpc --input grpc_unary_blocking.proto --output stubs
Downloading protoc executor file - protoc-3.9.1-osx-x86_64.exe
Download successfully completed. Executor file path - /var/folders/r1/p68hfp513tdd08hq3s1jdrmw0000gn/T/protoc-3.9.1-osx-x86_64.exe
Successfully extracted library files.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.MemberValueResolver (file:/$HOME/Downloads/ballerina-swan-lake-alpha2/distributions/ballerina-slalpha2/bre/lib/handlebars-4.0.6.jar) to method java.util.Collections$EmptyMap.isEmpty()
WARNING: Please consider reporting this to the maintainers of com.github.jknack.handlebars.context.MemberValueResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Successfully generated ballerina file.->

Is this expected?

**Comment by BuddhiWathsala** [comment]
@miriam-z, I guess you are confusing with the warnings, right?. 

We have used handlebars to generate Ballerina files from a given protobuf file. However, ATM, handlebars do not support Java 11 properly even though Ballerina internally uses Java 11. That is the reason for these warnings. 

Currently, we are in the process of removing handlebars and try to generate relevant Ballerina files using our syntax tree to prevent these warnings.

Please find the active task here https://github.com/ballerina-platform/ballerina-standard-library/issues/1103
