### ISSUE TITLE
Transaction handler function name suggested along with ()

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29748]
**Description:**

![trxHandler](https://user-images.githubusercontent.com/15815199/113147065-068de900-924e-11eb-83b7-c3bc943097e1.gif)

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/lang.'transaction as trx;

public function main() {
    var onRollbackFunc = isolated function(transaction:Info? info, error? cause, boolean willTry) {
                             io:println(" trxAborted");
                         };

    var onCommitFunc = isolated function(transaction:Info? info) {
                           io:println(" trxCommited");
                       };

    transaction {
        trx:onCommit(onCommitFunc);
        checkpanic  commit;
    }
}
```

**Affected Versions:**
SL Alpha 4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Closing the issue because it tracked at high level, https://github.com/ballerina-platform/ballerina-lang/issues/30078
