### ISSUE TITLE
Incomplete suggestions for cyclic union definition?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29740]
**Description:**
The type being defined is not suggested.

![cyclic_union_def](https://user-images.githubusercontent.com/8376983/113129266-52ce2e80-9238-11eb-8889-c8ca44cb10c9.png)

But the following is a valid type definition.

```ballerina
type CyclicUnion int|CyclicUnion[];
```

**Comment by nadeeshaan** [comment]
As per the syntax tree's resolution, the syntax tree has properly identified the type definition as follows,
<img width="828" alt="Screenshot 2021-05-04 at 13 20 26" src="https://user-images.githubusercontent.com/1329674/116974285-87bc1e00-acdb-11eb-9abe-d9f19fdd8ad6.png">

We will have to address this at the semantic layer.

**Comment by dulajdilshan** [comment]
> As per the syntax tree's resolution, the syntax tree has properly identified the type definition as follows,
> <img alt="Screenshot 2021-05-04 at 13 20 26" width="828" src="https://user-images.githubusercontent.com/1329674/116974285-87bc1e00-acdb-11eb-9abe-d9f19fdd8ad6.png">
> 
> We will have to address this at the semantic layer.

Here we are getting a missing-node error. I think we need to have a proper procedure for appending the `CyclicUnion` symbol even there is a missing node in its member's list

**Comment by dulajdilshan** [comment]
Deferred. In order to prioritize other issues over this.
