### ISSUE TITLE
Long strings are not formatted according to max cloumns

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#29757]
**Description:**
Consider a long string that is concatenated with `+` operator and exceeds the column length 120. The formatter only places the string value on the next line, doesn't split with `+` operators.

<img width="1250" alt="Screenshot 2021-04-01 at 08 40 27" src="https://user-images.githubusercontent.com/5234623/113238251-016c8080-92c6-11eb-9e6e-37234ad2180d.png">

**Steps to reproduce:**
```
public function main() {
    string stringVal =  "this is a sample. this is a sample. this is a sample. this is a sample. this is a sample. this is a sample. " + " this is a sample. this is a sample. this is a sample." + "this is a sample. this is a sample. this is a sample. this is a sample. this is a sample. this is a sample. this is a sample." + " this is a sample. this is a sample.";
}

```

**Affected Versions:**
SL Alpha4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
The formatter no longer supports the line wrapping feature, instead, it now allows the user to break new lines at appropriate places as required. i.e. the formatter preserves the user-defined new lines (up to a maximum of one blank line). The indentation of a user-defined new line will be aligned to the nearest tab space.

For instance, if the user decides to format the code snippet given above as follows, it will be preserved as it is by the formatter. However, the formatter will not do the line wrapping on its own.
```bal
public function main() {
    string stringVal = "this is a sample. this is a sample. this is a sample. this is a sample. this is a sample. " + 
        "this is a sample. " + " this is a sample. this is a sample. this is a sample." + 
        "this is a sample. this is a sample. this is a sample. this is a sample. this is a sample. " + 
        "this is a sample. this is a sample." + " this is a sample. this is a sample.";
}
```
