### ISSUE TITLE
[LS] Query expression completions suggest `from clause` when a `from clause` is already available

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29764]
**Description:**
Type a query expression which has a `from clause` and at the end of the from clause or any other clause (`where`, `join`, etc), see the suggestions. It includes `from clause` and `from` keyword. This is not correct as a query pipeline can have only one `from clause`.

**Steps to reproduce:**
See description

**Affected Versions:**
SLA4-SNAPSHOT

**Suggested Labels (optional):**
Language Server, Bug, Priority/Medium?

**Comment by malinthar** [comment]
According to the [spec](https://ballerina.io/spec/lang/master/#section_6.35) we can have multiple `form-clauses` in a query pipeline.
