### ISSUE TITLE
[Testerina] Validate mocking imported functions when module is imported in submodules

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#29833]
**Description:**
Function mocking throws a bad-sad error when a function is mocked in a project where the module is not imported. 

eg. Mocking io:println when the io module is not imported in the current module.  

The compile checks pass however at the desugar level it fails to obtain the function reference. 

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Reverted fix in latest staging branch due to failures in distribution : https://github.com/ballerina-platform/ballerina-lang/pull/30375

Compilation check fails for default module importing the function to mock. `parent.getImports()` is not applicable.

**Comment by Ibaqu** [comment]
This validation is dependent on using the function pointers in the test config annotation. When annotations support const types for function pointers, the validation will be handled by the function pointer improvement. 

This issue cannot be resolved at the desugar level for the same reason, as the BLangImportPackage for functions imported in the submodules is not resolvable for the default module and vice versa

**Comment by Ibaqu** [comment]
https://github.com/ballerina-platform/ballerina-spec/issues/815

**Comment by azinneera** [comment]
This is not an ordinary scenario since the user will usually want to mock a function that is used in the source code which means the import is already added to the module.
