### ISSUE TITLE
AsyncAPI support in Ballerina

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#29849]
Created this issue to discuss more on supporting AsyncAPI in Ballerina. 
https://www.asyncapi.com/

**Comment by MaryamZi** [comment]
We now have
https://github.com/ballerina-platform/asyncapi-tools
https://github.com/ballerina-platform/asyncapi-triggers

**Comment by anupama-pathirage** [comment]
Closing as per the above comment
