### ISSUE TITLE
Check compatibility of coverage XML with VSCode code coverage plugins

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#29852]
**Description:**
Check compatibility of coverage XML with VSCode Coverage Gutters plugin

**Describe your task(s)**

Coverage gutters

- [ ] Check if code highlighting is working
- [ ] Check the need of path fixes

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Coverage gutters

Noticed the below error.

```
[1617688185016][coverageparser][jacoco-parse]: Error: filename: /Users/dilhashanazeer/Documents/StdLibs/module-ballerina-url/url-ballerina/target/report/url/coverage-report.xml Cannot read property 'map' of undefined
[1617688185016][coverageparser][jacoco-parse]: Stacktrace: TypeError: filename: /Users/dilhashanazeer/Documents/StdLibs/module-ballerina-url/url-ballerina/target/report/url/coverage-report.xml Cannot read property 'map' of undefined
```

When searching for a solution, came across the following similar issue and it seems that the jacoco XML parser(i.e. https://github.com/vokal/jacoco-parse) used by coverage gutters plugin is deprecated. The last supported jacoco version is '0.7.9'. But, the version used by Testerina is '0.8.5'.
https://github.com/ryanluker/vscode-coverage-gutters/issues/217

**Comment by Dilhasha** [comment]
I have done the following to see whether we can dump and use the coverage report in lcov format since many vscode code coverage plugins support the lcov format.

1. Try to dump the coverage report in lcov format.

Noticed that the resources to generate the code coverage report in lcov format are very limited. There is no straightforward way to generate a lcov report from Jacoco. So, we have to maintain our own lcov Formatter and process and pass the information needed explicitly to the lcov Formatter. Please refer to the diff in [1].

[1] https://www.google.com/url?q=https://github.com/ballerina-platform/ballerina-lang/compare/master...Dilhasha:try-lcov?expand%3D1&sa=D&source=editors&ust=1619032755797000&usg=AOvVaw1oXfESpqLHe14nYWb_TXBi

2. Evaluate the performance impact from the Jacoco code coverage XML generation

**Graphql ballerina module (A multi module ballerina project)**

**_Tests + Jacoco XML + Testerina json_**

real    0m21.193s
user    0m35.955s
sys     0m2.857s

Time elapsed = 21.193s
Total CPU time = 38.812s

**_Tests + Testerina json_**

real    0m17.545s
user    0m27.386s
sys     0m1.700s

Time elapsed = 17.545s
Total CPU time = 29.086s

**_Diff_**

Time elapsed diff = 3.648s
CPU time diff = 9.726s


**IO**

**_Tests + Jacoco XML + Testerina json_**

real    0m20.355s
user    0m27.043s
sys     0m1.619s

Time elapsed = 20.355s
Total CPU time = 28.662s

**_Tests + Testerina json_**

real    0m18.020s
user    0m24.767s
sys     0m1.485s

Time elapsed = 18.020s
Total CPU time = 26.252s

**_Diff_**

Time elapsed diff = 2.335s
CPU time diff = 2.41s

**Comment by Dilhasha** [comment]
If we are to provide an option for lcov format, we need to maintain and support it from the test framework. Moreover, there will be an additional resource usage.

**Comment by hevayo** [comment]
Lets add a flag to point out what format the coverage file should be.

**Comment by Dilhasha** [comment]
Created a separate issue to track adding the flag https://github.com/ballerina-platform/ballerina-lang/issues/30381
