### ISSUE TITLE
Implement full build pipeline

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#29896]
**Description:**
We need to have a GitHub Action workflow to build all the repositories from ballerina-lang repository to ballerina-distribution repository. There we need to change versions to SNAPSHOT and publish each other using maven local.

**Comment by keizer619** [comment]
This is not required anymore

**Comment by NipunaMadhushan** [comment]
Implemented full build pipeline for ballerina. 
Developer can select the branch of the ballerina-lang to trigger workflow.
https://github.com/ballerina-platform/ballerina-release/pull/1070
