### ISSUE TITLE
[LS] Update documentation doesn't support multiline descriptions for parameters, return and deprecated description

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29912]
**Description:**
$subject

Right now, if a user writes multiline descriptions for parameters, return or deprecated description; once the documentation is updated with `Update documentation` code action, the newlines will be malformatted.

Consider this, where a new param `b` has been added to the function `nameIt()`. Here the `update documentation` will be suggested.
```
class ClassName {
    public int name = 10;

    # This is a test method within a class
    #
    # # Deprecated
    # This method is deprecated
    # And another line
    @deprecated
    public function nameIt(int b) {

    }
}
```
When the code action is executed:
```
class ClassName {
    public int name = 10;

    # This is a test method within a class
    #
    # + b - Parameter Description
    # # Deprecated
    # This method is deprecated
And another line
    @deprecated
    public function nameIt(int b) {

    }
}
```
Note the line above `@deprecated` line.

**Steps to reproduce:**
See above description

**Affected Versions:**
SLA5 SNAPSHOT

**Suggested Labels (optional):**
Language Server

**Suggested Assignees (optional):**
IMS94

**Comment by nadeeshaan** [comment]
Shouldn't the missing `#` be available with the parsed content?
