### ISSUE TITLE
Incorrect position given for incorrect rest field

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29949]
Consider the following snippet:
```ballerina
type Person record {
    string name;
    int mbp2;
    string...;
};
```
Get the following error for the above:
```
open record cannot contain rest field
```
There are 2 issues here.
- Wrong position given for the error. The position given is the position of the field above the rest field. The error should be given to the rest field itself.
- Misleading error message. It says that an open record cannot contain a rest field. But this terminology is slightly incorrect. The error here is that a rest field is included in an inclusive record type descriptor. That's what's not allowed. An open record can be either an inclusive record typedesc or an exclusive record typedesc with a rest field.

Also note that since the position is wrong, the error highlighting in the VS Code plugin is also wrong.

**Comment by lochana-chathura** [comment]
> Wrong position given for the error. The position given is the position of the field above the rest field. The error should be given to the rest field itself.

This is causing due to a known issue with the parser diagnostics for the invalid nodes. #24765

> Misleading error message. It says that an open record cannot contain a rest field. But this terminology is slightly incorrect. The error here is that a rest field is included in an inclusive record type descriptor. That's what's not allowed. An open record can be either an inclusive record typedesc or an exclusive record typedesc with a rest field.

ACK.

**Comment by rdulmina** [comment]
The first one is a known issue #24765
For the second one, will something like `Inclusive record type descriptor cannot contain rest field` appropriate?

**Comment by pubudu91** [comment]
> The first one is a known issue #24765
> For the second one, will something like `Inclusive record type descriptor cannot contain rest field` appropriate?

Yes. We generally avoided using the terms "inclusive record typedesc" and "exclusive record typedesc" in error messages, docs etc. But in this case, I think we may have to use those terms 🤔

**Comment by rdulmina** [comment]
> > The first one is a known issue #24765
> > For the second one, will something like `Inclusive record type descriptor cannot contain rest field` appropriate?
> 
> Yes. We generally avoided using the terms "inclusive record typedesc" and "exclusive record typedesc" in error messages, docs etc. But in this case, I think we may have to use those terms thinking

Cool will update the error message
