### ISSUE TITLE
Broken Image in the IO Module Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#29946]
Need to fix the broken image in [1].

Now, docs are displayed through the \Central. In the ballerina-distribution repo, the BALAs are used to generate API docs and they are sent to the Central. Currently, resources like images are not being packed into the BALA.

[1] https://docs.central.ballerina.io/ballerina/io/0.6.0-alpha5

**Comment by shehan360** [comment]
Currently resources like images are not packed into the bala. We will need to pack them in the bala in order to show them.

**Comment by praneesha** [comment]
@shehan360 - Do we have the possibility to pack it or do we need to remove it from docs?

**Comment by azinneera** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/33746 we have supported specifying the icon in the Ballerina.toml under `package` table.

IMO, this can be used as a solution for this issue.

If it doesn't suffice, we will be supporting packaging a user-specified directory (https://github.com/ballerina-platform/ballerina-spec/issues/988) in a future release.

**Comment by azinneera** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/36877 a custom directory can be packaged into the bala. This can be used to pack additional resources required for the Ballerina Central.
