### ISSUE TITLE
Always have included open records as compile time errors

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#29945]
**Description:**
Currently the following code compiles without an issue:
```
public type Student record {
    string name;
};
public function main() {
    foo(name="riyafa");
}
function foo(*Student st) {
}
```
But the following code gives a compilation error:
```
public type Student record {
    string name;
};
public function main() {
    foo(name="riyafa", score =1);
}
function foo(*Student st) {
}
```
as 
```
ERROR [compiler.bal:(5:24,5:29)] too many arguments in call to 'foo()'
```
Note the `open` record `Student` in both cases. Using open records as included record should be a compile time error if the second scenario is invalid. Hence we need to provide compile time errors in both cases. This can be along the following lines:
```
Invalid use of open record type `Student` as  an included parameter.
```
Same issue is there when a rest field is present in a closed record.

**Describe your problem(s)**
Discussed above
**Describe your solution(s)**
Discussed above

**Comment by MaryamZi** [comment]
For included record parameters the [spec](https://ballerina.io/spec/lang/master/#function_call) says

> The arg-name of every named-arg must be distinct. Each named-arg must correspond to either a parameter that is not a rest-param or to a field of an included-record-param. In the latter case, there are two possibilities.
> 
> - The field is described by an individual-field-descriptor with a type that is not never.
> - The field is described by a record-rest-descriptor, either explicitly as part of an exclusive-record-type-descriptor or implicitly as part of an inclusive-record-type-descriptor. In this case:
>   - for every parameter name and every individual-field-descriptor of an included-record-param with a type that is not never, the record-type-descriptor must include an individual-field-descriptor that has type never and is optional, and so disallows a field with that name;
>   - **the record-type-descriptor must not include any other individual-field-descriptor;** and
>   - there must be no other included-record-param with a record-rest-descriptor.

https://github.com/ballerina-platform/ballerina-spec/issues/1021 was created to look into the possibility of relaxing this restriction.

Closing this issue since the current behaviour is in-line with the current spec.
