### ISSUE TITLE
A transitive dependancy error comes when building the project using docker container for SLAlpha4

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-lang#29963]
**Description:**
When a ballerina HTTP service is created and build using ballerina SLAlpha4 docker container it gives an error as
```
error: compilation failed: Transitive dependency cannot be found: org=ballerina, package=task, version=2.0.0-alpha8
```
The screenshot of the terminal is shown below.
![Screenshot from 2021-04-09 20-47-24](https://user-images.githubusercontent.com/34184297/114202683-0dff7180-9975-11eb-9cbb-7c1e7b21b499.png)

**Steps to reproduce:**
1. Create a new ballerina project
2. Create a simple HTTP service inside that. [BBE example](https://ballerina.io/learn/by-example/hello-world-service.html)
3. Build the project using the SLAlpha4 docker container

**Affected Versions:**
Ballerina SLAlpha 4

**OS, DB, other environment details and versions:**
Ubuntu 20.04 LTS
Ballerina SL Alpha 4
JDK 11

**Other references:**
 Find the link for the failed GitHub action of a similar build [here](https://github.com/sachinira/module-ballerinax-azure-cosmosdb/runs/2297566721?check_suite_focus=true).

**Comment by abeykoon** [comment]
@keizer619 , could you please prioritise this as it is a blocker for Alpha4 releases of the connectors?

**Comment by sachinira** [comment]
Closing the issue as this issue is fixed in the central manually.
