### ISSUE TITLE
Complement of integer literal

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#29976]
In slalpha4, I type:

```
~0
```

in the shell, it prints

```
0
```

which is of course wrong.  If I type

```
~(0)
```

it correctly print

```
-1
```

**Comment by jclark** [comment]
Happens outside the shell too:

```
import ballerina/io;

public function main() {
   io:println("~0 is ", ~0);
}
```

prints

```
~0 is 0
```

**Comment by chiranSachintha** [comment]
The following program  should give an error as `operator '!' not defined for 'int'` (currently this is compile fine)
```ballerina
public function main() {
    int a = !5;
}

```
