### ISSUE TITLE
Module cache is not updated, when removing modules from IDE

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29995]
Steps: 

- Create a project with a sub-module. 
- Then call one of the functions in that submodule from the main module. 
- Then delete that submodule.
- You can still see LS  suggestions for that module. See the following screenshot. This is taken after removing the `calc` submodule. 

![image](https://user-images.githubusercontent.com/1356214/114883773-d6843f80-9e22-11eb-939d-50c89e4e130f.png)

**Comment by nadeeshaan** [comment]
Tested locally and observed this is working. Can you confirm that there is a similar log in the output channel as following

`[Info  - 10:21:38 AM] Operation 'workspace/didChangeWatchedFiles' {module: 'testmod', uri: 'file:///.../testmod'} removed`

**Comment by IMS94** [comment]
@hasithaa could you check this in the latest release and see if it's reproduced.

**Comment by malinthar** [comment]
Could not reproduce this in the latest

**Comment by sanjana** [comment]
Closing since this issue has been fixed in the SL Beta 1.
