### ISSUE TITLE
[Semantic API] A symbol is returned for wild card binding pattern

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#30000]
Consider the following:
```ballerina
_ = 3.14;
```
If check for `_`'s symbol, we'd get a var symbol for it. Do we need a symbol for it or should we just return empty?

**Comment by sanjana** [comment]
The Syntax Tree Visualization of the above code segment is as following: 

![image](https://user-images.githubusercontent.com/9464997/117244524-d04c1680-ae56-11eb-8d78-b2a08a5d26e5.png)

Also, in the `SymbolEnter` stage, the `_` is a typeNode of `BLangUserDefinedType`. 
The `varNode` is `other $missingNode$_0 = 3.14`.

**Comment by pubudu91** [comment]
The above behaviour is correct. The wild card binding pattern cannot be used at the module level. `_ = 3.14;` is a [destructuring assignment statement](https://ballerina.io/spec/lang/master/#section_7.14.4).

**Comment by sanjana** [comment]
@pubudu91 if we shouldn't return a symbol, then does it need to return `null` instead of the `_` if we check the symbol at cursor?

**Comment by pubudu91** [comment]
> @pubudu91 if we shouldn't return a symbol, then does it need to return `null` instead of the `_` if we check the symbol at cursor?

Yes. No need to have a symbol for the wild card. So can just return `null`.
