### ISSUE TITLE
Support mock backend initialization and start before module init phase

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#30006]
**Description:**
In the current mock implementation in the test framework, the mocking is done after the module initialisation for the ballerina package. 
We need a way to do this before module initialisation to cater for the clients to make calls to backend during initialisation for various optimisations.

**Describe your problem(s)**
Please refer https://github.com/ballerina-platform/ballerina-lang/issues/29901# for one such requirement.

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
This can be supported if we can mock 'new()'

**Comment by azinneera** [comment]
Closing since there is a solution for this as mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/29901#issuecomment-824920940
