### ISSUE TITLE
When writing unit tests with expressions that always evaluate to true, an NPE is thrown

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#30017]
**Description:**
When adding unit tests to master with expressions that always evaluate to `true`, an `NPE `is thrown. Need to investigate the cause for this.

```ballerina
function func() returns int {
    return 1;
}

public function test() {
    boolean b = func is function () returns int;
    panic error(string `${b}`);
}
```
The above example throws an NPE at https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/AnnotationUtils.java#L112

```ballerina
public function test() {
    int a = 12;
    boolean b = a is int;
    panic error(string `${b}`);
}
```
The above example throws an NPE at https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/TypeChecker.java#L2524

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Probably same as this https://github.com/ballerina-platform/ballerina-lang/issues/29887
