### ISSUE TITLE
Bad, sad from use of readonly

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30025]
See attached.

This goes away if `ops` is declared as `final BasicTypeOps[] ops`.

[semtype.zip](https://github.com/ballerina-platform/ballerina-lang/files/6325262/semtype.zip)

**Comment by MaryamZi** [comment]
Seems to happen when the field of the record is a function type. 

Reproducible with
```ballerina
type Foo record {|
    function () f;    
|};

public function main() {
    Foo & readonly x = {f: main};
}
```
