### ISSUE TITLE
Enable test failing due to changes to supported types of main function

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#30037]
**Description:**
The test MappingConstructorExprTest.testSpreadOpFieldTaintAnalysisNegative is disabled in the master because of the recent compilation checks added to the master to limit the supported types of the main parameters.

**Describe your task(s)**
Fix or replace the test https://github.com/ballerina-platform/ballerina-lang/blob/3f186a7d32e828ee2d27c2d771c4b3ee4ef18f54/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/expressions/mappingconstructor/MappingConstructorExprTest.java#L218
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/29829

**Comment by MaryamZi** [comment]
Enabled on https://github.com/ballerina-platform/ballerina-lang/tree/fix-and-enable-tests in #30281.

Will be merged to master via a separate PR.
