### ISSUE TITLE
Type reference in the error constructor should consider as the contextually expected type for the error

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#30035]
**Description:**
From https://github.com/ballerina-platform/ballerina-lang/pull/29059#discussion_r613936786

Following should be allowed.
```ballerina
type ErrorOne error<record {| int i; |}>;
type ErrorTwo error<record {| int j; |}>;

type Error ErrorOne|ErrorTwo;

public function main() {
    error x = error Error("", i = 1); // Here the contextually expected type for the error constructor is `Error`
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Spec issue https://github.com/ballerina-platform/ballerina-spec/issues/817

**Comment by MaryamZi** [comment]
The current behaviour seems to be correct according to the spec issue.
