### ISSUE TITLE
Integrate Ballerina Shell with lang server to provide better tab completion

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#30054]
**Description:**
Currently Ballerina Shell only provides a fixed set of keywords as the tab completions.
It would be better if we can use lang server to provide better tab completions.

Eg:
```ballerina
=$ int var3 = 4;
=$ va[TAB]  // should suggest var3
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**
`Area/Shell`

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
In order to have the language server integrated with the shell will be cumbersome since we need to have a shell client implemented similar to the Vim language client. Instead we can only consider the completion implementation specific to the shell use-case.

**Comment by gayalkuruppu** [comment]
Maybe we can try another approach. For example `jshell` and `python` shells provide variable completions(OP) and other intelligent completions for ex: 

<img width="768" alt="Screenshot 2022-06-27 at 17 38 43" src="https://user-images.githubusercontent.com/46120162/175938259-4ae3370c-1655-4b7b-9357-1aaa7083e7fc.png">

<img width="674" alt="Screenshot 2022-06-27 at 17 41 04" src="https://user-images.githubusercontent.com/46120162/175938129-c33dfd58-968d-4748-9c2a-74f2e973dd23.png">

We can check their approach and get an idea. They do not seem to use a language server for this.

**Comment by mohanvive** [comment]
Not planning to prioritise now.
