### ISSUE TITLE
Enable Ballerina Shell to persist the commands to a file and rerun files similar to jshell

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#30058]
**Description:**
Similar to `jshell` it would be better if there was a command to directly save the commands up to then into a file so that it can be run directly via shell. This would serve as a way to easily save work done in the shell.

Eg: For example in jshell,
```java
jshell> int i = 3
i ==> 3

jshell> i + 3
$2 ==> 6

jshell> string p = "Hello World"
|  Error:
|  cannot find symbol
|    symbol:   class string
|  string p = "Hello World";
|  ^----^

jshell> String p = "Hello World"
p ==> "Hello World"

jshell> p
p ==> "Hello World"

jshell> /save file1.jshell
```

Will produce file with content

```text
int i = 3;
i + 3
String p = "Hello World";
p
```
And when we run it via jshell again we don't get expression results but the variables/etc... get created and modified.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**
`Area/Shell`

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Not planning to prioritise this improvement now.
