### ISSUE TITLE
Cannot run ballerina while being a directory with a space. e.g. "Program files"

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#3005]
When the ballerina distribution is in a location with a space to the folder name (e.g. "Program files") the ballerina run command is not working

**Error**
`ballerina: error while loading built-in package 'ballerina/lang/errors/'. Illegal character in opaque part at index 20: jar:file:/C:/Program Files/ballerina-tools-0.90/bre/lib/ballerina-native-0.90.ja
r`

**Workaround**
Save the ballerina distribution in a folder without a space

**Comment by uthaiyashankar** [comment]
This problem is no longer there.
