### ISSUE TITLE
Fix error for types that are not yet supported with constant declaration

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#30073]
**Description:**
$title
```ballerina
public const int:Signed32 BT_INT = 1;
```
ATM the above gives the following compilation error,
`constant cannot be defined with type 'int:Signed32', expected a simple basic types or a map of a simple basic type`
This needs to be updated.

**Describe your task(s)**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/21542

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by jclark** [comment]
There's no difference between:

```
public const int:Signed32 BT_INT = 1;
```

and

```
public const int BT_INT = 1;
```

and

```
public const BT_INT = 1;
```

See https://ballerina.io/spec/lang/master/#section_8.8

The type of a constant is always a singleton. In all the above cases, the type is `1`.

**Comment by MaryamZi** [comment]
Agreed, @jclark. 

The issue with something like `public const int:Signed32 BT_INT = 1;` right now is that we haven't implemented support for defining constants with builtin subtypes yet, but the error we log is

```
ERROR [test.bal:(1:14,1:26)] constant cannot be defined with type 'int:Signed32', expected a simple basic types or a map of a simple basic type
```

even though this is valid according to the spec.

As the first step, we will be fixing this error to say it is not supported yet. This is also the case for some of the other types we don't support as constants yet.
