### ISSUE TITLE
Improving Build Performance by reducing Central requests

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#30084]
**Description:**
In the current implementation of package version resolution logic we need to query ballerina Central multiple times. The times needed to query the central will increase with the number of import you have in the program. This performance hit will come when you build a program first time when Dependencies.toml is not percent. 

Currently for each module build will call two separate calls to the central. 
1. If the module has dot in its name ie "foo.bar" it will call central to resolve the package name of the module. 
2. If the import version is not specified it will call central to find the latest version of the package. 

As an optimization we can resolve the package and the latest version with a single call. This will significantly reduce the build time by reducing the network calls. A typical central request will take around  500ms. 

In-order to implement the above we need to add some support to central as well.

Affected Version 
slalpha5

**Comment by azinneera** [comment]
With beta3, the following improvements has been done to minimize calls to central:
1. Fetching all the dependencies' metadata in a single call and only query again if there is conflicting versions in the dependency graph
2. Run the subsequent builds in sticky mode for 24 hours to use package cached locally

After this improvement, we observed a drop of about 7 seconds for the second build when testing the nballerina package

Package resolution in Beta2 for 2nd compilation: 7984ms
Package resolution in Beta3 for 2nd compilation: 675ms
