### ISSUE TITLE
TypeDescKind of the type-descriptor of ExplicitNewExpressionNode is invalid

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#30090]
**Description:**
* I am currently writing a compiler plugin for `websubhub module` and I need to validate the parameters provided for `websubhub:Listener` init method. For this requirement I have written a simple node visitor to collect all the explicit / implicit new expressions and filter out only the `websubhub` listeners. But for explicit new expression node type-descriptor gives a `TypeDescKind.UNION` even though it should provide `TypeDescKind.OBJECT`. 

**Steps to reproduce:**
* Try implementing a simple node visitor to collect all listener initialization with explicit new expressions. The `visit` method implementation could be like follows.
```ballerina
    public void visit(ExplicitNewExpressionNode node) {
        QualifiedNameReferenceNode nameRef = (QualifiedNameReferenceNode) node.typeDescriptor();
        Optional<Symbol> symbolOpt = context.semanticModel().symbol(nameRef);
        if (symbolOpt.isPresent() && symbolOpt.get() instanceof TypeReferenceTypeSymbol) {
            TypeSymbol typeSymbol = ((TypeReferenceTypeSymbol) symbolOpt.get()).typeDescriptor();
            if (typeSymbol.typeKind() == TypeDescKind.OBJECT) {
               ObjectTypeSymbol objectSymbol = (ObjectTypeSymbol) typeSymbol;
               Optional<ModuleID> moduleId = objectSymbol.getModule().map(ModuleSymbol::id);
               String identifier = objectSymbol.getName().orElse("");
               if (moduleId.isPresent() && isWebSubHubListener(moduleId.get(), identifier)) {
               	explicitNewExpressionNodes.add(node);
               }
           }
        }
    }
```

**Affected Versions:**
* Ballerina Lang - 2.0.0-alpha8-20210419-135100-df7a4e3f

**OS, DB, other environment details and versions:**
* Ubuntu 20.04 LTS

**Comment by pubudu91** [comment]
Fixed with #30154
