### ISSUE TITLE
Subtype error with recursive rest tuple type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30113]
In slalpha4, this gets a compile-time error:

```
type MyRecType int|[MyRecType...];

public function main() {
  MyRecType d = [1, 2, 3];
  json j = d;
}
```

If `[MyRecType...]` is replaced by `MyRecType[]`, the error goes away.

**Comment by MaryamZi** [comment]
Seems to be due to https://github.com/ballerina-platform/ballerina-lang/issues/22244.
