### ISSUE TITLE
Type references make fromJsonWithType fail

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30110]
This gets a runtime error, when it shouldn't:

```
type Foo [Bar...];
type Bar string;

public function main() returns error? {
   json j = ["foo"];
   Foo f = check j.fromJsonWithType();
 }
```

It works if the definition of Foo is changed to:

```
type Foo [string...];
```

**Comment by gabilang** [comment]
It looks like the issue has been solved with beta-2

**Comment by warunalakshitha** [comment]
We have fixed few issues related to fromJsonWithType with https://github.com/ballerina-platform/ballerina-lang/pull/30665 for beta 2 and this seems fixed too. I am closing this as per @gabilang  comment. Please reopen if you have any other concerns.

**Comment by warunalakshitha** [comment]
We have fixed few issues related to fromJsonWithType with https://github.com/ballerina-platform/ballerina-lang/pull/30665 for beta 2 and this seems fixed too.

@gabilang Shall we write a test case for this?
