### ISSUE TITLE
Value equality checks produce incorrect results at runtime for numeric values of different basic types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30135]
**Description:**
$title. io.ballerina.runtime.internal.TypeChecker#isEqual(java.lang.Object, java.lang.Object, java.util.List<io.ballerina.runtime.internal.TypeChecker.ValuePair>) returns incorrect answers.

This seems to have been changed in https://github.com/ballerina-platform/ballerina-lang/commit/3bde69dfcb23dd381eb25a256cb16aab10a336ee#diff-1b3d31c221969697c68318cd01f8eb7554016483f8c961b6a857461b9072cfb3R1148 (for other numeric types too) for type cast support. But the behaviour is different for equality checks and type casts.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main() {
    // int i = 12;
    // boolean b = i == 12.7; // operator '==' not defined for 'int' and 'float'

    anydata x = 12;
    io:println(x == 12.7); // Prints `true`!
}
```

**Affected Versions:**
slalpha4

**Comment by warunalakshitha** [comment]
As per spec Two values v1 and v2 are exactly equal if they have the same basic type T and T is simple type, and v1 and v2 are identical values within the possible of values allowed for T;

So AFAIU that means int a = 12 and float b = 12 , a == b -> false since not same type. only exception would be with bytes

**Comment by MaryamZi** [comment]
Yeah, if they are of different basic types the `==` check should evaluate to false.

```ballerina
import ballerina/io;

public function main() {
    int a = 12;
    anydata b = a;
    float c = 12;
    anydata d = c; 
    io:println(b == d); // Currently prints `true`.
}
```

`byte` is a subtype of `int`, so the basic type is still `int`. So a == check for a `byte` value and an `int` value is basically a comparison of two `int` values, which satisfies the "same basic type" requirement.
