### ISSUE TITLE
Codecov PR comment shows a code coverage reduction with new Native code

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#30155]
**Description:**

Codecov PR comment shows a drastic coverage reduction with new Native code.

Check https://github.com/ballerina-platform/module-ballerinax-mysql/pull/104

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30189

**Comment by Dilhasha** [comment]
This is the code coverage for the above mentioned PR after applying the fix.
https://codecov.io/github/Dilhasha/module-ballerinax-mysql/commit/c947cef62a5e39723e7031c83874d6f0fae07431

**Comment by lahirusamith** [comment]
the PR is now having sufficient codecov figures to merge.
