### ISSUE TITLE
== should narrow type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30165]
With slalpha4 the compiler rejects this program:

```
function foo(string? s) returns string {
  if s == () {
    return "";
  }
  else {
     return s;
  }
}
```

But it's correct because the spec says:

> If E has the form x == E1 or E1 == x where the static type of E1 is an expression whose static type is a singleton simple type T1, then
the narrowed type for x implied by truth of E is the intersection of Tx and T1
the narrowed type for x implied by falsity of E is Tx with T1 removed

So the type of s in the else clause is (string? - ()) which is string.

**Comment by jclark** [comment]
The workaround is to use `s is ()` instead.

@hasithaa Even though there is a workaround, this should be high priority, because it is something that even beginning users will come across.

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/18167

**Comment by jclark** [comment]
Also relates to https://github.com/ballerina-platform/ballerina-spec/issues/814
