### ISSUE TITLE
An unnecessary error is reported when a value is not supplied for a mandatory configurable variable in a sub module 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#30163]
Say there exists a submodule in a package, and that module contains a mandatory configurable variable. When a value is not supplied via `Config.toml`, I get the following errors. The second error is misleading and unnecessary

```
error: value not provided for required configurable variable 'name'
error: [Config.toml:(1:1,11:16)] invalid module structure found for module 'config1.log'. Please provide the module name as '[config1.log]'
```

My `Config.toml` does not contain any configuration values related to the submodule.

**Comment by manuranga** [comment]
I think ideal would be
```
error: [MyConfig.toml] value not provided for required configurable variable 'config1.log.name'
```
@HindujaB  Will that be implementable under current design?
