### ISSUE TITLE
Cannot compile with slalpha5

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30197]
I was unable to compile my project (https://github.com/jclark/semtype) with slalpha5.  I upgraded with `bal dist pull slalpha5`.

When I build I get:

```
ERROR [print.bal:(83:5,83:28)] mismatched visibility qualifiers for field 'insertions' with object type inclusion
```

which is weird, because I do not have a file `print.bal` (nor any field called `insertions`).

**Comment by jclark** [comment]
My Dependencies.toml included

```
[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha7"
```

@sameerajayasoma suggested deleting this, and that fixed the problem.

**Comment by sameerajayasoma** [comment]
This error message is not descriptive enough. We need to include the module name.

Looping @azinneera @hasithaa

**Comment by jclark** [comment]
I didn't add anything to `Dependencies.toml`.

From the user perspective, the update caused my correct program to stop working.

**Comment by hasithaa** [comment]
Can you remove this dependency and also delete the `target/` directory. Then call `bal build` again. This issue was identified with the previous version as well.

**Comment by jclark** [comment]
When I try and delete the target directory I get an error:

```
C:\Users\jjc\Documents\baltest\semtype\target\cache\jjc\semtype\0.1.0\java11\semtype.jar
The process cannot access the file because it is being used by another process.
```

which is weird, because I don't think any other program is accessing it.

**Comment by jclark** [comment]
I had about ten java processes hanging around using semtype.jar. Not sure why that is happening. I didn't ever run java.exe myself: only via `bal` and visual studio code.

Sometimes when I try to stop a debugging session, it doesn't work and I get a timeout. Maybe that is related.

**Comment by hasithaa** [comment]
Yes, That could be an issue. @NipunaRanasinghe Could you please check this?

**Comment by NipunaRanasinghe** [comment]
@hasithaa Seems this process hanging issue is happening only on windows (all the sub-processes are getting terminated properly in both ubuntu and macOS environments). I'll prioritize this issue for the coming release.

**Comment by NipunaRanasinghe** [comment]
@jclark @hasithaa We have found a Windows-specific debugger issue, where the debug server hangs when trying to resolve ballerina test sources, which leads to the remote VM not being terminated properly. We have already merged the fix with https://github.com/ballerina-platform/ballerina-lang/pull/30535 and will be available with the coming SL beta1 release.

**Comment by NipunaRanasinghe** [comment]
@jclark @hasithaa Could you please verify that the aforementioned debugging issues are fixed with the latest (SLBeta1) release? (I hope we can close this issue if so)

**Comment by jclark** [comment]
You can clone https://github.com/ballerina-platform/nballerina, then build and debug in the `compiler` subdirectory. It needs the name of a file to compile: examples `.bal` files  in the `test` directory.

**Comment by NipunaRanasinghe** [comment]
> You can clone https://github.com/ballerina-platform/nballerina, then build and debug in the `compiler` subdirectory. It needs the name of a file to compile: examples `.bal` files in the `test` directory.

Looping in @manuranga @ruvi-d

**Comment by NipunaRanasinghe** [comment]
> You can clone https://github.com/ballerina-platform/nballerina, then build and debug in the `compiler` subdirectory. It needs the name of a file to compile: examples `.bal` files in the `test` directory.

Looping in @manuranga @ruvi-d

**Comment by manuranga** [comment]
@NipunaRanasinghe 
SemType code is now in nballerina repo. It's a 100% ballerina code base, test it as if you'd test any other user code. If original bug doesn't exist when debug it under windows, you may close this issue.

**Comment by NipunaRanasinghe** [comment]
Closing the issue as the debugging related issues are fixed with SLBeta1 release (Tested the bBallerina compiler program on SLBeta1 and both the program debugging and test debugging sessions are getting terminated gracefully). @jclark Please feel free to reopen/create issues if you still experience any complications with the latest release.
