### ISSUE TITLE
Invalid symbol name generated for incomplete xml namespacedeclaration

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30198]
**Description:**
Consider the following incomplete source snippet.
```
import ballerina/module1;

public const STRING_CONST = "http://ballerina.com/";
public const INT_CONST = 1234;

xmlns 
```
Here we create a symbol for the xml namespace declaration as well as the created symbol's name is an empty string.

**Comment by KavinduZoysa** [comment]
Now, this is working as expected. Hence we can close this issue.
![Screenshot from 2023-02-28 10-30-40](https://user-images.githubusercontent.com/28332708/221759484-2c8f63ca-754e-4e6f-8093-64e1652e14dd.png)
