### ISSUE TITLE
Comments added to `Dependencies.toml` will not persist after build

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#30209]
**Description:**
$Title

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
Blocked with https://github.com/ballerina-platform/ballerina-lang/issues/30231

**Comment by azinneera** [comment]
Closing the issue since this is not relevant anymore.

After SL Beta3, the nature of the Dependencies.toml is changed. It is considered to be an auto-generated file and hence the user is not expected to edit it.
