### ISSUE TITLE
Two incompatible versions exist in the dependency graph

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-lang#30215]
**Description:**
```
import ballerina/log;
import ballerinax/googleapis_calendar as calendar;

configurable string clientId = ?;
configurable string clientSecret = ?;
configurable string refreshToken = ?;
configurable string refreshUrl = ?;

public function main() returns error? {

    calendar:CalendarConfiguration config = {
        oauth2Config: {
            clientId: clientId,
            clientSecret: clientSecret,
            refreshToken: refreshToken,
            refreshUrl: refreshUrl
        }
    };
    calendar:Client calendarClient = check new (config);

    stream<calendar:Calendar,error> resultStream = calendarClient->getCalendars();
    record {|calendar:Calendar value;|}|error? res = resultStream.next();
    if (res is record {|calendar:Calendar value;|}) {
        log:printInfo(res.value["id"]);
    } else {
        if (res is error) {
            log:printError(res.message());
        }
    }
}
```

This is written in a single ballerina file in SL Alpha4.

The latest version of ```ballerinax/googleapis_calendar``` in central is written in SLAlpha 4.
But the latest version of ```ballerinax/log``` in central is written in SLAlpha 5.

So, it gives the following error:
```
error: compilation failed: Two incompatible versions exist in the dependency graph: ballerina/log versions: 1.1.0-alpha8, 1.1.0-alpha7
```
Before the release of SL Alpha 5, this issue was not there.
But after the release of SL Alpha 5, when i write a program in SLAlpha 4, this error happens.

If we write a ballerina project, we will be able to give the versions in Dependencies.toml file.
But for a single ballerina file, can we solve this issue?

**Steps to reproduce:**
Try to run this sample in SL Alpha 4
https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar/blob/main/samples/get_calendars.bal

**Affected Versions:**
Ballerina SL Alpha 4

**Comment by azinneera** [comment]
Fixed in SLBeta1.
