### ISSUE TITLE
Annotations on return type not supported in function type descriptors

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#30219]
Consider the following:
```ballerina
function testFnTypedesc() {
    function () returns @a1 {desc: "In a typedesc"} string fn;
}
```
The above is syntactically valid. But we currently just ignore the annotations attached to the return type of a function type descriptor. i.e., it's not considered in `BLangFunctionTypeNode`.

**Comment by pubudu91** [comment]
Once this is fixed, enable the commented test in `FunctionSymbolTest`

**Comment by MaryamZi** [comment]
This doesn't result in a compilation error (when the annotation `a1` is undefined) on 2201.0.0. The annotation attachment is probably not even validated.

**Comment by MaryamZi** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/18207.
