### ISSUE TITLE
Able to push a package with a local repo dependancy to central

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#30235]
**Description:**
Even though a similar package name does or does not exist in central, should not be able to push a package with a local dependency to the central. Currently, it's allowed to push for both scenarios.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
As the fix the central should validate if the dependent packages should exists in central before accepting push.

**Comment by hevayo** [comment]
Fix: Add repository to dependencies-graph.json and modify push command to check if there are any other repositories before pushing to central.

**Comment by pramodya1994** [comment]
When checking the feasibility of accessing the repository from the `BalaWriter`, Found that the repository can be added to the `ResolvedPackageDependency` from `PackageDependencyGraphBuilder` L 169. 

But there is a problem when handling this use case against private repositories.

**Comment by azinneera** [comment]
With the refactored package resolution design, we do not add the repository in the dependency-graph.json. Also, the central validates the existence of the dependencies of the package being pushed. Therefore, this is not considered a bug.
