### ISSUE TITLE
Same dependancy version from two repos should not be compatible

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#30236]
**Description:**
Eg:
`A depends on IO from local`
`A depends on B from local`
`B depends on IO`
Should not be able to build

But it will give following error:
```
Compiling source
	xxx/a:0.1.0
ERROR [b.bal:(4:5,4:31)] undefined function 'println'
error: compilation contains errors
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
The following scenario was tested in the following manner with projects `A`, `B` and `C`

`C` is a project with a function `printHello()` that is published to central. 
- A change is made to the printHello() function and pushed to local. 

`B` imports `C` from central
- `B` has a function `print()` that calls `C:printHello()`
- This prints the content pushed previously to central

`A` imports both `B` and `C (local)`
- `A` calls `B:print()` and `C:printHello()`

The result: the `B:print()` resolves to `C (local)`  and not from central. 

As such the following behaviour works without any compilation issues. As discussed this behaviour will need to be revisited and the spec will have to be re-evaluated

**Comment by Ibaqu** [comment]
Depends on : https://github.com/ballerina-platform/ballerina-lang/issues/31180

**Comment by azinneera** [comment]
This is fixed with the new package resolution design.
