### ISSUE TITLE
RecordFieldSymbol's TypeDescriptor does not carry toplevel type information

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#30245]
**Description:**

<img src="https://user-images.githubusercontent.com/35211477/116401016-60330480-a848-11eb-9561-1806ad526844.png" width="400" height="200" />

In the code segment depicted above, we have a `TYPE_REFERENCE` symbol (`Age`) defined  and used as  a field type in the record definition(`ageRecord`).  Here, when we access `fieldDescriptors` of `ageRecord`  we retrieve `int` as the `typeKind` of the `TypeDescriptor` of the `RecordFieldSymbol` corresponding to `age`  field. (instead of type `Age`). We want this top-level type information in providing some of the features of LS. The behavior is same for other field types as well. (table, map,etc)

**Comment by pubudu91** [comment]
This is unfortunately due to a limitation in the current compiler implementation. This is captured in #26284.

**Comment by malinthar** [comment]
> This is unfortunately due to a limitation in the current compiler implementation. This is captured in #26284.

@pubudu91  ack

**Comment by pubudu91** [comment]
Checked this with Chiran's PR, and this seems to get resolved with it. Note the type of `age` below. However, best to test a bit more with the Semantic API.
<img width="582" alt="Screenshot 2021-10-30 at 00 17 04" src="https://user-images.githubusercontent.com/6260009/139486786-aa9fce1a-a26d-4989-9495-686bdc81d003.png">
