### ISSUE TITLE
No completions are provided for field access experssions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30242]
**Description:**
Consider the following source snippet and no completions are provided at the cursor position.

`string header = "+ ".'join('join(" + ", headers)).j<cursor>` Completions are not provided

**Affected Versions:**
sl-alpha5 at least

**Comment by dulajdilshan** [comment]
Related discussion https://github.com/ballerina-platform/ballerina-lang/pull/30778#discussion_r641318484

**Comment by dulajdilshan** [comment]
The same error occurs for this.

```ballerina
public function main() {
    string[] hello = ["a", "b"];
    int[] mapResult = hello.'map(function (string a) returns int {
        return 12;
    }).<cursor>
}
```
