### ISSUE TITLE
Refactor `isSymbolDefinedInRootPkgLvl` to handle types correctly

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#30262]
**Description:**
Please refer discussion https://github.com/ballerina-platform/ballerina-lang/pull/28955#discussion_r589956084

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Also see https://github.com/ballerina-platform/ballerina-lang/issues/30268
