### ISSUE TITLE
Update Tool Not Updated with the Distribution

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#30261]
Currently, when a Ballerina distribution is updated, the "update tool" itself is not updated, nor it is prompting the user to do so. This sometimes ends up in incorrect behavior, e.g. cache related issues that was observed (which was fixed after updated the update tool). We need a mechanism to make sure the update tool is updated properly with the distributions.

**Comment by keizer619** [comment]
We will do following improvement to update the tool along with dist pull/update
https://github.com/ballerina-platform/ballerina-update-tool/issues/152
