### ISSUE TITLE
Cannot have a variable named "error"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30268]
**Description:**
$title, but it is possible to have parameters named "error".

**Steps to reproduce:**
```ballerina
public function main() {
    error 'error = error("error!"); // ERROR: redeclared builtin symbol 'error'
}

function func(error 'error) { // OK

}
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/30262

**Affected Versions:**
slalpha5

**Comment by dilanSachi** [comment]
```ballerina
int 'anydata = 1;
int 'json = 2;
```
results in the same issue

**Comment by MaryamZi** [comment]
Let's use https://github.com/ballerina-platform/ballerina-lang/issues/34950 to track this.
