### ISSUE TITLE
Variables Renamed in VSCode to Reserved Keywords, Need to be escaped as Quoted Identifiers

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#30292]
**Description:**
Currently, when a variable is renamed to a reserved keyword in the VSCode, it will be renamed and there would also be a syntax error. 
With the changes made at #29964, it would be possible to escape the reserved keywords as quoted identifiers when presenting. 
Therefore, when renaming a variable to a reserved keyword, it would be better to have a prompt in the LS client to get the user's consent and escape it to be a quoted identifier. 

**Describe your problem(s)**
Currently can rename a variable symbol to be a reserved keyword that would cause a syntax error.
![var-rename-to-rkw](https://user-images.githubusercontent.com/9464997/116850115-a6ec7a00-ac0d-11eb-9295-4fd8ff790839.gif)

Also, the user could manually rename a variable as a quoted identifier.
![var-rename-to-quoted-id](https://user-images.githubusercontent.com/9464997/116850166-bff52b00-ac0d-11eb-958e-8b72aa42c820.gif)

**Describe your solution(s)**
If the user renames a variable to be a reserved keyword (without the preceding quote), prompt a confirm message to get the consent and rename it as an escaped quoted identifier. Otherwise, halt the renaming operation as enforcement of programming best practices.

**Related Issues:**
#29462 
#28567

**Suggested Labels:**
Type/Bug

**Comment by malinthar** [comment]
Before applying the test edit we nedd to verify whether the user actually prefers it. Therefore  the newtext should be added as  an Annotated Text. We need to bump LSP4J to support this. However bumping is currently blocked by https://github.com/ballerina-platform/ballerina-lang/issues/31441
