### ISSUE TITLE
`error:CallStackElement` for a single bal file contains the name of the file as the module name

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30293]
**Description:**
$title. AFAIK, there is no module associated with single bal files, so I think we can skip the `moduleName` field for a single bal file.

Related discussion https://ballerina-platform.slack.com/archives/CAXS256RX/p1620006525089600 

**Steps to reproduce:**
foo.bal
```ballerina
import ballerina/io;

public function main() {
    error e = error("error!");
    io:println(e.stackTrace().callStack);
} 
```

Prints 
> [{"callableName":"main",**"moduleName":"foo"**,"fileName":"foo.bal","lineNumber":4}]

**Affected Versions:**
slalpha5

**Comment by gabilang** [comment]
This issue is similar to https://github.com/ballerina-platform/ballerina-lang/issues/28837
