### ISSUE TITLE
[Proposal] Implement replace/split APIs in the lang.string class

### ISSUE THREAD

**Issue by jdchathuranga** [ballerina-platform/ballerina-lang#30330]
**Description:**
Replace and split are one of the most commonly used APIs on String objects, almost all other languages(regardless of old or modern) implement their replace and split APIs in their String class itself, so propose to have those two functions in the lang.string class, obviously for more complex stuff we can use regex, but for a very simple replace or split,  we should have a much simpler replace/split APIs in the lang.string class.

**Problem**
split/replace functions are one of the most commonly used functions, and all-most all the languages implement this in the string class itself, so developers naturally expected to have these functions in the string class, It is more convenient and intuitive to have replace/split functions in the lang.string class itself.

**Solution**
Implement replace/split functions in the lang.string class.

**Comment by pubudu91** [comment]
Design discussions regarding the language is done in the [ballerina-spec](https://github.com/ballerina-platform/ballerina-spec) repo. There's an open issue for this: https://github.com/ballerina-platform/ballerina-spec/issues/174. Please feel free to add your thoughts and suggestions to the discussion there.
