### ISSUE TITLE
Validate the usage of  `KEY_NOT_FOUND` error code

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#30341]
**Description:**

This error code is being used in the file compiler plugin https://github.com/ballerina-platform/module-ballerina-file/blob/master/file-compiler-plugin/src/main/java/io/ballerina/stdlib/file/compiler/FileServiceValidator.java#L96. But its logic seems to be validating if the remote qualifier is present in a method. (This error code does not have any usages in ballerina-lang ATM)
Need to validate its usage.

**Comment by pubudu91** [comment]
This can be closed right? Since they won't be using this error code?

**Comment by lasinicl** [comment]
> This can be closed right? Since they won't be using this error code?

Yes. :)
