### ISSUE TITLE
Lang server cyclic module imports

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30358]
I am working on a project with multiple modules (https://github.com/jclark/semtype/).

After modifying one module, it sometimes gets into a state where modules that import that module give an invalid cyclic module import error.
<img width="1193" alt="Screenshot 2021-05-05 110533" src="https://user-images.githubusercontent.com/499966/117099463-733f5a80-ad9b-11eb-9052-9d94ab9361a2.png">

Reloading the window makes the problem go away.

**Comment by nadeeshaan** [comment]
This was a caching issue we experienced earlier when we are reusing the same compilation for subsequent edits. Tried the same on master branch and swanlake beta-3 snapshot does not reproduce this issue.
Hence Closing this issue and please reopen if the issue can still be observed.
