### ISSUE TITLE
Formatting of readonly object type is wrong

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#30366]
**Description:**
```ballerina
type Atom readonly & object {
    function compare(Atom other);
};
```

after formatting:
![Screenshot 2021-05-05 at 15 17 46](https://user-images.githubusercontent.com/1496990/117123964-54e65880-adb5-11eb-97e2-49e8e2e253c7.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IrushiL** [comment]
Closing this issue, since this is fixed in the latest master (SL Beta RC1).
