### ISSUE TITLE
Incomplete suggestions in some cases

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30378]
**Description:**
$title. For constructs from an imported module.

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Foo record {|
    xml x;
|};

public function main() returns error? {
    Foo foo = {x: xml `<foo>hello</foo>`};

    json j = foo.toJson();
    io:p<cursor>

    Foo|error r1 = j.cloneWithType(); 
    io:println(r1);

    // doesn't work here

    Foo|error r2 = j.fromJsonWithType();
    io:println(r2);

    // works here
}
```

Note how the functions aren't suggested.

![suggestions](https://user-images.githubusercontent.com/8376983/117238490-9b39c700-ae4a-11eb-9a38-3354705fc382.png)

**Affected Versions:**
slalpha5

**Comment by nadeeshaan** [comment]
@MaryamZi can you please verify this on the latest master? Could not reproduce this on master.

**Comment by MaryamZi** [comment]
I can still observe this on master.

Using the following project with one sub module `mod1` and importing `mod1` in the default module.

mod1
```
public type PrintTemplate record {|
    int i;
|};

public function println() {
    
}

public function func(PrintTemplate p) {
    
}
```

default
```
import foo.mod1;

type Foo record {|
    xml x;
|};

public function main() returns error? {
    Foo foo = {x: xml `<foo>hello</foo>`};

    json j = foo.toJson();
    // mod1:<cursor>

    // doesn't work here

    Foo|error r1 = j.cloneWithType(); 
    // mod1:p<cursor>

    // doesn't work here

    Foo|error r2 = j.fromJsonWithType();
    mod1:

    // works here
}
```

When it doesn't work
![30378_1](https://user-images.githubusercontent.com/8376983/121837474-4ca60500-ccf3-11eb-87fa-726db3537547.png)

When it works
![30378_2](https://user-images.githubusercontent.com/8376983/121837479-50398c00-ccf3-11eb-8593-d9df32bcf698.png)

**Comment by IMS94** [comment]
Had a look at this in the syntax tree visualizer. At the first 2 occasions, parser detects
```
    mod1:

    Foo|error r1
```
as the type binding pattern. Need to check this with the parser.
![Screenshot from 2021-06-18 14-00-43](https://user-images.githubusercontent.com/11285165/122532209-e8aa7600-d03d-11eb-9120-067de0aeb245.png)

**Comment by nadeeshaan** [comment]
> Had a look at this in the syntax tree visualizer. At the first 2 occasions, parser detects
> 
> ```
>     mod1:
> 
>     Foo|error r1
> ```
> 
> as the type binding pattern. Need to check this with the parser.
> ![Screenshot from 2021-06-18 14-00-43](https://user-images.githubusercontent.com/11285165/122532209-e8aa7600-d03d-11eb-9120-067de0aeb245.png)

Basically, why do we allow spaces after `:`. At least we have to disallow new line character to handle similar cases. Otherwise we will have to special case this from the LS side

**Comment by lochana-chathura** [comment]
> Basically, why do we allow spaces after `:`. At least we have to disallow new line character to handle similar cases. Otherwise we will have to special case this from the LS side

Isn't that formatters job to take care of whitespace, newline, etc? IMO, this has to be handled from the LS side.

As per the ballerina spec, `qualified-identifier := module-prefix : identifier` and
>"TokenWhiteSpace is implicitly allowed on the right-hand side of productions for non-terminals whose names start with a lower-case letter."  

In java also following works with no compilation error.
```java
System.
             // some comment
             out.
                        
                        
                   println("test");
```
