### ISSUE TITLE
`resource` qualifier is not suggested

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30385]
**Description:**
$title. Only the snippet is suggested.

```ballerina
import ballerina/http;

service / on new http:Listener(8080) {
    res<cursor> function get foo(http:Caller caller, http:Request req) {
        
    }
}
```

![resource_suggestion](https://user-images.githubusercontent.com/8376983/117250390-c3ccbb80-ae60-11eb-81e7-5b6de0734194.png)

**Affected Version:**
slalpha5

**Comment by nadeeshaan** [comment]
This is fixed in latest master. Hence closing the issue
