### ISSUE TITLE
Snippet for anonymous function

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30387]
**Description:**
Can we provide $title?

**Describe your problem(s)**
```ballerina
function () f = f<cursor>
```

```ballerina
var f = f<cursor>
```

![anon_function_snippet](https://user-images.githubusercontent.com/8376983/117258591-c16f5f00-ae6a-11eb-9133-4e1d9682b3ec.png)

Maybe we can provide one that results in

```ballerina
function () f = function () {

};
```

**Comment by nadeeshaan** [comment]
Duplicate of #https://github.com/ballerina-platform/ballerina-lang/issues/25490.
