### ISSUE TITLE
No intersection error shown for a valid error intersection

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30403]
**Description:**
Consider the following error intersection:
```
type Foo record {|
    int i;
|};

type Bar record {|
    int i;
|};

type FooError error<Foo> & error<Bar>;
```
It shows an error with message `invalid intersection type '$anonType$_276 & $anonType$_277': no intersection(BCE2026)`.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 1 SNAPSHOT

**Comment by rdhananjaya** [comment]
Related? https://github.com/ballerina-platform/ballerina-lang/issues/30118
