### ISSUE TITLE
Invalid `pattern will not be matched` error

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30463]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Rec record {|
    int|float a;
|};

public function main() {
    [int, Rec|string] x = [12, {a: 1}];

    match x {
        [12, "B"] => {
            io:println(1);
        }
        [12, {a: 1}] => { // ERROR: pattern will not be matched
            io:println(2);
        }
    }
}
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/30196

**Affected Versions:**
slalpa5

**Comment by lasinicl** [comment]
> Need to enable relevant tests in org.ballerinalang.test.statements.matchstmt.MatchStructuredErrorPatternsTest too.

Blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/30475
