### ISSUE TITLE
Add completion support for concat() 

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#30509]
**Description:**
No completions are provided for the string function concat()

![6](https://user-images.githubusercontent.com/27485094/117928974-e99f0800-b319-11eb-9930-ae759f491e0d.png)

**Steps to reproduce:**
`string t = "Hello ".concat("World");`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by pubudu91** [comment]
Seems to be an issue when the param is a rest param. Another such case is `sum()` in `lang.int`. Will have to check in other lang libs as well and see if there are more cases.
