### ISSUE TITLE
Add a qualifier to a Class Symbol, in order to specify whether a listener

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30512]
**Description:**
$title

**Affected Versions:**
sl-beta1-rc1 at least

**Comment by pubudu91** [comment]
Need to make use of https://github.com/ballerina-platform/ballerina-lang/blob/2d84395334ff5842263271ac62012204d04f1fa8/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L2300. Can consider adding a method to `ClassSymbol` to check if it the class is compatible to be used as a listener.

**Comment by nadeeshaan** [comment]
> Need to make use of
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/2d84395334ff5842263271ac62012204d04f1fa8/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/Types.java#L2300
> 
> . Can consider adding a method to `ClassSymbol` to check if it the class is compatible to be used as a listener.

+1

**Comment by pubudu91** [comment]
In an offline chat we decided not to go with the above described approach for this. Need to look in to how we can expose various type checking functionalities such as the above.

**Comment by pubudu91** [comment]
Can maybe address this with #33121. Should consider whether to provide a constant for the listener type.

**Comment by mohanvive** [comment]
Not came across this requirement recently, hence closing the issue.
