### ISSUE TITLE
[LS] Completions for `self.<cursor>` is not shown for start action within a method inside a class

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30519]
**Description:**
$title

Consider the following code:
```
public class WordCounter {

    public function countInText(string text) {
        string[] lines = regex:split(text, "\n");        
        future<map<int>> f = start self.<cursor>
    }

    function countWordsInLine(string line) returns map<int> {

    }
}
```

Consider the above code and the cursor is at `<cursor>`. At that position, completions for other methods inside the class are not shown.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 1 RC2

**Suggested Labels (optional):**
Language Server

**Comment by TharushiJay** [comment]
Blocked by #31117
