### ISSUE TITLE
[Language Server] Incorrect suggestion for completion 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#30515]
**Description:**
Refer the below recording for your reference. 

https://user-images.githubusercontent.com/7523274/117953094-6f7b7d00-b333-11eb-8a03-3b49857efbe0.mp4

**Steps to reproduce:**
Below is the code snippet. Here, there are suggestions such as "error constructor" and "object constructor" which are invalid.

```ballerina
import ballerina/io;

type InvalidAccountIDError error;

type AccountNotFoundError error;

const ACCOUNT_NOT_FOUND = "AccountNotFound";

const INVALID_ACCOUNT_ID = "InvalidAccountID";

public function main() {
   int negResult = getAccountBalance(-1);
   int invalidResult = getAccountBalance(200);

    transaction {
        int parsedNum = check parse("12");

        // Parsing a random string will return an error. This will
        // cause control to be transferred to the `on fail` clause.
        int parsedStr = check parse("invalid");

        error? res = commit;
    } on fail error e {
        io:println("Error occurred during parsing: ", e.message());
    }
}

function parse(string num) returns int|error {
    return int:fromString(num);
}

function getAccountBalance(int accountID) returns int {

    if accountID > 


}
```

**Comment by malinthar** [comment]
There are use cases where `error constructor` and `object constructor` can be used to generate valid expressions in this context.

eg:
```ballerina
function myFunc() {
    int abc = 12;
    var x = object {};
    // x
    if abc > (object {int aa = 12;}).aa {

    }
}
```

```ballerina
function myFunc2() {
  if error("Custom Error") === error("Custom Error")  {
   
  }
}
```

**Comment by IMS94** [comment]
@malinthar Agreed. What we can do from our side is sorting the suggestions to match the LHS of the condition. Let's try and do that.

**Comment by nadeeshaan** [comment]
This completion comes to the top since we do not have a filter text for the snippets and VSCode matches to a space in the label.

**Comment by malinthar** [comment]
> This completion comes to the top since we do not have a filter text for the snippets and VSCode matches to a space in the label.

resolved by https://github.com/ballerina-platform/ballerina-lang/pull/31124

**Comment by nadeeshaan** [comment]
Closing based on the previous comment
