### ISSUE TITLE
No completion are provided for field access expression

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30514]
**Description:**
Consider the following source snippet,

```
import ballerina/http;

HttpListenerProvider provider = new();
public listener t2 = provider.<cursor>

function name() {
    
}

class HttpListenerProvider {
    public function getListener() returns http:Listener {
        return check new http:Listener(9090);
    }
}
```

Consider how the source is resolved by the parser
<img width="1156" alt="Screenshot 2021-05-12 at 14 59 55" src="https://user-images.githubusercontent.com/1329674/117952476-d3ea0c80-b332-11eb-8ac8-57a75eb2c2cb.png">

**Affected Versions:**
slbeta1-rc1 at least

**Comment by lochana-chathura** [comment]
Duplicate of #30634

**Comment by lochana-chathura** [comment]
Now it is parsing correctly. If no LS changes on top of this. Can close this issue.

**Comment by nadeeshaan** [comment]
This is fixed now.Hence closing the issue.
