### ISSUE TITLE
The built-in subtypes of `Xml` does not have filler value

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#30524]
**Description:**
The insertion of a member to an array of `xml built-in subtype` at a position greater than the size of the array panics abruptly. 

**Steps to reproduce:**
```
import ballerina/io;

public function main() {

    'xml:Text x1 = 'xml:createText("text 1");
    'xml:Text x2 = 'xml:createText("text 2");
    'xml:Text x3 = 'xml:createText("text 3");

    'xml:Text[] x = [x1, x2];
    insertListValue(x, 4, x3);
    io:println(x);
} 

function insertListValue('xml:Text[] list, int pos, 'xml:Text value) {
    list[pos] = value;
}
```
Above program panics with following message:
```
error: {ballerina/lang.array}IllegalListInsertion {"message":"array of length 2 cannot be expanded into array of length 5 without filler values"}
```
But the insertion should be allowed with filler values according to the [spec](https://ballerina.io/spec/lang/master/#FillMember).
**Affected Versions:**
slalpha5
**OS, DB, other environment details and versions:**
**Related Issues (optional):**
**Suggested Labels (optional):**
Type/Bug, Team/jBallerina
**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/22642.

**Comment by gabilang** [comment]
Above PR (#30354) will fix this issue.
