### ISSUE TITLE
LS does not suggest function pointer 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#30529]
**Description:**
As depicted in the following image, LS only suggest the function call. Function pointer should be also suggested.

![Screenshot from 2021-05-13 09-29-55](https://user-images.githubusercontent.com/35211477/118075810-72777b80-b3ce-11eb-8f34-d09f68271aab.png)

**Steps to reproduce:**
Try above code segment in VSCode

**Comment by malinthar** [comment]
Related issues: #29748 #30078

**Comment by nadeeshaan** [comment]
When we consider the given context, which is the block statement context, the function call expression is a valid suggestion IMHO. 
If we have a context such as bellow,

```var test = add<cursor>```

the most viable suggestion would be the pointer instead of the function call expression.

**Comment by malinthar** [comment]
> When we consider the given context, which is the block statement context, the function call expression is a valid suggestion IMHO.
> If we have a context such as bellow,
> 
> `var test = add<cursor>`
> 
> the most viable suggestion would be the pointer instead of the function call expression.

Agreed. Function pointer should be provided if the context type of the node at cursor  is function.

**Comment by malinthar** [comment]
Can be closed with above PR
