### ISSUE TITLE
[LS] Suggest methods of a class within method body of methods within the same class

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30520]
**Description:**
$subject

Right now, we have to type `self.<cursor>` to get completions for methods with the class. It will be convenient if we show suggestions for methods of the same class without having to type `self.`.

**Describe your problem(s)**
See description

**Suggested Labels (optional):**
Language Server

**Comment by nadeeshaan** [comment]
@TharushiJay
