### ISSUE TITLE
Transaction keywords suggested at module level

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#30532]
**Description:**
`transaction` and `transactional` keywords are suggested at module level. They are not valid at module level, hence we should fix it.

Refer the below recording.

https://user-images.githubusercontent.com/7523274/118087923-ec662f80-b3e3-11eb-9a8e-f484a632662a.mp4

**Comment by nadeeshaan** [comment]
@mohanvive the `transaction` keyword is suggested as the module prefix and the `transactional` keyword is suggested to allow defining the transactional functions.

**Comment by mohanvive** [comment]
OK, makes sense then.

**Comment by nadeeshaan** [comment]
Closing the issue as per the last comment.
