### ISSUE TITLE
The typekind of @untainted annotation is TYPE_REFERENCE

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#30541]
**Description:**
While compiling following code, it occurred that the `@untainted` annotation's typeDescriptor typekind is `TYPE_REFERENCE`. Earlier it was `SINGLETON`

```
    resource function get dbJson(@untainted @http:Payload json abc) returns string {
        return "done";
    }
```

**Affected Versions:**
2.0.0-beta.1

**Comment by pubudu91** [comment]
Was fixed with #30551
