### ISSUE TITLE
Compiler doesn't complain about assigning value to module level final constructs

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#30577]
**Description:**
$title

**Steps to reproduce:**
The following compiles. 
```ballerina
function foo() {

}

public function main() {
    foo = foo;
}
```

**Affected Versions:**
slalpha5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24315.
