### ISSUE TITLE
Code Action to automatically complete a record

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#30588]
**Description:**
Consider following screenshot 
![Screenshot from 2021-05-16 16-33-01](https://user-images.githubusercontent.com/323846/118394846-cf8c5f00-b664-11eb-95fc-9234f5221474.png)

In the above scenario we can introduce a code action to automatically complete the missing non default-able fields of a record.

**Comment by nadeeshaan** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/31099 we have handled this with a fill all completion item.

**Comment by IMS94** [comment]
Closing this since the above PR has been merged.
