### ISSUE TITLE
=== with integer subtype

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30586]
In slalpha5, this:

```
function f(int:Signed32|object{} v) returns boolean {
  return v === 0;
}
```

gets the error `operator '===' not defined for '(int:Signed32|object { })' and 'int'`.

Changing `int:Signed32` to `int` makes the error go away.

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/31861.
