### ISSUE TITLE
'--tests' flag behaves differently when build command is executed giving the project path

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#30653]
**Description:**
'--tests' flag behaves differently when build command is executed giving the project path

**Steps to reproduce:**

See the below command(provides the path to ballerina project) to run specific tests at [[1]](https://github.com/ballerina-platform/ballerina-lang/tree/master/tests/testerina-integration-test/src/test/resources/project-based-tests/module-execution-tests).

```bal build --tests moduleExecution.Module1:* module-execution-tests```

This gives the following output. 

`ballerina: Invalid Ballerina package directory: <current-path>, cannot find 'Ballerina.toml' file.`

If the same command is executed after traversing to the project path as follows, the specific tests get executed correctly.

```bal build --tests moduleExecution.Module1:*```

This behaviour is specific to 'bal build' command and the 'bal test' command behaves as expected

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Closing since `--tests` flag has been removed
