### ISSUE TITLE
Improve diagnostic Message

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30686]
**Description:**
Consider the following screen capture, where the diagnostic message contains `$anonType$_34` which does not make sense.

<img width="660" alt="Screenshot 2021-05-20 at 12 27 20" src="https://user-images.githubusercontent.com/1329674/118934135-a4a55200-b967-11eb-8173-52b0dbca039a.png">

**Affected Versions:**
ls-beta1-SNAPSHOT at least

**Comment by dulajdilshan** [comment]
I was not able to reproduce this. @nadeeshaan Is this fixed?

**Comment by nadeeshaan** [comment]
It seems this has been fixed now. Couldn't reproduce.

**Comment by MaryamZi** [comment]
Fixed in slbeta2.
