### ISSUE TITLE
bal build creates an executable for projects with 1.2.x structure

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#30684]
**Description:**
With the introduction of the new compiler plugin design, we started to allow building no-source packages. This has resulted in successfully building projects with 1.2.x structure. We should not build no-source packages unless the package has a compiler plugin attached to it.

Therefore, allowing the compilation of no-source packages needs to be fixed as follows:

`bal build` - not allowed
`bal build -c` without compiler plugins - not allowed
`bal build -c` with compiler plugins - allowed

**Comment by hevayo** [comment]
If the project is empty we will display a message "error: package is empty please add at least one .bal file" 

We will consider a package is empty if 

- There are no bal files in package directory
- And there are no module directories
- If there are modules at least one should have a .bal file.
