### ISSUE TITLE
Mismatch in locations of generating resources with schema.

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-lang#30689]
**Description:**
On some connectors, the resource folder is getting generated on the root folder.[1]
But on another set of connectors, resources are getting generated inside the `modules` under the project name.[2]

Please refer to the example below.
[1] 
![image](https://user-images.githubusercontent.com/19235998/118945013-b2aca000-b972-11eb-855d-ca2215e1172c.png)
[2] 
![image](https://user-images.githubusercontent.com/19235998/118945121-c952f700-b972-11eb-924f-4dd86f6edad7.png)

Both of the above connecters contains the record/types.bal (ballerina file with record types) inside the root path.
So ideally it should generate a resource folder inside the root folder[1] in my opinion.

**Steps to reproduce:**
[1]
Clone https://github.com/ballerina-platform/module-ballerinax-github
Setup the repo and type `bal build -c --skip-tests` inside `github` folder.
[2]
Clone https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar
Setup the repo and type `bal build -c --skip-tests` inside `calender` folder.

**Ballerina version:**
Ballerina Swan Lake Alpha 5

**Findings related to the issue**
[2] This scenario was happening for connectors with `.` on the connecter name.
e,g : 
```
[package]
org= "ballerinax"
name= "googleapis.calendar"
```

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by miyurud** [comment]
Closing this issue as it will be handled by the [Issue 131](https://github.com/ballerina-platform/module-ballerinax-datamapper/issues/131).
