### ISSUE TITLE
User defined error type owner is set to `lang.annotations`

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30688]
**Description:**
Consider a user defined error type like below residing in say `mod1`:
```
public type Mod1Error error;
```
the `owner` of the user defined error type is set to `lang.annotations`. This doesn't happen to errors like `type Err error<MyRec>`. The `owner` is used by the `ReferenceFinder` to determine references to module `mod1`.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta1 snapshot

**Related Issues (optional):**
#29276

**Comment by IMS94** [comment]
This cause `goto defs` to not work for user defined error types with type reference `error` (ex: `type Err error`). Module of such user defined type symbols are set to `lang.annotations` too. 

Blocks #29276

**Comment by IMS94** [comment]
Relates to #29232

**Comment by mohanvive** [comment]
Relates to https://github.com/ballerina-platform/ballerina-lang/issues/26284

**Comment by mohanvive** [comment]
@pubudu91 Shall we prioritise and check this?

**Comment by pubudu91** [comment]
> @pubudu91 Shall we prioritise and check this?

The correct module info gets returned now with the fix done for #26284.

**Comment by pubudu91** [comment]
Checked again in 2201.0.0, the correct module gets returned for this. Hence closing this.
