### ISSUE TITLE
Action invocation inside a function gives an internal error occurred.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#3068]
But, this should be failed at the semantic level. 

 ```
import ballerina.lang.system;

function main(string[] args){
    TestConnector con = create TestConnector();
    // following is not allowed in Ballerina
    system:println(con.callTest());
}

connector TestConnector () {

    action callTest(TestConnector c)(string){
        return "hello";
    }
}
```

Result is same, even we use old syntax - TestConnector.callTest(con)  instead of con.callTest().

**Comment by anupama-pathirage** [comment]
Verified the issue with below code in 0.95.0 release and issue still exists.

```ballerina
function main(string[] args){
	endpoint<TestConnector> con {
		create TestConnector();
	}
   	// following is not allowed in Ballerina
   	println(con.callTest());
}

connector TestConnector () {
	action callTest()(string){
	   return "hello";
	}
}
```

**Comment by uthaiyashankar** [comment]
This might not be valid anymore. Need to check and resolve.

**Comment by hasithaa** [comment]
This is not valid. This testcase will cover this scenario. 

https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/ballerina-test/src/test/resources/test-src/endpoint/test_action_negative.bal#L25
