### ISSUE TITLE
Schema files are not generated for record types that are only used inside streams 

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-lang#30690]
**Description:**
Refer this client function
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/2c2ffa793727f944e04acce8d801bc927ac228ee/gsheet/client.bal#L97
But this connecter doesn't generate File_schema.json inside resources.

**Steps to reproduce:**
Clone the connecter https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets
Setup the repo and type `bal build -c --skip-tests` inside `gsheet` folder.

**Ballerina version::**
Ballerina Swan Lake Alpha 5

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by miyurud** [comment]
Closing this issue as it will be handled by the [Issue 130](https://github.com/ballerina-platform/module-ballerinax-datamapper/issues/130).
