### ISSUE TITLE
[Testerina] Object Mocking withArguments fails to generate proper parameter cases at runtime

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#30691]
**Description:**
withArguments() registers the arguments to the Mock Registry. For certain functions, Object mocking fails to validate the cases properly which results in picking up the incorrect values from the Mock Registry. 

**Steps to reproduce:**
Mock the get() function in http_Client_endpoint in HTTP Module

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Remember to update documentation or revert commits as necessary :

- [ ] BBEs
- [ ] Learn Pages
- [ ] API docs

**Comment by Dilhasha** [comment]
Learn pages are updated with https://github.com/ballerina-platform/ballerina-dev-website/pull/2269.
