### ISSUE TITLE
Invalid completions within the service declaration body

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30708]
**Description:**
```
import ballerina/module1;
service on module1:listener1 {
    public <cursor>
}
```

at the given cursor position, remote function snippets should not suggest. 

Consider the following capture for the resolved tree
<img width="1374" alt="Screenshot 2021-05-21 at 12 05 16" src="https://user-images.githubusercontent.com/1329674/119093049-d502f400-ba2c-11eb-8435-4cd47a3ee779.png">

**Steps to reproduce:**

**Affected Versions:**
sl-beta1-SNAPSHOT at least

**Comment by rdulmina** [comment]
We can try constructing missing `object-field` with `public` qualifier while the ideal recovery is to invalid `public` keyword. Also when I try the following sample it also gives `remote function` suggestion
```bal
service on module1:listener1 {
    public <cursor>int a;
}
```
Looks like constructing an `object-field` won't work right?

**Comment by nadeeshaan** [comment]
> We can try constructing missing `object-field` with `public` qualifier while the ideal recovery is to invalid `public` keyword. Also when I try the following sample it also gives `remote function` suggestion
> 
> ```ballerina
> service on module1:listener1 {
>     public <cursor>int a;
> }
> ```
> 
> Looks like constructing an `object-field` won't work right?

In order to provide completions honouring the qualifiers, we should be able to access the qualifiers via the object field in the incomplete scenario.
