### ISSUE TITLE
There's no Way to Retrieve the Member Types of an Intersection Type

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#30728]
**Description:**
The `getName()` function returns `<RecordTypeName> & readonly` as the type name for readonly records, in the native code when trying to get the type name.

This is a blocker for GraphQL.

Update:
In GraphQL, we generate the schema at the runtime. For generating the schema, we need the type name since the GraphQL types are nominal. Therefore, to get the type names from the intersection types, we should have a method to retrieve the original member types (similar to what we did with union types #29139).

**Comment by MaryamZi** [comment]
Can you please share an example of what you mean by readonly record?

**Comment by ThisaruGuruge** [comment]
Check this line:
https://github.com/ballerina-platform/module-ballerina-graphql/blob/e0c8e3fcc035a1bc5f45510f22bd234bf6d4fa6c/graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java#L150

Here, I am a readonly record type.

The record is defined as follows:

```
class ExecutorVisitor {
    *parser:Visitor;

    private final __Schema schema;
    private final Engine engine;
    private Data data;
    private ErrorDetail[] errors;

    isolated function init(Engine engine, __Schema schema) {
        self.engine = engine;
        self.schema = schema;
        self.data = {};
        self.errors = [];
    }
}
```

This `schema` field is the readonly record type, I am passing to the native code. Inside the native code, fields of this record are accessed, and those field names are giving this error. 

You can checkout the [`isolation-fix`](https://github.com/ballerina-platform/module-ballerina-graphql/tree/isolation-fix) branch in the GraphQL repo and debug at [CallableUnitCallback.java#L150](https://github.com/ballerina-platform/module-ballerina-graphql/blob/e0c8e3fcc035a1bc5f45510f22bd234bf6d4fa6c/graphql-native/src/main/java/io/ballerina/stdlib/graphql/runtime/engine/CallableUnitCallback.java#L150). 

I think I answered the question, please let me know if this isn't what you asked :)

**Comment by ThisaruGuruge** [comment]
Is there a way to get the members of an intersection type? That might solve this.

**Comment by MaryamZi** [comment]
As discussed offline, the observations are as expected. Since the type is being retrieved from the value, if it is immutable you will get `T & readonly` as the type.

> Is there a way to get the members of an intersection type? That might solve this.

This is not possible at runtime atm. This will require changes similar to those done at compile-time to support https://github.com/ballerina-platform/ballerina-lang/issues/29984.

**Comment by ThisaruGuruge** [comment]
> This is not possible at runtime atm. This will require changes similar to those done at compile-time to support #29984.

I will update the issue for this requiremennt.
