### ISSUE TITLE
+ not defined for string subtype

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30734]
In slalpha5, this:

```
function foo(string s, ("x"|"y") e) returns string => s + e;
```

gets the error `operator '+' not defined for 'string' and 'x|y'`.

**Comment by lasinicl** [comment]
This has been fixed in slbeta1 RCs, hence closing this issue. 
Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/30103
