### ISSUE TITLE
Incorrect error typing with check applied to conditional expression

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30737]
With slalpha5, the following correct program:

```
type Err distinct error;

function foo(boolean b) returns string|Err {
  return check (b ? bar() : baz());
}

function bar() returns string|Err {
  return "";
}

function baz() returns string|Err {
  return "";
}
```

gets the error

```
 invalid usage of the 'check' expression operator: no matching error return type(s) in the enclosing invokable
```

Pushing the `check` down into each arm of the ternary expression makes the error go away.

**Comment by jclark** [comment]
This gets the same error:

```
type Err distinct error;

function foo(string[] args) returns string|Err {
  return args.push(check bar(s));
}

function bar(string s) returns string|Err {
  return "";
}
```

**Comment by jclark** [comment]
I keep running into this one.

Sometimes a change in one file of a module makes the error appear in another file.

**Comment by rdhananjaya** [comment]
Reopening since the PR which closed this issue is reverted due to a bug. 
https://github.com/ballerina-platform/ballerina-lang/pull/31189
