### ISSUE TITLE
Code action for implementing methods list the methods one by one

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#30749]
Consider the following scenario:
```ballerina
class ListenerImpl {
    *Listener;
}

public type Listener object {

    public function 'start() returns error?;

    public function gracefulStop() returns error?;

    public function immediateStop() returns error?;

    public function detach(service object {} s) returns error?;

    public function attach(service object {} s, string[]? name = ()) returns error?;
};
```
When I check the code actions for the above, it gives a code action each for each of the methods. Can we have another option to implement all the methods in one code action?

<img width="703" alt="Screenshot 2021-05-24 at 13 53 31" src="https://user-images.githubusercontent.com/6260009/119319283-dbe16f00-bc97-11eb-9972-b6095ba9b4b8.png">

**Comment by IMS94** [comment]
We have to support the same for `object constructor expressions`:
```
type Foo object {
    function abc() returns int;
    function def() returns int;
};

object {} x = object Foo {
    <here>
};
```
