### ISSUE TITLE
Implement Pull module Code Action

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30757]
**Description:**
$title

In order to implement this particular use-case, the Language Server has to either depend on executing the Ballerina pull command internally, or to use a pull API provided via the developer tools

**Comment by nadeeshaan** [comment]
@hevayo is there an already existing API to achieve this?

**Comment by azinneera** [comment]
> @hevayo is there an already existing API to achieve this?

@nadeeshaan You can use the existing APIs to do the following steps which will automatically pull modules from central if it does not exist locally and create caches. 

1. Load the project - `ProjectLoader.load(<path>)`
2. Resolve dependencies and compile `project.currentPackage().getCompilation()`

**Comment by IMS94** [comment]
@azinneera I followed this approach. But, `RemotePackageRepository` reads the `offline` flag from system properties instead of build options. Therefore, couldn't find a way to do an online build just for a single project. Any suggestions?

**Comment by azinneera** [comment]
@IMS94 

> @azinneera I followed this approach. But, `RemotePackageRepository` reads the `offline` flag from system properties instead of build options. Therefore, couldn't find a way to do an online build just for a single project. Any suggestions?

@IMS94 When `offline` build option is given, when loading the project, it should set the system property. Looks like this is not implemented in some overloaded methods used for project loading.

**Comment by IMS94** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/31711
