### ISSUE TITLE
Messy markdown rendered on hover over function symbol

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#30776]
**Description:**
Consider the following source code
```ballerina
# Description
#
# + param1 - Param1
# + return - Integer
function myFunc(int param1) returns int{
    return 1;
}

```

<img src="https://user-images.githubusercontent.com/35211477/119461179-13feb580-bd5d-11eb-9bcd-52c3bbd4aafc.png" width=500/>

**Comment by nadeeshaan** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30746

**Comment by malinthar** [comment]
Closed as this is fixed in the stage branch
