### ISSUE TITLE
[Semantic API] Documentation for TypeDefinition is not resolved

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#30787]
**Description:**

Consider the following scenario

module1(sub-module) contains the following type definition
```ballerina
# Err1 custom error type.
public type Err1 error;
```
the default module refers to the above definition as follows.
 ```ballerina
module1:Err1 myErr;
```
The BSymbol resolved for `Err1` is of `error ` type (instead of `TypeDefinition`) as depicted below.

<img src="https://user-images.githubusercontent.com/35211477/119492216-6e5b3e80-bd7c-11eb-96fe-f81eeb8c2fc7.png" width=500 />

Due to this behavior some of the information such as documentation is not accurate(as the BSymbol is not accurate)

**Steps to reproduce:**
Follows above steps

**Comment by malinthar** [comment]
Relates to #29276

**Comment by pubudu91** [comment]
This is due to #26284

**Comment by pubudu91** [comment]
This seems to get resolved with Chiran's PR. In VS Code, shows the correct documentation when hovering over `Err1`

**Comment by pubudu91** [comment]
Closing since this is now fixed and covered by tests with the PR above.
