### ISSUE TITLE
[Semantic API] Symbol defined in LHS visible in RHS

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#30790]
**Description:**
![rhs_lhs](https://user-images.githubusercontent.com/15815199/119509259-1cbbaf80-bd8e-11eb-9ec8-5db1e1b407c6.gif)

**Steps to reproduce:**

**Affected Versions:**
SL beta 1 rc4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This is already captured in #25607.
