### ISSUE TITLE
Parsing a JSON element that uses a reserved word throws a syntax error

### ISSUE THREAD

**Issue by PowellDean** [ballerina-platform/ballerina-lang#30795]
**Description:**

Working with an online financial API. The "Symbol Lookup" call returns JSON with the element name "type":

Example return value:
{
  "count": 1,
  "result": [
    {
      "description": "BALLERINA",
      "displaySymbol": "XXBALXX",
      "symbol": "XXBALXX",
      "type": "Common Stock"
    }
  ]
}

When attempting to check the value of "type" the following error is thrown:

ERROR [modules/common/common.bal:(26:38,26:38)] missing identifier
ERROR [modules/common/common.bal:(26:42,26:43)] invalid token 'type'

**Steps to reproduce:**

Code snippet:

    string query = string `?q=${aSymbol}&token=${aToken}`;
    http:Client clientEP = check new("https://xxx/api/v1/search");
    http:Response resp = check clientEP->get(query);

    json|error jsonValue = resp.getJsonPayload();
    if (jsonValue is json) {
        json|error payload = jsonValue.result;
        if (payload is json) {
            json[] all = <json[]>payload;
            foreach var stockInfo in all {
                io:println(stockInfo);
                io:println(stockInfo.symbol);
                io:println(stockInfo.type);
                io:println(stockInfo.description);
            }
        }
    }

**Affected Versions:**

Ballerina Swan Lake Alpha 5
Language specification v2020-12-17
Update Tool 1.3.3

**OS, DB, other environment details and versions:**
Ubuntu Linux 20.04

**Related Issues (optional):**

**Comment by MaryamZi** [comment]
Since `type` is a reserved keyword in Ballerina, we need to use a [quoted identifier](https://ballerina.io/learn/by-example/quoted-identifiers.html) in the field access for the `type` field here.

```ballerina
io:println(stockInfo.'type);
```

**Comment by PowellDean** [comment]
Thank you. I missed that little nugget in the linked documentation. Much appreciated, and apologies for opening a bug report in error.

Dean

**Comment by MaryamZi** [comment]
> Thank you. I missed that little nugget in the linked documentation. Much appreciated, and apologies for opening a bug report in error.

No worries! :)
