### ISSUE TITLE
ints must overflow

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#30796]
**Description:**
```ballerina
int i = 9223372036854775807;
i = i + 1;
```
Above should overflow and crate a runtime error, we can use `java.lang.Math.addExact()` to achieve this

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/20799
