### ISSUE TITLE
"Transitive dependency not found" error

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30807]
With beta1 RC5, on this branch: https://github.com/ballerina-platform/nballerina/tree/james-bir

I get an error in the driver package:

```
Compiling source
        jjc/driver:0.1.0
error: compilation failed: Transitive dependency cannot be found: org=wso2, package=nballerina.bir, version=0.1.0
```

This is on Windows using build.bat to build all the packages.

**Comment by sameerajayasoma** [comment]
I tried importing the `nballerina.bir` module in the driver module as `_` as a workaround. Then I got the following error

```
Compiling source
	sameera/driver:0.1.0
error: failed to load the module 'wso2/nballerina.types:0.1.0' from its BIR due to: class org.wso2.ballerinalang.compiler.semantics.model.types.BNoType cannot be cast to class org.ballerinalang.model.types.IntersectableReferenceType (org.wso2.ballerinalang.compiler.semantics.model.types.BNoType and org.ballerinalang.model.types.IntersectableReferenceType are in unnamed module of loader 'app')
```

**Comment by jclark** [comment]
I get that same error if I do `bal build` (without the `-c`) in the `front` package

**Comment by pubudu91** [comment]
> I tried importing the `nballerina.bir` module in the driver module as `_` as a workaround. Then I got the following error
> 
> ```
> Compiling source
> 	sameera/driver:0.1.0
> error: failed to load the module 'wso2/nballerina.types:0.1.0' from its BIR due to: class org.wso2.ballerinalang.compiler.semantics.model.types.BNoType cannot be cast to class org.ballerinalang.model.types.IntersectableReferenceType (org.wso2.ballerinalang.compiler.semantics.model.types.BNoType and org.ballerinalang.model.types.IntersectableReferenceType are in unnamed module of loader 'app')
> ```

Looked in to this a bit. It looks like there's mismatch between the BIR writer and the reader. The above exception occurs when trying to define the `union` field of the following record from the BIR:
```ballerina
type UniformTypeOps readonly & record {|
    BinOp union = binOpPanic;
    BinOp intersect = binOpPanic;
    BinOp diff = binOpPanic;
    UnaryOp complement = unaryOpPanic;
    UnaryTypeCheckOp isEmpty = unaryTypeCheckOpPanic;
|};
```
Tried to create a smaller reproducible sample by copying just the relevant parts for the following:
```ballerina
type UniformTypeOps readonly & record {|
    BinOp union = binOpPanic;
|};
```
But this compiled without issue. So the actual mismatch is probably occurring somewhere else. Seems like we'll have to take a closer look at the BIR writer and reader.

**Comment by MaryamZi** [comment]
The CCE seems to be due to the type look up in the BIR symbol enter phase being attempted based on an encoded name (a generated type's name that has been encoded by the backend due to special characters) rather than the decoded name. 

We can use https://github.com/ballerina-platform/ballerina-lang/issues/30814 to track fixing this.

**Comment by azinneera** [comment]
The original issue reported was because we do not support transitive dependencies from the local repo yet. This improvement is tracked by #30980
