### ISSUE TITLE
BIRPackageSymbolEnter fails due to look up based on encoded names

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30814]
**Description:**
See https://github.com/ballerina-platform/ballerina-lang/issues/30807#issuecomment-849416643 onward.

Happens at https://github.com/ballerina-platform/ballerina-lang/blob/stage-slbeta1/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L1168.

Even though this particular case is for a generated type's name, I guess this can happen even for user-defined types that have names with characters that will get encoded.

**Affected Versions:**
slbeta1-rc5

**Comment by jclark** [comment]
Not sure if #30816 is the same.

**Comment by MaryamZi** [comment]
This happened when constructs in a module are used in other modules of the same package. This particular case was fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30821.

But moving the non-default modules of the types package in https://github.com/ballerina-platform/nballerina/tree/james-bir out to different packages resulted in the same error as https://github.com/ballerina-platform/ballerina-lang/issues/30816 which has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30836.

Main issue https://github.com/ballerina-platform/ballerina-lang/issues/30818 has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30858.
