### ISSUE TITLE
CME in DataMapperCompiler Plugin

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#30834]
**Description:**
Got CME  as follows  when I was working in a multi-module project intermittently. 

![Screenshot from 2021-05-28 13-38-51](https://user-images.githubusercontent.com/35211477/119954542-b5d00d80-bfbc-11eb-8294-b960deaeda70.png)

**Steps to reproduce:**

**Affected Versions:**
slbeta1-rc5

**OS, DB, other environment details and versions:**
Ubuntu

**Comment by IMS94** [comment]
This should be fixed with https://github.com/ballerina-platform/module-ballerinax-datamapper/pull/138

**Comment by malinthar** [comment]
closed via: https://github.com/ballerina-platform/module-ballerinax-datamapper/pull/138
