### ISSUE TITLE
Incomplete tooling support for retry-spec

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30866]
**Description:**
$title. Hovering, go to, etc. don't work for https://ballerina.io/ballerina-spec/spec.html#retry-spec in https://ballerina.io/ballerina-spec/spec.html#retry-stmt.

**Steps to reproduce:**
```ballerina
function demo() returns error? {
    var m = error:DefaultRetryManager; // Works here.

    // Doesn't work here.
    retry<error:DefaultRetryManager>(3) transaction {
        check commit;
    }
}
```

**Affected Versions:**
slbeta1-rc5

**Comment by IMS94** [comment]
Rename, goto def, find references doesn't work within `retry` block.
