### ISSUE TITLE
Missing puncutation in tagline in central

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#30879]
**Description:**
Need to have a full stop at the end

 
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/16300038/120147951-1d789980-c205-11eb-9e67-83a5c2b47054.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
This is fixed with https://github.com/wso2-enterprise/ballerina-central/pull/409

**Comment by hemikak** [comment]
Completed by @hasithaweerasinghe
