### ISSUE TITLE
Information in module cards is not clear on central

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#30878]
**Description:**
$subject refer below.

Specially the word `any` appears in some cards and by appearance not sure what it is. And the date, first created or last updated etc.
So can we have a tool tip. But at the same time now  when we hover it gives different view. So tooltips may not be the best option to solve it.

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/16300038/120147809-e2766600-c204-11eb-84ea-1a46b028bb1e.png">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
@anupama-pathirage `java11` and `any` are the platform targets we can run our code. `any` packages should be able to run on any java version.

**Comment by anupama-pathirage** [comment]
Yes.But IMO, it won't be clear for a use that here we are talking about `Platform`. Just seeing any won't help the user without knowing (having a label or tooltip) that this is the platform.

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2-enterprise/ballerina-central/issues/561 to track this
