### ISSUE TITLE
Improve the central searching as it gives improper resutls

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#30887]
**Description:**
We need to do the $subject to give more priority to the keyword or module title. Refer below recording. It gives highest priority to a module which have the searched word `google` in the bottom of the description.

![Screen-Recording-2021-05-31-at-2](https://user-images.githubusercontent.com/16300038/120170965-21191a00-c21f-11eb-99fc-4958ea63a2ad.gif)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Fixed with https://github.com/wso2-enterprise/ballerina-registry/pull/842
