### ISSUE TITLE
Errors in Central Cookie policy

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#30886]
**Description:**
Below issues in [1]

**Issue 1 :** 
Current one : `This information is used to make the Site work as you expect it to. `
Suggestion : `This information is used to make the site work as you expect it to. ` - Not the diff in word `Site`

**Issue2:**
Current one : `Our website will set several types of third-party cookie, and we do not control the operation of any of them.`
Suggestion : `Our website will set several types of third-party cookies, and we do not control the operation of any of them.` - Note the diff in word `cookie`

**Issue3:**
Current one :`The third-party cookies which maybe set include:`
Suggestion :`The third-party cookies which may be set include:` -   Note the diff in word `maybe`

**Issue4:**
Current one :`Session cookies do not collect information from the users computer.`
Suggestion :`Session cookies do not collect information from the user's computer.` - Note the diff in the word `users`

[1] https://central.ballerina.io/cookie-policy

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Fixed with https://github.com/wso2-enterprise/ballerina-central/pull/410.

@praneesha , can you review this document? https://github.com/wso2-enterprise/ballerina-central/blob/v2.0-dev/central-site/markdown_files/cookie-policy.md

**Comment by praneesha** [comment]
Issue 1: The capitalization is used for "Site" as a legal formality. It is how entities are referred in legal documents and contracts.

Issue2: Already fixed.

Issue 3: Changed to "The third-party cookies, which may be set will include:"

Issue 4: Already fixed.

Did the [review](https://github.com/wso2-enterprise/ballerina-central/commits/v2.0-dev/central-site/markdown_files/cookie-policy.md).

**Comment by hemikak** [comment]
Closing as PR is merged
