### ISSUE TITLE
Incorrect for Swan Lake word in version selector in central

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#30880]
**Description:**
Shouldn't we use Swan Lake or swan-lake ?

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/16300038/120148237-89f39880-c205-11eb-9097-4aeffee6c681.png">

Same issue with the version selector tool tip:

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/16300038/120170243-65f08100-c21e-11eb-8792-240728be4b4c.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Closing as PRs are merged
