### ISSUE TITLE
Query expression doesn't use narrowed type

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#30888]
**Description:**
```ballerina
public function main() {
    int[]? a = [1, 2, 3];
    if (a is int[]) {
        var b = from var i in a select i; // incompatible types: 'int[]?' is not an iterable collection(BCE2800)

        int[] t = a; // this works fine

        foreach int i in a { // this also works fine
            
        }  
    }
}
```

**Steps to reproduce:**

**Affected Versions:**
Swanlake beta 1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Issue already fixed with https://github.com/ballerina-platform/ballerina-lang/pull/30885
