### ISSUE TITLE
Error messages related to inferring target type of dependently typed functions are harder to decipher

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#30890]
**Description:**
```ballerina
import ballerina/http;

http:Client clientEndpoint = check new ("http://postman-echo.com");

public function main() {
    // incompatible type for parameter 'targetType' with inferred typedesc value:
    // expected 'typedesc<(ballerina/http:1.1.0-beta.1:Response|ballerina/http:1.1.0-beta.1:PayloadType)>', 
    // found 'typedesc'(BCE3931)
    _ = check clientEndpoint->post("/post", "POST: Hello World");

    // cannot infer type for parameter 'targetType'(BCE3934)
    var x = check clientEndpoint->post("/post", "POST: Hello World");
}
```

This error message could be confusing to a user of `post` function because he/she probably doesn't know the mechanics of dependently typed function.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
First one is due to https://github.com/ballerina-platform/ballerina-lang/issues/16908. Once that is fixed, the error will be

> incompatible type for parameter 'targetType' with inferred typedesc value: expected 'typedesc<(ballerina/http:2.5.0:Response|anydata)>', found 'typedesc\<any>'

With the changes in https://github.com/ballerina-platform/ballerina-lang/pull/38284, the error for the second one will be

> cannot infer the 'typedesc' argument for parameter 'targetType': expected an argument for the parameter or a contextually-expected type to infer the argument

**Comment by MaryamZi** [comment]
Closing this issue since 
- https://github.com/ballerina-platform/ballerina-lang/issues/16908 tracks the first case and 
- https://github.com/ballerina-platform/ballerina-lang/pull/38284 fixes the second case for update 4
