### ISSUE TITLE
Cannot join to a invited organization without having organization in my account

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#30891]
**Description:**
$subject.

Is it mandatory to have an organization In my login to join an invited organization?

Refre the below

1. logged in with first email and invited to the 2nd mail under an org
2. Logged in with second email and that doesn't have any org
3. All the other tabs are deactivated and no way to accept the invitation until I create an org under this 2nd email

![My-Movie(1)](https://user-images.githubusercontent.com/16300038/120182601-39dbfc80-c22c-11eb-97dc-6edd190c8cb0.gif)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Yes, currently we are enforcing the user to create an organization for their own when joining and when they have no organizations. Lets discuss this in extent on what we can do to improve.

**Comment by hemikak** [comment]
This is fixed with https://github.com/wso2-enterprise/ballerina-central/pull/471. Done by @hasithaweerasinghe.
