### ISSUE TITLE
Create variable code action doesn't use/generate the module prefix on type-desc of created variable.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#30909]
**Description:**
Consider below code:

```ballerina

import ballerina/lang.'typedesc;

type Error distinct error;

public function main() {
   Error.typeIds(); // execute code action 'create variable`
}
```

Type descriptor part of the generated variable (`TypeId[]? & readonly`) does not contain the module prefix part, and we need to manually add that at the moment.

![Screenshot 2021-06-01 at 15 03 31](https://user-images.githubusercontent.com/1496990/120301597-a7e6f900-c2ea-11eb-8a9e-c0adbba9a6b4.png)
![Screenshot 2021-06-01 at 15 03 41](https://user-images.githubusercontent.com/1496990/120301603-aa495300-c2ea-11eb-86f1-2fa10ab800d2.png)
![Screenshot 2021-06-01 at 15 03 58](https://user-images.githubusercontent.com/1496990/120301615-ad444380-c2ea-11eb-8012-cccb446f5fdf.png)

**Steps to reproduce:**

**Affected Versions:**
Swan Lake beta rc7
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This is possibly related to the issue mentioned in #26284

**Comment by IMS94** [comment]
@pubudu91 Seems so. In this case, when we get the `signature()` of type reference type symbol (of `TypeId`), the `getModule()` method returns `lang.annotations`. Within `getModule()`, it refers to `symbol.tsymbol.owner` as mentioned in the issue you pointed out.

**Comment by pubudu91** [comment]
Checked this with Chiran's PR, and seems to be working.

**Comment by mohanvive** [comment]
> Checked this with Chiran's PR, and seems to be working.

For me, above usecase works in beta-04 as well. It seems it is fixed already without his PR. :)

**Comment by IMS94** [comment]
Seems like this is fixed. Shall we close this then?

**Comment by nadeeshaan** [comment]
Closing since the issue has been fixed.
