### ISSUE TITLE
Implicit final-ness of variables is not considered within isolated functions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30902]
**Description:**
Suppose we have a function like below:
```
    public isolated function getPetById(int id) returns models:Pet|PetNotFound {
        models:Pet[] pets = self.pets.filter(isolated function(models:Pet pet) returns boolean {
            return pet.id == id;
        });
        if pets.length() > 0 {
            return pets[0];
        }
        return error PetNotFound("No pet found for ID: " + id.toString());
    }
```
Here, `id` which is the function parameter is implicitly final. But the compiler warns within the function passed to `filter()` method saying that `id` is not isolated/non-immutable. Implicit final factor should be supported for ease of use + better user user experience with Ballerina. Otherwise, they will have to create final variables like below:
```
final int currentId = id;
```
with the parameter `id` passed in. And use the final variable within isolated functions, etc.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta1 RC6

**Comment by MaryamZi** [comment]
This happens only for parameters since they use a different flag to indicate finalness (FUNCTIONAL_FINAL). Other implicitly final variables can be accessed in anonymous isolated functions if their types are subtypes of `readonly` or `isolated object {}`.
