### ISSUE TITLE
Resolving packages without internet

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#30911]
**Description:**
Currently when trying to build a package having `import ballerina/jballerina.java` gives an error when internet is disconnected. Ideally this should not fail as `ballerina/jballerina.java` is already there in the distribution. This is the same with `ballerina/io` import.

**Steps to reproduce:**
Build the following without internet.
```ballerina
import ballerina/jballerina.java;

public function pi() returns float = @java:FieldGet {
   name:"PI",
   'class:"java/lang/Math"
} external;
```

**Affected Versions:**
ballerina-swan-lake-beta1

**OS, DB, other environment details and versions:**
Mac

**Comment by IrushiL** [comment]
Blocking on implementation of package resolution diagnostics.
