### ISSUE TITLE
[Shell] Provide a mechanism for auto importing modules used in a snippet

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#30915]
Consider the simple case of using `io:println()` to print something. Currently, I have to explicitly import the `io` module before using it. If I attempt to use it without importing, I get the following error:
```
=$ io:println("hello world")                                                                                                                                                                                         
| error: undefined function 'println'
| 	io:println("hello world")
| 	^-----------------------^
| Compilation aborted due to errors.
```
Instead of doing this, it'd be great if we can automatically add an import for `io` in this. At least maybe do this for standard libraries that are available OOTB in the distribution?

**Comment by DamithaSenevirathne** [comment]
Fixed with #33989
