### ISSUE TITLE
No suggestions for annotations in http module when typeing at EOF

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#30913]
**Description:**
when I type `@http:` at the end of the file no suggestions are shown. It shows suggestions if there is a top-level construct that follows it. Should be a parser issue.

**Comment by nadeeshaan** [comment]
@rdulmina this is due to the current implementation we follow in Language Server. We currently support annotations for the construct immediately after the cursor

**Comment by nadeeshaan** [comment]
Similar issue #29420

**Comment by IMS94** [comment]
@nadeeshaan what can we do about this? Shall we show all the annotations?

**Comment by nadeeshaan** [comment]
> @nadeeshaan what can we do about this? Shall we show all the annotations?

+1

**Comment by IMS94** [comment]
Blocked by #31356
