### ISSUE TITLE
Renaming a distinct error type doesn't work as expected

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#30931]
**Description:**
$title.

**Steps to reproduce:**

```ballerina
type Error distinct error;

type MyError distinct Error;
```

Renaming `MyError` to `E1` changes the code as follows

```ballerina
type Error distinct error;

type E1 distinct E1;
```

**Affected Versions:**
slbeta1-rc8

**Comment by IMS94** [comment]
This is same as #29276 and caused by #30688
