### ISSUE TITLE
[Formatter] Improving formatting of return statement

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#30936]
Here is the sample code:

![Screenshot from 2021-06-01 23-35-55](https://user-images.githubusercontent.com/46120162/120371028-e7393800-c332-11eb-8178-5392b39da715.png)

Here is what I get after using the Format Document:

![Screenshot from 2021-06-01 23-36-11](https://user-images.githubusercontent.com/46120162/120371195-164fa980-c333-11eb-8b2a-31ac8cf943b1.png)

**Steps to reproduce**

```
isolated class Counter {
    private int n = 0;

    isolated function get()
        returns int {
        lock {
            returns self.n;
        }
    }

    isolated function inc() {
        lock {
            self.n += 1;
        }
    } 
}
```

**Comment by IrushiL** [comment]
Since there is a syntax error in this scenario (the `returns` keyword inside the lock statement is an invalid token), this incorrect-looking formatting is to be expected. This should be fixed once the code is corrected.

**Comment by gayalkuruppu** [comment]
This issue is caused due to a syntax error in return statement
