### ISSUE TITLE
Incorrect completion inside comment

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30948]
Sometimes at the end of a comment line, I hit Return and VS Code decides to insert some meaningless completion.  GIF attached.

![nballerina-1622609254686](https://user-images.githubusercontent.com/499966/120425603-b986da00-c398-11eb-912b-d28ebcfc5177.gif)

**Comment by IMS94** [comment]
Similar issue: https://github.com/ballerina-platform/ballerina-lang/issues/30696
