### ISSUE TITLE
[Formatter] Multiline function parameter formatting should be improved

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#30943]
**Description:**
title

**Steps to reproduce:**
```
function foo(int x, 
int y) {
    return;
}
```
Here is the sample code before formatting:

![Screenshot from 2021-06-02 01-43-34](https://user-images.githubusercontent.com/46120162/120385525-2a9ca200-c345-11eb-913a-e5f30500278f.png)

 Can we improve this to get the following:

![Screenshot from 2021-06-02 01-53-26](https://user-images.githubusercontent.com/46120162/120385686-5cae0400-c345-11eb-88b6-792bf9aa0a43.png)

**Comment by KavinduZoysa** [comment]
This is fixed in the latest formatter. Hense closing.
