### ISSUE TITLE
Language server responses become slow while typing `isolated` keyword in resource methods (in services)

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30952]
**Description:**
Consider the following code:
```ballerina
isolated int count = 0;

service / on new http:Listener(8080) {
     resource <cursor> function get getResource(http:Caller caller, http:Request req) returns string{
        lock {
            count += 1;
        }
        return "hello world";
    }
}
```
At `<cursor>` if we start typing `isolated` keyword, language server responses (completions, diagnostics) become really slow. Even after completing typing `isolated` keyword, it takes several seconds (around 5 secs) to clear the diagnostics.

With the newly added warning `concurrent calls will not be made to this method since the method is not an 'isolated' method` if resource methods are not isolated, users will tend to add `isolated` keyword to resource methods or the service. Therefore, this should be addressed quickly.

**Steps to reproduce:**
See description

**Affected Versions:**
Sl Beta 1 RC8

**Comment by lochana-chathura** [comment]
Related to #30685.
