### ISSUE TITLE
[LS] `where` keyword not suggested in between clauses in query pipeline

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#30968]
**Description:**
Consider:
```
models:Pet[] listResult = from var pet in allPets
        where pet.value.value > 1000.0
        w<cursor>
        select pet;
```
At `<cursor>`, `where` clause is not suggested.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 1

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/31103
