### ISSUE TITLE
Provide filler values for Intersection type with valid constructor

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#30977]
**Description:**
The spec says we will have array filler values if the element type contains a valid constructor.
Consider the following example ,
```ballerina
type Person readonly & record {|
    string name = "default";    
|};

public function main() {
    Person p1 = {name: "Hinduja"};
    Person[] arr = [];
    arr[2] = p1;
}
```
It gives an error 
```
error: {ballerina/lang.array}IllegalListInsertion {"message":"array of length 0 cannot be expanded into array of length 3 without filler values"}
```
**Affected Versions:**
beta1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
[#850](https://github.com/ballerina-platform/ballerina-spec/issues/850)

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
This works as expected. Hense closing
