### ISSUE TITLE
BAD SAD while type testing a Complex Union type 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#31011]
Observed this in SLBeta1. The code I used here is 

```
if stmt is anydata {
            
}
```

Here `stmt` is https://github.com/ballerina-platform/nballerina/blob/9f3819aa1e8a12ce47261836ef11a947ed587913/modules/front/ast.bal#L19

Log: [ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/6602994/ballerina-internal.log)

**Comment by MaryamZi** [comment]
This seems to be related to (or probably the same as https://github.com/ballerina-platform/ballerina-lang/issues/30681). 

The following (modified from the nballerina package) also results in an SO error.

```ballerina
function func(ListTypeDesc x) {
    if x is anydata {

    }
}

type TypeDesc LeafTypeDesc|ConstructorTypeDesc;

type LeafTypeDesc "any"|"boolean";
type ConstructorTypeDesc ListTypeDesc|MappingTypeDesc;

type ListTypeDesc record {|
    TypeDesc rest;
    ListDefinition? def = ();
|};

type MappingTypeDesc record {|
    string[] fields;
    TypeDesc rest;
|};

class ListDefinition {
    int i = 1;
}
```
