### ISSUE TITLE
Consider the repo when loading a package from Project API package cache

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#31026]
**Description:**
ATM only the org name, package name and version are considered when looking up for a package from the packageCache 
https://github.com/ballerina-platform/ballerina-lang/blob/5a2abbf71648b99d8c709b798c8c3500b9afd7ba/compiler/ballerina-lang/src/main/java/io/ballerina/projects/environment/PackageCache.java#L60

This results in intermittent test failures since there can be two packages (the difference being the repository) in the package cache and the wrong one is returned.

Affected test cases: 
https://github.com/ballerina-platform/ballerina-lang/blob/5a2abbf71648b99d8c709b798c8c3500b9afd7ba/project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java#L253
https://github.com/ballerina-platform/ballerina-lang/blob/5a2abbf71648b99d8c709b798c8c3500b9afd7ba/project-api/project-api-test/src/test/java/io/ballerina/projects/test/PackageResolutionTests.java#L303

**Comment by Ibaqu** [comment]
Blocked on spec issue

**Comment by azinneera** [comment]
This was opened thinking the cache is shared with projects. The actual issue is that packages can be duplicated in the cache if the repo is changed through due to a Dependencies.toml edit.
