### ISSUE TITLE
Tooling functionality does not work for the given project

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#31030]
**Description:**
I am working on the below project. I do not get any tooling functionality via VSCode for this project.

https://github.com/ballerina-platform/module-ballerina-websubhub/tree/my-websubhub-samples/websubhub-examples/kafka-hub/hub-impl

**Comment by nadeeshaan** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/30973

**Comment by nadeeshaan** [comment]
Tested in the latest master build and cannot reproduce the issue. Hence closing the issue. If the issue still persists, please reopen.
