### ISSUE TITLE
[Semantic API] getModule() not working for type params

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#31063]
**Description:**
Module data is not available for type parameters.

**Steps to reproduce:**
1. Refer to the following code in `lang.array`

```
# A type parameter that is a subtype of `any|error`.
# Has the special semantic that when used in a declaration
# all uses in the declaration must refer to same type.
@typeParam
type Type any|error;

# Removes a member of an array.
#
# This removes the member of parameter `arr` with index parameter `index` and returns it.
# It panics if there is no such member.
#
# + arr - the array
# + index - index of member to be removed from parameter `arr`
# + return - the member of parameter `arr` that was at parameter `index`
public isolated function remove(Type[] arr, int index) returns Type = @java:Method {
    'class: "org.ballerinalang.langlib.array.Remove",
    name: "remove"
} external;
```
2. Get the symbol of the return parameter of the function `remove` (Type).
3. Get the `symbol.getModule()` which returns a null. This missing data causes broken links in api docs (https://docs.central.ballerina.io/ballerina/lang.array/1.1.0/functions#remove) 

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
We've intentionally skipped type params from being considered as a type ref because of #18150
