### ISSUE TITLE
Dependency order between packages are not consistent.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#31082]
**Description:**
We found out that dependency resolution between packages is not consistent between compilations while fixing https://github.com/ballerina-platform/ballerina-lang/issues/31009.

The dependency order is correct but different. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
@rdhananjaya this behavior is expected. We recreate the dependency graph for every compilation and once the dependency graph is created, we sort it topologically. The number of topological ordering possibilities depends on the number of independent nodes (vertices with no incoming edges in DAG terms). So if there is more than one package that is not dependant on any other, the sorted order can change per compilation.

Nonetheless, is there any requirement that we need to have another sort on top of this?

**Comment by rdhananjaya** [comment]
IMO this is not expected from the build system, this hinders the whole **Reproducible builds** concept by introducing unwanted randomness into the system.
We once found a bug that was intermittently crashing the compiler due to this inconsistency in the dependency resolution. (The actual bug was in compiler front-end, but it was intermittent due to this).

On a separate note, using a stable sorting algorithm should solve this issue. We do this for re-ordering module variables ([link](https://github.com/ballerina-platform/ballerina-lang/blob/aba806865dc52cf94b3ff61510cfaeeaf9e62fc7/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/cyclefind/GlobalVariableRefAnalyzer.java#L60))

**Comment by azinneera** [comment]
We need to sort the documents of each module to complete it. The document list should be sorted when
1. it is added to a module at the project creation
2. when a document is added to a module
