### ISSUE TITLE
Compilation info logs prints to the standard error stream

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#31090]
**Description:**
The following compilation logs in a Ballerina project print to the standard error stream instead of the standard output stream.
```
Compiling source
	buddhi/temp:0.1.0

Running executable
```
I reckon the cause of this issue is in here, we should change it to the standard out.
https://github.com/ballerina-platform/ballerina-lang/blob/27d811be95409e67c714b3cf06195635914636ee/cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/RunCommand.java#L88

**Steps to reproduce:**
Run a simple HelloWorld Ballerina project using the following commands.
```
bal run 1> sample.txt
bal run 2> sample.txt
```

**Affected Versions:**
- SL Beta 1
- MacOS

**Comment by hevayo** [comment]
This is by design so you can filter out only program output by disregarding the stderror. Otherwise both ballerina programs output and build command output will be visible in stdout.
