### ISSUE TITLE
Shouldn't arrays:sort() do in-place sorting? 

### ISSUE THREAD

**Issue by chethiya** [ballerina-platform/ballerina-lang#3113]
```
import ballerina.lang.system;
import ballerina.lang.arrays;

function main (string[] args) {
    string[] a = ["C", "B", "A"];
    string[] res = arrays:sort(a);
    system:println(a);
    system:println(res);
}
```
Above sort() function uses an additional linear space allocation and does not support in-place sorting. I see sorting is still WIP. But shouldn't the default behavior of sort() function be in-place sorting, or is there some other sort function I've missed?

**Comment by uthaiyashankar** [comment]
This functionality is removed.
