### ISSUE TITLE
Memory leak in compiler due to duplicated entries in typeCache map

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#31132]
**Description:**

**_$subject_** was found when we analyzed the heap usage of the jballerina-tools distribution built from `2.0.0-alpha5-dev` branch (commit: 8241385b4d5a8ec9ccde92053aeadda44a3fca63) for the following scenario:

_Adding and deleting newlines to a source file in googleapis.calendar module [1]. Some of the dependencies were not there in the local cache so the package showed diagnostics for the unresolved modules (since the LS is run offline)._

When we kept adding/deleting newlines we found out that the retained bytes increased significantly for `org.wso2.ballerinalang.compiler.util.Name` [2]. When analyzing further with @pubudu91 we figured out that the memory leak is due to duplicated entries in the `typeCache` map resulting in unnecessarily held `BSymbol` objects.

**Steps to reproduce:**

Duplication of entries can be reproduced with ballerina-lang as follows:

1. Write the below test case in `io.ballerina.projects.test.TestBuildProject` [3]:

```java
@Test
    public void testMemoryLeak() {
        BuildProject project = BuildProject.load(Paths.get("<path-to-module-ballerinax-googleapis.calendar>/calendar"));
        project.currentPackage().getCompilation();
        for (int i = 0; i < 10; i++) {
            DocumentId documentId = project.currentPackage().getDefaultModule().documentIds().stream().findFirst().get();
            String sourceCode = project.currentPackage().getDefaultModule().document(documentId).syntaxTree().toSourceCode();
            project.currentPackage().getDefaultModule().document(documentId).modify().withContent(sourceCode).apply();
            project.currentPackage().getCompilation();
        }
    }
```
2. Debug and evalute `TypesFactory.getInstance(project.projectEnvironmentContext().getService(CompilerContext.class)).typeCache` for each iteration and you can observe it growing

**Affected Versions:**
At least Alpha 5.4

**OS, DB, other environment details and versions:**
Tested on Ubuntu 20.04

[1] https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar
[2] https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Names.java
[3] https://github.com/ballerina-platform/ballerina-lang/blob/master/project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java

**Comment by pubudu91** [comment]
When working on fixing this issue by implementing `equals()` and `hashCode()` for `BType` and `BSymbol` and their sub classes, faced an issue with cyclic types. Basically attempting to implement `hashCode()` for them resulted in stack over flow errors. Even if we got around the stack over flow issue, there's the concern about correctness of using mutable fields of a class in the hash code computation. Therefore, we decided not to go down this path. Instead, we'll remove the type cache for now and see.
