### ISSUE TITLE
[Question] if name == main() (similar to Python)

### ISSUE THREAD

**Issue by miriam-z** [ballerina-platform/ballerina-lang#31131]
Is it possible to do something similar to Python

sample.bal:

```
function sample() {
   etc
}

if __name__ == main():
  sample()
```
  
so that modules can run in isolation during development and not via bal shell or after bal build then bal run:

bal run sample.bal

**Comment by KavinduZoysa** [comment]
We are closing this issue for now, and we will take this one later.
