### ISSUE TITLE
Ability to use VSCode to find a type a variable 

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31159]
Please add ability use VSCode to find a type a variable 
Slimier to this https://twitter.com/DavidKPiano/status/1403500184290664461

**Comment by nadeeshaan** [comment]
When hover over a variable, we can include the type name as well. Hence this will be consistent with the other constructs

**Comment by manuranga** [comment]
Please consider the following case; it that correctly shows `(int|boolen[])?` it'll be great.

eg:
```ballerina
import ballerina/io;

public function main() {
    var x = f();
    if !(x is string) {
        io:println(x); // what is the type of x here
    }
}

public function f() returns int|string|boolean[]?{
    return 2;
}
```

**Comment by gayalkuruppu** [comment]
@manuranga @nadeeshaan 
```
import ballerina/module1;

# Description for module variable with init
final isolated configurable int modVar1 = 12;  //hover at modVar1
```
For the above scenario, What would be the suitable expected hover result? `int` or `Description for module variable with init` (which is the result we already suggest)
