### ISSUE TITLE
HTTP TRACE and PATCH is not supported.

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#3115]
$subject. The HTTP spec denotes this method and this is needed to be supported.

**Comment by riyafa** [comment]
Currently Http TRACE is not supported. PATCH is supported by https://github.com/ballerina-platform/ballerina-lang/pull/858

**Comment by riyafa** [comment]
There is no plan to support TRACE method in ballerina at the moment unless if a requirement to do so arises. This is because the TRACE method is not highly used in the integration space. You can call this method using the `execute` method in http:Request.
