### ISSUE TITLE
[Semantic API] Incorrect ModuleID for typedesc types

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#31179]
**Description:**
Subject
TargetType link is not working in api docs due to this issue.
https://docs.central.ballerina.io/ballerina/http/1.1.0-beta.1/clients/FailoverClient#post

**Steps to reproduce:**
1. Have the following code
```
# The types of data values that are expected by the HTTP `client` to return after the data binding operation
public type TargetType typedesc<aClass|State>;

public function testFunc(TargetType targ) {
}
```
2. Get the symbol of `TargetType` in function parameter `targ` in `testFunc`.
3. The ModuleID will be `lang.annotations`

**Affected Versions:**
sl-beta1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
I believe this is due to #26284

**Comment by pubudu91** [comment]
Checked this with Chiran's PR. It seems to resolve this.

**Comment by pubudu91** [comment]
Checked in 2201.0.0 and this now returns the correct module ID. Hence closing this.
