### ISSUE TITLE
Tuple type definition only considers filler values in certain indexes 

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#31170]
**Description:**
Considering a type definition involving a tuple containing multiple types, if we only assign a value to the 0th index the latter indexes get filled with filler values and therefore is considered as a valid. If we try assigning a value to a type that corresponds any other index other than the 0th, then the filler values are not considered and therefore is deemed invalid.

**Steps to reproduce:**
```
type Foo [int, string, boolean];
Foo a = ["text"]; // compilation error: incompatible types: expected 'int', found 'string'
Foo b = [true];   // compilation error: incompatible types: expected 'int', found 'boolean'
```

**Comment by MaryamZi** [comment]
Filling members only happens at the end. The current behaviour is is in-line with the spec.

> If there is a contextually expected type, then **the type that the inherent type requires for each list member provides the contextually expected type for the expression for the member**; otherwise there is no contextually expected type for the expressions for members.
>
> A member of a list can be filled in automatically if the [FillMember](https://ballerina.io/spec/lang/master/#FillMember) abstract operation would succeed on it. The inherent type of a list establishes either a fixed length for the list or just a minimum length for the list, which may be zero. In either case, **a list constructor may specify only the first k members, provided that for each i from k + 1 up to the fixed length of the list, the i-th member can be filled in automatically**.

IMO, using the list constructor members for arbitrary tuple member types will open up room for error and unintended behaviour. This will especially be the case with members of the same type.
