### ISSUE TITLE
Panics are logged as a crashes

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#31171]
With the recent changes to the crash log, it seems panics are also considered as crashes and logged as such. This behaviour is wrong. Panics should not be considered as crashes. 

For example, now all the unit tests with panics print logs similar to the following:
```
ballerina-new-parser-test-suite > jballerina-test > org.ballerinalang.test.bala.functions.DependentlyTypedFunctionsBalaTest > testRuntimeCastError STANDARD_ERROR
    [2021-06-15 11:15:22,003] SEVERE {b7a.log.crash} - error: {ballerina}TypeCastError {"message":"incompatible types: 'map' cannot be cast to 'map<anydata>'"}
        at testorg.foo.dependently_typed.1_0_0:query(interop_funcs.bal:43)
           dependently_typed_functions_bir_test:testRuntimeCastError(dependently_typed_functions_bir_test.bal:68) 
    io.ballerina.runtime.internal.util.exceptions.BLangRuntimeException: error: {ballerina}TypeCastError {"message":"incompatible types: 'map' cannot be cast to 'map<anydata>'"}
        at testorg.foo.dependently_typed.1_0_0:query(interop_funcs.bal:43)
           dependently_typed_functions_bir_test:testRuntimeCastError(dependently_typed_functions_bir_test.bal:68)
        at org.ballerinalang.test.BRunUtil.lambda$invoke$2(BRunUtil.java:435)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by azinneera** [comment]
In the cli we catch and handle `RuntimePanicException`: https://github.com/ballerina-platform/ballerina-lang/blob/5804ecbf1f34c56c7c60c1d1573134349de09f0e/cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java#L72-L73

AFAIU, this should be thrown as a `RuntimePanicException` from the runtime if it should not crash. 

@warunalakshitha thoughts please.

**Comment by warunalakshitha** [comment]
IMO this should be handle by runtime. @riyafa

**Comment by riyafa** [comment]
@pubudu91 Is this in the master branch? When I run the following code with this PR: https://github.com/ballerina-platform/ballerina-lang/pull/31098 I get only an error log:
```
public function main() {
    panic error("Returning an error");
}
```
Error log:
```
error: Returning an error
```
Can you please provide a sample code where crash log is printed for panic?

**Comment by riyafa** [comment]
@pubudu91 can you please provide a code to reproduce this issue?

**Comment by pubudu91** [comment]
> @pubudu91 can you please provide a code to reproduce this issue?

Sorry, missed this. This only seem to be occurring in tests. Didn't see this when using the jbal tools distribution

**Comment by riyafa** [comment]
Is this issue still valid? If so can you please provide example test cases to test this?

**Comment by pubudu91** [comment]
Yes, it's still valid. Just checked in latest master. Run the tests in `jballerina-unit-test` module. You should see logs such as the ones mentioned above getting printed for test cases which have used panics.

**Comment by warunalakshitha** [comment]
Notice this when running jballerina-unit-tests and send a quick fix with https://github.com/ballerina-platform/ballerina-lang/pull/31437
