### ISSUE TITLE
Package resolution not picking the latest out of two version when it is coming from a transitive dependency

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#31180]
**Description:**
If a dependency is both direct and transitive but with different yet compatible versions, we always prioritize the direct dependency. Therefore, when the transitive dependency has the latest version, still the older one is taken since it comes from the direct dependency.

https://github.com/ballerina-platform/ballerina-lang/blob/07e48f1231751d19e62d5d47bd9ddba34520af71/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java#L178-L181

Example:
`PackageA dependsOn PackageB (0.1.0)`
`PackageA dependsOn PackageC`
`PackageC dependsOn PackageB (0.1.1)`

**_Expected:_** resolve to 0.1.1 of PackageB
**_Actual:_** resolves to 0.1.0 of PackageB

**Affected Versions:**
SL Beta1

**Comment by Ibaqu** [comment]
Blocked on : https://github.com/ballerina-platform/ballerina-lang/issues/30980

**Comment by azinneera** [comment]
This is being addressed in the resolution changes in Beta3.

**Comment by azinneera** [comment]
This is resolved with the package resolution refactor
