### ISSUE TITLE
Revisit why clonable is duplicated in lang.error and lang.value

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#31186]
**Description:**
No errors observed even though `lang.error` Clonable type is removed.

https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/master/lang/lib/error.bal

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
See https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/error.bal#L19.
