### ISSUE TITLE
Completion on record field names

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31193]
In VSCode, when I'm using records, I don't seem to get completion on field names. Given the data-oriented nature of Ballerina, this is an absolutely crucial feature. Not sure if this is a bug or a missing feature. For records I want to see the fields first before the possible langlib methods.

This would make writing Ballerina sooo much more convenient.

Attached is an example from the nballerina repo.
![compiler-1623808950104](https://user-images.githubusercontent.com/499966/122146904-0a5efe00-ce82-11eb-82a4-40512e3d1063.gif)

**Comment by IMS94** [comment]
Same as #30881. 
Blocked by #30906

**Comment by mohanvive** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31580 .
