### ISSUE TITLE
No completions when `:` is proceeded by some text value

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#31221]
**Description:**

```ballerina
import ballerina/lang.value;
public function main() {
    json|error fromJsonString = value:fromJsonString("hello");
    
}
```
I need to change the `value:fromJsonString` to some other function in `value` module. So I delete the `fromJsonString` part and try to get completions. I don't get any.

![Screenshot 2021-06-16 at 19 09 28](https://user-images.githubusercontent.com/1496990/122229481-69e6f900-ced6-11eb-9503-930aefc3870e.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This is fixed in the latest master. Hence closing the issue
