### ISSUE TITLE
Testerina diff `---` and `+++` need to be swapped

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31225]
Testerina diff should show how to **correct** a wrong output. That is, applying the diff on the current wrong result will produce the expected result

<img width="522" alt="Screenshot 2021-06-16 at 10 00 58 PM" src="https://user-images.githubusercontent.com/1686124/122258243-75deb500-ceee-11eb-8d28-e129df709525.png">

Currently it's backwards.

**Comment by Dilhasha** [comment]
Fixed with #31227
