### ISSUE TITLE
`Missing semicolon` error diagnostic is shown on the next line

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#31268]
**Description:**
Consider the code below:
```
# Description
#
# + d - Parameter Description
# + return - Return Value Description
public function getMessage(string d) returns string {
    string a = "a";
    string b = "b"
    return "Hello, World!";
}
```
In the 2nd statement in function body, error for the missing semicolon is shown at the beginning of the next line. This needs to be fixed.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 1

**Comment by lochana-chathura** [comment]
Duplicate of #29418

**Comment by IMS94** [comment]
Closing this due to duplicate.
