### ISSUE TITLE
Need to add the  content assist for the client, object, and class

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#31286]
**Description:**
We have code completion for the main function. Like this, we need to add the code completion for the client, object, and class.
<img width="610" alt="Screenshot 2021-06-18 at 5 05 05 PM" src="https://user-images.githubusercontent.com/12771261/122556048-ab9fad00-d058-11eb-902a-d0ab2366fa39.png">
**Affected Versions:**
SLBeta1

**Comment by nadeeshaan** [comment]
We are adding only the more specific use-cases. That's why we have a main function snippet as this. For classes there is a separate snippet which will be suggested even after typing the public keyword. Object type descriptor also behaves the same. Hence closing the issue
