### ISSUE TITLE
Dependencies of the connector doesn't resolve correctly when using the connector

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#31290]
**Description:**
Create a new DB connector and included the driver-jar inside. When trying to use the new connector without providing the driver-jar dependency, I am getting a CNF error in DB Driver classes. when I check the connector bala file in local depository, driver jar is there inside,
```
.ballerina/repositories/local/bala/ballerinax/azure.mysql/0.1.0/any/platform/any/mysql-connector-java-8.0.20.jar
```

**Steps to reproduce:**
* Build the connector in the GitHub repository[1] and push the build artifacts to local central. 
* Run the ballerina program using the connector without providing the driver-jar dependency in the `Ballerina.toml` file. Sample program[2]

1.  https://github.com/ballerina-platform/module-ballerinax-azure.mysql
2. https://gist.github.com/daneshk/848d66afeff9e62c99dc3cbf93848d14

Expected Outcome
The program should run without any errors as the driver-jar is already packed inside the connector.

Actual Outcome
Getting the below error while running the programs 

```
error: Error while loading database driver. This may be because the database driver path is not configured correctly in the `Ballerina.toml` file or provided database driver version is not supported by the connector
```
This error comes because we get a CNF error when trying the load driver classes.

**Affected Versions:**
Ballerina Swanlake alpha5

**Comment by azinneera** [comment]
This is fixed in Beta1 with https://github.com/ballerina-platform/ballerina-lang/pull/30104

**Comment by daneshk** [comment]
when we add `jballerina.java` import and ignore it like `import ballerina/jballerina.java as _;`, we able to build and run the test successfully. As we already fixed in the `beta.1` and we found a workaround. We can proceed it
