### ISSUE TITLE
Same variable cannot repeat in a match pattern

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#31329]
VS Code gives the following error when nballerina/compiler is loaded.
![image](https://user-images.githubusercontent.com/9362271/122754910-d9336300-d2b1-11eb-88a0-20fe0f5eb11b.png)

But if you build the project, these errors are not shown.

**Comment by manuranga** [comment]
I believe this should be fixed in beta2

**Comment by nadeeshaan** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/31031. This will be available in swanlake-beta2 onwards Hence closing the issue. If the issue exists further, please reopen.
