### ISSUE TITLE
Add diagnostics to the Annotation and Documentation Nodes when they are not attached to a construct

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#31356]
**Description:**
$subject as per the LS requirements.

Related Comments: https://github.com/ballerina-platform/ballerina-lang/pull/31342#issuecomment-865514963, https://github.com/ballerina-platform/ballerina-lang/pull/31342#issuecomment-865617446
Related PR: #29751

**Comment by lochana-chathura** [comment]
@nadeeshaan @IMS94 would the same diagnostic (`annotation.not.attached.to.a.construct`) be enough for both top-level and object-level? Top-level we have `variable-decl` as the parent and at the object-level we have `object-field` as the parent.

or do we need two types? 
Let's say `annotation.not.attached.to.a.top.level.construct`, `annotation.not.attached.to.a.object.member`

**Comment by IMS94** [comment]
@lochana-chathura For our use case, we can manage with a single diagnostic. We just want to know if there's no attached node for a given annotation node and if yes, show all annotation suggestions. 

But, having a separate diagnostic for object members will come in handy to filter out object field/method specific annotations. If you can add 2 separate diagnostics, that'll be helpful.
