### ISSUE TITLE
Diagnostic provided when try to user a `foreach` loop over a stream with completion type `error` is confusing/wrong

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#31366]
**Description:**
```ballerina
public function main() returns error? {
    var l = [1, 2, 3];
    // just to get the compiler happy
    stream<int, error> streamResult = <stream<int, error>> <any> l.toStream();
    
    foreach var i in streamResult { // incompatible types: expected 'int', found '(int|error)'(BCE2066)
        
    }
}
```

I think given diagnostic here is confusing, and feels like something wrong with the type of variable `i` but then it's a `var` and not something user provided.
The error should say that, we can't iterate over a stream like this.

**Steps to reproduce:**

**Affected Versions:**
Swan Lake beta1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
See https://github.com/ballerina-platform/ballerina-lang/issues/28264#issuecomment-1477631113.
