### ISSUE TITLE
Couldn't get the ballerinax stdlib modules in the auto Completions

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#31370]
**Description:**
$subject. See the following images for more info.

<img width="679" alt="Screenshot 2021-06-22 at 11 14 46 AM" src="https://user-images.githubusercontent.com/12771261/122929879-0f8fe180-d389-11eb-890e-0e5c8f2c7995.png">

<img width="608" alt="Screenshot 2021-06-22 at 11 16 23 AM" src="https://user-images.githubusercontent.com/12771261/122929994-2d5d4680-d389-11eb-8b1a-28c0f41631fb.png">

This issue gets due to the ballerinax modules are not in the distribution. But this issue didn't solve even after running `bal run` command.

Affected Versions:
SLBeta1

**Comment by IMS94** [comment]
@kalaiyarasiganeshalingam After `bal run`, did you reload the window?

**Comment by IMS94** [comment]
Inability to pull an unavailable module from central is currently a limitation in LS which we plan to address along with #30757

**Comment by kalaiyarasiganeshalingam** [comment]
> @kalaiyarasiganeshalingam After `bal run`, did you reload the window?
Yes, I reloaded the window. But it will work, If we import that manually after being pulled from central.

**Comment by mohanvive** [comment]
This issue will be resolved with https://github.com/ballerina-platform/ballerina-lang/issues/30757.
