### ISSUE TITLE
[LS] Incorrect resolution of context when the cursor is positioned within leading minutiae 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#31382]
**Description:**
$subject observed for the following cases.
```ballerina
public function testFunction() {
    isolated <cursor>
}
```
```ballerina
public class TestClass {
    isolated <cursor>
}
```
The resolved context for the completion provider is functionBodyBlockNodeContext in the first case instead of variable declaration and ClassDef in the second in the second case.

Following is the syntax tree for the first case
![syntax tree](https://user-images.githubusercontent.com/35211477/123037246-f419ea80-d40b-11eb-8595-ebf8f465f428.png)

**Comment by IMS94** [comment]
Blocked by #31406
