### ISSUE TITLE
[LS] Access modifiers (public/private) are suggested for nodes which already have an access modifier

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#31401]
**Description:**
$subject

Consider following code:
```
class MyClass {
    private <cursor>
}

public <cursor>
```
At `<cursor>` the `private/public` keywords are shown again.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 2 SNAPSHOT

**Comment by malinthar** [comment]
May be related to: https://github.com/ballerina-platform/ballerina-lang/issues/31382
