### ISSUE TITLE
Language Server drops path parameter symbols from suggestions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31411]
**Description:**
Consider the following source snippet where the completion suggestions does not suggest the path parameter `bar`.

```
import ballerina/http;
service  on new http:Listener(8080) {
    resource function get foo/[string bar](http:Caller caller, http:Request req) {
        string s = bar;
        <cursor>
    }
}
```

**Affected Versions:**
swanlake beta1 at least

**Comment by IMS94** [comment]
Closing this since #31413 has been merged into staging branch which will be merged to master after beta 2 release.
