### ISSUE TITLE
Parser sees var name starting with _ as a wildcard binding

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#31421]
**Description:**
```ballerina
string '_&"*%_var = "sample value";
```

**Steps to reproduce:**

**Affected Versions:**
SL beta 2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Parsing as `string '_ MISSING[;] MISSING[function]&"*%_var = "sample  MISSING[=]value MISSING[+]"; MISSING[;]`
 which is the excepted behavior as characters have not been excluded with `\`.

With https://github.com/ballerina-platform/ballerina-lang/issues/30470 we will make `_` reserved keyword. Yet one can use `_` as a `variable-reference` with a quote. Let's keep this issue to address that problem.
