### ISSUE TITLE
Diagnostics has ambiguous words

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#31429]
**Description:**
See the following images for more info
<img width="800" alt="Screenshot 2021-06-25 at 1 15 32 PM" src="https://user-images.githubusercontent.com/12771261/123389459-86aabd00-d5b7-11eb-92d1-0f7fc257272f.png">

<img width="993" alt="Screenshot 2021-06-25 at 1 17 44 PM" src="https://user-images.githubusercontent.com/12771261/123389711-c7a2d180-d5b7-11eb-9e3c-c0b680118150.png">

**Steps to reproduce:**
Copy the following codes on the VSCode

```ballerina
import ballerina/http;

listener http:Listener weatherReporter = new (9091);
service /weather on weatherReporter {

    resource function post schedule(@http:Payload json payload,) returns error|string {}
}
```

```ballerina
public function main() {
    test("Hi");
}

function test(string input,) {}
```

**Comment by lochana-chathura** [comment]
Related to #29168
