### ISSUE TITLE
`foreach` statement added with broader types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#31436]
**Description:**
$title. `foreach` statement for a `string` variable gets added with `string` instead of `string:Char` as the iteration type. This change was recently introduced in the FE - https://github.com/ballerina-platform/ballerina-lang/pull/31078.

**Steps to reproduce:**
```ballerina
public function main() {
    string s = "foo";

   s.f<cursor>
}
```

Accepting adds
```ballerina
    foreach string item in s {
        
    }
```

but we should add

```ballerina
    foreach string:Char item in s {
        
    }
```

**Affected Versions:**
slbeta2-rc3

**Comment by MaryamZi** [comment]
For `xml<T>`, the iteration value type is `T`, but currently gets added with `xml<T>`.

```ballerina
public function main() {
    xml<xml:Element> x = xml `<hello/>`;

    x.f<cursor>
}
```

adds

```ballerina
   foreach xml<xml:Element> item in x {
       
   }
```

but should add

```ballerina
   foreach xml:Element item in x {
       
   }
```

Also see https://ballerina.io/ballerina-spec/spec.html#section_5.1.6

**Comment by malinthar** [comment]
Blocked  by #31521
