### ISSUE TITLE
Strings with code points > 0xFFFF are handled incorrectly

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31444]
For example:

```
import ballerina/io;

public function main() {
   string s = "\u{1F600}";
   io:println("Should be 1: ", s.length());
}
```

prints

```
Should be 1: 2
```

This is on slbeta1.

**Comment by riyafa** [comment]
The emoji form of `\u{1F600}` is 😀[[1]](https://emojipedia.org/emoji/%F0%9F%98%80/). When we print the emoji as in the following code:
```
import ballerina/io;

public function main() {
   string s = "\u{1F600}";
   io:println("Should be 1: ", s.length());
   s = "😀";
   io:println("Should be 1: ", s.length());
}
```
the following is printed:
```
Should be 1: 2
Should be 1: 1
```
Notice that it prints the length correctly for the emoji.
So investigating the bir dump noticed the following:
```
 bb0 {
        %1 = ConstLoad ὠ0;
        %4 = ConstLoad -1;
        %7 = ConstLoad Should be 1: ;
        %6 = <Printable> %7;
        %5 = <Printable> %6;
        %11 = length(%1) -> bb1;
    }
    bb1 {
        %6 = <Printable> %11;
        %8 = <Printable> %6;
        %3 = newArray ...[%4];
        %12 = println(%3) -> bb2;
    }
    bb2 {
        %1 = ConstLoad 😀;
        %11 = ConstLoad -1;
        %7 = ConstLoad Should be 1: ;
        %6 = <Printable> %7;
        %5 = <Printable> %6;
        %4 = length(%1) -> bb3;
    }
```
In the line ` %1 = ConstLoad ὠ0;`, the value of `\u{1F600}` is parsed incorrectly by the parser. Hence this issue is with regards to the parser rather than the runtime implementation of BString. Hence removing the `Team/JBallerina` label

**Comment by manuranga** [comment]
Issues exist even for chars in ascii range.

```ballerina
import ballerina/io;
public function main() {
    string s = "\u{97}";
    io:println(s.toBytes());
    io:println(s);
}
```
Above code prints
```
[194,151]

```
But it should be
```
[97]
a
```

**Comment by lochana-chathura** [comment]
> But it should be
> 
> ```
> [97]
> a
> ```
As per the spec, 
"In a NumericEscape, CodePoint must valid Unicode code point; more precisely, it must be a **hexadecimal** numeral ..."
Therefore we get  `a` for `string s = "\u{61}";`

**Comment by manuranga** [comment]
Ya I should have put `"\u{61}"`, but still current output for `"\u{97}"` is also wrong, is that being fixied in your pr?

**Comment by lochana-chathura** [comment]
> Ya I should have put `"\u{61}"`, but still current output for `"\u{97}"` is also wrong, is that being fixed in your pr?

ASCII range seems to be working fine. 151 is the decimal equivalent of 0x97, which is out of the ASCII range. 
Therefore with `toBytes()`/ UTF 8  we get c2 97 => [194,151] is the expected behaviour?

**Comment by manuranga** [comment]
Makes sense.
