### ISSUE TITLE
[LS] Goto definitions doesn't work within query expressions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#31453]
**Description:**
Consider the following source code taken from https://github.com/ballerina-platform/nballerina.
```ballerina
function listSources(string initialChars) returns string[][]|io:Error|file:Error {
    return from var entry in check file:readDir(SOURCE_DIR)
           let string path = entry.absPath
           // JBUG #31360 gets a bad, sad if includePath is inlined in the obvious way
           where check includePath(path, initialChars)
           select [path];
}
```

Within the query pipeline, if we try to goto definition of `path`, `SOURCE_DIR` or `entry`, it says no definitions found. This source is located in https://github.com/ballerina-platform/nballerina/blob/main/compiler/tests/testSuite.bal.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 2 RC4

**Comment by malinthar** [comment]
@IMS94 Could not reproduce on the slbeta3-snaphsot. My suspicion is  LS might have broken when you tried go to definition. Could you try again?

**Comment by IMS94** [comment]
I noticed this earlier on nballerina project. I can't reproduce that now. We can close this.
