### ISSUE TITLE
Gradle task for `:ballerina-cli:test` does not build all tests locally

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#31462]
**Description:**
When building the `:ballerina-cli` locally, the test task executes tests inconsistently. RunCommandTest doesn't get executed along with a few others. On some occasions, tests don't execute at all. 

This makes it difficult to write new tests and verify that the feature works properly. Running with 'no build cache' or 'rerunning all tasks' does not rectify this issue.  

**Steps to reproduce:**
Run gw build on ballerina-cli

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Does not reproduce locally. Hence, closing.
