### ISSUE TITLE
Fix service context completion for on keyword

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31489]
**Description:**
Consider the following source snippet,

`service TestObject <cursor>`

**Steps to reproduce:**
At the given cursor position only the `on` keyword should be suggested.

**Affected Versions:**
swanlake beta1 at least

**Comment by lochana-chathura** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/31504#issuecomment-880422016

**Comment by lochana-chathura** [comment]
Now we can use the following API to access the leading invalid tokens.
https://github.com/ballerina-platform/ballerina-lang/blob/1dc0f3d9dcef94a4bad7a01a997f071f6b7bc687/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/Node.java#L156

i.e. `node.leadingInvalidTokens()` will give the qualifier list.
