### ISSUE TITLE
Java command line options do not get considered when 'bal run' is used for running a Ballerina file or a package

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#31491]
**Description:**

If the java heap size needs to be increased to run a Ballerina program, changing the java command line options `-Xms -Xmx` in the `BAL_HOME/bin/bal` file have no effect in the Ballerina runtime jvm heap size,  if `bal run` is used inside a ballerina package or to run a `file.bal` Currently it works only when using `bal run` with a `file.jar`.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
The `-Xms` and `-Xmx` can be set with `JAVA_OPTS` environment variable.
