### ISSUE TITLE
Mutating a value during iteration should panic

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#31494]
**Description:**
```ballerina
import ballerina/io;
public function main() {
    int[] v = [1, 2];

    foreach var item in v {
        io:println(item);
        var res = v.remove(1);
        io:println("Removed" + res.toString());
    }
}
```

Output: 

 ```
1
Removed2
2
error: {ballerina/lang.array}IndexOutOfRange {"message":"array index out of range: index: 1, size: 1"}
        at ballerina.lang.array.1_1_0:remove(array.bal:141)
           bbe:main(bbe.bal:7)
```

As per spec

> Mutation of a structured value during iteration is handled as follows. A call to next() must panic if there has been any mutation to the structured value since the iterator was created other than the following:
>  1. removing a member of the structured value that a preceding call to the iterator has already returned;
>  2. changing the member associated with an existing key.

**Steps to reproduce:**

**Affected Versions:**
SL Beta 2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Depends on https://github.com/ballerina-platform/ballerina-spec/issues/899
