### ISSUE TITLE
Enable RefTypeTest.testInteropWithJavaStringReturn

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#31516]
**Description:**
`RefTypeTest.testInteropWithJavaStringReturn` was disabled in #31514 to get the master to be stable.

**Comment by HindujaB** [comment]
This test is enabled in the current master. 
https://github.com/ballerina-platform/ballerina-lang/blob/b64c9805023ca9bd9a1fff25d0340a0639529059/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/javainterop/RefTypeTests.java#L231

Hence closing the issue.
