### ISSUE TITLE
Type narrowing can continue after assignment of value belonging to narrowed type

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#31531]
Spec issue : https://github.com/ballerina-platform/ballerina-spec/issues/842

**Comment by rdulmina** [comment]
This requirement is already there in master
https://github.com/ballerina-platform/ballerina-lang/blob/266b2d3dc65f96a6644bfd0a8ea1fae42d88ba03/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SemanticAnalyzer.java#L4092-L4097
