### ISSUE TITLE
[LS] Type descriptors are suggested in RecordFiledName context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#31543]
**Description:**
Consider the code segment below.

```ballerina
type myType record {|
    int in<cursor>
|};
```
LS suggests type descriptors  in the cursor position as depicted below. 
![record](https://user-images.githubusercontent.com/35211477/124115641-acd6ce00-da8b-11eb-8ef1-b2989c7868e3.png)

**Affected Versions:**
slbeta3-snapshot

**Comment by mohanvive** [comment]
It is fixed in the latest master, now. Hence closing the issue.
