### ISSUE TITLE
Auto completion support for debugger expression evaluation

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#31571]
**Description:**
$subject would be a nice-to-have feature for the Ballerina debugger expression evaluator, where we can improve the VSCode debugger to provide a suggestions list, when the user start typing in 
- Evaluation console
- Watch window 
- Conditional breakpoints dialogs

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment]
- [ ] Check how conditional breakpoints completion work
- [ ] Check if LS get text changes from console 
- [ ] Check how java do it
- [ ] Check if we can reuse LS Utils to give the completions

**Comment by NipunaRanasinghe** [comment]
Closing since we have added completion support for evaluation window with https://github.com/ballerina-platform/ballerina-lang/pull/33152 and have created separate issues for all the sub tasks.
