### ISSUE TITLE
CLI flag to override target dir

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31574]
**Description:**
Have a flag to change `target` dir location and name, when running `bal build` and other tasks from a package.

caution: need to decide what to do when both this flag and `--output` are given at the same time.

**Describe your problem(s)**
When ballerina build is run from an external build tool like cmake or gradle, we should redirect ballerina build dir to tool specific location.

**Describe your solution(s)**
Have a CLI flag eg: `bal build --output-dir ../build`, this should write all the files to `../build` (not to `../build/target`).

**Comment by hevayo** [comment]
Probably we can repurpose --output flag here. Currently --output flag is not supported for projects hence we can use it to point to build directory.

**Comment by sameerajayasoma** [comment]
Unfortunately, we have another issue for the same topic. https://github.com/ballerina-platform/ballerina-lang/issues/32295

It has up-to-date details. I am closing this one.
