### ISSUE TITLE
Diagnostics for import module shown in problems tab

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#31582]
**Description:**
If you try the go-to-definition feature; all diagnostic errors/warnings appear under the `Problems` tab for the import module and it does not get cleared after closing the navigated tab.

![goto_diagnostics](https://user-images.githubusercontent.com/15815199/124504270-bf7f3900-dde4-11eb-85d6-001d4196898c.gif)

**Steps to reproduce:**

**Affected Versions:**
SL Beta 2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This particular behaviour has been resolved with the project API changes and the respective LS changes. This can no longer observed when we go to a standard library source. Hence closing this issue. If the issue can be observed further, please feel free to reopen the issue.
