### ISSUE TITLE
Consider effective types/narrowed types when checking unreachability in match pattern with type quard

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#31588]
**Description:**
$title

**Describe your task(s)**
```ballerina
public function main() {
    int|boolean a = 1;

    match a {
        var x if a is int|string => {

        }
        var y if a is int|int[] => { // this should be unreachable

        }
    }
}
```

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/30191

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Instead of assignability, we should check intersections with effective/narrowed type at https://github.com/ballerina-platform/ballerina-lang/pull/31428/files#diff-6b4a8cb1f7bd56d5a95a80500c4febcba531cdde5af59b66a477acd35e8485acR1525.
