### ISSUE TITLE
Disabling Test Groups does not Work when a Test Belongs to Multiple Groups

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#31613]
**Description:**
When a test belongs to multiple groups, disabling a group does not disable the tests belonging to that test group.

Consider the following scenario:

```ballerina
import ballerina/io;
import ballerina/test;

@test:Config {
    groups: ["group1", "group2"]
}
function test1() {
    io:println("Test1");
}

@test:Config {
    groups: ["group2"]
}
function test2() {
    io:println("Test2");
}
```

When we run 
```bal test --disable=group1``` 

This prints the following:

```
Running Tests

	sample
Test1
Test2
```

But the `test1` should be skipped here.

**Comment by Dilhasha** [comment]
@ThisaruGuruge 

It works as expected for me. Can you please try with the following command?

`bal test --disable-groups=group1`

**Comment by ThisaruGuruge** [comment]
Is the correct flag is `--disable-groups`? Sorry, my bad. This is working.
