### ISSUE TITLE
Language server suggest completions inside comments

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#31610]
**Description:**
Please see the following image where I get suggestions inside comment sections
![Screenshot from 2021-07-07 11-45-56](https://user-images.githubusercontent.com/323846/124709488-2aca2780-df19-11eb-9cb2-7e4d26c06341.png)

**Affected Versions:**
slbeta2

**Comment by BuddhiWathsala** [comment]
Still, I'm getting this in the tooling version `2.1.1`. Those suggestions are not module specific, but still, there are some generic suggestions. I even have a function called `foo` in this program, it also gives as a suggestion.

![Screenshot 2021-11-02 at 17 57 23](https://user-images.githubusercontent.com/18663444/139846280-e89b0bdf-0885-4c64-9325-37088996c0a0.png)

**Comment by nadeeshaan** [comment]
@BuddhiWathsala what's the Ballerina version you are using. I'm checking this on master branch and it is not providing any suggestions

**Comment by BuddhiWathsala** [comment]
I was using swan lake beta 4.

**Comment by BuddhiWathsala** [comment]
I was using swan lake beta 03.

**Comment by BuddhiWathsala** [comment]
Tried this with SL beta 05 and did not occur anymore. Hence closing the issue.
