### ISSUE TITLE
Getting `Time out` issue often when trying push new bala to central

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-lang#31647]
**Description:**
Getting `Time out` issue often when trying push new bala to central

**Steps to reproduce:**
We are getting the following issue when we try to push a new bala to central. This doesn't happen always. It gets success for some instances & fails for some instances.

Ballerina.toml structure
```
[package]
org = "rolandhewage"
name = "cdatatest.jira"
version = "0.2.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["CData","jira"]

[[platform.java11.dependency]]
path = "../../libs/cdata.jdbc.jira.jar"
```

Package includes following files
Ballerina.toml
main.bal
Package.md

```
 failed to push the package: 'rolandhewage/cdatatest.jira:0.2.0' to the remote repository 'https://api.central.ballerina.io/2.0/registry/packages'. reason: timeout
```

![Screenshot from 2021-07-09 08-25-02](https://user-images.githubusercontent.com/44081958/125022137-a2bf5b80-e099-11eb-83f5-30188b40673d.png)

**Affected Versions:**
SL Beta 1

**OS, DB, other environment details and versions:**
Ubuntu 20.04
JDK 11

**Suggested Labels (optional):**
Area/Central

**Comment by hemikak** [comment]
I was able to push the same package using curl. Timeout issues usually come when there connection issues.

**Comment by hemikak** [comment]
Please reopen if issue exists. Try using a different ISP.
