### ISSUE TITLE
Function with return type never which doesn’t panic should give an error

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#31645]
**Description:**

Currently the following compiles and runs without any problem.
```
public function main() {
    function_which_never_returns();
}

public function function_which_never_returns() returns never {
    int a = 2;
}
```
This should give an error because the function must never complete normally.

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/29292.
