### ISSUE TITLE
Add more query expression/action tests to cover uncovered visits in QueryDesugar

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#31658]
**Description:**
$title

**Describe your task(s)**
Add tests to cover uncovered areas in the query desugar(check the following PR).
https://github.com/ballerina-platform/ballerina-lang/pull/31242/files

**Comment by gimantha** [comment]
Also add some tests to cover the review comments in this pr https://github.com/ballerina-platform/ballerina-lang/pull/31926
