### ISSUE TITLE
Can't run a selected test with map data provider

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31672]
After switching the data provider to use `map<>` style, I can't run a individual test anymore.

`bal test --tests "nballerina.front:testParser#int i = {}"`  gives `error: there are test failures`
 
Here is a sample set of tests we have in nBallerina project. (Note the first case has a new line in it, and `"` is part of the test case name)
```
                [pass] testParser#
0
                [pass] testParser#"\t"
                [pass] testParser#"     "
                [pass] testParser#"\n"
                [pass] testParser#"\r"
                [pass] testParser#"\\"
                [pass] testParser#"\""
                [pass] testParser#"what"
                [pass] testParser#"Say \"what\" again."
                [pass] testParser#x
                [pass] testParser#int i = {}
```

**Comment by manuranga** [comment]
I anticipated this would happen, that is why I suggested string escape approach in [31146 (comment)](https://github.com/ballerina-platform/ballerina-lang/issues/31146#issuecomment-863982694). Please reconsider that or something similar.

**Comment by azinneera** [comment]
With beta3-SNAPSHOT, its happening when running just `bal build` (without the `--tests` flag). However it passes with beta2.1
