### ISSUE TITLE
Error when casting json to record needs to be more specific

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#31694]
**Description:**
When casting json to a record if json and record is incompatible we get the following error
```
error: {ballerina}TypeCastError {"message":"incompatible types: 'map<(json & readonly)> & readonly' cannot be cast to 'Coord'"}
        at converting_from_json_to_user_defined_type:main(converting_from_json_to_user_defined_type.bal:17)
```
Here is it is hard to figure out what exactly went wrong when you are dealing with a complex json structure. It would be better if we can give the cause of the above error.  ie specifying the missing fields.

Observed in slbeta2

**Comment by Nadeeshan96** [comment]
Fixed with #32961
