### ISSUE TITLE
Bad code generated for byte comparison

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31700]
This prints `false` when it should print `true`.

```
import ballerina/io;

public function main() {
    io:println(testByte(0x20));
}

function testByte(byte b) returns boolean {
    if b >= 0x20 {
       return true;
    }
    return false;
}
```

Changing `byte` to `int` or changing `0x20` to decimal both make the problem go away.

**Comment by hasithaa** [comment]
@warunalakshitha Can we add this to the current sprint?

**Comment by warunalakshitha** [comment]
Had a quick check. There is a bug in codegen specific to byte. We plan to revisit codegen and test all byte specific operations since we found multiple issues related to byte operations. 

@hasithaa since today is last date of sprint we will add as high priority item in next sprint. BTW @Nadeeshan96 will work on this.

**Comment by jclark** [comment]
If it’s a bug in codegen, why does changing 0x20 to 32 avoid the bug?

**Comment by warunalakshitha** [comment]
In BIR, Operand type for '0x20' is byte but for '32' is int. During codegen we specifically handle byte type. As an example following code will fail too :(.

```ballerina
public function main() {
    byte a =32;
    byte b = 32;
    io:println(a >= b);
}
```

**Comment by jclark** [comment]
Sounds like the BIR is wrong then. Whether a integer constant is decimal or hexadecimal shouldn't affect whether it is treated as a byte. Any integer in the range 0 to 255 belongs to the `byte` type regardless of whether it is written in decimal or hex.

**Comment by Nadeeshan96** [comment]
> Sounds like the BIR is wrong then. Whether a integer constant is decimal or hexadecimal shouldn't affect whether it is treated as a byte. Any integer in the range 0 to 255 belongs to the `byte` type regardless of whether it is written in decimal or hex.

Created a new issue #31750 to handle this.
