### ISSUE TITLE
Method call expression should support invoking a function pointer when it's a field.

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#31710]
**Description:**
```ballerina
class C {
    function () returns int foo = function () returns int => 1;
}

public function main() {
    C c = new();
    // Below should be allowed.
    c.foo(); // undefined method 'foo' in object 'C'(BCE2013)
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/22654
