### ISSUE TITLE
[LS] Avoid showing $CompilationError symbols 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#31745]
**Description:**
Consider the following source code
```ballerina
public function main() {
    io:println("Hello World!");
    <cursor>
}


function myfunc(int a, in) {
    
}
```

Get the following completion items at the cursor position
![Screenshot from 2021-07-16 11-57-50](https://user-images.githubusercontent.com/35211477/125903855-e99ee6e9-10d6-4cd9-8d2d-0ac2e250eacc.png)

we should avoid from adding the symbols which has $CompilationError.

**Steps to reproduce:**
Follow above steps

**Affected Versions:**
slbeta3-snapshot

**Comment by malinthar** [comment]
To filter out $CompilationError symbols the visibleSymbols() API added by the following PR can be used. 
https://github.com/ballerina-platform/ballerina-lang/pull/31072
We should pass DiagnosticState.VALID to get valid symbols.

**Comment by nadeeshaan** [comment]
This is bit of a tricky case. In this particular scenario, if we skip processing the symbol when generating the completion item, that will provide a function snippet with a single parameter. So, IMHO, as per the UX point of view, we should be able to provide a snippet which can explicitly imply that the particular definition is having an error. 

@pubudu91 @IMS94 WDYT?

**Comment by malinthar** [comment]
> IMHO, as per the UX point of view

Agreed that is a valid point. However, if we consider a similar scenario in IDEA java, they does not show the symbol with the error as depicted in the following figures.
![img1](https://user-images.githubusercontent.com/35211477/126280748-df884f85-d27c-41ab-8202-577e0ed9cd67.png)
![img2](https://user-images.githubusercontent.com/35211477/126280764-3060a819-1007-4ba0-8b72-b7c565c84677.png)

**Comment by IMS94** [comment]
> This is bit of a tricky case. In this particular scenario, if we skip processing the symbol when generating the completion item, that will provide a function snippet with a single parameter. So, IMHO, as per the UX point of view, we should be able to provide a snippet which can explicitly imply that the particular definition is having an error.
> 
> @pubudu91 @IMS94 WDYT?

@nadeeshaan The scope of this issue is to avoid (or optimize) showing compilation errors in suggestions using the new API added in #31072. I agree with your argument. If that's the case, we have to handle compilation errors depending on the context.
 
- For function invocations, we can modify `FunctionCompletionItemBuilder#getFunctionInvocationSignature()` to handle parameters with compilation errors. Whether to disregard or show something like `unknown/anydata <varName>`.
- For variables, we can decide if we avoid showing erroneous ones (we have to handle redeclared variables anyway) 
WDYT?

**Comment by nadeeshaan** [comment]
> > This is bit of a tricky case. In this particular scenario, if we skip processing the symbol when generating the completion item, that will provide a function snippet with a single parameter. So, IMHO, as per the UX point of view, we should be able to provide a snippet which can explicitly imply that the particular definition is having an error.
> > @pubudu91 @IMS94 WDYT?
> 
> @nadeeshaan The scope of this issue is to avoid (or optimize) showing compilation errors in suggestions using the new API added in #31072. I agree with your argument. If that's the case, we have to handle compilation errors depending on the context.
> 
> * For function invocations, we can modify `FunctionCompletionItemBuilder#getFunctionInvocationSignature()` to handle parameters with compilation errors. Whether to disregard or show something like `unknown/anydata <varName>`.
> * For variables, we can decide if we avoid showing erroneous ones (we have to handle redeclared variables anyway)
>   WDYT?

Agreed. If we cannot filter this from the Semantic API level, we need to filter it from the LS

**Comment by IMS94** [comment]
@nadeeshaan There's an overloaded method in `SemanticModel` which takes desired diagnostic states (VALID, REDECLARED, UNKNOWN_TYPE). We can use that accordingly at LS side.

**Comment by nadeeshaan** [comment]
> @nadeeshaan There's an overloaded method in `SemanticModel` which takes desired diagnostic states (VALID, REDECLARED, UNKNOWN_TYPE). We can use that accordingly at LS side.

@IMS94 yes, I think this is the API we discussed for addressing this similar use-case as well. I think using this API should be the ideal solution. Shall we incorporate this then?

**Comment by IMS94** [comment]
Sure! I will look at this.

**Comment by IMS94** [comment]
Created https://github.com/ballerina-platform/ballerina-lang/issues/32038 to improve variable completions by filtering invalid/redeclared symbols.
