### ISSUE TITLE
Compile error when calling length() on string FiniteTypes

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#31749]
Consider the following Code.

```ballerina
public type EqualityOp "==" | "!=" | "===" | "!==";

public type EqualityInsn record {|
    EqualityOp op;
|};

function foo(EqualityInsn e) {
    if ((e.op).length() == 2) {

    }
}
```
This gives the compile error 
`undefined function 'length' in type '==|!=|===|!=='`

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/31863 (https://github.com/ballerina-platform/ballerina-lang/pull/31863/commits/0d3fd9b7576359556276ffd07c0d474829f366ba).

**Comment by pcnfernando** [comment]
Tests added in https://github.com/ballerina-platform/ballerina-lang/pull/31927
