### ISSUE TITLE
Iterating over strings using `foreach` loop for uni-code characters

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#31767]
**Description:**
Iterating over strings using `foreach` loop will lead to different results for certain uni-code characters.

**Steps to reproduce:**
```
import ballerina/io;

string test = "￿"; // utf-8 codepoint `EFBFBF`
string test2 = "𐀀"; // utf-8 codepoint `F0908080`

function loop1(string s) {
    foreach var char in s {
        io:println("$", char);
    }
}

function loop2(string s) {
    foreach int i in 0 ..< s.length() {
        string char = s[i];
        io:println("#", char);
    }
}

public function main() {
	loop1(test);
	loop2(test);
	io:println("------");
	loop1(test2);
	loop2(test2);
}
```
Result from `loop2` and `loop1` are different
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Related to #31444

**Comment by lochana-chathura** [comment]
Parsing correctly from FE.

**Comment by HindujaB** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/31775
