### ISSUE TITLE
Remove null-check in `PositionUtil.withinRange()`

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#31764]
**Description:**
$title

**Describe your task(s)**
Previously we have added a `null`-check in PositionUtil.withiRange() to make sure to return `false` if the `nodePosition` is `null`
Ref: https://github.com/ballerina-platform/ballerina-lang/pull/31440

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Issue is no longer valid.
