### ISSUE TITLE
[Debugger] Invalid `xml` child variable representation

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#31793]
**Description:**
For `xml` variables, the number of child variable counts and its values are represented incorrectly.

**Steps to reproduce:**
- Consider the below code segment:
```
public function main() {

    xml x1 = xml `<parent>
                    <child1>
                        <grandchild1>"Hello"</grandchild1>
                        <grandchild2>"World"</grandchild2>
                    </child1>
                    <child2>
                        <grandchild1>"Hello"</grandchild1>
                        <grandchild2>"World"</grandchild2>
                    </child2>
                  </parent>`;
}
```
- Add a debug point at the last line of `main()` method and start the program in debug mode.
- Expand the `xml` variable and we could observe that the number of child variable counts and its values are represented incorrectly.
<img width="1059" alt="Screen Shot 2021-07-20 at 7 46 56 AM" src="https://user-images.githubusercontent.com/11292766/126252728-41e50e7f-5653-4103-8a79-c458ab7fc58f.png">

**Comment by NipunaRanasinghe** [comment]
This seem to be happening due to a potential bug in ballerina runtime representation of XML values. Created https://github.com/ballerina-platform/ballerina-lang/issues/31904 with detailed explanation on the observed runtime behaviour.
