### ISSUE TITLE
No completions for anonymous function within class

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#31792]
**Description:**
```ballerina
class F {
    function (int...) returns int k = function(int... r) returns int {
        r.<cursor> // no completions here
        return r[0];
    };
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
The Semantic API side issue of this seems to be getting fixed with #31909. Will have to reevaluate and see after it's merged as to what else needs to be fixed to support this.

**Comment by pubudu91** [comment]
Tagged the lang server label since the PR which addressed the Semantic API side issue of this has been merged.

**Comment by nadeeshaan** [comment]
This issue has been fixed in master. Hence we do not need any LS side fix. Hence closing the issue
