### ISSUE TITLE
Refactor default value handling of optional types

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#31790]
**Description:**

Modify `CommonUtil.getDefaultValueForType()` method to return an `Optional<String>` where it will return `Optional.empty()` when the type is an optional one.

Also add a new API to return a default value regardless of the type being an optional type.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment]
Should fix #31556 along with this.
