### ISSUE TITLE
Module symbols at compiler API are defined with the un-quoted package alias (not with the package alias name originally defined by the user)

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#31808]
**Description:**
$title

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Can you update this with a description of the issue?

**Comment by pubudu91** [comment]
The issue here is that we don't have a separate symbol for prefixes. For prefixes what we do is we create a module symbol and set its name to the prefix. Ideally, what we need to do is have a separate symbol kind for prefixes.
