### ISSUE TITLE
 int:toHexString returns wrong string for negative values

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31814]
According to spec: ``Negative numbers will have a `-` prefix.``.

```
import ballerina/io;

public function main() {
    io:println((-1).toHexString());
}
```
above code outputs 
```
ffffffffffffffff
```
Expected output is
```
-1
```

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33460
