### ISSUE TITLE
Range expression with hexadecimal numbers does not work

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#31827]
**Description:**

The following code snippets currently do not work. But they should be supported.
```ballerina
    foreach int i in 0x1 ... 0x5 { }
```
```ballerina
    foreach int i in 0x1 ..< 0x5 { }
```
**Given error message:**
```logtalk
Compiling source
        temp.bal
ERROR [temp.bal:(4:13,4:16)] incompatible types: expected 'other', found 'int'
ERROR [temp.bal:(4:22,4:33)] operator '..<' not defined for 'byte' and 'byte'
error: compilation contains errors
```
**Affected Versions:**
Ballerina Swan Lake Beta 3

**Suggested Labels (optional):**
Team/CompilerFE

**Comment by Nadeeshan96** [comment]
Another concern is that whether we can put `byte i` instead of `int i` there, or any other subtype of  `int` such as `int:Unsigned8`,`int:Signed32`, etc.

**Comment by lochana-chathura** [comment]
May be related to #33139

**Comment by lochana-chathura** [comment]
> Another concern is that whether we can put `byte i` instead of `int i` there, or any other subtype of `int` such as `int:Unsigned8`,`int:Signed32`, etc.

In the [range-expr](https://ballerina.io/ballerina-spec/spec.html#range-expr) section of the spec says,

> The result of a range-expr is a new object belonging to the object type Iterable<int,()> that will iterate over a sequence of integers in increasing order

Since the resultant type is `Iterable<int,()>` we can't hold the iterator value with a subtype of int.
