### ISSUE TITLE
Improve the diagnostic error when there are cyclic imports

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#31855]
**Description:**
When there is a cyclic dependency import among 2 modules inside a package, the compilation of one module is ignored completely. Therefore, the errors seem to be misleading and the user is not able to see clearly that this is caused due to a cyclic dependency import issue. The diagnostic error could be improved in this scenario.

**Describe your problem(s)**
* Create a project.
```
$ bal new test
```
* Create 2 modules.
```
$ cd test
$ bal add mod1
$ bal add mod2
```
* Introduce a cyclic import in between the modules.

**mod1:**
```bal
import ballerina/io;
import test.mod2;

public function hello1() {
    io:println("Hello World!");
    mod2:hello2();
}
```
**mod2:**
```bal
import ballerina/io;
import test.mod1;

public function hello2() {
    io:println("Hello World!");
    mod1:hello1();
}
```
* Error would be as follows:
```
Compiling source
	irushi/test9:0.1.0
ERROR [mod1.bal:(2:1,2:19)] cannot resolve module 'test.mod2 as mod2'
ERROR [mod1.bal:(6:5,6:18)] undefined function 'hello2'
ERROR [mod1.bal:(6:5,6:18)] undefined module 'mod2'
error: compilation contains errors
```

This error would be a bit more confusing when the project is large.

**Affected Version:** Ballerina Swan Lake Beta 2

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This is already tracked by https://github.com/ballerina-platform/ballerina-lang/issues/27371. Hence closing this.
