### ISSUE TITLE
Compiler gives incorrect error when the function definition assigned with a `var`

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#31850]
**Description:**

Consider following code,

```
// variable declaration//
var 'add = <function (int v1, int v2) returns int> __recall_any("'add");

any|error __last__ = __recall_any_error("__last__");
function __stmts() returns any {
    do {
                __last__ = (
                    add(1,2)
                );

    } on fail error e {
        __last__ = ();
        return e.message() + " " + e.detail().toBalString();
    }
}
```
In above code , add(1,2) line raises 

```
| error: undefined function 'add'
| 	add(1,2)
| 	^------^
| Compilation aborted due to errors.
```
But if we replace `var` with the `function (int v1, int v2) returns int`  in the variable declaration
as follows

`function (int v1, int v2) returns int 'add = <function (int v1, int v2) returns int> __recall_any("'add"); `

code segment execute without undefined function error.

Related to Ballerina Shell Testcase

`>> var add = function (int v1, int v2) returns int { return v1 + v2; };`
`>> add(5, 10)`

**Steps to reproduce:**
Execute above code segment

**Affected Versions:**
slbeta3

**Comment by pubudu91** [comment]
Smaller snippet reproducible in the regular compiler:
```ballerina
public function main() {
    int fnResult = fn(1,2); // error given for fn()
}

var fn = <function (int, int) returns int> foo();

function foo() returns any {
    return "";
}
```

**Comment by MaryamZi** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/29243.

**Comment by DamithaSenevirathne** [comment]
Related testcases disabled by the https://github.com/ballerina-platform/ballerina-lang/pull/31798 
Need to enable them later
