### ISSUE TITLE
Nil is added as the place-holder value for a `decimal`-typed field

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#31859]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Foo record {|
    decimal val;
|};

public function main() {
    Foo f = {v};
}
```

![decimal_default](https://user-images.githubusercontent.com/8376983/126688474-d692f7ed-4fac-4a07-93f6-5511ff9f69de.png)

Accepting `val` adds 
```ballerina
type Foo record {|
    decimal val;
|};

public function main() {
    Foo f = {val: ()};
}
```

Can't we use `0` instead?

**Affected Versions:**
slbeta2

**Comment by IMS94** [comment]
Will be fixed along with https://github.com/ballerina-platform/ballerina-lang/issues/31790
