### ISSUE TITLE
Type test expression on int subtypes gives a compilation error in some cases

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#31875]
**Description:**

Currently for K=8,16,32 and M=8,16,32
If `int:SignedK a = 1;` , checking `a is int:UnsignedM` or `a is byte` will give a compilation error if `M>=K`, otherwise no error
If `int:UnsignedK a = 1;` or `byte a = 1;` , checking `a is int:SignedM` will give a compilation error if `M<=K`, otherwise no error

**Steps to reproduce:**
```ballerina
public function main() {
    int:Signed8 a = 1;
    boolean ans  = a is int:Unsigned8;
}
```
gives
```logtalk
Compiling source
        temp.bal
ERROR [temp.bal:(5:20,5:38)] incompatible types: 'int:Signed8' will not be matched to 'int:Unsigned8'
error: compilation contains errors
```
**Affected Versions:**
Ballerina Swan Lake Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Team/CompilerFE 

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Btw
If `int:SignedK a = 1;` , checking `a is int:SignedM` will not give any compilation error
If `int:UnsignedK a = 1;` or `byte a = 1;` , checking `a is int:UnsignedM` or `a is byte` will not give any compilation error

**Comment by Nadeeshan96** [comment]
To do : add missing cases here https://github.com/ballerina-platform/ballerina-lang/blob/202cb2d7595d3dafb1429c607ce27e55688946b0/tests/jballerina-unit-test/src/test/resources/test-src/expressions/binaryoperations/type-test-expr.bal#L1282 after the issue is closed.

**Comment by MaryamZi** [comment]
Part of https://github.com/ballerina-platform/ballerina-lang/issues/24451.
