### ISSUE TITLE
Module ID for the Stream Type Definitions are identified as `lang.annotations`

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31884]
**Description:**
$title.

Consider the following source snippet, which is defined within a multi-module project. (Not in default module)

```
type ClassType Class1;

type StreamType1 stream<int>;

type StreamType2 StreamType1;

type TestRecord record {|
    
|};
```

- Consider `TestRecord` and `ClassType` where the module ID is captured as the current module's module ID - which is expected
- When we consider `StreamType1` and `StreamType2`, the module ID captured is `lang.annotations` - which is expected to capture the current module. 
When checked, the `BSymbol` itself has this wrong information captured when we access `symbol.owner` within the semantic API.

**Affected Versions:**
SwanLake-Beta2 at least

**Comment by dulajdilshan** [comment]
Related to this issue: https://github.com/ballerina-platform/ballerina-lang/issues/26284
