### ISSUE TITLE
Type references on the same module but on different files aren't listed

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#31885]
**Description:**
The references API doesn't list the references on a different file within the same module.

**Steps to reproduce:**
file A
```
type AccountNotFoundError error;
```

file B
```
function name() {
    AccountNotFoundError accountNotFoundError = error AccountNotFoundError("ACCOUNT_NOT_FOUND", count = 500);
}
```
`AccountNotFoundError` on file B is not considered as a reference of the type object defined on file A.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Had a look at this. The references work when I check references using the type definition. But doesn't work when checking it using the type refs. I think this may be due to #26284. Will have a closer look and see.

**Comment by pubudu91** [comment]
Checked with Chiran's PR and the above scenario works with it.

**Comment by pubudu91** [comment]
Checked this in 2201.0.0 and it's working as expected. Hence closing this.
