### ISSUE TITLE
Incorrect field references for an object

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#31886]
**Description:**
The references API lists incorrect field references for the following scenario.

**Steps to reproduce:**
```
public type Address object {
    public string city;
    public string country;

    public function value() returns string;
};

Address address = object {
    public string city; //<GET reference for the city token>
    public string country;

    public function init() {
        self.city = "London";
        self.country = "UK";
    }

    public function value() returns string {
        return self.city + ", " + self.country;
    }

    function getCity() returns string => string `Default: ${self.city}`;
};

```
Currently, it returns the full object definition as the reference for the `city` token, but not the the actual references used inside the object.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Same as #31834
