### ISSUE TITLE
Accessing child elements of XML sequences return unexpected results

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#31904]
**Description:**
Refer to the below code example. Note that accessing the first element of the sequence using `xmlSequence.children().get(0)` returns an empty XML value and `xmlSequence.children().get(1)` returns the 0th element, as shown below.

```ballerina
public function main() {
    xml xmlSequence = xml `
                    <child1>
                        <grandchild1>"Hello1"</grandchild1>
                        <grandchild2>"World1"</grandchild2>
                    </child1>
                    <child2>
                        <grandchild1>"Hello2"</grandchild1>
                        <grandchild2>"World2"</grandchild2>
                    </child2>
                  `;
    var child1 = xmlSequence.children().get(0);
    var child2 = xmlSequence.children().get(1);
}
```

#### values of child elements
<img width="192" alt="Screenshot 2021-07-27 at 14 10 42" src="https://user-images.githubusercontent.com/29032600/127124448-cb0fec36-08c1-458d-b626-4852cf30e29c.png">

#### parent sequence 
<img width="280" alt="Screenshot 2021-07-27 at 14 12 08" src="https://user-images.githubusercontent.com/29032600/127124458-7b0f5302-4c9f-4a33-a6a6-960854f469e9.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
The `child1` variable is not empty, it is whitespace. This is the expected behaviour and not a bug. This is the whitespace between `<child1>` and `<grandchild1>`.

```ballerina
io:println(child1 is xml:Text); // true
io:println(child1 == xml ``); // false - not empty
```

If `child1` is

```
<child1><grandchild1>"Hello1"</grandchild1><grandchild2>"World1"</grandchild2></child1>
```

you will not get the whitespace XML text when calling `children()`.

**Comment by NipunaRanasinghe** [comment]
> The `child1` variable is not empty, it is whitespace. This is the expected behaviour and not a bug. This is the whitespace between `<child1>` and `<grandchild1>`.
> 
> ```ballerina
> io:println(child1 is xml:Text); // true
> io:println(child1 == xml ``); // false - not empty
> ```
> 
> If `child1` is
> 
> ```
> <child1><grandchild1>"Hello1"</grandchild1><grandchild2>"World1"</grandchild2></child1>
> ```
> 
> you will not get the whitespace XML text when calling `children()`.

Ah I see.. thanks for the clarification @MaryamZi 🙂 
In that case, I think what we should do is improving the debugger variable presentation to clearly represent whitespaces and empty values so that the debug users won't get confused in such contexts.

**Comment by NipunaRanasinghe** [comment]
Closing the issue since the observed behaviour is expected.
