### ISSUE TITLE
Unexpected result of .data() on a value of type  <xml<xml:Element>>

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#31911]
**Description:**

Unexpected result of `.data()` on a value of type `<xml<xml:Element>>`

**Steps to reproduce:**
Run `bal test bug-report.bal`  (see attached file `bug-report.bal.txt`)

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Attached files**
[bug-report.bal.txt](https://github.com/ballerina-platform/ballerina-lang/files/6886235/bug-report.bal.txt)

**Comment by MaryamZi** [comment]
Seems to be an issue with query expressions and depends on the expected type.

Works as expected when `xml<xml:Element>` is the expected type.

```ballerina
import ballerina/io;

public function main() {
    xml value = xml`
        <Element>data</Element>
        <Element>data</Element>
    `;

    any[] r1 = from var el in value
        select el.<Element>;
    io:println(r1.length());
    foreach int i in 0 ..< r1.length() {
        io:println(i, " ", r1[i] is xml:Element);
    }

    xml<xml:Element> r2 = from var el in value
        select el.<Element>;
    io:println(r2.length());
    foreach int i in 0 ..< r2.length() {
        io:println(i, " ", r2[i] is xml:Element);
    }
}
```

```cmd
5
0 false
1 true
2 false
3 true
4 false
2
0 true
1 true
```

**Comment by pcnfernando** [comment]
> ```ballerina
> import ballerina/io;
>
> public function main() {
>     xml value = xml`
>         <Element>data</Element>
>         <Element>data</Element>
>     `;
>
>     any[] r1 = from var el in value
>         select el.<Element>;
>     io:println(r1.length());
>     foreach int i in 0 ..< r1.length() {
>         io:println(i, " ", r1[i] is xml:Element);
>     }
>
>     xml<xml:Element> r2 = from var el in value
>         select el.<Element>;
>     io:println(r2.length());
>     foreach int i in 0 ..< r2.length() {
>         io:println(i, " ", r2[i] is xml:Element);
>     }
> }
> ```

As I see it; this works as expected.

If we rewrite the logic in the query expression using `foreach`; it would look like below
```ballerina
public function main() {
    xml value = xml `
        <Element>data</Element>
        <Element>data</Element>
    `;

    // any[] r1 = from var el in value
    //     select el.<Element>;
    // io:println(r1.length());
    // foreach int i in 0 ..< r1.length() {
    //     io:println(i, " ", r1[i] is xml:Element);
    // }

    any[] r1 = [];
    foreach var el in value {
        r1.push(el.<Element>);
    }
    io:println(r1.length()); // prints 5; (text, element, text, element, text)
    foreach int i in 0 ..< r1.length() {
        io:println(i, " ", r1[i] is xml:Element);
    }

    // xml<xml:Element> r2 = from var el in value
    //     select el.<Element>;
    // io:println(r2.length()); // prints 2; (element, element)
    // foreach int i in 0 ..< r2.length() {
    //     io:println(i, " ", r2[i] is xml:Element);
    // }

    xml r2 = 'xml:concat();
    foreach var el in value {
       r2 = r2 + el.<Element>;
    }
    io:println(r2.length()); // prints 2; (element, element)
    foreach int i in 0 ..< r2.length() {
        io:println(i, " ", r2[i] is xml:Element);
    }
}

```

@MaryamZi WDYT?

**Comment by MaryamZi** [comment]
Yeah, my bad. The comparison I should have used is `xml<xml:Element>[]`. 

```ballerina
    xml<xml:Element>[] r2 = from var el in value
        select el.<Element>;
    io:println(r2.length());
    foreach int i in 0 ..< r2.length() {
        io:println(i, " ", r2[i] is xml:Element);
    }
```

Prints the same as when `any[]`.
```
5
0 false
1 true
2 false
3 true
4 false
```

My original example compared list and xml, but in the xml case we concatenate.

> list - the constructed list has a member for each emitted value; every emitted value must belong to type T, where T[] is the type of the constructed value
> xml - the constructed xml value is the concatenation of the emitted values; every emitted value must be of type xml

**Comment by MaryamZi** [comment]
The original source is

```ballerina
import ballerina/test;

@test:Config
function test() {
    xml value = xml`
        <Element>data</Element>
        <Element>data</Element>
    `;

    any[] elements = from var el in value
        select el.<Element>;

    foreach var element in elements {
        // passes as expected
        test:assertTrue(element is xml<xml:Element>, "el isn't an xml:Element");

        // fails, but shouldn't 
        test:assertEquals((<xml<xml:Element>>element).data(), "data", "unexpected result for element.data()");
    }
}
```

When iterating over `value` there will be 5 iterations - two `xml:Element` items and three `xml:Text` items. When we do `el.<Element>` on the `xml:Text` items, we get empty sequence. When we call `.data()` on empty sequences we get an empty string, which is why the assertion with `"data"` fails.

If there was no white space (resulting in `xml:Text` items) the test would pass.

e.g., 
```ballerina
xml value = xml`<Element>data</Element><Element>data</Element>`;
```

```ballerina
import ballerina/test;

@test:Config
function test() {
    xml value = xml`<Element>data</Element><Element>data</Element>`;

    any[] elements = from var el in value
        select el.<Element>;

    foreach var element in elements {
        test:assertTrue(element is xml<xml:Element>, "el isn't an xml:Element");
        test:assertEquals((<xml<xml:Element>>element).data(), "data", "unexpected result for element.data()");
    }
}
```

@Gubaer, hope this addresses your issue. Please reopen if you have further concerns.

**Comment by Gubaer** [comment]
> @Gubaer, hope this addresses your issue. Please reopen if you have further concerns.
Ah, got it, silly me!
