### ISSUE TITLE
Ballerina project build fails throwing the error `method is too large: '.<init>'`

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-lang#31925]
**Description:**
Following error was thrown while building a Ballerina connector which was generated using Ballerina Open API tool. 

`ERROR [<project-name>:(1:1,1:1)] method is too large: '.<init>'`

The generated connector includes large number of Ballerina enumerations (60) and remote functions (88). 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment]
Verified method too large fix with beta 3 RC 1 pack. Therefore closing the issue.
