### ISSUE TITLE
Add capability to edit a selected source snippet

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31928]
**Description:**
Consider when the following source snippet is added in the ballerina shell
```
function testFunction() {
    int a = 10;
    int b = 10;
    io:println(a + b);
}
```

If the user needs to change the internals of the function's body, the user has to rewrite the same function. Instead, provide the capability to edit the source snippet

**Comment by mohanvive** [comment]
Not prioritised as of now.
