### ISSUE TITLE
[Ballerina Shell] Add support to save the current content to a file

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31938]
**Description:**
Add the capability to save the current content to a file. This is necessary, when using ballerina within a docker container as well as loading a previous state.

In order to complete the particular use-case, the shell should be able to re-initialise the previous state (Just the variables and the other constructs) from the content of the file.

**Affected Versions:**
SwanLake Beta2 at least

**Comment by mohanvive** [comment]
Not planning to prioritise this now.
