### ISSUE TITLE
Failing debugger evaluation test in #31251

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#31936]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/31251

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with #31251
