### ISSUE TITLE
Assignment in while body can invalidate narrowing in while condition

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31935]
This should get a compile time error, but actually (in slbeta2) gets a runtime error:

```
public function main() {
   foo(1);
}

function foo(any v) {
   any x = v;
   if x is int {
      while x > 0 {
         x = x - 1;
	 x = ();
      }
   }
}
```

**Comment by jclark** [comment]
Actually it's even more difficult that this. Consider:

```
public function main() {
   foo(1);
}

function foo(any v) {
   any x = v;
   if x is int {
      int i = 2;
      while i > 0 {
         x = x + 1; // not allowed
	 x = ();
	 i = i - 1;
      }
   }
}
```

This should get a compile time error, but actually (in slbeta2) gets a runtime error.

There is an execution path in which `x = ()` is executed before `x = x + 1`, so x cannot be narrowed. So this cannot be done in one pass any more.

**Comment by MaryamZi** [comment]
This has been disallowed as discussed in https://github.com/ballerina-platform/ballerina-spec/issues/904.
