### ISSUE TITLE
Improve diagnostic message when the user is trying to access an array element by providing a non-integer index

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#31954]
**Description:**

When the user is trying to access an array element by providing a non-integer index, the bellow diagnostic message is displayed.

```
incompatible types: expected 'int', found 'string'(BCE2066)
```

sample code:
```ballerina
string[] fruits = ["apple", "banana", "mango", "pineapple", "avocado"];
string fruit = fruits["apple"];
```

This message makes confusions for some users since it is not providing what/where expects `int`.

Since ballerina does not support array element access for non-integer indexes, it would be better if we can optimize this error message. It will be more clear if we can include something like `array index must be an 'int'` within the diagnostic.

**Comment by sajeerAhamed15** [comment]
@nadeeshaan please tag the relevant people.
