### ISSUE TITLE
Issue with the fromBytes() function

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#31959]
We are developing a language server written in ballerina and we used a network socket to connect the client and the server. It should send the following message.

[file4.txt](https://github.com/ballerina-platform/ballerina-lang/files/6905017/file4.txt)

In order to receive that message, we should convert the string to a json object and remove the “content-length:..” line which is the first line of the received string. In order to remove the "content-length:.." part we used both indexOf() function and regex. It removed not only the first line of the string but also a part in the middle of the string.
The part which got removed in the middle of the string contained whitespaces and CR and LF characters, so we tried to remove them using regex and it removed the CR LF characters but the same issue was encountered in the middle of the string. 

The part which got removed is shown below,

"signatureHelp": {
                    "dynamicRegistration": true,
                    "**signatureInfo**{"documentationFormat":["markdown","plaintext"], ….. }

The rest of the characters in “signatureInformation” cannot be seen. This was the same place where the whitespaces were. 

This should not happen as indexOf function should only return the first occurrence of the character and regex:replaceFirst is supposed to remove only the first occurrence of the string.

**Comment by MaryamZi** [comment]
Is it possible to share the code used for the modification and the original JSON object (or string) with the "content-length" part? 

Also if you do have the content as a JSON object, isn't removing the entry from the JSON object using https://lib.ballerina.io/ballerina/lang.map/1.1.0/functions#remove an option?

**Comment by mindula** [comment]
Hi @MaryamZi this is the code i used to modify the string.
[main.txt](https://github.com/ballerina-platform/ballerina-lang/files/6914781/main.txt)

and this is the original string i get with the "content-length: " line
[file2.txt](https://github.com/ballerina-platform/ballerina-lang/files/6914791/file2.txt)

i cannot use the https://lib.ballerina.io/ballerina/lang.map/1.1.0/functions#remove as an option because i cannot convert the received string to a json object due to the issue i get from the above code

**Comment by mindula** [comment]
Hi @MaryamZi i tried writing the content i get from the stream into a file and took it as the input. Then the issue did not appear. The issue occurs when i try to get the content directly from the stream.

**Comment by MaryamZi** [comment]
Related discussion: https://ballerina-platform.slack.com/archives/CAXS256RX/p1627878040003800

**Comment by MaryamZi** [comment]
Closing this issue since it wasn't an issue in `fromBytes()`.
