### ISSUE TITLE
Improve diagnostic message when the user is trying to perform an operation between two different types

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#31956]
**Description:**

When the user is trying to perform an operation between two different types, the bellow diagnostic message is displayed.

```
operator '+' not defined for 'string?' and 'string'(BCE2070)
```

sample code:
```ballerina
string? firstName = "tom";
string fullName = firstName + "hanks";
```

For some users, this message gives a notion like the `+` operator is not defined for this particular concatenation. (They think they should achieve the requirement by using some other operator)

It would be better if we can optimize this error message in a way that user gets a clear idea about the issue.

**Comment by sajeerAhamed15** [comment]
@nadeeshaan please tag the relevant people.
