### ISSUE TITLE
Improve diagnostic message when the user is trying to access record fields using square brackets 

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#31953]
**Description:**

 When the user is trying to access a record field by using square brackets and, by providing a non-string value, the bellow diagnostic message is displayed.

```
incompatible types: expected 'string', found 'int'(BCE2066)
```

sample code:
```ballerina
covid19:CovidCountry getStatusByCountryResponse = check covid19Endpoint->getStatusByCountry(country);
string population = getStatusByCountryResponse[0];
```
 
This message makes confusions for some users since it is not providing what/where expects string.

Since ballerina does not support record field access for non-string indexes, it would be better if we can optimize this error message. It will be more clear if we can include something like `the field name must be a 'string'` within the diagnostic.

**Comment by sajeerAhamed15** [comment]
@nadeeshaan please tag the relevant people.
