### ISSUE TITLE
Symbol of a documentation parameter comes as empty

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#31964]
**Description:**
The symbol of a markdown documentation parameter results in an empty `Optional<Symbol>`.

**Steps to reproduce:**
```
# Description
#
# + x - Field Description  
public type Coord record {
    readonly int x;
    # + y - Field Description
    int y;
};
```
Get the symbol of `x` documentation parameter.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sanjana** [comment]
The documentation parameter `x` symbol can be retrieved with an implementation in the `SymbolFinder`. 

Do we also need to get the `markdownDocAttachment` parameter symbol `y` which is of a record field symbol?
