### ISSUE TITLE
LS feature to list down the user-defined functions 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#31977]
**Description:**
At the moment, there is no way to find the functions defined by the user in VSCode. If you have a lengthy ballerina code, then it is cumbersome to browse through the files/project to find the functions. It would be ideal to list down the user-defined functions in a left-side panel. 

As of now, the diagram panel list-down the functions. But, it does not allow to go to the function definition.

**Comment by pubudu91** [comment]
#27700 captures the document symbol API requirement
