### ISSUE TITLE
The resolved ReturnTypeDescriptor of langlib method is incorrect

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#31974]
**Description:**
Consider the following source code where try to implement the `toString()`  method declaration of runtime:StackFrame object type symbol.  https://github.com/ballerina-platform/ballerina-lang/blob/d4eb62a39664bbee06b2a624751bd453d3a5c9c2/langlib/lang.runtime/src/main/ballerina/runtime.bal#L67-L76

```
import ballerina/lang.runtime;

function test() {
    var myObj = object runtime:StackFrame {
        
    };
}

```
When I access the particular MethodSymbol though methods() API in ObjectTypeSymbol the resolved symbol does not have a return type descriptor as depicted below. 
![1](https://user-images.githubusercontent.com/35211477/127802737-c046fb98-9ae9-4129-9c2f-e4c8b4d0796e.png)
![2](https://user-images.githubusercontent.com/35211477/127802741-19ebe648-22ea-49c3-b067-2fa16a2c649c.png)

**Steps to reproduce:**
Follow above steps

**Affected Versions:**
slbeta3-snapshot

**Comment by pubudu91** [comment]
It seems like the internal type symbol for the method of the effective type created is buggy. The return type is `null` there. Hence the above issue. Works correctly when looking it up for the object member type.

**Comment by pubudu91** [comment]
Had a further look into this. It seems like this is a bug in the BIR reading when it comes to intersected object types. The type symbol created for the effective type's methods don't seem to be going through the regular path for defining method symbols.

**Comment by pubudu91** [comment]
Related issue #30051

**Comment by MaryamZi** [comment]
Yeah, for intersection types methods are introduced in a different path due to https://github.com/ballerina-platform/ballerina-lang/issues/30051. The symbols probably aren't populated correctly on that path.
