### ISSUE TITLE
Improve `create function` code action 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#31981]
**Description:**
Although `create function` code action allows users to implement an undefined function, it would be great to incorporate the below improvements.

- Define the undefined function closer to the usage. (eg: at the end of the current usage function)
- Reuse the variable names as the function arguments (if possible)

**Comment by malinthar** [comment]
Following is a similar scenario in intelij IDEA.
![Screenshot from 2021-08-04 15-02-36](https://user-images.githubusercontent.com/35211477/128172908-1eece2c9-ef53-44ce-a7d5-fc0c728d3475.png)

For hard coded value which does not have a reference/declaration, random parameter names(similar to our current implementation) are used.  The arguments that refer to variable names are modified into camel case as depicted above. 

Shall we follow the same pattern? WDYT @mohanvive @IMS94 @nadeeshaan 
If the parameter name is already defined in the scope a suffix (numer) can be added to the modified variable name as well.

**Comment by IMS94** [comment]
@malinthar +1. And for hardcoded values, I think they are using the first letter of the type name (`int -> i`, `string -> s`, ...). We can do the same.

**Comment by mohanvive** [comment]
@malinthar Yes, that looks good. +1.
