### ISSUE TITLE
Issue with code completion for test module

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#32005]
**Description:**

The code completion suggests only one annotation when typed at the bottom of file. But if I type at the start, I get the complete list as suggestions.

**Steps to reproduce:**

Please see the attached gif.
![code_Completion_bug](https://user-images.githubusercontent.com/5234641/128136632-1276a3ed-02ec-4040-b1d6-a570e3abc208.gif)

**Affected Versions:**
Ballerina SL Beta2 

**OS, DB, other environment details and versions:**
Using the VSCode plugin for Beta2 at https://marketplace.visualstudio.com/items?itemName=wso2.ballerina

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@nadeeshaan @IMS94 FYA

**Comment by IMS94** [comment]
@Dilhasha This was fixed with #31342 and will be available in SL Beta 3.

**Comment by Dilhasha** [comment]
Thanks @IMS94
