### ISSUE TITLE
Stop creating union types per invocation 

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#32019]
Consider following code 

```ballerina
type Color "red" | "green" | "blue";
 
function parseColor(string c) returns Color {
  if c is Color {
      return c;
  }
  panic error("unexpected input : " + c);
}
 
 
```
In generated code `io.ballerina.runtime.internal.types.BFiniteType` objects are created per invocation of the function. It should be created once and kept in a static variable.

**Comment by warunalakshitha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/32325
