### ISSUE TITLE
Improve accuracy of completions by filtering invalid variables using diagnostic state

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32038]
**Description:**
With #31072, a new API was added to get the visible symbols filtered by their diagnostic state (valid, redeclared, unknown). Need to incorporate this API in LS completions to improve completions.

This can be used to remove suggesting variables being declared in completions. For example:
```
int count = <cursor>
```
Right now, at `<cursor>` we suggest, `count` which is being declared. We can avoid showing that using the above API.

**Describe your task(s)**
See description

**Related Issues (optional):**
#30081
PR: #31072

**Comment by gayalkuruppu** [comment]
fix of this issue expects the following snippet to not give completion suggestion `seven`. Fix should omit the completion suggestion of `seven` because it has an unknown type,  `var`
```
int ten = 10;

function testFunction() {
    var seven = <cursor>
}
```
But for the following will keep getting completion suggestion `seven`
```
int ten = 10;

function testFunction() {
    int seven = <cursor>
}
```
