### ISSUE TITLE
Remove duplicated stack trace elements from the error cause stack traces

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#32047]
**Description:**
Stack trace with error cause locations may have unnecessarily repeated stack trace elements. Needed to properly handle them and Provide much needed and sufficient stack trace elements only when the stack trace is too large. 

Consider the following sample code,
```
public function main() {
    panic bar();
}

function bar() returns error {
    error b = error("b", y());
    return b;
}

function y() returns error {
    return x();
}

function x() returns error {
    error c = error("c");
    return c;
}
```
With the changes done with the PR https://github.com/ballerina-platform/ballerina-lang/pull/31973 there can be repeated elements in the stack trace as follows, 
```
error: b
        at gabilan.cause_location.0_1_0:bar(main.bal:6)
           gabilan.cause_location.0_1_0:main(main.bal:2)
cause: c
        at gabilan.cause_location.0_1_0:x(main.bal:15)
           gabilan.cause_location.0_1_0:y(main.bal:11)
           gabilan.cause_location.0_1_0:bar(main.bal:6)
           gabilan.cause_location.0_1_0:main(main.bal:2)
```
Unnecessary repeated elements should be needed to be removed. 
**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

Team/jBallerina

**Suggested Assignees (optional):**

**Comment by riyafa** [comment]
Since it is a stacktrace I think it is okay to have these duplicates, otherwise if we remove the duplicates  
```
gabilan.cause_location.0_1_0:bar(main.bal:6)
gabilan.cause_location.0_1_0:main(main.bal:2)
```
from 
```
gabilan.cause_location.0_1_0:x(main.bal:15)
gabilan.cause_location.0_1_0:y(main.bal:11)
```
then we might actually be missing some stacktrace.
@manuranga what do you think?
