### ISSUE TITLE
Add negative test cases for `Dependencies.toml` after adding new changes

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#32058]
**Description:**
Need to add more test cases for `Dependencies.toml` after new changes are added from PR https://github.com/ballerina-platform/ballerina-lang/pull/32057

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Test cases has been written in PackageResolutionIntegrationTests
