### ISSUE TITLE
Provide a way to mock any global variable within a Ballerina package

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#32077]
**Description:**

Consider a scenario where a transitive dependency of a module has a globally defined client with auth configurations. With the current mock implementation, there is no way to directly mock this global variable before the dependent module initialization. So, the auth call to the token endpoint executes before the mock replacement.

See the sample code at https://github.com/Dilhasha/MyHTTPTest/blob/e21c4c8f8127c6e0400d9f25d9635c7df51aa7c6/modules/foo/foo.bal#L3

We need to come up with a way to mock these global initializations.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
We have a suggested approach to achieve this. Refer https://ballerina.io/learn/test-ballerina-code/test-services-and-clients/#mock-final-clients
