### ISSUE TITLE
Test output is cut off

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#32081]
Can't see the real issue due to `...` cutting off the comparison. 
<img width="751" alt="Screenshot 2021-08-10 at 10 16 17 AM" src="https://user-images.githubusercontent.com/1686124/128809947-99ea0c13-05d4-4c20-b731-b72e827c4739.png">

**Comment by Ibaqu** [comment]
To Do : 

- [ ] Increase Error format threshold
- [ ] Extra formatting if possible

**Comment by manuranga** [comment]
I feel like we shouldn't try to be too cleaver.
