### ISSUE TITLE
New code action to extract mapping constructors

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32094]
**Description:**
Consider the following scenario:
```
function test() {
    callFunction({
        id: 1,
        name: "name",
        country: "LK",
        ....
    });
}
```
To make the code readable, users may want to extract the mapping constructor as below:
```
function test() {
    <RecordType> rec = {
        id: 1,
        name: "name",
        country: "LK",
        ....
    };
    callFunction(rec);
}
```
This code action will be useful to make the code more readable for the users

**Describe your problem(s)**
See description

**Describe your solution(s)**
See description

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
