### ISSUE TITLE
Fix string index providing the wrong value for debugger evaluator

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#32102]
**Description:**
The following debugger evaluator test  is failing when we changed it after #32105.
 https://github.com/ballerina-platform/ballerina-lang/blob/a2fb574e9f8576863e22c9b1aac0bffa4581bfa3/tests/jballerina-debugger-integration-test/src/test/java/org/ballerinalang/debugger/test/adapter/evaluation/ExpressionEvaluationTest.java#L415
 
 The change, 
 ```java
 debugTestRunner.assertExpression(context, String.format("typeof %s[0]", STRING_VAR), "f", "typedesc");
 ```

It should pass, as the typeof evaluation is done on the string value `foo` with index 0. 

This passes correctly in `bal run` with the same `typeof` changes
```ballerina
string s = "foo";
io:println(typeof s[0]); // typedesc f
```

**Affected Versions:**
beta3-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#15278

**Comment by NipunaRanasinghe** [comment]
Closing with #32122
