### ISSUE TITLE
Fix `typeof` usage in debugger evaluator error messages

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#32101]
**Description:**
The ballerina debugger evaluatior uses the `typeof` expression and the result's string value for the error messages. 
But, with the change after #32105, the `typeof` will return the singleton type instead of its basic type for simple basic values. Therefore the error messages will become unclear. 

Eg: 
```
operator '<' not defined for 'int' and 'string'
```
this error will become 
```
operator '<' not defined for '20' and 'foo'
```
We need to change this behavior. 
This can be changed to use the `getType()` API from TypeChecker via interop instead of the `typeof`. 

**Steps to reproduce:**
https://scans.gradle.com/s/xyvp55sc4wcmw/tests/failed

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#15278

**Comment by NipunaRanasinghe** [comment]
Closing with #32122
