### ISSUE TITLE
Comparison checks needed to be defined for the `NaN` resulted from decimal operations

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#32111]
**Description:**
Spec says,
```
NaN, infinities and subnormals are not supported; operations that would result in one of these values according to the normal rules of IEEE 754-2008 instead result in a panic.
```
Since `NaN` can be resulted from the decimal operations, the equality, exact equality and comparison checks needed to be defined for `NaN`.
```
decimal nan = 0.0/0.0;

nan == nan
nan === nan

nan <= nan
nan < nan
na1 >= nan
nan > nan    

```

**Describe your task(s)**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/17977

**Suggested Labels (optional):**
Team/jBallerina

**Suggested Assignees (optional):**

**Comment by gabilang** [comment]
According to the standard we followed, decimal operations do not result in `NaN`.
Currently the following code results in `NaN`
```
import ballerina/io;

public function main() {
    decimal a = 0.0;
    decimal b = 0.0;
    decimal c = a/b;
    io:println(c);
}
```
It can be a bug and we suppose to need panic in those cases.

**Comment by HindujaB** [comment]
The following code results in a runtime crash
```ballerina
    float nan1 = 0.0 / 0.0;
    decimal nan = <decimal> nan1;
```
Need to check th constructors as well.
