### ISSUE TITLE
Union Type Array Throws an Error when Assigned to a Member Type Array

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#32123]
**Description:**
Consider the following code:

```ballerina
distinct isolated service class Foo {
}

distinct isolated service class Bar {
}

type FooBar Lift|Trail;

public function main() {
    Foo[] foos = [];
    FooBar[] fooBars = foos;
    Bar[] bars = [new()];
    foreach Bar bar in bars {
        fooBars.push(bar);
    }
}
```

This throws a Runtime Error, `{ballerina/lang.array}InherentTypeViolation`.

Seems like when we assign a member type array to a union type array, the type of the array is changed to the member type.

**Comment by warunalakshitha** [comment]
This is expected behavior since both types are distinct.  At runtime fooBars will have foos array. So we can't put Foo to a Bar[]
You can change the code as below to get work.

```

public function main() {
    Foo[] foos = [];
    FooBar[] fooBars = [];
    foreach Foo foo in foos {
        fooBars.push(foo);
    }
    Bar[] bars = [new()];
    foreach Bar bar in bars {
        fooBars.push(bar);
    }
}


```
