### ISSUE TITLE
[Testerina] Support Function Mocking for Modules within the same package

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#32137]
**Description:**
At the `BIRGen` level, the function mocking implementation replaces function calls only at the place where the mock object is defined. ie. If the function mock object is defined in the default module, the function calls are only replaced at the default module, while the modules in the package are ignored

This means that function calls in other modules in the package are not replaced by the mock function, leading to discrepancies when testing with transitive dependencies.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This is the expected behavior since the purpose of mocking is to unit test. You can mock the functions used in other modules in the tests written in those modules.
