### ISSUE TITLE
`bal run -- <command line options>`:   `-` or  `--` options are not possible

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#32152]
**Description:**
When `bal run` is invoked with command line arguments for the Ballerina program after the `--` argument, `bal run` rejects command line arguments starting with `-` or `--`, i.e. `-h` or `--help`.

**Steps to reproduce:**

```bash
# clone the sample repo
$ git clone https://bitbucket.org/gubaer/ballerina-bal-run-options.git
$ cd ballerina-bal-run-options

# OK case
$ bal run main.bal -- foo bar
number of command line options passed in:  2
arg [0]: 'foo'
arg [1]: 'bar'

# NOK case
$ bal run main.bal -- -h
error: undefined CLI argument: '-h'
# expected
number of command line options passed in:  1
arg [0]: '-h'

# NOK case
$ bal run main.bal -- --help
error: undefined option: 'help'
# expected
number of command line options passed in:  1
arg [0]: '--help'
``` 

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by riyafa** [comment]
@Gubaer The repo you have asked to clone from is inaccessible.

But I think I understand your issue. The ballerina program can be run in two ways as follows:
```
bal run file.bal
bal run proj.jar
```
When we run as in the first case it supports other command line arguments supported by `ballerina` such as `--debug`. In this case all the command line arguments from the user program should follow after `--`.
When we run as in the second case it does not have other command line arguments from `ballerina` and hence we can have command line arguments from the user program  follow immediately afterward without having to be followed by `--`.

Hence in your use case if you want to input command line arguments starting with `-` or `--` as operands you will have to run it as follows:

```
bal run main.bal -- -- -h
```
If it is run using the jar file it can be run as follows:
```
bal run main.jar -- -h
```

**Comment by Gubaer** [comment]
Thanks, `bal run main.bal -- -- -h` works for me.

To use the `--` option twice seems unintuitive, though. I suggest to keep the issue open but to change its 
type from **Type/Bug** to **Type/Improvement**, with low priority.

**Comment by riyafa** [comment]
This is similar to the issue here: https://github.com/ballerina-platform/ballerina-lang/issues/31865 
Hence closing this as it will be handled there
