### ISSUE TITLE
[Semantic API] function symbols do not contain text range information

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#32176]
**Description:**
All the function symbols retrieved using the semantic API seem to be missing text range information, although the line range information is correct. Therefore, apparently there's no way to resolve the corresponding syntax tree node for a given symbol, as the `io.ballerina.compiler.syntax.tree.NonTerminalNode.findNode()` method of the syntax API only accept a text range.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
This should work once we modify the node transformer to include the text range as well when creation position info for AST nodes.
