### ISSUE TITLE
Persist `Dependencies.toml` after pull module code action is executed

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32209]
**Description:**
Once the pull module code action is executed, fetched versions should be persisted to avoid future version conflicts. This is done to avoid conflicts of versions when the same code is being built while the latest version available in ballerina central has changed.

When doing this, should consider the `sticky` option in `Ballerina.toml` as well. 

**Describe your task(s)**
See description

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/30757

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
