### ISSUE TITLE
[Testerina] Code coverage report end braces not highlighted as covered

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#32201]
**Description:**
<img width="1042" alt="test_ErrorValues" src="https://user-images.githubusercontent.com/43578935/129694558-02a73eab-4fe3-48a3-862d-b176e4d0d2e7.png">

**Steps to reproduce:**
Run the following project with code coverage flag

https://github.com/Ibaqu/Covid19Stats

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
Tried generating the coverage using the generated class files using jacoco CLI and the end braces are still missed.  So, this is not an issue with how Testerina interprets coverage. 

<img width="1027" alt="Screenshot 2021-09-24 at 18 27 10" src="https://user-images.githubusercontent.com/5234641/134678635-f7c4ade7-ccf0-47c3-a94e-f598ba4ff219.png">

@warunalakshitha Seems like an issue with the runtime implementation. Shall we please check and fix this?

**Comment by gabilang** [comment]
Closing this since fixed with the PR https://github.com/ballerina-platform/ballerina-lang/pull/33642
