### ISSUE TITLE
Unused module imports in Ballerina Shell

### ISSUE THREAD

**Issue by kdsuneraavinash** [ballerina-platform/ballerina-lang#32219]
**Description:**

Currently, compilation errors are given for unused module imports.
For the shell, this is very problematic. Because in the shell following is a valid session,

```ballerina
=$ import ballerina/io
=$ int v = 100
=$ io:println(v)
```

We have to selectively include imports to stop errors that can come from situations like this. (Because when compiling `int v = 100` even if there is an import, it is not used)
This currently is an added complexity. If there is a flag on the compiler to toggle whether it gives an errors on imports or not, or to toggle these errors off on shell mode, all those can be simplified.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**
#28408

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
Not prioritised now.
