### ISSUE TITLE
float:fromHexString throws an error when used

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/ballerina-lang#32220]
**Description:**
`float:fromHexString`  function throws the following error 
`error: {ballerina}TypeCastError {"message":"incompatible types: 'handle' cannot be cast to '(float|error)'"}
        at ballerina.lang.float.1_0_0:fromHexString(float.bal:367)`

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    io:println(float:fromHexString("0x1a"));
}
```
It gives the same error with or without the 0x prefix (as used in `int:fromHexString` )

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by jclark** [comment]
That's not a valid [HexFloatingPointLiteral](https://ballerina.io/spec/lang/2021R1/#HexFloatingPointLiteral).

**Comment by ushirask** [comment]
> That's not a valid [HexFloatingPointLiteral](https://ballerina.io/spec/lang/2021R1/#HexFloatingPointLiteral).

The error persists with valid HexFloatingPointLiterals
