### ISSUE TITLE
Float exact equality on +/-0 generates bad code

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#32247]
In slbeta2, this prints true, when it should print false.

```
import ballerina/io;

public function main() {
  io:println(0.0 === -0.0);
}
```

**Comment by HindujaB** [comment]
This is fixed in slbeta3 and later versions through PR https://github.com/ballerina-platform/ballerina-lang/pull/32071.
Hence, closing the issue.
