### ISSUE TITLE
Grammar supports invalid int/float declarations

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#3225]
**Case I**
```go
function main (string[] args) {
    int a = 8L;   // the 'L' suffix
    system:println(a);
}
```
The line `int a = 8L;` does not fail at at the parser (grammar) level. Instead it throws the following error at the model building phase:
```
ballerina: for input string: "8L"
```  
---
**Case 2**
```go
function main (string[] args) {
    int a = 78_25;   // an underscore between numbers
    system:println(a);
}
```
---
**Case 3**
Below program parses and runs without any errors:
```go
function main (string[] args) {
    float a = 8F; // the 'F' suffix
    system:println(a);
}
```
Output:
```
8.0
```
---
**Case 4**
Below program parses and runs without any errors. 'e' is treaed as the exponential:
```go
function main (string[] args) {
    float a = 8e4; // an 'e' in the middle
    system:println(a);
}
```
Output:
```
80000.0
```
---
**Case 5**
```go
function main (string[] args) {
    float a = 0x8p+4;
    system:println(a);
}
```
Output:
```
128.0
```

**Comment by Shan1024** [comment]
Case 4,5 is allowed by the language specification (https://ballerina.io/res/Ballerina-Language-Specification-WD-2018-05-01.pdf).
