### ISSUE TITLE
Revisit (optional) field access completion for optional fields

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#32262]
**Description:**
$title.

**Describe your problem(s)**
Optional field access is not allowed as an lvalue. i.e., it cannot be used to update a field and field access should be used instead.

```ballerina
type Record record {|
    int optionalField?;
|};

public function main() {
    Record x = {};

    // Invalid.
    x?.optionalField = 1;

    // Valid.
    x.optionalField = 1;
}
```

But right now, when I use `.` and select the field, it always changes to optional field access.
```ballerina
type Record record {|
    int optionalField?;
|};

public function main() {
    Record x = {};

    x.o<cursor>
}
```

![optional_field_access_bug](https://user-images.githubusercontent.com/8376983/130312287-205ac30e-f95e-46a3-92bc-12347559b0cc.png)

Accepting this adds
```ballerina
x?.optionalField
```

**Describe your solution(s)**
I suggest we go ahead with field access either

1. if it is on the LHS
```ballerina
x.o<cursor> = 1;
```

2. or when the context doesn't imply it is a read
```ballerina
x.o<cursor>
```

**Comment by nadeeshaan** [comment]
> **Description:**
> $title.
> 
> **Describe your problem(s)**
> Optional field access is not allowed as an lvalue. i.e., it cannot be used to update a field and field access should be used instead.
> 
> ```ballerina
> type Record record {|
>     int optionalField?;
> |};
> 
> public function main() {
>     Record x = {};
> 
>     // Invalid.
>     x?.optionalField = 1;
> 
>     // Valid.
>     x.optionalField = 1;
> }
> ```
> 
> But right now, when I use `.` and select the field, it always changes to optional field access.
> 
> ```ballerina
> type Record record {|
>     int optionalField?;
> |};
> 
> public function main() {
>     Record x = {};
> 
>     x.o<cursor>
> }
> ```
> 
> ![optional_field_access_bug](https://user-images.githubusercontent.com/8376983/130312287-205ac30e-f95e-46a3-92bc-12347559b0cc.png)
> 
> Accepting this adds
> 
> ```ballerina
> x?.optionalField
> ```
> 
> **Describe your solution(s)**
> I suggest we go ahead with field access either
> 
> 1. if it is on the LHS
> 
> ```ballerina
> x.o<cursor> = 1;
> ```
> 
> 1. or when the context doesn't imply it is a read
> 
> ```ballerina
> x.o<cursor>
> ```

+1 for the approach. We will be adding more context awareness for this and modify the behaviour. The suggested approach suits the language specification and hence we will be proceeding accordingly.
