### ISSUE TITLE
Array with negative array length const-expr does not give any error.

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32269]
**Description:**
Creating an array with const-expr as array length in which the const-exper will evaluate to a negative integer does not give any error.
```bal
const LENGTH1 = -1;
public function main() returns () {
    boolean[LENGTH1] bool; // no error
}
```

**Affected Versions:**
Current Master

**Comment by lochana-chathura** [comment]
Fixed with #33603
