### ISSUE TITLE
Create function code action doesn't add boolean return type when used inside an if condition

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32279]
**Description:**
Consider the following code:
```
public function main() {
    if createVal() {
        
    }
}
```
Here, when `createVal()` function is created using `create function code action`, it adds the following:
```
function createVal() {
    
}
```
Note that the `boolean` return type is missing.

**Steps to reproduce:**
See description

**Affected Versions:**
Beta 3 snapshot

**Comment by sanjana** [comment]
Need to address the following type of cases as well. 

```
if createVal() && check() {        
}

if createVal2() == 0 && check() {
}

function check() returns boolean {
   return true;
}
```

**Comment by IMS94** [comment]
The above cases get covered by the binary expression scenario
