### ISSUE TITLE
`cloneReadOnly()` creates immutable type with wrong package 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#32283]
**Description:**
When an immutable value is created from an imported type that contains a record, the immutable type is created with the original (imported) package, instead of the current package. 

**Steps to reproduce:**
In a package `foo`, module `foo.mod1`,
```ballerina
public type Student record {
    string name;
};
public type StudentMap map<Student>;
```
In foo.bal, 
```ballerina
import foo.mod1;

public function main() returns error? {
    mod1:StudentMap studentMap = {a: {name: "aaa"}, b: {name: "bbb"}};
    map<mod1:Student> & readonly result = studentMap.cloneReadOnly();
}
```
The created immutable value will contain the wrong package for its internal values. 
![Screenshot from 2021-08-23 13-48-01](https://user-images.githubusercontent.com/28644893/130414549-431adbfb-62aa-4b97-b8e2-aada12e75f21.png)

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by MaryamZi** [comment]
The original module was used at the time because we did not have a way to identify the current module (the module in which the `cloneReadOnly()` call is done).
