### ISSUE TITLE
Getting TypeCastError during runtime when testing some connectors with SLBeta3 

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-lang#32298]
**Description:**
When testing Azure Service Bus connector and MongoDB connector, getting TypeCastError

[ASB connector error](https://github.com/LakshanSS/module-ballerinax-azure-service-bus/runs/3401278839?check_suite_focus=true)

[MongoDB connector error](https://github.com/LakshanSS/module-ballerinax-mongodb/runs/3407478035?check_suite_focus=true)

**Affected Versions:**
Ballerina Swan Lake Beta3 RC1

**OS, DB, other environment details and versions:**
Ubuntu
JDK 11
Ballerina SLBeta3

**Comment by MaryamZi** [comment]
The errors seems to be like

```cmd
{ballerina}TypeCastError {"message":"incompatible types: 'error' cannot be cast to '(asb:Message|asb:AsbError)?'"}

    at ballerinax.asb.0:receive(client.bal:399)
    ballerinax.asb.0.AsbClient:receive(client.bal:184)
    ballerinax.asb.0.tests.asb_test:testSendAndReceiveMessageFromQueueOperation(tests/asb_test.bal:82)
```

The issue here seems to be that the value is a normal error value which you are trying to cast to a distinct error `asb:AsbError`. Same for MongoDB.

Can you please check if the error value is created correctly as an `asb:AsbError`?

**Comment by LakshanSS** [comment]
MongoDB: [link to distinct error creation
](https://github.com/ballerina-platform/module-ballerinax-mongodb/blob/cc7141870bdecd2d915f863588ab98c9be456def/mongodb-native/src/main/java/org/ballerinalang/mongodb/exceptions/BallerinaErrorGenerator.java#L50)

ASB: [link to distinct error creation](https://github.com/ballerina-platform/module-ballerinax-azure-service-bus/blob/2762f0b908461c65482ce1ef69a45372ed2fa6dd/asb-native/src/main/java/org/ballerinalang/asb/ASBUtils.java#L36)

Distinct error creation code is there in the above places. 
But only normal errors are created.

**Comment by LakshanSS** [comment]
I guess some change has happened in `io.ballerina.runtime.api.creators.ErrorCreator`

**Comment by warunalakshitha** [comment]
We need to use @createError(module, errorTypeName, message, cause, details)  to create a distinct error. Other api is already deprecated. Java doc should have those information.

**Comment by warunalakshitha** [comment]
MAke sure we need to define the type in the bal file too.

**Comment by LakshanSS** [comment]
Thanks @warunalakshitha 
We'll use the suggested api instead of the old deprecated api.
