### ISSUE TITLE
`ModuleLoadRequest.locations` list grows abnormally leading to OOM

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32290]
**Description:**
While debugging for #32020, we encountered an OOM scenario. While the main cause for the OOM is #32289, we noticed an abnormal growth in `ModuleLoadRequest.locations` list. Corresponding heap dump is attached here.

After reproducing the OOM scenario, we noticed aroud 800 objects in the above list.

**Heap Dump**
https://drive.google.com/file/d/1DTho2ewn8UJhyGjG99wJxjzOjmQM8xzK/view?usp=sharing

![ModuleLoadRequest1](https://user-images.githubusercontent.com/7523274/130463652-09b916b3-bc7a-43eb-b9fb-503678e57207.png)

**Steps to reproduce:**
We produced this in `nballerina` project with the steps mentioned in [this comment](https://github.com/ballerina-platform/ballerina-lang/issues/32020#issuecomment-903504701).

**Affected Versions:**
SL Beta 3 Snapshot

**Comment by malinthar** [comment]
Hi @azinneera @IMS94 , I analyzed two sub-sequent heap dumps to check if the object(instance) count of `ModuleLoadRequest` changes. As observed on the call, we have got 125 as the count for both the scenarios. However, there was a significant growth of the retained heap for `ModuleLoadRequest` in the second case (about 200MB).  
When both the heaps were analyzed, it was realized that the reason for the growth is only one particular `ModuleLoadRequest`. Hense, the `ModuleLoadRequest` object count does not change, but there is one `ModuleLoadRequest` of which the retained size has significantly grown. 
`ModuleLoadRequest` has a attribute called `locations`  which contains `NodeLocation` objects of which the size is depicted below for the two scenarios.

Using Visual VM
### dump 1
![dump1](https://user-images.githubusercontent.com/35211477/130794751-ced79fcd-4150-46a2-9fc4-398d90d3a80c.png)

### dump2
![dump2](https://user-images.githubusercontent.com/35211477/130794809-2c88bc81-8a3c-4a97-8775-8b8ef4b5c726.png)

Using IBM heap analyzer
### dump1
![dump11](https://user-images.githubusercontent.com/35211477/130795280-0266b018-d898-4646-a52c-9db78cdea1ba.png)

### dump2
![dump22](https://user-images.githubusercontent.com/35211477/130795438-46a87cd5-2c20-4bfc-a9c6-a69687f1b643.png)

This  can potentially be the cause for the rapid growth.

**Comment by IMS94** [comment]
Closing this since #32424 was merged to sl-beta3 dev branch and future improvements on this is tracked under #32497.
