### ISSUE TITLE
Code Action generates syntactically incorrect source

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#32313]
**Description:**
Refer the following screen capture. Code action executed against the `nBallerina` repo.

https://user-images.githubusercontent.com/1329674/130611780-b1cd4b9e-c3dd-47cb-8d13-1269c8973903.mp4

**Comment by IMS94** [comment]
Blocked by #32569

**Comment by nadeeshaan** [comment]
Blocking issue has been resolved. Hence removing the label

**Comment by TharushiJay** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/33207
