### ISSUE TITLE
Implement uniqueId for `ServiceDeclarationSymbol`

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#32324]
**Description:**
As an effort to support REST API development we are implementing an introspection endpoint for any ballerina HTTP service and that particular introspection endpoint will be serving a OpenAPI Doc for that particular service. But in-order to achieve this we need to identify service declaration via a uniqueId which could also be accessed at runtime.

**Comment by pubudu91** [comment]
Closing since #32328 was merged
