### ISSUE TITLE
Array member access with negative key value does not give any compilation error

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32326]
**Description:**
Consider the below sample 
```bal
public function main() {
    byte[2] d = [1, 33];
    d[-1] = 3; // @error list index out of range
}
```
Note the `-1` is used as the key. This program compiles successfully but gives errors at runtime.

**Affected Versions:**
Current master

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33560
