### ISSUE TITLE
isolated error with language server

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#32323]
With nballerina source I am getting an error about `isolated` showing up from time to time that I do not get when I compile. It goes away if I reload. This is with nballerina at https://github.com/ballerina-platform/nballerina/tree/18c07e1fe5b1246c403aca901a33f1abfac6e455

![image](https://user-images.githubusercontent.com/499966/130713362-7c7bd476-b234-41c4-8b5b-0c1a64480998.png)

**Comment by hasithaa** [comment]
This might be related to the memory leak we observed in LangServer mode. If so, this PR https://github.com/ballerina-platform/ballerina-lang/pull/32301 will fix the issue.
