### ISSUE TITLE
Utility to enforce semvar to Ballerina APIs

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#32368]
**Description:**
As of now a developer can change the version of a package at will. This will result in users releasing new versions of packages which are not semvar compatible. This proposal is to create a utility that will inform the user if the API changes conform to the new package version which user is trying to build. 

Action Items 

- [x] Create a spec to determine the version based on API Changes. Here the spec will tel us which changes in ballerina code will result in major, minor and patch versions respectively. 
- [x] Implement a library to analyses ballerina package based on the above spec
- [x] Implement a compiler plugin/CLI tool to inform user if the package version change match the  code changes

M1 - Check patch versions are compatible

**Comment by NipunaRanasinghe** [comment]
Closing since the tool implementation is added with https://github.com/ballerina-platform/ballerina-lang/issues/35552 and a few other subsequent PRs.
