### ISSUE TITLE
Parser Error Handler in a never ending loop

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#32369]
**Description:**
LS became unresponsive while I was editing the following source code in a multi-module project. I analyzed two subsequent thread dumps. There is a thread running over 222 seconds which causes the unresponsiveness. Please find the thread dumps below. 

```ballerina
import ballerina/http;

type PET record {
    string id;
    string name;
    boolean isAvailable;
};

configurable int port = 8080;
configurable string host = "localhost";

//new expressions default values are not added.
//named argument support not provided.
listener http:Listener petStoreListner = new(port,config={host:host});

service / on petStoreListner {
    private map<Pe<cursor>
    resource function get pet/[string petId]() returns @http:Payload PET | http:BadRequest | http:NotFound {
        
    }
}

var a = myF(a=10,b=20);

function myF(int a, int b) {

}

```

Thread dump 1
![tdump1](https://user-images.githubusercontent.com/35211477/130905106-257dd048-6931-4eee-80d0-454d952efbf8.png)

https://drive.google.com/file/d/11Qj4A2BWTtUJLBE2LppcqIL8KW3ZVcmD/view?usp=sharing

Thread dump 2
![tdump2](https://user-images.githubusercontent.com/35211477/130905122-301fb35d-e119-43d3-82a9-c068a39a18ef.png)

https://drive.google.com/file/d/11Qj4A2BWTtUJLBE2LppcqIL8KW3ZVcmD/view?usp=sharing

The CPU and Memory usage is normal.
![cpu](https://user-images.githubusercontent.com/35211477/130904745-a320e8d2-92c3-4279-b136-9a9f0848fe2e.png)

![memory](https://user-images.githubusercontent.com/35211477/130904757-0dba5367-c61f-4e60-9160-14fe87a04153.png)

**Steps to reproduce:**
Try editing the about source code around the indicated cursor position.

**Affected Versions:**
slbeta3 & slbeta4-SNAPSHOT

**Comment by rdulmina** [comment]
Any of the above samples does not reproduce the issue. When I change the code to reproduce the issue, I found a general issue that causes an infinite loop similar to the stack trace in the thread dump. (accidentally typed `map\`) Not sure If it was the original issue but sent a fix for that #32682. Let's close this issue with this fix and reopen if it still exists.
