### ISSUE TITLE
Remove ballerina/observe getting injected when observability is enabled 

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#32364]
**Description:**
ATM, both `ballerina/observe` and `ballerinai/observe` are injected when `observabilityIncluded` build option is set. As per the offline chat with @nadundesilva, for observability initialization, `ballerinai/observe` is the mandatory package and the `ballerina/observe` was injected due to a limitation in configurable values. Now the limitation is resolved and hence we can remove the `ballerina/observe` module from injecting. With this change, we can treat the `ballerina/observe` similar to standard libraries and push to Ballerina Central.

**Comment by nadundesilva** [comment]
The Observability functionality seems to be working in Ballerina Beta 3 RC pack as expected after removing the injection of the imports. Hence closing the issue.
