### ISSUE TITLE
Getting incompatible types error when using (int population = (resp.population?.value ?: 0) / 1000000;)

### ISSUE THREAD

**Issue by sarindaSenevirathne** [ballerina-platform/ballerina-lang#32377]
**Description:**

![Screenshot from 2021-08-26 11-24-07](https://user-images.githubusercontent.com/32522173/130910640-9247feb7-2952-4c84-a15d-bbd7c6d4fecf.png)

Getting this error when using this compound if statement,

**Steps to reproduce:**

1. Create a new ballerina file
2. Add this code
```
import ballerinax/covid19;
import ballerina/http;

type Stats record {|
    string country;
    decimal totalCasesPerMillion;
|};

service / on new http:Listener(8090) {
    isolated resource function get stats/[string country]() returns Stats|error {
        covid19:Client covid19Client = check new ();
        covid19:CovidCountry statusByCountry = check covid19Client->getStatusByCountry(country);
        decimal totalCases = statusByCountry?.cases ?: 0;
        // Added a http client
        http:Client clientEndpoint = check new ("url");
        json resp = check clientEndpoint->get("/countrypop",targetType=json);
        int population = (resp.population?.value ?: 0) / 1000000;

        decimal totalCasesPerMillion = totalCases / <decimal> population;
        Stats payload = {country: country, totalCasesPerMillion: totalCasesPerMillion};
        return payload;
    }
}
```

**Affected Versions:**

Ballerina Swan Lake Alpha5

**Comment by SasinduDilshara** [comment]
> Reproducible with
> 
> ```ballerina
> public function main() {
>     json resp = ();
>     int population = (resp.population?.value ?: 0) / 1000000;
> }
> ```

In the `2201.1.1` this code give the following Error.
```
operator '/' not defined for '(json|error)' and 'int'(BCE2070)
```

**Comment by MaryamZi** [comment]
> > Reproducible with
> > ```ballerina
> > public function main() {
> >     json resp = ();
> >     int population = (resp.population?.value ?: 0) / 1000000;
> > }
> > ```
> 
> In the `2201.1.1` this code give the following Error.
> 
> ```
> operator '/' not defined for '(json|error)' and 'int'(BCE2070)
> ```
> 
> The error message is correct ryt?. @MaryamZi wdyt?.

Yeah, the new error seems to be correct. Let's add some tests though, including something like

```ballerina
public function main() {
    json a = ();
    any[] b = [];
    int _ = (a.x?.y ?: b) / 10;
}
```
