### ISSUE TITLE
Remove already initialized error message for the constant declarations

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#32392]
**Description:** 
Consider following program.
```ballerina
const abc2 = 1;
const abc2 = "1";
```
Compiler throws following errors.
```
ERROR [test.bal:(2:7,2:11)] redeclared symbol 'abc2'
ERROR [test.bal:(2:7,2:11)] symbol 'abc2' is already initialized with '1'
```
Here, already initialized error relevant only when at least one is an enum member.

**Comment by KavinduZoysa** [comment]
@prakanth97, please check this issue is solved from the constant improvement you are working on.
