### ISSUE TITLE
Cannot infer array length from a closed array

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32396]
**Description:**
```bal
public function main() {
    int[5] a = [2, 4, 5, 5, 5];
    int[*] b = a;
}
```
Gives error `invalid usage of closed type: can not infer array size`

**Affected Versions:**
Current master

**Comment by SandaruJayawardana** [comment]
According to the discussion in https://github.com/ballerina-platform/ballerina-spec/issues/993, we do not need to support this scenario (infer array size from a variable reference).
