### ISSUE TITLE
No compilation error when calling `toJson()` on a variable of type `table<map<any>>`

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#32405]
**Description:**

Since `toJson()` is only defined on `anydata`, following cases should result in compilation errors.
case i.
```
public function main() {
   table<map<any>> tbl = table [
            {a: "x", b: 3},
            {c: "z", d: 5}
   ];

   json j = tbl.toJson();
}
```
case ii.
```
type Bar record {|
   int id;
   any a;
|};

type Foo record {|
   int id;
   Bar b;
|};

public function main() {
   table<Foo> tb = table[
         {id: 1, b: {id: 1, a: 5}}
   ];

   json j = tb.toJson();

}
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
This is an issue with the `anydata` check for tables. 

Same as https://github.com/ballerina-platform/ballerina-lang/issues/34696. Will be fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34803.
