### ISSUE TITLE
NPE in language server when executing "isDynamicCommandRegistrationSupported()"

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#32439]
**Description:**

NPE in language server for default monaco client initialize request in below source line

https://github.com/ballerina-platform/ballerina-lang/blob/2.0.0-beta3-dev/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/util/LSClientUtil.java#L116

**Steps to reproduce:**

1. Start language server
2. initialize client LS connection

**Affected Versions:**
beta3-rc

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
