### ISSUE TITLE
Check the usage of kotlin-stdlib dependency

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#32443]
**Description:**
Check the usage of kotlin-stdlib dependency as there is a medium severity CVE in the current version.

**Comment by sameerajayasoma** [comment]
Where do we use this dependency?

**Comment by IrushiL** [comment]
@sameerajayasoma This dependency seems to have been added with the PR https://github.com/ballerina-platform/ballerina-lang/pull/15404 for adding native image generation with GraalVM.

@warunalakshitha @manuranga I was informed that this feature is no longer being used, if so can we remove it? Else, we could consider upgrading the `org.jetbrains.kotlin:kotlin-stdlib` to a version that is not vulnerable.

**Comment by warunalakshitha** [comment]
We can remove it.

**Comment by azinneera** [comment]
I think it's being used transitively in the HTTP client library okhttp3 we are using in CentralClient. Manually removing this from bre lib caused CNF for a kotlin class when trying to run bal build.

```
[2021-12-01 13:48:05,050] SEVERE {b7a.log.crash} - kotlin/TypeCastException 
java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at okhttp3.ResponseBody.create(ResponseBody.java:214)
	at okhttp3.internal.Util.<clinit>(Util.java:69)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:124)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:449)
	at org.ballerinalang.central.client.CentralAPIClient.getClient(CentralAPIClient.java:841)
```

**Comment by IrushiL** [comment]
@azinneera Thanks for the input. Because of this issue, I sent PR bumping the kotlin-stdlib version to a non-vulnerable one. https://github.com/ballerina-platform/ballerina-lang/pull/34080
