### ISSUE TITLE
assertEquals should accept any as the first parameter

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#32440]
With the spec change ballerina-platform/ballerina-spec#814 assertEquals should also be changed to accept an any argument.

current signature looks like :
```ballerina
public isolated function assertEquals(anydata|error actual, anydata expected, string msg = "Assertion Failed!")
```
It should be :
```ballerina
public isolated function assertEquals(any actual, anydata expected, string msg = "Assertion Failed!")
```

**Comment by Ibaqu** [comment]
Closing as the improvement has been made after the spec change to the `any` type.
