### ISSUE TITLE
Invalid text range for token

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#32445]
**Description:**
Consider the following source code.
```
function myFunc {
    isolated client 
}
```
The text range of client token is as follows.
![tec](https://user-images.githubusercontent.com/35211477/131330911-efcc1ccc-840d-4560-aa39-2edc200838e8.png)

Irrespective of where the above code segment is used. The text range of client token always seem to be as depicted above.

**Steps to reproduce:**
Mentioned above

**Comment by lochana-chathura** [comment]
Parsed as `INVALID[client] INVALID[isolated] MISSING[] MISSING[] MISSING[;]}`. Note the order we have stored the invalid tokens is wrong.
