### ISSUE TITLE
Bump guava version 23.0 reference to latest

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#32441]
**Description:**
Bump guava version 23.0 reference to latest 

We are packing 30.0-jre version not 23.0. There are references of this version in several places. Needs to be updated
https://github.com/ballerina-platform/ballerina-lang/blob/3b1996867fddc02840a4c79ef6483a93d379f7c1/misc/testerina/modules/testerina-core/build.gradle#L35

https://github.com/ballerina-platform/module-ballerinax-twilio/blob/master/gradle.properties#L10

https://github.com/ballerina-platform/module-ballerinax-twitter/blob/main/gradle.properties#L10

https://github.com/ballerina-platform/ballerina-lang/blob/2765ebbda30d563602351fe16aea72026cae8c32/gradle/javaProject.gradle#L49

**Comment by keizer619** [comment]
Guava 23.0 has been removed from ballerina-lang as its not required
- https://github.com/ballerina-platform/ballerina-lang/pull/32535

Following connectors guava version has been updated

- https://github.com/ballerina-platform/module-ballerinax-twilio/pull/120
- https://github.com/ballerina-platform/module-ballerinax-twitter/pull/17

**Comment by LakshanSS** [comment]
As Twilio and Twitter connectors also didn't require this dependency, we have removed them in 

Twilio https://github.com/ballerina-platform/module-ballerinax-twilio/pull/121
Twitter https://github.com/ballerina-platform/module-ballerinax-twitter/pull/18
