### ISSUE TITLE
Remove versions of langlibs in compiler

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#32470]
**Description:**
As per the current implementation, the lang repo has the lang library versions hardcoded https://github.com/ballerina-platform/ballerina-lang/blob/79e484fee14324cfa2f73324170ae621981fa853/compiler/ballerina-lang/src/main/java/org/ballerinalang/model/elements/PackageID.java#L66-L110

Since the latest language spec is updated and that we now do not have versions to lang libraries (ref: https://github.com/ballerina-platform/ballerina-spec/commit/eff622461edb56250d597efbcba136aea3793f50) we should remove the hardcoded versions.

**Comment by azinneera** [comment]
This is a prerequisite for #32420

**Comment by hasithaa** [comment]
Can we create a package without a version? IIRC, it will default to 0.1.0.

**Comment by azinneera** [comment]
@hasithaa As per the offline discussion with @sameerajayasoma we decided to set the version  of langlibs to `0.0.0`
