### ISSUE TITLE
Resource paths with special chars and escape chars are not resolved properly during runtime

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#32504]
**Description:**
Consider the following example:
```ballerina
import ballerina/http;

service /foo on new http:Listener(9090) {
    resource function get foo\$bar\@() returns string {
        return "Hello, World!";
    }
}
```

```shell
$ curl http://localhost:9090/foo/foo%24bar%40
```

During the runtime in HTTP module, when we get the resource paths as follows for the example above:
```java
void foo(BObject service) {
    ServiceType serviceType = (ServiceType) service.getType();
    ResourceMethodType[] functions = serviceType.getResourceMethods();
    for (ResourceMethodType function : functions) {
        String[] paths = function.getResourcePath();
    }
}
```

![image](https://user-images.githubusercontent.com/9639050/131508475-2d93417c-e352-4399-82f4-8455fba33ee9.png)

we get this as `foo\$bar\@`. Shouldn't this be resolved as `foo$bar@` without the escape char (`\`) used in Ballerina code?

But, when we decode the function name, it gets resolved as expected as `$get$foo$bar@`.

![image](https://user-images.githubusercontent.com/9639050/131509304-1130f9d0-9309-40db-a9bd-e1e0e42f9c04.png)

**Affected Versions:**
Tested on SwanLake Beta2

**Comment by warunalakshitha** [comment]
This seems to be a bug in getResourcePath api.

**Comment by HindujaB** [comment]
This is because we only encode the function names at compile time. And we don't encode the resource paths specifically. 
If we encode the resource paths as well, then it will be `foo$0036bar@` instead of `foo$bar@`. This is because the encoding modifies the non-jvm-supported characters. 
So, what is the expected version for the resource path here? @ldclakmal

**Comment by ldclakmal** [comment]
In that case, I would expect `foo$0036bar@` instead of `foo\$bar\@`, so that we can decode that using `IdentifierUtils` class if needed. The point is, we use `foo\$bar\@` as the resource path since that is the only way that we can represent the actual `foo$bar@` resource path in a Ballerina service, which will be called by a request with the path `foo%24bar%40`. During the runtime, I am expecting actual resource path (`foo$bar@`) as a resolved string array when we call the `.getResourcePath()` method. But, due to the encoding modifies non-jvm-supported characters, it would be okay to represent it as `foo$0036bar@` instead of `foo\$bar\@` IMO.
Maybe, @chamil321 may have different concerns.

**Comment by warunalakshitha** [comment]
In that case getting "foo\$bar\@" should be ok. IMO we should not use IdentifierUtils since it is an internal api and encode and decodes are part of runtime internals. API should provide whatever the function name define by the user.

**Comment by warunalakshitha** [comment]
Removed the bug label since current behaviour of the api is correct. @chamil321 @ldclakmal Do we have further queries on this?

**Comment by chamil321** [comment]
> Removed the bug label since current behaviour of the api is correct. @chamil321 @ldclakmal Do we have further queries on this?

No concerns from our side.

**Comment by ldclakmal** [comment]
Closing the issue with above comments.
