### ISSUE TITLE
Assigning an incorrect value to `int:MIN_VALUE` type variable does not give a compilation error

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#32513]
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() {
    int:MAX_VALUE b = -10; // gives compilation error as expected
    int:MIN_VALUE a = -10; // no error
}
```

**Affected Versions:**
slbeta2

**Comment by MaryamZi** [comment]
This is most probably the same as https://github.com/ballerina-platform/ballerina-lang/issues/33405. @SandaruJayawardana is already looking into it.
