### ISSUE TITLE
Implement missing functions in Core class

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/ballerina-lang#32538]
**Description:**
Port missing functions in semtype Core class from core.bal

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ushirask** [comment]
@rdhananjaya

**Comment by rdhananjaya** [comment]
Shall we list the functions, if possible? That way, it'll be easy to verify that all methods there are implemented.

**Comment by rdhananjaya** [comment]
@ushirask is all functions listed above, covered in #32554?

**Comment by ushirask** [comment]
> @ushirask is all functions listed above, covered in #32554?

Yes.
