### ISSUE TITLE
Type-guard compeltion item is not suggested by LS

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#32556]
**Description:**
Consider the following two scenarios where I try to use the type-guard completion item. In the second case it is not suggested.
![1](https://user-images.githubusercontent.com/35211477/131903218-3cc64001-8084-4eb8-bf42-8f826e7e7618.png)
![2](https://user-images.githubusercontent.com/35211477/131903286-9e43189d-02d2-40e8-b730-31fbdec99972.png)

**Steps to reproduce:**
```ballerina

function func2() returns int{
    int|error myVar = 1;
    myVar.<cursor>
    if myVar is int {
          return 1;
    }
}
```

**Comment by nadeeshaan** [comment]
When we get the parent of the `myVar.` which is a field access expression, it gives the parent as `TypeTestExpressionNode`, which is invalid.

**Comment by lochana-chathura** [comment]
Related or same as #32587.
