### ISSUE TITLE
Getting method is too large: '$populate$type$Client$attachedFunctions0' ERROR during bal build

### ISSUE THREAD

**Issue by LakshanSS** [ballerina-platform/ballerina-lang#32560]
**Description:**
When building [this project](https://github.com/LakshanSS/ballerinax-openapi-connectors/tree/shoppingcontent-slbeta3/openapi/googleapis.shoppingcontent) which has 88 remote functions, getting the following error.
`ERROR [googleapis.shoppingcontent:(1:1,1:1)] method is too large: '$populate$type$Client$attachedFunctions0'`

**Steps to reproduce:**
Do a `bal build` in [this project](https://github.com/LakshanSS/ballerinax-openapi-connectors/tree/shoppingcontent-slbeta3/openapi/googleapis.shoppingcontent).

**Affected Versions:**
Ballerina SLBeta3 RC1

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/31631

**Comment by warunalakshitha** [comment]
This should be fixed with https://github.com/ballerina-platform/ballerina-lang/issues/32019 which is merged for beta 3 RC2. I will verify with beta 3 RC2 once released.

**Comment by LakshanSS** [comment]
In slbeta3 RC2, this package is building fine

**Comment by warunalakshitha** [comment]
Closing the issue as per above comment.
