### ISSUE TITLE
Assigning `-9223372036854775808` to an `int` does not overflow

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#32577]
**Description:**
Consider the following line in [lang.int](https://ballerina.io/spec/lang/master/#lang.int) spec
```
# Minimum value of type `int`.
public const MIN_VALUE = -9223372036854775807 - 1; // -9223372036854775808 would overflow
```
Since ballerina doesn't have a concept of positives and negatives,  the positive part here `9223372036854775808` should overflow. 

**Steps to reproduce:**
```ballerina
public function main() {
    int a = -9223372036854775808; //This should overflow, but works ATM
}
```
**Affected Versions:**
slbeta2

**Comment by KRVPerera** [comment]
In two`s complement for 64 bit range.

**-2<sup>(n-1)</sup> )  --- 0 --- 2<sup>(n-1)</sup> - 1**
**-2<sup>(63)</sup> )  --- 0 --- 2<sup>(63)</sup> - 1**
**-9223372036854775808 --- 0 --- 9223372036854775807**
