### ISSUE TITLE
VSCode Incorrectly Showing bal Files Having Errors 

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#32578]
**Description:**
In the VSCode side pane where the files are shown, it sometimes shows some files are having errors (highlighting those files in red, and showing the error count as well). But when the file is opened, it does not contain any error. Once we close the file, the error appears back in the side pane.

Check the following screencast. This uses the Ballerina GraphQL module.

https://user-images.githubusercontent.com/40016057/132165745-81d743b9-48e4-4286-b3f2-5ce2fe0302d7.mov

**Affected Versions:**
SwanLake-Beta.3-RC1

**OS, DB, other environment details and versions:**
VSCode Version: 1.60.0
Ballerina VSCode Plugin Version: 2.1.0
OS: macOS Big Sur

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2/ballerina-plugin-vscode/issues/135 to track this.
