### ISSUE TITLE
Generate Config.toml based on configurables in a project

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#32585]
**Description:**
As of now user needs to extract and create a Config.toml manually. Instead of doing it manually we can create a compiler plugin to extract the configs and create a configuration file with all the variables automatically. 

1. Config.toml will be created in `target/bin` directory by default
2. If there is a Config.toml in the above location we will try to merge the new configs with the existing one without overwriting the values.

**Comment by rdhananjaya** [comment]
`display` is a source only annotation, I don't think we should export that from a module.  [display annot](https://github.com/ballerina-platform/ballerina-lang/blob/db26274b9e4092d0aa595f8842be300b810a0062/langlib/lang.annotations/src/main/ballerina/annotations.bal#L92)

**Comment by Dilhasha** [comment]
The API changes required to retrieve the configurable details will be available with Beta4.

If the user needs to generate the config-schema json, user has to do the following.

- Build the compiler plugin for config schema generation using

`./gradlew clean :compiler-plugins:configurable-schema-generator:build`

- Add the generated jar at `ballerina-lang/misc/compiler-plugins/modules/configurable-schema-generator/build/libs/configurable-schema-generator-2.0.0-beta.4.jar` to the `<ballerina-distribution>/bre/lib` path.

- Now when you run the Ballerina project you’ll get the JSON schema generated at `target\bin\config-schema.json`

**Comment by Dilhasha** [comment]
With Beta4 latest RC, we have added the compiler plugin to the distribution and introduced the flag `generate-config-schema`. You can use it with `bal build`, `bal run` and `bal pack` to generate a JSON schema with the details of configurable variables in the current package.
