### ISSUE TITLE
Invalid suggestions for string variable

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32587]
**Description:**
Consider the bellow sample
```bal
public function main() {
    string stringVar = "a";
    int i = 0;
    stringVar.<cursor>
    while i <= stringVar.length() {
        io:println(""); 
        i+=1;
    }
}
```
Gives incorrect suggestions

![Screenshot from 2021-09-06 18-49-35](https://user-images.githubusercontent.com/26381349/132223822-160d9830-497c-4824-84cc-708f7f832c27.png)

But it correctly gives suggestions when I comment the `io:println(""); ` line

![Screenshot from 2021-09-06 18-53-53](https://user-images.githubusercontent.com/26381349/132224194-55eb8ada-c95f-4e65-a5c0-9bbb8426f8c7.png)

**Affected Versions:**
Current master

**Comment by nadeeshaan** [comment]
In this particular use-case the parser does not identify the `stringVar.` part as a field access expression. The parser resolution strategy marks the `stringVar` as an invalid token and proceed. If you look at the diagnostics shown in the first use-case and the second use-case, they are completely different. In both of the cases, the resolution should be the same irrespective of the `io:println("")` part.

When debugged, as per my understanding, we have to fix this from the parser.
