### ISSUE TITLE
Semantic API returning incorrect module symbol for value lang library symbols

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#32586]
**Description:**
Please refer to the below code. When trying to access the module symbol from the value library's `jsonDecimal` symbol returns `lang.annotations` library as the result (which is incorrect).

```ballerina
import ballerina/lang.value;

public function main() {
    value:JsonDecimal jsonDecimal = 23;
}
```

<img width="954" alt="Screenshot 2021-09-06 at 15 30 46" src="https://user-images.githubusercontent.com/29032600/132211717-ff98cf18-c0df-42bb-8688-02faf6966878.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Had a look at this. It seems this is a bug in the compiler. In the internal symbol for `JsonDecimal`, the package ID is correct. But the owner symbol is set to the module symbol of `lang.annotations`.
