### ISSUE TITLE
Conflict jar warning due to module-info.class

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#32591]
**Description:**
We recently updated the version of the **BouncyCastle** jars (from 1.61 to 1.69) which we used in several modules like `crypto`, `http`, `websocket`, `grpc`, and `websub` due to the security vulnerability found in 1.61 version. Please refer to [1] for more information related to that.

Now, with the latest distribution pack, we get the following warning when we build a simple HTTP service program with `bal build hello.bal`

```shell
Compiling source
        hello.bal

Generating executable
        warning: Detected conflicting jar files:
                'bcpkix-jdk15on-1.69.jar' dependency of 'ballerina/crypto' conflict with 'bcprov-jdk15on-1.69.jar' dependency of 'ballerina/crypto'
        hello.jar
```

When we do a `bal build` with `--list-conflicted-classes flag`, we get the following additional information.

```shell
META-INF/versions/9/module-info.class
```

[1] https://github.com/ballerina-platform/ballerina-distribution/issues/2124

**Affected Versions:**
Swan Lake Beta3 RC2

**Comment by azinneera** [comment]
We can skip adding the `module-info.class` to avoid this warning

**Comment by pramodya1994** [comment]
Currently, we do the following check to avoid this:
`!entryName.equals("module-info.class")`

If we change this to `endsWith`, this issue will be fixed.
