### ISSUE TITLE
Suggestions should be context-aware

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#32607]
I am using Ballerina Swan Lake Beta2.  Let me describe the requirement using the following image. 
<img width="745" alt="Screen Shot 2021-09-06 at 8 35 11 PM" src="https://user-images.githubusercontent.com/2637328/132427760-ccae5b09-13ae-4724-b23e-2afce4e8f2d3.png">

IMO, the first two completion items should be `http:Response` and `http:ClientError`.

**Comment by mohanvive** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/32792 .

**Comment by nadeeshaan** [comment]
Blocker has been resolved. Hence removing the label

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/26284
