### ISSUE TITLE
[LS Code Actions] 'Create variable' code action provides invalid code snippet for langlib functions

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#32610]
**Description:**
Please refer the sample code snippet and syntactically incorrect output after invoking `create variable` code action for the `runtime` lang library function.

***code snippet***
<img width="260" alt="Screenshot 2021-09-08 at 09 15 18" src="https://user-images.githubusercontent.com/29032600/132443259-5b3832e9-e7e1-485a-b508-b67860a82d33.png">

***Code Action result***
<img width="431" alt="Screenshot 2021-09-08 at 09 15 28" src="https://user-images.githubusercontent.com/29032600/132443278-4acafce8-6a62-47be-8faa-cc23336abfef.png">

Considering the module prefix when deriving the variable type within LS code actions might solve this for similar contexts. The expected output is shown below.

<img width="513" alt="Screenshot 2021-09-08 at 09 15 44" src="https://user-images.githubusercontent.com/29032600/132443283-10a4ef11-fd9c-42c8-aa84-b0994a6e34bf.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharushiJay** [comment]
The issue here is that the signature of the type reference type symbol doesn’t have the module prefix since the owner is set as `lang.annotations`. This is similar to #30909 and possibly related to #26284.

@pubudu91 WDYT?

<img width="861" alt="Screenshot 2021-09-14 at 11 08 57" src="https://user-images.githubusercontent.com/27485094/133203583-0a85d88c-e9bc-4596-8f99-ce59610bae3f.png">

**Comment by pubudu91** [comment]
This is similar to #32586. This is a bug in the `BIRPackageSymbolEnter`: https://github.com/ballerina-platform/ballerina-lang/blob/2f5506cae9cb9f83ca27feeed528b4b4ffc6bce1/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L1275
This should've been `env.pkgSymbol`, not `env.pkgSymbol.owner`.
