### ISSUE TITLE
`from` in a `from` get stuck in a loop

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#32614]
```ballerina 
   error? e = from var dir in check file:readDir("./testSuite")
              from var sub in check file:readDir(dir.absPath)
              do {
                  io:println(sub.absPath);
              };
```
Above gets stuck in an infinite loop.

**Comment by manuranga** [comment]
Maybe this only happens when `file:readDir(dir.absPath)` throws an error, becase there was a file, not a dir inside `./testSuite`.

**Comment by manuranga** [comment]
could be related to #32615

**Comment by KavinduZoysa** [comment]
We can close this issue because the actual error is not presented anymore. But there is a runtime error for this nested query and issue is tracked in #32615
