### ISSUE TITLE
Wrong behaviour with XML attribute access with qualified name where the qualified name referring to a module const string 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#32624]
**Description:**
```ballerina

// public const string A = "{NSURL}B"; this is in module `y`

// import org/y;

xmlns "NSURL" as ns;
public function main() {
    
    io:println(y:A);
    xml x = xml `<a ns:A="content"></a>`;
    io:println(x.y:A); // y:A should refer to the value from `y` === `{NSURL}B`
}
```

Reproduceble with:
[X.zip](https://github.com/ballerina-platform/ballerina-lang/files/7126953/X.zip)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Also compiler seems to validate the content of `y:A` when used like this. Verify if we need this validation?

**Comment by KavinduZoysa** [comment]
Another example:
main.bal
```ballerina
import ballerina/io;
import new_pkg.mod as mod;

public function main() {
    xml x = xml `<items id='9'></items>`;
    io:println(x.mod:ID); // error
}
```

mod.bal
```ballerina
public const ID = "id";
```

Above example should work according to, 
```It is also allowed for the xml-attribute-name to be specified as a qualified-identifier, in which the prefix is a module-prefix declared using an import-decl. In this case the qualified-identifier must refer to a module-const-decl of type string, and the attribute name string is the value of the referenced constant.```
