### ISSUE TITLE
Need to improve the config related BBE

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#32656]
**Description:**
The existing Ballerina [configuration-related BBE](https://ballerina.io/learn/by-example/configurable-variables.html?is_ref_by_example=true) is not comprehensive enough to understand the overall idea related to configurable variables.

IMO, we should add the following information:
- How to configure the `Config.toml`
- Usage of environment variables
- Configure secrets
- Configurations pass as arguments to the `bal` command

**Comment by HindujaB** [comment]
We currently have a separate learn page to explain the whole feature with the points above mentioned. 
https://ballerina.io/learn/making-ballerina-programs-configurable/defining-configurable-variables/

We can add this learn page link to the BBE. 
Similar to the testing BBEs - https://ballerina.io/learn/by-example/testerina-assertions.html?is_ref_by_example=true
