### ISSUE TITLE
Warning: Detected conflicting jar files in ballerina/sql & 'ballerinax/mysql

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#32666]
**Description:**
I am getting following warning when using mysql module 
```
warning: Detected conflicting jar files:
        'sql-native-0.6.0-beta.2-20210630-212800-2903cac.jar' dependency of 'ballerina/sql' conflict with 'sql-native-0.6.0-beta.2.jar' dependency of 'ballerinax/mysql'
```
It seems the same jar is included in two modules. is it required or can we remove the native lib from one module so that the warning will go away.

Affected versions beta2

**Comment by azinneera** [comment]
Meeting noted from the discussion on 08/06/2022: https://docs.google.com/document/d/1x4lqUrHtbUobt0nhbnCnUQ4hdy4V_-WX02Ajg0oZSZ8/edit?usp=sharing

Based on the notes we agreed to introduce a governance model to prevent using incompatible jars in ballerina and ballerinax packages. For this:

- [ ]  Implement an API in central is required to query jars used in ballerina and ballerinax packages
- [ ]  Avoid using fat jars in ballerina and ballerinax packages
- [ ]  Adopt an approval process when using a new version of an existing jar or using a new jar

**Comment by azinneera** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/36659:
* Latest version will be picked if there are two jars of the same library for all organizations
  * The equality of 2 jars is checked using the `groupId` and the `artifactId` from the Ballerina.toml
  * Apache Maven's [ComparableVersion](https://maven.apache.org/ref/3.6.0/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html) is used for version comparison. This is the library used by maven for version resolution and is capable of handling both Semver and non-semver versions

Next steps:
 * Issue a warning for conflicting jars of non-ballerina organizations
 * Decide on the rules for version comparison and improve if needed
    * Which version to pick if the lower version is stable and the latest is not?
    * If the jars are from `ballerina*` org, should we validate if it is Semver compatible?

**Comment by daneshk** [comment]
We have a use case where we need to access the platform dependency jar from the Ballerina project's imported modules from the CLI tool. Let's say, for example,

We have a Ballerina project that imports the` ballerinax/mysql.driver` module. `ballerinax/mysql.driver` module has a platform dependency on the MySQL driver jar. Once we build the project, this module is pulled from the central and stored in the local cache. If we check the local cache, the MySQL driver jar is located in the path[1]. We need to access this path from the CLI tool as we need to execute SQL scripts against the DB. 

Is there an API from the project level in which we can get the platform dependency path of the certain imported module? If not, can we provide one? 

1. <user_home>/.ballerina/repositories/central.ballerina.io/bala/ballerinax/mysql.driver/1.3.0/java11/platform/java11

**Comment by azinneera** [comment]
> We have a use case where we need to access the platform dependency jar from the Ballerina project's imported modules from the CLI tool. Let's say, for example,
> 
> We have a Ballerina project that imports the` ballerinax/mysql.driver` module. `ballerinax/mysql.driver` module has a platform dependency on the MySQL driver jar. Once we build the project, this module is pulled from the central and stored in the local cache. If we check the local cache, the MySQL driver jar is located in the path[1]. We need to access this path from the CLI tool as we need to execute SQL scripts against the DB.
> 
> Is there an API from the project level in which we can get the platform dependency path of the certain imported module? If not, can we provide one?
> 
> 1. <user_home>/.ballerina/repositories/central.ballerina.io/bala/ballerinax/mysql.driver/1.3.0/java11/platform/java11

You can use the following API to get the platform library path:
https://github.com/ballerina-platform/ballerina-lang/blob/bba812d6d6a6dd6d0dbb15ba516338da4eb8fae7/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java#L241-L243

The drawback of the above method is that the code generation phase will have to be run in order to access the API which can be run after the project is loaded. Alternatively, you can also use the following API to access the platform library entries in the Ballerina.toml. 

https://github.com/ballerina-platform/ballerina-lang/blob/bba812d6d6a6dd6d0dbb15ba516338da4eb8fae7/compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageManifest.java#L267
This contains the library paths relative to the source root. You can construct the absolute path with the following API:

`dependencyPkg.project().sourceRoot().resolve(<lib-path-from-bal-toml-entry>)`

**Comment by azinneera** [comment]
Reopening the issue to track the documentation on the best practices for writing platform libraries.

**Comment by Dilhasha** [comment]
I have improved the documentation for the platform dependencies section with the missing details. Please review the content at
https://docs.google.com/document/d/1RY4DsGOJN_fEKbSHnnbTyhXnu-xwEJ6DVdpPUJ8mFdI/edit?usp=sharing

**Comment by azinneera** [comment]
Added the content to the website with https://github.com/ballerina-platform/ballerina-dev-website/pull/6441. Closing the issue as its complete.
