### ISSUE TITLE
Isolated flag is not switched on in isolated service declarations

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#32661]
**Description:**
$title

```ballerina
listener Listener aListener = new ();

isolated service / on aListener {
   
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@dulajdilshan, can you please elaborate on how this check is done?

The following prints true.

```ballerina
import ballerina/io;

listener Listener aListener = new ();

isolated service / on aListener {

}

class Listener {

    public function init() {
    }

    public function attach(service object {} s, string|string[]? name = ()) returns error? {
        io:println(s is isolated service object {});
    }

    public function detach(service object {} s) returns error? {
    }

    public function 'start() returns error? {
    }

    public function gracefulStop() returns error? {
    }

    public function immediateStop() returns error? {
    }
}
```

Checked on slbeta2 also, which was released before September 2021.

**Comment by KavinduZoysa** [comment]
Closing this issue because it works as mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/32661#issuecomment-1055461272
