### ISSUE TITLE
Avoid querying the central when exact match is needed and the version is available in filesystem

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#32675]
**Description:**

When the versions are available in Dependencies.toml and a non-expired `target/build` is present,  internally it should be considered as `sticky == true, and locking mode == HARD` which means we should match the exact version. If that version is available in the filesystem repos, we should not query the central.

**Steps to Reproduce:**

1. Create a package with a few dependencies and build with `--dump-build-time` flag and note the package resolution time
      This will create the Dependencies.toml and the `target/build` file
2. Re-run the build command and compare the package resolution times

*_Expected Behavior:_*
The package resolution time for the 2nd attempt should be much lesser than the first time since it is expected to resolve from the filesystem and so no central querying should take place.

*_Actual Behavior:_*
Both times are almost equal

**Affected Versions:**
Beta.3-SNAPSHOT

**Comment by Dilhasha** [comment]
- [ ] Make sure that no central calls are done during consecutive builds.

**Comment by Dilhasha** [comment]
Tested the Package resolution times for nballerina project to see that it is reduced for consecutive builds and matches with the time taken when built using --offline flag.
