### ISSUE TITLE
Issue when determining basic type for numeric-literals

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#32698]
**Description:**
Consider the following program,
```ballerina
float|decimal x = 2;
```
According to the spec [section 6.5](https://ballerina.io/spec/lang/2021R1/#section_6.5) 
![image](https://user-images.githubusercontent.com/34838308/132683025-2f294305-af62-4b84-8fa5-d485d83f3459.png)

 basic type of the numeric-literal (here, `2`) should be 'int' (referring to `otherwise, if the numeric literal is an int-literal, then the basic type is int;`) and above program should create a compile error. But with the current compiler implementation, basic type equals to 'float'.

**Comment by MaryamZi** [comment]
May depend on https://github.com/ballerina-platform/ballerina-spec/issues/943 for some cases.
