### ISSUE TITLE
[Semantic API] `references()` not working for key specifier in a table

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#32705]
Consider the following:
```ballerina
type Foo record {
    readonly int x;
    int y;
};

public function main() {
    table<Foo> key(x) tb = table key(x) [
        {x: 1001, y: 20}
    ];
}
```
If I look up the references of the field `x`, I only get the definition and the reference in the mapping constructor. I think this should ideally be returning the references in the key specifiers as well.

**Comment by dulajdilshan** [comment]
The symbol information in the table key specifier is missing.

**Comment by mohanvive** [comment]
This issue should be fixed at the compiler FE side. Let's check for possible solutions at compiler level.
