### ISSUE TITLE
`CompilerLifecycleTask` is not executed when we use `bal run` command

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#32717]
**Description:**
We have developed a in-built compiler plugin for ballerina OpenAPI to generate OpenAPI docs for HTTP services in built time. In this plugin we have used `CompilerLifecycleTask` provided in ballerina project API to inject resources to generated thin-jar and executable jar. 

When we use `bal build` command, `CompilerLifecycleTask` is invoked and resource injection will be successful. But if we use `bal run` command then `CompilerLifecycleTask` is not invoked and resource injection will be unsuccessful. 

**Affected Versions:**
- Ballerina Swan Lake Beta3 RC3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Related to [#1616](https://github.com/ballerina-platform/ballerina-standard-library/issues/1616)

**Comment by hevayo** [comment]
I think we should add a new lifecycle method to run after module code has generated. ie ModuleCodeGenerated

**Comment by azinneera** [comment]
With the linked PR, we now support adding sources and resources with code generator compiler plugins and so these will be added to the thin jars and the executable/archive. Refactoring the resource packaging implementation to use code generators will resolve this issue.
