### ISSUE TITLE
[Query Expressions]Some queries fail resolving closure symbols

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#32710]
**Description:**
```ballerina
 var res = from var emp in (from var x in (from var xx in (from var xxx in (from var {firstName, lastName, dept} in employeeList
                        where 1 == 1
                        select firstName + " " + lastName)
                    select xxx)
                select xx)
            select x)
        select emp;
```
 
**Steps to reproduce:**

**Affected Versions:**
SL Beta 3 rc 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Getting a closure issue for
```ballerina
    int[][] data = [[1, 2], [2, 3, 4]];
    (function ())[] res = from int[] arr in data
        select function() {
            int sumOfEven = 0;
            error? ignored = from int i in arr
                do {
                    sumOfEven += i;
                };
        };
```

**Comment by pcnfernando** [comment]
```ballerina
type A record {|
    int[] pos;
|};

public function main() {
    A[] res = from var a in 2...5
        select {
            pos: (from var b in (from var c in 1...2 where c == a select c) // undefined symbol 'a'
                select b)
        };
}
```

**Comment by lasinicl** [comment]
Related Issues:
https://github.com/ballerina-platform/ballerina-lang/issues/32710
https://github.com/ballerina-platform/ballerina-lang/issues/36286
https://github.com/ballerina-platform/ballerina-lang/issues/36488
https://github.com/ballerina-platform/ballerina-lang/issues/37425
https://github.com/ballerina-platform/ballerina-lang/issues/37481
https://github.com/ballerina-platform/ballerina-lang/issues/38511

**Comment by KavinduZoysa** [comment]
This should be covered via https://github.com/ballerina-platform/ballerina-lang/pull/39762
