### ISSUE TITLE
`bal` commands and VSCode plugin do not work correctly inside folders which have a space in their name

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#32740]
**Description:**

If the current directory's path contains a folder which has a space in its name, `bal` CLI commands do not work correctly.
```logtalk
nadeeshand@nadeeshand folder2 % pwd
/Users/nadeeshand/foldername withaspace/folder2
nadeeshand@nadeeshand folder2 % bal version
Error: Could not find or load main class withaspace.folder2
Caused by: java.lang.ClassNotFoundException: withaspace.folder2
```

Also the if the path of the opened folder in VSCode, has a folder which has a space in its name, it also does not work correctly.
![image](https://user-images.githubusercontent.com/33286289/133281353-a935187c-30f2-4816-94fe-cdcbf3367fdc.png)

**Steps to reproduce:**

**Affected Versions:**
slbeta4-snapshot
2.0.0-beta3-dev branch

**OS, DB, other environment details and versions:**
Observed in both ubuntu 20.04 and macOS 11.5.2

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
Similar issue https://github.com/ballerina-platform/ballerina-lang/issues/32863

**Comment by IMS94** [comment]
I get the same error in the latest GA RC pack.
```
imesha@imesha:~/Downloads/Linux Installer deb$ bal version
Error: Could not find or load main class Installer
Caused by: java.lang.ClassNotFoundException: Installer
Update Tool 1.3.7-rc1
```

**Comment by mohanvive** [comment]
@keizer619 Can you guys please check this?

**Comment by NipunaMadhushan** [comment]
closing this issue as it has been fixed with https://github.com/ballerina-platform/ballerina-update-tool/pull/210
