### ISSUE TITLE
Issue with using `userSpecifiedMemberTypes()` in UnionTypeSymbol

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#32760]
**Description:**
This  `userSpecifiedMemberTypes()` API is used to access the typeSymbols in the union type in code generator in openapi. 

When tried to access all the typeSymbol in given `Dog|Cat? pet` record field, It returns only 2 typeSymbols with TypeReference symbol for Dog and one UnionTypeSymbol for both `Cat`  and `nil`. 

Expected to have 3 symbols for `Dog|Cat? pet` .

**Steps to reproduce:**

**Affected Versions:**
Ballerina swanlake beta 03 rc 3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-openapi/issues/590
https://github.com/ballerina-platform/ballerina-openapi/issues/587

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Related to #32569. Similar issue there. This seems to be a bug in the `BUnionType`.

**Comment by dulajdilshan** [comment]
Can you please try using `memberTypes()` instead?
