### ISSUE TITLE
Compilation Error for visibleSymbol's `typeDescriptor` 

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#32792]
**Description:**

When trying to get the `visibleSymbols` at `cursor`, we get `COMPILATION_ERROR`  for the symbol `getResult`'s `typeDescriptor` 

**Steps to reproduce:**
```
function foo() {
    int getResult = getValue();
    if getResult is <cursor> {
    }
}

function getValue() returns int {
    return 0;
}
```

**Affected Versions:**
slbeta3

**Comment by pubudu91** [comment]
Looks like an issue with how the compiler defines the type narrowed symbol in cases like this. The `visibleSymbols()` API is picking up the (incorrectly) type narrowed symbol here when it should've actually picked up the original symbol in this particular scenario.
