### ISSUE TITLE
Function defined outside `service` declaration is not identified while writing `if` a statement within a `resource function`

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#32791]
**Describe your problem(s)**
Consider the following code snippet 
```import ballerina/http;

service / on new http:Listener(8080) {
    resource function get count () returns json|error {
        int|string getResult = getValue();
        if 
    }
}


function getValue() returns int|string {
    return 0;
}
```
Here we get diagnostics at `getValue()` inside the service, Even though it is implemented.

![Screenshot from 2021-09-16 16-06-41](https://user-images.githubusercontent.com/46120162/133725281-c6fdb3cc-6569-4555-ab54-cc2f44484e59.png)

**Describe your solution(s)**

 Can we improve the parser recovery logic here, so that the `getValue()` function is not taken as inside the `service`?

**Related Issues (optional):**

We keep getting code action suggestions to implement relevant functions even after accepting the code action to implement the method.

**Comment by lochana-chathura** [comment]
Quoting from the google chat room discussion:

Lochana:
> from a parser point of view, both the above code and below are the same. That's the issue.
> ```
> service / on new http:Listener(8080) {
>     resource function get count () returns json|error {
>         int|string getResult = getValue();
>         if }
>     }
> 
>     function getValue() returns int|string {
>         return 0;
>     } 
> ```

Dulmina:

> I was thinking that we need to find a way to improve this anyway right? We handled similar cases via recovery completion mode but this is beyond that.

> Lets create an issue but not sure whether we can improve this from the parser side
