### ISSUE TITLE
Annotations attached to anon functions are missing

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#32809]
Consider the following:
```ballerina
function testAnonFuncs() {
    var fn1 = @v1 function(int x, int y = 0, string... z) {
        int total = x + y;
    };
}

annotation v1 on function;
```
Here, if we debug and see, the annotation `v1` attached to the anon function is missing from the annotation attachments in the AST node for it.

**Comment by MaryamZi** [comment]
Tracked with https://github.com/ballerina-platform/ballerina-lang/issues/18207.
