### ISSUE TITLE
false positives for WARNING: unreachable pattern

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#32818]
**Description:**
I some cases the ballerina analyzer/compiler emits `WARNINGS` of type `unreachable pattern` which are false positives.

**Steps to reproduce:**
One specific case can be reproduced with test cases in this [bitbucket repo](https://bitbucket.org/gubaer/ballerina-match-issue).

```bash
# clone repository
$ git clone https://bitbucket.org/gubaer/ballerina-match-issue

# run the test
$ bal test
	gubaer/ballerina_match_issue:0.0.1
===> these are false positives
WARNING [tests/test.bal:(58:9,58:19)] unreachable pattern
WARNING [tests/test.bal:(80:9,80:19)] unreachable pattern

Running Tests

	ballerina_match_issue

		[pass] test01
		[pass] test02
		[pass] test03
		[pass] test04

		4 passing
		0 failing
		0 skipped
```
The two false positives are also displayed as diagnostics in VS Code. Launch VS Code with `code .` and navigate to the file [`tests/test.bal`](https://bitbucket.org/gubaer/ballerina-match-issue/src/master/tests/test.bal).

![Screenshot from 2021-09-20 14-48-40](https://user-images.githubusercontent.com/249051/134004929-c1a76031-aaf2-40dd-93cc-ebd4337da546.png)

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by MaryamZi** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/31126.

**Comment by SasinduDilshara** [comment]
This issue is already Fix.
We only adding tests cases in the https://github.com/ballerina-platform/ballerina-lang/pull/37061
