### ISSUE TITLE
[Debugger] When debugging a transaction debugger go through lines which are not suppose to run but program works fine.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#3281]
**Issue:**
When debugging a transaction block it will ignore conditional blocks (ex:- IF conditions) and visit inside those conditional blocks and always visit the aborted block even when there is no abort statement in transaction block or no exception occur. But the output of the program is correct. 

**Sample program**
```js
import ballerina.data.sql;
import ballerina.lang.system;

function main (string[] args) {
    sql:ConnectionProperties properties = {maximumPoolSize: 1};
    sql:ClientConnector db = create sql:ClientConnector (sql:MYSQL, "localhost", 3306, "test1", "root", "password", properties);
    transaction {
        sql:Parameter[] parameters = [];
        int i = db.update("INSERT INTO `students` values (1, 'test')", parameters);
        system:println("Inserted count:" + i);
        if (i == 0) {
            abort;
        }
        } failed {
        system:println("Failed..");
        retry 3;
        } aborted {
       system:println("Transaction aborted..");
    } committed {`
        system:println("Transaction committed...");
    }
}
```

**Comment by lankavitharana** [comment]
This is tracked with git issue - https://github.com/ballerinalang/ballerina/issues/3281

**Comment by lankavitharana** [comment]
this is tracked with https://github.com/ballerinalang/ballerina/issues/3591

**Comment by hevayo** [comment]
Reopen since it was closed pointing to the same issue.

**Comment by NipunaRanasinghe** [comment]
Closing since the conditional statements debugging inside transnational blocks are working as expected in the latest SwanLake release (SLAlpha4).
