### ISSUE TITLE
compilation fails with `error: jVM generation is not supported for type other`

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#32819]
**Description:**
Compilation of a module fails with `error: jVM generation is not supported for type other`.

This should't be the case for [this specific module](https://bitbucket.org/gubaer/ballerina-issue-compilation-fails). 

**Steps to reproduce:**

```bash
# clone the sample repo
$ git clone https://bitbucket.org/gubaer/ballerina-issue-compilation-fails

# build the client
$ cd client
$ bal build
error: jVM generation is not supported for type other
```
Comment out [line 27-30 in `client.bal`](https://bitbucket.org/gubaer/ballerina-issue-compilation-fails/src/db17d0b9de72723d6eca4772828be008b6ce9c9d/client/client.bal#lines-27,28,29,30) and build again:

```bash
# when line 27-30 are commented out, the build succeeds
$ bal build
Compiling source
	gubaer/grpc_position_service_client:0.0.1

Generating executable
	target/bin/grpc_position_service_client.jar
``` 

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Related Issues (optional):**
#32818

**Comment by SasinduDilshara** [comment]
Minimal version of this scenario
```
type MyError1 error;
type MyError2 error;

public function main() {
    error? v = getCustomError();
    match v {
        var errorA if v is MyError1 => { 
            
        }
        var errorB if v is MyError2 => { 
            
        }
    }
}

function getCustomError() returns error {
    return error MyError1("");
}
```

**Comment by SasinduDilshara** [comment]
Another minimal version of this issue

```
type MyError1 error<record { int x; }>;
type MyError2 error<record { int y; }>;

public function main() {
    error? v = getCustomError();
    match v {
        var errorA if v is MyError1 => { 
            
        }
        var errorB if v is MyError2 => { 
            
        }
    }
}

function getCustomError() returns error {
    return error MyError1("Message", x = 2);
}
```

**Comment by SasinduDilshara** [comment]
This issue is already Fixed.
We only adding tests cases in the #37095
