### ISSUE TITLE
[Debugger] Number of variables are wrong when variables with same name are declared in each block of Try statement

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#3282]
**Issue:**

When there are multiple variables declared inside a try-catch-finally block with the same name on debug it list down five variables in that name when there is only 3 variables declared. This is only happening for try-catch block. 

**Sample Code**
```js
import ballerina.lang.errors;

function main (string[] args) {
    string[] data = null;
    int[] i1 = [1, 2, 3];
    try {
        int i = 34;
    } catch (errors:NullReferenceError nul){
        int i = 34;
    }
    catch (errors:Error err){
            int i = 45;
    }
    finally{
            int i = 56;
    }
}
```

when debug variable listing shows 5 variables with the name **"i"**

**Comment by Shan1024** [comment]
Closing since the `try-catch` block is now removed from the language.
