### ISSUE TITLE
Can't use templates with `bal init`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#32824]
**Description:**
$title, even though the command help text mentions it (`bal init -h`).

**Steps to reproduce:**
```cmd
$ bal init --template main
ballerina: unknown option: '--template'
Run 'bal help' for usage.
```

**Affected Versions:**
slbeta3-rc3

**Comment by azinneera** [comment]
We dont allow adding templates with `bal init`. The help text has been updated in SL GA.
