### ISSUE TITLE
Compilation fails when a dependency is moved to another hierarchical package

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#32832]
**Description:**

Compilation fails when a package moves a dependency to a hierarchical package. 

**Steps to reproduce:**

Consider the following scenario.

`pack1` exports `pack1.mod.doc`
`pack2` imports  `pack1.mod.doc`

- Rebuild and publish another version of `pack1` where the module `mod.doc` is removed in order to move it to a new package. 
- Now create `pack1.mod` and add the module `doc`. Now this package exports `pack1.mod.doc`

`pack1` exports `pack1`
`pack1.mod` exports `pack1.mod.doc`
`pack2` imports  `pack1.mod.doc`

- Now, when trying to build `pack2`, this results in a compilation failure as it tries to pull and use the latest version of `pack1` instead of using latest version of `pack1.mod`.

**Affected Versions:**

Swan Lake Beta3 RC3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
This can only happen if a user decided to split/merge an existing multi-module package. As per the current Ballerina Central design, a module can be only in one package. Therefore, this scenario will not be handled for Swan Lake.

**Comment by Dilhasha** [comment]
As no two packages can export the same module (i.e. when constructing the full module name, it can be only resolved from one package), we can close this issue as it is the expected behavior.
