### ISSUE TITLE
No default value generated for the record field

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#32841]
**Description:**
Consider the following screen capture

https://user-images.githubusercontent.com/1329674/134278619-4727783a-956b-4d25-b632-c7561e6a0aab.mp4

For the particular field, the value is a union. We should find a better way to handle this use-case

**Affected Versions:**
SanLake beta4-snapshot at least

**Comment by TharushiJay** [comment]
Observed this behaviour in **Beta 3 RC3**.
<img width="443" alt="Screenshot 2021-10-04 at 10 47 15" src="https://user-images.githubusercontent.com/27485094/135800478-f9ab3cf6-19f7-4886-881a-6d9290e88c3e.png">

And on **master**, the mapping constructor is inserted along with `oauthClientConfig` and the relevant keys are also suggested as seen in the following screen capture.



https://user-images.githubusercontent.com/27485094/135800793-29b227f8-a75b-4b7a-9e03-dfbea6fff8a7.mov


The difference in master and sl beta 3 is the depth we introduced to avoid SO errors.

Therefore, I'm not able to reproduce this issue.
