### ISSUE TITLE
Add how to run a single test into `How to test Ballerina` guide

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#32842]
**Description:**
It seems we can use the command `bal test --tests testName /path_to_module` to invoke a single test (learned it via VS Code code action `run`), I think we need to add this capability to the guide.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment]
@rdhananjaya We have specified this in the `executing tests` section in the guide.
https://ballerina.io/learn/testing-ballerina-code/executing-tests/

**Comment by rdhananjaya** [comment]
Oh my bad, didn't see that. I'll close this issue.
