### ISSUE TITLE
Add spec conformance to anon function expression's auto completions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#32879]
**Description:**
$title

**Comment by TharushiJay** [comment]
Created issues
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33285
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33291
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33292
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33312
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33313

**Comment by nadeeshaan** [comment]
Closing the issue, since all the associated sub issues are fixed
