### ISSUE TITLE
[VS Code plugin] fix rendering of string templates within a mapping constructor expression

### ISSUE THREAD

**Issue by Gubaer** [ballerina-platform/ballerina-lang#32881]
**Description:**
The VS Code plugin doesn't render string templates within mapping constructor expressions as expected.

**Steps to reproduce:**

Consider the following ballerina fragment:
```ballerina
const int i = 1;
final string message = string`foo bar: ${i}`;

var obj = {
    // rendering of the string template should be the same as 
    // for 'final string message' above
    message: string`foo bar with ${i}`

// this comment should be rendered in green

// this closing bracket should be rendered in brown
};
```
The VS Code plugin renders it as follows:
![Screenshot from 2021-09-23 11-54-20](https://user-images.githubusercontent.com/249051/134488024-f1cef82e-2ced-4dcf-ae08-2bb34446577a.png)

**Affected Versions:**

Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

Plugin Version:
Released on 6/1/2021, 16:13:16
Last updated 9/10/2021, 06:05:54

Linux integrationbox 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nadeeshaan** [comment]
Created an issue in the plugin repository since this is a syntax highlighting issue. Please refer https://github.com/wso2/ballerina-plugin-vscode/issues/139. Hence closing this issue
