### ISSUE TITLE
Incorrect behaviour in `bitwise-or-expr` when the static types of operands are `int:UnsignedK`

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32888]
Accroding to spec 

```for XOR or OR, if the type of both operands is a subtype of int:UnsignedK when K is 8, 16 or 32, then the static type of the result is int:UnsignedN where N is the smallest such K; otherwise, the static type of the result is int.```

```bal
public function main() {
    int:Unsigned16 g = 256;
    int:Unsigned8 h = 0;

    int:Unsigned8 i = g | h; // should result in an error since the smallest such K is 16, 
                             // currently gives no error
}
```

Also 
```bal
public function main() {
    int:Unsigned16 g = 256;
    int:Unsigned8 h = 0;

    io:println((g | h) == (256 | 0));  // should give true, currenly gives false since it evaluates `g | h` to `0`
}
```

Related discussion https://github.com/ballerina-platform/ballerina-spec/issues/458#issuecomment-599018950

**Comment by rdulmina** [comment]
Please note that this issue is also with the `bitwise-xor-expression`.

**Comment by rdulmina** [comment]
```bal
type MyType int;

type MyType2 int:Signed32|int:Unsigned16;

type MyType3 int:Unsigned32|int:Signed8;

type MyType4 byte|int:Signed8;

type MyUnionType MyType2|MyType4;

public function main() {
    MyType a = 5;
    MyType b = 433;
    int c = 765;
    MyType2 d = 4344;
    MyType3 e = -34;
    MyType4 f = -76;
    MyUnionType g = 75;

    printResult(d | e); // @output -2
    printResult(d | f); // @output -4

    printResult(e | e); // @output -34
    printResult(e | f); // @output -2
    printResult(e | g); // @output -33

    printResult(f | f); // @output -76
    printResult(f | g); // @output -1
}

function printResult(int result) {
    io:println(result);
}
```
The above sample is also failing. Could be the same issue

**Comment by rdulmina** [comment]
> ```ballerina
> type MyType int;
> 
> type MyType2 int:Signed32|int:Unsigned16;
> 
> type MyType3 int:Unsigned32|int:Signed8;
> 
> type MyType4 byte|int:Signed8;
> 
> type MyUnionType MyType2|MyType4;
> 
> public function main() {
>     MyType2 d = 4344;
>     MyType3 e = -34;
>     MyType4 f = -76;
>     MyUnionType g = 75;
> 
>     printResult(d | e); // @output -2
>     printResult(d | f); // @output -4
> 
>     printResult(e | e); // @output -34
>     printResult(e | f); // @output -2
>     printResult(e | g); // @output -33
> 
>     printResult(f | f); // @output -76
>     printResult(f | g); // @output -1
> }
> 
> function printResult(int result) {
>     io:println(result);
> }
> ```
> 
> The above sample is also failing. Could be the same issue

@rpjayasekara this sample is still failing

**Comment by rdulmina** [comment]
> ```ballerina
> import ballerina/io;
> 
> type MyType2 int:Signed32|int:Unsigned16;
> 
> type MyType3 int:Unsigned32|int:Signed8;
> 
> type MyType4 byte|int:Signed8;
> 
> type MyUnionType MyType2|MyType4;
> 
> type MySingletonUnionType 1|2|3;
> 
> public function main() {
>     MyType2 d = 4344;
>     MyType3 e = -34;
>     MyType4 f = -76;
>     MyUnionType g = 75;
>     MySingletonUnionType h = 2;
> 
>     printResult(d | d); // @output 4344
>     printResult(d | g); // @output 4347
>     printResult(d | h); // @output 4346
>     printResult(d | e); // @output -2
>     printResult(d | f); // @output -4
> 
>     printResult(e | e); // @output -34
>     printResult(e | f); // @output -2
>     printResult(e | g); // @output -33
> 
>     printResult(f | f); // @output -76
>     printResult(f | g); // @output -1
> }
> 
> function printResult(int result) {
>     io:println(result);
> }
> ```
> 
> The above sample is also failing. Could be the same issue

@rpjayasekara this issue is still exists

**Comment by rdulmina** [comment]
```bal
type MyType int;

type MyType2 int:Signed32|int:Unsigned16;

type MyType3 int:Unsigned32|int:Signed8;

type MyType4 byte|int:Signed8;

type MyUnionType MyType2|MyType4;

function init() {
    MyType2 d = 4344;
    MyType3 e = -34;
    MyType4 f = -76;
    MyUnionType g = 75;

    printResult(d ^ e); // @output -4314
    printResult(d ^ f); // @output -4276

    printResult(e ^ e); // @output 0
    printResult(e ^ f); // @output 106
    printResult(e ^ g); // @output -107

    printResult(f ^ f); // @output 0
    printResult(f ^ g); // @output -1
}

function printResult(int result) {
    io:println(result);
}
```
this sample also fails

**Comment by lochana-chathura** [comment]
@rdulmina shall we close this issue since we have #35247 remaining.
