### ISSUE TITLE
Runtime library is missing in the Project API Bootstrap

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#32890]
**Description:**
Runtime library is missing in the Project API Bootstrap

**Affected Versions:**
Beta.3-SNAPSHOT

**Comment by LakshanSS** [comment]
I tested this with SLBeta3 RC4 pack.
This issue is fixed now.

Anyway still this fix is not added to `nightly` docker tag as `nightly` build of ballerina-distribution is failing due to trivy scan.
