### ISSUE TITLE
Query expression `check` not returning the error with custom errors

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#32905]
example case in [nballerina](https://github.com/ballerina-platform/nballerina/blob/6e3ea58f28a3e229169d966bee91c3b40873042b/compiler/compile.bal#L76
)
Issue exists only when trying to check the custom `CompileError` type. If changed to `error` this will work

**Comment by gimantha** [comment]
Here is a reproducible example

```ballerina
public type Semantic error<SemanticDiagnostic>;

public type SemanticDiagnostic record {|
    string message;
|};

public function main() {
    Semantic|int[] val = test();
}

public function test() returns int[]|Semantic {
    int[] val = from var _ in [1, 2, 3] select check foo();
    return val;
}

function foo() returns int|Semantic {
    return error Semantic("intersection must not be empty", message="GFGF");
}

```

**Comment by MaryamZi** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/33473 is probably the same.

**Comment by MaryamZi** [comment]
Let's use https://github.com/ballerina-platform/ballerina-lang/issues/33473 to track this.
