### ISSUE TITLE
Ballerina by Examples (examples not work)

### ISSUE THREAD

**Issue by vaassi** [ballerina-platform/ballerina-lang#32913]
**Description:**
I'll try to run examples from official site without any modifications, and get a lot of errors.

**Steps to reproduce:**
run examples from object section, f.e.
https://play.ballerina.io/?gist=d5a5da634b62fe74a5bda100297c8d39&file=object_methods.bal

**Affected Versions:**
latest

**OS, DB, other environment details and versions:**
windows 10, chrome

**Comment by MaryamZi** [comment]
The shared sample seems to be using 1.2 syntax whereas the playground is using Swan Lake beta1.

I'm afraid it may not be possible to run 1.2 samples on the Ballerina playground. But you could [download the latest 1.2 release -  1.2.19](https://ballerina.io/downloads).

Alternatively, you could switch to the latest beta release (beta2) of the new and improved Ballerina Swan Lake [1], [2].

The examples have also been revamped.
- [Learn by Example](https://ballerina.io/learn/by-example/introduction/) 
- [Reference by Example](https://ballerina.io/learn/by-example/)

[1] https://blog.ballerina.io/posts/announcing-the-first-preview-of-ballerina-swan-lake
[2] https://ballerina.io/downloads/swan-lake-release-notes

**Comment by anupama-pathirage** [comment]
Closing this issue as per the above comment. Please feel free to re-open if the above suggestions are not working.
