### ISSUE TITLE
Unary negation with int:MIN_VALUE does not overflow

### ISSUE THREAD

**Issue by rpjayasekara** [ballerina-platform/ballerina-lang#32922]
**Description:**
The following program have to give a panic as the positive of `int:MIN_VALUE` is an overflow scenario. But it gives this value `-9223372036854775808` the answer.
```
public function main() {
    int a = -9223372036854775808;
    int b = -a; // @panic integer overflow on unary negative
}
```
Spec section - https://ballerina.io/ballerina-spec/spec.html#section_6.22

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
This gives compile time error as expected. Hence we can close this.
