### ISSUE TITLE
Bad sad when applying Unary negation to a byte variable

### ISSUE THREAD

**Issue by rpjayasekara** [ballerina-platform/ballerina-lang#32926]
**Description:**
$title

**Steps to reproduce:**
```
public function main() {
    byte a = 1;
    int e = -a;
}

```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Duplicate of #31826
