### ISSUE TITLE
Unary minus and plus not working with user defined sub types of int/float

### ISSUE THREAD

**Issue by rpjayasekara** [ballerina-platform/ballerina-lang#32928]
**Description:**
Unary plus and minus not working with user defined sub types of int and float. Gives the `operator not defined` error.

**Steps to reproduce:**

```
type Ints -2|-1|0|1|2;
public function main() {
    Ints a = 1;
    Ints b = 2;
    Ints c = 0;

    io:println(-a); // @output -1
    io:println(-b); // @output -2
    io:println(-c); // @output 0
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rpjayasekara** [comment]
This also gives the same error. `operator '-' not defined for '(int:Signed8|int:Unsigned32)'`
```
public function main() {
    int:Signed8|int:Unsigned32 b = 12;
    io:println(-b); 
}
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33614, merged to master in https://github.com/ballerina-platform/ballerina-lang/pull/33977.
