### ISSUE TITLE
NumberFormatException when casting out of range float to decimal type

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#32938]
**Description:**
$title

**Steps to reproduce:**
```
public function main() {
    io:println(<decimal> 9.99E+6111f);
}
```

> [2021-09-28 10:19:18,306] SEVERE {b7a.log.crash} - Infinite or NaN 
> java.lang.NumberFormatException: Infinite or NaN
>         at java.base/java.math.BigDecimal.<init>(BigDecimal.java:923)
>         at io.ballerina.runtime.internal.values.DecimalValue.valueOf(DecimalValue.java:577)
>         at floating-point-literal.main(floating-point-literal.bal:35)
>         at $_init.$lambda$main$(.)
>         at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
>         at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
>         at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
>         at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MaryamZi** [comment]
@chiranSachintha, can you check this with the literal changes also? The behaviour for this should be the same as 

```ballerina
decimal d = 9.99E+6111f;
```

**Comment by MaryamZi** [comment]
> @chiranSachintha, can you check this with the literal changes also? The behaviour for this should be the same as
> 
> ```ballerina
> decimal d = 9.99E+6111f;
> ```
> 
> **Edit:** we need to verify this.

Depending on the conclusion for this, may be the same as https://github.com/ballerina-platform/ballerina-lang/issues/34997 if this needs to be handled at runtime.

**Comment by lasinicl** [comment]
Works as expected in 2201.1.0. Added tests via https://github.com/ballerina-platform/ballerina-lang/issues/32938. Hence closing the issue
