### ISSUE TITLE
Incorrect error message for undefined variable in mapping-constructor-expr

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#32965]
**Description:**
Consider the bellow sample where the `x` is undefined
```bal
function name() {
    io:println({x: x});
}
```
Gives an incorrect error message `a type compatible with mapping constructor expressions not found in type 'ballerina/io:0.6.0-beta.2:Printable'` where the expected error message is `undefined symbol 'x'`.

**Comment by MaryamZi** [comment]
Isn't this an extra error message? I seem to get the `undefined symbol 'x'` error also.

**Comment by rdulmina** [comment]
I see, I didn't notice that earlier. IMO `a type compatible with mapping constructor expressions not found in type 'ballerina/io:0.6.0-beta.2:Printable` is an unnecessary error message because `undefined symbol 'x'` is the actual issue here. Should we remove that extra error message WDYT?

**Comment by MaryamZi** [comment]
Yes, ideally we shouldn't log this error if any of the fields of the mapping constructor expression resulted in an error. 

Updating the labels since this is more of an improvement rather than a bug.
