### ISSUE TITLE
Additive expression with string and xml should return the xml value when the string value is empty string

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#32979]
**Description:**
$title.

The [spec](https://ballerina.io/ballerina-spec/spec.html#additive-expr) says 

> if one operand is an empty string and one is xml, then the result is the xml value operand

But right now, we seem to be creating a new sequence at runtime (desugared to both operands being XML IINM).

With https://github.com/ballerina-platform/ballerina-lang/issues/32978 this also leads to an incorrect result for exact equality checks at the moment.

**Comment by KavinduZoysa** [comment]
```ballerina
public function main() {
    xml a = xml `<foo/>`;
    string b = "";
    xml x1 = a + ""; 
    xml x2 = a + b; 
}
```
This works as expected. Therefore we can close this issue.
