### ISSUE TITLE
[Query] Warn observed when starting server on a VM

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3298]
Following Warn was observed when starting ballerina on a VM environment.

`[2017-09-08 12:37:31,779]  WARN  {io.netty.util.internal.MacAddressUtil} - Failed to find a usable hardware address from the network interfaces; using random bytes: 6a:d5:80:63:c5:1f:34:81`

Following are the network interfces of the server

```
ens3      Link encap:Ethernet  HWaddr fa:16:3e:94:03:64  
          inet addr:192.168.48.205  Bcast:192.168.51.255  Mask:255.255.252.0
          inet6 addr: fe80::f816:3eff:fe94:364/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1400  Metric:1
          RX packets:877039 errors:0 dropped:0 overruns:0 frame:0
          TX packets:363428 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:904701564 (904.7 MB)  TX bytes:134927134 (134.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:164 errors:0 dropped:0 overruns:0 frame:0
          TX packets:164 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:12104 (12.1 KB)  TX bytes:12104 (12.1 KB)
```
Is this warning gracefull?

**Comment by riyafa** [comment]
This not a valid any more as the server runs without warnings in EC2 instances without issues. If it is valid can you please be more specific about the VM you used?

**Comment by yasassri** [comment]
@riyafa As mentioned offline to you this was observed in Openstack. Also I believe we should know the exact reason for this WARN, may be this might not be an issue.

**Comment by riyafa** [comment]
I guess it is fixed in https://github.com/ballerina-platform/ballerina-lang/issues/1981
