### ISSUE TITLE
Allow triggering custom notifications with LS APIs

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#32989]
**Description:**
Allow sending custom client notifications after execting LS API requests/notifications.
For example, the diagram view has a requirement to send client notifications after didChange execution to update the text document or to fetch performance analysis.

**Comment by nadeeshaan** [comment]
Will be facilitated with #35057

**Comment by IMS94** [comment]
Closing this since https://github.com/ballerina-platform/ballerina-lang/issues/35057 is now resolved. You can now use the pub sub model available in LS to subscribe for project updates and then use the LS Client to send messages to the VSCode client side.
