### ISSUE TITLE
Annotation completions are not suggested in typeof/let expressions

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#32987]
**Description:**
$Subject

**Steps to reproduce:**
```
function testFunction() {
    var testVar = typeof @<cursor>
}
```
or
```
function hypot(float x) => let @<cursor>
```
we should get annotations suggested at the cursor. We get `display` and `tainted` annotations for `let expression` but for both cases we do not get user defined annotations as completions.

**Comment by IMS94** [comment]
This is same as #35223. 
```ballerina
function testFunction() {
    var testVar = typeof @<cursor>
}
```
Here, at the `<cursor>`, node is a simple name reference where the `@` is in the leading minutiae of the node.
