### ISSUE TITLE
Add test cases for local repository packages

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#33005]
**Description:**
Tests should be added to the ballerina distribution repo.

Scenarios identified: [Doc](https://docs.google.com/document/d/193dui-Wn-cEAL14iRgBwJ0WBujfrT8FNMy19jy8ZDQE/edit?usp=sharing)

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Closing since https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/test/java/io/ballerina/projects/test/resolution/packages/LocalRepoDependencyTest.java contains local repo tests
