### ISSUE TITLE
Object constructor expression is not identified as an expression

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33009]
**Description:**
Consider the following capture.

https://user-images.githubusercontent.com/1329674/135587461-18b312ee-6684-436b-9de1-f42f607192b0.mp4

In the above, the mapping constructor expression is identified by the parser and proceed while the `variable assignment is required` diagnostic is provided. This same behaviour cannot be observed for the object constructor expression, which seems a bit discontinued with the general user experience.

**Affected Versions:**
SwanLake-Beta4-SNAPSHOT at least

**Comment by lochana-chathura** [comment]
Closing as we have #34314 to track this.
