### ISSUE TITLE
Need a way to find what type of value a record/list/error constructor is creating

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#33014]
**Description:**
I think it would be really helpful to the user if we can find a way to help them identify what type of value a record/list/error constructor is creating. Maybe a tool tip and a way to go to definition.
```ballerina
function foo() returns SomeComplexType {
       .... stuff ....
       return { a: "abc", b, ... }; // I'd love to see what is the type of this record is
}
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2/ballerina-plugin-vscode/issues/134 to track this issue.
