### ISSUE TITLE
Wrong member types in union returned for XML attribute access expr

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#33018]
Consider the following:
```ballerina
function testXMLAttributeAccess() {
    xml x = xml `<root attr="attr-val"><a></a><b></b></root>`;
    string|error|() val = <1>x?.attr<2>;
}
```
The type for the above range gets returned correctly. But seems to have the same issue as #32569

**Comment by dulajdilshan** [comment]
The internal procedure in the compiler is as follows:
1. We identify this as a lax field-access type and assign `string` as the type.
2. check whether if the resultant type can be an `error`, and if so, create a union type with `error` and `string`.
3. check whether if the type is nill-able, and if so create a union type with the previously created union type and `nill`.

IMO, This is correct. @pubudu91 WDYT?

**Comment by pubudu91** [comment]
The issue is it creates the union as `(string|error)|()` where as it should be impossible to write a union like that. It should be `string|error|()`. Note that I used the parenthesis to depict a union. See the below screenshot as well.
<img width="909" alt="Screenshot 2021-11-24 at 18 17 21" src="https://user-images.githubusercontent.com/6260009/143241597-74e0697e-89c3-469f-a6d9-ad09bb20b868.png">

**Comment by KavinduZoysa** [comment]
In the compiler, it gives this union three different types. Please check below.
![Screenshot from 2023-03-02 09-33-13](https://user-images.githubusercontent.com/28332708/222328435-44437470-e422-49a4-a670-8a0da9f44e8f.png)
