### ISSUE TITLE
[LS] Sorting in error constructor context is not accurate

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33027]
**Description:**
Consider the following scenario

```ballerina
type ErrorDetail1 record {|
    string cause;
    int errorCode;
|};

type myErr1 error<map<anydata>>;

type myErr2 error<map<anydata>>;

type myErr3 error<ErrorDetail1>;

type myStr string;


public function main() {
    string msg = "message";
    int code = 10;
    myErr3 myerr = error(<cursor>)
}
```
Get the completion list as follows. The completion list should be sorted based on assignability.
![1](https://user-images.githubusercontent.com/35211477/135802034-21bd6864-9123-481c-ae0f-5bc0caa82157.png)
![2](https://user-images.githubusercontent.com/35211477/135802039-c148de9e-a4a4-49a5-9085-5cfba5c30027.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by malinthar** [comment]
Sub task of #32878

**Comment by IMS94** [comment]
Let's fix the FunctionCallExpressionTypeFinder along with this to use Types API
