### ISSUE TITLE
Contradicting diagnostics are provided for unary `+` and `-` based expressions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33026]
**Description:**
Consider the following source captures,

<img width="467" alt="Screenshot 2021-10-04 at 10 43 27" src="https://user-images.githubusercontent.com/1329674/135798365-9a39b682-e824-497d-912e-bf8c61a5975a.png">
<img width="467" alt="Screenshot 2021-10-04 at 10 48 06" src="https://user-images.githubusercontent.com/1329674/135798390-48456f7a-02a3-4801-876b-44fca9f10645.png">

`BCE2008` seems to be because of the parser's resolution strategy. Other than that, the remaining diagnostics are contradicting.

Following shows that the bit inverter works in the expected manner which suggests the `variable assignment required` diagnostic and the `invalid statement` diagnostic.

<img width="467" alt="Screenshot 2021-10-04 at 11 10 21" src="https://user-images.githubusercontent.com/1329674/135799850-641ab3aa-7dbe-4c0a-8fab-66ca7b5368c4.png">

**Affected Versions:**
SwanLake Beta3-SNAPSHOT at least

**Comment by lochana-chathura** [comment]
Related issue: #30020
