### ISSUE TITLE
Provide a way to disable runtime warnings

### ISSUE THREAD

**Issue by Mirage20** [ballerina-platform/ballerina-lang#33033]
**Description:**
There are warnings like `unused configuration value` which get printed at the runtime. This is good as we can see if there are any configuration values that are not used or figure out any typos. 

**Describe your problem(s)**

1. Since this has a specific format, it will be difficult to capture this if the deployment system uses a structured logging format. 
2. Adding configuration to an upcoming feature will result in an unused warning, which can cause unnecessary alerts.

**Describe your solution(s)**

Provide a way to disable the runtime warnings.

**Comment by HindujaB** [comment]
@manuranga 
The warnings are generated only when there is a toml value provided and a matching configurable variable is not 
 found. So, the warnings will not be generated if there's a configurable variable regardless of the default value provided or not.

**Comment by sameerajayasoma** [comment]
We decided to make all unused config keys in the toml file errors. This is what the spec says.
