### ISSUE TITLE
Bal Build Command does not show error message with invalid options

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#33052]
**Description:**
bal build --invalidOption

package build without any errors.

**Expected Behaviour:**
CLI should provide an error message with an invalid option and the build should not continue.
**Affected Versions:**
beta3 rc5

**Comment by azinneera** [comment]
This is fixed in SL GA. The current output is as follows:
```
$ bal build --invalidOption
ballerina: unknown option: '--invalidOption'
Run 'bal help' for usage.
```
