### ISSUE TITLE
`Document This` codeaction for class is suggested within object method body

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33072]
**Description:**
Consider the source:
```ballerina
class Student {

    public function getName() returns string {
        
        return "name";
    }
}
```
Put the cursor on the `return` statement and you will see the `Document This` codeaction, Click on it, and the documentation will be added to the class `Student`.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 3 RC5

**Comment by IMS94** [comment]
@nadeeshaan I can still the `Document This` code action on the return statement on 2201.0.3 RC1. Shall we reopen this?

**Comment by nadeeshaan** [comment]
> @nadeeshaan I can still the `Document This` code action on the return statement on 2201.0.3 RC1. Shall we reopen this?

We actually merged this one for the master. Should be available with a latest minor release though
