### ISSUE TITLE
Testarina error message formatting is broken

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33106]
<img width="604" alt="Screenshot 2021-10-06 at 11 11 42 PM" src="https://user-images.githubusercontent.com/1686124/136256016-aaee9b32-58da-4b08-ade8-8342c12a624a.png">

**Comment by Ibaqu** [comment]
Formatting works under the same conditions however the text wrapping above can be seen when resizing the window of the terminal after the logs have been printed.
