### ISSUE TITLE
Update resource snippet

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#33124]
**Description:**
Update resource snippet according to https://ballerina.io/spec/lang/2021R1/#resources. Need to incorporate method name, resource path, etc.

- Current
```
    resource function name . () {
        
    }
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Here we have provided the minimalistic snippet without introducing immediate semantic errors where the resource path being `.`

**Comment by malinthar** [comment]
Closing as this is fixed in in the latest version
![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/b15103f6-677e-4ab5-8c65-26dc2482f3c1)
