### ISSUE TITLE
[LS] Separate top level node and documentable node to separate APIs

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33153]
**Description:**
When finding node based codeactions, we rely on `NodeBasedPositionDetails` which provides access to `matchedTopLevelNode()`. This is used to show the `Document This` (documentation) code action. However, as per syntax tree, top level nodes are the direct children of root node. As of now, the `matchedTopLevelNode()` method returns the closest documentable node. 

In cases like object methods, closest documentable node is different from the top level nodes. Therefore, we should separate out APIs for detecting top level nodes and documentable nodes.

**Describe your task(s)**
See description

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/33072

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
