### ISSUE TITLE
`range-expr` is not `isolated`

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#33163]
**Description:**
According to the spec [1] 
```
A range-expr is always isolated.
```
But it's not ATM.
[1] https://ballerina.io/spec/lang/master/#section_6.26

**Steps to reproduce:**
```ballerina
public function main() {
    object {
        *object:Iterable;
        public function iterator() returns object {
            public function next() returns (record {|int value;|}?);
        };
    } range = 1...10;

    io:println(<any>range is isolated object {}); // prints false, but should be true
}
```

**Affected Versions:**
slbeta3

**Comment by MaryamZi** [comment]
I believe the section of the spec "A range-expr is always isolated." is to cover that a range expression is always an isolated expression. 

The main test for this would be something like

```ballerina
isolated int i = 1;

function fn() returns object {} {
    lock {
        return i ... i + 1;
    }
}
``` 

Note: this doesn't work atm.

I do think `range is isolated object {}` and `range is isolated object {isolated function next() returns int;}` should also evaluate to true. AFAIK, the spec doesn't explicitly mention this atm.

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33533.
