### ISSUE TITLE
Spec difference in lang.int constants

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33170]
**Description:**
Please note the type not specified for lang.int constants in https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/master/lang/lib/int.bal 

Implementaion in https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.int/src/main/ballerina/int.bal#L57

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
Might be related to https://github.com/ballerina-platform/ballerina-lang/issues/33168

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
We should be able to update all the constants except MIN_VALUE. We need to fix https://github.com/ballerina-platform/ballerina-lang/issues/28334 to write `MIN_VALUE` without the type.

**Comment by MaryamZi** [comment]
Removing the bug label since the effect is the same with or without the type.
