### ISSUE TITLE
[VS Code] Some suggestions doesn't work inside ternary conditional-expr

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33199]
**Description:**

https://user-images.githubusercontent.com/15815199/137093772-54a32124-7334-4e07-ad1e-13106bb8a2b0.mov

**Steps to reproduce:**

**Affected Versions:**
SL Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gayalkuruppu** [comment]
related: #33791
