### ISSUE TITLE
Move ballerina/observe and ballerinai/observe packages to separate repositories

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-lang#33195]
**Description:**
For puushing the ballerina/observe package to central, we need to move the following repositories to separate repos.

- [x] `ballerina/observe` (New Repo: `module-ballerina-observe`)
  - [x] Move the package
  - [x] Add to ballerina distribution
  - [x] Update Package.md accordingly
  - [x] Add workflows for Building, PR, Release (including push to Ballerina Central)
  - [x] Update all dependencies using Observability in their builds / tests
  - [x] Remove from ballerina-lang
  - [x] Integrate into full multi-repo build of Ballerina
- [x] `ballerinai/observe` (New Repo: `module-ballerinai-observe`)
  - [x] Move the package
  - [x] Add to ballerina distribution
  - [x] Add workflows for Building, PR, Release (without push to Ballerina Central)
  - [x] Update all dependencies using Observability in their builds / tests
  - [x] Remove from ballerina-lang
  - [x] Move observability integration tests to new repo
  - [x] Integrate into full multi-repo build of Ballerina
- [x] Update gradle build scripts with the module dependencies
  - [x] module-ballerina-log
  - [x] ballerina-distribution

**Comment by LakshanKarunathilake** [comment]
Feature is de-prioritized for the moment, I will update here once everything is ready

**Comment by nadundesilva** [comment]
We need to figure out what we will be doing to handle the conflict in module names (`observe`) between the two modules `module-ballerina-observe` and `module-ballerinai-observe`.

The ballerina release pipelines work by using only the module name in the version property in `gradle.properties` and therefore conflicts each other.

**Comment by LakshanKarunathilake** [comment]
I tested the changes with the latest pack **2201.0.0 (Swan Lake) RC1**. It seems the changes are working accordingly. I compiled and tested all the BBEs therefore closing the issue
