### ISSUE TITLE
Add completion support for service typing

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33191]
**Description:**
$title

**Comment by shafreenAnfar** [comment]
We (@nadeeshaan @IMS94 @Bhashinee @shafreenAnfar) had a chat on this. It is also related to the issue https://github.com/ballerina-platform/ballerina-standard-library/issues/2034. As per the discussion we had, the best possible experience we could provide to the user is something as the below.

1. When the user type `service` at the top level, LS core will list down the service snippets for all the relevant standard libraries. For instance, for HTTP it would look like the below,

```ballerina
service / on new http:Listener(9090) {
    
}
```
2. Then from each standard library extensions we provide code actions to generate relevant resource templates. This is similar to what we did for `websocket`.

Do add If I have missed out anything.
