### ISSUE TITLE
Unreachability check within conditional-expr

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33202]
**Description:**
With https://github.com/ballerina-platform/ballerina-lang/pull/31797 unreachability check is introduced for the if-else-stmt.

```ballerina
function printTrue() {
    if true {
        io:println(1);
    } else {
        io:println(-1); // throw a compiler error saying code unreachable
    }
}
```

Should we support the same for Conditional expressions?

```ballerina
_ = true ? io:println(1) : io:println(-1);
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Need to verify this based on https://github.com/ballerina-platform/ballerina-spec/issues/887#issuecomment-991825589 and the last sentence in the [spec](https://ballerina.io/spec/lang/master/#section_7.4.3).
