### ISSUE TITLE
Looking up langlib function for a parameter node returns the langlib function without contextual type information

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33209]
**Description:**
Consider the following scenario:
```ballerina
type Pet record {|
    string name;
    int 'type;
|};

public function main() {
    Pet[] pets = [];
    pets.<cursor>;
}
```
At `<cursor>` when we get suggestions for langlib methods, we see `push(Pet... vals)`. Internally we lookup for the langlibs of the `pets` here. Now consider this:

```ballerina
public function main() {
    Pet[] pets = [];
    pets.push({<cursor>});
}
```
here at `<cursor>` when we try to determine the type of the mapping constructor using the function symbol what we get is the langlib function `push(any[]|error... vals)`. We use `semanticModel.symbol(mappingConstructorExpression.parent().parent())` to obtain the symbol.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 4 Snapshot

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/30928

**Comment by pubudu91** [comment]
The above case seems to be handled from LS side in GA as it correctly gives the completions for the record fields for the above case. The issue in this is that we give a function symbol with type params bound to a particular type for function symbols you get through the `langLibMethods()` in a `TypeSymbol`. When directly looking up the function using `symbol()`, you get the symbol for the function defined in the lang lib, with type params unbound. So the question is whether we should be returning a type param bound function symbol for this case as well. 🤔
