### ISSUE TITLE
[Parser] In a chained conditional-expr var ref used as the false-exp parsed incorrectly

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33215]
**Description:**
```ballerina
    int n = 10;
    int res = 5 == 5 ? 10 < 5 ? 100 : n : -1; // getting undefined module 'n'
    _ = 5 == 5 ? (10 < 5 ? 100 : n) : -1; //works
```

**Steps to reproduce:**

**Affected Versions:**
SL Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Related to #33270

**Comment by lochana-chathura** [comment]
We need to split at the right-most qualified identifier.
