### ISSUE TITLE
Variable type narrowing in the form x == E1, does not get narrowed

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33217]
**Description:**
```ballerina
function errorFunction(int x) {
    _ = x == -1 ? 1 : (x == -1 ? 2 : 3); // @error at falsity expr x should be narrowed as not -1
```
From the spec https://ballerina.io/spec/lang/2021R1/#conditional_variable_type_narrowing

> If E has the form x == E1 or E1 == x where the static type of E1 is an expression whose static type is a singleton simple type T1, then
the narrowed type for x implied by truth of E is the intersection of Tx and T1
the narrowed type for x implied by falsity of E is Tx −ro T1

**Steps to reproduce:**

**Affected Versions:**
SL Beta 3 

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Related issue #30598. Same reason as described above.

**Comment by lochana-chathura** [comment]
When fixing this issue we need to clean up the comments added in PR #34964 for the following files.
```
TernaryExpressionTest.java
ternary_expr_type_narrow.bal
TypeGuardTest.java
test_type_guard_type_narrow_1.bal
test_type_guard_type_narrow_2.bal
```
