### ISSUE TITLE
Erroneous type checking while calling lang.value functions on conditional-expr 

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33213]
**Description:**
```ballerina
string res = (5 == 5 ? 10 : ()).toBalString(); // incompatible types: expected 'int', found '()'
```

Getting unassignable error at type checker trying to check assignability between false-exp type in conditional-expr and the contextually expected type which is taken as `int` in this case.  

Note the different types of the true-exp and the false-exp.

```ballerina
io:println((x is int ? 1 : 2).toBalString()); //works
```

**Steps to reproduce:**

**Affected Versions:**
SL Beta 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SandaruJayawardana** [comment]
Related issue with elvis-expr.
```ballerina
    string? x = ();
    string y = (x?:()).toBalString(); // incompatible types: expected 'string', found '()'
```
