### ISSUE TITLE
Create function code action returns an invalid function

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33228]
**Description:**
Consider the following scenario
```ballerina
import Test.module1;

module1:Type1 myvar;

public function func1() {
    myFunction(myvar)
}
```

The result of the create function code action is as follows.
```ballerina
function myFunction(string myvar1) {
    
}
```
The parameter should be of module1:Type1 type. 

This is probably due to https://github.com/ballerina-platform/ballerina-lang/issues/26284

**Comment by nadeeshaan** [comment]
This issue has been fixed in the latest master after merging #26284 . Hence closing the issue.
