### ISSUE TITLE
Context type is not correctly identified for langlib methods

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#33229]
**Description:**

Consider the langlib method `map`, 
```
int[] nums = [1, 2, 3];
int[] evenNums = nums.map(<cursor>)
```
Currently context type at cursor is identified as `ARRAY`. 

This should be fixed in `ContextTypeResolver` to skip the first param in the case of langlib methods.

**Comment by IMS94** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/37872
