### ISSUE TITLE
Semicolon is not needed for do clause

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#33227]
**Description:**
$subject

**Steps to reproduce:**
```
function ignore(error? x) {

}

public function main() {
    int[] ia = [1, 2, 3];
    int[] tmp = [];
    error? x = from var i in ia
        do {
            tmp.push(i);
        } // error : missing semicolon token
    ignore(x);
}
```

**Affected Versions:**
beta3

**Comment by rdulmina** [comment]
Semicolon of var declaration statement is the one missing here
```
local-init-var-decl-stmt :=
   [annots] [final] typed-binding-pattern = action-or-expr ;
```
it should be action-or-expr followed by a semicolon. So the error is correct.

**Comment by gimantha** [comment]
> My example is not correct. @rdulmina please consider this.
> 
> ```
> public function main() returns error? {
>     int[] ia = [1, 2, 3];
>     int[] tmp = [];
>     check from int i in ia
>         do {
>             tmp.push(i);
>         } // error : missing semicolon token
> }
> ```
> 
> Is this expected?

Checking expression can only contain an expression right? query action is not an expression. So we need to disallow this right? @rdulmina

**Comment by rdulmina** [comment]
Yes but in this context it's checking-action right? 
> checking-action := checking-keyword action

So `action-stmt --> checking-action ;`
