### ISSUE TITLE
Invalid compilation error for valid match guard

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33238]
**Description:**
Works on slbeta3, but results in an error on the current master. Debugged a bit and seems like it could be related to the changes done to fix https://github.com/ballerina-platform/ballerina-lang/issues/31782.

**Steps to reproduce:**
```ballerina
enum Department {
    FINANCE,
    LEGAL,
    ENGINEERING
}

type Employee record {|
    string name;
    Department department;
|};

public function main() {
    Employee & readonly employee = {name: "Jo", department: LEGAL};

    match employee {
        {department: FINANCE} => {
            
        }
        {deparment: LEGAL} if !update(employee) => { // error: incompatible types: expected '(Employee & readonly)', found 'other'

        }
    }
}

isolated function update(Employee & readonly employee) returns boolean => true;

```

**Affected Versions:**
slbeta4-SNAPSHOT

**Comment by gimantha** [comment]
@MaryamZi `employee` can never be matched to `{deparment : LEGAL}` right? In that case shouldn't it give an error (not the error currently it gives, but with proper types) ? If that's not the case, https://github.com/ballerina-platform/ballerina-lang/pull/33241 will fix the issue

**Comment by MaryamZi** [comment]
Sorry, my bad! :woman_facepalming: That was a typo. Error should be "pattern will not be matched" right?

**Comment by gimantha** [comment]
Issue is fixed as the original fix done for https://github.com/ballerina-platform/ballerina-lang/issues/31782 is reverted. Keeping open to add tests
