### ISSUE TITLE
Ambiguity between ternary expression, Elvis operator and nillable type descriptors

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33259]
Consider the issue here: https://github.com/ballerina-platform/ballerina-lang/issues/32367

Although this has been fixed with a temp solution, This has to be fixed properly for all the cases, where there can be nillable types, ternary expression or elvis operators

**Comment by lochana-chathura** [comment]
TODO:
https://github.com/ballerina-platform/ballerina-lang/blob/04f2c2ea37880970f26bb33ce15c10d7af1f4a8e/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java#L5723-L5724
