### ISSUE TITLE
Ordering of the suggestions incorrect for module completions

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#33271]
**Description:**
Refer to the image below. 

For ex: when user types `io` can we have the matching items which has the exact pattern of `io` first. i.e. interchange the below two suggestions

<img width="673" alt="image" src="https://user-images.githubusercontent.com/16300038/137640167-4810384f-5711-4a52-b9a3-67dfc63c023c.png">

**Comment by nadeeshaan** [comment]
In this scenario, we have to use the module's prefix/ alias as the filter text. It seems that the VSCode client de-prioritise the `ballerina/io` since it has the `/` in the text.
