### ISSUE TITLE
Improve anon function expression completion item sorting in `FunctionTypeDescriptorNodeContext`

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#33285]
**Description:**

Consider :
<img width="518" alt="Screenshot 2021-10-18 at 12 08 12" src="https://user-images.githubusercontent.com/27485094/137681416-52951588-9047-449f-89ee-3b14918c7a46.png">

At cursor, completion items should be sorted to match type desc context.

**Related Issues (optional):**

Relates to #32879

**Comment by nadeeshaan** [comment]
This issue has been already fixed in the master. Check whether you need to scroll the list.

<img width="554" alt="Screenshot 2021-10-21 at 15 44 09" src="https://user-images.githubusercontent.com/1329674/138258103-2867813b-7d2c-4af9-acc7-eaabcac185f5.png">

Hence closing the issue.
