### ISSUE TITLE
Ballerina Shell requirements related to NodeParser

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#33287]
**Description:**

Consider following two cases.

1.  `"abc->method(arg1)"`;

if we parse this as an expression, expected node is `RemoteMethodCallActionNode`.

In the current shell implementation, similar cases handled by parsing  as a statement as shown below.

`node = ((AssignmentStatementNode) NodeParser.parseStatements("a = " + source ) .get(0)).expression();`

2. "`@strand { thread:"any" } worker w1 { }`"

if we parse this as a statement, expected node is `NamedWorkerDeclarationNode`.

Need a method to identify above two nodes.

**Comment by lochana-chathura** [comment]
Updating the issue.

- For scenario 1 and all other expressions, we can now use `parseActionOrExpression()`.
- For scenario 2 and all other statements, we can now use `parseFunctionBodyBlock()`
