### ISSUE TITLE
Improve anon function expression sorting to increase the priority of `function` keyword

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#33291]
**Description:**

Consider,
<img width="799" alt="Screenshot 2021-10-18 at 18 56 23" src="https://user-images.githubusercontent.com/27485094/137740485-0878228d-acd7-4ca1-8c79-0bae92ddd406.png">

At cursor position, change sorting priority as
1. Variables assignable 
2. Anon function snippet
3. **Function keyword**
4. Other symbols follow the default sorting order

**Related Issues (optional):**
Relates to #32879

**Comment by nadeeshaan** [comment]
Suggestion: What if we use the following order
1. Variable which have the type of function
2. functions
3. function keyword
4. anon function snippet
5. others

**Comment by TharushiJay** [comment]
> Suggestion: What if we use the following order
> 
> 1. Variable which have the type of function
> 2. functions
> 3. function keyword
> 4. anon function snippet
> 5. others

+1 to the suggestion.
