### ISSUE TITLE
Compiler does not support for variable named `json

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#33293]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
int 'json =  1;
```
Output:
`ERROR [test.bal:(1:5,1:10)] redeclared builtin symbol 'json'`

**Related Issues :**
#30268

**Affected Versions:**
Swan Lake Beta 3

**Comment by MaryamZi** [comment]
Let's use https://github.com/ballerina-platform/ballerina-lang/issues/34950 to track this.
