### ISSUE TITLE
Deriving the type for a table constructor doesn't correctly handle members having fields of the same name but of different types

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33297]
**Description:**
The [spec](https://ballerina.io/ballerina-spec/spec.html#table-constructor-expr) says
> If there is no contextually expected type, then the member type of the inherent type is derived from the the static type of the expressions for the members: the member type will be the smallest record type that is a supertype of the static types of all the expressions in the row-list.

**Steps to reproduce:**
Consider

```ballerina
public function main() {
    var v1 = table [
        {a: 1},
        {a: "str", b: 2}
    ];
}
```

Shouldn't the type be inferred as `table<record {|int|string a; int b?;|}>`?

Currently results in a compilation error.

```cmd
cannot infer the member type from table constructor. field 'a' type is ambiguous
```

**Affected Versions:**
slbeta3

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/33296

**Comment by lochana-chathura** [comment]
> Same for
> 
> ```ballerina
> function init() {
>     record {string a; int b?;} m = {a: "str", b: 2};
>     string s1 = "a";
>     string s2 = "b";
> 
>     var v1 = table [
>         {a: 1},
>         {...m},
>         {[s1]: true, c: 2, [s2]: false}
>     ];
>     table<record {int|string|boolean a?; int|string b?; anydata c?;}> t1 = v1;
> }
> ```

@MaryamZi just to be clear, 
here for v1, inferred type should be `table<record {| (int|string) a?; int b?;  int c?; boolean...; |}>` right?

**Comment by MaryamZi** [comment]
@lochana-chathura it should be

```ballerina
table<record {int|string|boolean a?; int|boolean b?; anydata c?;}>
```

right?

- `a` and `b` can be `boolean` because of the `boolean` fields with computed keys in the third member
- `c` can be `anydata` because `m` is open by `anydata`
- rest descriptor has to be anydata (or the record has to be an inclusive one) also because `m` is open

The original type I used in https://github.com/ballerina-platform/ballerina-lang/issues/33297#issuecomment-946764504 is wrong.

**Comment by lochana-chathura** [comment]
@MaryamZi Sorry I missed the open record part.
If we consider inferred record types for each `mapping-constructor-expr`, that would be,

1. `record {| int a; |}`
2. `record {| string a; int b?; anydata...; |}`
3. `record {| int c; boolean...; |}` 

Note that, [3] does not have `boolean a;` and `boolean b;` fields as it is considered as a rest-descriptor as per the below spec interpretation.
> If there are fields specified as a computed-name-field, then there will also be a record-rest-descriptor T..., where T is the union of the broad types of the value-expr in all such fields. 

Now from,

> the member type will be the smallest record type that is a supertype of the static types of all the expressions in the row-list.

Shouldn't the smallest supertype be,
`record {| int|string a?; int b?; int c? ; (boolean|anydata)...; |}`
=> `record {| int|string a?; int b?; int c? ; anydata...; |}` ?

**Comment by MaryamZi** [comment]
Since the computed keys may be `a` and/or `c` in 3., `a` and/or `c` may be `boolean` right?

Similarly, since 2. can have a field `c`, `c` can also be `anydata`.

So shouldn't it be

```ballerina
table<record {| int|string|boolean a?; int|boolean b?; anydata c? ; anydata...; |}>
```

For the static types
> 
> 1. `record {| int a; |}`
> 2. `record {| string a; int b?; anydata...; |}`
> 3. `record {| int c; boolean...; |}`

`record {| int|string a?; int b?; int c? ; anydata...; |}` cannot be the smallest supertype, because 2. and 3. are not subypes of it.

2. is not a subtype because it may have an `anydata` `c` field
3. is not a subtype because it may have `boolean` `a` and/or `b` fields

**Comment by lochana-chathura** [comment]
You are right. Thank you!.
