### ISSUE TITLE
[Refactor] Remove duplicated positional arg type finding logic inside LS code base

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#33308]
**Description:**
The logic to find type of a positional argument given the positional arg node has been duplicated in several places including `ContextTypeResolver` (2 places) and `FunctionReturnTypeFinder`. Need to make them consistent and remove duplicated logic.

**Describe your task(s)**
See description

**Related Issues (optional):**
#33203
#33189

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
