### ISSUE TITLE
CCE when using a binary expression as the index in a member access expression

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#33301]
**Description:**
$subject

**Steps to reproduce:**
```
public type Rec record {|
    [string, string...] names;
|};

public function main() {
    Rec rec = { names: ["a", "b", "c"]};
    string s = rec.names[rec.names.length() - 1];
}

```
**Affected Versions:**
swan-lake beta3

**Comment by MaryamZi** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/34072. Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34184 for 2201.0.0.
