### ISSUE TITLE
[HTTP] Cannot invoke services when Transfer encoding has multiple values

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3331]
**Steps**

1. Send the following request to a ballerina service. (Chunked, gzipped message)
Header :
`Transfer-Encoding: gzip, chunked`

**Issue:** Ballerina server will give the following error
`no matching service found for path : /bad-request`

**Comment by riyafa** [comment]
There's no such error in the current ballerina server
