### ISSUE TITLE
Provide a method of getting the size of a file

### ISSUE THREAD

**Issue by uvindra** [ballerina-platform/ballerina-lang#3334]
Currently Ballerina does not have a way of getting the size of a given file. Due to this when reading the file we need to make a guess as to the size of bytes that needs to be allocated in order to read the file

```go
files:open(target, "r");
var content, n = files:read(target, 100000);
```
This is not very efficient and it can sometimes be necessary to know the exact size of the file. It would be ideal if we could get the size of the file and be able to allocate the exact size of bytes to be read.

This ability to get the size of a file is available in Go[1], so a similar api can be provided in Ballerina

[1] https://stackoverflow.com/questions/17133590/how-to-get-file-length-in-go

**Comment by pubudu91** [comment]
This will become possible once the new I/O design is completed.

**Comment by wggihan** [comment]
We have moved existing file related functionalities to internal package. We will provide a proper file/path API in the near future after analyzing it further. For the moment I'm closing this issue.
