### ISSUE TITLE
Compilation error not shown when using conditional expressions within logical expressions

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#33358]
**Description:**
When attempting to replace an expression within a logical expression with a conditional expression, the compiler does not give a compilation error, rather gives the output of the conditional expression. However when written within parenthesis the compilation error is shown.

**Steps to reproduce:**
```
public function main() {
    string a = "text";
    io:println(true && a == "text"? 2 : 1); 
    io:println(false && a == "text"? 2 : 1); 
    io:println(true || a == "text"? 2 : 1); 
    io:println(false || a == "text"? 2 : 1); 
}
```

**Comment by lochana-chathura** [comment]
The output for the above seems to be correct. 
```
2
1
2
2 
```

@suleka96 according to the operator precedence table in the spec, 
`x && y` and `x || y` have higher precedence over `x ? y : z`.

Therefore,
`true && a == "text"? 2 : 1` means `(true && a == "text")? 2 : 1` not `true && (a == "text"? 2 : 1)`
`true || a == "text"? 2 : 1` means `(true || a == "text")? 2 : 1`

**Comment by MaryamZi** [comment]
Closing this issue since the behaviour is correct/as expected.
