### ISSUE TITLE
The inherent type for `any arr = [1];` should be `(any|error)[]`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#33377]
**Description:**
$subject.

For `any arr = [1];` currently the inherent type is `any[]` But it should be `(any|error)[]`.
i.e. Applicable contextually expected type here should be  `(any|error)[]` not `any[]`, since `(any|error)[]`  belongs to `any`.

**Spec-Issue:**
ballerina-platform/ballerina-spec#969

**Comment by MaryamZi** [comment]
Similarly for `any _ = {}`, the type should be `map<any|error>`,
