### ISSUE TITLE
No error when binding patterns bind optional fields of a record 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33389]
**Description:**
$title, see https://github.com/ballerina-platform/ballerina-spec/issues/445.

Additionally the type used is also incorrect.

Need to follow up on the spec discussion before we fix this (to decide if we are disallowing this or making the type `T?`).

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Employee record {
    string name;
    int id;
    Employee lead?;
};

public function main() {
    Employee e = {name: "Jo", id: 1234};

    string eName;
    int eId;
    Employee eLead;
    {name: eName, id: eId, lead: eLead} = e; // Allowed!
    io:println(eLead is Employee); // false
    io:println(<any> eLead is ()); // true

    var {name, id, lead} = e;

    Employee ld = lead; // Allowed!
    io:println(ld is Employee); // false
    io:println(<any> ld is ()); // true
}
```

**Affected Versions:**
slbeta3

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34359
