### ISSUE TITLE
Support for cross platform path seperators for Files is missing

### ISSUE THREAD

**Issue by uvindra** [ballerina-platform/ballerina-lang#3338]
When defining the path of a File in Ballerina a complete string is used to represent the path as below,

```go
files:File target = {path:"/tmp/result.txt"};
```
This works on Unix based OS's but will not work on Windows which natively uses '\\' as the path separator.

Therefore a cross platform path separator is required to correctly define file paths

**Comment by SupunS** [comment]
Tested on v0.95.1 and works fine. Below is a sample:
```ballerina
package foo.bar;

import ballerina.file;
import ballerina.io;

function main (string[] args) {
    file:File source = {path:"C:\\Users\\Supun\\Desktop\\sample.txt"};

    io:ByteChannel byteChannel = source.openChannel("r");
    var blb, cnt = byteChannel.readBytes(1000);
    println(cnt);

    string s = blb.toString("UTF-8");
    println(s);
}
```

**Comment by pubudu91** [comment]
@uvindra Support for that is not there.. I guess we'll have to provide something similar to `File.separator` in Java.. Can you re-open this issue?

**Comment by SupunS** [comment]
I have some concerns over that. A path similar to "/foo/bar" will not be meaningful in a windows environment, since the absolute path in windows starts with something like "C:\\foo\bar". So in windows, if someone says the path as "/foo/bar" what should be the behavior?

Other concern is that if someone uses File.separator and construct a file path, (say, `string path = "foo" + File.separator + "bar"`), then in windows environment this will result "foo\bar" where `\b` will be treated as an escape character.. Even in java, this is the behavior.

**Comment by uvindra** [comment]
Thats the wrong argument, the point is there is a reason for File.separator in Java. It overcomes the need to write platform specific code.

Please consider the example of getting the value of a path from an environment variable such as CARBON_HOME and then using that to do file I/O. On Windows the variable could be `C:\some-path` on Linux it could be `/usr/local/some-path`. After reading the CARBON_HOME you need to append the relative path of the location of the file that you need to read, such as `repository/deployment`. How do you do this in a platform independent manner so that the code runs correctly every where?

**Comment by SupunS** [comment]
I see your point. +1 to have a way to get a path in a platform independent manner.

I still thinks `File.separator` will break in the case-2 I mentioned earlier (using it with string to construct a file path). May be we can have a native function to which we can pass the segments of the file path and get the complete file-path.

**Comment by hemikak** [comment]
With 0.975.0 version you can use the 'resolve' function to create your file path platform independently.
Example:
```ballerina
import ballerina/internal;

internal:Path myPath = new("/tmp");
internal:Path myResults = myPath.resolve("my-results", "result.txt");
```

Hence closing
