### ISSUE TITLE
Error in template string with unicode

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#33390]
**Description:**
Related to #550

**Steps to reproduce:**
```
public function main() {
    string s = string`"\u{D800}"`; // error:invalid unicode '\u{D800}'
    io:println(s);
}
```
This should not do any precessing.

**Affected Versions:**
swan-lake beta3

**Comment by gimantha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34555
