### ISSUE TITLE
`decimal:fromString()` should not accept HexFloatingPointLiterals as the argument

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#33406]
**Description:**
Consider the following program,

```ballerina
public function main() {
    decimal|error a = decimal:fromString("0x12a.a");
    io:println(a);
}
```
Output is,
```
298.6250
```
Spec [says](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/decimal.bal),
```
argument must follow the syntax of DecimalFloatingPointNumber as defined by the Ballerina specification
# with the following modifications
# - the DecimalFloatingPointLiteral may have a leading `+` or `-` sign
# - a FloatingPointTypeSuffix is not allowed
# This is the inverse of `value:toString` applied to an `decimal`
```
According to the spec, argument should not allow HexFloatingPointLiterals.
 

**Affected Versions:**
SL Beta 3

**Related Issues (optional):**

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33460
