### ISSUE TITLE
Current lang.error detail() function return type is different from  the spec.

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33402]
Current implementation has the following signature

`public isolated function detail(error<DetailType> e) returns DetailType = external`

But Spec(https://ballerina.io/ballerina-spec/spec.html#lang.error) says it should be

`public isolated function detail(error<DetailType> e) returns readonly & DetailType = external;`

Affect version: slbeta3

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33542
