### ISSUE TITLE
Stream `next` argument name spec deviation

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#33410]
**Description:**
```Ballerina
public isolated function next(stream<Type,CompletionType> stm) returns record {|
```

```Ballerina
public isolated function next(stream<Type,CompletionType> **strm**) returns record {|
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33460
