### ISSUE TITLE
`xml:setChildren(Element elem, xml|string children)` causes crash in runtime

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#33419]
**Description:**
$title, however this does not crash when we pass an `xml` to the `children` parameter only happens when passing a string to it.

**Steps to reproduce:**
```

public function main() {
    string url = "https://ballerina.io";
    xml:Element b = xml `<ele href="${url}"><foo>temp</foo></ele>`;
    xml:setChildren(b, "a");
}
```

> [2021-10-26 17:20:50,819] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.BmpStringValue cannot be cast to class java.lang.String (io.ballerina.runtime.internal.values.BmpStringValue is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap') 
> java.lang.ClassCastException: class io.ballerina.runtime.internal.values.BmpStringValue cannot be cast to class java.lang.String (io.ballerina.runtime.internal.values.BmpStringValue is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
> 	at org.ballerinalang.langlib.xml.SetChildren.setChildren(SetChildren.java:57)
> 	at ballerina.lang$0046xml.0.xml.setChildren(xml.bal:156)
> 	at test7.main(test7.bal:9)
> 	at $_init.$lambda$main$(.)
> 	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
> 	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:323)
> 	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> 

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33460
