### ISSUE TITLE
`lang.array:sort()` should create a new array

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#33415]
**Description:**
According to [spec](https://github.com/ballerina-platform/ballerina-spec/blob/11277d73b77f5f0c2871c7e7f04cc803ca9f31b2/lang/lib/array.bal#L172-L175) `lang.array:sort()` shoud create a new array and sort. But currently in the implementation it sorts the calling array itself.

**Affected Versions:**
Current master

**Comment by KRVPerera** [comment]
Fixed https://github.com/ballerina-platform/ballerina-lang/pull/33489
