### ISSUE TITLE
Compiler rejects valid xml type

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#33426]
**Description:**
```ballerina
type RO_XML xml<N|RO_E|RO_C|RO_C|T>; // incompatible types: 'xml' cannot be constrained with '(xml<never>|RO_E|RO_C|xml:Text)'

type R readonly;

// @type N < R
type N xml<never>;

// @type T < R
// @type N < T
type T xml:Text;

// @type N = RN
type RN readonly & N;

// @type RO_E < R
type RO_E xml:Element & readonly;

// @type RO_C < R
type RO_C xml:Comment & readonly;

// @type RO_P < R
type RO_P xml:ProcessingInstruction & readonly;
```

Looks like this is due to not getting the effective type of the readonly intersections.

Also note that there are 2 error messages for the same error. This is usually caused by hashing issue in arguments to diagnostic messages.
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in update 2. We can add tests and close this.

**Comment by MaryamZi** [comment]
Tests were added in https://github.com/ballerina-platform/ballerina-lang/pull/42337.
