### ISSUE TITLE
Quotes are getting skipped when calling `toString()` of literals 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#33465]
**Description:**
Currently, when we get the `toString()` (java) of the literals, we skip `"`. Is this correct?
Let's say we have an example like this
```ballerina
function test() {
    map<anydata> mm = {s1: "hello", s2: 123};
}
```
When we get the `toString()` of the value of the field we get `hello` instead of `"hello"`. Moreover, when we get the `toString()` of the first and second fields, we get `s1: hello` and `s2: 123`.

This affects when we log diagnostics as well.

Another example for this is
```ballerina
map<"string"|"boolean"> po = {q: 123};
```
This produces an error `incompatible types: expected 'string|boolean', found 'int'` (without quotes even though they are string values)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/34361. Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34534 for 2201.0.1.
