### ISSUE TITLE
Closure vars not visible in an anon function

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#33493]
Consider the following:
```ballerina
function test() {
    int y = 10;

    var fn1 = function (<cursor>string s) {
        int z = y + 1;<cursor>
    };
 }
```
The closure var `y` should be visible at the illustrated cursor positions.

**Comment by sanjana** [comment]
@pubudu91, The symbol `y` is visible for the second cursor position (`int z = y + 1;<cursor>`) in the current master.

At the first cursor position (`var fn1 = function (<cursor>string s) {`), do we need the symbol `y` to be visible? 

@mohanvive @nadeeshaan WDYT?

**Comment by nadeeshaan** [comment]
> ```ballerina
> int y = 10;
> 
>     var fn1 = function (<cursor>string s) {
>         int z = y + 1;<cursor>
>     };
> ```

IINM, we can only type the following, regarding the first cursor position,

```
int y = 10;

var fn1 = function (string s = <cursor>) {
        int z = y + 1;
};
```

So I believe that `y` should be suggested only in this position.

**Comment by pubudu91** [comment]
> ```ballerina
> int y = 10;
> 
>     var fn1 = function (<cursor>string s) {
>         int z = y + 1;<cursor>
>     };
> ```

Yes, the use case you explained is the scenario. But IINM, when it comes to visibility, what we consider is a scope. I don't think we can restrict it to such a finer a level. Also, the issue is still there in master for both cases.
