### ISSUE TITLE
[Semantic API] Need to define the `visibleSymbols()` behaviour for init() method

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#33492]
Consider the following:
```ballerina
function testObjectConstructor() {
    int y = 0;

    var obj = object {
        string name = "";
        int age;

        function init() {
            self.age = 0;
            var s = self.getName(); 
        }

        function getName() returns string {
            return self.name;
        }
    };
}
```
In the init() method, the getName() method is not visible. But init() is visible in getName(). Need to evaluate the behaviours for methods in object constructors. And should evaluate and see classes too.

**Comment by mohanvive** [comment]
Start the discussion with compiler FE team.

**Comment by dulajdilshan** [comment]
Here we are not getting `getName()` as a completion without the `self` keyword

**Comment by dulajdilshan** [comment]
We need to decide on whether we should allow calling methods in within methods without self keyword. Please see the below example.
```ballerina
class className {
    function something() {
        getName();
    }

    function getName() {
        
    }
}
```

**Comment by pubudu91** [comment]
> We need to decide on whether we should allow calling methods in within methods without self keyword. Please see the below example.
> 
> ```ballerina
> class className {
>     function something() {
>         getName();
>     }
> 
>     function getName() {
>         
>     }
> }
> ```

That's not allowed by the spec. Always need to use `self` when referring to fields and methods within a class/object constructor.

**Comment by dulajdilshan** [comment]
There is a case that we need to handle https://github.com/ballerina-platform/ballerina-lang/pull/34287#issuecomment-994269005

**Comment by lochana-chathura** [comment]
The reason for symbols being not visible in case1 is recovery.
```bal
class Vehicle {
	public string brand =

	function () returns string {
		return "Toyota";
	}
}
```

Above is a valid syntax. Hence the source get recovered as,
```bal
class Vehicle {
	public string brand = 

	function  INVALID[getBrand]() returns string {
		return "Toyota";
	}
 MISSING[;]}
```

But in case2 we detect it in the parser from `}` token.
