### ISSUE TITLE
getChildrenList() of BXmlSequence is not worked properly with line break

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#33497]
**Description:**
When initialising xml with line break between elements, couldn't get the proper Bxml list by using xmlSequence.getChildrenList().

Xml initialisation with line break in ballerina: 
```ballerina
xml x1 = xml `<books>
                      <item>book1</item>
                      <item>book2</item>
                      <item>book3</item>
                  </books>
                  `;
```
Output of the List:
```
[<books>
                      <item>book1</item>
                      <item>book2</item>
                      <item>book3</item>
                  </books>, 
                  ]
```
Next iteration output is: 
```
[
                      , <item>book1</item>, 
                      , <item>book2</item>, 
                      , <item>book3</item>, 
                  ]
```
If Xml has line break before or after that elements, that line break should be eliminated by `getChildrenList()` but that was not removed here.

**Steps to reproduce:**
Run the above xml with this 
```List<BXml> sequence = xmlSequence.getChildrenList();```

Please refer this code to get more info, 
https://github.com/ballerina-platform/module-ballerina-xmldata/pull/291/files#diff-238e355567a10837bf03aed486fd6caac98a21b9d4e3b4403b86aec40e2d0012R212

**Affected Versions:**
Beta 4- SNAPSHOT

**Comment by HindujaB** [comment]
For the sample 
```ballerina
   xml x1 = xml `<books>
    <item>book1</item>
    <item>book2</item>
    <item>book3</item></books>`;
```
when there is a new line character in between an xml sequence, it is parsed as a `xml:Text` element with `"\n"`. 
Since we can create `xml:Text` elements with empty string or new line character, we need to verify the behavior in a n xml sequence.
@suleka96 WDYT?

**Comment by HindujaB** [comment]
And the fix needs to be done in compiler-FE parser phase. Hence, removing the jballerina tag

**Comment by suleka96** [comment]
> For the sample
> 
> ```ballerina
>    xml x1 = xml `<books>
>     <item>book1</item>
>     <item>book2</item>
>     <item>book3</item></books>`;
> ```
> 
> when there is a new line character in between an xml sequence, it is parsed as a `xml:Text` element with `"\n"`. Since we can create `xml:Text` elements with empty string or new line character, we need to verify the behavior in an xml sequence. @suleka96 WDYT?

The current behaviour of xml:Text in an xml sequence is correct. If the user needs to get rid of unnecessary whitespaces, the strip() function can be used.

**Comment by HindujaB** [comment]
But the below code gives no change.
```ballerina
import ballerina/io;

public function main() {
    xml x1 = xml `<books>
    <item>book1</item>
    <item>book2</item>
    <item>book3</item></books>`;
    io:println(x1.children().length()); // gives 6
    io:println(x1.strip().children().length()); // gives 6
}
```

**Comment by suleka96** [comment]
Sorry my bad you can do `x1.elementChildren()` to just get the elements.

**Comment by HindujaB** [comment]
@kalaiyarasiganeshalingam Would that work for you?
If it's from native code, we might need to use `elements()` method from `XmlSequence`.

**Comment by rdhananjaya** [comment]
As @suleka96  said, it is expected to have the xml text values (which are whitespaces) in the xml value.
Had a discussion with @kalaiyarasiganeshalingam and closing this issue.
