### ISSUE TITLE
Revert #32103 and allow join as identifier only in method call expression

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#33507]
**Description:**
For the below keywords we have allowed them to be used as identifiers via #32103

- `where`
- `join`
- `order`
- `by`
- `equals`
- `ascending`
- `descending`
- `limit`
- `outer`
- `select`

**Describe your task(s)**

Need to revert this and allow only `join` as an identifier only in the method call expression

**Related Issues (optional):**

Related spec Issue [https://github.com/ballerina-platform/ballerina-spec/issues/958](https://github.com/ballerina-platform/ballerina-spec/issues/958)

**Comment by hasithaa** [comment]
@rdulmina In spec issue, we proposed only allow `join` keyword in method call expression. Similar to `map` and `start` keywords.

**Comment by rdulmina** [comment]
Fixed with #33515
