### ISSUE TITLE
Able to define invalid `XML`s with multiple possible root nodes

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#33501]
**Description:**
$Subject

**Steps to reproduce:**
Run the below sample.
```
import ballerina/io;

public function main() {
    xml x = xml `<name>Alex</name><age>30</age>`;
    io:println(x);
}
```

**Output:**
```
<name>Alex</name><age>30</age>
```
However, this is not a valid `XML` since there can be multiple possible root nodes.

**Affected Versions:**
SLBeta3

**OS, DB, other environment details and versions:**
MacOS

**Comment by MaryamZi** [comment]
The `xml` type in Ballerina represents all XML values where

```
An xml value is a sequence representing parsed XML, such as occurs in the content of an XML element.
```

See https://ballerina.io/spec/lang/master/#XML

An XML value can be a singleton of element, processing instruction, comment, and text or a sequence of multiple items. It is not required to be a valid XML document.
