### ISSUE TITLE
[1.2.x] Scopes are not populating properly in the runtime:principal for cached oauth2 tokens

### ISSUE THREAD

**Issue by chashikajw** [ballerina-platform/ballerina-lang#33539]
**Description:**
Authorization fails when using a previously used access token. This issue happens because of scopes are not populating properly in the runtime:principal for cached oauth2 tokens
**Steps to reproduce:**

Following logs can be observed for the API calls and in the second API call, scopes are not attached to the cache key. Cache keys are different for the same oauth2 token (second key the scopes are missing).

1. First API call
`2021-10-29 15:10:15,735 DEBUG [ballerina/cache] - Cache entry from the given key: admin@carbon.super-Consumer_hyphen_Data_hyphen_Standards__v1-getb9a42d1a61864a709d93108ef2f2e63c-GET-default,, is not available.
2021-10-29 15:10:15,739 DEBUG [ballerina/cache] - Cache entry from the given key: admin@carbon.super-Consumer_hyphen_Data_hyphen_Standards__v1-getb9a42d1a61864a709d93108ef2f2e63c-GET-default,, is not available.`

2. Second API call
`2021-10-29 15:12:10,602 DEBUG [ballerina/cache] - Cache entry from the given key: admin@carbon.super-Consumer_hyphen_Data_hyphen_Standards__v1-getb9a42d1a61864a709d93108ef2f2e63c-GET, is not available.
2021-10-29 15:12:10,603 DEBUG [ballerina/cache] - Cache entry from the given key: admin@carbon.super-Consumer_hyphen_Data_hyphen_Standards__v1-getb9a42d1a61864a709d93108ef2f2e63c-GET, is not available.`

**Affected Versions:**
1.2.x

**OS, DB, other environment details and versions:**
Microgateway-toolkit-3.2

**Comment by ldclakmal** [comment]
Fixed with the above PR. Hence closing the issue.
