### ISSUE TITLE
No error when a mapping binding pattern binds rest fields

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#33538]
**Description:**
$title. Where the field is of type `T`, the type seems to be considered `T?`. I don't think this is inline with the spec.

**Steps to reproduce:**
```ballerina
public function main() {
    record {| int i; int...; |} a = {i: 1};
    record {| int i; int...; |} {i: _, j} = a; // no error

    // int x = j; // incompatible types: expected 'int', found 'int?'
}
```

**Affected Versions:**
slbeta4-rc1

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34359
