### ISSUE TITLE
Some messages in exceptions contain Java level information

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#3354]
When handling exceptions and creating Ballerina error messages, currently, the common practice is to get the message from the exception thrown and customize that message to fit to Ballerina. However, there are some cases where the message itself contains Java level implementation details which we need to hide from the Ballerina user. Therefore, we may need to reconsider our approach to creating error messages. Given below is one of the such instances I came across. This is somewhat related to issue #3333 as well.

```
error: ballerina.lang.errors:Error, message: no enum constant org.ballerinalang.logging.util.BLogLevel.WARNING
	at ballerina.utils.logger:info(ballerina/utils/logger/natives.bal:1)
	at com.xyz:logTest(com/xyz/test.bal:6)
	at com.abc:main(com/abc/test.bal:11)
```

**Comment by uthaiyashankar** [comment]
This should have been fixed now. Please reopen if this issue is still there.
