### ISSUE TITLE
Add code action for adding a return statement in a function

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33565]
**Description:**
Consider the following source snippet,

```
function parse(string str) returns int? { // Results in a warning.
   int|error a = int:fromString(str);
   if a is int {
       return a;
   }
}
```

Here, in order to avoid the waring, we can add a return statement at the end of the function.

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/33568
