### ISSUE TITLE
Enrich error message in error ctor when error-type-reference is provided

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#33574]
**Description:**

#### Code sample
```Ballerina
type ErrorA error;
int|string uc4 = error ErrorA("msg");
```

#### Error
```LogTalk
ERROR [t3.bal:(2:18,2:37)] incompatible types: expected '(int|string)', found 'error
```

#### Expected error
```Ballerina
ERROR [t3.bal:(2:18,2:37)] incompatible types: expected '(int|string)', found 'ErrorA'
```

This error is currently issued from
https://github.com/ballerina-platform/ballerina-lang/blob/8adfc0ac5b12d60c70d33893a15e49e7eba2920e/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L2799

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Getting the expected error on slbeta6. Keeping the issue open to add tests.

**Comment by MaryamZi** [comment]
Need to also check [this comment](https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-beta.6/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L2913).

**Comment by KavinduZoysa** [comment]
This works as expected in Ballerina 2201.3.0
