### ISSUE TITLE
Cannot execute .bal files using relative path on Windows

### ISSUE THREAD

**Issue by tdevinda** [ballerina-platform/ballerina-lang#3357]
### Method to reproduce: (my values in brackets)
- Install and extract ballerina (E:\Software\Ballerina)
- create a .bal file (hello.bal)
- cd to the directory of the .bal file (D:\Projects\ballerina)
- do ballerina run from dir using relative path (ballerina run hello.bal)

### Outcome:
Ballerina reports there is no such file or directory (ballerina: no such file or directory: hello.bal)

### Example output;
```
D:\Projects\ballerina>dir
 Volume in drive D is Documents
 Volume Serial Number is XXXXXX

 Directory of D:\Projects\ballerina

2017-09-22  03:25 PM    <DIR>          .
2017-09-22  03:25 PM    <DIR>          ..
2017-09-22  03:25 PM               103 hello.bal
               1 File(s)            103 bytes
               2 Dir(s)  43,741,040,640 bytes free

D:\Projects\ballerina>ballerina run hello.bal
ballerina: no such file or directory: hello.bal
```

**Comment by uthaiyashankar** [comment]
This problem is not there now.
