### ISSUE TITLE
Current lang.error `RetryManager ` shouldRetry() function argument type is different from the spec.

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#33589]
**Description:**
The current implementation has the following signature

```ballerina
public type RetryManager object {
 public function shouldRetry(error? e) returns boolean;
};
```

But Spec(https://ballerina.io/ballerina-spec/spec.html#lang.error) says it should be

```ballerina
public type RetryManager object {
 public function shouldRetry(error e) returns boolean;
};
```

Affect version: slbeta3

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/33590
