### ISSUE TITLE
How do I run one file on 3 different machines and synchronize the data between them? How to implement blockchain?

### ISSUE THREAD

**Issue by salemalem** [ballerina-platform/ballerina-lang#33592]
Let's say I have server program
I run it on 1st machine and I want to store information on that running server. I want the same program but running on second machine to synchronize that data from 1st server automatically.
Basically, a blockchain implementation in Ballerina because blockchain is also about networks along with cryptography.

**Comment by gimantha** [comment]
As of now there is no built in mechanism to synchronise information in memory between multiple servers. But you could try writing transactional services to pass messages between multiple servers.

**Comment by KavinduZoysa** [comment]
Closing this for now, and we will take this one later on.
