### ISSUE TITLE
Need an API to Access Internal Segments of a Resource Path 

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#33609]
**Description:**
There is a requirement in [GraphQL compile-time schema generation](https://github.com/ballerina-platform/ballerina-standard-library/issues/2047) to access the internal segments of a resource path from a `ResourceMethodSymbol`. Even though internally this information is available, there isn't an API to access them.

**Comment by pubudu91** [comment]
@ThisaruGuruge In `ResourceMethodSymbol`, there's a method for getting the resource path, `resourcePath()`. This will return a `ResourcePath` instance. Depending on the kind of resource path that method has, you can access its components. For example, if the resource path consists of path segments, the returned instance will be an instance of `PathSegmentList`. From this you can get the segments of the path. Doesn't this address the above mentioned requirement?

**Comment by ThisaruGuruge** [comment]
Thanks, @pubudu91 for the clarification. This resolves the issue.
