### ISSUE TITLE
Need a Way to Access Diagnostic Info from One Code Analyzer to Another

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#33610]
**Description:**
In [GraphQL compile-time schema generation](https://github.com/ballerina-platform/ballerina-standard-library/issues/2047), we have two phases.

1. Validating the GraphQL service
2. Generating the GraphQL schema

When we encounter a compilation error, the second phase should not be run. But currently, we can not access the diagnostic information added from the 1st step from the 2nd step. (As a workaround, we can do some kind of a hack, by passing a Map to the first code analyzer and then passing it back to the 2nd step). But ideally, there should be a way to retrieve this information within the context.

**Comment by sameerajayasoma** [comment]
I have already designed the code generator APIs to address this requirement. Code generators generate source code or resource files, but to do that, they need to analyze the syntax and semantic properties of the current source code. Therefore code generators are essentially analyzers as well. 

Here is the `CodeGeneratorContext` API: 
```java
/**
 * Represent the context required to initialize a {@code CodeGenerator}.
 * <p>
 * This class can be used to add various generator tasks during the {@code CodeGenerator} initialization.
 *
 * @since 2.0.0
 */
public interface CodeGeneratorContext {

    /**
     * Add a source code generator task to be triggered once the compilation is completed.
     *
     * @param generatorTask the source code generator task to be executed
     */
    void addSourceGeneratorTask(GeneratorTask<SourceGeneratorContext> generatorTask);

    /**
     * Add a code analysis task to be triggered once the semantic analysis of a syntax node with
     * one of the specified {@code SyntaxKind}s.
     *
     * @param analysisTask the analysis task to be executed
     * @param syntaxKind   the {@code SyntaxKind} of the nodes on which the analysis task is triggered
     */
    void addSyntaxNodeAnalysisTask(AnalysisTask<SyntaxNodeAnalysisContext> analysisTask, SyntaxKind syntaxKind);

    /**
     * Add a code analysis task to be triggered once the semantic analysis of a syntax node with
     * one of the specified {@code SyntaxKind}s.
     *
     * @param analysisTask the analysis task to be executed
     * @param syntaxKinds  the collection of {@code SyntaxKind}s of nodes on which the analysis task is triggered
     */
    void addSyntaxNodeAnalysisTask(AnalysisTask<SyntaxNodeAnalysisContext> analysisTask,
                                   Collection<SyntaxKind> syntaxKinds);
}
```
You can optionally add syntax analysis tasks to understand more about the source code you are dealing with. Such analyzers can aggregate information, and when the code generator task is executed, you can use that information to make decisions. 

What this means is that you can move all your analysis code to the code generator task.
