### ISSUE TITLE
 Evaluate module level variables in debugger

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33615]
Please add the ability to eventuate module level variables in the watch panel in VSCode. We need support for both current module variables `x` and other module variables `m:x`

**Comment by NipunaRanasinghe** [comment]
@manuranga We already support same/other module-level variables in debugger view and expression evaluation console as shown below. 
<img width="1390" alt="Screenshot 2021-11-19 at 10 01 42" src="https://user-images.githubusercontent.com/29032600/142565690-ede6b180-6e49-4d5e-9832-2feca35fd580.png">

**Comment by manuranga** [comment]
Can you please test this nballerina repo. I can't evaluate `t:NIL` as show in the screen below 

<img width="1375" alt="Screenshot 2021-12-07 at 8 11 20 PM" src="https://user-images.githubusercontent.com/1686124/145049705-c4f8f3d6-fc36-41a4-b48b-c05740fb25e4.png">

**Comment by NipunaRanasinghe** [comment]
@manuranga I tested evaluations on nballerina compiler and evaluations are working for me as expected. However the constant `t:NIL` which you mentioned does not exist in the types module and therefore you might have got an evaluation output as below for `t:NIL`. (Note that the evaluator has returned a result for the existing constant: `t:UL_NIL`)


<img width="471" alt="Screenshot 2021-12-22 at 14 19 09" src="https://user-images.githubusercontent.com/29032600/147064351-17955146-5a36-44b6-a679-aee07a317200.png">

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/34533
