### ISSUE TITLE
Auto-completions spec conformance for the `StartAction`

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33630]
**Description:**
$title

Sub Tasks
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33747
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33757

**Comment by TharushiJay** [comment]
Created issues
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33747
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33757
