### ISSUE TITLE
Auto-completions spec conformance for the `WaitAction`

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33632]
**Description:**
$title
https://ballerina.io/spec/lang/master/#wait-action

- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33825
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33886
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/34497

**Comment by TharushiJay** [comment]
Created issues 
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33825
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33886
