### ISSUE TITLE
Model module resources and test resources in the Project API

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#33652]
In the initial version of the project API design, I didn't model resources and test resources of a module. The API doesn't provide a way to access such resources. We've been getting several requests for this feature. I came across this while implementing the code generator support. https://github.com/ballerina-platform/ballerina-lang/issues/33651

**Comment by azinneera** [comment]
There can be 2 types of resources:  Resources needed for the runtime vs other purposes (i.e docs, icons, etc.) The latter will be addressed by https://github.com/ballerina-platform/ballerina-lang/issues/33651 and therefore, we will only address the former here.

Resources needed for the runtime can be in two forms: static resources added manually vs resources generated dynamically during compilation.
There are differences between the two which need to be considered when designing the APIs:

| static        | dynamic           |
| ------------- |:-------------:|
| Has a path in the FS      | No paths, the document is in memory |
| Has a content      | Has a content      |
| Doesn't need a save() operation | Needs to be saved to a temp location, i.e target /generated-resources    |
