### ISSUE TITLE
Incorrect Error Message 

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#33658]
Adding the following function to a program gives an exception error, 

```
function read(handle receiver) returns int = @java:Method {
   'class: "java.io.InputStream"
} external;
```

Error :
`ERROR [main.bal:(28:1,30:12)] {ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'No such Java method 'read' which throws checked exception found in class 'class java.io.InputStream''`

This error should be corrected as,
METHOD_SIGNATURE_DOES_NOT_MATCH ‘No such Java method ‘read’ which **does not** throw checked exception found in 'class java.io.InputStream 

Or it should have mentioned to return **int|error** instead of **int**.

**Comment by Maninda** [comment]
Got a similar kind of error when the interop function is

```ballerina
isolated function poll(Listener listenerEndpoint) returns Error? = @java:Method{
    name: "poll",
    'class: "io.ballerina.stdlib.ftp.server.FtpListenerHelper"
} external;
```
and the the native Java method signature as
```java
public static void poll(BObject ftpListener) throws BallerinaFtpException
```

The error got resolved when the Java method signature is changed to
```Java
public static Object poll(BObject ftpListener)
```

**Comment by gabilang** [comment]
When the java method throws a checked exception, the return type of extern function should contain `error` type. Currently we do not have a way to directly match checked exceptions with distinct errors.
