### ISSUE TITLE
Improve the hover of any object:RawTemplate objects

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#33669]
**Description:**
Even though the object:Rawtemplate are defined as objects with fields strings and insertions. These fields are used only at desugar level and within the library code. For users, this is unnecessary as this is similar to a datatype definition.

```
object: Rawtemplate rt = `SELECT * From Students where id = ${id}`;
```

These fields need to be hidden in the hover object. 
<img width="579" alt="Screenshot 2021-11-05 at 21 06 40" src="https://user-images.githubusercontent.com/27669465/140537330-39280841-1512-418e-9f0b-d7eee02261e2.png">

**Comment by nadeeshaan** [comment]
Given the structure of the type, the semantic API and the LS consume these fields as common fields compared to the other type definitions as well. Therefore in order to filter out these fields specifically, we need to have a some sort of flag or should be controlled with the access modifiers.

**Comment by niveathika** [comment]
@pubudu91 Can we look into making the fields private?

**Comment by daneshk** [comment]
> @pubudu91 Can we look into making the fields private?

@niveathika We are using these fields in the SQL module to concatenate two or more rawTemplates to one. So we can't make those fields private. Special case this with a flag as Nadeeshan mentioned is the option we have IMO

**Comment by pubudu91** [comment]
Had an offline discussion with Niveathika a little while back regarding this. A couple of points:
- `private` is not allowed on fields of an object type. Even if we make them non-public, I think it might affect the type compatibility and break the feature (have to verify).
- `RawTemplate` object type is just another object type in the language. There's nothing preventing a user from using as a regular object type. So I don't think we should do anything specifically for it to hide its fields.

**Comment by niveathika** [comment]
We have improved the description mentioning about the usage of backtick strings to create this object. Considering this field description can be exposed.
