### ISSUE TITLE
Identifier with unicode escape sequence gives redeclared symbol error

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#33667]
**Description:**
Consider the below sample
```bal
const int a = 5;
int \u{24}anonType\u{24}_0 = 5;
```
gives `ERROR [test.bal:(20:5,20:27)] redeclared symbol '$anonType$_0'`

**Affected Versions:**
Current master

**Comment by KavinduZoysa** [comment]
This works in `Ballerina 2201.3.0`. We can close the issue.
