### ISSUE TITLE
Missing details in hover such as function name and stream completion type

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#33671]
**Description:**
Function names are not visible for object hover
<img width="706" alt="Screenshot 2021-11-05 at 21 02 56" src="https://user-images.githubusercontent.com/27669465/140537485-929adf0b-5f63-4eed-bdb7-fcf882c1bd7c.png">

Stream completion type is incomplete `sql:Error?` is seen as `sql:?`
<img width="655" alt="Screenshot 2021-11-05 at 21 04 07" src="https://user-images.githubusercontent.com/27669465/140537652-0bef5df3-895c-4bd7-a9e5-5ebcf79ddcb0.png">

**Comment by IMS94** [comment]
`sql:Error?` being printed as `sql:?` was fixed in #33721

**Comment by IMS94** [comment]
@niveathika we rely on `Symbol.signature()` to get the function signature. Need to check why we get this behavior.

**Comment by IMS94** [comment]
This was fixed in #34134.
