### ISSUE TITLE
Clickable links within Hover

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#33673]
**Description:**
This allows users to view API docs descriptions of parameter records easily rather than going to API docs. 

For example, sql:ParameterisedQuery object as parameter for query() function.
<img width="655" alt="Screenshot 2021-11-05 at 21 04 07" src="https://user-images.githubusercontent.com/27669465/140539700-18eb81c7-7478-424f-b596-04899d3c4595.png">

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
