### ISSUE TITLE
Update the organization name validation for Ballerina.toml

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#33676]
**Description:**
$topic

Currently, we are using the following regex to validate the organization name in Ballerina Central. Hence, we need to update the organization validation regex for Ballerina.toml
`^[a-zA-Z0-9]([-](?![-])|[a-zA-Z0-9]){1,38}[a-zA-Z0-9]$`

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by suganyasuven** [comment]
Need to support to this [spec](https://github.com/ballerina-platform/ballerina-spec/issues/791)

**Comment by pramodya1994** [comment]
Currently, we have added the following validations for the `org` in Ballerina.toml:
- ASCII only
- alphanumeric + underscore only
- no initial underscore
- no trailing underscore
- no consecutive underscores
- max length 256 chars
As mentioned in this [spec issue](https://github.com/ballerina-platform/ballerina-spec/issues/791).

@hevayo @suganyasuven Do you need anything else here?

**Comment by azinneera** [comment]
Since the change in lang repo is already done, closing this and will open another for the fix in Ballerina Central.
