### ISSUE TITLE
Code completion for remote function can be sorted based on LHS of the expression

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#33672]
**Description:**
<img width="854" alt="Screenshot 2021-11-05 at 21 02 16" src="https://user-images.githubusercontent.com/27669465/140537934-f88b886f-1076-4c8d-83a1-e439aa17011f.png">

Here sql:ProcedureCallResult[] is only returned for call method. This can be highlighted.

**Comment by IMS94** [comment]
Same as #33672
