### ISSUE TITLE
Verify runtime behavior for xml sequence 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#33681]
**Description:**
We need to verify the runtime behavior for xml sequence value if it contains newline characters in the sequence.

**Describe your task(s)**
```ballerina
xml x1 = xml `<books>
                      <item>book1</item>
                      <item>book2</item>
                      <item>book3</item>
                  </books>
                  `;
```
This is to verify the expected behavior of the `getChildrenList()` call for the above xml sequence.

**Related Issues (optional):**
#33497

**Comment by HindujaB** [comment]
When there is a new line character in between an xml sequence, it is parsed as a xml:Text element with "\n".
Since we can create `xml:Text` elements with empty string or new line character, the current behavior for `getChilderenList()` is as expected.

**Comment by hasithaa** [comment]
Please talk to @rdhananjaya on this issue.

**Comment by rdhananjaya** [comment]
This is expected. For the given xml literal expected sequence should looks like:
```
<books>\n.....................<item>book1</item>\n.....................<item>book2</item>\n.....................<item>book3</item\n.....................</books>\n.....................
```


```ballerina
import ballerina/io;
public function main() {
   xml x1 = xml `<books>
                      <item>book1</item>
                      <item>book2</item>
                      <item>book3</item>
                  </books>
                  `;

    io:println(x1.length()); // print 2 [books elem and the text following that
    io:println((x1/*).length()); // print 7
}
```

**Comment by HindujaB** [comment]
Since this is the expected behavior, closing the issue.
