### ISSUE TITLE
Implement a way to add modules into a ballerina project without the default template

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#33685]
In the VSCode low code editor, when a user adds a new module into a ballerina project, there will be a default template generated along with a set of test cases. The user has to manually delete this content every time a new module is added. Since this is somewhat of a usability issue, it would be better if we can either,
* refactor the template added by default to a simpler form (or remove it altogether) OR
* introduce a flag to the CLI command to add a blank module without a default template

The second option seems like a safe way since we can configure the add module option in the VSCode low code editor to execute the bal command with a flag.

**Comment by azinneera** [comment]
@IrushiL does it mean that the user should be able to add a module without tests?

**Comment by Dilhasha** [comment]
The generated template includes only the simplified necessary files. Hence, closing.
