### ISSUE TITLE
Pushing bala with invalid access token still shows the progress bar before unauthorized message

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#33696]
**Description:**
When pushing a bala to central with an invalid access token, the progress bar still shows up before the error. 

```
~/Desktop/TestProject ❯ bal push 
                  
ibaqu/TestProject:1.0.0 [project repo -> central] 100% [===============================================================] 1516/1516 B (0:00:00 / 0:00:00) 
ballerina: unable to push package ibaqu/TestProject:1.0.0 as there are dependencies of the package missing in the registry. missing dependencies: [ballerina/io:1.0.1]
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
This happens since we send only one request to do both of the tasks:
- validate token
- upload the bala
We might have to decouple if we want to validate the token before uploading bala.

**Comment by ShammiL** [comment]
A new method to validate token before pushing package added.
