### ISSUE TITLE
Semantic API doesn't contains annotations of the modules pulled by central

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#33711]
**Description:**
$Subject. 
However semantic api works just fine, when the module is in the same package(as a module)
![image](https://user-images.githubusercontent.com/23274047/140903827-45b15e38-7a73-4be2-8493-62d5b8e88f3e.png)

When the module is pushed to the central (or local repo), semantic api does not return the annotations.
**Steps to reproduce:**
Working code - https://github.com/ballerina-platform/module-ballerina-c2c/tree/master/c2c-extension-test/src/test/resources/service/expose-int-or-http

Module Code - https://github.com/ballerina-platform/module-ballerina-c2c/blob/master/c2c-extension-test/src/test/resources/service/expose-int-or-http/modules/mod/mod.bal#L21

**Affected Versions:**
slbeta3
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Could potentially be due to #30222

**Comment by hasithaa** [comment]
This requires changes to current BIR model. Hence, we need to prioritize this for GA.

**Comment by MaryamZi** [comment]
The main issue of annotation attachments not being available in the BIR is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/16379.

This particular case seems to be a requirement for parameter annotations. These are not added to the BIR yet.

**Comment by pubudu91** [comment]
Closing this since as per the above comment, the particular issue raised here is addressed.
