### ISSUE TITLE
Unnecessarily expect an explicit return

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33725]
Following gives `this function should explicitly return a value` warning when it shouldn't.

```ballerina
const SOME_CONST = ...;

function f() returns boolean? {
    int i = 0;
    while true {
        if i == SOME_CONST {
            return false;
        }
    }
}
```

**Comment by hasithaa** [comment]
@manuranga this is the spec issue https://github.com/ballerina-platform/ballerina-spec/issues/973 for this change. With this change, you need to have a `return` stmt at the end of the function to avoid the warning.

**Comment by jclark** [comment]
@hasithaa The end of the function is not reachable (because the `while` condition is singleton true and there is no `break`), so this is a bug.

**Comment by hasithaa** [comment]
Ahh, My bad, I missed it.

**Comment by lasinicl** [comment]
but shouldn't the `while` block have a `return` when not satisfying the `i == SOME_CONST` condition?

**Comment by jclark** [comment]
@lasincl It's not an error to have a non-terminating loop.

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33729
