### ISSUE TITLE
Compiler Plugin failes for error return types

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#33721]
**Description:**
In the compile plugin of ballerina websub module, we have used `signature()` method of `TypeReferenceTypeSymbol` to get the full type description of error return types. 

With the `SL Beta4` RC pack, return type validation of websub compiler plugin has broken due to a change in `signature()` method of `TypeReferenceTypeSymbol`.  

Even though this validation fails with the RC pack, all the compiler plugin test cases are passing with the latest lang version. 

**Steps to reproduce:**
* Write a simple `websub:SubscriberService` and try to build this program using latest `SL Beta4 RC1` pack.
```ballerina
import ballerina/websub;

@websub:SubscriberServiceConfig {
    target: ["http://0.0.0.0:9090/hub", "test"],
    leaseSeconds: 36000
}
service on new websub:Listener(9091) {
    remote function onEventNotification(websub:ContentDistributionMessage event) 
                                        returns websub:Acknowledgement|websub:SubscriptionDeletedError? {
        return websub:ACKNOWLEDGEMENT;
    }
}
```

**Affected Versions:**
* SL Beta4 RC1

**Comment by mohanvive** [comment]
@ayeshLK I have tried to reproduce this issue, but failed. Can you please list down the exact steps (and attach any artefacts) that you are following to reproduce the issue with the pack?

**Comment by nadeeshaan** [comment]
@ayeshLK Do you have the diff for the two cases?

**Comment by ayeshLK** [comment]
@mohanvive / @nadeeshaan 

Expected output:
```

**Comment by mohanvive** [comment]
I am trying to debug the code that you shared. But it is pulling the websub 2.0.0 and failing with below error. Am I missing anything here?

```
mohanadarshan@mohan bin % BAL_JAVA_DEBUG=5005 bal run test.bal
Listening for transport dt_socket at address: 5005

Compiling source
	test.bal
ballerina/websub:2.0.0 [central.ballerina.io -> home repo]  100% [===================================================================================] 14570/14570 KB (0:00:15 / 0:00:00) 
	ballerina/websub:2.0.0 pulled from central successfully
ERROR [test.bal:(1:1,1:25)] cannot resolve module 'ballerina/websub'
ERROR [test.bal:(3:1,6:2)] undefined annotation 'SubscriberServiceConfig'
ERROR [test.bal:(3:1,6:2)] undefined module 'websub'
ERROR [test.bal:(7:16,7:31)] undefined module 'websub'
ERROR [test.bal:(7:16,7:31)] unknown type 'Listener'
ERROR [test.bal:(8:41,8:74)] undefined module 'websub'
ERROR [test.bal:(8:41,8:74)] unknown type 'ContentDistributionMessage'
ERROR [test.bal:(9:49,9:71)] undefined module 'websub'
ERROR [test.bal:(9:49,9:71)] unknown type 'Acknowledgement'
ERROR [test.bal:(9:72,9:103)] undefined module 'websub'
ERROR [test.bal:(9:72,9:103)] unknown type 'SubscriptionDeletedError'
ERROR [test.bal:(10:16,10:38)] undefined module 'websub'
error: compilation contains errors
```

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/33735
