### ISSUE TITLE
Lock wait timeout exceeded error when running multiple calls that includes distributed transactions

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#3374]
Seemingly, subsequent calls with distributed transactions causes database hang due to too many connections due to some problems in connection management. Due to this client get hanged.

When executing the [sample client ](https://github.com/erandidesilva/integration-tests/blob/mysqlConnectorTests/src/test/java/org/ballerinalang/tests/connectors/rdbms/operations/transactions/distributed/DisTransactionTest.java) against the ballerina files [[1](https://github.com/erandidesilva/integration-tests/blob/mysqlConnectorTests/src/test/resources/Artifacts/mysql_connector/resources/services/DisTransactionService.bal)], [[2](https://github.com/erandidesilva/integration-tests/blob/mysqlConnectorTests/src/test/resources/Artifacts/mysql_connector/resources/services/DistributedTransactionTest.bal)] following error occurs in client and the client is hanged

**Error at client side**
`com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction`

**Comment by uthaiyashankar** [comment]
We are not getting this error now. Should have been fixed.
