### ISSUE TITLE
Observing OOM when doing subsequent compilations

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33741]
**Description:**
Get the nBallerina repo and open it with the VSCode plugin.
Now try editing a source in one of the modules or multiple modules.
This will lead to an OOM with the following heap observation with the `SemanticAnalyzer`

<img width="1388" alt="Screenshot 2021-11-10 at 14 13 56" src="https://user-images.githubusercontent.com/1329674/141079716-507f88b6-6e57-46b6-91fc-b6f81d1f4640.png">

**Affected Versions:**
SwanLake-Beta4-RC1 at least

**Comment by sameerajayasoma** [comment]
Do we know what caused this? It has to be a commit after beta3 right?

**Comment by gimantha** [comment]
> Do we know what caused this? It has to be a commit after beta3 right?

Yes. In subsequent compilations, states are not clean properly in semanticAnalyzer phase. They get accumulated in `prevEnv` Stack in `SemanticAnalyzer`. Can be fixed easily by clearing the stack. But to properly fix it, we need to address #33753, #33315

**Comment by gimantha** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/33761
