### ISSUE TITLE
Fix sorting in `is-expr`

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#33749]
**Description:**

<img width="432" alt="Screenshot 2021-11-10 at 16 57 08" src="https://user-images.githubusercontent.com/46120162/141105254-7638b143-8478-48fd-a924-8055bf93e0a4.png">

Can we give priority to variable's type/types when giving auto completions? Completions are coming through `TypeTestExpressionNodeContext.java`

**Comment by nadeeshaan** [comment]
Similar to #32607. Since this requirement will be addressed with the issue mentioned. Hence closing the issue
