### ISSUE TITLE
Enable jballerinaDebugger tests disabled due to removing running tests from bal build cmd 

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#33748]
**Description:**
The following : https://github.com/ballerina-platform/ballerina-lang/pull/33743/commits/55496a23c3198a1c25d8acf2a95889dc197b185a have been disabled 

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
Since running tests are removed from the `build` command, we will keep these tests disabled because underneath we wrote the tests for the `test` command.
