### ISSUE TITLE
Diagnostics are inconsistent for the subsequent compilations

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33745]
**Description:**
Consider the following scenario,

1. Get the nBallerina repo
2. Open `nballerina/compiler/modules/types/bdd.bal` (Observe the number of diagnostics)
3. Open `nballerina/compiler/modules/front/codeGen.bal` (Observe that the number of diagnostics are being changed)
4. Now edit the `nballerina/compiler/modules/front/codeGen.bal`  (Add a new line at the end of the file) file and observe the diagnostics vanishes in the particular file
5. Now go to `nballerina/compiler/modules/types/bdd.bal` and edit (Add a new line at the end of the file) the file, and observe how the diagnostics appear in the `codeGen.bal` file.

**Affected Versions:**
SwanLake-Beta4-RC1 at least

**Comment by gimantha** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/33762
