### ISSUE TITLE
Missing completions for `strand` and `thread`

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#33757]
**Description:**

<img width="641" alt="Screenshot 2021-11-11 at 09 33 39" src="https://user-images.githubusercontent.com/27485094/141235114-179cfc0e-d5dc-4e17-9aed-465e2b2f7189.png">
<img width="641" alt="Screenshot 2021-11-11 at 09 33 56" src="https://user-images.githubusercontent.com/27485094/141235123-00f024ff-634c-471a-8cee-e8b156c3bcfe.png">

**Describe your task(s)**

Add completion items for `strand` and `thread` in the above scenarios.

**Related Issues (optional):**
Relates to #33630

**Comment by nadeeshaan** [comment]
This is an edge scenario where we cannot identify the attached node for the annotations.

**Comment by IMS94** [comment]
We can get over
```ballerina
function demo() {
    future<int> f = @stra<cursor>
}
```
scenario somehow.
But the following case is complex:
```
function demo() {
    future<int> f = @strand {<cursor>}
}
```
Because in that case, the node at cursor, `@strand {}` is identified as a simple name reference node.

**Comment by IMS94** [comment]
Blocked by #35223 until a better recovery is implemented in the parser side.

**Comment by lochana-chathura** [comment]
Parser changes were merged to the master. Hence removing the Blocked label.
