### ISSUE TITLE
Verify Compiler phases not to keep certain states in data flow and semantic analysis

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33753]
1. In certain cases, we maintain state variable to keep track of the environments and the data flow paths. But if these variables are not cleaned properly, Stacks, maps lists can grow infinitely and leads to OOMs. 
 Ex: https://github.com/ballerina-platform/ballerina-lang/issues/33741

2. Some state variables like booleans should be reset after compilation of one package before going into the next compilation of the same package or a different package. This can affect the consistency of how diagnostics are shown in VS code. 
 Ex: https://github.com/ballerina-platform/ballerina-lang/issues/33745

**Comment by hasithaa** [comment]
We should be able to address this with https://github.com/ballerina-platform/ballerina-lang/pull/33315, we need to migrate existing visitors to new visitor pattern.
