### ISSUE TITLE
VSCode API docs are not properly rendering error types

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#33788]
**Description:**
See the highlighted type below.

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/16300038/141429716-50036c04-14c8-4958-bd70-c782de7d6e84.png">

**Affected Versions:**

Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.6

**Comment by IMS94** [comment]
This should be similar to https://github.com/ballerina-platform/ballerina-lang/issues/33721. Need to verify.

**Comment by IMS94** [comment]
Verified on SL Beta 4 RC2. This has been fixed.
![Screenshot from 2021-11-17 10-56-49](https://user-images.githubusercontent.com/11285165/142140497-ac944c7e-063a-4732-ae48-4e2d3951da99.png)
