### ISSUE TITLE
Create variable code action generates invalid return types for stdlib methods

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#33787]
**Description:**
$subject for below example.

```ballerina
import ballerinax/java.jdbc;
import ballerina/sql;
import ballerina/io;

public function main() returns error? {
    // Initializes the JDBC client.
    jdbc:Client jdbcClient = check new ("jdbc:h2:file:./dbdir2/bbes/java_jdbc",
        "rootUser", "rootPass");
    jdbcClient->execute(`CREATE TABLE tutorials_tbl ( 
    id INT NOT NULL, 
    title VARCHAR(50) NOT NULL, 
    author VARCHAR(20) NOT NULL, 
    submission_date DATE 
    );`);
    check jdbcClient.close();
    io:println("After client close");
}
```

It generates invalid return type as follows.

`sql:ExecutionResult|ballerina/sql:1.0.0:`

Refer to the below video for more details.

https://user-images.githubusercontent.com/16300038/141429133-0eaf6924-1f22-4c28-b342-016d58b7757b.mov

**Affected Versions:**

```
Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.6```

**Comment by IMS94** [comment]
This should be due to https://github.com/ballerina-platform/ballerina-lang/issues/33721. Need to verify.

**Comment by IMS94** [comment]
Verified on SL Beta 4 RC2. This has been fixed.
![Screenshot from 2021-11-17 11-01-52](https://user-images.githubusercontent.com/11285165/142140815-d88eed2c-4af1-4996-ada9-0a9072dd0788.png)
