### ISSUE TITLE
Path/Rest params in the resource function are considered as unused

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#33793]
**Description:**
Following sample gives the unused variable warning. 
```ballerina
import ballerina/http;
service / on new http:Listener(9090) {
    resource function get [string name]() returns string {
        return "ballerina";
    }
}
```
`WARNING [main.bal:(5:27,5:40)] unused variable 'name'`

Happens for both path and rest parms([string... s])

**Affected Versions:**
beta4-rc1

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33794.
