### ISSUE TITLE
Incorrect code action suggested for spread field in mapping constructor

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33792]
**Description:**
Consider the following source code.
![abc](https://user-images.githubusercontent.com/35211477/141455562-41d68643-fe10-461c-8e7d-8275d12bd3f0.png)

Here `Change variable 'a' type to 'float'` code action is suggested which is incorrect. A correct suggestion would be to change the type of the `field2`  in `b`'s type descriptor that is causing the `incompatible  types` error. 

**Steps to reproduce:**
```ballerina
public function main() {
    record {|int field1;float field2;|} b;
    record {|int field1;int field2;|} a =  {...b};
}
```

**Affected Versions:**
slbeta5-snapshot

**Comment by malinthar** [comment]
This is not reproducible due to https://github.com/ballerina-platform/ballerina-lang/issues/33167

**Comment by TharushiJay** [comment]
Fixed with ​​https://github.com/ballerina-platform/ballerina-lang/pull/34090 and code action is not suggested anymore. Hence, closing the issue.
