### ISSUE TITLE
Ballerina command line tool extention giving errors due to conflicting ANTLR dependencies 

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-lang#33811]
**Description:**
We are trying to implement a command line tool for Ballerina GraphQL client generation. This tool uses a third-party [library](https://github.com/graphql-java/graphql-java)  for GraphQL schema validation and GraphQL query validation. This library uses the ANTLR dependency internally. We get the following error when we try to run our command line tool pack with the Ballerina distribution due to conflicting dependency versions.
![Screenshot from 2021-11-15 14-01-26](https://user-images.githubusercontent.com/34184297/141748337-033d2d82-30ee-4e15-a2c5-bbe332c4106d.png)

**Describe your problem(s)**
The above seems to occur because the ballerina distribution is packing an old ANTLR version(4.5.1) in a jar named
`antlr4-runtime-4.5.1.wso2v1.jar` located at `ballerina-swan-lake-beta4-SNAPSHOT/distributions/ballerina-slbeta4/bre/lib`, but the ANTLR version used in our third party library is `4.9.2`

**Describe your solution(s)**
This issue seems to resolve if we remove this old ANTLR dependency located at `ballerina-swan-lake-beta4-SNAPSHOT/distributions/ballerina-slbeta4/bre/lib` 
Please provide any appropriate fix to address this issue

**Comment by azinneera** [comment]
This has been introduced by the commit https://github.com/ballerina-platform/ballerina-lang/blob/cbd82c62955af85b50c231af1d6426d191ab1352/distribution/zip/jballerina-tools/build.gradle#L81 for handlebars usage in bindgen tool. This has caused an issue as reported in the slack thread https://ballerina-platform.slack.com/archives/C47EAELR1/p1646827299201019

@IrushiL shall we remove altlr from the rt jar if it is no longer used?

**Comment by IrushiL** [comment]
**Reason/Other**

This PR has been fixed with the linked PR.
