### ISSUE TITLE
API for checking the isolation property of a service method is unclear

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#33813]
**Description:**
In current ballerina runtime API if we need to check whether object-method is isolated we use `object.getType().isIsolated(methodName)` [1] and according to the internal implementation details of this method [2] it will first check whether both service-object and the method are isolated. 

But this should not be the case and preferably this should be done via two APIs, one API to check the isolation property of the service-object and the next one to check the service method. In the current runtime API it has a method to check whether the service-object is isolated [3] but it is not used because it will be a redundant API call due to above mentioned issue.

It would be better if we could focus the functionality of each API and implement them to execute only the respective check.

[1]
[https://github.com/ballerina-platform/ballerina-lang/blob/b7dfbd59f4a94ebd45224a1ef64785a9ed6aeb0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java#L44](https://github.com/ballerina-platform/ballerina-lang/blob/b7dfbd59f4a94ebd45224a1ef64785a9ed6aeb0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java#L44)

[2] 
[https://github.com/ballerina-platform/ballerina-lang/blob/b7dfbd59f4a94ebd45224a1ef64785a9ed6aeb0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java#L102](https://github.com/ballerina-platform/ballerina-lang/blob/b7dfbd59f4a94ebd45224a1ef64785a9ed6aeb0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/types/BObjectType.java#L102)

[3]
[https://github.com/ballerina-platform/ballerina-lang/blob/b7dfbd59f4a94ebd45224a1ef64785a9ed6aeb0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java#L36](https://github.com/ballerina-platform/ballerina-lang/blob/b7dfbd59f4a94ebd45224a1ef64785a9ed6aeb0f/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/types/ObjectType.java#L36)

Currently [#2383](https://github.com/ballerina-platform/ballerina-standard-library/issues/2383) task is blocked due to this confusion.

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/33826
