### ISSUE TITLE
The trap  keyword is not suggested in block node context.

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33831]
**Description:**
`trap` keyword is not suggested in the following contexts.

![Screenshot from 2021-11-16 12-44-49](https://user-images.githubusercontent.com/35211477/141938362-78878bdd-f648-49fb-940d-e37b4b744cdf.png)

![Screenshot from 2021-11-16 12-46-47](https://user-images.githubusercontent.com/35211477/141938570-f967c780-b100-4aaa-a707-2b8723955590.png)

**Comment by malinthar** [comment]
Sub task of #33626

**Comment by malinthar** [comment]
Check for other keywords as well

**Comment by gayalkuruppu** [comment]
As per the offline discussion, we will not provide these keywords in module part context. But the missing expression related keywords will be added to the block node context.
