### ISSUE TITLE
Expression completion items are not suggested in trap expression context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33833]
**Description:**
```ballerina
public function main() {
      int|error myVar = getInt();
      trap 
}

function getInt() returns int|error {
    return 0;
}

trap <cursor>
```
At the cursor position depicted above, LS does not suggest expression completion items.
![Screenshot from 2021-11-16 12-54-17](https://user-images.githubusercontent.com/35211477/141939547-b6ccedfb-908b-4473-ade5-4c436ef1373c.png)

**Steps to reproduce:**
Try to get completions at the indicated cursor position using `cmd` + `space`

**Comment by malinthar** [comment]
Sub task of #33626

**Comment by gayalkuruppu** [comment]
@malinthar  Is this a valid use case for module level declarations? either for `trap-expr` or `trap-action`? [spec](https://ballerina.io/spec/lang/master/#module_level)

**Comment by malinthar** [comment]
> @malinthar Is this a valid use case for module level declarations? either for `trap-expr` or `trap-action`? [spec](https://ballerina.io/spec/lang/master/#module_level)

consider the following cases.

Case 1
```
var myvar = trap <cursor>

```
Case 2 : Forward typing 

```
 trap <cursor>
```
User can later assign this to a module-var. (eg: using the create-var code action).  You can refer the behavior of  check expression as well.

**Comment by gayalkuruppu** [comment]
If we are allowing those, I think we should allow these scenarios as well
consider the following case,

ex 1:
```
float x = 1.0;
let float x2 = x+x, float x3 = x*x in x2+x3;
```
<img width="407" alt="Screenshot 2021-11-24 at 12 30 43" src="https://user-images.githubusercontent.com/46120162/143190380-78b8f178-9c14-40e3-810f-a9806ba6ff5a.png">

1. first we should allow user to create a variable or ignore return value in the module-level similar to this
<img width="443" alt="Screenshot 2021-11-24 at 12 29 06" src="https://user-images.githubusercontent.com/46120162/143190245-25d547bd-0e40-413d-8e71-96de99ae3ee4.png">

2. We should give completions of those keywords like `let` in module-level

ex2 :
<img width="423" alt="Screenshot 2021-11-24 at 12 43 12" src="https://user-images.githubusercontent.com/46120162/143191880-afc72062-33cd-485c-bd38-4964865b923e.png">

<img width="449" alt="Screenshot 2021-11-24 at 12 43 56" src="https://user-images.githubusercontent.com/46120162/143191975-ba029f54-2d97-4164-9284-a43d98a7da84.png">

here as well we need to give `typeof` completion in module-level. I think there will be more fixes to do to the current implementation if we're allowing this. In that case, shall we move this to a new issue?

WDYT? @nadeeshaan @IMS94

**Comment by nadeeshaan** [comment]
I think, in this particular case, if we have `trap <cursor>` we can provide the completions since the user has done that. But we limited the expression context completions to maintain the consistency of the UX since some of the code actions are not working at top level and the diagnostics are not intuitive. So we do not get the user to that point

**Comment by gayalkuruppu** [comment]
> I think, in this particular case, if we have `trap <cursor>` we can provide the completions since the user has done that. But we limited the expression context completions to maintain the consistency of the UX since some of the code actions are not working at top level and the diagnostics are not intuitive. So we do not get the user to that point

what about this scenario?
```
public function main() {
    decimal aa = 1.0;
}
int a = 10;
typeof <cur>
```
Are we going to give completions for all these scenarios as well or `trap` is a special case?

**Comment by gayalkuruppu** [comment]
related discussion: https://github.com/ballerina-platform/ballerina-lang/discussions/34008

**Comment by IMS94** [comment]
Since we provide correct completions at <cursor> below:
```
function getInt() returns int|error {
    return 0;
}

int x = trap <cursor>
```
we won't be suggesting completions for the `expression` context in the `trap` expression at the module level.
