### ISSUE TITLE
No signature help for new expression

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33867]
**Description:**
$title and please refer the following

https://user-images.githubusercontent.com/1329674/142129392-af18a5de-eee3-4ce7-a803-a5e24da1b4c9.mp4

**Affected Versions:**
slBeta4-rc2 at least

**Comment by IMS94** [comment]
Checked this in 2201.2.0-SNAPSHOT. This is fixed now.
