### ISSUE TITLE
Service declaration does not infer type from listeners attach method

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#33873]
**Description:**
Lang issue related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2398

This is fine when only structural typing is at play, but then the service type of the listener attach method is a `distinct` object the service decl is force to use the `type reference` to say the desired type of the service.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/33842
