### ISSUE TITLE
Reported diagnostics have different line location in logs

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#33887]
**Description:**
$subject. Here the reported line location is row-1 and column -1. 

As seen in the hover, both error and hint are added for the same location but in logs, these have different line location.
<img width="781" alt="Screenshot 2021-11-17 at 16 44 54" src="https://user-images.githubusercontent.com/27669465/142190657-c53fcd88-80ad-4ecc-89ba-45d30ecae7bb.png">

**Comment by IMS94** [comment]
Since both diagnostics are shown for the same line in vscode (hover), only the line numbers printed in the console seems to be translated (0 based vs  1 based indexes) incorrectly.

**Comment by dulajdilshan** [comment]
When printing the diagnostics we convert the ranges to 1's based. Example: https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDiagnostic.java#L95-L112. How about doing the same thing for this? @niveathika

**Comment by niveathika** [comment]
These were created using [DefaultDiagnostic](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/DefaultDiagnostic.java) class, if this needs to be added on top of this, shouldn't we improve the interface? @dulajdilshan

**Comment by dulajdilshan** [comment]
> These were created using [DefaultDiagnostic](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/diagnostics/DefaultDiagnostic.java) class, if this needs to be added on top of this, shouldn't we improve the interface? @dulajdilshan
I think this is a valid point. How about adding another method to get the toString with 1's based?

**Comment by dulajdilshan** [comment]
Here, we can change the toString() of `Diagnostic` class. @hasithaa Is this possible?
