### ISSUE TITLE
The keyword outer is not suggested in query expression context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33888]
**Description:**
![outer](https://user-images.githubusercontent.com/35211477/142802086-fe140399-453d-40d8-b4c7-b16e852501f0.png)

At the cursor position `join`, `outer` keywords and `join clause` snippets are not suggested. 

**Steps to reproduce:**
```ballerina

function findNumOfAthletesBycountry() returns map<int> | error{
    stream<MedalStats, error?> medalStats = check getMedalStats();
    map<string> countByCountry = from var athlete in check getAthletes() o<cursor>
                                
}
```

**Related Issues (optional):**
#33862

**Comment by malinthar** [comment]
Sub task of #33628

**Comment by TharushiJay** [comment]
At cursor position, `join` and `join clause` snippets are suggested as below. 

<img width="881" alt="Screenshot 2021-11-26 at 16 09 49" src="https://user-images.githubusercontent.com/27485094/143568132-746f2745-3557-4231-8eba-3a3ab71a1d13.png">

Hence, only added completions for missing `outer` keyword in PR https://github.com/ballerina-platform/ballerina-lang/pull/34018.

**Comment by malinthar** [comment]
> At cursor position, `join` and `join clause` snippets are suggested as below.
> 
> <img alt="Screenshot 2021-11-26 at 16 09 49" width="881" src="https://user-images.githubusercontent.com/27485094/143568132-746f2745-3557-4231-8eba-3a3ab71a1d13.png">
> 
> Hence, only added completions for missing `outer` keyword in PR #34018.

Will you try the following
```
function findNumOfAthletesBycountry() returns map<int> | error{
    stream<MedalStats, error?> medalStats = check getMedalStats();
    map<string> countByCountry = from var athlete in check getAthletes()  <cursor>
                                
}
```

**Comment by TharushiJay** [comment]
> > At cursor position, `join` and `join clause` snippets are suggested as below.
> > <img alt="Screenshot 2021-11-26 at 16 09 49" width="881" src="https://user-images.githubusercontent.com/27485094/143568132-746f2745-3557-4231-8eba-3a3ab71a1d13.png">
> > Hence, only added completions for missing `outer` keyword in PR #34018.
> 
> Will you try the following
> 
> ```ballerina
> function findNumOfAthletesBycountry() returns map<int> | error{
>     stream<MedalStats, error?> medalStats = check getMedalStats();
>     map<string> countByCountry = from var athlete in check getAthletes()  <cursor>
>                                 
> }
> ```

Thanks for pointing it out! Fixed in PR https://github.com/ballerina-platform/ballerina-lang/pull/34018.
