### ISSUE TITLE
Suggest `ballerina/io` instead of `isolated` keyword as the first completion item

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#33893]
<img width="699" alt="Screen Shot 2021-11-17 at 3 21 27 PM" src="https://user-images.githubusercontent.com/2637328/142298421-87ea0685-6bf5-4644-8758-63345a58db92.png">

See the above image. The first item should be `ballerina/io` IMO.

**Comment by nadeeshaan** [comment]
This issue has been fixed in latest master and can only be seen in the SwanLake-Beta4. Hence closing
