### ISSUE TITLE
Inavlid suggestions when try outside a function

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#33896]
**Description:**

When try to get the suggestions for a stdlib module outside a function it gives invalid results. Inside the functions it gives correct suggestions.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/16300038/142380368-76c69593-f2f3-433f-ad5e-515727e1c006.png">

**Steps to reproduce:**

Refer to the video

https://user-images.githubusercontent.com/16300038/142380671-dd346c35-64f6-4fbf-9e8b-197b2ec351bf.mov

**Affected Versions:**

Tested with Beta4 RC2

**Comment by TharushiJay** [comment]
This has been fixed on master. Hence, closing the issue.

Please refer the video below,

https://user-images.githubusercontent.com/27485094/142801329-3394c13a-bf4f-4528-b358-5f8cba10aa0b.mov
