### ISSUE TITLE
Improve sorting in limit expression node context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33903]
**Description:**
![limit-clause](https://user-images.githubusercontent.com/35211477/142559183-03bd6357-88ab-403b-9910-81cb7bd0c4cf.png)

As depicted by the above capture, the expressions after `limit` keyword are not sorted correctly. According to the spec the expressions that are allowed in the said context should have a subtype of `int` . Those should be given the highest precedence. 

**Steps to reproduce:**
```ballerina
function findToptenCountriesByAthletes() returns error? {
    int zlimit = 10;
    string alimit = "";
    map<int> athletesByCountry = check findNumOfAthletesBycountry();
    string[] listResult = from [string,int] entry in athletesByCountry.entries() 
                     order by entry[1] 
                     limit  <cursor> select entry[0];
    
    io:println("Top 10 countries by number of Athletes: ");
    foreach string item in listResult {
              io:println("\t", item);
    }
}
```

**Affected Versions:**
slbeta4-rc2

**Comment by malinthar** [comment]
Subtask of #33628

**Comment by gayalkuruppu** [comment]
Blocked by #33121

**Comment by IMS94** [comment]
Reason/Complex because we were waiting for a new API from the semantic API to implement this.
