### ISSUE TITLE
Disable renaming `self` keyword

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#33902]
**Description:**
$title

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gayalkuruppu** [comment]
What should be the expected behaviour for the `main` keyword? @dulajdilshan @nadeeshaan

**Comment by dulajdilshan** [comment]
> What should be the expected behaviour for the `main` keyword? @dulajdilshan @nadeeshaan

IMO, the `main` is not a keyword, it is a default function name. `main` should be enabled for renaming.

**Comment by gayalkuruppu** [comment]
> > What should be the expected behaviour for the `main` keyword? @dulajdilshan @nadeeshaan
> 
> IMO, the `main` is not a keyword, it is a default function name. `main` should be enabled for renaming.

+1
