### ISSUE TITLE
Make diagnostic for the warning `this function should explicitly return a value` more descriptive

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#33909]
**Description:**
Diagnostic for the warning `this function should explicitly return a value` does not contain module information.

**Describe your problem(s)**

Consider a multi-module project which has files with the same name. The warning does not point to the actual file path including module details and leads to confusion.

Consider project https://github.com/Dilhasha/Testerina/tree/updated-test/Guide_Object_Mocking

When doing `bal build` it shows the following warning diagnostic.

`WARNING [main.bal:(39:42,39:49)] this function should explicitly return a value`

The warning is for a method in `main.bal` of a non-default module and that information is not available in the diagnostic.

**Describe your solution(s)**
Include module information or the relative path from the project root in the diagnostic for this warning.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Probably this should be reproducible for other cases as well.

**Comment by MaryamZi** [comment]
Let's use https://github.com/ballerina-platform/ballerina-lang/issues/34218 to track this.
