### ISSUE TITLE
Tooling support not working properly for included record parameters

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#33924]
**Description:**
The print functions of the log module (`printInfo()`, `printError()`, `printWarn()`, `printDebug()`) accept any number of key-value pairs that are included-record parameters. The values can be of `anydata` type, a function pointer or an error stack trace.

The following are the definitions and method signature.
```ballerina
# A value of anydata type, a function pointer, or an error stack trace.
public type Value anydata|Valuer|error:StackFrame[];

# A function that returns anydata type.
public type Valuer isolated function () returns anydata;

# Key-Value pairs that needs to be desplayed in the log.
#
# + msg - msg which cannot be a key
# + 'error - 'error which cannot be a key
public type KeyValues record {|
    never msg?;
    never 'error?;
    Value...;
|};

# Prints info logs.
# ```ballerina
# log:printInfo("info message", id = 845315)
# ```
#
# + msg - The message to be logged
# + 'error - The error struct to be logged
# + keyValues - The key-value pairs to be logged
public isolated function printInfo(string msg, error? 'error = (), *KeyValues keyValues) {
```

However, in the VS code, there is no information regarding the types of key-value pairs. See the attached image.

<img width="1173" alt="Screenshot 2021-11-20 at 15 25 04" src="https://user-images.githubusercontent.com/39085607/142722741-7c7096d4-7bfc-4a76-a7e7-14420d429a60.png">

**Affected Versions:**
SL Beta 4

**OS, DB, other environment details and versions:**
MacOS

**Comment by anupama-pathirage** [comment]
Created https://github.com/wso2/ballerina-plugin-vscode/issues/133 to track this issue.

**Comment by nadeeshaan** [comment]
Basically, adhering to the language semantics, we show the actual type definition of the parameter, which is `KeyValues`. In the signature help, that is shown highlighted. 
The expected UX is that the user can jump to the definition of the particular type definition while writing the variable and also we provide the auto-completions for the particular record's fields as well, for example as shown for the following context.

`log:printInfo("test", err, {<trigger completion here>});`

**Comment by prabushi** [comment]
Reopening the issue as this is related to the language server.

**Comment by IMS94** [comment]
Closing this since what LS shows is based on the definition of the lang lib function. However, currently the signature help shown is incorrect. Created #39525 to track that.
