### ISSUE TITLE
Missing completions after stream keyword and table keyword

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#33931]
**Description:**
![stream](https://user-images.githubusercontent.com/35211477/142805909-594ac03d-6161-4172-b9c2-f2c91ed9d6de.png)

A similar behavior is observed after table keyword as well. 

**Steps to reproduce:**
```ballerina
function queryTest() {
    int[] arr = [1,2,3];
    table <cursor>
}
```

**Affected Versions:**
slbeta4

**Comment by malinthar** [comment]
Sub-task of #33628

**Comment by malinthar** [comment]
Please refer https://ballerina.io/ballerina-spec/spec.html#section_6.35 for possible completions at the depicted cursor position.

**Comment by TharushiJay** [comment]
At cursor position `table <cursor>`, there are 2 possible behaviours. It can either be followed by a `row-type-parameter` to form a `table-type-descriptor` (https://ballerina.io/ballerina-spec/spec.html#table-type-descriptor) or a `key-specifier` to form a `query-construct-type` (https://ballerina.io/ballerina-spec/spec.html#query-construct-type) 

Honoring the parsers’ decision to identify node at cursor as `TableTypeDescriptorNode` and resolving to `TableTypeDescriptorNodeContext` (for a `table-type-descriptor`), completions cannot be provided for a `key-specifier` to form a `query-construct-type`.

Similarly, `stream <cursor>` can form either a `stream-type-descriptor` (https://ballerina.io/ballerina-spec/spec.html#stream-type-descriptor) or a `query-construct-type` (https://ballerina.io/ballerina-spec/spec.html#query-construct-type). Therefore, completions cannot be provided after `stream` keyword as well.

Hence, closing this issue.
