### ISSUE TITLE
[Semantic API] `typeOf()` works for the whole named-arg node

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#33944]
Consider the following:
```ballerina
foo(name, <1>age = <2>val<3>);
```
Currently `typeOf()` works for `(1, 3)` as well. But it should only work for `(2, 3)`.

**Comment by dulajdilshan** [comment]
In the compiler, We model named-arg as an expression. Shouldn't this be a non-expression node? @pubudu91 @mohanvive 

Ref: https://ballerina.io/spec/lang/master/#named-args

**Comment by pubudu91** [comment]
> In the compiler, We model named-arg as an expression. Shouldn't this be a non-expression node? @pubudu91 @mohanvive
> 
> Ref: https://ballerina.io/spec/lang/master/#named-args

Yes, it shouldn't have been modelled as an expression.

**Comment by pubudu91** [comment]
Fixed with #34310
