### ISSUE TITLE
K8s load tests fail when there is `lock` in the execution flow

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#33952]
**Description:**
During a load test in Kubernetes, an error rate was observed for higher concurrent users (20 and above) when there is a single or multiple `lock` syntax in the execution flow. After a few minutes (2-3 minutes) the tests are started, there is an increasing error rate, and `Read timed out` logs get printed in the JTL output.

Here are the summary test specifications and the observations:

Test duration: 15 mins
Payload size: 50 bytes

Container specifications ([c2c properties](https://ballerina.io/learn/running-ballerina-programs-in-the-cloud/code-to-cloud-deployment/#clouddeployment)):
```toml
[cloud.deployment]
min_memory="256Mi"
max_memory="512Mi"
min_cpu="200m"
max_cpu="1000m"
```

| Concurrent users | Errors |
|---|---|
| 5 | NO |
| 10 | NO |
| 20 | YES |
| 30 | YES |

**Steps to reproduce:**
1. Clone and build the sample project.
    https://github.com/ldclakmal/ballerina-samples/tree/master/load-tests/locks
2. Build and push the Docker image.
    ```shell
    docker build -t ldclakmal/ballerina-locks:latest target/docker/ballerina_locks
    docker push ldclakmal/ballerina-locks:latest
    ```
3. Deploy it in k8s.
    ```shell
    kubectl apply -f ./target/kubernetes/ballerina_locks
    kubectl expose deployment ballerina-locks-deployment --type=NodePort --name=ballerina-locks-svc-local
    ```
4. Check the `NodePort` of the service.
    ```shell
    kubectl get svc
    ```
5. Run the load test (assign the `NodePort` for the `-Jport` argument).
    ```shell
    jmeter -n -t ./resources/http-post-request.jmx -l original.jtl -Jusers=30 -Jduration=600 -Jhost=localhost -Jprotocol=http -Jpath=foo -Jresponse_size=50 -Jpayload="./resources/50B.json" -Jport=<NodePort>
    ```

The JMeter output summary log will keep running for a few minutes (2-3 minutes) and then it can be seen with an increasing error rate. Refer to the following output samples.

**JMeter Log**
```shell
Creating summariser <summary>
Created the tree successfully using http-post-request.jmx
Starting standalone test @ Tue Nov 23 11:08:58 IST 2021 (1637645938606)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
Warning: Nashorn engine is planned to be removed from a future JDK release
summary +      1 in 00:00:05 =    0.2/s Avg:  5237 Min:  5237 Max:  5237 Err:     0 (0.00%) Active: 3 Started: 3 Finished: 0
summary +    764 in 00:02:27 =    5.2/s Avg:  2795 Min:     8 Max: 120029 Err:    17 (2.23%) Active: 30 Started: 30 Finished: 0
summary =    765 in 00:02:32 =    5.0/s Avg:  2798 Min:     8 Max: 120029 Err:    17 (2.22%)
summary +     30 in 00:02:00 =    0.2/s Avg: 120010 Min: 120004 Max: 120020 Err:    30 (100.00%) Active: 30 Started: 30 Finished: 0
summary =    795 in 00:04:32 =    2.9/s Avg:  7221 Min:     8 Max: 120029 Err:    47 (5.91%)
```

**JTL Output**
The following logs can be seen in the `.jtl` output file:
```shell
timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect
1637324448823,2496,HTTP Request,200,OK,Users 1-3,text,true,,179,938,4,4,http://localhost:31123/foo,2486,0,1
1637324445002,6317,HTTP Request,200,OK,Users 1-1,text,true,,179,938,4,4,http://localhost:31123/foo,6308,0,25
...
...
1637324557882,103,HTTP Request,200,OK,Users 1-11,text,true,,179,938,30,30,http://localhost:31123/foo,103,0,0
1637324557809,120018,HTTP Request,Non HTTP response code: java.net.SocketTimeoutException,Non HTTP response message: Read timed out,Users 1-14,text,false,Test failed: text expected to contain /50/,2620,0,30,30,http://localhost:31123/foo,0,0,0
1637324557809,120018,HTTP Request,Non HTTP response code: java.net.SocketTimeoutException,Non HTTP response message: Read timed out,Users 1-24,text,false,Test failed: text expected to contain /50/,2620,0,30,30,http://localhost:31123/foo,0,0,0
1637324557802,120025,HTTP Request,Non HTTP response code: java.net.SocketTimeoutException,Non HTTP response message: Read timed out,Users 1-4,text,false,Test failed: text expected to contain /50/,2620,0,30,30,http://localhost:31123/foo,0,0,0
1637324557809,120018,HTTP Request,Non HTTP response code: java.net.SocketTimeoutException,Non HTTP response message: Read timed out,Users 1-6,text,false,Test failed: text expected to contain /50/,2620,0,30,30,http://localhost:31123/foo,0,0,0
1637324557807,120020,HTTP Request,Non HTTP response code: java.net.SocketTimeoutException,Non HTTP response message: Read timed out,Users 1-9,text,false,Test failed: text expected to contain /50/,2620,0,30,30,http://localhost:31123/foo,0,0,0
...
...
...
```

Sample output logs can be found: https://github.com/ldclakmal/ballerina-samples/tree/master/load-tests/locks/resources/logs

**Tested Version:**
Ballerina SwanLake Beta4-RC3

**OS, DB, other environment details and versions:**
MacOS Monterey
Version 12.0.1
MacBook Air (M1, 2020)

**Comment by warunalakshitha** [comment]
IS this only happen in K8s. I mean can we reproduce the same in the local machine.

**Comment by ldclakmal** [comment]
> @ldclakmal Is this only happen in K8s. I mean can we reproduce the same in the local machine.

I didn't try to reproduce in local machine. But I hope this can be reproduced for a higher number of concurrency users depending on the specifications of the machine.

On a separate note, this behaviour was there for sometime after the Swan Lake `lock` implementation AFAIR. Because, we observed the same behaviour in AWS VM performance tests as we were using locks for `ballerina/cache` implementation.

**Comment by HindujaB** [comment]
This is the load test results done in my local linux machine. 
environment :
Ubuntu 20.04.3 LTS
openjdk 11.0.8 2020-07-14
minikube version  v1.21.0
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
properties : 
duration - 900s
protocol - http 
response-size - 50 bytes
json payload - `{"size":"50B","payload":["0123456789","ABCDEFGH"]}` (As in the file `/resources/50B.json`)

Results (error rate) : 
| Concurrent users | beta 4 | beta 5 | beta 6 |
|:----------------:|:------:|--------|--------|
| 5                | 0%     | 0%     | 0%     |
| 10               | 0%     | 0%     | 0%     |
| 20               | 0%     | 0%     | 0%     |
| 30               | 0%     | 0%     | 0%     |
| 40               | 0%     | 0%     | 0%     |
| 50               | 0%     | 0%     | 0%     |

Could this be specific to MacOS? @ldclakmal

**Comment by ldclakmal** [comment]
Did a test on Azure K8S cluster and could not reproduce the issue. This can be related to MacOS, will check and confirm again. Hence closing the issue.
