### ISSUE TITLE
Make `--target-dir` flag work with `bal test`

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33954]
`bal test --target-dir myTmp` gives following error.
```
ballerina: unknown option: '--target-dir'
Run 'bal help' for usage.
```

**Comment by manuranga** [comment]
Came across during https://github.com/ballerina-platform/nballerina/pull/720

**Comment by manuranga** [comment]
Please create new issues or extend this issue to include `clean` and `run` as well.

**Comment by Ibaqu** [comment]
Issue to track adding `--target-dir` flag to `clean` and `run` command : https://github.com/ballerina-platform/ballerina-lang/issues/34000
