### ISSUE TITLE
Requesting approach for accessing the service distinct type for service declaration node

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#34011]
**Description:**
Need to access service class details through the semantic model when the service has written as with service declaration 
 ```ballerina
import ballerina/http;
service / on new http:Listener(9090) {
      // mock implementation 
 }
```

Earlier, we were supposed to check the service is related to the http module by checking its listener module type but with the help of [the new implement](https://github.com/ballerina-platform/ballerina-standard-library/issues/2398), it would be easy for developing other compiler plugins, if we can get details from directly its class.
Going through the current serviceNodeDeclaration and accessing its symbol was unable to capture any details regarding the class details to the above example.
Did some accessing its parent node using Semantic Model and Syntax tree as well, That time it gives an empty symbol.
Could you please let us if there is a way to access class details without reaching listeners type checking ?

**Related Issues (optional):**
https://github.com/ballerina-platform/openapi-tools/issues/749

**Comment by pubudu91** [comment]
The above is not possible since a service decl being modelled as a class is an implementation detail. From an API perspective, service decls and service classes need to be treated as 2 separate constructs, as defined by the spec. Hence closing this issue.
