### ISSUE TITLE
Checking expressions should support arbitrary expressions

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#34014]
according to [spec](https://ballerina.io/spec/lang/2021R1/#checking-expr) checking expression can be used with any expression. But currently it expect expression to be a call expression.

Both of the fallowing should produce the same output

```
public function main() {
    error? a = test();
    checkpanic a;
}

function test() returns error? {
    return error("test");
}
```

and 
```
public function main() {
    checkpanic test();
}

function test() returns error? {
    return error("test");
}
```

but 1st produce error 
```
ERROR [main.bal:(3:16,3:17)] invalid expression, expected a call expression
error: compilation contains errors
```
while only 2 produce the expected result
```
error: test
	at main:test(main.bal:6)
	   main:main(main.bal:2)
```

**Comment by lochana-chathura** [comment]
Under the [statements](https://ballerina.io/spec/lang/master/#statement) in spec `expression ;` is not a valid statement. Only `action ;`(action-stmt) is valid.
But with [call-stmt](https://ballerina.io/spec/lang/master/#call-stmt) only `function-call-expr` and `method-call-expr` allowed with `checking-keyword`.

Hence 1st sample is not syntactically valid.
