### ISSUE TITLE
Cannot use objects own methods via self

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#34035]
**Description:**

```Ballerina
final int i = 100;

type Sum2 function (int x, int y) returns int;

final Sum2 sumF = function(int x, int y) returns int {
    return x + y;
};

class C1 {
    Sum2 func = sumF;

    function summer() returns int {
        return self.func(4, i);
    }
}
```

```LogTalk
ERROR [f2.bal:(13:16,13:26)] undefined function 'func'
```

**Steps to reproduce:**

**Affected Versions:**
master

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
If I'm not mistaken this PR add this https://github.com/ballerina-platform/ballerina-lang/pull/31589
@chiranSachintha  please confirm.
