### ISSUE TITLE
Improve change return type code action to add optional error for check expression

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34036]
**Description:**
Consider the following scenario where I have a check expression. 

```ballerina
public function main() {
      var myvar = check mod1:find<cursor>Num();
}
```
Currently there there is no code action suggested in the depicted  range  to change the return type descriptor of the enclosing function to `error?`.

To accommodate the above requirement we can extend the `Change Return Type` code action to support  the diagnostic `BCE3032`. 

![error](https://user-images.githubusercontent.com/35211477/143824766-a802209e-55e6-420c-9dfb-e8d75c7c09e7.png)

**Comment by IMS94** [comment]
Shall we take this post GA? Such code action will be very useful. @nadeeshaan

**Comment by gayalkuruppu** [comment]
@IMS94 @malinthar @TharushiJay  For an scenario like the following, is it neccessary to have the optional? Don't we need to provide both the options? 
```
public function name() returns int {
    var myvar = check findNum();
    return myvar;
}

function findNum() returns int|error { 
    return 0;
}
```
