### ISSUE TITLE
Test handling of type reference types in different compiler phases and add more tests where required

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#34073]
**Description:**
$title, we came across several issues due to type reference types not being handled in certain places.

- https://github.com/ballerina-platform/ballerina-lang/issues/34032
- https://github.com/ballerina-platform/ballerina-lang/issues/34033
- https://github.com/ballerina-platform/ballerina-lang/issues/34038
- https://github.com/ballerina-platform/ballerina-lang/issues/34035

Creating this task to proactively identify any other places we may have missed.

**Comment by KRVPerera** [comment]
- https://github.com/ballerina-platform/ballerina-lang/issues/35107
- https://github.com/ballerina-platform/ballerina-lang/issues/35105
- https://github.com/ballerina-platform/ballerina-lang/issues/35108
