### ISSUE TITLE
`cloneWithType` should not panic in some cases with int subtypes

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#34082]
**Description:**

In the below cases `cloneWithType` should not panic because values 1, 2, 3 belong to all the int subtypes and hence `cloneWithType` does not require any conversion. So it should pass and should not panic.
```bal
public function main() {
    int[] x = [1, 2, 3];
    (int|decimal)[] e1 = checkpanic x.cloneWithType(); // does not panic, correct behaviour
    (byte|float)[] e2 = checkpanic x.cloneWithType(); // panics, but should not 
    (int:Unsigned8|float)[] e3 = checkpanic x.cloneWithType(); // panics, but should not 
    (int:Signed8|decimal)[] e4 = checkpanic x.cloneWithType(); // panics, but should not 
    (decimal|int:Signed16)[] e5 = checkpanic x.cloneWithType(); // panics, but should not 

    byte[] y = [1,2,3];
    (byte|float)[] p1 = checkpanic y.cloneWithType(); // does not panic, correct behaviour
    (int|float)[] p2 = checkpanic y.cloneWithType(); // panics, but should not 
    (int:Unsigned8|float)[] p3 = checkpanic y.cloneWithType(); // panics, but should not 

    int:Signed16[] z = [1, 2, 3];
    (int|float)[] q1 = checkpanic z.cloneWithType(); // does not panic, correct behaviour
    (byte|float)[] q2 = checkpanic z.cloneWithType(); // panics, but should not
    (int:Signed32|float)[] q3 = checkpanic z.cloneWithType(); // panics, but should not
}
```
Should also consider the other remaining cases of int subtypes not shown above.

**Steps to reproduce:**

**Affected Versions:**
Ballerina Swan Lake Beta 5 - snapshot

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment]
Another issue is that if we write a code like this,
```bal
public function main() {
   byte[] z = [1, 2, 3];
   (decimal|float)[] l = checkpanic z.cloneWithType();
}
```
it gives the following error message which is not right.
```logtalk
error: {ballerina/lang.value}ConversionError {"message":"'byte[]' value cannot be converted to '(decimal|float)[]': 
                array element '[0]' should be of type '(decimal|float)', found '1'
                array element '[1]' should be of type '(decimal|float)', found '2'
                array element '[2]' should be of type '(decimal|float)', found '3'"}
        at ballerina.lang.value.0:cloneWithType(value.bal:86)
           temp:main(temp.bal:5)
```

The error message should point out the conversion is failed because of ambiguous target type.

**Comment by gabilang** [comment]
> Another issue is that if we write a code like this,
> 
> ```ballerina
> public function main() {
>    byte[] z = [1, 2, 3];
>    (decimal|float)[] l = checkpanic z.cloneWithType();
> }
> ```
> 
> it gives the following error message which is not right.
> 
> ```logtalk
> error: {ballerina/lang.value}ConversionError {"message":"'byte[]' value cannot be converted to '(decimal|float)[]': 
>                 array element '[0]' should be of type '(decimal|float)', found '1'
>                 array element '[1]' should be of type '(decimal|float)', found '2'
>                 array element '[2]' should be of type '(decimal|float)', found '3'"}
>         at ballerina.lang.value.0:cloneWithType(value.bal:86)
>            temp:main(temp.bal:5)
> ```
> 
> The error message should point out the conversion is failed because of ambiguous target type.

Addressed this issue with the PR https://github.com/ballerina-platform/ballerina-lang/pull/34136
