### ISSUE TITLE
Suggestions for outside variables are not showing inside a stream iteration

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#34105]
**Description:**
When I tried to iterate a stream using `strm.forEach()`, the VSCode suggestions only appear for variables inside the function. The outside variables which we tend to use in generic cases are not suggested. For example, as below, there is a suggestion for `var1`, but no suggestion for `var0`.

<img width="424" alt="Screenshot 2021-12-02 at 14 46 37" src="https://user-images.githubusercontent.com/18663444/144394029-d40e52b6-72c2-4edd-a722-dad222bb5e34.png">

**Steps to reproduce:**

Follow the aforementioned steps.

**Affected Versions:**
- Ballerina Swan Lake Beta 05
- VSCode Ballerina plugin `v2.1.1`
- VSCode version: 1.62.3
- macOS

**Comment by nadeeshaan** [comment]
As per the initial observation, the `visibleSymbols` API does not capture the symbol.
