### ISSUE TITLE
Rewrite the AST to detect the `qualifed-identifier` at symantic analyzer in partially written `conditional-expr`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34145]
**Description:**
$subject as proposed by @hasithaa 

Consider the below code,
```
function printIfTrue(boolean b) {
    boolean c = b ? io:pr<cursor> // syntacatically this is a valid conditional-expr
}
```
With PR #34133, the above is special-cased from the LS side and required completions are given. After triggering the completions diagnostics are not that good due to the way we parse it. 

We can improve the diagnostic by doing $subject.

**Comment by gayalkuruppu** [comment]
Even after the fix #34133 we get the following diagnostics as @lochana-chathura mentioned in the Description

Case 1: Usual behavior for qualified-identifier

<img width="809" alt="Screenshot 2021-12-03 at 16 39 08" src="https://user-images.githubusercontent.com/46120162/144801707-0772fb38-5c18-45ea-9f8d-20295295327c.png">

Case 2: qualified-identifier inside a conditional-expr

<img width="702" alt="Screenshot 2021-12-03 at 16 39 39" src="https://user-images.githubusercontent.com/46120162/144801720-335cdfb3-b2bc-4b95-b933-94dc39b59d3a.png">
