### ISSUE TITLE
Missing create variable code action for error expression and byte-array-literal

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#34141]
**Description:**
$Title

**Steps to reproduce:**
<img width="659" alt="Screenshot 2021-12-03 at 18 20 32" src="https://user-images.githubusercontent.com/46120162/144788965-d87c0005-d245-4292-b0e0-d3d7468fac7b.png">

<img width="696" alt="Screenshot 2021-12-03 at 18 21 28" src="https://user-images.githubusercontent.com/46120162/144798591-d025e840-8f54-49df-b075-1109646e4167.png">

**Comment by nadeeshaan** [comment]
Shouldn't we get the `Variable assignment required` diagnostic at the first place?

**Comment by gayalkuruppu** [comment]
@nadeeshaan  Is there a way that we can get a `variable assignment required` diagnostic, so we can provide related code actions?

**Comment by nadeeshaan** [comment]
> @nadeeshaan Is there a way that we can get a `variable assignment required` diagnostic, so we can provide related code actions?

@gayalkuruppu that should be provided by the compiler.  So at the first place we should try to handle this from the compiler if possible. 
@MaryamZi @hasithaa any thoughts on this?

**Comment by MaryamZi** [comment]
In both cases, IINM, they don't seem to be recovered as expressions. Instead they seem to be recovered as an if statement and a destructuring assignment statement (with an error binding pattern), which is why we don't get the "variable assignment required" diagnostic.

Looping in @lochana-chathura and @rdulmina also.

**Comment by rdulmina** [comment]
Parser currently does not provide the diagnostic to support `create variable code action` for every expression. This should be fixed with #29091 but it is a nontrivial task. A related issue #29779.

**Comment by rdulmina** [comment]
Closing this issue since we have #29091 to track this. Please feel free to reopen.
