### ISSUE TITLE
[LS] Workspace manager proxy doesn't support bala URI scheme

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34146]
**Description:**
We introduced `bala` URI scheme in https://github.com/ballerina-platform/ballerina-lang/pull/32870. With the workspace manager proxy, we have added a new layer above the workspace manager named the `WorkspaceManagerProxy`. It should be updated to handle the `bala` URI scheme.

Otherwise this will throw errors for `didOpen`, `didClose` events when a langlib/stdlib file is opened (via goto ref) and goto def/references do not work in lang lib/std lib files.

**Steps to reproduce:**
See description.

**Affected Versions:**
SL Beta6 Snapshot

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
