### ISSUE TITLE
Missing visible symbols in let expression

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#34144]
**Description:**
$Title

**Steps to reproduce:**
<img width="596" alt="Screenshot 2021-12-03 at 10 27 23" src="https://user-images.githubusercontent.com/46120162/144798935-abf8cb0b-cef5-4294-ba40-432956515c39.png">

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/33236

**Comment by mohanvive** [comment]
The issue is no longer reproducible in the master.

**Comment by mohanvive** [comment]
@gayalkuruppu
