### ISSUE TITLE
Bug in diagnostic reporting when compiling a module with a syntax error for the second time

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#34159]
**Description:**

When a new document is added to a module that has syntax errorsform an existing file, the expected diagnostic in the existing document is not reported.

**Steps to reproduce:**

Try the below test case
1 Create a project and add following content to main.bal:
```bal
public function main() {
}
; // expected syntax error - invalid token ";"
```
2. Write the below test case and execute:
```java
 @Test
  public void temp() {
     // load the package, compile and verify diagnostics
     Project project = ProjectLoader.loadProject(Paths.get(<bal-project-with-syntax-error>));
     PackageCompilation compilation1 = project.currentPackage().getCompilation();
     Assert.assertEquals(compilation1.diagnosticResult().errorCount(), 1);

     // Add another bal document (this doesn't have any errors)
     DocumentId documentId = DocumentId.create("foo.bal", project.currentPackage().getDefaultModule().moduleId());
     DocumentConfig documentConfig = DocumentConfig.from(documentId, "public function hello() {}", "foo.bal");
     Module newModule = project.currentPackage().getDefaultModule().modify().addDocument(documentConfig).apply();
        
     // Recompile and verify diagnostics
     PackageCompilation compilation2 = project.currentPackage().getCompilation();
     Assert.assertEquals(compilation2.diagnosticResult().errorCount(), 1); // failing
    }
```
**Affected Versions:**
SL Beta.5 at least

**Comment by azinneera** [comment]
The issue `io.ballerina.cli.cmd.BuildCommandTest.testBalFileWithSyntaxError` should be enabled.

**Comment by pubudu91** [comment]
Had a discussion with Asma regarding this. The issue seems to be due to using the node cloner right at the beginning of the compilation method. Since the syntax issue reporting logic is right after it, this seems to result in syntax diagnostics getting dropped. I think doing the syntax diagnostic reporting before cloning should fix the issue.
