### ISSUE TITLE
Behaviour of the `UnionTypeSymbol.memberTypeDescriptors()` API broken

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34155]
$subject due to #34130. Note that this is a broken behaviour of a public API.

**Comment by dulajdilshan** [comment]
@pubudu91 Can you please provide more information?

**Comment by mohanvive** [comment]
@pubudu91 Need more info on this issue, please?

**Comment by pubudu91** [comment]
Sorry, missed this. This should be fine as per https://github.com/ballerina-platform/ballerina-lang/pull/34130#discussion_r762887757
