### ISSUE TITLE
Type narrowing after return: type doesn't get narrowed when `==` is used

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#34160]
**Description:**
```ballerina
function foo(int? i) {
    if i == () {
        return;
    }
    int j = i; // Type doesn't narrow when `==` is used
}

function bar(int? i) {
    if i is () {
        return;
    }
    int j = i;
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34664
