### ISSUE TITLE
Comments get duplicated when "Remove 'check' keyword" code action is applied

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#34170]
**Description:**
$title

**Steps to reproduce:**
Please consider the following screencast.

https://user-images.githubusercontent.com/19838787/144962489-3321a6ff-606c-4780-8e34-4b2b897bae18.mp4

**Affected Versions:**
slbeta4

**Comment by malinthar** [comment]
Closing as this is not reproducible in the latest version
