### ISSUE TITLE
Getting incorrect TypeDescriptor value 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-lang#34172]
**Description:**
Ideally this should give the TypeDescriptor value for `nats:Message`. Instead it is returning a `RecordTypeSymbol`. 
<img width="931" alt="Screen Shot 2021-12-07 at 10 31 27 AM" src="https://user-images.githubusercontent.com/39673615/144969646-1271975a-9abd-419b-8522-e216c92fb3fa.png">

**Ballerina Code:**
```ballerina
import ballerinax/nats;

listener nats:Listener subscription = new(nats:DEFAULT_URL);
type Foo nats:Message;

@nats:ServiceConfig {
    subject: "demo.bbe.*"
}
service nats:Service on subscription {

    remote function onMessage(Foo message) {
    }
}
```
**Native Code Validation**
https://github.com/ballerina-platform/module-ballerinax-nats/blob/b3a8c38b4af2f151992f56afa80d450537a3b615/compiler-plugin/src/main/java/io/ballerina/stdlib/nats/plugin/NatsFunctionValidator.java#L159

**Affected Versions:**
Ballerina Lang : 2.0.0-beta.6-20211206-152800-07b307e2

**Comment by pubudu91** [comment]
Fixed with #34177. Hence closing.
