### ISSUE TITLE
Ballerina cannot be exposed as a SOAP web service

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3418]
**Usecase**
A client sends a SOAP request to a service and expects the response as a SOAP message

**Issue**
Ballerina cannot handle SOAP messages out of the box. Need to send the soap message as a HTTP payload.

**Comment by riyafa** [comment]
This is currently possible using the [soap connector](https://github.com/wso2-ballerina/package-soap).
