### ISSUE TITLE
[Documentation] Provide environment-specific instructions in "Ballerina by Example" examples 

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerina-platform/ballerina-lang#3419]
In [1], the command which we need to to use to run the program is given as:

$ ballerina run hello-world.bal

In Linux environments, this should be either one of following:
$ sh ballerina run hello-world.bal
$ ./ballerina run hello-world.bal

This may confuse a user who is trying to run his first Ballerina program. This issue is there in all of the 'Ballerina by Example' examples. 

[1] https://ballerinalang.org/docs/by-example/hello-world

**Comment by samgnaniah** [comment]
Assign to me.

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-examples/issues/803 to track this
