### ISSUE TITLE
Project does not get updated when a module is deleted on ubuntu

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34198]
**Description:**

Open a multi-module project using vscode and add a import statement for one of sub-modules as follows. 

```ballerina
import project1.mod1;

public function main() {

}

```
Now try deleting  the `mod1` module and check if the diagnostics, completions are correct. It seems that the project does not get updated when the module is deleted. 

The cause of the issue seems to be how the didChangedWatched() method handles events. It updates the project when there is only one change. 
https://github.com/ballerina-platform/ballerina-lang/blob/a91fcae07236692df6c0b045e0fde95525f54b95/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java#L418-L436

On ubuntu, three `Delete` change events for each file that were  in the mod1  directory are sent, where as on mac only a single `directory Delete` change is event sent. Hence, this is only reproducible on ubuntu atm. 

**Steps to reproduce:**
Mentioned above

**Affected Versions:**
slbeat6-rc1

**Comment by IMS94** [comment]
Closing this since this is now fixed. Verified in 2201.4.0-SNAPSHOT
