### ISSUE TITLE
Compiler gives ambiguous type error for valid XML unions

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#34207]
**Description:**
$title

**Steps to reproduce:**
`xml<xml:Text>|xml<xml:Comment>|xml x13 = xml `text1`;
`

**Comment by MaryamZi** [comment]
Can't seem to reproduce this on 2201.0.1.

**Comment by KavinduZoysa** [comment]
FIxed in `Ballerina 2201.3.0`. Therefore closing the issue.
