### ISSUE TITLE
Revisit `call-stmt` validation at parser level

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34200]
**Description:**
Currently for `check expr;` when the `expr` is not a ` function-call-expr` or `method-call-expr` we marked the expr as invalid and create a `function-call-expr` as the expression.

This was introduced with PR #29282 based on issue #28769. IIRC, we did this validation at the parser level, because there was a complication when handling it at compiler phases.

Since we make the `expr` invalid this could be a problem for LS to give suggestions when writing `check-expr` without varaible assignments. And also to provide create variable code action.

e.g.
```bal
function findNumOfAthletesByCountry() returns map<int>|error {
    map<int> countByCountry = {};
    check from var athlete in check getAthletes() <cursor>}
```

**Comment by IMS94** [comment]
Cases like `check (getInt() * 100);` works fine with the `Create variable code action`. Therefore, the impact of this to LS can be considered very low. Additionally LS now uses a CodeActionNodeValidator visitor which verifies if the node in focus is syntactically correct.

Therefore, closing this issue.
