### ISSUE TITLE
Update Syntax API accroding to new spec definition for array type descriptor

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34210]
**Description:**

Previously spec defines array type desc as 
>array-type-descriptor := member-type-descriptor [ [ array-length ] ]
member-type-descriptor := type-descriptor

with https://github.com/ballerina-platform/ballerina-spec/issues/1001#issuecomment-984421775 it is updated as follows. Need to update the Syntax API accordingly.

>array-type-descriptor := array-member-type-descriptor array-dimension+
array-dimension := [ [ array-length ] ]
array-member-type-descriptor := type-descriptor but not array-type-descriptor

**Comment by lochana-chathura** [comment]
Old structure: https://gist.github.com/lochana-chathura/5d2cfb5d5432ce53ed52447c8770812f
New structure: https://gist.github.com/lochana-chathura/f8c13d2738dc3089f2591a27ffe734d6

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34322
