### ISSUE TITLE
Quick fix code action issue when the erroneous is enclosed with parenthesis 

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#34212]
**Description:**
The quick fix result in error.
<img width="764" alt="Screenshot 2021-12-08 at 15 13 02" src="https://user-images.githubusercontent.com/5234623/145186142-19ee7d28-3ad0-4923-af76-23605750f677.png">

Expected
<img width="784" alt="Screenshot 2021-12-08 at 15 13 19" src="https://user-images.githubusercontent.com/5234623/145186172-65081fb0-a059-446a-8815-476c461e1c55.png">

**Steps to reproduce:**

1. Create a service 
2. Add the following code segment to the service

```
import ballerina/http;

service / on new http:Listener(8090) {
    resource function get route(@http:Header {name: "x-item"} string headerValue) returns json|error {
        http:Client locationEP = check new ("https://samples.choreoapps.dev/company/hr");

        string path = headerValue == "employee" ? "/employee/1" : "/department/1";
        json response = check locationEP->get(path);
        json mappedValue = {title:"",fullname: (response.firstName).toString()}
        return response;
    }
}
```
4. Add the quick fix 
5. The check statement added does not fix the issue

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
