### ISSUE TITLE
[Documentation] Cannot go to the previous example in ballerina-by-example

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3421]
**Issue**
If you go to multiple examples in [1] and try to go to the previous example, you cannot do so. You need to go to Home and select the sample again

[1] https://ballerinalang.org/docs/by-example/

**Comment by samgnaniah** [comment]
Assign to Madhura.

**Comment by manuranga** [comment]
@dilinisg is this fixed now ? I don't understand what you mean by this.

**Comment by dilinisg** [comment]
Hi,
This means you don't have an option to go back in the site.

**Comment by manuranga** [comment]
Ah, ok , got it. I thought browser back button didnt work.

**Comment by uthaiyashankar** [comment]
These pages are going through major changes. It is already fixed in the new design. Hence, will not fix for the existing pages.
