### ISSUE TITLE
Destructuring not supported with a value of static type of a type-reference

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#34211]
**Description:**
```ballerina
type T [int, int];

public function main() {
    T t = [1, 1];
    var [a, b] = t;  // compiler error here: looks like we haven't flaten the type-reference here.

    [int, int] v = [1, 1];
    var [c, d] = v; // this is fine
}
```

**Steps to reproduce:**

**Affected Versions:**
Beta6 RC1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34220.
