### ISSUE TITLE
LS stopped working after changing the package name in Ballerina.toml

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34216]
**Description:**
All LS functionalities stopped working after $subject. In the output channel the following stack trace can be seen.

![current](https://user-images.githubusercontent.com/35211477/145191121-c8896623-77f8-4b4c-8d6d-df7586e7be29.png)

The issue seems to be in the documentId() method in the BuildProject class in line 175 as depicted below. This occurs  moduleId.moduleName() not containing the new package name. Instead it consists of the older package name. 

https://github.com/ballerina-platform/ballerina-lang/blob/a91fcae07236692df6c0b045e0fde95525f54b95/compiler/ballerina-lang/src/main/java/io/ballerina/projects/directory/BuildProject.java#L167-L179

**Steps to reproduce:**
Create a package/project named `myproject` and change the package name as follows in the Ballerina.toml file.
```toml
[package]
distribution = "slbeta6"
org="acer"
name="myprojec"

[build-options]
observabilityIncluded = true

```

Additional attachment
![save1](https://user-images.githubusercontent.com/35211477/145193054-102c2aa8-1ea3-4120-b194-dac7329d99f1.png)

**Affected Versions:**
slbeta6-snapshot

**Comment by azinneera** [comment]
`Ballerina.toml` cannot be accessed like a normal document. The `BuildProject.document()` method is for the `.bal` files. `Ballerina.toml` should be accessed as `project.currentPackage().ballerinaToml()`. IMHO, the implementation in BallerinaWorkSpaceManager should be updated to handle this.

Modification of Ballerina.toml should be done as follows:
```java
project.currentPackage().ballerinaToml().get().modify().withContent(<newContent>).apply();
```

**Comment by malinthar** [comment]
> `Ballerina.toml` cannot be accessed like a normal document. The `BuildProject.document()` method is for the `.bal` files. `Ballerina.toml` should be accessed as `project.currentPackage().ballerinaToml()`. IMHO, the implementation in BallerinaWorkSpaceManager should be updated to handle this.
> 
> Modification of Ballerina.toml should be done as follows:
> 
> ```java
> project.currentPackage().ballerinaToml().get().modify().withContent(<newContent>).apply();
> ```

Could you point me to the said usage. It seems that we are already using the approach use suggested.

https://github.com/ballerina-platform/ballerina-lang/blob/a91fcae07236692df6c0b045e0fde95525f54b95/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java#L800-L834

**Comment by azinneera** [comment]
Sorry, I misunderstood the issue since the locally reproduced error for me was coming from Ballerina.toml. This is happening since we resuse the `documentIds`, `moduleIds` and `packageIds` when updating the project which has the old name

**Comment by azinneera** [comment]
There are two issues that needs to be fixed here:
1. Usage of `ModuleId.moduleName()`
    This method was introduced for internal usages and is not supposed to expose to the user. But this has been added and public and so has been used by the API users. In Beta.6, we have deprecated the method before removing it. This method should be made package-private and all its current usages should be updated to use `Module.moduleName`. 

2. Reusing the ids when updating Ballerina.toml - once the first issue is fixed the original issue will be resolved and this issue is independent of the cause for the original issue. Therefore, this will be tracked by #34276
