### ISSUE TITLE
Compiler diagnostics only contain the file name

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34218]
Consider the following diagnostic:
```
ERROR [core.bal:(394:21,394:48)] invalid list binding pattern: expected an array or a tuple, but found 'wso2/nballerina.types:0.1.0:UniformSubtype'
```
Note how only the file name is provided in the message. If we are working on a large project with multiple modules, this is not exactly helpful in narrowing down where the error occurred since you don't know which module contains the mentioned file. You have to basically hunt down in each module for that file.

**Comment by MaryamZi** [comment]
Also see https://github.com/ballerina-platform/ballerina-lang/issues/33909.
