### ISSUE TITLE
Constant integers do not overflow for larger values

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#34230]
**Description:**
$title. This happens only when we initialize constants with expressions.

**Steps to reproduce:**
```ballerina
import ballerina/io;

const int X = int:MAX_VALUE + 2;

public function main() {
    io:println(X); // current output: -9223372036854775807
}
```
**Affected Versions:**
SL Beta6 RC1

**Comment by KavinduZoysa** [comment]
Related to https://github.com/ballerina-platform/ballerina-lang/issues/36538
