### ISSUE TITLE
[Documentation] Need a proper way to send feedback in ballerina-by-example site

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3423]
This opens up a wizard to create an account which is not very user friendly. 
![feedback](https://user-images.githubusercontent.com/1845370/31126042-1ca3a46a-a868-11e7-9afd-014c044a9d0f.png)

**Comment by samgnaniah** [comment]
Assign to Madhura. He will work on a fix.

**Comment by uthaiyashankar** [comment]
These pages have been going through major changes. Hence, will not fix for current pages.
