### ISSUE TITLE
Revisit type reference types in multi-module/bala scenarios

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#34247]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/issues/34241 was due to types in imported modules getting updated with details from the modules in which they are imported.

#34246 introduced a temporary fix for slbeta6 by adding a check for the owner. But we need to properly revisit how we model such type definitions and how they are handled in the BIR.

**Affected Versions:**
slbeta6

**Comment by pcnfernando** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34468
