### ISSUE TITLE
Diagnostic message remove single quotes when it displays the message in the terminal

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#34250]
**Description:**
I experienced this issue while using openAPI validator plugin. In openAPI we have messages with single quotes for specialized parameters in the compiler diagnostic message. After making the diagnostic it displays without a single quote, Could you please let me know is there a reason for this?

**given message**
> "Missing OpenAPI contract parameter '%s' in the counterpart Ballerina service resource (method: '%s', path: '%s')" 

**expected message**
 >  "ERROR [service.bal:(4:1,19:2)] Missing OpenAPI contract parameter 'q' in the counterpart Ballerina service resource (method: 'get', path: '/weather')"

**displayed message**
> "ERROR [service.bal:(4:1,19:2)] Missing OpenAPI contract parameter q in the counterpart Ballerina service resource (method: get, path: /weather)"

**Affected Versions:**
SwanLake beta6 RC1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
This issue was resolved after adding double quotes to the string template.
`"Missing OpenAPI contract parameter ''%s'' in the counterpart Ballerina service resource (method: ''%s'', path: ''%s'')`

**Comment by dulajdilshan** [comment]
Some templating examples: https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/resources/compiler.properties
