### ISSUE TITLE
[Documentation] Indentation issues when a sample is copied

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3425]
**Steps**
1. Go to [1]
2. Copy to clipboard a sample

**Issue**
Indentation issues when copied the sample
e.g.

```
service<http> PeopleManagementService {    @http:resourceConfig {
        methods:["GET"],
        path:"/employee/"
    }
```

[1] https://ballerinalang.org/docs/by-example

**Comment by samgnaniah** [comment]
Assign to Madhura.

**Comment by uthaiyashankar** [comment]
This should have been fixed.
