### ISSUE TITLE
Fix OOM issues found via LS simulator workflow

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34265]
**Description:**
We have built the [LS simulator workflow](https://github.com/ballerina-platform/ballerina-lang/actions/workflows/language_server_simulator.yml) to simulate long running coding sessions via LS. We have encountered the following OOM cases.

Case 1:
https://github.com/ballerina-platform/ballerina-lang/actions/runs/1556503733
Leaks Suspects Report: https://drive.google.com/file/d/1fhPtl-BuYeIxrzzFQPajQvR-B_cRWb4z/view?usp=sharing

Case 2:
https://github.com/ballerina-platform/ballerina-lang/actions/runs/1561233450
Leaks Suspects Report: https://drive.google.com/file/d/12WaOWGSnpQZRb64OoIHtPaaCtfBd4R2l/view?usp=sharing

**Steps to reproduce:**
It may be hard to reproduce these issues since the behavior of the LS simulator is unpredictable.

**Affected Versions:**
SL Beta7 Snapshot
SL Beta6 Snapshot

**Comment by IMS94** [comment]
Few more such failures can be found under workflow runs: https://github.com/ballerina-platform/ballerina-lang/actions/workflows/language_server_simulator.yml

Under each failed run, there should be a heap dump attached.

**Comment by gimantha** [comment]
> Few more such failures can be found under workflow runs: https://github.com/ballerina-platform/ballerina-lang/actions/workflows/language_server_simulator.yml
> 
> Under each failed run, there should be a heap dump attached.

I am trying to get this reproduced locally, running the tests for like 2.5 hrs still not getting OOM. one suspect is, `BLangVarBindingPatternMatchPattern` not being cloned. We will have to clone it and see if it fixes the problem.
