### ISSUE TITLE
Behaviour of renaming of a record field in specific fields with var name

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34268]
Consider the following:
```ballerina
type Person record {
    string <1>name;
};

function foo() {
    string <2>name = "Pubudu";
    Person p = {<3>name};
}
```
In the above case, if we rename either the record field or the var, we end up with a broken source file. It'd be great if we can handle this in the rename feature. For example, a behaviour like follows for each of the above numbered rename places:
1 - Renaming record field to `fname`:
Break the var name specific field to a regular specific field as follows: `{name}` => `{fname: name}`

2 - Renaming the var to `fname`:
Break the var name specific field to a regular specific field as follows: `{name}` => `{name: fname}`

3 - Renaming the var ref to `fname`:
Rename both, the record field and var name: `{name}` => `{fname}`

Not sure how feasible this will be to implement though.

**Comment by nadeeshaan** [comment]
I believe we have a user experience draw back when we try to implement this. For instance, consider that there are multiple places where the person record is being used as shown in the description. Those occurrences can be in distributed even in multiple modules as well. 
- Once we change the variable name, then we need to alter the occurrences of the particular variable name as well as the record's field name. 
- If we are going to change the field name, we need to change all the occurrences/ usages of the particular field.
- Changing the particular field leads to alteration of similar variables and their references as well.

If we are going to provide a solution, then we have to think through this deep requirement which is having certain number of refactoring levels.

**Comment by IMS94** [comment]
Closing this since the LS won't be adding a fix to this scenario due to the complexity of the different scenarios we have to address. 

Please create a new issue if this a widely used scenario.
