### ISSUE TITLE
[Documentation] No way to go back in the API doc

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3427]
No way to go back in the API doc. We have to click on the header or browser back button to go back

https://ballerinalang.org/docs/api/0.93/index.html

**Comment by samgnaniah** [comment]
Assign to Madhura. He will be working on a fix.

**Comment by uthaiyashankar** [comment]
We are redoing the pages, and this is handled. We are not going to solve this for the current pages.
