### ISSUE TITLE
Ignore variable code action is suggested for  variable types that contain error

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34279]
**Description:**
Consider the following scenario

```ballerina
public function main() {
    int |error value  = func();
}

function func() returns int | error{
    return 10;
}
```

I get the unused var diagnostic for variable value. 

![err1](https://user-images.githubusercontent.com/35211477/145750500-f9aa5533-6305-4c83-89c8-8470fd80f3cc.png)

However, when the code action is performed, it results in the following syntax error.
 
![err2](https://user-images.githubusercontent.com/35211477/145750645-227526ff-a73e-4040-a2e7-20d1f4ee1067.png)

**Steps to reproduce:**
Mentioned above
**Affected Versions:**
slbeta6-rc2

**Comment by nadeeshaan** [comment]
Can be fixed once #33121 is done
