### ISSUE TITLE
Resource path that precedes with / results in Missing identifier

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#34289]
**Description:**

Then the resource path precedes with a `/`, it results in `Missing identifier` diagnostic error. This causes confusion in the Choreo resource form as we can't identify the issue. The error diagnostic should ne more meaningful to identify the exact error.  
<img width="552" alt="Screenshot 2021-12-13 at 12 48 12" src="https://user-images.githubusercontent.com/5234623/145768863-a3beeede-6a46-4759-99ee-dad21d8dc56f.png">

**Describe your problem(s)**
```
import ballerina/http;

service / on new http:Listener(8080) {
    resource function get /hello(string name) returns json|error? {
        return error("");
    }
}
```

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment]
Fixed in #34370 for SL-RC1
