### ISSUE TITLE
Singlethons populated inside GeneratorTask is inaccessible from CompilerLifecycleTask

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#34296]
**Description:**
In Azure functions and AWS Lambda functions modules, we generate the source file inside GeneratorTask class.  We use the same data model inside CompilerLifecycleTask phase so we store it in a singlethon class as a cache. For some reason in latest pack, Singlethon class seems to be empty when CompilerLifecycleTask phase is reached. 

**Steps to reproduce:**
https://github.com/xlight05/module-ballerinax-azure.functions/tree/stripped-ext

you can make the pack by executing  ./gradlew clean build . It'll be created in <repo-path>/azurefunctions-extension-bala azurefunctions-extension-bala/build/extracted-distribution. 

Test case is available at azurefunctions-extension-test/src/test/resources/deployment

You can do BAL_JAVA_DEBUG=5005 <repo-path>/azurefunctions-extension-bala/build/extracted-distribution/jballerina-tools-2.0.0-beta.6-20211211-193900-8a474932/bin/bal build
to debug. 

extension source- , azurefunctions-extension

You can observe the value of TestSinglethon using the above sample.
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
@xlight05 I tested this with a simple Singleton class but didn't encounter any issues. Here is the scenario I tried:
1. Added a Singleton class to the compiler plugin package with the public field `timestamp`
2. Access the singleton and set the current timestamp in a codeGenerator task
3. Verify the timestamp in the CompilreLifeCycleTask

The source code of the plugin and the Singleton can be found here: https://gist.github.com/azinneera/2288815f83fe2e8b03cd762f7047c6fe

This is the output I got:
```
Compiling source
	user/foo:0.1.0
Before update:0
After update in codegen task:1639462777872
WARNING [main.bal:(18:9,18:13)] no such documentable parameter 'name'
WARNING [main.bal:(20:5,20:5)] concurrent calls will not be made to this method since the method is not an 'isolated' method
WARNING [main.bal:(25:9,27:12)] unused variable 'e'
WARNING [main.bal:(34:9,34:155)] unused variable 'executeResponse'

Generating executable
Compiler lifecycle event ctx:1639462777872
	target/bin/foo.jar

```

**Comment by azinneera** [comment]
The above was tested with an in-built compiler plugin. Was able to reproduce the issue with a package-provided compiler plugin.

**Comment by azinneera** [comment]
This is the expected behavior since the classloaders are different for the analysis and lifecycle phases. The suggested  approach to pass information is to persist to the target/ directory and access.
