### ISSUE TITLE
Create variable code action not supported for `object-constructor` and `error-constructor` Expressions

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34314]
**Description:**
$subject.

The reason for,
- object-constructor-expr not supported is due to ambiguity in parsing with object-type-descriptor
- error-constructor-expr not supported is due to ambiguity in parsing with error-binding-pattern

Since we have a predictive parser with no backtracking, we can't distinguish the two cases.

**Comment by lochana-chathura** [comment]
The reason for,
1. `object-constructor-expr` not supported is due to ambiguity in parsing with `object-type-descriptor`
2. `error-constructor-expr` not supported is due to ambiguity in parsing with `error-binding-pattern`

**Comment by gayalkuruppu** [comment]
@lochana-chathura Will this be supported anytime soon? came across the use case(create variable for error-constructor) couple of times while using ballerina.

**Comment by IMS94** [comment]
@lochana-chathura is there a plan to support this? If not, shall we close this as `Won't Fix`?
