### ISSUE TITLE
Definite assignment error for valid Ballerina program where there is a `if` block before the assignment

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#34331]
**Description:**
```ballerina
import ballerina/io;
public function main() {
    int i;
    while true {
        int k = 0;
        if k == 1 { // just an unrelated `if`
        }

        i = 2; // `i` is initialized in a `while true`
        if i == 2 {
            break;
        }
    }
    int j = i; // error: variable 'i' may not have been initialized(BCE3700)
    io:println(j);
}
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34185 and the fix will be available with the Swan Lake GA release. Hence closing this issue.
