### ISSUE TITLE
Cannot Test Generated Resources from the Resource Generator in Testerina

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#34348]
**Description:**
When we generate a resource using code generator plugin, the generated resource does not exist in the testerina tests. Therefore, testing the generated resources is not possible. 

This is a blocker for https://github.com/ballerina-platform/ballerina-standard-library/issues/2047

**Comment by Ibaqu** [comment]
Reopening since : https://github.com/ballerina-platform/ballerina-lang/pull/35242

**Comment by Dilhasha** [comment]
Will be addressed when the support to embed static resources is provided. Related spec issue : https://github.com/ballerina-platform/ballerina-spec/issues/1100

**Comment by Dilhasha** [comment]
We have changed the resource embedding approach. We do not recommend using code generators to support resource generation. 
Hence the issue is not relevant anymore.
