### ISSUE TITLE
Add parameter annotations to the BIR and add them to the symbol in BIR package symbol enter

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#34342]
**Description:**
$title.

Related to https://github.com/ballerina-platform/ballerina-lang/issues/33711.

Address the specific case in https://github.com/ballerina-platform/ballerina-lang/issues/33711#issue-1048402565/

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34329
