### ISSUE TITLE
Wrong type of the variable showed when hovering

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34366]
**Description:**
![Peek 2021-12-16 16-11](https://user-images.githubusercontent.com/25485997/146356714-1d337590-e9b0-4414-b9b6-38e34e702b6b.gif)

**Steps to reproduce:**
Hover the cursor to the `b` in the line `20 c = b` in the following ballerina code
```ballerina
function testReachableCodeWithBinaryCondition4() returns int {
    10|20 b = 10;

    if b == 10 {
        return 10;
    }

    20 c = b;

    if b  == 20 {
        return 20;
    }
}
```

**Affected Versions:**
Swan Lake beta 6

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34449
