### ISSUE TITLE
Record type are not suggested when trying to add HTTP payload

### ISSUE THREAD

**Issue by tharindulak** [ballerina-platform/ballerina-lang#34363]
**Description:**
When we try to add a payload for HTTP resource, we don't get record types. 

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/20821008/146350427-ca65119c-52eb-463a-9d04-de81fb043176.png)

**Affected Versions:**
Swan Lake Beta 6

**OS, DB, other environment details and versions:**
Mac OS

**Comment by nadeeshaan** [comment]
Tried on the latest patch branch and observed the following behavior where the records are being suggested.
<img width="1170" alt="Screen Shot 2022-03-25 at 3 29 42 PM" src="https://user-images.githubusercontent.com/1329674/160099277-98111621-4cfc-44da-a657-794b344169ed.png">

Hence closing the issue and if the still exists, please reopen.
