### ISSUE TITLE
Local variables don't get defined under the correct environment

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34369]
**Description:**
```ballerina
function testRun(string name) returns int {
    if !(name is "") {
        return 1;
    }

    string testvar = "toyota";
   <cursor>
}
```
Try getting the completions at the `<cursor>` position.

Here `testvar` will be visible if we remove `return 1` line

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
Original Issue: https://github.com/wso2-enterprise/internal-support-ballerina/issues/12

**Comment by dulajdilshan** [comment]
Some Findings: https://github.com/wso2-enterprise/internal-support-ballerina/issues/12#issuecomment-995721633

**Comment by lasinicl** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/34449
