### ISSUE TITLE
Improve the behaviour of `create function` code action

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34385]
**Description:**
Improve the behaviour of create function code action in following cases.

1. `10|11 i = getTenOrEleven();`

Generated function,
<img width="420" alt="Screenshot 2021-12-17 at 10 25 16" src="https://user-images.githubusercontent.com/27485094/146491144-b3552801-6e93-49cb-9f0a-c8b29ac4caa4.png">

2. `if !getBoolean() {}`

Generated function,
<img width="420" alt="Screenshot 2021-12-17 at 10 27 30" src="https://user-images.githubusercontent.com/27485094/146491356-8785720e-5e40-4fc4-9af7-4aaa468c0d64.png">

3. `int _ = getInt();`

Generated function,
<img width="447" alt="Screenshot 2021-12-17 at 10 28 37" src="https://user-images.githubusercontent.com/27485094/146491426-751eba89-dc8d-4f90-84be-30af19f6db1a.png">

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
