### ISSUE TITLE
Module level var is not suggested in function body block context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34392]
**Description:**
Consider the following source 
```ballerina
record{| int field1;|} myVar = {field1: 0};

# Prints `Hello` with input string name.
#
# + name - the input sting name
# + return - "Hello, " with the input string name
public function hello(string name) returns string {
    if !(name is "") {
        return "Hello, " + name;
    }
    return "Hello, World!";
}

public isolated function IFucnction(int a) {
   
}
 
public function function1(int n) {
     <cursor>
}

```

The module-var `myVar` is not suggested at the cursor position. When the `hello` function is removed along with its documentation the issue is not there.
![myvar](https://user-images.githubusercontent.com/35211477/146542789-935e7665-c5cf-44cd-a44f-855dc549c7e8.png)

![myvar2](https://user-images.githubusercontent.com/35211477/146542894-31b0ca7c-2bb2-44ae-8258-520159d42a5b.png)

**Steps to reproduce:**
Mentioned above

**Affected Versions:**
slbeta6

**Comment by gimantha** [comment]
Checked with 2201.0.2 and this issue is fixed
