### ISSUE TITLE
Goto def for annotations in start action doesn't work

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34408]
**Description:**
Consider the following code:
```
function myFunction() {
    future<()> _ = @strand{thread: "any"} start another();
}

function another() {

}
```
When we get the definition for `@strand` annotation, no definition is found.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta6

**Comment by nadeeshaan** [comment]
What if we add some other annotation? Is it showing the same behaviour?

**Comment by IMS94** [comment]
@nadeeshaan Yes. I tried the below code:
```ballerina
type Data record {

};

const annotation Data MyAnnot on source worker;

function fn() {
    future<error?>[] futures = [];
    foreach int i in 0 ..< len {
        foreach int j in 0 ..< len {
            future<error?> f = @MyAnnot start calculate(mat1, mat2, result, i, j);
            futures.push(f);

            future<error?> _ = @strand {thread: "any"} @MyAnnot start calculate(mat1, mat2, result, i, j);
        }
    }
}
```
Goto def for `MyAnnot` doesn't work (near start actions). But when we check for references of `MyAnnot` annotations, it's usages are shown correctly.
