### ISSUE TITLE
Invalid completions are provided for chained invocation

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#34419]
**Description:**
Consider the following source snippet where the shown completions are invalid.

```
match command.toLowerAscii() {
        GREETING => {
            io:println("GREETING");
            io:println(getServerGreeting(mFields.get(ProfileName)));
        }
        REGISTER => {
            io:println("REGISTER");
            io:println(storeData(mFields));
        }
        UNREGISTER => {
            io:println("UNREGISTER");
            io:println(removeUser(mFields.get(WaId)));
        }
        SUBSCRIBE => {
            (regex:replaceFirst(messageBody, command, "")).<cursor>
            io:println("SUBSCRIBE");
            io:println(subscribeToTeam(mFields.get(WaId), command));
        }
        UNSUBSCRIBE => {
            io:println("UNSUBSCRIBE");
            io:println(removeUser(mFields.get(WaId)));
        }
    } 
```

<img width="682" alt="Screenshot 2021-12-21 at 08 48 26" src="https://user-images.githubusercontent.com/1329674/146865274-14f25c20-d629-4367-9471-833b9d0e679c.png">

**Steps to reproduce:**
Get the completions at the given cursor postion

**Affected Versions:**
SwanLake-Beta6 at least

**Comment by nadeeshaan** [comment]
This is because the current node at cursor is not not identified as a field/method access expression.
@lochana-chathura @rdulmina can you guys shed some light on this?

**Comment by rdulmina** [comment]
Will have a look

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34478
