### ISSUE TITLE
How to use a legacy java implementation using Ballerina

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#3441]
**Use case:**
Username token generation is done by a leagacy java sdk. There is a need to call this sdk and obtain relevant username token to be passed to a backend.

Currently there is no documentation indication on this. Could you please point a direction in achieving this by using Ballerina?

**Comment by riyafa** [comment]
You can use native functions to achieve this in ballerina at the moment. This procedure is not documented properly at the moment.

**Comment by hasithaa** [comment]
Adding more to @riyafa comment. Another option is to expose legacy SDK as an API and call it using Ballerina.
