### ISSUE TITLE
Change return type code action does not chnage the signature of the correct method/function

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34424]
**Description:**
Consider the following capture.
![ezgif com-gif-maker(11)](https://user-images.githubusercontent.com/35211477/146876989-9fde8011-472c-453d-86f2-d1ec6090d3f3.gif)

**Steps to reproduce:**
```ballerina
public function test(){


    var var1 = object {
        int id = 10;
        function getId() {
            return self.id;
        }
    };

    
}

```

**Affected Versions:**
slbeta6

**Comment by nadeeshaan** [comment]
Closing the issue, since the fix has been merged.
