### ISSUE TITLE
Nil-lifting operations should not perform short-circuiting on operand evaluation

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#34441]
**Description:**
Spec clarification: https://github.com/ballerina-platform/ballerina-spec/issues/1013

**Steps to reproduce:**

**Affected Versions:**
SL beta-6
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment]
Just tested this on `+` operator, we need to test this with other `nil-lifting` operators as well.

Sample:
```ballerina
import ballerina/io;
public function main() {
    int? r = foo() + bar(); // only evaluate foo
}

function foo() returns int? {
    io:println("foo");
    return ();
}

function bar() returns int? {
    io:println("bar");
    return ();
}
```

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35938
