### ISSUE TITLE
No suggestion for local variable inside foreach

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34458]
**Description:**

Consider the below sample. Variable `total` is not suggested inside foreach

![Screenshot from 2021-12-23 10-31-24](https://user-images.githubusercontent.com/26381349/147238380-c91bdb03-f768-4d69-b743-6d53f7e3917d.png)

**Comment by pubudu91** [comment]
This seems like the same as #34105. Fixed by #34484. Hence closing this.
