### ISSUE TITLE
Incorrect output of `toString` for decimal with tailing zeros

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#34472]
**Description:**
```
import ballerina/io;
public function main() returns error? {
    decimal d1 = 0.0d;
    decimal d2 = 0d;
    io:println(check decimal:fromString(d1.toString()) === check decimal:fromString(d2.toString())); // should be false
}
```
When there are tailing zeros after decimal point, `toString` does not consider them.

**Comment by hasithaa** [comment]
closed with https://github.com/ballerina-platform/ballerina-lang/pull/34582

**Comment by rdulmina** [comment]
This issue also exists for `toBalString`
```bal
public function main() returns error? {
    decimal d1 = 0.0d;
    io:println(d1.toBalString()); // prints 0d but it should print 0.0d
}
```

**Comment by KavinduZoysa** [comment]
@rdulmina, except value `0`, other values have the correct balString output right?

**Comment by KavinduZoysa** [comment]
Please check this https://github.com/ballerina-platform/ballerina-lang/issues/34748#issuecomment-1017394145

**Comment by rdulmina** [comment]
Closing as per the comment https://github.com/ballerina-platform/ballerina-lang/issues/34748#issuecomment-1017394145
