### ISSUE TITLE
Invalid code generated for an invalid expression

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34481]
Consider the following:
```ballerina
map:map({}, a => a.toString());
```
If I use the create var code action for the above, it results in the following:
```ballerina
map<map:Type1> mapResult = map:map({}, a => a.toString());
```
This is invalid since `map:Type1` is not a publicly available symbol.

**Comment by nadeeshaan** [comment]
The diagnostic properties include `map<map:Type1>` as the expected type and from the LS we do not alter the type information. We might need to check whether this type information has delegated to the diagnostics API from the compiler

**Comment by dulajdilshan** [comment]
The lanlib defined as follows 
```ballerina
# Applies a function each member of a map and returns a map of the result.
#
# The resulting map will have the same keys as the argument map.
#
# + m - the map
# + func - a function to apply to each member
# + return - new map containing result of applying parameter `func` to each member
public isolated function 'map(map<Type> m, @isolatedParam function(Type val) returns Type1 func) returns map<Type1> = @java:Method {
    'class: "org.ballerinalang.langlib.map.Map",
    name: "map"
} external;
```

**Comment by dulajdilshan** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/35157

**Comment by KavinduZoysa** [comment]
The issue for the provided example has been fixed. Closing this as a low-priority task with the Icebox label might reopen in the future.
