### ISSUE TITLE
Field name completions are not provided inside mapping constructor within multiple wait

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34497]
**Description:**
Consider
```ballerina
import ballerina/log;

type WaitResult record {|
    boolean producer;
    boolean consumer;
|};

public function main() {
    log:printInfo("initializing app...");

    worker Producer returns boolean {
        int i = 100;
        i -> Consumer;
        log:printInfo("Sent item", i = i);
    }

    worker Consumer returns boolean {
        int i = <-Producer;
        log:printInfo("Received item", i=i);
    }

    WaitResult res = wait {<cursor>};
    log:printInfo("Worker execution finished", result = res);
}
```

At `<cursor>`, we should provide completions for the field names `producer` and `consumer`. 

**Steps to reproduce:**
See description

**Affected Versions:**
Swan Lake 2201 Snapshot Build 1

**Comment by TharushiJay** [comment]
This is similar to case 1 in https://github.com/ballerina-platform/ballerina-lang/issues/33886. It was decided not to provide mapping expression related completions here https://github.com/ballerina-platform/ballerina-lang/pull/33979#issuecomment-983302328.

**Comment by nadeeshaan** [comment]
> This is similar to case 1 in #33886. It was decided not to provide mapping expression related completions here [#33979 (comment)](https://github.com/ballerina-platform/ballerina-lang/pull/33979#issuecomment-983302328).

Add some context to @TharushiJay 's explanation here,

We decided not to provide the field completions due to the inconsistency of the default value generation of this particular scenario. We will have to revisit the default value generation.

**Comment by IMS94** [comment]
I see. Agreed. Hence closing this issue.
