### ISSUE TITLE
Bal CLI  fails when a cmd is invoked from a folder which has spaces in name

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#34496]
**Description:**
When we execute a bal cmd (e.g. ```bal home```) from a folder which has spaces in its name, bal script passes invalid arguments to JVM as it hasn't wrapped the heapdump path with quotes and it fails. 

**Steps to reproduce:**

![Capture](https://user-images.githubusercontent.com/1505855/148030807-7573cad6-dd00-4e8e-afd5-aedf8931fce6.PNG)

![Capture2](https://user-images.githubusercontent.com/1505855/148030824-29accaed-db57-40a2-a306-95f25ba265e7.PNG)

**Steps to fix:**

![Capture3](https://user-images.githubusercontent.com/1505855/148030866-abc318af-1328-4354-854f-cf5fab12006d.PNG)

![Capture4](https://user-images.githubusercontent.com/1505855/148030892-c3aa5ce7-52b4-46db-b184-7058d2b3563f.PNG)

**Affected Versions:**
slbeta6

**Related Issues (optional):**
This is the same reason why VSCode extension fails on windows with WSL2.  In that setup, the working directory has spaces in its name (```c:/...../AppData/.../Microsoft VS Code```) and hence same issue happens. This is critical as most windows users are now using WSL.
https://github.com/ballerina-platform/ballerina-lang/issues/33305
https://github.com/wso2/ballerina-plugin-vscode/issues/136

**Suggested Labels (optional):**
Severity/Critical

**Comment by IMS94** [comment]
This is same as https://github.com/ballerina-platform/ballerina-lang/issues/32740. We can close both once this is resolved.

**Comment by kaviththiranga** [comment]
@IMS94 thanks, yeah its the same issue and for Windows WSL2 users, this will break always because the working dir is set to ```c:/...../AppData/.../Microsoft VS Code``` always.

**Comment by kaviththiranga** [comment]
This should fix it, @keizer619  plz check
https://github.com/ballerina-platform/ballerina-lang/pull/34499

**Comment by IMS94** [comment]
This should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34501.
