### ISSUE TITLE
Answer - fully internationalized language ?

### ISSUE THREAD

**Issue by allustin** [ballerina-platform/ballerina-lang#3450]
based on this https://medium.com/ballerinalang/ballerina-thinking-about-names-why-restrict-to-english-c1f9803e827

Does ballerinalang would be speak in i18n ?

If is not joke - we could make a help for russian ;-)

**Comment by artbear** [comment]
+1 for russian translate

**Comment by afkham** [comment]
Yes we have plans to fully internationalize.

**Comment by allustin** [comment]
@afkham any news ?
