### ISSUE TITLE
Fix debugger test failures on function pointer support for defaultable parameters

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#34512]
**Description:**
Some of the debugger integration tests are failing with the changes related to https://github.com/ballerina-platform/ballerina-lang/pull/31589 and need to be fixed before merging the mentioned PR.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praveennadarajah** [comment]
Closing with https://github.com/chiranSachintha/ballerina-lang/pull/5
