### ISSUE TITLE
SemanticAnalyzer throws NPE

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#34548]
**Description:**
Consider the following source snippet

```
function testIterableOperation() {
    Customer c1 = {id: 1, name: "Melina", noOfItems: 12};
    Customer c2 = {id: 2, name: "James", noOfItems: 5};
    Customer c3 = {id: 3, name: "Anne", noOfItems: 20};

    Customer[] customerList = [c1, c2, c3];

    string outputNameString =
                from var person in check getPersonList() 

}

function getPersonList() returns Person[]|error {
    Person p1 = {firstName: "Amy", lastName: "Melina", age: 23};
    Person p2 = {firstName: "Frank", lastName: "James", age: 30};

    Person[] personList = [p1, p2];
    return personList; 
}

type Customer record {
    int id;
    string name;
    int noOfItems;
};

type Person record {
    string firstName;
    string lastName;
    int age;
};
```

This source does not throws the NPE and works fine. Now, comment the `Person` record. Then the null pointer exception is thrown. From this point onwards, even the `Person` record is un-commented, the NPE will be continuously thrown.

**Affected Versions**
SwanLakeBeta-6 at least

**Comment by gimantha** [comment]
Did you notice if the functionalities are broken, after this NPE ?

**Comment by nadeeshaan** [comment]
@gimantha not really. The functionalities seems to be working fine other than the frequent logging of the exception. My concern is that the NPE does not go away even after fixing the issue. Wouldn't that be some sort of a caching related behaviour, which might lead to issues?

**Comment by MaryamZi** [comment]
Probably the same as Case II of https://github.com/ballerina-platform/ballerina-lang/issues/34621.

**Comment by KavinduZoysa** [comment]
This behavior is unavailable in the latest vs code plugin(3.3.11)
