### ISSUE TITLE
Omit the quote when providing completions for `map()`, `join()`, `start()` 

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34545]
Currently the completions for the above are shown with a leading `'`. The completion behaviour for the the two should be as follows:
- In method call expr contexts, it should provide the completion without the quote.
- In function call expr contexts (both regular and qualified name ref), it should provide it with the quote.

Before fixing this, need #34297 to be resolved in the compiler.

**Comment by mindula** [comment]
As in the image below, we get the functionSymbol with the quote. Hence, this should be fixed in the semanticAPI

<img width="546" alt="Screenshot 2023-07-10 at 10 00 05" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/a614deaa-55da-49fa-95b5-3d279b24e92b">

**Comment by KavinduZoysa** [comment]
This is fixed in the latest ballerina versions.
