### ISSUE TITLE
LS throws IndexOutOfBoundsException for completions in a cyclic union

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34544]
**Description:**
<img width="775" alt="Screenshot 2022-01-06 at 15 42 45" src="https://user-images.githubusercontent.com/27485094/148367257-492579fe-85bb-4f84-82e5-82bed05f908c.png">

**Steps to reproduce:**
```
type Cloneable readonly|xml|Cloneable[]|<cursor>
```

**Affected Versions:**
SL Beta6

**Comment by pubudu91** [comment]
Possibly related to #29740

**Comment by nadeeshaan** [comment]
> Possibly related to #29740

It seems the member types are empty. Isn't that illogical according to the spec? Union types should have non-empty list of members. We can check for the empty list and bypass the default behaviour from LS as a workaround as well. Before that shall we check whether what's the root cause?

**Comment by pubudu91** [comment]
> > Possibly related to #29740
> 
> It seems the member types are empty. Isn't that illogical according to the spec? Union types should have non-empty list of members. We can check for the empty list and bypass the default behaviour from LS as a workaround as well. Before that shall we check whether what's the root cause?

Had a look at this. The weird behaviour with regard to the empty union seems to be a bug in the compiler. Created #35297 to track this.
