### ISSUE TITLE
`MultiModuleTestDebugTest` failure when adding lang queries in `main.bal`

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#34549]
**Description:**
`MultiModuleTestDebugTest` failure when adding lang queries in `main.bal`

**Steps to reproduce:**
- Consider the below code segment:
```
    int[] nums = [1, 2, 3, 4];
    int[] numsTimes10 = from var i in nums
        select i * 10;
```
- Add the above code segment at the end of `main()` method in `/ballerina-lang/tests/jballerina-debugger-integration-test/src/test/resources/project-based-tests/breakpoint-tests/main.bal`.
- Run the `MultiModuleTestDebugTest`. The test will fail.
- The test will pass when we remove the above code segment.
- This behaviour is only observed in the release branch `stage-swan-lake` and not in the `master` branch.

**Comment by NipunaRanasinghe** [comment]
Closing as this is not reproducible with the latest swan lake releases
