### ISSUE TITLE
list-groups command throws NPE when executed for packages

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#34551]
**Description:**
list-groups command throws NPE when executed for packages. 

**Steps to reproduce:**

Create a ballerina project with test groups and execute the following command.

`bal test --list-groups`

This results in an NPE.

**Affected Versions:**
2201.0.0-20211221-194900-b414ea8e

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Certain fields were rendered invalid from a previous change and were not considered in the list groups feature. This has since been fixed.
