### ISSUE TITLE
NPE in `TypeHashVisitor` when use `null` in union-type

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34556]
**Description:**
NPE occurs in `TypeHashVisitor` when the compiled source contains a function type with a parameter of union-type that defined as follows
```ballerina
public type TestType string|int?[]|null;

public function doThis(TestType res) {
    
}
```

**Steps to reproduce:**
1. Include the above code into the ballerina project. Build it and push it to the `local` repository
2. Create a ballerina file and try using the `doThis` function by passing it to a function call. (see the example below)
```ballerina
import org/testType;

public function main() {
    func1(testType:doThis);
}

function func1(function (testType:TestType resp) callback) {
}
```
3. Run 

**Affected Versions:**
`Ballerina 2201.0.0 (Swan Lake) Snapshot build 1`, `stage-swan-lake` branch

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34578
