### ISSUE TITLE
Update the constant symbol type when visiting the expression itself

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#34570]
**Description:**
Currently, constant symbol type is updated by the [updateSymbolType](https://github.com/ballerina-platform/ballerina-lang/blob/fdb8d28e9454125877cb5405043dd92c7faf754b/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java#L113) method in `ConstantValueResolver`. We can probably do this in better way when visiting the expression itself (when creating the BLangConstantValue).

Related [discussion](https://github.com/ballerina-platform/ballerina-lang/pull/34371#discussion_r771497698).

**Comment by KavinduZoysa** [comment]
Related to #36538
