### ISSUE TITLE
No error for unreachable statements in some scenarios

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34579]
**Description:**
According to the spec,

> When the execution of a statement or a transfer of control is conditional on the result of evaluating an expression, then the analysis assumes that it is possible for the statement to be executed or control to be transferred, **unless the static type of the expression makes it impossible.**

Following cases do not give errors.
```bal
public function main() {
   if fn() {
       io:println("true");
   } else {
       io:println("false"); // no error
   }
}
 
function fn() returns true {
   return true;
}

public function fn2() {
   boolean a = 0 < 1;
   if <true>a {
       io:println("true");
   } else {
       io:println("false"); // no error
   }
}
```

**Comment by rdulmina** [comment]
Basically, if we give any other expression where the static type is singleton `true` or `false`, it does not give any error other than for literals `true` and `false`
