### ISSUE TITLE
Add runtime unit test for calling object method with default args

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#34585]
**Description:**
$Subject using runtime api.

**Comment by warunalakshitha** [comment]
https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/jballerina-unit-test/src/test/java/org/ballerinalang/nativeimpl/jvm/runtime/api/tests/Async.java

**Comment by warunalakshitha** [comment]
Tests should cover,
1) calling an object method that has default param, passing arguments for default param.
2) calling an object method that has default param, not passing arguments for default param.

**Comment by Nadeeshan96** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34658.
