### ISSUE TITLE
Applying a compiler plugin code action automatically duplicates commented out code

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34581]
**Description:**

Refer to the screen recording below where executing the `Replace with '2.0'` code action automatically inserts a duplicated code segment that was commented out.

https://user-images.githubusercontent.com/27485094/148741278-4df2272a-e358-4dab-8d78-5379b74b9ca3.mov

**Steps to reproduce:**

```
// import ballerina/io;

// // Anonymous function syntax.
// var isOdd = function(int n) returns boolean {
//     return n % 2 != 0;
// };

// // Function type syntax.
// type IntFilter function (int n) returns boolean;


public function main() {
    float x = 2.;
}

```

**Affected Versions:**
SL Beta6

**Comment by IMS94** [comment]
Had a look at this. 
```ballerina

// A comment here
public function main() {
   float a =  2.;
}

```
Issue here is, `syntaxTree.rootNode().lineRange()` returns (2:0, 4:1). LS rely on this line range to replace the content of the source file. Is this the expected behavior? @lochana-chathura @rdulmina

**Comment by lochana-chathura** [comment]
@IMS94 That is expected.
For any node we have,
1). node.textRange() // this range does not include the leading and trailing minutiea
2). node.textRangeWithMinutiae() // this range does include minutiea

`node.lineRange()` referes to the corresponding line range of `node.textRange()`. Therefore it does not include minutiea.
For example here the root node's line range will be `(5,0, 7,1)`.
```
1.  // Comment 1
2.  
3.  // Comment 2
4.  
5.  public function main() {
6.    float a =  2.;
7.  }
8.
9.  // Commnet 3
10.
11. // Comment 4 
```

**Comment by IMS94** [comment]
Agreed. We will have to use `textRangeWithMinutiae()` then. Thanks for the explanation.
