### ISSUE TITLE
Invalid completions in Mapping constructor context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#34597]
**Description:**
Consider the following scenario

![image](https://user-images.githubusercontent.com/35211477/148901250-f8b87d5f-7c02-4145-bbef-128119c0d975.png)

As depicted above,  completions in mapping constructor context are not accurate. 

**Steps to reproduce:**
```Ballerina
import ballerina/io;
import ballerina/regex;
import ballerina/udp;

# OPERATION type in message
public enum OPERATION {
    REG
}

type Message record {|
    string host;
    int port;
    OPERATION op;
|};

public function processMessage(udp:Datagram datagram) returns error? {
    Message message = check message(datagram);
}

function message(udp:Datagram datagram) returns Message | error{
  string data = check string:fromBytes(datagram.data);  
  string[] args = regex:split(data," ");
  Message message = {};
}
```

**Affected Versions:**
2201.0.0-Snapshot

**Comment by nadeeshaan** [comment]
This has been fixed in the latest `stage-swan-lake` branch. Hence closing the issue.
