### ISSUE TITLE
Runtime Performance comparison with services

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#34605]
**Description:**
Need to compare passthrough comparison between
1.2.x
2.0.0 - alpha
2.0.0 - beta
2.0.0- GA

**Comment by warunalakshitha** [comment]
@gabilang Please update the setup detail + results here

**Comment by gabilang** [comment]
Performed a performance test with https passthrough scenario https://github.com/gabilang/ballerina-performance. Added a summary report there.
