### ISSUE TITLE
Missing remote method completions

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#34603]
**Description:**

In the following scenario we should get the completions of remote methods. ex:- getIssue()

<img width="988" alt="Screenshot 2022-01-11 at 10 59 47" src="https://user-images.githubusercontent.com/46120162/148903366-6c298e67-34e8-4e07-9089-37cb565a2137.png">

**Steps to reproduce:**
```
import ballerina/io;
import ballerinax/github;

public function main() {
    string owner = "ballerina-platform";
    string repoName = "ballerina-lang";

    github:Repository|error repository = getGithubRepository(owner, repoName);
    if repository is error {
        io:println("Could not find stars in repo ", owner, "'s ", repoName);
    } else {
        io:println(repoName, " has ", repository.stargazerCount, " stars");
    }
}

function getGithubRepository(string owner, string repoName) returns github:Repository|github:Error|error {
    github:ConnectionConfig connectionConfig = {
        auth: {
            token: "fake token"
        }
    };
    github:Client|error githubClient = new (connectionConfig);
    if githubClient is error {
        return githubClient;
    }
    github:Repository|github:Error repository = githubClient->getRepository(owner, repoName);
    github:Issue|github:Error issue = githubClient-><cur>
    return repository;
}
```
**Affected Versions:**
SL Beta6

**Comment by nadeeshaan** [comment]
This is a subsequent issue of #34369. Will you be able to check on a latest build and verify? A fix has been added with https://github.com/ballerina-platform/ballerina-lang/pull/34449 and merged to `stage-swan-lake` branch. Let's verify on that

**Comment by nadeeshaan** [comment]
Since this is a similar issue as mentioned in the above comment, we are closing this issue.
