### ISSUE TITLE
Need to define the symbol relationship(s) in mapping binding patterns

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34606]
Consider the following:
```ballerina
type Person1 record {|
    string name;
    int mbp2;
    string...;
|};

function test1() {
    string mbp1;
    int mbp2;
    map<string> rbp3;
    {name: <1>mbp1, <2>mbp2, ...<3>rbp3} = <Person1>{name: "Jane Doe", mbp2: 10, "foo": "bar"}; // destructuring assignment stmt
}
```
A couple of points here:
- According to the spec, the var names in binding patterns (e.g., locations `<1>`, `<2>`, `<3>`) are not var references. i.e., they're not expressions. But in the compiler we have modelled them as var refs. I suppose from a practical implementation POV, it makes sense, for providing features such as find refs, rename, goto def. But this also means use of `typeOf()` on these also works. 
- Currently, there's no relationship between `name` in the binding pattern and `name` in the mapping constructor. Need to take a closer look and decide on the behaviour for this. Does `name` in the binding pattern refer to the `name` field in the record type of the RHS expr?

The current impact of this is that plugin features such as find refs, rename, goto def etc. aren't working for the aforementioned cases.

**Comment by mohanvive** [comment]
Pointed allocated for the analysis and design.

**Comment by dulajdilshan** [comment]
In the typescript, when we have destructuring, they allow us to perform `rename`, `goto-def` and `references` actions.
```typescript
interface TypeA {
    name: string;
    age: number;
}

function ert() {
    const { name: df, age} = { name: "dd", age: 23} as TypeA;
}
```
(TypeScript)

Below is the behaviour when we perform the `Rename symbol` action on the above source code
Scenario 1:
![Scenario_1_Peek 2022-03-08 15-25](https://user-images.githubusercontent.com/25485997/157212739-86e897df-58f0-4b0f-b7e4-17d7504ae279.gif)

Scenario 2:
![Scenario_2_Peek 2022-03-08 15-26](https://user-images.githubusercontent.com/25485997/157212872-d8df2031-cc51-44f8-89e1-366ec1af6a28.gif)

**Comment by dulajdilshan** [comment]
Had a chat with @mohanvive @nadeeshaan @pubudu91 and @sanjana on this. We decided to provide the `Rename Symbol` functionality for binding patterns defined with variable-name 
i.e: `mbp2` of the following code
```ballerina
{ name: mbp1, mbp2 } = <Person1>{name: "Jane Doe", mbp2: 10, "foo": "bar"};
```
Steps:
![Screenshot from 2022-03-08 15-31-55](https://user-images.githubusercontent.com/25485997/157214218-afacd491-37f5-4c1b-91e7-b059d8e91446.png)

![Screenshot from 2022-03-08 15-32-14](https://user-images.githubusercontent.com/25485997/157214236-b95b6582-2fd6-4593-ad10-4dbc7ef6cc6f.png)

![Screenshot from 2022-03-08 15-32-32](https://user-images.githubusercontent.com/25485997/157214257-625c48ce-0799-44a4-a1fc-757203224046.png)

**Comment by dulajdilshan** [comment]
Created an issue to track the rest  of the development https://github.com/ballerina-platform/ballerina-lang/issues/35377

**Comment by pubudu91** [comment]
Had a further chat with @mohanvive @nadeeshaan and @dulajdilshan today regarding this. Specifically about whether or not to consider the field names in a binding pattern as references to field names of the RHS type. Consider the following example,
```ballerina
type Person record {|
    string name;
    int mbp2;
    string...;
|};

function test() {
    string mbp1;
    int mbp2;
    map<string> rbp3;

    {<1>name: mbp1, mbp2, ...rbp3} = <Person>{name: "Jane Doe", mbp2: 10, "foo": "bar"};
}
```
At first glance, in the above case it'd look like `name` at `<1>` is a reference to the `name` field in `Person`. 

But consider the following case:
```ballerina
function test() {
    string mbp1;
    int mbp2;
    map<string> rbp3;

    record {|string name; int mbp2; string...;|} x = {name: "Jane Doe", mbp2: 10, "foo": "bar"};
    {<1>name: mbp1, mbp2, ...rbp3} = x;
}
```
In this particular case, do we still consider `name` at `<1>` as a reference to the field `name` of `x`'s record type descriptor? 

The conclusion was that we can't consider cases like the above one as referring the exact field. It's saying that it should have a field called `name`, but it's not referring to the field `name` in the type descriptor. Therefore, we won't be considering this as a reference of the field name, and consequently, won't be renamed either.
