### ISSUE TITLE
ProjectAPI version filter doesnt work when versions like slbeta6.1 and slbeta10 are used

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#34611]
**Description:**
The filter needs to be updated to handle decimals and numbers larger than 9

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
This is a blocker for slbeta 6 patch

**Comment by hevayo** [comment]
This will be addressed by the new version scheme. Since patch versions are not supported in package resolution and central for beta releases this patch should go as slbeta6. We did slbeta5.1 in a similar manner. The version will be only indicated in zip or installer.

**Comment by azinneera** [comment]
Closing the issue as per the above comment.
