### ISSUE TITLE
Debugger stuck when executing an expression in the debug console

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#34627]
**Description:**
Consider the following screen capture.

https://user-images.githubusercontent.com/1329674/149080260-d934f905-f4eb-4d6c-8e2b-321d39c7f963.mp4

Here, when we evaluate the `resp.statusCode` we get the response and once we evaluate `resp. getTextPayload` the editor process get stuck without resuming or returning any output for the evaluation.

**Affected Versions:**
Swanlake-Beta6 at least

**Comment by NipunaRanasinghe** [comment]
I tried reproducing the issue and noticed that this behaviour can be observed only for some object methods of the `response` object. (i.e rep.getByteStream(), response.getContnetType() is working fine)

**Comment by NipunaRanasinghe** [comment]
Closing with #34775. Tested in RC2 pack and everything works as expected.
