### ISSUE TITLE
Need to support type inferring for constants 

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#34623]
**Description:**

The type architecture ATM follows a top down approach, assuming that we know the type, as a result we are unable to do type inferring for constants. We need to modal this in a bottom up approach. 

**Steps to reproduce:**
Instances like the one shown below is not supported ATM
`const NEG_TWO = -2;`

**Comment by MaryamZi** [comment]
> Instances like the one shown below is not supported ATM 
> `const NEG_TWO = -2;`

Isn't this particular example the same case as the type being required with non-literal expressions, being tracked in https://github.com/ballerina-platform/ballerina-lang/issues/28334?

> The type architecture ATM follows a top down approach, assuming that we know the type, as a result we are unable to do type inferring for constants. We need to modal this in a bottom up approach.

Not sure I get how this is relevant here. In most cases we defer resolving a type until whatever types that type depends on are resolved. We also have https://github.com/ballerina-platform/ballerina-lang/issues/32617 tracking a more generic solution.

**Comment by MaryamZi** [comment]
Closing since this is being tracked by other issues.
