### ISSUE TITLE
Write Tests for Type- Narrowing

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34631]
No of people: 2
Write test cases for all the type-narrowing cases

- [x] If stmt
- [x] Ternary Expr
- [x] While Stmt
- [x] From Clause
- [x] From Do Stmt
- [ ] Match Stmt

Report bugs if there are any which are not reported

**Comment by MaryamZi** [comment]
In-line with the spec's definition of narrowing this needs to focus on the changes we did to narrowing to allow for semantic subtyping also.
