### ISSUE TITLE
Constant names should be shown instead of their values in error messages

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#34640]
**Description:**

The following code snippet,
```bal
const NUMBER = 1;

public function main() {
    NUMBER x1 = "hello";
}
```
will give
```
Compiling source
        compile-err.bal
ERROR [compile-err.bal:(4:17,4:24)] incompatible types: expected '1', found 'string'
error: compilation contains errors
```
In the given compilation error, what is shown is the constant value and not the constant name. Instead of constant value `1`, the constant name `NUMBER` should be shown.

**Steps to reproduce:**
Depicted above.

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
This gives the correct error message in `Ballerina 2201.4.0`
