### ISSUE TITLE
No error given when resolve transitive dependency from bala has built with higher dist version

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#34650]
**Description:**
When resolving dependency from a bala has built from higher distribution version, that should be ignored, and `cannot resolve module` error should be thrown. But no error was given when trying to write a test case [1] for the above scenario.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/34561/commits/3ebc69a4fbd2059eb66c8964765cf19333ab1fd0

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
Need to enable [test](https://github.com/ballerina-platform/ballerina-lang/pull/34561/commits/7f65286896ea427bc9f22715df784db4dee6d405) after fixing this issue

**Comment by azinneera** [comment]
Since this will only occur when a newer version like SL Update1 is released, we may add this as a patch release after the GA.
