### ISSUE TITLE
Ignore unused variable code action in let expression not working

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#34668]
**Description:**
```
public function main() {
    int _ = let int a = 1, int b = 2 in a;
}
```
there is a diagnostic `unused variable 'b'(BCE20403)` shown for above code snippet but we do not provide code action to ignore the unused variable.

Also for the following scenario in the module level we do not provide the said code action but also we do not provide diagnostics for that case. Hence that is expected.

```
import io;

int a = 10; // unused variable

public function main() {
    int b = 10;
    io:println(b);
}
```

**Comment by nadeeshaan** [comment]
Closing, since the fix has been merged
