### ISSUE TITLE
nBallerina test `testTypesJson` fails with `error : There are test failures` and no stacktrace

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#34662]
**Description:**
An exception stemming from the test is not handled properly by testerina when printing the stack trace. 
The actual error is an ArrayIndexOutOfBounds which is more critical 

**Steps to reproduce:**
Run nballerina tests with the latest distribution pack

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

Sub issues
- [x] #34660
- [x] #34663

**Comment by manuranga** [comment]
Last successful build was https://github.com/ballerina-platform/ballerina-distribution/actions/runs/1651121237
Fist unsuccessful build was https://github.com/ballerina-platform/ballerina-distribution/actions/runs/1654653748
@warunalakshitha I think it's worth to look at what the pr merged to lang between those two builds.
