### ISSUE TITLE
Improve the runtime frames yield depth size to increase dynamically

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#34671]
**Description:** 
ATM max frames stack size is 256 but we can start with a small number and increase it dynamically on demand.

**Comment by manuranga** [comment]
Since we copy stack to heap only on yield lazily, is should be possible to start with no frames array at all.

**Comment by warunalakshitha** [comment]
Following code will break due to maximum frame yeild depth size

`ballerina
public function main() {
   bar(0);
}

function bar(int x) {
    if (x == 200) {
        io:print(x);
        runtime:sleep(1);
    } else {
        bar(x + 1);
    }
}
`

**Comment by Nadeeshan96** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35034.
