### ISSUE TITLE
Missing completions of the parameter inside the logic of the while loop

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34701]
**Description:**
$title

Try to get completions on the following cursor position

```ballerina
function convertCsvToTable(io:ReadableCSVChannel readableCsvChannel) returns table<DataRecord> {
    table<DataRecord> dataRows = table []; // Define the table

    readableCsvChannel.skipHeaders(1); // Skip headers

    while re<cursor> {

    }
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment]
@dulajdilshan just checked this in Swan Lake RC1 pack. Completions seem to be working fine.
![completions](https://user-images.githubusercontent.com/11285165/150296649-3ae519cc-5a48-4c2a-a637-7a64bc185167.gif)

Can you verify as well?

**Comment by dulajdilshan** [comment]
> @dulajdilshan just checked this in Swan Lake RC1 pack. Completions seem to be working fine. ![completions](https://user-images.githubusercontent.com/11285165/150296649-3ae519cc-5a48-4c2a-a637-7a64bc185167.gif)
> 
> Can you verify as well?

Yeah. It's working.
