### ISSUE TITLE
Renaming a symbol with invalid syntax to a valid state does not work 

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#34705]
**Description:**

Rename `XYZ` to `io` in the following code snippet.

```
import ballerina/io;

public function main() {
    XYZ:print();
}
```

**Steps to reproduce:**

![renaming-invalid-to-valid](https://user-images.githubusercontent.com/9464997/149902765-0b84c653-1e03-485a-8f96-53429449386f.gif)

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment]
We also need to consider the literals.

**Comment by IMS94** [comment]
The decision was to not provide the rename popup (via `prepareRename` phase) for invalid qualified name references. In the original example, we will not show rename option to the `xyz` invalid module prefix.
