### ISSUE TITLE
Table lookup doesn't check equality on keys where there is only one hash candidate 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#34712]
**Description:**
```ballerina
import ballerina/io;
type R record {|
    readonly int|float|decimal|boolean v;
    int code;
|};

type Tab table<R> key(v);

public function main() {
    Tab t = table [
            {v: 0, code: 0}
        ];

    io:println(t);
    io:println(t[0f]);
}
```

The offender seems to be ignoring the `equals` check:
https://github.com/ballerina-platform/ballerina-lang/blob/472454e8fdb97e2568277de407607186f41f91e5/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/values/TableValueImpl.java#L588

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rpjayasekara** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34716
