### ISSUE TITLE
Incorrect filter text in table type descriptor snippet block with key

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34729]
**Description:**

Consider the completion item `type TypeName table<> key`.
<img width="812" alt="Screenshot 2022-01-19 at 12 46 16" src="https://user-images.githubusercontent.com/27485094/150082316-b96095d0-3a53-4d5a-ab1a-20dcaf0bfb17.png">

It disappears when I type anything beyond `t`.
<img width="812" alt="Screenshot 2022-01-19 at 12 42 32" src="https://user-images.githubusercontent.com/27485094/150082085-9cf3c34d-dc89-411d-8dd7-5ce18d7d940d.png">

**Affected Versions:**
stage-swan-lake

**Comment by nadeeshaan** [comment]
Closing the issue since the fix has been merged
