### ISSUE TITLE
Add unrechability analysis support for unreachable sub expressions

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#34722]
**Description:**
According to the unreachability section of the spec
> Similarly, when the evaluation of a subexpression is conditional on the result of previously evaluating another subexpression, then the analysis assumes that the second evaluation is possible unless the static type of the first subexpression makes it impossible

With this, we need to add unreachability analysis support for

- [ ] Conditional expression (#33202)
- [ ] logical-and-expr
- [ ] logical-or-expr

**Comment by MaryamZi** [comment]
Need to verify this based on https://github.com/ballerina-platform/ballerina-spec/issues/887#issuecomment-991825589 and the last sentence in the unreachability section of the [spec](https://ballerina.io/spec/lang/master/#section_7.4.3).

**Comment by rdulmina** [comment]
> Need to verify this based on [ballerina-platform/ballerina-spec#887 (comment)](https://github.com/ballerina-platform/ballerina-spec/issues/887#issuecomment-991825589) and the last sentence in the unreachability section of the [spec](https://ballerina.io/spec/lang/master/#section_7.4.3).

Created spec issue https://github.com/ballerina-platform/ballerina-spec/issues/1028
