### ISSUE TITLE
Provide a meaningful port number for the generated service snippets

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#34724]
**Description:**
```
import ballerina/http;
service  on new http:Listener(0) {
    
}
```
As shown above, the auto-complete snippet generates the service with the port 0. Instead shall we provide a port number such as `8080`?

**Affected Versions:**
Swanlake-beta6 at least

**Comment by malinthar** [comment]
For the explicit new expression we generate values for required parameters of the init function  using the getDefaultValueForType() method. Hense, special casing looking at the parameter name is not ideal IMHO. WDYT @nadeeshaan ?

**Comment by nadeeshaan** [comment]
@malinthar yes, Since we use the generic implementation and we cannot rely on the param name that is not straight forward. We might need to have some sort of a meta information to do so. Maybe a meta annotation. 
@shafreenAnfar thoughts?

**Comment by shafreenAnfar** [comment]
Yeah, some default would be nice but I don't mind the current experience either. I feel if there is no straight forward way, we can park this problem and revisit later.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
