### ISSUE TITLE
[ProjectAPI] Write Integration tests for Package Resolution

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#34730]
**Description:**

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
Fixed comments discussed on first code review with https://github.com/ballerina-platform/ballerina-lang/pull/34804/commits/1a55ea0f080cf413577ced7c2e9a869504d73307

**Comment by pramodya1994** [comment]
2nd code review comments:
- Add another build scenario with `build` file for `testCase0006`

**Comment by Ibaqu** [comment]
Review comments :  
- [ ] Cover cases 0007 - 0009
- [ ] Rename covered cases to 0010 - 0012. Refactor where applicable
