### ISSUE TITLE
Applying code actions for an incorrect usage of `value:ensureType` function leads in compilation errors

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#34743]
**Description:**
$title

**Steps to reproduce:**

![screencast3](https://user-images.githubusercontent.com/19838787/150288281-29b591fc-f2e0-43d3-a375-34c10289cc4d.gif)

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake) RC1

**Comment by nadeeshaan** [comment]
Similar issue.
https://github.com/ballerina-platform/ballerina-lang/issues/34694
