### ISSUE TITLE
Getting unnecessary suggestions after resetting the type of a type narrowed variable

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#34747]
**Description:**
$title

**Steps to reproduce:**
Consider the following example.
```ballerina
public function main() {
    int? a = 10;
    if a is int {
        a += 1; // type reset to `int?`
        int? _ = a<curser> 
    }
}
```
`a`'s type seems to be suggested as `int` even after the type has been reset. 
This results in getting unnecessary suggestions for `a`.

![screencast4](https://user-images.githubusercontent.com/19838787/150303458-486a314d-fc17-485b-8d9d-824082c50e74.gif)

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake) RC1

**Comment by KavinduZoysa** [comment]
Fixed in `Ballerina 2201.4.0`.
