### ISSUE TITLE
Unreachability not checked within query actions

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#34744]
**Description:**
```ballerina
check from var item in 1...5
where false
do {
    io:println("this is unreachable");
};
```

**Steps to reproduce:**

**Affected Versions:**
SL GA RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34784
