### ISSUE TITLE
Getting the Original Members of a Union Type

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#34752]
**Description:**
Consider the following Ballerina code:

```ballerina
distinct service class Student {
}

distinct service class Teacher {
}

function getPerson() returns (Teacher|Student)?[] {
    return [];
}
```

Using the runtime (native) APIs, if I get the return type of the `getPerson()` method, it is an `ArrayType`. Then if we get the element type of this array, it is a union type. Then if we call `getOriginalMemberTypes()` on this union type, it returns a list of two elements.

The sample code:

```java
import io.ballerina.runtime.api.types.ArrayType;
import io.ballerina.runtime.api.types.MethodType;
import io.ballerina.runtime.api.types.Type;
import io.ballerina.runtime.api.types.UnionType;

static void checkReturnType(MethodType methodType) {
    Type returnType = methodType.getType.getReturnType(); // ArrayType
    Type elementType = ((ArrayType) returnType).getElementType(); // UnionType
    List<Type> originalMemberTypes = ((UnionType) elementType).getOriginalMemberTypes();
}
```

The `originalMemberTypes` list here contains two elements:

0. `Teacher|Student`
1. `()`

Shouldn't this be a list of three elements (like below)?

0. `Teacher`
1. `Student`
2. `()`

Seems like the parenthesis around the `Teache|Student` makes them a single member of a union type, but feels like they are still two members of the original union type. The parenthesis are used only because there is no other way to define an array of `Teacher|Student?`.

**Comment by MaryamZi** [comment]
This is probably because the usage of parentheses make `(Teacher|Student)` a separate type, as if it were

```ballerina
type Person Teacher|Student;

function getPerson() returns Person?[] {
    return [];
}
```

Initial thoughts, the current behaviour seems OK to me. We'll have to discuss and see though.
