### ISSUE TITLE
Directories with spaces breaks ballerina

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#34757]
**Description:**
I created a directory call `a a` and move into that and executed `bal -v` which causes following issue

```
Error: Could not find or load main class a
Caused by: java.lang.ClassNotFoundException: a
Update Tool 1.3.7-rc2
```

However this issue has been there for several versions and it works in version `slalpha5` or older versions

OS : Mac

**Comment by NipunaMadhushan** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34740.
