### ISSUE TITLE
Missing completions in table type descriptor node context

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34750]
**Description:**
Missing completions for
1. Record type descriptor snippet
<img width="744" alt="Screenshot 2022-01-20 at 15 52 13" src="https://user-images.githubusercontent.com/27485094/150320605-7c8ee152-21e3-491b-bac4-e820993c8ec5.png">

2. `key` keyword
<img width="744" alt="Screenshot 2022-01-20 at 16 09 27" src="https://user-images.githubusercontent.com/27485094/150323020-4397bb63-0ddc-450a-ba87-de1a480c56b7.png">

**Steps to reproduce:**
1.
```
table<record {|string name;|}> t = table [{name: "A"},
                                          {name: "B"}];
```
2.
```
type Person record {
    readonly string name;
    int age;
};

type PT table<Person> key(name);
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake) RC1

**Comment by nadeeshaan** [comment]
Case 1 is fixed with #34770 and case 2 is a limitation at the moment.

**Comment by nadeeshaan** [comment]
Here in the the use-case 2, `k` is identified as a module level variable declaration, instead of a part of the table type descriptor. The reason could be that the `key` keyword is optional in a table type descriptor. 
@rdulmina @lochana-chathura Is there any way we can handle this?

**Comment by lochana-chathura** [comment]
I'm afraid we can't do anything from the parser side. Consider the following example,
`table<Person> k = table [{name:"Alice", age:21}];`
Thing is if the `table<type-descriptor>` is followed by `k` we can't conclude it is going to be `key`.

**Comment by nadeeshaan** [comment]
> I'm afraid we can't do anything from the parser side. Consider the following example, `table<Person> k = table [{name:"Alice", age:21}];` Thing is if the `table<type-descriptor>` is followed by `k` we can't conclude it is going to be `key`.

@lochana-chathura I was having the same concern. May be we have to keep this as a known limitation for now.

**Comment by nadeeshaan** [comment]
Closing the issue, since use-case 1 is resolved and created a separate issue to track use-case 2

https://github.com/ballerina-platform/ballerina-lang/issues/34945
