### ISSUE TITLE
Change variable type code-action removes the variable  

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34762]
**Description:**
$title

```ballerina
type Employee record {
    readonly string name;
    int salary;
};

table<Employee> key(name) tart = table [
    { name: "John", "salary": 100},
    { name: "James", salary: 300}
];

public function main() {
    table tValue = tart;
}
```
![Code-Action-removes-variable-Peek 2022-01-21 09-54](https://user-images.githubusercontent.com/25485997/150465551-18b5b5f6-63bf-4f59-9b99-44546141ee28.gif)

**Steps to reproduce:**

**Affected Versions:**
VSCode v3.0.0-preview-m9, Ballerina v2201.0.0-rc1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@dulajdilshan isn't the source we are having is with a syntax error in the table type? The resolved tree might have been the root cause for this.

**Comment by dulajdilshan** [comment]
> @dulajdilshan isn't the source we are having is with a syntax error in the table type? The resolved tree might have been the root cause for this.

Yeah, it has a syntax error.

**Comment by IMS94** [comment]
This issue was caused by LS relying on diagnostics on a recovered node (by parser). Fix is to avoid suggesting code actions when a node has syntax errors.
