### ISSUE TITLE
Incorrect create function code action 

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#34767]
**Description:**

In the first two scenarios we do not give the expected return type and its default value in the created function even though we identify the return type by the compiler. In the 3rd scenario, the number of parameters are doubled and has changed its name and type.

1) 
![Screenshot 2022-01-21 at 11 22 10](https://user-images.githubusercontent.com/46120162/150473515-bbe81bd5-ae21-45bc-a99d-fff6712461aa.png)

2)
![Screenshot 2022-01-21 at 11 23 16](https://user-images.githubusercontent.com/46120162/150473618-d4400395-67a9-46c7-9f1f-8837c613ac8b.png)

3)
![Screenshot 2022-01-21 at 11 24 23](https://user-images.githubusercontent.com/46120162/150473749-10257074-6b53-49d9-81f4-e628ebc4516c.png)

**Steps to reproduce:**
1)
```
function test1() {
    fail getFail();
}
```
2)
```
function test2() returns int {
    return getReturn();
}
```
3)
```
function test3() {
    boolean a = true;
    a = getBool(boolean q, boolean w);
}
```

**Affected Versions:**
SL 2201.0.0 RC1

**Comment by nadeeshaan** [comment]
For 1 and 2, in both cases we get `CompilationErrorType` as the type of the symbol.

For the case 3, the source is having a syntax error. The recovered syntax is assuming that we have a function with four arguments. Hence we will need to check this more deeply on how to handle such sccenarios.

**Comment by gayalkuruppu** [comment]
Please consider the following scenario as well 
```
function test4() {
    int a = check getCheck();
}
```
