### ISSUE TITLE
Completions not working for unions of errors

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34789]
Consider the following:
```ballerina
type ErrX distinct error;
type ErrY distinct error;

type Err ErrX|ErrY|error<map<anydata>>;

public function main() {
    Err err = error ErrX("Foo");
    string message = err.<cursor>
}
```
Calling `err.message()`, `err.cause()` is allowed on unions of errors. Therefore, I think we need to provide those suggestions as well.

**Comment by nadeeshaan** [comment]
I think we need to consider the union of errors specially when providing the langlib methods via the `typeSymbol.langLibMethods()`. In the current implementation we only provide the symbols associated to the union type without considering the union members. If we consider the API user point of view, the user has to do explicit analysis of the type to capture the particular langlib methods.

@dulajdilshan @mohanvive @pubudu91 thoughts?
