### ISSUE TITLE
Assigning to a type narrowed var seems to blindly reset its type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34783]
Consider the following:
```ballerina
function fromBytes(byte[] b) {
    string|error fromBytesResult = string:fromBytes(b);
    
    if fromBytesResult is error {
        panic fromBytesResult;
    }

    string s = fromBytesResult; // valid

    fromBytesResult = "foo"; // this seems to reset the type despite this expr being a string expr

    s = fromBytesResult; // incompatible types: expected 'string', found '(string|error)'
}
```
In the above case, assigning a string typed expr to `fromBytesResult` shouldn't reset its type to `string|error` right?

**Comment by MaryamZi** [comment]
Any assignment to a type-narrowed variable resets the type of the variable.

This is in-line with the current [spec](https://ballerina.io/spec/lang/2022R1/#conditional_variable_type_narrowing).

> A narrowed type for a variable x implied by an expression in which x occurs ceases to apply in a region of code where there is a possibility at runtime that x has been assigned to since the evaluation of the expression.

Related discussion - https://github.com/ballerina-platform/ballerina-spec/issues/842.
