### ISSUE TITLE
Go-to definition and renaming doesn't work for table's row type parameter

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34801]
**Description:**
$title

![Rename_table_type_param_Peek 2022-01-24 14-26](https://user-images.githubusercontent.com/25485997/150757330-4d5f0edc-d6af-4f89-b842-09ce8782ba92.gif)

Source code:
```ballerina
type Person record {|
    readonly int id;
    string name;
|};

type Student record {|
    *Person;
    int examYear?;
|};

function doThis() returns table<Student> {
    table<Person> tHuman = table [{id: 1, name: "Dulaj"}];

    table<Student> tStudent = tHuman.map(function(Person human) returns Student {
        return {
            id: human.id,
            name: human.name
        };
    });
    return tStudent;
}

```
Try renaming `table<Person<cursor>>`
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
This is happening due to the token capture logic. We consider the left inclusive and right exclusive approach to find a token. Also, this is only limited to this particular scenario and other symbols are working without issue. Hence considering as an improvement point.
