### ISSUE TITLE
`bal new -t choreo/<CoreoSampleName> <newProjectName>` command doesn't generate the Ballerina.toml with `keywords` field

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-lang#34807]
**Description:**

When we try to generate a package using an existing Choreo sample by using the command `bal new -t choreo/<CoreoSampleName> <newProjectName>`, for example `bal new -t choreo/gsheet_new_row_to_github_new_issue myProject`, it doesn't generate the Ballerina.toml with `keywords` field.

**Steps to reproduce:**
Run the following command `bal new -t choreo/gsheet_new_row_to_github_new_issue myProject`
This will use the following sample.
https://github.com/wso2-enterprise/choreo-samples/tree/choreo-v2/samples/integrations/gsheet-new-row-to-github-new-issue
You can see that the sample includes the `keywords` field in the Ballerina.toml 
https://github.com/wso2-enterprise/choreo-samples/blob/39ab1153361b7765e92358c059fc4b143b86a64d/samples/integrations/gsheet-new-row-to-github-new-issue/Ballerina.toml#L6
But the Ballerina.toml of the generated package doesn't include this information. 
![Screenshot from 2022-01-24 16-57-33](https://user-images.githubusercontent.com/44081958/150774966-f6847925-17f8-40b5-8504-7f2ddb2c194e.png)
The `keywords` field is missing. This is a common issue across all the samples.

**Affected Versions:**
Ballerina Version SL Beta 6 

**OS, DB, other environment details and versions:**
Ballerina Version: SLBeta6
Operating System: Ubuntu 20.04
Java SDK: 11

**Related Issues (optional):**

**Suggested Labels (optional):**

Priority/High

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
According to `writeBallerinaToml` in [CommandUtil](https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/CommandUtil.java#L327), currently, we are not writing existing keywords from the template. So we can simply add those to the newly created project `Ballerina.toml` file from this method.

@azinneera Is there any reason why we are ignoring `keywords` here? Can we add them here?
