### ISSUE TITLE
Continue comment when ENTER is pressed

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34816]
**Description:**
$subject.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/39232462/150926008-837f1e7a-2da5-4223-97e0-31290cb85b5e.gif)

As shown in the gif above `#` is continued when ENTER is pressed for ballerina doc comments.
But this is not working for the regular comments.

**Comment by lochana-chathura** [comment]
I think we need to continue the comment only when the cursor is inside the comment.
e.g. `// comment. <cursor>`  ENTER at cursor should not continue the comment as most of the case user may be trying to not write a comment in the next line.

**Comment by mohanvive** [comment]
IMO, the behaviour of the document comment`#` is valid. But, yes we should improve the `//` comment because we use that as both multi line and single line comment in Ballerina.

**Comment by nadeeshaan** [comment]
This particular behaviour is a part of the VSCode's default single line comment approach. If we are to fix this, we will have to specially handle these cases from the VSCode plugin. Even though we try to fix it from the plugin, implementation can be tricky given the structure/ patterns of the syntaxes.

**Comment by mohanvive** [comment]
Closing with the above comment.
