### ISSUE TITLE
Invalid mapping function generated from AI data mapper code action

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-lang#34829]
**Description:**
Consider the following code:

```
type Person record {
    string name;
    int age;
};

type Employee record {
    string name;
    int age;
    int empNo;
};

public function main() {
    Employee employee = {name: "Jane Doe", age: 25, empNo: 1};
    Person person = <Employee> employee;
    Employee employeeResult = <Person> person;
}
```

Once the `Generate mapping function` code action is executed on `Employee employeeResult = <Person> person;`, the following invalid function snippet is generated.
```
function mapEmployeeToPerson (Employee employee) returns Person {
// Some record fields might be missing in the AI based mapping.
	Person person = {age: employee.age, name: employee.name};
	return person;
}
```

If the explicit typecast is to be replaced with a mapping function, the argument type of it should be corrected to `Person` from `Employee` and, the return type should be corrected to `Employee` from `Person`.

**Steps to reproduce:**
![invalid-datamapper-generation](https://user-images.githubusercontent.com/9464997/150965605-8b930ed7-5610-48b6-aecd-cce651a7f51d.gif)

**Affected Versions:**
2201.0.0 (Swan Lake)

**Comment by isuruRuhu** [comment]
Do we still have this issue?

**Comment by isuruRuhu** [comment]
Closing this issue since we don't have this component in Ballerina anymore
