### ISSUE TITLE
NPE when using query expression with undefined record types

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#34831]
**Description:**
$title

**Steps to reproduce:**
1. Copy and paste the following ballerina source code to a file
```ballerina
function filterWithColumn(table<UndefinedRecordType> tableData, string colLabel, string colValue) returns table<UndefinedRecordType> {
    table<UndefinedRecordType> tableResult = from UndefinedRecordType row in tableData
        where row[colLabel] == colValue
        select row;

    return tableResult;
}
```
2. Run the the code with `bal run`

**Affected Versions:**
VSCode v3.0.0-preview-m9, Ballerina v2201.0.0 RC2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
Possibly related to https://github.com/ballerina-platform/ballerina-lang/issues/34621

**Comment by rdulmina** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36044
