### ISSUE TITLE
Invalid diagnostic `attempt to expose non-public symbol ''` for the valid code

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34839]
**Description:**
```bal
public function test(1|2|3 n) {
    if n is 2 {
        return;
    }

    1|3 _ = n;
}

```

![Screenshot from 2022-01-26 11-01-13](https://user-images.githubusercontent.com/39232462/151109036-56422fad-f7da-4dda-b6c2-4c86765236b2.png)

**Affected Versions:**
2201.0.0 RC2

**Comment by lochana-chathura** [comment]
Even for the valid scenarios, I think we need to give the error for the `return-stmt` instead of highlighting the whole `function-defn`.

**Comment by rdulmina** [comment]
The incorrect error message for singleton types is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/36959.. Need to fix the error pos for valid scenarios

![image](https://user-images.githubusercontent.com/26381349/188874514-cf0717ae-b4e3-4052-bdc9-636d3ea14723.png)
