### ISSUE TITLE
Update LS simulator to simulate delete operations

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34886]
**Description:**
Right now, the LS simulator workflow only adds content to a source file. Need to update it to remove content from a source file. Especially `imports` and etc.

**Describe your problem(s)**
See description

**Describe your solution(s)**
Need to update the design to support deletion operations

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
