### ISSUE TITLE
Invalid diagnostics appear when a `.bal` is renamed in VSCode extension

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#34895]
Open a Ballerina package with VSCode. Implement a simple HTTP example. Now rename the `.bal`. You will see invalid diagnostics in the file.

**Comment by nadeeshaan** [comment]
This will be addressed with #34933

**Comment by nadeeshaan** [comment]
@sameerajayasoma do you have an example scenario when this happened? I tried with the latest VSCode and VSCode plugin while I could not reproduce this issue.

**Comment by TharushiJay** [comment]
Closing the issue since it cannot be reproduced.

**Comment by sameerajayasoma** [comment]
I can't reproduce now too. Looks like it is fixed
