### ISSUE TITLE
Fix the warnings given by `test` module

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#34892]
**Description:**
$subject. Refer to issue #34884 description for more details.

![Screenshot from 2022-01-28 16-49-17](https://user-images.githubusercontent.com/39232462/151538167-c2e45fd3-7f93-4db1-b400-fc65dbfe434a.png)

**Affected Versions:**
2201.0.0 RC3

**Comment by Ibaqu** [comment]
Documentation was not included which caused the warnings to appear.
