### ISSUE TITLE
Deleting a source file doesn't clear diagnostics of that file

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34903]
**Description:**

Create a ballerina project. Add another `bal` file and type something invalid there. In VSCode, under the `problems` tab, you will see errors related to that newly created file. 

Now, delete the new file and look at the `Problems` tab. Diagnostics are still there.

**Steps to reproduce:**
See description

**Affected Versions:**
Swan Lake 2201 GA

**Comment by nadeeshaan** [comment]
Will be addressed with #34933

**Comment by TharushiJay** [comment]
Closing since the fix has been merged with https://github.com/ballerina-platform/ballerina-lang/pull/35771.
