### ISSUE TITLE
Implement file operation events in Language server

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#34933]
**Description:**
Currently, we do not honour the file renaming, deleting and creation, based on the file events emitted by the editor.
https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#workspace_willCreateFiles

**Comment by IMS94** [comment]
Related PR https://github.com/ballerina-platform/ballerina-lang/pull/35771

**Comment by mohanvive** [comment]
Closed with, https://docs.google.com/document/d/17ixNBCHbODkaz3BE1Kos2KvrLw1OQWSb4zcrnpPq9AI/edit
