### ISSUE TITLE
Replace usage of commands in code actions with `codeAction/resolve` request

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#34935]
**Description:**

Since LSP 3.16, there's a `codeAction/resolve` request which we can use to computer the `edit` of the code action. See the related section in LSP spec: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#codeAction_resolve

By using this approach, we can remove the usage of commands which we are using currently for code actions like create function and documentation related code actions.

Need to check the following:
* By enabling resolve support, will all the code actions be required to be migrated to this format. If so, this may not be worthy.

**Describe your problem(s)**
This is more of an improvement. A best practice to reduce computation of text edits when computing the code actions.

**Describe your solution(s)**
Use LSP's `codeAction/resolve` to compute text edits.

**Comment by IMS94** [comment]
@nadeeshaan WDYT of this?

**Comment by nadeeshaan** [comment]
> 

@IMS94 I'm +1 for this. First of all we have to go through the current code actions and identify the ones with text edits which are having a significant computation complexity. Let's start with that and proceed.

**Comment by IMS94** [comment]
@nadeeshaan +1. Let's take this up once the current important items are cleared from the backlog.

**Comment by mohanvive** [comment]
Prioritised this issue over https://github.com/ballerina-platform/ballerina-lang/issues/36139 .
