### ISSUE TITLE
Completions for the `key` keyword is not provided

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#34945]
**Description:**
Completions are not provided at the cursor position due to the limitation of context identification's ambiguity.

```
type Person record {
    readonly string name;
    int age;
};

type PT table<Person> k<cursor>

```

Additional discussion:
https://github.com/ballerina-platform/ballerina-lang/issues/34750#issuecomment-1026539528

**Comment by IMS94** [comment]
Here the following scenario works:
```ballerina
type PT table<Person> <cursor>
```
But the following doesn't:
```
type PT table<Person> k<cursor>
```
Since the unsupported scenario has a low frequency to occur and the parser is unable to recover better, closing this issue. Please raise a new issue if the same concern arises in the future.

**Comment by lochana-chathura** [comment]
> @lochana-chathura Since the unsupported scenario has a low frequency to occur and the parser is unable to recover better, shall we close this issue?

+1
