### ISSUE TITLE
When the completion type has no nil it should reflect in type param `CompletionType`

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#34966]
**Description:**
Looks like `next` methods return type is the union with `nil` and expected completion type. Changing the code to accept a `IntRecord|error?` from next removes the crash. But spec does not mention that the completion type can be `nil` implicitly. This could be a issue in type param analyser and should reflect in all the places we have `CompletionType`

#### Spec
>A type stream<T,C> where C does not include nil describes an unbounded stream

#### Ballerina code
```ballerina
type IntRecord record {|
    int value;
|};

function init() {
    stream<int, error> emptyStream = new stream<int, error>();
    IntRecord|error returnedVal = emptyStream.next();
    if (returnedVal is IntRecord) {
        io:println(returnedVal.value);
    } else {
        io:println(returnedVal);
    }
}
```

#### Crash Log
```LogTalk
SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at s4.init(s4.bal:38)
        at $_init.$gen$$0046$0060init$0062(.:1)
        at $_init.$moduleInit(.)
        at $_init.$lambda$$moduleInit$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
- https://github.com/ballerina-platform/ballerina-lang/issues/31671

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pcnfernando** [comment]
The issue here is when we construct a stream using `new` without providing a `StreamImplementor<T,E?>`, we use `nil` returning iterator by default. 
From the spec
> When the arg-list is empty, the result will be an empty stream (i.e. a stream whose next method returns nil).

This crash was caused when trying to assign the iterator's `next()` return value which is `()` to the unbounded stream's completion type `error`. We have to restrict this usage at compile time for unbounded streams.

**Comment by KavinduZoysa** [comment]
This is a compile-time error in `Ballerina 2201.4.0`
