### ISSUE TITLE
Wrong location given for diagnostic related to constants

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#34974]
Consider the following:
```ballerina
const C = {foo: s};
          ^^^^^^^^
```
For the above, I get the following compile error:
```
ERROR [test2.bal:(8:11,8:19)] type is required for constants with expressions
```
The location given in the diagnostic is underlined in the above code snippet. This location is incorrect. I think we should be giving this error to the constant itself. i.e., `C`. It is misleading to give the error to the const expr.

**Comment by MaryamZi** [comment]
This error will not be logged once we fix https://github.com/ballerina-platform/ballerina-lang/issues/28334.
