### ISSUE TITLE
Abstract objects gives incorrect VSCode suggestions 

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#35002]
**Description:**
Ballerina time module has an implementation, which uses an abstract object `Zone`. Then, we extend the abstract object to implement the actual logic `TimeZone`.

For these APIs, the VSCode gives incorrect suggestions, see below.

<img width="458" alt="Screenshot 2022-02-10 at 11 57 38" src="https://user-images.githubusercontent.com/18663444/153351985-a7b8d90c-9ef0-4d29-aed8-fdae7bd25170.png">

The code snippet it gives is as follows,
<img width="454" alt="Screenshot 2022-02-10 at 12 13 40" src="https://user-images.githubusercontent.com/18663444/153352249-35b278f5-ed14-4aad-976c-590ed114a8b3.png">

But the correct suggestion should be,

```ballerina
import ballerina/time;
import ballerina/io;

public function main() returns error? {
    time:Zone timezone = check time:loadSystemZone();
    time:Civil civil = timezone.utcToCivil(time:utcNow()); // without Zone
    io:println(civil);
}

```
**Affected Versions:**
SL GA

**OS, DB, other environment details and versions:**
- macOS
- VSCode version: 1.64.1
- Ballerina VSCode extension: 3.0.0

**Comment by IMS94** [comment]
Had a look into this. LS relies on the function name provided by the function symbol to generate the insert text, in this case `Zone.utcToCivil()`. I could reproduce this on both 2201.0.0 and 2201.0.1. But when tried with 2201.0.x branch after pulling `time` module from central, the completions worked as expected.
![Screenshot from 2022-03-08 17-19-40](https://user-images.githubusercontent.com/11285165/157232773-1b2f94be-018f-4aaa-b3b6-951fde275d37.png)
Seems like a BIR issue. Need to dig deep.
