### ISSUE TITLE
Incorrect static type of  `member-access-expr` when the static type of `container-expression` is a subtype of `xml<M>`

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35019]
**Description:**
$title
The spec (https://ballerina.io/spec/lang/master/#member-access-expr) says,

> Let T the static type of container-expression. ......
>  If T is a subtype of xml\<M\>, then the static type of the member-access-expr is M|E, where E is the type of the empty xml value.

**Steps to reproduce:**
```ballerina
type XmlType1 xml<xml:Element|xml:ProcessingInstruction>;

function init() {
    xml a1 = xml `<name>Sherlock Holmes</name><!--Comment-->`;
    xml:Element|xml:Comment|xml:ProcessingInstruction|xml:Text b1 = a1[0]; // OK

    xml<xml:Comment> a2 = xml `<!--Comment1--><!--Comment2-->`;
    xml:Comment b2 = a2[1]; // incompatible types: expected 'xml:Comment', found 'xml<xml:Comment>'

    xml<xml:ProcessingInstruction> a3 = xml `<?xml-stylesheet type="text/xsl" href="style.xsl"?>`;
    xml:ProcessingInstruction b3 = a3[0]; // incompatible types: expected 'xml:ProcessingInstruction', found 'xml<xml:ProcessingInstruction>'

    xml<xml:Element> a4 = xml `<name>Sherlock Holmes</name><name>Enid Blyton</name>`;
    xml:Element b4 = a4[1]; // incompatible types: expected 'xml:Element', found 'xml<xml:Element>'

    xml<xml:Text> a5 = xml `Some Text`;
    xml:Text b5 = a5[0]; // OK
    xml<xml:Text> b6 = a5[0]; // OK

    XmlType1 a6 = xml `<name>Enid Blyton</name><name>Dan Brown</name>`;
    xml:Element|xml:ProcessingInstruction b7 = a6[1]; // incompatible types: expected '(xml:Element|xml:ProcessingInstruction)', found 'xml<(xml:Element|xml:ProcessingInstruction)>'
}
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment]
I've implemented the changes to fix the static type, but the change may result in langlib functions being called on xml unions now, in places that were previously a langlib call on a value of the `xml` type.

E.g.,

```ballerina
xml<xml:Comment> a = xml ``;
int length = a[0].length();
```

But, xml langlib functions aren't supported on unions yet - https://github.com/ballerina-platform/ballerina-lang/issues/28697. Putting this issue on hold to see if we can fix that since if not, this could be a backward incompatible change.
