### ISSUE TITLE
Prioritize `println()` over `print()` and `string` over `stream` in LS completions

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#35017]
**Description:**
$subject.

**Describe your problem(s)**
1. `println()` is the common usage. One would rarely use `print()`. We need to give priority to former one. Picking the second suggestion every time you want to print something is quite annoying.

![Screenshot from 2022-02-10 21-37-37](https://user-images.githubusercontent.com/39232462/153448054-a2baa991-76f4-41b7-86e5-5d8476717ac6.png)

Java:
![Screenshot from 2022-02-10 13-26-34](https://user-images.githubusercontent.com/39232462/153448326-b6eef8da-d35b-486c-a1ad-a36e16169033.png)

2. Every time you want to type `string`, `stream` comes as the first suggestion. This is annoying too.
![Screenshot from 2022-02-10 13-06-25](https://user-images.githubusercontent.com/39232462/153449883-b78ff550-ab94-4187-a480-04b734c6c5ea.png)

**Comment by lochana-chathura** [comment]
@mohanvive @nadeeshaan WDYT of the priority of this issue for SL minor release? For me, this is an annoying behavior on a daily basis.

**Comment by nadeeshaan** [comment]
> @mohanvive @nadeeshaan WDYT of the priority of this issue for SL minor release? For me, this is an annoying behavior on a daily basis.

@lochana-chathura Intellij IDEA handles such scenarios using the shared indexes as well as doing a code analysis based on the user behaviour as well as with other similar heuristics. In the current Language Server implementation, we do not have such capability (personalized/ behavioural analysis based) implemented. At the moment, when we get a certain symbol, we distinguish them based on the symbol kinds. If we have symbols of the same kind we do not analyze/ extensively analyze them to take decisions as you have mentioned. This kind of implementation will be a major change though.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task and this becomes a major change with the Icebox label might reopen in the future.
