### ISSUE TITLE
Invalid duplicate key error for non duplicate keys

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#35046]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
type Record record {
    readonly string x;
    readonly string y;
    int z;
};

table<Record> key(x, y) _ = table [
        {
            x: "x4",
            y: "2022/02/10",
            z: 100
        },
        {
            x: "x1",
            y: "2022/02/40",
            z: 100
        }
];
```

Both the `x` and `y` fields have different values in the two mapping constructor expressions, but this results in a duplicate key error.

```cmd
$ bal run x.bal 
Compiling source
        x.bal
ERROR [x.bal:(13:9,17:10)] duplicate key found in table row key('x, y') : 'x1, 2022/02/40'
```

**Affected Versions:**
2022.0.0

**Comment by pcnfernando** [comment]
We create a compound hash for the key values. Seems in this case, the compound hash being created is equal to one another.

**Comment by pcnfernando** [comment]
Closing since #35130 is merged
