### ISSUE TITLE
Implement document sync event subscriber for extensions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#35057]
**Description:**
- In the current implementation, once document sync operations such as `didOpen` and `didChange` are emitted by the client, at the LS we perform tasks such as diagnostics publishing and code action re-registration. 
- These should not carry out for each and every sync event since the semantic model calculation can be expensive. Hence, we can introduce a server-side debouncing and notify the subscribers of the particular event and the subscribers can then perform whatever task they wish.

### Class Diagram

![Language Server Architecture3](https://user-images.githubusercontent.com/1329674/154398758-65244fa6-27d9-491b-87bb-f14f3b854e60.png)

#### EventSubscriber
- Any tool/ extension which would like to get notified of the events, should implement this Interface. These implementations should be in the classpath and will be loaded at the runtime as SPIs.
- A given subscriber can be subscribed to more than one event given by the server. The subscriber should implement the `getPublisherKinds` method and return a list of `PublisherKind`s

#### PublisherKind
- And enum, which contains all the supported publishing events. The subscribers can use this to notify the server, which are the events they are interested in.

#### EventPublisher
- The event publisher interface is implemented by a particular publisher. For example, the project update-related publisher will implement this particular interface.
- This is an internal interface and will not be accessible publically to the extension developers
- The server will decide, which events to be delegated to a particular publisher.
- The publisher can implement a debouncing mechanism if needed

**Comment by mohanvive** [comment]
Even though PR https://github.com/ballerina-platform/ballerina-lang/pull/35599 is ready, we are not planning to merge for update #1. Since changes are in the critical flow of LS, we would like to do in-depth review and perform testing cycle.

**Comment by gayalkuruppu** [comment]
As per the offline discussion held,

1. Subscriber was limited to to subscribe for only a single publisher. This is due to the inability of getting the publisher at a given subscriber. 
2. Conclusion was made to not include URI Scheme as a parameter of the Event Subscriber, but to handle that at the client or else inside the subscriber if needed using `context.fileUri()`
