### ISSUE TITLE
Missing completions in mapping constructor context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#35061]
**Description:**
![image](https://user-images.githubusercontent.com/35211477/153914293-6e91b764-9003-43f9-a485-39cf045719a2.png)

As depicted above, visible symbols are not suggested at the cursor position.

**Steps to reproduce:**
```ballerina
type MyType record {|
    string field1;
|};

function testFunction(string name) {
    MyType var1 = {field1: "Hello" + n<cursor>}
}
```

**Affected Versions:**
2201.0.1

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged.
