### ISSUE TITLE
Auto completions are not working for nested records

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#35064]
**Description:**
Consider the following example.
![Screenshot from 2022-02-15 11-28-07](https://user-images.githubusercontent.com/23274047/154002323-db392ce2-7d82-48f5-92b0-3b993e54aeaf.png)

Code  - 
```bal
    SendOrderConfirmationRequest req = {
        email: "anjanasupun05@gmail.com",
        'order: {
            order_id: "1",
            shipping_tracking_id: "2323",
            shipping_cost: {
                
            },
            shipping_address: {

            },
            items: []
        }
    };
```

```bal
public type SendOrderConfirmationRequest record {|
    string email = "";
    OrderResult 'order = {};
|};

public type OrderResult record {|
    string order_id = "";
    string shipping_tracking_id = "";
    Money shipping_cost = {};
    Address shipping_address = {};
    OrderItem[] items = [];
|};

public type Money record {|
    string currency_code = "";
    int units = 0;
    int nanos = 0;
|};



```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@pubudu91 @dulajdilshan 

When we try to get the `TypeSymbol` of the variable we get the record type symbol. Now, when we access the record fields and check the name, it shows that the name of the field does not contain the `'` as it is done in the variables. Shall we have a look? Maybe we will have to do the same fix we did for variables as well.

**Comment by pubudu91** [comment]
Had a look at this. The field symbol's name itself contains the `'`. However the issue is that `fieldDescriptors()` return a map and that doesn't support the `'order` and `order` equivalency.
