### ISSUE TITLE
Improve the error for missing the key expression in a member access expression

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35076]
**Description:**
$title

**Steps to reproduce:**
```ballerina
function init() {
    string str = "Hello";
    _ = str[]; // error: missing key expr in member access expr
}
```
In the error message, **expression** is referred to as **expr**. 
The error should be fixed as **`missing key expression in member access expression`**.

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by lochana-chathura** [comment]
There are a few other error messages in `syntax_diagnostic_message.properties` also with `expr` instead of `expression`, we need to correct them.
