### ISSUE TITLE
Compiler plugin resources addition not working as expected

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#35073]
**Description:**
We are using compile-time code generators in WebSub module to add an additional resource to the generated executable programmatically.  But even though we are using this code-generator inside WebSub compiler-plugin, the resource is included into a different resource path rather than `resources/ballerina/websub/<major-version>/<additional-resource>` inside the executable.. 

This is regarding the  ballerina-lang change [#33987](https://github.com/ballerina-platform/ballerina-lang/pull/33987)

**Comment by pramodya1994** [comment]
Closing this issue since the original use-case can be done using code modifiers.
Also, resources will be deprecated due to the suboptimal design.
