### ISSUE TITLE
Where to add annotations for services

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#3508]
There are few levels we can add annotations for a service. Global level, resource level and within a resource. There is no clear documentation on how we can achieve this, Can we elaborate on this in https://ballerinalang.org/docs/api/0.93/ballerina.net.http.html

**Comment by samgnaniah** [comment]
Assign to Shafreen.

**Comment by afkham** [comment]
The BBEs, guides and language spec should cover these in detail now.
