### ISSUE TITLE
Need an API to get the caller module name during the runtime

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#35083]
**Description:**

$Subject

**Describe your problem(s)**
The `log` module prints the name of the module from which the log function is called as part of the log message. eg: 
```
time = 2021-07-05T10:42:53.697+05:30 level = INFO module = "myorg/foo" message = "info log"
```

Currently, a Java native function is used to get the module name. This uses the stack trace taken from the current thread [[1]](https://github.com/ballerina-platform/module-ballerina-log/blob/master/log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java#L89).

It would be better if there was a Ballerina API that would return the name of the module from which the log function is called.

[1] https://github.com/ballerina-platform/module-ballerina-log/blob/master/log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java#L89

**Comment by warunalakshitha** [comment]
Providing runtime api to get the caller module can be done but then we do to pass the caller module to every function call which can add additional overhead at runtime. As per the offline discussion, we identified the requirement is to pass the caller module which is available in the compiler time to log function call.

**Comment by warunalakshitha** [comment]
We should be able do this using new compiler plugin option to change user code. Issue can be found by https://github.com/ballerina-platform/ballerina-lang/issues/35232

**Comment by warunalakshitha** [comment]
I am closing this since above requirement can be done through compiler plugin. Please reopen if you have further queries on this.
