### ISSUE TITLE
Improve Build time

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#35097]
**Description:**
Following is a set of task we can do to improve the build time performance 

- [x] Remove dupilicate bir and jar generation for test if mocking feature is not used.
- [x] Fail fast on errors without waiting for code generation
- [x] Optimize BCentral calls for the 2nd compilation
- [x] Optimize response time of the calls to BCentral
- [ ] Introduce caching for current project - https://github.com/ballerina-platform/ballerina-lang/issues/36499

**Comment by Thevakumar-Luheerathan** [comment]
With issue https://github.com/ballerina-platform/ballerina-lang/issues/40024, we introduced following optimisation techniques for a build process, 

1.  Offline resolution while executing compiler plugins. (https://github.com/ballerina-platform/ballerina-lang/pull/40191)
2. Offline resolution after executing compiler plugins if the imports are identical between initial and current packages. (https://github.com/ballerina-platform/ballerina-lang/pull/40321)

For a simple http service, we obtained following time optimisation for the 1st build.
 
**with 2201.5.0**
```
        timestamp : 1692946934549
        offline : false
        compile : false
        projectLoadDuration : 439
        packageResolutionDuration : 79801
        codeGeneratorPluginDuration : 1478
        codeModifierPluginDuration : 39
        packageCompilationDuration : 16
        codeGenDuration : 1771
        emitArtifactDuration : 473
        testingExecutionDuration : 0
        totalDuration : 84035
```

**with 2201.5.1**

```
        timestamp : 1692947060476
        offline : false
        compile : false
        projectLoadDuration : 487
        packageResolutionDuration : 67538
        codeGeneratorPluginDuration : 1438
        codeModifierPluginDuration : 41
        packageCompilationDuration : 16
        codeGenDuration : 1627
        emitArtifactDuration : 456
        testingExecutionDuration : 0
        totalDuration : 71700
```

**Comment by azinneera** [comment]
> **Description:** Following is a set of task we can do to improve the build time performance
> 
> * [x]  Remove dupilicate bir and jar generation for test if mocking feature is not used.
> * [x]  Fail fast on errors without waiting for code generation
> * [ ]  Optimize BCentral calls for the 2nd compilation
> * [ ]  Optimize response time of the calls to BCentral

We will be working on the above 2 for U9.

> * [ ]  Introduce caching for current project - [Introduce caching for current project to improve build time #36499](https://github.com/ballerina-platform/ballerina-lang/issues/36499)

**Comment by azinneera** [comment]
Closing this since we have done improvements to the compilation.
