### ISSUE TITLE
Publishing Java Packages to Central

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#35100]
**Description:**
Currently if a user wants to use java library they have to use the bind gen tool to generate the bindings. If the same java library is used by many developers they might create duplicate java bindings. With this effort we want to implement a process to get the java libraries to Ballerina Central so users can easily share java bindings for common java libraries.  

Milestone 1 : Select a set of commonly used java packages and pus it to ballerina central

**Comment by azinneera** [comment]
Closing since this is not a concern.
