### ISSUE TITLE
Line Wrap when line width is exceeded

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#35118]
**Description:**
Currently implementation of formatter doesn't seem to wrap the code line is too long.  This will make it easier to format the code to make it more readable. 

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is done.
