### ISSUE TITLE
No compilation error when a `table-constructor-expr` with keys specified is assigned to a table type constrained with `map`

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35126]
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() {
    table<map<int|string|float>> _ = table key(a, b) [{a: 1, b: "ABC", "c": 10f}]; // No error
}
```
We provide compilation errors such as `table with constraint of type map cannot have key specifier or key type constraint` for specifying keys for a table type constrained with map. Shouldn't the above example result in a similar compilation error for the `table-constructor-expr`?

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by pcnfernando** [comment]
As per the spec, key sequence comes from contextually expected type or table constructor expression. If available in both; it should be the same. When a map constrained table is used as the contextually expected type, we cannot specify a key constraint or a key sequence; hence the error. But it should be possible to specify it during construction IMO.
> The key sequence of the inherent type comes from the key-specifier of applicable contextually expected type or the key-specifier in the table-constructor-expr. If both of these are present, then they must be the same. If neither of them are present, then the key sequence is empty. The key sequence of the table value is the same as that of its inherent type. The key sequence and member type must meet the same consistency requirements as if they were specified together in a [table type descriptor](https://ballerina.io/spec/lang/2021R1/#tables). For every field-name in the key sequence of the inherent type every mapping-constructor-expr in the row-list must include a specific-field that has a value-expr that is a const-expr. It is a compile-time error if two or more rows of the table have the same key value.

The provided sample and the code below should behave similarly IMO.
```ballerina
type Foo record {|
    readonly int id;
    string name;
|};

table<Foo> _ = table key(id) [{id: 1, name: "ABC"}, {id: 1, name: "ABC"}]; //error duplicate key
```

Thoughts @gimantha @mohanvive ?

**Comment by lasinicl** [comment]
I find what we support atm to be a bit consistent too.
```ballerina
type Foo record {|
    readonly int id;
    string name;
|};

table<Foo> a = table key(id) [{id: 1, name: "ABC"}, {id: 2, name: "ABC"}]; 

public function main() {  
    //a.add({id: 2, name: "ABC"}); // panics
    _ = a[1]; // member access is not supported for keyless table 'a'
    _ = a.keys(); // incompatible types: expected 'table<map<(any|error)>> key<ballerina/lang.table:0.0.0:KeyType>', found 'table<Foo>'
}
```

**Comment by MaryamZi** [comment]
I also think the following is OK.

```ballerina
public function main() {
    table<map<int|string|float>> _ = table key(a, b) [{a: 1, b: "ABC", "c": 10f}];
}
```

I believe this is another scenario where some of the inherent type information comes from the constructor itself. 

The inherent type shouldn't be `table<map<int|string|float>>` though, which seems to be the case now.

```ballerina
import ballerina/io;

public function main() {
    table<map<int|string|float>> t = table key(a, b) [{a: 1, b: "ABC", "c": 10f}];
    io:println(t is table<record {| readonly int|string|float a; readonly int|string|float b; int|string|float c; |}> key(a, b)); // false atm, but should be true?

    // incompatible types: 'table<map<(int|string|float)>>' cannot be cast to 
    // 'table<record {| readonly (int|string|float) a; readonly (int|string|float) b; (int|string|float) c; |}> key(a, b)'
    var _ = <table<record {| readonly int|string|float a; readonly int|string|float b; int|string|float c; |}> key(a, b)> t; 
}
```



> I find what we support atm to be a bit inconsistent too.
> 
> ```ballerina
> type Foo record {|
>     readonly int id;
>     string name;
> |};
> 
> table<Foo> a = table key(id) [{id: 1, name: "ABC"}, {id: 2, name: "ABC"}]; 
> 
> public function main() {  
>     //a.add({id: 2, name: "ABC"}); // panics
>     _ = a[1]; // member access is not supported for keyless table 'a'
>     _ = a.keys(); // incompatible types: expected 'table<map<(any|error)>> key<ballerina/lang.table:0.0.0:KeyType>', found 'table<Foo>'
> }
> ```

This is the expected behaviour, since `a`'s static type is still a keyless table.

```ballerina
table<Foo> key(id) a = table key(id) [{id: 1, name: "ABC"}, {id: 2, name: "ABC"}]; 
table<Foo> b = a; 

public function main() {  
    _ = a[1]; // OK
    _ = a.keys(); // OK

    _ = b[1]; // error
    _ = b.keys(); // error
}
```
