### ISSUE TITLE
Create variable and type guard/check error code actions are not working for grpc:Error

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#35129]
**Description:**
$Subject. Can only see the create variable code action. 
![Screenshot from 2022-02-19 17-44-10](https://user-images.githubusercontent.com/23274047/154800332-0b308efa-4243-42cb-86fb-80e27dac7f3c.png)

Simpler sample - 
Code actions for int|error function. Contains three create variable code actions with typeguard and check.
![int-or-error](https://user-images.githubusercontent.com/23274047/155508603-601b6a27-6d31-49c5-b74b-22c289f911bd.gif)

Code actions for Record|grpc:Error function. Only create variable code action is visible.
![grpc-error](https://user-images.githubusercontent.com/23274047/155508676-97c4304f-c199-45f8-8698-a2de5abdc144.gif)

However, after the variable is created typeguard code action is available. 
![Screenshot from 2022-02-19 17-46-16](https://user-images.githubusercontent.com/23274047/154800374-fd00f9a4-05f0-4a1a-ab92-b4c695f756b4.png)

**Steps to reproduce:**
Should be reproducible in `greeter_client.bal` on https://ballerina.io/learn/writing-a-grpc-service-with-ballerina/

**Affected Versions:**
GA
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
For me, the use-case is working as expected. Will you be able to elaborate more on what's the issue is? Maybe a gif would be nice to identify the issue

**Comment by xlight05** [comment]
It is reproducible in the learn page scenario. I've attached the zip below.
[greeter_client.zip](https://github.com/ballerina-platform/ballerina-lang/files/8131631/greeter_client.zip)

You can go to greeter_client.bal, line number 5. and see the available code actions for the diagnostic. Create variable and type guard/check error code action is missing.
