### ISSUE TITLE
`Fill required fields` attempts to fill values for fields with default values 

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35124]
Consider the following:
```ballerina
public function main() {
    Foo f = {<cursor>};
}

type Foo record {|
   string s = "foo";
|};
```
When you use the fill required fields action at the given cursor position, it'll fill the fields with default values as well. This may not be intended in all cases. For example, 
```ballerina
http:Ok ok = {<cursor>};
```
Using the fill required fields in above case results in the following:
```ballerina
http:Ok ok = {status: new()};
```
In this particular case, the intention of the library is not at all for the user to fill the `status` field.

**Comment by nadeeshaan** [comment]
Closing since the fix has been merged
