### ISSUE TITLE
Readonly records doesn't seems to work with included record parameters

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35148]
**Description:**
```ballerina
type T readonly & record {|
    int i;
    string j;
|};

function foo(*T t) { // error: expected a record type as an included parameter(BCE2113)

}
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
The spec says for [included record parameters](https://ballerina.io/spec/lang/master/#included-record-param)

> The type-reference in an included-record-param must refer to a type defined by a record-type-descriptor.

Created a spec issue for this - https://github.com/ballerina-platform/ballerina-spec/issues/1224.
