### ISSUE TITLE
Flush the symbol table and module caches if the compiler crashes

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35158]
If the compiler crashes, what we currently do is add a bad sad diagnostic to it. Additionally we need to get rid of the half compiled symbols etc. from the various caches across the compiler and the Project API. The pkg env map in symbol table and the package cache are 2 such places we need to flush the corrupted modules from. Additionally, we'll need to flush out any dependent modules as well, if there are any.

**Comment by lochana-chathura** [comment]
This is on hold until we figure out how exactly this is done.
