### ISSUE TITLE
Inconsistent behavior for mapping constructor expression. The type is not getting inferred for mapping-constructor 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#35157]
**Description:**
Scene 1:
```ballerina
public function main() {
    {o1: "ne", o2: "two"};
}

```
Here the type is getting inferred and we can perform correct quick fixes on this
![Screenshot from 2022-02-22 09-08-49](https://user-images.githubusercontent.com/25485997/155058919-dbf88ae3-f243-4199-a90f-be6bfe0c38ec.png)
![Screenshot from 2022-02-22 10-01-09](https://user-images.githubusercontent.com/25485997/155063513-d8a0f188-fb28-4739-a4a5-bb2b6b94e405.png)

Scene 2:
```ballerina
public function main() {
    map:map({o1: "one", o2: "two"}, a => a.toString());
}
```
Here the type of the `{o1: "one", o2: "two"}` is not getting inferred.
![Screenshot from 2022-02-22 09-57-13](https://user-images.githubusercontent.com/25485997/155063328-b799845c-1c65-49fc-8ad7-4d173015d079.png)

![Screenshot from 2022-02-22 09-57-21](https://user-images.githubusercontent.com/25485997/155063260-a0236b21-dca0-4111-b50c-16f8c6535469.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Spec issue - https://github.com/ballerina-platform/ballerina-spec/issues/1050.
