### ISSUE TITLE
The letters 'f' and 'd' appear two time in compilation errors

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#35152]
**Description:**

The suffix 'f' and 'd' appears two time in compilation errors for the cases which involve with floating point and decimal literals.

**Steps to reproduce:**
```ballerina
public function main() {
    1f _ = 5; // incompatible types: expected '1ff', found 'int'

    1d _ = 5; // incompatible types: expected '1dd', found 'int'
}
```

**Affected Versions:**
2201.0.0

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35285
