### ISSUE TITLE
Allow spread operator in list constructors

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#35178]
Please refer to : https://github.com/ballerina-platform/ballerina-spec/issues/52

**Comment by lochana-chathura** [comment]
- [x] Open github discussion. https://github.com/ballerina-platform/ballerina-lang/discussions/35351
- [ ] Implement parser and error handler changes.
- [ ] Implement type checker changes.
- [ ] Implement desugar changes.
