### ISSUE TITLE
`array.reduce(..)` is not developer friendly

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#35187]
**Description:**
Currently when we are going to invoke `reduce` langlib function on an array we have to do as follows:
```ballerina
int[] values = [80, 85, 90];

int total = values.reduce(function (int a, int b) returns int => a + b, 0);
```

But ideally this should work as follows:
```ballerina
int[] values = [80, 85, 90];

int total = values.reduce((a, b) => a + b, 0);
```

Currently Kotlin [1]  has this feature.

[1] - [https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/reduce.html](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/reduce.html)

**Comment by hasithaa** [comment]
Yes, this has to be improved in the Compiler type checker.

**Comment by KavinduZoysa** [comment]
@hasithaa, are we expecting to remove/reduce types for an example like this?

```ballerina
public function main() {
    int[] values = [80, 85, 90];
    string _ = values.reduce(function (string a, int b) returns string => a + b.toString(), "0");
}
```

**Comment by KavinduZoysa** [comment]
This is OKAY, we have to infer type of `a` from lhs type of statement.

**Comment by hasithaa** [comment]
Ideally, we should be able to infer the type of the lambda function by looking at LHS side. So we should support this, 
```
public function main() {
    int[] values = [80, 85, 90];
    string _ = values.reduce((a,b) => a + b.toString(), "0");
}
```

**Comment by KavinduZoysa** [comment]
We have investigated how to solve this issue. In order to support this, we have to backtrack type matching. But our current typeparam implementation does not support this. So this becomes a design change.

Since there are planned design changes in the future, we will differ this issue.
