### ISSUE TITLE
Operator not defined error when one operand is optional and other one is non optional in relational expressions

### ISSUE THREAD

**Issue by rpjayasekara** [ballerina-platform/ballerina-lang#35195]
**Description:**
Gets operator not defined error when one operand is optional and other one is non optional in relational expressions.

```
function init() {
    decimal? a = -32.45;
    decimal b = -32;
    io:println(a >= b); // operator '>=' not defined for 'decimal?' and 'decimal'
    io:println(b >= a); // operator '>=' not defined for 'decimal?' and 'decimal'
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SandaruJayawardana** [comment]
Related issue
```ballerina
type x false|();
type y true|();

x a1 = ();
y b1 = true;

boolean x2 = a1 < b1; // operator '<' not defined for 'x' and 'y'
````
