### ISSUE TITLE
NPE at runtime with `rollback-stmt` used in an if block when the if statement is conditioned using a `transactional-expr`

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35209]
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() returns error? {
    transaction {
        if transactional {
            rollback;
        }

        check commit;
    }
}
```
Error log:

```

error: java.lang.NullPointerException
        at ballerinai.transaction.0:getAndClearFailure(internal.bal:165)
           main:main(main.bal:54)
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by pcnfernando** [comment]
Even after the rollback is executed, the commit statement is invoked. 
From the spec
`
Note that like the commit action, the rollback statement does not alter the flow of control
`
At the time the commit is executed, it's not in transactional scope.

We'll anyway have to handle the NPE and provide a proper error message.
