### ISSUE TITLE
Bal new command from a template doesnt copy icon file from template module

### ISSUE THREAD

**Issue by Drifftr** [ballerina-platform/ballerina-lang#35208]
**Description:**
When we execute bal new command with a template (ex :- `bal new sampleapp -t choreo/circuit_breaker`) generated ballerina.toml has the fields from the template module's ballerina.toml.  But when the template module's ballerina.toml defines icon path it should copy the icon in the path too. Otherwise the generated module will fail to build.

**Steps to reproduce:**
1. bal new sampleapp -t choreo/circuit_breaker
2. Check ballerina.toml
```
[package]
org = "choreo"
name = "sampleapp"
version = "1.0.3"
export = ["sampleapp"]
distribution = "slbeta6"
keywords = ["Type/RestApi","Category/Service","Internal/http"]
icon = "docs/icon.png"
```
It has icon field. But there is no file in the specified file path. Ideally bal new command should copy icon file from the original module if icon field is present.

**Affected Versions:**
Ballerina Swan Lake Beta 6.2

**Related Issues (optional):**
https://github.com/wso2-enterprise/choreo/issues/11505

**Comment by pramodya1994** [comment]
This is fixed in version `2201.0.0` via https://github.com/ballerina-platform/ballerina-lang/pull/35113
Discussed a temporary solution to fix the build error in choreo scripts.
