### ISSUE TITLE
Invalid code action for unused `error` variable

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#35215]
**Description:**

https://user-images.githubusercontent.com/34838308/155460434-eaf3bab0-53ac-4184-aea2-e14a86059ba5.mov

**Affected Versions:**
Plugin version: 3.0.0
SL 2201.0.0

**Comment by lasinicl** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/34279

**Comment by SandaruJayawardana** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/34279
