### ISSUE TITLE
Fail fast on errors without waiting for code generation

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#35219]
**Description:**

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**
- https://github.com/ballerina-platform/ballerina-lang/issues/35097

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Closing since fixed with #35298

**Comment by Ibaqu** [comment]
Issue created to track a possible improvement in the way the jballerinabackend fails.
