### ISSUE TITLE
Record field completed with invalid value in mapping constructor

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35225]
Refer to the following:

https://user-images.githubusercontent.com/6260009/155486453-592aab97-13c5-41c1-ad5e-95c160c6c5ff.mov

As it can be seen, when completing the `thread` field, it also adds `parent` to this. This should be `"parent"`.
```ballerina
import ballerina/io;

public function main() {
    io:println("Starting main");

    @strand{<cursor>}
    worker W1 {
        io:println("Hello world from worker #1");
    }
}
```

**Comment by DamithaSenevirathne** [comment]
Blocked by #35407
