### ISSUE TITLE
Improve parser to detect partially written annotations in expressions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#35223]
**Description:**
Consider the following scenarios:
1.
```ballerina
function demo() {
    future<int> f = @stra<cursor>
}
```
2.
```ballerina
function demo() {
    future<int> f = @strand {<cursor>}
}
```
In both cases, the `<cursor>` is within the leading minutiae of the initializer. And the node at cursor is identified as a `simple name reference` node.

**Describe your problem(s)**
See description

**Describe your solution(s)**
Need to improve the parser logic to detect those nodes as annotations. Especially `case 2`.

**Related Issues (optional):**
#33757

**Comment by lochana-chathura** [comment]
Currently, we are keeping the annotation intact (without invalidating) at the top level and the statement level. However, we do not do it at the expression level. We need to do it there as well.
