### ISSUE TITLE
Completions rely on erroneous type checking  behaviour for mapping constructors

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#35237]
**Description:**
```ballerina
type Application record {|
    string id;
    string name;
    int 'version;
|};

Application ap = {}; //atm, expession type is resolved to `Application` which is wrong. Should be `other`
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
blocked by https://github.com/ballerina-platform/ballerina-lang/issues/36356
