### ISSUE TITLE
Add a compiler plugin task to modify user code at compile-time

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#35232]
We identified there are three main tasks in our [compiler plugin](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/CompilerPlugin.java) design:
- [Code analyzer](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/CodeAnalyzer.java)
- [Code generator](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/plugins/CodeGenerator.java) 
- Code modifier

We've already completed the first two tasks, and they are available in Swan Lake GA. We recently came across a use case that requires modifying user code during compile time. See: https://github.com/ballerina-platform/ballerina-standard-library/issues/2715

I propose to implement only built-in code modifier support for the moment. I.e., only code modifiers authorized by Ballerina authors can be added to the compiler, and no external code modifiers are allowed initially.

**Comment by ThisaruGuruge** [comment]
Hi @azinneera @pramodya1994, when can we have a release with this feature? Or is there a way we can use this feature without a release?

https://github.com/ballerina-platform/ballerina-standard-library/issues/2047 is waiting on this.

**Comment by azinneera** [comment]
@ThisaruGuruge The implementation is done. Will add it to both patch branch and master in this sprint after a code review.

**Comment by ThisaruGuruge** [comment]
> @ThisaruGuruge The implementation is done. Will add it to both patch branch and master in this sprint after a code review.

Thank you for the information!

**Comment by azinneera** [comment]
@ThisaruGuruge According to the compiler plugin design, older distributions cannot build packages that have code modifier compiler plugins. Therefore, this feature will be shipped with update 1 only. The feature will be merged to the master branch within this sprint so that you can work on the GraphQL changes. Let us know if you have any conerns.

**Comment by ThisaruGuruge** [comment]
> @ThisaruGuruge According to the compiler plugin design, older distributions cannot build packages that have code modifier compiler plugins. Therefore, this feature will be shipped with update 1 only. The feature will be merged to the master branch within this sprint so that you can work on the GraphQL changes. Let us know if you have any conerns.

That will be okay if we can test this without a release. I hope this won't be an issue if we can get at least a timestamped version of the ballerina lang. (Given that the changes are backward compatible, hope we only need to update the lang version in the GraphQL package to test this).
