### ISSUE TITLE
Invalid compilation error when printing a query expression

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35241]
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() {
    io:println(from int a in [1, 2, 3] select a); // ambiguous type '[int, int]' 
}
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/35031
