### ISSUE TITLE
Missing suggestion items before annotation attachment

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#35278]
**Description:**

Consider the below sample where the cursor is placed before an annotation attachment. For that place, only type and import suggestions are given.
```bal
<cursor>
@deprecated
function foo(int i, string s) {

}
```

**Comment by nadeeshaan** [comment]
![Mar-01-2022 15-53-32](https://user-images.githubusercontent.com/1329674/156151681-acf26be5-ccde-4140-8e5e-bee2c7868ef7.gif)
@rdulmina Please refer to the above capture, where the completions are suggested as expected. This is in the latest patch branch

**Comment by rdulmina** [comment]
> ![Mar-01-2022 15-53-32](https://user-images.githubusercontent.com/1329674/156151681-acf26be5-ccde-4140-8e5e-bee2c7868ef7.gif) @rdulmina Please refer to the above capture, where the completions are suggested as expected. This is in the latest patch branch

Ack. Closing the issue since it is fixed in the patch branch
