### ISSUE TITLE
Propagate type reference type to runtime

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#35270]
**Description:**
Note; `IntOneRef` and `MyTuple` type reference information are lost in below scenarios.
```ballerina
type IntOne 1;
type IntOneRef IntOne;

public function main() returns error? {
    IntOneRef _ = <IntOneRef>2; // error: {ballerina}TypeCastError {"message":"incompatible types: 'int' cannot be cast to 'IntOne'"}
}

```

```ballerina
public type MyTuple [int, string];

function foo() returns MyTuple => [1, ""];

public function main() {
    any a = foo;
    var b = <function () returns int> a; // currently isolated function () returns ([int,string])' cannot be cast to 'function () returns (int)'
}

```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
I think we need to pay some attention to this since this is not supported in runtime, there's still quite a bit of hacks left over in the compiler related to type defs and type refs.
