### ISSUE TITLE
Remove standard lib imports from LS unit tests

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#35276]
**Description:**
There are unit test cases in language-server-core that has import statements of standard libs. These can result in  inconsistencies and intermittent test failures. Therefore, such usage should be refactored.

**Comment by dulajdilshan** [comment]
This Affects the Semantic API as well. https://scans.gradle.com/s/mrieiaek53ij2/tests/:ballerina-compiler-api-test:test/io.ballerina.semantic.api.test.TypedescriptorTest/testSymbolModuleInfo?top-execution=1 is failing due to this
