### ISSUE TITLE
Remove standard lib imports and its usages from Semantic API test cases

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#35294]
**Description:**
Relying on whether we have cached the std-libs or not will be prone to intermittent test failures. Therefore, we need to remove them from the Semantic API test cases

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Fixed by #35295
