### ISSUE TITLE
Improve function call expression type finder to identify the type correctly

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#35309]
**Description:**
Behaviour in `2201.0.0`:
<img width="605" alt="Screenshot 2022-03-02 at 16 19 58" src="https://user-images.githubusercontent.com/27485094/156402573-e823aafe-544b-4a19-b227-270e69dd6183.png">

Behaviour in `2201.0.1`:
<img width="605" alt="Screenshot 2022-03-02 at 16 26 54" src="https://user-images.githubusercontent.com/27485094/156402599-fb763af2-6fb6-4e1e-8685-aa4a5f344270.png">

**Describe your problem(s)**
The code action doesn't appear anymore with the check `isInvalidReturnType()` returning true since its `returnTypeSymbol` is a `compilationErrorTypeSymbol`. https://github.com/ballerina-platform/ballerina-lang/blob/c7be81002cc60056112b80f77272cdadf53eac17/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateFunctionCodeAction.java#L72-L73.

Source : 
```
type Employee record {|
   readonly string name;
|};
 
public function main() {
   table<Employee> key(name) t = table [
           {name: "abc"},
           {...getRow()}
       ];   
}
```
**Describe your solution(s)**

Improve the function call expression type finder to identify the type correctly in the above scenario, so that the below function can be created with the code action.

<img width="688" alt="Screenshot 2022-03-02 at 21 56 52" src="https://user-images.githubusercontent.com/27485094/156404412-c797c2fe-6390-4b2e-9c4d-702600ebd053.png">

**Comment by nadeeshaan** [comment]
I had an initial look at the issue and it seems that our `typeOf` API in the semantic model returns `CompilationErrorType` for the `getRow` expression.
