### ISSUE TITLE
Create function code action is not suggested in conditional expr context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#35325]
**Description:**
![pic](https://user-images.githubusercontent.com/35211477/156623410-8bda2184-2ce9-45ab-9691-2fe82beda25f.png)

As depicted above, the create function code action is not suggested as a quick fix. 

**Steps to reproduce:**

```ballerina
function testConditional(int arg) {
      string word = arg > 0 ? getString(arg)  : "" ;
}
```

**Affected Versions:**
2201.0.1

**Comment by nadeeshaan** [comment]
When we try to get invoke the `typeOf` API for the `getString(arg)` node, we get the `CompilationErrorType` as the result and because of that, we do not show the code action. 
@dulajdilshan @sanjana @pubudu91 is this possible to handle?

**Comment by IMS94** [comment]
Another scenario of the same syntax node is covered by #36321
