### ISSUE TITLE
It seems there are some invalid suggestions

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#35334]
Check the below example.

<img width="790" alt="Screen Shot 2022-03-04 at 4 28 31 PM" src="https://user-images.githubusercontent.com/6178058/156751450-acedc9b1-c5a4-4d86-8a61-6a9aa6961a2a.png">

**Comment by nadeeshaan** [comment]
@shafreenAnfar what's the http version being used here? I'm using a released version where I'm not getting these entries.

**Comment by shafreenAnfar** [comment]
I have been using `Ballerina 2201.0.0`

**Comment by IMS94** [comment]
Blocked by #35629

**Comment by IMS94** [comment]
Closing this since the BIR side change has been merged and nothing needs to be done at LS side.
