### ISSUE TITLE
Code action to generate record types

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#35333]
Usually when working with services we start with defining the service interface. Consider the below program.

<img width="489" alt="Screen Shot 2022-03-04 at 4 17 46 PM" src="https://user-images.githubusercontent.com/6178058/156750196-c206f439-f01e-4d1a-84f4-55bc1b2dc177.png">

Here once I type `Payment`, I believe there should be a code action to generate the following.

<img width="502" alt="Screen Shot 2022-03-04 at 4 23 51 PM" src="https://user-images.githubusercontent.com/6178058/156750590-155892e7-4737-4dd6-8ab1-491d79dab1f0.png">

Anyway, I think this is a generic feature not specific to services.

**Comment by nadeeshaan** [comment]
This is a similar use-case that we can facilitate with this particular code action
#32093
