### ISSUE TITLE
Provide language support for in-memory source streams

### ISSUE THREAD

**Issue by HirumalPriyashan** [ballerina-platform/ballerina-lang#35367]
**Description:**
Currently, in order to provide language support we are required to have in-disk `bal` file. If we can provide support for in-memory source streams it will be beneficial when there's no `bal` file is available in disk.

As an example, in VSCode notebook API, it uses a separate scheme called `vscode-notebook-cell` for schemes in Uri and it also requires an extension other than `.bal` to identify the given file is a notebook. In such a case, we can't provide language support through the language server since there is no `bal` file in disk.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
