### ISSUE TITLE
[Documentation] No details on package declarations and how packages can be run at different levels

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3538]
No details on package declarations and how packages can be run at different levels 

- From where to run the service when a package is given etc.
- How to import a package and give is an alias

**Comment by anupama-pathirage** [comment]
This is same issue https://github.com/ballerinalang/ballerina/issues/3214

**Comment by samgnaniah** [comment]
Assign to Anupama.

**Comment by afkham** [comment]
We now have documentation that covers these aspects
