### ISSUE TITLE
[Query Action]Nil return within do clause does not brake the loop

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#35383]
**Description:**
Query action does not differentiate the nil return within the do clause and the nil completion for each iteration.

```ballerina
function testNilReturnWithinQueryAction() returns string? {
    int count = 0;
    error? res = from int i in 1 ... 3
        do {
            count = count + 1;
            if 5 + 5 == 10 { //to avoid unreachable error
                return;
            }
        };
    io:println(count == 3); //prints true
    //return statement should have broken the loop
    panic error("Return statement should brake the loop and return");
}
```

**Steps to reproduce:**

**Affected Versions:**
SL GA

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
Enable tests in this [PR](https://github.com/ballerina-platform/ballerina-lang/pull/35344), once this issue is fixed
