### ISSUE TITLE
xml subtypes other than `xml:Text` returns false for anydata check

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#35395]
**Description:**
$subject

**Steps to reproduce:**

```ballerina
import ballerina/io;
public function main() {
    xml:Comment com = xml `<!--I am a comment-->`;
    xml:Comment[] arr = [com, com];
    anydata a = arr; // compiler error : incompatible types: expected 'anydata', found 'xml:Comment[]'
    io:println(arr is anydata); // true
}
```
Note that, the `isAnydata()` check returns contradicting results at compile-time and runtime. 
This happens for other `xml` subtypes as well. 

**Affected Versions:**
SwanLake GA

**Comment by KavinduZoysa** [comment]
@MaryamZi, this gives true without any compile errors in current master

**Comment by MaryamZi** [comment]
Let's add some tests and close this issue.
