### ISSUE TITLE
[1.2.X] XML serialization bug 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35404]
**Description:**
This seems to be fixed in swanlake track, but present in the 1.2.X track.

```ballerina
import ballerina/io;
import ballerina/lang.'xml;

public function main() returns error? {
    string x = "<A xmlns=\"abc\"><B xmlns=\"\"/><B xmlns=\"\"/><B xmlns=\"\"/></A>";
    xml y = check 'xml:fromString(x);
    io:println(y);
}
```

Expected result: `<A xmlns="abc"><B xmlns=""/><B xmlns=""/><B xmlns=""/></A>`
1.2.25 result.     : `<A xmlns="abc"><B xmlns=""/><B/><B/></A>`

**Steps to reproduce:**

**Affected Versions:**
1.2.x
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SandaruJayawardana** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35447

**Comment by SandaruJayawardana** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35447
