### ISSUE TITLE
Getting incorrect value when using an external source related to `thread : "parent"` 

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#35407]
**Description:**

**Steps to reproduce:**

Consider following code example that we used to get completions for  `thread` field as mentioned in the issue #35225 

```ballerina
public function main() {

    @strand{thread: parent}
    worker W1 {

    }
}
```

Note that here expected value is `"parent"` instead of `parent`

But if we consider following code example

```ballerina
public type Thread1 "parent" | "any";

public type StrandDataHello record {|
    string name?;
    string policy?;
    Thread1 thread = "parent";
|}; 

public const annotation StrandDataHello strand on source worker;

public function main() {

    @strand{thread: "parent"}
    worker W2 {
    }  
}

```

In this case we get the expected `"parent"`.

The reason for the issue is we are getting incorrect value when we are using an external source.

**Comment by MaryamZi** [comment]
What is `parent` in the first example?

**Comment by DamithaSenevirathne** [comment]
@MaryamZi it the value we get when completing the `thread` field as mentioned in the issue https://github.com/ballerina-platform/ballerina-lang/issues/35225

**Comment by dulajdilshan** [comment]
Reverted the fix with https://github.com/ballerina-platform/ballerina-lang/pull/35798 hence re-opening
