### ISSUE TITLE
Introduce a set of builder APIs for creating type symbols

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35415]
Need to create a set of builder APIs for building type symbols in the Semantic API. A preliminary design for these is available at https://docs.google.com/document/d/15I164NKdPX0xu40Nxiy6wL_eJg2rvG2YFtUNDdcKgZ8/edit?usp=sharing

**Comment by sanjana** [comment]
Fixed by #36828
Reason/Other
