### ISSUE TITLE
Change the error message 'attempt to expose non-public symbol' to a warning

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#35426]
**Description:**
Change `attempt to expose non-public symbol` diagnostic to a warning 

**Steps to reproduce:**
```
public function testDefaultModuleFunction1(DefaultModRecord1 param1) {
}

type DefaultModRecord1 record {
    int field1;
};
```

The above program gives the following error message,
`ERROR [main.bal:(56:1,58:2)] attempt to expose non-public symbol 'DefaultModRecord1'`

The compiler should give a warning instead of an error message as the code above is similar to the one below, 
```
public function testDefaultModuleFunction1(record {int field1;} param1) {
}
```

**Comment by dulajdilshan** [comment]
Related comment: https://github.com/ballerina-platform/ballerina-lang/issues/18342#issuecomment-679154924

**Comment by dulajdilshan** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/36797/commits/96b96ac584af086db54e56447dde4940b1f43f12
