### ISSUE TITLE
Improve function mock implementation after runtime changes to optimize birgen phase

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#35474]
**Description:**
As part of the effort to optimize module jar generation https://github.com/ballerina-platform/ballerina-lang/issues/35234 ,

The runtime will be referring to the Testerina test suite to get mock function information. (They will be populating the test suite with the mock function details using TestProcessor.) https://github.com/ballerina-platform/ballerina-lang/blob/1781d8f68e46afeddf831ff1dfd60adf12410802/misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/TestProcessor.java#L171 
Then the function calls will be handled at runtime instead of the birgen phase.

When above solution is in place, we can work on the following improvements.

- [x]  Port the Mock Annotation Processor(https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/MockAnnotationProcessor.java) to use Code generators and add the mock function definition to the package. With this, we can remove the mock function generation from desugar level. https://github.com/ballerina-platform/ballerina-lang/issues/29331

- [ ] With above, we can look at supporting function pointers for mocking.

https://github.com/ballerina-platform/ballerina-lang/issues/28013
https://github.com/ballerina-platform/ballerina-lang/issues/32138

- [ ]  Revist the following requirements for mocking and see whether we can support them with new changes.

https://github.com/ballerina-platform/ballerina-lang/issues/32137
https://github.com/ballerina-platform/ballerina-lang/issues/32077

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Closing since there are individual issues to track each requirement.
