### ISSUE TITLE
Go to definition doesn't work for public variables in another module

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#35479]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/websubhub;

public function main() {
    error? x = websubhub:INTERNAL_SUBSCRIPTION_ERROR;

    var y = websubhub:UNSUBSCRIPTION_ACCEPTED;
}
```

Both of these are public, final variables.

**Affected Versions:**
2201.0.1

**Comment by mindula** [comment]
Looked into this and we get the correct symbol but the `filePath` in the symbol's location is empty. This gives us an empty `sourceFile` because it prevents the LS from navigating to the source file.

**Comment by mindula** [comment]
Further looked into this and it seems like we are not getting the correct position of `varSymbol` in the `definePackageLevelVariables()` method in `BIRPackageSymbolEnter.java`. 
if we consider the `defineFunction()` method, we are taking the position first and it is set to an invokable symbol later and this could be the possible cause for this issue.

**Comment by mindula** [comment]
Seems like the `org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter#writeGlobalVars()` method is not writing the position as well. Can you have a look @MaryamZi
