### ISSUE TITLE
incompatible types error for `5 n = 3 + 2;`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#35476]
**Description:**
$subject.

Under additive-expr spec says, 
>the static type of both operand expressions is a subtype of the same basic type, in which case the static type of the result will be this basic type, **modified by the usual [singleton typing](https://ballerina.io/spec/lang/master/#singleton_typing) rules**;

Therefore, shouldn't the `5 n = 3 + 2;` be allowed? Currently, this gives `incompatible types: expected '5', found 'int'`

**Affected Versions:**
2201.0.1

**Comment by chiranSachintha** [comment]
@lochana-chathura IMO current behaviour is correct. 
Spec says that `the static type of both operand expressions is a subtype of the same basic type, in which case the static type of the result will be this basic type`.
consider the following example
```ballerina
public function main() {
    5 n = foo() + 2;
}

function foo() returns int {
    return 3;
}
```
We didn't know the value of `foo` in compile time. right?

**Comment by MaryamZi** [comment]
As @lochana-chathura mentioned, singleton typing applies for `3 + 2`, so `5 _ = 3 + 2;` should work.

Quoting the section from the spec

> The specification of a particular kind of compound expression may say that the static type of the result of an expression E is a type T modified by the usual singleton typing rules. This means that when all subexpressions of the compound expression have a singleton type, then the static type of E is a singleton subtype of T. This subtype is computed by evaluating the expression at compile-time with operands whose values belong to the corresponding singleton types.

Singleton typing doesn't apply to `foo() + 2` when `foo`'s return type is `int`, since the static type is not a singleton.

@lochana-chathura, this is part of https://github.com/ballerina-platform/ballerina-lang/issues/33090 and more a new feature rather than a bug.

Shall we use https://github.com/ballerina-platform/ballerina-lang/issues/33090 to track this also?

**Comment by lochana-chathura** [comment]
> this is part of #33090 and more a new feature rather than a bug.

 Ack.

> Shall we use #33090 to track this also?

Do you mean close this issue and track this on the other issue?

**Comment by MaryamZi** [comment]
> > Shall we use #33090 to track this also?
> 
> Do you mean close this issue and track this on the other issue?

Yeah, when implementing that, we will have to verify each expression kind for which singleton typing applies. So this should get covered.

**Comment by lochana-chathura** [comment]
Closing as we track this on #33090
