### ISSUE TITLE
NPE in constant declaration node context

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#35488]
**Description:**

<img width="577" alt="Screenshot 2022-03-14 at 22 16 37" src="https://user-images.githubusercontent.com/27485094/158220435-fc546d98-28c3-4f0a-9e4c-3ea41c68e376.png">

Deriving completions at cursor position fails with the following exception.
```
[Error - 10:13:36 AM] Operation 'text/completion' failed! {uri: '/Users/tharushijayasekara/Documents/Test/test4.bal', [2:35], error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
```
**Steps to reproduce:**
```
const string name = "John";
const string greeting = "Hello" + name;
```
**Affected Versions:**
2201.0.2 (Swan Lake)

**Comment by nadeeshaan** [comment]
The reason for this behavior is that the semantic API returns a `null` singleton type as the `typeDescriptor` of the `geeting`'s type. 
@pubudu91 @dulajdilshan thoughts on handling this?

**Comment by pubudu91** [comment]
Hmm since at this point `greeting` is still not defined, don't think there'd be any type info to look at 🤔

**Comment by dulajdilshan** [comment]
> The reason for this behavior is that the semantic API returns a `null` singleton type as the `typeDescriptor` of the `geeting`'s type. @pubudu91 @dulajdilshan thoughts on handling this?

Do we need to consider  `greeting` as a completion here? (`greeting` is not defined at the cursor point)

**Comment by nadeeshaan** [comment]
@dulajdilshan no, we should ignore it. IIRC for this limitation, we already had an issue as well.
