### ISSUE TITLE
No suggestion for `null` keyword in statement level or module level

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#35482]
**Description:**

$title

![Screenshot from 2022-03-16 12-11-31](https://user-images.githubusercontent.com/26381349/158531824-b77a1cc2-6c6a-4d67-865a-96c4d6c1cabf.png)

**Comment by nadeeshaan** [comment]
@rdulmina what's the exact use-case for that? We do not suggest the null keyword at these contexts since simply having null is not a valid expression. We suggest new since we can start writing something like `new http:getHeaders()` and then use the code actions to generate variables.

**Comment by rdulmina** [comment]
> @rdulmina what's the exact use-case for that? We do not suggest the null keyword at these contexts since simply having null is not a valid expression. We suggest new since we can start writing something like `new http:getHeaders()` and then use the code actions to generate variables.

I was trying to write var declaration statement with nil type ie `null a = null;`

**Comment by nadeeshaan** [comment]
> > @rdulmina what's the exact use-case for that? We do not suggest the null keyword at these contexts since simply having null is not a valid expression. We suggest new since we can start writing something like `new http:getHeaders()` and then use the code actions to generate variables.
> 
> I was trying to write var declaration statement with nil type ie `null a = null;`

That makes sense. We will look in to this @rdulmina
