### ISSUE TITLE
[Documentation] Need more guidance on different ways of writing Ballerina programs

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerina-platform/ballerina-lang#3549]
If I go to Ballerina docs page [1], it has 3 sections: Examples, API reference and Language spec. 
However, this page gives no indication on the developer tools available for Ballerina.  Someone new, coming to this page might not know that a composer and IDE plugins are available for Ballerina. 

I suggest that we add a new section on tools available. This new section should provide info such as:

Different ways of writing Ballerina programs:
- Text editor way
- IDE plugins
-- Intellij Idea
-- Atom
-- etc
- Composer

Each of these should be further broken down into subsections as below. For example, if we take Composer section, it should provide following subsections:
- Downloading and installing composer
- Starting composer
- Writing your first Ballerina program using the composer
- More examples 

[1] https://ballerinalang.org/docs/

**Comment by anupama-pathirage** [comment]
Ballerina quick tour [1] and  IntelliJ IDEA plugin [2] has details on this.

[1] https://ballerinalang.org/docs/quick-tour/quick-tour/
[2] https://github.com/ballerinalang/plugin-intellij

**Comment by afkham** [comment]
We now have separate BBEs, guides etc and the language spec.
