### ISSUE TITLE
Fix failing debugger tests for function pointer support with defaultable parameters 

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#35494]
**Description:**
With https://github.com/ballerina-platform/ballerina-lang/pull/31589[](https://github.com/ballerina-platform/ballerina-lang/pull/31589), the following debugger integration test cases are failing due to the runtime side changes. 

https://scans.gradle.com/s/74l6xanamoipw/tests/overview?outcome=failed

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/chiranSachintha/ballerina-lang/pull/6

**Comment by anupama-pathirage** [comment]
@NipunaRanasinghe Why  are we  closing this with a PR to a fork?

**Comment by NipunaRanasinghe** [comment]
@anupama-pathirage Its because @chiranSachintha couldn't get his runtime changes merged as there were some debugger failures. Therefore we thought of getting the required debugger changes merged to the fork branch.

**Comment by anupama-pathirage** [comment]
In that case, is it correct to close the issue until the changes are merged to  ballerina-lang repo?

**Comment by NipunaRanasinghe** [comment]
@anupama-pathirage As mentioned in the issue description, these debugger tests weren't failing in the lang repo branch, but only in the PR build. Therefore I thought of closing the issue once after verifying that the tests are passing in the PR build. Apologies if the issue description is not clear enough or if it wasn't the best approach that I followed :)

**Comment by anupama-pathirage** [comment]
@NipunaRanasinghe Thanks for the clarification. Seems fine.  :)
