### ISSUE TITLE
`ArrayValue` creation does not evaluate array size mismatch

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#35522]
**Description:**
$subject
The following public `ArrayValue` constructor is used in the value creator APIs which accepts parameters for array type and the array size.
```java
    public ArrayValueImpl(ArrayType type, long size, BListInitialValueEntry[] initialValues) {
    }
```
As we keep the size information in the array type as well, there can be two different sizes given from these parameters. 
Currently, this size difference is not validated when using this constructor. But it can cause erroneous behavior.

**Comment by Nadeeshan96** [comment]
As discussed in the sync-up meeting, need to do this in the constructors: Change the field `ArrayType.size` to match the passed argument `size`, and not to do a validation.
