### ISSUE TITLE
No error for isolated `let-expr` when `let-var-decl` is not isolated

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#35525]
**Description:**
`A let-expr is isolated if the expression following in is isolated; a reference in that expression to a variable bound by a let-var-decl will be treated as isolated if the expression initializing the variable in the let-var-decl is isolated.`

As per the above spec requirement, the following example should give compile error.

**Steps to reproduce:**
```
isolated int x = 2;
int y = 23;

function foo() {
    lock {
        x = let int i = y in i + 2; // should be an compile error
    }
}

public function main() {
    foo();
}
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment]
Why (where) should this result in an error?

**Comment by KavinduZoysa** [comment]
At `x = let int i = y in i + 2;`, since x is isolated `i + 2` should be isoalated. For that the expression that initialize `i` should be isolated. 
Isn't it wrong?

**Comment by MaryamZi** [comment]
The requirement for the initializer is that it be an isolated expression.

> A let-expr is isolated if the expression following in is isolated; a reference in that expression to a variable bound by a let-var-decl will be treated as isolated **if the expression initializing the variable in the let-var-decl is isolated**.

Quoting from the [spec](https://ballerina.io/spec/lang/master/#section_6.2.6)

> If the static type of an expression is immutable, i.e. a subtype of readonly, or an isolated object, i.e. a subtype of isolated object {}, then the expression is isolated.

In your example, the static type of `y` is `int`, which is a subtype of `readonly`. Therefore, it is an isolated expression.

The error is logged as expected when the type is not a subtype of `readonly`.

```ballerina
isolated int[] x = [];

function foo() {
    lock {
        int[] y = [23];
        x = let int[] i = y in i;
    }
}
```

**Comment by KavinduZoysa** [comment]
Thanks for the clarification.
