### ISSUE TITLE
`table<MapType> key<KeyType>` should be assignable to `table<MapType>`

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#35576]
**Description:**
$title

_Originally posted by @dulajdilshan in https://github.com/ballerina-platform/ballerina-lang/issues/35271#issuecomment-1078767575_

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
2201.0.0

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/35271

**Comment by pcnfernando** [comment]
Below is supported atm. 

```ballerina
import ballerina/io;
type Employee record {
    readonly int id;
    string name;
};

public function main() {
  table<Employee> key<int> a = table key(id) [{id: 0, name: ""}];
  table<Employee> b = a;
  io:println(b);
}
```

But https://github.com/ballerina-platform/ballerina-lang/issues/35271#issuecomment-1078767575 describes of a scenario where the opposite is true. Can you please check @dulajdilshan ?

**Comment by pcnfernando** [comment]
Differing until https://github.com/ballerina-platform/ballerina-lang/issues/35576#issuecomment-1143176828 requirement is sorted

**Comment by dulajdilshan** [comment]
> Below is supported atm.
> 
> ```ballerina
> import ballerina/io;
> type Employee record {
>     readonly int id;
>     string name;
> };
> 
> public function main() {
>   table<Employee> key<int> a = table key(id) [{id: 0, name: ""}];
>   table<Employee> b = a;
>   io:println(b);
> }
> ```
> 
> But [#35271 (comment)](https://github.com/ballerina-platform/ballerina-lang/issues/35271#issuecomment-1078767575) describes of a scenario where the opposite is true. Can you please check @dulajdilshan ?

This is true. The original issue is we don't get `filter()` as a lang-lib method for tables for which we haven't defined the key. Digging deep down we found that we get an assignability error with `table<MapType> key<KeyType>` and `table<MapType>`.

**Comment by pcnfernando** [comment]
That is expected. Please check the comments on the `filter` and `reduce`; both these cases require a table with keys.
[1] https://github.com/ballerina-platform/ballerina-spec/blob/e8a25f6ebdb03a3eb110f162c7a06b58777a9375/lang/lib/table.bal#L105
[2] https://github.com/ballerina-platform/ballerina-spec/blob/e8a25f6ebdb03a3eb110f162c7a06b58777a9375/lang/lib/table.bal#L125

**Comment by pcnfernando** [comment]
The issue here is we consider `table<Type>` as a keyless table. But a keyless table is actually `table<Type> key<never>`.

**Comment by pcnfernando** [comment]
Here the only change should be in the error messages; where we use the "keyless" phrase to describe tables without a key constraint. Actually a `table<Type>` is a supertype that can have both key-ed and keyless tables. Therefore it's correct to restrict `filter`, `remove`,... functions for it. @dulajdilshan please note. 

@prakanth97 let's add update the error messages and add tests that clearly differentiate this behavior.
