### ISSUE TITLE
Resolve type params in object and record types in `TypeParamResolver`

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35596]
Currently the type params within object and record types aren't resolved in https://github.com/ballerina-platform/ballerina-lang/blob/95f08123f94dafc0e1a7758917f6f6822b6c83c1/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/TypeParamResolver.java#L153. Need to implement this to address issues like the following:
<img width="928" alt="Screenshot 2022-03-28 at 14 41 37" src="https://user-images.githubusercontent.com/6260009/160366557-616adf5a-514b-4107-8850-bcc0d9a2170d.png">
Note how the type params within the object type is not resolved.

**Comment by pubudu91** [comment]
Needed for https://github.com/wso2-enterprise/choreo/issues/4380

**Comment by pubudu91** [comment]
Needed for Choreo issue no. 4380

**Comment by dulajdilshan** [comment]
Currently working on 
- implementing visitor method for *map*, *Object*, *record*  in type-param-resolver
- Improving is-type-param checker logic in type-param-resolver
It seems like we need to move this to the 56 sprint (Next Sprint)
