### ISSUE TITLE
Requesting public API for decoding unicode characters

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#35615]
**Description:**
In the OpenAPI tool, we have a requirement for supporting to generate  OpenAPI spec when the ballerina service has any Unicode with string (example 01)
**Example 01: ballerina service (tool input)**
```ballerina
service /'limit on new http:Listener(9090) {
    resource function put พิมพ์ชื่อ(string ชื่\u{E2D}) {
    }
```
**Example 02: expected OpenAPI spec(tool output)**
```openapi
openapi: 3.0.1
info:
  title: Limit
  version: 0.0.0
servers:
  - url: "{server}:{port}/limit"
    variables:
      server:
        default: http://localhost
      port:
        default: "9090"
paths:
    /พิมพ์ชื่อ:
    get:
      operationId: operation_get_/พิมพ์ชื่อ
      parameters:
        - name: ชื่อ
          in: query
          required: true
          schema:
            type: string
      responses:
        "202":
          description: Accepted
```
For getting the above expected OpenAPI spec (example 02) , we tried to implement the same behaviour function with the [unescapeBallerina](https://github.com/ballerina-platform/ballerina-lang/blob/d257e0d12e2c278d80199356d79a8cf1b67c7237/misc/identifier-util/src/main/java/io/ballerina/identifier/Utils.java#L186) which come from under the identifiers. During the implementation seems that we are going to duplicate the code in openapi tool as well and it will cause requesting several APIs as well. 
Due to that, we used java reflection API as a workaround to generate this task.

We would like to get to know whether it is possible to give a public API, like `isKeyword()` in SyntaxInfo to access decode Unicode.

**Comment by lochana-chathura** [comment]
Related Issue: #37046

**Comment by NipunaRanasinghe** [comment]
Closing since the support has been provided with https://github.com/ballerina-platform/ballerina-lang/pull/38318
