### ISSUE TITLE
Packages loaded from BIR show anon types in module's symbols

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#35629]
**Description:**
$subject causes #35334. Seems like some of the virtual symbols that are load from BIR are not set with the `origin=VIRTUAL` causing those symbols to appear in `module.allSymbols()`.

Note that this behavior is observed in distributions, but not when a package is pulled from central.

**Steps to reproduce:**
Type `http:<cursor>` in any context and have a look at the suggestions. Some anon types and intersection types are present in the list.

**Affected Versions:**
2201.0.0, 2201.0.1, 2201.0.2

**Comment by MaryamZi** [comment]
Probably related to https://github.com/ballerina-platform/ballerina-lang/issues/34808.

**Comment by rdulmina** [comment]
> Probably related to #34808.

https://github.com/ballerina-platform/ballerina-lang/issues/34808. is a different case

**Comment by rdulmina** [comment]
https://github.com/ballerina-platform/ballerina-lang/issues/35334 is due to an issue in `ImmutableTypeCloner` and fixed with #36121
