### ISSUE TITLE
Incorrect type resolving for intersection types when there's a type def for the same type

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35624]
Consider the following case:
```ballerina
type Foo record {|
    int a;
|};

type FooReadonly Foo & readonly;

function test() {
    Foo & readonly v; // invalid type symbol resolved for the intersection type here
}
```
If we take a look at the type symbol created for the intersection type above, it'll be the same type symbol created for `FooReadonly`. There shouldn't be a connection to that type def for other similar intersection types created. This leads to the wrong type symbol instance being returned to the Semantic API users for cases like this.

**Comment by sanjana** [comment]
A permanent fix for this would be to avoid the overriding code block at https://github.com/ballerina-platform/ballerina-lang/blob/3be3514f9fd1df63b877365d4e1b13d31b383fd1/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java#L1660-L1672

This would be possible once #36855 is completed. 

Therefore a temporary fix on the Semantic API is introduced at #37080.
