### ISSUE TITLE
[Documentation] Selecting multiple lines from Ballerina examples is not convenient

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerina-platform/ballerina-lang#3562]
When selecting multiple lines from the code snippets in the Ballerina examples, page content on the sides also get copied. This is somewhat inconvenient.

Please refer screenshot below:

![select-multiple-lines](https://user-images.githubusercontent.com/7592890/31399226-30f64c0a-ae09-11e7-92be-61eb654f54cd.png)

**Comment by uthaiyashankar** [comment]
This should have been fixed. Working correctly in the current pages.
