### ISSUE TITLE
Refactor CommonUtil class

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#35641]
**Description:**
The CommonUtil class in the language server currently has grown up  and has a bunch of method that are not common(used only by a single entity).
We should introduce a organized utility package for various operations of the Language Server with this effort. 
Eg: CompletionOprtationUtil, CodeActionOperationUtil, etc

**Comment by TharushiJay** [comment]
Created #36293 to track the refactoring of remaining LS utils.
