### ISSUE TITLE
`bal test` command doesn't give any error when the listener `start` fails

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#35660]
**Description:**
I have a project with a main.bal file as follows,

```ballerina
import ballerina/http;

service /yy on new http:Listener(9090) {
    resource function get greeting() returns string {
        return "Hello, World!";
    }
}

service /xx on new http:Listener(9090) {
    resource function get greeting() returns string {
        return "Hello, World2!";
    }
}
```

and tests as follows,

```ballerina
import ballerina/test;
import ballerina/http;

http:Client clientEndpoint = check new ("http://localhost:9090/");

@test:Config {}
function test1() returns error? {
    string response = check clientEndpoint->get("yy/greeting");
    test:assertEquals(response, "Hello World!");
}

@test:Config {}
function test2() returns error? {
    string response = check clientEndpoint->get("xx/greeting");
    test:assertEquals(response, "Hello, World2!");
}
```

Running this ballerina project gives an error as I am trying to start two listeners on the same port(9090). Following are the outputs of the `bal run` and `bal test` commands.

bal run 

```
Compiling source
	bhashinee/HttpTest:0.1.0

Running executable

error: failed to start server connector '0.0.0.0:9090': Address already in use
	at ballerina.http.2:externStart(http_service_endpoint.bal:117)
	   ballerina.http.2.Listener:start(http_service_endpoint.bal:51)
```

bal test

```
Compiling source
	bhashinee/HttpTest:0.1.0

Running Tests

	HttpTest

		[fail] test1:

		    Not Found {"statusCode":404,"headers":{"content-length":["49"],"content-type":["text/plain"],"date":["Mon, 4 Apr 2022 21:24:36 +0530"],"server":["ballerina"]},"body":"no matching service found for path : /yy/greeting"}

		    	at ballerina.http.2:createResponseError(http_client_endpoint.bal:774)
		    	ballerina.http.2:processResponse(http_client_endpoint.bal:646)
		    	ballerina.http.2.Client:processGet(http_client_endpoint.bal:200)

		[pass] test2

		1 passing
		1 failing
		0 skipped
```

Address already in use error is not reflected when running the tests. I think if running the `main.bal` program gives an error it should not even attempt to run tests.

**Comment by azinneera** [comment]
@warunalakshitha The response from the method invoke returns a null and therefore, the test continues execution. Any idea why this happens?
https://github.com/ballerina-platform/ballerina-lang/blob/7626430a54fde1b88d70d5e3f6ace48f582b767b/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/BTestRunner.java#L296

**Comment by warunalakshitha** [comment]
One possibility is https://github.com/ballerina-platform/ballerina-lang/blob/7626430a54fde1b88d70d5e3f6ace48f582b767b/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java#L110 can be null

**Comment by azinneera** [comment]
> One possibility is
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/7626430a54fde1b88d70d5e3f6ace48f582b767b/misc/testerina/modules/testerina-runtime/src/main/java/org/ballerinalang/test/runtime/entity/TesterinaFunction.java#L110
> 
> can be null
IMO, in case of a module start failure, an exception should be returned instead of a null. @warunalakshitha WDYT?

**Comment by Bhashinee** [comment]
@Ibaqu 
Is this fixed? I still see this when I build the WebSocket package. I am using 2201.1.0 Ballerina lang version.

**Comment by Ibaqu** [comment]
At the time we merged this PR the scenario worked but it seems the issue still persists in the 1.0 version. I will take a look

**Comment by Ibaqu** [comment]
@Bhashinee The changes are included in the 2.x version but not in 1.x. It may be that the changes weren't synced properly to the 1.x branch.
