### ISSUE TITLE
Invalid cyclic error for recursive readonly types 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35686]
**Description:**
```
type T readonly & (A|B); // invalid cyclic type reference in '[B, T, B]'(BCE2036)
type A readonly & [T];
type B readonly & [T];
```
**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdulmina** [comment]
Assigned to @prakanth97

**Comment by SasinduDilshara** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/40663
