### ISSUE TITLE
Invalid "unreachable code" error

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35694]
**Description:**
```ballerina
public type Type A|Tuple|List;
public type A "A";
public type Tuple ["tuple", Type, Type...];
public type List ["list", int?, Type];

function foo(Type t) {
    if t is List {
        return;
    }
    int i = 0; // unreachable code(BCE2106)
}
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lasinicl** [comment]
The expression in the `if` statement is always evaluated as 'true'. Hence the unreachable error. 
Need to fix type narrowing for this.

**Comment by SasinduDilshara** [comment]
I guess this issue occurs because of this. #37271
