### ISSUE TITLE
operator '&&' not defined for 'boolean' and 'true'

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35693]
**Description:**
```ballerina
function foo() {
    if 1 == 1 && bar() { // operator '&&' not defined for 'boolean' and 'true'(BCE2070)

    }
    if true && bar() { // operator '&&' not defined for 'boolean' and 'true'(BCE2070)

    }
}

function bar() returns true => true;
```

Same error for `||`.
**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gimantha** [comment]
We will defer the issue for the time being and will take it later
