### ISSUE TITLE
`else` part in `if`-`else` statement does not work properly with `http:StatusCodeResponse` records

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#35704]
**Description:**
When we have [`http:StatusCodeResponse`](https://lib.ballerina.io/ballerina/http/2.2.1/types#StatusCodeResponse) record types as a union part of a type, and use `if` - `else` to separate the types, the type narrowing is not working properly for `else` part. (See the example)

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/http;

type A http:Response|json|record {||};
type B http:Ok|http:Created|http:InternalServerError;

public function main() {
    http:Ok j = {};
    callFunction(j);
}

function callFunction(A|B val) {
    if val is B {
        mello(val);
    } else {
        hello(val);
    }
}

function hello(A a) {
    io:println("A");
}

function mello(B b) {
    io:println("B");
}
```

Getting the following compiler error :
```
incompatible types: expected 'A', found '(A|B)'
```

**Affected Versions:**
Ballerina 2201.0.2(Swan Lake)

**Update** :
If I remove the `json` from type A, this is working

**Comment by MaryamZi** [comment]
Since you have `json` in `A|B`, we don't narrow in the else block atm.

Assuming `status` is **not** a `readonly` field, something like the following value is a valid argument to `callFunction` with the current semantic sub-typing rules.

```ballerina
public type MyOkResponse record {|
    string mediaType?;
    map<string|int|boolean|string[]|int[]|boolean[]> headers?;
    anydata body?;
    json|http:StatusOK status = new;
|};
```

So we can't narrow in the else block.

```ballerina
import ballerina/http;

function callFunction(http:Response|json|record {||}|http:Ok|http:Created|http:InternalServerError val) {
    if val is http:Ok|http:Created|http:InternalServerError {
        http:Ok|http:Created|http:InternalServerError _ = val;
    } else {
        http:Response|json|record {||} _ = val;
    }
}

public type MyOkResponse record {|
    string mediaType?;
    map<string|int|boolean|string[]|int[]|boolean[]> headers?;
    anydata body?;
    json|http:StatusOK status = new;
|};

function fn(MyOkResponse resp) {
    callFunction(resp);
}
```

There are some improvements suggested with readonly fields in the spec though (1017). But according to the current rules, this is expected.

**Comment by TharmiganK** [comment]
Thank you so much for clarification 👍
