### ISSUE TITLE
Address the issues in #35535 related to function mocking callOriginal case 

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#35764]
**Description:**
Due the changes done in the PR https://github.com/ballerina-platform/ballerina-lang/pull/35535, an issue arises with the ordering of the test execution. 
eg:
```ballerina
test:when(mock_intAdd).thenReturn(100);
test:when(mock_stringAdd).callOriginal();
test:assertEquals(intAdd(10, 6), 100);
test:assertEquals(stringAdd("hello"), "hi there!");
```
Above case is not working as expected due to the changes introduced in the above PR.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Blocked on https://github.com/ballerina-platform/ballerina-lang/issues/36037

**Comment by azinneera** [comment]
> Blocked on #36037

We had a call and agreed on an approach that is different from the current one to resolve https://github.com/ballerina-platform/ballerina-lang/issues/35764. Hence this issue can be done and the above issue can be closed once the solution is tried.

**Comment by gabilang** [comment]
Closing this since the PR has been merged.
