### ISSUE TITLE
ConstantSymbol `.typeDescriptor().signature()` returns value with `"` for enum

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#35783]
**Description:**
When accessing the signature value for the below enum type, it returns value including `"`, earlier it returns without any `"` 
This new change is a breaking change for Ballerina To OpenAPI tool spec generation.

```ballerina
enum Action {
    PATCH,
    DELETE,
    PUT,
    POST,
    GET
}
```
try to access PATCH value , using `.typeDescriptor().signature()` it returns value `"PATCH"`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
OpenAPI PR for temp fix https://github.com/ballerina-platform/openapi-tools/pull/950

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
Reopen due to this issue is still has in ballerina lang `2201.2.0-20220704-165400-1b5e32c` version 
related discussion https://github.com/ballerina-platform/openapi-tools/pull/950#discussion_r884395865 
This is blocker for OpenAPI tool Ballerina to OpenAPI command for Update 2

**Comment by lnash94** [comment]
Meeting attendees :  @mohanvive , @dulajdilshan , @NipunaRanasinghe , @lnash94 

- During the meeting, all the possible scenarios in the Enum behaviour was discussed and identified that providing signature behaviour is correct. 
- From the tooling, perspective decided to proceed with the current fix because ballerina currently supports only the enum for string type. Therefore the tool won't be affected handling enum type except string.
- For further implementation, the tool needs to take the type of the SingletonType (e.x: string, int, float). Therefore having type from type-descriptor of the enum value, It was decided to provide an API for singleton type within the next releases.

**Comment by dulajdilshan** [comment]
> Meeting attendees : @mohanvive , @dulajdilshan , @NipunaRanasinghe , @lnash94
> 
> * During the meeting, all the possible scenarios in the Enum behaviour was discussed and identified that providing signature behaviour is correct.
> * From the tooling, perspective decided to proceed with the current fix because ballerina currently supports only the enum for string type. Therefore the tool won't be affected handling enum type except string.
> * For further implementation, the tool needs to take the type of the SingletonType (e.x: string, int, float). Therefore having type from type-descriptor of the enum value, It was decided to provide an API for singleton type within the next releases.

We can get the type of the constant symbol via `broaderTypeDescriptor()` can you please check?

**Comment by lnash94** [comment]
@dulajdilshan  Could you please let me know whether the full API call is `.broaderTypeDescriptor().signature()` or not, when I try to call this I receive the enum data type as `string` instead of the Value. did I miss something ?

**Comment by dulajdilshan** [comment]
According to this meeting https://github.com/ballerina-platform/ballerina-lang/issues/35783#issuecomment-1181626283, we thought to go with the current implementation and Open API needed to get the type of the `SingletonType`. To do this you can use `.broaderTypeDescriptor()` of `ConstantSymbol`  or the `originalType()` of the `SingletonType`

**Comment by dulajdilshan** [comment]
Also, to get the value, you can use `constValue()` of `ConstantSymbol`
