### ISSUE TITLE
`ascending/descending` keywords not suggested for partially written ascending/descending keywords

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#35818]
**Description:**
Consider
```ballerina
    string[][] usages = from var [_, usage] in data.entries()
        order by usage.employeeId a<cursor>
```
At cursor, it doesn't suggest `ascending` keyword.

**Steps to reproduce:**
See description

**Affected Versions:**
2201.0.3 RC2

**Comment by malinthar** [comment]
Related to #35774

**Comment by malinthar** [comment]
![image](https://user-images.githubusercontent.com/35211477/166297974-13a143fa-3040-498a-8e68-bc99bdc31e63.png)

The parser has added the missing `select` keyword as a recovery strategy. Therefore the effective context for the completions become `FunctionBodyBlockNodeContext`. Therefore the direction keywords are not suggested at the cursor position.
