### ISSUE TITLE
Additive expression allowed with operands of subtypes that contain both xml and string

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#35825]
**Description:**
The [spec](https://ballerina.io/spec/lang/master/#additive-expr) says 

> It is required that either:
>
> - the static type of both operand expressions is a subtype of the same basic type, in which case the static type of the result will be this basic type, modified by the usual [singleton typing](https://ballerina.io/spec/lang/master/#singleton_typing) rules; or
> - **the static type of one operand expression must be a subtype of xml and of the other operand expression must be a subtype of string, in which case the static type of the result is xml.**

**Steps to reproduce:**
But we seem to now allow 
```ballerina
type Strings "A"|"foo";

function errorFunction(string:Char|xml a, xml:Element|Strings b, xml<xml:Comment|xml:Text>|string c) {
    xml _ = a + a; 
    xml _ = a + b; 
    xml _ = a + c; 
    xml _ = b + b; 
    xml _ = b + c; 
    xml _ = c + c; 
}
```

May be related to https://github.com/ballerina-platform/ballerina-lang/pull/35763.

May also have to clarify in the spec if we can allow this instead of disallowing it.

**Affected Versions:**
2201.1.0-SNAPSHOT, current master

**Comment by chiranSachintha** [comment]
Discussed in the [spec](https://github.com/ballerina-platform/ballerina-spec/issues/1087). Here we need to disallow the following kinds of scenarios also.
```ballerina
function value(int|float x, int|float y) {
    int|float k = x + y;
}
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36004.
