### ISSUE TITLE
Documentation for Compiler Plugins

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#35879]
**Description:**
[Doc link](https://docs.google.com/document/d/1-WKmzHCpp8rjlBWkOzSUKQzVQ-sjhQzV9pZHDUZzahE/edit?usp=sharing)

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by azinneera** [comment]
Since we are in the process of redesigning the compiler plugin architecure, the documentation will be done as a part of the implementation of the new design. This is captured in https://github.com/ballerina-platform/ballerina-spec/issues/1191
