### ISSUE TITLE
Heavy cpu/memory consumption with readonly records

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35923]
**Description:**
```ballerina
import ballerina/io;

// Observe the output after removing readonly-ness of T
type T readonly & record {|
    T? t;
|};

public function main() {
    int i = 0;
    T[] list = [];
    T t = { t: () };
    T p = t;
    while true {
        if i % 1000 == 0 {
            io:println(i);
        }
        T c = { t: p };
        list.push(c);
        p = c;
        i += 1;
    }
}
```

This resulted in extremely slow execution (observed though the stdiout) and finally ended up throwing a stackoverlfow.
Making `T` non-readonly fixes this. Seems to be caused by creating singleton types for readonly values.

Originally observed when testing nBallerina semtypes.
Note the extremely large memory allocations in the screenshot of a memory dump. (memory dump is not from the sample)

![Screenshot 2022-04-26 at 09 36 32](https://user-images.githubusercontent.com/1496990/165279983-8a2d8436-799b-4c5e-8ef2-493a3d8e2d29.png)

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
This happens due to the recursive `toString()` call when creating the singleton typedesc for an immutable value. 
This can be fixed by caching the string value of the map to re-use the cached string value.

**Comment by rdhananjaya** [comment]
It may alleviate this a bit, but I'm not sure if caching would work here. Look at the size of generated strings.
