### ISSUE TITLE
XML filter expression escapes the escape character

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35982]
**Description:**
```ballerina
import ballerina/io;

public function main() {
    xml x = xml
        `<config-items>
          <item1>Some Item</item1>
        </config-items>`;

    io:println("Hello World!");
    xml a = x.<config\-items>; // wrong result
    io:println("---");
    io:println(a);
    io:println("---");

    xml b = x/*;
    //io:println(b);

    xml c = b.<item1>;
    io:println(c);
}
```

Generated string constant in ` $_string_constants` class.
```java
 $bString10 = new BmpStringValue("config\\-items");
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.0.3 (Swan Lake)
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by poorna2152** [comment]
Fixed in [41810](https://github.com/ballerina-platform/ballerina-lang/pull/41810)
