### ISSUE TITLE
Additive expression allowed with operands that contain a union of basic types

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#36003]
**Description:**
The [spec](https://ballerina.io/spec/lang/2021R1/#section_6.24) says,
- the static type of both operand expressions is a subtype of the same basic type, in which case this basic type will be the static type of the result, 
But we allow the following scenarios also

```ballerina
import ballerina/io;
public function main() {
    int|float a = 10;
    int|float b = 15.3;
    io:print(a + b); // prints 25
}
```
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/35825

**Comment by chiranSachintha** [comment]
Consider the following program
```ballerina
public function main() {
    int|float a = 10;
    int|float b = 15.3;
    
    float _ = a + b;
}
```
This gives an error as
```
ERROR [test3.bal:(6:15,6:20)] incompatible types: expected 'float', found 'int'
```

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/36004.
