### ISSUE TITLE
Error when compiling the code with a large hard coded large string 

### ISSUE THREAD

**Issue by slahirucd7** [ballerina-platform/ballerina-lang#36015]
**Description:**
When we hard code a large string (~1MB ) and tries to build the code it gives an error. 

**Steps to reproduce:**

1. Create a ballerina file and include a large string (~ size of 1 MB). 
2. Compile the code.
3. Gives below error
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/40932779/166641102-2b55a8d5-644a-472d-99ed-993f02825744.png">

**Affected Versions:**

```
Ballerina 2201.0.2 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9

```

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
The fix is merged with PR https://github.com/ballerina-platform/ballerina-lang/pull/36089
