### ISSUE TITLE
More improvements on working with optional fields

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#36021]
Points: 3
Spec Issue: https://github.com/ballerina-platform/ballerina-spec/issues/1079

**Comment by KavinduZoysa** [comment]
```
record Topt {
   int x?;
   int y?;
};
```

As per the spec issue, what we have to support is,

1. destructuring
     `var { x, y } = t;` The type of `x` and `y` should be `int?`
2. constructing
     ```
     int? x = 1;
     int? y = ();
     Topt t = {x, y};
     ```
     `t` has a `x` field and no `y` field
3. updating
    If `r` has a type with an optional field `int x?`, then
    ```
    r.x = ();
    ```
    This should remove the field `x` from `r`.
