### ISSUE TITLE
Allow client objects to have resource methods

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#36024]
Spec Issue : https://github.com/ballerina-platform/ballerina-spec/issues/1080

- [x] Open github discussion https://github.com/ballerina-platform/ballerina-lang/discussions/36265
- [x] Add parser changes
- [x] Add TypeChecker changes
- [x] Add Desugar changes
- [x] Add BIR changes
- [x] Add test cases

**Comment by rdulmina** [comment]
Fixed with  #36959
