### ISSUE TITLE
Update LS simulator to simulate addition of import declarations nodes

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36031]
**Description:**
$subject

and if possible update the random code snippets generated to use those imports

**Describe your problem(s)**
See description

**Describe your solution(s)**
See description

**Comment by IMS94** [comment]
@malinthar we should do #36322 as well to support removal of import statements.

**Comment by malinthar** [comment]
> @malinthar we should do #36322 as well to support removal of import statements.

Will do
