### ISSUE TITLE
Need a meaningful error message when casting to a struct fails

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3604]
Release 0.93

I have a struct as below
```
struct ResultCount {
    int Count;
}
```
Then I am going to retrieve data from a database and get an int value. Here I have used a wrong field name. Eg: The column name of the DB is "Value" and here I have used "Count". So I get an error when casting.
```
ResultCount rs;    
while (datatables:hasNext(dt1)) {
        any dataStruct = datatables:next(dt1);
        rs, err = (ResultCount) dataStruct;       
        if (err != null){
            system:println(err);
        }else{
            count = rs.Count;
        }
        
    }
```

`{msg:"'RS' cannot be cast to 'tests.Hackathon:ResultCount'", cause:null, sourceType:"RS", targetType:"tests.Hackathon:ResultCount"}`

This error is not meaningful and does not provide any help for the user to identify the root cause for the issue

**Comment by uthaiyashankar** [comment]
This issue is outdated now. There were several changes to the database, sql part. Please check in the new version and reopen.
