### ISSUE TITLE
Unable to retrieve Service annotations via semantic API

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#36041]
**Description:**
Consider the following sample. 
```ballerina
@af:QueueTrigger {
    queueName: "queue2"
}
service "queue" on new af:QueueListener("queue2") {
    remote function onMessage(string inMsg) returns @af:QueueOutput {queueName: "queue3"} [string,string] {
                return ["Hello", inMsg];
    }
}
```

Annotation declaration inside af: module
public const annotation QueueConfiguration QueueTrigger on service;

I need to check the annotation attached to the service in the build time using a compiler extension and the annotations field was empty.  

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
The original issue is that we are not getting the correct symbol with SemanticModel.symbol(Node node). We get an AnnotationSymbol instead of ServiceDeclarationSymbol

**Comment by dulajdilshan** [comment]
Needed a method to differentiate the annotations coming in the desugaring phase

**Comment by dulajdilshan** [comment]
Added BUILTIN as the source for the annotations coming through the desugaring phase. And ignore BUILTIN annotations when finding the symbol in `SymbolFinder`
