### ISSUE TITLE
Incorrect context type for start action node

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36053]
**Description:**
$Title

**Steps to reproduce:**
```
function testFunction() {
    future<int> fInt = start <cur>;
}

function getInt() returns int {
    return 0;
}
```
Here at the cursor we get the context type from the ContextTypeResolver as `future<int>`. But we should get `int` instead. Sorting of the `start action` is still given correctly even though the context type is incorrect, So if we correct the context type, we will also need to change the sorting accordingly.

**Affected Versions:**
2201.1.1

**Comment by IMS94** [comment]
`ExpectedTypeFinder`'s `transform(StartActionNode)` method should consider the cursor position when determining the expected type. If the cursor is after the `start` keyword, the expected type should be `int` if the binding pattern (LHS) returned `future<int>`

**Comment by IMS94** [comment]
The current approach works for the LS even though the expected types are interchanged. Therefore, not going to address this right now.
