### ISSUE TITLE
Relational operator doesn't work properly for tuples and arrays

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#36102]
**Description:**
$title. Consider following scenarios.

**Steps to reproduce:**
```ballerina
type x [boolean?, int]|[boolean, int, decimal?, string]; // ordered type -> [boolean?, int, decimal?, string]
type y [boolean?, int]|[boolean, int?, decimal]; // ordered type -> [boolean?, int, decimal]
// for x and y, ordered type can be taken as [boolean?, int, decimal?, string]

x a1 = [(), 1];
y b1 = [()];

boolean x2 = a1 < b1; // error: operator '<' not defined for 'x' and 'y'
```

```ballerina
type x int?[2]|int[5]; // ordered type -> [int?, int?, int, int, int]
type y int?[2]; // ordered type -> [int?, int?]
// for x and y, ordered type can be taken as [int?, int?, int, int, int]

x a1 = [(), 1];
y b1 = [()];

boolean x2 = a1 < b1; // operator '<' not defined for 'x' and 'y'
```
**Affected Versions:**
2201.1.0 (Swan Lake)

**Comment by MaryamZi** [comment]
The requirement is that there is an ordered type to which both operands belong to.

> ```ballerina
> type x [boolean?, int]|[boolean, int, decimal?, string]; // ordered type -> [boolean?, int, decimal?, string]
> type y [boolean?, int]|[boolean, int?, decimal]; // ordered type -> [boolean?, int, decimal]
> // for x and y, ordered type can be taken as [boolean?, int, decimal?, string]
> 
> x a1 = [(), 1];
> y b1 = [()];
> 
> boolean x2 = a1 < b1; // error: operator '<' not defined for 'x' and 'y'
> ```

`[boolean?, int]` doesn't belong to `[boolean?, int, decimal?, string]`. Neither do `[boolean?, int]` nor `[boolean, int?, decimal]`. There is no ordered type to which both operands (and therefore members of the union) belong to.

> ```ballerina
> type x int?[2]|int[5]; // ordered type -> [int?, int?, int, int, int]
> type y int?[2]; // ordered type -> [int?, int?]
> // for x and y, ordered type can be taken as [int?, int?, int, int, int]
> 
> x a1 = [(), 1];
> y b1 = [()];
> 
> boolean x2 = a1 < b1; // operator '<' not defined for 'x' and 'y'
> ```

Similarly there's no ordered type here either.

IMO, these errors are expected. cc @lasinicl

**Comment by MaryamZi** [comment]
Ah, but list of differing lengths can be compared, let me recheck.

**Comment by MaryamZi** [comment]
I still think the error for the first one is OK.

The spec says lists are ordered when 

> The following rules determine when a subtype of list is ordered:
> 
>  - [T...] is ordered, if T is ordered;
>  - [] is ordered;
>  - [T, rest] is ordered if T is ordered and [rest] is ordered.

For 
```ballerina
type x [boolean?, int]|[boolean, int, decimal?, string];
type y [boolean?, int]|[boolean, int?, decimal];
```

the simplest type to which all of these belong to IMO is `[boolean?, int?, decimal|string?...]` and `decimal|string?` is not ordered. 

For

```ballerina
type x int?[2]|int[5];
type y int?[2];
```

the simplest type to which all of these belong to is `[int?, int?, int...]` and `int?` and `int` are ordered, so this may be OK.

**Comment by SandaruJayawardana** [comment]
Yeah. 1st example is incorrect. Thanks for the explanation.
Instead of 1st example we can take following one for tuple case.
```ballerina
type x [boolean, int, decimal?, string]; // ordered type -> [boolean, int, decimal?, string]
type y [boolean?, int?, decimal]; // ordered type -> [boolean?, int, decimal]
// for x and y, ordered type can be taken as [boolean?, int, decimal?, string...]

x a1 = [true, 1];
y b1 = [false];

boolean x2 = a1 < b1; // error: operator '<' not defined for 'x' and 'y'
```

**Comment by SandaruJayawardana** [comment]
> ```ballerina
> type x [boolean, int, decimal?, string]; // ordered type -> [boolean, int, decimal?, string]
> type y [boolean?, int?, decimal]; // ordered type -> [boolean?, int, decimal]
> // for x and y, ordered type can be taken as [boolean?, int, decimal?, string...]
> 
> x a1 = [true, 1];
> y b1 = [false];
> 
> boolean x2 = a1 < b1; // error: operator '<' not defined for 'x' and 'y'
> ```

My bad. This is not an example for union of tuples. Probably this example is related to https://github.com/ballerina-platform/ballerina-lang/issues/35195

For the union tuple case, 

```ballerina
type x [boolean?, int]|[boolean, int, decimal?]; // ordered type -> [boolean?, int, decimal?]
type y [boolean?, int]|[boolean, int?]; // ordered type -> [boolean?, int?]
// for x and y, ordered type can be taken as [boolean?, int?, decimal?...]

x a1 = [(), 1];
y b1 = [()];

boolean x2 = a1 < b1; // error: operator '<' not defined for 'x' and 'y'
```

**Comment by SandaruJayawardana** [comment]
Few more bugs
```ballerina
int[2] x1 = [1];
[int, int] x2 = [1,2];
boolean x17 = x1 < x2; // Currently give operator '<' not defined for 'int[2]' and '[int,int]' error
// Here, we can take [int, int] as the ordered type. Therefore, this is a valid code.
```    

```ballerina
type x [boolean, int, decimal, string, int, float]; 
type y [boolean, int, decimal]; 

x a1 = [true, 1];
y b1 = [false];

boolean x2 = a1 < b1; // currently working. But should give an error because there is no ordered type to which the static type of both operands belong.
```

**Comment by SandaruJayawardana** [comment]
```ballerina
public function main() {
    int[] a = [2];
    int[2] b = [1, 2];

    boolean x = b > a; // operator '>' not defined for 'int[2]' and 'int[]'
    boolean y = a > b; // working
}
```
here, both scenarios should be supported since we can take [int...] as the ordered type.
