### ISSUE TITLE
Add `getAllDependents` and `getAllDependencies` method to the DependencyGraph class

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#36113]
https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/DependencyGraph.java

```java
    // Returns all direct and indirect dependents of the node T
    public Collection<T> getAllDependents(T node) {
    }

    // Returns all direct and indirect dependencies of node T 
    public Collection<T> getAllDependencies(T node) {
    }
```

**Comment by shreyajha03** [comment]
@sameerajayasoma  Can I please take this issue ?
Thanks!

**Comment by adripo** [comment]
@keizer619 can I please be assigned to this issue? There have been no updates for 3 weeks

**Comment by adripo** [comment]
@keizer619 @sameerajayasoma I created a PR for the issue. If Shreya comes back with a PR, please just ignore mine. Thanks

**Comment by adripo** [comment]
Thanks @keizer619
Can you please run the workflows on my PR?

**Comment by keizer619** [comment]
> Thanks @keizer619 Can you please run the workflows on my PR?

There are some test failures.

**Comment by adripo** [comment]
@keizer619 I made some confusion in the tests, bot now they're all fixed. Please re-run the checks.

**Comment by adripo** [comment]
@sameerajayasoma @keizer619 I see that CI Windows still fails, but I don't know why. Could you have a look please?

**Comment by azinneera** [comment]
> @sameerajayasoma @keizer619 I see that CI Windows still fails, but I don't know why. Could you have a look please?

@adripo These are some intermittent test failures. We have fixed it now. Can you rebase your PR with the master branch?

**Comment by adripo** [comment]
@azinneera I resynced with master
