### ISSUE TITLE
Add more information to javadoc of `ValueCreator.createRecordValue` API

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#36116]
**Description:**

Need to mention not to use `createRecordValue(RecordType recordType)` and `createRecordValue(RecordType recordType, BMapInitialValueEntry[] keyValues)` methods to create record values using record types defined in Ballerina, and to do that use other `createRecordValue` methods.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
Closing since the fix is added through PR
