### ISSUE TITLE
NoSuchMethodError Occurs when Two Versions of the Same Package Exists 

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#36122]
**Description:**
When the same package has two versions, the following error occurs:

```shell
error: java.lang.NoSuchMethodError {"message":"'java.lang.Object io.ballerina.stdlib.http.api.service.endpoint.Start.start(io.ballerina.runtime.api.Environment, io.ballerina.runtime.api.values.BObject)'"}
```

This method is not changed, but it seems the issue is that there are two versions of the HTTP. The GraphQL package uses the HTTP `2.2.1` version, and the distribution has a different HTTP version. (`2.3.0-20220506-151100-8542beb`). 

**Affected Versions:**
Ballerina 2201.1.0-rc1

**Comment by warunalakshitha** [comment]
Is this related to async call inside tests?

Similar issue has been created with https://github.com/ballerina-platform/ballerina-lang/issues/36131 which will be fixed by https://github.com/ballerina-platform/ballerina-lang/pull/36132.

**Comment by warunalakshitha** [comment]
Seems above issue is different since NoSuchMethod error is due to issue with native code.

**Comment by ThisaruGuruge** [comment]
> Seems above issue is different since NoSuchMethod error is due to issue with native code.

Yes, this is a different issue.

**Comment by azinneera** [comment]
This issue is intermittent. Some runs are not giving any errors but when I send a request, it returns `{ballerina/lang.object}InherentTypeViolation`

**Comment by azinneera** [comment]
found that there are conflicting jars in the build.
```
Generating executable
    warning: Detected conflicting jar files:
        'http-native-2.2.1.jar' dependency of 'ballerina/websocket' conflict with 'http-native-2.3.0-20220506-151100-8542beb.jar' dependency of 'ballerina/http'
        'io-native-1.2.1.jar' dependency of 'ballerina/os' conflict with 'io-native-1.2.2-20220324-133700-7ff8450.jar' dependency of 'ballerina/io'
        'mime-native-2.2.1.jar' dependency of 'ballerina/websocket' conflict with 'mime-native-2.2.2.jar' dependency of 'ballerina/http'
```
WebSocket has an older version of http native jar. Due to this, the jars are conflicted and sometimes the old version (coming from websocket) is picked. Updating the websocket to use the latest http version would resolve the issue. 

> This issue is intermittent. Some runs are not giving any errors but when I send a request, it returns `{ballerina/lang.object}InherentTypeViolation`

Also, there are two more conflicts for io vs os and mime vs http. I think fixing these would fix the `{ballerina/lang.object}InherentTypeViolation as well.`

**Comment by azinneera** [comment]
Closing since this is resolved by updating the conflicting jars.
