### ISSUE TITLE
Async invocation inside test module failed with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#36131]
**Description:**
Getting java.lang.NoSuchMethodError when we call remote function asynchronously.

**Steps to reproduce:**
main.bal
```ballerina
public isolated client class MainClient {
    remote function getMessage() returns string {
      return "Main Client";
    }
}
```

test.bal
```ballerina

import ballerina/test;

@test:Config {}
public function testAsyncRemoteFucntionMain() returns (error?) {
    MainClient 'client = new MainClient();
    future<string> message = start 'client->getMessage();
    string|error msg1 = wait message;
    test:assertEquals(msg1, "Main Client");

}

```

Getting

SEVERE {b7a.log.crash} - 'io.ballerina.runtime.api.values.BString waruna.serviceProject.0.$_init.$lambda$observability0$getMessage(io.ballerina.runtime.internal.scheduling.Strand, io.ballerina.runtime.api.values.BObject, boolean)' 
java.lang.NoSuchMethodError: 'io.ballerina.runtime.api.values.BString waruna.serviceProject.0.$_init.$lambda$observability0$getMessage(io.ballerina.runtime.internal.scheduling.Strand, io.ballerina.runtime.api.values.BObject, boolean)'
        at waruna.serviceProject$test.0.tests.main_test.$$lambda$observability0$getMessage$lambda$_0$(tests/main_test.bal:5)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/36132
