### ISSUE TITLE
Introduce an "add connector in low-code view" like experience in the editor

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36145]
**Description:**
There's a flow in the low-code UI to add a connector. Users first search for the available connectors in the central and then use them. We should introduce a similar seamless experience to the pro-code users to explore connectors (and packages as a whole) that are available in the Ballerina central.

This will encourage/help users to discover packages and use them in the Ballerina project.

**Describe your problem(s)**
See description

**Describe your solution(s)**
New experience to explore and use packages/connectors in Ballerina Central

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
