### ISSUE TITLE
Improve completion item sorting in already completed statements

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36146]
**Description:**
Right now, LS sorts the completion items correctly for partially written statements. Ex:
```ballerina
public function main() returns error? {
    int val = get<cursor>
}

function getInt() returns int {
    return 1;
}

function getStr() returns string {
    return "";
}
```
At `<cursor>`, functions that return an int and int type variables will be sorted first. 

But if the user has already completed the statement similar to the below case, the sorting of completion items are not correct.
```ballerina
public function main() returns error? {
    int val = get<cursor>Str();
}

function getInt() returns int {
    return 1;
}

function getStr() returns string {
    return "";
}
```
In the above example, `getStr()` will be the 1st while `getInt()` comes 2nd. As per the variable declaration statement, user expect a function/var of type `int` to come first.

**Describe your problem(s)**
See description. 

**Describe your solution(s)**
Need to improve the LS `ContextTypeResolver` to derive the contextually expected type for already completed statements.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
In this particular scenario, at the cursor point, what is the resolved completion provider? What if we try to resolve to the same provider in both the cases?

**Comment by IMS94** [comment]
> In this particular scenario, at the cursor point, what is the resolved completion provider? What if we try to resolve to the same provider in both the cases?

@nadeeshaan Here the issue is with the completion item order. In 2 cases (partial and complete statement), we get 2 different results (`int` and `function () returns string`) as the context type from the `ContextTypeResolver`. That's causing the difference when we sort by assignability.
