### ISSUE TITLE
Refactor code action tests to include code action kind

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36140]
**Description:**
Look into the following.
1. Show source actions in the context menu
2. Make sure the existing code actions are grouped according to the code action kind as listed on the [document](https://docs.google.com/document/d/10LCUNwRZY3IRX0zmokyWn7W364XeCOqG8Xx4cSDYVUA/edit?usp=sharing)

**Comment by TharushiJay** [comment]
Listed in order of priority, the following subtasks are to be covered under this issue.
1) Show source actions in the context menu
2) Make sure the existing code actions are grouped according to the code action kind as listed on the [document](https://docs.google.com/document/d/10LCUNwRZY3IRX0zmokyWn7W364XeCOqG8Xx4cSDYVUA/edit?usp=sharing)
3) Implement the 3 new code actions (extract to variable, method and constant)
