### ISSUE TITLE
The command bal  run <project name> cannot find the config values

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#36156]
**Description:**

Consider a code which has a configurable variable. 
The command `bal  run` within the Ballerina project root folder works without any issue. But if we move out one level up, and use bal run <project name> gives an error like below as it can't find configurable variable values.

```
error: value not provided for required configurable variable 'greeting'
        at anupama/testConfig:0.1.0(main.bal:8)
```

**Steps to reproduce:**

Refer to the video below.

https://user-images.githubusercontent.com/16300038/168344584-726c43db-ff6c-4fd5-b538-1b7b145b0b81.mov

**Affected Versions:**

```
Ballerina 2201.0.2 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9
```

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
As per the spec for [configurables](https://github.com/ballerina-platform/ballerina-spec/blob/master/configurable/spec.md#locating-toml-files), the default path of the configuration file is `./Config.toml`. 
The error is expected in this case as the current directory (default path for the config file) does not contain the `Config.toml`. 
To make it work in any directory, we can provide the `Config.toml` path through the environment variable `BAL_CONFIG_FILES`.

**Comment by HindujaB** [comment]
The default file location-related information is mentioned on the `configurable` learn page. 
https://ballerina.io/learn/configure-ballerina-programs/provide-values-to-configurable-variables/

Hence, closing the issue. 
Please re-open if there is any concern regarding this.
