### ISSUE TITLE
Valid XML in XML template gives a compilation error

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-lang#36163]
**Description:**

`_` (underscore) is a valid XML element name but it can't be used in XML template.

**Steps to reproduce:**

```
$ cat issue.bal 
import ballerina/io;

public function main() {
    xml x = xml`<_/>`;
    io:println(x);
}
$ bal build issue.bal
Compiling source
	issue.bal
ERROR [issue.bal:(4:18,4:19)] '_' is a keyword, and may not be used as an identifier
error: compilation contains errors
```

**Affected Versions:**
```
$ bal version
Ballerina 2201.0.3 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9
```

**Comment by anupama-pathirage** [comment]
@MaryamZi Any update on this issue?

**Comment by MaryamZi** [comment]
> @MaryamZi Any update on this issue?

I'm afraid we haven't started on this yet. We will look into this in an upcoming sprint.

As an alternative, we can use the `xml:createElement` langlib function for now.

```ballerina
import ballerina/io;

public function main() {
    xml x = xml:createElement("_");
    io:println(x);
}
```

**Comment by pcnfernando** [comment]
@prakanth97 Can you backport the fix to the applicable branches

**Comment by prakanth97** [comment]
> @prakanth97 Can you backport the fix to the applicable branches

Sure
