### ISSUE TITLE
Use of `change return type` code action in union contexts

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#36167]
Refer to the following. The change return type code action doesn't work for union type contexts. In the following, what I expected to be able to do is add the type of the newly added return expression to the return type signature. i.e., make the return type a union. But instead, this changes the return type to the type of the new expression, breaking the code.

![image](https://user-images.githubusercontent.com/6260009/168740232-3da02051-04e5-43f8-bc8b-ee30f8d6bdfd.png)

```ballerina
function foo() returns int {
    int|string x = 10;

    if x is int {
        return x;
    }

    return x;
}
```

**Comment by mindula** [comment]
When we try to get the typeSymbol of `x`, it returns only `string` instead of `int|string`. This seems to be happening due to type narrowing. At the diagnostic location in this scenario, the type of `x` is narrowed to `string`. Because of that the return type of the function cannot be changed to `int|string `.

**Comment by pubudu91** [comment]
Ah no, this is a more general issue which cannot be solved just by looking at the type of the expression at the diagnostic location. And on second thoughts, maybe not a good idea to try and squeeze in this behaviour to the change return type code action 🤔 Basically what I had in mind is a behaviour like follows:


https://user-images.githubusercontent.com/6260009/171462622-6da1c84b-f839-4cde-9155-39a49f6e0ef1.mov
