### ISSUE TITLE
Service completions incomplete when first editing a source file

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#36170]
Refer to the following:

https://user-images.githubusercontent.com/6260009/168760420-ffbb7608-a673-4f67-a0bb-005b5324f621.mov

Note how the list of service snippets on various types of listeners is missing initially.

**Comment by IMS94** [comment]
@malinthar This behavior is expected at the initialization right? Can we improve this?

**Comment by malinthar** [comment]
> @malinthar This behavior is expected at the initialization right? Can we improve this?

This is expected. The initial completion request triggers the initialization of the Service Snippet Generator. 
To improve this we need to make the Service Snippet generator independent on the completion context and do the initialization to the Language Sever `init` method. That may be possible. But we have to dive in and figure out.
