### ISSUE TITLE
Semver tool test for Type definition

### ISSUE THREAD

**Issue by prathees98** [ballerina-platform/ballerina-lang#36182]
List down the possible positive + negative unit test cases to validate semantic CLI tool type definition APIs.
Need to implement those unit test cases for patch version verification.

split test data sets of module type definition and keep separate test sets in a separate json file for sub levels like annotation, documentation, identifier, type descriptor and advance type definition test cases (This is for capturing more than one changes in source code).

For an example, Rename a type definition.
Old code - `type Coord record{
int x;
int y;
 };
`
New code - `type Age record{
int x;
int y;
 };
`

Here the tool should identify the change in type definition identifier and need to suggest a appropriate version change. 
Other than that tool should identify more than one change in the type definition source code.
For an example Change the name of the record and add new field in to a type definition record.
Old code - `type Person record {
	string name;
	int age;
};
`
New code - `
type Coord record{
	string name;
	int age;
       int id;
 };
`
Here tool should identify two changes and need to suggest correct version change according to that changes in the source code.

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/36956
