### ISSUE TITLE
Semver tool test for Class definition

### ISSUE THREAD

**Issue by prathees98** [ballerina-platform/ballerina-lang#36183]
List down the possible positive + negative unit test cases to validate semantic CLI tool class definition APIs.
Need to implement those unit test cases for patch version verification.

split test data sets of module class definition and keep separate test sets in a separate json file for sub levels like annotation, documentation, identifier, class members and advance class definition test cases (This is for capturing more than one changes in source code).

For an example, Rename a class definition.
Old code - `public class Person{}`
New code - `public class Employee{}`

Here the tool should identify the change in class definition identifier and need to suggest a appropriate version change. 
Other than that tool should identify more than one change in the type definition source code.
For an example Change the object field type and add a new method in class definition record.
Old code - `public class counter{
	public int n;
	public int age;
}
`
New code - `public class counter{
	public int n;
	public String age;
       public function count(){}
}
`
Here tool should identify two changes and need to suggest correct version change according to that changes in the source code.

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/36906
