### ISSUE TITLE
Non-public types are accessible outside the module

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#36203]
**Description:**
> $Subject

**Steps to reproduce:**

1. Create one module : `module1` (`bal new module1`) and add the following to the `main.bal` : 
```ballerina
import ballerina/io;

// Level 1
public type Error distinct error;

// Level 2
public type ClientError distinct Error;
public type ListenerError distinct Error;
public type PayloadBindingError distinct Error;

// Level 3 - Internal Error Types
type PayloadBindingClientError ClientError & PayloadBindingError;
type PayloadBindingListenerError ListenerError & PayloadBindingError;

public function main() {
    io:println("Hello, World!");
}
```

2. Pack the module (`bal pack`) and push it to the local central (`bal push --repository=local`)

3. Create another module : `module2` (`bal new module2`)

4. Add the `module1` dependency to `module2/Ballerina.toml`:
```toml
[[dependency]]
org="user"
name="module1"
repository="local"
version="0.1.0"
```

5.  Add the following to the `main.bal` : 
```ballerina
import ballerina/io;
import user/module1;

public function main() {
    error err = error module1:PayloadBindingClientError("Hello, World!");
    io:println(err.message());
}
```

6. Run `module2` (`bal run module2`). There will be no compiler errors saying that `PayloadBindingClientError` is not accessible.

**Affected Versions:**
Ballerina SwanLake 2201.1.0 - RC1

> Note : 
There is no compiler errors even when the intersection types are non-public. But when there is no intersection, it is giving an error

**Comment by chamil321** [comment]
Checked with HTTP package, seeing the similar behaviour.

**Comment by MaryamZi** [comment]
Seems like error intersections are constructed as public types.

Non-default module `foo`
```ballerina
public type E1 distinct error;
public type E2 distinct error;

type E3 error<record {| int code?; |}>;

type E4 distinct error;

type E5 E1|E2;

type E6 E1 & E2;

type E7 distinct error;
type E8 E4 & E7;

type R record {
    int i;
};

type I readonly & R;
```

Default module
```ballerina
import temp_proj.foo;

public function main() {
    // OK
    error e1 = error foo:E1("error!");
    error e2 = error foo:E2("error!");

    // Errors as expected
    error e3 = error foo:E3("error!");
    error e4 = error foo:E4("error!");
    error e5 = error foo:E5("error!");

    // No errors.
    error e6 = error foo:E6("error!");
    error e8 = error foo:E8("error!");

    // Error as expected.
    foo:I i = {i: 1};
}
```
