### ISSUE TITLE
JSON Value to Ballerina Type mapping utility - refactor to map directly from value to type

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#36212]
This requirement is to map JSON value directly into the Ballerina record without any intermediate conversion.

Requirement

- Develop a module to convert a JSON string directly to a Ballerina record
- The module should be developed independently so that other modules can use this in future
- The module should be developed as a miscellaneous module, In the ballerina-lang repo under misc

Note: The JSON to Ballerina data mapping related information can be found here [1].
[1] https://docs.google.com/document/d/1hgVsywpozJEVS-DWQxY8iADCEc9LIQcMorSmOfPhF6Q/edit
[2] https://docs.google.com/document/d/19bxPh5sfR_ctOuBEDp4pJzMMHdYElPdb0nT2coWYZbU/edit#

- [x]  Finalize the specification for possible scenarios https://github.com/ballerina-platform/ballerina-lang/issues/36486
- [x]  Finalize the parser for the JSON validator
- [x]  Design the implementaion
- [x]  Implemente the util

**Comment by anupama-pathirage** [comment]
@keizer619 Please  add  the  Proper `Area/` and `Type/` labels.

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/36858 and https://github.com/ballerina-platform/ballerina-lang/pull/36963
