### ISSUE TITLE
Fix completions for configurable qualifier 

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#36216]
**Description:**
Fix completions provided for the configurable qualifier when there's a function implemented.
The current implementation takes the completion items from `getModulePartContextItems` and it includes a list of snippets for `public main function() {}`. To resolve that we can use the `onSuggestionAfterQualifier()` method and get the correct completion item list once #36215 is fixed. 

**Steps to reproduce:**
```
configurable <cursor>             

public function main() {
    
}
```

**Comment by IMS94** [comment]
Duplocate of #36323. Closing this since the other issue has more context.
