### ISSUE TITLE
Highlight/show TODO’s as info diagnostics

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36220]
**Description:**
Developers use `TODOs` to keep track of future work within the projects. In IntelliJ IDEA, there's a separate panel to view TODOs. But due to the limitations in language server protocol, we cannot give a similar experience. 

But looking at the RedHat java plugin, it shows TODOs as info diagnostics under the problems tab. This is a good way for the users to keep track of TODOs and if we can implement the same for Ballerina, it will be helpful.

**Describe your problem(s)**
See description

**Describe your solution(s)**
We need to analyze the documentation nodes in a separate compiler plugin and publish INFO diagnostics for TODOs we find.

**Comment by KavinduZoysa** [comment]
Duplicate of #36137
