### ISSUE TITLE
Introduce bal graph command

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#36229]
**Description:**
https://github.com/ballerina-platform/ballerina-spec/issues/928

**Comment by azinneera** [comment]
AFAIU, the purpose of this command is to be able to troubleshoot package resolution issues. The normal behavior of a user would be that he/she executes `bal build/run/test` and then if the command fails, he would run `bal graph` to see if there is an issue with the resolution.

As per the last meeting, we decided the following:
i. Introduce `bal graph` - implementation is to run upto resolution, print the graph, exit
ii. Remove the `hidden="true"` for `--dump-graph`, `--dump-raw-graphs` in `bal build` `run` and `test`

The reason to provide the 2nd option is that, if there are code generators and modifier plugins engaged, then the resolution is run twice and there can be changes to the dependencies in the 2nd run. So the `bal graph` would not produce the correct result for this case.

So I see two options to go forward with this:

1. Change the implementation of `bal graph` to be able to reproduce the same resolution outputs as the `bal build/run/test`
    - This means we should run compiler extensions in `bal graph` command and generate the graphs before and after
    - Since many packages are using code generators and modifiers now (e.g. http, graphQL, websub, log, azure_functions) the probability of the `bal graph` command being relevant is quite low
2. Drop `i` and implement only `ii`
    - The graph will be dumped even if the compilation fails
    
IMO, approach 2 is would be enough since the purpose of the user is to check why the build/runtime fails and the flag can be a option that can be passed to troubleshoot. @sameerajayasoma @hevayo WDYT?

**Comment by sameerajayasoma** [comment]
I agree that we should dump the final graph for every execution of `bal graph` command. 

Even though the main purpose of this utility is to troubleshoot dependencies resolution related problems, there can be other usages such as analyzing and visualizing the dependencies of a package. We discussed having such a view in Choreo.  

I prefer to have a separate command. This gives us the ability to customize the graph output, and change representations to help developers to identify issues easily. See https://doc.rust-lang.org/cargo/commands/cargo-tree.html and https://go.dev/ref/mod#go-mod-graph

**Comment by azinneera** [comment]
We discussed and agreed on the following:
* Introduce `PackageResolution.dumpGraph(PrintStream)`
* Remove the `System.out` from the `PackageResolution` and maintain a custom stream to dump all graphs
* When the API user calls `PackageResolution.dumpGraph(PrintStream)`, we write the content from the resolution stream to the user's stream.
