### ISSUE TITLE
[Shell] `Const`'s are not available for `/vars`

### ISSUE THREAD

**Issue by HirumalPriyashan** [ballerina-platform/ballerina-lang#36319]
**Description:**
$subject

Consider the following.
![image](https://user-images.githubusercontent.com/57571152/170257680-507f2247-d692-4300-8639-3b5887a72400.png)

**Suggested Labels (optional):**
Area/Shell

**Comment by dulajdilshan** [comment]
Here x is a constant right? why should we consider listing `x` down in `/vars`?

**Comment by HirumalPriyashan** [comment]
IMO `const` specifies that a **variable** value is constant. Except for the facts that `const` is immutable and known at the compile time(yes, those can be used to say that const is not a variable as well - so there's a bit of ambiguity), const can be used like a variable.

**Comment by DamithaSenevirathne** [comment]
Fixed by https://github.com/ballerina-platform/ballerina-lang/pull/36653
