### ISSUE TITLE
Refactor the usage of CodeActionContextTypeResolver

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#36324]
**Description:**
With https://github.com/ballerina-platform/ballerina-lang/pull/36110 we have introduced a new NodeTransformer called CodeActionContextTypeResolver to resolve the expected context type for a given code action context. It's observed that the logic inside this reolver might duplicate the logic of ContextTypeResolver for completion context. We have to come up with a design to refactor such duplication.

**Comment by mindula** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39811
