### ISSUE TITLE
Type suggestions are not provided after `configurable` keyword when its followed by a function

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36323]
Consider the following scenario. 
```
configurable <cursor>

public function main() {
    
}
``` 
Here the completion items include module level completions items (like main function, type defs, service declarations, etc). This needs to be fixed to suggest types instead.

_Originally posted by @mindula in https://github.com/ballerina-platform/ballerina-lang/issues/36189#issuecomment-1131190584_

**Comment by IMS94** [comment]
Blocked by #36215

**Comment by IMS94** [comment]
Relates to #35953

**Comment by LakshanWeerasinghe** [comment]
@IMS94 When I try to reproduce this issue, `types` were suggested along with `Snippets`, `Keywords` etc. So we need to do is prioritize the `types` suggestions. Right?

<img width="624" alt="Screenshot 2022-07-08 at 14 12 03" src="https://user-images.githubusercontent.com/46857198/177954143-a716e0c9-df6a-4f42-9d13-34a30a9b583e.png">

**Comment by IMS94** [comment]
Seems like this hasn't been fixed in #38227 in 2201.3.2-rc1. Need to check and fix.
![Peek 2023-01-13 14-51](https://user-images.githubusercontent.com/11285165/212284356-4182e652-163c-4529-bbf2-ef809916674a.gif)

**Comment by IMS94** [comment]
Actually the type suggestions are there now. But the sorting order is incorrect.
