### ISSUE TITLE
Create function code action doesn't work in lhs expression in ternary conditional expression

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36321]
Consider the following case
```
function testConditional3(int arg) {
    string res = isGreaterThanZero(arg) ? "a" : "b";
}
```
currently create function code action creates following method while we expect a `boolean` return
```
function isGreaterThanZero(int i) returns string {
    return "";
}
```

_Originally posted by @gayalkuruppu in https://github.com/ballerina-platform/ballerina-lang/pull/35815#pullrequestreview-981097638_

**Comment by dulajdilshan** [comment]
Assignee: @bimsarapathiraja
