### ISSUE TITLE
Field completions are missing in mapping constructor expression in named arg and new expression

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36339]
**Description:**
Some completions are missing in the master branch for the following scenarios.

**Steps to reproduce:**
> mapping_expr_ctx_source29.bal
```
type Application record {|
    string id;
    string name;
    int 'version;
|};

type ErrorData record {
    string errorCode;
    Application application;
};

type CustomError error<ErrorData>;

public function checkError() returns CustomError? {
    return error CustomError("Custom error", errorCode = "123", application = {<cur>});
}

```
> mapping_expr_ctx_source63.bal
```
type ClientConfig record {|
    string host;
    int port;
    string scheme;

    int timeout;
|};

public type Error distinct error;

client class Client {

    private ClientConfig config;

    public function init(ClientConfig config) returns error? {
        self.config = config;
    }

    remote function findByName(string name) returns json|Error {
        return {
            id: "123",
            name: "Test"
        };
    }
}

public function main() returns error? {
    Client cl = check new ({<cur>});
}
```

**Affected Versions:**
master branch

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/pull/35210

**Comment by IMS94** [comment]
Caused by #35210. Suggestions for the mentioned scenarios are not coming after the mentioned PR. Need to investigate.

**Comment by IMS94** [comment]
Blocked (named arg scenario) by #36356

**Comment by IMS94** [comment]
Since the blocked issue has been fixed, we can test and enable the disabled LS test

**Comment by malinthar** [comment]
Case 1 is not reproducible on 2201.2.x 
![image](https://user-images.githubusercontent.com/35211477/183575006-4ba583fc-5722-429e-a921-43545ecfbc93.png)
