### ISSUE TITLE
Type narrowing does not work with maps and inside lambda functions

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#36377]
**Description:**
```ballerina
function f1() returns boolean {
    decimal sa = 10d;
    map<decimal?> m = {x: 10d};
    return m["x"] == () || m["x"] < sa;
}
```

```ballerina
function bar(decimal? num) {
    var foo = function () {
        io:println(num == () || num > 0d);
    }; 
}
```

**Steps to reproduce:**

**Affected Versions:**
2201.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Type narrowing happens only for local variables and parameters (see https://ballerina.io/spec/lang/master/#conditional_variable_type_narrowing).

In both of these cases, we can't guarantee the variable to be of the narrowed type when we get to the second expression. So type is not narrowed.
