### ISSUE TITLE
Debugger not hitting the breakpoints in modules

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#36381]
**Description:**
Debugger not hitting the breakpoints in modules

**Steps to reproduce:**

1. Create a ballerina project
2. Add a module
3. Call a function in the module from the project bal file
4. Add a breakpoint to the module code
5. Try debugging

**Affected Versions:**
2201.1.0

**OS, DB, other environment details and versions:**
Ubuntu

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
@gigara I could reproduce the issue while debugging non-default modules. it seems we can step int/over/out on non-default modules but direct breakpoint hits aren't working. Debugging inside default module works as expected.
