### ISSUE TITLE
Add completion support for resource method call action

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#36382]
**Description:**
$title

https://github.com/ballerina-platform/ballerina-lang/pull/36378 introduce the parser changes for resource method call action. With that the  `remote_action_config3.json` test is disabled since the node is not implemented.

**Comment by lochana-chathura** [comment]
Need to enable `config29.json` and `config30.json` as well.

**Comment by IMS94** [comment]
Need to add completion support for the following cases:
1. `resource method` snippet completions inside client objects
2. Completions for type inside `resource-path-segment-param`
3. Completions for resource function names. This becomes tricky with the resource path segment params.

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/36891
