### ISSUE TITLE
Invalid type symbol given when a tuple is returned

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#36410]
**Description:**
Consider the following scenario,
```
function testTuple() returns string {
    return ["string", 10];
}
```
In the above case when we check the type of `[string,10]`, it returns `CompilationError`.

**Comment by IMS94** [comment]
Relates to #36167

**Comment by dulajdilshan** [comment]
Related spec doc: https://ballerina.io/spec/lang/master/#list-constructor

**Comment by dulajdilshan** [comment]
Here the contextual type is wrong, This happens for the mapping-constructor, table, and stream type as well. According to the compiler implementation, if the contextual type is wrong, the type, determined type and the expected type become no-type. which makes the Semantic API send a CompilerError when evaluating the type

**Comment by dulajdilshan** [comment]
Discussion on this: https://ballerina-platform.slack.com/archives/C9WMA6QDC/p1656578341414059

**Comment by dulajdilshan** [comment]
Since the contextual type is wrong, this behaviour is correct.
