### ISSUE TITLE
Allow a Package to Specify Which Files to Include When Creating a BALA File

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#36429]
Description: https://github.com/ballerina-platform/ballerina-spec/issues/988

**Comment by pramodya1994** [comment]
There's a requirement in the graphql package of resources API.
As per the internal discussion had with @DimuthuMadushan, He confirmed it is used in runtime, So we can replace that with golang `@embed` like design.
This is the HTML file they are using as response dispatch to the browser. ATM It's only 46 lines long.
https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/native/src/main/resources/graphiql.html

**Comment by gayaldassanayake** [comment]
Reopening since the usage of patterns will be completed only after the merging of https://github.com/ballerina-platform/ballerina-lang/pull/36877

**Comment by Ibaqu** [comment]
Add both PRs to 2.x branch
