### ISSUE TITLE
Equality expr is not allowed with records containing rest descriptor of type any

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#36430]
**Description:**

Consider the below sample gives the error for equality expr with records containing rest descriptor of type any

```bal
public function main() {
    record {|any...;|} x = {};
    io:println(x == x); // error operator '==' not defined for 'record {| any...; |}' and 'record {| any...; |}'
}
```

Another sample could be the same issue

```bal
public function main() {
    map<any> result2 = {};
    boolean a = {result2} == {result2}; // error operator '==' not defined for 'record {| map result2; |}' and 'record {| map result2; |}'
}
```

**Comment by MaryamZi** [comment]
`==` and `!=` can be used only when at least one of the operands is of a type that is a subtype of `anydata`.

Quoting the [spec](https://ballerina.io/spec/lang/master/#section_6.29)

> For both == and !=, at least one of the operands must have a static type that is a subtype of anydata.

The following works.

```ballerina
import ballerina/io;

public function main() {
    record {|any...;|} x = {};
    record {|anydata...;|} y = {};
    io:println(x == y);
}
```
