### ISSUE TITLE
Cannot pass negative numbers as arguments to a ballerina program

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#3643]
Since the negative number starts with `-`, a negative number is interpreted as a flag. For example, consider an instance where I want to pass `-200` as a CLI parameter to my Ballerina program.
```
$ ballerina run program.bal -200
```
The above results in the following message.
```
ballerina: unknown flag '-200'
Run 'ballerina help' for usage.
```

**Comment by MaryamZi** [comment]
A common approach to pass negative numbers (or any value starting with `-`) as arguments seems to be the introduction of `--` (to indicate that an argument is not a flag) as follows:
```cmd
$ ballerina run program.bal -- -200
```
