### ISSUE TITLE
Extended language service server capabilities not registered at initialization

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36448]
**Description:**
$subject

The following extended language services are currently not working. These extended services are not in the LS server capabilities list.

```
jsonToRecord/convert
performanceAnalyzer/getResourcesWithEndpoints
partialParser/getSTForSingleStatement
partialParser/getSTForExpression
openAPILSExtension/generateOpenAPI
ballerinaTrigger/trigger
ballerinaTrigger/triggers
```

**Steps to reproduce:**
Debug and look at the capabilities returned by LS in `BallerinaLanguageServer.initBalServices()` method.

**Affected Versions:**
2201.0.2, 2201.0.3, 2201.1.0, 2201.1.1-SNAPSHOT

**Comment by IMS94** [comment]
Had a look at this. This happens because the `META-INF` directory containing services is not auto generated when being built for modules under `misc/ls-extensions`

**Comment by IMS94** [comment]
Capabilities not being registered for the above mentioned services was due to SPI not detecting the implementations in extension modules. For that we have to add the implementation names under `resources/META-INF/services`. With #36451 I have added them.

However, the `partial parser` does not adhere to the new extended service model and does not implement the `CapabilitySetters`. You have to update those extensions to match. @prabushi @gigara

**Comment by IMS94** [comment]
Created https://github.com/ballerina-platform/openapi-tools/issues/1006 to fix this for OpenAPI LS extended service

**Comment by gigara** [comment]
@IMS94 noted. We will fix the partial parser.
