### ISSUE TITLE
Run test cases from `dataProvider` in sorted order

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#36465]
When cases are provided via a `@test:Config` `dataProvider` make them run in a sorted order.

**Comment by gayaldassanayake** [comment]
@manuranga can you elaborate on this more? 

Currently data driven tests accept two formats of data as mentioned [here](https://ballerina.io/learn/test-ballerina-code/define-data-driven-tests/).
1. Map of tuple
2. Array of array

Array of array tests are running in the provided order of the array.
