### ISSUE TITLE
Completions for query expression from clause are not sorted

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#36482]
**Description:**

Completions coming for `expression` in from clause doesn't seem to be sorted.

![Screenshot 2022-06-08 at 20 45 20](https://user-images.githubusercontent.com/26219651/172653356-7914fd9e-aaed-4dc4-a91c-a890f8b5e489.png)

**Steps to reproduce:**

Try to get completions for the mentioned position.
```ballerina
type Country record {
    string name;
    boolean independent?;
    decimal area;
    int population;
    string[] timezones;
};

configurable string cStr = "";

public function main() {
    Country[] res = [];
    string p1 = "";
    string p2 = "";
    int i1 = 0;
    int i2 = 0;

    Country[] filteredCountries = from Country c in //get completions here

}

function getCountries() returns Country[] {
    return [];
}
```

**Affected Versions:**
Ballerina 2201.1.0

**Comment by LakshanWeerasinghe** [comment]
@madushajg Currently the sorting order of the from clause context is prioritized as below
1. Iterables
2. Function call expressions 
3. Rest of the completions.

**Comment by LakshanWeerasinghe** [comment]
@madushajg  Can you specify what is your suggested order?

**Comment by madushajg** [comment]
> @madushajg Can you specify what is your suggested order?

@LakshanWeerasinghe [This](https://github.com/ballerina-platform/ballerina-lang/issues/36482#issuecomment-1161328930) order seems to be fine. However for the given scenario it suggested module var and local vars over iterable isnt'it?
