### ISSUE TITLE
Update Ballerina Compiler Toolkit extension icon

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#36484]
**Description:**
It would be better if we can update the Ballerina Compiler Toolkit VS Code extension icon.

<img width="327" alt="Screenshot 2022-06-08 at 10 13 16" src="https://user-images.githubusercontent.com/5234623/172762321-f9459aad-a68f-49f5-8d12-13c9db956936.png">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
