### ISSUE TITLE
Introduce caching for current project to improve build time

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#36499]
**Description:**
Need to check how we can improve build time by using generated BIR of the current module when the package is not changed.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pramodya1994** [comment]
Problems encountered when trying to use generated BIRs:

1. Accessing the Semantic model from the BIR is not possible
- `ObservabilitySymboldCollector` needs it
- `CompilerPlugins` need it

  To overcome the issue, two steps were taken: 
- reduced the scope for the first cut (When BIR is already in the target and if the package has not updated, tried only emitting executable by calling only `emit()` method inside `JBallerinaBackend`.)
- tried to skip compilation and perform only code generation but still, the `LifecycleTasks`  cannot be ignored

**Comment by azinneera** [comment]
> Problems encountered in code generation:
> 
> * The `LifeCycleTasks` compiler plugins are run after code generation is completed. Currently, this is used for cloud artifact generation (`bal build --cloud`)
>   
>   * This needs a compilation
>     https://github.com/ballerina-platform/ballerina-lang/blob/be3b2822af3fe3481bf5d86a1c10f0ab55283635/compiler/ballerina-lang/src/main/java/io/ballerina/projects/JBallerinaBackend.java#L215
>   * Semantic model can be accessed in the compiler plugin since the current package is provided in the plugin context

* `LifeCycleTasks` run after the code generation and since accessing the Semantic model is not allowed after the code generated phase, this is a bug that is there already. 
* AFAIU, we can't completely ignore the compilation but we can skip the code generators, modifiers, and analyzers and go ahead with the executable creation. When creating the compilation we should address the following:

  - Skip running code generators and code modifiers - this can be done in CompileTask
    https://github.com/ballerina-platform/ballerina-lang/blob/be3b2822af3fe3481bf5d86a1c10f0ab55283635/cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CompileTask.java#L94-L95
  - Skip running code analyzers - we can add a check by looking at the compilation state of the default module
    https://github.com/ballerina-platform/ballerina-lang/blob/be3b2822af3fe3481bf5d86a1c10f0ab55283635/compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java#L99-L102

**Comment by pramodya1994** [comment]
> * AFAIU, we can't completely ignore the compilation but we can skip the code generators, modifiers, and analyzers and go ahead with the executable creation. When creating the compilation we should address the following:
>   
>   * Skip running code generators and code modifiers - this can be done in CompileTask
>     https://github.com/ballerina-platform/ballerina-lang/blob/be3b2822af3fe3481bf5d86a1c10f0ab55283635/cli/ballerina-cli/src/main/java/io/ballerina/cli/task/CompileTask.java#L94-L95
>   * Skip running code analyzers - we can add a check by looking at the compilation state of the default module
>     https://github.com/ballerina-platform/ballerina-lang/blob/be3b2822af3fe3481bf5d86a1c10f0ab55283635/compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java#L99-L102

After skipping the above 2 instances, We could successfully rebuild a package having a `http` import.

**Comment by pramodya1994** [comment]
After having an offline discussion with @xlight05 identified code analyzer is used as a data holder in c2c. There semantic model will be accessed. As a solution to this problem project API should be provided data holder in compiler extensions and that will need some time design and implement.

**Comment by pramodya1994** [comment]
After discussion with @hevayo and @azinneera, decided to introduce a new build option called `enableCache` and explicitly enable it for the standard library for the second build (if the project has not been updated). This will not be passed to the c2c libraries.
