### ISSUE TITLE
[Semantic API] Resolve cyclic union type in `TypeParamResolver`

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#36519]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sanjana** [comment]
Since the `TypeParamResolver` is used when getting the lang lib methods of a type symbol and, it is highly unlikely that a cyclic union type dependency would be present in langlibs, deprioritizing this issue.
