### ISSUE TITLE
Meaningless error with `check trap xxxx()`

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#36528]
```ballerina
function testRunner(string s1, string s2) returns error? {

    check trap testCreateIgVersionService(s1, s2); // [squiggly lines on trap keyword] invalid expression, expected a call expression(BCE0671)
    _ = check trap testCreateIgVersionService(s1, s2);
}

function testCreateIgVersionService(string s1, string s2) returns error? {

}
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina 2201.1.0 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.9
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Prior to update to 2 (https://ballerina.io/spec/lang/2022R1/#call-stmt) check was only allowed as a statement if the expression it was used with was a function/method call. 

With update 2 (https://ballerina.io/spec/lang/2022R3/#section_7.17) this has been allowed - https://github.com/ballerina-platform/ballerina-lang/issues/36190.
