### ISSUE TITLE
[Semantic API] Getting the expected type for a given ST node position

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#36539]
Requirement for the $subject in Choreo statement editor

**Comment by DamithaSenevirathne** [comment]
Considering the requirement of the issue, Similar implementations(`ContextTypeResolver`) already implemented in the `debugger` and the `language-server`.

Based on the discussions, A new API which provides `expected type` will be implemented in the SemanticModel as follows,

`Optional<TypeSymbol> expectedType(Document document, LinePosition linePosition);`

This new implementation can be used by the `debugger`, `language-server` and in `Choreo statement editor`.

**Comment by NipunaRanasinghe** [comment]
@DamithaSenevirathne Just for your record, another use case of this API would be the new [semver validator tool](https://github.com/ballerina-platform/ballerina-lang/issues/32368), where we'll need this API to improve the existing type comparison logic. What will be the ETA of this API?
