### ISSUE TITLE
[Shell] Error output not matching with single `bal` file output

### ISSUE THREAD

**Issue by HirumalPriyashan** [ballerina-platform/ballerina-lang#36547]
Error output generated by Ballerina shell does not match with the output produced by executing single `bal` project file.

![image](https://user-images.githubusercontent.com/57571152/173801452-058c4b3b-1ab5-4f82-b2fb-014db9c9891c.png)

Noticed the same with following BBEs,
- https://ballerina.io/learn/by-example/match-statement-with-maps.html
- https://ballerina.io/learn/by-example/named-worker-return-values.html
- https://ballerina.io/learn/by-example/retry-transaction-statement.html
- https://ballerina.io/learn/by-example/rollback.html

**Comment by mohanvive** [comment]
Yes, this is expected. We discussed on this and decided not to change this.
