### ISSUE TITLE
Allow access for types of parameterized returns

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36542]
**Description:**

I'm trying to fetch the type of `cli-> get("convert?to=LKR&from=USD&amount=1&date=2022-05-29",{apiKey})` using the return type of the `http:Client`s `get()` method and access the types of the type, `TargetType` which are, `Response` and `anydata`. 

<img width="630" alt="Screenshot 2022-06-15 at 11 37 09" src="https://user-images.githubusercontent.com/46120162/173754884-04cf2333-abad-4330-9055-855da20b4158.png">

<img width="1152" alt="Screenshot 2022-06-15 at 11 42 24" src="https://user-images.githubusercontent.com/46120162/173755228-8f4067c1-4384-4e33-92ae-0399f24a0bcf.png">

`http_client_endpoint.bal`

<img width="883" alt="Screenshot 2022-06-15 at 11 39 20" src="https://user-images.githubusercontent.com/46120162/173754869-0782c276-5a56-483f-bb16-fc551480c47c.png">

`http_types.bal`

<img width="852" alt="Screenshot 2022-06-15 at 11 41 05" src="https://user-images.githubusercontent.com/46120162/173755009-98d08667-5838-4386-8903-647cc2cc8932.png">

**Steps to reproduce:**
```
import ballerina/http;

configurable string apiKey =  ?;
public function main() returns  error? {

    http:Client cli = check new("https://api.apilayer.com/exchangerates_data");
    cli-> get("convert?to=LKR&from=USD&amount=1&date=2022-05-29",{apiKey});
}
```
**Affected Versions:**
2201.1.0

**Comment by dulajdilshan** [comment]
Spec: 5.5.2
> A return-type-descriptor may be depend on the param-list in the following way. A type-reference occurring in a return-type-descriptor can refer to a parameter name if the type of the parameter is a subtype of typedesc. If p is such a parameter, then a reference to p in the return-type-descriptor denotes the type that is the value of p. If the default value for p is <> and p occurs in the return-type-descriptor in a union p|T, then for every basic type B, either the intersection of B and T must be empty, or the intersection of typedesc<B> and the declared type of p must be empty, or both. The return-type-descriptor thus denotes a distinct set of shapes for each invocation of the function. A function-signature with a return-type-descriptor that uses a type-reference to refer to a parameter name in this way is said to be dependently-typed. Functions with dependently-types signatures can be declared and used within Ballerina, but Ballerina does not yet provide a mechanism to define such functions.

**Comment by DamithaSenevirathne** [comment]
Solution for this issue to check for the `parameterized` symbol in the `SymbolFactory` and return `TypeReferenceTypeSymbol`.
