### ISSUE TITLE
Annotations not passed for union type refernce types

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#36543]
**Description:**
$subject
```ballerina
@Int {
    minValue: 18
}
type Bar int|float; // must pass the proper annotations to runtime
```

**Affected Versions:**
latest master

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
#36408

**Comment by HindujaB** [comment]
The actual requirement is to access the annotations of the union type at runtime through an extern function. 
```ballerina
@Int {
    minValue: 18
}
type Bar int|float;

public function main() {
    int b = 25;
    Bar|error val2 = validate(b);
}

public isolated function validate(anydata value, typedesc<anydata> td = <>) returns td|error = @java:Method {
    'class: "..."
} external;
```
where the annotations are retrieved using 
```java
public static Object validate(Object value, BTypedesc typedesc) {
    Type describingType = typedesc.getDescribingType();
    BMap<BString, Object> annotations = ((AnnotatableType) describingType).getAnnotations();
}
```
The problem happens when we infer the union type for the function-call `validate()`. 

In compiler FE, we flatten the union member types when inferring parameter types for extern functions. Due to that, the expected method-call `validate(b, Bar)` is converted into `validate(b, int|float)`. 
https://github.com/ballerina-platform/ballerina-lang/blob/4175b5491ca992402a9ff93a47db3899ad7acb31/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/Unifier.java#L439

Therefore, the required type-information to get the annotations is not available during the code generation. 
It would be preferable if we have the `TypeReferenceType` information when we load the type as a parameter.

**Comment by pcnfernando** [comment]
Reopening the issue since the below code crashes with the fix. This is because now the TypeReference type is propagated across unseen paths. Hence, need to test thoroughly.
```ballerina
type FooError record {
    string errorMessage = "";
};

type BarTypedesc typedesc<json>;


function dummyTest() {
    FooError fooError = {errorMessage:"msg"};
    var x = fooError.cloneWithType(BarTypedesc);
}
```
