### ISSUE TITLE
Implement the `Extract to method` code action

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36570]
**Description:**
Creates a new method containing the statements or expressions currently selected and replaces the selection with a reference to the new method. This feature is useful for cleaning up lengthy, cluttered, or overly complicated methods.

**Describe your problem(s)**
Before:
```
class Square {
    function calculateArea() {
        int height = 1;
        int width = 2;
        int area = height * width;
    }
}
```
**Describe your solution(s)**
After:
```
class Square {
    function calculateArea() {
        int height = 1;
        int width = 2;
        int area = self.getArea(height, width);
    }

    private function getArea(int height, int width) returns int {
        return height * width;
    }
}
```

**Comment by gayalkuruppu** [comment]
How are we going to handle resolving the CodeActionNodeType?  @IMS94

**Comment by IMS94** [comment]
That part will be untouched. May be in the future we can change the `CodeActionNodeType` to use `SyntaxKind` instead. With the above model, we will only make common logic to co-exist in a better manner. Inside `CodeActionRouter` we have to perform the same checks and run all 3 (2 +new range based code actions) code actions providers.

**Comment by gayalkuruppu** [comment]
But we will have to handle `range` and `cursor position` separately to get the `CodeActionNodeType` right? How is the `CodeActionNodeAnalyzer` implemented in this design?

**Comment by gayalkuruppu** [comment]
For the range it can fail with the current `codeActionNode` logic, if we're using that we need to improve it(if that is a possibility while not breaking current `nodeBasedCodeAction` implementation) For an example,
```
function testFunction() {
    int age = 2;
    age = age + 1;
}
```
what we get for the `codeActionNode` is the `variable declaration` when selected the two lines in the function body.

**Comment by gayalkuruppu** [comment]
As discussed offline, this code action will not support the statements which includes `NAMED_WORKER_DECLARATION` and `ACTION_STATEMENT`.

**Comment by gayalkuruppu** [comment]
Supported scope(node-wise) can be found [here](https://docs.google.com/document/d/1AcmzqXkIyvCcxbRSsTs6wwT9vIg5M6Wti5zov0WkbK8/edit?usp=sharing)
