### ISSUE TITLE
Ambiguous target type error when type can be determined

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#36604]
source:
```ballerina
const Access = "public";
type FunctionAccess Access[0]|Access[1];

public function main() returns error? {
    json[] p = ["public"];
    FunctionAccess f = check p.cloneWithType();
    io:println(f);
}
```

fails at runtime:
```
error: {ballerina/lang.value}ConversionError {"message":"'json[]' value cannot be converted to '($anonType$_3[0]|$anonType$_3[1])': ambiguous target type"}
```

**Comment by MaryamZi** [comment]
Seems to have been fixed on the update 1 patch branch. Prints `["public"]` as expected.

**Comment by manuranga** [comment]
Thanks for testing this.

Is there a build on [ballerina-distribution/actions](https://github.com/ballerina-platform/ballerina-distribution/actions) where I can download a update 1 patch pack?

**Comment by MaryamZi** [comment]
> Thanks for testing this.
> 
> Is there a build on [ballerina-distribution/actions](https://github.com/ballerina-platform/ballerina-distribution/actions) where I can download a update 1 patch pack?

I don't think there is, I checked with a pack I had built locally. cc @malinthar @keizer619

**Comment by warunalakshitha** [comment]
This should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/36199

**Comment by keizer619** [comment]
> Thanks for testing this.
> 
> Is there a build on [ballerina-distribution/actions](https://github.com/ballerina-platform/ballerina-distribution/actions) where I can download a update 1 patch pack?

We have recently introduced nightly for 2201.0.x and 2201.1.x as well
So there will be following nightly builds. 
 - [Daily (master)](https://github.com/ballerina-platform/ballerina-distribution/actions/workflows/daily-build.yml )
 - [Daily 2201.1.x](https://github.com/ballerina-platform/ballerina-distribution/actions/workflows/daily-build-2201.1.x.yml)
 - [Daily 2201.0.x](https://github.com/ballerina-platform/ballerina-distribution/actions/workflows/daily-build-2201.0.x.yml)

Each builds archive the distributions and publish them into docker hub under nightly, nightly-2201.0.x and nightly-2201.1.x tags
