### ISSUE TITLE
Function signatures of dependently typed functions are not correct in completions, hover and signature help

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36616]
**Description:**
Consider `array:map()` and `array:reduce()` functions.

**Completions**
![Screenshot from 2022-06-20 07-49-26](https://user-images.githubusercontent.com/11285165/174514300-e5fc9e5f-de19-4fd8-8ae9-1182f4407feb.png)
![Screenshot from 2022-06-20 07-48-48](https://user-images.githubusercontent.com/11285165/174514292-0d0891c5-fac1-4d28-b46a-1851a7c3e618.png)

**Signature Help**
![Screenshot from 2022-06-20 07-49-02](https://user-images.githubusercontent.com/11285165/174543673-7c49ecd6-5bc2-468b-b121-bc00425b0345.png)

Those function signatures doesn't reflect the parameters of the function type parameters required by those functions.

**Steps to reproduce:**
See description

**Affected Versions:**
2201.1.1-SNAPSHOT

**Comment by LakshanWeerasinghe** [comment]
This issue is blocked by #37123.

**Comment by LakshanWeerasinghe** [comment]
After the fixes made for the issue #37123 now the signatures are suggesting correctly.


<img width="838" alt="Screenshot 2022-10-21 at 10 55 48" src="https://user-images.githubusercontent.com/46857198/197118994-e2c18fa7-26e3-4b18-bbbe-c51674d5349e.png">

**Comment by IMS94** [comment]
@LakshanWeerasinghe Awesome.. @dulajdilshan is there a way we can improve the `array:Type val` (parameter of the function parameter)? Because we know the type `arr` and we should replace `arrray:Type` with the member type of the array. It will be a good addition if we can do so.

If SemanticAPI isn't able to, we should try that in LS side.

**Comment by LakshanWeerasinghe** [comment]
After using selecting this completion item, when user get the `function` Snippet suggested by us it is suggesting something this.
```
arr.'map(function (array:Type t) returns array:Type1 {
        return ;
    })
```
IMO if we improve this snippet it will be more useful to the user.
```
arr.'map(function (string  a) returns string {
        return a;
    })
```
WDYT @IMS94?

**Comment by IMS94** [comment]
@LakshanWeerasinghe this is very useful. +1. Shall we create an issue for this and track that?

**Comment by dulajdilshan** [comment]
> @LakshanWeerasinghe Awesome.. @dulajdilshan is there a way we can improve the `array:Type val` (parameter of the function parameter)? Because we know the type `arr` and we should replace `arrray:Type` with the member type of the array. It will be a good addition if we can do so.
> 
> If SemanticAPI isn't able to, we should try that in LS side.
> 
> @mohanvive WDYT?

It seems like, the type-param is not resolved correctly. Need to have a look in Semantic API level

**Comment by sanjana** [comment]
Checked and applied a fix in the `TypeParamResolver` in the `Semantic API`. 
The return type of the type ref is set with the bounded type. The function parameters needs to be checked and fixed in invokable type symbols.
