### ISSUE TITLE
--dump-graph prints missing dependencies in the dependency graph

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#36611]
**Description:**

The command `--dump-graph` prints the transitive dependencies that are missing.
Say we have a dependency A->B->C. We are trying to build the package `A`. `B` is prebuilt and available. `C` is not available to the user remotely or locally. 
In the `ResolutionEngine` the dependency graph initially contains `C` as well. However, since `C` is unresolved, it is removed from the graph later. But the flag `--dump-graph` prints the graph that prior to the removal of the node related to missing dependency `C`. 

**Steps to reproduce:**
1. Create package C and publish it to local repository.
2. Create package B that has C as a dependency,  and publish it to local repository.
3. Remove package C from the local repository.
4. Create package A that has B as a dependency. (A-> B-> C)
5. Try building A with `bal build --dump-graph`.

(The graph should contain only A, B. But it contains C as well)

**Affected Versions:**

**OS, DB, other environment details and versions:**
MacOS

**Comment by azinneera** [comment]
We record all dependencies on the raw graph (the graph object that is used to print the dot graph to the console) on purpose. This is to make troubleshooting easy. As an improvement, we can add an attribute such as `unresolved=true` to show that a particular dependency was not resolved
