### ISSUE TITLE
The `create variable and check error` code action return error in union type

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#36623]
**Description:**

$subject. Although it adds the `check` keyword still the return union type contains the error.

Current return type : `stream<byte[], io:Error?>|http:ClientError`
Expected return type: `stream<byte[], io:Error?>`

Refer to the below video.

**Steps to reproduce:**

https://user-images.githubusercontent.com/16300038/174652602-fe5007d2-8ec9-44db-a7ab-5cbc52bd9307.mov

**Affected Versions:**

bal -v
Ballerina 2201.1.0 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.9

VSCode plugin : V3.0.1

**Comment by IMS94** [comment]
Checked this in 2201.1.1 and works fine. A similar issue was reported in #36194 earlier. This issue has been resolved in 2201.1.1.
![Peek 2022-07-11 22-51](https://user-images.githubusercontent.com/11285165/178321987-f4787698-0dbb-498b-8e5d-b32ae401f6d8.gif)
