### ISSUE TITLE
Type guard not working for module level vars

### ISSUE THREAD

**Issue by HirumalPriyashan** [ballerina-platform/ballerina-lang#36626]
**Description:**
$title

**Steps to reproduce:**
```bal
int? x = 10;

function needInt(int n) {
    return;
}

function main() {
    if x is int {
        needInt(x); // incompatible types: expected 'int', found 'int?'
    }
}
```

**Comment by prabushi** [comment]
There is a compilation error that comes for the above scenario as well.
```
ERROR [a.bal:(9:17,9:18)] incompatible types: expected 'int', found 'int?'
error: compilation contains errors
```
@MaryamZi Is this expected?

**Comment by MaryamZi** [comment]
Yes, narrowing happens only for parameters and local variables (see https://ballerina.io/spec/lang/master/#conditional_variable_type_narrowing).

With other variables (including module-level variables), generally we cannot guarantee that the variable will continue to be of the narrowed type within the block for which the `is` check is done.

You can assign the value to a local variable and then do the `is` check, in which case the type of the variable will be narrowed.

```ballerina
public function main() {
    int? localX = x;

    if localX is int {
        needInt(localX);
    }
}
```
