### ISSUE TITLE
Fix return type code action not working in checking action

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36639]
**Description:**
$Title

https://user-images.githubusercontent.com/46120162/174745477-12a711ca-2358-452e-99b6-b88f8c8672de.mov

**Steps to reproduce:**
```
function testFunction() {
    future<string> testFutureString = start returnString();
    string testString = check wait testFutureString;

}

function returnString() returns string {
    return "";
}
```
**Affected Versions:**
2201.1.1

**Comment by IMS94** [comment]
Checked this on master (2201.5.0-SNAPSHOT) and now the `Change return type to 'error?'` code action is shown. Therefore closing this issue.
