### ISSUE TITLE
Duplicate variables are created with the create variable code action

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#36641]
**Description:**
Consider the following scenario,

https://user-images.githubusercontent.com/61020198/174753005-355963e3-e8ab-4397-9c85-95ab2c256902.mov

Here, when we apply the code action suggested in the if statement first and then apply the create variable code action to the first function call, both code actions create variables with the same name. 

**Steps to reproduce:**
```
function createIntWithError() returns int|error {
    return 10;
}

class MyClass {

    function testFunction() {
        createIntWithError();

        if true {
            createIntWithError();
        }

    }
}
```

**Comment by malinthar** [comment]
With https://github.com/ballerina-platform/ballerina-lang/pull/37135 we have added a rename pop-up with the create variable code action. Therefore, the user can now insert an appropriate name.
