### ISSUE TITLE
Incorrect result for multiplication with out of range int

### ISSUE THREAD

**Issue by suleka96** [ballerina-platform/ballerina-lang#36648]
**Description:**
$title

**Steps to reproduce:**
```
const num1 = -2;
const  num2 = -9223372036854775807;
const int ans = num1 * num2; // ans = -2
```

**Comment by prakanth97** [comment]
The spec did not mentioned about giving compile-time error for memory overflow. 
`A module-const-decl declares a compile-time constant`. Then, we have to give compile-time error to fix this issue. 
https://ballerina.io/spec/lang/2022R1/#section_8.8 
https://ballerina.io/spec/lang/master/#section_6.23

```
const num1 = -1;
const num2 = -9223372036854775808;
const int ans = num2 / num1; // -9223372036854775808
```
This should also give memory overflow but it gives wrong value. So, the fix has to be done for `Multiplicative expression`

**Comment by pcnfernando** [comment]
We'll have to handle these as such. We already have `todo`s in these functions.
eg: https://github.com/ballerina-platform/ballerina-lang/blob/5c98c383499abcca611cd2eda52606b9eb596c30/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/ConstantValueResolver.java#L425
