### ISSUE TITLE
[LS] Service template is incomplete 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#36658]
**Description:**
In the following capture the service template for `email:ImapListener` is generated without the required method(onMessage) implementation. 

![service_temp](https://user-images.githubusercontent.com/35211477/174950212-fdbe6861-c7a7-4ffb-9bfc-b4d84164003b.gif)

**Affected Versions:**
2201.1.1-rc1

**Comment by LakshanWeerasinghe** [comment]
The required unimplemented method diagnostics are generated from the compiler plugin not from LS. In the service template generation logic it checks if there are any methods attach to the `Service` type object define by the compiler plugin. 

<img width="1139" alt="Screenshot 2022-07-15 at 13 31 56" src="https://user-images.githubusercontent.com/46857198/179181931-1f701ed9-ff98-472a-8672-b811e6ab0a40.png">

Currently there are such methods attach to the `Service` object. So when the LS retrieving the modules it won't get any required methods. So the required method snippet is not generated.

After a discussion with stdlib team, all came to a decision to minimally support a Code Action to generate those required methods. This will be now address by the stdlib team.
