### ISSUE TITLE
Improve `remove unreachable code` code action to remove multiple code lines and the leading minutiae

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36654]
**Description:**
$Title

**Describe your problem(s)**

In the current implementation, we only remove the code line with the diagnostic. However, we need to remove leading minutiae and the lines following the diagnostic code line which are also unreachable. 

https://user-images.githubusercontent.com/46120162/174942324-ae127142-95f1-4617-8c22-e4e9890cecfc.mov

**Describe your solution(s)**

The code action should remove lines 11-12. IMO we can also remove lines 9-10 since they are unreachable as well even though they are user defined.

**Comment by KavinduZoysa** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/41000
