### ISSUE TITLE
Create record code action is suggested without syntax validation

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#36674]
**Description:**
Consider the following capture. Here the `Create record` code action should not be suggested as the syntax is invalid in the context.

![create_record](https://user-images.githubusercontent.com/35211477/175047087-ce38408c-385b-4474-8889-332ae694f85a.gif)

**Steps to reproduce:**
```ballerina
type Employee record {
    readonly string name;
    int salary;
};

table<Employee> key(name) tart = table [
    { name: "John", "salary": 100},
    { name: "James", salary: 300}
];

type tValue record {
    
};

public function main() {
    table tValue = tart;
}
```
**Affected Versions:**
2201.1.1

**Comment by mindula** [comment]
Closing since this is already fixed
