### ISSUE TITLE
Changes to packages in local dependancies do not get updated in LS

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#36689]
**Description:**
If a local dependency is updated the changes will not be picked up from Language server until restart. 

**Steps to reproduce:**
1. Create a package and push it in to local repository
2. Import it from another package and start editing it in VSCode
3. Use a construct from dependent package ie. function or variable
4. Open the first package and change the identifier of the construct 
5. Re pack and push to local repository
6. Start editing the send package and the updated name will not be suggested. 

**Affected Versions:**
Ballerina 2201.1.0 (Swan Lake Update 1)
OS Ubuntu latest

**Comment by IMS94** [comment]
@hevayo in this case, did you update the package version when publishing again to the local repo?

**Comment by IMS94** [comment]
Had a discussion with @azinneera on this and this is the expected behavior. If we push a package under the same version, it will not be reloaded. If we pushed a new version and updated `Ballerina.toml` to use that version, then it will be picked up.
