### ISSUE TITLE
Missing completions in Qualified name reference context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#36718]
**Description:**
Consider the following screen capture
![image](https://user-images.githubusercontent.com/35211477/175567083-56a88714-3f4a-448f-85b7-67102b79075c.png)

**Steps to reproduce:**
```ballerina

public function name() {
    
}

decimal: <cursor>
```

**Affected Versions:**
2201.1.1-rc1

**Comment by mohanvive** [comment]
Not planning to consider this now.
