### ISSUE TITLE
Improve already providing completions in ballerina shell

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36738]
**Description:**
$Title

**Describe your problem(s)**

Currently we are providing a predefined hardcoded set of keywords as completions for any use case. Some completions are incorrect and some are missing. ex: `fail` keyword

<img width="1563" alt="Screenshot 2022-06-27 at 17 57 22" src="https://user-images.githubusercontent.com/46120162/175941491-30a5c94e-2543-4bbd-b62f-4409e62bc7d4.png">
 [check](https://github.com/ballerina-platform/ballerina-lang/blob/master/ballerina-shell/modules/shell-cli/src/main/resources/command.keywords.txt)

**Describe your solution(s)**

Get the keywords using `SyntaxInfo.keywords()` instead of hardcoding them.

**Comment by mohanvive** [comment]
Will not be prioritised as of now.
