### ISSUE TITLE
Annotations not passed for elements of a reference type

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#36747]
**Description:**
$subject

```ballerina
@Int {
    minValue: 0
}
type PositiveInt int;

type CustomInt PositiveInt;

@Array {
    maxLength: 10
}
type CustomIntArray CustomInt[];
```

```java
// ...
Type referredType = TypeUtils.getReferredType(type);
if (referredType instanceof ArrayType) {
    Type elementType = ((ArrayType) referredType).getElementType();
    // ...
}
```

<img width="463" alt="image" src="https://user-images.githubusercontent.com/9639050/176103207-97d8354b-a5a5-4f10-a600-74f8722ef9bb.png">

**Affected Versions:**
2201.2.x

**Comment by warunalakshitha** [comment]
Following stdlibs will effect with this change.

module-ballerina-serdes
module-ballerinax-kafka
module-ballerina-http
module-ballerina-mime 
io- W

module-ballerina-websocket 
module-ballerina-xmldata
module-ballerina-graphql
module-ballerina-sql
module-ballerina-protobuf -N

module-ballerina-grpc
module-ballerinax-rabbitmq
module-ballerinax-oracledb
module-ballerinax-nats
module-ballerinax-postgresql -G
