### ISSUE TITLE
Invalid change variable type code action 

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#36745]
**Description:**

https://user-images.githubusercontent.com/27485094/176089725-3584c451-c1ef-4956-94c3-36375cd5a35f.mov

**Steps to reproduce:**
```
const i = base16 `aeeecdefabcd12345567888822`;

function testFunction() {
    byte[] arr = i;
}
```
**Affected Versions:**
2201.1.1 (Swan Lake Update 1)

**Comment by IMS94** [comment]
`Reason/Complex` because the LS did not expect the `NONE` type desc kind.
