### ISSUE TITLE
Semver tool enumeration declaration unit test

### ISSUE THREAD

**Issue by prathees98** [ballerina-platform/ballerina-lang#36782]
List down the possible positive + negative unit test cases to validate semantic CLI tool enumeration declaration.
Need to implement those unit test cases for patch version verification.

split test data sets of enumeration declaration and keep separate test sets in a separate json file for sub levels like annotation , documentation , enum member , identifier , qualifier and advance enumeration declaration test cases (This is for capturing more than one changes in source code).

For an example, Remove public qualifier from a enumeration declaration.
Old code - `public enum color{
	Red,
	Blue,
	Green
}`
New code - `enum color{
	Red,
	Blue,
	Green
}`

Here the tool should identify the change in enum declaration public qualifier removal and need to suggest a appropriate version change. 

Other than that tool should identify more than one change in the code.

For an example, Remove enum member , Remove public qualifier
Old code - `public enum color{
	Red,
	Blue,
	Green
}`
New code - `enum color{
	Red,
	Blue
}`

Here tool should identify two changes and need to suggest correct version change according to that changes in the source code.

**Comment by NipunaRanasinghe** [comment]
Closing since the required test cases have already been added with a separate PR
