### ISSUE TITLE
Disable Renaming Resource Access Actions

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#36794]
**Description:**
After the changes done for the semantic API, the 
![Screenshot from 2022-06-30 13-49-48](https://user-images.githubusercontent.com/25485997/176628707-bacd9d50-fa12-4189-bf82-452dcfbb5f8d.png)

**Describe your task(s)**

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/36703

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by malinthar** [comment]
sub task of #36382
