### ISSUE TITLE
Algorithm used to search for a package in the EnvironmentPackageCache is suboptimal

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#36790]
**Description:**
The below method is used to search for a package which iterates through each entry in the package map to find the package. 

https://github.com/ballerina-platform/ballerina-lang/blob/bbc86e22edb806c7d8689d1aa645c2c08963616b/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/EnvironmentPackageCache.java#L51-L63

We can do the following improvements:
* We can improve this to have a nested map to drill down based on the org, package name, and version. 
  i.e `Map<PackageOrg, Map<PackageName, Map<PackageVersion, Package>>>`
  
  `io.ballerina.projects.internal.PackageContainer` is implemented in a similar way. Refer: https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageContainer.java

* Along with this, we can deprecate the following API: 
`public Optional<Package> getPackage(PackageId packageId)`

With this improvement we can,

- Increase scalability due to efficient retrieval and insertion operations.
- Increase the readability since packages are hierarchically organised.
- Increase maintainability.

**Comment by HamzaMateen** [comment]
I want to work on this issue, can it be assigned to me please? Thanks!

**Comment by JayPokale** [comment]
Hello, myself Jay Pokale. I am a competitive programmer. Visit my LeetCode profile: [Click Here](https://leetcode.com/JayPokale)
I want to work on this task, can you assign it to me?

**Comment by HamzaMateen** [comment]
I was actually quite excited about this one but Jay should be assigned to work on this issue because I am currently working on another issue that I am assigned regarding implementation of bcrypt functionality in Ballerina Crypto package. Thanks

**Comment by azinneera** [comment]
> I was actually quite excited about this one but Jay should be assigned to work on this issue because I am currently working on another issue that I am assigned regarding implementation of bcrypt functionality in Ballerina Crypto package. Thanks

Thank you for informing us about it @HamzaMateen. We appreciate your contribution to Ballerina.

@JayPokale Thank you for your interest. I assigned you to this issue as requested.

**Comment by JayPokale** [comment]
Hello, @azinneera I optimized the search algorithm and also created a pull request (#41479).
I signed for Contributor License Agreement.
Kindly review my pull request.

**Comment by JayPokale** [comment]
I opened PR on this
Please check #41485

**Comment by azinneera** [comment]
@JayPokale Thank you for the effort. We shall review the PR.

**Comment by keizer619** [comment]
@JayPokale Any reason to close the PR? I hope you are working on this issue

**Comment by JayPokale** [comment]
> @JayPokale Any reason to close the PR? I hope you are working on this issue

I was not able to Identify why test cases are failing. I tried to fix but not able to do it so.

**Comment by keizer619** [comment]
ok in that case shall i unassign this or are you hoping to work ?

**Comment by JayPokale** [comment]
> > > @JayPokale Any reason to close the PR? I hope you are working on this issue
> > 
> > 
> > I was not able to Identify why test cases are failing. I tried to fix but not able to do it so.
> 
> ok in that case shall i unassign this or are you hoping to work ?

Sure, you can unassign me
