### ISSUE TITLE
[Build Tools] Test Update 2

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#36806]
**Description:**

- [ ] Code coverage for packages that have a code modifier or generator compiler plugin engaged
- [ ] bal graph command   
- [ ] `include` field in Ballerina.toml

**Comment by gayaldassanayake** [comment]
Manually tested `bal graph` and `include`

**Comment by gayaldassanayake** [comment]
### `bal Graph` scenarios to test
- With no dependencies - Should show only the current module.
- With a single direct dependency - Should show the current package, the dependency and an edge between two.
- With transitive dependencies - Should show the graph with dependencies (D->E->F)
- With `--dump-graphs` flag - Should show the initial, intermidiate and final graph versions
- With non-existing dependencies (F->G, where G is non-existing) - Should show a graph with only F
- With tests included - Should have test as a separate node in the graph, and an edge from package to tests.

### `include` field 



[Examples for **bal graph** , **include** scenarios](https://docs.google.com/document/d/1bmutLh8PB_8105ItQqDI-vyVDIFn34fLS5vAxR1urCA/edit?usp=sharing)

**Comment by gayaldassanayake** [comment]
Tested code coverage for,
1. log - [Logging BBE](https://ballerina.io/learn/by-example/logging.html), [Logging with context BBE](https://ballerina.io/learn/by-example/logging-with-context.html)
2. http - [Testerina documentation - Test services and clients](https://ballerina.io/learn/test-ballerina-code/test-services-and-clients/)
3. grpc - [grpc BBE](https://ballerina.io/learn/by-example/grpc-simple.html)

**Result** - No difference in the code in the report and the original code. Line coverage as expected.

**Comment by azinneera** [comment]
> Tested code coverage for,
> 
> 1. log - [Logging BBE](https://ballerina.io/learn/by-example/logging.html), [Logging with context BBE](https://ballerina.io/learn/by-example/logging-with-context.html)
> 2. http - [Testerina documentation - Test services and clients](https://ballerina.io/learn/test-ballerina-code/test-services-and-clients/)
> 3. grpc - [grpc BBE](https://ballerina.io/learn/by-example/grpc-simple.html)
> 
gRPC doesn't have a compiler plugin AFAIK. We should check graphql and websub
> **Result** - No difference in the code in the report and the original code. Line coverage as expected.

**Comment by azinneera** [comment]
Encountered a wrong line coverage while testing code coverage with the [GraphQL Hello World BBE](https://ballerina.io/learn/by-example/graphql-hello-world.html)
Please check https://drive.google.com/file/d/16jvAX81bMrxeyFyHx-9SHG8EWChr1Len/view?usp=sharing. Had to share it in drive since the upload is failing.

**Comment by Ibaqu** [comment]
Created an issue to track : https://github.com/ballerina-platform/ballerina-lang/issues/36864

**Comment by gayaldassanayake** [comment]
Tested code coverage for graphql. Similar to discussion in the sync-up, the empty line immediately before the service definition is picked up as a missed/ hit line whereas it should be an ignored line.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/29953428/177471359-ef87c2e8-20fb-4dab-b740-ab8b735db83d.png">

No abnormal behavior noticed for websub (used [WebSub BBE](https://ballerina.io/learn/by-example/websub-webhook-sample.html) for testing)
<img width="973" alt="image" src="https://user-images.githubusercontent.com/29953428/177471250-41c0b25c-7f52-4ecb-8a1b-a91cf1783f5d.png">

**Comment by gayaldassanayake** [comment]
Tested  
- bal graph
- include field
 for `2201.2.0 RC1` for different scenarios. Shows expected behavior.
