### ISSUE TITLE
Crash in distict object type

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#36883]
**Description:**
$subject

```ballerina
public function main() {
    distinct object { int i; } _ = object { int i = 3; };
}
```

```ballerina
public function main() {
    object { int i; } x = object {
        int i = 1;
    };

    distinct object { int i; } _ = x;
}
```

Both cases are crashing.

**Affected Versions:**
Ballerina 2201.1.0

**Comment by MaryamZi** [comment]
@SasinduDilshara, this is most probably related to https://github.com/ballerina-platform/ballerina-lang/issues/36714. Can you check with your changes and add tests in the same PR if fixed?

**Comment by SasinduDilshara** [comment]
I will check
