### ISSUE TITLE
Semantic API support for ClientResourceActionNode

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#36889]
**Description:**
Consider the following scenario.
```Ballerina
client class MyClient {
      resource function post path1/[string id1]/path2/[string... ids] (string b, string... ids2) {
            
      }
}

public function test() {
      MyClient cl = new();
      cl-> /path1/[""]/path2/[""].post()
}

```
Can improve the symbol api to return  the corresponding `resource method symbol` when the ClientResourceActionNode 
  (`cl-> /path1/[""]/path2/[""].post()`) used in the `symbol()` API. 

**Steps to reproduce:**
Mentioned above

**Comment by dulajdilshan** [comment]
Requirements for language-server: https://docs.google.com/document/d/1VaBKbYQcyy279ycTCkFX8fYnJ5b3TDz9vW_1icBFjck

**Comment by dulajdilshan** [comment]
When traversing through the nodes, It seems the resource path is consist of a list of BLangLiteral nodes. Therefore, the symbol information which we can use to build the compiler API symbols is missing. 

referencing code:
``` ballerina
public function test() {
    Client cl = new ("");
    cl-> /path2/<c1>[<c2>""]/path4.post();
}
```
Cursor positions `c1>`, <c2`

Any thoughts on this @MaryamZi ?

**Comment by MaryamZi** [comment]
@rdulmina is looking into this.

**Comment by dulajdilshan** [comment]
Blocked due to https://github.com/ballerina-platform/ballerina-lang/issues/37604
