### ISSUE TITLE
Improve `Document this` code action to be suggested when a function is highlighted

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#36896]
**Description:**
$Title

**Describe your problem(s)**
When highlighted a function, we do not get `Document this` code action. 

https://user-images.githubusercontent.com/46120162/177692017-e83f254f-ed44-4edb-86fb-175f5de235e9.mov

**Describe your solution(s)**
With the support of range based code actions by https://github.com/ballerina-platform/ballerina-lang/pull/36850 we can improve document this code action to get suggested when we highlight a function.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
