### ISSUE TITLE
Calling resource path with special characters return compilation error 

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#36898]
**Description:**
When the resource path has a special characters `/admin/api/2021-10/customers.json` 
```ballerina
   resource function get admin/api/`2021\-10/'customers\.json ()  returns string {
        // logic
        return "test";
    }
```
This resource function doesn't give any compilation issue, but when we are going to call it
```ballerina
string z = check c->/admin/api/`2021\-10/'customers\.json;
```    
This gave an error message including an undefined path in the client

**Comment by rdulmina** [comment]
Fixed with  #36959
