### ISSUE TITLE
Improve create variable and check error code action to return optional error

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#36915]
**Description:**
The following scenario already contains `error` as the return type and when we apply the create variable with check error code action it adds `|error` instead of returning `error?`.

https://user-images.githubusercontent.com/61020198/177758692-7bd4ed21-a7e1-473a-887f-e1a962608d2f.mov

**Comment by LakshanWeerasinghe** [comment]
Let's consider the below scenario

```
function createIntWithError() returns int| error {
    return 10;
}

function testSome() {
        createIntWithError();
        return error("");
}
```

When we apply the create variable CA it will result below code segment.

```
function testSome() returns error? {
        int intWithError = check createIntWithError();
        return error("");
}
```

But the `return` type should be `error` rather than `error?`.
