### ISSUE TITLE
Invalid diagnostics generated by compiler 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#36920]
**Description:**
Observed $subject by a Ballerina Hackathon attendee. Consider the below example code snippet 

```ballerina
import ballerina/io;

type EmployeeFillUpSummary record {|int id;|};
xmlns "blaaa" as s;
public function abc(string inputFile) {
      do {
        //xml xmlPaylod = check io:fileReadXml(inputFile);
        io:ReadableByteChannel rbc = check io:openReadableFile(inputFile);
        io:ReadableCharacterChannel rch = new (rbc, "UTF8");
        xml payload = check rch.readXml();
        io:println("#1->", payload);
        map<EmployeeFillUpSummary> empMap={};
        EmployeeFillUpSummary[] emA = [];
        var _ = check from var x in payload/<s:FuelEvent>
            do {
                xml gallons = x/<s:gallons>;
                decimal gal  = check decimal:fromString(gallons.data().trim()); 
                xml odometer = x/<s:odometerReading>;
                int odm = check int:fromString(odometer.data().trim());  
                xml gasPrice = x/<s:gasPrice>;
                decimal gp = check decimal:fromString(gasPrice.data().trim()); 
                string empid = check x.employeeId; 
                int employeeId = check int:fromString(empid);
                io:println("2 gallons ", gallons.data(), " odometer ", odometer.data(), " gasPrice ", gasPrice.data(), " employeeId ", employeeId);
                empMap
            };
    };
}
```

Compiler produces an unknown type error  for `empMap` (which is invalid). It seems like root cause would the parser recovery logic. 

<img width="910" alt="bug2" src="https://user-images.githubusercontent.com/7523274/177813467-f4d867c9-615c-4063-9625-9c932b8b2718.png">

**Comment by mohanvive** [comment]
@lochana-chathura @rdulmina Any comments on this?

**Comment by mohanvive** [comment]
Minimal version

```
type EmployeeFillUpSummary record {|int id;|};
public function abc(string inputFile) {
    map<EmployeeFillUpSummary> empMap={};
    empMap
}
```

**Comment by lochana-chathura** [comment]
On a separate note, I think it is better if we can rearrange the diagnostic in a way, syntax errors are at the top, and then the semantics errors. Because one has to fix the syntax errors first and then only the semantics. And also if we have syntax errors, semantic errors are based on them.

**Comment by mohanvive** [comment]
> Given the code is incomplete, I think this is okay. Recovers as local-var-decl,
> 
> ```ballerina
> public function abc(string inputFile) {
>     map<EmployeeFillUpSummary> empMap = {};
>     empMap MISSING[Identifier] MISSING[;] // empMap will be treated as a type-ref
> }
> ```
> 
> At the parser level, we don't have the semantic info and we don't know `empMap` is a type-reference or a variable reference. Immediately after the user enters the `=` token next to the `empMap`, the ambiguity is resolved so the diagnostic will go away.
> 
> We can make the recovery `empMap MISSING[=] MISSING[;]`. But, it doesn't make sense to me. For example,
> 
> ```ballerina
> type T int;
>  
> public function abc(string inputFile) {
>     // option-1
>     // T will be treated as a type-ref. So no error which is correct.
>     T MISSING[Identifier] MISSING[;] 
>     
> 
>     // option-2
>     // T will be treated as variable-ref.
>     // So the compile will give "cannot assign a value to a type definition"
>     // Although the user was expecting write something like T x = 10;
>     T MISSING[=] MISSING[;]
> }
> ```
> 
> If we keep "type name starts with a capital letter" convention aside. Below is a perfectly valid code.
> 
> ```ballerina
> type empMap map<any>;
> 
> public function abc(string inputFile) {
>     empMap _ = {};  // Here empMap is a type ref. 
> }
> ```

Hmm. Lochana, sorry I won't fully agree with this. 
We should guide users accurate manner when the code is incomplete. That's the situation user need proper guidance and help. Hence we shouldn't ignore this case just because the code is incomplete (and provide incorrect diagnostics)

Just to be clear, are we saying that our diagnostics are valid only when the code is complete, and incomplete code snippets could generate invalid diagnostics? 

I do get the reason from the parser perspective, but again providing `unknown type` diagnostic is incorrect. Even if we write some random string that also gives `unknown type`, this should be something like `unresolvable symbol` or `cannot resolve symbol`.

**Comment by lochana-chathura** [comment]
Agree with your point as well. 

We can consider making recovery of foo, `foo MISSING[;]`. Then we will not have this `unknown type` error. 
Instead, the user will be given  "Invalid expression statement". That is the java behavior as well.

**Comment by lochana-chathura** [comment]
Assigned to @SasinduDilshara
