### ISSUE TITLE
Inconsistent redeclared symbol compilation error

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#36928]
**Description:**

For the below code it gives a compilation error saying redeclared symbol.
```bal
function foo() {
    int a = 2;

    var func = function (string a) returns string {
        return "hello " + a;
    };
}
```
gives
```
Compiling source
        newiss.bal
ERROR [newiss.bal:(4:26,4:34)] redeclared symbol 'a'
error: compilation contains errors
```

But if we change the order of the two statements, it is not giving the error.
```bal
function foo() {
    var func = function (string a) returns string {
        return "hello " + a;
    };

    int a = 2;
}
```

I think it should behave the same way in both cases.

**Steps to reproduce:**
Given above.

**Affected Versions:**
Ballerina 2201.1.0 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
@Nadeeshan96 This behaviour is explained in [5.9.3 Variable and identifier scoping](https://ballerina.io/spec/lang/master/#section_5.9.3). The function expr works as block scope and its parameters shadows the parent scode variable `a` in the first example. But in the second example there is no shadowing. So this behaviour is correct.
