### ISSUE TITLE
NullPointerException in HoverUtil

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#36926]
**Description:**
Hovering over the module import throws the following NullPointerException.
<img width="1102" alt="Screenshot 2022-07-08 at 10 39 43" src="https://user-images.githubusercontent.com/61020198/177921384-c3cfc78d-2380-406f-86e3-0ef49fedcbff.png">

**Steps to reproduce:**
```
import ballerina/http;

function test() {
    
}
```
Place your cursor on `http`

**Affected Versions:**
2201.2.0 (Swan Lake Update 2) `2201.2.x` branch

**Comment by IMS94** [comment]
@mindula This was resolved in another issue. Can you verify and close this issue?

**Comment by mindula** [comment]
fixed with #37816
