### ISSUE TITLE
Wrong source files picked for highlighted code coverage

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#36975]
**Description:**

For multiple module ballerina projects, there are some inconsistent behaviors observed in visualizing the highlighted code coverage. Even though, the showed number of lines covered and lines missed are correct the source files picked for html reports are sometimes incorrect. 

**Steps to reproduce:**
main.bal
```ballerina


public function main() {
    
}

public function intAdd(int a, int b) returns (int) {
    return (a + b);
}

function stringAdd(string s) returns string {
    return "Hello " + s;
}

public function floatAdd(float a, float b) returns float {
    return (a + b);
}

```
moduleA/main.bal
```ballerina

public function floatAdd(float a, float b) returns float {
    return (a + b);
}


public function intAdd(int a, int b) returns (int) {
    return (a + b);
}
```
tests/test.bal
```ballerina
import ballerina/test;
import codecov_3.moduleA;

@test:Config {}
function testStringAdd() {
    test:assertEquals(stringAdd("Ballerina"), "Hello Ballerina");
}

@test:Config {}
function testFloatAdd() {
    test:assertEquals(floatAdd(2, 5), 7.0);
}

@test:Config {}
public function testIntAdd() {
    test:assertEquals(moduleA:intAdd(3, 2), 5);
}
```
highlighted coverage report
![incorrect_codecov1](https://user-images.githubusercontent.com/35595065/178469680-93422293-ae5d-4904-85d3-6763b4d6179a.png)

![codecov2](https://user-images.githubusercontent.com/35595065/178469746-013b0d3f-ed2a-446e-9bb3-dc933da89cb1.png)

**Affected Versions:**
2201.0.x, 2201.1.x
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Ibaqu** [comment]
Closing since this has been fixed in a separate PR
