### ISSUE TITLE
Isolation does not happen within let-expr

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#36976]
**Description:**
```
A let-expr is isolated if the expression following in is isolated; a reference in that expression to a variable bound by a let-var-decl will be treated as isolated if the expression initializing the variable in the let-var-decl is isolated.
```
According to the above statement in spec, the following example should be a compile error.
```ballerina
isolated int i = 0;

isolated function foo() {
    int d = 2;
    lock {
        i = let int x = d in x; // should be an error because `d` is not isolated
    }
}
```

**Affected Versions:**
2201.1.0

**Comment by MaryamZi** [comment]
Please see https://ballerina.io/spec/lang/master/#isolated_expressions.

> If the static type of an expression is immutable, i.e. a subtype of readonly, or an isolated object, i.e. a subtype of isolated object {}, then the expression is isolated.

So in your example, the expression initializing the variable is isolated.

The following results in an error.

```ballerina
isolated int[] i = [0, 1];

isolated function foo() {
    int[] d = [2];
    lock {
        i = let int[] x = d in x; // error
    }
}
```

**Comment by KavinduZoysa** [comment]
Above example gives an error as expected.
