### ISSUE TITLE
Attach diagnostics information with JsonToRecordConverter response in addition to Ballerina code block

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-lang#36992]
**Description:**
The improvement suggestion is to attach diagnostics information which is produced in the steps of JSON value to Ballerina record conversion with the response that is being sent.

**Task Requirement**
The requirement is to, when an issue, exception or an error is found at the step of converting a JSON value to Ballerina record, those information has to be captured and sent as diagnostics to the client that calls the API. The diagnostics are generated when the JSON value is invalid, JSON value is null or in some unaccepted cases.

**Related Issues:**
[JSON Value to Ballerina Type mapping utility - refactor to map directly from value to type](https://github.com/ballerina-platform/ballerina-lang/issues/36212)

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/36963
