### ISSUE TITLE
Annotations are not visible for primitive data types in remote function parameters 

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#36991]
**Description:**
I have a remote function similar to this,

```
    remote isolated function onTextMessage(Caller caller, Data data) returns anydata {
        io:println("server on text message");
        return data;
    }
```

Input parameter `Data` type is defined as follows,

```
@constraint:String {
    length: 10
}
public type Data string;
```

This is what I see when I get the parameters from the native side. It does not contain the annotation.
<img width="953" alt="Screenshot 2022-07-14 at 11 24 50" src="https://user-images.githubusercontent.com/11239305/178910821-1e581ec9-acb3-4e52-9016-ef25c282c33b.png">

I am trying to call the constraint package's validate function to validate the incoming messages before dispatching them to the remote function. So when I call `ValueCreator.createTypedescValue(type)` from native code it creates the Typedesc without the annotation. Hence the constraint validation does not happen when I call the `validate` function in the constraint package using the `typedesc` value created by calling the `ValueCreator.createTypedescValue` function.

This is working as expected for records,

<img width="897" alt="Screenshot 2022-07-14 at 11 22 57" src="https://user-images.githubusercontent.com/11239305/178911174-a4774aa5-c715-40ac-a699-2e685cd52f93.png">

Is there a way for me to retrieve the `Data` parameter with the annotations?

**Comment by HindujaB** [comment]
Closing as the fix is added to master.
