### ISSUE TITLE
Misleading error for large integers

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#3699]
Consider the following program:
```ballerina
import ballerina.lang.system;

function main (string[] args) {
    int a = 55555555555555555555555010100807;
    system:println(a);
}
```

Error thrown is:
```
ballerina: for input string: "55555555555555555555555010100807"
```

**Comment by pubudu91** [comment]
This is similar to the case in issue #3333, where the exception name (`NumberFormatException` in this case) gives the contextual info lacking in the error message itself. Maybe we should consider adding overflow checks and wrap the `NumberFormatException` in a `BallerinaException` and give a more meaningful error message?
