### ISSUE TITLE
Graphql build has been failing intermittently in Windows

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#37009]
**Description:**
Graphql build has been failing intermittently due to getting `nil` value from string arguments.  Check the following logs to get the error log.
https://github.com/ballerina-platform/module-ballerina-graphql/runs/7189193929?check_suite_focus=true#step:4:255
https://github.com/ballerina-platform/module-ballerina-graphql/runs/7226165147?check_suite_focus=true#step:4:232

**Describe your task(s)**
Count is getting from the string argument in the file package and grapql is using this function: 
```ballerina
isolated function buildWindowsPath(string... parts) returns string|Error {
    int count = parts.length();
    ....
}
```
The build fails with the following error from the above coding: 
```ballerina
{ballerina}TypeCastError {"message":"incompatible types: '()' cannot be cast to 'long'"}
```
As per this error message, we have a chance to get this error if the value of the parts is nil. But in graphql, some values of this are hard-coded. So, there is no chance to get nil.
```ballerina
isolated function getGraphQLDocumentFromFile(string fileName) returns string|error {
    string path = check file:joinPath("tests", "resources", "documents", fileName);
    return io:fileReadString(path);
}
```
And, locally tested the Graphql package on Windows10 but couldn't reproduce this error. So, couldn't find the cause for this build failure. 

@warunalakshitha @MaryamZi  We want to know if this build is affected by any lang or runtime changes. Can you help us?

**Comment by warunalakshitha** [comment]
I am closing this since this behaviour have not seen in recently. Please reopen if you have further queries on this.
