### ISSUE TITLE
Contextually expected return type is not supported for resource methods

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#37021]
**Description:**

With the [`Allow client objects to have resource methods #36024`](https://github.com/ballerina-platform/ballerina-lang/issues/36024) improvement and the client resource access action support given in this [PR](https://github.com/ballerina-platform/ballerina-lang/pull/36959), there is a requirement to add this support to HTTP client through the following resource signature : 

```ballerina
 public type SimpleParamType boolean|int|float|decimal|string;
 public type ParamType SimpleParamType[]|SimpleParamType;
 public type TargetType typedesc<http:Response|anydata>;

 public type Params record {|
     never headers?;
     never targetType?;
     ParamType...;
 |};

 // Should be extern since the return type is dependent
 public resource function get [string ...path](map<string|string[]>? headers = (),
      TargetType targetType = <>, *Params params) returns targetType|error = external;
```

**Describe your problem(s)**

But having `targetType` as the return type is giving the following error :
```
unknown type 'targetType'
```

**Comment by rdulmina** [comment]
Fixed with  #37042
