### ISSUE TITLE
Annotations are not passed for type reference type members of union types

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#37050]
**Description:**
$subject

```ballerina
type Foo record {|
    @constraint:String {
        length: 5
    }
    string name;
|};

type Bar record {|
    @constraint:Int {
        minValue: 18
    }
    int age;
|};

@constraint:Float {
    minValue: 5.2
}
type Baz float;

public function foo() {
    Foo|Bar|Baz payload = 4.5;
    Foo|Bar|Baz|error result = constraint:validate(payload);
    // ...
}
```

![image](https://user-images.githubusercontent.com/9639050/179647308-36635a37-cc95-4f74-a239-a0d9951efc7a.png)

**Affected Versions:**
lastest master (2201.2.x)

**Comment by HindujaB** [comment]
This needs the type-reference type support for the runtime API `getMemberTypes` of union type. 
This will be addressed with the fix for https://github.com/ballerina-platform/ballerina-lang/issues/36855. 
The fix is targeted for update 3.
