### ISSUE TITLE
Client resource method does not support included record param

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#37060]
**Description:**

To support the new `client with resource methods` in HTTP, we have a requirement to have the query parameters as an included record parameter as suggested in the [docs](https://docs.google.com/document/d/1u4eT3LRRIlAKRVriA8bKnJAmCgkLR6jvTFMap-sUuzs/edit).

The following is the definition of the resource of an untyped client :
```ballerina
public type SimpleParamType boolean|int|float|decimal|string;
public type ParamType SimpleParamType[]|SimpleParamType;

public type Params record {|
    never headers?;
    never targetType?;
    ParamType...;
|};

resource function get [string ...path](map<string|string[]>? headers = (), 
       TargetType targetType = <>, *Params params) returns targetType|ClientError = external;
```

And the following client call gives an error :

```ballerina
string response = check clientEP->/foo/bar(id=1234);
```

Error : `undefined defaultable parameter 'id'`

**Comment by rdulmina** [comment]
Fixed with #37064
