### ISSUE TITLE
Getting invalid visibleSymbols when using the AbstractDocumentServiceContext.visibleSymbols()

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37073]
**Description:**
In `AbstractDocumentServiceContext.java`s `visibleSymbols()` method we filter symbols with DIagnosticStates, `DiagnosticState.VALID` and `DiagnosticState.REDECLARED`. But we get incorrect visibleSymbols and sometimes some visibleSymbols are missing. But when used `SemanticModel.visibleSymbols()`, we get the correct visibleSymbols.

We use `List<Symbol> visibleSymbols(Document sourceFile, LinePosition position, DiagnosticState... states)` method from `SemanticModel` in `AbstractDocumentServiceContext` (for uses such as `CodeActionContext`) with filters for `DiagnosticState`s where this bug occur. For the method `List<Symbol> visibleSymbols(Document sourceFile, LinePosition position)` in `SemanticModel` the visibleSymbols() works fine.

**Steps to reproduce:**
```
function testFunction(int aa) {
    int age = 5;<cur>
    age = age + 1;
    int c = 10;
}
```
get visibleSymbols at `<cur>` using `AbstractDocumentServiceContext.visibleSymbols()` and `SemanticModel.visibleSymbols()`.

Here I have filtered the visibleSymbols by SymbolKind.VARIABLE and mapped their name for easy visualisation(checked without filtering and mapping but still got the same result).

 `AbstractDocumentServiceContext.visibleSymbols()`
<img width="1159" alt="Screenshot 2022-07-20 at 11 39 50" src="https://user-images.githubusercontent.com/46120162/179911018-798666b3-0084-4c80-9772-b15182c2fd4a.png">

`SemanticModel.visibleSymbols()`
<img width="1158" alt="Screenshot 2022-07-20 at 11 40 23" src="https://user-images.githubusercontent.com/46120162/179911083-7c83d6b8-db34-4f7d-9fe4-a9ea75f39cda.png">

**Affected Versions:**
2201.2.0

**Comment by sanjana** [comment]
Verified that the `.visibleSymbols()` method works as expected in both the SemanticModel and the AbstractDocumentServiceContext (with the diagnostic states filter for variable symbols).

The issue that @gayalkuruppu has been facing is due to the visible symbols being cached in the LS once been called at:

https://github.com/ballerina-platform/ballerina-lang/blob/6bea705d66c9afdd5861ac1b6111ef840901faf7/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java#L135


Therefore, this has to be addressed in the LS at the design level.

**Comment by gayalkuruppu** [comment]
> Verified that the `.visibleSymbols()` method works as expected in both the SemanticModel and the AbstractDocumentServiceContext (with the diagnostic states filter for variable symbols).
> 
> The issue that @gayalkuruppu has been facing is due to the visible symbols being cached in the LS once been called at:
> 
> https://github.com/ballerina-platform/ballerina-lang/blob/6bea705d66c9afdd5861ac1b6111ef840901faf7/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/contexts/AbstractDocumentServiceContext.java#L135
> 
> Therefore, this has to be addressed in the LS at the design level.

For earlier use cases we get visibleSymbols for a position (example: completions, code actions) and hence cached in the context, but when analysing the  code in more depth, specially for code actions such as https://github.com/ballerina-platform/ballerina-lang/issues/36570 and also hence we are now supporting code actions for a range the implementation of `AbstractDocumentServiceContext` should be altered. For now we can get the correct visible symbols at the LS level using the `visibleSymbols` method in `SemanticModel`

**Comment by sanjana** [comment]
Reason/Other
