### ISSUE TITLE
Feature to get the name of the constant variable

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#37115]
**Description:**
```ballerina
const OPEN = "open";
```
Currently calling getName() on the constant variable results in "$anonType$_1" instead of "OPEN".
This feature is required to implement some functionality in serdes module.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment]
For the following code, 
```ballerina
import ballerina/io;
const OPEN = "open";

public function main() {
    string a = "open";
    boolean res = a is OPEN; // OPEN is passed as a Finite Type
    io:println(res);
}
```
The type is passed as a Finite type with the name `$anonType_0` from the compilation. We need to pass the proper type name to the BIR for the constant types.
