### ISSUE TITLE
Template package BALA containing source files modified by the code generators/modifiers

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#37125]
**Description:**
Pack the original source code instead of source files modified by the code generators/modifiers to the BALA if the package is a template.

**Describe your problem(s)**
A template package (say `lib`) published to central can be used to create a new package using `bal new --template lib hello` format. 

However, during the `bal pack`  execution of the `lib` template package, there might be code modifiers/ generators that edit the source files of the project. These modified source files are added to the BALA. Once a new package `hello` is created using the template package, the modified source files (not the original code) will be in `hello` package.

The packages that are not templates need to pack the modified source files inside the BALA. This is because at the compile time we only run the compiler plugins of the direct dependencies.

**Describe your solution(s)**
Pack the original source code to the BALA iff the package is a template. The new packages which use the template will get the original source code as a result. Also BALA files of packages which are not templates will continue to have the modified code.

Note: This change assumes that the template packages are not used as ordinary dependencies. 

**Related Issues (optional):**
https://github.com/wso2-enterprise/internal-support-ballerina/issues/145 - Requests to have the original source code when using templates with `bal new`.

**Suggested Labels (optional):**
Area/CLI, Team/DevTools

**Comment by gayaldassanayake** [comment]
Looping @hevayo for the approval

**Comment by hevayo** [comment]
+1 to not running code generators for template packages.
