### ISSUE TITLE
Not providing union type when there is a check expression when function has an error return type

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#37153]
**Description:**
In below scenario `testReturnType` function has a `error?` return type when we apply change return type CA it gives `string` type as the return type. But it should provide the `string|error?` union type.

https://user-images.githubusercontent.com/46857198/181437521-29ff433c-0ee1-49aa-92ce-83e643254e1f.mov

**Suggested Labels (optional):**
Area/CodeAction, Team/LanguageServer

**Comment by IMS94** [comment]
In such cases, we should check if the enclosing function has an `error` return type already. If yes, we have to union the new type with an error to create the new return type.
