### ISSUE TITLE
Gracefully handle corrupt/invalid bala files

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#37161]
**Description:**
In #37147, we get an exception when one of the bala files in the ballerina home repo is corrupted or incompatible (?). If one package fails like that, loading every other package will fail (in compilation). Can we improve this to add a diagnostic if a bala cannot be loaded and proceed with the rest?

**Steps to reproduce:**
Not sure how we can reproduce this

**Affected Versions:**
2201.1.1

**Related Issues (optional):**
#34939
#36470

**Comment by malinthar** [comment]
Same as https://github.com/ballerina-platform/ballerina-lang/issues/37147

**Comment by gayaldassanayake** [comment]
Fixed for 2201.1.x with #37218
