### ISSUE TITLE
Debugger variable values are shown after struct delcarations with xml attributes

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#3716]
I tried following sample code in the composer and according following screenshot you could variable u struct is identified but after variable p nothing has been identified. This is happening only when struct declaration has xml variable declaration, that's the reason struct U is loaded.

```
struct Person {
    string name;
    int age;
    string city;
    xml xmlVal;
}

struct User {
    string username;
    string location;
}

function main (string[] args) {
    User u = {username: "John Allen", location: "London"};
    Person p = {name: "John Allen",age: 30,city: "London", xmlVal:xml`<test>sss</test>`};
    string name = "John";
    int age = 30;
}
```
<img width="1238" alt="screen shot 2017-10-20 at 12 02 03 pm" src="https://user-images.githubusercontent.com/2918812/31807767-adee6400-b58d-11e7-8dc9-f072cd3ca1b8.png">

**Comment by pranavan15** [comment]
Not reproducible in Ballerina version 0.990.0. Hence, closing the issue.
