### ISSUE TITLE
When there is an error returning create variable with check CA not giving correct return type

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#37166]
**Description:**

Let's consider the below scenario

```
function createIntWithError() returns int| error {
    return 10;
}

function testSome() {
        createIntWithError();
        return error("");
}
```
When we apply the create variable CA it will result below code segment.

```
function testSome() returns error? {
        int intWithError = check createIntWithError();
        return error("");
}
```
But the return type should be `error` rather than `error?`.

In this case when suggesting return text it should first look at all the return statements  inside the parents function body then give the suggestion.

**Comment by IMS94** [comment]
```
function testSome() {
        createIntWithError();
        return error("");
}
```
Since here the user already has an erroneous source. We cannot/shouldn't try to fix it for him/her. Therefore LS won't be  improving this case.
