### ISSUE TITLE
Improve code actions support for optional fields, union typed fields & query expressions

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#37182]
**Description:**
In data mapper, we are planning to reuse code actions from LS side to let user fix errors appear after mapping some fields (or convert some expressions) from Data Mapper UI itself.

Example :

```ballerina

type Input record {
    string fieldIn?;
}

type Output record {
     string fieldOut;
}

function transform(Input input) returns Output => {
    fieldOut: input.fieldIn
}

```
Scenario: User maps an optional field from the input record variable to output.
UX: A link will be drawn between the input field and out put field - but since there's an error - link will be rendered in red.
      User can click on Fix Icon on link and see available code actions to fix.
      User clicks "Add type Cast" option and code gets updated.
      Error goes away.
      
Below is an screenshot of code view experience for this use case ATM.
![image](https://user-images.githubusercontent.com/1505855/182056374-902d91ae-5520-49f7-9dfd-d24be4746b44.png)

**Describe your problem(s)**

For the mentioned experience, we are in need of several other code actions initially (the list can grow if we find any other common uses cases as we move on with Data Mapper features)

1. Suggest Elvis operator as a fix for accessing optional fields - similar to provided example above.
    Currently type cast is suggested as the only fix for that use case.
    Elvis lets user define a default value which is used in most of the mapping scenarios for missing data.
    Fixed code for this use case will be similar to below.
    
![image](https://user-images.githubusercontent.com/1505855/182058467-29f4fe59-e575-43a5-a811-ad079787f159.png)

2.  Suggest converting an array to array mapping into a query expression. 

There are two cases here.

- member types of the two arrays are equal
- member types are different

When member types are equal, user won't see any errors after mapping, but still can convert that field access/name reference expression into a query expression to further process the array (filter, etc).

When member types different, there will be compiler errors and converting to query will be the only solution possible.

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment]
The convert to query expression code is tracked under #37350
