### ISSUE TITLE
Cannot infer the type of `sql:ParametrizedQuery` from `object:RawTemplate`

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#37188]
**Description:**

Consider the below code.

```
sql:ParameterizedQuery[] whereClauses = [];
whereClauses.push(` name LIKE %${name}`);

```

The above throws a compilation error as follows.

`incompatible types: expected 'ballerina/sql:1.4.1:ParameterizedQuery', found 'ballerina/lang.object:0.0.0:RawTemplate'
`

The expectation is for this to infer the type  `sql:ParametrizedQuery` from `RawTemplate`.  

I had to cast it as follows to avoid the compilation issue.
```
whereClauses.push(<sql:ParameterizedQuery>` name LIKE %${name}`);
```

**Steps to reproduce:**

**Affected Versions:**

Ballerina 2201.1.1 (Swan Lake Update 1)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Same for several other expressions:
- object constructor
- error constructor
- table constructor
- new expression
