### ISSUE TITLE
Missing change variable type code action in wait future expression

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37202]
**Description:**
Add change variable type code action does not work for `BCE2652`. Check for other missing cases as well(if available).

**Describe your problem(s)**

https://user-images.githubusercontent.com/46120162/182302591-d14d65e3-a15b-40bf-a9a5-4f3050397cd5.mov

*code*
```
function test() {
    future<int> fut = start foo(); 
    int fVal = wait fut;
}

function foo() returns int {
    return 0;
}
```

**Describe your solution(s)**
Support change variable type for `BCE2652`. Check for other missing cases as well.

**Comment by TharushiJay** [comment]
Case 2:  Missing change variable type code action for functions with inferred typedesc value (`BCE3931`)

<img width="1015" alt="Screenshot 2022-08-25 at 12 19 05" src="https://user-images.githubusercontent.com/27485094/186594736-16c80ce3-7042-4e51-b9b3-9f928364fb72.png">
