### ISSUE TITLE
Explore the possibility of using `NodeFactory` to generate syntax nodes for code actions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#37233]
**Description:**
Right now, we are using string concatenations to generate functions, variable declarations, types, etc. We can use the Syntax Tree API's `NodeFactory` to achieve that instead.

**Describe your task(s)**
See description

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
