### ISSUE TITLE
Import module with an alias if that module name is used as an alias for another module

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#37248]
**Description:**
Consider the following scenario,

https://user-images.githubusercontent.com/61020198/182763664-41323036-637b-49b0-b461-49f69022871e.mov

Here we have three modules, `module1`, `module2` and `mod3`. In module1 we have, 

```
import project.mod3;
import project.module2;

public function getCountry() returns module2:Country|mod3:Data {
    return {name: "Sri Lanka"};
}
```
When we apply the `Create variable` code action as in the recording above, `mod3` gets imported even though it is the same name used as an alias for `module1`. Instead we could import `mod3` with an alias.

**Steps to reproduce:**
```
import project.module1 as mod3;

public function testFunction1() {
    mod3:getCountry();  
}
```

**Comment by IMS94** [comment]
This scenario is an edge case with very low likelihood of occurrence. Therefore, not planning to address this issue right now.
