### ISSUE TITLE
`findCycles()` is empty when there are cyclic dependancies

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#37257]
**Description:**
This  API `packageResolution.dependencyGraph().findCycles()` returns empty set where there are cyclic dependencies. But diagnostics are shown correctly.

**Comment by nipunayf** [comment]
When there are cyclic dependencies between the modules within a package, they are identified in the module dependency graph, and not in the package resolution graph. So, when you execute `packageResolution.dependencyGraph().findCycles()`, you get the cycles between packages which is empty

**Comment by azinneera** [comment]
Closing since this is the expected behavior.
