### ISSUE TITLE
[Semantic API] Required parameter information are missing in function type symbol

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#37282]
**Description:**
Refer to the below output values of the `functionSymbol.params()` and `functionSymbol.parameters()`(deprecated) APIs on the same function type symbol. 

Note the the information related to the required parameter `path` is missing (hence showing only 3 parameters), when trying to retrieve using the `params()` API.

Also note that debugger expression evaluation feature is broken for remote method invocations due to the above issue, and therefore this is an update 2 release blocker for the debugger side.
  
## `params()` output
<img width="635" alt="Screenshot 2022-08-05 at 16 58 53" src="https://user-images.githubusercontent.com/29032600/183068681-68d8bb6f-2ea7-4cb2-8dcd-7528eebaed05.png">

## `parameters()` (deprecated API) output
<img width="780" alt="Screenshot 2022-08-05 at 16 59 13" src="https://user-images.githubusercontent.com/29032600/183068715-91c0fe9d-26cc-467d-b4e9-96e29f8c0fe6.png">

**Comment by pubudu91** [comment]
Can you provide the Ballerina code corresponding to the above case? Does `path` happen to be a path parameter?

**Comment by NipunaRanasinghe** [comment]
> Can you provide the Ballerina code corresponding to the above case? Does `path` happen to be a path parameter?

This happens when I'm trying to access the symbol of HTTP get method, using the semantic API. Please find the below code sample that can be used to reproduce the issue.
```ballerina
import ballerina/http;

public function main() returns error? {
        http:Client httpClient = check new ("https://api.github.com");
        http:Response response = check httpClient->get("/args/ballerina-platform/repos");
}
```

Also note that this issue was reproducible only in update2 rc (not in update 1 versions)

**Comment by dulajdilshan** [comment]
When debugging, it appears to be that here, we select the wrong method symbol (Check the position and the symbol of the method symbol)
![Screenshot from 2022-08-11 01-16-37](https://user-images.githubusercontent.com/25485997/184006851-fde1324f-41a0-4d20-acc8-f4d31022e6de.png)
Screen shot: `org.ballerinalang.debugadapter.evaluation.engine.action.RemoteMethodCallActionEvaluator.invokeRemoteMethod` L117
https://github.com/ballerina-platform/ballerina-lang/blob/f92e6d16548fed432f37804e3797fdfe69309097/misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/action/RemoteMethodCallActionEvaluator.java#L117-L121

The method here we select is wrong (Check the method's location). The correct symbol that we should select is the method at [275,30]. But we choose the method at [262, 23].
![Screenshot from 2022-08-11 01-22-41](https://user-images.githubusercontent.com/25485997/184007614-a641706a-4ddc-40eb-9af4-12c764a079d0.png)

Screen shot: `http_client_endpoint.bal` at `ballerina/http` module.

The solution is to correct the behaviour of `findObjectMethodInClass()` to address multiple methods with the same method name.
https://github.com/ballerina-platform/ballerina-lang/blob/f92e6d16548fed432f37804e3797fdfe69309097/misc/debug-adapter/modules/debug-adapter-core/src/main/java/org/ballerinalang/debugadapter/evaluation/engine/expression/MethodCallExpressionEvaluator.java#L252-L257

**Comment by dulajdilshan** [comment]
I think this issue happened after adding support to client resource methods to `ballerina/http`

Ref: (commit) https://github.com/ballerina-platform/module-ballerina-http/commit/47de6804b766612b5ae07203f541a65f5655b06d

- `release-2.3.0`: https://github.com/ballerina-platform/module-ballerina-http/blob/release-2.3.0/ballerina/http_client_endpoint.bal
- `master`: https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/http_client_endpoint.bal
