### ISSUE TITLE
Suggest converting an array to array mapping into a query expression

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#37350]
**Description:**
There are two cases here:

    member types of the two arrays are equal
    member types are different

When member types are equal, user won't see any errors after mapping, but still can convert that field access/name reference expression into a query expression to further process the array (filter, etc).

When member types different, there will be compiler errors and converting to query will be the only solution possible.

**Describe your problem(s)**
See description

**Related Issues (optional):**
Originally reported in #37182

**Comment by IMS94** [comment]
Here's an example of the experience users will get for this.
![Peek 2022-08-23 13-33](https://user-images.githubusercontent.com/11285165/186105366-3b3a3a4d-1294-44d5-b426-367d71e102ae.gif)

Inside the mapping constructor:
![Peek 2022-08-23 13-42](https://user-images.githubusercontent.com/11285165/186107293-35a92cb3-7cc7-4906-ab5c-3d6857c2c2f3.gif)

Note that the indentation/formatting needs to be fixed.

@kaviththiranga this experience looks ok right?

**Comment by kaviththiranga** [comment]
@IMS94 yeah, this looks promising.
