### ISSUE TITLE
Logger tests failing intermittently

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#3736]
The logger tests fail intermittently in Jenkins build. The reason for test failure is when there are two or more logging backends present in the class path. Although logging backend dependencies were excluded from the dependencies used in Ballerina, test class path used by TestNG seem to be including multiple logging backends at times. The logger tests need to be moved to the integration test suite where it'll give a more realistic testing environment.

**Comment by wggihan** [comment]
@pubudu91 Can you verify whether still this applicable with the JBallerina implementation?

**Comment by pubudu91** [comment]
Still applicable. Therefore sent PR #18492 to add an integration instead of a unit test.
