### ISSUE TITLE
Some HTTP response status messages are not returned to the user

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#3740]
When 405 status code is returned, Method Not Allowed error is displayed to the user as shown below.
![5](https://user-images.githubusercontent.com/1845370/31883152-983e3736-b806-11e7-8ab3-31f24584e3d7.png)

But, these are not shown for every status code. For example, 415 Unsupported Media Type

**Comment by pubudu91** [comment]
"Unsupported media type" is something that will have to come with MIME support right?
