### ISSUE TITLE
Incorrect completions for client resource access path

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#37416]
**Description:**
Consider the following mp4 where 

1. Adds an extra `slash` when using the completion.
2. Adds the whole path when we try to complete a path segment or resource method name

https://user-images.githubusercontent.com/26381349/185044997-911ef8ea-e5f4-45c2-bf1f-63e7c4af19e0.mp4

**Affected Versions:**
Ballerina 2201.2.0-RC1

**Comment by malinthar** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/37386

**Comment by malinthar** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/37385

**Comment by malinthar** [comment]
Closing as this is fixed with #37386
