### ISSUE TITLE
Add location to Cyclic Module Imports diagnostic

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#37438]
**Description:**
Currently the `Cyclic Module Import` (BCE2001) diagnostic does not contain a line range. Therefore it is not highlighted in vscode.
![image](https://user-images.githubusercontent.com/35211477/185302650-50fb4962-1f4e-44d7-8bd0-166942f0fe72.png)

A valid line  range of the import statement should be added in order to improve the UX

**Comment by azinneera** [comment]
The location is not added for cyclic dependencies to be consistent with cases where the cyclic dependency is formed within dependencies. Locationless diagnostics are issued on purpose and they will have the line position as (0,0) and text range as (0.0). Can we figure out a way to display these diagnostics?

What if we highlight the first/last line of the file or entire file?

**Comment by Dilhasha** [comment]
> The location is not added for cyclic dependencies to be consistent with cases where the cyclic dependency is formed within dependencies. Locationless diagnostics are issued on purpose and they will have the line position as (0,0) and text range as (0.0). Can we figure out a way to display these diagnostics?
> 
> What if we highlight the first/last line of the file or entire file?

@malinthar any thoughts?

**Comment by malinthar** [comment]
> > The location is not added for cyclic dependencies to be consistent with cases where the cyclic dependency is formed within dependencies. Locationless diagnostics are issued on purpose and they will have the line position as (0,0) and text range as (0.0). Can we figure out a way to display these diagnostics?
> > What if we highlight the first/last line of the file or entire file?
> 
> @malinthar any thoughts?

We'll have to discuss and come to a conclusion

**Comment by azinneera** [comment]
Closing according to the explanation in https://github.com/ballerina-platform/ballerina-lang/issues/37438#issuecomment-1282187448. Please reopen if you have any issues with implementing the suggested solution.
