### ISSUE TITLE
Suggesting `main()` in incorrect contexts

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37444]
**Description:**
<img width="536" alt="Screenshot 2022-08-18 at 15 14 32" src="https://user-images.githubusercontent.com/46120162/185365017-cc6fe7b7-6b87-4d68-8d0c-8aa1218c98d5.png">

<img width="566" alt="Screenshot 2022-08-18 at 15 01 19" src="https://user-images.githubusercontent.com/46120162/185365044-e99824b6-6983-4854-b2bf-eb98ef62e489.png">
 

Main method should not be suggested in these scenarios.

**Steps to reproduce:**
```
int a = 10;
<cur>

public function main() {

}
```

**Affected Versions:**
2201.2.0

**Comment by gayalkuruppu** [comment]
As per the offline discussion, came to following conclusions. 

1. Assign "Z" as a default sort text for completion items.
2. Deprioritize main() among functions (default sorting)
3. Fix sorting for module level for the scenario when we don't have anything typed in the module-level

The sorting order to be finalized:

1. Types, 
2. Qualifiers, 
3. functions/ variables 
4. module completions

**Comment by gayalkuruppu** [comment]
- _Regarding `3. Fix sorting for module level for the scenario when we don't have anything typed in the module-level`_

The `nodeAtCursor` is always identified as a non ModulePartNode except for the case where the source code is empty. The `findNode()` works to traverse the child node until the it finds a terminal node. When there is a module level declaration/ definition already in the source code, findNode ends up at one of the module level declaration/ definition and returns that particular matched node. So, we will get the nodeAtCursor as `ModulePartNode` only for the case where the source code is empty. Had an offline discussion with @rdulmina and came to a conclusion to handle these scenarios either inside `getCompletions()` or `onPrevalidation()` where we already handle for similar type of scenarios.

**Comment by rdulmina** [comment]
`findNode` API is designed to find the inner most non-terminal node encapsulating the given text range

**Comment by gayalkuruppu** [comment]
BTW @rdulmina, for the following two scenarios, findNode() returns an ExternalTreeNodeList of declared module level delns and defns. Can that be handled from the parser side? cause we don't have a completion provider for the List node(and we cannot have either since lists can have different types of child nodes. So might need a fix for findNode() for these two cases). 
```
enum testEnum {
    ONE = "1",
    TWO = "2"
}
// no completions

xmlns "www.wso2.com" as ns;
// no completions
```
