### ISSUE TITLE
Missing init function completion inside object constructor expression

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37453]
**Description:**
<img width="560" alt="Screenshot 2022-08-18 at 17 17 19" src="https://user-images.githubusercontent.com/46120162/185545519-9f20e8eb-092c-4a1d-8196-721bd9b26994.png">

**Steps to reproduce:**

**Affected Versions:**
2201.2.0

**Comment by mohanvive** [comment]
@gayalkuruppu Is this a valid requirement?

**Comment by gayalkuruppu** [comment]
> @gayalkuruppu Is this a valid requirement?

We can have init() method inside object constructor expression to initialize object fields. https://ballerina.io/spec/lang/master/#object-field
