### ISSUE TITLE
Incorrect diagnostic property in query expression

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#37450]
**Description:**
Consider the diagnostic `variable assignment is required` at cursor position.

<img width="702" alt="Screenshot 2022-08-19 at 09 29 30" src="https://user-images.githubusercontent.com/27485094/185540076-c8df2d91-ce89-4dd8-84ff-24aa499ac2b9.png">

In the diagnostic properties which is used to derive the expected type, we get the `bType` incorrectly as `xml<string>` where it should be `string[]`.

<img width="749" alt="Screenshot 2022-08-19 at 09 28 14" src="https://user-images.githubusercontent.com/27485094/185539966-efce7958-ceb0-476d-b7aa-4d837f90fdba.png">

For a different case like `x1.toBalString()`, we get the type correctly as `string` in the diagnostic properties.

**Steps to reproduce:**
```
public function main() {
    xml x1 = xml `<book>The Lost World</book>`;

    from xml element in x1 select element.toBalString();
}
```

**Affected Versions:**
2201.2.0 (Swan Lake Update 2)

**Comment by pcnfernando** [comment]
As per the spec https://ballerina.io/spec/lang/master/#section_6.35,
> If there is no contextually expected type, then the basic type of the value constructed is the basic type of expression following in; it is a compile-time error if the static type of this expression is not a subtype of one of the basic types that a query expression can construct.

The basic type the query being resolved to seem to be correct because `x1` is a XML. But the constraint comes from the select clause, which is `string` in this case. Hence the type resolved would be `xml<string>`. But since we cannot constraint XML with `string`, we should get an error saying

**Comment by SasinduDilshara** [comment]
This issue was reopened due to https://github.com/ballerina-platform/ballerina-lang/pull/40497
