### ISSUE TITLE
Type cast code action not suggested in let variable decl

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#37465]
**Description:**
Consider the following capture.
![Screenshot from 2022-08-21 19-15-32](https://user-images.githubusercontent.com/35211477/185794007-cc377c2d-1a7c-42ee-bd94-57828b0d0da8.png)

The type cast code action is not suggested as a quick fix. 

**Steps to reproduce:**
```Ballerina
function testLetVar(int x) returns float =>
    let float? x1 = x in x1 ?: 0.0;
```

**Affected Versions:**
2201.2.0-rc2

**Comment by IMS94** [comment]
@malinthar shall we send this to master and 2201.3.x?

**Comment by malinthar** [comment]
> @malinthar shall we send this to master and 2201.3.x?

Done
