### ISSUE TITLE
[VSCode] Create variable and type guard is not working correctly for io:fileReadJson

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#37462]
**Description:**
Please check the screen capture.

https://user-images.githubusercontent.com/8402398/185731060-e2748434-7c40-4b43-9e57-0ac0658cf6f3.mov

Version:
Ballerina 2201.2.0-rc2
latest VSCode plugin

**Comment by IMS94** [comment]
This gets reproduced only when there are more than 3 `/` slashes in the file path provided. Need to investigate further.

**Comment by gigara** [comment]
This is happening because of a bug in the String Splitter feature in VSCode plugin.

**Comment by malinthar** [comment]
Closing as completed with  https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/515
