### ISSUE TITLE
No compilation error when implementation not provided for a resource function

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#37490]
**Description:**
In the below code, Teacher class can be instantiated even without providing the implementation for `get name()` resource function. Instantiating Teacher class should result in a compilation error  but this code complies just fine

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Person distinct service object {
    resource function get name() returns string;
};

distinct service class Teacher {
    *Person;

    resource function get salary() returns decimal {
        return 1000.00;
    }
}

public function main() returns error? {
    Person p = getPerson();
    if p is Teacher {
        io:println("Teacher");
    }
}

function getPerson() returns Person {
    Teacher t = new;
    return t;
}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ThisaruGuruge** [comment]
@MaryamZi Can you provide an ETA for this?

**Comment by rdulmina** [comment]
@ThisaruGuruge found the issue and will send a fix ASAP

**Comment by gimantha** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/37494. Please reopen if needed
