### ISSUE TITLE
Identifier java module should only be exposed compiler and runtime

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#37514]
**Description:**
This module should not exposed to outside.

**Comment by HindujaB** [comment]
The `io.ballerina.identifier` module is currently exported to the following modules. 
- io.ballerina.lang - to create symbols with compiler APIs
- io.ballerina.runtime - decode logic for runtime usage
- io.ballerina.shell - for variable declarations in the shell
- io.ballerina.testerina.runtime - decode package name for  code-coverage, stackTrace elements
- io.ballerina.lang.runtime - decode `getStackTrace()`
- io.ballerina.lang.error - decode `stackTrace()`
- io.ballerina.cli - no usages found
- ballerina.debug.adapter.core - decode for debug display names, encode for expression evaluation
- io.ballerina.jsonmapper - escape chars for json → record conversion

Therefore, we can remove only the `io.ballerina.cli` dependency.
