### ISSUE TITLE
[Task]: Incorporate recent client object related runtime changes with the debugger

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#37548]
### Description

Due to recent runtime changes on the client objects and resource methods with https://github.com/ballerina-platform/ballerina-lang/pull/37494, the debug adaptor should also be updated to support the new runtime types introduced with the same PR.

### Labels

DevTools

**Comment by rdulmina** [comment]
Fixed with #37549
