### ISSUE TITLE
[Bug]: Types not suggested in dependently-typed function signature scenarios

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#37562]
### Description

Refer to the following. Expected to see the type `http:Response` in the completions. However it works for regular assignment cases as the following shows. 

https://user-images.githubusercontent.com/6260009/187254212-c41b7bcb-8e24-4819-b93b-7b190921cdd8.mov

### Labels

LanguageServer

**Comment by gayalkuruppu** [comment]
Can provide the completions, but that will include incorrect completions as well. With this [PR](https://github.com/ballerina-platform/ballerina-lang/pull/36789), we can sort the valid completion items on top. blocked by https://github.com/ballerina-platform/ballerina-lang/issues/36539
