### ISSUE TITLE
[New Feature]: New code action to add `returns error?` when user adds a check expression

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#37569]
### Description

$subject

```ballerina
public function main() {
    int a = check getInt();
}

function getInt() returns int|error {
    return 1;
}
```
In above case, we should suggest to add `returns error?` inside the main function

### Describe your problem(s)

See descriiption

### Labels

LanguageServer

**Comment by LakshanWeerasinghe** [comment]
This feature is already there in the `2201.2.x` branch. It has been tracked by #37153.

**Comment by mohanvive** [comment]
Closing the issue as per the above comment by @LakshanWeerasinghe .
