### ISSUE TITLE
[Question]: multiple references to a named worker as a variable reference is not allowed

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#37596]
### Description

$title

### Steps to Reproduce

Can't compile the following code, even though `io:println` statements there, are mutually exclusively supported.
```bal
import ballerina/io;

public function main() {
    worker w1 {
        
    }

    // commenting one of the below will make the code run fine.
    io:println(typeof w1); 
    io:println(<any>w1 is future);
}
``` 
gives
```
Compiling source
        issue.bal
ERROR [issue.bal:(8:23,8:25)] multiple references to a named worker 'w1' as a variable reference is not allowed
ERROR [issue.bal:(9:21,9:23)] multiple references to a named worker 'w1' as a variable reference is not allowed
error: compilation contains errors
```

### Affected Version(s)

Ballerina 2201.1.0 (Swan Lake)

### Labels

CompilerFE

**Comment by MaryamZi** [comment]
As indicated by the error, this is not allowed.

Please see https://ballerina.io/spec/lang/master/#section_7.3.2

> It is a compile-time error if for any named worker it is possible for the name of that worker to be evaluated as a variable-reference more than once for any execution of that worker. This ensures that wait operations that use just a worker-name to identify the strand to wait on cannot fail at runtime.

**Comment by Nadeeshan96** [comment]
Got it, Thanks!! Hence closing the issue.
