### ISSUE TITLE
Symbol information is missing in resource-path in ResourceAccessAction

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#37604]
When traversing through the nodes, It seems the resource path is consist of a list of BLangLiteral nodes. Therefore, the symbol information which we can use to build the compiler API symbols is missing. 

referencing code:
``` ballerina
public function test() {
    Client cl = new ("");
    cl-> /path2/<c1>[<c2>""]/path4.post();
}
```
Cursor positions `c1>`, <c2`

_Originally posted by @dulajdilshan in https://github.com/ballerina-platform/ballerina-lang/issues/36889#issuecomment-1233989668_

**Comment by rdulmina** [comment]
`BLangResourceAccessInvocation.resourceAccessPathSegments` is a list constructor expression. Hence type of each resource math segment will be `BLangExpression`

**Comment by rdulmina** [comment]
Need to decide whether we are going to add a symbol for resource path segments or let the consumers handle with the existing information.

**Comment by aneeshafedo** [comment]
When accessing the `expression` node of a `ClientResourceAccessActionNode` node via Semantic API `semanticModel.symbol(clientResourceAccessActionNode.expression())`, a `ResourceMethodSymbol` was returned. 

![image](https://user-images.githubusercontent.com/34091327/193725130-b2124be6-b405-4e16-acad-8584c4138807.png)

Is this the intended output ? The `expression node` is originally a `SimpleNameReference`. Please refer ti the below code snippet. 

```bal
http:Client fares_apiEndpoint = check new (fareAPIUrl);
fares_api:Fare fare = check fares_apiEndpoint->/fare/[flightNumber]/[flightDate].get;
```

Note : My effort is to access the display annotation of `http:Client fares_apiEndpoint = check new (fareAPIUrl)` by getting the symbol of `fares_apiEndpoint`.

**Comment by rdulmina** [comment]
This is a known issue @aneeshafedo Please refer https://github.com/ballerina-platform/ballerina-lang/issues/37977
