### ISSUE TITLE
[Bug]: Invalid behavior when rerunning failed tests in a multi-module package

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#37639]
### Description

The following misbehaviors occur when the tests across multiple modules are run with the `rerun-failed` flag.
1. When both tests have the same name in different modules, both get executed despite one being passed in the previous run.
2. Each module overwrites the `rerun_tests.json`, so rerunning failed tests only works for a single module. 

### Steps to Reproduce

1. Initialize a package and create two modules in it.
2. Create a failing and a passing test case with the same name in each package.
3. After executing the tests once, run it again with the `rerun-flag` enabled.

### Affected Version(s)

SwanLake 2201.2.0

### Labels

DevTools

**Comment by gayaldassanayake** [comment]
Fixed for the `testerina-migration` branch with https://github.com/ballerina-platform/ballerina-lang/pull/37870
