### ISSUE TITLE
[Improvement]: Resource path parameters with singleton string types should be suggested as regular resource path identifiers

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#37668]
### Description

Currently suggestion is given to `cl->/["path"].accessor;` where it should give suggestion for `cl->/path.accessor;`

![Screenshot from 2022-09-07 12-54-22](https://user-images.githubusercontent.com/26381349/188815514-c80cd292-a716-48d2-ab3c-5a4f5d615a72.png)

### Labels

LanguageServer

**Comment by nipunayf** [comment]
In the case of having a singleton resource path, LS does not provide completion after `cl -> /["path"].`. Ideally, it should provide `accessor` as the completion.
