### ISSUE TITLE
[Bug]: Incorrect suggestion for resource path parameter without param name

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#37669]
### Description

1) Gives invalid suggestion `cl->/$*.accessor;` where it should suggest `cl->/[A].accessor;`

![Screenshot from 2022-09-07 13-18-13](https://user-images.githubusercontent.com/26381349/188820839-c173895c-6359-43d9-8e90-0778bc6bd5f9.png)

2) Suggest string value of constants; Suggests `cl->/["someLongPathSegment"].accessor;` where it should suggest `cl->/[A].accessor;`

![Screenshot from 2022-09-07 13-23-01](https://user-images.githubusercontent.com/26381349/188822484-d1e4393b-ad2f-4ab1-8f5a-189cc086e60f.png)

### Labels

LanguageServer

**Comment by rdulmina** [comment]
Part two ow this issue is blocked due to #37751

**Comment by sanjana** [comment]
The second part of this would be addressed in #37849, once #37751 is completed.
