### ISSUE TITLE
[Improvement]: Improve default sorting of module level completions

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37661]
### Description

Currently the order of default sorting is,

1. Snippets
2. Keywords (`SnippetBlock.Kind.KEYWORD`, does not include basic types)
3. Module completion items
4. Type completion items (Defined types, constants, enums, records, class. Does not include basic types)
5. Rest of the completions

Here we get the basic types and service templates in the 5th category because of its symbol kind. We need to prioritise them.  

More info:

- Completion items for basic types are built by getting the hardcoded set of lang lib module names and removing the initial `lang.` part of it. 
- Service templated are created as static completion items and the kind, `StaticCompletionItem.Kind.OTHER`(not the completionItemKind)

### Describe your solution(s)

1. Prioritise basic types and service templates
2. Remove providing the completion item `import` after other declarations which is invalid

### Labels

LanguageServer

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/37444

**Comment by hasithaa** [comment]
I have proposed some suggestions here, https://github.com/ballerina-platform/ballerina-lang/pull/37658#issuecomment-1240347911.
