### ISSUE TITLE
[Bug]: When inferring type for query-exp, collections of types other than query construct types should throw an error

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#37670]
### Description

From the spec https://ballerina.io/spec/lang/master/#section_6.35:
> If there is no contextually expected type, then the basic type of the value constructed is the basic type of expression following in; it is a compile-time error if the static type of this expression is not a subtype of one of the basic types that a query expression can construct.

```ballerina
import ballerina/io;
public function main() {
    xml x = xml ``;
    var res = from xml i in x // we should get an error here incompatible types: 'xml' cannot be constrained with 'int'
    select 1;

    io:println(res is int[]); //error incompatible types: 'xml<int>' will not be matched to 'int[]'
}
```

```ballerina
public function main() {
    var res = from string i in "x"
    select 1; // atm, no errors. should be an error

    string x = res;
}
```

### Affected Version(s)

2201.2.0

### Labels

CompilerFE

**Comment by SasinduDilshara** [comment]
```
public function main() {
    var res = from string i in "xyz"
    select 1; // atm, no errors. should be an error
}
```

But isn't it better if we return `int[]` type from the above query.
It will improve the user experience.

**Comment by pcnfernando** [comment]
If the user actually needs to create an `int[]`, instead of inferring the type; the user can write the code with a contextually expected type.

``ballerina
public function main() {
    int[] res = from string i in "XYZ" //this works
    select 1;
}
```

**Comment by SasinduDilshara** [comment]
This issue reopened due to https://github.com/ballerina-platform/ballerina-lang/pull/40497

**Comment by pcnfernando** [comment]
As per https://ballerina.io/spec/lang/master/#section_6.35.10, 
A query-select-expr that constructs a mapping or stream must specify a query-construct-type of map or stream respectively.
