### ISSUE TITLE
[HTTP] Need a native function to get entity as "application/octet-stream"

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#3767]
When the content-type header is not available, entity should be consider as application/octet-stream. Hence, we need a native function that can return a blob.

**Comment by pubudu91** [comment]
Doesn't the already existing function `getBinaryPayload()` satisfy this requirement?

[https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-http/src/main/java/org/ballerinalang/net/http/nativeimpl/request/GetBinaryPayload.java](https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-http/src/main/java/org/ballerinalang/net/http/nativeimpl/request/GetBinaryPayload.java)

**Comment by shafreenAnfar** [comment]
This has been implemented.
