### ISSUE TITLE
[Bug]: Missing `resource` keyword in the completion list for client object constructor

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#37687]
### Description

After the adding of the client resource function feature `resource` keyword should added to the completion list of the client object constructor.

### Affected Version(s)

2201.2.0

### Labels

LanguageServer

**Comment by malinthar** [comment]
same  as https://github.com/ballerina-platform/ballerina-lang/issues/37687
