### ISSUE TITLE
[Task]: Create an agreement between ComilerFE team and LS team when adding diagnostics

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#37683]
### Description

Currently there is no mutual agreement on how diagnostic objects are created, what are the properties of the diagnostics objects. Because of this some of the diagnostic based code actions are created based on assumptions. This can lead to breaking the LS side features if there is any change made from the CompilerFE w.r.t to diagnostics.  

### Labels

LanguageServer

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
