### ISSUE TITLE
GraalVM Native Image Compilation for Test Command

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-lang#37690]
### Description

Have native-image generate a module wise executable for test suites when `--native` command is provided

Meeting Notes : https://docs.google.com/document/d/1d7jtQ39txIpUQ-y9aKVcboMtYAV5OFpBOgrOjExQ47c/edit#

### Labels

DevTools

**Comment by Thevakumar-Luheerathan** [comment]
Native function mocking support is added with https://github.com/ballerina-platform/ballerina-lang/pull/38890. Currently, Native function mocking supports following functionalities.

- `call()` calling another function.
- `callOriginal()` calling same function.
- `withArguments()` mock with specific arguments.
- `thenReturn()` returns a single value.
-  Mock some function from other modules(Eg: `os:getEnv()`).
