### ISSUE TITLE
[Bug]: Parser incorrectly identifies client declaration when the client-uri is a constant-reference-expr

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#37696]
### Description
Recovers correctly for `client "client-uri" as <>`

<img width="1728" alt="Screenshot 2022-09-07 at 21 20 52" src="https://user-images.githubusercontent.com/46120162/189091197-7b34ed8c-9218-4c8f-bd53-eee08e21c582.png">

[update]
This issue was created based on the following version of the spec
<img width="573" alt="Screenshot 2022-09-08 at 16 00 37" src="https://user-images.githubusercontent.com/46120162/189100393-bfc0b279-c273-46bf-a4c1-4e44d8772bf0.png">

### Steps to Reproduce

```
const string aa = "client url"
client aa as <cur1>

function name() {
    client aa as <cur2>
}
```
Try both scenarios and get the client-decl node and module-client-node. 

### Affected Version(s)

client declaration feature branch

### Labels

CompilerFE

**Comment by rdulmina** [comment]
This is because the parser doesn't support `service-uri` as `simple-const-expr`s. It only support for string literals. Need to add parsing support for `simple-const-expr` as `service-uri`.

**Comment by gayalkuruppu** [comment]
Will provide completions based on `simple-const-expr` after `client` https://github.com/ballerina-platform/ballerina-lang/issues/37688

**Comment by MaryamZi** [comment]
Closing this since the service-uri in a client-decl has been restricted to string-literal, which is also what is implemented on the client-declaration branch.

**Comment by gayalkuruppu** [comment]
Will change the completions accordingly
