### ISSUE TITLE
HTTP build fails with latest language and cache version

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#37704]
**Description:**
> Lang version : 2201.2.0-rc1-20220906-071500-fd504a0e
> Cache version : 3.2.3-20220908-194000-d581bfa

Both [master](https://github.com/ballerina-platform/ballerina-release/runs/8261583090?check_suite_focus=true) and 2.x full builds are failing at HTTP level with the following error.

```bash
> Task :http-ballerina:build
Compiling source
        ballerina/http:2.4.1
error: compilation failed: The compiler extension in package 'ballerina:cache:3.2.3' failed to complete. 
class io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode cannot be cast to class 
io.ballerina.compiler.syntax.tree.UnaryExpressionNode
 (io.ballerina.compiler.syntax.tree.FieldAccessExpressionNode and 
io.ballerina.compiler.syntax.tree.UnaryExpressionNode are in unnamed module of loader 'app')
```

Assume that following change which added to the cache causes the issue.

https://github.com/ballerina-platform/module-ballerina-cache/pull/581/files#diff-f0466409987da462f76bb18fd3edf3be477d0543256618f6ee4b676a18f84d78R119

However, the ballerina-cache package successfully builds without any issue with the latest lang version
https://github.com/ballerina-platform/module-ballerina-cache/pull/634 

**Steps to reproduce:**
Check out to https://github.com/ballerina-platform/module-ballerina-http/tree/cast-error

Build HTTP using following cmd

```
./gradlew clean build -x http-native:test -x :http-ballerina-tests:startLdapServe -x :http-ballerina-tests:stopLdapServer -x :http-compiler-plugin-tests:test -x :http-ballerina-tests:commitTomlFiles -x :http-ballerina:commitTomlFiles
```

**Affected Versions:**
HTTP version=2.4.1-SNAPSHOT

**Comment by azinneera** [comment]
We had a call (@chamil321, @NipunaMadhushan and myself) and from the full build pipeline, we observed that with the latest lang master and 2201.2.x branches, the ballerina/cache is compiling successfully when it is directly built but the same package throws a compilation error when http is built (here the ballerina/cache is a dependency of http and is compiled from sources). @gimantha any idea?

**Comment by gimantha** [comment]
> We had a call (@chamil321, @NipunaMadhushan and myself) and from the full build pipeline, we observed that with the latest lang master and 2201.2.x branches, the ballerina/cache is compiling successfully when it is directly built but the same package throws a compilation error when http is built (here the ballerina/cache is a dependency of http and is compiled from sources). @gimantha any idea?

Due to some bug fixed probably some usages of nodes could have been changed. Will have a look

**Comment by gimantha** [comment]
While validating the cache configurations, Cache Validator compiler plugin can process ballerina codes like below

```
cache:CacheConfig config = {
    capacity: cacheConfig.capacity,
    evictionFactor: cacheConfig.evictionFactor
};
```

`cacheConfig.capacity` is a FieldAccessExpressionNode. So `GetTerminalNodeValue` (https://github.com/ballerina-platform/module-ballerina-cache/pull/581/files#diff-f0466409987da462f76bb18fd3edf3be477d0543256618f6ee4b676a18f84d78R119)  method has to handle specifically the nodes it needs to process, otherwise it will try to process every node in the else block except the literals and qualifiedNamesReferences.
