### ISSUE TITLE
[Bug]: Module imported with alias is not suggested

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#37705]
### Description

Consider the following capture 
![image](https://user-images.githubusercontent.com/35211477/189478043-c0a683d1-4416-4727-b81b-4abbd5d7ca28.png)

`obj` is not suggested as a completion item

### Steps to Reproduce

```Ballerina
import ballerina/lang.'object as obj;

public function main() {
    obj
}
```

### Affected Version(s)

2201.2.0

### Related area

Editor

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/37705

**Comment by mindula** [comment]
This is fixed.

<img width="594" alt="Screenshot 2023-07-07 at 11 18 18" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/831241f3-0601-4f0c-8fb8-cb3e0298b326">
