### ISSUE TITLE
[Bug]: Single quote prefix is not added to `class` field name during autocompletion

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#37769]
### Description

$title

![autocompletion](https://user-images.githubusercontent.com/33286289/190626413-b5e16f3d-1c49-4bcc-9934-370be821ef55.gif)

### Steps to Reproduce

```bal
import ballerina/jballerina.java;

function func() = @java:Method {
    'class: ""
} external;
```

### Affected Version(s)

Ballerina 2201.2.0 (Swan Lake Update 2)
VSCode plugin version v3.0.2

### Related area

Editor

**Comment by gayalkuruppu** [comment]
Here the `RecordFieldSymbol` we get is as follows,

<img width="1132" alt="Screenshot 2022-09-30 at 11 46 27" src="https://user-images.githubusercontent.com/46120162/193203099-082db4f8-ee75-4837-a306-c7aeb2c6552c.png">

In the [PR](https://github.com/ballerina-platform/ballerina-lang/pull/38001), I have escaped the reserved keyword by manually adding a `'`, which IMO is not the best way to handle this, but to get the correct symbol name from the semantic API. WDYT? @IMS94

**Comment by IMS94** [comment]
@gayalkuruppu This is the original definition of the `java:Method` annotation's data:
```ballerina
public type MethodData record {|
    Identifier name?;
    Class 'class;
    (Class | ArrayType)[] paramTypes?;
|};
```
There we have the `'` (quote). Means that information is lost along the way. @dulajdilshan @sanjana WDYT?
