### ISSUE TITLE
[Bug]: Parameter renaming is not working for named arguments

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#37764]
### Description

$title

https://user-images.githubusercontent.com/26381349/190577007-ddb57240-426a-448f-818f-adaf73c129a3.mp4

### Related area

Editor

**Comment by IMS94** [comment]
Blocked by #37924

**Comment by LakshanWeerasinghe** [comment]
Once #38448 PR is merged will continue the work for this issue.

**Comment by LakshanWeerasinghe** [comment]
This issue will be fixed with the #38448 PR.
