### ISSUE TITLE
[Bug]: Disallow `never` type wild-card-binding-pattern

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#37857]
### Description

As per this statement mentioned in the spec `, It is an error if the type-descriptor in the typed-binding-pattern is never.`, We need to disallow `never` type wild-card-binding-pattern.

### Steps to Reproduce

```ballerina
function bar() returns never {
   panic error("Error");
}

public function main() returns error? {
   never _ = bar(); // this should be an error
}
```

### Affected Version(s)

Ballerina 2201.2.0

### Related area

-> Compilation

**Comment by ImeshBalasuriya** [comment]
This seems to be fixed. The given code snippet produces the following error message.

```
expression of type 'never' or equivalent to type 'never' not allowed here(BCE3033)
```

**Comment by KavinduZoysa** [comment]
Closing the issue because this is already fixed in U8.
