### ISSUE TITLE
[Bug]: Missing return statement not detected for on-fail clause

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#37854]
### Description

```ballerina
function foo() returns int {
    do {
        // do some stuff which can result in an error
        return 10;
        // some more code
    } on fail var e {
        error err = e;
    }
}
```
In the above, the compiler should complain about a missing return statement since there's no return value if program control transfers to the on-fail clause. 

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
May be related to https://github.com/ballerina-platform/ballerina-lang/issues/37776. cc @pcnfernando

**Comment by pcnfernando** [comment]
> May be related to #37776. cc @pcnfernando

This issue is related to code analysis where we don't consider the do-block as a branch in the execution flow. Should be a small fix. Will check
#37776 relates to bir-gen issue where the `terminators` are incorrect.
