### ISSUE TITLE
[Bug]: bal format command only works on non-default modules

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#37868]
### Description

`bal format <module_name>` command seems to be working only for the non-default modules. when the default module is provided, the command ends up with the below error message.

```error: couldn't find an existing module by the name: <module_name>```

### Steps to Reproduce

1. Create a new ballerina package with name `foo`
2. Execute `bal format foo` on the package root directory

### Related area

-> Formatter

**Comment by AzeemMuzammil** [comment]
In such scenario, the entire project has to be formatted or just the default module?
```
.
├── Ballerina.toml
├── main.bal
└── modules
    └── util
        ├── Module.md
        ├── resources
        ├── tests
         │   └── lib_test.bal
        └── util.bal
```
Say this is a project structure, `bal format` would format all bal files in the project does `bal format foo` also should behave as the same or does it should format only the `main.bal` file?

**Comment by AzeemMuzammil** [comment]
After the discussion with @NipunaRanasinghe following decisions were made on how `bal format` should work

`bal format [OPTIONS] [<package>|<source-file>]`

```
OPTIONS
    --module <moduleName>
        Format only a specific module in the Package

     --file <fileName>
        Format only a specific file in the Package
```

Consider the below package structure,
```
.
├── Ballerina.toml
├── main.bal
└── modules
    └── util
        ├── Module.md
        ├── resources
        ├── tests
        │   └── lib_test.bal
        └── util.bal
```

1. Can format either an entire Ballerina Package or a standalone Ballerina file
    `bal format testPackage`
    `bal format testFile.bal`
2. If a specific module in a package need to be formatted,
    `bal format --module util`
3. If a specific file in a package need to be formatted,
    `bal format --file main.bal`
    `bal format --file modules/util/util.bal`

**Comment by sameerajayasoma** [comment]
I assume the `bal format` and `bal format .` commands format the current package.

**Comment by AzeemMuzammil** [comment]
Yes, Both commands would format the current package.

**Comment by sameerajayasoma** [comment]
Ack. Looks good
