### ISSUE TITLE
[Bug]:  Diagnostics are not meaningful

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#37864]
### Description

Consider the attached screen capture where the shown diagnostic contains `returnType` variable name which is not available in the code. Also the shown diagnostic is not meaningful

<img width="767" alt="Screenshot 2022-09-22 at 9 57 51 PM" src="https://user-images.githubusercontent.com/1329674/191767947-e2b204d3-9416-4620-a4a3-db071b9d5284.png">

### Affected Version(s)

```
Ballerina 2201.2.0 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10
```

### Related area

-> Compilation

**Comment by gimantha** [comment]
Related https://github.com/ballerina-platform/ballerina-lang/issues/36347

**Comment by gimantha** [comment]
> Related #36347

We will address this issue as suggested in https://github.com/ballerina-platform/ballerina-lang/issues/36347#issuecomment-1265107900
