### ISSUE TITLE
Review implementations and related areas of quoted-identifiers

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#37863]

**Comment by dulajdilshan** [comment]
# Implementation

The identifier in BLangNode, the `BLangIdentifier` has two values 

- value - processed name to use in references
- originalValue - name defined by the user

In Compiler, a symbol has two values for its name

- name - represents the name we use for symbol, created using the `name` of `BLangIdentifier`
- originalName - represent the value the user has defined, created using `originalName` of `BLangIdentifier`

ScopeEntries added using symbols’ `name` as the key.

Ex:
key: symbol = `client` : `'client`

In Semantic API, we iterate through symbols in a particular scope and create BallerinaSymbol for each symbol using their `originalName` except package-symbols

[https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java#L534](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java#L534)

```java
//TODO: Fix #31808 and remove this if-check
if (symbol.getKind() == SymbolKind.PACKAGE) {
    compiledSymbol = symbolFactory.getBCompiledSymbol(symbol, name.getValue());
} else {
    compiledSymbol = symbolFactory.getBCompiledSymbol(symbol, symbol.getOriginalName().getValue());
}
```

## Note

In BPackageSymbol, `originalName` and `name` are the names defined by the user by `bal add <name>`

Even though the user defined the package alias with a quoted identifier (`’module`), in Compiler, they model it as a name that only contains the un-quoted value (`module`). Therefore, the name originally the user has defined is not getting captured. 

We need a proper protocol and convention to follow to address issues that could occur

Related Issue for Sematic API: Related Issue for Semantic API,  [https://github.com/ballerina-platform/ballerina-lang/issues/31808](https://github.com/ballerina-platform/ballerina-lang/issues/31808)

**Comment by dulajdilshan** [comment]
Q: Why has Semantic API is modeled to use the original-name (the name user defined) to use to create the Compiler API Symbols?

A: When the user retrieves the symbol she has defined, she should get what she had declared.

As an example:
If the user wants to complete the `<cursor>` with `'int` vaue, she should be suggested `'int` instead of `int` (`int` is already a keyword)
```ballerina
int 'int = 4;
int valueX = <cursor>
```

**Comment by dulajdilshan** [comment]
These facts were found in the live discussion.

[1] In Semantic API, Module symbols have their unquoted names for quoted alias (`import test.module as 'mod`), But we add the quote (`'`) in the language server implementation when we give the completions.

[2] In the latest client declaration design, since the user should be able to call `cls:client` even though the client is defined as `'client`, we have special-cased this in language-server

**Comment by gayalkuruppu** [comment]
Another case which will be tracked under the [issue](https://github.com/ballerina-platform/ballerina-lang/issues/37769)
