### ISSUE TITLE
[Task]: Change CA testing to validate all the required CAs are suggested for a given cursor position

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#37889]
### Description

Currently, when we write test case for a code action, we only check for a given cursor position the intended code action is suggested. Let's say I am writing test cases for `extract to constant` code action. I am only checking `Extract to constant` code action is suggested, I am not checking what are the other code actions need to be suggested.

example:

```
int value = <cursor>100;
``` 
In this case the Language Server suggests two code actions. `Extract to Constant` and `Extract to variable`. Let's say if we are writing test cases for `Extract to constant` code action, we are not checking `Extract to variable` code action is being suggested for the given cursor position.

This testing approach needs to be changed to check whether all the required code actions are being suggested to a given cursor position.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
