### ISSUE TITLE
[Task]: Enable `codegenCoverageTest`

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/ballerina-lang#37884]
### Description

`CodegenCodeCoverageTest.codegenCoverageTest` test will be disabled with #37553 since `ballerina-codeModifier-any-0.1.0.bala` file has to be updated. This test should be re-enabled after updating the bala file.

### Related area

-> Test Framework

### Related issue(s) (optional)

#37504

### Suggested assignee(s) (optional)

@Ibaqu

**Comment by gayaldassanayake** [comment]
While re-enabling the test case, noted that there is a bug when mapping the code coverage for files with generated code. This results in an inaccurate coverage report with lines shifted.
