### ISSUE TITLE
[Bug]: Variable and resource-access-action location are same in `simpleVar->/foo/bar[2](10, 11);`

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#37977]
### Description

```ballerina
type Person record {|
   int val1;
   int val2;
|};

client class Foo {
   resource function post foo/bar/[string id](int q1, int q2) returns Person|error {
      if q1 > q2 {
         return error("Q1 > Q2");
      }
      return {val1: q1, val2: q2};
   }

   resource function get foo/[string id](int q1, int q2) returns int {
     return q1 + q2;
   }

   resource function post bar/[string... ids](string fullname) returns string {
     return ids[0] + fullname;
   }
}

public function main() {
   Foo fooClient = new();
   Person|error wVal = <1>fooClient->/foo/bar/["3"].post(1, 2);
}
```

In Semantic API, when we try to resolve the cursor position for `fooClient` and resource-access-action node, we get the same location (`<1>`). Because of this, we cannot identify whether we should get the resource-function or the `fooClient`

### Related area

-> Compilation

**Comment by aneeshafedo** [comment]
When accessing the `expression` node of a `ClientResourceAccessActionNode` node via Semantic API `semanticModel.symbol(clientResourceAccessActionNode.expression())`, a `ResourceMethodSymbol` was returned. 

![image](https://user-images.githubusercontent.com/34091327/193725130-b2124be6-b405-4e16-acad-8584c4138807.png)

Is this the intended output ? The `expression node` is originally a `SimpleNameReference`. Please refer to the below code snippet. 

```bal
http:Client fares_apiEndpoint = check new (fareAPIUrl);
fares_api:Fare fare = check fares_apiEndpoint->/fare/[flightNumber]/[flightDate].get;
```

Note : My effort is to access the display annotation of `http:Client fares_apiEndpoint = check new (fareAPIUrl)` by getting the symbol of `fares_apiEndpoint`.

**Comment by NipunaRanasinghe** [comment]
@gimantha @rdulmina Kindly note that we are planning for the 2201.2.2 release on next week to deliver the project diagram tool (targeted for kubecon) and this is a blocker for the tool backend. Therefore is there any possibility to prioritise this fix?

**Comment by rdulmina** [comment]
@NipunaRanasinghe We r working on this

**Comment by rdulmina** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38050. Semantic analyzer changes tracked by https://github.com/ballerina-platform/ballerina-lang/issues/38055
