### ISSUE TITLE
[New Feature]: An API to replace nodes from a Syntax tree and return a new Syntax tree 

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#38054]
### Description

Currently the SyntaxTree implementation provides `SyntaxTree replaceNode(Node target, Node replacement)` 
API to replace a given node with a target node.

### Describe your problem(s)

An API to replace a given map/list of nodes with the target map/list of nodes is required

For example: `SyntaxTree replaceNode(Map<Node, Node> targetToReplacementNodeMap)` this API should update all the nodes in a post-order manner (If the map has a child node and a parent node, The Child node should be replaced before then the parent node) and need to return the modified new syntax tree.

This API is required to Generate GraphQL schema for local service variable declaration.

### Related area

-> Compilation

### Related issue(s) (optional)

Related issue:[#3317]( https://github.com/ballerina-platform/ballerina-standard-library/issues/3317)

**Comment by MaryamZi** [comment]
Closing this issue for now since we don't plan on addressing it immediately.
