### ISSUE TITLE
[New Feature]: [LS] Add `inlay hint` support

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#38065]
### Description

With LSP 3.17 `inlay hint` support has been introduced to the LSP[1].
 https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHintParams

Adding support for this in completion contexts like positional argument context would be a plus for the UX

**Comment by IMS94** [comment]
We can start in this once #38108 is done

**Comment by mindula** [comment]
For Java in intelliJ Idea, inlay hints provide information about the following code elements,

1. Inheritors
2. Related problems
3. Usages
4. Code author
5. Parameters
6. Enum constants
7. New and complex expressions
8. Inferred and external annotations

For java in vscode, only parameter information is provided under inlay hints. To provide usage counts of classes and methods, they use codeLens support and displays them as references above the class/method name.

Similarly, as a starting step we can add inlay hint support for ballerina to provide information about parameter names.
