### ISSUE TITLE
[Task]: Add spec conformance tests for regexp langlib

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#38074]
### Description

$subject

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
PR - https://github.com/ballerina-platform/ballerina-spec/pull/1222

**Comment by MaryamZi** [comment]
We are closing this issue because it is not being actively worked on. Let's reopen when we resume conformance test efforts.
