### ISSUE TITLE
[New Feature]: Provide completion and related LS support for new regex support

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38095]
### Description

Consider the following new addition to support regex:
```ballerina
 string:RegExp regex = re `[0-9a-${endChar}]`;
```
LS should support completion support etc here.

### Related area

-> Editor

**Comment by dulajdilshan** [comment]
Related discussion: https://github.com/ballerina-platform/ballerina-lang/discussions/36805

**Comment by dulajdilshan** [comment]
Compiler FE changes: https://github.com/ballerina-platform/ballerina-lang/pull/37916

**Comment by dulajdilshan** [comment]
LS requirements can be found in the comments in [RegExp KT](https://docs.google.com/document/d/10GpEjbLoh9GvXJNSpOQjnburRos3SHM9jyc_fERKdzM/edit)

**Comment by pcnfernando** [comment]
Wondering if it is possible to support `ReBaseQuantifier`, `ReSyntaxChar`, and whatever we have set of options? It shouldn't anyway be a completion. But maybe just suggestions when we do 'Ctrl + Space'?
