### ISSUE TITLE
[Bug]: `Failed to send outboundRequestMsg to the backend` error appears after enabling the Prometheus Metrics Reporter

### ISSUE THREAD

**Issue by nilushancosta** [ballerina-platform/ballerina-lang#38128]
### Description

I am trying to use the Prometheus Metrics Reporter to expose Ballerina metrics. 

My Ballerina service runs fine if I don't enable the Prometheus Metrics Reporter. But when add the `Config.toml` to enable it, run the program and send requests, I get the following error
`Failed to send outboundRequestMsg to the backend`

Furthermore, the following stack trace appears on the Ballerina service side
```
Running executable

ballerina: started Prometheus HTTP listener 0.0.0.0:9797
error: Failed to send outboundRequestMsg to the backend
	at ballerina.http.2:externExecuteClientAction(http_client.bal:224)
	   ballerina.http.2.HttpClient:get(http_client.bal:96)
	   ballerina.http.2:sendNewRequest(caching_http_caching_client.bal:371)
	   ballerina.http.2:getCachedResponse(caching_http_caching_client.bal:329)
	   ballerina.http.2.HttpCachingClient:get(caching_http_caching_client.bal:163)
	   ballerina.http.2.Client:processGet(http_client_endpoint.bal:190)
```

### Steps to Reproduce

1. Create a new project by executing `bal new` command
2. Add the following program to the `main.bal` file
```
import ballerina/http;
import ballerinax/prometheus as _;

service /srvc on new http:Listener(8090) {
    resource function get test() returns record{}|error {
        http:Client httpEp = check new (url = "https://postman-echo.com");
        record {} getResponse = check httpEp->get(path = "/get");
        return getResponse;
    }
}
```
3. Run it by executing `bal run` and send a request to `http://localhost:8090/srvc/test` - This would succeed
4. Now add a `Config.toml` file with the following configuration to enable the Prometheus metrics exporter
```
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
``` 
5. Repeat step 3 above. This time the `Failed to send outboundRequestMsg to the backend` error will be returned and the stack trace in the description will appear in the Ballerina service logs

### OS, DB, other environment details and versions

MacOS Monterey (Version 12)

Ballerina 2201.1.2 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.10

### Related area

-> Observability

**Comment by NipunaMadhushan** [comment]
This happens when we are using only metrics (without tracing). A fix will be sent regarding the issue. Meanwhile, there is a work around for this issue. User can configure the following in `Config.toml`.

```
tracingEnabled=true
tracingProvider="noop"
```
