### ISSUE TITLE
[Bug]: `$CompilationError$` is given as variable type with create variable code action

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#38149]
### Description

Consider the following scenario where we're trying to apply the create variable code action without importing the required modules,

https://user-images.githubusercontent.com/61020198/195032527-b4771425-b979-4387-8708-8ab03313de8e.mov

### Steps to Reproduce

mod3.bal
```
public type Data record {|
    
|};
```
module2.bal
```
public type Country record {
    string name;
};
```
module1.bal
```
public function getCountry() returns module2:Country|mod3:Data {
    return {name: "Sri Lanka"};
}

function callGetCountry() {
    getCountry();
}
```

### Related area

-> Editor

**Comment by gayalkuruppu** [comment]
Tried two codes snippets to reproduce the issue

1. We do not get the diagnostic at the `getStatus()` method call when the import statement is commented out
```ballerina
import ballerina/http;

function getStatus() returns http:MutualSslStatus {
    return http:PASSED;
}

function name() {
    getStatus();
}
```

2. Created a project(called `testComp`) and added two modules inside the project (`newLib` and `oldLib`)

- inside the `newLib` in the `newLib.bal` I have added following code snippet,
```ballerina
public type TestRecord record {
    int recField1 = 0;
    string recField2 = "";
};
```
- and have using that inside `oldLib` in the `oldLib.bal`
```ballerina
import testComp.newLib;

function getFunction() returns newLib:TestRecord2 {
    return {rec2Field1: 10, rec3Field2: "rec3Field2"};
}

function testFunctionFunction() {
    getFunction();
}
```
here also we do not get the diagnostic for `getFunction()`

**Comment by gayalkuruppu** [comment]
As per the offline discussion with @mindula this is reproducible only when there is a union return type for the function. Hence adding another type-descriptor worked. 

ex:

```ballerina
import ballerina/http;

function getStatus() returns http:MutualSslStatus|string {
    return http:PASSED;
}

function name() {
    getStatus();
}
`1``
