### ISSUE TITLE
[Bug]: Type reference information lost for union of object types

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-lang#38156]
### Description

$title

### Steps to Reproduce

```
public class Student {
    string name;
    public function init(string n, int i) {
        self.name = n;
    }
}

public class NonReadOnlyStudent {
    final string name;

    public function init(string n, int i, int y) {
        self.name = n;
    }
}

type StudentRef Student;
type NonReadOnlyStudentRef NonReadOnlyStudent;

type UnionRef StudentRef|NonReadOnlyStudentRef;

function testObjectTypeReferenceType() {
    UnionRef st1 = new ("John", 1234);
    string name = st1.name;
}
```
![Screenshot 2022-10-11 at 15 10 28](https://user-images.githubusercontent.com/50439067/195055791-3e71146e-f200-4703-a491-e20206d60e4c.png)

For this example, type reference information is lost for `BLangTypeConversionExpr`. 

Got the result at https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java#L5972

### Affected Version(s)

current master

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
This is fixed in 2201.3.0 rc1
