### ISSUE TITLE
[Bug]: Several Prometheus metrics and non 2xx status code labels are missing for requests that result in errors

### ISSUE THREAD

**Issue by nilushancosta** [ballerina-platform/ballerina-lang#38157]
### Description

I have the following Ballerina program which returns an HTTP 200 response when I invoke `/srvc/success` and an HTTP 500 response when I invoke `/srvc/failure` .

```
import ballerina/http;
import ballerinax/prometheus as _;

service /srvc on new http:Listener(8090) {
    resource function get success() returns string|error {
        return "successful";
    }
    resource function get failure() returns error? {
        return error("Error");
    }
}
```

I sent requests to both these paths and looked at the Prometheus metrics afterwards. There were many metrics for the requests sent to `/srvc/success`. However only 1 metric; `inprogress_requests_value` was available for the `/srvc/failure` URL. 
I was expecting to see those other metrics for the `/srvc/failure` path as well

Furthermore, Prometheus metrics have the `http_status_code_group="2xx"` label for successful requests. However even after requests result in HTTP 500 responses, a `5xx` label does not get added to metrics.

### Steps to Reproduce

1. Create a new Ballerina project and add the above code to the `main.bal` file
2. Create a `Config.toml` file and add the following
```
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
```
3. Execute `bal run` and send requests to both endpoints
```
curl localhost:8090/srvc/success
curl localhost:8090/srvc/failure
```

4. Look at the metrics that have the tag value `/srvc/success`. You will find many metrics (E.g. `requests_total_value`, `response_time_seconds_max`, `response_time_nanoseconds_total_value` etc..
```
curl localhost:9797/metrics | grep "/srvc/success"
```

5. Now check the metrics having the tag value `/srvc/failure`. Only the `inprogress_requests_value` metric will be available
```
curl localhost:9797/metrics | grep "/srvc/failure"
```

6. Also look for `2xx` and non `2xx` `http_status_code_group` labels. Although we received both HTTP 200 and HTTP 500 responses, Prometheus metrics tags only have `2xx` labels
```
curl localhost:9797/metrics | grep 2xx
curl localhost:9797/metrics | grep 5xx
```

### OS, DB, other environment details and versions

MacOS Monterey (Version 12)

Ballerina 2201.1.2 (Swan Lake Update 1)
Language specification 2022R2
Update Tool 1.3.10

### Related area

-> Observability

**Comment by NipunaMadhushan** [comment]
When I was trying to reproduce the above issue, I got an error from the source code as follows. This was occurred when I was trying to send a request for failure().

`request command: curl localhost:8090/srvc/failure`

```
Compiling source
        nipunal/issue_test:0.1.0

Running executable

ballerina: started Prometheus HTTP listener 0.0.0.0:9797
error: Error
        at nipunal.issue_test.0.$anonType$_1:$get$failure(main.bal:9)
```

**Comment by NipunaMadhushan** [comment]
When requests are sent to `localhost:8090/srvc/failure`, another server is created as `ballerina_http_svc_0`.
The trace is seems as follows in jaeger.
<img width="1440" alt="Screenshot 2022-10-28 at 17 08 43" src="https://user-images.githubusercontent.com/51471998/198579204-1982bed8-7181-48cc-85c5-ce4f5af90e86.png">
