### ISSUE TITLE
[Bug]: `No such function` Error Occurs for Functions with Default Parameters

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#38171]
### Description

The GraphQL package tests are failing due to the `No such function` error. These functions are having default parameters. Therefore, this could be related to that.

This is a blocker for 2201.3.0 release.

### Affected Version(s)

Master and 2201.3.0

### Related area

-> Runtime

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38187
