### ISSUE TITLE
[Bug]: [Project API] `document` API is throwing an exception for generated IDL client 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#38234]
### Description

I generated an IDL client and reloaded the VSCode window. When I was trying to make a change in the generated client the following exception was thrown.

![image](https://user-images.githubusercontent.com/35211477/196113923-a5ca5632-674c-47f2-a9d6-c10e0ec5949e.png)

https://github.com/ballerina-platform/ballerina-lang/blob/656430fde21a51e5c01193a72127baf670bc4efe/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/workspace/BallerinaWorkspaceManager.java#L1108

Here we are trying to invoke the `document` method and get the document for the path of the generated idl client. It throws an exception. Due to this the project can't be compiled. 

### Steps to Reproduce

Mentioned above

### Affected Version(s)

2201.3.0-stage

### Related area

-> Editor

**Comment by azinneera** [comment]
@malinthar tested the scenario with changes in and got the following output:

**Comment by azinneera** [comment]
Ideally a generated file should be in read-only mode and the user should not be able to edit it.

**Comment by malinthar** [comment]
> @malinthar tested the scenario with changes in #38118 and got the following output:
> 
> ```
> [Info  - 1:49:49 pm] Operation 'text/didChange' {fileUri: 'file:///home/user/test/idlPlugins/client_decl_test/generated/myapi/idl_client.bal'} updated
> [Info  - 1:49:51 pm] Operation 'text/didChange' {fileUri: 'file:///home/user/test/idlPlugins/client_decl_test/generated/myapi/idl_client.bal'} updated
> [Error - 1:49:55 pm] Operation 'text/completion' failed! {uri: '/home/user/test/idlPlugins/client_decl_test/generated/myapi/idl_client.bal', [17:9], error: 'Semantic Model Cannot be Empty'}
> java.lang.RuntimeException: Semantic Model Cannot be Empty
> 	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentDocImportsMap(AbstractDocumentServiceContext.java:186)
> 	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getModuleCompletionItems(AbstractCompletionProvider.java:360)
> 	at org.ballerinalang.langserver.completions.providers.AbstractCompletionProvider.getTypeDescContextItems(AbstractCompletionProvider.java:325)
> 	at org.ballerinalang.langserver.completions.providers.context.BlockNodeContextProvider.getCompletions(BlockNodeContextProvider.java:95)
> 	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:48)
> 	at org.ballerinalang.langserver.completions.providers.context.FunctionBodyBlockNodeContext.getCompletions(FunctionBodyBlockNodeContext.java:39)
> 	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:125)
> 	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:81)
> 	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:65)
> 	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:40)
> 	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:124)
> 	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:149)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> ```

@azinneera  Looping in @dulajdilshan. Semantic model seems to be empty in this scenario. Hence, can't provide completions.

**Comment by malinthar** [comment]
> Ideally, a generated file should be in read-only mode and the user should not be able to edit it. Can we add this improvement?

Yes we can restrict edits

**Comment by azinneera** [comment]
> @azinneera Tried with the fix. I still get the issue when opening the document. After it's opened, when I do a change the issue is not there.
> 
> ![image](https://user-images.githubusercontent.com/35211477/196130718-efaca511-0e92-416b-beb6-b666a3dd60f5.png)
> 
Is this document opened before issuing a compilation? Generated IDL client files are not loaded when loading the project. It is only resolved during package resolution.

**Comment by dulajdilshan** [comment]
> Ideally, a generated file should be in read-only mode and the user should not be able to edit it. Can we add this improvement?

Then we can close https://github.com/ballerina-platform/ballerina-lang/issues/38017

**Comment by malinthar** [comment]
> > @azinneera Tried with the fix. I still get the issue when opening the document. After it's opened, when I do a change the issue is not there.
> > ![image](https://user-images.githubusercontent.com/35211477/196130718-efaca511-0e92-416b-beb6-b666a3dd60f5.png)
> 
> Is this document opened before issuing a compilation? Generated IDL client files are not loaded when loading the project. It is only resolved during package resolution. The reason is because if the user has removed the IDL import, then this client module is not necessary to be loaded into the package though its there in the FS.
> 
> Won't this be fixed if the file is in read-only mode?

Let's refactor this from the LS side to prevent accessing the document before it's created

**Comment by malinthar** [comment]
Closign as fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38272
