### ISSUE TITLE
[Bug]: Invalid Add type cast code action

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#38259]
### Description

Consider the following scenario where the `Add type cast` code action is suggested, 

https://user-images.githubusercontent.com/61020198/196413664-84ef1187-b77a-4294-8930-3759929ed355.mov

Improve the code action to apply the type cast to the entire expression.

### Steps to Reproduce

```
type RecordType record {
    json|error fieldName;
};

function toString(RecordType r) {
    json|error s1 = r.fieldName;
    string s2 = s1 is json? s1.toJson() : ""; 
}
```

### Related area

-> Editor

**Comment by IMS94** [comment]
Now the type cast is being added to the middle expression (`s1.toJson()`). Therefore closing this issue.
![Peek 2023-02-08 15-45](https://user-images.githubusercontent.com/11285165/217501130-8b189799-c654-4062-b05d-ef2741e25b2b.gif)
