### ISSUE TITLE
[Bug]: Invalid cyclic error for `type A [A]`

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#38269]
### Description

Following code sample gives `invalid cyclic type reference in '[T, T]'` compile time error.

```
type A [A];     // invalid cyclic type reference in '[T, T]'
```

### Related area

-> Compilation

**Comment by prakanth97** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/39589
