### ISSUE TITLE
[Bug]: Change parameter type code action is incorrect on field accesses of a record type parameter

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38271]
### Description

Consider:
```
type Data record {|
    string? name;
|};

type OutData record {|
    string name;
|};

public function convert(Data d) returns OutData {
    string t = d.na<cursor>me
}
```
At <cursor> we get the `change parameter 'd' type to 'string'` code action. Once applied, it changed the parameter of type `Data` to `string` which leaves `d.name` field access invalid.

### Steps to Reproduce

See description

### Affected Version(s)

2201.2.2-rc1

### Related area

-> Editor

### Suggested label(s) (optional)

Team/LanguageServer

**Comment by TharushiJay** [comment]
Had an initial look at this. As per the offline discussion, concluded not to provide the code action for record fields.
