### ISSUE TITLE
[New Feature]: Allow the user to customize formatter in the VSCode 

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#38296]
### Description

The ballerina VSCode plugin allows the user to format a ballerina source file with `shift+option+F` or with the `Format Document` option of the right click menu. Improve this to allow user to customise the formatting rules.

### Examples
- Break every line over 120 characters into multiple lines.
- Add a new line before every single line comment. 

### Describe your problem(s)

The user currently cannot customise the formatting rules.

### Describe your solution(s)

Introduce a configuration file (yaml. json etc) to allow the user to override the current default configurations.

ESLint implements the same by using configuration files[1]. 

[1]. https://eslint.org/docs/latest/user-guide/configuring/configuration-files

### Related area

-> Formatter

**Comment by IMS94** [comment]
Related discussion https://github.com/ballerina-platform/ballerina-lang/discussions/28641

**Comment by sanjana** [comment]
Related issue: #28234

**Comment by chathuranga95** [comment]
**[Suggestion]**
When breaking lines which are longer than 120 characters, we can have overridable rules as used in ESLint [2], [3].
[2] https://eslint.org/docs/latest/rules/function-paren-newline
[3] https://eslint.org/docs/latest/rules/object-curly-newline

**Comment by malinthar** [comment]
I did some analysis on the issue and the following are my findings

**Requirement:**

Currently, Ballerina LS uses the `formatting` request in the `BallerinaTextDocumentService` to format a given document. Additionally, the LS has a `rangeFormatting`procedure to format a selected range. 
Currently It does not honor any formatting options specified by the user. It uses hard-corded formatting options in the formatter[1]. 

The users should be able to provide custom-values for formatting options supported by the Ballerina Formatter. 

Formatting options that are currently supported by the Ballerina Formatter [2].

```
tabSize:int = 4
wsCharacter:string = “ “
columnLimit:int = 120
lineWrapping:boolean = false
forceFormatingOptions:ForceFormatingOptions = {forceFormatRecordFileds:boolean = false} 
```

Formatting options supported by LSP4J (LS)  [3]

```
tabSize:int
insertSpaces:boolean //prefer spaces over tabs
trimtrailingWhitespace:boolean
insertFinalNewline:boolean
trimFinalNewlines:boolean
```
These formatting options can be configured as follows on VSCode.

![image](https://user-images.githubusercontent.com/35211477/236887083-c8246b9d-cbb2-4d15-9750-7733de2fc5c6.png)

Following is a sample formating request with the above settings. 

![Screenshot from 2023-05-08 19-54-12](https://user-images.githubusercontent.com/35211477/236887256-c4ff0be2-c93b-4ca1-88da-09a68306f9aa.png)


There are several problems associated with the Ballerina Formatter. 

The Ballerina Formatter only supports the `tabSize` option out of the formatting options sent by VS-Code. However, the formatting procedure implementation in the Ballerina Language Server currently does not honor the provided options. Instead it uses the default value for `tabSize (4)`.
	
There is no global formatting property in VSCode for setting the following formatting options supported by the Ballerina formatter. 

```
1.columnLimit:int = 120
2.lineWrapping:boolean = false
3. forceFormatingOptions:ForceFormatingOptions = {forceFormatRecordFileds:boolean = false}
```

Problem: The above custom formatting options supported by the Ballerina formatter should be readable by the LS either at the formatting request or LS initialization. 

Solutions: 

1. Add support for reading a config file (toml, json) which specify the custom formatting options supported by the Ballerina formatter. The config file can be read at the initialization of the LS or at the invocation of the formatting procedure.

2. Provide formatting options as initializationOptions when the LS is initialized. 

> Note: There are only five formatting options (user-configurable options) currently supported by the Ballerina formatter. The formatter can be further improved to allow other formatting options. 


[1]https://github.com/ballerina-platform/ballerina-lang/blob/4df9b3836b0020fab1e06136a28265152d30b4b3/misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter/core/FormattingOptions.java#L153

[2]https://github.com/ballerina-platform/ballerina-lang/tree/master/misc/formatter/modules/formatter-core/src/main/java/org/ballerinalang/formatter

[3]https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions

[4] https://ballerina.io/learn/style-guide/coding-conventions/

**Comment by malinthar** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/28234

**Comment by KavinduZoysa** [comment]
We can close this issue because the requirements can be done as mentioned https://ballerina.io/learn/customize-formatting/#wrapping. 
We have to create Format.toml and specify the formatting options.
