### ISSUE TITLE
[Improvement]: Refactor Diagnostic Helper in Language Server

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#38309]
### Description

The DiagnosticHelper class is used to publish diagnostics to the client side. A thread can invoke either of the following methods to publish the diagnostics. 
https://github.com/ballerina-platform/ballerina-lang/blob/3a3b15ea0f2d0af250494feb2ab31b768e3dfca8/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java#L85-L144

When there is a contention among threads, the diagnostics corresponding to the thread which gets the execution at last will be visible to the user on client(vscode).

Following is a example scenario where the diagnostics published last is outdated.

![Screenshot from 2022-10-20 13-47-20](https://user-images.githubusercontent.com/35211477/196895100-ec47f24e-d867-4dc6-a5ac-2d6846b8db3e.png)

In the quickfix option, we have a code action to generate the IDL client. When we execute it it generates files related to the IDL client inside the generated folder. 

![image](https://user-images.githubusercontent.com/35211477/196895592-78f394ff-c28d-4401-ab25-e999f0e984e8.png)

For each of this files a `didChangeWatch` is triggered from the client side and a new thread is created to compileAndPublish diagnostics. Inaddtion, at the end of the generation of files we create another thread to publish diagnostics here. 

https://github.com/ballerina-platform/ballerina-lang/blob/3a3b15ea0f2d0af250494feb2ab31b768e3dfca8/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/executors/GenerateModuleForClientDeclExecutor.java#L121

So let's assume there are 4 threads in total, there is a contention among these threads. In many occasions the thread corresponding to the  `GenerateModuleForClientDeclExecutor` wins and publish the diagnostics(which are upto datet) first. And then the threads which are corresponding to the didChangeWatch event gets the chance and publish diagnostis (which are not up to date). 

Therefore, even-though the IDL client is generated, the diagnostic `no module generated for client declaration` is still shown to the user`.

Therefore, we have to introduce a way to manage the contention. (eg: By using a cancellation approach)

**Comment by malinthar** [comment]
I investigated the example scenario related to the IDL client generation and figured out the cause for the diagnostic inconsistency. When the IDL plugin generation is successful, a Scheduled Future (https://github.com/ballerina-platform/ballerina-lang/blob/8a2031c77a29185ada545b343fcabee8797c52c1/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java#L257)  is created to publish the diagnostics of the project. Further, the files created by the IDL client generation trigger the LS procedure `DidChangedWatched` and it also creates a scheduler to publish the diagnostics. 
The latter cancels execution of the first scheduled future if it is not complete(https://github.com/ballerina-platform/ballerina-lang/blob/8a2031c77a29185ada545b343fcabee8797c52c1/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java#L253). Then it proceeds to publish the duiagnostics. However, when it attempts to obtain the compilation using `projectPair.get().project().currentPackage().getCompilation()` the thread does not complete the execution(hangs). Need to investigate more to figure out the cause.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
