### ISSUE TITLE
[Bug]: NPE for field access expression on record json field

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-lang#38328]
### Description

$title

### Steps to Reproduce

```
type FooRec1 record {
    json j;
};

public function main() returns error? {
    FooRec1 rec1 = {j: "1"};
    rec1 = {j: {k: {l: "1"}}};
    json|error val = rec1.j.k.l.p;
}
```
This is a run-time error `{ballerina}JSONOperationError` instead this result in NPE.

### Affected Version(s)

Branch 2201.2.x

### Related area

-> Compilation

**Comment by KavinduZoysa** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/38419
