### ISSUE TITLE
[New Feature]: Need a code snippet suggestion to create a transformer function 

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#38333]
### Description

A new LS suggestion should be provided to create a base expression bodied function.

### Usage
The users will be able start writing data mapping functions by using this suggestion and they can either continue complete the data mapping using the code editor or use the visual data mapper to create the transformation.

### Code snippet to be generated
```ballerina
function transform() => ();
```

**Comment by IMS94** [comment]
We can provide a snippet completion item like below
```
function <name>(<>) => (<>);
```
The `<>` areas will be placeholders (with tab completions).
