### ISSUE TITLE
[Improvement]: Improve snippet completion item of dependently typed functions

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38338]
### Description

Currently the language server suggest the genetic completion item snippet for function parameters of the dependency typed functions. As example for the `map` function in the `array` module we suggest.

```
string[] arr = [];

arr.'map(function (array:Type t) returns array:Type1 {
        return ;
    })
```

### Describe your solution(s)

Here we know the type of this array so we can improve the completion item with the correct type. So the final result would be like this.

```
string[] arr = [];

arr.'map(function (string  item) returns string {
        return item;
    })
```

**Comment by nipunayf** [comment]
The `getExpectedType` function doesn't return the type that is being resolved by the `TypeParamResolver`, and hence it returns the type of the placeholder. We require an implementation to utilize the `TypeParamResolver` in this method to provide the expected type according to the context.
https://github.com/ballerina-platform/ballerina-lang/blob/1ee26924148a958727fc511645fd3948e3854267/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/ExpectedTypeFinder.java#L903-L968
