### ISSUE TITLE
[Bug]: Backslashes in a json payload obtained from the Ballerina http:Request object are automatically escaped

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#38343]
### Steps to reproduce 

Try out the following program
```ballerina
import ballerina/http;
import ballerina/io;

service / on new http:Listener(8090) {
    resource function post .(http:Caller caller, http:Request request) returns error? {
        json payload = check request.getJsonPayload();
        io:println(payload);
        return caller->respond(http:STATUS_OK);
    }
}
``` 
Execute the following curl request by replacing the URL of your service. This includes a json payload with backslashes.
```
curl --location --request POST '<url>' --header 'Content-Type: application/json' --data-raw '{"contact_email":"some-email","order_status_url":"https:\/\/zggdgfdgd\/56207048758\/orders\/123456abcd\/authenticate?key=abcdefg"}'
```

You can see the json payload captured in Ballerina has automatically escaped backslashes. See the above log output.

**Comment by HindujaB** [comment]
This happens at the runtime `JsonParser`.

**Comment by Nadeeshan96** [comment]
Currently json payload is given as
`{"contact_email":"some-email","order_status_url":"https://zggdgfdgd/56207048758/orders/123456abcd/authenticate?key=abcdefg"}`

**Comment by Nadeeshan96** [comment]
Closing the issue as the current behaviour is correct.
