### ISSUE TITLE
[Bug]: "cannot create new error value" error when the error type reference in the error constructor is loaded via the BIR

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38346]
### Description

$title.

Workaround is to use the type in the contextually-expected type.

### Steps to Reproduce

maryam/myproj

```ballerina
public type E1 distinct error;

public type E2 distinct (E1 & error<record {|anydata body;|}>);
```

Usage

```ballerina
import maryam/myproj;

public function main() {
    myproj:E2 e = error("", body = ""); // OK
    error e2 = error myproj:E2("", body = ""); // compilation error: cannot create a new error value from 'myproj:E2'
}
```

### Affected Version(s)

2201.2.1
2201.3.0-SNAPSHOT

### Related area

-> Compilation

**Comment by Nadeeshan96** [comment]
Refer the duplicate issue https://github.com/ballerina-platform/ballerina-lang/issues/39542 for more information.
