### ISSUE TITLE
[Bug]: Defining an integer variable with minimum allowed int value gives compilation error in master

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#38392]
### Description

Value out of range error for `-9223372036854775808`. It's observed in master. 

### Steps to Reproduce

```ballerina
public function main() {
    int i = -9223372036854775808;
}
```
64 bits two's complement representation of integer values should include `-9223372036854775808`

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
This is not a bug.

`-9223372036854775808` is a unary expression (`-L`), and `L` here is out of range for `int`.

You can use `int:MIN_VALUE` or `-9223372036854775807 - 1` instead.

This was incorrectly allowed previously (https://github.com/ballerina-platform/ballerina-lang/issues/32577).
