### ISSUE TITLE
[Debugger] Does not show value of exceptions

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#3840]
please refer https://github.com/ballerinalang/composer/issues/1110 for more details

**Comment by pranavan15** [comment]
Closing this issue as the `try-catch` and the `exception` concepts are now removed. Further, current debugger frames able to show the `error` value with the corresponding message. Check the below screenshot.

![debugger](https://user-images.githubusercontent.com/15685415/49859979-dd4bb380-fe1e-11e8-9ad8-8eb1d7dd4dc2.png)

**Comment by Shan1024** [comment]
Closing the issue since it is resolved.
