### ISSUE TITLE
[Bug]: No suggestions in certain contexts for constructs from modules generated for client declarations

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38400]
### Description

$title. E.g., suggestions are available in the body of a function but not in parameters.

- function body

![client_decl_body](https://user-images.githubusercontent.com/8376983/197953736-ac8ef7d2-e276-4bb8-868d-122e198fd45f.png)

- function parameter

![client_decl_params](https://user-images.githubusercontent.com/8376983/197953748-835bdbad-8875-43e0-9fc2-4896851f8e57.png)

### Steps to Reproduce

```ballerina
client "https://raw.githubusercontent.com/ballerina-platform/openapi-connectors/main/openapi/openweathermap/openapi.yaml" as weather;

function fn(weather:) {

}
```

### Affected Version(s)

2201.3.0-RC1

### Related area

-> Editor

**Comment by malinthar** [comment]
Sub task of #38400

**Comment by malinthar** [comment]
Closing as the IDL feature is deprioritized

**Comment by IMS94** [comment]
Closing this since the IDL client feature was removed
