### ISSUE TITLE
[Bug]: Generated modules are suggested to users

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38423]
### Description

At least for modules generated for client declarations we shouldn't suggest importing the module.

### Steps to Reproduce

```ballerina
client "openapi.yaml" as weather;

public function main() {
    wea<cursor>
}
```

![client_decl](https://user-images.githubusercontent.com/8376983/198215835-9b267606-d324-43ea-bc88-707804eab940.png)

### Affected Version(s)

2201.3.0-RC1

### Related area

-> Editor

**Comment by IMS94** [comment]
Closing this since the IDL feature was removed
