### ISSUE TITLE
[Bug]: Giving success message even if the client module is not generated

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38451]
### Description

When user execute the `Generate module for client declaration` code action with not having the specified `yml` file it will give success message and won't generate any modules either.

### Steps to Reproduce

1. Create ballerina project
2. Add yaml file named `openapi.yml` to its root 
3. Add this code snippet to the main.bal file
```
client "openapi.yaml" as weather;

public function main() {
}
```
4. Execute the code action.

https://user-images.githubusercontent.com/46857198/198582418-4465727c-39a6-4c71-b2eb-809f14315011.mov

### Related area

-> Editor

**Comment by IMS94** [comment]
Closing this since the IDL feature was reverted
