### ISSUE TITLE
[Bug]: After deleting the generated client the diagnostic is not showing for client declaration  

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38452]
### Description

When user deletes a already created generated module, the editor is not showing the diagnostic `no module generated for the client declaration (BCE4040)`.

### Steps to Reproduce

1. Create a ballerina project
2. Add yaml file named `openapi.yml` to its root 
3. Add this code snippet to the main.bal file
```
client "openapi.yml" as weather;

public function main() {
}
```
4. Execute the code action.
5. Delete the generated module.
6. Make source code change.

https://user-images.githubusercontent.com/46857198/198583318-ab6051e0-7665-4a1e-b9e0-86a16e7c41cf.mov

### Affected Version(s)

2201.3.0-RC1

### Related area

-> Editor

**Comment by azinneera** [comment]
This is a known limitation for module deletion in Project API. The same behavior exists for user-added modules as well. The project should be reloaded upon module deletion.

**Comment by malinthar** [comment]
> This is a known limitation for module deletion in Project API. The same behavior exists for user-added modules as well. The project should be reloaded upon module deletion.

@azinneera Normally, the users may change the  `openapi` spec frequently. After changing they might delete the generated module and expect the `diagnostic` and subsequently the `codeaction` to re-generate the module. So, having to reload each time they make a change to the spec may be bad in terms of the UX. IMO, better if we can prioritize this and add fix for this ASAP. WDYT?

**Comment by azinneera** [comment]
> > This is a known limitation for module deletion in Project API. The same behavior exists for user-added modules as well. The project should be reloaded upon module deletion.
> 
> @azinneera Normally, the users may change the `openapi` spec frequently. After changing they might delete the generated module and expect the `diagnostic` and subsequently the `codeaction` to re-generate the module. So, having to reload each time they make a change to the spec may be bad in terms of the UX. IMO, better if we can prioritize this and add fix for this ASAP. WDYT?

Changing the spec file will invalidate the loaded module and so during the next edit, the `no module generated` diagnostic will be shown. This will only happen if the user deletes the generated directory which again during the next edit, the diagnostic will be shown. IMP, this would suffice for now.

**Comment by Dilhasha** [comment]
Not applicable since client declaration is not supported anymore.
