### ISSUE TITLE
[Bug]: Change type code action gives incorrect results for IDL client object initialization expression

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38466]
### Description

When user tries to change the variable type after declaration of a client object, the change the variable type code action will provide incorrect result.

https://user-images.githubusercontent.com/46857198/198949606-23a6196c-5f1c-4756-95a1-ee8b1b455ec6.mov

### Steps to Reproduce

1. Create a ballerina project
2. Add yaml file named `openapi.yml` to its root 
3. Add this code snippet to the main.bal file
```
client "openapi.yml" as weather;

public function main() {
  weather:client cl = new({}, "");
}
```
4. Keep the cursor inside new keyword. (n<cursor>ew)
5. Execute the change variable type code action.

### Affected Version(s)
2201.3.0-RC1

_No response_

### Related area

-> Editor

**Comment by malinthar** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38506

![idl-client](https://user-images.githubusercontent.com/35211477/200511730-fcdb1392-f13c-49bd-9301-f6fb1d9f6d57.gif)

**Comment by malinthar** [comment]
PR to master https://github.com/ballerina-platform/ballerina-lang/pull/38507

**Comment by malinthar** [comment]
Closing this as IDL feature is deprioritized

**Comment by IMS94** [comment]
Closing this since the IDL client feature was reverted
