### ISSUE TITLE
[Bug]: Extract to local var and extract to local function gives incorrect results when extracting IDL client new expression

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38467]
### Description

After user declaring IDL client object as a local variable and try to execute the `extract to local variable` or `extract to function` code actions it will provide incorrect results.

https://user-images.githubusercontent.com/46857198/198950647-66844386-24ea-477d-b67f-b9f3fa521e25.mov

### Steps to Reproduce

1. Create a ballerina project
2. Add yaml file named `openapi.yml` to its root 
3. Add this code snippet to the main.bal file
```
client "openapi.yml" as weather;

public function main() {
  weather:client cl = check new({}, "");
}
```
4. Keep the cursor inside new keyword. (n<cursor>ew)
5. Execute the `extract to function` and `extract to local variable` code actions.

### Affected Version(s)

2201.3.0-RC1

### Related area

-> Editor

**Comment by malinthar** [comment]
Related issue #38466

**Comment by IMS94** [comment]
Closing this since the IDL client feature was reverted
