### ISSUE TITLE
[Bug]: "bal init ." can result in invalid package name

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#38473]
### Description

When I run `bal init .` it will create a package with "." as the package name. This will result in a package where most of the tooling will not work. We should probably validate this and not allow "." as the package name for bal init. 

Also suggest to change the help text to "Initialize a Ballerina package inside the current directory" instead of  "Create a new Ballerina package inside the current  directory" which gives a different meaning.
```
NAME
       ballerina-init - Initialize a Ballerina package inside the current directory

``` 

### Related area

-> Other Area

**Comment by ShammiL** [comment]
It was decided to redesign both `bal init` and `bal new` to improve their functionalities. The findings and suggestions for improvements can be found here, https://docs.google.com/document/d/1LqEe1vh_txv9Kv6KdAiVICkLUoUo2c6XU4LIWvrw1OE/edit?usp=sharing

**Comment by azinneera** [comment]
We decided to redesign the commands to deprecate init. Refer https://github.com/ballerina-platform/ballerina-spec/issues/1212
