### ISSUE TITLE
[Bug]: Buggy type guard creation behaviour when using create var code action for `T?` typed expressions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#38480]
### Description

Use the "Create variable and type guard" code action on `bar()` in the following program.
```ballerina
public function main() {
    bar();
}

function bar() returns Foo? {
}

type Foo error;
```

It generates the following:
```ballerina
public function main() {
    Foo? barResult = bar();
    if barResult is Foo {

    }
    if barResult is error {

    }   
}

function bar() returns Foo? {
}

type Foo error;
```
In the above, it should've generated it as follows I think:
```ballerina
if barResult is Foo {

} else {

}
```

### Affected Version(s)

2201.1.2
2201.2.1

### Related area

-> Editor

**Comment by gayalkuruppu** [comment]
@gimantha Can you please check the following scenario and the result. Need to confirm whether the following behaviour is correct, so that we can provide the code action result accordingly(whether `if barResult is Foo {}` or `if barResult is error {}`). 
Code: 
```ballerina
public function main() {
    Foo|error barResult = bar();
    io:println(typeof(barResult));

    if barResult is Foo {
        io:println("foo line");
    }
    if barResult is error {
        io:println("error line");
    }

}

function bar() returns Foo|error {
    Foo foo = error("");
    return foo;
}

type Foo error;
```

Result:
```
typedesc error
error line
```

**Comment by gimantha** [comment]
@gayalkuruppu The `typeof` has to be Foo in this case and it should print both `foo line` and `error line`. I think for errors the reference type information is not yet implemented. @HindujaB Can you please confirm?

**Comment by HindujaB** [comment]
>  @HindujaB Can you please confirm?
Yes. In the above case, it should print for both `Foo` and `error` cases. 
The `typeof` returning `typedesc error` instead of `typedesc Foo` is a spec deviation. This will be fixed when we support the `type-reference` type at runtime.
But, `barResult is Foo` returning false should be a type-checker bug. Shall we create a separate issue on this?

**Comment by HindujaB** [comment]
The type-reference information is now passed to runtime. 
The output is as follows with the current master. 
```
typedesc mod:Foo
foo line
error line
```
