### ISSUE TITLE
[Bug]: Named worker strands do not run on separate threads even if the function is isolated

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#38483]
### Description

$title

The spec says in https://ballerina.io/spec/lang/master/#section_7.3.2
> Each named worker runs on its own new strand. The strand can run on a separate thread from the default worker if the function is isolated.

We see the `BIRFunction.annotAttachments` is empty in the functions created for the named workers even if they are inside the isolated functions.

### Steps to Reproduce

```bal
import ballerina/io;

type Person record {|
    string name;
    boolean employed;
|};

isolated function process(Person[] & readonly members, int[] & readonly quantities) {
    worker w1 {
        Person[] employedMembers = from Person p in members
            where p.employed
            select p;
        int count = employedMembers.length();
        count -> function;
    }

    int totalMemberCount = members.length();

    int memberCount = <- w1;
    io:println(string `Employed Members: ${memberCount}`);

    future<int> avgFuture = start get_average(quantities, memberCount);

    int unemployedCount = totalMemberCount - memberCount;
    io:println(string `Unemployed Members: ${unemployedCount}`);

    int avg = checkpanic wait avgFuture;
    io:println(string `Average: ${avg}`);
}

isolated function get_average(int[] & readonly quantities, int employedCount) returns int {
    int total = int:sum(...quantities);
    int avg = employedCount == 0 ? 0 : total / employedCount;
    return avg;
}

public function main() {
    Person[] & readonly members = [{name: "aaa", employed: false}, {name: "aaa", employed: true}, {name: "aaa", employed: true}];
    int[] & readonly quantities = [10, 20, 30];
    process(members, quantities);
}
```

We see though the `get_average` function contains the annotation, the `$lambda$0` function for worker `w1` does not have the annotation.

### Affected Version(s)

Ballerina 2201.2.2 (Swan Lake Update 2)

### Related area

-> Compilation

**Comment by Nadeeshan96** [comment]
Here need to add the `strand thread : any` annotation to the `BLangFunction` of the workers which are going to run on separate threads. There it is needed to:
add the annotation to `function.annAttachments` and `function.symbol.annotationAttachments` and change `function.symbol.schedulerPolicy` to `any`.

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/issues/38483
