### ISSUE TITLE
[Bug]: Completions for quote identifier given without the quote

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#38485]
### Description

Consider the following:
![image](https://user-images.githubusercontent.com/6260009/199080414-e7ac9386-1f9e-41c1-9828-6024d5a85aa1.png)

In the above, when I click on `type`, it gets completed as `type`, whereas it should've been completed as `'type`. Same when i type `f.` and get the completion. IIRC, this used to work properly, where we used to give quoted identifiers in completions if the user had written it as a quoted identifier in the code. 

```ballerina
public function main() {
    Foo f = {<cursor1>};
    f.<cursor2>
}

type Foo record {|
    int 'type;
|};
```

### Affected Version(s)

2201.2.1

### Related area

-> Editor

**Comment by mindula** [comment]
fixed with #38003 but the label of the completion item should be fixed.
