### ISSUE TITLE
[Bug]: `Remove re-declared import` code action is not suggested for modules in the current package

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#38489]
### Description

Consider the following scenario where we try to import the same module twice.

https://user-images.githubusercontent.com/61020198/199156769-5a0e886b-b70b-40ac-8bdb-b7742f7ba3f9.mov

The diagnostic we get here is `redeclared symbol 'module1' (BCE2008)` not `redeclared import module (BCE2004)`

### Related area

-> Editor

**Comment by hasithaa** [comment]
Technically, it is a prefix symbol that is redeclared in that symbol scope, So it is a redeclared symbol. This logic is a generic implementation for all symbol spaces. 

But we can improve the error message only for import statements.

**Comment by DamithaSenevirathne** [comment]
Created issue https://github.com/ballerina-platform/ballerina-lang/issues/38669 for compilerFE improvements.
Created PR : https://github.com/ballerina-platform/ballerina-lang/pull/38725 to address to suggest correct codeaction.
