### ISSUE TITLE
[Bug]: Using the "Create variable" code action for a type from a module generated for a client declaration adds an import for the module

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38497]
### Description

$title. Since explicitly importing these modules is no longer allowed, it will result in a compilation error.

### Steps to Reproduce

```ballerina
client "petstore.yaml" as petstore;

public function main() returns error? {
    petstore:client cl = check new;

    cl->/pets(); // Create variable
}
```

https://github.com/ballerina-platform/openapi-tools/blob/master/openapi-cli/src/test/resources/petstore.yaml

### Affected Version(s)

2201.3.0-RC1

### Related area

-> Editor

**Comment by malinthar** [comment]
Closing as the IDL feature was removed.
