### ISSUE TITLE
[HTTP] Revoked Certificate verification 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#3849]
This can be done using CRL or OCSP protocols. There is a similar implementation in WSO2 ESB. See below.

http://blog.lasindu.com/2014/12/revoked-certificate-verification-for.html

**Comment by Bhashinee** [comment]
Fixed : https://github.com/ballerina-platform/ballerina-lang/pull/4644 and https://github.com/wso2/transport-http/pull/46
