### ISSUE TITLE
[Bug]: `filePath` variable of the `LineRange` object returns file name 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-lang#38500]
### Description

When trying to get the file path of a given node via the `filePath` of a `LineRange` object, it actually returns only the file name. 

```bal
TypeDefinitionSymbol typeDefinitionSymbol = (TypeDefinitionSymbol) symbol;
String filePath = typeDefinitionSymbol.getLocation().get().lineRange().filePath();
```

![image](https://user-images.githubusercontent.com/34091327/199195425-da5d4f11-c430-4170-b92e-35eb8f02f4df.png)

Is this the expected behavior ? @dulajdilshan @IMS94 @NipunaRanasinghe

**Comment by NipunaRanasinghe** [comment]
IMO to rectify the DX, we should either return the relative file path in here or, rename this `filePath()` API as `fileName()`. @IMS94 @dulajdilshan WDYT?

**Comment by IMS94** [comment]
This is the expected behavior. Had a chat with @dulajdilshan as well. Can you look at `PathUtil.getFilePathForSymbol()` method in LS? We are deriving the file path from a symbol's location there.

**Comment by NipunaRanasinghe** [comment]
@IMS94 Ack. So if thats's the expected behaviour, shouldn't we change the API name from `filePath()` to `fileName()`, to avoid more confusions in the future? Otherwise people might keep using this API expecting the file path, and will end up getting unexpected results

**Comment by dulajdilshan** [comment]
> @IMS94 Ack. So if thats's the expected behaviour, shouldn't we change the API name from `filePath()` to `fileName()`, to avoid more confusions in the future? Otherwise people might keep using this API expecting the file path, and will end up getting unexpected results

+1. Let's change the name of the API in future releases

**Comment by IMS94** [comment]
@dulajdilshan since this is a commonly used class, we cannot just rename. We have to deprecate `filePath` first and introduce `fileName`

**Comment by dulajdilshan** [comment]
> @dulajdilshan since this is a commonly used API level class, we cannot just rename. We have to deprecate `filePath` first and introduce `fileName`

Yeah of course.
