### ISSUE TITLE
[Bug]: Generate module for client declaration failure gives modules generated successfully pop up

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#38512]
### Description

![Screenshot 2022-11-02 at 11 00 48](https://user-images.githubusercontent.com/15815199/199405998-fd33e7e0-6300-4ec6-b65a-175eb2faae12.png)

### Affected Version(s)

v2201.3.0 rc1

### Related area

-> Editor

**Comment by malinthar** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38470
