### ISSUE TITLE
Full build checks for the master branch PRs are getting hanged intermittently

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#38510]
### Description

Due to $subject, there has been a huge queue for the workflow jobs with the platform repos. Refer to https://github.com/ballerina-platform/ballerina-lang/actions/runs/3369201951 as an example scenario, where 4 out of 8 jobs for ballerina-lang:Full build pipeline is hanging and consuming resources for 6 hrs each. 

The related workflow (https://github.com/ballerina-platform/ballerina-lang/actions/workflows/pull_request_full_build.yml) is manually disabled until getting fixed.

### Related area

-> CICD

**Comment by niveathika** [comment]
One more check we can introduce is to reduce timeouts to 2 hrs max.

**Comment by niveathika** [comment]
Hanging for distribution is reproducible in FBP https://github.com/ballerina-platform/ballerina-release/actions/runs/3372000434/jobs/5594915567

**Comment by niveathika** [comment]
Reopening as the issue of distribution dev tools tests hanging still needs to be identified and fixed

**Comment by niveathika** [comment]
@NipunaMadhushan Seems the timeout option is not applying to the other builds in the matrix,

https://github.com/ballerina-platform/ballerina-lang/actions/runs/3391545211

**Comment by niveathika** [comment]
Noticed concurrency setting not being applied for jobs in the matrix. @NipunaMadhushan FYA

**Comment by NipunaMadhushan** [comment]
Noticed that every PR check for ballerina-distribution hanged from project-api-tests.
`Executing: /home/runner/work/ballerina-lang/ballerina-lang/project-api-tests/build/test-distribution/ballerina-2201.3.0-SNAPSHOT-swan-lake/bin/bal push /tmp/bal-test-integration-packaging-workspace-8631619587375541510/disttestpackbeta6/bctestorg-disttestpackbeta6-any-1.1.0.bala`
