### ISSUE TITLE
[Task]: Fix failing LS testcases after replacing `contextTypeResolver` with `expectedType API`

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#38546]
### Description

Since usages of `ContextTypeResolver` replaced by the `expectedType` API, failing LS cases need to be fixed.

### Related area

-> Editor

**Comment by TharushiJay** [comment]
As per the offline discussion, the following test cases will not be addressed in this PR. @DamithaSenevirathne will further look into those.
```
“Function_call_expression_ctx_config15.json”
“Function_call_expression_ctx_config19.json”
"mapping_constructor_expr_ctx_config3.json"
“New_expr_ctx_config15.json”
“New_expr_ctx_config11.json”
“New_expr_ctx_config16.json”
“New_expr_ctx_config26.json”
“New_expr_ctx_config14.json”
"mapping_expr_ctx_config38_negative.json",
“Anon_func_expr_ctx_config1a.json”
```

**Comment by TharushiJay** [comment]
Due to parser changes for client declaration, the context is identified incorrectly in`var_def_ctx_config16.json` (https://github.com/ballerina-platform/ballerina-lang/issues/38711). Therefore, it will be fixed once https://github.com/ballerina-platform/ballerina-lang/pull/38800 is merged reverting the changes.

**Comment by TharushiJay** [comment]
```
“Function_call_expression_ctx_config15.json”,
“Function_call_expression_ctx_config19.json”
```
will be fixed from the LS side.

**Comment by DamithaSenevirathne** [comment]
PR: https://github.com/ballerina-platform/ballerina-lang/pull/38852 will address remaining cases

**Comment by TharushiJay** [comment]
Due to the recent changes in https://github.com/ballerina-platform/ballerina-lang/pull/38852, the following LS tests mentioned on this [document](https://docs.google.com/document/d/1Nhfp34jqOGyhKooCDFAS85P3z2ypj4vakXTqNYzcPCM/edit) need to be fixed as well.

**Comment by IMS94** [comment]
@mindula could you overtake this and see through the expected types API.

**Comment by IMS94** [comment]
Closing this since the test cases have been fixed and the PR to master is ready: https://github.com/ballerina-platform/ballerina-lang/pull/39287
