### ISSUE TITLE
Unclear error message when non-existent directory given as source path

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#3854]
The following error is given to the user when a non-existent directory is given as the source path. 
```
ballerina: invalid Ballerina source path, it should either be a directory or a file with a '.bal' extension.
```
Need to refine the error message. The error message should clearly indicate that the runtime failed to locate any valid .bal files in the given location. The "it should either be a directory" part does not make it clear that the given directory path is invalid.

**Comment by afkham** [comment]
Fixed
