### ISSUE TITLE
[New Feature]: Extending bal pull command to pull all direct, indirect dependencies of a project.

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#38542]
### Description

Spec issue : https://github.com/ballerina-platform/ballerina-spec/issues/1010

### Describe your problem(s)

In cloud editing environments like code-servers when you open an existing package with a dependencies.toml there will be compiler errors due to missing dependencies. We have to `bal build` to fetch and resolve all the dependencies.

### Describe your solution(s)

Extend the `bal pull` command to,

1. Pull a specified package - existing functionality
    ``` bal pull <org-name>/<package-name>[:<version>] ```

2. a) Inside a ballerina package with no parameters - pull all the direct/ indirect dependencies of the package
         ```bal pull ```

    b) With a path given for the root of a ballerina package - pull all the direct/ indirect dependencies of the package found in  the provided path.
         ```bal pull path/to/the/root/dir/of/package```

### Related area

-> Other Area

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-spec/issues/1010

**Comment by azinneera** [comment]
Closing since this will be put on hold till the new code generator design is finalized.
