### ISSUE TITLE
[Bug]: VS Code plugin inserts an invalid string concatenation

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#38551]
### Description

Refer to the following. Note the cursor position between `"bar"` and `]`.

![image](https://user-images.githubusercontent.com/6260009/199691031-308ffbdf-94ff-47d8-895b-ab77c19e37a0.png)

When I press enter at the above cursor position, the following is the result:

![image](https://user-images.githubusercontent.com/6260009/199691331-8aab08d3-583c-4668-bee2-e9a68e9a79f8.png)

### Affected Version(s)

2201.2.1

### Related area

-> Editor

**Comment by IMS94** [comment]
Seems like this is related to #37462 (string splitter in VSCode plugin side). @gigara can you check this?

**Comment by IMS94** [comment]
Sample source code:
```ballerina
function foo () returns  [(string|map<anydata>)[], map<anydata>, string][] {
    return [
        [
            ["foo", {name: "", kind: "", 'type: ""}], {id: 100}, "bar"<cursor>]
    ];
}
```
Press enter at the cursor
