### ISSUE TITLE
Support function and operator binding on literals

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/ballerina-lang#3855]
Suppose the following operator :
```
int[] arr = [1,2,3];
int length = lengthof arr;
```

Here arr must be defined in order to use the length of. However, following are also useful when writing a program.

```
int length = lengthof [];
int length = lengthof [1,2,3];
```

When functions are bound to types, it would be convenient if they worked in a similar fashion. For example,
```
string str = "lowercase string";
string str2 = str.toUpperCase();
```

could also be written as :
`string str2 = "lowercase string".toUpperCase();`

This is a common functionality that is supported accross many languages.

See discussion : https://groups.google.com/forum/#!topic/ballerina-dev/c7sWiQlAyjE

**Comment by hasithaa** [comment]
We intentionally not supporting the following syntax. 

var x = [];
var a = [1,2,3];

So [].length() is no longer valid. 

Still "lowercase string".toUpperCase(); nice to have.
