### ISSUE TITLE
[Improvement]: Introduce quick pick support for extract to local variable code action

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#38557]
### Description

We introduced quick pick support for extract to constant code action. Now we should do the same for extract to local variable code action.

### Related area

-> Editor

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/pull/38208

**Comment by mindula** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39350
