### ISSUE TITLE
[Task]: Add spec conformance tests for regular expression syntax

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#38560]
### Description

$title

### Related area

-> Other Area

**Comment by pcnfernando** [comment]
Added though https://github.com/ballerina-platform/ballerina-spec/pull/1185/files

**Comment by MaryamZi** [comment]
We are closing this issue because it is not being actively worked on. Let's reopen when we resume conformance test efforts.
