### ISSUE TITLE
[Bug]: Unable to Access semantic API for modified node

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#38576]
### Description

$Subject. 
The same issue will happen when another compiler extension access a node added by other compiler plugin

### Steps to Reproduce

1.Write a compiler extension which modifies the user's code. (Ex - Add an annotation to function)
2. Try to access the symbol using semantic api of the modified function in the code generated phase.

### Affected Version(s)

2201.2.3 and 2201.3.0

### Related area

-> Compilation

**Comment by dulajdilshan** [comment]
I had a chat with Anjana, It seems like although we modified the syntax tree using `modifySourceFile()` in the project API, we don't get the correct symbol when using `SemanticModel.symbol()`.

**Comment by xlight05** [comment]
Steps to Reproduce - 
1. Clone the repo - https://github.com/ballerina-platform/module-ballerinax-azure.functions
2. ./gradlew clean build 
3. Put a debug point in the codegenerated phase - https://github.com/ballerina-platform/module-ballerinax-azure.functions/blob/f977b98ff82107ebf75f403e159e3f11558bdd84/compiler-plugin/src/main/java/org/ballerinax/azurefunctions/AzureFunctionServiceVisitor.java#L47
4. Try to access the Annotation added to the resource function. You should get a NPE.

**Comment by xlight05** [comment]
Had a chat with @dulajdilshan  and @azinneera on this. Apparently from the Project API Side, Semantic API is not designed to be not accessible in the first place, therefore that's why we are getting this output here. However, I have seen similar issues without using compiler lifecycle listeners as well, will post a new issue when I find the exact reproduction steps. Closing this for now.
