### ISSUE TITLE
[Bug]: Some test cases for ballerina salesforce module is not running properly

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/ballerina-lang#38609]
### Description

The ballerinax/salesforce contains 3 modules and each has separate set of test cases. Once the connector is configured and the test cases are running some of the test cases in some modules doesn't seem to run. 

![Screenshot from 2022-11-10 10-13-10](https://user-images.githubusercontent.com/34184297/201002597-e3ede747-94a8-4912-b759-23f3327d224a.png)

### Steps to Reproduce

- Configure the Salesforce connector 
- Run the tests

### Affected Version(s)

Ballerina 2201.3.0

### OS, DB, other environment details and versions

Ubuntu 20.04
Java 11

### Related area

-> Test Framework

**Comment by gayaldassanayake** [comment]
The failing GitHub action url: https://github.com/ballerina-platform/module-ballerinax-sfdc/actions/runs/3430457773/jobs/5717444952

**Comment by gayaldassanayake** [comment]
The failure there is not related to a testerina bug, but an invalid ballerina error type return value from the test `testQuery`.
It returns an error with no `detail()`, `message()` properties. When trying to access these methods of the error, a runtime error is thrown from within the error.message().

The reason looks to be an unhandled java exception coming from the `salesforce` native code. @sachinira is looking into it as of now.

**Comment by sachinira** [comment]
> The failure there is not related to a testerina bug, but an invalid ballerina error type return value from the test `testQuery`. It returns an error with no `detail()`, `message()` properties. When trying to access these methods of the error, a runtime error is thrown from within the error.message().
> 
> The reason looks to be an unhandled java exception coming from the `salesforce` native code. @sachinira is looking into it as of now.

Ack. Looping @kasthuriraajan

**Comment by sachinira** [comment]
@gayaldassanayake tested the Salesforce connector locally. The tests were passing as expected for `salesforce.soap` module

![Screenshot from 2022-11-20 09-42-14](https://user-images.githubusercontent.com/34184297/202885054-934670df-2e89-40ee-8f1c-fa0aff283a7d.png)

![Screenshot from 2022-11-20 09-42-28](https://user-images.githubusercontent.com/34184297/202885063-689e27f0-9023-4cc4-94e9-9d974992286e.png)


In the `salesforce.bulk` module and `salesforce.rest` modules which we can observe few test cases are not running in the daily build 

When I test the `create` operation of  `salesforce.rest` module

```
salesforce:Client baseClient = check new (sfConfig);

    record{} accountRecord = {
        "Name": "IT World",
        "BillingCity": "Colombo 1"
    };

    salesforce:CreationResponse|error res = baseClient->create("Account", accountRecord);

    if res is salesforce:CreationResponse {
        log:printInfo("Account Created Successfully. Account ID : " + res.id);
    } else {
        log:printError(msg = res.message());
        log:printError(msg = res.detail().toString());
    }
```

I could access the message() and detail() properties

```
sachini@sachinira:~/Documents/my_tasks/my-connectors/module-ballerinax-sfdc/salesforce/samples/rest_api_usecases$ /home/sachini/Downloads/installers/ballerina-2201.3.0-swan-lake/bin/bal run sobject_create.bal 
Compiling source
        sobject_create.bal

Running executable

time = 2022-11-20T09:52:39.555+05:30 level = INFO module = "" message = "Account Created Successfully. Account ID : 0015g000013OFXtAAO"
sachini@sachinira:~/Documents/my_tasks/my-connectors/module-ballerinax-sfdc/salesforce/samples/rest_api_usecases$ /home/sachini/Downloads/installers/ballerina-2201.3.0-swan-lake/bin/bal run sobject_create.bal 
Compiling source
        sobject_create.bal

Running executable

time = 2022-11-20T09:57:22.622+05:30 level = ERROR module = "" message = "Bad Request"
sachini@sachinira:~/Documents/my_tasks/my-connectors/module-ballerinax-sfdc/salesforce/samples/rest_api_usecases$ /home/sachini/Downloads/installers/ballerina-2201.3.0-swan-lake/bin/bal run sobject_create.bal 
Compiling source
        sobject_create.bal

Running executable

time = 2022-11-20T10:00:31.164+05:30 level = ERROR module = "" message = "Bad Request"
time = 2022-11-20T10:00:31.173+05:30 level = ERROR module = "" message = "{\"statusCode\":400,\"headers\":{\"Cache-Control\":[\"no-cache,must-revalidate,max-age=0,no-store,private\"],\"Content-Type\":[\"application/json;charset=UTF-8\"],\"Date\":[\"Sun, 20 Nov 2022 04:30:30 GMT\"],\"Set-Cookie\":[\"CookieConsentPolicy=0:1; path=/; expires=Mon, 20-Nov-2023 04:30:30 GMT; Max-Age=31536000\",\"LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Mon, 20-Nov-2023 04:30:30 GMT; Max-Age=31536000\",\"BrowserId=EQ6OKmiMEe23vp0WuyIweA; domain=.salesforce.com; path=/; expires=Mon, 20-Nov-2023 04:30:30 GMT; Max-Age=31536000\"],\"Sforce-Limit-Info\":[\"api-usage=754/15000\"],\"Strict-Transport-Security\":[\"max-age=63072000; includeSubDomains\"],\"Transfer-Encoding\":[\"chunked\"],\"X-Content-Type-Options\":[\"nosniff\"],\"X-Robots-Tag\":[\"none\"],\"X-XSS-Protection\":[\"1; mode=block\"]},\"body\":[{\"duplicateResut\":{\"allowSave\":true,\"duplicateRule\":\"Standard_Account_Duplicate_Rule\",\"duplicateRuleEntityType\":\"Account\",\"errorMessage\":\"Duplicates found\",\"matchResults\":[{\"entityType\":\"Account\",\"errors\":[],\"matchEngine\":\"FuzzyMatchEngine\",\"matchRecords\":[{\"additionalInformation\":[],\"fieldDiffs\":[],\"matchConfidence\":100.0,\"record\":{\"attributes\":{\"type\":\"Account\",\"url\":\"/services/data/v48.0/sobjects/Account/0015g000013OFXtAAO\"},\"Id\":\"0015g000013OFXtAAO\"}}],\"rule\":\"Standard_Account_Match_Rule_v1_0\",\"size\":1,\"success\":true}]},\"errorCode\":\"DUPLICATES_DETECTED\",\"message\":\"Duplicates found\"}]}"
sachini@sachinira:~/Documents/my_tasks/my-connectors/module-ballerinax-sfdc/salesforce/samples/rest_api_usecases$ 
```

Will schedule a call to furthur discuss the issue. The root cause seems not related to the salesforce native

Local Test Configurations
Ballerina 2201.3.0

**Comment by gayaldassanayake** [comment]
As per the discussion with @sachinira, 
There is an unhandled `BError` thrown from the salesforce native(java) code which has a null `message` field. That needs to be fixed from the salesforce connector side. 

The possibility of adding restrictions in creating a `BError` with a null `message` field needs to be evaluated.

Closing the issue since it is not related to the testerina framework.
