### ISSUE TITLE
[Bug]: Getting `failed to load test execution class` error when running test with --native flag

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#38614]
### Description

Getting the following error time to time, when running the graphql module test with `--native` flag 

```
Running Tests

	graphql.parser
error: failed to load test execution class :ballerina.graphql$0046parser$test.1.tests.test_execute-generated_1
error: there are test failures
```

Github action logs related to this error can be found here: https://github.com/ballerina-platform/module-ballerina-graphql/actions/runs/3430907608/jobs/5718422153#step:9:194 

### Related area

-> Test Framework

**Comment by dilanSachi** [comment]
gRPC also fail with the same error

https://github.com/ballerina-platform/module-ballerina-grpc/actions/runs/3436040349/jobs/5729106377#step:9:223

**Comment by TharmiganK** [comment]
Protobuf also failing even after all the tests have been passed 
https://github.com/ballerina-platform/module-ballerina-protobuf/actions/runs/3436448665/jobs/5729977670#step:9:155
