### ISSUE TITLE
[Improvement]: Give compile-time error for negative startIndex in the regexp langlib functions

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-lang#38645]
### Description

$title

### Describe your problem(s)

```regexp:Span? _ = regExpr1.find(str1, -5);``` Here better to give CE instead of RE.

### Related area

-> Compilation

**Comment by sanjana** [comment]
This shall also be addressed in `findAll`, `findGroups()`, `findAllGroups` methods as well.

**Comment by sanjana** [comment]
A similar approach to what's used in the `string:substring()` could be used here. 
Therefore, a Runtime Error shall be expected when a negative value is passed here.
