### ISSUE TITLE
[Bug]: Fix debugger integration test `testEvaluationsOnLangLibs` to allow addition of `int:range`

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/ballerina-lang#38646]
### Description

`testEvaluationsOnLangLibs` in `DependencyEvaluationTest` is failing for the #38279 PR after introducing the `int:range` langlib function. The test needs to be fixed and re-enabled.

### Related area

-> Compilation

### Related issue(s) (optional)

#38348

### Suggested assignee(s) (optional)

@Nipuna

**Comment by NipunaRanasinghe** [comment]
Closing since the required changes are merged to the feature branch with https://github.com/ushirask/ballerina-lang/pull/52
