### ISSUE TITLE
[Bug]: Outdated Ballerina Formatter error message

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#38681]
### Description

When I execute the `bal format` command inside the invalid Ballerina package using Swanlake 2201.2.1 version. Received this error message with outdated command `ballerina format`

```
error: not a valid Ballerina project.
usage: ballerina format should be run inside a ballerina project or pass in a ballerina file.
i.e. `ballerina format <ballerina-file>`

run `ballerina format -h` for more details
```
this should be update with new `bal` command instead of using `ballerina`  for the Swanlake 2201.2.1 version and above

expected error
```
error: not a valid Ballerina project.
usage: ballerina format should be run inside a ballerina project or pass in a ballerina file.
i.e. `bal format <ballerina-file>`

run `bal format -h` for more details
```

### Steps to Reproduce

Try to execute `bal format` command outside the ballerina package 

### Affected Version(s)

2201.2.1

### OS, DB, other environment details and versions

Linux

### Related area

-> Formatter

**Comment by Ishad-M-I-M** [comment]
Hi. Can I get this issue assigned to me.

**Comment by SasinduDilshara** [comment]
Hi @Ishad-M-I-M 

Yes, you can work on this issue.

To help you get started, here are some resources that may help you get started with Ballerina:

Understanding Ballerina Platform:
Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)

How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)

Learn Ballerina:
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)

Get Help and Connect:
Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by Ishad-M-I-M** [comment]
@SasinduDilshara, I have created a PR  on this.
I have set the target branch as `2201.2.x`. Hope it should be the target.
