### ISSUE TITLE
[Bug]: Pull packages from local repository not worked as expected

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#38694]
### Description

I Created a Ballerina package using following code.
```
public type E1 distinct error;

public type E2 distinct (E1 & error<record {|anydata body;|}>);
```

Then executed following commands.
1. `bal pack`
2. `bal push --repository=local`

Then I try to import the module.
```
import sasindudilshara/proj;

public function main() {
    proj:E2 e = error("", body = "");
    error e2 = error proj:E2("", body = "");
}
```
Then following error occurred.

```
ERROR [test2.bal:(1:1,1:30)] cannot resolve module 'sasindudilshara/proj'
ERROR [test2.bal:(4:5,5:13)] undefined module 'proj'
ERROR [test2.bal:(4:5,5:13)] unknown type 'E2'
ERROR [test2.bal:(5:22,6:30)] undefined error type descriptor 'E2'
ERROR [test2.bal:(5:22,6:30)] undefined module 'proj'
```

The code does not pull the package from local repository.

Workaround is to push package to ballerina central and then import.

### Related area

-> Central

**Comment by azinneera** [comment]
You should add the dependency in the Ballerina.toml. Refer https://ballerina.io/learn/manage-dependencies/#use-dependencies-from-the-local-repository

**Comment by Dilhasha** [comment]
Answered. Hence, closing.
