### ISSUE TITLE
[Improvement]: Code action for Auto generating record fields

### ISSUE THREAD

**Issue by CharukaK** [ballerina-platform/ballerina-lang#38729]
### Description

Currently, there is a suggestion for auto-filling the required fields of a record as shown below
![2022-11-20-181901_615x257_scrot](https://user-images.githubusercontent.com/18122888/202902880-86c909bf-d932-4dd5-97c3-2d5abdfb2cb1.png)

but when we hover over the error there is no code action I feel it should be a code action rather than a suggestion maybe we can show that in suggestions as well as code actions?
![2022-11-20-181911_753x337_scrot](https://user-images.githubusercontent.com/18122888/202902949-d3da7374-a227-4f80-bd16-a6ee2fa1a8ef.png)

### Related area

-> Editor

**Comment by mindula** [comment]
This has been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38003
