### ISSUE TITLE
[Bug]: VS Code does not show diagnostics from code modifier plugin

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#38730]
### Description

There are instances where, package specific diagnostics must be reported from modifier plugin analysis tasks. These cannot be reported from code analyser, since the code is already modified, the node locations are changed.)

These are not reported in VSCode, however when compiling the diagnostics will be print. The experience is broken in the case since, output is different.

<img width="671" alt="Screenshot 2022-11-20 at 23 10 09" src="https://user-images.githubusercontent.com/27669465/202917433-72f1396d-a628-4f76-8c33-de63755d53f9.png">

<img width="1429" alt="Screenshot 2022-11-20 at 23 11 47" src="https://user-images.githubusercontent.com/27669465/202917407-9f41c687-f7be-4229-b981-bbdaf4478caf.png">

### Related area

-> Compilation

**Comment by azinneera** [comment]
Code modifiers are not designed to run in the LS. Therefore, this behavior is expected. You can use the analyzer plugin if you want to add custom validations.
