### ISSUE TITLE
Support generated/ directory in package structure

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#38766]
Spec issue: https://github.com/ballerina-platform/ballerina-spec/issues/1179

- [x] Implement package loading
- [x] API changes to support LS functionality for generated sources in default module
- [x] API changes to support LS functionality for generated sources in non-default module
- [x] Test and verify the generated source support during `bal build` and in LS

**Comment by Dilhasha** [comment]
Update on current progress.

Current changes available at https://github.com/Dilhasha/ballerina-lang/tree/generated-without-idl

PR can be sent after merging https://github.com/ballerina-platform/ballerina-lang/pull/38864

**Comment by Dilhasha** [comment]
Test status tracked in https://docs.google.com/spreadsheets/d/1Qvds95SXMTc5yEXLAmA-mtQLI-kuwQ4Lo7WSuHtTbRI/edit?usp=sharing

**Comment by Dilhasha** [comment]
Need to fix test failures in https://github.com/ballerina-platform/ballerina-lang/pull/38977

- [ ] :language-server:language-server-core:test
