### ISSUE TITLE
[Improvement]: GraalVM native image generation command output - Fix grammar issues

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#38760]
### Description

```
bal build --native 
WARNING : Native image generation is an experimental feature, which supports only a limited set of functionality.
```

This warning message should be improved as follows:
`WARNING: Native image generation is an experimental feature that supports only a limited set of functionality.`

### Related area

-> Other Area

**Comment by sameerajayasoma** [comment]
Here is my suggestion. 
`WARNING: GraalVM Native Image generation in Ballerina is an experimental feature`

**Comment by azinneera** [comment]
Also, we should try to improve the inconsistencies in the error messages for scenarios like:
```
Failed generating 'payment' after 3m 30s.
Error: Image build request failed with exit status 1
error: unable to create native image
```
