### ISSUE TITLE
[Task]: Write a separate Node Visitor for Type-checking the Group by and Collect clause

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#38774]
### Description

The way the aggregated variables behave is context-specific. Aggregated variables are created in a frame only when we have a group by clause or a collect clause.  Their usage is valid only in aggregated functions like sum. (which accepts rest args) and list constructors ( where we can use the spread operators on arrays). In future, there can be cases where we have to add, multiply, subtract.. etc between aggregated variables. and Having all these semantic changes in our default semantic analyzer  can complicate the implementation. So the suggestion is to have a different type-checker for aggregated variables.

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-spec/issues/441

**Comment by KavinduZoysa** [comment]
This will be handles in https://github.com/ballerina-platform/ballerina-lang/pull/40447
