### ISSUE TITLE
[Bug]: Compiler crashes for langlib call in query expression

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#38783]
### Description

$title

### Steps to Reproduce

```ballerina
type Employee record {|
    string id;
    string name;
|};

public function main() {
    string[] ids = [];
    Employee[] employees = [];
    string[] _ = from string id in ids
                    where employees.some(employee => employee.id == id)
                    select id;
}
```

### Affected Version(s)

2201.3.0-RCs

### Related area

-> Compilation

### Related issue(s) (optional)

May be related to https://github.com/ballerina-platform/ballerina-lang/issues/32710

**Comment by lasinicl** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39608
