### ISSUE TITLE
[Task]: When client supports both quick pick and rename capabilities improve the extract command

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38803]
### Description

There are three scenarios we need to consider when we have quick pick and rename support capabilities.

1. Client with quick pick capability
2. Client with renaming capability
3. Client with renaming and quick pick capability

We need to handle the third case for extract to code actions (extract to function, extract to constant and extract to local variable).
In this case we need send the start position of the selected expression as a command argument to the quick pick command to execute once after the user picks his/her intended expression.

### Related area

-> Editor

**Comment by IMS94** [comment]
Needs #38663 to be merged to start this

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
