### ISSUE TITLE
[Task]: Validate change type of raw template code action after introduction of the regex template

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38804]
### Description

Currently change raw type of template code action only supports string and xml types. After adding the regex feature we need to verifying the code action is working correctly, if not improve the code action to support regex templates as well.

### Related area

-> Editor

**Comment by IMS94** [comment]
@mindula shall we verify this along with @39290?

**Comment by IMS94** [comment]
Have to improve the convert to template code action to support `regexp`. Blocked by #39362

**Comment by IMS94** [comment]
We can proceed since #39362 was merged
