### ISSUE TITLE
[Improvement]: Extract to function code action - Supported syntaxkinds

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#38819]
### Description

Currently we support limited number of syntaxKinds for this code action and we can use this issue to track improvements done for the code action in future. Please do add new syntaxkinds introduced in the language. For more info check the [document](https://docs.google.com/document/d/1AcmzqXkIyvCcxbRSsTs6wwT9vIg5M6Wti5zov0WkbK8/edit?usp=sharing), it has explanations why we cannot support for some cases and why we are not supporting some cases. For some cases, you can already find test cases added in the `ExtractToFunctionCodeActionTest.java` as negative tests. 

### Statements

**Already supported**
- [x] LOCAL_VAR_DECL
- [x] ASSIGNMENT_STATEMENT
- [x] IF_ELSE_STATEMENT
- [x] WHILE_STATEMENT
- [x] RETURN_STATEMENT
- [x] COMPOUND_ASSIGNMENT_STATEMENT
- [x] LOCK_STATEMENT
- [x] FOREACH_STATEMENT
- [x] MATCH_STATEMENT
- [x] DO_STATEMENT

**To be supported**
- [x] BLOCK_STATEMENT
- [ ] ACTION_STATEMENT
- [ ] FORK_STATEMENT
- [ ] TRANSACTION_STATEMENT
- [ ] RETRY_STATEMENT
- [ ] XMLNS_DECLARATION

**Cannot be supported**

- PANIC_STATEMENT
- CONTINUE_STATEMENT
- BREAK_STATEMENT
- NAMED_WORKER_DECL
- ROLLBACK_STATEMENT
- INVALID_EXPRESSION_STATEMENT
- FAIL_STATEMENT

### Expressions

**Already supported**
- [x] BINARY_EXPRESSION
- [x] BRACED_EXPRESSION
- [x] QUALIFIED_NAME_REFERENCE
- [x] INDEXED_EXPRESSION
- [x] FIELD_ACCESS
- [x] METHOD_CALL
- [x] MAPPING_CONSTRUCTOR
- [x] TYPEOF_EXPRESSION
- [x] UNARY_EXPRESSION
- [x] TYPE_TEST_EXPRESSION
- [x] SIMPLE_NAME_REFERENCE
- [x] LIST_CONSTRUCTOR
- [x] TYPE_CAST_EXPRESSION
- [x] TABLE_CONSTRUCTOR
- [x] LET_EXPRESSION
- [x] IMPLICIT_NEW_EXPRESSION
- [x] EXPLICIT_NEW_EXPRESSION
- [x] STRING_LITERAL
- [x] NUMERIC_LITERAL
- [x] BOOLEAN_LITERAL
- [x] ERROR_CONSTRUCTOR

**To be supported**
- [ ] CHECK_EXPRESSION
- [ ] TRAP_EXPRESSION
- [ ] XML_TEMPLATE_EXPRESSION
- [ ] RAW_TEMPLATE_EXPRESSION
- [ ] STRING_TEMPLATE_EXPRESSION
- [ ] EXPLICIT_ANONYMOUS_FUNCTION_EXPRESSION
- [ ] IMPLICIT_ANONYMOUS_FUNCTION_EXPRESSION
- [ ] QUERY_EXPRESSION
- [ ] OPTIONAL_FIELD_ACCESS
- [ ] CONDITIONAL_EXPRESSION
- [ ] TRANSACTIONAL_EXPRESSION
- [ ] OBJECT_CONSTRUCTOR
- [ ] XML_FILTER_EXPRESSION
- [ ] XML_STEP_EXPRESSION
- [ ] XML_NAME_PATTERN_CHAIN
- [ ] XML_ATOMIC_NAME_PATTERN
- [ ] BYTE_ARRAY_LITERAL
- [ ] ASTERISK_LITERAL
- [ ] REQUIRED_EXPRESSION

**Cannot be supported**

- PARENTHESIZED_ARG_LIST
- ANNOT_ACCESS
- NIL_LITERAL
- NULL_LITERAL

**Will not be supported**
- FUNCTION_CALL

### Related area

-> Editor

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
