### ISSUE TITLE
[New Feature]: Add code action to sort members by the module part member type

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#38820]
### Description

If we have a code scattered its module part members all over the file we can provide a code action (maybe called `Sort members` or `Sort module part members`) which will be a source action to sort the members. 

Ex: Consider the following code snippet
```ballerina
import ballerina/io;

public function main() {
    io:println("Hello, World!");

}

const int POPULATION = 0;

function test() {
    
}
```

After applying the code action, we can format the module part members as follows,

```ballerina
import ballerina/io;

const int POPULATION = 0;

public function main() {
    io:println("Hello, World!");

}

function test() {
    
}
```

The ordering should be decided in a way, that it would not affect the UX and ballerina good practices. 

### Related area

-> Editor

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
