### ISSUE TITLE
[Bug]: Cannot Create Enum Values with Assigned Values in Native Code

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#38846]
### Description

We have [this bug](https://github.com/ballerina-platform/ballerina-standard-library/issues/3721) in GraphQL package, where we cannot pass the correct enum value into a resource method parameter, when there's a value assigned to an enum member.

In the native code, I tried to access the union type related to the enum, but it only contains the assigned values, not the member type names. Without this information, the GraphQL bug cannot be fixed. Therefore, I think we should consider this as a bug.

### Affected Version(s)

Ballerina SwanLake Update 2 (2201.2.0) 

This also affects the other versions as well.

### Related area

-> Runtime

### Related issue(s) (optional)

#37115

**Comment by ThisaruGuruge** [comment]
@warunalakshitha Do we have any update on this? Can we have this before the next patch release?

**Comment by warunalakshitha** [comment]
@ThisaruGuruge We will check and update soon.

**Comment by Nadeeshan96** [comment]
The fix will be provided with update 4 release. What we will be providing is this. You can call `getName()` on `io.ballerina.runtime.api.types.FiniteType` to get the user defined enum member type name. For example if there is a enum like this,
```bal
enum Weekday {
    SUNDAY = "Sunday",
    MONDAY = "Monday"
}
```
we need to iterate through enum `UnionType.getMemberTypes()` and call `getName()` on each of the member types. It will give `SUNDAY` and `MONDAY`. I have written a similar test in the PR.
