### ISSUE TITLE
[Bug]: Create record code action adds the generated record after the documentation of top level node 

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38895]
### Description

Consider the following code:
```ballerina
import ballerina/graphql;

// Don't change the port number
service /graphql on new graphql:Listener(9090) {

    // Write your answer here. You must change the input and
    // the output of the below signature along with the logic.
    resource function get activity(string ID) returns ActivityDetails[]|error {
       
    }
}
```
When the `create record ActivityDetails` code action is executed (near return type descriptor), this is the result:
```
import ballerina/graphql;

// Don't change the port number
type ActivityDetails record {|
    
|};

service /graphql on new graphql:Listener(9090) {

    // Write your answer here. You must change the input and
    // the output of the below signature along with the logic.
    resource function get activity(string ID) returns ActivityDetails[]|error {
  
    }
}
```
Note that the documentation string above service declaration has been moved.

### Affected Version(s)

2201.3.0-rc3

### Related area

-> Editor

**Comment by mindula** [comment]
The same behaviour can be seen with extract to constant code action

**Comment by mindula** [comment]
In the above scenario, the description is not a document but a comment starting with `//`. Therefore, the text edit is applied after the comment as the comment does not belong to the service declaration node. If the above description is a document starting with `#`, the code action will correctly apply the text edits before the document.
