### ISSUE TITLE
[Bug]: Inconsistancy between usage log and the command line argument positioning for bal test/ build

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#38903]
### Description

The usage log for bal test is,
```
USAGE:
    bal test [--offline]
                   [<ballerina-file> | <package-path>] [(--key=value)...]
```

However if we provide,
`bal test native-test.bal --native` ---(1),  it outputs `ballerina: positional parameter at index 0..* (<projectPath>) should be specified only once Run 'bal help' for usage`

But `bal test --native native-test.bal` ---(2) is working properly. 

Here either the usage text or the command line argument should be the correct order.

NOTE 
1. Here `--native` is taken as an example. Other flags also display similar behavior
2. Need to check if the other tools (bal build etc) also have the same problem.

### Steps to Reproduce

type,
1. bal test native-test.bal --native
2. bal test --native native-test.bal

### Affected Version(s)

2201.3.0

### Related area

-> Other Area

**Comment by ShammiL** [comment]
Fixed in #39546
