### ISSUE TITLE
[Bug]: Method too large exception in a Ballerina method with large amounts of constants defined

### ISSUE THREAD

**Issue by AnjanaSenanayake** [ballerina-platform/ballerina-lang#38941]
### Description

In my Ballerina program, there is an `init()` method throwing the following error.

```
ERROR [healthcare_fhir_r4.bal:(18:1,3045:2)] method is too large: '$split$method$3'
error: compilation contains errors
```

### Steps to Reproduce

**Steps to reproduce and workarounds tried**
- The mentioned `init()` method had a constant initialization, which caused around 3000 lines of code. Given the readability concerns of the code, the constants were exported to a separate `bal` file called `variable.bal` and referred to that in `init()`  method. However, yet it caused the same issue. 
- Then again, `bal build` was tried with removing the constant reference (defined in `variable.bal`) in `init()` and for our surprise, the issue persisted. 
- Therefore, tried reducing the amount of defined constants to much less number (around 1000 lines of code) in the `variable.bal` file and observed that the **build is happening**. 

So irrespective of whether it is called/referred in a function, Ballerina throws this error when there are large set of constants defined somewhere in the code (even in a separate `.bal` file)

### Affected Version(s)

Ballerina distributions: _2201.1.2_,  _2201.2.3_

### OS, DB, other environment details and versions

Ubuntu 20.04

### Related area

-> Compilation

### Related issue(s) (optional)

#38796

**Comment by gabilang** [comment]
Since all the type reference type constants initialization have been added to a single `init` method of the generated constant class, method too large will be thrown when a module has large number of constants. So moving them into separate `bal` files won't fix the issue in your case. 
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/39019 
This issue will be resolved with the PR https://github.com/ballerina-platform/ballerina-lang/pull/39113

**Comment by AnjanaSenanayake** [comment]
Hi @gabilang @warunalakshitha, have we released this fix with Ballerina Update 4. Just to verify (Since we noticed that the issue persists in Update 4 as well)

**Comment by gabilang** [comment]
Yes, Fixes fot the ClassTooLarge and MethodTooLarge issues have been added with 2201.4.0. Are you getting method too large issue with the same stacktrace as above?
