### ISSUE TITLE
[Bug]: NPE in ConvertToQueryExpressionCodeAction

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#38980]
### Description

A NullPointerException is thrown at the following cursor position,
<img width="1181" alt="Screenshot 2022-12-07 at 22 29 37" src="https://user-images.githubusercontent.com/61020198/206242802-b2a4041e-56a4-4783-94f2-de7b5d821167.png">

### Steps to Reproduce

```
type User record {|
    string name;
    string age;
|};

function name() {
    User u<cursor>
}
```

### Related area

-> Editor

**Comment by IMS94** [comment]
Sames happens for 
```
public function main() {
    var ob<cursor>
}
``
