### ISSUE TITLE
[Bug]: Ballerina bindgen not support for custom maven repositories.

### ISSUE THREAD

**Issue by tharindu1st** [ballerina-platform/ballerina-lang#38994]
### Description

When bindgen  ava code which contains dependencies from custom maven repository. it's not retrieve from there due to hardcoded repositories.
https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/maven-resolver/src/main/java/org/ballerinalang/maven/MavenResolver.java#L80-L87

### Affected Version(s)

2201.3.0

### OS, DB, other environment details and versions

UBUNTU

### Related area

-> Other Area

**Comment by keizer619** [comment]
This is fixed in following PR
https://github.com/ballerina-platform/ballerina-lang/pull/39659
