### ISSUE TITLE
[Bug]: Native Image build is not working on Mac with Apple M1 chip

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#39003]
### Description

The `bal build --native` command is giving the following error while building the native-image :
```
Error: Darwin native toolchain (x86_64) implies native-image target architecture class 
jdk.vm.ci.amd64.AMD64 but configured native-image target architecture is class jdk.vm.ci.aarch64.AArch64.
```

But when the `native-image` command is run separately with the generated jar, it is working without any issues

> **Note:** This may be due to the java JDK used by ballerina to build the jar file. That JDK is for `x86_64` architecture (see the OS details below) and the native-image tool is installed for `arm64` architecture. For more information check this [issue comment](https://github.com/oracle/graal/issues/4694#issuecomment-1174636233)

### Steps to Reproduce

- Create a simple ballerina package using `bal new hello`
- Run the `bal build --native` command inside the `hello` package

### Affected Version(s)

Ballerina SwanLake 2201.3.0

### OS, DB, other environment details and versions

OS : Mac OS Ventura
Chip : Apple M1
Architecture : arm64 (aarch64)

Additional info :
```console
$ arch
arm64
```
```console
$ cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```console
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
```console
$ echo $GRAALVM_HOME
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0/Contents/Home
```
```console
$ java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08, mixed mode)
```
```console
$ file $GRAALVM_HOME/bin/native-image
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0/Contents/Home/bin/native-image: Mach-O 64-bit executable arm64
```
```console
// The jdk used by bal command
$ file /Library/Ballerina/dependencies/jdk-11.0.15+10-jre/bin/java 
/Library/Ballerina/dependencies/jdk-11.0.15+10-jre/bin/java: Mach-O 64-bit executable x86_64
```

### Related area

-> Runtime

**Comment by Thevakumar-Luheerathan** [comment]
This issue is not reproducible. Both Ventura, Monterey mac os versions were checked

**Comment by TharmiganK** [comment]
May be the issue is with the xcode. I'll try a fresh install and will close this issue if this is not reproducing 👍

**Comment by MohamedSabthar** [comment]
I'm getting the same error on macOS Monterey

**Comment by pcnfernando** [comment]
Facing the same. @TharmiganK how did you resolve it?

**Comment by TharmiganK** [comment]
> Facing the same. @TharmiganK how did you resolve it?
I have not resolved it yet, planning to do a fresh install

@Thevakumar-Luheerathan @azinneera can you guys check on this?

@pcnfernando if you want to build the native-image locally, there is a workaround to use `native-image` command rather than `bal build --native`. You can follow the following instructions :
1. Use `bal build` to generate the jar file. The jar file will be created in the `target/bin` directory.
2. Run the following command to generate the native image :
```
native-image -jar target/bin/<jar-file> --no-fallback
```
 This will generate the native executable.

**Comment by Thevakumar-Luheerathan** [comment]
@pcnfernando @MohamedSabthar  @TharmiganK This error seems to be due the packed `jdk-11.0.15+10-jre` version with Ballerina. Renaming/Removing the `jdk-11.0.15+10-jre` makes the `bal build --native` work(Ballerina takes `jdk-11.0.8+10-jre` as default `JAVA_HOME`).

**Comment by TharmiganK** [comment]
@Thevakumar-Luheerathan from Update 3, ballerina only packs `jdk-11.0.15+10-jre`, and ballerina only adds the JRE based on the OS type, and not based on the architecture. So even for a Mac with `aarch64` architecture, the ballerina packs the JRE compatible with `x86_64`. This might be the reason for this issue.

Did the following experiments :
1. Pulled ballerina - `2201.2.0` to get `jdk-11.0.8+10-jre` and renamed existing  `/Library/Ballerina/dependencies/jdk-11.0.15+10-jre`. This will use `jdk-11.0.8+10-jre` for ballerina build. Then tried `bal build --native` after changing back to  `2201.3.0`.
    > **Note**: The `jdk-11.0.8+10-jre` is from `OpenJDK` and the existing `jdk-11.0.15+10-jre` is from `Zulu`.

2. Download [Mac `aarch64` compatible JRE](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.15_10.tar.gz) and unpack the tar file. Since the lib folders(including `bin`) are inside the `Contents/Home` directory we need to move them to the root directory of the unpacked JRE (since ballerina does not consider about  `Contents/Home` directory). Replace `/Library/Ballerina/dependencies/jdk-11.0.15+10-jre` with the downloaded one. Then tried `bal build --native`
   > **Note**: The downloaded `jdk-11.0.15+10-jre` is from `Temurin`.

For both cases, the native build worked without an issue. So the issue might be related to the changes after `jdk-11.0.8+10-jre` (I think after this version they have supported `aarch64` separately). But not sure about the root cause.

So, I could think of the following fixes :
1. Use the user's JRE to generate the byte code when the `--native` flag is used. This can be done by accessing the `GRAALVM_HOME` environment variable, which is already a prerequisite for native builds. This will make sure we are using the same JRE to generate the byte code and the executable.
2. Pack JRE based on the architecture. This requires a new version of [`ballerina-custom-jre`](https://github.com/ballerina-platform/ballerina-custom-jre).
3. If we are packing the graalvm JRE for Update 4, then we don't need `GRAALVM_HOME` anymore. And there is no more JRE architecture changes since we use the same JRE to generate the byte code and the executable. But in that case we have to think about whether we should pack the graalvm JRE based on architecture or not.

**Comment by TharmiganK** [comment]
Closing this issue as this is now resolved with the new installer
