### ISSUE TITLE
[Bindgen Tool] Generated Ballerina binding for `java.lang.String` parameters doesn't allow passing nil values

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#39059]
### Description

Consider the following Java method and the counterpart Ballerina function generated using the bindgen tool

- Java method
  ```java
  public void testFunction(String param) {
  }
  ```

- Generated ballerina function
  ```ballerina
  public function testFunction(string param)  {
  }
  ```

As per the generated function signature, it doesn't allow passing nil values to the function. This could be problematic if the underlying Java function has logic depending on the parameter being null, as the that scenario won't be supported through Ballerina. 

### Related area

-> Bindgen Tool

### Related issue(s) (optional)

Refer to https://discord.com/channels/957996897782616114/1052287921253798009/1052287921253798009 for the related discord discussion.

**Comment by sameerajayasoma** [comment]
It looks like the Bingen tool generates `string?` as the return type if the Java method returns a `java.lang.String`. 

```java
public String testFunction(String testParam) {
   // Do something.
}
```
```ballerina
public function testFunction(string arg0) returns string?{
  // Do something.
}
```

I agree that this is inconsistent.

**Comment by NipunaRanasinghe** [comment]
@sameerajayasoma Thanks for your input. So based on our discord discussion as well, it seems we have the following 2 options to rectify the current behaviour.

**Option 1:**  Map java String to Ballerina `string?` type(which will be consistent with how generate bindings for the return types)

**Option 2:**  Map java String to Ballerina `handle` type and provide the related string conversion utils via `ballerina/java` library (as proposed in the initial design doc https://docs.google.com/document/d/1hlKSd-tQQfr8tJVvHUor7zOIqHbztqu2jqihnK7IUhw/edit?usp=sharing)


IMO option 1 would make more sense, as it will be aligned with existing the return type generation and, it will also eliminate the requirement of having separate util functions to be used for the conversion between `string` and `handle` datatypes. @sameerajayasoma @hevayo Appreciate if you could confirm.

**Comment by sameerajayasoma** [comment]
I prefer option 1

**Comment by NipunaRanasinghe** [comment]
@sameerajayasoma thanks for your input. We'll proceed accordingly

**Comment by NipunaRanasinghe** [comment]
Closing as this will be addressed with https://github.com/ballerina-platform/ballerina-lang/issues/39434
