### ISSUE TITLE
[Bug]: `function` keyword suggested annotation context

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#39072]
### Description

Consider
```ballerina
import ballerina/module1;

public type AnnotationType record {
    string foo;
    int bar?;
};

public const annotation AnnotationType sourceVarAnnotation1 on source var;

public const annotation sourceVarAnnotation2 on source var;

@<cursor>
int testModuleVar = 12;
```
At cursor, we suggest the `function` keyword. It's not relevant to that context. Also double check the completions we provide at annotation context.
![annot_completions](https://user-images.githubusercontent.com/11285165/207843294-4d7354d7-b0a1-4be8-972f-c18cd00bb830.gif)

### Related area

-> Editor

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
