### ISSUE TITLE
[Improvement]: Weird error messages when test suite fails to run

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#39095]
### Description

It seems if the test runner fails, it gives the error message in the form `error: Dependant module initialization for test suite failed due to` + `<error message from the cause>`. For example, this is an error message that I got:
```
error: Dependant module initialization for test suite failed due to Something wrong with the connection
```
This does not look the best of error messages. It's better if this error reporting strategy can be improved. 

### Related area

-> Test Framework

**Comment by azinneera** [comment]
The error message `Something wrong with the connection` comes from the package implementation. Please open the issue in the  relevant package repository if it is still reproducible.
