### ISSUE TITLE
GraalVM Check hanging on windows

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#39121]
**Description:**
$Subject
https://github.com/ballerina-platform/module-ballerina-graphql/actions/runs/3726081024/jobs/6325349177
https://github.com/ballerina-platform/module-ballerina-websub/actions/runs/3726095656/jobs/6323818686
https://github.com/ballerina-platform/module-ballerina-file/actions/runs/3726088365/jobs/6325379520

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@TharmiganK

**Comment by Thevakumar-Luheerathan** [comment]
I removed those PR merge done (between 12-12-2022 and 14-12-2022) one by one and checked the impact on the workflow.  https://github.com/ballerina-platform/ballerina-lang/pull/38986 PR seems causing the issue. I reverted that the changes done on that PR. [Workflow is passing fine.](https://github.com/Thevakumar-Luheerathan/module-ballerina-websub/actions/runs/3873081772).

**Comment by TharmiganK** [comment]
May be the issue is with `IOUtils.copy` method. Seems like [it can hang when copying larger streams](https://stackoverflow.com/questions/25038912/ioutils-copy-hangs-when-copying-big-stream).

@Thevakumar-Luheerathan What is the reason to use that method?

**Comment by Thevakumar-Luheerathan** [comment]
> May be the issue is with `IOUtils.copy` method. Seems like [it can hang when copying larger streams](https://stackoverflow.com/questions/25038912/ioutils-copy-hangs-when-copying-big-stream).
> 
> @Thevakumar-Luheerathan What is the reason to use that method?

We needed that method to test the native implementation. From the native test cases, we are passing a custom printStream. We need all the logs to be copied to that stream to verify the image output. I am currently trying to replace the `IOUtils.copy` with a streamGobbler which uses a separate thread to copy the subprocess stream to given printStream line by line.

**Comment by TharmiganK** [comment]
> > May be the issue is with `IOUtils.copy` method. Seems like [it can hang when copying larger streams](https://stackoverflow.com/questions/25038912/ioutils-copy-hangs-when-copying-big-stream).
> > @Thevakumar-Luheerathan What is the reason to use that method?
> 
> We needed that method to test the native implementation. From the native test cases, we are passing a custom printStream. We need all the logs to be copied to that stream to verify the image output. I am currently trying to replace the `IOUtils.copy` with a streamGobbler which uses a separate thread to copy the subprocess stream to given printStream line by line.

If we are using it only for test purposes, having it in the main source is really odd right?

**Comment by Thevakumar-Luheerathan** [comment]
It is not only for test purpose. Having this `IOUtils.copy` covers both test requirement and normal usage requirement. There is another option (`builder.inheritIO()`) can be used (windows is running without any issue with that method call). But, with that, generated image output can not be validated.
