### ISSUE TITLE
[Bug]: Foreach completion items not suggested for iterables in return statement context

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#39149]
### Description

![image](https://user-images.githubusercontent.com/35211477/208964542-a9737371-8d8d-4e3e-8f44-d768246896b5.png)

`foreach` abd 'foreach i` completion items are not suggested at the above cursor position.

### Steps to Reproduce

```Ballerina
import ballerina/http;

type Kind "dog"|"cat"|"other";

type Pet record {|
    string name;
    int age;
    Kind kind;
|};

service /pets on new http:Listener(9090) {
    Pet[] pets = [];

    resource function post .(@http:Payload Pet pet) {
        int|string a = 10;
        self.pets.push(pet);
    }

    resource function get dogs() returns Pet[] {
        return self.pets.filter((pet) => pet.kind == "dog");
    }

    resource function get dog(string name) returns Pet {
        return self.pets.f<cursor>
    }

}
```

### Affected Version(s)

2201.3.1

### Related area

-> Editor

**Comment by IMS94** [comment]
@malinthar here we anyway cannot suggest that right?

**Comment by malinthar** [comment]
> @malinthar here we anyway cannot suggest that right? Because if we provide, we will have to add the `foreach` statement before the `return` statement and, what should be the value we return in the return statement?
> 
> Also, `foreach` statement, doesn't return anything. Therefore, it's invalid in a return statement. WDYT?

Agreed! We can close this issue
