### ISSUE TITLE
[Bug]: Annotations are not passed in the type if the type is readonly

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#39156]
### Description

The field level annotations are not passed with the type when the type is readonly. Due to this `constraint:validate()` method is not able to validate the constraints. 

Related to : https://github.com/ballerina-platform/ballerina-standard-library/issues/3742

### Steps to Reproduce

See the following code :

```ballerina
import ballerina/io;
import ballerina/constraint;

type Album readonly & record {|
    @constraint:String {
        maxLength: 5,
        minLength: 1
    }
    string title;
    string artist;
|};

public function main() returns error? {
    Album a = {
        artist: "test",
        title: "testss"
    };
    Album validAlbum = check constraint:validate(a);
    io:println(validAlbum);
}
```

The `<AnnotatableType>.getAnnotations()` is `null` when the record is `readonly`. If we remove `readonly`, we can get the annotations.

### Affected Version(s)

Ballerina SwanLake 2201.2.x
Ballerina SwanLake 2201.3.x

### Related area

-> Runtime

**Comment by MaryamZi** [comment]
Don't you get the intersection type for `Album` as the argument for `td`? How are you retrieving the annotations from it?

**Comment by TharmiganK** [comment]
> Don't you get the intersection type for `Album` as the argument for `td`? How are you retrieving the annotations from it?

Yes, `Album` is intersection type but the annotation is not there even if we get the effective type from the intersection.

**Comment by MaryamZi** [comment]
> > Don't you get the intersection type for `Album` as the argument for `td`? How are you retrieving the annotations from it?
> 
> Yes, `Album` is intersection type but the annotation is not there even if we get the effective type from the intersection.

I think not having it in the effective type is correct. You should be able to get the constituent types of the intersection type (`io.ballerina.runtime.api.types.IntersectionType#getConstituentTypes`), get the anonymous record type, and then retrieve the annotations from the record type.

**Comment by TharmiganK** [comment]
> > > Don't you get the intersection type for `Album` as the argument for `td`? How are you retrieving the annotations from it?
> > 
> > 
> > Yes, `Album` is intersection type but the annotation is not there even if we get the effective type from the intersection.
> 
> I think not having it in the effective type is correct. You should be able to get the constituent types of the intersection type (`io.ballerina.runtime.api.types.IntersectionType#getConstituentTypes`), get the anonymous record type, and then retrieve the annotations from the record type.

Ok, I'll try. 

But in this case the intersection is between `readonly` and the target type, so passing the annotation in this case is ok right? Shouldn't we treat this particular case separately?

**Comment by MaryamZi** [comment]
> 

We use the concept of an effective type for typing (since the types of the fields are different from the constituent types). We don't copy metadata.

Copying metadata won't work anyway with say an intersection of two records (which we don't support yet).

```ballerina
annotation record { int min; } annot on record field;

type Foo record {|
    @annot {
        min: 100
    }
    int|string a;
|};

type Bar record {|
    @annot {
        min: 200
    }
    int|float a;
|};

type Baz Foo & Bar; // effectively `record {| int a; |}`
```

The intersection represents all the values that belong to both `Foo` and `Bar`, and the metadata isn't considered for that.

cc @rdulmina

**Comment by TharmiganK** [comment]
@MaryamZi I have tried to get the annotations from the constituent types of the intersection type **but still it is empty**. (The `Album` type is obtained as a `TypeReferenceType` and I got the referred type to obtain the constituent types)
<img width="1005" alt="Screen Shot 2023-01-04 at 8 57 23 AM" src="https://user-images.githubusercontent.com/63336800/210479891-62ad6fce-db79-4b9a-bf2f-2025f52c5c7e.png">


When I remove the `readonly`, I could see the annotations
<img width="1005" alt="Screen Shot 2023-01-04 at 8 58 56 AM" src="https://user-images.githubusercontent.com/63336800/210480246-62ab75b7-a144-43cc-b0e1-019e29059862.png">

**Comment by MaryamZi** [comment]
The annotations are available in the global annotation map, but seems like the look up in `io.ballerina.runtime.internal.AnnotationUtils#processAnnotations` is done with a different annotation key.

```ballerina
import ballerina/constraint;

type InlineAlbum readonly & record {|
    @constraint:String {
        minLength: 1
    }
    string title;
    string artist;
|};
```

`((BmpStringValue) annotationKey).value` - `record {| string title; string artist; |}`
`((BmpStringValue) Arrays.stream(globalAnnotMap.getKeys()).iterator().next()).value` - `$anonType$InlineAlbum$_0`

@HindujaB, @warunalakshitha, any thoughts on this? Using the shape will not work when we have multiple anonymous records with the same shape, right? This should probably be solved with @chiranSachintha's changes though. Since we will be avoiding this look up.

@TharmiganK, a workaround for the time-being would be to avoid the anonymous record.

```ballerina
import ballerina/constraint;

type MutableAlbum record {|
    @constraint:String {
        maxLength: 5,
        minLength: 1
    }
    string title;
    string artist;
|};

type Album readonly & MutableAlbum;
```

**Comment by HindujaB** [comment]
I checked with the following code. 
```ballerina
import ballerina/constraint;

type InlineAlbum readonly & record {|
    @constraint:String {
        minLength: 1
    }
    string title;
    string artist;
|};

type MutableAlbum record {|
    @constraint:String {
        maxLength: 5,
        minLength: 1
    }
    string title;
    string artist;
|};

type InlineAlbum MutableAlbum & readonly;

public function main() returns error? {
    MutableAlbum a = {
        artist: "testA",
        title: "testssA"
    };
    MutableAlbum validAlbum = check constraint:validate(a); 
    // key in the global map - MutableAlbum
    // key used to set annotations - MutableAlbum

    InlineAlbum b = {
        artist: "testB",
        title: "testssB"
    };
    InlineAlbum validAlbum2 = check constraint:validate(b);
    // key in the global map - $anonType$InlineAlbum$_0 
    // key used to set annotations - InlineAlbum
}
```
Concern 1 :
Here, shouldn't we have `InlineAlbum` as the annotation key in the global map? @MaryamZi 
I'm assuming that we can't have different annotations between the `InlineAlbum` record and the `InlineAlbum` intersection types in this case.  

Concern 2 :
When we populate annotations to the types, the annotation key is retrieved from the `typeName` of the relevant type. We use the shape of the record only if there's no user-defined type name. 
This only happens in the inline record cases. 
```ballerina
record {|
    @constraint:String {
        maxLength: 5,
        minLength: 1
    }
        string title;
        string artist;
    |} c = {
        artist: "testC",
        title: "testssC"
    };
```
In this case, the annotation key passed in the global map is `$anonType$$c$$_0` and the type-name is `record {| string title; string artist; |}`.
This can cause inconsistencies if multiple inline records with different annotations and similar shapes are defined. We should pass the `$anonType$$c$$_0` key and use that to populate annotations to the types. 

What would be the behavior with @chiranSachintha's changes with typedesc? Are we verifying the annotation keys with type-names?

**Comment by MaryamZi** [comment]
> I checked with the following code.
> 
> ```ballerina
> import ballerina/constraint;
> 
> type InlineAlbum readonly & record {|
>     @constraint:String {
>         minLength: 1
>     }
>     string title;
>     string artist;
> |};
> 
> type MutableAlbum record {|
>     @constraint:String {
>         maxLength: 5,
>         minLength: 1
>     }
>     string title;
>     string artist;
> |};
> 
> public function main() returns error? {
>     MutableAlbum a = {
>         artist: "testA",
>         title: "testssA"
>     };
>     MutableAlbum validAlbum = check constraint:validate(a); 
>     // key in the global map - MutableAlbum
>     // key used to set annotations - MutableAlbum
> 
>     InlineAlbum b = {
>         artist: "testB",
>         title: "testssB"
>     };
>     InlineAlbum validAlbum2 = check constraint:validate(b);
>     // key in the global map - $anonType$InlineAlbum$_0 
>     // key used to set annotations - InlineAlbum
> }
> ```
> 
> Concern 1 : Here, shouldn't we have `InlineAlbum` as the annotation key in the global map? @MaryamZi I'm assuming that we can't have different annotations between the `InlineAlbum` record and the `InlineAlbum` intersection types in this case.
> 

No, the annotations are specified on the anonymous record, not on `InlineAlbum`. So it should be associated with the record, not the intersection. Also see https://github.com/ballerina-platform/ballerina-lang/issues/39156#issuecomment-1369704594.

Also, isn't the shape the key here? Rather than `InlineAlbum`?

> Concern 2 : When we populate annotations to the types, the annotation key is retrieved from the `typeName` of the relevant type. We use the shape of the record only if there's no user-defined type name. This only happens in the inline record cases.
> 
> ```ballerina
> record {|
>     @constraint:String {
>         maxLength: 5,
>         minLength: 1
>     }
>         string title;
>         string artist;
>     |} c = {
>         artist: "testC",
>         title: "testssC"
>     };
> ```
> 
> In this case, the annotation key passed in the global map is `$anonType$$c$$_0` and the type-name is `record {| string title; string artist; |}`. This can cause inconsistencies if multiple inline records with different annotations and similar shapes are defined. We should pass the `$anonType$$c$$_0` key and use that to populate annotations to the types.
> 
> What would be the behavior with @chiranSachintha's changes with typedesc? Are we verifying the annotation keys with type-names?

With Chiran's change we will be passing the annotations directly when resolving the typedesc, and there won't be a look up based on the name. So, I believe this should get resolved.

**Comment by HindujaB** [comment]
As per the offline discussion with @TharmiganK, the fix is needed in the `3.x` and update 4. And the workaround provided may complicate the BBE use case. 
Therefore, I added a runtime fix to use the internal name to retrieve the annotations.
