### ISSUE TITLE
[Bug]: Field access completions are not working for `regexp`

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#39183]
### Description

$subject. 
<img width="881" alt="Screenshot 2023-01-05 at 12 04 32" src="https://user-images.githubusercontent.com/46857198/210716791-37ab997e-9278-4ef1-874a-950631cc8e45.png">

The completion list must contain other necessary accessible methods.

### Affected Version(s)

Master

### Related area

-> Editor

**Comment by IMS94** [comment]
Related issue #39289

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/39336
