### ISSUE TITLE
[Improvement]: Can't infer the dependently-typed inside the query expression

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#39191]
### Description

Here foo is a SQL connector. 
```
Employee[] employees = check from var emp in foo->query(`SELECT * FROM employees`) select emp;
```
and it gives `cannot infer type for parameter 'rowType'`

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Spec issue: https://github.com/ballerina-platform/ballerina-spec/issues/1208

**Comment by hasithaa** [comment]
We are closing this issue since this is tracked in the spec.
