### ISSUE TITLE
[Bug]: JSON with backticks are not properly escaped on string conversion. 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#39216]
### Description

$subject. Check with the sample code below.

### Steps to Reproduce

Code to reproduce the issue.

```ballerina
import ballerina/io;

public function main() {
    json j = {
        "resultCount": 50,
        "results": [
            {
                "wrapperType": "track",
                "longDescription": "The year's biggest action-adventure is coming home with a vengeance! Brendan Fraser and an all-star cast reunite with Stephen Sommers for explosive, non-stop thrills in \"the ultimate rollercoaster movie ride!\" (Seattle Post Intelligencer)"
            }
        ]
    };
    io:println(j);
}
```

Current output  : This is an invalid JSON as escape characters are missing.

```
{"resultCount":50,"results":[{"wrapperType":"track","longDescription":"The year's biggest action-adventure is coming home with a vengeance! Brendan Fraser and an all-star cast reunite with Stephen Sommers for explosive, non-stop thrills in "the ultimate rollercoaster movie ride!" (Seattle Post Intelligencer)"}]}
```

Expected output:

```
{"resultCount":50,"results":[{"wrapperType":"track","longDescription":"The year's biggest action-adventure is coming home with a vengeance! Brendan Fraser and an all-star cast reunite with Stephen Sommers for explosive, non-stop thrills in \"the ultimate rollercoaster movie ride!\" (Seattle Post Intelligencer)"}]}
```

### Affected Version(s)

2201.3.0

### Related area

-> Compilation

**Comment by manuranga** [comment]
Let's cover a conformance test suite (eg: https://github.com/nst/JSONTestSuite) to catch issues proactively.

**Comment by MaryamZi** [comment]
`io:println` calls `value:toString` (https://lib.ballerina.io/ballerina/lang.value/0.0.0/functions#toString) on the value, which corresponds to the "ToString abstract operation defined in the Ballerina Language Specification, using the direct style" (https://ballerina.io/spec/lang/master/#ToString).

If you need a string that complies with the JSON format, you need to use `value:toJsonString` (https://lib.ballerina.io/ballerina/lang.value/0.0.0/functions#toJsonString).

Output when `value:toJsonString` is used:

```
{"resultCount":50, "results":[{"wrapperType":"track", "longDescription":"The year's biggest action-adventure is coming home with a vengeance! Brendan Fraser and an all-star cast reunite with Stephen Sommers for explosive, non-stop thrills in \"the ultimate rollercoaster movie ride!\" (Seattle Post Intelligencer)"}]}
```

**Comment by hasithaa** [comment]
This is not a bug. This is expected behavior since io:println also use the toString operation.
