### ISSUE TITLE
[Improvement]: Refactor enpoint for get definition by position

### ISSUE THREAD

**Issue by axewilledge** [ballerina-platform/ballerina-lang#39220]
### Description

Refactor the code to use workspaceManagerProxy.get(fileUri) method instead of using the get() method

### Related area

-> Compilation

**Comment by hasithaa** [comment]
Please add more details to the issue.

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
