### ISSUE TITLE
[Improvement]: Add rename pop-up for extract type code action

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#39246]
### Description

![Peek 2023-01-13 08-47](https://user-images.githubusercontent.com/35211477/212229493-35173e5b-15f0-4f2b-a11f-067a106cddcd.gif)

As depicted above the rename pop-up could be useful for the users with extract type code action. 

### Related area

-> Editor

**Comment by mindula** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/39253

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
