### ISSUE TITLE
[Bug]: Need to improve SymbolFinder logic to comply with new tuple-member structure

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#39263]
### Description

```
const <1>A = "AA";
A <2>a = <3>A;

type TTT [@annot int, <4>A];
```

Here is the impact for the user:
Here, if we rename the `A` by positioning the cursor on <1> or <2> or <3>, It renames <1>, <2>, <3>, and <4>.
But if we try to rename `A` in <4>, it only renames <4>. 

Reason:
When we look up `A` in <1>, <2>, <3>, we consider the `ConstantSymbol` we get and compare it with each other symbols we get in all the locations. But, when we look up <4>, we compare the `TupleMember` symbol with `ConstantSymbol`.

### Possible approach to solve
We need to consider the singleton-type symbol/ constant symbol in SymbolFinder logic

### Steps to Reproduce

```
const <1>A = "AA";
A <2>a = <3>A;

type TTT [@annot int, <4>A];
```

Try renaming `A` in <4>

### Related area

-> Compilation

**Comment by dulajdilshan** [comment]
Impact on the VScode plugin user due to this:
- The new name of the tuple member doesn't reflect in the type-def or constant
Ex: 
```
const A = "aa:;
type Tup [A, int];
```
or
```
type IntType int;
type Tup [IntType, int];
```

- Go to def will not work from the tuple-member
- `references()` is not working. (Only shows itself as the reference)

**Comment by dulajdilshan** [comment]
The same kind of scenario can be observed in variables defined with the function type as follows.
```
annotation record {int x;} annot on parameter;

type Foo int;

public function main() {
    function (@annot { x: 0 } Foo) f;
}
```
But here, when we are finding the symbol in `Foo` at param in function-type, we get the Foo type-definition. Here, we don't have any way to get the annotations (the param variable owns the annotation attachments, not the type here)

**Comment by dulajdilshan** [comment]
Had a live chat with @hasithaa @MaryamZi @IMS94 on this, It is concluded that we refactor semantic API as follows;

- Cursor at tuple member and calling `symbol()` will give the type-symbol as we did previously (before the tuple annotation change). With this, we will not be able to get the annotation attached to the tuple-member
- `members()` API can be called in the tuple type and we can get the annotation attached to the tuple-members

**Comment by MaryamZi** [comment]
> * Cursor at tuple member and calling `symbol()` will give the type-symbol as we did previously (before the tuple annotation change). With this, we will not be able to get the annotation attached to the tuple-member

Shall we create a separate issue for this, though? Please mention the behaviour for function parameters when there's no parameter name (vs the return type) also.

**Comment by dulajdilshan** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39298
