### ISSUE TITLE
[Bug]: [Project Design Diagrams] Incorrect file paths retrieved for services residing in non-default modules 

### ISSUE THREAD

**Issue by SumayyaZiyad** [ballerina-platform/ballerina-lang#39273]
### Description

$subject.

Refer the sample below where the service resides in the ZonalForecast.bal file of the ZonalForecast non-default module.

<img width="305" alt="Screenshot 2023-01-17 at 10 03 35 AM" src="https://user-images.githubusercontent.com/36619740/212810775-1c8374be-0f12-4572-b112-b0a6ed332c07.png">

The absolute file path of this service is retrieved as follows.

<img width="946" alt="Screenshot 2023-01-17 at 10 03 13 AM" src="https://user-images.githubusercontent.com/36619740/212810789-465e4da0-68cc-42ec-851b-02eea4cb5fff.png">

This affects the go-to-source functionality of the project design diagrams generator.

### Affected Version(s)

Detected on 2201.3.1

### Related area

-> Other Area

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/ballerina-lang/pull/39275 and https://github.com/ballerina-platform/ballerina-dev-tools/pull/162
