### ISSUE TITLE
[Bug]: Parser recovers incorrectly for unicode property escape in regexp

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#39277]
### Description

 ```
 regexp:RegExp r = re `\p{<cursor>}`;
 ```
In the above case parse recovers by giving an invalid missing location. Even the close bracket is present in the node it gives as it is not present.

<img width="1139" alt="Screenshot 2023-01-17 at 12 33 00" src="https://user-images.githubusercontent.com/46857198/212831422-32e31146-50e6-45ad-947f-13e8e46764de.png">

### Affected Version(s)

Master - Update 4

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
There is another case similar to this. 

```
regexp:RegExp r = re `\p{gc=<cursor>}`;
```
<img width="1147" alt="Screenshot 2023-01-17 at 17 35 32" src="https://user-images.githubusercontent.com/46857198/212894607-3fc3b5f7-fef2-4bf2-b939-b95d17b4c436.png">

If we look at the parent of this `ReUnicodeGeneralCategoryNode` it shows `\p{gc=} MISSING[)]`.

It is better if the parser can identify and recover as `\p{gc=MISSING[]}`.

**Comment by pcnfernando** [comment]
These issues seem to have been fixed during the parser refactoring we did with https://github.com/ballerina-platform/ballerina-lang/pull/39211 which brought some lexer logic to parser level.
We have yet to update some error messages

**Comment by mohanvive** [comment]
Need to verify with the latest change and close this.

**Comment by LakshanWeerasinghe** [comment]
Parser recovered in the expected way. Hence closing the issue.

<img width="1297" alt="Screenshot 2023-02-23 at 14 48 10" src="https://user-images.githubusercontent.com/46857198/220866253-92a964d7-31d9-41a0-abe9-626b2bf9fc8e.png">

<img width="1282" alt="Screenshot 2023-02-23 at 14 48 56" src="https://user-images.githubusercontent.com/46857198/220866272-b0325740-ab56-4234-b9e1-2087035778cc.png">
