### ISSUE TITLE
[Bug]: Support regex completions when regex referred via string langlibs

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#39289]
### Description

It seems, regex langlib related tooling completions are not working for the below cases. 

```
public function main() {
    string str2 = "Ballerina is great";
    string:RegExp regExpr2 = re `Ba[a-z ]+`;

    regExpr2.<cursor>
}
```

<img width="571" alt="Screenshot 2023-01-18 at 10 54 39" src="https://user-images.githubusercontent.com/7523274/213091310-0338a18e-ac58-4fc0-bd99-84873c643a16.png">

### Related area

-> Compilation

**Comment by mohanvive** [comment]
Same, applies when functions are accessed when having `import ballerina/lang.regexp;` import.

**Comment by IMS94** [comment]
Blocked by #39336
