### ISSUE TITLE
[Improvement]: Allow integer references inside ReBaseQuantifier in regex

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#39286]
### Description

Consider the following code sample

```
public function main() {
  string a = "1";
  string:RegExp x3 = re `AB+C*D{${a}}`; // ERROR: invalid quantifier in regular expression
  string:RegExp x4 = re `AB+C*D{1}`; // Works fine
}
```

It is better if we can allow integer references inside this regex.

### Related area

-> Compilation

**Comment by lasinicl** [comment]
According to the spec, an interpolation is allowed where a `ReAtom` is allowed. Hence, the above error.

**Comment by SasinduDilshara** [comment]
It is decided that we don't need to add integer references to the grammar. Hence closing the issue
