### ISSUE TITLE
[Bug]: Progress bar for pulling packages has hard coded info

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#39293]
### Description

See https://github.com/ballerina-platform/ballerina-lang/blob/a5b744cf2fde4505ebc2c598b5edf8f077d08f22/cli/central-client/src/main/java/org/ballerinalang/central/client/Utils.java#L288

Here, the info about the source location and the target location for the package are hard coded. This is misleading when you are working with different Central environments and home repos. Instead of this, it'd be better if this showed the actual source and target locations. e.g., `staging-central.ballerina.io`

For the target location, if it's the default home repo, then it's fine to name it as `home repo`. But if it's a custom location, best to print the actual location instead of saying `home repo`.

### Related area

-> Central

**Comment by ShammiL** [comment]
Noticed and fixed similar hard-coded information in the progress bar for pushing packages.
