### ISSUE TITLE
[Bug]: LS suggests some invalid completions for Regex constructs

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#39292]
### Description

Consider below image, it suggests methods such as `toString` and `toBalString`. But compiler gives error when those methods are added. 

<img width="714" alt="Screenshot 2023-01-18 at 12 30 42" src="https://user-images.githubusercontent.com/7523274/213105578-8cea3204-a236-4f43-a948-fbdcd4d29b2a.png">

### Related area

-> Compilation

**Comment by pcnfernando** [comment]
This seems to be a generic issue for `readonly`, `object` intersection
<img width="703" alt="Screenshot 2023-01-30 at 11 54 42" src="https://user-images.githubusercontent.com/15815199/215403623-e88203db-7318-4e5d-ac21-c93f8432bfa6.png">

**Comment by malinthar** [comment]
> This seems to be a generic issue for `readonly`, `object` intersection <img alt="Screenshot 2023-01-30 at 11 54 42" width="703" src="https://user-images.githubusercontent.com/15815199/215403623-e88203db-7318-4e5d-ac21-c93f8432bfa6.png">

I observed that the issue with how we handle intersection types in the langlibmethods() API. It should provide the langlibmethods of the effective type when there is an intersection type.

**Comment by malinthar** [comment]
Blcoked by https://github.com/ballerina-platform/ballerina-lang/issues/39485
