### ISSUE TITLE
[Task]: Unify snippet completions for templated expression

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#39290]
### Description

We could observe regex templated expression snippet suggested as shown below. But there is no snipper suggestions for other templated expressions. 

<img width="606" alt="Screenshot 2023-01-18 at 10 59 57" src="https://user-images.githubusercontent.com/7523274/213093613-cb90b596-60ae-444c-b698-bb9e0a8a45c5.png">

### Related area

-> Compilation

**Comment by IMS94** [comment]
Related issue #38804. We can address both with this.
