### ISSUE TITLE
[Bug]: NPE after `annotations` module prefix

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#39318]
### Description

Consider the following scenario,

<img width="1197" alt="Screenshot 2023-01-20 at 13 56 29" src="https://user-images.githubusercontent.com/61020198/213650099-362273bf-8c79-455c-b896-82dc7b37fe11.png">

### Steps to Reproduce

```
import ballerina/lang.annotations;

function test() {
    annotations:<cursor>
}
```

### Related area

-> Editor

**Comment by IMS94** [comment]
Here the `BallerinaFunctionTypeSymbol.returnTypeDescriptor()` throws the NPE since the `typeSymbol` is null inside the `FunctionTypeSymbol`. Happens for the following function symbol:
```ballerina
function (int:Unsigned8,int:Unsigned8) returns (object { public isolated function iterator () returns (object { public isolated function next () returns (record {| int value; |}?); }); })
```
