### ISSUE TITLE
[Bug]: Runtime error when trying to create an error value when a detail field's name has identifier escapes

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#39322]
### Description

$title.

### Steps to Reproduce

```ballerina
public function main() {
    error<record {| int err\:code; |}> e = error("error!", err\:code = 1001);
}
```

```cmd
$ bal run test.bal 
Compiling source
        test.bal
WARNING [test.bal:(2:5,2:78)] unused variable 'e'

Running executable

error: {ballerina/lang.map}KeyNotFound {"message":"invalid field access: field 'err\:code' not found in record type 'record {| int err:code; |}'"}
        at test:main(test.bal:2)
```

### Affected Version(s)

2201.3.2

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Need to also check binding patterns once this is fixed. Related issue for mapping binding patterns - https://github.com/ballerina-platform/ballerina-lang/issues/38835.

**Comment by hasithaa** [comment]
> Need to also check binding patterns once this is fixed. Related issue for mapping binding patterns - #38835.

@ushirask Please verify this and close the issue.

**Comment by MaryamZi** [comment]
Seems to have been fixed on U6.
