### ISSUE TITLE
[Bug]: Can't use a mapping binding pattern within a list binding pattern against an open record

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#39324]
### Description

$title.

### Steps to Reproduce

```ballerina
public function main() {
    [record { int a; int b; }] r = [{a: 1, b: 2}];

    int a;
    int b;
    {a, b} = r[0]; // OK

    [{a, b}] = r; // error
}
```

```cmd
$ bal run test.bal 
Compiling source
        test.bal
ERROR [test.bal:(8:16,8:17)] incompatible types: expected '[record {| int a; int b; |}]', found '[record {| int a; int b; anydata...; |}]'
```

Seems like the type computed for the mapping binding pattern here is a closed record.

### Affected Version(s)

2201.3.2

### Related area

-> Compilation

**Comment by dulajdilshan** [comment]
In
```
[{a, b}] = r;
```

`r`'s type is computed as `[record {| int a; int b; anydata...; |}]` instead of `[record {int a; int b; }]`. Is this intentional?

**Comment by MaryamZi** [comment]
> In
> 
> ```
> [{a, b}] = r;
> ```
> 
> `r`'s type is computed as `[record {| int a; int b; anydata...; |}]` instead of `[record {int a; int b; }]`. Is this intentional?

`record {| int a; int b; anydata...; |}` is the same as `record {int a; int b; }`.

An inclusive record type descriptor => open by `anydata`.

**Comment by dulajdilshan** [comment]
> `record {| int a; int b; anydata...; |}` is the same as `record {int a; int b; }`.
> 
> An inclusive record type descriptor => open by `anydata`.

Yeah. It makes sense. My question is why don't we use `record {int a; int b; }` directly?

**Comment by MaryamZi** [comment]
> > `record {| int a; int b; anydata...; |}` is the same as `record {int a; int b; }`.
> > An inclusive record type descriptor => open by `anydata`.
> 
> Yeah. It makes sense. My question is why don't we use `record {int a; int b; }` directly?

Do you mean the string representation?

**Comment by dulajdilshan** [comment]
> Do you mean the string representation?
I mean the type. Have we modeled (by default) to have a close record as the type?

**Comment by MaryamZi** [comment]
> > Do you mean the string representation?
> 
> I mean the type. Have we modeled (by default) to have a close record as the type?

`record {| int a; int b; anydata...; |}` is not closed, it is an open record.

https://ballerina.io/spec/lang/master/#record-type-descriptor 

> A record type descriptor that either is an inclusive-record-type-descriptor or is an exclusive-record-type-descriptor with a record-rest-descriptor is called open; a record type descriptor that is not open is called closed.

We do not have separate representations for inclusive vs exclusive record type descriptors.
