### ISSUE TITLE
[Bug]: CodeAction didn't work with configurable statements

### ISSUE THREAD

**Issue by kanushka** [ballerina-platform/ballerina-lang#39332]
### Description

Typecasting CodeAction didn't work with configurable statements.

### Steps to Reproduce

Try to change below configurable statement's type using code actions

## Sample source
```ballerina
import ballerina/io;

configurable int tst = "";

public function main() {
    io:println("Hello, World!");
}
```

https://user-images.githubusercontent.com/24244523/214031439-caab396f-5a27-4655-995d-c0b597d7b3fe.mp4

### Affected Version(s)

2201.3.2

### Related area

-> Editor

**Comment by malinthar** [comment]
Closing this as it has already been fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39388

![Peek 2023-02-06 21-23](https://user-images.githubusercontent.com/35211477/217021640-0c4f4cde-0502-46cb-a742-c1d986c09513.gif)
