### ISSUE TITLE
[Bug]:  Missing lang lib methods in regexp langlib 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#39336]
### Description

Case 1:

Consider the following code.

```Ballerina
import ballerina/lang.regexp;

public function main() {
    regexp:RegExp reg = re ``;
    int a = 10;
}
```

The type symbol of `reg` is as follows.
![image](https://user-images.githubusercontent.com/35211477/214114440-0acc6f02-0597-4ac5-b7da-eb898fdbc0eb.png)

As depicted below, the set of lang libs methods of `reg` type symbol does not have methods like `find`, `findGroup()`, etc. 
https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.regexp/src/main/ballerina/regexp.bal
![image](https://user-images.githubusercontent.com/35211477/214114228-1807ca50-bca0-415c-bb74-afaeb2e9edec.png)

Case 2:
```Ballerina

public function case2() {
    string:RegExp reg = re `World`;

    regexp:Span? matchAt = reg.matchAt("World");

    if matchAt is regexp:Span {
        matchAt.<cursor>
    } else {

    }
}
```
Langlib methods of `Span` type symbol contains the `toString` Method. 

![image](https://user-images.githubusercontent.com/35211477/214210812-2004d72c-9904-4e24-af3d-f00c66d8fbcd.png)

However when `toString` method is used, get the following compilation error.

![Screenshot from 2023-01-24 09-44-24](https://user-images.githubusercontent.com/35211477/214210966-0cb195a8-997f-44c6-bb57-91a9bc9d486f.png)

_No response_

### Affected Version(s)

2201.4.0-SNAPSHOT

### Related area

-> Editor

**Comment by IMS94** [comment]
@malinthar is it the same if we get the raw type and get langlibs?

**Comment by malinthar** [comment]
> @malinthar is it the same if we get the raw type and get langlibs?

![image](https://user-images.githubusercontent.com/35211477/214211422-904acb62-109e-446d-a2c6-f700bc93f837.png)

Yes same behaviour

**Comment by dulajdilshan** [comment]
https://github.com/ballerina-platform/ballerina-lang/blob/2bff9487920ec2e28b243017bda6ceec836b9eb6/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRegexpType.java#L49

why is this return `anydata`? don't we have to send it as `REGEXP`? @pcnfernando @lasinicl

**Comment by pcnfernando** [comment]
> https://github.com/ballerina-platform/ballerina-lang/blob/2bff9487920ec2e28b243017bda6ceec836b9eb6/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/types/BRegexpType.java#L49
> 
> why is this return `anydata`? don't we have to send it as `REGEXP`? @pcnfernando @lasinicl

Seems to be a bug. Please update it. It won't have any semantic change anyways

**Comment by dulajdilshan** [comment]
> Seems to be a bug. Please update it. It won't have any semantic change anyways

@malinthar Shall we correct this and handle regexp in lang-lib methods?
