### ISSUE TITLE
[Bug]: Testerina native implementation prints `[pass]` logs

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#39375]
### Description

The testerina test console log prints only the summary of the tests. It prints the failed test names if there are any failed tests. The passed tests are printed only if the printstream is the console log. This is done for the sake of brevity.

However, with the native implementation of `bal test` (--native), the pass logs are printed all the time. This is a deviation from the expected behaviour. 

### Steps to Reproduce

1. Create a ballerina project with a simple test case.
2. Run the test case with `bal test --native`.

You may observe there is a log similar to `[pass] sampleTest`.

### Affected Version(s)

Update 4 onwards

### Related area

-> Test Framework

**Comment by Thevakumar-Luheerathan** [comment]
We are using `System.console()` to detect interactive terminal(to prevent printing [pass] logs only in interactive terminals). Due to a [bug in Graalvm ](https://github.com/oracle/graal/issues/5721), `System.console()` always returns null. That is the reason for the failure.

**Comment by azinneera** [comment]
Closing since this is due to a bug since the bug is related to graalvm
