### ISSUE TITLE
[Improvement]: Annotation attachment value is null for non-constant annotation attachments

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-lang#39381]
### Description

`attachmentValue` of an `AnnotationAttachmentSymbol` always has value when the annotation-attachment is a constant. And there are cases where annotation-attachment is not a constant and in those cases attachmentValue is null and it makes sense as sometimes the value cannot be determined at the compile-time. But in some instances even though the annotation-attachment is not a constant, the value associated with it has a literal value. And in those cases, attachmentValue can still be non-null even though annotation-attachment is not a constant.

Please take a look at the example below.
```Ballerina
public type InlineClass record {
    @constraint:String {
        minLength: 10
    }
    string studentName;
};
```
In this example, the annotation-attachment is not a constant, but the value associated with it has a literal value so, this value can be captured into semantic-model `AnnotationAttachmentSymbol`

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
The current behaviour is in-line with the language specification. A value is available at compile-time (via symbols) only if it is evaluated at compile-time, and only `const` annotations are evaluated at compile-time.

https://ballerina.io/spec/lang/2022R3/#section_9.1

> If the annotation-decl for a tag specifies const, then a mapping-constructor-expr in annotations with that tag must be a const-expr and is evaluated at compile-time with the semantics of a const-expr. Otherwise, the mapping-constructor-expr is evaluated when the annotation is evaluated and the ImmutableClone abstract operation is applied to the result.

**Comment by MaryamZi** [comment]
Closing as the value not being available is expected with non-const annotations.
