### ISSUE TITLE
[Bug]: Incorrect sort order in LS completion test cases

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#39408]
### Description

After merging https://github.com/ballerina-platform/ballerina-lang/pull/38596 following sort order related to following testcases are affected. 

In following cases string variables and functions should be prioritized.

[completion/expression_context/config/mapping_expr_ctx_config5.json]
[completion/expression_context/config/mapping_expr_ctx_config6.json]
[completion/expression_context/config/mapping_expr_ctx_config8.json]
[completion/expression_context/config/mapping_expr_ctx_config9.json]

And expectedtype need to be narrow down in the following testcase as suggested by https://github.com/ballerina-platform/ballerina-lang/pull/38596#discussion_r1085156847

[/completion/expression_context/config/mapping_expr_ctx_config38_negative.json]

### Related area

-> Editor

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
