### ISSUE TITLE
[Bug]: Undefined function `clonewithType` in type `table<map<anydata>>`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#39419]
### Description

`table<map<anydata>>` is a subtype of `anydata`. So `cloneWithType` should be available. This only happens if I call this function as a method of the value. If I call the `value:cloneWithType()` it does not provide the compilation error.

### Steps to Reproduce

```bal
import ballerina/lang.value;
import ballerina/io;

public function main() {
    table<map<anydata>> tab = table [{"a":1}, {"b":2}];
    io:println(tab is anydata); // true
    map<json>[] tab_clone = checkpanic value:cloneWithType(tab);
    map<json>[] tab_clone2 = checkpanic tab.clonewithType(); // undefined function 'clonewithType' in type 'table<map<anydata>>'(BCE2012)
}
```
gives
```
Compiling source
        code.bal
ERROR [code.bal:(8:45,8:58)] undefined function 'clonewithType' in type 'table<map<anydata>>'
error: compilation contains errors
```

### Affected Version(s)

Ballerina 2201.3.2 (Swan Lake Update 3)

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
> ```ballerina
>     map<json>[] tab_clone2 = checkpanic tab.clonewithType(); 
> ```

There's a typo here, `w` instead of `W` - clone**w**ithType, so the error is expected.

The following works.

```ballerina
map<json>[] tab_clone2 = checkpanic tab.cloneWithType();
```
