### ISSUE TITLE
[Bug]: Incorrect sorting order in expression context related to XML

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#39416]
### Description

Consider the completion testcase [completion/expression_context/config/xml_attribute_access_expr_ctx_config1.json]

As suggested by https://github.com/ballerina-platform/ballerina-lang/pull/38596#discussion_r1086425859 need to prioritized namespaces (attributes) first.

### Related area

-> Editor

**Comment by IMS94** [comment]
Checked this again. In this scenario,
```
import ballerina/module1;

xmlns "http://ballerina.com/ns0" as ns0;

function testFunction() {
    xmlns "http://ballerina.com/ns1" as ns1;
    xml x2 = xml `<foo n>hello</foo>`;
    
    x2.<cursor>
}
```
ideally we should show the completions for the attributes. But that's not available as symbol information. Therefore, we cannot improve this scenario.
