### ISSUE TITLE
[Bug]: Incorrect sorting order in completion test

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-lang#39412]
### Description

consider following completion test case [completion/expression_context/config/mapping_expr_ctx_config41.json]

```ballerina
type Rec3 record {
    int rec3Field1;
    int rec3Field2;
};

type RecUnion Rec1|Rec2|record {int anonField1; string anonField2;};

type RecUnion2 Rec1|Rec2;

public function main() {
    int rec3Field2 = 12;
    Rec3 rec3 = {
        rec3Field1: 0,
        r<cursor>
    }   
}

```
 
As suggested by https://github.com/ballerina-platform/ballerina-lang/pull/38596#discussion_r1086413442 field name should come first in the order.

### Related area

-> Compilation

**Comment by IMS94** [comment]
Double checked this. This behavior is correct since here the variable `rec3Field2` gets suggested because the record has a field with the same name. Variables with other names are not suggested.
