### ISSUE TITLE
[Bug]: Node cloner not cloning the const-pattern expression

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#39420]
### Description

$title. 
We set the expression directly, without cloning it.
https://github.com/ballerina-platform/ballerina-lang/blob/923ccffce8ad1c0549130344e7cfa1e3b58d75ac/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/parser/NodeCloner.java#L729

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
This issue was identified through the daily build failure.
https://github.com/ballerina-platform/ballerina-release/actions/runs/4038121682/jobs/6941897704

**Comment by MaryamZi** [comment]
Reopening since a test needs to be added.

**Comment by chiranSachintha** [comment]
I will close this issue since I have created a PR for the tests(https://github.com/ballerina-platform/ballerina-lang/pull/39454)
