### ISSUE TITLE
[Bindgen Tool] Improve support for passing/retrieving java Null values via generated Ballerina functions 

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#39434]
### Description

As per the current Ballerina bindgen tool implementation, the generated bindings seems to be not consistent when support passing/retrieving null values to/from the underlying java code. And this can lead to unexpected behaviour and runtime errors in the resulting Ballerina code.

### Describe your problem(s)

Consider the following Java method and the counterpart Ballerina function generated using the bindgen tool

#### Java method
```java
public String getHeadElement(String[] param) {
}
```
#### Generated ballerina function
```ballerina
public function getHeadElement(string[] param) returns string  {
}
```
As per the generated function signature, it neither allows passing nil values to the function or, retrieving nil values as the return values. This could be problematic if the underlying Java function has logic depending on the parameter/return being null, as the that scenario won't be supported by the generated bindings.

### Describe your solution(s)

As per the discussion had with @sameerajayasoma and @hevayo, the following alternatives were suggested to overcome the situations like above.

### Option 01: 
Modify parameter and return bindings generation logic to **always** generate nilable types (i.e. `T?`), for all the Java types which extends `java.lang.Object` (hence nullable).

e.g: 
```ballerina
public function getHeadElement(string?[]? param) returns string? {
}
```

Pros:
\- The generated bindings from the tool will be null-compatible, OOTB
Cons: 
\- Users will always have to use match statements/ type checks to handle the `()` case, when accessing return values from the generated bindings
 
### Option 02: 
Provide CLI option(s) for users to selectively make the parameter and return types nillable.
Here, the generated bindings **will not** be null-compatible by default and, users will have the control to generate nilable types 
incase they have Java functions having logics depending on the parameter/return being null. This can be achieved either by,
1. Using a single command option (e.g. `--allow-null`) or
2. Using separate options for parameter and return types (e.g. `--allow-null-params` and `--allow-null-returns`)

Pros:
\- Users will have some level of fine-grained control to generate bindings(based on the underlying java function logic)

### Option 03:
Generate null-compatible bindings, only when the underlying java functions contain nullable-related annotations (e.g. **@NotNull**, **@Nullable**)
 
Cons:
\- Since these are not built-in annotations and from 3rd party tools, hard to rely-on
\- Therefore users will have no control to decide the null-compatibility, when using 3rd party classes (i.e. Java library classes, maven dependencies)

@hevayo @sameerajayasoma Appreciate your concerns and the preferred option to move forward with 

### Related issue(s) (optional)
https://github.com/ballerina-platform/ballerina-lang/issues/39059

**Comment by sameerajayasoma** [comment]
AFAIR, in option 2 we generate bindings without the support for passing nil or return nil values. The suggestion options can be used to change this behavior.

**Comment by sameerajayasoma** [comment]
I can think of following CLI options. I prefer the last one.

--with-optional-types
--with-optional-param-types
--with-optional-return-types

--with-optional-types
--with-optional-types-param
--with-optional-types-return


bal bindgen java.lang.String --with-optional-types

**Comment by NipunaRanasinghe** [comment]
> AFAIR, in option 2 we generate bindings without the support for passing nil or return nil values. The suggestion options can be used to change this behavior.

Yes, you are correct :)

> I can think of following CLI options. I prefer the last one.

+1 to move forward with the option 02 and, the following set of command options
`--with-optional-types`
`--with-optional-types-param`
`--with-optional-types-return`

@hevayo appreciate your thoughts on this
