### ISSUE TITLE
[Bug]: Invalid Error in regex

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#39447]
### Description

Following code

```
public function main() {
  string:RegExp x7 = re `\\-`;
}
```
Gives

```
Compiling source
        test.bal
ERROR [test.bal:(4:27,4:27)] missing syntax char after backslash
```

But according to the spec this should work fine.

`//-` should work in following way according to the spec

Regexp -> ReTerm ReTerm
             -> ReEscape ReAtom
             -> ReQuoteEscape ReLiteralChar
             -> / ReSyntaxChar ` -`
             -> `//-`

### Related area

-> Compilation

**Comment by mohanvive** [comment]
@SasinduDilshara I have checked this issues, isn't above should fail according to the spec? Isn't it resolve something like the below as per the spec,

```
-> ReEscape ReAtom
-> ReQuoteEscape ReLiteralChar
-> \ ReSyntaxChar  -
-> \\^-
```

**Comment by mohanvive** [comment]
> @SasinduDilshara I have checked this issue, isn't above should fail according to the spec? Isn't it resolve something like the below as per the spec,
> 
> ```
> -> ReEscape ReAtom
> -> ReQuoteEscape ReLiteralChar
> -> \ ReSyntaxChar ReLiteralChar
> -> \\^-
> ```

My interpretation is incorrect. Hence, I'll check this further
