### ISSUE TITLE
[Task]: Refactor create variable code actions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#39475]
### Description

Right now, create variable code actions have 4 variants 
1. create variable
2. create variable with type
3. create variable and check error
4. create variable and type guard

These classes have duplicated code and have used wrapper classes (like CreateVariableOut) to reuse calculating the create variable text edits. It needs refactoring because now the logic has become complex due to the rename popup

### Describe your task(s)

See description

### Related area

-> Editor

**Comment by KavinduZoysa** [comment]
Closing this as a low-priority task with the Icebox label might reopen in the future.
