### ISSUE TITLE
[Bug]: Runtime throws a Java exception for empty character class (re `[]`)

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#39489]
### Description

Consider following codes

```
import ballerina/io;

public function main() {
  string:RegExp x = re `(?:a[])`;
  io:println(x.findAll("abcd").forEach(e => io:println(e.substring()))); //runtime error: Unclosed character class near index 6 (?:a[                                    
}
```
```
import ballerina/io;

public function main() {
  string:RegExp x2 = re `(?:a)`;
  io:println(x2.findAll("abcd").forEach(e => io:println(e.substring()))); // no runtime error 
}
```

So in the first case error message is ` Unclosed character class`. This is a invalid error message

### Related area

-> Runtime

**Comment by SasinduDilshara** [comment]
There is a idea about this issue from team members in a separate call
```
Java seems not support an empty character class. when you have [], it consider ] as a character in the character class and wants you to close that. If you add some character between [], it should work. We'll have to special case during desugaring since ballerina supports this
```

**Comment by pcnfernando** [comment]
Empty character class(re `[]`) should not be a syntax error as it is allowed by the [ballerina grammar](https://ballerina.io/spec/lang/master/#section_10.1).
As per ECMAScript 2022 standard which ballerina uses as a reference; an empty character class in a regular expression should match nothing. 

However, an empty character class in a regular expression is usually not intended, and it is considered a mistake in the regular expression pattern(https://eslint.org/docs/latest/rules/no-empty-character-class). Therefore, it is important to check and fix any empty character classes in regular expressions to ensure that they match the intended pattern. Hence, we are making empty character class in the regexp a compilation error.
