### ISSUE TITLE
[Bug]: `runCodeModifierPlugins()` run AnalysisTask too inside the ModifierTask

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#39503]
### Description

HTTP package adding code modifiers to support default payload param https://github.com/ballerina-platform/ballerina-standard-library/issues/3276

When writing test cases, first the code modifiers should be run. 

```java
    @Test
    public void testCodeModifierPayloadAnnotation() {
        Package currentPackage = loadPackage("sample_package_31");
        CodeModifierResult codeModifierResult = currentPackage.runCodeModifierPlugins();
        Assert.assertEquals(codeModifierResult.reportedDiagnostics().errorCount(), 0);
        Optional<Package> updatedPackage = codeModifierResult.updatedPackage();
        DiagnosticResult diagnosticResult = updatedPackage.get().getCompilation().diagnosticResult();
        Assert.assertEquals(diagnosticResult.errorCount(), 0);
    }
```

During the `runCodeModifierPlugins` executing, the package AnalysisTask also run and try to analyse the old package without any modification. How can this be resolved?

The `runCodeGenAndModifyPlugins` function does it properly. It does not run AnalysisTask.

### Related area

-> Compilation

**Comment by gayaldassanayake** [comment]
The `PackageCompilation->compile` method skips the code analyzers iff there are code generators. This logic needs to be extended to skip code analyzers when there are code modifiers as well.

Will send a fix soon.
