### ISSUE TITLE
[Task]: Add float API doc examples to the spec

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#39508]
### Description

Currently the Ballerina specification does not contains apidoc examples for float langlib.

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/pull/38905

**Comment by SasinduDilshara** [comment]
PR - https://github.com/ballerina-platform/ballerina-spec/pull/1205

**Comment by MaryamZi** [comment]
Closing this issue since we won't be adding this immediately.
