### ISSUE TITLE
[New Feature]: A way to label GraalVM compatible modules

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#39514]
### Description

At the moment in Ballerina echo system there are two types of modules. One that is GraalVM compatible and the one that is not GraalVM compatible. Right now there is no systematic way of distinguishing one from the another. Therefore, `bal build --native` could fail without any warning. 

If we have a way to label them, complier can give proper warnings and error messages. Also we can improve Ballerina central to display a nice GraalVM badge. Both could help avoid nasty build breaks.

### Related area

-> Compilation

**Comment by sameerajayasoma** [comment]
Let's use the term package here. Modules are too low-level. 

A Ballerina repository is a collection of compiled Ballerina packages. We also use the term `balo` for a compiled package.  `balo` is a file format based on the popular ZIP file format.  We can identify two kinds of `balo` files based on the presence of platform-specific binaries.  

`balo` files with no platform-specific libraries are always GraalVM native image compatible.  We need a way to identify which `balo` files with platform-specific libraries are GraalVM compatible.

**Comment by Dilhasha** [comment]
Following are the two high-level tasks to be addressed.

- [ ] Support `graalvmCompatibility` property in Ballerina.toml for `java*` platforms and include the value in `package.json` during `bal pack`

- [ ] Issue a warning if a package is not GraalVM compatible during `bal build --graalvm`

**Comment by Dilhasha** [comment]
doc changes: https://github.com/ballerina-platform/ballerina-dev-website/pull/7146
