### ISSUE TITLE
[Bug]: Incorrect typecheking in nested tuple type

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#39519]
### Description

$subject

```ballerina
[(int[])|(string[])][] res = [[[23, 24], ["Name"]]]; // compile error: tuple and expression size does not match
```
The above error is invalid. But the following case is working.
```ballerina
[(int[])][] res = [[[23, 24]]]; // Working
```

### Steps to Reproduce

Please check the description

### Affected Version(s)

Ballerina 2201.3.0

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
```ballerina
[(int[])|(string[])][] res = [[[23, 24], ["Name"]]];
```

On the left side we have 
- an array where the member type
  -  is a tuple which has a single member
     - which is either an `int[]` or a `string[]`

But with the list constructor expression, you are trying to create 
- an array where the member
  - is a list with two members
 
So the list constructor and the expected type don't match.

Without one level of list, this is

```ballerina
[(int[])|(string[])] x = [[23, 24], ["Name"]];
```
which also results in an error.

So getting an error for the original example is correct?

**Comment by KavinduZoysa** [comment]
@MaryamZi, yes you are correct.
