### ISSUE TITLE
[Bug]: Debugger misses breakpoints inside modules

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [ballerina-platform/ballerina-lang#39530]
### Description

Consider a ballerina package which contains submodules. These modules can contain tests. However, when tests are debugged in the package, debugger fails to hit the breakpoints present in the submodule test. 
 
Even if the debugger is invoked directly for the test present in the submodule, it still fails to hit the breakpoint. 

### Steps to Reproduce

Consider the following example. There, 
In the `debugger-test` package, there is a module called `util`. Breakpoint in the tests in `util` is missed while debugging the tests of the package.

https://user-images.githubusercontent.com/85400922/217241277-0584aa96-a661-4b5e-9d8d-55f7ec73a01c.mov

Issue was found while debugging the GraphQL parser module.

### Affected Version(s)

master

### OS, DB, other environment details and versions

Mac OS

### Related area

-> Debugger

### Suggested assignee(s) (optional)

@NipunaRanasinghe

**Comment by NipunaRanasinghe** [comment]
Closing as completed
