### ISSUE TITLE
[Bug]: Syntax tree visualizer crashes when declaring a RegExp

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#39536]
### Description
$subject

<img width="1463" alt="Screenshot 2023-02-08 at 10 19 05" src="https://user-images.githubusercontent.com/46857198/217436618-39e8f1de-3970-47a1-b4cb-54ad06683d31.png">

### Affected Version(s)

2201.4.0-SNAPSHOT - Master

### Related area

-> Editor

**Comment by mindula** [comment]
This is fixed now.

<img width="1465" alt="Screenshot 2023-07-07 at 15 22 34" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/e3b2be95-a1e5-4a1f-af9d-b1a74a85a740">
