### ISSUE TITLE
[Bug]: Invalid compilation error given when creating a new error value from an error type with intersection in an imported module

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#39542]
### Description

$title

Note that this works if we don't use the error-type-reference in the error constructor. It should work with that also.

Because of this issue, autocompletion also does not work with that particular case. Need to see to that also.
For example after the `:`, the error-type-reference is not suggested.
```
LibTest:InvalidDocumentError err44 = error LibTest:
```

### Steps to Reproduce

Create a package having a type defined like the below in the `main.bal`.
```bal
public type DocumentError distinct error;

public type InvalidDocumentError distinct (DocumentError & error<record {| string[]? errors; |}>);
```
Say the `Ballerina.toml` is like this for the above package.
```
[package]
org = "nadeeshand"
name = "LibTest"
version = "0.1.0"
```
Publish that to the local Ballerina repository using the below commands.
```shell
bal pack
bal push --repository local
```

Then create another package and try to create an error value using the imported error type.

Balleriana.toml
```
[package]
org = "nadeeshand"
name = "testPrj"
version = "0.1.0"

[[dependency]]
org = "nadeeshand"
name = "LibTest"
version = "0.1.0"
repository = "local"
```

Code in the `main.bal` which gives the compilation error.
```bal
import ballerina/io;
import nadeeshand/LibTest;

public function main() {
    LibTest:InvalidDocumentError err4 = error("err", errors = []); // works
    io:println(err4);

    LibTest:InvalidDocumentError err44 = error LibTest:InvalidDocumentError("err", errors = []); // does not work
    io:println(err44);
}
```

The above gives compilation error.
```
Compiling source
        nadeeshand/testPrj:0.1.0
ERROR [main.bal:(8:48,8:76)] cannot create a new error value from 'LibTest:InvalidDocumentError'
error: compilation contains errors
```

### Affected Version(s)

Ballerina 2201.3.2 (Swan Lake Update 3)

### Related area

-> Compilation

**Comment by Nadeeshan96** [comment]
After fixing this can add tests [here](https://github.com/ballerina-platform/ballerina-lang/pull/39531/files#diff-e6adc21ba04e78ccfb70676daccab4bc2da4c60463a3a0c1e9127d5cd8018f35R38-R39).

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/38346?

**Comment by Nadeeshan96** [comment]
> Duplicate of #38346?

It seems so. Hence I will close this issue. Thank you very much for pointing this out!
