### ISSUE TITLE
[Bug]: AfterGroups function is not executed

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#39556]
### Description

$subject

### Steps to Reproduce

Execute `bal test --groups g1 after-groups-with-disabled-test.bal` on the following file:

https://github.com/ballerina-platform/ballerina-lang/blob/master/tests/testerina-integration-test/src/test/resources/single-file-tests/grouping/after-groups-with-disabled-test.bal

### Affected Version(s)

2201.4.0-SNAPSHOT

### Related area

-> Test Framework

**Comment by gayaldassanayake** [comment]
The issue is due to skipping the disabled test during the test ordering process, and then checking if all the tests are executed before running the before group method. But this condition is never met since the disabled test is not going to be executed.

Working on a solution as of now.
