### ISSUE TITLE
http:Request getHeaders() function is not working

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/ballerina-lang#3955]
This is available in API docs, but results in an error as it is not implemented yet.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1029806/32492458-450bcff8-c3b2-11e7-94da-7a43a42bd36d.png">

This is a useful function when performing routing based on the headers available.

**Comment by pubudu91** [comment]
Related issue #3675

**Comment by arukshani** [comment]
A new called getHeaderNames() is available. Fixed with #7008
