### ISSUE TITLE
[Improvement]: Support custom-detailed distinct error subtypes

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#39595]
As far as I can tell, following should work according to the spec. But currently it gives `invalid intersection type` 

```ballerina
type BlobErrorDetail record {|
        int httpStatusCode;
        string azureErrorCode;
|};

type BlobError distinct error<BlobErrorDetail>;

public type ResourceNotFoundDetail record {|
        404 httpStatusCode = 404;
        "ResourceNotFound" azureErrorCode = "ResourceNotFound";
|};

type ResourceNotFound BlobError & distinct error<ResourceNotFoundDetail>
```

**Comment by MaryamZi** [comment]
This is because of the default values.

Works when `ResourceNotFoundDetail` is

```ballerina
public type ResourceNotFoundDetail record {|
    404 httpStatusCode;
    "ResourceNotFound" azureErrorCode;
|};
```

Related spec issues/discussions - https://github.com/ballerina-platform/ballerina-spec/issues/754, https://github.com/ballerina-platform/ballerina-spec/issues/544#issuecomment-778099662.

**Comment by MaryamZi** [comment]
Closing this since the behaviour is in-line with what was defined by the spec (at least for now).
