### ISSUE TITLE
Original XML data is lost when coming from the runtime APIs.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#39598]
### Description

Consider the following program. 

```ballerina
import ballerina/io;

public function main() returns error? {
    xmlns "http://www.w3.org/2003/05/soap-envelope" as soap;
    xmlns "http://services.resource.registry.carbon.wso2.org" as ns;

    xml literal = xml `<?xml version='1.0' encoding='UTF-8'?>
<data>&lt;xsl:apply-templates someattrib=" &amp;lt;" /></data>`;


    io:ReadableByteChannel rbc = check io:openReadableFile("soap.xml");
    io:ReadableCharacterChannel rch = new (rbc, "UTF8");
    xml payload = check rch.readXml();

    io:println("Original XML: ", payload);
    io:println("Literal XML: ", literal);
    io:println("Compaire: ", literal == payload);
}
```

soap.xml
```xml
<?xml version='1.0' encoding='UTF-8'?>
<data>&lt;xsl:apply-templates someattrib=" &amp;lt;" /></data>
```

Here, both soap.xml and the XML literal have the same XML document. But those are passed as two values.

Program Output
```
Original XML: <data>&lt;xsl:apply-templates someattrib=" &lt;" /></data>
Literal XML: <?xml version='1.0' encoding='UTF-8'?><data>&lt;xsl:apply-templates someattrib=" &amp;lt;" /></data>
Compaire: false
```

Here are observations.
- Missing top XML PI
- Modified XML text value.  

### Affected Version(s)

SL U2, U3

### Related area

-> Runtime

**Comment by hasithaa** [comment]
Here is the working program. 


[issue.zip](https://github.com/ballerina-platform/ballerina-lang/files/10728579/issue.zip)

**Comment by warunalakshitha** [comment]
As per the observation xml PI is already missed inside the runtime core. I assume it was some how missed in io side.

**Comment by sahanHe** [comment]
Hi @warunalakshitha , from IO module, we create the channel and parse it to runtime API `XmlUtils.parse(reader)` to read the xml payload in [here](https://github.com/ballerina-platform/module-ballerina-io/blob/d5574696137eafe1c07bbd1750ca2b58f8a04009/native/src/main/java/io/ballerina/stdlib/io/nativeimpl/CharacterChannelUtils.java#L185). Is there any additional things that should be done from IO module?

**Comment by Nadeeshan96** [comment]
### Regarding the missing top XML PI
Currently at compile-time, the xml declaration is considered as a regular XML processing instruction. But [according to the xml information set](https://www.w3.org/TR/xml-infoset/#infoitem.pi), it should not be.

And also, it does not check whether an xml value is well-formed with regard to the xml declaration. https://www.w3.org/TR/xml/#NT-XMLDecl

E.g. Following are not compile-time errors, though the xml values may result in malformed xml documents.
```bal
xml x1 = xml `<data>Data</data><?xml version='1.0' encoding='UTF-8'?>`;
xml x2 = xml `<?xml version='1.0' encoding='UTF-8'?><data>Data</data><?xml version='1.0' encoding='UTF-8'?>`;
xml x3 = xml `<?xml encoding='UTF-8' version='1.0'?><data>Data</data>`;
xml x4 = xml `<?xMl version='1.0' encoding='UTF-8'?><data>Data</data>`;
xml x5 = xml `<?xml version='1.0' encod='UTF-8'?><data>Data</data>`;
xml x6 = x1 + x2;
xml x7 = x1 + x3;
xml x8 = x1 + x4;
xml x9 = x2 + x3;
```

At runtime, we use [the Woodstox parser](https://github.com/FasterXML/woodstox) for parsing xml. It does not consider the xml declaration as an xml processing instruction, but like the properties of the xml document (which we can access using `getEncoding(), getVersion(), isStandalone(), standaloneSet(), getCharacterEncodingScheme()`), which is correct. Therefore, we get the xml as above when reading from the file.

In both [the spec](https://ballerina.io/spec/lang/master/#section_6.6.2) and the [xml proposal](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md), I could not find any reference to the xml declaration. But [here](https://ballerina.io/spec/lang/master/#section_6.6.2), it says the xml template expression is parsed using the production content in the W3C XML Recommendation. So the above code should result in compilation errors. 

To fix this I think we can consider the following options.
#### Option 1
Compile-time: Disallow xml declaration inside xml template expressions.
Runtime: No need to change the behaviour.
Can change [`io:fileWriteXml`](https://lib.ballerina.io/ballerina/io/1.4.0#fileWriteXml) to write xml declaration by providing information, if needed.

#### Option 2
Compile-time: Allow to have a valid xml declaration inside xml template expressions. Use that only to parse the xml content correctly and do not include it in the xml value.
Runtime: No need to change the behaviour.
Can change [`io:fileWriteXml`](https://lib.ballerina.io/ballerina/io/1.4.0#fileWriteXml) to write xml declaration by providing information, if needed.

I think option 2 is better and more in line with the spec. @hasithaa @warunalakshitha WDYT? Is there another better option?

**Comment by Nadeeshan96** [comment]
According to [the spec issue](https://github.com/ballerina-platform/ballerina-spec/issues/1225), we should disallow the XML declaration within xml template expressions. Created https://github.com/ballerina-platform/ballerina-lang/issues/39858 for that.

**Comment by Nadeeshan96** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39624.
