### ISSUE TITLE
[Bug]: NPE returned when trying to access MethodSymbol from context.typeOf(node) in semantic model

### ISSUE THREAD

**Issue by tharindu-nw** [ballerina-platform/ballerina-lang#39612]
### Description

Get the following error when building https://github.com/tharindu-nw/ballerina-registry/tree/graphql/projects/package_api_graphql 

```
Compiling source
    registry/package.api.graphql:0.1.0
ballerina/sql:1.6.2 [central.ballerina.io -> home repo]  100% [============================================] 364/364 KB (0:00:01 / 0:00:00) 
    ballerina/sql:1.6.2 pulled from central successfully
error: compilation failed: The compiler extension in package 'ballerina:sql:1.6.2' failed to complete. Cannot read field "pos" because "funcNode.symbol" is null
```

Ballerina version: 2201.3.0
Got the same error after downgrading the sql version to 1.6.1

### Steps to Reproduce

* do a `bal build` with https://github.com/tharindu-nw/ballerina-registry/tree/graphql/projects/package_api_graphql

### Related area

-> Compilation

**Comment by niveathika** [comment]
This is due to compiler throwing NPE when we try to access a method symbol from BallerinaSemanticModel.

Code Line: https://github.com/ballerina-platform/module-ballerina-sql/blob/v1.6.2/compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java#L68

**Comment by tharindu-nw** [comment]
After checking the code, found a syntax error (unnecessary `new` keyword) here: https://github.com/tharindu-nw/ballerina-registry/blob/5221c8241ffbd473230d00df767f9ecf3012159f/projects/package_api_graphql/package_api_graphql_service.bal#L56

Tried building after removing that and got the following error:
```
ERROR [ballerina/log/2.5.1::natives.bal:(267:1,270:12)] {ballerina/jballerina.java}METHOD_SIGNATURE_DOES_NOT_MATCH 'Incompatible param type for method 'replace' in class 'java.lang.String': Java type 'char' will not be matched to ballerina type 'handle''
```

**Comment by dulajdilshan** [comment]
Had to debug the original code shared here against ballerina-lang 2201.3.0 and 2201.3.x, It turns out to be the original problem comes from:
https://github.com/ballerina-platform/ballerina-lang/blob/0dbeaf81dbb2a8cec554b43ffb5044ae229aa169/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java#L288

Here, `funcNode.symbol` is getting `null`

**Comment by tharindu-nw** [comment]
Issue seems to go away after removing the extra `new` keyword here: https://github.com/tharindu-nw/ballerina-registry/blob/5221c8241ffbd473230d00df767f9ecf3012159f/projects/package_api_graphql/package_api_graphql_service.bal#L56

**Comment by dulajdilshan** [comment]
Due to this https://github.com/ballerina-platform/ballerina-lang/issues/39612#issuecomment-1434099052

**Comment by dulajdilshan** [comment]
Due to this https://github.com/ballerina-platform/ballerina-lang/issues/39612#issuecomment-1434099052
