### ISSUE TITLE
[Bug]: readonly inner tuple destructuring dosn't work

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#39622]
There is a bug in inner tuple destructuring.

```ballerina
public type X readonly & [string, [int]];

function foo(X x) {
    var [s, [i]] = x;
}
```
In above `s` works, but `i` does not.  It works if we remove `readonly`.

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/37994. Fixed on master (update 5).
