### ISSUE TITLE
[Bug]: `--list-groups` command with `--groups` flag does not return correct group list

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#39629]
### Description

When a single file test contains the groups [g1, g2, g3, g4, g5, g6], the list command only prints [g1, g2, g3, g4] when used in combination with `groups` flag.

### Steps to Reproduce

Create a single bal file with below content and execute `bal test --groups g1 --list-groups single-file-tests/grouping/groups-test.bal`

```
import ballerina/test;

@test:Config{
    groups:["g1","g2"]
}
function testFunc1 () {
    test:assertFalse(false, msg = "errorMessage");
}

@test:Config{
    groups:["g1","g2","g3"]
}
function testFunc2 () {
    test:assertFalse(false, msg = "errorMessage");
}

@test:Config{
    groups:["g1","g2","g3","g4"]
}
function testFunc3 () {
    test:assertFalse(false, msg = "errorMessage");
}

@test:Config{
    groups:["g5"]
}
function testFunc4 () {
    test:assertFalse(true, msg = "errorMessage");
}

@test:Config{
    groups:["g6"]
}
function testFunc5 () {
    test:assertFalse(true, msg = "errorMessage");
}

@test:Config{}
function testFunc6 () {
    test:assertFalse(false, msg = "errorMessage");
}
```

### Affected Version(s)

2201.4.0

### Related area

-> Test Framework

**Comment by Thevakumar-Luheerathan** [comment]
Enable `testListGroupsWithOtherFlags` testerina-integration-test method under `GroupingTest.java` once the issue is resolved.
