### ISSUE TITLE
[Task]: Test observability with update 4

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#39626]
### Description

$Subject

### Related area

-> Runtime

**Comment by gabilang** [comment]
Tested with 2201.4.0, no blockers found regarding Observability (Found a minor bug and created an issue https://github.com/ballerina-platform/ballerina-lang/issues/39717). 
Tested with this a multiple service Ballerina project https://github.com/gabilang/travel-agency.
Following is the result from Jaeger for distributed tracing.
![Screenshot from 2023-02-28 08-06-44](https://user-images.githubusercontent.com/35595065/221739160-288ce034-15c4-4cad-a046-3aa8c0f7581d.png)
