### ISSUE TITLE
[Bug]: Regexp toString() method returns the desugared value

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#39635]
### Description

$subject

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
If this issue occurred after https://github.com/ballerina-platform/ballerina-lang/pull/39618/commits/fcdddd9977be81a07ec1bd081fae03e1838de630 commit,

one possible reason for this issue is following addition
```
result = ASTBuilderUtil.createLiteral(reCharacterClass.pos, symTable.stringType, "");
```
Because in here, it creates a new AST node without handling the `toString()` method.

**Comment by SasinduDilshara** [comment]
Tests with following scenarios, which are changed the original regex in runtime. But in those regex paterns, `toString()` works fine.
```
public function main() {
   var r = re `^A&B\s`;
   io:println(r.toString()); //^A&B\s
   io:println(r.toBalString()); //re `^A&B\s`
}
```

**Comment by LakshanWeerasinghe** [comment]
This issue occurred when I desugared a empty character class (`[]`) into a non capturing group pattern (`(?:)`). We pass this desugared nodes into the runtime and the runtime uses the `stringValue` method to get the value for the `toString` method. 

So we have to override the `stringValue` methods to get the correct result for the `toString`.

**Comment by LakshanWeerasinghe** [comment]
Closing this issue because this won't be a concern for now, since we are not going to desugar any regexp value.
