### ISSUE TITLE
[Improvement]: Improve completions in function call expression when there are named arguments 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#39676]
### Description

Improve the completion items provided in different contexts in the function call expression node when there are named arguments specified. 

### Describe your problem(s)

Case 1:

```Ballerina

public function main() {
    testArgs(second = "",<cursor>)
}

function testArgs(int first, string second, int[] third) {

}

```
Only named arg completion items should be suggested

Case 2:

```Ballerina

public function main() {
    testArgs(<cursor>, second = "")
}

function testArgs(int first, string second, int[] third) {

}

```

Suggest both named arg and positional arg completion items. 

### Related area

-> Editor

**Comment by IMS94** [comment]
We have to check the `new expression` for the same behavior and address that.
