### ISSUE TITLE
[Bug]: No error when for invalid additive expression when one operand is a union of members that belong to the same basic type

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#39700]
### Description

The following program compiles without any errors, but it should be a compile-time error. The program attempts to concatenate a string and an int, which is not allowed. The compiler should have detected this type mismatch and thrown an error during the compilation process.

```ballerina
import ballerina/io;

public function main() {
    string:Char o = "s";
    var data = ["10", o].map( m => m + 1);
    io:println(data);
}
```

### Affected Version(s)

2201.5.0-SNAPSHOT

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/39680

**Comment by MaryamZi** [comment]
This isn't an anonymous function issue. Seems to be a bug via `org.wso2.ballerinalang.compiler.semantics.analyzer.Types#validNumericTypeExists`.

```ballerina
public function main() {
    string|string:Char x = "";
    _ = x + 1;
}
```

**Comment by chiranSachintha** [comment]
We need to fix the following kinds of scenarios as well. This should be a compile-time error. Currently, it is compiling without any errors.
```ballerina
import ballerina/io;

public function main() {
    var data = [<string|string>"10"].map( m => m + 1);
    io:println(data);
}
````

**Comment by MaryamZi** [comment]
```ballerina
public function main() {
    string|("a"|"b") a = "a";
    _ = a + 1; // no error
    _ = 1 + a;

    ("a"|"b")|string b = "a";
    _ = b + 1; // no error
    _ = 1 + b;

    string|string:Char c = "s";
    _ = c + 1; // no error
    _ = 1f + c;

    string|string d = "";
    _ = d + 1; // no error
    _ = 1 + d;

    (1|2)|int e = 1;
    _ = e + "";
    _ = "" + e; // no error

    xml:Element|xml:Text f = xml ``;
    _ = f + 1;
    _ = 1 + f; // no error
}
```
