### ISSUE TITLE
[Bug]: HTTP Path parameters are not unescaped from the parser level

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#39770]
### Description

```
import ballerina/http;

type Account record {
    string id;
    string name;
    string email;
    string phone;
};

service /account2\-id on new http:Listener(9090) {

    resource function get account/[string account\-id]() returns Account {
        return {
            id: account\-id,
            name: "John Doe",
            email: "john.doe@email.com",
            phone: "1234567890"
        };
    }
}
```

I have a code like the above which is using the HTTP standard library. When reading path param variables at the HTTP level, `account\-id` has to be read as `account-id`. But currently, it is coming as  `account\-id`.

### Steps to Reproduce

Run the above code in the Ballerina version 2201.4.0 which will give the error `error: service registration failed: Invalid character: '\' in expression`. 

### Affected Version(s)

2201.4.0

### Related area

-> Compilation

**Comment by HindujaB** [comment]
We still need to merge the fix to the master. Hence re-opened.
