### ISSUE TITLE
[Improvement]: Bundle all path params in the resource function to BArray in the native function

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#39781]
### Description

Support following Java interop binding,

The Ballerina function
```
resource function get resourceName/[BT1 p1]/[BT2 p2]/.../[BTn pn](BT1 t1, …, BTn tn) returns BRT = @java:Method {
	[name: “methodName”,]
class: “x.y.z.ClassName”,
} external;
```
The Java function
```
class: 	x.y.z.ClassName;
method: JRT methodName(Environment env, BObject client, BArray pathParams, JT1 t1, JT2 t2, …, JTn tn);
```

Here all the path param values in the Ballerina resource function are bundled to the BArray pathParams variable. BArray with anydata types.

### Describe your problem(s)

In the current support, we need input parameters for each path param defined in the Ballerina resource function. but we have a generic native function that needs to bind to any resource function and we don't know how many path params are in the resource function.

### Describe your solution(s)

Described the in the description.

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/39737

### Suggested label(s) (optional)

jballerina

### Suggested assignee(s) (optional)

@warunalakshitha

**Comment by rdulmina** [comment]
Fixed with #39854
