### ISSUE TITLE
[Improvement]: Add support to get function name, path params details from environment API

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#39783]
### Description

When we deal with native functions, sometimes we need to assign a generic java function to multiple ballerina functions, and the execution logic in the native function needs to know the function name and other path param details to execute the logic. There is no way to get this information in the native function.

### Describe your problem(s)

In the persistent implementation, we generate a Ballerina client and resource functions. these are external resource functions and the native java function is a generic function that can attach to multiple generated resource functions. when we are executing the native code. we need to know the resource function name and path parameters.

### Describe your solution(s)

Give a new API from the Environment class to get the function name and path params.

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/39737

### Suggested label(s) (optional)

jballerina

### Suggested assignee(s) (optional)

@warunalakshitha

**Comment by Nadeeshan96** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39827.
