### ISSUE TITLE
[Bug]: Code Modifier is not running in the vscode

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#39792]
### Description

We have recently add a code modifier in the `http` module to [inject payload annotation automatically on structured parameter types](https://github.com/ballerina-platform/module-ballerina-http/pull/1428) ([Related issue](https://github.com/ballerina-platform/ballerina-standard-library/issues/3276) ). But when I test this in the vs code the code modifier did not ran automatically. Since our code analyser depends on the annotation we are adding from the code modifier, I am seeing unexpected errors.

### Steps to Reproduce

1. Clone this [GitHub repository](https://github.com/TharmiganK/module-ballerina-http.git) and checkout to the `test` branch.

2. Run the following command to build and push the module to the local repository :

    ```console
    ./gradlew clean build -x test -PpublishToLocalCentral=true
    ```

3. Create a new ballerina project, and add this to the `main.bal` file
    
    ```bal
    import ballerina/http;

    type User record {|
        string name;
        int age;
    |};

    service on new http:Listener(9090) {

        resource function post hello(User user) {}
    }
    ```

4. Update the `Ballerina.toml` file to use the local http pack which is published in the step 2.

    ```toml
    [[dependency]]
    org="ballerina"
    name="http"
    repository="local"
    version="2.6.1"
    ```

4. You could see the error from the vscode language server. But if you run the code using `bal run` it will be compiled successfully.

<img width="1249" alt="Screenshot 2023-03-03 at 14 40 07" src="https://user-images.githubusercontent.com/63336800/222679521-a5a722bc-5c1b-46c3-9d4c-220bd70f4d16.png">

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

Mac OS(Ventura) with aarch64

### Related area

-> Other Area

**Comment by IMS94** [comment]
@azinneera @Dilhasha what's the best way for us to tackle this problem? Is exposing the `withCodeModifiers` CompilationOption to be set by LS an option?

**Comment by azinneera** [comment]
> @azinneera @Dilhasha what's the best way for us to tackle this problem? Is exposing the `withCodeModifiers` CompilationOption to be set by LS an option?

Code modifiers are not designed to run on LS. If the change from the code modifier is obvious, can't we remove the validation from the analyzer here?

**Comment by TharmiganK** [comment]
> > @azinneera @Dilhasha what's the best way for us to tackle this problem? Is exposing the `withCodeModifiers` CompilationOption to be set by LS an option?
> 
> Code modifiers are not designed to run on LS. If the change from the code modifier is obvious, can't we remove the validation from the analyzer here?

@azinneera We have separate validations depends on whether the parameter is payload or query. This is currently identified by the payload annotation (which is set by the code modifier). And we have a logic in the code modifier to identify structural types to add this annotation. 

So in order to skip the validations in the analyser we need to know the parameter type i.e. we may have to duplicate the logic in the code modifier to the analyzer to identify the structural types.

**Comment by chamil321** [comment]
> > @azinneera @Dilhasha what's the best way for us to tackle this problem? Is exposing the `withCodeModifiers` CompilationOption to be set by LS an option?
> 
> Code modifiers are not designed to run on LS. If the change from the code modifier is obvious, can't we remove the validation from the analyzer here?

Ideally LS should be able to incorporate code modifier changes for their analysis. Otherwise code modifier feature will not be very useful for Stdlibs.
 
One workaround is to skip the particular validation only for both query param types and payload param types at the analysis task. That means basic-simple, basic-sequence and basic-structured types (https://ballerina.io/spec/lang/master/#section_5.1.4)

But it is not ideal, at code modifier level we provide error diagnostics when there are ambiguity between query param type and Payload param type. Those error will not be reflected if we don't incorporate code modifiers.
