### ISSUE TITLE
[Bug]: Gradle build with `-P publishToLocalCentral=true` flag fails.

### ISSUE THREAD

**Issue by Ishad-M-I-M** [ballerina-platform/ballerina-lang#39825]
### Description

The `gradle clean build -P publishToLocalCentral=true` command fails with following issue. But the files can be found in the relevant location. (ballerina\build\bal_build_target\bala\platform\java11)
```
Publishing to the ballerina local central repository..
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
ballerina/graphql:1.6.2 [project repo -> central] 100% [==========] 271/271 KB
ballerina: failed to push the package: 'ballerina/graphql:1.6.2' reason:missing platform libraries in bala file: [platform\java11\graphql-native-1.6.2-SNAPSHOT.jar, platform\java11\graphql-commons-1.6.2-SNAPSHOT.jar]
```

### Steps to Reproduce

- Run  `gradle clean build -P publishToLocalCentral=true`  for `module-ballerina-graphql`

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

OS: Windows 11

### Related area

-> Dev-tools

**Comment by azinneera** [comment]
According to the error message, there seems to be an issue with the platform libraries. Can you check if the required libraries are created properly?
