### ISSUE TITLE
[Improvement]: Remove `version` keyword 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#39833]
### Description

Since we are no longer using the `version` as a keyword, we can remove this restriction from the parser. 

### Related area

-> Compilation

**Comment by ushirask** [comment]
@hasithaa  `version` keyword is still allowed at parser level although it's no longer supported. Should we only remove restriction on `version` as an identifier explicitly as suggested, or should we remove parsing `version` as a keyword altogether.

**Comment by hasithaa** [comment]
Yes, since it is not a key word anymore.
