### ISSUE TITLE
[Bug]: Incorrect default value shown in VS Code API Docs help

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#39853]
### Description

$subject observed for the `Listener` in `ballerinax/trigger.google.drive`

<img width="947" alt="image" src="https://user-images.githubusercontent.com/16300038/224372708-2a145f93-0236-4783-9799-aaf5a195408f.png">

The real default values is `8090` although it shows as `0` above.

https://lib.ballerina.io/ballerinax/trigger.google.drive/0.9.1#Listener-constructor

### OS, DB, other environment details and versions

Ballerina 2201.3.2 (Swan Lake Update 3)
Language specification 2022R4
Update Tool 1.3.13

Plugin version : v3.3.13

### Related area

-> Compilation

**Comment by IMS94** [comment]
The cause for this issue is that `google drive` listener hasn't documented the `listenOn` parameter and the LS had not handled missing parameters. 
![Screenshot from 2023-03-21 13-11-21](https://user-images.githubusercontent.com/11285165/226544051-4ec6018f-57fd-40f7-9e39-4b05a79d4da5.png)

**Comment by IMS94** [comment]
This hadn't been completely fixed with #39988. #40540 was caused by the fix. Will be addressed with #40542
