### ISSUE TITLE
[Improvement]: Introduce distribution field to Dependencies.toml and bump dependencies if a higher distribution is used

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#39850]
### Description

Currently, the `Dependencies.toml` does not record the distribution version that is used to build the ballerina project. However it records the versions of dependencies that the previous build has used. Moreover, the dependencies are only bumped in patch versions from what is specified in `Dependencies.toml`.

### Describe your solution(s)

The above needs to be changed as follows.
1. `Dependencies.toml` should keep track of the distribution version used as follows.
    ``` toml
    [ballerina]
    dependencies-toml-version = "2"
    distribution-version = "2201.5.0"
    ``` 
    In order to be backward compatible, field `distribution-version` should be optional.
2. If a project is built using a newer distribution version than what is recored in the `Dependencies.toml`, the dependencies should be bumped to the latest minor version compatible with that distribution version. 
3. If the distribution version is not mentioned in the `Dependencies.toml`, the dependency versions should be bumped similar to (2).

### Related area

-> Compilation

**Comment by gayaldassanayake** [comment]
Re opening since we need to add more automated tests to validate the functionality. However the feature is implemented and merged to the master branch. This will go with SL Update 5.

**Comment by azinneera** [comment]
We should add CLI tests as well. Opening the issue to track it.

**Comment by gayaldassanayake** [comment]
Need to update documentation in https://ballerina.io/learn/manage-dependencies/#update-dependency-versions to match this change.
