### ISSUE TITLE
[Bug]: Prometheus linter fails for Prometheus metrics reported by Ballerina

### ISSUE THREAD

**Issue by nilushancosta** [ballerina-platform/ballerina-lang#39862]
### Description

Prometheus has a `promtool check metrics` commands. This runs a built in linter where we can pass Prometheus metrics over stdin to lint them for consistency and correctness.

When I ran this command for Ballerina Promethus metrics, linting failed.
E.g. Error message
```
error while linting: text format parsing error in line 17: second HELP line for metric name "response_time_seconds"
```

### Steps to Reproduce

1. Create a new project by executing `bal new` command
2. Add the following program to the `main.bal` file
```
import ballerina/http;
import ballerinax/prometheus as _;

service /srvc on new http:Listener(8090) {
    resource function get test() returns record{}|error {
        http:Client httpEp = check new (url = "https://postman-echo.com");
        record {} getResponse = check httpEp->get(path = "/get");
        return getResponse;
    }
}
```
3. Add a `Config.toml` file with the following configuration to enable the Prometheus metrics exporter
```
[ballerina.observe]
metricsEnabled=true
metricsReporter="prometheus"
``` 

4. Run it by executing `bal run` and send several requests to `http://localhost:8090/srvc/test
5. Execute the following to run the linter. If you are using `brew` you can install the tool through Prometheus (`brew install prometheus`)
```
curl http://localhost:9797/metrics | promtool check metrics
```

### Affected Version(s)

```
Ballerina 2201.4.0 (Swan Lake Update 4)
Language specification 2022R4
Update Tool 1.3.13
```

### Related area

-> Observability

**Comment by NipunaMadhushan** [comment]
This error occurs due to formatting error in the following several metrics.

```
response_time_seconds_mean
response_time_seconds_max
response_time_seconds_min
response_time_seconds_stdDev
```
These metrics are positioned under summary metrics for `response_time_seconds` which contains the headers for `TYPE` and `HELP` text only for `response_time_seconds` metric.

**Comment by NipunaMadhushan** [comment]
Noticed that we provide HELP text and TYPE text each and every metric with the same metric name which is not the correct format of metric exposition.

The metric exposition format can be found [here](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md).

**Comment by NipunaMadhushan** [comment]
After correcting the above mentioned formatting issue, I received the following response for the promtool metric check.

```
requests_total_value counter metrics should have "_total" suffix
response_time_nanoseconds_total_value counter metrics should have "_total" suffix
response_time_nanoseconds_total_value use base unit "seconds" instead of "nanoseconds"
response_time_seconds_max no help text
response_time_seconds_mean no help text
response_time_seconds_min no help text
response_time_seconds_stdDev metric names should be written in 'snake_case' not 'camelCase'
response_time_seconds_stdDev no help text
```

Usually counter metric name should end with `total` or `sum` according to the best practices of metrics naming and labelling. 
The best practices for naming metrics and labels can be found [here](https://prometheus.io/docs/practices/naming/).
The data model of metrics can be found [here](https://prometheus.io/docs/concepts/data_model/).

**Comment by NipunaMadhushan** [comment]
[PR](https://github.com/ballerina-platform/module-ballerinax-prometheus/pull/163) will resolve the formatting issues regarding the metric data model. 

How ever there are still other formatting issues related to metrics and label naming conventions.
* `requests_total_value` - counter metrics should have "_total" suffix
* `response_time_seconds_stdDev` - metric names should be written in 'snake_case' not 'camelCase'
* `timeWindow` - label names should be written in 'snake_case' not 'camelCase'
