### ISSUE TITLE
[New Feature]:  Completion support for compiler plugins 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#39892]
### Description
Story: Compiler plugins for standardlibs such as http, grpc, and graphql should be able to provide their own completion items in different completion contexts.

Constraints: The completion items should only be provided when the compiler plugins are activated or when there is an import statement in a particular module. 

Example

### http

1. Provide custom resource function snippets in service body context

eg: `get, post, delete, etc. `

![image](https://user-images.githubusercontent.com/35211477/229456644-6ac614f7-d626-4627-ac90-0bc531ccf0fc.png)

	
2. Provide completion items for new expressions with different arguments inside function body block context

     eg:  new expression for a secure client, a client with JWT authentication

![image](https://user-images.githubusercontent.com/35211477/229457481-46155774-21f3-40fa-9f6e-49ba5ea1084c.png)

3. Provide completion items in the module part context

     listeners, clients, custom service snippets, etc.

### udp

![image](https://user-images.githubusercontent.com/35211477/229457708-511100d4-ad9f-4a6f-b46e-c33da86e2dda.png)

Provide onDatagram(), onByte() completion items inside the service body context

More information: https://docs.google.com/document/d/1lwfYLjyjtXjHc8-2F3hcgsLjmcKHAXTOKo99mR08Fas/edit?usp=sharing

### Related area

-> Compilation

**Comment by nadeeshaan** [comment]
AFAIU, in the current implementation, the completions provided are context-sensitive. Hence, the plugins should be able to inject completion items into the relevant context. What's the approach to achieving that? Are we going to publish the completion extension jar along with the lib itself?

**Comment by malinthar** [comment]
> Just out of curiosity, AFAIU in the current implementation, the completions provided are context-sensitive. Hence, the plugins should be able to inject completion items into the relevant context. What's the approach to achieving that? Are we going to publish the completion extension jar along with the lib itself?

We will allow the plugins to provide the completions items based on the context. For this, we intend to use a completion context with limited number of properties such as nodeAtCusror, cursorPosition, currentSyntaxTree, etc.  

Each compiler plugin(lib) will add a CompletionProvider object  to it's context at the initialization of the plugin. Therefore the completion extension(provider) will be in the lib it self as depicted in the following class diagram.


```mermaid
classDiagram
    LangExtensionDelegator <-- TextDocumentService:completions()
    CompletionExtension <|-- CompilerPluginCompletionExtension
    PositionedActionContext <|-- CompletionContext
    CompletionContext <|-- CompletionContextImpl
    CompletionProvider <|-- AbstractCompletionProvider

    CompilerPluginCompletionExtension <-- LangExtensionDelegator:completions()
    CompletionContextImpl <-- CompilerPluginCompletionExtension:create()
    CompletionProvider <-- CompilerPlugin : create()
    CompilerPlugin <-- CompilerPluginManager:init()
    CompletionItem <-- CompletionProvider:create()
    CompletionUtil <-- CompletionProvider:uses
    CompletionContext <-- CompletionManager:uses
    CompletionContext <-- CompletionProvider:uses

    LangExtensionDelegator *-- CompletionExtension
    CompletionManager <-- CompilerPluginCompletionExtension:completions()
    PackageCompilation *-- CompilerPluginManager
    CompilerPluginManager *-- CompletionManager
    CompletionProvider <-- CompletionManager:getCompletions()
    CompilerPluginManager *-- CompilerPluginContext
    CompilerPluginContext *-- CompletionProvider  

```
