### ISSUE TITLE
[Bug]: BIR reads params incorrectly in attached functions

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-lang#39900]
### Description

GraphQL module has defined `Interceptor` type as follows:
```ballerina
public type Interceptor readonly & distinct service object {
    isolated remote function execute(Context context, Field 'field) returns anydata|error;
};
```

In GraphQL service config, It accepts an array or single Interceptor:
```ballerina
public type GraphqlServiceConfig record {|
    readonly Interceptor|Interceptor[] interceptors = [];
|};
```
Consider the following GraphQL service:
```ballerina
import ballerina/graphql;
import ballerina/log;

readonly service class LogInterceptor {
    *graphql:Interceptor;

 isolated remote function execute(graphql:Context context, graphql:Field 'field)
    returns anydata|error {
        string fieldName = 'field.getName();
        log:printInfo(string `Field "${fieldName}" execution started!`);
        var data = context.resolve('field);
        log:printInfo(string `Field "${fieldName}" execution completed!`);
        return data;

    }
}

@graphql:ServiceConfig {
    interceptors: new LogInterceptor()
}
service /graphql on new graphql:Listener(9090) {
    isolated resource function get name() returns string {
        log:printInfo("Executing the field \"name\"");
        return "GraphQL Interceptors";
    }
}
```
When running the above service, it returns the following compilation error.
```shell
ERROR [main.bal:(14:5,36:6)] mismatched function signatures: expected 'public function execute(ballerina/graphql:1.7.0:Context , ballerina/graphql:1.7.0:Field ) returns (anydata|error)', found 'public function execute(ballerina/graphql:1.7.0:Context context, ballerina/graphql:1.7.0:Field field) returns (anydata|error)'
error: compilation contains errors
```
But there is no difference between these function signatures. 

### Steps to Reproduce

1. Clone this GraphQL branch https://github.com/DimuthuMadushan/module-ballerina-graphql/tree/interceptor and build using `./gradlew clean build -x test`
2. Use the intermediate pack generated at the `root/target` directory to run the above sample GraphQL service.

### Affected Version(s)

2201.4.0

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Seems like it could be because the parameter names are not available when loaded via the BIR - https://github.com/ballerina-platform/ballerina-lang/blob/v2201.4.0/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L618.

**Comment by ThisaruGuruge** [comment]
@MaryamZi Do we have an ETA for the fix? This is affecting the GraphQL implementation. We do have a workaround for now, but if we can get this fixed it would be better.

**Comment by MaryamZi** [comment]
> @MaryamZi Do we have an ETA for the fix? This is affecting the GraphQL implementation. We do have a workaround for now, but if we can get this fixed it would be better.

Since this will require BIR changes, this will most likely be fixed only for the next update release.
