### ISSUE TITLE
[Task]: Test Update 5 features

### ISSUE THREAD

**Issue by ShammiL** [ballerina-platform/ballerina-lang#39936]
### Description

Test the new features in Update 5.

### Describe your task(s)

- Test possible scenarios for `bal deprecate`.
- Test the distribution-version field to the Dependencies.toml and changing dependency resolution based on the distribution field.

### Related area

-> Other Area

**Comment by Thevakumar-Luheerathan** [comment]
Following doc contains the scenarios which were tested
https://docs.google.com/document/d/1RjSLmmTeFMoKQWVGe-o2ZXmEq80twa-ewbDUHlaDpbk/edit

Test result of connectors can be found below
https://docs.google.com/spreadsheets/d/1mvVAqsOWaKVoUkNA4smpv9sMOFeCMwea_GdzENrV8BI/edit?usp=sharing

**Comment by gayaldassanayake** [comment]
Smoke tested Dependency updating feature with a set of scenarios and works as expected, including the LS functionality.
