### ISSUE TITLE
[Improvement]: Marking the starting and ending bounds within a regexp

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#39949]
### Description

```ballerina
public function main() {
    _ = re `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`;
   _ = re `(ab(c))`;
}
```

Is it possible to mark/highlight the start and end bounds when `[``]`/`(``)` is clicked

### Related area

-> Other Area

**Comment by IMS94** [comment]
This is possible. The LSP has a feature called [`Document Highlighting`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight) that does exactly this. But the LS hasn't implemented this method. Whatever the highlighting that you get on VSCode right now is the default highlighting by VSCode.

LS has to implement highlighting support. It means, we have to consider providing highlight support for other symbols too.
