### ISSUE TITLE
[Bug]: Getting `IllegalArgumentException` with multiple newlines inside `main` function

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#39947]
### Description

![Illegale](https://user-images.githubusercontent.com/25485997/226640395-dc3334e0-8935-4229-bbc2-1ec642cdf522.gif)

### Steps to Reproduce

```
public function main() {
    record { int a; int b; } r = {a: 1, b: 2}; <cursor>
}
```

Try adding several newlines at cursor position 

### Affected Version(s)

2201.3.4, 2201.4.0

### Related area

-> Editor

**Comment by malinthar** [comment]
Closing as no longer reproducible 
![new_line](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/24f21e51-10c1-4356-93f0-606861b126cf)
