### ISSUE TITLE
[Bug]: Compilation fails when using query expressions to assign values for union typed record fields

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#40012]
### Description

Getting the following compilation error when I'am trying to assign values to union typed record field using query expression.
```
ambiguous type '[org/project:0.1.0:T3, org/project:0.1.0:T3]'
```

### Steps to Reproduce

Sample source:
```ballerina

type T1 record {
    T3[] t3s;
};

type T2 record {
    T3[]|T4[] t3OrT4;
};

type T3 record {
    string str;
};

type T4 record {
    boolean foo;
};

function transform(T1 t1) returns T2 => {
    t3OrT4: from var t3sItem in t1.t3s
        select {
           str: ""
        }
};
```

The error remains even I did a type cast within the select clause
```ballerina
function transform(T1 t1) returns T2 => {
    t3OrT4: from var t3sItem in t1.t3s
        select <T3>{
           str: ""
        }
};
```

### Affected Version(s)

Ballerina `2201.4.0`

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
Please consider the following code

```
type Book record {|
    string title;
    string author;
|};

class BookGenerator {
    int i = 0;

    public isolated function next() returns record {|Book value;|}|error? {
        self.i += 1;
        if (self.i < 0) {
            return error("Error");
        } else if (self.i >= 3) {
            return ();
        }
        return {
            value: {
                title: "Title " + self.i.toString(), author: "Author " + self.i.toString()
            }
        };
    }
}

function testSimpleQueryExprForStringNegative() returns error? {
    string:Char chr = "a";
    BookGenerator bookGenerator = new ();
    stream<Book, error?> bookStream = new (bookGenerator);

    string:Char[]|string _ = check from Book _ in bookStream
        select chr;  // ambiguous type '[string:Char, string:Char]'
    string:Char[]|int|string _ = check from Book _ in bookStream
        select chr; //  ambiguous type '[string:Char, string:Char, string:Char]'
    [string:Char, string:Char]|int|string _ = check from Book _ in bookStream
        select chr; // ambiguous type '[string:Char, string:Char, string:Char]'

    xml|int[] xmlValue = check from Book book in bookStream
        select xml `<Book>
                        <Author>${book.author}</Author>
                        <Title>${book.title}</Title>
                    </Book>`; // ambiguous type '[xml:Element, xml:Element]'
}
```

This compiled with following errors

```
ERROR [test.bal:(36:16,36:19)] ambiguous type '[string:Char, string:Char]'
ERROR [test.bal:(38:16,38:19)] ambiguous type '[string:Char, string:Char, string:Char]'
ERROR [test.bal:(40:16,40:19)] ambiguous type '[string:Char, string:Char, string:Char]'
ERROR [test.bal:(43:16,46:29)] ambiguous type '[xml:Element, xml:Element]'
```

The error messages are also seems wrong in here.

**Comment by sanjana** [comment]
> Please consider the following code
> 
> ```
> type Book record {|
>     string title;
>     string author;
> |};
> 
> class BookGenerator {
>     int i = 0;
> 
>     public isolated function next() returns record {|Book value;|}|error? {
>         self.i += 1;
>         if (self.i < 0) {
>             return error("Error");
>         } else if (self.i >= 3) {
>             return ();
>         }
>         return {
>             value: {
>                 title: "Title " + self.i.toString(), author: "Author " + self.i.toString()
>             }
>         };
>     }
> }
> 
> function testSimpleQueryExprForStringNegative() returns error? {
>     string:Char chr = "a";
>     BookGenerator bookGenerator = new ();
>     stream<Book, error?> bookStream = new (bookGenerator);
> 
>     string:Char[]|string _ = check from Book _ in bookStream
>         select chr;  // ambiguous type '[string:Char, string:Char]'
>     string:Char[]|int|string _ = check from Book _ in bookStream
>         select chr; //  ambiguous type '[string:Char, string:Char, string:Char]'
>     [string:Char, string:Char]|int|string _ = check from Book _ in bookStream
>         select chr; // ambiguous type '[string:Char, string:Char, string:Char]'
> 
>     xml|int[] xmlValue = check from Book book in bookStream
>         select xml `<Book>
>                         <Author>${book.author}</Author>
>                         <Title>${book.title}</Title>
>                     </Book>`; // ambiguous type '[xml:Element, xml:Element]'
> }
> ```
> 
> This compiled with following errors
> 
> ```
> ERROR [test.bal:(36:16,36:19)] ambiguous type '[string:Char, string:Char]'
> ERROR [test.bal:(38:16,38:19)] ambiguous type '[string:Char, string:Char, string:Char]'
> ERROR [test.bal:(40:16,40:19)] ambiguous type '[string:Char, string:Char, string:Char]'
> ERROR [test.bal:(43:16,46:29)] ambiguous type '[xml:Element, xml:Element]'
> ```
> 
> The error messages are also seems wrong in here.

After applying the fix at #40077, this error would no longer occur. 
But the incompatible types error would occur as pointed in #40013. 
@LakshanWeerasinghe can this case also be validated in the fix of #40013 (Need to pull the changes at #40077).

**Comment by sanjana** [comment]
> @sanjana Any idea about the ETA of this? What would be the Ballerina version that is supposed to have this fix?

@madushajg We are targeting to include this in the update 6. The PR is updated. Getting it reviewed and expecting to merge it as soon as possible.

**Comment by madushajg** [comment]
okay great! 
Thanks for the update

**Comment by sanjana** [comment]
We found a bug related to the type checker when proceeding the current fix. Therefore will be revisiting the approach and will be sending the fix in a patch version.
