### ISSUE TITLE
[Bug]: Compilation fails when using ternary expression within select clauses

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#40013]
### Description

Getting `incompatible types: expected '<TYPE_A>', found '<TYPE_B>'` error when I'am trying to use a ternary expression within a select clause.

### Steps to Reproduce

Sample source:
```ballerina
type T1 record {
    T3[] t3s;
};

type T2 record {
    T3[]|T4[] t3OrT4;
};

type T3 record {
    string str;
};

type T4 record {
    boolean foo;
};

function transform(T1 t1) returns T2 => {
    t3OrT4: from var t3sItem in t1.t3s
        select t3sItem.str == ""
        ? <T3>{
           str: ""
        } : <T4>{
            foo: false
        }
};
```

### Affected Version(s)

Ballerina `2201.4.0`

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
In the example you provided, getting an compile time error is the correct behavior. We cannot have a union type inside a select clause. Because `type T2` should have a either array of `T3` or `T4`.

Consider the below case,
```
type T1 record {
    boolean b;
};

type T2 record {
    string str;
};

function name() {
    T1[]|T2[] array = [returnT1OrT2("")];
}

function returnT1OrT2(string value) returns T1|T2 {
    if value == "" {
        return <T1> { b: false};
    }
    return <T2> { str:  value };
}
```
This is a simplified version explaining what you have done here. So getting a compilation error is correct.

**Comment by LakshanWeerasinghe** [comment]
Further you can declare `type T2` as below. This way you will not get any error. But the `(T3|T4)[]` and `T3[]|T4[]` have two different meanings.
```
type T2 record {
    (T3|T4)[] t3OrT4;
};
```

**Comment by LakshanWeerasinghe** [comment]
In this issue will improve the error diagnostic we give. The solution will contain following things,

1. Diagnostic position will be, beginning of the from clause to end of the select clause.
2. The expected and actual types will resolved correctly and shown in the diagnostic.

**Comment by madushajg** [comment]
> In the example you provided, getting an compile time error is the correct behavior. We cannot have a union type inside a select clause. Because `type T2` should have a either array of `T3` or `T4`.
> 
> Consider the below case,
> 
> ```
> type T1 record {
>     boolean b;
> };
> 
> type T2 record {
>     string str;
> };
> 
> function name() {
>     T1[]|T2[] array = [returnT1OrT2("")];
> }
> 
> function returnT1OrT2(string value) returns T1|T2 {
>     if value == "" {
>         return <T1> { b: false};
>     }
>     return <T2> { str:  value };
> }
> ```
> 
> This is a simplified version explaining what you have done here. So getting a compilation error is correct.

I see. Thanks for the clarification.

**Comment by LakshanWeerasinghe** [comment]
Blocked by #40012

**Comment by LakshanWeerasinghe** [comment]
We improvement of the error message will be,
```
incompatible types: expected 'T3[]|T4[]', found '(T3|T4)[]'
```
