### ISSUE TITLE
`statas.code` is 0 in Jeager output

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#40018]
<img width="816" alt="Screenshot 2023-02-08 at 17 12 25" src="https://user-images.githubusercontent.com/6178058/217520354-83a2c6be-9cc5-4ac0-b3f6-1d67aa9ce249.png">

Use the below code to reproduce
https://github.com/shafreenAnfar/springboot-and-ballerina/tree/main/ballerina-user-rest-service

**Comment by shafreenAnfar** [comment]
Transferred the issue Ballerina lang as observerbility is done at lang level. Please feel free to re-transfer if needed.

**Comment by NipunaMadhushan** [comment]
Noticed that the `status.code` tag only appears in Jaeger and not appeared in Zipkin or New Relic. Also checked whether we add a tag with key name `status.code` and not found.
<img width="1440" alt="Screenshot 2023-11-23 at 22 07 17" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/e2c87de4-61fd-4958-9d2d-ba26403a6be9">
<img width="1440" alt="Screenshot 2023-11-23 at 22 07 47" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/48c22f52-5dc2-4cb6-8bec-782d43bf759c">
