### ISSUE TITLE
[Bug]: Experiencing slowness compiling nBallerina with SL Update 4

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#40024]
### Description

**2201.4.0**
$subject. Build time details are as follows.

- `bal build --dump-build-time` after a `bal clean`:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680065492243
        offline : false
        compile : false
        projectLoadDuration : 674
        packageResolutionDuration : 10824
        packageCompilationDuration : 126542
        codeGenDuration : 4080
        emitArtifactDuration : 566
        testingExecutionDuration : 0
        totalDuration : 142717
```     
 - 2nd build:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066214492
        offline : false
        compile : false
        projectLoadDuration : 771
        packageResolutionDuration : 5496
        packageCompilationDuration : 60900
        codeGenDuration : 4861
        emitArtifactDuration : 568
        testingExecutionDuration : 0
        totalDuration : 72633        
```        
- `bal build --offline --dump-build-time` after a `bal clean`:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066323368
        offline : true
        compile : false
        projectLoadDuration : 783
        packageResolutionDuration : 1066
        packageCompilationDuration : 5740
        codeGenDuration : 4630
        emitArtifactDuration : 532
        testingExecutionDuration : 0
        totalDuration : 12783
```
- 2nd build:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066367428
        offline : true
        compile : false
        projectLoadDuration : 763
        packageResolutionDuration : 955
        packageCompilationDuration : 5539
        codeGenDuration : 6000
        emitArtifactDuration : 991
        testingExecutionDuration : 0
        totalDuration : 14289
```     
**2201.3.0**

`bal build --dump-build-time` after a `bal clean`:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066549834
        offline : false
        compile : false
        projectLoadDuration : 663
        packageResolutionDuration : 9604
        packageCompilationDuration : 3114
        codeGenDuration : 5437
        emitArtifactDuration : 1011
        testingExecutionDuration : 0
        totalDuration : 19855
```        
- 2nd build:
```
Dumping build time information
        target/build-time.json
        timestamp : 1680066649461
        offline : false
        compile : false
        projectLoadDuration : 763
        packageResolutionDuration : 5726
        packageCompilationDuration : 3340
        codeGenDuration : 5156
        emitArtifactDuration : 753
        testingExecutionDuration : 0
        totalDuration : 15778        
```
- `bal build --offline --dump-build-time` after a `bal clean`:
```        
Dumping build time information
        target/build-time.json
        timestamp : 1680066711687
        offline : true
        compile : false
        projectLoadDuration : 688
        packageResolutionDuration : 1079
        packageCompilationDuration : 3482
        codeGenDuration : 6225
        emitArtifactDuration : 689
        testingExecutionDuration : 0
        totalDuration : 12187
```      
 - 2nd build:
```
 Dumping build time information
        target/build-time.json
        timestamp : 1680066748891
        offline : true
        compile : false
        projectLoadDuration : 695
        packageResolutionDuration : 935
        packageCompilationDuration : 3358
        codeGenDuration : 7358
        emitArtifactDuration : 1113
        testingExecutionDuration : 0
        totalDuration : 13497       
```         

### Steps to Reproduce

Execute `bal build` at nBallerina repo compiler module. https://github.com/ballerina-platform/nballerina/tree/main/compiler

### Affected Version(s)

2201.4.0

### OS, DB, other environment details and versions

Ubuntu 20.04

### Related area

-> Compilation

**Comment by azinneera** [comment]
From the Project API PoV, the behaviour is excepted. The offline builds in both distributions have similar duration which is what we must compare. Here is the reason for the different compilation times in U4:

> ### Description
> **2201.4.0** $subject. Build time details are as follows.
> 
> * `bal build --dump-build-time` after a `bal clean`:
> 
> ```
> Dumping build time information
>         target/build-time.json
>         timestamp : 1680065492243
>         offline : false
>         compile : false
>         projectLoadDuration : 674
>         packageResolutionDuration : 10824
>         packageCompilationDuration : 126542
>         codeGenDuration : 4080
>         emitArtifactDuration : 566
>         testingExecutionDuration : 0
>         totalDuration : 142717
> ```
> 
1. There can be dependencies compiled using the source (.bala)
2. After the execution of code generators, the Project API caches are discarded and so resolution is run again. Since its an online compilation, the slowness is expected.

> * 2nd build:
> 
> ```
> Dumping build time information
>         target/build-time.json
>         timestamp : 1680066214492
>         offline : false
>         compile : false
>         projectLoadDuration : 771
>         packageResolutionDuration : 5496
>         packageCompilationDuration : 60900
>         codeGenDuration : 4861
>         emitArtifactDuration : 568
>         testingExecutionDuration : 0
>         totalDuration : 72633        
> ```
> 
* Still the compilation is online but the dependencies are compiled using the BIR. Hence the time is improved than the first one.

> * `bal build --offline --dump-build-time` after a `bal clean`:
> 
> ```
> Dumping build time information
>         target/build-time.json
>         timestamp : 1680066323368
>         offline : true
>         compile : false
>         projectLoadDuration : 783
>         packageResolutionDuration : 1066
>         packageCompilationDuration : 5740
>         codeGenDuration : 4630
>         emitArtifactDuration : 532
>         testingExecutionDuration : 0
>         totalDuration : 12783
> ```
> 
> * 2nd build:
> 
> ```
> Dumping build time information
>         target/build-time.json
>         timestamp : 1680066367428
>         offline : true
>         compile : false
>         projectLoadDuration : 763
>         packageResolutionDuration : 955
>         packageCompilationDuration : 5539
>         codeGenDuration : 6000
>         emitArtifactDuration : 991
>         testingExecutionDuration : 0
>         totalDuration : 14289
> ```
> 
The significant drop in the duration is because its run offline. This is almost equal to the time taken in U3 offline build.

**Comment by lochana-chathura** [comment]
> From the Project API PoV, the behaviour is excepted. The offline builds in both distributions have similar duration which is what we must compare.

I am still not convinced by your justification. If we are executing the same cmd(`bal build`) from U3 vs U4 and there's a significant difference in terms of time for the same action. Shouldn't the update 4 changes responsible for that?

**Comment by azinneera** [comment]
> > From the Project API PoV, the behaviour is excepted. The offline builds in both distributions have similar duration which is what we must compare.
> 
> I am still not convinced by your justification. If we are executing the same cmd(`bal build`) from U3 vs U4 and there's a significant difference in terms of time for the same action. Shouldn't the update 4 changes responsible for that?

The time of the compilation can increase based on the changes added by the compiler plugins. If there are any changes to the existing compiler plugins or addition of new ones, then this will increase the compilation time. So we can check if there is a change in the compiler plugins.
