### ISSUE TITLE
[Bug]: resource path is null when we get type from node using semantic model

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-lang#40036]
### Description

When generating API docs for client objects in http module, it will fall under type reference node. When we get the type from the node using semantic model, for resource functions, it says the resource path is null.

<img width="741" alt="Screenshot 2023-03-30 at 10 32 46" src="https://user-images.githubusercontent.com/51471998/228734840-baf78511-8bc7-458f-806a-e2185276ac81.png">

### Steps to Reproduce

I have used http module to generate API docs

### Related area

-> Compilation

**Comment by rdulmina** [comment]
@NipunaMadhushan can u put the sample code in the description

**Comment by NipunaMadhushan** [comment]
@rdulmina sure.

https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/http_client_object.bal
https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/resiliency_failover_client.bal#L79

**Comment by dulajdilshan** [comment]
resource-path is calculated on-demand. Therefore, we can use `resourcePath()` API to get it

**Comment by dulajdilshan** [comment]
Currently, we don't have a method to get the tye of the rest-path-param. Need to have this fix from the Semantic API side

**Comment by dulajdilshan** [comment]
Approach: Create symbols for resource path and include type information inside them
