### ISSUE TITLE
[Improvement]: Introduce an approach to mock resource methods when using object mocking

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#40059]
### Description

The existing member mocking implementation support in Object mocking has limitations when used to mock resource functions within a client object.

The following are the limitations to address.

- When the resource method is invoked as `client->/foo/bar` in source code
There is no name for the resource function and we need to differentiate cases between the HTTP verbs.

- when the resource method is invoked as `client->get("/foo/bar")` in source code
The member function mocking approach works only if it is the only `get` used within a particular test case. If there are invocations to multiple get resources, only one mock definition is effective and the tests fail to mock.

We need to introduce an approach to mock resource methods addressing the above limitations.

### Describe your problem(s)

Consider a sample ballerina service as follows.

```
import ballerina/http;

service / on new http:Listener(9090) {

    // This function responds with `string` value `Hello, World!` to HTTP GET requests.
    resource function get greeting() returns string {
        return "Hello, World!";
    }
    resource function get number() returns int {
        return 123;
    }
}

```

And, a ballerina project with the following sample source and test files in default module which invokes above service.

`main.bal`

```
import ballerina/http;
import ballerina/io;

http:Client cl = check new ("http://localhost:9090");

public function main() {
    string greeting = getGreeting();
    io:println(greeting);
    int num = getNum();
    io:println(num);
    string both = getBoth();
    io:println(both);
}

function getBoth() returns string {
    return getGreeting() + getNum().toString();
}

function getGreeting() returns string {
    string|error val = cl->get("/greeting");
    if (val is string) {
        return val;
    } else {
        return "";
    }
}

function getNum() returns int {
    int|error num = cl->get("/number");
    if num is error {
        return 0;
    } else {
        return num;
    }
}
```

`main_test.bal`

- When multiple get resources are invoked within a source function e.g. `getBoth`

```
import ballerina/test;
import ballerina/http;

@test:Config {}
function testFunction() {
    cl = test:mock(http:Client);
    test:prepare(cl).when("get").thenReturn("Hello World");
    test:assertEquals("Hello World", getGreeting());
    test:prepare(cl).when("get").thenReturn(1);
    test:assertEquals(1, getNum());
    test:assertEquals("Hello World1", getBoth());
}
```

This crashes the test when trying to call both.

- When only mocking one `get` function at a time as in the following test, it successfully completes the mocking.

```
import ballerina/http;
@test:Config {}
function testFunction() {
    cl = test:mock(http:Client);
    test:prepare(cl).when("get").thenReturn("Hello World");
    test:assertEquals("Hello World", getGreeting());
    test:prepare(cl).when("get").thenReturn(1);
    test:assertEquals(1, getNum());
}
```

### Related area

-> Compilation

**Comment by Dilhasha** [comment]
Until this is fixed, the test double based object mocking approach can be used instead.

https://ballerina.io/learn/test-ballerina-code/mocking/#create-a-test-double

**Comment by Thevakumar-Luheerathan** [comment]
> Until this is fixed, the test double based object mocking approach can be used instead.
> 
> https://ballerina.io/learn/test-ballerina-code/mocking/#create-a-test-double

test double seems having some issues https://github.com/ballerina-platform/ballerina-lang/issues/40810

**Comment by Dilhasha** [comment]
> > Until this is fixed, the test double based object mocking approach can be used instead.
> > https://ballerina.io/learn/test-ballerina-code/mocking/#create-a-test-double
> 
> test double seems having some issues #40810

Test Double is working as expected. Identified an issue with exception handling for multi-module packages. Please refer https://github.com/ballerina-platform/ballerina-lang/issues/40810#issuecomment-1623486141

**Comment by Dilhasha** [comment]
For the issue of multiple resource functions, we can use `withArguments` option to overcome the issue of crashing and handling various invocations. 

> when the resource method is invoked as client->get("/foo/bar") in source code
The member function mocking approach works only if it is the only get used within a particular test case. If there are invocations to multiple get resources, only one mock definition is effective and the tests fail to mock.

Sample test for the provided example:

`main_test.bal`

```
import ballerina/test;
import ballerina/http;

@test:Config {}
function testFunction() {
    cl = test:mock(http:Client);
    test:prepare(cl).when("get").withArguments("/greeting").thenReturn("Hello World");
    test:assertEquals("Hello World", getGreeting());
    test:prepare(cl).when("get").withArguments("/number").thenReturn(1);
    test:assertEquals(1, getNum());
    test:assertEquals("Hello World1", getBoth());
}
```

**Comment by Dilhasha** [comment]
The design document for this can be found at https://docs.google.com/document/d/1Bf-3Wqndf9QQUimoUWw1sVIWcTIU7r_l8obQFQqjPOw/edit?usp=sharing

**Comment by Dilhasha** [comment]
intial implementation at https://github.com/ballerina-platform/ballerina-lang/commit/bc94fe76b396175a1ffb0e7e9d4e535bff13ff77
