### ISSUE TITLE
[SQLConnector] Oracle Varrays insert fails

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#4007]
Sample code 
```ballerina
import ballerina.data.sql;

function main (string[] args) {
    endpoint<sql:ClientConnector> testDB {
         create sql:ClientConnector(
            sql:ORACLE, "localhost", 0, "xe", "system", "oracle", {maximumPoolSize:5});
    }

    int ret = testDB.update("CREATE TYPE string_varray AS VARRAY(10) OF VARCHAR2(100)", null);
    println("Array type creation status:" + ret);

    ret = testDB.update("CREATE TABLE sample_varray_table (id number(20), arrayData string_varray)", null);
    println("Table creation status:" + ret);

    string[] data = ["hello", "world"];
    sql:Parameter para1 = {sqlType:sql:Type.INTEGER, value:1};
    sql:Parameter para2 = {sqlType:sql:Type.ARRAY, value:data};
    sql:Parameter[] parameters = [para1, para2];

    ret = testDB.update("INSERT INTO sample_varray_table(id,arrayData) VALUES (?,?)", parameters);
    println(ret);

    ret = testDB.update("DROP table sample_varray_table", null);
    println("Table Drop status:" + ret);

    ret = testDB.update("DROP type string_varray", null);
    println("Type Drop status:" + ret);

    testDB.close();
    println("Connector shut downs successfully");
}
```

output
`
Array type creation status:0
Table creation status:0
Listening for transport dt_socket at address: 5005
error: error, message: error in set array value to statement: Unsupported feature
	at ballerina.data.sql:ClientConnector.update(<native>:0)
	at .:main(../samples/testTime.bal:20)

`

**Comment by anupama-pathirage** [comment]
The reason is Oracle JDBC does not support the JDBC 4.0 method createArrayOf method of java.sql.Connection interface. This method only allows anonymous array types, while all Oracle array types are named.
[1] https://docs.oracle.com/cd/B28359_01/java.111/b31224/oraarr.htm#i1056647

**Comment by Manuri** [comment]
Closing since this is not possible to do with the current generic implementation we have. Need to implement this in the future when it comes to a point that we implement database specific clients.
