### ISSUE TITLE
[Improvement]: Add check error code action not suggested 

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#40123]
### Description

Consider the following scenario
![image](https://user-images.githubusercontent.com/35211477/230307837-ce4af3f6-61fd-4ab5-a7cd-a9d4dda2959d.png)

The `io:fileWriteBytes("./audio_clips", audioBytes); ` returns a value of type `io:Error?`. The diagnostic can be resolved adding the  `check`  keyword. Therefore, the `Add check error` code action can be suggested as a quick fix in this case. 

### Related area

-> Editor

**Comment by nipunayf** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/42507
