### ISSUE TITLE
[New Feature]: Introduce a method to easily refer to connectors in central

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#40125]
### Description

When a connector such as `openai.audio` or `trigger.google.drive` is used, the user has to browse ballerina central and add the import statement manually to the ballerina source code in VSCode and pull the particular connector as depicted below.

![pull_module](https://user-images.githubusercontent.com/35211477/230329403-774d0624-16ca-4e18-bcfb-75a6d0e239a2.gif)

### Describe your problem(s)

The user has to have previous knowledge about the existence of the connector and manually add the import statement. This can be considered a UX gap. 

### Describe your solution(s)

In order to reduce/remove this gap one of the following solutions can be implemented.

1. Getting a list of published connectors/packages from the central at the start-up of the LS and loading those into the LSPackageLoader. 
2. Provide a command like `Show Examples` to render a view which shows the categorization of available connectors. Selecting an item on the list of connectors will include an import statement in the source code, pulling the package from the central. 

### Related area

-> Editor

**Comment by IMS94** [comment]
+1. This is a really good idea. We can show only packages from `ballerina` (already packed in distribution) and `ballerinax` orgs coming from central.
