### ISSUE TITLE
[Bug]: Code action gives compile time error in regex

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40129]
### Description

The create variable code action in following code gives a compile time error

```
import ballerina/lang.regexp;

public function main() returns error? {
    regexp:ReplacerFunction;
}
```

When we select the `create variable` code action
It generates

```
import ballerina/lang.regexp;

public function main() returns error? {
    typedesc<function () returns string> typedescResult = regexp:ReplacerFunction;
}

```
and it gives ```ERROR [main.bal:(4:59,4:82)] incompatible types: expected 'typedesc<function () returns (string)>', found 'typedesc<isolated function (ballerina/lang.regexp:0.0.0:Groups) returns (string)>'```

### Related area

-> Compilation

**Comment by malinthar** [comment]
This is no longer reproducible
![create_var](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/fe43266d-43fe-4628-8217-7030b3502aa6)
