### ISSUE TITLE
[Improvement]: Missing completion item for http:Client

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#40120]
### Description

Consider the following scenario
![image](https://user-images.githubusercontent.com/35211477/230295145-c322a79c-c80e-4b6e-be85-bae39ad7defe.png)

As depicted in the image above, the http:Client type is not shown as a completion item. Since it is frequently used, it should be displayed in the list. 

### Related area

-> Editor

**Comment by mindula** [comment]
Looked into this and seems like this issue has been fixed.
<img width="609" alt="Screenshot 2023-04-26 at 19 07 53" src="https://user-images.githubusercontent.com/61020198/234593547-1dc88590-524a-4a3d-b854-d15a3b163215.png">
