### ISSUE TITLE
[Bug]: Invalid Fill required fields code action 

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#40137]
### Description

Consider the following scenario,

https://user-images.githubusercontent.com/61020198/230452380-bbe7c3a0-7dbf-412c-942f-062d6348ff57.mov

The `'type `field is applied again with the code action even though it already exists. 

### Steps to Reproduce

```
type Foo record {|
    int 'type;
    string name;
|};

public function testFun() {
    Foo & readonly val = {'type: 0};
}
```

### Related area

-> Editor

**Comment by malinthar** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/40294

**Comment by pcnfernando** [comment]
Assigned to @dulajdilshan as per https://github.com/ballerina-platform/ballerina-lang/pull/38448#issuecomment-1641808272
