### ISSUE TITLE
[Improvement]: Attempting to rename a variable to `re` gives unnecessary suggestion with quoted identifier

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#40163]
### Description

$title, with the regular expression changes. 

`re` is not a keyword (although the implementation initially considered it to be so).

### Describe your problem(s)

```ballerina
public function main() {
    string:RegExp x = re `[aA]*`;
}
```

![re](https://user-images.githubusercontent.com/8376983/230608716-57f15825-91ab-4be8-809a-83713447ec52.png)

### Related area

-> Editor

**Comment by IMS94** [comment]
LS relies on the `SyntaxInfo.isKeyword()` API exposed by the Syntax API. When looked at it's logic, seems like it's treating `re` as a keyword. @rdulmina @lochana-chathura if it was decided that `re` isn't a keyword, shouldn't we remove that from the keywords? 

PS: In `SyntaxInfo` class, it iterates over the `SyntaxKind` enum values and take every member before the `OPEN_BRACE_TOKEN` as a keyword.

**Comment by MaryamZi** [comment]
Looping in @pcnfernando also.

**Comment by lochana-chathura** [comment]
As per the lexer logic `re` is treated as a keyword only if it is followed by a backtick. Hence, having a variable name as `re` would not make it a keyword. So we can safely exclude it from the `SyntaxInfo.isKeyword()` list.

**Comment by lochana-chathura** [comment]
As per @IMS94 this issue will automatically be resolved by excluding `re` from the  `SyntaxInfo.isKeyword()` list. Hence an LS test is not required.
