### ISSUE TITLE
[Bug]: `RegExp` type is not shown in `string` and `regexp` api docs,

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40161]
### Description

`RegExp` type definition is missing in both [string API doc](https://lib.ballerina.io/ballerina/lang.string/0.0.0) and [regexp API doc](https://lib.ballerina.io/ballerina/lang.regexp/0.0.0)  .

```
string:RegExp _ = re ``;
regexp:RegExp _ = re ``;
```

The issue is related to the `addTypeDefinition` method in here https://github.com/ballerina-platform/ballerina-lang/blob/8a7f24b0c3abc4d1e4f14d9ae05241d0debd32dd/misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java#L168.

### Related area

-> API Docs

**Comment by NipunaMadhushan** [comment]
Closing this since it was fixed with https://github.com/ballerina-platform/ballerina-lang/pull/40162
