### ISSUE TITLE
[Bug]: invokeMethodAsyncSequentially hangs when called from within a service

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-lang#40201]
### Description

When `invokeMethodAsyncSequentially()` is called within a native method which is invoked by a service resource function, the operation does not complete. 

This only happens if the client is initialized outside of the resource function.

### Steps to Reproduce

Example code can be found at: https://github.com/kaneeldias/invoke-test

```ballerina
import ballerina/io;
import ballerina/jballerina.java;
import ballerina/http;

public client class TestClient {

    isolated function callBMethod() returns string = @java:Method {
        'class: "io.ballerina.stdlib.test_project.Utils",
        name: "callBMethod"
    } external;

    isolated function getString() returns string {
        io:println("Inside Ballerina getString method");
        return "Hello";
    }
}

TestClient testClient = new;

service / on new http:Listener(8080) {
    resource function get callBMethod() returns error? {
        io:println("Inside Ballerina service resource method");
        string result = testClient.callBMethod();
        io:println(result);
    }
}
```

**Java native method**
```java
    public static BString callBMethod(Environment env, BObject client) {
        System.out.println("Inside native callBMethod method");

        BFuture future = env.getRuntime().invokeMethodAsyncSequentially(
            client, "getString", null, null, null, null, PredefinedTypes.TYPE_STRING
        );

        return (BString) getFutureResult(future);
    }
```

When the above code is run, and we `GET` `localhost:8080/callBMethod`, the following output is seen and the program hangs.
```sh
Inside Ballerina service resource method
Inside native callBMethod method
```

In the above case, the Ballerina method `TestClient.callBMethod()` and the Java native method `callBMethod()` is invoked, but the Ballerina method `TestClient.getString()` is not invoked.

### Affected Version(s)

Update 5 RC1

### Related area

-> Runtime

**Comment by warunalakshitha** [comment]
It seems async api is called incorrectly. You need to pass a callback to  invokeMethodAsyncSequentially  and during notify success we need to set the future value.
Please refer https://ballerina.io/learn/java-interoperability-guide/ballerina-ffi/#call-methods-asynchronously to how to handle asynchronous call.

**Comment by kaneeldias** [comment]
Closing issue as the issue does not persist when the recommended usage of the API is used
