### ISSUE TITLE
[Task]: RegExp community call preparation (May)

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#40225]
### Description

$subject

https://github.com/wso2-enterprise/marketing-ballerina/issues/137

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
Please find the suggesting agenda for the RegExp community call

```
1. Overview of Ballerina's new regular expression support
2. Demo
3. Future Developments
4. Q&A
```
