### ISSUE TITLE
[Bug]: Using java.util.Random to generate XIDs for distributed transactions is not secure enough

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#40262]
### Description

In https://github.com/ballerina-platform/ballerina-lang/blob/62804bbc471a1e9548b2eefda7cfc7a12cf96f41/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/XIDGenerator.java#L35 using `java.util.Random` does not provide sufficient security for the applications which are needed high assurance. We can use `java.security.SecureRandom` instead. 

### Related area

-> Runtime

**Comment by Nadeeshan96** [comment]
@gabilang Are we considering a security purpose here https://github.com/ballerina-platform/ballerina-lang/blob/62804bbc471a1e9548b2eefda7cfc7a12cf96f41/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/XIDGenerator.java#L35? It seems this is used to generate a random unique ID. So it may not be necessary to change it. Using `SecureRandom` is slower (can say roughly 10x or 20x) than `Random` and use higher memory. Anyway we can do this change to mitigate the warning.

**Comment by gabilang** [comment]
A transaction ID is used to uniquely identify a transaction and is often used for logging, auditing, and tracking purposes. In addition, transaction IDs may be used to ensure that transactions are executed in the correct order or to prevent duplicate transactions from occurring. It's important that transaction IDs are secure to prevent unauthorized access or tampering with sensitive data. An attacker who is able to guess or predict a transaction ID could potentially access or modify sensitive data, impersonate a user, or perform other unauthorized actions. For example, if a transaction ID is simply a sequential number, an attacker could guess the next ID in the sequence and create a fake transaction that would be accepted by the system.

To ensure the security of transaction IDs, they should be generated using a secure random number generator, Java provides `SecureRandom` class for this purpose. This ensures that the IDs are unpredictable and resistant to guessing or prediction attacks.
There is always a trade-off between security and speed in generating transaction ids. It's not desirable to compromise security for higher performance in distributed transaction cases.

**Comment by Nadeeshan96** [comment]
Thanks a lot for the clarification!
