### ISSUE TITLE
[New Feature]: Missing visible symbols in the group by clause

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#40289]
### Description

Missing the visible symbols for `buyer` and `price` in the below code segment.

### Steps to Reproduce

```
function testIterableOperation() {
    var orders = [{buyer: "b1", price: 12}, {buyer: "b2", price: 13}, {buyer: "b3", price: 14}, {buyer: "b3", price: 15}];

    var buyers = from var {buyer, price} in orders
               group by b<cursor>
               
}
```

### Affected Version(s)

Branch `query-grouping-aggregation`

### Related area

-> Compilation

### Related issue(s) (optional)
https://github.com/ballerina-platform/ballerina-lang/issues/40291

_No response_

**Comment by dulajdilshan** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/tree/query-grouping-aggregation
