### ISSUE TITLE
[Improvement]: Improve group by key list end parsing

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#40292]
### Description

```
function testIterableOperation() {
    var orders = [{buyer: "b1", price: 12}, {buyer: "b2", price: 13}, {buyer: "b3", price: 14}, {buyer: "b3", price: 15}];

    var buyers = from var {buyer, price} in orders
               group by buyer, price
               s<cursor>
}
```
The above code segment is parsed incorrectly as below. 

<img width="743" alt="Screenshot 2023-04-24 at 15 23 33" src="https://user-images.githubusercontent.com/27485094/233978259-e6b8db11-9daa-4036-95c2-a9bd814a8f5b.png">

### Related area

-> Compilation

### Related issue(s) (optional)

#4029

**Comment by rdulmina** [comment]
Fixed with  #40297
