### ISSUE TITLE
[Bug]: Quoted identifiers are unquoted in RecordFieldSymbol

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#40294]
### Description

Consider the following source.

```ballerina
type Foo record {|
    int 'type;
    string name;
|};

public function testFun() {
    Foo & readonly val = {'type: 0};
}

```

The type of variable `val` is an intersection type.The effective type of the intersection type is a `RecordType`. When investigated figured that the original name of filed `'type` is missing there. 

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/de360bdf-6bb5-4687-9ec9-440fd01b1e33)

### Affected Version(s)

2201.5.0 (master)

### Related area

-> Editor

**Comment by malinthar** [comment]
When investigated figured out that the name of the field is incorrect in the BField.
![image](https://user-images.githubusercontent.com/35211477/234171630-c7b79bed-e738-4343-bedf-51df966a479d.png)

**Comment by dulajdilshan** [comment]
Some informations can be found related to quoted-identifier implementation in Semantic API

**Comment by LakshanWeerasinghe** [comment]
@malinthar You can find the original name of the field inside the `RecordFieldSymbol`. You can access 
using this way `entry.getValue().getName()`. For completions and code actions we use this `RecordFieldSymbol`.
