### ISSUE TITLE
Can't use `self` of a `readonly` or `isolated` object as a captured variable in an `isolated` function

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#40296]
### Description

The following program gives a compile time error. 

```ballerina
import ballerina/io;

readonly class Test {
    
    string[] words;
    int length;

    isolated function init(string[] & readonly words, int length) {
        self.words = words;
        self.length = length;
    }

    isolated function getCount() returns int {
       // An Error at self.length.
        return self.words.filter(  isolated function (string word) returns boolean  =>  word.length() == self.length ).length();
    }
}

public function main() {
    string[] words = ["hello", "world", "this", "is", "a", "test"];
    Test test = new Test(words.cloneReadOnly(), 4);
    int count = test.getCount();
    io:println(count);
}
```

But it should work. 

Workaround: Assign the affected field locally and pass that to the closure. 

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
I believe this is because `self` isn't considered `final`. The following seems to be allowed atm too, so the error in the isolated function is correct atm (because it's not safe).

```ballerina 
readonly class Class {
    int i;

    function init(int i) {
        self.i = i;
    }

    function updateSelf() {
        self = new (2); // assigns to self
    }
}
```

The spec doesn't seem to mention this, will create an issue.

**Comment by MaryamZi** [comment]
This should get fixed once `self` is marked as implicitly final as finalized in the spec. Changing the type since this isn't quite a bug given `self` isn't final atm.
