### ISSUE TITLE
[New Feature]: Introduce an API to obtain initializer method type from ObjectType

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#40302]
### Description

At present, invoking `getMethods()` function on the `ObjectType` produces an array of methods that does not comprise the `init` method. However, there is a need to obtain access to the `init` method type of the `ObjectType` for constructing the service object.

Consider the following class

```ballerina
readonly service class Sort {
    *graphql:Directive;
    Direction direction;

    function init(Direction direction, int data) {
        // ...
    }

    isolated remote function applyOnField(graphql:Context ctx, graphql:Field 'field) 
    returns anydata|error {
       // ...
    }
}
```

Calling `getMethods()` on the above class returns an array containing `applyOnField` method but not the` init` method.

### Describe your problem(s)

We have a requirement in GraphQL module to construct service objects from a given object `typedesc`. To do that **the knowledge of the `init` method parameter types is necessary to create the relevant object by constructing those values in the native side**. Unfortunately, currently there isn't a straightforward approach to create an object from a typedesc.

### Describe your solution(s)

I can think of two ways:
1. Modify the `getMethods()` function to **include** the type of the `init` method in the returned array.
2. Introduce a new function called `getInitializer()` that solely returns the methodType of the `init` method.

### Related area

-> Compilation

**Comment by ThisaruGuruge** [comment]
@warunalakshitha @HindujaB Can we prioritize this for the next sprint? A GraphQL feature is waiting on this.
