### ISSUE TITLE
[Improvement]: Requesting public API for supporting to check the Regex Pattern validity before code generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-lang#40318]
### Description

We have a requirement to validate the given regex pattern before giving the tooling support to ballerina code generations. Therefore it would be great if we can have a public API from NodeParser including the validity of the pattern and the details of the errors. 

### Related area

-> Compilation

**Comment by sanjana** [comment]
Closing as per https://github.com/ballerina-platform/ballerina-lang/pull/40339#issuecomment-1596483212.
