### ISSUE TITLE
[Bug]: Bad type on operand stack error when readonly table is returned

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#40376]
### Description

```ballerina
type Customer record {|
    readonly int id;
    readonly string name;
    int noOfItems;
|};

isolated table<Customer> key(id) customerTable = table [];

public function main() {
    _ = getApiKeywords();
}

isolated function getApiKeywords() returns readonly & table<Customer> key(id) {
    lock {
        return customerTable.cloneReadOnly();
    }
}
```

Stacktrace:
```
[2023-05-09 22:29:46,516] SEVERE {b7a.log.crash} - Bad type on operand stack
Exception Details:
  Location:
    test.main(Lio/ballerina/runtime/internal/scheduling/Strand;)Ljava/lang/Object; @3404: putfield
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'io/ballerina/runtime/internal/values/TableValueImpl'
```

### Affected Version(s)

v2201.5.0

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
In the `Desugar`, the function body of the `getApiKeywords()` function is generated as follows.

```
Return: <table<(Customer & readonly)> key(id) & readonly> ballerina/lang.value:0.0.0:Cloneable $v$1 = <ballerina/lang.value:0.0.0:Cloneable> customerTable
```

In the `Desugar`, the function body of the `main` function is generated as follows.

```
BLangFunction: [PUBLIC] main ([]) (null) Body: {_ = <any> ; Return: ()}
```

**Comment by SasinduDilshara** [comment]
> In the `Desugar`, the function body of the `getApiKeywords()` function is generated as follows.
> 
> ```
> Return: <table<(Customer & readonly)> key(id) & readonly> ballerina/lang.value:0.0.0:Cloneable $v$1 = <ballerina/lang.value:0.0.0:Cloneable> customerTable
> ```
> 
> In the `Desugar`, the function body of the `main` function is generated as follows.
> 
> ```
> BLangFunction: [PUBLIC] main ([]) (null) Body: {_ = <any> ; Return: ()}
> ```

Seems like the return value of the `getApiKeywords()` function is casted into `<table<(Customer & readonly)> key(id) & readonly>`, which is the expected behaviour.

**Comment by SasinduDilshara** [comment]
Had a discussion with @HindujaB and sees like the issue is having in the runtime side.
Seems like handling intersection type inside the `generateFrameClassFieldUpdateByTypeTag` in `MethodGen` is wrong.
