### ISSUE TITLE
Suggestion : Shall we add restrictions on possible values for parameters?

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/ballerina-lang#4037]
The reason for the above suggestion is the issue raised in https://github.com/ballerinalang/composer/issues/3843 by @yasassri 

> When you add a log the default values are as follows.
> 
> system:log(0, null);
> 
> But according to https://ballerinalang.org/docs/api/0.93/ballerina.lang.system.html Log levels are 1,2,3,4,5

We have no way of determining what values are allowed for function parameters. One way of determining this is via documentation annotation. We currently don't have annotation for this. The problem is that the users will not be aware of this error until runtime. Hence, this might be a useful feature. 

This will also go inline with what is discussed at https://groups.google.com/d/msg/ballerina-dev/2xN29Ci9qI4/4szDe-llAgAJ on defining ranges for integers during declaration as @afkham  has mentioned.

Either approach is fine as long as there is a way of restricting the user and warning of the error before reaching runtime.

**Comment by afkham** [comment]
The new type system addresses this. What is missing is the ability to specify ranges of values as a type. e.g. type minute int(0..59);
