### ISSUE TITLE
[Bug]: Non-isolated function pointers can be called within an isolated function

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#40380]
### Description

```ballerina
public isolated function foo() {
    var f = bar;
    string _ = f(); //should throw a compilation error here
}

function bar() returns string {
    return "bar";
}
```

Ref: https://ballerina.io/spec/lang/master/#isolated_functions

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
https://github.com/ballerina-platform/ballerina-lang/blob/v2201.5.0/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java#L2075

Seems to be a [regression](https://github.com/ballerina-platform/ballerina-lang/pull/36395/files#diff-90dc57beeefe7f36f406f57edecf4a23024fd420b8698934638fb5bf4672322dR2057) from the changes for worker/start action isolated support.
