### ISSUE TITLE
[Task]: Add completion support for collect clause

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#40399]
### Description

Subtask of adding completions for group by clause https://github.com/ballerina-platform/ballerina-lang/issues/40291

### Related area

-> Editor

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/40291

**Comment by TharushiJay** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/40432

**Comment by KavinduZoysa** [comment]
Fixed via #40498
