### ISSUE TITLE
[Improvement]: Improve EnvironmentPackageCache to Cache Only Required Data

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#40398]
### Description

Currently, all the data, including syntax trees and documents, is cached in the project API for later use. However, when dealing with a large dependency tree, this can result in out-of-memory errors (OOM). Initially, these data are cached to be used by LS and other tools. However, it has been observed that LS does not utilize this cache and instead relies on the Compiler API to derive the required information. Even the resolution of 'Go to Definition' is handled differently. After discussions with @azinneera and @IMS94, we concluded that it would be worth exploring the possibility of cleaning up unnecessary data once the BIR  is generated.

Here is a heap dump generated for the following Ballerina program. 

```
import ballerina/io;
import wso2healthcare/healthcare.fhir.r4;
import wso2healthcare/healthcare.hl7v23;
import wso2healthcare/healthcare.hl7v231;
import wso2healthcare/healthcare.hl7v24;
import wso2healthcare/healthcare.hl7v25;
import wso2healthcare/healthcare.hl7v251;
import wso2healthcare/healthcare.hl7v26;
```

<img width="1546" alt="Screenshot 2023-05-10 at 16 34 48" src="https://github.com/ballerina-platform/ballerina-lang/assets/1356214/72ba99b1-ac61-473e-8094-0572b712c010">

### Related area

-> Compilation

**Comment by sameerajayasoma** [comment]
@hasithaa, I had a quick look at this. The compiler API heavily uses the cached SyntaxTree object. We can't simply remove this. It will slow down the compilation and LS operations. So your original claim is wrong :)

**Comment by hasithaa** [comment]
@sameerajayasoma this is only happening at when we compile from Bala. In other cases, we use bir and we don't have syntax trees to cache . My original argument for those depending packages' cached syntax trees. Those are not used by after generating the bir. If it's we can't really compile from the BIRs.

**Comment by nirmal070125** [comment]
One workaround to this problem is increasing the max memory of the JVM. 
Steps:
1. Locate `{bal_home}` - 
```
% where bal                                                            
/Library/Ballerina/bin/bal
```
Hence,
`{bal_home}=/Library/Ballerina/`

2. Find active Ballerina version -

```
% bal --version
Ballerina 2201.4.2 (Swan Lake Update 4)
Language specification 2022R4
Update Tool 1.3.14
```
Hence,
`{version}=2201.4.2`

3. Open the `bal` file to edit - 

`{bal_home}/distributions/ballerina-{version}/bin/bal`

4. Locate `Xmx` value and increase it to 3GB.
```
-Xmx3g
```

**Comment by Thevakumar-Luheerathan** [comment]
As per the discussion, we have decided following things,
1) Syntax Tree caching for the dependency modules is disabled for a package as those syntax trees are not much usable.
2) Introduce a hidden command line flag (something like `--disable-syntax-tree-caching`) for CLI commands to suppress the syntax tree generation for the sources(these sources itself are enough to cause the OOM) as these syntax tree is not much usable during CLI command execution.(whenever we need syntax tree of a source, It will be generated with this flag)
