### ISSUE TITLE
[Improvement]: LS completions for resource-access-action include `$^`, `$^^` path-segments

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#40428]
### Description

Currently, the behavior of providing completions for resource-access-actions is as follows.

![image](https://github.com/ballerina-platform/ballerina-lang/assets/25485997/46731dc8-e151-4d52-be51-55375eaa3538)

The names of the path segments `$^`, and `$^^` are meaningless for the ballerina user. We need to come up with a proper names/values to represent this.

ballerina code
```ballerina
client class BookService {
    resource function get .() {
    }

    resource function get [int bookId]/["authors"]() {
    }

    resource function get [string...]() {   
    }
}

public function main() {
    BookService bookService = new;
    bookService->
}
```

### Describe your problem(s)

At the root, in the compiler, we assign `$^`, and `$^^` if there are no variables associated with the resource functions path segment. This is okay for now. We need to solve this either through the _Semantic API_ level or the _Language-Server_ level.

### Related area

-> Editor

**Comment by malinthar** [comment]
This behaviour is due to the name of the respective paramter symbols being `$^` and `$^^`. 

From the LS side we can address the above as follows.

Case 1
```ballerina
resource function get [int bookId]/["authors"]() {
}
```
The suggested completion item's label should be `/[int bookId]/["authors"]`. 

Case 2
```ballerina
resource function get [string...]() {   
}
```
In this case we have to suggest two completion items. See https://github.com/ballerina-platform/ballerina-lang/issues/39661#issuecomment-1468603644.

Therefore, the suggested completion items' labels should be `/<path>` and `/[string... paths]`.

**Comment by IMS94** [comment]
+1

**Comment by malinthar** [comment]
@dulajdilshan found the following when investigated.
![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/9eb346b8-8989-4fdf-8c2c-84bab6c5cf51)

The Named path segment corresponding to the ` ["authors"]` is does not have the "authors" information in it. Therefore we have to fix that from the semantic API side. 

And the following is modelled incorrectly as well
```ballerina
resource function get [string...]() {   
}
```

The `resourcePath` of the `resourceMethodSymbol` should consist of a path rest param. Instead it has a named segment. 

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/621e7238-6315-4861-9c21-ab24ff78b6f7)

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/7cb62d0a-dde3-4194-92ca-a3bcc6782f3d)

**Comment by dulajdilshan** [comment]
> @dulajdilshan found the following when investigated.

Some of the cases will be addressed via https://github.com/ballerina-platform/ballerina-lang/pull/39477.

>The Named path segment corresponding to the  ["authors"] is does not have the "authors" information in it. Therefore we have to fix that from the semantic API side.

Yeah. We can improve this at the semantic API level by getting the type-info (which is a finite-type) and assign it's type name to the name of the named-path

> The `resourcePath` of the `resourceMethodSymbol` should consist of a path rest param. Instead, it has a named segment.

This needs to be addressed. Btw Path-segment list doesn't need to have all named-path segments, we can have parameters and rest param as well. But this case needs to be addressed since it is wrong to give NamedPAthSegment for RestPathSegment

**Comment by nipunayf** [comment]
The problem cannot be reproduced with version 2201.8.6.

<img src="https://github.com/ballerina-platform/ballerina-lang/assets/59343084/c7f80510-0d36-4949-b355-34eebcf2fc2a" width=500>

However, as mentioned in the above discussions, there are a few improvements made to the completions of the rest param in a resource access, and it is tracked here: https://github.com/ballerina-platform/ballerina-lang/issues/42298.
