### ISSUE TITLE
[Bug]: Compiler error on cyclic type value creation

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#40422]
### Description

When we use a cyclic type inside a union, it is resolving into a `BNoType` type instance. 

### Steps to Reproduce

```ballerina
public type Data int|Data[];
public type Type int | EmptyArray;
public type EmptyArray Data[0];

public function main() {
    Type a = 4; // compiler error
}
```
This gives the following error.
```
incompatible types: expected 'Type', found 'int'
```
Note: If we add `public` to the type it passes.

### Affected Version(s)

current master

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/40083

**Comment by prakanth97** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/39589
