### ISSUE TITLE
[Improvement]: Improve group by key list end parsing

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#40425]
### Description

```
function testIterableOperation() {
   var orders = [{buyer: "b1", product:"beer", price: 12}, {buyer: "b2", product:"coke", price: 13}, {buyer: "b3", product:"sprite", price: 14}, {buyer: "b3", product:"fanta", price: 15}];


    var y = from var {buyer, product, price} in orders 
    group by buyer <cursor>
}
```

The above code segment is parsed incorrectly as below.

<img width="751" alt="Screenshot 2023-05-16 at 16 20 17" src="https://github.com/ballerina-platform/ballerina-lang/assets/27485094/44ba7b7a-66da-4cd4-aab0-21349e5010ed">

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/40292

**Comment by rdulmina** [comment]
Fixed with  #40436
