### ISSUE TITLE
[Bug]: IndexOutOfBoundsException in HoverUtil

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#40438]
### Description

Hovering over `find` in the following scenario throws an IndexOutOfBoundsException,

```
function demo() {
    regexp:find(re `John`, "John");
}
```

<img width="1090" alt="Screenshot 2023-05-17 at 12 55 32" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/571da9df-2fd0-49a4-aae7-e261b890e836">

### Related area

-> Editor

**Comment by malinthar** [comment]
Closing as fixed with https://github.com/ballerina-platform/ballerina-lang/pull/40629
