### ISSUE TITLE
Current implementation does not validate native functions/actions

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#4044]
In current implementation  we only have function and action signatures for native functions and actions. We use them for semantic validations. And only in runtime we bind the actual implementation to those functions and actions. But in current implementation, we don't validate parameters and return types when doing the actual binding. We just match function/action name.
Need to add a validation when doing the binding.

**Comment by hasithaa** [comment]
The Compiler validates native function declaration, that will make sure the program is free from type errors. So we don't need this validation as a part of the compiler/runtime. The Native function developer should have necessary unit test cases to validate each arguments combinations. 

Hence I am closing this issue, Please re-open if you don't agree. :)
