### ISSUE TITLE
[Bug]: Not validating if there are Ballerina packages within the directory when initializing a package

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#40451]
### Description

According to the current implementation, that directory can have other Ballerina packages when initializing a package within an existing directory. After initializing a package in this directory, all those packages can become unusable complaining that they are already within a Ballerina package. 

### Steps to Reproduce

- Create a directory `PackageA` and traverse into that directory.
```
 mkdir PackageA
 cd PackageA
```
- Within that directory, create multiple packages using `bal new PackageB` etc.
```
 bal new PackageB
 bal new PackageC
```
- Now  initialize the package `PackageA`
```
 bal new .
```
- Now try to run the other packages as follows.
```
 bal run PackageB
```

This throws the following error.
`ballerina: Provided path is already within a Ballerina package: MyNewPack1`

### Related area

-> Other Area

**Comment by ShammiL** [comment]
This issue was fixed by validating the given directory to check if there are any Ballerina projects already existing in it and terminating package creation.
