### ISSUE TITLE
[Bug]: Duplicated completion items for fields in mapping  constructor

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#40477]
### Description

Consider the following capture

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/234ab7bc-ce58-4c14-88d5-f408205b8f9e)

### Steps to Reproduce

```ballerina
service / on new http:Listener {
    resource function get 'order/[string orderId]() returns http:Ok|http:NotFound {
        // Write your code here
        if !orders.hasKey(orderId) {
            return <http:NotFound>{};
        }
        return <http:Ok>{};
    }
}

```

### Affected Version(s)

2201.5.0

### Related area

-> Editor

**Comment by malinthar** [comment]
> Since the duplicate fields are coming from each of the return types, I think if we show only the common stuff, the `detail` field of the `CompletionItem` would have to be a union of both types

In the following example, there are two fields with the same name `field1`, `field1` among the fields of the member types of the union type. If we consider `field1`s both are `string` typed. So the completion item is the exact same. However, the detail of the completion item shows the corresponding type definitions  `Type1.field1`  and `Type2.field1` as depicted below

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/79049326-722f-4812-98c0-c8822bbc8ad0)

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/e3e70f80-10fe-4afd-90af-142c8cd11f92)

If we consider `field2`s, the types are different, `string` and `int`. Therefore the insert texts of the two completion items, `field2:""` are `field2:0` different. The corresponding type definitions are shown in the detail of the completion item in this case as well.

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/7f1bcf1d-60da-4226-8788-8a05cf399353)

If we are to suggest a single completion item for the fields with the same name, we will lose the detail (corresponding type definition). Moreover, we have to decide how to handle the fields with the same name but different types. 

@pcnfernando @IMS94 @hasithaa WDYT?

**Comment by pcnfernando** [comment]
> > Since the duplicate fields are coming from each of the return types, I think if we show only the common stuff, the `detail` field of the `CompletionItem` would have to be a union of both types
> 
> In the following example, there are two fields with the same name `field1`, `field1` among the fields of the member types of the union type. If we consider `field1`s both are `string` typed. So the completion item is the exact same. However, the detail of the completion item shows the corresponding type definitions `Type1.field1` and `Type2.field1` as depicted below
> 
> ![image](https://user-images.githubusercontent.com/35211477/245084310-79049326-722f-4812-98c0-c8822bbc8ad0.png)
> 
> ![image](https://user-images.githubusercontent.com/35211477/245084767-e3e70f80-10fe-4afd-90af-142c8cd11f92.png)
> 
> If we consider `field2`s, the types are different, `string` and `int`. Therefore the insert texts of the two completion items, `field2:""` are `field2:0` different. The corresponding type definitions are shown in the detail of the completion item in this case as well.
> 
> ![image](https://user-images.githubusercontent.com/35211477/245088065-7f1bcf1d-60da-4226-8788-8a05cf399353.png)
> 
> If we are to suggest a single completion item for the fields with the same name, we will lose the detail (corresponding type definition). Moreover, we have to decide how to handle the fields with the same name but different types.
> 
> @pcnfernando @IMS94 @hasithaa WDYT?

IMO,
1. If the types are the same, a single suggestion along with the `detail field` of the CompletionItem as a union of both type-defs
2. If the names are the same, but the types are different, the behavior should not change. Both suggestions should be there
