### ISSUE TITLE
[Bug]: Enable formatter tests from query group by and collect

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#40493]
### Description

$sujbect. 
These cases should be enabled
"query_expr_source_120.bal","query_expr_source_121.bal","query_expr_source_122.bal","query_expr_source_123.bal", "query_expr_source_124.bal","query_expr_source_126.bal","keyword_source_01.bal", "keyword_source_02.bal"

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
Done with #40495
