### ISSUE TITLE
[2201.6.0-stage and 2201.6.x] Full build pipeline failure with query expressions

### ISSUE THREAD

**Issue by tharindu-nw** [ballerina-platform/ballerina-lang#40494]
**Description:**
Fails at nballerina level: https://github.com/ballerina-platform/ballerina-release/actions/runs/5060826646/jobs/9089852522

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Simplified version from one failure in nBallerina.

```ballerina
type ModuleDecls [string, FuncDecl...];

type FuncDecl [string, Signature];

public type Signature [string, string[], string];

type ModuleDeclsMemo record {|
    readonly string id;
    map<Signature> funcs = {};
|};

public function main() {
    record {|
        table<ModuleDeclsMemo> key (id) decls = table[];
    |} sc = {};

    ModuleDecls[] decl = from var { id, funcs } in sc.decls
                        select [id, ...from var [name, sig] in funcs.entries()
                                    select <FuncDecl>[name, sig]];
}
```

**Comment by SasinduDilshara** [comment]
This is fixed now with https://github.com/ballerina-platform/ballerina-lang/pull/40497
