### ISSUE TITLE
[Bug]: Invalid parser recovery for invalid function call

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40500]
### Description

```
string a = string `a${"a"}`;

public function main() {
    _ = re `${a}`.find("")();
}
```
This gives

```
ERROR [test.bal:(4:9,4:29)] operator '+' not defined for 'ballerina/lang.regexp:0.0.0:Span?' and '()'
ERROR [test.bal:(4:27,4:27)] missing binary operator
```

### Related area

-> Compilation

**Comment by ushirask** [comment]
@rdulmina since `missing binary operator` looks okay as an error message but since parser recovers it as a missing `+` operator can we introduce a non-specific binary operator into parser error recovery and just give the `missing binary operator` as an error.

**Comment by SasinduDilshara** [comment]
```
public function main() {
    _ = foo()();
}
function foo() returns function () returns int {
    return function () returns int {
        return 42;
    };
}
```

this also get the same error

**Comment by rdulmina** [comment]
> @rdulmina since `missing binary operator` looks okay as an error message but since parser recovers it as a missing `+` operator can we introduce a non-specific binary operator into parser error recovery and just give `missing binary operator` as an error.

i'm afraid that we cannot do that since we need to always generate a syntax tree which is valid accroding to the language spec
