### ISSUE TITLE
[Task]: Missing `Create function code action` in `GroupingKeyVarDeclarationNode`

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#40553]
### Description

<img width="950" alt="Screenshot 2023-05-31 at 10 55 24" src="https://github.com/ballerina-platform/ballerina-lang/assets/27485094/4e8f24c6-10c4-4464-9521-9a5020ebab5a">

### Describe your task(s)

```
   var orders = [{buyer: "b1", price: 12}, {buyer: "b2", price: 13}, {buyer: "b3", price: 14}, {buyer: "b3", price: 15}];

    var buyers = from var {price} in orders 
   group by price, int i = getInt()
   select price;
```

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/40508

**Comment by TharushiJay** [comment]
@dulajdilshan consider the above scenario.

For the following node at cursor position,`semanticModel.typeOf(groupingKeyVarDeclarationNode)` returns empty. What is the correct behaviour?

<img width="683" alt="Screenshot 2023-05-31 at 10 54 53" src="https://github.com/ballerina-platform/ballerina-lang/assets/27485094/480cca80-21a1-4eb7-a27f-3738008d86a8">

**Comment by dulajdilshan** [comment]
> @dulajdilshan consider the above scenario.
> 
> For the following node at cursor position,`semanticModel.typeOf(groupingKeyVarDeclarationNode)` returns empty. What is the correct behaviour?

You trying to get the type of statement, not an expression.

**Comment by TharushiJay** [comment]
As per the offline discussion created https://github.com/ballerina-platform/ballerina-lang/issues/40593 to check the semantic API behaviour of `GroupingKeyVarDeclarationNode`. 

Will be going forward with `groupingKeyVarDeclarationNode.typeDescriptor()` to support the missing code action.
