### ISSUE TITLE
[Bug]: Compilation errors are not shown in the IDE but when we do bal run for specific error intersections

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#40595]
### Description

```bal
type A error<Detail1> & error<Detail2>;
type Detail1 record {
    A? c;
    int a;
};

type Detail2 record {|
    int|string a;
    int b;
    () c;
|};
```

For the above sample there is not error logged in the IDE. But we try to run it, it fails with compilation errors

```
ERROR [:(0:0,0:0)] invalid error detail type '$anonIntersectionRecordType$_0', expected a subtype of 'map<ballerina/lang.value:0.0.0:Cloneable>'
ERROR [:(0:0,0:0)] unknown type '$anonIntersectionRecordType$_0'
```

### Related area

-> Editor

**Comment by malinthar** [comment]
Closing as the issue seems to be fixed in 2201.8.0-SNAPSHOT (master) 

![Screenshot from 2023-07-26 09-29-09](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/d5d0d038-f13d-46cf-aa10-25c3c375522f)
