### ISSUE TITLE
[Bug]: Missing Distinct Qualifier in ObjectTypeSymbol

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-lang#40619]
### Description

The `distinct` qualifier of `Interceptor` type in the following code is missing in the `ObjectTypeSymbol`. Tried to access the qualifiers using `objectTypeSymbol.qualifiers()` API. Since the qualifier is missing, it cannot be validated at the compiler plugin.

```ballerina
public type Interceptor distinct service object {
    isolated remote function execute(Context context, Field 'field) returns anydata|error;
};

readonly service class ServiceInterceptor {
    *graphql:Interceptor;

    isolated remote function execute(graphql:Context context, graphql:Field 'field) returns anydata|error {
        anydata|error result = context.resolve('field);
        return result;
    }
}

service graphql:Service on new graphql:Listener(4000) {
    resource function get foo() returns graphql:Interceptor {
        return new ServiceInterceptor();
    }
}
```
This issue is similar to the https://github.com/ballerina-platform/ballerina-lang/issues/37560 which was fixed earlier. But it seems the fix is a partial fix. It doesn't capture the `distinct` qualifier in types like `Interceptors`. This doesn't work in u4, u5, u6. But this works with u5 latest timestamp.

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
@LakshanWeerasinghe mentioned that the origin is different (SOURCE vs COMPILED_SOURCE) when the flag is available vs not available. So, it's basically that the flag is not available via the BIR.

This already seems to be the case on 2201.5.0. With the new version of GraphQL (v1.8.0) compatible with 2201.5.0, once it is pulled, there is an extra error for https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/compiler-plugin-tests/src/test/resources/ballerina_sources/validator_tests/27_invalid_return_types/service.bal on the second compilation (when it is via the BIR). So this is not something new on 2201.5.x. The reason for this failing on 2201.5.x seems to be due to the source being used for the test instead of the BIR, which seems to be different from what happened previously. That'll have to be looked into separately.

**Comment by MaryamZi** [comment]
> The reason for this failing on 2201.5.x seems to be due to the source being used for the test instead of the BIR, which seems to be different from what happened previously. That'll have to be looked into separately.

This could also be due to the new v1.8.0 release. We need to check if v1.8.0 is pulled for the compiler plugin test.

**Comment by MaryamZi** [comment]
> 2\. `isolated` qualifier is not read from the BIR.

Can you please share an example for this? Just wondering for what scenarios this is the case because `isolated`-ness is widely used with client objects in libraries and we have tests in org.ballerinalang.test.bala.isolation.IsolationAnalysisBalaTest too.

**Comment by LakshanWeerasinghe** [comment]
```ballerina
public type Interceptor distinct isolated client object {
    isolated remote function execute() returns anydata|error;
};
```
I used the above code snippet to try that out. When I unmask the
<img width="346" alt="Screenshot 2023-06-27 at 14 16 02" src="https://github.com/ballerina-platform/ballerina-lang/assets/46857198/b9075076-a093-4920-978b-3c98e23a569c">
 flags I got the below results.

**Comment by MaryamZi** [comment]
The following worked for me via the BIR too.

```ballerina
import maryam/foo;

isolated client readonly class InterceptorImpl {
    *foo:Interceptor;

    isolated remote function execute() returns anydata|error => 1;
}

final foo:Interceptor fi = new InterceptorImpl();

public isolated function main() returns error? {
    _ = check fi->execute(); // if `foo:Interceptor` is not `isolated` this should result in an error
}
```

It could be being set elsewhere.

**Comment by LakshanWeerasinghe** [comment]
> ```ballerina
> public type Interceptor distinct isolated client object {
>     isolated remote function execute() returns anydata|error;
> };
> ```
> 
> I used the above code snippet to try that out. When I unmask the <img alt="Screenshot 2023-06-27 at 14 16 02" width="346" src="https://user-images.githubusercontent.com/46857198/249091894-b9075076-a093-4920-978b-3c98e23a569c.png"> flags I got the below results.

This behavior has occurred due to caching issue when running the tests. Hence ignore this comment.

**Comment by LakshanWeerasinghe** [comment]
> When fixing this issues following this have been identified.
> 
> 1. When the object network qualifier is a `client` it will identified as a `service` qualifier.
> 2. `isolated` qualifier is not read from the BIR.
> 3. When we use the flags value read from the inputstream in the BIR to set the tSymbol flag it will give a compiler crash.
> 
> I will be looking in to the above cases as well.

1 & 2. This happened due to a cache issue. 
All the type level flags are propagated properly. When we create the BSymbol we propagate the flags one by one. Because of this reason we have missed the qualifiers like `distinct`, `isolated` at the BSymbol.
