### ISSUE TITLE
[Language Basics]Video creation

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#40638]
List types
- [x] Arrays
- [x] Tuples

**Comment by SasinduDilshara** [comment]
Array -  https://drive.google.com/file/d/1P-NBGlAf9fZdRBMTmlrgN6Ba43ELqArp/view?usp=share_link
Tuple - https://drive.google.com/file/d/19-CZlNqD2Eb4XPXGaDDU6uSH6-fTQZAv/view?usp=share_link

Will proceed stream, table and Query Videos after considering the feedbacks from the team

**Comment by SasinduDilshara** [comment]
Final Array and Tuple Videos


https://drive.google.com/file/d/1ocPfbGu8RvBiDNnpeVtXWG7RGQcsupAY/view?usp=share_link
https://drive.google.com/file/d/1CPV8VpfUjNXXvqunhNQfzZ2PGVm1hSx1/view?usp=share_link

**Comment by SasinduDilshara** [comment]
Table video - https://drive.google.com/file/d/1J-FFfPym8kM6ZebTLr5vdxQO9GIIDFkt/view?usp=share_link

**Comment by SasinduDilshara** [comment]
Stream Video - https://drive.google.com/file/d/1bTaj0c4Og4bTijqjhvMVeGykp6t8IZXL/view?usp=share_link

**Comment by SasinduDilshara** [comment]
Array Part 1 - https://drive.google.com/file/d/1YGg-9ikL43xcK_qcZqbAkG3MS_Zt_yH9/view?usp=share_link
Array Part 2 - https://drive.google.com/file/d/1lTgpUWSPPXwz6-5ec_oXzIylVki9gI_V/view?usp=share_link

**Comment by SasinduDilshara** [comment]
Please find descriptions, video names, video drive links and timelines for each video in following document
https://docs.google.com/document/d/1umxTeIO11AX3YumcDxP6oAppU43qRjmT9JNAO2rt1jE/edit?usp=sharing

**Comment by SasinduDilshara** [comment]
This task is done and uploaded to the youtube
