### ISSUE TITLE
[Improvement]: Improve SyntaxTree memory usage

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#40648]
### Description

$subject.

### Describe your problem(s)

We have noticed high memory usages related to the SyntaxTree when large projects are compiled. Following is a sample memory dump. 

<img width="1546" alt="memory_dump" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/f608434d-2036-465c-9cfb-0226ebb47858">

**Comment by lochana-chathura** [comment]
As per our last discussion, we identified the following places for improvement.
1. Avoid the `EnumSet` usage in the `STNode` 
https://github.com/ballerina-platform/ballerina-lang/blob/36941999f208dcf6545f40e4bd672c47c3d5d83c/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STNode.java#L45

2. Revisit the caching `LineRange`, `TextRange`, etc in the `Node`
https://github.com/ballerina-platform/ballerina-lang/blob/4b05b24a01a9d688bd64f36237d35e525f30b01c/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/syntax/tree/Node.java#L134-L145

Though we use lazy loading in the ST, at the `BLangNodeBuilder` we visit the full tree creating the complete facade and also calculating positions for each node. Therefore, the complied ST will always have almost all the textRange, lineRange information cached. Making the syntax tree heavier. 

However, on the other hand, by avoid caching such calculated text and line range information, it may lead to a performance impact as we have to do the full tree traversal up to a given node in order to calculate its position.

3. Verify if the `String` usage in `LineRange` is the same instance across all the nodes for the given bal file.
https://github.com/ballerina-platform/ballerina-lang/blob/7861756bf0e304693c66e97c943a8802e82a68a9/compiler/ballerina-tools-api/src/main/java/io/ballerina/tools/text/LineRange.java#L28

**Comment by lochana-chathura** [comment]
Create #40653 to address 1.

**Comment by lochana-chathura** [comment]
>  3. Verify if the `String` usage in `LineRange` is the same instance across all the nodes for the given bal file.

Verified. They all have the same instance.

<img width="1120" alt="Screenshot 2023-06-12 at 12 33 56" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/c2208454-2f0e-4aae-b838-bd8e38a611a4">

**Comment by hasithaa** [comment]
@lochana-chathura 
Shall we use the `short` type instead of the `int` in the line positions classes and check the memory usage?

**Comment by lochana-chathura** [comment]
Well for the generated edifact project(total 170 modules),
without fix 1, we go OOM at the 160th module when creating the internal tree.
with fix 1, we go OOM at the 73rd module when creating the external tree.

However, in the latter case when we go OOM the LinePosition memory usage is negligible(~ 2000 objects).

<img width="1705" alt="Screenshot 2023-06-13 at 10 53 49" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/2dc574f5-30b0-4c80-ab15-70447706c966">

**Comment by lochana-chathura** [comment]
- Could save ~30MB removing these `int`s which are only used for the incremental parser which we do not use ATM.
https://github.com/ballerina-platform/ballerina-lang/blob/d85f96e4ece574ffef50d41fae4d052e2776b46d/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/tree/STToken.java#L40-L43

- Could save another ~70MB making the token width-related variables `short`s.
https://github.com/ballerina-platform/ballerina-lang/blob/0abb3341691f0060f96fa91438f6d698c0000a9a/misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/tree/STNode.java#L40-L43

**Comment by lochana-chathura** [comment]
Closing the issue as we did some improvement with fix 1, and we decided it was enough for the moment.
