### ISSUE TITLE
[Bug]: The code completion for annotation field is not working for some fields

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#40668]
### Description

When we have a union-typed field for an annotation (union of `int` and `record`) and when we try to give it as a record value, the code completions are not working properly.

> **Note:** This tooling support is required for this new feature in the constraint package - https://github.com/ballerina-platform/module-ballerina-constraint/pull/79

### Steps to Reproduce

Check the following code in vscode:
```bal
annotation StringConstraints String on type, record field;

type ConstraintRecord record {|
    anydata value;
    string message;
|};

type StringConstraints record {|
    int|record{| *ConstraintRecord; int value; |} length?;
|};

@String {
    length : {} // enter the curly braces and try to type the field name it does not complete with the proper fields
}
type TestString string;
```

### Affected Version(s)

Ballerina SwanLake 2201.6.0

### OS, DB, other environment details and versions

Mac OS with Apple M1 chip

### Related area

-> Editor

**Comment by malinthar** [comment]
When investigated, I figured out that the ExpectedTypeAPI returns an invalid expected type at the cursor position depicted above. The syntax tree node at the cursor is a SpecificFieldNode.  

The expected type API uses the NodeFinder class to find the BLangNode node in a given range. In the above case the range given (specic field node in the annotation attachment) is not within the range of any of the topLevel nodes. Therefore, the node finder return null when the lookup() method in the NodeFinder is called. https://github.com/ballerina-platform/ballerina-lang/blob/0abb3341691f0060f96fa91438f6d698c0000a9a/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/NodeFinder.java#L227

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/f5889ba8-c546-4b24-85ea-bef76df74f84)

**Comment by hasithaa** [comment]
We can't do the 2, it is a backward incompatible change. +1 for 1st one.

**Comment by mindula** [comment]
Blocked by https://github.com/ballerina-platform/ballerina-lang/issues/41186
