### ISSUE TITLE
[Improvement]:  Mocking private final object for unit testing inside a class

### ISSUE THREAD

**Issue by sanduninduwara** [ballerina-platform/ballerina-lang#40666]
### Description

I am writing unit tests for the functions inside the class. However, the initiation of this class involves creating a private final object from the DAO layer.
the current workaround suggested is to write the private final object initialization logic in a separate function.
But It will lead to a change in the implementation of the class initialization.

### Describe your solution(s)

Implement a way to mock the final object and its methods without writing the final object initialization logic in a separate function.

### Related area

-> Compilation

**Comment by Dilhasha** [comment]
This will be addressed as part of https://github.com/ballerina-platform/ballerina-lang/issues/42193
