### ISSUE TITLE
[Task]: Test Group by feature for Ballerina U7

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40743]
### Description

Test Group by for Ballerina U7

### Related area

-> Compilation

**Comment by SasinduDilshara** [comment]
Please find the following document with bugs and improvements

https://docs.google.com/document/d/1qxLs_abL1ngjsXlXOmShNGPJjonqZEj82aapOI6UKzE/edit?usp=sharing

**Comment by pcnfernando** [comment]
Please find the issues identified in
https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aopen+is%3Aissue+author%3Apcnfernando+%5BGroupBy%5D
