### ISSUE TITLE
[New Feature]: Ability for Compiler plugins to execute tests

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#40749]
### Description

This is needed for `bal test --cloud` feature.  
https://github.com/ballerina-platform/module-ballerina-c2c/issues/695
https://docs.google.com/document/d/17M1MVultHfQnDRqE7GBk4u-4bFtb5_QSRnwqIgKnB2M/edit?usp=sharing

### Describe your problem(s)

We need a way to execute tests in a given container(by c2c)

### Describe your solution(s)

We may need a new phase Listener(Similar to CompilerLifecycleListener) for this. Then the compiler extensions could write logic to execute the tests. 

In the case of cloud, we need to give the test execution responsibility to cloud extension (similar to graalvm build when --cloud flag is there)

### Related area

-> Test Framework

### Related issue(s) (optional)

https://github.com/ballerina-platform/module-ballerina-c2c/issues/695

**Comment by Ramith-D-Rodrigo** [comment]
This can be achieved by executing a docker command using the ProcessBuilder after building the docker image for the tests.

**Comment by Dilhasha** [comment]
> This can be achieved by executing a docker command using the ProcessBuilder after building the docker image for the tests.

Ramith was able to achieve this by introducing an executable emition phase for tests which allows using the same `CompilerLifecycleListener`.

Hence, closing this issue. The use case is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/41036
