### ISSUE TITLE
[Bug]: Invalid undefined function error in main method

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#40782]
### Description

```
public function main() {
    int test = 7;
    var b = test();
}

function test() returns [int] {
    return [];
}
```

Gives `undefined function 'test'` error.
But the function `test` is defined in module level scope.
So, the error message should be change to something like `cannot invoke a integer`

### Related area

-> Compilation

**Comment by prakanth97** [comment]
```
int test = 7; // redeclared symbol 'test'

public function main() {
    var b = test(); // undefined function 'test'
}

function test() returns [int] {
    return [];
}
```
Don't we have to log the same error like this?
