### ISSUE TITLE
[Bug]: Incorrect error msg for map constants

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-lang#40792]
### Description

- ```const person = {name : "Joe", name : "Jack"};```
Currently it gives `invalid usage of finite literal: duplicate key 'name'`, spec did not mention about `finite`. It can be corrected to `invalid usage of record literal: duplicate key 'name'`.

- ```const int|float|string mUnion3 = {a: 1, b: 2};```
It gives `incompatible types: expected ' {a: 1,b: 2}', found '(int|float|string)'` which is wrong.

### Affected Version(s)

2201.7.0-stage

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
>  spec did not mention about `finite`. It can be corrected to `invalid usage of record literal: duplicate key 'name'`.

At the same time in the current spec a [literal](https://ballerina.io/spec/lang/master/#section_6.5) is interpreted as,
```
literal :=
   nil-literal
   | boolean-literal
   | numeric-literal
   | string-literal
   | byte-array-literal
numeric-literal := int-literal | floating-point-literal
```

Wondering "record literal" is the correct term now.

**Comment by prakanth97** [comment]
> > spec did not mention about `finite`. It can be corrected to `invalid usage of record literal: duplicate key 'name'`.
> 
> At the same time in the current spec a [literal](https://ballerina.io/spec/lang/master/#section_6.5) is interpreted as,
> 
> ```
> literal :=
>    nil-literal
>    | boolean-literal
>    | numeric-literal
>    | string-literal
>    | byte-array-literal
> numeric-literal := int-literal | floating-point-literal
> ```
> 
> Wondering "record literal" is the correct term now.

At moment we log `invalid usage of record literal: duplicate key 'name'` for the below example,

```
public function main() {
    var person = {name : "Joe", name : "Jack"};
}
```
It seems spec didn't mentioned such a `record-literal`

**Comment by lochana-chathura** [comment]
In the AST naming also we call `BLangRecordLiteral` which is an obsolete term.

I would like to make the error message shorter too. (Improves coders' error message reading time while convincing the meaning)

How about `Invalid record: duplicate key 'name' found`?

**Comment by prakanth97** [comment]
> In the AST naming also we call `BLangRecordLiteral` which is an obsolete term.
> 
> I would like to make the error message shorter too. (Improves coders' error message reading time while convincing the meaning)
> 
> How about `Invalid record: duplicate key 'name' found`?

Agree

**Comment by lochana-chathura** [comment]
> How about `Invalid record: duplicate key 'name' found`?

Correction: `invalid {0} constructor: duplicate key ''{1}'' found`
-  `0` argument could either be `record` or `mapping` (as it is now already)

The current spec use "mapping constructor" term. However, since we already provide custom error for record vs mapping in this scenario, we can say  "record constructor" and "mapping constructor" which is more meaningful for the user?
