### ISSUE TITLE
Initialization loop detection in global variable and constant initialization

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#4079]

**Comment by SupunS** [comment]
Also, we need to detect self-references (#4066) and circular dependencies in import statements. Currently, the compilation fails with  ` ballerina: internal error occurred `.

**Comment by hasithaa** [comment]
@rdhananjaya Can you check this. I think we have fixed this issue.

**Comment by rdhananjaya** [comment]
Yes this is solved for global variables
```ballerina
int i = j;
int j = k;
int k = i;

public function main(string... args) {
    
}
``` 
will result in a `illegal cyclic reference '[i, j, k]'`

As we don't have const assignment yet, this is not yet applicable.

**Comment by rdhananjaya** [comment]
Closing as this was solved with https://github.com/ballerina-platform/ballerina-lang/pull/13094
