### ISSUE TITLE
Taint tracking of network delivered data

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerina-platform/ballerina-lang#4081]

**Comment by ayomawdb** [comment]
This is resolved. 

We have added taint checking support for SQL client connector, file API, IO API, HTTP and other network related connectors. Security sensitive areas of same APIs and additionally security sensitive areas of stdlib has been marked with @ sensitive annotation to make sure un-trusted data is not   accepted in such areas without proper validation / sensitization.

Relevant PRs are as follows: 
#4928  #5029 #5227 #5243 #5246 #5712 #5727 #5757 #5846 #5874 #6080 #6178 #6483 #6613 #6617 #6682 #6741 #6794 #6913 #7013 #7148 #7253

Ballerina by example is available at: 
https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/taint-checking

@uthaiyashankar @sameera-jayasoma: Kindly mark this issue resolved.

**Comment by afkham** [comment]
Implemented
