### ISSUE TITLE
[Bug]: Incorrect behaviour in `Strand.createTrxContextBranch()` when `strandName` is null

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-lang#40825]
### Description

In the [`Strand.createTrxContextBranch()`](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Strand.java#L146) method, if a null value is passed to the `strandName` parameter, the block ID of newly created transaction context is appended with `_null` (e.g. `4_null`).

This is then added to the registry with the `_null` suffixed transaction block ID. An example of a situation where it occurs can be found in the SQL module [here](https://github.com/ballerina-platform/module-ballerina-sql/blob/master/native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java#L194). This can be an issue when we want to maintain the current transaction context when using `runtime.invokeMethodAsyncSequentially()` and the name of the current strand is `null`. 

Finally, when we do `check commit` the [`TransactionManager.notifyCommit()`](https://github.com/ballerina-platform/ballerina-lang/blob/master/bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/transactions/TransactionResourceManager.java#L287) method is called which retrieves the relevant transaction contexts using the transaction block ID. But in this case, the `_null` suffix is not present, so the method doesn't capture the relevant context accurately. Hence, the transaction is not committed.

Suggestion is to perform a null check on the `strandName` parameter in `Strand.createTrxContextBranch()` and only create a new transaction block id if the value is not null.

**Current method**
```java
private TransactionLocalContext createTrxContextBranch(TransactionLocalContext currentTrxContext,
                                                       String strandName) {
    TransactionLocalContext trxCtx = TransactionLocalContext
            .createTransactionParticipantLocalCtx(currentTrxContext.getGlobalTransactionId(),
                    currentTrxContext.getURL(), currentTrxContext.getProtocol(),
                    currentTrxContext.getInfoRecord());
    String currentTrxBlockId = currentTrxContext.getCurrentTransactionBlockId();
    trxCtx.addCurrentTransactionBlockId(currentTrxBlockId + "_" + strandName);
    trxCtx.setTransactionContextStore(currentTrxContext.getTransactionContextStore());
    return trxCtx;
}
```

**Suggested change**
```java
private TransactionLocalContext createTrxContextBranch(TransactionLocalContext currentTrxContext,
                                                       String strandName) {
    TransactionLocalContext trxCtx = TransactionLocalContext
            .createTransactionParticipantLocalCtx(currentTrxContext.getGlobalTransactionId(),
                    currentTrxContext.getURL(), currentTrxContext.getProtocol(),
                    currentTrxContext.getInfoRecord());
    String currentTrxBlockId = currentTrxContext.getCurrentTransactionBlockId();
	if (strandName != null) {
		    trxCtx.addCurrentTransactionBlockId(currentTrxBlockId + "_" + strandName);
	}
    trxCtx.setTransactionContextStore(currentTrxContext.getTransactionContextStore());
    return trxCtx;
}
```

### Related area

-> Runtime

**Comment by kaneeldias** [comment]
Re-opening issue as the behaviour is still not as expected.

**Comment by pcnfernando** [comment]
The flow is as follows
1. Within a transaction block, call a remote isolated object method
https://github.com/kaneeldias/module-ballerinax-persist.sql/blob/native-query/ballerina/tests/mysql-native-tests.bal#L257

2. This method makes a Java native call
https://github.com/kaneeldias/module-ballerinax-persist.sql/blob/native-query/ballerina/tests/mysql_rainier_generated_client.bal#L351

3. From Java native side, we call a Ballerina method using invokeMethodAsyncSequentially()
https://github.com/kaneeldias/module-ballerinax-persist.sql/blob/native-query/native/src/main/java/io/ballerina/stdlib/persist/sql/datastore/SQLProcessor.java#L223

4. This method again makes a Java native call
https://github.com/ballerina-platform/module-ballerinax-mysql/blob/master/ballerina/client.bal#L79

5. The Java native call completes and the result is returned up the flow

6. We commit the transaction in the original transaction block.

With these back-and-forth native calls, multiple strands get created and it's wrong to create transactional branches for all of these newly created branches. Looking into to alternatives atm.

Previous fix is anyway valid.

**Comment by dsplayerX** [comment]
This issue may have arisen because transactions were registered in `resourceRegistry` with their `strandID`s, leading to a mismatch when committing the original transaction with the main strand. This mismatch prevented the transaction's completion. To address the strand mismatch, we avoided adding `strandID` to `resourceRegistry`, as outlined in this pull request: https://github.com/ballerina-platform/ballerina-lang/pull/41800.
