### ISSUE TITLE
Ballerina Package versioning

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#4087]

**Comment by hasithaa** [comment]
Right now module import declarations with versions is not supported.

**Comment by hasithaa** [comment]
For the initial implementation, The Plan is to cover the following scope. 

- Ability to define the module import version in ballerina source. 
  - Support Single Source and Modules
  - Support only the SemVar. (No Ranges)
- It Doesn't support multiple version import in the same module.
   - The compiler will complain if multiple version is detected.
- Compiler resolve modules using the user given order. 
   - Order:
     - Lock file version.
     - Toml version 
     - Source file version.
     - If no version is specified, Use the latest version from Central.

@sameerajayasoma @sanjiva @hevayo Thoughts?

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19540
