### ISSUE TITLE
Wrong error when mismatching types exist for multi return functions

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4093]
Consider the following code snippet,

`string token, _ = (string)formParams["token"];`

This gives the following compilation error,

`error: org.abc.serviceImpl[]/TokenServiceImpl.bal:12:17: mismatched input ','. expecting ';'`

**Comment by uthaiyashankar** [comment]
Multi return, casting etc. is no longer valid. Hence, resolving.
