### ISSUE TITLE
[New Feature]: Add support for custom repositories for library packages

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#41016]
### Description

The current package resolution design only supports a predefined set of repositories (distribution, Ballerina Central and local). Supporting custom package repositories like Github packages, Nexus and Artifactory will be useful.

**Comment by Thevakumar-Luheerathan** [comment]
Design document : https://docs.google.com/document/d/19BFmvRelmVZ1FuocaF3O6WLJbwXru6L2VNpOw0A22YM/edit?usp=sharing

**Comment by Thevakumar-Luheerathan** [comment]
PR https://github.com/ballerina-platform/ballerina-lang/pull/41177 adds following support

1. Support for Github maven registry, Nexus maven repository, Artifactory maven repository 
2. Support for push and pull
3. Package resolution similar to local repository
