### ISSUE TITLE
Constraint JSON to Same Struct type coversions shouldn't be unsafe

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#4102]
Converting constraint JSON to same Struct (which is same Struct type to create constraint json) shows as a unsafe conversion. Since its same Struct it should be safe.

```
struct Person {
    string pName;
    string gender;
}

function sampleFunction() {
    json<Person> personJson = {};
    Person person = {};
   
    //Unsafe conversions
    personJson = <json<Person>> person;
    person = <Person> personJson;
}
```

**Comment by hasithaa** [comment]
As per 0.985.0 Spec. There are no conversion operations defined. The only way to achieve this to use seal/convert.

```ballerina
function sampleFunction() {
    json<Person> personJson = {};
    Person person = {};

    personJson = person.seal( json<Person>);
    person = personJson.seal(Person);
}
```

@mohanvive  Pls note.

**Comment by warunalakshitha** [comment]
@hasithaa @mohanvive  Json to same struct type conversions/stamp is not assignable hence it should be unsafe ( which is correct behavior with 9.9.0 impl).  If not we need to make them assignable as well.

**Comment by mohanvive** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/12713 .. But, it is not unsafe since respective types are not assignable.
