### ISSUE TITLE
[Improvement]: Introduce a way to run tests in a docker container

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#41036]
### Description

We have `bal build --cloud` but not  `bal test --cloud` but to verify the package functionality in a cloud platform, we must run the tests also in a container. This applies to GraalVM verification as well. `bal test --graalvm --cloud` should run the tests in a container.

For this, there should be a standalone testable jar that can be run inside a container. We can check the possibility of generating a single testable jar or separate jars for each module.

**Comment by Dilhasha** [comment]
Following are the sub tasks for $subject.

- [ ] Create an uber jar for test modules
- [ ] Create test executable task and emit executable
- [ ] Verify code-coverage, mocking with the new test executable
- [ ] Lifecycle plugin implementation at C2C for running tests in docker container

**Comment by Dilhasha** [comment]
@Ramith-D-Rodrigo 

Let's create a spreadsheet with all the cases we need to address

**Comment by Ramith-D-Rodrigo** [comment]
--graalvm --cloud=docker is supported now. Implemented using the testable fat jar while also considering the mocking features.

Added the relevant tests for the changes. --cloud flag changes are added in c2c repository. The tests added in this repo check the changes in BTestMain and the execution of testable fat jar.
