### ISSUE TITLE
[Improvement]: Achieve predictable builds

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#41037]
### Description

Spec issue: https://github.com/ballerina-platform/ballerina-spec/issues/1247

### Related area

-> Compilation

**Comment by ShammiL** [comment]
The design for this was finalized in discussions with @sameerajayasoma and @azinneera.
Design document - https://docs.google.com/document/d/1nab6j6i5ywm9cYfvrsYxmErokXhuHI6CWlPYGoJPQTg/edit#heading=h.rtjhmirpqawr

**Comment by azinneera** [comment]
Closing since this is deprioritized. The discussion can be followed up in the related spec issue.
