### ISSUE TITLE
No method to set form params

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#4106]
Currently there is an option to getFormParams, but no option to setFormParams.

**Comment by chamil321** [comment]
User can set payload along with "application/x-www-form-urlencoded" header to send formParams.

```ballerina
http:Request req = new;
req.setTextPayload("a=b&c=d", mime:APPLICATION_FORM_URLENCODED);
var response = clientEP1 -> post("/", req);
```
