### ISSUE TITLE
[Bug]: BIR doesn't show any error if a class have methods with same signature. 

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#41106]
### Description

$title

But in `SymbolEnter` it shows redeclared symbol error for multiple attached-funcs with same signatures

```ballerina
public readonly class BarClass {
    public isolated function patch(int[] artifacts, boolean publish) returns byte[] {
        return [1, 0, 1];
    }

    public isolated function patch(int[] artifacts, boolean publish) returns byte[] {
        return [1, 0, 1];
    }
}
```

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
The BIR symbol enter isn't expected to log errors like this. We also don't run compiler phases again when symbols are loaded from the BIR, they are expected (should be guaranteed) to be correct.

I believe we can close this and keep https://github.com/ballerina-platform/ballerina-lang/issues/41105. Fixing that will remove the requirement to log an error here also?

**Comment by dulajdilshan** [comment]
> The BIR symbol enter isn't expected to log errors like this. We also don't run compiler phases again when symbols are loaded from the BIR, they are expected (should be guaranteed) to be correct.
> 
> I believe we can close this and keep #41105. Fixing that will remove the requirement to log an error here also?
