### ISSUE TITLE
[Bug]: Language Server unresponsive after including a cyclic dependency

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#41111]
### Description

$subject as depicted below

![cyclic_dependency](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/f31a0522-bf45-4392-b6d7-48aace8792fe)

### Related area

-> Compilation

**Comment by azinneera** [comment]
When there is a cyclic dependency, the compilation cannot be continued, so it is a crashed state. Hence this behavior is expected. The diagnostic is issued to indicate the cyclic dependency which can be used to resolve the error.

**Comment by malinthar** [comment]
> When there is a cyclic dependency, the compilation cannot be continued, so it is a crashed state. Hence this behavior is expected. The diagnostic is issued to indicate the cyclic dependency which can be used to resolve the error.

I see. However, the VSCode user might not know about the crashed state unless they look at the problems tab. The LS may seem unresponsive because features such as completion, code-action will not work without the compilation. To avoid the confusion we can send a notification from the LS side when the compilation is in a crashed state specifying a user error.
