### ISSUE TITLE
[Bug]: Invalid `isolated` qualifier attached to symbol

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#41133]
### Description

Consider the following source
```Ballerina
int[] arr = [1, 2, 3];

string a = "";

function testFunction(int... arg) {

}

public function main() {
    int[] arr2 = [];
}
```

When I tried to get the `qualifers()` from the variable symbol corresponding to `arr`, it returns  an invalid `ISOLATED` qualifier as depicted below. 

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/b3b04e00-6c14-433c-bb3c-78a8cc3f1841)

Due to this we are not getting any completions for `arr` variable in the following context

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/060dedb7-6b6c-48a1-898b-98583e991a54)

### Steps to Reproduce
Mentioned above

### Affected Version(s)
2201.8.0 (master)

_No response_

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
This could be because `arr` is inferred to be `isolated`. 

If, for example, `arr` was accessed outside a `lock` statement, the `isolated` flag shouldn't be added.

```ballerina
function testFunction(int... arg) {
    _ = arr; // outside lock
}
```

**Comment by malinthar** [comment]
> This could be because `arr` is inferred to be `isolated`.
> 
> If, for example, `arr` was accessed outside a `lock` statement, the `isolated` flag shouldn't be added.
> 
> ```ballerina
> function testFunction(int... arg) {
>     _ = arr; // outside lock
> }
> ```

Ack! Consider the following case where I observed an inconsistent behaviour.



```Ballerina
int[] arr = [1, 2, 3];

string a = "";

function testFunction(int... arg) {

}

public function main() {
    int[] arr2 = [a<cursor>];
}
```
![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/2fc986c8-0ac0-45fc-a663-7db7806e73a8)


`arr` symbol is suggested as depicted. When analyzed found that the `arr` symbol does not contain the `isolated` qualifer.

![image](https://github.com/ballerina-platform/ballerina-lang/assets/35211477/36f6a58a-43d4-4e25-baea-2e34ec9d7971)

The reason for this is that the IsolationAnalyzer is run after the typeCheck(pkgNode) phase. So when there is an error in the source code the IsolationAnalyzer does not run. That's the reason for inconsistency.

**Comment by malinthar** [comment]
Closing this issue as it occurs die to the design of the compiler phases.
