### ISSUE TITLE
[Bug]: Invalid symbol position given for intersection error types

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#41183]
### Description

For the below scenario, we get `VIRTUAL` as the `symbol.origin` for `MyDefaultError`. Hence, `MyDefaultError` is not included in the list of visible symbols

<img width="594" alt="Screenshot 2023-08-09 at 15 26 50" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/f674c3c2-2046-442f-81a6-69bd16a415e3">

<img width="524" alt="Screenshot 2023-08-09 at 15 28 19" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/44f26e04-d6ef-4790-9aa8-275f1aa14378">

### Steps to Reproduce

```
type DefaultError distinct error;

public type MyErrorDetail record {
    string fileName;
};

type MyDefaultError DefaultError & error<MyErrorDetail>;

public function main() {
    My<cursor>
}
```

### Related area

-> Compilation

**Comment by mindula** [comment]
Related issue: #34509

**Comment by nipunayf** [comment]
The issue cannot seem to be reproduced with 2201.8.3.

<img width="576" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/59343084/21687f66-77ad-40d4-b27e-977ff895c555">
