### ISSUE TITLE
[Packerina] Error message for errors in building a .balx is too generic

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4121]
For the following build command with an erroneous path, the given error message is too generic and is not helpful in identifying what caused the error.
Command with the erroneous path and the resulting error message:
```
$ ballerina build passthroughservice/ -o passthroughService.balx
ballerina: error writing program file 'passthroughService.balx'
```
The command with the correct path:
```
$ ballerina build passthroughservice/samples/ -o passthroughService.balx
```

**Comment by afkham** [comment]
This has been fixed
