### ISSUE TITLE
[Task]: Fix Improper Resource Shutdown or Release in Ballerina 1.2.x

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#41261]
### Description

Need to fix the $subject vulnerability reported in https://docs.google.com/spreadsheets/d/1MAabEyyYwg8PzziDR4XbPJyeCUhKEgFrDrMDYFX9RVM/edit#gid=407096550

### Related area

-> Runtime

**Comment by gabilang** [comment]
The above issue can be mitigated by try-with-resources (or manually call close) if there any constructor call made to `JSONGenerator` or it can be a false positive. Hence closing the issue.
