### ISSUE TITLE
[Bug]: File too large error when building ballerina project

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#41279]
### Description

$title

Related issue: https://github.com/wso2-enterprise/internal-support-ballerina/issues/427

### Affected Version(s)

2201.5.1
2201.7.1

### Related area

-> Compilation

**Comment by warunalakshitha** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/41215

**Comment by malinthaprasan** [comment]
Hope we are working on this issue. This is an important fix we need to in-cooperate OpenAPI generator to when we try to generate ballerina services from large OpenAPI files.
