### ISSUE TITLE
[Bug]: Nballerina repo build fail with compiler errors update 8 distribution

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#41283]
### Description

Try to build the [nballerina](https://github.com/ballerina-platform/nballerina) repo with latest sl update 8 daily build packs from https://github.com/ballerina-platform/ballerina-distribution/actions/runs/5958619240

Build fails with following errors.
<img width="1438" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/4163165/ce9cdd51-c3af-4394-a3de-dac89233d40d">

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
PRs

https://github.com/ballerina-platform/ballerina-lang/pull/41286
https://github.com/ballerina-platform/nballerina/pull/1230

**Comment by warunalakshitha** [comment]
Closing since PR is merged.
