### ISSUE TITLE
[Improvement]: Improve Ballerina Profiler UI

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#41315]
### Description

$title

We can do the following improvements.
1. Currently when we open the profiler output, it does not fit to the window size.
<img width="1440" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/33286289/4a828384-0c15-467a-899b-9cffa3348c1c">
We need to fit the whole output to the window to see the overview without scrolling.

2. We can rename the tab to `Ballerina flamegraph` or just `flamegraph`.
<img width="284" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/33286289/e3ecf361-35f9-4a40-9e82-793199063567">

3. The clear button is for clearing search. Need to rename to `clear search` or move it next to `search`.
<img width="501" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/33286289/bcda09c4-3563-4440-aeca-a2113b1e8d8c">

### Related area

-> Other area

**Comment by Nadeeshan96** [comment]
3. Ballerina Profiler words are not aligned.
<img width="246" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/33286289/ea090c40-5bfc-4083-a0cf-36c49238fc48">

**Comment by gabilang** [comment]
Closing this issue since the proposed improvements have been added with the PRs https://github.com/ballerina-platform/ballerina-lang/pull/41538 and https://github.com/ballerina-platform/ballerina-lang/pull/41823
