### ISSUE TITLE
[Query] Encrypt content of a file

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#4132]
There is a need to encrypt and store a file received through a HTTP request. Is there a way in Ballerina to achieve file encryption in Ballerina?

**Comment by anupama-pathirage** [comment]
Ballerina crypto package provides the necessary utilities that are required to hash content using different hashing mechanisms and algorithms. Refer https://ballerina.io/learn/api-docs/ballerina/crypto.html for more details.
