### ISSUE TITLE
Need a mechanism to encrypt and decrypt values

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#4135]
Need a mechanism to encrypt and decrypt values. Following are few scenarios that we need the support.
**Scenario 1:** Encrypting the key store and trust store passwords

@http:configuration {
    keyStorePassword:"test",
    trustStorePassword:"test"
}

**Scenario 2:** Encrypting values like the access token, refresh token, client id and secret which will be stored in a separate file and read through the config API.

**Comment by anupama-pathirage** [comment]
Releated https://github.com/ballerinalang/ballerina/issues/4132
