### ISSUE TITLE
Integrate code generation bal tools to package build

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#41415]
Currently, Ballerina tools (like bal openapi, bal grpc, bal graphql, bal asyncapi, bal persist, and bal bindgen) are used to generate code, which developers often include in the package source code. This manual inclusion poses challenges:

Generated code is not available for CI tools
Cloning the source repo requires manual generation of the code
Resolution:

Enhance package build configuration to auto-generate code from a single source of truth.
Preserve the manual code generation option for specific use cases.

Design document: https://docs.google.com/document/d/1XsZK3UlqXv4TLEgRKVc0UBRRilLTmLZ1heDTmIRuylE/edit?usp=sharing

**Comment by azinneera** [comment]
Currently, Ballerina tools (like bal openapi, bal grpc, bal graphql, bal asyncapi, bal persist, and bal bindgen) are used to generate code, which developers often include in the package source code. This manual inclusion poses challenges:

- Generated code is not available for CI tools
- Cloning the source repo requires manual generation of the code

**Resolution:**

Enhance package build configuration to auto-generate code from a single source of truth.
Preserve the manual code generation option for specific use cases.

Design document: https://docs.google.com/document/d/1XsZK3UlqXv4TLEgRKVc0UBRRilLTmLZ1heDTmIRuylE/edit?usp=sharing

**Comment by ShammiL** [comment]
The following improvements were done in PR #41542
* Add a getter to access the `packageInstance` from `ToolContext`.
* Change options schema file name from `<tool-type>-<tool-id>-options-schema.json` to `<tool-type>-options-schema.json`.
* When `additionalProperties` field in the options schema file is set to `false`, give error diagnostic and exit for additional optional fields given in `Ballerina,.toml`.

**Comment by ShammiL** [comment]
The following improvements and fixes were done with PRs #41553, #41574 and #41616:

- Remove generated directory in `bal clean` and add relevant tests. (#41389)
- Handle Ballerina toml tool property validations.
- Handle Ballerina toml diagnostics related to build tools at pre build tool task level before compilation.
- Improve diagnostics related to build tools.
- Handle bad sad errors thrown for invalid values or values not provided for build tool toml properties.
- Add Ballerina toml tests for build tool perperties.

**Comment by ShammiL** [comment]
After the improvements following is the behaviour of the build tools:
1. Validation of tool configuration in `Ballerina.toml` is handled as follows:
- `toolId`, `filepath` are required fields, cannot be empty and must be a string value.
- If `targetModule` is not provided or an empty string, the default module is taken as the target module, if a value is provided it must be a string value. 
- Optional tool configurations are validated using the schema provided by the tool developer.
- No two tool configurations can have the same `toolId` or the `targetModule`.

2. All tool related manifest diagnostics are printed before the execution of tools.

4. Below information on the configurations are available through the `ToolContext` during the tool execution:
- Tool id
- Filepath
- Target module
- Optional configurations as a Map<String, Object>
- Cache path
- Output path
- Current package instance

5. Diagnostics found during the tool execution can be reported using the `ToolContext.reportDiagnostic()` method.
6. Following scenarios cause compilation failure:
- Validation failures in Ballerina.toml tool configurations
- Tool not found for execution
- Errors reported during tool execution
