### ISSUE TITLE
Still, version has been identified as a keyword in VSCode version 4.5.1

### ISSUE THREAD

**Issue by Thiyanwso2** [ballerina-platform/ballerina-lang#41411]
### Description

$subject
![Screenshot from 2023-09-19 11-57-14](https://github.com/ballerina-platform/ballerina-lang/assets/65483741/39c1460d-1104-4647-8194-e8b98606c8db)

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
@Thiyanwso2 this issue needs to be created in the [ballerina-grammar](https://github.com/ballerina-platform/ballerina-grammar) repo. Please move this issue to there.
