### ISSUE TITLE
Cannot declare multiple variables in a single declare statement 

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4144]
I tried to declare following,
```
int a,b;
```
Which resulted following error.
```
error: org.abc.util[]/AccountOperationsUtil.bal:30:10: mismatched input ','. expecting ';'
the compilation contains errors
```
Is there any specific reason to limit this? If not can we add the support?

**Comment by hasithaa** [comment]
This is intentional. This syntax doesn't scale/read well when you have initializers for variables.
