### ISSUE TITLE
[Query] How to write content to a PDF file

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#4145]
Here is my code. This successfully generates the pdf file. But, when the file is opened it shows as error message as "File type unknown (application/text) is not supported". What is the correct encoding format I should use here?

```
function getFileChannel (string filePath, string permission)
(io:ByteChannel) {
    file:File src = {path:filePath};
    io:ByteChannel channel = src.openChannel(permission);
    return channel;
}


public function writeToPDF (int[] accNo) {
    string text = "my name is xx";
    blob content = text.toBlob("UTF-8");
    io:ByteChannel destinationChannel = getFileChannel("./sampleResponse.pdf");
    var var1 = destinationChannel.writeBytes(content, 0);
}
```

**Comment by uthaiyashankar** [comment]
pdf is a binary file.. not a text format. Just chagning the encoding is not going to work. 

PDF file format is : https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf
