### ISSUE TITLE
[Bug]: invalid gradle config in toml parser gson project version 

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#41451]
### Description

It was added as   implementation 'com.google.code.gson:gson:"${project.gsonVersion}"'  but it should be   implementation "com.google.code.gson:gson:${project.gsonVersion}"

### Related area

-> Runtime

**Comment by salamafazlul** [comment]
When attempting a Maven build on Windows, the process fails with the following error

Could not resolve dependencies for project org.example:untitled:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.ballerinalang:ballerina-cli:jar:2201.5.0 -> ... -> com.google.code.gson:gson:jar:"${project.gsonVersion}": Failed to read artifact descriptor for com.google.code.gson:gson:jar:"${project.gsonVersion}": Could not transfer artifact com.google.code.gson:gson:pom:"${project.gsonVersion}" from/to github-pvt (https://maven.pkg.github.com/ballerina-platform/*)

Importantly, this project builds fine using Gradle.

**Comment by gabilang** [comment]
Closing this issue since the Fix is merged to `2201.8.x` branch.
