### ISSUE TITLE
[Bug]: Code coverage reports fail to generate if path is given as the first argument

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#41488]
### Description

We can run `test` command by passing a path as `bal test <PATH>`. However if we try to generate code coverage reports using `bal test <PATH> --test-report --code-coverage` this would just run the tests without generating code coverage report. Also note if we run `bal test  --test-report --code-coverage <PATH>` (path as the last argument) it will generate the code coverage report.

### Steps to Reproduce

1. Create a ballerina project at say `~/foo` directory and add a dummy test file in to the `test` sub directory
2. Run `bal test ~/foo --test-report --code-coverage`

### Affected Version(s)

2201.8.1

### OS, DB, other environment details and versions

Linux

### Related area

-> Test Framework

**Comment by azinneera** [comment]
`bal test <PATH> --test-report` should print an error since Picocli does not allow params (--test-report) after the argument (<PATH>).

**Comment by Dilhasha** [comment]
This is mentioned in the test command synopsis.
```
$bal test -h

SYNOPSIS
       bal test [OPTIONS] [<package>|<source-file>] [(-Ckey=value)...]
```
