### ISSUE TITLE
[Improvement]: Provide a code action to break lines in a Ballerina string template

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#41499]
### Description

String templates are designed to allow the user to input text as it is. Thus, unlike quoted strings, the code editor allows the user to write a string template for multiple lines. However, in some cases, the user may want to break the string template into multiple lines to restrict the character limit per line rather than having a new line in the string. It is better if the LS can provide a code action for this scenario.

### Describe your solution(s)

LS needs to provide a code action when the `cursor-point` is within the context of a string template as shown in the below code.

```ballerina
import ballerina/io;

public function main() {
    var name = "Name";
    io:println(
        string `Hello, ${name}! <cursor-point>Some text`);
}
```

After the execution of the code action, it can format the code above as shown below.

```ballerina
import ballerina/io;

public function main() {
    var name = "Name";
    io:println(
        string `Hello, ${name}! ` +
        string `Some text`);
}
```

### Related area

-> Other Area

**Comment by nadeeshaan** [comment]
Code actions are meant to be used for the refactorings which can alter the semantics as well as non-trivial syntax. In this scenario, we should first see whether we need to allow the user to make this decision. Refactorings such as these (especially syntax refactorings) should adhere to the coding best practices and formatting practices. This is a scenario which we can categorise as a formatting best practice. Hence, IMHO, we should not expose this as a part of the code action implementation. We should expose this via our formatter.

**Comment by nipunayf** [comment]
> Code actions are meant to be used for the refactorings which can alter the semantics as well as non-trivial syntax. In this scenario, we should first see whether we need to allow the user to make this decision. Refactorings such as these (especially syntax refactorings) should adhere to the coding best practices and formatting practices. This is a scenario which we can categorise as a formatting best practice. Hence, IMHO, we should not expose this as a part of the code action implementation, since it is not intuitive for the user, from where we are going to add the break of lines. yes, they can try and check, but code actions should be intuitive in the first look. If we really need to do this, we should expose this via our formatting implementation, based on the length of the template expression or based on other heuristics.

I agree with this comment as well since the initial requirement came as a formatting feature. However, the idea of a code action arose with the concern of how the user can select the precise point to break for better readability. After an offline discussion, we have decided to leave this as a formatting feature and let the user manually change it if required for readability. Hence, closing the issue and delegating it to the formatter: https://github.com/ballerina-platform/ballerina-lang/issues/41513.
