### ISSUE TITLE
Add remove() method to XML

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#4149]
There is no way to remove an element/child from an XML

**Comment by SupunS** [comment]
`removeAttribute(string qname)` is available for removing attributes. 

Needs a way to remove a certain element from an XML seq, and returns a new seq.

**Comment by hasithaa** [comment]
removeChildren lang lib method is available.
https://github.com/ballerina-platform/ballerina-lang/blob/master/langlib/lang.xml/src/main/ballerina/src/lang.xml/xml.bal#L149
