### ISSUE TITLE
[Bug]: Querying a table after modifying values gives the previous values.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#41503]
### Description

**Sample code to reproduce the issue.**

```ballerina
import ballerina/io;

type Employee record {|
    readonly string orgId;
    readonly string appId;
    string company;
|};

table<Employee> key(orgId, appId) empTable = table [
    {orgId: "1", appId: "1", company: "xxx"}
];

public function main() {
    io:println("Table - before update:");
    io:println(empTable);

    empTable.put({
        orgId: "1",
        appId: "1",
        company: "yyy"
    });

    io:println("Table-After update:");
    io:println(empTable);

    table<Employee> results = from Employee r in empTable
        where r.orgId == "1" && r.appId == "1" 
        select r;

    io:println("Result from Query:");
    io:println(results);

}
```

**Current output:**

```
Table - before update:
[{"orgId":"1","appId":"1","company":"xxx"}]
Table-After update:
[{"orgId":"1","appId":"1","company":"yyy"}]
Result from Query:
[{"orgId":"1","appId":"1","company":"xxx"}]
```

After updating a record in the `empTable`, it is reflected in the table.
But when querying the data from that table the `results` variable still contains the old value for the attribute `company`.
Correct value should be `[{"orgId":"1","appId":"1","company":"yyy"}]`

### Affected Version(s)

**Version:**
bal -v
Ballerina 2201.8.0 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.0

**Comment by sameerajayasoma** [comment]
It looks like, this happens only when there are composite keys in a table.  I tested the above sample with a single key and I've got the expected output.
