### ISSUE TITLE
[Bug]: Confusing error messages when I use redeclared variable name for a `configurable` variable

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#41533]
### Description

I accidentally used an already declared variable name for a configurable variable. I couldn't understand the error messages initially. It took me a few minutes to figure out what was going on in VSCode.

### Steps to Reproduce

I defined the following variable without knowing that the same variable is defined somewhere else. 
```
configurable string host = ?;
``

I noticed red squiggly lines in VSCode and tried `bal build.` Here is the output:
```
ERROR [service.bal:(7:14,7:20)] invalid type for configurable variable: expected a subtype of 'anydata'
ERROR [service.bal:(7:21,7:25)] redeclared symbol 'host'
```


### Affected Version(s)

Ballerina Swan Lake Update 8.1

### OS, DB, other environment details and versions

_No response_

### Related area

-> Compilation

### Related issue(s) (optional)

_No response_

### Suggested label(s) (optional)

_No response_

### Suggested assignee(s) (optional)

_No response_

**Comment by HindujaB** [comment]
reproducible with the following
```ballerina
Host host = new();
configurable string host = ?;

class Host {
}
```
