### ISSUE TITLE
[Bug]: Ballerina profiler fails to profile when there are mandatory configurable variable

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#41547]
### Description

I tried profiling the following service and got the following error in the console. 
https://github.com/sameerajayasoma/ballerina-samples/tree/main/publish-hotel-reservations-to-kafka

```
error: value not provided for required configurable variable 'kafkaUrl'
        at sameera/publish_hotel_reservations_to_kafka:0.1.0(main.bal:6)
error: value not provided for required configurable variable 'kafkaTopic'
        at sameera/publish_hotel_reservations_to_kafka:0.1.0(main.bal:7)
```

### Related area

-> Compilation

**Comment by HindujaB** [comment]
This happens due to the current directory is set to `/target/bin` when running the profiler. Therefore, it doesn't read from the package directory as default.  
As a workaround, we can use the `BAL_CONFIG_FILES` env variable with the `Config.toml` path.

I'll send a fix for this.
