### ISSUE TITLE
[Improvement]: Improving Ballerina Resource Function Developer Experience in VS Code Extension

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-lang#41563]
### Description

With the majority of Ballerina connectors using Ballerina resource functions, developer experience with resource functions plays a critical role in Ballerina.

The Ballerina VS Code extension provides support for handling resource functions effectively. However, we have identified the following issues and potential improvements:

### 1. Auto-completion even after path parameters

![Auto-Completion Issue](https://github.com/RDPerera/img-repo/blob/main/Screen%20Recording%202023-10-23%20at%2021.44.06.gif?raw=true)

Currently, after entering a parameter, the auto-completion feature does not work as expected. It would be better to provide suggestions for resource paths after specifying a parameter.

### 2. Add descriptions when hovering over resource paths

![Description Issue](https://github.com/RDPerera/img-repo/blob/main/Screen%20Recording%202023-10-23%20at%2021.46.28.gif?raw=true)

VS Code currently provides descriptions only when hovering over parameters. We propose adding descriptions for resource paths when hovering over them.

### 3. Replace `<path>` with parameter names and types
![<path> Issue](https://github.com/RDPerera/img-repo/blob/main/Screen%20Recording%202023-10-23%20at%2021.42.28.gif?raw=true)

Parameter names for resource functions are displayed as "path" instead of their actual names and types.

### 4. List down all the paths to keyword.method()    [eg: Calls.post]
![Image](https://github.com/ballerina-platform/ballerina-lang/assets/39415471/e0b28cae-3649-4351-a329-722df849fc2f)

If we just type `calls.post`, it should list down all the paths to `calls.post()`.

## Steps to Reproduce

To reproduce the issue, follow these steps:

1. Download the OpenAPI specification from [Link to OpenAPI Spec](https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_api_v2010.yaml).
2. Generate and build resource functions using the Ballerina OpenAPI Tool by referring to the [Ballerina OpenAPI Tools Documentation](https://ballerina.io/learn/openapi-tool/).
3. Write the following example code:

```ballerina
import ballerinax/twilio;

public function createCall() returns error? {
    twilioresource:CreateCallRequest call = {
        To: toPhoneNumber,
        From: fromPhoneNumber,
        Url: recordingURL
    };
    twilioresource:ApiV2010AccountCall? response = check twilioClientResource->/Accounts/[accountSid]/Calls.post(call);
    if (response is twilioresource:ApiV2010AccountCall) {
        log:printInfo("Call made successfully.");
        log:printInfo(response.toString());
    } else {
        log:printError(response.toString());
    }
}
```

## Additional Information

- Ballerina Version: Ballerina 2201.8.0 (Swan Lake Update 8)
- Operating System: macOS
- VS Code Extension Version: v4.5.3

### Related area

-> Editor

### Suggested assignee(s) (optional)

@KavinduZoysa

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/ballerina-platform/ballerina-lang/issues/41563#issue-1958585099)

**Comment by shafreenAnfar** [comment]
Also, if we just type `call.post`, it should just list down all the paths to `call.post`

**Comment by RDPerera** [comment]
> Also, if we just type `call.post`, it should just list down all the paths to `call.post`

Added to the issue.

**Comment by KavinduZoysa** [comment]
Since #41636 is under discussion, and other issues are fixed, we can close this major issue.
