### ISSUE TITLE
[Bug]: Profiler console output contains invalid characters

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#41577]
### Description

$subject

### Steps to Reproduce

Create a bal package and run `bal profile`.

![Screenshot (2)](https://github.com/ballerina-platform/ballerina-lang/assets/28644893/22be39e3-b34e-4186-9a60-0a31fdbb6a60)

Note the `?` character in the console output.

### Affected Version(s)

2201.8.2

### OS, DB, other environment details and versions

Windows 10

### Related area

-> Runtime

**Comment by gabilang** [comment]
It's due to the code-page used in windows CMD is 437 by default. This code-page prevents to show the Unicode characters properly. If we change the code-page to 65001, it will show the Unicode characters properly. 

We can change the code-page of the windows CMD by using the command `chcp 65001`.

**Comment by gabilang** [comment]
In order to keep a consistent terminal/cmd output pattern across platforms, we can use a character which is supported in the code-page 437 for bulleting or we can remove the bullets. 
As per an offline discussion, we decided to not to use bullets instead use right indentation. 
The output log is going to look as follows, 
```
================================================================================
Ballerina Profiler: Profiling...
================================================================================
Note: This is an experimental feature, which supports only a limited set of functionality.
[1/6] Initializing...
[2/6] Copying executable...
[3/6] Performing analysis...
[4/6] Instrumenting functions...
      Instrumented module count: 44
      Instrumented function count: 3981
[5/6] Running executable...
```
