### ISSUE TITLE
[Bug]: No code action to add the `http:ClientError` type for the return type

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#41584]
### Description

```
import ballerina/random;
import ballerina/http;

service /employee on new http:Listener(9091) {
    resource function get id() returns random:Error? {
        int intInRange = check random:createIntInRange(1000, 99999);
        http:Client a = check new(); // No code action to add the http:ClientError type for the return type
    }
}
```

In the above code sample, No code action found to add the http:ClientError type for the return type

### Related area

-> Compilation

**Comment by nipunayf** [comment]
Code actions are generated based on the diagnostics the LS server received. In the above scenario, it only generates the diagnostic `missing required parameter 'url' in call to 'new()' (BCE2063)`, and thus it does not provide the code action to change the return type.

**Comment by nipunayf** [comment]
Closing this issue as the code action to return `http:ClientError` works as expected in 2201.8.1 once the correct diagnostic is provided (i.e., once the required parameter is provided to the initializer).
