### ISSUE TITLE
[Improvement]: Use the relative path of the package in `bal new` command output

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#41603]
### Description

Improve the `bal new` command output. 

### Describe your problem(s)

Here is the current bal new command output:
```
sameera@sameera eggplant % bal new content-based-message-routing
package name is derived as 'content_based_message_routing'. Edit the Ballerina.toml to change it.

Created new package 'content_based_message_routing' at /Users/sameera/work/<bla/bla/bla>/eggplant/content-based-message-routing.
```

I think there is no need to show the absolute path when the package is created inside the current directory. 

Also, you need to upper case the `package` here. 

### Describe your solution(s)

Can we improve the output as follows when the package is created within the current directory?
 ```
sameera@sameera eggplant % bal new content-based-message-routing
Package name is derived as 'content_based_message_routing'. Edit the Ballerina.toml to change it.

Created new package 'content_based_message_routing' at content-based-message-routing.
```

### Related area

-> Compilation

**Comment by roysti10** [comment]
Hi can I pick this up

**Comment by azinneera** [comment]
> Hi can I pick this up

Sure, I assigned you.

**Comment by roysti10** [comment]
@azinneera when i do `bal new`, i get the message 
```shell
➜ bal new test
Created new package 'test' at test.
```

I cannot reproduce the above issue

**Comment by azinneera** [comment]
> @azinneera when i do `bal new`, i get the message
> 
> ```shell
> ➜ bal new test
> Created new package 'test' at test.
> ```
> 
> I cannot reproduce the above issue

Hi @roysti10 

I checked with Update 8 on Ubuntu, MacOS and Windows. The issue is reproducible in all 3. Can I know the ballerina version you are using?

**Comment by roysti10** [comment]
@azinneera 
On linux
```bash
> bal new test
Created new package 'test' at /mnt/c/Users/tauro/Documents/test.
> bal version
Ballerina 2201.8.2 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.2
```

on windows
```pwsh
➜ bal new test
Created new package 'test' at C:\Users\tauro\test.
   19:28:47  ~  ﮫ 1.427s 
➜ bal version
Ballerina 2201.8.2 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.2
```

I can now reproduce the path problem but the message mentioned above is not reproducible

**Comment by roysti10** [comment]
@azinneera have raised a PR for this
