### ISSUE TITLE
[Bug]: Defaultable Parameters in Functions Cannot Reference 'self.' Variables

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-lang#41609]
### Description

I've encountered an issue while trying to use defaultable parameters in a remote isolated function in Ballerina. Here's a sample of the code that demonstrates the problem:

```
public isolated client class Client {
    final string foo;
    public isolated function init() returns error? {
        self.foo = "hello";
    }
    remote isolated function hello(string text = self.foo) returns string {
        return text;
    }
}
```

The issue arises when attempting to use the `self.foo` defaultable parameter in the remote isolated function. The Ballerina compiler reports the error: `undefined symbol 'self'`.

### Steps to Reproduce

1. Create a Ballerina class similar to the one mentioned above.
2. Attempt to use defaultable parameterstring `text = self.foo`

### Affected Version(s)

Ballerina 2201.8.0 (Swan Lake Update 8)

### OS, DB, other environment details and versions

Ballerina 2201.8.0 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.1
Mac OS

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
This is not a bug.

At the moment, `self` is accessible/in-scope only within the method.

There's an open spec issue to consider supporting this in the future - https://github.com/ballerina-platform/ballerina-spec/issues/95, https://github.com/ballerina-platform/ballerina-spec/issues/1055.

As an alternative for this specific case, I would have the parameter be of type `string?` and use `()` as the default and handle using `self` within the method.

```ballerina
remote isolated function hello(string? text = ()) returns string {
    return text ?: self.foo;
}
```
