### ISSUE TITLE
Single variable simple expressions are not valid

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#4161]
Following program does not work. It says below. But Ideally it should work.

ballerina: invalid template expression: {a}

import ballerina.net.http;

@http:configuration {basePath:"/hello"}
service<http> helloWorld {

    @http:resourceConfig {
        methods:["GET"],
        path:"/{a}"
    }
    resource sayHello (http:Request request, http:Response response, string a) {
        response.setStringPayload(a);
        response.send();
    }
}

**Comment by afkham** [comment]
Issue is still reproducible @shafreenAnfar

**Comment by arukshani** [comment]
Fixed with #9136
