### ISSUE TITLE
Enum reference name improvement suggestion

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-platform/ballerina-lang#4162]
In 0.95.2 following syntax is there
```
sql:Parameter para1 = {sqlType:sql:Type.INTEGER, value:1, direction:sql:Direction.IN};
```
Since there is a bit of a repetition feeling here which can be confusing to the user.(sqlType:sql:Type) can we change it? Ideally it should be something as below, but we might need to evaluate the possibility with the language restraints and give the best possible way ( as a user I would not care if the syntax is a truct or a enum) to the user that is non confusing. 

```
sql:Parameter para1 = (sql:Type.INTEGER, 1, sql:Direction.IN);
```

**Comment by hasithaa** [comment]
Consider Java static import mechanism.

**Comment by uthaiyashankar** [comment]
This is covered with new design. current style is sql:TYPE_INTEGER
