### ISSUE TITLE
[Bug]: Incomplete error message on `xml:fromString` method

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#41668]
### Description

```
import ballerina/io;
public function main() {
    string a = string `
        <?xml version='1.0' encoding='UTF-8'?>
            <soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
            xmlns:tns="http://www.example.com/">;
                <soap:Body>
            <tns:receive.cdiResponse>
            <Response>
            <Code>1000</Code>
            <Description><![CDATA[OK]]></Description>
            </Response>
            </tns:receive.cdiResponse>
                </soap:Body>
            </soap:Envelope>
        `;
    
    xml|error fromString = xml:fromString(a);
    io:println(fromString);
}
```

in here the program outputs,
```
error("failed to parse xml: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
 at [row,col {unknown-source}]: [2,13]")
```

This error message is not clear for the user. It is better to have a meaningful error message.

Affected version - 2201.8.0

### Related area

-> Compilation

**Comment by Nadeeshan96** [comment]
Here the error message is clear and correct. According to https://github.com/ballerina-platform/ballerina-spec/issues/1225#issuecomment-1465468709, we do not allow "xml" as a processing instruction target when parsing xml strings. Hence we cannot include the xml declaration also. If we change the processing instruction target to another value, say `abc`, it works without any problem.

**Comment by warunalakshitha** [comment]
As per above comment I am closing the issue. Please reopen if you have further queries on this.
