### ISSUE TITLE
Test Failure in NotSoBasicWorkerTest

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#4169]
Getting an intermittent test failure on current master.
```ballerina
testForkJoinWorkersWithNonBlockingConnector(org.ballerinalang.test.worker.NotSoBasicWorkerTest)  Time elapsed: 6.158 sec  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [10]
    at org.ballerinalang.test.worker.NotSoBasicWorkerTest.    (NotSoBasicWorkerTest.java:165
```
we need to change the test case, as test can return 10 on slow network connections.
https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-test/src/test/resources/test-src/workers/fork-join-blocking.bal#L13

**Comment by uthaiyashankar** [comment]
This should have been fixed. Will review and resolve.

**Comment by afkham** [comment]
Fixed
