### ISSUE TITLE
[Bug]:An error occurred when creating the test report on Windows.

### ISSUE THREAD

**Issue by MinuliKannangara** [ballerina-platform/ballerina-lang#41779]
### Description

Gives NoSuchFileException exception when generating the test report. 
<img width="754" alt="Screenshot 2023-11-28 160448" src="https://github.com/ballerina-platform/ballerina-lang/assets/73284411/8c23c3af-c51b-4982-ad61-85e71ce8d82e">

### Affected Version(s)

Ballerina 2201.8.2 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS- Windows 11

### Related area

-> Test Framework

**Comment by gayaldassanayake** [comment]
I was able to reproduce the issue on Windows. The problem seems to be arriving due to not being able to extract the zip containing the test report template. This template is located within the ballerina home. I will update on the findings here.
