### ISSUE TITLE
[Bug]: An error is not thrown for an invalid annotation in tuple type descriptors

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#41787]
### Description

The compiler does not throw an error when we use an undefined annotation along with a type descriptor in tuple type descriptors.

### Steps to Reproduce

Run the following Ballerina code. 

```ballerina
[@UndefinedAnnotation int, int] [first, second] = [1, 2];
```

### Affected Version(s)

Ballerina 2201.8.0 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS: macOS 14.1.1 23B81
JDK: openjdk 17.0.8 2023-07-18

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
We need to add test when annotations are present in tuple variable fields.
Example:

```ballerina
type AnnotRecord record {|
    string value;
|};

annotation AnnotRecord annot on field;
public function main() {
    [@annot{value: ""} int, int] [first, second] = [1, 2];
}
```
