### ISSUE TITLE
[WebSocket] Need service pointers support for client connector 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#4180]
At the moment we do it by specifying the service name as a string. But ideally we should specify it using service pointers. This is a concept similar to function pointers yet to be implemented.

**Comment by riyafa** [comment]
Service pointers support is currently available. What we need is service instantiation support which is currently being implemented.

**Comment by riyafa** [comment]
Now service instantiation support is available in Ballerina as of 0.990 version.
