### ISSUE TITLE
[Bug]: bal test command returning exit-code 0 on failure

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#41815]
### Description

The `bal test` command exits with an exit code of 0 when encountering a module-level error.

### Steps to Reproduce

For instance, if there is a global variable in the test code, like the example below:

```ballerina
final Client gmailClient = check new (gmailConfig);
```

If an error occurs during the execution of this code, the `bal test` command exits with code 0.  It's expected to return exit code 1.

### Affected Version(s)

Tested on: 2201.8.4

### Related area

-> Test Framework

**Comment by ShammiL** [comment]
This issue arises when the program encounters an error at runtime in the generated module `$_init` class before running the tests. The `getTestExecutionState()` method in `TesterinaUtils.java` returns '0' exit code in this scenario. 

In the above given scenario,
```ballerina
final Client gmailClient = check new (gmailConfig);
```
fails when the gmail `Client` class constructor is called with wrong configurations before running tests.

Following can be used to reproduce this.

```ballerina
int a = 1/0;

@test:Config {}
public function testMethod() {
     // test implementation
}
```
