### ISSUE TITLE
[Task]: Remove `typedesc` class create for records

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#41851]
### Description

In the earlier implementation includes a `typedesc` class for storing default values of record fields. This was initially necessary to retain default values within the `typedesc`. However, with the recent work to creating closures for record defaults, the `typedesc` class is no longer required and can be safely removed.

### Related area

-> Runtime

**Comment by rdulmina** [comment]
if we remove the typedesc class we need to find a way to preserve the value class for the corresponding typedesc. Hence we decided to keep the class as it is

**Comment by rdulmina** [comment]
typedesc class handles the instantiation of the corresponding generated value class for the type.
![Screenshot 2024-08-22 at 15 39 15](https://github.com/user-attachments/assets/15fda9be-ea32-4767-b095-5f9195aed624)
