### ISSUE TITLE
[Bug]: The test initialization fails when mocking generated http clients

### ISSUE THREAD

**Issue by menakaj** [ballerina-platform/ballerina-lang#41891]
### Description

Scenario:

- There is a set of clients which are generated by the bal open api tool. (there are resource functions for each http resource defined in the openapi definition)
- Each client is initialized by a initializer function.
- The initializer function is mocked in the test to created the mock client
- There is a mock client implemented and it is being returned as the client when mocking.

With this setup, when running bal test, it's terminated with the following log. There are no any clue on what went wrong during the initialization phase.

<img width="541" alt="Screenshot 2023-12-15 at 11 37 13" src="https://github.com/ballerina-platform/ballerina-lang/assets/10165411/ad1860a0-7c4a-4f46-87ab-e1f1563d42c5">

### Steps to Reproduce

- Generate few clients from open api definitions
- initialize the clients as final in the source code and use initialization functions
- Implement some dummy code to call the clients
- In the test, mock each initialization function
- implement the test method
- Run `bal test`

### Affected Version(s)

2202.7.1

### OS, DB, other environment details and versions

N/A

### Related area

-> Other Area

### Suggested label(s) (optional)

testFramework

**Comment by Dilhasha** [comment]
This issue is fixed in 220.7.3 onwards. You can move to 2201.7.4 i.e. the latest 7.x patch ATM.

If you try with 2201.7.3, it will display the actual error which is an unnecessary function in the test double.

```
error: invalid function '$get$configs$groups' provided
	at ballerina.test.0:mock(mock.bal:309)
```
