### ISSUE TITLE
[Bug]: Undocumented rest parameter shows as null on hover

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#41896]
### Description

The hover description for an undocumented rest parameter shows `null`. Ideally, it should display an empty string for the considered parameter.

<img width="556" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/59343084/c05f564e-154c-4da2-a708-9650f2a23264">

### Steps to Reproduce

Hover on the below function call expression.

```ballerina
# Description.
#
# + param - parameter description  
# + return - return value description 
function name(string param, int... ids) returns string {
    return "hello";
};

public function main() {
    _ = name("hello", 1, 2, 3);
}
```

### Affected Version(s)

Ballerina 2201.8.3 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS: macOS 14.1.2 23B92
JDK: openjdk 20.0.2 2023-07-18

### Related area

-> Compilation

**Comment by KavinduZoysa** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-lang/pull/41773
