### ISSUE TITLE
[Improvement]: Extend Testerina `.withArgument` method to allow more data types

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#41909]
### Description

When trying to mock a mysql database client, I need to pass sql:ParameterizedQuery type object to mock `mysql:queryRow` method with `withArguments` function in testerina. How ever this is not possible with the current implementation of `withArguments` which accepts `anydata|error` params.
 

### Describe your problem(s)

``` ballerina
sql:ParameterizedQuery noUserQuery = `SELECT id FROM users WHERE name = ?`;
test:prepare(forumDBClient).when("queryRow").withArguments(noUserQuery).thenReturn(noUserError);
```

Fails with error
> error {ballerina/test:0}FunctionSignatureMismatchError ("incorrect type of argument provided at position '1' to mock the function 'queryRow()'")
                                callableName: validateArgumentsExt moduleName: ballerina.test.0 fileName: mock.bal lineNumber: 346
                                callableName: withArguments moduleName: ballerina.test.0.MemberFunctionStub fileName: mock.bal lineNumber: 132
                                callableName: testCreateExistingUser moduleName: wso2.bal_forum$test.0.tests.bal_forum_service_test fileName: tests/bal_forum_service_test.bal lineNumber: 53
                                callableName: testCreateExistingUser$lambda0$ moduleName: wso2.bal_forum$test.0.tests.test_execute-generated_1 fileName: tests/test_execute-generated_1.bal lineNumber: 4

### Describe your solution(s)

Extend the data types which are accepted by withArguments() method 

### Related area

-> Test Framework

**Comment by Dilhasha** [comment]
Until we address it in https://github.com/ballerina-platform/ballerina-lang/issues/42193,
The solution is to avoid withArguments and use `thenReturn`. IF there are multiple calls, can use `thenReturnSequence` as mentioned in https://ballerina.io/learn/test-ballerina-code/mocking/#stub-with-multiple-values-to-return-sequentially-for-each-function-call
