### ISSUE TITLE
[Bug]: Error when accessing a const array defined in a module

### ISSUE THREAD

**Issue by poorna2152** [ballerina-platform/ballerina-lang#41901]
### Description

Compilation error occurs when accessing an array defined in a module

### Steps to Reproduce

Consider the following code with a module `mod`
 proj.mod
```ballerina
public const string[] NAME = ["name"];
```

proj
The main file `main.bal`,
```ballerina
import proj.mod;

public function main() {
    string[] _ = [...mod:NAME];
}
```

This gives the following error, 
```
ERROR [main.bal:(4:22,4:30)] attempt to refer to non-accessible symbol ''
```

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Happens only with constants. Could be due to the consts/symbols we generate for constants (with exactly the values specified).

proj.mod

```ballerina
public const string[] CONST_ARR = ["name"];
public string[] arr = ["name"];
```

proj

```ballerina
import proj.mod;

public function main() {
    string[] _ = [...mod:CONST_ARR]; // error
    string[] _ = [...mod:arr]; // OK
}
```
