### ISSUE TITLE
[New Feature]: Expose JSON path as a Ballerina library function

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#41908]
### Problem 
If the given json structures have so many nested arrays, we need to traverse through json using multiple nested loops to find given json key.  Even we bind that to record still we need multiple loops in code.

### Solution

We can support json path capability as a ballerina library function, so developer requires less code. Even we miss the compile time type checking with that it will be very useful dealing with complex json structures at runtime if the json structure is guaranteed to be same at runtime.

**Comment by MaryamZi** [comment]
This has been added to the JSON data module - https://github.com/ballerina-platform/ballerina-library/issues/5938

https://central.ballerina.io/ballerina/data.jsondata/0.1.0#read
