### ISSUE TITLE
[Bug]: Diagnostics reported in CompilerLifecycleEventContext are ignored

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#41915]
### Description

$Subject.

Consider the following code. 
```java
    @Override
    public void perform(CompilerLifecycleEventContext compilerLifecycleEventContext) {
        DiagnosticInfo diagnosticInfo = new DiagnosticInfo(C2CDiagnosticCodes.DOCKER_FAILED.getCode(),
                "Test Diag", DiagnosticSeverity.WARNING);
        Diagnostic diagnostic = DiagnosticFactory.createDiagnostic(diagnosticInfo, new NullLocation());
        compilerLifecycleEventContext.reportDiagnostic(diagnostic);
        
        }
 ```
 
Ideally, this should show a warning to all packages which uses this compiler plugin. but in this case this diagnostic is ignored. 

### Steps to Reproduce

1. Clone https://github.com/xlight05/module-ballerina-c2c/tree/lifecycle-diag
2. Invoke ./gradlew clean build -x check -x test and copy the generated pack
3. Create a sample ballerina project(http hello world) and invoke <generated pack path> build --cloud=docker

### Affected Version(s)

All

### Related area

-> Compilation

**Comment by ShammiL** [comment]
A fix for this has been introduced in the PR #42131 and the following changes were introduced as a result.
- Diagnostics recorded inside the `JBallerinaBackend` will contain all diagnostics reported during compilation and executable generation stages. Therefore, jar resolving diagnostics and lifeCyclePlugin diagnostics will also be added to this.
- `EmitResult` generated during the executable generating stage will only contain the diagnostics related to executable generating stage and not any other diagnostics reported in earlier stages. Before this fix, all diagnostics were included in the `EmitResult`.
- After the `EmitResult` is generated, all `EmitResult` diagnostics will be printed. This means any other diagnostics related to earlier stages will not be printed again.
