### ISSUE TITLE
[Bug]: Linkage error when loading interface implementation of a compiler plugin from a Ballerina Tool

### ISSUE THREAD

**Issue by Xenowa** [ballerina-platform/ballerina-lang#41957]
### Description

When a Ballerina compiler plugin implements an interface from a Ballerina tool, an attempt to load this interface implementation through the Ballerina tool using `URLClassLoader` with the parent class loader set as `CustomToolClassLoader`, and employing `ServiceLoader`, it results in a `java.lang.LinkageError`. The error specifically points to an attempted duplicate interface definition, preventing the expected loading and invocation of methods within the implemented class of the compiler plugin.

### Steps to Reproduce

Clone the thin-jar-service-loading branch of the repository [here](https://github.com/Xenowa/ballerina-tool-plugin-bridge/tree/thin-jar-service-loading) and follow the instructions in the README file.

### Affected Version(s)

Ballerina 2201.8.2

### Related area

-> Runtime

### Suggested label(s) (optional)

Area/CLI, Team/DevTools

**Comment by gayaldassanayake** [comment]
The issue occurs when there is an SPI (Service Loading) within the tool.

The tools are running on a separate `self-first` class loader named `CustomToolClassLoader` implemented in ballerina-lang. This overrides the default `URLClassLoader` behaviour (`parent-first`) to load the classes from the urls first and then from the parent. 

However there is a bug in this logic where it loads the class without checking if it has been loaded first. Looking if the class is already loaded before class loading within `CustomToolClassLoader->loadClass` fixes the issue.

In the mean time, we need to figure out if we can implement a custom class loader within the scan tool and properly load classes without any linkage errors as a workaround. Will update the thread with the progress.

**Comment by gayaldassanayake** [comment]
Provided a pack with the fix. Since there might be other changes that are needed, will not make a PR until the required changes are finalized.
