### ISSUE TITLE
[Doc] Mention that build command only works in tools-distribution

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4199]
https://github.com/ballerinalang/ballerina/blob/master/docs/tutorials/create-archive.md

**Comment by lankavitharana** [comment]
now build command works in runtime pack as well, below commit adds packerina jars to runtime pack
https://github.com/ballerina-platform/ballerina-lang/commit/a70e0bc
hence closing the issue.
