### ISSUE TITLE
[Bug]: Some Shell help topics are not available.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#41990]
### Description

$subject 

<img width="1509" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/16300038/e8a3dbc4-5424-4689-ba05-422778f166d5">

@praneesha / @xlight05 Can this be due to recent revamps in BBE titles etc?

Btw @hasithaa we need to check all and fix. 

### Steps to Reproduce

Issue the following commands in Shell

```
/help topics 
/help aws lambda s3 trigger
```

### Affected Version(s)

Ballerina 2201.8.4 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.2

### Related area

-> Shell

**Comment by nipunayf** [comment]
This is due to the file name change (`aws_lambda_s3_trigger.bal` -> `aws-lambda-s3-trigger.bal`) that occurred in the distribution, and the issue is resolved with: https://github.com/ballerina-platform/ballerina-distribution/pull/5180

**Comment by praneesha** [comment]
Fixed in `master` and `2201.8.x` branches via the below.

[1] https://github.com/ballerina-platform/ballerina-distribution/pull/5181
[2] https://github.com/ballerina-platform/ballerina-distribution/pull/5180/
