### ISSUE TITLE
[Improvement]: Remove requiring single quotes around cases in data providers

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#42017]
### Description

ATM selectively running tests requires single quotes around cases apart from the quotes as in the below example at https://ballerina.io/learn/test-ballerina-code/define-data-driven-tests/#execute-specific-data-sets

`$ bal test --tests fruitsDataProviderTest#"'banana'"`

Before SL U3 due to a technical limitation in the Java implementation, we had to use single quotes as well. But, with the Ballerina based test engine, we need to look at the possibility of supporting it without the single quotes.

The single quote check can be removed here. 
https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-core/src/main/ballerina/execute.bal#L299

Verify after adding fix:

- [ ] Need to test for all possible cases
- [ ] Keep supporting the single quotes to avoid breaking changes
- [ ] Test https://github.com/manuranga/nballerina with the change

### Related area

-> Test Framework

**Comment by Dilhasha** [comment]
With following change, it worked without single quotes. We need to do the verifications mentioned in the issue.

```
--- a/misc/testerina/modules/testerina-core/src/main/ballerina/execute.bal
+++ b/misc/testerina/modules/testerina-core/src/main/ballerina/execute.bal
@@ -299,7 +299,7 @@ function skipDataDrivenTest(TestFunction testFunction, string suffix, TestType t
                 if (subFilter.startsWith(SINGLE_QUOTE) && subFilter.endsWith(SINGLE_QUOTE)) {
                     updatedSubFilter = subFilter.substring(1, subFilter.length() - 1);
                 } else {
-                    continue;
+                    updatedSubFilter = subFilter;
                 }
             }
```

**Comment by gayaldassanayake** [comment]
Tasks to verify the fix
[ ] Test edge cases 
[ ] Test nballerina
[ ] Update the website with new version
[ ] Manually test with a sample repo
