### ISSUE TITLE
[Bug]: Simple POST request from a cURL client fails with NPE for a Ballerina service ran using lang master

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#42027]
### Description

When we invoke a Ballerina service which runs with lang master, then the a simple POST request fails with the following error:
```
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.scheduling.Scheduler.createFuture(io.ballerina.runtime.internal.scheduling.Strand, io.ballerina.runtime.api.async.Callback, java.util.Map, io.ballerina.runtime.api.types.Type, String, io.ballerina.runtime.api.async.StrandMetadata)
```

**Note:** This is not happening if we invoke the service by adding a Ballerina test in the same package. This might be the reason for **not identifying this issue in the full build pipeline PR check**

### Steps to Reproduce

Service code used to reproduce this issue:
```bal
import ballerina/http;

type Album readonly & record {|
    string title;
    string artist;
|};

final table<Album> key(title) albums = table [
    {title: "Blue Train", artist: "John Coltrane"},
    {title: "Sarah Vaughan and Clifford Brown", artist: "Sarah Vaughan"}
];

service / on new http:Listener(9090) {
    resource function get albums() returns Album[] {
        return albums.toArray();
    }

    resource function post albums(Album album) returns Album|http:Conflict {
        if albums.hasKey(album.title) {
            return http:CONFLICT;
        }
        albums.add(album);
        return album;
    }
}
```

Steps to reproduce this issue:
1. I have used the following timestamped version of lang - `2201.9.0-20240120-003700-f65e7994`. This is also reproducible when we build the lang master and use it in the http module

2. Clone the ballerina-http repository and update the lang version in the `gradle.properties` file

3. Run `./gradlew clean build -x test -x check`. This will create a temporary distribution in the `target` path in the repo root.

4. Use the `bal` command in that `target` directory to run the above Ballerina service

5. Make a cURL request: `curl -v "http://localhost:9090/albums" -d '{"title": "test", "artist": "test"}' -H "content-type: application/json"`

### Affected Version(s)

Ballerina SwanLake Update 9

### Related area

-> Runtime

**Comment by HindujaB** [comment]
I checked the cause for this not happening in the `bal test` environment. For `bal run` when we invoke the `moduleStart` to start listening, there are no jobs to be run further in the same scheduler. Therefore, it is garbage collected and set to null. For `bal test` this scenario won't happen as we invoke `testExecute` after the `moduleStart` which will use the same scheduler.
