### ISSUE TITLE
[Bug]: No error given when non-constant variable reference is used in the namespace uri of xmlns

### ISSUE THREAD

**Issue by poorna2152** [ballerina-platform/ballerina-lang#42075]
### Description

There should be an error when a non-constant variable reference is used to set the namespace uri in an xmlns declaration.

### Steps to Reproduce

Consider the following case,

```ballerina
final string x = "a";

xmlns x as ns;

```

Based on the [spec](https://ballerina.io/spec/lang/master/#xml-namespace-uri) this should give an error.

### Affected Version(s)

2201.8.4

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
This issue is a duplicate of #41988.
