### ISSUE TITLE
[Bug]: `RecordTypeSymbol.fieldDescriptors()` returns NPE

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#42094]
### Description

I have an error intersection like this:
```bal

type ErrorDetail record {
    string|string[] headers?;
    anydata body?;
};
type StatusCodeError distinct error<ErrorDetail>;
type NotFoundError distinct StatusCodeError;

type UserErrorInfo record {|
    string timeStamp;
    string userId;
    string message;
|};

type UserErrorDetail record {|
    *ErrorDetail;
    UserErrorInfo body;
|};

type Error distinct error;

type UserNotFoundError Error & NotFoundError & error<UserErrorDetail>;
```

In the compiler plugin, I am accessing this `UserNotFoundError` type symbol and get the effective error type from the intersection. Then I get the type descriptor of the detail field which is a Ballerina Record Type in this case.

When I call `fieldDescriptors()` method on this Record Type I am getting a Null Pointer Error.

<img width="1552" alt="Screenshot 2024-02-01 at 18 30 14" src="https://github.com/ballerina-platform/ballerina-lang/assets/63336800/43e1ef37-e6e8-4794-8eff-69de935d2e3a">

**Please note that this a blocker to this feature which is expected to deliver with update 9:** 
- https://github.com/ballerina-platform/ballerina-library/issues/5135

### Steps to Reproduce

See the description above.

Java code:
```java
TypeSymbol intersectionErrorType = ((TypeReferenceTypeSymbol) typeSymbol).typeDescriptor();
TypeSymbol effectiveErrorType = ((IntersectionTypeSymbol) intersectionErrorType).effectiveTypeDescriptor();
TypeSymbol detailRecordType = ((ErrorTypeSymbol) effectiveErrorType).detailTypeDescriptor();
((RecordTypeSymbol) detailRecordType).fieldDescriptors();
```

> **Note:**
> If I change the error intersection like this then it works:
> ```ballerina
> type Error0 distinct error<UserErrorDetail>;
> 
> type UserNotFoundError0 Error0 & NotFoundError;
> ```

### Affected Version(s)

Ballerina SwanLake Update 8 (2201.8.4)

### Related area

-> Compilation

**Comment by prakanth97** [comment]
In the compiler, `UserNotFoundError ` is resolved properly, seems semantic api is not exposing it.

**Comment by nipunayf** [comment]
The latest changes in the master appear to work properly for the above scenario, even using the semantic API.

<img width="714" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/59343084/e74d4bfa-191b-4b87-b824-ffa7857a413a">

**Comment by TharmiganK** [comment]
@nipunayf please note that the sample is updated. The previous one was not reproducing this issue

**Comment by nipunayf** [comment]
The problem can be reduced to the following example.

```ballerina
type ErrorDetail record {
    string msg;
};

type UserNotFoundError distinct error & error<ErrorDetail> & error<ErrorDetail> ;
```

The error `Cannot invoke "io.ballerina.tools.diagnostics.Location.lineRange()" because "symbol.pos" is null` is generated at https://github.com/ballerina-platform/ballerina-lang/blob/12560f8af64009fb2e01ccc1fd4f776b48bc43bd/compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/symbols/BallerinaSymbol.java#L65

After the first intersection between `distinct error & error<ErrorDetail>`, it generates a resultant record type, and the position of the `msg` field symbol is null, and this is propagated to the final intersection.
