### ISSUE TITLE
[Bug]: `readonly` objects not identified as `Clonable`

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#42107]
### Description

This is the behaviour of the Current Ballerina version

```
readonly class A {

}


public function main() returns error? {
    readonly & A a = new A();
    _ = check a.clone(); // undefined method 'clone' in object '(A & readonly)'(BCE2013)
}
```

According to the spec all the readonly types should be clonable.
So this should not be a error.

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Closing since this is the expected behaviour.
