### ISSUE TITLE
[Documentation] Information on properties of inner structs are not available in API docs

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#4211]
Information on properties of inner structs are not available in API docs. 
For example : retryConfig is an inner struct which has 2 properties; count and interval. These details are not available in the API doc
https://ballerinalang.org/docs/api/0.95.1/ballerina.net.http.html#SSL

**Comment by VijithaEkanayake** [comment]
Documentation is updated with the relevant details
https://ballerina.io/learn/api-docs/ballerina/http.html#RetryConfig
