### ISSUE TITLE
[Improvement]: Allow passing parameters to Compiler Plugin context from the project API

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#42121]
### Description

There are some use-cases where the developers need to pass parameters/ Java objects into the compiler plugins to achieve the desired function.

### Describe your problem(s)

*Requirements so far*
- Passing of module and db params to the CodeAnalyzerContext in `persist generate` command
- Access a set of object from an code analyzer from a life cycle plugin.
- Passing of a reporter object to a code analyzer context in `bal scan` tool

As of now, we do not have a proper way to include these params in the compiler plugin context.

### Describe your solution(s)

Introduce an API that allows user to pass custom arguments to the compiler plugin context (or specific analyzer/ modifier/ generator contexts) from the project API.

This can be a list of key(string)-value(object) pairs.
``` java
project.currentPackage().setCompilerPluginParam("module", moduleName);
```

However, we have to decide if we should display these params to all types and all the available compiler plugins of a module.

### Related area

-> Compilation

**Comment by Xenowa** [comment]
The Ballerina scan tool is used to perform static code analysis on Ballerina files by checking the source code against a pre defined set of language specific rules. To extend  its capabilities, we plan to introduce compiler plugins that enforce Ballerina library-specific  rules. However, this requires passing a scanner context to the compiler plugins before they execute.

Currently, the scan tool performs core analysis, engages compiler plugins during package compilation. Then the compiler plugins creates new scanner contexts and serialize their  findings to a file, which the scan tool later de-serializes and gathers for reporting.

Ideally we should be able to pass a single scanner context created from the scan tool to the compiler plugins before they engage. During package compilation, these plugins should report analysis issues directly to the scan tool via the reporter obtained from this passed  scanner context.

This approach simplifies the process, eliminates unnecessary file I/O, and enables more efficient and streamlined communication between the scan tool and its compiler plugins.
