### ISSUE TITLE
[Bug]: Getting error when getting the symbol for a class definition which is defined in a separate module

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#42159]
### Description

When I call `SemanticModel.symbol(ClassDefinitionNode)` I am getting a Bad Sad error. This is happening only when the class is defined in a separate module.

```console
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-02-14 17:01:36,200] SEVERE {b7a.log.crash} - No value present 
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143)
        at io.ballerina.compiler.api.impl.BallerinaSemanticModel.getCompilationUnit(BallerinaSemanticModel.java:495)
        at io.ballerina.compiler.api.impl.BallerinaSemanticModel.symbol(BallerinaSemanticModel.java:181)
```

### Steps to Reproduce

1. Create a Ballerina project
2. Add a module in the project
3. Define a simple Ballerina class inside the new module
```ballerina
class Client {}
```
4. Try to get the symbol related to this ClassDefinitionNode using the semantic model

### Affected Version(s)

Ballerina SwanLake 2201.8.4

### Related area

-> Compilation

**Comment by TharmiganK** [comment]
Adding more context to this issue:
- I am writing a compiler plugin which visit the syntax tree and when I find a class definition node, I call `SemanticModel.symbol(ClassDefinitionNode)`.
- This is happening for both public and non-public class definitions in the modules

**Comment by dulajdilshan** [comment]
After proper investigation to this, I found that: The way we access the semantic model is not correct in the `openapi-tools`:  https://github.com/ballerina-platform/openapi-tools/blob/e84b6a9f6eaecf7f628fc9ab0a89578f2b5c6c42/ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/ServiceToOpenAPIMapper.java#L259,

The correct way to find the compiler symbol for the given node is as follows.

```Java
Module module = project.currentPackage().module(project.currentPackage().moduleIds().stream().toList().get(1)); // get the `representations` module
DocumentId documentId = module.documentIds().stream().findFirst().get();    // contains only `representations.bal` document
SyntaxTree syntaxTree = module.document(documentId).syntaxTree();   // get the syntax tree of the `representations.bal` document
ModuleMemberDeclarationNode classDefNode = ((ModulePartNode) syntaxTree.rootNode()).members().get(0); // get the class-def node

SemanticModel semanticModel_1 = project.currentPackage().getCompilation().getSemanticModel(module.moduleId());   // initialize semantic model
semanticModel_1.symbol(classDefNode).get();
```

<img width="1186" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/25485997/3484934d-6dcc-4cd5-a61b-63e3807857ea">


The reason for this is. The semantic Model is a per-module construct and we should not access semantic APIs using nodes or locations from unmatching modules. @TharmiganK Please check.

**Comment by dulajdilshan** [comment]
However, we are sending a bad sad error since we have let semantic API throw an error if incorrect usage.

**Comment by TharmiganK** [comment]
Ack. Thanks for the help. I will correct this from `openapi-tool` side. 

Please close this issue once you fix throwing the bad sad error for such scenarios. Better to throw a proper error in this case
