### ISSUE TITLE
[Bug]: Invalid Suggestions for Fields in Records within Service Config Annotation

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-lang#42178]
### Description

The Ballerina VS code plugin suggests invalid records fields for records in `ServiceConfig` annotation. 

![Screenshot from 2024-02-19 10-46-43](https://github.com/ballerina-platform/ballerina-lang/assets/35717653/65c4bb1a-c375-4df9-89b5-9bc33e25c201)

The suggested fields are the fields of `ServiceConfig` record. Ideally, it should suggest fields of the `CorsConfig` records.
```ballerina
    allowHeaders
    allowMethods
    allowOrigins
    exposeHeaders
    allowCredentials
    maxAge
```

### Affected Version(s)

2201.8.4

### Related area

-> Compilation

**Comment by KavinduZoysa** [comment]
Closing the issue because it is fixed via https://github.com/ballerina-platform/ballerina-lang/pull/41809 in master branch.
