### ISSUE TITLE
[New Feature]: Design a new mocking framework 

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#42193]
### Description

There are some limitations in the existing test framework. Following are some of the major limitations.

- When there are service-level configurations that do a call during module initialization, 
there's no way to mock it rather than adding a mock service.

e.g. auth 
https://github.com/gayaldassanayake/training-content/blob/c33cde2bebadeb76270aa8fa8add15e6a8ea6a62/back-end/sentiment-api/service.bal#L21

- Support mocking global variables at the module level

With the current mock framework, we need to assign the global variable using a function and then use compile time function mocking. This is not user-friendly.
https://ballerina.io/learn/test-ballerina-code/test-services-and-clients/#mock-final-clients

### Related area

-> test framework

**Comment by Thevakumar-Luheerathan** [comment]
We have to generate separate GraalVM images when the function mocking is there. Reason, Function mocking uses Dynamic class loading mechanism. It is better if we can eliminate this limitation with this new design.

**Comment by Thevakumar-Luheerathan** [comment]
> We have to generate separate GraalVM images when the function mocking is there. Reason, Function mocking uses Dynamic class loading mechanism. It is better if we can eliminate this limitation with this new design.

To achieve this, we can evaluate the method mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/42281

**Comment by Thevakumar-Luheerathan** [comment]
We can consider https://github.com/ballerina-platform/ballerina-lang/issues/42330 with new mock design
