### ISSUE TITLE
[Bug]: API docs parameter description is not displayed for parameters with escape character (')

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#42216]
### Description

<img width="823" alt="Screenshot 2024-02-22 at 14 42 11" src="https://github.com/ballerina-platform/ballerina-lang/assets/27669465/3b456794-d8be-492f-82b9-6fba9a28442c">

Here check for description for `'select` parameter

### Related area

-> Editor

**Comment by nipunayf** [comment]
The problem can be reduced to the following Ballerina code.

```ballerina
# Description.
#
# + 'type - parameter description  
# + val - parameter description
function f<CURSOR>n(string 'type, string val) {}
```
