### ISSUE TITLE
[Improvement]: Convert the runtime representation of list, map and xml types to SemTypes.

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#42259]
### Description

Part of #40511
This require porting the cell types to jBallerina. With this we can also support `table`, `error`, `function` and `object` types (all of which are internally represented as combinations of `list` and `map` types) as well

### Related area

-> Runtime

### Related issue(s) (optional)

Require #42258

**Comment by heshanpadmasiri** [comment]
This would be done in fallowing stages

- [ ] Implement list semtype in runtime
- [ ] Implement mapping semtype in runtime
- [ ] Implement xml semtype in runtime

**Comment by lochana-chathura** [comment]
Closing as all subtasks are completed.
