### ISSUE TITLE
[Improvement]: Change the test file name created with `bal add <module-name>`

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#42262]
### Description

When we do `bal add <module-name>`, 
in the generated tests the test file name is set to `lib_test.bal`. Shall we change it to `<module-name>_test.bal`?

### Related area

-> Test Framework

**Comment by gayaldassanayake** [comment]
The current approach is to set the name depending on the template. For add command `lib` and `service` templates are allowed.
1. lib (default) - creates `tests/lib_test.bal`
2. service - creates `tests/service_test.bal`
