### ISSUE TITLE
[Improvement]: Slow LS functionalities caused by resolving dependencies in `PackageContext.java`

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#42261]
### Description

The `getResolution` method in `PackageContext.java` which resolves all the dependencies, results in high CPU usage. We tested this on a low performance machine and found no significant memory consumption, instead, the CPU usage spiked. As a result of this issue, noticeable slowness in LS functionalities can be observed.  

The specs of the laptop were as follows,
Windows 10
i5-10210U CPU
RAM - 16GB

### Related area

-> Compilation

**Comment by Thevakumar-Luheerathan** [comment]
Related release issue : https://github.com/ballerina-platform/ballerina-release/issues/2629
