### ISSUE TITLE
Internal Server Error when opening Ballerina Test docs using VS Code View API Docs

### ISSUE THREAD

**Issue by dsplayerX** [ballerina-platform/ballerina-lang#42301]
**Description:**

An Internal Server Error occurs when attempting to open the Ballerina Test library documentation within the VS Code View API Docs functionality. 
- Generated Link: https://lib.ballerina.io/ballerina/test/0.0.0#Config
- Working Link: https://lib.ballerina.io/ballerina/test/latest#Config

![image](https://github.com/ballerina-platform/ballerina-central/assets/100945633/e30ee47d-afd9-4a9a-8c90-e6fe93fc87d7)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2201.8.5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Open a Ballerina project in Visual Studio Code.
2. Access the documentation for the test library using the VS Code View API Docs feature.
3. Open the provided link: https://lib.ballerina.io/ballerina/test/0.0.0#Config

**Related Issues:**

**Comment by LakshanWeerasinghe** [comment]
In here we have to pick the ballerina version and replace with `0.0.0`.
