### ISSUE TITLE
[HTTP] Payloads are included in the responses to HEAD requests

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4231]
Tried the following sample and the passthrough sample, and in both cases, the responses received for the HEAD requests contained response bodies as well.

Hello World sample
```ballerina
import ballerina.net.http;

@http:configuration {
	basePath: "/hello"
}
service<http> helloWorld {

    @http:resourceConfig { 
	path: "/"
    }
    resource sayHello (http:Request req, http:Response res) {
        res.setStringPayload("Hello, World!");
        _ = res.send();
    }
}
```
request:
`$ curl -v http://localhost:9090/hello -X HEAD`

response:
```
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Connection: Keep-Alive
< Content-Length: 13
< 
* Connection #0 to host localhost left intact
Hello, World!
```

**Comment by shafreenAnfar** [comment]
IMO, this is OK as user has specifically set the payload. Yes this does violates the spec but there can be legacy systems that requires this behaviour. Hence, restricting it could end up hindering our ability to do certain integration.

**Comment by pubudu91** [comment]
Closing this as per @shafreenAnfar 's comment
