### ISSUE TITLE
[Improvement]: Provide code actions to fix invalid access of mutable storage

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#42331]
### Description

The fix for the error message `invalid access of mutable storage in an 'isolated' function (BCE3943)` is decisive based on the user's preference. If the user only wants to read the values, they can make the variable immutable. On the contrary, if they intend to manipulate the data structure in a concurrent-safe manner, they can decide to make the variable isolated. Since both fixes are rather straightforward, the LS can provide CAs as quick fixes.

### Describe your solution(s)

Consider the following source code with the respective diagnostic.

```ballerina
int[] arr = [];

isolated function length() returns int {
    return arr.length();
}
```

**FIX1**: Allow the user to make the variable immutable by making it final and/or readonly.
```ballerina
final int[] & readonly arr = []  // changed

isolated function length() returns int {
    return arr.length();
}
```

**FIX2**: Allow the user to make the variable isolated when the user knows that they have to manipulate the data structure in a concurrent-safe manner.
```ballerina
isolated int[] arr = []; // changed

isolated function length() returns int {
    return arr.length();
}
```

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/28681

**Comment by MaryamZi** [comment]
There's also the case of when the type of the variable is a subtype of `isolated object {}`. Here also. we can suggest adding `final`. Generally, if the type is a subtype of `readonly|isolated object {}`, adding final is enough.

```ballerina
isolated class Counter {
    private int current = 1;

    isolated function next() returns int {
        lock {
            int value = self.current;
            self.current += 1;
            return value;
        }
    }
}

Counter counter = new; // make this final

public isolated function main() {
    int _ = counter.next();
}
```
