### ISSUE TITLE
[Bug]: Parsing issue for function invocations with map type descriptors as arguments

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#42347]
### Description

$subject

When we pass a map type descriptor to a `ensureType` function invocation parser will give an error.

### Steps to Reproduce

```ballerina
function cast() returns error? {
    anydata v = {a: 1};
    var a = v.ensureType(map<int>);
}
```

### Affected Version(s)

2201.8.6

### Related area

-> Compilation

**Comment by rdulmina** [comment]
The spec for this is still not finalized https://github.com/ballerina-platform/ballerina-spec/issues/797. Implementation is done to allow only simple types https://github.com/ballerina-platform/ballerina-spec/issues/797#issuecomment-810917172
