### ISSUE TITLE
[Task]:  Implement runtime APIs for runtime management module

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#42406]
### Description

$subject

### Describe your task(s)

Add new APIs to populate available services, and listener details at runtime for runtime management module

### Related area

-> Runtime

**Comment by hasithaa** [comment]
Shall we update the issue with the current design details?

**Comment by HindujaB** [comment]
The currently added runtime APIs are as follows.
```java
    /**
     * Get the list of runtime artifacts.
     * @return List of artifacts that contains information about the active services and listeners.
     */
    public List<Artifact> getArtifacts();
```
This returns a list of artifact instances that represent the services at runtime. An artifact instance contains a name (service name), type (only service is supported now), and a map of details. The details enclose the following information.
- `listeners` - a list of listener objects attached to the service
- `attachPoint` - the attach point specified in the service declaration (for example, `basePath` in HTTP)
- `service` - the service object

```java
    /**
     * Get the current Ballerina node.
     * @return Ballerina node.
     */
    public Node getNode();
```
This returns a node instance that represents the Ballerina runtime node. A node instance contains a nodeId (self-generated unique ID), and a map of details. The details enclose the following information.
- `balVersion` - The Ballerina version
- `balHome` - The path of Ballerina home
- `osName` - Name of the Operating System
-  `osVersion` - Version of the Operating System

The above APIs can be called from a Ballerina environment instance. Similar to this,

```java 
import io.ballerina.runtime.api.Artifact;
import io.ballerina.runtime.api.Environment;
import io.ballerina.runtime.api.Node;

Repository repository = env.getRepository();
List<Artifact> artifacts = repository.getArtifacts();
Node node = repository.getNode();
```

**Comment by HindujaB** [comment]
closing as the PR is now merged with the master. Please feel free to reopen if there are any concerns.
