### ISSUE TITLE
[Bug]: The `typeOf(Node)` API generates `No value present` for an expression defined in a module

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#42432]
### Description

$title. Note that this issue cannot be reproduced when the respective expression node is within the default module.

![image](https://github.com/ballerina-platform/ballerina-lang/assets/59343084/fe1734b7-869b-46c5-a037-cc6febe00566)

The node information is shown below:
![image](https://github.com/ballerina-platform/ballerina-lang/assets/59343084/54b161f4-906c-46b6-9735-58eb164e7b63)

### Steps to Reproduce

Add the following function to a module within a new package, and invoke the `typeOf(Node)` API for the expression node outlined by the `<START>` and `<END>` tags.

```ballerina
public function isEven(int num) returns boolean {
    return <START>num % 2 == 0<END>;
}
```

### Affected Version(s)

Ballerina 2201.8.0 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS: macOS 14.2.1 23C71
JDK: openjdk 17.0.8 2023-07-18

### Related area

-> Compilation

**Comment by dulajdilshan** [comment]
We are expected get call Semantic API functions on the semantic model of other modules (Semantic model is per module).

However, this works fine in the semantic model of the respective module. 

Checked in current `master` (05b0fcd15cdeea6411dc4b31ea3abd0916aba794) and `2201.9.x`

**Comment by dulajdilshan** [comment]
Had an offline chat with @nipunayf,
