### ISSUE TITLE
[Improvement]: Add retries to Central Client

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#42431]
### Description

We are getting intermittent bal build issues from time to time due to random central call failures. 

Seems like we have retryOnConnectionFailure enabled from okHTTP side. We need to evaluate on what occasions it retries and how many times it does that. 

Most common failures we've observed as of now were 500, 502, 503 and connection resets for now.  We need to see if retryOnConnectionFailure retries for such such cases, if not handle those separately.  

If retryOnConnectionFailure doesn't work for such cases,I feel like having even a single retry should reduce these intermittent failures by a great margin. 

### Related area

-> Compilation

**Comment by Thevakumar-Luheerathan** [comment]
A similar client as the Central client is created with okHttp3 client. A service that always returns 500, 502, and 503 respectively for its resources is also created. I couldn't observe the client retrying for the resource calls mentioned above.
We will add retries manually.
