### ISSUE TITLE
Printing a struct after casting, prints the (additional) fields of the original struct.

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#4252]
Consider below program
```ballerina
function main (string[] args) {
    Student s = {name:"John", age:30, gpa:3.78};
    Person p = (Person) s;

    // printing Person. Should only print two fields
    println(p);
}

struct Person {
  string name;
  int age;
}

struct Student {
  string name;
  int age;
  float gpa;
}
```

But when we print after casting, it prints all three fields (see below).
```
{name:"John", age:30, gpa:3.78}
```

The underlying issue is that the type of the struct value remains unchanged as `Student` at runtime, even though it is casted to `Person`. Hence the struct to string conversion (during println) occurs assuming that the struct type is `Student`.

This is the same root cause for the issue #4253

**Comment by Kishanthan** [comment]
The new syntax is as follows

```ballerina
import ballerina/io;
function main (string... args) {
    Student s = {name:"John", age:30, gpa:3.78};
    Person p = <Person> s;

    // printing Person. Should only print two fields
    io:println(p);
}

type Person record{
  string name;
  int age;
};

type Student record{
  string name;
  int age;
  float gpa;
};
```

This is not an issue. The reason being that, whatever the conversion, the storage type remains the same as the original type before any conversion. A conversion does not change the storage type and hence if we do a print, it will print the storage value.
