### ISSUE TITLE
[Bug]: Intersection of readonly and record type with defaults doesn't function correctly when it is within a Ballerina package

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-lang#42523]
### Description

$title.

Following program compiles without any error when it is in ballerina package.
```ballerina
type Temp record {|
    any[] initalValues = [10, 20, 30];
|};

function value() {
    // Now results in compile-time error.
    Temp & readonly _ = {};
}
```

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
@nipunayf @chiranSachintha can't see the fix sent to the master?

**Comment by MaryamZi** [comment]
Changes introduce to master via https://github.com/ballerina-platform/ballerina-lang/pull/42564.
