### ISSUE TITLE
[Bug]: Invalid suggestions for nested record in annotation

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42536]
### Description

$title.

### Steps to Reproduce

```ballerina
public type Graphiql record {|
    boolean enabled = false;
    string path = "graphiql";
    boolean printUrl = true;
|};

public type GraphqlServiceConfig record {|
    int maxQueryDepth?;
    Graphiql graphiql = {};
|};

annotation GraphqlServiceConfig annot on class;

@annot {
    graphiql: {
        <cursor>
    }
}
service class Service {
    
}
```

Ctrl + Space suggests fields of the outer record.

![Screenshot from 2024-04-11 08-34-46](https://github.com/ballerina-platform/ballerina-lang/assets/8376983/122c2a59-fd5b-4713-b028-b03bc5cc2858)

### Affected Version(s)

2201.8.6

### Related area

-> Editor

**Comment by nipunayf** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/40668, and fixed with https://github.com/ballerina-platform/ballerina-lang/pull/41809

**Comment by MaryamZi** [comment]
Verified with the U9 test pack. Closing since this is a duplicate and is fixed.
