### ISSUE TITLE
[Bug]: The "Implement method' code action adds invalid code when reserved keywords are used

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42540]
### Description

$title, since they are added without the quote.

### Steps to Reproduce

```ballerina
import ballerina/graphql;

readonly service class AuthZInterceptor {
   *graphql:Interceptor;
}
```

adds

```ballerina
import ballerina/graphql;

readonly service class AuthZInterceptor {
    *graphql:Interceptor;

    isolated remote function execute(graphql:Context context, graphql:Field field) returns anydata|error {
        return;
    }
}
```

Note how `field` is not a quoted identifier.

### Affected Version(s)

2201.8.6

### Related area

-> Editor

**Comment by nipunayf** [comment]
The error is not reproducible with the latest changes (2201.10.0-SNAPSHOT)


https://github.com/ballerina-platform/ballerina-lang/assets/59343084/ef3e54f4-3f1c-4ff6-9332-d85c822f3a80
