### ISSUE TITLE
[Improvement]: Unnecessary message related to the generated directory when using `bal clean`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42553]
### Description

$title.

### Describe your problem(s)

```cmd
ballerina: provided target directory '<PATH_TO_PROJECT>/target' does not exist.
Existing generated directory was not found
```

### Describe your solution(s)

1. Do we really need to mention this, given the `generated` directory won't always be there
2. Even if we do include this, shouldn't it be consistent with the message for no target directory?

### Related area

-> Other Area

**Comment by Dilhasha** [comment]
Completed. Hence,closing.
