### ISSUE TITLE
[New Feature]: Observability support for GraphQL

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42562]
### Description

Creating this to track $title.

Current suggestions include at least the following

**Tracing**

At the moment, when service classes are returned from a GraphQL service, while there are traces for the subsequent calls on the services, they are all shown separately, and are not nested (i.e., parent span information doesn't seem to be propagated as expected).

https://ballerina.io/learn/by-example/graphql-returning-service-objects/

**Metrics**

Can we have at least

* GraphQL-specific metrics like query, mutation, and subscription counts
* A (Grafana) dashboard with GraphQL metrics

### Related area

-> Observability

**Comment by ThisaruGuruge** [comment]
Similar to other GraphQL dashboards, we should include the following metrics:

1. *No. of requests*
2.  *Requests per second*
3. *Request error rate*
4. *Errors per second*
5. *Response latency*
6. *Top 10 most requested operations*
7. *Top 10 slowest operations*
8. *Top 10 operations that errored*
9. *Top 10 fields requested*
10. *No. of Query, Mutation, and Subscription operations*
11. *CPU usage*
12. *Memory usage*

The HTTP service can obtain above 1, 2, 11, and 12.

Others have to be published from the GraphQL Engine. 

As the first step, we can consider the 1, 2, 3, 4, 5, 6, 10, 11, and 12. We can also consider 9 for the first phase, but we can keep it for the second phase with the rest of the metrics too.

@shafreenAnfar @MaryamZi please let me know if I missed anything here.

**Comment by NipunaMadhushan** [comment]
I checked on Including observability support for GraphQL. 

Currently there is no inheritance between the resource functions in graphql service and the resource functions in service classes. The issue occurred when we were using service classes as a return parameter inside a graphql service.

I noticed that we don't pass the properties from the parent strand to the next in graphql as we do in http module. I tried to pass the properties from the parent strand as well to the next strand as well. But it seems like the GraphiQL client request at http://localhost:<PORT>/testing is identified as the parent span. 

<img width="1436" alt="Screenshot 2024-04-22 at 01 03 25" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/c01b0dcd-2678-4983-91f6-f39a168004e4">

But I also noticed that the span created from the resource function in the main service has also ended before the spans generated for resource function in service class.

**Comment by NipunaMadhushan** [comment]
Furthermore, I identified that the strand for the main service resource function had been ended before the execution of the service object resource functions. That is why the parent strand had been set to GraphiQL client request strand. Therefore when I pass the properties(observer context) from the current strand to the future strand, it will identify the GraphiQL client request span as the parent span.

**Comment by NipunaMadhushan** [comment]
I tried to pass the new observer context(observer context for the main graphql service object) to the parent strand (main http service request). Then I passed the parent strand observer context to future strands for sub service objects. It worked for the usecase as the spans for sub service object requests are nested under the main graphql service request span.

<img width="1440" alt="Screenshot 2024-04-26 at 01 44 05" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/ca2847d0-5276-43c8-9493-49dd3d2ec89e">

**Comment by NipunaMadhushan** [comment]
I tested the above fix with with the interceptors as well and the following output came in jaeger.

<img width="1440" alt="Screenshot 2024-04-26 at 22 28 45" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/0779a104-6b07-42b9-a8f3-5a5fc232d72d">

With the current implementation in ballerina runtime observability, we cannot set the main service object as the parent span for other service object spans.

**Comment by NipunaMadhushan** [comment]
Final view of after adding metrics tags to metrics will be as follows.

<img width="1429" alt="Screenshot 2024-05-06 at 22 42 54" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/63c7f01e-4e16-4284-9774-de4b01e3b719">

<img width="1427" alt="Screenshot 2024-05-06 at 22 43 01" src="https://github.com/ballerina-platform/ballerina-lang/assets/51471998/f16e05cf-cae6-4319-b79f-368c10685090">
