### ISSUE TITLE
Even after ensuring type, the compiler does not pick up the variable

### ISSUE THREAD

**Issue by sacheeramesh** [ballerina-platform/ballerina-lang#42593]
**Description:**
A record type has a nullable attribute, It can either be a string or a null. In the code, I checked the attribute is a string, but within the if condition, I cannot treat the variable as a string. the compiler still picks up the variable as a string or null. 

**Steps to reproduce:**

Record type : 
```
# Employee record.
type Employee record {
    # First name of the employee
    string firstName;
    # Compensation details or null
    string? compensation;
};

# Compensation record.
public type Compensation record {|
    # Compensation type
    string key;
    # Compensation value
    string value;
    # Type of the value
    CompensationType 'type;
|};
```

Code:
```
Employee|error result = databaseClient->queryRow(query);
 types:Compensation[]|error compensations = [];
    if result.compensation is string {
        compensations = result.compensation.fromJsonStringWithType();
    }
```

Error:
incompatible types: expected 'string', found 'string?'

**Affected Versions:**
Ballerina 2201.8.4
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
Type narrowing happens only for parameters and local variables. Since the record value is mutable, we can't guarantee that the field will continue to be a string even if the `is` check evaluates to true when that check is done.

You can assign `result.compensation` to a variable and use that instead, narrowing will then work as you expect here.

```ballerina
string? compensation = result.compensation;
if compensation is string {
    compensations = compensation.fromJsonStringWithType();
}
```

**Comment by sacheeramesh** [comment]
HI @MaryamZi Understood and thank you for the update
