### ISSUE TITLE
[Bug]: Executing specific cases of a data provider doesn't work as expected with single bal files

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42600]
### Description

$title. Runs all.

### Steps to Reproduce

Try one of the samples in https://ballerina.io/learn/test-ballerina-code/define-data-driven-tests/#execute-specific-data-sets in a single bal file.

### Related area

-> Test Framework

**Comment by Thevakumar-Luheerathan** [comment]
This issue wasn't identified with update 9 RC2 or master. This issue is there only with update8. It is fixed in master/update9 with https://github.com/ballerina-platform/ballerina-lang/pull/42117.
