### ISSUE TITLE
[Improvement]: Improvements to JSON to record conversion

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42610]
### Description

$title.

### Describe your problem(s)

For 

```json
{
    "a": 1, 
    "b": "str",
    "c": null
}
```

we generate

```ballerina
type NewRecord record {
    int a;
    string b;
    anydata c;
};
```

### Describe your solution(s)

At the moment,

1. when there are `null` values, the relevant field is generated as `anydata`, why not use `json`?
2. the generated records are inclusive record typedescs, open by `anydata`. Can't we generate exclusive record typedescs with `json` as the rest descriptor instead?

This way, the generated record will also be a subtype of `json`.

```ballerina
type NewRecord record {|
    int a;
    string b;
    json c;
    json...;
|};
```

### Related area

-> Other Area

**Comment by Shadow-Devil** [comment]
Hey @azinneera, do you think this issue could also be included into the hacktoberfest? If yes, I would like to work on it and be assigned :)
