### ISSUE TITLE
[Bug]: Bindgen tool generates incorrect code

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#42624]
### Description

Bindgen tool generates a code with compilation errors.

### Steps to Reproduce

1. Create a project
2. Inside the project execute `bal bindgen -mvn com.github.jknack:handlebars:4.3.1 --public com.github.jknack.handlebars.Handlebars com.github.jknack.handlebars.Template`
3. Compiler the project. 

```
Compiling source
        hasitha/test:0.1.0
ERROR [modules/com.github.jknack.handlebars/Template.bal:(41:20,41:46)] incompatible types: expected '(string|hasitha/test.java.io:0.1.0:IOException)', found 'string?'
ERROR [modules/com.github.jknack.handlebars/Template.bal:(68:20,68:46)] incompatible types: expected '(string|hasitha/test.java.io:0.1.0:IOException)', found 'string?'
error: compilation contains errors
```

### Affected Version(s)

Update9 RC1

### Related area

-> Bindgen Tool

**Comment by keizer619** [comment]
This is happening in `2201.8.6` as well
