### ISSUE TITLE
[Improvement]: Support a new option to add attributes in XML to Record conversion

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#42653]
### Description

Currently we have an option to include namespaces when converting an XML to a record. Similarly add another option to add attributes.

**example:**

```
<book>
    <title lang="en">string</title>
</book>
```

**Without attributes**

```
@xmldata:Name {value: "book"}
type Book record {
    string title;
};

```
**With attributes**

```
type Title record {
    string \#content;
    @xmldata:Attribute
    string lang;
};

@xmldata:Name {value: "book"}
type Book record {
    Title title;
};

```

### Related area

-> Compilation

**Comment by prakanth97** [comment]
We can support following two options for attributes.

1. Option1: `Add attributes` As mentioned in this issue description, user can include or exclude attribute with this option.
2. Option2: `Ignore attribute annotation` where user can remove the attribute annotation only.

@hasithaa @mindula WDYT should we support both cases or the only the `option1`?

**Comment by mindula** [comment]
Decided to add two options for each of the above mentioned scenarios.

**Comment by hasithaa** [comment]
Yes, these are two different options. But if developer decides to ignore attributes, we need to disable add attribute annotation option in the UI.
