### ISSUE TITLE
Rewrite HTTP action invocation in a ForkJoin Worker Test case as an integration test case

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#4265]
Following test cases is disabled as it fails intermittently. Hence rewrite this test case as an integration test, which calls to a local endpoint. 

https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-test/src/test/java/org/ballerinalang/test/worker/NotSoBasicWorkerTest.java#L161

**Comment by NatashaWso2** [comment]
Closing this issue since we have removed the join and timeout blocks from the fork and the test was modified to suit the latest changes.
