### ISSUE TITLE
[HTTP] Add support for enforcing HTTP 1.0

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4267]
Created to keep track of the above mentioned feature which is mentioned in issue #846 

On the client connector side when we do this we need to make sure two things. 

1) We never chunk the outbound request. 
2) Connection is closed by default. 

On the server side,

This need to work automatically. If the user sends a 1.0 request. We need to stop chunking and close the connection.

**Comment by shafreenAnfar** [comment]
This has been fixed.
