### ISSUE TITLE
[Bug]: Strand is not yeilding at `runtime:sleep`

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#42678]
### Description

Assume we have two worker, say `w1` and `w2` and have an alternate wait (ie. `wait w1|w2`). Now assume we have a `runtime:sleep` in the first worker to execute (say this is `w1`). When we hit this `sleep` it should cause the strand of `w1` to pause. This should free us the thread that was running that strand to execute `w2`. However this doesn't happen and instead `w1` blocks the execution of the program.

### Steps to Reproduce

1. Clone https://github.com/heshanpadmasiri/worker-yeild-bug
2. Run `bal run` in fallowing directories
   1. [ExternalServices](https://github.com/heshanpadmasiri/worker-yeild-bug/tree/master/ExternalServices) 
   2. [server](https://github.com/heshanpadmasiri/worker-yeild-bug/tree/master/server)
   3. [client](https://github.com/heshanpadmasiri/worker-yeild-bug/tree/master/client)

worker `w2` should run first and when it hits sleep it don't yield and handover to `w1`

_I couldn't get a more simpler test case to work since runtime will always choose to execute worker without the sleep every time. This is the only time I managed to get the runtime to run the worker with sleep first_

### Affected Version(s)

verified on `2201.8.6`

### Related area

-> Runtime

**Comment by HindujaB** [comment]
The above code contains the `return wait w2 | w1;` statement which waits for one of the multiple workers to terminate. 
As per the latest spec,  
> As soon as one of the wait operations completes normally with a non-error value v, the alternate-wait-action completes normally with result v. If all of the wait operations complete normally with an error, then it completes normally with result e, where e is the result of the last wait operation to complete. If any of the wait operations completely abruptly before the alternate-wait-action completes, then the alternate-wait-action completes abruptly.

In the provided code, the first worker `w1` returns a conversion error during the HTTP client calls due to invalid data mapping `LiveScoreService2Res`. It should be `LiveScoreService1Res`.  Due to the alternate wait action we use, it waits for `w2` to finish executing (technically, hangs due to the runtime sleep call). The `w1` is already terminated due to the error.  

Therefore, the above behavior is expected. If we want to catch the errors from all workers, we should use the multiple wait action.

**Comment by heshanpadmasiri** [comment]
> The above code contains the `return wait w2 | w1;` statement which waits for one of the multiple workers to terminate. As per the latest spec,
> 
> > As soon as one of the wait operations completes normally with a non-error value v, the alternate-wait-action completes normally with result v. If all of the wait operations complete normally with an error, then it completes normally with result e, where e is the result of the last wait operation to complete. If any of the wait operations completely abruptly before the alternate-wait-action completes, then the alternate-wait-action completes abruptly.
> 
> In the provided code, the first worker `w1` returns a conversion error during the HTTP client calls due to invalid data mapping `LiveScoreService2Res`. It should be `LiveScoreService1Res`. Due to the alternate wait action we use, it waits for `w2` to finish executing (technically, hangs due to the runtime sleep call). The `w1` is already terminated due to the error.
> 
> Therefore, the above behavior is expected. If we want to catch the errors from all workers, we should use the multiple wait action.

Confirmed this is to be the reason.
