### ISSUE TITLE
Missing http service path error is not complete

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#4268]
HTTP method is not indicated.

I had a service for `/` but it was for `POST`, when I send a get I get following: 
`no matching service found for path : /`

It should be `No matching service found for HTTP method GET at path : /`

**Comment by pubudu91** [comment]
@manuranga methods are specified for resources. The error message for that contains the method name as well as it can be seen in the [code](https://github.com/ballerinalang/ballerina/blob/f111b6b6f0c830f5ab56161048b4281c9c35812a/modules/ballerina-http/src/main/java/org/ballerinalang/net/http/HTTPResourceDispatcher.java#L57). Do you have the Ballerina code for the service you tried out?
