### ISSUE TITLE
[Bug]: No such field exception for client method call in a test function

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#42693]
### Description

Getting no such field exception when I have a client method call inside the test function. The client method has escape characters and has a default parameter. 
If I move the same code in the test function to the main function then it worked as expected
It seems like an issue in the generated code for the test function

### Steps to Reproduce

1. Create a ballerina project 

2. Add the following to `main.bal`
    ```bal
    import ballerina/io;
    client class Client {
    
        resource function get users\-all(string 'order = "asc") returns json {
            return [];
        }
    }
    
    final Client clientEP = new;
    
    public function main() {
        json res = clientEP->/users\-all();
        io:println("obtained response: ", res);
    }
    ```

3. Add the following test function in the `tests` directory
    ```bal
    import ballerina/io;
    import ballerina/test;
    
    @test:Config {}
    function test() {
        json res = clientEP->/users\-all();
        io:println("obtained response: ", res);
    }
    ```

4. Run `bal run` - This is working

5. Run `bal test`:
    ```console
    $ bal test
    
    Compiling source
            tharmigan/project:0.1.0
    
    Running Tests
    
            project
    [2024-05-06 08:48:51,532] SEVERE {b7a.log.crash} - $Client_$get$users\-all_order 
    java.lang.NoSuchFieldError: $Client_$get$users\-all_order
            at tharmigan.project$test.0.tests.test.test(tests/test.bal)
            at tharmigan.project$test.0.tests.test_execute-generated_1.test$lambda0$(tests/test_execute-generated_1.bal:4)
            at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
            at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
            at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
            at java.base/java.lang.Thread.run(Thread.java:833)
     
    
            test has failed.
    
    
                    [fail] test:
    
                        error("java.lang.NoSuchFieldError: $Client_$get$users\-all_order")
                                    callableName: test$lambda0$ moduleName: tharmigan.project$test.0.tests.test_execute-generated_1 fileName: tests/test_execute-generated_1.bal lineNumber: 4
    
    
    
                    0 passing
                    1 failing
                    0 skipped
    
                    Test execution time : 0.032s
    error: there are test failures
    ```

### Affected Version(s)

SwanLake Update 8 (2201.8.6)
SwanLake Update 9 (2201.9.0)

### Related area

-> Test Framework

**Comment by nipunayf** [comment]
The problem is only reproducible when the client definition is outside of the respective test file. Once the definition is placed along with the test function in the same file, the error is not generated.

**Comment by TharmiganK** [comment]
> The problem is only reproducible when the client definition is outside of the respective test file. Once the definition is placed along with the test function in the same file, the error is not generated.

Yes, the issue arises when we have the generated code for test. There seems to be an inconsistency in the generated byte code for the tests and main, where we call a function to get the default value for this resource method argument.

**Comment by Thevakumar-Luheerathan** [comment]
The slash in the resource method is causing the issue. If we remove that slash, it works fine. The following snippets show various instances of generated code.
- The client is in main.bal 

    1. Generated client call in main.bal
         
          <img width="796" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/84483520/b74d70be-c833-410c-9268-3711b3ce2104">

    2. Generated client call in test.bal
            
          <img width="794" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/84483520/36564f8e-fc41-4134-a48e-d16c75d6931b">


- The client is in test.bal
    1. Generated client call in test.bal
         <img width="769" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/84483520/dc136bc8-1910-4fd6-9059-a80d8eb34056">

@gabilang can you have a look on it?
