### ISSUE TITLE
[Bug]: Record literal expression error evaluation create infinite loop

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#42728]
### Description

$subject

### Steps to Reproduce

The compiler type-checker creates unnecessary anonymous record types when evaluating record literals and logging an error. 
https://github.com/ballerina-platform/ballerina-lang/blob/89f1a3982bb9aa0d51c2bc982dbc6a5c79b80c23/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L1907

The log error call creates new anonymous record types in a loop. This results in around 12000 new `anonType_` type definitions which cause `file too large` and `method too large` errors in code generation.

Please refer to the code provided at https://github.com/wso2-enterprise/internal-support-ballerina/issues/672 

### Affected Version(s)

2201.8.x and onwards

### Related area

-> Compilation

### Related issue(s) (optional)

https://github.com/wso2-enterprise/internal-support-ballerina/issues/672

**Comment by HindujaB** [comment]
Removing the `getInferredTupleType` method call in the logging error fails in the following cases. 
https://scans.gradle.com/s/zpxzt5hn2u2hg/tests/overview?outcome=FAILED

**Comment by chiranSachintha** [comment]
https://github.com/ballerina-platform/ballerina-release/issues/2699
