### ISSUE TITLE
[Improvement]: Reuse the existing semtype port tests to test the runtime semtype implementation

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#42814]
### Description

We already has type testing framework for testing compiler side implementation of semtypes. We should be able to refactor the logic such  that we can just replace the type checking and type resolution logic and run same tests on both compiler and runtime type systems.

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
Added with #43279 via #42841
