### ISSUE TITLE
[Bug]: Getting `Existing generated directory was not found` during `bal clean` when a `generated` dir exists outside the bal project

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#42816]
### Description

I got this when the `generated` dir was immediately outside the ballerina project.

### Steps to Reproduce

<img width="622" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/5234641/3ffc3c13-010d-4aa2-abea-de4606befbb5">

### Affected Version(s)

2201.9.0

### Related area

-> Compilation

**Comment by ShammiL** [comment]
This issue is not reproducible for Update 9 as a fix was added before the release. Added the same fix for master.
