### ISSUE TITLE
[Bug]: gradle build issues in windows

### ISSUE THREAD

**Issue by Thushara-Piyasekara** [ballerina-platform/ballerina-lang#42844]
### Description

This issue contains a list of gradle issues present when building ballerina-lang on Windows.

1. `:bir-spec:kaitai`  task failure
Windows build fails for `:bir-spec:kaitai` task with the following exception,
```
* What went wrong:
Execution failed for task ':bir-spec:kaitai'.
> name.valery1707.kaitai.KaitaiException: Fail to generate Java files
```

2. `:jballerina-tools:generateDocs` task failure
If we exclude the above task and run the build again, following exception is thrown,
```
* What went wrong:
Execution failed for task ':jballerina-tools:generateDocs'.
> Process 'command 'C:\src\jdk-17.0.8.7-hotspot\bin\java.exe'' finished with non-zero exit value 1
```

3. `./gradlew clean` task failure
This is mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/42782.
When running the `./gradlew clean` after a build, following exception is thrown,
```
Execution failed for task ':clean'.
> java.io.IOException: Unable to delete directory 'C:\Users\Ballerina_CodeBase\BallerinaLangClones\ballerina-lang\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\Ballerina_CodeBase\BallerinaLangClones\ballerina-lang\build\tmp\.cache\expanded\expanded.lock
    - C:\Users\Ballerina_CodeBase\BallerinaLangClones\ballerina-lang\build\tmp\.cache\expanded
    - C:\Users\Ballerina_CodeBase\BallerinaLangClones\ballerina-lang\build\tmp\.cache
    - C:\Users\Ballerina_CodeBase\BallerinaLangClones\ballerina-lang\build\tmp
```

As a workaround for failure 1 and 2, use the following command,
```
./gradlew build -x check x :jballerina-tools:generateDocs -x :bir-spec:kaitai
```

### Steps to Reproduce

To reproduce above mentioned errors run the following commands in `ballerina-lang` directory.

1. `:bir-spec:kaitai`  task failure
```
./gradlew build -x check 
```

2. `:jballerina-tools:generateDocs` task failure

```
./gradlew build -x check -x :bir-spec:kaitai
```

3. `./gradlew clean` task failure
Run the following command after attempting a build,
```
./gradlew clean
```

### Affected Version(s)

Ballerina 2201.10.0 (Swan Lake Update 10)

### OS, DB, other environment details and versions

OS: Windows 10

### Related area

-> CICD

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/42782
https://github.com/ballerina-platform/ballerina-lang/issues/41090

**Comment by Shadow-Devil** [comment]
Hi, I also noticed that on windows the clean command would not work and found out that it is a known issue in gradle (gradle/gradle#25752) and is fixed with gradle 8.7. I also proposed to update gradle in this PR to fix this issue: #42783 (and issue #42782)

**Comment by Shadow-Devil** [comment]
I also created a PR where I tried to fix the windows build and also javadoc, test execution and unrelated improvements: #42797

**Comment by Thushara-Piyasekara** [comment]
@Shadow-Devil Thank you for the contribution. It's my bad, I didn`t check thoroughly for existing PRs. I will link your issue here.

**Comment by Shadow-Devil** [comment]
PR #42782 just got merged. For me, `./gradlew build -x check` is now working on Windows. 
Also directly running `./gradlew :bir-spec:kaitai` works for me.
If I execute `./gradlew :jballerina-tools:generateDocs` I get following error:
```
> Task :docerina-gradle-plugin:createJavadoc
E:\Programming\open-source\ballerina-lang\misc\ballerina-gradle-plugins\docerina-gradle-plugin\src\main\java\org\ballerinalang\plugin\gradle\doc\DocerinaGen.java:33: warning: no comment
    public static void main(String[] args) {
                       ^
error: warnings found and -Werror specified
1 error
1 warning
```

**Comment by Thushara-Piyasekara** [comment]
@Shadow-Devil, If you try running the gradle task with the `--info` flag, it will print the full stacktrace.

```
./gradlew :jballerina-tools:generateDocs --info
```

You will get the following error,
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.ballerinalang.docgen.docs.BallerinaDocGenerator.<clinit>(BallerinaDocGenerator.java:70)
        at org.ballerinalang.plugin.gradle.doc.DocerinaGen.main(DocerinaGen.java:34)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 2 more
```
This error seems to be the actual cause for `./gradlew :jballerina-tools:generateDocs` not working. The reason for this might be due to `slf4j` dependency not being properly provided. Hope this is helpful. I will also try to find the root cause and update here if I find it.

**Comment by Shadow-Devil** [comment]
@Thushara-Piyasekara I tried to run it with the `--info` flag and still got a successful build:
```
> Task :jballerina-tools:generateDocs
Caching disabled for task ':jballerina-tools:generateDocs' because:
  Gradle does not know how file 'build\api-docs\ballerina' was created (output property '$1'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).
Task ':jballerina-tools:generateDocs' is not up-to-date because:
  Implementation of input property 'jvmArgumentProviders.$0' has changed for task ':jballerina-tools:generateDocs'
Starting process 'command '...\openjdk-17.0.2\bin\java.exe''. Working directory: E:\Programming\open-source\ballerina-lang\distribution\zip\jballerina-tools Command: ...\openjdk-17.0.2\bin\java.exe -Dballerina.home=E:\Programming\open-source\ballerina-lang\distribution\zip\jballerina-tools\build -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp E:\Programming\open-source\ballerina-lang\distribution\zip\jballerina-tools\build\distributions\jballerina-tools-pathing-2201.10.0-SNAPSHOT.jar org.ballerinalang.plugin.gradle.doc.DocerinaGen E:\Programming\open-source\ballerina-lang\distribution\zip\jballerina-tools\build/api-docs
Successfully started process 'command '...\openjdk-17.0.2\bin\java.exe''
docerina: API documentation generation for doc path - E:\Programming\open-source\ballerina-lang\distribution\zip\jballerina-tools\build\api-docs
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 2m 18s
```

**Comment by Thushara-Piyasekara** [comment]
@Shadow-Devil I tried again with the latest version of the master branch. But `./gradlew :jballerina-tools:generateDocs --info` command seems to produce the above mentioned error on Windows. Then I tried the same procedure in another Windows laptop the `./gradlew :jballerina-tools:generateDocs --info` task executed successfully. 

Maybe there is a gradle caching issue in my end. Or the fix you mentioned here https://github.com/ballerina-platform/ballerina-lang/issues/42844#issuecomment-2158105563 partially fixed the error. I will test it more and update here.

**Comment by Shadow-Devil** [comment]
@Thushara-Piyasekara You can just disable the cache locally for testing. Set `org.gradle.caching=false` in the `gradle.properties` file

**Comment by Shadow-Devil** [comment]
Maybe it could also be some different Windows version. I used Windows 10 where it went successful. Do you run Windows 10 on your Laptop and maybe Windows 11 on your PC where it is failing?

**Comment by Shadow-Devil** [comment]
@Thushara-Piyasekara could you try again now that #42797 is also merged?

**Comment by Thushara-Piyasekara** [comment]
> Maybe it could also be some different Windows version. I used Windows 10 where it went successful. Do you run Windows 10 on your Laptop and maybe Windows 11 on your PC where it is failing?

It was Windows 10 on both machines. The other laptop was from a colleague.

**Comment by Thushara-Piyasekara** [comment]
> @Thushara-Piyasekara could you try again now that #42797 is also merged?

I will try again and update here. Thank you for working on this issue.

**Comment by Thushara-Piyasekara** [comment]
I tested it again throughout the week and `./gradlew :jballerina-tools:generateDocs` is working in both laptops now. 

Since all three commands mentioned in this issue are working now, we can close this issue. Thank you again for the contribution @Shadow-Devil.
