### ISSUE TITLE
[Bug]: Cannot debug readonly records in SL 8.x and 9.x

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#42848]
### Description

$subject.

```bal
import ballerina/io;

public type Rec1 readonly & record {|
    int id;
    string str;
|};

public function main() {
    Rec1 r1 = { id: 1, str: "hello" };
    io:println(r1.id); // place the debug point here
}
```

Consider the above simple readonly record. The record field values are not shown in the debugger. 
Please refer to the below screenshot.

<img width="915" alt="Screenshot 2024-06-03 at 13 58 41" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/c4ea237d-800f-488f-be4f-d3b18960bfc6">

Note: Field values are shown in the debugger when the `readonly`  intersection is removed from the record.

Shows the correct information in 2201.7.1

<img width="808" alt="Screenshot 2024-06-03 at 14 11 32" src="https://github.com/ballerina-platform/ballerina-lang/assets/39232462/ba839eb9-8264-448d-83a0-e41dddd54fd7">

### Affected Version(s)

SL 2201.8.0 at least. 

Works in 2201.7.1

**Comment by Thevakumar-Luheerathan** [comment]
Added to the 2201.8.7 milestone: https://github.com/ballerina-platform/ballerina-release/issues/2631
