### ISSUE TITLE
[New Feature]: No API to get the location of a `NodeList`

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#42867]
### Description

$subject. 

Encountered this requirement to @TharmiganK when getting the location of `absolute-resource-path` in `service socialMedia:Service /social\-media/api on new http:Listener(8080)`. 

We can get the location of the `NodeList` from `underlyingListNode().location()`. However, `underlyingListNode()` is not exposed to public. 

So, I think we can implement an API `location()` from `NodeList` class which returns `underlyingListNode().location()`.

**Comment by lochana-chathura** [comment]
This seems like a common requirement. However, I wonder how we didn't encounter such until today. :)

**Comment by MaryamZi** [comment]
Closing this issue for now since we don't plan on addressing it immediately.
