### ISSUE TITLE
[Task]: Evaluate retention of strand-dump tool with Java virtual threads

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-lang#42879]
### Description

$title

### Related area

-> Runtime

**Comment by ravinperera00** [comment]
Currently, the strand dump is obtained by sending a `TRAP` signal using the `kill -5 <PID>` command. This displays an overview of all the strands used in the runtime as follows.
<p align="center">
<img src="https://github.com/ballerina-platform/ballerina-lang/assets/62183347/6b6353d2-0749-4752-a3ab-3ff73eb10d82" alt="strand_dump" width="600">
</p>

With the switch to virtual threads and the removal of the concept of “strand groups”, the strand dump will need to contain the number of virtual threads in use and their respective stack traces. The native thread dump present with Java can be used to obtain information regarding the state of platform threads, however, it does not contain information about virtual threads ([Refer](https://openjdk.org/jeps/444)). This forces us to use the `jcmd` tool that can produce a thread dump file that contains information regarding both platform and virtual threads. The following command can be used for that.

`jcmd <pid> Thread.dump_to_file -overwrite <file>`

Once a thread dump file is produced, it can be parsed to find information specific to virtual threads. The file contains information such as the thread number, thread name, and stack trace. A report can then be generated using that information as follows.

<p align="center">
<img src="https://github.com/ballerina-platform/ballerina-lang/assets/62183347/5ea7d56f-ebc9-4793-8b9f-4d7aa2161cbf" alt="ballerina_dump" width="600">
</p>
