### ISSUE TITLE
[Improvement]:  Provide an option to configure transaction auto commit timeout

### ISSUE THREAD

**Issue by dsplayerX** [ballerina-platform/ballerina-lang#42922]
### Description

Long-running transactions are being cleaned before reaching the commit phase, resulting in a `transaction not found` error during the commit phase.

It is possible that this issue is caused by the [`cleanupTransactions()`](https://github.com/ballerina-platform/module-ballerinai-transaction/blob/d6d250182359862776b50e383fb8f1e9f438eaea/transaction-ballerina/commons.bal#L51), which is responsible for cleaning up transactions by auto committing transactions that have been running for more than 120 seconds in the backend. This process could be prematurely ending active long-running transactions before they have the chance to reach the actual commit phase.

The full stack trace is as below. 
```
time=2024-06-13T16:52:53.875+05:30 level=DEBUG module=ballerinai/transaction message="Running 2-phase commit for transaction: 892402ef-89b1-4304-b06a-1f375618e316:1"
time=2024-06-13T16:52:53.881+05:30 level=DEBUG module=ballerinai/transaction message="Auto-committed initiated transaction: 892402ef-89b1-4304-b06a-1f375618e316. Result: committed"
error: Transaction: 892402ef-89b1-4304-b06a-1f375618e316:1 not found
        at ballerinai.transaction.0:endTransaction(transaction_block.bal:118)
           dsameendra.long_running_transaction_issue.0:main(main.bal:8)
```

### Steps to Reproduce

Code to reproduce the issue:

```
import ballerina/log;
import ballerina/lang.runtime;

public function main() returns error? {
    transaction {
        check longRunningTask();
        check commit;
    }
}

function longRunningTask() returns error? {
    foreach int i in 0...120 { // 120 because the cleaup transaction clears transactions after 120s
        log:printDebug(string`Time elapsed: ${i}s`);
        runtime:sleep(1);
    }
}
```

### Affected Version(s)

Tested on ballerina version 2201.9.0

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
@dsplayerX Please send the fix for 9.x branch as well

**Comment by dsplayerX** [comment]
> @dsplayerX Please send the fix for 9.x branch as well

https://github.com/ballerina-platform/ballerina-lang/pull/42963

**Comment by chiranSachintha** [comment]
Closed with https://github.com/ballerina-platform/module-ballerinai-transaction/pull/550
