### ISSUE TITLE
[Bug]: Annotation values with mapping values panic at runtime for const annotations

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#42933]
### Description

$title.

### Steps to Reproduce

```ballerina
public type AnnotationRecord record {|
    string summary?;
    Examples examples?;
|};

public type Examples record {|
    map<ExampleItem> response;
|};

public type ExampleItem record {
    map<string> headers?;
};

const annotation AnnotationRecord annot on type;

@annot {
    examples: {
        response: {}
    }
}
type Employee record {|
    int id;
    string name;
|};
```

```cmd
error: {ballerina/lang.map}InherentTypeViolation {"message":"invalid value for record field 'examples': expected value of type 'record {| readonly record {| |} & readonly response; |} & readonly', found 'Examples'"}
        at x:$annot_func$_0(demo.bal:16)
```

The value seems to be created as a mutable value.

Works when `Examples` is updated to be an immutable record (since the value is then created as an immutable value due to `Examples`' type).

```ballerina
public type Examples readonly & record {|
    map<ExampleItem> response;
|};
```

### Affected Version(s)

2201.9.1 and older versions

### Related area

-> Compilation

**Comment by chiranSachintha** [comment]
When creating the annotation value, we make it immutable by invoking `cloneReadonly`. The problem occurs when populating the initial values of the record.
In the above example, 
```
public type AnnotationRecord record {|
    string summary?;
    Examples examples?;
|};
```
When creating the `AnnotationRecord` value, we use the type of the field as `Examples`, and do a `istypecheck` with the type of the field. That is immutable.

We can fix this by making the field read-only as well.
```ballerina
public type AnnotationRecord record {|
    string summary?;
    Examples & readonly examples?;
|};

public type Examples record {|
    map<ExampleItem> response;
|};

public type ExampleItem record {
    map<string> headers?;
};

const annotation AnnotationRecord annot on type;

@annot {
    examples: {
        response: {}
    }
}
type Employee record {|
    int id;
    string name;
|};
```

**Comment by chiranSachintha** [comment]
As a workaround for this issue, we can define the `Examples` type as read-only.

**Comment by chiranSachintha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/42966
