### ISSUE TITLE
[Improvement]: Integrate object semtype into jBallerina type engine

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#42974]
### Description

This is to be done under 2 stages

- [x] https://github.com/ballerina-platform/ballerina-lang/issues/42972
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/42973 

### Related area

-> Compilation

**Comment by lochana-chathura** [comment]
Closing as both tasks are completed.
