### ISSUE TITLE
[Bug]: Getting a runtime error while invoking the client methods for a generated client

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#42988]
### Description

We have generated a client for Slack API using the Ballerina OpenAPI tool and when trying to invoke methods in the connector we are getting a runtime error.

### Steps to Reproduce

1. Publish the Slack client [1] to local ballerina central.  
2. Write a small test case using the Slack client.
    ```ballerina
    import ballerinax/slack;
    
    configurable string token = ?;
    public function main() returns error? {
        slack:Client slack = check new({ auth: {token} });
        var response = check slack->/users\.getPresence();
    }
    ```

3. Following error is thrown.
    ```sh
    error: No such method: $gen$Client&0046$get$users&0046getPresence
        at nivedhtith.test_function.0:main(main.bal:14)
    ```

[1] - https://github.com/adibmbrk/module-ballerinax-slack

### Affected Version(s)

Ballerina SL 2201.9.0

### Related area

-> Runtime

**Comment by HindujaB** [comment]
Seems like a bug from with https://github.com/ballerina-platform/ballerina-lang/pull/41885 changes.
