### ISSUE TITLE
[Question]: Service and Object have the same TypeTag

### ISSUE THREAD

**Issue by Shadow-Devil** [ballerina-platform/ballerina-lang#43034]
### Description

I don't know if this is a bug or intended, but it seems quite strange that both Object and Service have the same TypeTag. I think it was forgotten to add the +1 to the definition of the service tag.

Relevant code:
https://github.com/ballerina-platform/ballerina-lang/blob/74c7367c33644cb3464523349896622ac5221a5f/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/TypeTags.java#L60-L62

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Previously (pre-Swan Lake) objects and services used to be two separate things. However, with the current service design, services are just another kind of object, so the two being the same is intentional. 

We could probably get rid of the service tag altogether though.

**Comment by Shadow-Devil** [comment]
Thank you for clarifying it. I also added this change to remove the Service TypeTag in one of my PR where I found it. (#43035)

**Comment by ThisaruGuruge** [comment]
Removing the service type tag may break the existing library compiler plugins, and they need some time to fix them. Therefore, I'd suggest if we are to remove the service type tag, do it before the next update release and provide some time for library owners to move.
