### ISSUE TITLE
Add a sample with multiple packages to Ballerina by Examples

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#4304]
**Description:**
Need to add a Ballerina by Example which will show how to work with multiple packages.

**Steps to reproduce:**
N/A

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by afkham** [comment]
Guides & BBE will cover this
