### ISSUE TITLE
[Improvement]:  Support accessing resources in a ballerina package

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#43041]
### Description

There are three types of resources supported in packages.

- The resources added at `<package_root>/resources`
- The resources exported by dependencies
- The resources added by compiler plugins(code analyzers) after compilation to generated resources path

With this improvement, users can access these resources using the Java `classLoader:getResourceAsStream` API at runtime by providing the resource path as `resources/<resource_name>`.

### Describe your problem(s)

- The current approach for user provided resources and resources exported from dependencies -  these resources are added within a module specific path which is not intuitive

- The resources generated from compiler plugins to the final executable -  these resources get added with a user package specific path. So, accessing the resource is not possible without knowing the user package within which the resource gets added

### Describe your solution(s)

- Resources will be bound to the package, not to specific modules

- The existing resource APIs at module level will be deprecated with U10 and will be removed with U11

- During code generation phase, 

    The resources of the package
    The resources from dependencies
    The resources added by compiler plugins to the generated resources path(`target/resources`) 

will get packed to a resources.jar and cached in the compilation cache at `target/cache/`

- During build and run, the above resources.jar will be added to the executable
- During test, the resources.jar will be available in the test execution class path
- The pack command will add the following resources to the `<bala_root>/resources` directory in the BALA file
        The resources of the package
        The resources added by compiler plugins to the generated resources path

- When loading resources from the dependencies, first the resources are checked at `resources/` path, if not the resources are checked at `modules/<mod_nam>/resources` to ensure backward compatibility

- Priority order for resources - resource addition will start with the leaf nodes of the dependency tree and highest priority to package-provided resources

- Conflict resolution for resources
    Issues a warning when replacing a resource
    Issues an error and fails if the compiler plugins are trying to add a resource with the same name as a package provided resource

 
### Related area

-> Other Area

**Comment by LakshanWeerasinghe** [comment]
@Dilhasha why aren't we providing a way to access resources through a Ballerina API?

**Comment by azinneera** [comment]
> @Dilhasha why aren't we providing a way to access resources through a Ballerina API?

@LakshanWeerasinghe that's in the roadmap. That is the next step of it. IMO, we can provide it in a standard library package.
