### ISSUE TITLE
[HTTP] Interceptors for requests/responses coming in to/going out of resources

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4305]
**Description:**
Currently, there is no way to intercept the message coming into or going out of a resource and perform some additional processing on those.

**Comment by hasithaa** [comment]
Related to https://github.com/ballerinalang/ballerina/issues/4074

**Comment by riyafa** [comment]
Currently this is supported as Ballerina http filters. Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/9009
