### ISSUE TITLE
[New Feature]: Add new runtime API to `invokeMethodAsync` with a classloader

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#43055]
### Description

$subject

### Describe your problem(s)
https://github.com/ballerina-platform/ballerina-lang/issues/42729#issuecomment-2188484013

_No response_

### Related area

-> Runtime

### Related issue(s) (optional)

https://github.com/ballerina-platform/ballerina-lang/issues/42729

**Comment by HindujaB** [comment]
As per the latest discussion with @warunalakshitha, @gayaldassanayake, and @azinneera, the following were discussed.
- There will be a classloader mismatch when the API is called from the System classloader as the expected method is called from the provided custom classloader. 
- We can resolve this if it is ensured the API call and the ballerina classes are loaded from the same classloader
- To achieve this, it is suggested to use a new Java module that calls the runtime APIs and pack the module where the created pack is invoked using Java reflections. 

I locally tested and verified a similar scenario, where the custom classloader includes all the `ballerina-rt.jar`, the new module that calls runtime APIs, and the compiled jar (thick jar) files.
@gayaldassanayake Can you check this and let us know any concerns?

**Comment by gayaldassanayake** [comment]
> @gayaldassanayake Can you check this and let us know any concerns?

Currently working on this. Will attempt this and raise any concerns.

**Comment by gayaldassanayake** [comment]
> I locally tested and verified a similar scenario, where the custom classloader includes all the `ballerina-rt.jar`, the new module that calls runtime APIs, and the compiled jar (thick jar) files. @gayaldassanayake Can you check this and let us know any concerns?

Got this to work with the help of @HindujaB. I will raise concerns if/when I get them. Thanks

**Comment by HindujaB** [comment]
Closing the issue as the provided suggestion is working for the use case. 
The remaining similar cases will be addressed in this issue - https://github.com/ballerina-platform/ballerina-lang/issues/43171.
Please feel free to reopen if there's any concern.
