### ISSUE TITLE
[Task]:  Remove dependency of `mime4j` 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#43098]
### Description

$subject

### Describe your task(s)

This is to solve the security vulnerability https://github.com/advisories/GHSA-jw7r-rxff-gv24 that is not resolved with axiom version `1.4.0`. Since there are no latest versions with the security fix, we need to find and test alternative ways to have `axiom-api` operations. 
Currently, some implementations of the runtime APIs in `BXml` classes are using the `axiom-api` package. Therefore thorough testing is also needed before switching the packages. 

### Related area

-> Runtime

**Comment by Shadow-Devil** [comment]
I also created an issue in their Jira a while ago to update the vulnerable dependency but until now there was no interaction from their side. See here the issue: https://issues.apache.org/jira/projects/AXIOM/issues/AXIOM-521
