### ISSUE TITLE
[Bug]: Invalid output in `toString` function for nested array 

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#43113]
### Description

Please consider following code

```
import ballerina/io;

anydata[] arr = [];

public function main() {
    arr.push(arr);
    io:println(arr);  // prints [...], This is unclear for user
}
```

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
This is not a bug, comes from the spec - https://ballerina.io/spec/lang/master/#ToString

Please create an issue if you have a suggestion for a better alternative. 

I think this is OK, and at some point we would expect users to be aware of what specific representations mean.
