### ISSUE TITLE
Implement static rules for language static code analyzer

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#43123]
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/43142
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/43143
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/43144

**Comment by SasinduDilshara** [comment]
As the first task I read the all spotbugs rules define for the Java and select appropriate rules for Ballerina

**Comment by SasinduDilshara** [comment]
As the second task I read the all sonar cloud rules define for the Java and select appropriate rules for Ballerina

**Comment by SasinduDilshara** [comment]
Created the static rules documents and currently it is on the review process.
https://docs.google.com/document/d/117SJltpBJU4lb5hzhTZQe2rTOig_5O97tqetRzHeyU8/edit?usp=sharing

**Comment by SasinduDilshara** [comment]
The implementation details of this issue will be track in here
https://github.com/ballerina-platform/ballerina-lang/issues/43144
