### ISSUE TITLE
[Bug]: The `Run` code lens does not work for services

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#43130]
### Description

$title only appears in versions after 2201.9.2. The code lens works as expected in versions 2201.8.6 and 2201.9.1. Additionally, it works as expected on Windows OS.

### Steps to Reproduce

1. Create a new Ballerina project using the service template `bal new -t service`.
2. Start the service using the `Run` code lens.

### Affected Version(s)

2201.9.2 onwards

### OS, DB, other environment details and versions

OS: macOS 14.5 23F79
JDK: openjdk 17.0.8 2023-07-18

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment]
This is now fixed with the vs-code `v4.7.3` release. 

Uploading Screen Recording 2024-07-19 at 10.48.04.mov…

**Comment by LakshanWeerasinghe** [comment]
@Dilhasha can we close this?

**Comment by Dilhasha** [comment]
Fixed with https://github.com/wso2-enterprise/vscode-extensions/pull/3371
Hence closing.
