### ISSUE TITLE
[Bug]: Object Mocking failed when there is a private field type different

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#43156]
### Description

When we have private fields in the Mock object which is not correctly mapped with the field types of the original object, mocking fails giving the following error,

```
error: incompatible field type 'int' provided for field name
        at ballerina.test.0:mock(mock.bal:309)
           danesh.object_mocking$test.0.tests.init-tests:getMockClient(tests/init-tests.bal:5)
```

Do we need to validate private fields when we do object mocking?

### Steps to Reproduce

You can reproduce the issue with the following source code

Source code

```ballerina
import ballerina/io;

Foo f = initialize();

public function initialize() returns Foo {
    return new Foo();
}

public class Foo {

    private string name;
    public function foo() {
        io:println("Hello, Foo!");
    }
    
}

public class Bar {

    private int name;
    public function foo() {
        io:println("Hello, Bar!");
    }

}

public function main() {
    io:println("Hello, World!");
}
```

Test code

```
import ballerina/test;

@test:Mock {functionName: "initialize"}
isolated function getMockClient() returns Foo {
    return test:mock(Foo, new Bar());
}
```

### Affected Version(s)

Latest Ballerina versions

### Related area

--> Testerina

**Comment by Dilhasha** [comment]
> Can we get this fixed with update 10 please, as it is blocking the feature [ballerina-platform/ballerina-library#5840](https://github.com/ballerina-platform/ballerina-library/issues/5840)

Ack.
