### ISSUE TITLE
[Bug]: Annotation Values for Resource Method Types are not Present in the Runtime

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#43162]
### Description

When the `getAnnotation()` or `getAnnotations()` method is called on the `ResourceMethodType` value, the annotations are not present even though the annotations are added in the Ballerina code. 

### Steps to Reproduce

Consider the following Ballerina code:

```ballerina
import ballerina/graphql;

@graphql:ServiceConfig {
    cacheConfig: {}
}
service on new graphql:Listener(9090) {

    @graphql:ResourceConfig {
        cacheConfig: {
            maxAge: 60
        }
    }
    resource function get greeting() returns string {
        return "Hello, World!";
    }

    resource function get profile(string name) returns Profile {
        return new(name);
    }
}

public isolated distinct service class Profile {
    private final string name;

    public isolated function init(string name) {
        [self.name](http://self.name/) = name;
    }

    @graphql:ResourceConfig {
        cacheConfig: {
            maxAge: 60
        }
    }
    isolated resource function get name() returns string => [self.name](http://self.name/);
}
```

We pass the `BObject` value of the GraphQL service object to the native code when the service is attached to the listener. In the native code, the annotations for the `greeting` resource are there. 

Then we iterate through the `ResourceMethodType` values of the service object, and when try to access the annotations of the resource methods of the `Profile` type, the `getAnnotations` API returns null, even though the `get name()` resource does have an annotation. This is a blocker for https://github.com/ballerina-platform/ballerina-library/issues/6722 where the annotation values cannot be accessed so the complexity values are incorrect.

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
May be the same issue as https://github.com/ballerina-platform/ballerina-lang/issues/43122, for which there is already a PR https://github.com/ballerina-platform/ballerina-lang/pull/43121.

I'll also check, but FYI @HindujaB.

**Comment by MaryamZi** [comment]
Seems like it is not the type reference issue. But could be https://github.com/ballerina-platform/ballerina-lang/issues/33594, https://github.com/ballerina-platform/ballerina-lang/issues/42906#issuecomment-2227344070 (as Hinduja is also checking), if access is in the `attach` method.

Can we consider accessing at a method like `start` if this is the case?

**Comment by ThisaruGuruge** [comment]
Moving to the start method solved the issue, but we need a proper fix. But considering the time constraints, we are going ahead with this fix.

**Comment by HindujaB** [comment]
As we have an issue [1] that follows up with original cause and the provided workaround is working, I am closing the issue. Please feels free to reopen if there's any concern.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/33594
