### ISSUE TITLE
[Task]: Replace reflection based runtime calls with runtime `invoke` API

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#43171]
### Description

$subject

### Describe your task(s)

Currently, the following modules use reflections to start ballerina runtime. We can replace the with runtime APIs.
- ballerina-shell
- debug-adapter-runtime
- ballerina-test-utils

### Related area

-> Runtime

**Comment by warunalakshitha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/43389
