### ISSUE TITLE
Improve error reporting in Ballerina

### ISSUE THREAD

**Issue by lasinducharith** [ballerina-platform/ballerina-lang#4318]
Following are some errors which Ballerina/Intellij Idea is reporting against any compile-time or runtime issues. 

[1] error: fail to compile file: null
[2] error: fail to compile file: index: 121, Size: 121
[3] ballerina: 1

These errors are not descriptive enough to pin-point an issue.
More details can be found in ballerina-dev.
https://groups.google.com/forum/#!topic/ballerina-dev/60MpRiYeI2Y

**Comment by Shan1024** [comment]
@anupama-pathirage - These are not related to IDEA plugin. These should be improved in the language. So I think it is better to update the label.

**Comment by hasithaa** [comment]
This error reporting is handled with 0.970.0 release. ( with Bad-Sad error). Hence closing this issue.
