### ISSUE TITLE
[New Feature]: Allow type inclusion of readonly records

### ISSUE THREAD

**Issue by Shadow-Devil** [ballerina-platform/ballerina-lang#43198]
### Description

Currently, the following is not allowed:
```ballerina
type A record {
    string a;
} & readonly;

type B record {
    *A;
} & readonly;
```
The following compiletime error is thrown:
```
incompatible types: 'A' is not a record(BCE2091)
```

It would be great to allow type inclusion of records that are also readonly.

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
We plan on allowing this as suggested in https://github.com/ballerina-platform/ballerina-spec/issues/1224.

**Comment by MaryamZi** [comment]
Closing this issue since the corresponding spec issue is still open. We will introduce changes to the implementation once the spec change is done.
