### ISSUE TITLE
[Bug]: Static resources are not included in the native image when build via a single file

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#43277]
### Description

The resources generated in the `target/resources` directory are not included in the GraalVM native image which is built for a single ballerina file. This works for a ballerina project.

In addition to that, when we built a native image manually using the JAR file and `native-image` command. That also failed to include the resources. As a workaround we need to manually add them. But since the resources are generated by the ballerina libraries, it should be included by default.

### Steps to Reproduce

Check static resource generation for single file

### Affected Version(s)

Ballerina SwanLake Update 10(2201.10.x)

### Related area

-> Runtime

**Comment by Dilhasha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/43276
