### ISSUE TITLE
[Bug]: Unable to detect invalid variables

### ISSUE THREAD

**Issue by sahandilshan** [ballerina-platform/ballerina-lang#43299]
### Description

Error output given by the compiler is not relevant or is sometimes very confusing. Most of the time the compiler cannot identify the correct issue. At that time it gives an error message that is completely misleading to the user. As an example in the code snippet below, the problem is that there's no variable called `aiOauthApp.clientId,`. It is supposed to show that the variable is not defined or has a similar error message. Instead, it gives a misconfusion error message to the user.

![Screenshot 2024-08-18 at 7 16 06 PM](https://github.com/user-attachments/assets/0c2ad662-f2f4-4462-83e3-abd1d5f0bbf9)

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
Don't you get both errors when you compile the code?

Trying with

```ballerina
import ballerina/http;

public function main() returns error? {
    http:Client cl  = check new ("");

    // a type compatible with mapping constructor expressions not found in type 'ballerina/http:2.11.3:RequestMessage'
    // undefined symbol 'app'
    string _ = check cl->post("", {id: app.id});

    record {} app = {};
    // a type compatible with mapping constructor expressions not found in type 'ballerina/http:2.11.3:RequestMessage'
    // invalid field access: 'id' is not a required field in record 'record {| anydata...; |}', use member access to access a field that may have been specified as a rest field
    string _ = check cl->post("", {id: app.id});
}
```

seeing

```cmd
ERROR [demo.bal:(8:35,8:47)] a type compatible with mapping constructor expressions not found in type 'ballerina/http:2.11.3:RequestMessage'
ERROR [demo.bal:(8:40,8:43)] undefined symbol 'app'
ERROR [demo.bal:(13:35,13:47)] a type compatible with mapping constructor expressions not found in type 'ballerina/http:2.11.3:RequestMessage'
ERROR [demo.bal:(13:40,13:46)] invalid field access: 'id' is not a required field in record 'record {| anydata...; |}', use member access to access a field that may have been specified as a rest field
```

If you're not seeing all relevant errors, please share the relevant code snippet.

Note that the errors shown on VS Code depend on where you hover. For example, `undefined symbol 'app'` is only relevant from 8:40 to 8:43, so that error will be shown only when you hover there.

![Screenshot from 2024-08-20 11-02-48](https://github.com/user-attachments/assets/cb6d2322-a63d-4917-a48f-588021ed2b36)

The total number of errors at the top of the file also indicate that there's more than one error.

**Comment by MaryamZi** [comment]
The "a type compatible with mapping constructor expressions not found in type 'ballerina/http:2.11.3:RequestMessage'" error is logged because the `RequestMessage` type is defined a union type against which we need to identify compatibility. 

```ballerina
public type RequestMessage anydata|Request|mime:Entity[]|stream<byte[], io:Error?>;
```

**Comment by MaryamZi** [comment]
We would appreciate it if you could create issues (or a single issue listing multiple problems) for the other compile-time errors that may be unclear.

**Comment by sahandilshan** [comment]
`Don't you get both errors when you compile the code?`
Hi @MaryamZi. Just checked and as the 2nd error, it shows the undefined variable error. From the developer's point of view, I guess that error should be the one that should get prioritized over the other one.

`We would appreciate it if you could create issues (or a single issue listing multiple problems) for the other compile-time errors that may be unclear.`
Will create issues for unclear error messages.

**Comment by MaryamZi** [comment]
The diagnostics are ordered by position, so that they generally can be addressed in the natural order.

**Comment by MaryamZi** [comment]
Closing this issue since the relevant error is present. Please feel free to open issues for any unclear errors you come across.
