### ISSUE TITLE
[Bug]: Ballerina Notebook not working with 2201.10.0

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#43345]
### Description

The following error occurred while attempting to run a Ballerina Notebook in 2201.10.0.

```
Incompatible ballerina version 
```

### Affected Version(s)

2201.10.0

### OS, DB, other environment details and versions

Windows

### Related area

-> Editor

**Comment by tharindulak** [comment]
This issue is fixed in VSCode 4.7.6. Please reopen if the issue is still there.
