### ISSUE TITLE
Doc generation does not produce API docs 

### ISSUE THREAD

**Issue by suganyasuven** [ballerina-platform/ballerina-lang#43505]
**Description:**
$title

It is failed to create the API docs json file for the following bala file
https://fileserver.central.ballerina.io/2.0/ballerinax/choreo/0.4.1/ballerinax-choreo-java11-0.4.1.bala
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaMadhushan** [comment]
This issue is no longer valid. Therefore closing the issue
