### ISSUE TITLE
Type System Re-Structure

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#4356]
Make "any" type to the top of the type system, so functions/services/connectors also can be assigned to any. Also, we need an "isassignable" concept for types to check if one variable can be assigned to another given one, e.g. structurally equivalent.

Three types of variables, value types, mutable reference types and immutable reference types.

**Comment by uthaiyashankar** [comment]
Can we resolve this now?

**Comment by hasithaa** [comment]
This is added, But individual types have issues and captured them as separate issues. Hence closing this issue.
