### ISSUE TITLE
[Improvement]: Migrate cloud artifacts to Java 21

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#43570]
### Description

The cloud artifacts need to be migrate to Java 21 for the release of Ballerina update 11. 
These artifacts include:

- [x] Ballerina base image
- [x] Ballerina JDK base image
- [x] Ballerina Github action
- [x] Ballerina performance tests workflows
- [x] Ballerina GraalVM base images
- [ ] Azure functions base
- [ ] Aws layers

### Related area

-> Standard Library

**Comment by HindujaB** [comment]
This task is done except for the `azure.functions` and `aws.lambda` module migration. They will be tracked in the library migration task. 
Hence, closing this issue.
