### ISSUE TITLE
Complete annotations support in Ballerina

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#4358]
**Description:**
At the moment, annotations can be attached to structs, functions, services, connectors. But the Ballerina grammar allows your annotation even package level variables, function parameters, return values etc. Ballerina compiler simply ignores these annotations at the moment.

**Comment by hasithaa** [comment]
@MaryamZi Please verify this. I think we can close this issue now.

**Comment by MaryamZi** [comment]
> @MaryamZi Please verify this. I think we can close this issue now.

Yes, these are not ignored now.

Will close this issue since the pending tasks with the new annotation syntax are being tracked in https://github.com/ballerina-platform/ballerina-lang/issues/14352.
