### ISSUE TITLE
[Bug]: Incorrect handling of reserved keyword in Ballerina data mapping generation.

### ISSUE THREAD

**Issue by VellummyilumVinoth** [ballerina-platform/ballerina-lang#43620]
### Description

When generating data mappings in Ballerina, the `version` field is incorrectly treated as a reserved keyword. Instead of generating the mapping as `version: patient.version`, the system produces an incorrect mapping like `'version: patient.'version`, which is syntactically invalid. This causes the code to fail during execution or compilation.

#### 1. Define Ballerina code
```
public function mapPatientToUsCore(Patient patient) returns Patient => {
   
};

public type Patient record {
    string patientType;
    string patientId;
    string version;
};
```
#### 3. Observe that the generated mapping incorrectly escapes the version field as `'version: patient.'version` instead of the correct format `version: patient.version`.

```
public function mapPatientToUsCore(Patient patient) returns Patient => {
    patientType: patient.patientType,
    patientId: patient.patientId,
    'version: patient.'version
};
```

### Related area

-> Compilation

**Comment by MaryamZi** [comment]
`version` used to be a keyword, adding the quote may be related to that. 

But, it shouldn't fail and doesn't seem to fail for me either. Where/how does it fail?

**Comment by VellummyilumVinoth** [comment]
Thanks Ack.

This is AI data mapper bug. We will fix it.

**Comment by VellummyilumVinoth** [comment]
Reason/Other
