### ISSUE TITLE
[Bug]: The `cannot complete future twice error` does not have any information such as stack trace

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#43654]
### Description

Related to this issue: https://github.com/wso2-enterprise/internal-support-ballerina/issues/837

An error: `cannot complete the same future twice.` is thrown from the lang without any logs where the error is originated. Since it is a panic behaviour, we expects more information.

### Steps to Reproduce

Could not able to reproduce the issue

### Affected Version(s)

Ballerina Swan Lake Update 7

### Related area

-> Runtime

**Comment by warunalakshitha** [comment]
Runtime actually throw a ballerina error if same future called twice, but it seems http or any other package seems not catch properly. We have fixed this issue in update 11 with new concurrency model (Now API user cant complete same future twice via API), but there are some implementation implications to fix in previous versions.
