### ISSUE TITLE
Ballerina run depends on the current directory

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#4368]
Providing bal file location in an absolute way doesn't work. You have to `cd` into the directory and then run from there.

Following doesn't work
```bash
 ~ $ ballerina run ~/Desktop/MyProj/foo/bar
```
But following works
```bash
 ~/Desktop/MyProj $ ballerina run foo/bar
```
If you look at `javac` both works.

**Comment by uthaiyashankar** [comment]
This is working now. Should have been fixed in the recent changes.
