### ISSUE TITLE
Change caching implementation

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#4377]
**Description:**
Caching implementation needs to be changed so that it behaves like a map (element adding, retrieving, etc).

**Steps to reproduce:**
N/A

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by afkham** [comment]
Will not implement
