### ISSUE TITLE
Running a service flag should come before the run

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#4381]
Following shouldn't work.
`ballerina run helloworld.bal -s`

Following should continue work.
`ballerina run -s helloworld.bal`

**Comment by MaryamZi** [comment]
Closing this issue since the `-s` flag is no longer relevant and enforcing an ordering for flags (CLI params in general) is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/5286.
