### ISSUE TITLE
[Math] Add support for high precision numbers

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4385]
**Description:**
Need to add support for high precision numbers in Ballerina, since the precision of provided number types (int and float) may not be sufficient for some use cases (i.e: finance use cases).

**Suggested Labels (optional):**
Type/Feature

**Comment by pranavan15** [comment]
This requirement is met via the introduction of the `decimal` type. `decimal` type is a basic, simple type in Ballerina, which corresponds to the IEEE 754-2008 128-bit decimal (radix 10) floating point number format. This resolves the floating point precision error problem as well. Please find more details in PR https://github.com/ballerina-platform/ballerina-lang/pull/11034.

**Comment by MaryamZi** [comment]
Closing this issue since this requirement is now supported.
