### ISSUE TITLE
Add proper support for localization

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4390]
**Suggested Labels (optional):**
Type/Feature

**Comment by wggihan** [comment]
@pubudu91 Can you be more specific regarding this request?

**Comment by pubudu91** [comment]
I meant adding support for locale-specific formatting. Like how Java provides this through its `Locale` class. This would be part of the i18n work I guess.

**Comment by wggihan** [comment]
@pubudu91 Understood. I think this should come from language itself rather than a StdLib library, hence changing the label to Area/Language.

**Comment by hasithaa** [comment]
Related Spec issue https://github.com/ballerina-platform/ballerina-spec/issues/41

**Comment by hasithaa** [comment]
@pubudu91 Closing this issue for the inactivity. If you think is this valid, Could you please create this in https://github.com/ballerina-platform/ballerina-spec/ with more details.
