### ISSUE TITLE
Inconsistent behaviour with Workers and no return function.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#4394]
**Description:**
Consider following two programs, where Function `foo` is implemented without worker and with worker construct. Technically both should be equivalent to each other as the first one is a syntactic shortcut for defining a function with a single worker. Hence Both should execute in the same way. 

Without workers.
```ballerina
function main(string[] args){
    println("before foo");
    foo();
    println("after foo");
}

function foo(){
    sleep(1000);
    println("foo");
}

// output
//before foo
//foo
//after foo
```

With Workers.
```ballerina
function main(string[] args){
    println("before foo");
    foo();
    println("after foo");
}

function foo() {
    worker w1 {
        sleep(1000);
        println("foo");
    }
}

// output
//before foo
//after foo
//foo

```
**Steps to reproduce:**

Execute above programs. 

**Affected Versions:**
0.95.6

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by lafernando** [comment]
This is now fixed.
