### ISSUE TITLE
Writing a literal string[] to the record IO channel results in an array index out of range error.

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#4397]
**Description:**
Writing a literal string[] to the record IO channel results in an array index out of range error.

**Steps to reproduce:**
Running the following code sample will reproduce the error.

import ballerina.file;
import ballerina.io;

function main (string[] args) {
    io:TextRecordChannel prRecordChannel = getFileRecordChannel("/Users/azeez/Downloads/PR.csv", "w", "UTF-8", "\n", ",");

    string[] fooRecord = ["abc", "def", "eee"];
    prRecordChannel.writeTextRecord(fooRecord);
}

function getFileRecordChannel (string filePath, string permission, string encoding,
                               string rs, string fs) (io:TextRecordChannel) {
    file:File src = {path:filePath};
    io:ByteChannel channel = src.openChannel(permission);
    io:CharacterChannel characterChannel = channel.toCharacterChannel(encoding);
    io:TextRecordChannel textRecordChannel = characterChannel.toTextRecordChannel(rs, fs);
    return textRecordChannel;
}

**Suggested Labels:**
type/bug

**Suggested Assignees:**
pamod

**Comment by arukshani** [comment]
Fixed in #4398
