### ISSUE TITLE
[HTTP] Make certPassword an optional configuration when configuring HTTPS

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4405]
**Description:**
Currently, if using HTTPS, the user is required to configure the `certPassword`. If it is not set, an exception is thrown and the program terminates. In the HTTP transport, if the user hasn't provided `certPassword`, it automatically takes the store password as the `certPassword`. We have to reflect the same behaviour in Ballerina side as well, and make `certPassword` optional. 

**Suggested Labels (optional):**
Type/Improvement

**Suggested Assignees (optional):**
Myself

**Comment by Bhashinee** [comment]
Fixed from  : https://github.com/ballerina-platform/ballerina-lang/pull/5347

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing this issue.
