### ISSUE TITLE
Rename readTextRecord() and introduce more native functions to record-io

### ISSUE THREAD

**Issue by lasinducharith** [ballerina-platform/ballerina-lang#4431]
- Rename readTextRecord() in [1] to nextTextRecord(), so that it is intuitive that above method is/can be used to read the next text record in a file. 
- Provide native ballerina functions to read a given record, read a set of record etc.

[1] https://ballerinalang.org/docs/by-example/record-i-o

**Comment by riyafa** [comment]
Now record/io implementation is completely different: https://ballerina.io/learn/by-example/record-io.html
This issue is no longer valid.
