### ISSUE TITLE
Provide detailed examples for the use of record-io

### ISSUE THREAD

**Issue by lasinducharith** [ballerina-platform/ballerina-lang#4432]
Include an example/part of example to demonstrate how a set of text records, or a given text record(ex: 5th record) can be retrieved from a file and write to a file. Related to https://github.com/ballerinalang/ballerina/issues/4431

[1] https://ballerinalang.org/docs/by-example/record-i-o

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-examples/issues/806 to track this
