### ISSUE TITLE
Read only fields for Structs

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#4437]
**Description:**
Have something like this. 
```ballerina
struct Foo {
readonly string name;
}
```

Idea is to have a field which is read-only from outside of the package. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by afkham** [comment]
Done
