### ISSUE TITLE
Ballerina user repository cannot be used with runtime distribution

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#4438]
**Description:**
Packages in Ballerina user repository are marked as unknown packages when we use Ballerina runtime distribution. 

**Steps to reproduce:**
Add few packages from user repository and run the Ballerina program.

**Affected Versions:**
0.95.7

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced with ballerina 0.974.1-SNAPSHOT pack, hence closing this issue.
