### ISSUE TITLE
Cannot assign special characters for strings 

### ISSUE THREAD

**Issue by sajithaliyanage** [ballerina-platform/ballerina-lang#4458]
**Description:**
Can't assign strings including special character '\\' for string data type. Error code is given below.
`function main (string[] args) {`
`      string varibale = "%w[{s#5)\PyR";`
 `     println(varibale);`
`}`

It gives an error  - **token recognition error at: '"%w[{s#5)\P'**

when I escape the character '\\' it works. code like
`string varibale = "%w[{s#5)\\PyR";`

**Suggested Labels (optional):**
Type/Bug

**Comment by pubudu91** [comment]
Isn't this the expected behaviour? Even in Java, the '\' character is used for escaping. If your intention is to include the '\' character in a string, then you should escape it.

**Comment by hasithaa** [comment]
As @pubudu91 mentioned, this is the expected behavior. Hence closing the issue.
