### ISSUE TITLE
Setting --sourceroot doesn't work

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#4466]
**Description:**
--sourceroot argument includes the path to the directory containing source files and packages.

**Steps to reproduce:**
Location of bal file is a.b.c.d
Package - c.d
Run code from - a
Cmd - 
```
/a$ ballerina run c/d --sourceroot b/
```

**Affected Versions:**
0.95.6

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/4640 , hence closing this issue.
