### ISSUE TITLE
Disallow converting a map with missing fields, to struct.

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#4496]
**Description:**
Below sample works without any runtime errors. However the conversion should fail if the map does not contain some field that exists in the struct.
```ballerina
struct Employee {
    string name;
    int birthYear;
}

function main (string[] args) {
    map m = {abc: 1992, name: "Bob"};
    var emp, e = <Employee> m;
    println(e);
    println(emp);
}
```
**Affected Versions:**
0.95.8

**Comment by hasithaa** [comment]
From 0.980.0 language specification, cast conversation support is removed. This scenario is no longer valid. use the match statement to do the conversion.
