### ISSUE TITLE
getType().getTag() of an array in a ballerina map gives value for 'any' type and not 'BRefValueArray' type.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#4505]
**Description:**
```
map m1 = {line1:"No. 20", line2:"Palm Grove", city:"Colombo 03", country:"Sri Lanka", checkinsTimes: [900, 2230]};
```
The type of the 'checkinsTimes' array is a 'BRefValueArray'. But getting the type tag number of the array, it gives as 'BAnyType' type(value as 6). The value should ideally be 16.

**Steps to reproduce:**
Compile the following:  
```
map m1 = {line1:"No. 20", line2:"Palm Grove", city:"Colombo 03", country:"Sri Lanka", checkinsTimes: [900, 2230]};
```
**Affected Versions:**
Last commit: 96c16488014db5f594dcd2a5545f4aa8d62173d6

**OS, DB, other environment details and versions:**
Mac OS, MVN: 3.5.0

![screen shot 2018-01-30 at 11 02 18 am](https://user-images.githubusercontent.com/4398820/35550765-e8cd73da-05b1-11e8-9dbc-f333df6d959f.png)

**Comment by pubudu91** [comment]
I tried to compile the above snippet. Got the following compile error: `invalid usage of array literal with type 'any'`

@hemikak Is this issue valid anymore?

**Comment by hasithaa** [comment]
@pubudu91 This is restricted in Ballerina now. We can close this issue.
