### ISSUE TITLE
composer going to split view mode when saving new file from source view

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-lang#4521]
**Description:**
Composer is putting me back into splitview when I save a new file from source view

**Steps to reproduce:**
- create new file
- go to source view and edit
- save
- now UI has gone back to splitview

**Affected Versions:**
0.96 at least

**Comment by NipunaMarcus** [comment]
This issue has been fixed in the composer 0.973.0 hence closing this issue.
