### ISSUE TITLE
Incorrect precision when adding floats

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4525]
**Description:**

I have the following Bal program.

```
package my_prog;

function main (string[] args) {
    println(addF(1.1, 2.2));
}
 
function addF (float a, float b)(float) {
    return a + b;
}
```

Executing the above results below.

```
Running sample.bal
3.3000000000000003
Execution Ended.
```

**Affected Versions:**
0.9.6

**Comment by lafernando** [comment]
This is expected, due to the binary representation of floating point values in the CPU. You can't get perfect decimal point values always.
