### ISSUE TITLE
Java error in Ballerina, and introducing an error for reaching XML entity expansion limit

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#4533]
**Description:**
When XML entity expansion limit is reached following error occurs, which exposed Java error in Ballerina. 

```
error: error, message: failed to get xml as string: ParseError at [row,col]:[1,1]
Message: JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
	at .:main(/home/ayoma/git/BallerinaTests/XmlTests/XmlEntityExpansion.bal:16)
```

It is required to define a Ballerina level error that is returned when entity expansion limit is hit. This is a common XML attack pattern. Hence, users might want to take some defensive action when this error occurs too often. 

**Related Issues (optional):**
#4540

**Steps to reproduce:**
Run example code [1]
[1] https://github.com/ayomawdb/BallerinaTests/blob/master/XmlTests/XmlEntityExpansion.bal

**Suggested Labels (optional):**
 Type/Improvement  Severity/Major  Priority/Highest

**Comment by hasithaa** [comment]
@Kishanthan @ayomawdb @SupunS , With JBallerina I think we can't hide the fact that we are using Java. IMO, we can expose this error at run-time. 

WDYT?

**Comment by Kishanthan** [comment]
> @Kishanthan @ayomawdb @SupunS , With JBallerina I think we can't hide the fact that we are using Java. IMO, we can expose this error at run-time.
> 
> WDYT?

Yes, these errors will be exposed to user as we are using java underneath.
