### ISSUE TITLE
getType().getTag() of a BJSON gives the value of a String

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#4539]
**Description:**
```
json jString1 = "Apple";
```

The above value is a BJSON. But the type tag value is 3. Which is String.

**Steps to reproduce:**
Run the below code:
```
json jString1 = "Apple";
```

**Affected Versions:**
Commit: be9447833a769664f2f1e323e5eabd28b885584e

**OS, DB, other environment details and versions:**
Mac OS

![screen shot 2018-02-05 at 11 06 14 am](https://user-images.githubusercontent.com/4398820/35789791-9f1af854-0a64-11e8-8f34-99677cdd9103.png)

**Comment by SupunS** [comment]
This is intentional. The type tag represents the type of the BJSON at runtime (string/int/boolean/etc). Checking 'instanceof' is the way to go.

**Comment by SupunS** [comment]
Closing the issue, since this is the correct behavior.
