### ISSUE TITLE
XML parsing inconsistency between "Runtime Only" and "Tools + Runtime" distributions

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#4540]
**Description:**
There are inconsistencies in XML parsing with "Runtime Only" and "Tools + Runtime" distributions (see "Steps to reproduce").

Additionally, identified that the "Ballerina Tests" is also working similar to "Ballerina Tools + Runtime Distribution" behavior (and test cases are written assuming everything is tested against "Ballerina Tools + Runtime Distribution"). 

_Note: I could get the "Ballerina Tests" to work similar to  "Ballerina Runtime Only" distribution by making the change highlighted in https://github.com/ayomawdb/ballerina/commit/649bccb86cbb2559a3f78cfa7f3fbb78a4038801._ 

**Steps to reproduce:**
$subject can be reproduced by using below code: 
```
public function main (string[] args) {
    var xmlData,_ = <xml>"<foo/>";
    println(xmlData);
}
```

Result generated by Ballerina Tools + Runtime : 

`<foo/>`

Result generated by Ballerina Runtime Only

`<foo></foo>`

There are other differences in terms of XML parser security, such as:

- Entity expansion limit
   - Ballerina Runtime Only: 64,000
   - Ballerina Tools Distribution: unknown error occurred
- External entity inclusion:
   - Ballerina Runtime Only : allowed
   - Ballerina Tools Distribution: disallowed

**Related Issues (optional):**
#4533 

**Suggested Labels (optional):**
 Type/Bug  Severity/Major  Priority/Highest

**Comment by SupunS** [comment]
Tested with 0.974.0, now both the distributions return the same output. 
Entity expansion errors are also identical.
Hence closing this issue.
