### ISSUE TITLE
Rename Constants classes

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#4558]
**Description:**
There are several classes named `Constants` that cause confusion and hence should be renamed accordingly.

**Comment by riyafa** [comment]
The HTTP and WebSocket constants classes have been renamed appropriately in https://github.com/ballerina-platform/ballerina-lang/pull/4613

**Comment by anupama-pathirage** [comment]
This is originally requested in https://github.com/ballerina-platform/ballerina-lang/pull/4548#discussion_r166199220 and needs to be done for the entire code base.

**Comment by SupunS** [comment]
jballerina runtime has proper class names for all the constant classes. Hence removing the JBallerina tag :)

**Comment by prabushi** [comment]
There are no 'Constants' named classes related to the VSCode plugin code. Hence, removed the label.

**Comment by hasithaa** [comment]
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.
