### ISSUE TITLE
Position of enum node has minus values as end line and end column.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#4582]
**Description:**
When retrieving position from enum node available under <package_node>.enums[] values available for the end line and end column values are below 0 (-1).  This affect go to definition functionality when try to find the definition of an enum. 

```Ballerina
package balproject.pkg1;

@Description{value:"Test enum for request methods"}
@Field{value:"POST: enumerator for post method"}
enum methods {
    POST,
    GET
}

function func2 (methods ss) {
    methods ns = methods.POST;
    ss = methods.GET;
}
```

**Comment by NipunaMarcus** [comment]
Added the fix from the language server side to calculate the position of the enum. still need to fix this from the ballerina-core level.

**Comment by afkham** [comment]
enums have been removed from the language
