### ISSUE TITLE
Cookie support for client connector

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#4630]
**Description:**
ATM ballerina has HTTP session cookie support for server connector. Client connector should also get the ability to exchange cookie if needed.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
feature

**Suggested Assignees (optional):**

**Comment by arukshani** [comment]
Closing since this is a duplicate of #10729
