### ISSUE TITLE
Introduce a compiler extension to validate Ballerina annotation attachments  

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#4633]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lankavitharana** [comment]
since we have the extension now, shall we close this issue?

**Comment by hasithaa** [comment]
Closing this issue, as this is already implemented. You can find the new compiler plugin design from here. https://github.com/ballerina-platform/ballerina-lang/issues/19325
