### ISSUE TITLE
ballerina compose cmd not working

### ISSUE THREAD

**Issue by udhayamgit** [ballerina-platform/ballerina-lang#4657]
**Description:**
when i try to run compose command in mac it get results for hyperledger compose cmds. I already installed Hyper ledger compose.

udhayams-MacBook-Air:~ udhayamp$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/udhayamp/apache-maven-3.5.2/bin:/Users/udhayamp/ballerina-tools-0.961.0/bin
udhayams-MacBook-Air:~ udhayamp$ composer
composer <command>

Commands:
  composer archive <subcommand>      Composer archive command
  composer card <subcommand>         Command for managing business network cards
  composer generator <subcommand>    Composer generator command to convert a Business Network Definition to code
  composer identity <subcommand>     Composer identity command
  composer network <subcommand>      Composer network command
  composer participant <subcommand>  Composer participant command
  composer runtime <subcommand>      Composer runtime command
  composer transaction <subcommand>  Composer transaction command

Options:
  --help         Show help  [boolean]
  -v, --version  Show version number  [boolean]

Examples:
  composer archive create
  composer identity issue
  composer network deploy
  composer participant add
  composer transaction submit

For more information on Hyperledger Composer: https://hyperledger.github.io/composer/

Not enough non-option arguments: got 0, need at least 1
udhayams-MacBook-Air:~ udhayamp$

**Comment by keizer619** [comment]
The commands you have specified is related to a completely different called Hyperledger composer. 
Ballerina composer is a completely different tool to compose ballerina programs. Please raise your issue in the hyperledger composer repository [1]
[1] https://github.com/hyperledger/composer

**Comment by keizer619** [comment]
Here what could happen is both commands are conflicting as its the same name. You can easily use following command from the composer directory to start the ballerina composer.
`./composer`

If you really want to have command for ballerina composer, in order to avoid the conflict you can use some other name like "ballerina-composer" as the command

**Comment by uthaiyashankar** [comment]
Resolving the issue as per last comment.
