### ISSUE TITLE
Issue when assigning constrained json to json

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-platform/ballerina-lang#4665]
**Description:**
The example[1] in Ballerina examples, shown below states that a new property can be added to a constrained json (json<Person>) by assigning it to a json variable (json employee). However, instead of the value of "person" being assigned to "employee" the reference is passed because;

i) When a value of "person" is changed, that is reflected in "employee",
ii) An extra field to the "employee" cannot be added as it is stated in the example[1]
```
structPerson {
    string name;
    int age;
    string city;
}

function main (string[] args) {

    json<Person> person = {name:"Jon"};

    person.age = 25;
    person.city = "Colombo";
    println(person);

    json employee = person;

    employee.profession = "Software Engineer";
    println(employee);
}
```
[1] https://ballerinalang.org/docs/by-example/constrained-json

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
This issue is no longer valid. The latest ballerina version behaves as expected according to the document - https://ballerina.io/learn/by-example/constrained-json.html

You can add new fields to the employee json.
