### ISSUE TITLE
[Testerina] Add an option to group test cases

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4676]
**Description:**
Add an option to group test cases and execute the same. The user should be able execute test groups selectively.

**Affected Versions:**
0.961.0

**Comment by NatashaWso2** [comment]
The option to group test cases is already provided in the latest master, hence closing this issue.

[https://ballerina.io/learn/by-example/testerina-group-tests.html](https://ballerina.io/learn/by-example/testerina-group-tests.html)
