### ISSUE TITLE
Public constants declared in builtin packages not visible in other packages

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4690]
**Description:**
A public constant added to a builtin package is not accessible from another package. The program compiles and runs fine. But if you print the value of the constant, an empty line is printed. 

**Suggested Labels (optional):**
Type/Bug

**Comment by SupunS** [comment]
This is the same issue as https://github.com/ballerina-platform/ballerina-lang/issues/8398. Hence closing this one.
