### ISSUE TITLE
[IO] Add capability to create tcp server in ballerina

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#4719]
**Description:**
Create a function which will open server socket and start listening to a given IP/Port.

The function should return read/write socket capabilities. 

Server should be able to perform the following,

- Accept incoming connections
- Read the content from a given channel using the I/O APIs
- Write content to the channel using I/O APIs

**Comment by wggihan** [comment]
We have added this functionality with 0.981.0 version. Please note that this syntax will change in a future version most probably.

````
import ballerina/io;

function main(string... args) {
   io:ServerSocket server = new();
   check server.bindAddress(9999);
   while (true) {       
       io:Socket s = check server.accept();
       check s.close();
   }
   check server.close();
}

````
