### ISSUE TITLE
Invalid error message when non-existed bal file is provided to "ballerina run"

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#4729]
**Description:**
If you provide a non-existent file to the ballerina run command, it produces an ambiguous error. The error should simply say that the file does not exist.

**Steps to reproduce:**
ballerina run file-that-doesnt-exist.bal
ballerina: valid package not available at 'file-that-doesnt-exist.bal'

**Affected Versions:**
ALL

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Comment by uthaiyashankar** [comment]
This is fixed now. Error message:

ballerina: cannot find file 'file-that-doesnt-exist.bal'
