### ISSUE TITLE
Cannot include a log inside a test function

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4750]
**Description:**
Original issue can be found at : https://github.com/ballerina-lang/testerina/issues/136

**Related Issues (optional):**
https://github.com/ballerina-lang/testerina/issues/136

**Comment by yasassri** [comment]
package my_prog;

import ballerina.test;
import ballerina.log;
import ballerina.config;

function testFunc1 () {
    string users = config:getGlobalValue("un");
    log:printInfo("info log : " +users);
}

**Comment by NatashaWso2** [comment]
This issue is fixed in the latest master, hence closing this issue.
