### ISSUE TITLE
Null JSON to Struct should return an error

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#4757]
**Description:**
```ballerina
function foo() {
    json j = null;
    var p, e = <Person> j; 
}
```
In the above program, both p and e is null. But since j is a null JSON, it should return an error, and `e` should be not null.

**Affected Versions:**
0.962.0

**Comment by lafernando** [comment]
This behaves now as, when the above is run, it will throw a NullReferenceError, since j is null, and it cannot be converted to Person.
