### ISSUE TITLE
Retrieval of HTTP headers should be case insensitive 

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#4761]
**Description:**
In netty the headers are maintained in a different header `struct` than a map[1]. In Ballerina it is maintained as a `BMap` which is incorrect because of the case insensitive nature of HTTP headers. When the `getHeader` function of the  http:InRequest is called it makes a case-sensitive check to retrieve the value for a header name which is a spec violation.

[1] https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java

**Comment by pubudu91** [comment]
I'm running into this issue in implementing the HTTP caching client. The following sample demonstrates this problem.
```ballerina
import ballerina.net.http;
import ballerina.config;
import ballerina.io;

@http:configuration {port: 9090}
service<http> test {

    @http:resourceConfig {
        path:"/"
    }
    resource testResource (http:Connection conn, http:InRequest req) {
        http:OutResponse res = {};
        res.setStringPayload("Resource invoked");
        io:println(req.getHeader("Test"));
        _ = conn.respond(res);
    }
}
```
Invoking the above service with `curl http://localhost:9090/test -H'Test:foo-bar'` prints `foo-bar`.

But invoking it using `curl http://localhost:9090/test -H'test:foo-bar'` prints `null`.

**Comment by shafreenAnfar** [comment]
This has been fixed.
