### ISSUE TITLE
[Testerina] validate test:config annotation and attributes

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4767]
**Description:**
Annotation attributes should be validated using the annotation extension when that is merged. The validation should include following.

- Duplicate annotations.
- Duplicate attribute.
- Invalid values for attributes. etc.

**Comment by Dilhasha** [comment]
Annotations:

- @test:BeforeSuite, @test:AfterSuite, @test:BeforeEach,  @test:AfterEach
hese Should be allowed to duplicate and is already allowed.

- @test annotation can not be duplicated for the same function

Annotation attributes:

- **enable: {true | false}** This attribute needs validation

**Comment by Dilhasha** [comment]
This is fixed in the current releases. Hence, closing.
