### ISSUE TITLE
No content assistance for errors followed by throw keyword

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#4772]
Original issue - https://github.com/ballerina-lang/language-server/issues/104

**Description:**

No content assistance for errors followed by throw keyword. 

```

function main(string[] args) {
    system:println("Hello, World!");
    error err = {msg:"Account with id: is not found"};
        try {
            **throw err;**
        }
        catch(error err22) {
            system:println("Error caught...");
        }finally {
            system:println("Finally...");
        }
}
```

**Related Issues:**

https://github.com/ballerinalang/composer/issues/4042

**Comment by uthaiyashankar** [comment]
Duplicate https://github.com/ballerina-platform/ballerina-lang/issues/4572
