### ISSUE TITLE
Few connectors that bundles with ballerina lang don't have documentation.

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#4779]
Original issue - https://github.com/ballerina-lang/docerina/issues/111

There are no documentation generated for the some connectors including followings.

- Twitter
- LinkedIn
- oauth2
- soap
 and etc.....

**Comment by NatashaWso2** [comment]
All the connectors are now pushed to Ballerina Central (we don't have a connector for LinkedIn as yet).
So all the connector docs are generated at Central, hence closing this issue.
