### ISSUE TITLE
No way to ignore functions

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#4780]
Original issue - https://github.com/ballerina-lang/docerina/issues/100

if we have 2 ballarina files within a package and if only one of the files have docarina parameters set, when the html doc file is generated an empty function is shown, see attachment.  

steps
1.create two ballerina files

2.call ballerina.doc functions only for one file

3.generate the docs the syntax used was
../../../ballerina-tools-0.88/bin/ballerina doc ../../../wso2/ -o doc/   -v
Note:wso2 is the root path for the packages and doc is the location where the docs are to be generated

Note: A way should exist to ignore any functions that should not go into the documentation
![docs](https://user-images.githubusercontent.com/6552100/27583811-36763ed8-5b25-11e7-9fa5-5d01417649c4.png)

**Comment by hevayo** [comment]
The issue is no longer valid
