### ISSUE TITLE
Foreach Iterable operator issue on a map

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#4796]
**Description:**
Different results when using the foreach iterable operator on a map

**Steps to reproduce:**
```
function main (string[] args) {
    map words = { a:123, b:12, c:111, d:444, e:1 };
    words.foreach(function (string k, int v){
                    println("-- foreach operation's value :" + k);
    });
}
```

When running the above, we get the following error.

```
error: error, message: 0
	at .:$lambda$0(/xxx/xxx/Desktop/test2.bal:3)
	at .:$lambda$stream1(/xxx/xxx/Desktop/test2.bal:3)
	at .:$lambda$iterable0(/xxx/xxx/Desktop/test2.bal:3)
	at .:main(/xxx/xxx/Desktop/test2.bal:3)
```

By changing the second parameter of lambda, **_int v_** to **_string v_** above error resolved. But in this case, when I print the values v and k separately, both gave the same output (keys of the map).
```
-- foreach operation's value :a
-- foreach operation's value :b
-- foreach operation's value :c
-- foreach operation's value :d
-- foreach operation's value :e
```

When we change the second parameter to _**any v**_ we can get the value printed.

Also, by having only one parameter to the lambda, resulted in the same error as mentioned above.

Note: It would be better if we can get the aforementioned error log bit descriptive as well.

**Affected Versions:**
v0.962.0

**Comment by uthaiyashankar** [comment]
This should have been fixed. Following code works

============
map<int>  words = { a:123, b:12, c:111, d:444, e:1 };
    words.foreach(((string, int) val) => () {
                    string k;
                    int i;
                    (k, i) = val;
                    io:println("-- foreach operation's key :" + k + " and value:" + i);
    });
==============

-- foreach operation's key :a and value:123
-- foreach operation's key :b and value:12
-- foreach operation's key :c and value:111
-- foreach operation's key :d and value:444
-- foreach operation's key :e and value:1

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
