### ISSUE TITLE
Add Separate templates for different service types

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#4809]
**Description:**
> In the current completion and suggestion implementation, we suggest http service by default. Instead of having one template for services it would be ideal to suggest possible service template types.
Same as the service, when suggesting resources, we need to analyze the enclosing service type and suggest resource templates accordingly.

**Affected Versions:**
> v0.962.0

**Comment by rasika** [comment]
Created https://github.com/ballerina-platform/ballerina-lang/issues/10218 to track resource level suggestions
