### ISSUE TITLE
Cannot use the horizontal scroll bar in split view mode

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#4819]
**Description:**
In the split view, we cannot click on the horizontal scroll bar.

**Steps to reproduce:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1329674/36578302-3e55360c-1882-11e8-9e7e-52f168698cd8.gif)

**Affected Versions:**
Current head 74df3bc0ef882af243b4b5346423596ad4aaa8a2

**Comment by hevayo** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/9012
