### ISSUE TITLE
Cannot delete IF block when it's added inside another block 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#4820]
**Description:**
User cannot delete the If block from the diagram when it is in another block statement like try/catch , while or transaction. 

**Steps to reproduce:**

![ezgif com-video-to-gif 29](https://user-images.githubusercontent.com/9109762/36578585-384c377c-1884-11e8-9672-b6ecea83267a.gif)

**Affected Versions:**
Current Master

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9299
