### ISSUE TITLE
Cannot delete finally block in design view

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#4821]
**Description:**
Cannot delete the finally block in the design view. When try to hover over the delete, it disappears. Same applies for the try block after deleting the catch block

**Steps to reproduce:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1329674/36578645-9ce90c82-1884-11e8-885d-34afd8f2180e.gif)

**Affected Versions:**
Current head at 74df3bc0ef882af243b4b5346423596ad4aaa8a2

**Comment by maheeka** [comment]
While resolving, please note that the try should have either a finally or a catch at the minimum. Hence deleting a catch should not be possible unless there is another catch or a finally. Similarly, finally cannot be deleted unless there is a catch.
