### ISSUE TITLE
ballerina.collections:Vector is not iterable

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#4823]
**Description:**

The following code will result in a compilation error:

   collections:Vector v = {vec:[]};
    v.add("Foo");
    v.add("Bar");

    foreach foo in v {
        println(foo);
    }

The error is:
incompatible types: 'ballerina.collections:Vector' is not an iterable collection

A collection not being iterable makes using it not very developer friendly.

**Comment by pubudu91** [comment]
Closing since we have removed the Collections package
