### ISSUE TITLE
ballerina.collections:Vector.remove works only with indexes

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#4827]
**Description:**

Consider the following code:

   collections:Vector v = {vec:[]};

    v.add("Foo");
    v.add("Bar");

    v.remove("Foo") doesn't work. You need to give the index to remove ; v.remove(0). This defeats the purpose of using a Vector as opposed to an array.

**Comment by pubudu91** [comment]
Closing since we have removed the Collections package
