### ISSUE TITLE
[Composer] Fix welcome page issue with samples properly

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#4828]
**Description:**
Samples needs to be removed from pack, but composer welcome page needs those samples, so those samples were moved back to tools distribution tempoararily. Need to find a better solution and fix the problem properly

**Steps to reproduce:**

**Affected Versions:**
0.963.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
this temporary move was done with PR - https://github.com/ballerina-lang/ballerina/pull/4826

**Comment by hevayo** [comment]
Fixed in 0.970.0
