### ISSUE TITLE
[HTTP] Provide an API for deleting a header based on the header value

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4863]
**Description:**
Currently, you can only remove a header by giving the header key. But in cases where there may be multiple header values per header key, the user needs to be able to delete a specific value from those header values. 

Example usecase:
`Upon successful validation of a cached response, before serving it to the user, any "Warning" headers present with a 1xx series status code needs to be removed from the response`

**Comment by arukshani** [comment]
This is a very specific usecase and retrieving a header based on a value might return different headers since the same value can be used in multiple headers. 

With an offline discussion with Pubudu it was realized providing this functionality is not going to add any value hence closing this issue.
