### ISSUE TITLE
[HTTP Client] Retry is not working if both retry and timeouts used at the same time

### ISSUE THREAD

**Issue by rosensilva** [ballerina-platform/ballerina-lang#4866]
**Description:**
HTTPClient retry is not working if both retry and timeout are used at the same time. HTTPClinet is not allowing endpointTimeout to retry if the connection is stuck in not responding service.  

**Steps to reproduce:**
1) create HTTPClient with both retry and timeouts as follows, 
```ballerina
create http:HttpClient("http://localhost:9090/test/",
                       {endpointTimeout:2000,
                           retryConfig:{
                                           count:10,
                                           interval:100
                                        }})
```
2) make an HTTP call to not responding service using the above endpoint
3) the call will try only once

**Affected Versions:**
Ballerina 0.962.0

**Comment by VijithaEkanayake** [comment]
Fixed with: https://github.com/ballerina-platform/ballerina-lang/pull/6190/files
