### ISSUE TITLE
[Composer] Undo changes cursor position in source view.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#4868]
**Description:**
While editing the code in source view, the undo action moves the cursor to the top left corner of the editor.

**Steps to reproduce:**
Type ballerina content and perform an undo action.

**Affected Versions:**
v0.961.1.SNAPSHOT

**OS, DB, other environment details and versions:**
MAC OS

**Related Issues (optional):**
https://github.com/ballerina-lang/composer/issues/3509
https://github.com/ballerina-lang/composer/issues/4690
https://github.com/ballerina-lang/composer/issues/4906

**Suggested Labels (optional):**
Added

**Comment by hemikak** [comment]
Can we accommodate the default monaco undo action/operation. As of now the undo removes by every action performed(The undo is also slow, are we having a synchronous call ?). But the default monaco editors undo works in block wise.

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8827
