### ISSUE TITLE
Add Expires directive to session cookie

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#4894]
**Description:**
```
Set-Cookie: id=a3fWa; Expires=Wed, 21 Oct 2015 07:28:00 GMT;
```

The session cookie is deleted when the client shuts down, because now we don't specify an Expires or Max-Age directive.

**Comment by arukshani** [comment]
Closing this since this is covered in newly introduced cookie API https://github.com/ballerina-platform/ballerina-lang/issues/10729
