### ISSUE TITLE
Allow ballerina to execute shell commands

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4902]
**Description:**
ATM there is no mechanism to execute shell commands through ballerina. It would be beneficial if this support is available. Most of the programming languages have this feature. 

**Affected Versions:**
0.963

**Comment by hasithaa** [comment]
Related #17278

**Comment by niveathika** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/17415
