### ISSUE TITLE
Provide a way to dynamically load and link a ballerina library using a symbol

### ISSUE THREAD

**Issue by isurulucky** [ballerina-platform/ballerina-lang#4923]
**Description:**
It should be possible to dynamically load a ballerina library (similar the reflections API provided by Java language), using a symbol (a struct name, etc.) and link it with the runtime.

**Suggested Labels (optional):**
Type/New Feature

**Comment by hasithaa** [comment]
We have to re-evaluate this, as this may not work with the native implementation. Can you specify your specific use case?

**Comment by hasithaa** [comment]
From the description, this seems to be like a platform or runtime specific feature.

**Comment by Kishanthan** [comment]
@isurulucky , can you give more information on this? Are you suggesting to load ballerina modules (types and functions) without importing them?

**Comment by warunalakshitha** [comment]
I am closing the issue and please reopen if you have further queries on this.
