### ISSUE TITLE
Cannot Use a struct from a different package when converting Json -> Struct

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#4926]
**Description:**

Cannot Use a struct from a different package when converting Json -> Struct

**Steps to reproduce:**
Please refer the following code sample.

https://github.com/yasassri/event-manager/blob/master/EventComponent/src/serviceImpl/EvenServiceImple.bal#L29

**Comment by SupunS** [comment]
Fixed with #4935
