### ISSUE TITLE
Create sample to read CSV files and stream values to database

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#4929]
**Description:**

The sample should demonstrate reading values from CSV file using record-io API. These records will be inserted into a table in database.

**Steps to reproduce:**
N/A

**Affected Versions:**
N/A

**OS, DB, other environment details and versions:**
N/A

**Suggested Labels (optional):**
Task

**Suggested Assignees (optional):**
Pamod

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-examples/issues/809 to track this
