### ISSUE TITLE
Add native functions to get remote address, local address, port, ..etc

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#4950]
**Description:**
Currently, there is no way to access remote address, local address. port, ..etc at ballerina level. 

**Related Issues (optional):**
This is required to set X-Forwarded headers manually upon user requirement
https://github.com/ballerina-lang/ballerina/issues/4426

**Comment by VijithaEkanayake** [comment]
This can be achieved with https://github.com/ballerina-platform/ballerina-lang/pull/6063/files
