### ISSUE TITLE
Support String representation for all the available types

### ISSUE THREAD

**Issue by nirmal070125** [ballerina-platform/ballerina-lang#4977]
**Description:**

All the available types should ideally have a string representation. Needs to verify this.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This is available with JBallerina 1.0.0-Alpha
https://github.com/ballerina-platform/ballerina-spec/blob/2763f8220d92513282a43c8decc0c5017190aea6/lang/lib/value.bal#L73
