### ISSUE TITLE
Root of the Ballerina service endpoint should return an index.html

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#4978]
**Description:**
At the moment when we hit root of the Ballerina service, it simply returns 404 saying no matching service found. Instead of that it would be more developer friendly if we can send an index.html as the entity body of the 404 response. This index.html file should include the list of available services and its resources. 

Ballerina developers must be able to configure this behaviour using an annotation configuration.

**Comment by afkham** [comment]
I don't think this is needed. This may be good for Ballerina server mode, but not when it runs services.

**Comment by riyafa** [comment]
Closing based on the reasoning by @afkham
