### ISSUE TITLE
Lang server features doesn't work in composer when use simple case http headers 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#5010]
**Description:**
In ballerina composer lang server features doesn't work. Reason caused this is that when following [HTTP/2 spec](https://tools.ietf.org/html/rfc7540#section-8.1.2) it is necessary to use simple case when using headers. But when in composer backend when uses simple case headers lang server feature stop working.  Added [temporary fix](https://github.com/ballerina-lang/ballerina/pull/5001) by changing the header case back to camel case. Need to find the place where it breaks and fix it properly to support HTTP/2.

**Comment by hevayo** [comment]
This is fixed some time back issue is with LS client.
