### ISSUE TITLE
Package self import not detected by compiler

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-platform/ballerina-lang#5024]
**Description:**
The compiler doesn't detect a self import package. That is importing the same package inside a .bal in which it self is residing in. The following sample causes an internal error

**Steps to reproduce:**
```
package test.wso2.sample;

import ballerina.io;
import test.wso2.sample;
public function main (string[] args) {
    io:println("Hello, World!");
}
```
**Affected Versions:**
0.964.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
This is the same issue as https://github.com/ballerina-platform/ballerina-lang/issues/4878. Hence closing.
