### ISSUE TITLE
Can't create a blob type variable with initial value

### ISSUE THREAD

**Issue by praminda** [ballerina-platform/ballerina-lang#5044]
**Description:**
If we want to initialize a blob variable with initial value there is no way to do that at the moment.
Ex:
`blob a = null;` doesn't work.
Following is the usecase I was not able to accomplish without being able to initialize a blob variable.
Assume we have a function definition as `function foo (int i, blob bar) {}`. Now I want to call this function by providing default values for each parameter. Ex: `foo (0, null)`. I'm able to get this working for all other data types but with blob its not possible. of course its possible to achieve this by,
`blob bar; foo (0, bar);` But for my use case(ballerina code generation) I need to get this done in one line with the function call .

**Comment by hasithaa** [comment]
This can be achieved with a blob literal. Blob literal support is added to the master. Hence closing this issue. Related to https://github.com/ballerina-platform/ballerina-lang/pull/8618
