### ISSUE TITLE
"string".toBlob() is not accepted in method call

### ISSUE THREAD

**Issue by praminda** [ballerina-platform/ballerina-lang#5045]
**Description:**
Consider following usecase,
`function parseData (string name, blob item) {}`

For invoking above method following statement should be valid.
`parseData("name", "string".toBlob("UTF-8"))`

However this is not accepted. If we change the statement as below it is accepted.

`string item = "string"; parseData("name", item.toBlob("UTF-8"))`

**Comment by SupunS** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/3855
