### ISSUE TITLE
Issue in caching due to concurrent caching access

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#5085]
**Description:**
Currently caching uses a map to store caches. Since the map is not thread safe, caching fails in load tests. Need to check whether we can use `ConcurrentHashMap`.

**Comment by lafernando** [comment]
The data structure used is a LinkedHashMap, and we use locks to handle concurrent access in some of the actions such as put and get. But, this hasn't been implemented to all the operations, such as "hasKey", "clear", "remove" and "size". These also must be handled.
