### ISSUE TITLE
Remove woodstox dependency from tests

### ISSUE THREAD

**Issue by ayomawdb** [ballerina-platform/ballerina-lang#5087]
**Description:**
Ballerina unit tests were executed with "woodstox" dependencies in place and the correct expected behavior was observed with "woodstox". However, since this dependency was not included in the distribution, run-time behavior was different from behavior during test execution. 

We need to remove this dependency from from test execution and correct unit tests accordingly. 

(Additionally, it is required to make sure, if user defined the XML literal as <foo/> output also should be "<foo/>", and if the literal was <foo></foo>, then it should also print it as is)

**Comment by uthaiyashankar** [comment]
@ayomawdb can we resolve this?

**Comment by ayomawdb** [comment]
@uthaiyashankar No. This issue is still unaddressed and was low prioritized. @SupunS can confirm on this.
