### ISSUE TITLE
Eliminate Guava dependency from Ballerina

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#5090]
**Description:**
Siddhi source code requires Guava as the external library for the implementation. Due to this, we have initiated an effort to move the Guava source code within the Siddhi source itself but it introduces a lot of complications like below and it takes a considerable amount of time to resolve them.
> Transitive dependencies
> Code styling issues 
> Findbug related issues

Then, Guava library added as the external dependency for now and we have to remove this in near future soon.

**Suggested Assignees (optional):**
mohan@wso2.com

**Comment by gimantha** [comment]
Siddhi dependency is removed hence streams do not need guava, but seems some of the stdlib modules use guava
