### ISSUE TITLE
[Langserver/Composer] Suggestions not working

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#5095]
**Description:**
Suggestions in the composer is not working.

**Steps to reproduce:**
See the gifs

![0enqrngxzp](https://user-images.githubusercontent.com/4398820/37239095-0c46ebd0-245b-11e8-916c-3eb87c7a2a6c.gif)
![duynykxeyj](https://user-images.githubusercontent.com/4398820/37239096-0c7a789c-245b-11e8-8d17-009801dd7cdd.gif)

**Affected Versions:**
0.964.0

**OS, DB, other environment details and versions:**
Mac

**Comment by nadeeshaan** [comment]
Fixed in Latest master and closing the issue
