### ISSUE TITLE
[Tables] In memory tables dont close the connections properly

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#5106]
**Description:**
When the in-memory tables are created using SQL-queries in ballerina, more DB connections are created but they are never released. A connection for each table stays open.

**Steps to reproduce:**
Can be seen multiple-connections in TableSqlQueryTest test class, there are 11 connections, but expected is only 1.

**Affected Versions:**
0.965

**Comment by anupama-pathirage** [comment]
TableLiteralTest.java - testSessionCount test case is disabled until this is fixed.

**Comment by Manuri** [comment]
@anupama-pathirage I ran the TableLiteralTest multiple times with these two tests enabled but didn't encounter any failure. Is this still reproducible for you?

![testspassed](https://user-images.githubusercontent.com/1335271/49992059-f5e7d500-ffa8-11e8-93ec-98dfcec8a063.png)

**Comment by anupama-pathirage** [comment]
@Manuri This was disabled since it was a intermittent test failure which occurred on multiple travis and jenkins builds

**Comment by mohanvive** [comment]
Issue is no longer valid in new table implementation which is introduced in Swan Lake release preview #1.
