### ISSUE TITLE
ServiceEndpoing start() should consider error scenario 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#5211]
**Description:**
At the moment, we don't wait till binding is complete to return from start() implementation. Ideally, we should return from the function only when binding is completed. 

Also we do not consider the error scenario here, we need to consider that too.

https://github.com/ballerina-lang/ballerina/blob/master/stdlib/ballerina-http/src/main/java/org/ballerinalang/net/http/serviceendpoint/Start.java#L73

**Comment by riyafa** [comment]
Not relevant in the current version 0.975.1
