### ISSUE TITLE
VM doesn't have json multidimentional array support

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#5264]
**Description:**
type of multidimensional json array is a single dimensional json array in VM side

**Steps to reproduce:**
```ballerina
import ballerina.io;

public function main (string[] args) {
    json[][][][][][][] jsonMulti = [];
    io:println(typeof jsonMulti);
}
```
above code prints "json[]"

**Affected Versions:**
current master and previous releases(last release 0.965.0)

Note - fix test cases in PR - https://github.com/ballerina-lang/ballerina/pull/5261 after fixing this

**Comment by lafernando** [comment]
Typeof is not available anymore.
