### ISSUE TITLE
Enforce CLI param order

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#5286]
**Description:**
Currently, CLI parameters/options don't have an order. We can specify them in any order we like. Ideally, we should be able to enforce some order to this. For example,
```
$ ballerina run -c ballerina.conf program.bal prog args
```

**Comment by sanjiva** [comment]
In addition to order, we can't have ballerina take over program arguments! So under no condition should we be touching anything that comes after the name of the program to run.

This will become even more critical when we do the generalization of main() signature.
