### ISSUE TITLE
Getting 404 from Ballerina By Example Source links

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#5370]
**Description:**
Source links of BBE seem to be outdated.

**Steps to reproduce:**
Click the source link at the bottom of any BBE page.
For example the source link of Hello World sample points to [1]

[1] https://github.com/ballerina-lang/ballerina/tree/master/samples/ballerina-by-example/examples/hello-world

**Comment by uthaiyashankar** [comment]
This is fixed in new BBE
