### ISSUE TITLE
Wrong server response in  HTTP Header

### ISSUE THREAD

**Issue by pzfreo** [ballerina-platform/ballerina-lang#5414]
**Description:**
Currently the server header in HTTP responses is 
server: wso2-http-transport

This should be "ballerina-http-transport" or "ballerina-http-server"

**Steps to reproduce:**
curl -v any ballerina HTTP service

**Affected Versions:**
All

**OS, DB, other environment details and versions:**
Any

**Related Issues (optional):**

**Suggested Labels (optional):**
http, service

**Suggested Assignees (optional):**

**Comment by shafreenAnfar** [comment]
Hi, 

This has been fixed in the latest version. Below is the output.

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
