### ISSUE TITLE
Language server adding imports in wrong place (VSCode)

### ISSUE THREAD

**Issue by pzfreo** [ballerina-platform/ballerina-lang#5416]
**Description:**
I'm using the automatic "show fixes" to add an import in VSCode, but unfortunately it is adding the import at the current cursor and not at the top of the file.

**Steps to reproduce:**
Start a new file in VSCode and type "service". Let the LS autocomplete a default HTTP service. By default this is missing the HTTP import. Now click on the lightbulb to add the import, and it adds the import in the middle of the current text (as follows):

```
s
import ballerina.net.http;
ervice<http> demo {
    resource resourceName (http:Connection conn, http:InRequest req) {
    }
}
```

**Affected Versions:**
0.964.0

**OS, DB, other environment details and versions:**
Mac OS, VSCode Version 1.21.1 (1.21.1)

**Related Issues (optional):**

**Suggested Labels (optional):**
Language Server

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@pzfreo This particular issue has been fixed in the latest master (caac5810e580985131f6a9a386db1f003d755163). Hence closing the issue and feel free to reopen if there are any concerns
