### ISSUE TITLE
Remove overloading functions from test suite  

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#5429]
**Description:**

According to current syntax, function overloading is not supported. Thus need to remove following .bal files. 

/modules/web/src/plugins/ballerina/tests/resources/formatted/function-overloading-diff-arg-count.bal
/modules/web/src/plugins/ballerina/tests/resources/formatted/function-overloading.bal

**Comment by anupama-pathirage** [comment]
@hevayo : These files in /modules/web/src/plugins/ files are used for composer testing and seems no longer using. Shall we consider remove them?
