### ISSUE TITLE
Un reachable Pattern Issue with Error union Types

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#5445]
**Description:**
Consider the following native function code snippet (Original file can be found at https://github.com/ballerina-lang/ballerina/blob/master/stdlib/ballerina-builtin/src/main/ballerina/ballerina/file/natives.bal#L109).

Instead of returning a tuple, used the following to return a union type.
`public native function <File file> mkdirs () returns (boolean| AccessDeniedError| IOError);`

When the following sample used to test,

```
import ballerina.file;
import ballerina.io;

function main (string[] args) {
    file:File dirs = {path:"file path"};
   var dirCreated = dirs.mkdirs();
    match dirCreated {
        boolean =>io:println("success");
        file:AccessDeniedError e1 => io:println(typeof e1);
        file:IOError e2 => io:println(typeof e2);
    }
}
```
When run this, gets the following error.
**_unreachable pattern: preceding patterns are too general or the pattern ordering is not correct_** 

Both error structs are as follows.

```
public struct AccessDeniedError {
    string message;
    error[] cause;
}
```
```
public struct IOError {
    string message;
    error[] cause;
}
```

**Comment by hasithaa** [comment]
Ballerina's type system is based on structural types not on nominal types. Hence both AccessDeniedError and IOError are equal. Hence given error message is correct. 

Additionally, we have introduced a new error type, the match statement will be replaced with type-guard.
