### ISSUE TITLE
Transformer parameter not visible inside map function

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-platform/ballerina-lang#5485]
**Description:**
```ballerina
transformer <Persons source, Employees target>  personsToEmployees(int empId){        //line No.1
   target.list = source.list
                   .map(
                   function (Person p)(Employee){ 
                       return <Employee, personToEmployee(empId)> p;             // line No.2
                   });
}
```
Please note that parameter **empId** that is being passed into the **personToEmployee** transformer. This gives a compilations error saying that empId in line No.1 is not visible to line No.2.

Error: `undefined symbol 'empId'`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by uthaiyashankar** [comment]
Transformer is removed.
