### ISSUE TITLE
Cannot define a function pointer without initializing 

### ISSUE THREAD

**Issue by suhothayan** [ballerina-platform/ballerina-lang#5523]
**Description:**

Originnally the funciton pointer is defined as : 
`function () returns (error|null) onTriggerFunction; `
the complier focess to initilize that 
`variable 'onTriggerFunction' is not initialized`

This also does not work even if we make runnable
 `(function () returns (error|null)| null) onTriggerFunction = null;`
throws error 
`incompatible types: expected 'function () returns (null|error)', found 'null'`

The only possible option is assigning an empty function as below:
`function () returns (error|null) onTriggerFunction = function () returns (error|null) { return null;};`

I believe there an easier way of initializing this.

**Affected Versions:**
0.964.1-SNAPSHOT

**Comment by afkham** [comment]
(function () returns (error|null))? onTriggerFunction; works
