### ISSUE TITLE
Need sort function for string array

### ISSUE THREAD

**Issue by Biruntha** [ballerina-platform/ballerina-lang#5555]
**Description:**
Need this function for twitter connector. 
Existing arrays:sort(string []) is not working in Ballerina 0.964.1-SNAPSHOT.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by riyafa** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/1433

**Comment by hasithaa** [comment]
You can use array.sort lang lib method and string.codePointCompare method to achieve this. Fixed with JBallerina 1.0.0-alpha.
