### ISSUE TITLE
Issues casused in map type and IterableOperations after type change

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#5557]
**Description:**

After type change following cases are not working with iterable operation

#### count() is not working
error :  `undefined symbol 'count'`

``` ballerina
map m = {a:"A", b:"B", c:"C", d:"D", e:"E"};
count = m.count();
```
Current Test: https://github.com/ballerina-lang/ballerina/blob/master/tests/ballerina-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal#L89

------

#### key value pairs cannot be passed as tuples
error : `too many variables are defined for iterable type '((string,string))[]'`

``` ballerina
function testBasicMap2() returns (string[]) {
    map m = {a:"A", b:"B", c:"C", d:"D", e:"E"};
    string[] values = m.map(mapAnyToString)
                .filter(function (string k,string v) returns (boolean) {
                       if (k == "a" || k == "e") {
                           return true;
                       }
                       return false; })
                .map(concatString);
    return values;
}

function mapAnyToString (string key, any value) returns (string, string) {
    var v, _ = (string)value;
    return (key, v);
}
```
Current Test: https://github.com/ballerina-lang/ballerina/blob/master/tests/ballerina-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal#L102

---

#### returning tuple in map() cannot be assigned to map
error:` incompatible types: expected 'map', found '((string,xml))[]'`

``` ballerina

xml xdata = xml `<p:person xmlns:p="foo" xmlns:q="bar">
        <p:name>bob</p:name>
        <p:address>
            <p:city>NY</p:city>
            <q:country>US</q:country>
        </p:address>
        <q:ID>1131313</q:ID>
    </p:person>`;

function xmlTest() returns (int, any, map){
    map m = xdata.children().elements()[1].children().elements().map(function (int i, xml x) returns (string, xml){
        return (<string>i, x);
    });
    return (xdata.children().count(), xdata.children().elements().count(), m);
}
```

Current Test: https://github.com/ballerina-lang/ballerina/blob/master/tests/ballerina-test/src/test/resources/test-src/expressions/lambda/iterable/basic-iterable.bal#L156

**Comment by Kishanthan** [comment]
@keizer619 , all these test cases are already fixed on the master and enabled.
