### ISSUE TITLE
Package language server build (vsix) with the tools distribution

### ISSUE THREAD

**Issue by pzfreo** [ballerina-platform/ballerina-lang#5567]
**Description:**
Currently the vsix file is not in the tools distribution. If you have different builds of Ballerina on your machine, you cannot easily change the VSIX in Visual Studio to match the version you are using, because it requires a rebuild.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
We do not include vsix file inside platform distribution but for each release we provide vsix file separately from the ballerina.io website.  For older versions users can visit [archived versions](https://ballerina.io/downloads/archived/) and download the relevant vsix file.
