### ISSUE TITLE
Get cache should behave as map

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#5577]
**Description:**
If we want to get a value from a map and that value is not in the map, an error will be thrown. So we need to check and make sure that key is in the map first. 

Similar behavior should be added to cache get function.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by afkham** [comment]
Now we return () if there is no value
