### ISSUE TITLE
Auto completion drop down appear when type period in documentation annotation.  

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#5580]
**Description:**
When typing the description text in the MD documentation annotation typing a period will cause auto completion drop down to pop up and show completion suggestions. This is not valid for this location.

**Steps to reproduce:**
![completion doc issue](https://user-images.githubusercontent.com/9109762/37709607-c6f08c38-2d30-11e8-87df-336b5edf904c.png)

**Comment by nadeeshaan** [comment]
This has been already fixed in the latest master. Hence closing the issue
