### ISSUE TITLE
String to XML conversion (and vise versa) fails

### ISSUE THREAD

**Issue by bhathiya** [ballerina-platform/ballerina-lang#5695]
**Description:**
`var x1 = <xml> "<root><foo/></root>";`

Above line gives following error. 
`incompatible types: 'string' cannot be convert to 'xml'`

Note: XML to String conversion is failing too.

Affected Test Cases:
https://github.com/ballerina-lang/ballerina/blob/master/tests/ballerina-test/src/test/java/org/ballerinalang/test/types/xml/XMLAttributesTest.java

**Comment by uthaiyashankar** [comment]
String to xml:

xml x1 = xml `<root><foo/></root>`;

**Comment by bhathiya** [comment]
@uthaiyashankar That worked IIRC. The problem was with casting. 
```
string s = "<root><foo/></root>";
var x1 = <xml> s;
```

**Comment by Kishanthan** [comment]
`xml` to `string` conversion is supported OOTB.

Ex :
```
xml x1 = xml `<foo foo="http://wso2.com" >hello</foo>`;
string s = <string>x1;
//or can directly print the value 
io:println(x1);
```

But the idea to support `string` to `xml` is only at the relevant places such as reading file content as xml or reading as http payload as xml. These are supported as API methods from the respective packages.
