### ISSUE TITLE
String to Boolean should be an unsafe conversion

### ISSUE THREAD

**Issue by mefarazath** [ballerina-platform/ballerina-lang#5707]
**Description:**
Consider below function,
```
function stringToBoolean(string value) returns (boolean) {
    boolean result;
    result = <boolean>value;
    return result;
}
```
This should throw a compilation error saying its an unsafe operation. But it compiles without giving any errors.

**Affected Versions:**
0.964.1-SNAPSHOT

**Comment by uthaiyashankar** [comment]
Duplicate : https://github.com/ballerina-platform/ballerina-lang/issues/4172
