### ISSUE TITLE
No support for MIME message encoding for both headers and entity body 

### ISSUE THREAD

**Issue by dushaniw** [ballerina-platform/ballerina-lang#5942]
**Description:**
 In ballerina.mime, the function **encode(blob content) (blob)** bounded for MimeBase64Encoder struct, only supports encoding a blob type. So according to the current implementation, we are only able to encode an entity body part with a blob content.

 `        mime:Entity textBodyPart = {};`
`         textBodyPart.setBlob(bodyText.toBlob("UTF-8"));`
`         var getBlobResponse = textBodyPart.getBlob();`
`         mime:MimeBase64Encoder encoder = {};`
`         match getBlobResponse {`
`                 blob msgBlob => {`
`                         blob blobEncode = encoder.encode(msgBlob);`
`                 }`
`                 mime:EntityError err => io:println(err);`
`         }`

However, the Entity struct represents both headers and body of a message. Since there is no support for encoding whole message with both headers and entity body, we are not able to use ballerina.mime support for sending a base64 encoded email message with headers, body and message attachments in ballerina gmail connector.

**Steps to reproduce:**

**Affected Versions:**
0.964

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by arukshani** [comment]
Please note that base64 is one of the values we provide in "content-transfer-encoding" header which indicates the type of transformation that has been used in order to represent the body in an acceptable manner for transport. That does not include headers. Only the body should be encoded. So it is only the entity body that you should encode not the whole entity. 

And can you please provide more info regarding your requirement so that i can see what the exact issue is. 
Here's the spec btw > https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html
Thanks.

**Comment by arukshani** [comment]
@dushaniw
A new method called "getBodyPartsAsChannel()" has been introduced to convert the given parts as a channel as it this is needed for gmail connector API. 

 Can you please verify whether this is working.

**Comment by arukshani** [comment]
Output of 'getBodyPartsAsChannel()' on a multipart entity wraps the whole message with a boundary which is not needed for Gmail connector. Therefore, a new method is needed to convert the Entity to a byte channel. Will inform you once that is implemented Dushani. 

**Sample**

--556b0b8b339b42ef
To: dushaniw@wso2.com
Subject: Test
From: dushaniwellappili@gmail.com
Cc: dushaniwellappili@gmail.com
Bcc: dushaniwellappili@gmail.com
content-type: multipart/mixed;boundary=adce710aa16eebb8

--adce710aa16eebb8
content-type: multipart/related;boundary=8dfa22047e1fd565

--8dfa22047e1fd565
content-type: multipart/alternative;boundary=a564970075426c29

--a564970075426c29
content-type: text/plain

text body
--a564970075426c29
content-type: text/html

HTML BODY
--a564970075426c29--

--8dfa22047e1fd565--

--adce710aa16eebb8--

--556b0b8b339b42ef--

**Comment by arukshani** [comment]
Since gmail connector is not using MIME, we are closing this.
