### ISSUE TITLE
Iterable operator map dosen't work

### ISSUE THREAD

**Issue by TharinduNM** [ballerina-platform/ballerina-lang#5945]
**Description:**
The iterable operator `map` doesn't work in the current ballerina version.

**Steps to reproduce:**
```
import ballerina/io;

function main (string[] args) {
    json[] ar = ["sdf","b","c"];
    string[] lis = ar.map(function(json i) returns (string){
        return i.toString();
    });
    io:println(lis);
}
```
This code should convert the json array to a string array. But it gives the output: `["", "", ""]`

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Please use foreach for now. Here is an example.
```ballerina
function main (string[] args) {
    json[] ar = ["sdf","b","c"];
    string[] lis;
    foreach i,j in ar {
        lis[i] = j.toString();
    }
    io:println(lis);
}
```

**Comment by vlgunarathne** [comment]
Hi Hasitha,

The **foreach** loop doesn't work inside a transformer. 

The map doesn't give any syntax errors inside the transformer. However there is an issue with the return inside the map function. Please see the code below.

```ballerina
import ballerina/io;

public function main (string[] args) {


    json book = {name:"Book1", authors:[{name:"Author1"},{name:"Author2"},{name:"Author3"}]};
    var b1 = <Book, jsonToBook()>book;
    io:println(b1);


}

struct Book {
    string name;
    Author[] authors;
}

struct Author {
    string name;
}

transformer <json s, Book t> jsonToBook() {
    t.name = s.name.toString();
    t.authors = s.authors.map(
                         function (json node) returns Author {
                             var athr =? <Author>node;
                             return athr;
                         }
                         );
}
```

The output of the code will be as follows:

**{name:"Book1", authors:[{name:""}, {name:""}, {name:""}]}**
Please note the empty values for **name**.

**Comment by anupama-pathirage** [comment]
Checked in 0.970.1 and map is working 

```ballerina
import ballerina/io;

function main (string... args) {
    json[] ar = ["sdf","b","c"];
    string[] lis = ar.map((json j) => (string) {
	return j.toString();
});
    io:println(lis);
}
```
