### ISSUE TITLE
Unable to stop compilation from compiler plugins

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#6031]
**Description:**
- The dlog with Diagnostic.Kind.ERROR should stop the compilation.
`dlog.logDiagnostic(Diagnostic.Kind.ERROR, endpointNode.getPosition(), e.getMessage());`

- This is not working at the moment. Even though the kind is set as an error from the plugin, the compiler prints the error and continues.

- There should be a logDiagnostic method that doesn't require position as a parameter as well.

**Steps to reproduce:**
- Create a compiler plugin and dlog an error.

**Affected Versions:**
0.970.0-alpha0

**OS, DB, other environment details and versions:**
Mac OS

**Suggested Labels (optional):**
Bug, L1/L2 for May

**Suggested Assignees (optional):**
SameeraJ

**Comment by Shan1024** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/commit/e51fa1b3bfee0ba9238a79c4781b8e618e85ed4e.
