### ISSUE TITLE
[IO] Introduce String to Channel Conversion 

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#6067]
**Description:**
We need a function that does the following,

//Usage 1
String content = "Ballerina";
IOUtils.getChannel(String content,String encoding) returns (io:CharacterChannel);

Once that channel is obtained a json channel could be created in the following manner,

//Usage 2

io:CharacterChannel channel;
io:JsonChannel jsonChannel = channel.createJsonChannel(channel);

json jsonContent = jsonChannel.readJson();

**Comment by riyafa** [comment]
When can this be expected? We need string to json conversion only in 
WebSockets even if it does not involve any channels :)

**Comment by riyafa** [comment]
Resolved in the current master
