### ISSUE TITLE
Stabilize HTTP/2 support of HTTP transport implementation

### ISSUE THREAD

**Issue by isudana** [ballerina-platform/ballerina-lang#6076]
**Description:**
HTTP/2 support for HTTP is available with all the necessary features. 
Need to stabilize the implementation with testing for edge cases, heavy load, etc.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shafreenAnfar** [comment]
Closing this as this is done.
