### ISSUE TITLE
[HTTP] Improve the current HTTP response codes by including reason phrase

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#6163]
**Description:**
Currently, the HTTP response status codes are just integers. Need to improve this to include the reason phrase as well. So it would look like something below:
```ballerina
public struct ResponseStatus {
        int statusCode;
        string reasonPhrase
}
```

**Comment by riyafa** [comment]
Now it is possible to obtain the `statusCode` and the `reasonPhrase` from the `Response` object

**Comment by pubudu91** [comment]
@riyafa Reopening this issue since what this issue is about is unify the status code and reason phrase into a common data structure called `ResponseStatus` and define enums/constants for the standard HTTP status codes, along with the reason phrase (currently, we only provide `int` constants for status codes). This is somewhat similar to what Netty provides, as `HttpResponseStatus`.

**Comment by riyafa** [comment]
@pubudu91 currently we also provide the `reasonPhrase` in the `http:Response` object. It was misleading to say we only provide the status code as numbers. A different object called `ResponseStatus` can be created to include both which makes sense.

**Comment by pubudu91** [comment]
I was referring to the response status codes in [https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-http/src/main/ballerina/http/response_status_codes.bal](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-http/src/main/ballerina/http/response_status_codes.bal)

**Comment by riyafa** [comment]
okay that makes sense. Thanks

**Comment by davebaol** [comment]
It makes a lot of sense.
This is exactly what I was looking for in Ballerina API docs.

**Comment by anuruddhal** [comment]
Following is the correct link.
https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/http/src/main/ballerina/http/response_status_codes.bal

**Comment by shafreenAnfar** [comment]
Hi All, we have defined status codes as <status>_<response phrase> to address this. See below.
https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/http/src/main/ballerina/src/http/response_status_codes.bal

Hence, closing this issue.
