### ISSUE TITLE
Intermittent test failure of web socket test case

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6168]
**Description:**
$subject of testCloseConnection in org.ballerinalang.test.service.websocket.sample. ConnectionStoreSampleTest. Currently particular test case is disabled and it occurs due to the failure of removing stored client.

Moved from https://github.com/ballerina-lang/tools-distribution/issues/134

**Comment by irunika** [comment]
This issues is already addressed via https://github.com/ballerina-platform/ballerina-lang/issues/7893.
