### ISSUE TITLE
Ballerina - Test Integration module build failed in windows

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6169]
**Description:**
Ballerina - Test Intergration module build is failing in windows due to checkstyle violations. Btw this is a bug in checkstyle that some checkstyle violations are not found in unix based sytems but found in windows.

This is the log:
[INFO] Building Ballerina - Test Integration 0.95.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading from wso2.releases: http://maven.wso2.org/nexus/content/repositories/releases/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.pom
Downloading from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.pom
Downloaded from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.pom (6.3 kB at 24 kB/s)
Downloading from wso2.releases: http://maven.wso2.org/nexus/content/repositories/releases/org/apache/mina/mina-parent/2.0.16/mina-parent-2.0.16.pom
Downloading from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/mina/mina-parent/2.0.16/mina-parent-2.0.16.pom
Downloaded from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/mina/mina-parent/2.0.16/mina-parent-2.0.16.pom (33 kB at 71 kB/s)
Downloading from wso2.releases: http://maven.wso2.org/nexus/content/repositories/releases/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.jar
Downloading from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.jar
Downloaded from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.jar (651 kB at 521 kB/s)
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ test-integration ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ test-integration ---
[INFO] Starting audit...
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\context\Server.java:53:47: error: Unable to get class information for @throws tag 'BallerinaTestException'.
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\context\ServerInstance.java:525: error: First sentence should end with a period.
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\context\Utils.java:115:63: error: Unable to get class information for @throws tag 'BallerinaTestException'.
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\service\http\sample\HTTPVerbsPassthruTestCases.java:34: error: First sentence should end with a period.
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\util\HttpsClientRequest.java:197: error: First sentence should end with a period.
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\util\websocket\client\WebSocketClient.java:55: error: First sentence should end with a period.
C:\Users\Raveen S Rathnayake\tools-distribution\modules\tests\test-integration\src\test\java\org\ballerinalang\test\util\websocket\server\WebSocketRemoteServerFrameHandler.java:33: error: First sentence should end with a period.
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Ballerina - Tools .................................. SUCCESS [ 7.907 s]
[INFO] ballerina .......................................... SUCCESS [01:03 min]
[INFO] Ballerina - Test Integration ....................... FAILURE [ 5.151 s]
[INFO] ballerina-tools .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2017-11-19T23:51:01+05:30
[INFO] Final Memory: 37M/420M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project test-integration: Failed during checkstyle execution: There are 7 errors reported by Checkstyle 6.11.2 with https://raw.githubusercontent.com/wso2/code-quality-tools/master/checkstyle/checkstyle.xml ruleset. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :test-integration

Moved from https://github.com/ballerina-lang/tools-distribution/issues/213

**Comment by SupunS** [comment]
All the issues related we had with the windows build is now fixed. We also now have AppVeyor configured to the git repo to trigger a windows build for every PR. Hence closing this issue.
