### ISSUE TITLE
Handle Docerina return type

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#6170]
This logic is disabled due to type-checker refactoring.

Disabled with comit. 23c159b2818d1066072a84b6d9322bab12e8967d

**Comment by NatashaWso2** [comment]
Return types are handled by Docerina with https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/docerina/src/main/java/org/ballerinalang/docgen/Generator.java#L418

Since this issue is resolved, closing this.
