### ISSUE TITLE
Need to capture keyboard shortcuts from all controls

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6233]
<a href="https://github.com/uthaiyashankar"><img src="https://avatars3.githubusercontent.com/u/2410076?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [uthaiyashankar](https://github.com/uthaiyashankar)**
_Wednesday Feb 15, 2017 at 07:58 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/672_

----

For example, if you press ctrl + S from an edit box (while editing service name for example), it invokes browser's save option. not the editor's save option.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Thursday Jul 06, 2017 at 07:17 GMT_

----

Similar duplicate https://github.com/ballerinalang/composer/issues/854

**Comment by uthaiyashankar** [comment]
This is still valid

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
