### ISSUE TITLE
Opened Ballerina files on Ballerina editor (graphical view) cannot be reordered.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6234]
<a href="https://github.com/Sewmi"><img src="https://avatars2.githubusercontent.com/u/7960586?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Sewmi](https://github.com/Sewmi)**
_Saturday Feb 18, 2017 at 05:35 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/835_

----

Ballerina files that are opened in Ballerina editor  (graphical view) cannot be reordered as user preferred.

<img width="1438" alt="ballerina_composer_reordering" src="https://cloud.githubusercontent.com/assets/7960586/23090690/29ebacf4-f5ca-11e6-82fe-897d980362ef.png">

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Thursday Jul 06, 2017 at 05:13 GMT_

----

this will be get fixed after the golden layout implementation

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Tuesday Oct 24, 2017 at 11:15 GMT_

----

We have dropped golden layout. hence issue still valid

**Comment by uthaiyashankar** [comment]
This issue is still valid

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
