### ISSUE TITLE
Provide a runtime per service/application

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6236]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Sunday Feb 19, 2017 at 21:58 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/1002_

----

Currently the run functionality is global to the composer and there is no capability to individually run a service and application at the same time. The reason is the running mechanism is global to the composer (composer is bind with single runtime) 

By using separate run times for the services and applications that is developed through composer will provide better usability for the user.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/hevayo"><img src="https://avatars0.githubusercontent.com/u/323846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hevayo](https://github.com/hevayo)**
_Thursday Mar 23, 2017 at 05:32 GMT_

----

+1 This will help to debug integration scenarios involving multiple bal services.

**Comment by nadeeshaan** [comment]
Closing the issue since this is no longer valid
