### ISSUE TITLE
When clicking on expression editor cursor should be placed on the selected position

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6237]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Tuesday Apr 18, 2017 at 12:43 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/1381_

----

When clicking the cursor always positions at the end : 
<img width="194" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/25131167/62d1de46-2462-11e7-8e63-9cb3fae171ed.png">

The cursor should position at the selected position when clicking on the editor : 
<img width="162" alt="image" src="https://cloud.githubusercontent.com/assets/1029806/25131217/8defd088-2462-11e7-90c8-360563ec8070.png">

**Comment by hevayo** [comment]
Expression editor has been removed from 0.970.0
