### ISSUE TITLE
Samples get saved on sample location

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6239]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dakshika](https://github.com/dakshika)**
_Monday Jun 12, 2017 at 05:45 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/1915_

----

When you save a sample it will save under sample location and override the file. 

ballerina-tools-0.88/samples/echoService/echoService.bal

This will kill the sample behavior and if some user change accidentally and they can't revert back to original due to this bug

Tested on ballerina-tools-0.88

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Tuesday Jun 27, 2017 at 08:50 GMT_

----

this has to fix below issue as well. 
* unsaved sample name on breadcrumb should be "sampleName" or "Untitled"

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Thursday Jul 06, 2017 at 10:34 GMT_

----

similar issue https://github.com/ballerinalang/composer/issues/1832

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
