### ISSUE TITLE
Statement highlighting

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6240]
<a href="https://github.com/jeradrutnam"><img src="https://avatars1.githubusercontent.com/u/7569427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeradrutnam](https://github.com/jeradrutnam)**
_Monday Jun 12, 2017 at 06:28 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/1922_

----

There should be an indicator for users to identify the focused statement. 

e.g. Change background color or Change border color

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Thursday Jul 06, 2017 at 10:48 GMT_

----

@jeradrutnam: do you have any design for this

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
