### ISSUE TITLE
A few Swagger related issues

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6241]
<a href="https://github.com/handakumbura"><img src="https://avatars0.githubusercontent.com/u/6889802?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [handakumbura](https://github.com/handakumbura)**
_Monday Jun 19, 2017 at 08:45 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2017_

----

The issues were observed with the .89 build no 412[1] on a chrome 54.0.28 instance.

1> There is mechanism in place in the design view to remove swagger annotations once they are put in place.

2> The design view freezes when the schemas attribute(@swagger:ServiceConfig {}) is selected, as a workaround you can switch to code view and switch back to design view.

3> The swagger definition generated when using the schema attribute seems to be incorrect. to reproduce this behavior add,

@swagger:ServiceConfig { schemes: [ "http","https"]} at service level and observe the generated swagger definition.

4> Looks like the parameter model definitions are not captured by the annotations currently. Definition segment,

      parameters:
      - in: "body"
        name: "body"
        description: "The branch locator payload containing the zip code of the consumer."
        required: true
        schema:
          $ref: "#/definitions/RequestPayload"
definitions:
  RequestPayload:
    type: "object"
    properties:
      BranchLocator:
        $ref: "#/definitions/ZipCode"
  ZipCode:
    type: "object"
    properties:
      ZipCode:
        type: "string"

[1] - https://wso2.org/jenkins/job/ballerinalang/job/tools-distribution/org.ballerinalang.tools$ballerina-tools/412/ MD5: 885309adbacd3fd3b221fb08a9d6b4bf

**Comment by hevayo** [comment]
Implementation has differed
