### ISSUE TITLE
It is not clear that you can edit services and resource names.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6242]
<a href="https://github.com/hevayo"><img src="https://avatars0.githubusercontent.com/u/323846?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hevayo](https://github.com/hevayo)**
_Thursday Jun 22, 2017 at 13:11 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2061_

----

Suggesting to give an edit icon next to service or resource name when you hover over a service or resource.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Monday Nov 13, 2017 at 19:34 GMT_

----

@dakshika - what do you think about this?  
@hevayo  - you mean like pop up an action box like tool boxes. I think this is more connected with the @jeradrutnam 's idea of highlighting statement panels and boxes when hover and showing a tool box?

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
