### ISSUE TITLE
Errorneous statement gets reverted on enter

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6243]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Jun 22, 2017 at 14:20 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2076_

----

Click on an assignment and start typing
<img width="150" alt="image" src="https://user-images.githubusercontent.com/1029806/27438754-de54a40a-5783-11e7-9389-ea104621d939.png">

During typing, following is an erroneous statement. 
<img width="168" alt="image" src="https://user-images.githubusercontent.com/1029806/27438770-e7730536-5783-11e7-923e-daa36639be1d.png">

If user looses focus at this point (by mistake), everything is reverted back to the old state, resulting the user to start typing from beginning.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/hevayo"><img src="https://avatars0.githubusercontent.com/u/323846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hevayo](https://github.com/hevayo)**
_Monday Jul 24, 2017 at 09:07 GMT_

----

We need display an error when the content is not valid.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Monday Nov 13, 2017 at 09:22 GMT_

----

Current behaviour is as follows.

When user types syntactically incorrect source, the source is reverted and an error message is displayed.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/1029806/32718113-f5c38142-c853-11e7-9739-a6e1e14c3616.png">
<img width="162" alt="image" src="https://user-images.githubusercontent.com/1029806/32718119-fac914a4-c853-11e7-810f-2fa6821337f8.png">

We should disable falling back on the editing mode when hit enter with syntactically incorrect code.  
@hevayo  WDYT?

**Comment by hevayo** [comment]
No longer relevant 0.970.0
