### ISSUE TITLE
Can edit the code when debugging the code

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6245]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Jun 30, 2017 at 12:34 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2224_

----

The fields should be disabled.

![debug](https://user-images.githubusercontent.com/1845370/27734742-ec055112-5db9-11e7-9d9e-9fcd6b1e2356.png)

**Comment by hevayo** [comment]
Usually in other editors when you debug you are still allowed to edit the code hence we will not restrict it in composer as well.
