### ISSUE TITLE
Improve navigation from console output

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6246]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Saturday Jul 01, 2017 at 06:11 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2237_

----

Instead of just logging line number in an error output, add an option where line number can be clicked to navigate to the error line. This must be similarly supported in design view.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
