### ISSUE TITLE
Make composer work on mobile browsers

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6247]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Sunday Jul 02, 2017 at 02:51 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2241_

----

Check the compatibility of composer on mobile browsers and fix the issues.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Monday Jul 03, 2017 at 05:08 GMT_

----

Mobile browsers mean? mobile phones or tabs ... because in mobile phones viewing diagram might be bit unrealistic.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dakshika](https://github.com/dakshika)**
_Monday Jul 03, 2017 at 10:41 GMT_

----

IMO we need to support for tabs, not to the mobile

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
