### ISSUE TITLE
Keyword highlighting improvements

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6248]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Jul 06, 2017 at 05:53 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2282_

----

Consider the following sample : 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/1029806/27897150-1aa08736-623c-11e7-9783-f4e68268b084.png">

Here Person, Address and PhoneNumber are structs and hence must be treated as variable types in the same or similar level of importance(highlighting) as primitive variable types (int, boolean, etc).

Such use of `Person p` can appear in multiple forms -- as variable declaration, variable def statements and parameter definitions (arg and return). Hence best is to generalize how we detect this. 

As per discussiong with @kaviththiranga, we can take an approach based on the token stream received by the Antlr Grammar. We can bring the Antlr tokenizing to client side and get the tokens and apply the styling in the ACE editor based on the token type.

For example in the above example, `Person p` can appear as  : 
```
1. Person p;
2. Person p = {};
3. function testFunction(Person p){}
4. function getPerson()(Person)
```
All the Person references are represented as nameReferences in the token stream for the above 4 scenarios.
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/1029806/27897349-691ef5a4-623d-11e7-8929-02b87e8dced3.png">

In the ACE editor, we can bind the styling to this 'nameReference' type as a rule.

**Comment by hevayo** [comment]
This is fixed with new tmLanguage and monarch grammers
