### ISSUE TITLE
[Task] Implement Foreach component for the composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6250]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Friday Jul 14, 2017 at 07:07 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2360_

----

- Implement the Foreach parser and Foreach ui component for the ballerina composer.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NatashaWso2"><img src="https://avatars3.githubusercontent.com/u/13446645?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NatashaWso2](https://github.com/NatashaWso2)**
_Tuesday Nov 14, 2017 at 10:03 GMT_

----

ForEach is not yet implemented

**Comment by NipunaMarcus** [comment]
Foreach support has been added for composer and available in 0.970.0
