### ISSUE TITLE
[ContentAssistance] Suggestions for array types are not available, except string[]

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6251]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Jul 14, 2017 at 10:28 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2368_

----

Pack - ballerina-tools-0.90-SNAPSHOT - 14/07

Suggestions for other array types are not available, except string[]

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/nadeeshaan"><img src="https://avatars3.githubusercontent.com/u/1329674?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nadeeshaan](https://github.com/nadeeshaan)**
_Monday Jul 24, 2017 at 09:27 GMT_

----

Since the array type suggestion does not make sense, we need to remove suggesting the array types. So remove the string[] as well

**Comment by nadeeshaan** [comment]
We have avoided suggesting array types. We only support primitive and user-defined types as suggestions since suggesting arrays as types are not scalable in the long run. Hence closing the issue.
