### ISSUE TITLE
Remove "nameRef" and fix related white space issues.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6253]
<a href="https://github.com/manuranga"><img src="https://avatars0.githubusercontent.com/u/1686124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [manuranga](https://github.com/manuranga)**
_Friday Jul 21, 2017 at 21:20 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2582_

----

**Comment by NipunaMarcus** [comment]
This is fixed in the latest master hence closing this issue.
