### ISSUE TITLE
[Transform] allow using variables indexed variables in transformations

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6254]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Jul 27, 2017 at 07:02 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2633_

----

E.g.

Person p = [....]

When suggesting variables for input/output users must be able to type and use p[5] or p.address, or if json json.address where address is a complex type.

**Comment by keizer619** [comment]
Transformer syntax is remove, hence closing this issue :)
