### ISSUE TITLE
Testarina run and debug support for Composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6255]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Jul 31, 2017 at 12:15 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2643_

----

Testarina programs are run differently (as below) and this cannot be done through the current run and debug implementation of the composer.

`ballerina test testarinaFileName`

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
