### ISSUE TITLE
Annotations are not available in the exported SVG

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6257]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Aug 03, 2017 at 10:39 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2660_

----

Release 0.91

Following is the actual diagram (in left) and downloaded diagram as a SVG. 

![svg1](https://user-images.githubusercontent.com/1845370/28918193-01fedc1a-7866-11e7-959f-8e1dc5176e2a.png)

**Issues**
1. Annotations are not shown. 
2. Alignment issues in the parameters of the function

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Friday Aug 11, 2017 at 05:20 GMT_

----

Diagram export is only considering the SVG element when exporting diagram as png and svg. Annotation details are drawn using HTML which will be excluded in this method as it is not SVG. To include annotations when exporting diagram either we have to implement them using SVG or convert them to SVG during exporting diagram.   This will be discuss further and try to find a solution.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 16:28 GMT_

----

Can still observe in 0.95 release

![32](https://user-images.githubusercontent.com/1845370/32407190-462e6e3a-c1ab-11e7-99a9-d364d2ae0256.png)

**Comment by hevayo** [comment]
Implementation has differed
