### ISSUE TITLE
Struct add field tab control sequence improvements

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6258]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Aug 10, 2017 at 10:25 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2690_

----

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1029806/29166518-443aac2a-7de4-11e7-956b-9ddb979a1298.png">

Now, tab after typing type will navigate to annotation. Since this is the expectation, can we move the control to name editor instead of annotate?

**Comment by hevayo** [comment]
Implementation has differed
