### ISSUE TITLE
[Debug] Debug points are not preserved after refreshing the composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6259]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Aug 11, 2017 at 11:59 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2731_

----

Release 0.91.1

Debug points are not preserved after refreshing the composer

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Thursday Oct 19, 2017 at 15:26 GMT_

----

Observed in the 3rd pack given to QA on 19/10/2017  for the 0.94 release

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
