### ISSUE TITLE
Break-point manager for composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6260]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Aug 11, 2017 at 12:01 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2732_

----

Like in IDEA, it is useful for us to identify where we have put break points etc. by using a break-point manager. Hope this feature can be incorporated in Composer as well.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
