### ISSUE TITLE
[Debugger] Active debug pointer(statement) should be focused while debugging 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6261]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars1.githubusercontent.com/u/6814264?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Friday Aug 11, 2017 at 19:09 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2761_

----

When we debug a larger .bal program in the graphical view, specially when step in and step out diagram is not getting focused to the current/active debug point. It is not getting scrolled automatically.

Step 1
I'm at this last statement.

<img width="1145" alt="screen shot 2017-08-12 at 12 34 48 am" src="https://user-images.githubusercontent.com/6814264/29228119-36488dcc-7ef6-11e7-84ce-c1008640d6cf.png">

Step 2
Clicked "step out" or "step over". I'm still at the same position in the diagram.

<img width="1135" alt="screen shot 2017-08-12 at 12 35 02 am" src="https://user-images.githubusercontent.com/6814264/29228154-51bfda42-7ef6-11e7-991e-62d3a146f204.png">

Step 3
But it should be focussed to following location

<img width="1142" alt="screen shot 2017-08-12 at 12 35 13 am" src="https://user-images.githubusercontent.com/6814264/29228193-731f43ee-7ef6-11e7-8284-98c62544dfb9.png">

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/pahans"><img src="https://avatars2.githubusercontent.com/u/1552869?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pahans](https://github.com/pahans)**
_Thursday Oct 26, 2017 at 06:13 GMT_

----

This should be implemented for source view as well.

**Comment by hevayo** [comment]
Implementation has differed
