### ISSUE TITLE
[ContentAssist] Variables declared below the usage should not appear as suggestions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6266]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Aug 22, 2017 at 13:33 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2837_

----

Release 0.92

**Steps**
1. Declare a variable as int i;
2. Add a while loop above this line and write the condition as "i < 2"

**Issue**
"i" appears as suggestions at step 2

**Comment by nadeeshaan** [comment]
In order to implement this capability, we need to have the position information of the BSymol nodes. Since the current core implementation does not support this we will be adding this as an improvement. We need to implement this behavior as a feature

**Comment by mohanvive** [comment]
Above issue is no longer valid in VSCode plugin. Hence, closing the issue.
