### ISSUE TITLE
[ContentAssist] Inconsistencies in the Content Assistance suggestions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6267]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Aug 23, 2017 at 06:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2880_

----

Pack - 23/08/2017

1. Suggestions that are appearing in the source view are not suggested in the design view
![sug1](https://user-images.githubusercontent.com/1845370/29601261-3867772a-87f8-11e7-83f0-7936752ade3b.png)
![sug2](https://user-images.githubusercontent.com/1845370/29601270-409db44a-87f8-11e7-98f3-920fb275ab9c.png)

2. Different suggestions for Ctrl+Space and starting letter
![sug3](https://user-images.githubusercontent.com/1845370/29601320-8f2ee584-87f8-11e7-8872-e0f992b3b137.png)
![sug4](https://user-images.githubusercontent.com/1845370/29601326-96a09fe2-87f8-11e7-8068-f21c3fa5b726.png)

**Comment by nadeeshaan** [comment]
No longer valid since the implementation has been changed. Hence closing the issue.
