### ISSUE TITLE
[xmlLiterals] Giving syntax errors as \ will be removed

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6268]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Aug 23, 2017 at 07:02 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2888_

----

Pack - 23/08/2017

This given as error as the slash (\) will be removed when you switch to the sources view adding this from the design view

xml x5 = xml `aaa{{v1}}b\{{bb{{v2}}c\}}cc{d{}e}{f{`;

**Comment by hevayo** [comment]
Not relevant, we no longer allow editing statements in design view.
