### ISSUE TITLE
[ContentAssist] HTTP methods are not suggested

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6269]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Aug 23, 2017 at 13:19 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2924_

----

Pack - 23/08/2017

HTTP methods are not suggested in both design and source views

**Comment by hevayo** [comment]
Fixed in 0.970.0
