### ISSUE TITLE
The files should be opened or tabs should be switched when debugging services in a package

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6273]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Aug 28, 2017 at 13:45 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2943_

----

Release 0.93

**Steps**
1. Add debug points in two bal files in a package
eg: eCommerce sample
 
**Issue**
When debugging moves from one bal file to another, the composer does not open the corresponding file or if already opened, move to that bal file. So, the user has to manually switch the files

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
