### ISSUE TITLE
404 for documentation support for some connectors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6274]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Aug 29, 2017 at 06:44 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2951_

----

Release 0.93

No doc support for the following connectors

- Twitter
- LinkedIn
- oauth2
- soap etc

![4042](https://user-images.githubusercontent.com/1845370/29807541-08264352-8cb2-11e7-969a-c483ae2e4854.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Friday Sep 08, 2017 at 08:39 GMT_

----

Documents for these connectors are not yet available. Added issue for Docerina to track the this issue. please refer: https://github.com/ballerinalang/docerina/issues/111

**Comment by hevayo** [comment]
Not relevant for new versions.
