### ISSUE TITLE
Need to scroll a lot horizontally to see the full xml message when debugging

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6275]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Aug 29, 2017 at 09:32 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2954_

----

Release 0.93

Need to scroll a lot horizontally to see the full xml message when there are multiple namespaces

![xml1](https://user-images.githubusercontent.com/1845370/29814447-f7777f44-8cca-11e7-990d-5d46ab5de2e1.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
