### ISSUE TITLE
[Transform] Include a notification area

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6277]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Aug 31, 2017 at 12:45 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2985_

----

Currently transform expanded view uses the global notification area. When there is a half baked scenario (e.g. typing in source view), alerts of transform will popup in source view. To avoid this, introduce a new alert system which is enclosed to transform perspective without using the global notification area. Currently alerts are disabled due to this reason

**Comment by afkham** [comment]
Transformer has been removed so this is no longer valid
