### ISSUE TITLE
[ContentAssist] Variables are not suggested for send and receive

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6278]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Sep 01, 2017 at 09:11 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2988_

----

Release 0.93

![send1](https://user-images.githubusercontent.com/1845370/29963138-71418392-8f23-11e7-9566-5ff5cf7484c8.png)

**Comment by hevayo** [comment]
Not relevant, Implementation has differed
