### ISSUE TITLE
[ContentAssist] No suggestion for the default keyword of default worker

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6279]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Friday Sep 01, 2017 at 09:20 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2989_

----

Release 0.93

![default](https://user-images.githubusercontent.com/1845370/29963518-c2e42d98-8f24-11e7-87b1-56e4d8d1cdb8.png)

**Comment by hevayo** [comment]
Implementation has differed
