### ISSUE TITLE
Issues in the exported images of compact and action views

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6280]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Sep 04, 2017 at 05:40 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2997_

----

Release 0.93

![expimgact](https://user-images.githubusercontent.com/1845370/30013021-8d46398a-9161-11e7-8010-806450d89fd2.png)

![imgcompact](https://user-images.githubusercontent.com/1845370/30013013-82585c10-9161-11e7-8cf4-e4d490f7d093.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Wednesday Sep 06, 2017 at 11:59 GMT_

----

This issue is occurs only on Firefox and it is happening because of css property `dominant-baseline` doesn't work properly in firefox.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
