### ISSUE TITLE
No way to build the program in the composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6282]
<a href="https://github.com/dakshika"><img src="https://avatars2.githubusercontent.com/u/6497326?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dakshika](https://github.com/dakshika)**
_Tuesday Sep 12, 2017 at 09:46 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3049_

----

simply  below command 

ballerina build hello-world.bal -o hello.balx

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
