### ISSUE TITLE
[Language Server] - getBuiltInTypes stuck in Windows

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6283]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars1.githubusercontent.com/u/6814264?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Thursday Sep 14, 2017 at 06:51 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3071_

----

Need to test language server in Windows. specially loading builtin types

**Comment by hevayo** [comment]
Not relevent
