### ISSUE TITLE
Short-cut key to switch the design and source view tabs

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6284]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Sep 20, 2017 at 11:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3098_

----

Just like we switch apps with ALT+Tab, need a short cut key to switch between design and source view tabs. Otherwise, every time we need to switch between the views, we need to click on the tabs.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
