### ISSUE TITLE
Composer cannot show xml literals with indentation and line breaks

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6285]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Sep 21, 2017 at 12:03 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3105_

----

Pack 0.93 (19/09)

**Add the below code segment in the composer**
```
   xml x1 = xml `<book>
                    <name>Sherlock Holmes</name>
                    <author>Sir Arthur Conan Doyle</author>
                  </book>`;
    system:println(x1);
```

**This will be shown like below in the design view**
![xml1](https://user-images.githubusercontent.com/1845370/30694552-216aed2a-9ef2-11e7-96de-f4233ec8883f.png)

**When switched back to the source view**
![xml2](https://user-images.githubusercontent.com/1845370/30694602-5897e1fe-9ef2-11e7-8fe6-97817f9b60f3.png)

**Expected**
Show the xml element just as it is written (with indentation and line breaks)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Thursday Sep 21, 2017 at 12:43 GMT_

----

Same issue for json:
A json written like below will show in one line in the design view and when reformatting
```
json j1 = {"Store": {"@id": "AST", "name": "Anne",
    "address": {"street": "Main", "city": "94"}, "codes": ["4", "8"]}};
```

**Comment by NipunaMarcus** [comment]
closing this hence the issue has been fixed.
