### ISSUE TITLE
[Intermittent] 404 when loading the composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6286]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Sep 27, 2017 at 14:42 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3195_

----

Release 0.93

404 is observed when trying to open the composer

![404](https://user-images.githubusercontent.com/1845370/30919758-f81fe06a-a3bf-11e7-9c33-b26baac685d6.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/manjulaRathnayaka"><img src="https://avatars0.githubusercontent.com/u/3263607?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [manjulaRathnayaka](https://github.com/manjulaRathnayaka)**
_Wednesday Sep 27, 2017 at 15:06 GMT_

----

This happens because load balancer is not updated for newly created ballerina composer URLs. It takes 10seconds to appear. I am working on a fix to identify this and reload the page as a quick fix from load balancer level. To properly fix this usability issue, we have to increase the frequency of load balancer configuration updates.

**Comment by hevayo** [comment]
This issue is no longer relevant.
