### ISSUE TITLE
How to bring up the composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6287]
<a href="https://github.com/shazni"><img src="https://avatars0.githubusercontent.com/u/5644096?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shazni](https://github.com/shazni)**
_Tuesday Oct 03, 2017 at 09:15 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3260_

----

How to run the composer and bring it to the browser is not available in the https://ballerinalang.org/docs/

IMO the documentation on the git page [1] should also be in the website. 

[1] https://github.com/ballerinalang/composer

**Comment by samgnaniah** [comment]
This is covered in our Quick Tour now: https://ballerina.io/learn/quick-tour/

Please close.
