### ISSUE TITLE
Newly added directories while save window is open are not updated

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6288]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Wednesday Oct 04, 2017 at 09:41 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3277_

----

**Steps to Reproduce**

1. Open the composer and create a Bal file.
2. Go to save window and select a directory.
3. Without closing the save window, manually create a directory at any location.
4. Check whether the newly created directory is listed.

**Issue**: The newly created directory is not listed in the save menu.

**Comment by NatashaWso2** [comment]
This is not reproducible in ballerina 0.981.2-SNAPSHOT, so closing this issue.
