### ISSUE TITLE
Add composer run command to start as a background process

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6289]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Wednesday Oct 04, 2017 at 14:23 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3288_

----

Can we add a ./composer run option to start composer as a background process?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
