### ISSUE TITLE
User guide points to Ballerina by example site

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6290]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Monday Oct 09, 2017 at 05:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3346_

----

Version: 0.93

Currently the user guide is pointing to [1]. Rather this should point to a user guide applicable for the composer, which explains the needed steps in composer. The current user guide should be linked as "Language Reference" and not as a user guide.

Apart from above, there should be a quick start referenced from here as well.

[1] https://ballerinalang.org/docs/by-example/

**Comment by samgnaniah** [comment]
This is not relevant anymore as we have migrated to ballerina.io now. Please close.
