### ISSUE TITLE
Syntax highlighting is not done correctly for some sql queries

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6291]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Oct 09, 2017 at 05:35 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3350_

----

Normally syntax of queries are highlighted in green color as it is inside double quotes. But for this query the formatting was not applied.

![query3](https://user-images.githubusercontent.com/1845370/31326398-6ca26afc-ace4-11e7-9ca1-01848fb1d5c5.png)

**Comment by hevayo** [comment]
The issue was raised in composer which deprecated hence closing the issue.
