### ISSUE TITLE
Re-organize given samples in composer and categorize according to complexity

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6292]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Monday Oct 09, 2017 at 05:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3351_

----

Currently the samples mainly contain a set of services and a main function demonstration. The usages of functions, connectors are not displayed. 

A user who is looking to get started, might look at a how to write a service, how to create a main function. A user who already has a bit of an idea but want to know how to achieve a use case by using ballerina. And if we organize our samples in Ballerina to cater this, it will be much useful and will address different level of users who are looking to get something done.

So ideally there should be a starting sample for service and main, and then categorized samples according to complexity that displays various usages of Ballerina.

**Comment by hevayo** [comment]
Fixed in 0.970.0
