### ISSUE TITLE
Long queries cannot be shown correctly in the design view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6294]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Oct 09, 2017 at 06:13 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3355_

----

Only part of the query is displayed and the text box has expanded outside the boundary of the main program as well

![screenshot from 2017-10-09 11-38-57](https://user-images.githubusercontent.com/1845370/31326645-bbe0d246-ace6-11e7-94b0-1cfad136420b.png)

**Comment by hevayo** [comment]
We no longer provide statement editing hence closing the issue.
