### ISSUE TITLE
A query separated into multiple lines is arranged back to a single line when switch to design view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6295]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Oct 09, 2017 at 06:49 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3360_

----

A query separated into multiple lines is arranged back to a single line when switch between design and source view
![query5](https://user-images.githubusercontent.com/1845370/31327270-d9018618-aceb-11e7-8827-f333eaa13f2f.png)

Note the space in between the query. This is where the query was broken to multiple lines
![qyery6](https://user-images.githubusercontent.com/1845370/31327275-df9379d2-aceb-11e7-8a46-4a60a7750cbd.png)

**Comment by hevayo** [comment]
Implementation has differed
