### ISSUE TITLE
Disorted source view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6296]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Monday Oct 09, 2017 at 08:03 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3368_

----

Version: 0.93
Browser: Chrome Version 61.0.3163.100

As shown in the attached image, the source view alignment is broken (at line 10 and line 1). The code has to be aligned well at all levels

**Disorted source view**
![composer_disortedsource](https://user-images.githubusercontent.com/15624590/31329118-36dccf9a-acf6-11e7-92fe-fe320324ccbb.png)

**Relevant design view**
![composer_designview](https://user-images.githubusercontent.com/15624590/31329119-36de24bc-acf6-11e7-9080-91f3d939a520.png)

**Comment by hevayo** [comment]
Implementation has differed
