### ISSUE TITLE
Provide mechanism to disable or enable an element when commented in source

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6298]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Monday Oct 09, 2017 at 10:50 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3382_

----

Version: 0.93
Browser: Chrome Version 61.0.3163.100

Ballerina code lines can be commented out. But when commented, in design view the entire design element dissapears. But it shouldn't be the case. Rather when commented out, the respective element in the designer view should be either disabled or a change of color should happen. Current design is misleading to the user.

**Source view**
![composer_comment_source](https://user-images.githubusercontent.com/15624590/31334811-7a32ff3c-ad0d-11e7-974e-0c8ebde5a1cb.png)

**Design view**
![composer_comment_design](https://user-images.githubusercontent.com/15624590/31334829-8fcb6596-ad0d-11e7-8a3e-7e01dbdd17f8.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Oct 10, 2017 at 04:19 GMT_

----

Marking as severity high as this is degrading user experience

**Comment by hevayo** [comment]
Implementation has differed
