### ISSUE TITLE
Need a proper way to show large content in the debugging variable view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6300]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Oct 09, 2017 at 12:42 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3396_

----

![prop2](https://user-images.githubusercontent.com/1845370/31338567-69d10458-ad1d-11e7-8fa3-7df4f162cf9a.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
