### ISSUE TITLE
[UX] When User adds an attribute and Enters the cursor should automatically switch to the value field

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6303]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 09, 2017 at 14:21 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3406_

----

It's better if we can automatically move the cursor to the value field after adding an attribute to the config element.

![screenshot from 2017-10-09 19-49-54](https://user-images.githubusercontent.com/7681361/31342705-3cbc98a2-ad2b-11e7-9026-2d1a9ac44927.png)

**Comment by hevayo** [comment]
Implementation has differed
