### ISSUE TITLE
Add an option to clear the console window

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6304]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 09, 2017 at 15:34 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3409_

----

can we add an option to clear the console window?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
