### ISSUE TITLE
Is it possible to allow user to run two programs in parallel 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6305]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 09, 2017 at 15:42 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3414_

----

I have two programs 

1. Ballerina Service
2. Ballerina Main Function to invoke the service.

But I Cannot execute these together. Is it possible to allow the user to execute a main function while a service is running?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
