### ISSUE TITLE
Import not added automatically for ballerina.lang.files when a statement added through code

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6307]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Oct 10, 2017 at 06:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3443_

----

Version: 0.93
Browser: Chrome Version 61.0.3163.100

Added the following code snippet through the source view. As shown in the attached image, the import declaration was not added automatically. This is automatically added when being dropped from the library section. But unforunately the below case is a struct definition, so there is no way to add it through the library section.

```files:File file = {path:url};```

![composer_ftpcon](https://user-images.githubusercontent.com/15624590/31372767-f6fd842c-adb4-11e7-8b4c-fe6a17deb5c5.png)

**Comment by hevayo** [comment]
This feature will be supported via LanguageServer.

**Comment by nadeeshaan** [comment]
This has been fixed in the v0.990.0 onwards. Hence closing the issue
