### ISSUE TITLE
Remove http import when relevant configurations for http is removed from ballerina file

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6308]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Oct 10, 2017 at 06:58 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3445_

----

Version: 0.93
Browser: Chrome Version 61.0.3163.100

As an example if the user is using ftp configuration, then the default imported ballerina,net.http will not be of any use. Please remove it as it's added by default when the service component is dropped in. Since the composer imports that explicitly then it should be removed without user interaction if not used.

We will have to redefine the importing mechanism as there are lot of ways where a code can be generated in composer, so that the mechanism handles all these paths.

**Comment by nadeeshaan** [comment]
Issue no longer valid since the editors/IDEs behave as such. Also, removing the import as soon as a relavent statement removed will cause removing and adding the import frequently based on the user's behavior. Hence closing the issue.
