### ISSUE TITLE
No support to enter path/query params according to the correct syntax

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6309]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Oct 10, 2017 at 07:32 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3448_

----

No support from the composer to enter path/query params according to the correct format. If we write partially and check somewhere else for the correct syntax, the previously partially written code will give an error and removed from the text box. This is not user friendly.

**Comment by hevayo** [comment]
Implementation was differed we have removed path adding from the diagram
