### ISSUE TITLE
Tab doesn't get closed for an open file when deleted

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6311]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Oct 10, 2017 at 09:56 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3462_

----

Version: 0.93
Browser: Chrome Version 61.0.3163.100

**Steps**
1. Open a file -> tab will be open
2. Delete the relevant file

**Actual behaviour**
Tab doesn't get closed even though the file is deleted

**Expected behaviour**
Tab should close when the file is deleted

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT, so closing this issue.
