### ISSUE TITLE
Ability to reformat only a given code segment

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6312]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Oct 10, 2017 at 13:54 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3484_

----

Version: 0.93
Browser: Chrome Version 61.0.3163.100

Can we have $subject?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
