### ISSUE TITLE
When undoing the focus should move to the undo location

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6313]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Wednesday Oct 11, 2017 at 09:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3509_

----

In a large file, if you undo we cannot find where the undo is happening. It's better if we can move the focus to the relevant area.

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8827
