### ISSUE TITLE
[Intermittent] Composer crashes Intermittently 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6316]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 12, 2017 at 10:59 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3598_

----

**Environment**
Java 1.8
Browser: Chrome 58.0.3029.110 (64-bit)

![screenshot from 2017-10-12 16-27-16](https://user-images.githubusercontent.com/7681361/31492829-54a0ee14-af6a-11e7-8787-e6f4a9e5bd6f.png)

**Comment by NipunaMarcus** [comment]
This has been fixed in the current version of the composer hence closing the issue.
