### ISSUE TITLE
How to reorder functions from the design view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6318]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 12, 2017 at 13:08 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3638_

----

Is it possible to reorder functions and other elements from the design view?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
