### ISSUE TITLE
Wrong error message when a file is saved to a location without write access

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6320]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Oct 12, 2017 at 16:10 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3675_

----

![27](https://user-images.githubusercontent.com/1845370/31506713-d9aa7636-af95-11e7-8110-635e242a529c.PNG)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9008
