### ISSUE TITLE
Can add Application Arguments from the try-it window

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6321]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 12, 2017 at 16:12 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3676_

----

While the try-it window is open the user can add Application Arguments which doesn't get persisted and doesn't make sense to the user.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
