### ISSUE TITLE
Add auto scroll ability to console

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6322]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 12, 2017 at 16:30 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3680_

----

Can we add auto scroll ability to console?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
