### ISSUE TITLE
Can add break points to every element from source view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6324]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Friday Oct 13, 2017 at 05:33 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3693_

----

![screenshot from 2017-10-13 10-53-23](https://user-images.githubusercontent.com/7681361/31531636-d7a6a6be-b005-11e7-9894-26e2c2bedfa1.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
