### ISSUE TITLE
Change the border color of the selected element

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6325]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 16, 2017 at 12:25 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3763_

----

Can we change the color of the border of a code segment? If e have a large code block e.g: a while loop. It is difficult to recognize the boundary of the loop. Can we change the color when the element is selected?

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Wednesday Nov 15, 2017 at 18:08 GMT_

----

We do have a boundary for the while loop in design view. Are you referring to having another level of highlighting?

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
