### ISSUE TITLE
Can add multiple main methods

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6326]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 16, 2017 at 17:18 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3807_

----

Is there a way to restrict this from the design view?

**Comment by hevayo** [comment]
The intention is not to restrict since a user can add multiple main methods from source view as well. We show the compiler errors once added.
