### ISSUE TITLE
High CPU usage when switching from Design view to source view.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6327]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Tuesday Oct 17, 2017 at 00:18 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3872_

----

I created the following set of services,

import ballerina.net.http;

```
@http:configuration {basePath:"/echo",
    port:8286
}
service<http> echo {

    @http:resourceConfig {
        methods:["POST","GET"],
        path:"/"
    }
    resource echo (http:Request req, http:Response res) {
        string payload = req.getStringPayload();
        res.setStringPayload(payload);
        res.send();
    }
    resource echo2 (http:Request req,http:Response res) {
    }
    resource echo3 (http:Request req,http:Response res) {
    }
    resource echo4 (http:Request req,http:Response res) {
    }
    resource echo5 (http:Request req,http:Response res) {
    }
    resource echo6 (http:Request req,http:Response res) {
    }
    resource echo7 (http:Request req,http:Response res) {
    }
    resource echo8 (http:Request req,http:Response res) {
    }
    resource echo9 (http:Request req,http:Response res) {
    }
    resource echo10 (http:Request req,http:Response res) {
    }
    
}
@http:configuration {
}
service<http> service1 {
    resource echo1 (http:Request req,http:Response res) {
    }
    resource echo2 (http:Request req,http:Response res) {
    }
    resource echo3 (http:Request req,http:Response res) {
    }
}
```
When I swich from the Design view to source view the CPU usage goes up, around 80-100%.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Wednesday Nov 15, 2017 at 17:21 GMT_

----

Will place this issue on-hold as this cannot be reproduced.

**Comment by hevayo** [comment]
This issue is no longer observable in latest releases 0.970.0+ hence closing the issue.
