### ISSUE TITLE
Some of the list menus have layout issues

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6328]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Oct 17, 2017 at 05:30 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3884_

----

Windows-firefox
![31](https://user-images.githubusercontent.com/1845370/31648070-6857a246-b329-11e7-9771-e25b119a6817.PNG)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Wednesday Nov 15, 2017 at 17:31 GMT_

----

Also as seen on above, the border of the file explorer crosses the menu in other OS and browsers. 
<img width="196" alt="image" src="https://user-images.githubusercontent.com/1029806/32850696-c2822c38-ca2a-11e7-9177-b0c9858a493a.png">

**Comment by hevayo** [comment]
Fixed in 0.975.0
