### ISSUE TITLE
Try-it cannot identify all the services that are up and running in a package

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6330]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Oct 17, 2017 at 09:51 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3908_

----

1. Have multiple services in a package
2. Run one file from the composer. All the services should be up and running
3. Go to try-it and verify the services drop down

**Issue**
Only the service that the user ran is visible in the drop donw

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Monday Nov 06, 2017 at 09:19 GMT_

----

Observed in 0.95 release as well

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Wednesday Nov 15, 2017 at 17:16 GMT_

----

Hi Dilini, are you referring to having a Ballerina program where services are in different bal files?

If it is multiple services in one bal file, this is working at the moment.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1029806/32849980-ade7ba1a-ca28-11e7-8618-360cccea9a33.png">

We will revisit the package scenario with new package improvements that are under development

**Comment by pahans** [comment]
Fixed in 0.973.0
