### ISSUE TITLE
Can add code while the code block is minimized

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6331]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 19, 2017 at 11:28 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3995_

----

![screenshot from 2017-10-19 16-56-34](https://user-images.githubusercontent.com/7681361/31768818-97dbe9e8-b4ee-11e7-85df-c51fbf3cf8c2.png)

**Comment by hevayo** [comment]
Fixed in 0.970.0
