### ISSUE TITLE
Minimized code blocks are expanded in split view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6332]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 19, 2017 at 11:33 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3997_

----

The behavior in slipt view source and source view is inconsistent.
![screenshot from 2017-10-19 17-02-11](https://user-images.githubusercontent.com/7681361/31769006-6b4c2360-b4ef-11e7-985b-09ffec5e90fc.png)

![screenshot from 2017-10-19 17-02-22](https://user-images.githubusercontent.com/7681361/31769009-6cb2c0a6-b4ef-11e7-86f6-b10b39ca23a2.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
