### ISSUE TITLE
Syntax highlighting doesn't work when declared across multiple lines

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6333]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 19, 2017 at 11:51 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4001_

----

![screenshot from 2017-10-19 17-16-03](https://user-images.githubusercontent.com/7681361/31769554-cfe810de-b4f1-11e7-8b94-555f66250e78.png)

**Comment by hevayo** [comment]
Fixed in 0.970.0
