### ISSUE TITLE
Wrong error mesage when a native function is added

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6334]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Oct 19, 2017 at 12:07 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4005_

----

This error is not meaningful
![11](https://user-images.githubusercontent.com/1845370/31770134-182c914c-b4f4-11e7-84a7-234b6776a3b0.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Thursday Oct 19, 2017 at 15:40 GMT_

----

This is applicable for var type
![28](https://user-images.githubusercontent.com/1845370/31779840-b3ad37a8-b511-11e7-82d8-df2088b1c6ca.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Tuesday Oct 24, 2017 at 14:43 GMT_

----

This is because if invalid scope check in trasform. Closing this issue to track with https://github.com/ballerinalang/composer/issues/3898

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT, so closing this issue.
