### ISSUE TITLE
Differentiate the newline character in syntax highlighting

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6335]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Thursday Oct 19, 2017 at 12:13 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4007_

----

![screenshot from 2017-10-19 17-42-41](https://user-images.githubusercontent.com/7681361/31770322-f743df3e-b4f4-11e7-934a-3ad84a9e8e67.png)

**Comment by roonyh** [comment]
Escaped characters within strings are differentiated by syntax highlighting for both composer and vscode now.

![image](https://user-images.githubusercontent.com/3872221/45157625-52e02c00-b1ff-11e8-9f36-9e57511bb69e.png)
![image](https://user-images.githubusercontent.com/3872221/45157686-7e631680-b1ff-11e8-9443-af77eeb793f0.png)
