### ISSUE TITLE
Code alignment is disorted when transaction block is placed inside try-catch

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6336]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Oct 19, 2017 at 12:15 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4008_

----

Please see the attached image. The code generation is disorted when transaction is placed inside try-catch

![com_0 94_4](https://user-images.githubusercontent.com/15624590/31770380-525a25e0-b4f5-11e7-8b66-7d4495b433ce.png)

**Comment by NatashaWso2** [comment]
This issue is not reproducible in 0.981.2-SNAPSHOT so closing this issue.
