### ISSUE TITLE
Provide statment box default given statement without syntax errors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6337]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Oct 19, 2017 at 12:36 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4011_

----

As an example when the updateWithGeneratedKeys action of sql connector is dropped in following syntax is generated
```
var var1,var2 = mysqlConn.updateWithGeneratedKeys("",{},{});
```
But as shown in the attached image, it generates syntax  errors. Since we are generating this code for the user, it's better to provide a code segment that doesn't contain syntax errors since a user will follow the given code snippet.

![com_0 94_trans_5](https://user-images.githubusercontent.com/15624590/31771042-2efe59ce-b4f8-11e7-9527-c612f7e19d80.png)

**Comment by NatashaWso2** [comment]
Closing this issue since this is not valid now
