### ISSUE TITLE
[Intermittent] A new frame is added for every line stepped over

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6338]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Oct 19, 2017 at 12:38 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4013_

----

![14](https://user-images.githubusercontent.com/1845370/31771084-5bd97186-b4f8-11e7-9387-793f76b74568.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/pahans"><img src="https://avatars2.githubusercontent.com/u/1552869?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pahans](https://github.com/pahans)**
_Wednesday Oct 25, 2017 at 19:16 GMT_

----

related to https://github.com/ballerinalang/composer/issues/4016

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this.
