### ISSUE TITLE
Resource config: second http method is not added correctly from design view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6339]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Oct 19, 2017 at 13:26 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4025_

----

Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

As shown in the below image, when adding the second http method it's added without the double quotes.

![com_0 94_trans_8](https://user-images.githubusercontent.com/15624590/31773036-1c38f8ba-b4ff-11e7-8288-6e16e596448a.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/hevayo"><img src="https://avatars0.githubusercontent.com/u/323846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hevayo](https://github.com/hevayo)**
_Friday Oct 20, 2017 at 05:20 GMT_

----

Hi 
Here the user is capable of providing a variable identifier instead of a string. So increase of providing a string user has to explicitly type the enclosing quotes. 

will reduce the severity of this issue due to above and will keep this open till we find a solution for the usability issue.

Thanks
Jo

**Comment by hevayo** [comment]
Implementation has differed we no longer have a annotation UI.
