### ISSUE TITLE
Debug point get removed when statement is changed

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6340]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Oct 19, 2017 at 15:33 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4044_

----

Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Steps**
1. Drop in an assignment box
2. Put in an assignment
3. Add a debug point
4. Change the assignment

The debug point get removed.

**Comment by hevayo** [comment]
Implementation has differed we no longer have graphical debugging.
