### ISSUE TITLE
Debug point is able to be added to a non executable code 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6341]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Oct 19, 2017 at 15:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4046_

----

Currently debug point is able to be added to a non executable code as a variable declaration. This should be fixed

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [erandidesilva](https://github.com/erandidesilva)**
_Friday Oct 20, 2017 at 06:54 GMT_

----

Debug is hit on a transaction block start as well. Since this is not executable, we should not have a debug on this.

**Comment by pahans** [comment]
Closing in favour of https://github.com/ballerina-platform/ballerina-lang/issues/6324
