### ISSUE TITLE
Generated syntax with HTTP connection Options are not readable 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6342]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Friday Oct 20, 2017 at 05:19 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4055_

----

If you add HTTP options for HTTP connector it generates the following syntax, Which is not readable.

`http:ClientConnector __endpoint1 = create http:ClientConnector("loclhost",{port:2,endpointTimeout:0,followRedirects: {enabled:true,maxCount:2},ssl: {trustStoreFile:"adadsdsdad",trustStorePassword:"dsdada",keyStoreFile:"adadsdadad",keyStorePassword:"aas"}});`

![screenshot from 2017-10-20 10-49-02](https://user-images.githubusercontent.com/7681361/31806270-4e7fd354-b584-11e7-9d13-f35512f2ad0c.png)

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this issue.
