### ISSUE TITLE
Documentation tabs are not persisted

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6343]
<a href="https://github.com/roonyh"><img src="https://avatars0.githubusercontent.com/u/3872221?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roonyh](https://github.com/roonyh)**
_Friday Oct 20, 2017 at 05:58 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4060_

----

* Open several documentation tabs
* Refresh the page
* Welcome page rendered in place of active documentation tab, other doc tabs vanish.

**Comment by hevayo** [comment]
Implementation has differed we do not have documentation tab.
