### ISSUE TITLE
Provide support for @doc annotations for the properties defined in the property window for  services and connectors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6344]
<a href="https://github.com/NatashaWso2"><img src="https://avatars3.githubusercontent.com/u/13446645?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NatashaWso2](https://github.com/NatashaWso2)**
_Friday Oct 20, 2017 at 06:27 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4065_

----

We need to have @doc annotations for the properties provided in the property window.  These @doc annotations would be used to populate the placeholders, labels and the options (if its a selection) of the property inputs. 

This feature fixes : #3994, #3990, #3846, #4054, #4052 , #4256 , #4358 , #4553

**Comment by hevayo** [comment]
Implementation has differed we no longer have the property editor.
