### ISSUE TITLE
Refactor Fragment Util to have Parse functions by removing create fragment functions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6348]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Friday Oct 20, 2017 at 10:59 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4093_

----

Refactor the FragmentUtil class by replacing ex:- createReturnParameterFragment() to be parseReturnParameterFragment()

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
