### ISSUE TITLE
Closing API docs does't bring back the focus to the working tab

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6349]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Sunday Oct 22, 2017 at 06:34 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4128_

----

**Comment by hevayo** [comment]
Implementation has differed we no longer have API docs.
