### ISSUE TITLE
No errors are shown when invalid packages are added

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6350]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 23, 2017 at 06:54 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4140_

----

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NatashaWso2"><img src="https://avatars3.githubusercontent.com/u/13446645?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NatashaWso2](https://github.com/NatashaWso2)**
_Friday Nov 10, 2017 at 11:12 GMT_

----

Closed this issue by mistake, so reopening it

**Comment by hevayo** [comment]
Fixed in 0.970.0
