### ISSUE TITLE
Response of the service goes to a different client

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6351]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Oct 23, 2017 at 08:19 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4141_

----

Release 0.94
1. Start the echo service from browser1
2. Start the same service from a different browser (browser2). An error will say the address is already in use and terminate the service
3. Go to the "try it" from the service that is running in browser1 and send a message

**Issue**
The response of the message will be shown in the console of browser2. Also, you won't be able to stop the running service as well. Need to kill the process

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
