### ISSUE TITLE
Error when a struct is mapped to a struct

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6352]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Tuesday Oct 24, 2017 at 06:36 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4153_

----

Error when a struct is mapped to a struct
![7](https://user-images.githubusercontent.com/1845370/31927885-90e68314-b8b3-11e7-9fe5-47b70d898b83.png)

**Comment by hevayo** [comment]
Implementation is differed we no longer have transformer
