### ISSUE TITLE
Give option to choose running the service or application when have ballerina file with both main and service

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6353]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Tuesday Oct 24, 2017 at 08:06 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4157_

----

User should be give a option to run a ballerina file which contain a service and a main function and choose which one to run, application or the service.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
