### ISSUE TITLE
[Transform] Support dynamic casting/conversion

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6354]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Wednesday Oct 25, 2017 at 10:19 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4183_

----

- Explicit safe casting : struct => map
- Struct to struct casting
- Json to json casting

**Comment by keizer619** [comment]
Transformer syntax is removed, hence closing this issue
