### ISSUE TITLE
Update welcome page screenshots

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6356]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Saturday Oct 28, 2017 at 02:24 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4229_

----

Sample screenshots have to be updated or generated.

**Comment by hevayo** [comment]
Differed
