### ISSUE TITLE
Formatting issues when adding new variables giving syntax errors in transform

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6357]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Sunday Oct 29, 2017 at 06:11 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4270_

----

Browser : Firefox
**Steps**
1. Open the struct transform sample
2. Go to the transform view
3. Add a new variable

**Issue**
Formatting issues when adding new variables giving syntax errors in transform

**Before**
![38](https://user-images.githubusercontent.com/1845370/32141112-c3eb2f10-bc9d-11e7-82b9-cd7f779dfadd.png)
**After adding the variable**
![39](https://user-images.githubusercontent.com/1845370/32141114-d38b93ce-bc9d-11e7-9804-9bab015e8ecd.png)

**Comment by keizer619** [comment]
Transformer syntax is removed, hence closing this issue
