### ISSUE TITLE
Opening a bal with wrong package will result getting stuck in 'loading'

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6358]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Monday Oct 30, 2017 at 00:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4272_

----

Since it makes users clueless, we need to at least provide an error or warning message. Please check the following from trying to open twitter connector. Without the package, it opens without an issue. 

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/1029806/32150180-5d4d9430-bd35-11e7-9ec2-60b0263f7080.png">

**Comment by hevayo** [comment]
Fixed in 0.970.0
