### ISSUE TITLE
Anonymous Struct support in Composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6360]
<a href="https://github.com/keizer619"><img src="https://avatars0.githubusercontent.com/u/2918812?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [keizer619](https://github.com/keizer619)**
_Monday Oct 30, 2017 at 06:57 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4287_

----

Need to support Anonymous Struct in transform. It could be used in several levels, we need to support adding them from UI and generate UI from the source.

1. As a Struct field.
```
struct Person {
    string name;
    struct { string no; string lane; string city; } address;
}
```
2. As a variable type
```
function testFunc2() {
    struct { string no; string lane; string city; } address;
}

```
3. As a function parameter type
```
function testFunc1(struct { string no; string lane; string city; } address2) {
  
}
```

**Comment by keizer619** [comment]
We don't have anonymous structs anymore and we are not showing object in the diagrams, hence closing this issue
