### ISSUE TITLE
[Transform] Operator Lattice for Mapping

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6362]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Monday Oct 30, 2017 at 10:08 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4297_

----

- [x] Removing operator mappings
- [ ] Create mapping
- [ ] Casting mappings

**Comment by keizer619** [comment]
Transformer syntax is remove, hence closing this issue
