### ISSUE TITLE
Implementing HTTP Trace log UI 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6363]
<a href="https://github.com/pahans"><img src="https://avatars2.githubusercontent.com/u/1552869?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pahans](https://github.com/pahans)**
_Monday Oct 30, 2017 at 12:10 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4301_

----

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/bkLIecHwhcM/wgYwt75IAQAJ

**Comment by hevayo** [comment]
Available from 0.970.0
