### ISSUE TITLE
Improve program directory related experience 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6364]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Oct 31, 2017 at 03:12 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4306_

----

- When a user tries to open a packaged file within a program dir, ask whether user wants to open the program dir too and open upon confirmation.
- When a user adds a package to a file for the first time,
           - If it's a new file which not yet persisted, upon save, in save dialog, show a check box with message that we need to create the sub folder for package structure.
           - if it's file which is already saved, display an alert with same message and provide a btn to create folder structure and move file there
- when a user changes the package of a opened file, ask and move file to correct directory
- provide a wizard to create a file within program dir and a package

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Tuesday Oct 31, 2017 at 05:08 GMT_

----

Also kavith we need Rename and Sync file structure from the disk functionality to be added to the composer.
Related issues: 
#4253 : After renaming a directory cannot run a program
#1147 : Improve File or Folder open UI
#885 : Open more than one file by selecting multiple bal file at a time
#1663 : Auto refresh folders when users open files with 'Open File Explorer' button
#4609 : Composer doesn't detect file changes from file system

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Wednesday Nov 01, 2017 at 06:24 GMT_

----

@NipunaMarcus, WDY mean by sync file structure?

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Thursday Nov 02, 2017 at 04:59 GMT_

----

@kaviththiranga  Mean when refresh the project explorer we should be able to see added files from outside of the composer or renamed directory.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Nov 27, 2017 at 10:31 GMT_

----

Completed:
When a user tries to open a packaged file within a program dir, ask whether user wants to open the program dir too and open upon confirmation.

![asknopen-program-dir](https://user-images.githubusercontent.com/1505855/33262464-57acb124-d38c-11e7-883e-2e7fbaea9425.gif)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
