### ISSUE TITLE
Fix Launcher in windows - folder where path exceeds 256 chars

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6365]
<a href="https://github.com/pahans"><img src="https://avatars2.githubusercontent.com/u/1552869?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pahans](https://github.com/pahans)**
_Wednesday Nov 01, 2017 at 09:19 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4333_

----

![](https://lh3.googleusercontent.com/-5iS4uCMPMIo/Wff9b4-liRI/AAAAAAAARns/XiSxdkqKtzkyZ8JNZsqpZNnfnFNe6TwzgCL0BGAYYCw/h1080/Capture.PNG)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/pahans"><img src="https://avatars2.githubusercontent.com/u/1552869?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pahans](https://github.com/pahans)**
_Friday Nov 03, 2017 at 05:07 GMT_

----

This only occurs when running a file in a folder where path exceeds 256 chars. droped the severity since this is an edge case

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
