### ISSUE TITLE
Collapse the code when collapsable constructs are collapsed

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6366]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Nov 02, 2017 at 07:17 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4347_

----

1. Add a main function and code within it
2. Collapse the main function in the design view

**Improvement**
Collapse the code in the source view as well. Support vise-versa

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
