### ISSUE TITLE
Status of the constructs (expanded/collapsed) should be preserved across sessions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6368]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Nov 02, 2017 at 07:25 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4349_

----

1. Collapse the functions in a program
2. Refresh the page

**Expected**
The collapsed functions should be in collapsed state after page refresh

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
