### ISSUE TITLE
Documentation for imported bres

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6369]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Nov 02, 2017 at 10:08 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4359_

----

Need a way to show documentation for imported libs in composer

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Friday Nov 03, 2017 at 03:03 GMT_

----

Let's provide documentation for importing docs and libs.

**Comment by hevayo** [comment]
Implementation has differed we no longer have the library tool palette.
