### ISSUE TITLE
Can't we determine which type of service is running http or ws?

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6371]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 03:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4409_

----

Can't we determine which type of service is running; http or ws? (without showing HTTP/WS server)
![7](https://user-images.githubusercontent.com/1845370/32401961-5e35f61c-c140-11e7-84af-5567d601698f.png)

**Comment by shafreenAnfar** [comment]
I think the log is correct because ballerina transport support both protocols on the same port at the same time. It is not HTTP or WS, but instead HTTP and WS. Hence, closing the issue.
