### ISSUE TITLE
[HTTP] Wrong reference type shown for functions that is supposed to manipulate the response

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6372]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Saturday Nov 04, 2017 at 04:02 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4411_

----

As shown in the attached image, the reference type shown for setStringPayload is of type request. But the setStringPayload is ususally used with response manipulation. For default generated code, the reference type should be selected according to the manipulation whether its response or request

![com_0 95_2](https://user-images.githubusercontent.com/15624590/32402125-17e2153a-c143-11e7-831b-ee38b3cb1fff.png)

**Comment by hevayo** [comment]
Implementation has differed
