### ISSUE TITLE
[HTTP] Source generated for endpoint should be properly formatted

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6373]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Saturday Nov 04, 2017 at 04:11 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4415_

----

Current formatting of endpoint when dropped in is as given in below image. It should be properly formatted.

![com_0 95_3](https://user-images.githubusercontent.com/15624590/32402175-461aba82-c144-11e7-928e-e20c32dd1beb.png)

**Comment by NipunaMarcus** [comment]
This has been fixed with the initial formatting support hence closing this issue.
