### ISSUE TITLE
[Try-it] Not working properly when two services in the same package are running in different ports

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6374]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Saturday Nov 04, 2017 at 04:58 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4419_

----

Steps 
Following services have to be in the same package
1. Create service1 with port 9090
2. Create service2 with port 9091
3. Deploy the services

When try it opened,  it's always taking the port of one service out of the two, and shows only details of that service all the time

Samples attached 
[serviceTests.zip](https://github.com/ballerinalang/composer/files/1442941/serviceTests.zip)

![com_0 95_6](https://user-images.githubusercontent.com/15624590/32402474-a94b8d06-c14a-11e7-99b3-4aef73b6e0f9.png)
![com_0 95_7](https://user-images.githubusercontent.com/15624590/32402475-a97c29a2-c14a-11e7-817d-114b3f5333fd.png)

**Comment by pahans** [comment]
Fixed in 0.973.0
