### ISSUE TITLE
Cannot add a anon struct in structs from the design view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6375]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 05:15 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4421_

----

1. Add a struct
2. Try to add the following from the design view
`struct {int d; int b;}test;`

**Issue**
Cannot add a anon struct in structs from the design view

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/keizer619"><img src="https://avatars0.githubusercontent.com/u/2918812?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [keizer619](https://github.com/keizer619)**
_Tuesday Nov 21, 2017 at 09:12 GMT_

----

We need to do a complete revamp in the struct view to support this as in following task
https://github.com/ballerinalang/composer/issues/4287

**Comment by hevayo** [comment]
Implementation has differed we no longer show the struct diagram.
