### ISSUE TITLE
Error messages are overlapped in transform view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6376]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 07:26 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4438_

----

![18](https://user-images.githubusercontent.com/1845370/32403438-779bd2c4-c15f-11e7-95ca-9bdd9e13a77e.png)

**Comment by keizer619** [comment]
Transformer syntax is removed, hence closing this issue
