### ISSUE TITLE
Improvements in run/debugging

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6377]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 13:30 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4451_

----

1. Need to click exactly on the expand icon (triangle) to expand the view
2. The "Toggle Console" and "Launch config dialog" is not much visible to the user
3. Does not directly give the idea that arguments can be configured from the "Show Launch config dialog" because of the tool tip given
![28](https://user-images.githubusercontent.com/1845370/32405796-f6ec7006-c191-11e7-83fc-1610c0214f56.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
