### ISSUE TITLE
No option to export the diagram of transform view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6378]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 16:35 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4455_

----

When there is a transform, there is no option for an user to export the diagram of the transform view. It's nice to have it

**Comment by keizer619** [comment]
Transformer syntax is removed, hence closing this issue
