### ISSUE TITLE
Debug hit highlighting should go away when the flow is finish

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6379]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Sunday Nov 05, 2017 at 09:54 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4464_

----

This happens in split view. 

![screenshot from 2017-11-05 15-21-20](https://user-images.githubusercontent.com/7681361/32413701-4b1daa22-c23d-11e7-8e05-2c9713145efe.png)

**Comment by pahans** [comment]
Fixed in master
