### ISSUE TITLE
Properties in previous debug session are shown in the new session

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6380]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Sunday Nov 05, 2017 at 09:59 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4467_

----

![screenshot from 2017-11-05 15-28-27](https://user-images.githubusercontent.com/7681361/32413743-0af2661c-c23e-11e7-8c2d-35e393394460.png)

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9715
