### ISSUE TITLE
Run Option in the left pane is enabled although a program is not selected

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6381]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Sunday Nov 05, 2017 at 10:07 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4468_

----

![screenshot from 2017-11-05 15-36-25](https://user-images.githubusercontent.com/7681361/32413796-3191819e-c23f-11e7-8921-a9658dd9e68c.png)

**Comment by NatashaWso2** [comment]
This is not reproducible in ballerina 0.981.2-SNAPSHOT, so closing this issue
