### ISSUE TITLE
Debug points are not synced between source and design

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6382]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Sunday Nov 05, 2017 at 10:22 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4470_

----

After adding some debug points, if you add some code from source(split view).The debug points get out of sync.

![screenshot from 2017-11-05 15-50-05](https://user-images.githubusercontent.com/7681361/32413923-46896bb4-c241-11e7-9afc-6aa2f7bbf45f.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
