### ISSUE TITLE
Debug point doesn't  move when a run-time error is encountered

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6383]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Sunday Nov 05, 2017 at 10:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4472_

----

![screenshot from 2017-11-05 16-16-38](https://user-images.githubusercontent.com/7681361/32414061-c6daa7a8-c244-11e7-8ff3-8608c4d60d86.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Thursday Nov 09, 2017 at 06:16 GMT_

----

IMO program should terminate itself if the error is not handled when debugging. 
@pahans WDYT?

**Comment by pahans** [comment]
closing in favor of https://github.com/ballerina-platform/ballerina-lang/issues/5130
