### ISSUE TITLE
Generated programs by importing swagger definitions seems invalid

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6386]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Nov 06, 2017 at 01:52 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4489_

----

![screenshot from 2017-11-06 07-21-42](https://user-images.githubusercontent.com/7681361/32421972-2d89459e-c2c3-11e7-9c5d-6a1f3379a204.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/nadeeshaan"><img src="https://avatars3.githubusercontent.com/u/1329674?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nadeeshaan](https://github.com/nadeeshaan)**
_Monday Nov 06, 2017 at 06:03 GMT_

----

@yasassri can you share the swagger file

**Comment by hevayo** [comment]
Duplicate
