### ISSUE TITLE
Cannot access the option list in the action view where "Hidden Code" text is

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6387]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Nov 06, 2017 at 02:26 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4495_

----

Cannot access the option list (debug/delete etc) in the action view where "Hidden Code" text is.
![44](https://user-images.githubusercontent.com/1845370/32422651-8456558e-c2c7-11e7-9a52-6b2fcdce74ba.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Nov 06, 2017 at 02:28 GMT_

----

@dilinisg In action view, hidden code meant to be like that

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Nov 06, 2017 at 02:30 GMT_

----

user has to switch to default view to work with hidden nodes. This is the expected behaviour

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/nadeeshaan"><img src="https://avatars3.githubusercontent.com/u/1329674?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nadeeshaan](https://github.com/nadeeshaan)**
_Monday Nov 06, 2017 at 09:35 GMT_

----

Closing the issue based on the previous comment

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Monday Nov 06, 2017 at 11:18 GMT_

----

Hi all,
I think you have misunderstood what I meant. What I wanted to say is the option list of the first statement (var nameString, _ = ...) is covered from the label "Hidden Text". Hence, we cannot debug that statement. Reopening the issue

**Comment by hevayo** [comment]
Implementation has differed we no longer support debugging in diagram hence closing the issue.
