### ISSUE TITLE
clean up distro - some files are named native.bal and some natives.bal

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6388]
<a href="https://github.com/sanjiva"><img src="https://avatars1.githubusercontent.com/u/2355900?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sanjiva](https://github.com/sanjiva)**
_Monday Nov 06, 2017 at 07:43 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4509_

----

I saw these two with native.bal:

      385  11-06-2017 00:52   ballerina-tools-0.95.0/src/ballerina/mock/native.bal
      227  11-06-2017 00:52   ballerina-tools-0.95.0/src/ballerina/test/native.bal

We need to be consistent; even if there's only one it should be natives.bal.

**Comment by riyafa** [comment]
There is only this [file](https://github.com/ballerina-platform/ballerina-lang/blob/master/misc/testerina/modules/testerina-core/src/main/ballerina/test/native.bal) with the `native.bal` name in testerina. @nirmal070125  please fix this.
