### ISSUE TITLE
Unresolved package name error when a package is imported and used

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6390]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Nov 09, 2017 at 10:49 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4559_

----

![74](https://user-images.githubusercontent.com/1845370/32601732-ac84c2d0-c569-11e7-933d-e51a19962b9a.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Jan 02, 2018 at 04:45 GMT_

----

@dilinisg , is this package under the same program directory?

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Tuesday Jan 02, 2018 at 05:04 GMT_

----

@kaviththiranga - yes same directory

**Comment by hevayo** [comment]
Unable to reproduce in 0.975.0
