### ISSUE TITLE
OutOfMemoryError in composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6391]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Nov 09, 2017 at 11:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4562_

----

Could not access the composer from the browser. The following error was thrown from the back-end.
`./composer: line 206:  4685 Killed                  $JAVACMD -Xms256m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="$BAL_COMPOSER_HOME/logs/heap-dump-tool.hprof" -Djava.util.logging.config.file="$BAL_COMPOSER_HOME/bre/conf/composer-logging.properties" $JAVA_OPTS -classpath "$COMPOSER_CLASSPATH" -Djava.io.tmpdir="$BAL_COMPOSER_HOME/tmp" -Djava.command="$JAVACMD" -Dballerina.home="$BAL_COMPOSER_HOME" -Dbal.composer.home="$BAL_COMPOSER_HOME" -Djava.security.egd=file:/dev/./urandom -Dfile.encoding=UTF8 -Dcomposer.port=9091 -DenableCloud=false -Dworkspace.port=8289 -Dtransports.netty.conf=./resources/composer/services/netty-transports.yml -Dmsf4j.conf=./resources/composer/services/deployment.yaml org.ballerinalang.composer.service.workspace.app.WorkspaceServiceRunner $@
`

No heap dump was available in $BAL_COMPOSER_HOME/logs/heap-dump-tool.hprof location

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Friday Nov 24, 2017 at 11:48 GMT_

----

Is this happened on the 0.95.1? if this happened again please put the code that you were working on so we can try to reproduce.

**Comment by pahans** [comment]
Could not reproduce this issue.
