### ISSUE TITLE
Theme miss match in the http configuration property window

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6392]
<a href="https://github.com/srsharon"><img src="https://avatars0.githubusercontent.com/u/10986966?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Friday Nov 10, 2017 at 08:55 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4565_

----

![image](https://user-images.githubusercontent.com/10986966/32650155-b779bcf4-c622-11e7-937f-a81526a5951b.png)

**Comment by hevayo** [comment]
Implementation has differed
