### ISSUE TITLE
Highlight diagram and code in split view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6393]
<a href="https://github.com/lahirus"><img src="https://avatars2.githubusercontent.com/u/3665108?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lahirus](https://github.com/lahirus)**
_Friday Nov 10, 2017 at 21:10 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4572_

----

This is a nice to have feature.
We can highlight each other when the composer is viewed in split view.
i.e.,
Highlight the relevant part of the diagram when we mouse over a line of code
Highlight the relevant line of code when we mouse over a part of the diagram

**Comment by prabushi** [comment]
Issue moved to [ballerina-platform/plugin-vscode #35](https://github.com/ballerina-platform/plugin-vscode/issues/35) via [**ZenHub**](https://www.zenhub.com/)
