### ISSUE TITLE
Reformat issue in structs

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6397]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Monday Nov 13, 2017 at 18:21 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4585_

----

```
struct Person {
    string name;
    string age;
}
```

gets formatted as,

```
struct Person {string name;string age;
}
```

**Comment by hevayo** [comment]
Implementation differed
