### ISSUE TITLE
[HTTPClient] Client creation statement should be single lined

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6398]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Tuesday Nov 14, 2017 at 06:02 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4587_

----

As shown in the below image, the HTTPClient creation statement is broken to two lines. Ideally this should be generated to be in the same line unless a specific length is exceeded.

![composer_1](https://user-images.githubusercontent.com/15624590/32765202-66a4f6c6-c92f-11e7-8187-a2f6ac70138f.png)

**Comment by hevayo** [comment]
Implementation has differed
