### ISSUE TITLE
Remote debug instructions are not clear

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6400]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Thursday Nov 16, 2017 at 06:46 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4617_

----

**Description:**
Looking at the below dialog, it is not clear what are the steps to perform remote debug. We should explain that the command must be executed and the url is of websocket must be copied to the text box. 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1029806/32877484-b096f53e-ca99-11e7-9ff5-61374f94b120.png">

**Affected Product Version:** 0.95.0

**OS, DB, other environment details and versions:**    OSX 10.13.1 (17B48), Google Chrome 62.0.3202.94 

**Steps to reproduce:**

1. Open any bal file
2. Click on debug pane
3. Click on remote debug option.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
