### ISSUE TITLE
[Improvement] Provide git support in composer

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6402]
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Friday Nov 17, 2017 at 07:57 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4639_

----

When switching between branch1 and branch2, currently the composer does not load the files accordingly. Since switching may cause some changes in files, it's better to reflect this in composer. Hence it would be good to provide git support by reloading files automatically when a change is detected.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Monday Nov 20, 2017 at 05:46 GMT_

----

There is a file sync menu item in the file explorer menu. User can use that to sync the project with the file system's latest updates. We will work on the feature for reloading project structure automatically.

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
