### ISSUE TITLE
Descriptions are overlapping in swagger definition 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6403]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Saturday Nov 18, 2017 at 10:30 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4656_

----

**Description:**
![screenshot from 2017-11-18 15-58-20](https://user-images.githubusercontent.com/7681361/32979343-6ba65082-cc79-11e7-8d03-03bcd201d15d.png)

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
FireFox

**Comment by hevayo** [comment]
Implementation has differed
