### ISSUE TITLE
Values not cleared from the previous debug sessions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6406]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Saturday Nov 18, 2017 at 11:56 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4661_

----

**Description:**
![screenshot from 2017-11-18 17-18-44](https://user-images.githubusercontent.com/7681361/32980027-6a243574-cc85-11e7-8ed5-16467135395a.png)
**Suggested Labels:**

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
FireFox

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this issue.
