### ISSUE TITLE
Inconsistency in code formatiing when adding connectors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6408]
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Saturday Nov 18, 2017 at 12:41 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4665_

----

**Description:**
![screenshot from 2017-11-18 17-56-46](https://user-images.githubusercontent.com/7681361/32980304-ea30529e-cc89-11e7-801e-38cdf5b1decb.png)

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
Firefox

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Monday Nov 20, 2017 at 13:05 GMT_

----

This is happening only when you drag and drop a connector action without drag and drop an endpoint first. If we drag and drop an endpoint first endpoint code formatting are okay.

**Comment by NipunaMarcus** [comment]
connectors are no longer used and endpoint formatting will be fixed with the formatting implementation which is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/8085  hence closing this issue.
