### ISSUE TITLE
Try-it UI issues

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6409]
<a href="https://github.com/NatashaWso2"><img src="https://avatars3.githubusercontent.com/u/13446645?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NatashaWso2](https://github.com/NatashaWso2)**
_Tuesday Nov 21, 2017 at 04:37 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4673_

----

**Description:**
The UI issues of Try-it are referenced here. 

- [ ] Adjust the response view layout when window is resized

- [ ] Fix adding and deleting of headers

- [ ] Disable method body for GET request

- [ ] Adjust the input text when the service name is lengthy

**Suggested Labels:**
Bug

**Affected Product Version:**
0.95.1

**Related Issues:**
#3670
#3710
#4512 
#4597

**Comment by pahans** [comment]
Fixed in 0.973.0
