### ISSUE TITLE
Undo dosn't jump to last edited location.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6410]
<a href="https://github.com/manuranga"><img src="https://avatars0.githubusercontent.com/u/1686124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [manuranga](https://github.com/manuranga)**
_Tuesday Nov 21, 2017 at 13:22 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4690_

----

**Description:**
Usability issue, undo dosn't jump to last edited location.

**Affected Product Version:**
0.95.0

**Steps to reproduce:**
1. Edit text
2. Click different place
3. Press undo

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Jan 02, 2018 at 04:49 GMT_

----

Currently our undo manager is overriding the behaviour of source-editors one and have a unified logic for undo/redo for both design changes and source changes. It just takes the new source replaces the old source with undo/redo. Hence, there is no way to handle previous cursor position unless we save the same inside the undo/redo stack.

However, if we follow a hybrid approach for handling undo/redo - that is, using the built-in undo manager of source-editor when in source view and refactor the composer undo manager logic accordingly, we can solve this easily and properly.

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8827
