### ISSUE TITLE
Cannot scroll the left pane

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6411]
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Wednesday Nov 22, 2017 at 06:40 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4697_

----

**Description:**
Cannot scroll the left pane, so part of the file names will not be visible unless you expand the whole pane
![4](https://user-images.githubusercontent.com/1845370/33113366-08f7e2fe-cf7e-11e7-9568-39e6dd92e45e.png)

**OS, DB, other environment details and versions:**    
Chrome

**Comment by hevayo** [comment]
This is intentional, giving a Horizontal scroll will make the UI hard to work with.
