### ISSUE TITLE
No support for XML transformation

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6415]
<a href="https://github.com/SupunS"><img src="https://avatars3.githubusercontent.com/u/7834839?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SupunS](https://github.com/SupunS)**
_Tuesday Nov 28, 2017 at 07:28 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4745_

----

Please refer https://github.com/ballerinalang/ballerina/issues/3588 for details.

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin  hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
