### ISSUE TITLE
Composer not setting default service in Try It

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6420]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Thursday Nov 30, 2017 at 08:17 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4765_

----

**Description:**
Refer https://github.com/ballerinalang/ballerina/issues/4173 for more details.

**Comment by hevayo** [comment]
Implementation has differed
