### ISSUE TITLE
Preserving parentheses in source gen

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6421]
<a href="https://github.com/manuranga"><img src="https://avatars0.githubusercontent.com/u/1686124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [manuranga](https://github.com/manuranga)**
_Monday Dec 04, 2017 at 06:01 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4776_

----

**Description:**
Parentheses disappears after UI operations.

**Related .bal file source**
```
function x (int a, int b, int c) {
    var x = ( a + b ) * c;
}
```
**Related Issues:**
Depends on ballerinalang/ballerina#4219

**Comment by NipunaMarcus** [comment]
This has been fixed in the current master hence closing the issue.
