### ISSUE TITLE
Remove preceding whitespaces in tool tip of statements

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6422]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Monday Dec 04, 2017 at 08:00 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4781_

----

**Description:**
When statement text is too long, the full content is shown in a tool tip. 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1029806/33541947-0cee50e6-d8f7-11e7-9482-c9673ffcfc4c.png">

The preceding whitespaces (newline, indenting spaces) must be removed from this source gen. 

**Affected Product Version:** 0.95.3

**OS, DB, other environment details and versions:**    
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
macOS - 10.13.1 (17B1003)
**Steps to reproduce:**
- Open a bal file and create a function/resource
- Type a statement with a very long content

**Related .bal file source**
Sample source : 
```
function main (string[] args) {
    Person p = {firstName: "John", lastName: "Doe", age: 30, address: "221B, Baker St, London"};
    
    if (true) {
        var var1 = {firstName: "John", lastName: "Doe", age: 30, address: "221B, Baker St, London"};
    } else {
    }
```

**Comment by NipunaMarcus** [comment]
These designs for drawing statements no longer available hence closing this issue.
