### ISSUE TITLE
Invalid default value for value types

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6423]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Monday Dec 04, 2017 at 11:58 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4785_

----

**Description:**
String has default value as {} in function invocations.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/1029806/33551774-728835c2-d918-11e7-8ca9-d171ed9eeac7.png">

**Affected Product Version:** 0.95.3

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
Drag and drop a function which has strings as parameters

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Tuesday Dec 05, 2017 at 12:48 GMT_

----

This has impacted, endpoint declaration, action invocation as well.

**Comment by hevayo** [comment]
Implementation differed
