### ISSUE TITLE
Cannot access Structs in current Package via Composer environment packages

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6425]
<a href="https://github.com/nadeeshaan"><img src="https://avatars3.githubusercontent.com/u/1329674?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nadeeshaan](https://github.com/nadeeshaan)**
_Wednesday Dec 06, 2017 at 12:13 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4808_

----

**Description:**
In the current implementation, at the composer core level, we can retrieve the constructs in a package via the environment's packages [1]. Bu this packages list doesn't contain the current package reference. Due to this reason, we had an issue as per #4790. In order to address the issue in a meaningful manner, we need to rethink the current package list managing at composer environment level.

[1] https://github.com/ballerinalang/composer/blob/master/modules/web/src/plugins/ballerina/env/environment.js#L118

**Comment by hevayo** [comment]
Implementation has differed
