### ISSUE TITLE
 Composer out of sync

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6426]
<a href="https://github.com/anupama-pathirage"><img src="https://avatars0.githubusercontent.com/u/16300038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anupama-pathirage](https://github.com/anupama-pathirage)**
_Thursday Dec 07, 2017 at 05:24 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4809_

----

**Description:**
Refer https://github.com/ballerinalang/ballerina/issues/4230 for more details

**Comment by hevayo** [comment]
Fixed in latest Master
