### ISSUE TITLE
Unable to open files which are more than 120kb

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6427]
<a href="https://github.com/hevayo"><img src="https://avatars0.githubusercontent.com/u/323846?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hevayo](https://github.com/hevayo)**
_Friday Dec 15, 2017 at 01:47 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4836_

----

**Description:**
If you try to open a file that is more than 120kb composer will get stuck at Loading message. You can create a file with a large JSON to test it.

**Affected Product Version:**
0.95.4

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/hevayo"><img src="https://avatars0.githubusercontent.com/u/323846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hevayo](https://github.com/hevayo)**
_Saturday Dec 16, 2017 at 02:28 GMT_

----

Use the attached file to reproduce.
[test.bal.zip](https://github.com/ballerinalang/composer/files/1564449/test.bal.zip)

**Comment by kaviththiranga** [comment]
This is not applicable to VSCode and was only an issue in composer standalone distribution, which we no longer maintain.
