### ISSUE TITLE
if-else flow chart design implementation

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6428]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 03:53 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4837_

----

**Description:**
Implement complete if-else and if-elseif-else like designs with flow chart design

**Comment by hevayo** [comment]
differed
