### ISSUE TITLE
HTTP Service/Resource design highlighting on HTTP verbs and path

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6429]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 04:13 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4846_

----

**Description:**
When an HTTP service is designed, the design view must highlight on the HTTP verb and the resource path as they are the invocation details of the service. Current design hides these details in annotations.

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
