### ISSUE TITLE
Implementation of the invocation statements

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6430]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 04:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4847_

----

**Description:**
All invocation statements must be redesigned to be similar to below.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/1029806/34026527-ba8fc03a-e17c-11e7-9b6e-aeb68eab15b6.png">

The statements include : 

- [ ] Action invocation statement, var def statements and assignment statements
- [ ] worker receiver and sender
- [ ] reply
- [ ] return

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 08:10 GMT_

----

Fix the following issue, when the invocation contains a non-existing endpoint.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1029806/34032638-1e5801d4-e19d-11e7-82ee-2bf315f6e9bc.png">

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 08:24 GMT_

----

Also consider the incorrect source as reported in https://github.com/ballerinalang/composer/issues/4851

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1029806/34033260-7f1bc36e-e19f-11e7-8c90-31078429f2c8.png">

**Comment by hevayo** [comment]
differed
