### ISSUE TITLE
Break, Return, Continue, Reply for breaking flow chart nodes -  while, ifelse

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6432]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 05:55 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4849_

----

**Description:**
Flowchart nodes if-else and while should properly show the flow changes denoted by break, return, continue, reply keywords

E.g. : 
```ballerina
while(i < 5) {
    if (i == 4) {
           break;
    }
}
```

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
