### ISSUE TITLE
Asking to open the project folder in refresh

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6433]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 06:48 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4850_

----

**Description:**
When refreshing composer with a bal file that was not opened as a program, the same confirmation dialog appears. We should have a way to preserve the information of how the file was opened before.  
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1029806/34030139-b800d7ea-e191-11e7-8ef4-e1ed34d043fb.png">

**Affected Product Version:** 0.95.5

**OS, DB, other environment details and versions:**  N/A  

**Steps to reproduce:**
- Open passthroughservice.bal from welcome page.
- Open the file from the confirmation
- Now refresh composer
- Confirmation must not appear

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
