### ISSUE TITLE
Redeclared symbol error in endpoint not shown in design view

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6434]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 08:24 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4851_

----

**Description:**
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1029806/34033201-45475112-e19f-11e7-8cd0-287b4fabfc4d.png">

**Affected Product Version:** 0.95.4

**OS, DB, other environment details and versions:**   
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
macOS - 10.13.1 (17B1003) 

**Steps to reproduce:**
Please find attached source.

**Related .bal file source**
```ballerina
import ballerina.net.http;
service<http> service1 {
    resource echo1 (http:Request req,http:Response res) {
        
        endpoint<http:HttpClient> endpoint2{create http:HttpClient("",{});
        }
        
        endpoint<http:HttpClient> endpoint2{create http:HttpClient("",{});
        }
        
        var var1,var2 = endpoint2.get({},{});
        
        if (true) {
            var var1,var2 = endpoint2.get({},{});
        } else {
        }
    
        
    }
}
```

**Comment by NipunaMarcus** [comment]
We are no longer showing error from the design view ... hence closing this issue.
