### ISSUE TITLE
Redesign debug view in flow chart node

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6435]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Friday Dec 15, 2017 at 09:16 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4852_

----

**Description:**
For the new if-else and while nodes, verify the debugging in design view

**Comment by pahans** [comment]
closing this in favor of https://github.com/ballerina-platform/ballerina-lang/issues/5130
