### ISSUE TITLE
Reformatting source removes comments

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6436]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Tuesday Dec 19, 2017 at 12:42 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4857_

----

**Description:**
Reformatting a commented bal file will remove all the commented content.

**Affected Product Version:** 0.95.5

**OS, DB, other environment details and versions:**   N/A 

**Steps to reproduce:**
- Create a simple bal program and comment out any lines.
- Click on reformat button
- All comments are removed

**Related .bal file source**
Example : 
```ballerina
import ballerina.net.http;
function func1() {
    
    endpoint<http:HttpClient> endpoint1{create http:HttpClient("",{});
    }
    int a = 0;
    int cnt = 2000;
    var var1,var2 = endpoint1.get({},{});
    if (cnt < 1000) {
       // a = 1;
        var var1,var2 = endpoint1.get({},{});
    } else {
    }
    a = 1;
        if (cnt < 1000) {
       // a = 1;
        var var1,var2 = endpoint1.get({},{});
    } else {
    }
    // a = 4;
    // var var1,var2 = endpoint1.get({},{});
}
```

**Comment by NipunaMarcus** [comment]
We are in the process of implementing formatting support through language server... there is a in progress task hence closing this issue and linking this to the task.
