### ISSUE TITLE
Change swagger theme to compliment source view.

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6437]
<a href="https://github.com/maheeka"><img src="https://avatars1.githubusercontent.com/u/1029806?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maheeka](https://github.com/maheeka)**
_Monday Dec 25, 2017 at 12:46 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4904_

----

**Description:**
Swagger view theme should compliment source view theme. Currently, it is a whitish theme. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1029806/34339819-664cd352-e99f-11e7-8e0f-c78a007de5cd.png">

Also update screenshot in https://github.com/ballerinalang/composer/blob/master/docs/images/SwaggerView.png when the changes are made.

**Affected Product Version:** 0.95.6

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
- Open any sample service and click on swagger view

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
