### ISSUE TITLE
Undo/Redo is slow when in source view/split view (monaco editor)

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6438]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Jan 02, 2018 at 04:53 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4906_

----

With the recent revamp of source editor to use monaco editor, undo/redo inside the source view is experiencing a performance issue.

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8827
