### ISSUE TITLE
Build failure when building on windows 10

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6439]
<a href="https://github.com/DimalChandrasiri"><img src="https://avatars2.githubusercontent.com/u/11191791?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DimalChandrasiri](https://github.com/DimalChandrasiri)**
_Tuesday Jan 02, 2018 at 06:41 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4910_

----

**Description:**
Build failure when building composer on windows 10. Following is the build log.

`[INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ workspace-service ---
[INFO] Starting audit...
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\endpoint\PetStoreApi.java:25: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\endpoint\PetStoreApiImpl.java:25: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\endpoint\PetStoreEp.java:81: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\endpoint\PetStoreEp.java:81: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\handlers\impl\CatHandlerImpl.java:27: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\handlers\impl\DogHandlerImpl.java:15: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\handlers\impl\DogHandlerImpl.java:19: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\handlers\impl\DogHandlerImpl.java:19: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\handlers\interfaces\CatHandlerI.java:27: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\handlers\interfaces\DogHandlerI.java:28: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\model\Cat.java:20: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\model\Dog.java:20: Missing a Javadoc comment. [JavadocType]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\PetStoreWSClientTest.java:107: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\PetStoreWSClientTest.java:107: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\PetStoreWSClientTest.java:130: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\PetStoreWSClientTest.java:130: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\PetStoreWSClientTest.java:157: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:59: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:59: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:88: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:88: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:105: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:105: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:120: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:120: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:151: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\utils\RequestHandler.java:151: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\WebSocketClient.java:51: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\composerapi\WebSocketClient.java:51: First sentence should end with a period. [JavadocStyle]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\tryit\HttpClientTryItTest.java:123: First sentence of Javadoc is incomplete (period is missing) or not present. [SummaryJavadoc]
[ERROR] C:\Users\dimal\Documents\GitHub\composer\modules\services\workspace-service\src\test\java\org\ballerinalang\composer\service\workspace\tryit\HttpClientTryItTest.java:123: First sentence should end with a period. [JavadocStyle]
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Ballerina Composer - Parent ........................ SUCCESS [  5.492 s]
[INFO] Ballerina Composer - Workspace Service ............. FAILURE [  3.508 s]
[INFO] Ballerina Composer - Web ........................... SKIPPED
[INFO] js-tests ........................................... SKIPPED
[INFO] integration-tests .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.346 s
[INFO] Finished at: 2018-01-02T12:04:20+05:30
[INFO] Final Memory: 28M/71M
[INFO] ------------------------------------------------------------------------`

**Affected Product Version:**
Master Branch, Commit 441004aa7a88ceecec661ff1f289744d8eb0099f

**OS, DB, other environment details and versions:** 
OS : Windows 10  v1709 Build 16299.125

**Steps to reproduce:**
Clone the composer repository and build using `mvn clean install`

**Comment by hevayo** [comment]
Fixed in Master
