### ISSUE TITLE
Cannot compile builtin packages using BCompileUtils

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#6464]
**Description:**
I tried using `BCompileUtil` for compiling the HTTP package and the IO package. But an exception was thrown because apparently the native function loader cannot locate the functions. This seems to be because of a mismatch between the package names in where it's accessed (in `ProgramFileReader`) and the generated native elements provider. In the latter, the package name is `ballerina.http` while in the former, the package path is used and it's just `http`

**Comment by SupunS** [comment]
@pubudu91 Why do you need to compile builtin packages? Can you explain your use case?

Anyway, with the introduction of BALO (compiled packages), all the builtin packages are already compiled. Hence those are not needed (and cannot be) compile again.
