### ISSUE TITLE
Worker line plus position breaks when adding a new worker

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6468]
<a href="https://github.com/keizer619"><img src="https://avatars0.githubusercontent.com/u/2918812?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [keizer619](https://github.com/keizer619)**
_Tuesday Jan 23, 2018 at 10:59 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4986_

----

This only happens if you add a worker inside Resource. Seems like worker scope add a spacing

![screen shot 2018-01-23 at 4 32 21 pm](https://user-images.githubusercontent.com/2918812/35272179-5c060ef0-005a-11e8-86d8-9029eeb070a3.png)

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/srsharon"><img src="https://avatars0.githubusercontent.com/u/10986966?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [srsharon](https://github.com/srsharon)**
_Wednesday Jan 24, 2018 at 04:30 GMT_

----

![image](https://user-images.githubusercontent.com/10986966/35314594-3cb4d232-00ed-11e8-8147-5f3a133fda3a.png)

There is also an additional plus that comes on the left corner of the service and function container.

**Comment by hevayo** [comment]
Fixed in 0.970.0
