### ISSUE TITLE
Redesign Composer buttons

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6469]
<a href="https://github.com/keizer619"><img src="https://avatars0.githubusercontent.com/u/2918812?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [keizer619](https://github.com/keizer619)**
_Friday Jan 05, 2018 at 07:01 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4923_

----

- Floating Action Buttons related view
   - Switch between detail and flow views.
   - Switch to Code/ Split View/Design View
   - Switch between detail and flow views.

- Static Flat Button
   - Add definitions
   - Add Resource / Action
   - Add Statement
   - Add Connectors
   - Add Service Level Connectors.
   - Package change

- Flat
   - Delete Frame
   - Collapse Frame
   - Mark Debug point
   - Delete Statement
   - Jump to source view
   - Configure Service Properties
   - Configure Connector Properties
   - Add parameter
   - Add Return

**Comment by hevayo** [comment]
implementation differed
