### ISSUE TITLE
Plus button appears even after the resources are collapsed

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6470]
<a href="https://github.com/srsharon"><img src="https://avatars0.githubusercontent.com/u/10986966?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [srsharon](https://github.com/srsharon)**
_Friday Jan 05, 2018 at 06:19 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4922_

----

![image](https://user-images.githubusercontent.com/10986966/34597619-da35b2c2-f20d-11e7-9c0d-d167b6dfdb2e.png)

**Description:**
The plus button to add workers and endpoints in the resources appear even after the resource is collapsed  

**Steps to reproduce:**
1. Open websocket sample in welcome page
2. Collapse the top resources

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9299
