### ISSUE TITLE
Get rid of console logs from compiler upon syntax errors

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6471]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Jan 09, 2018 at 06:01 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4928_

----

When the compiler is invoked from composer backend, sometimes compiler error logs are printed in composer startup terminal. Seems there are some places where the compiler classes directly writes to System.Out/Error and we do not have a control over it. For the moment, we need to swap System.Out/Error temporarily before invoking compiler and switch it back once the task is accomplished.

For the proper fix: We need to find out the places where this happens and fix them to use a logger API to print errors - we may need to send PRs to antlr repos.

**Comment by hevayo** [comment]
Fixed in 0.970.0
