### ISSUE TITLE
LangServer features for persisted files on windows are not working

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6473]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Jan 15, 2018 at 14:10 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4954_

----

**Comment by NipunaMarcus** [comment]
This issue is fixed in lang server available in the current master hence closing this issue.

**Comment by hevayo** [comment]
Works with 0.970.0
