### ISSUE TITLE
Need to add migration logic to handle local storage between composer versions

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6474]
<a href="https://github.com/pahans"><img src="https://avatars2.githubusercontent.com/u/1552869?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pahans](https://github.com/pahans)**
_Monday Jan 22, 2018 at 11:41 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4981_

----

**Description:**
we will need something like this to handle localstrorage changes between ballerina versions
```js
var versions = {
    '1.0.1': function () {
        console.log('going into migrate_1_0_1');
    },
    '1.0.2': function () {
        console.log('going into migrate_1_0_2');
    },
    '1.0.3': function () {
        console.log('going into migrate_1_0_3');
    },
}

function migrate() {
    if (!localStorage.getItem('db:version')) {
        localStorage.setItem('db:version', '1.0.0');
    }
    for (var version in versions) {
        var current_version = localStorage.getItem('db:version');
        if (version > current_version) {
            var callback = versions[version];
            callback();
            localStorage.setItem('db:version', version);
        }
    };
}
```

**Related Issues:**
https://github.com/ballerinalang/composer/pull/4980

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
