### ISSUE TITLE
remove jquery dependency or bump version to latest

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6475]
<a href="https://github.com/kaviththiranga"><img src="https://avatars3.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Tuesday Jan 23, 2018 at 01:22 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4983_

----

AFAIR we currently use jquery in some trivial use cases only. A lot of dependencies of jquery were removed when we revamped the composer as a react app. Find the possibility of getting rid of jquery completely or at least bump the version to a latest one to avoid security issues.

**Comment by uthaiyashankar** [comment]
<a href="https://github.com/keizer619"><img src="https://avatars0.githubusercontent.com/u/2918812?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [keizer619](https://github.com/keizer619)**
_Tuesday Jan 23, 2018 at 14:23 GMT_

----

We have used jQeury in Transformer, for DOM manipulations related to jsPlumb [1]. We could replace those with pure JS.

[1] https://github.com/ballerinalang/composer/blob/master/modules/web/src/plugins/ballerina/diagram/views/default/components/transformer/transformer-render.js

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
