### ISSUE TITLE
Can not generate docs with 0.970.0-alpha1

### ISSUE THREAD

**Issue by erandiganepola** [ballerina-platform/ballerina-lang#6477]
**Description:**
Found errors when trying to generate docs with ballerina version 0.970.0-alpha1.

Input command - <ballerina doc docs -o salesforce>
Found error - 
" docerina: API documentation generation failed for docs: docs/.ballerina"

Input command - <ballerina doc docs -o salesforce/salesforce_connector.bal>
Found error -
"docerina: API documentation generation failed for docs: docs/.ballerina"

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
The correct command to generate docs is as follows: 
ballerina doc -o docs salesforce
ballerina doc -o docs salesforce/salesforce_connector.bal

This is working as expected in master, hence closing this issue
