### ISSUE TITLE
Check operator can not be used on strings

### ISSUE THREAD

**Issue by harshanL** [ballerina-platform/ballerina-lang#6642]
**Description:**
We can use "check" operator on instances such as "int iW1 = check <int>resW1[0]". But this is not the same for strings. If we try to use it as "string iW1 = check <string>resW1[0]"" It gives a compilation failure "invalid usage of the checked expression operator: no expression type is equivalent to error type compilation contains errors".

**Steps to reproduce:**

Given below is a code to reproduce this issue.
```
import ballerina/io;

function main (string[] args) {

    fork {
        worker w1 {
            int i = 23;
            string s = "Colombo";
            io:println("[w1] i: " + i + " s: " + s);
            i, s -> fork;
        }

        worker w2 {
            float f = 10.344;
            io:println("[w2] f: " + f);
            f -> fork;
        }
    } join (some 1) (map results) {
        if (results["w1"] != null) {
            any[] resW1 = check <any[]>results["w1"];
            int iW1 = check <int>resW1[0];
            string sW1 = check <string>resW1[1];
            io:println("[join-block] iW1: " + iW1 + " sW1: " + sW1);
        }

        if (results["w2"] != null) {
            any[] resW2 = check <any[]>results["w2"];
            float fW2 = check <float>resW2[0];
            io:println("[join-block] fW2: " + fW2);
        }
    }
}
```
**Affected Versions:**
ballerina-0.970.0-alpha1-SNAPSHOT

**OS, DB, other environment details and versions:**
N/A

**Suggested Labels (optional):**
Severity/Blocker, Type/Bug, Priority/Highest

**Comment by hasithaa** [comment]
<string>resW1[1] is a safe conversion. Hence it returns only string type, not error|string union type. Hence using check is not required here. Hence Given error message by the compiler is correct.
