### ISSUE TITLE
Prometheus HTTP bind error

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#6804]
**Description:**
When you try to run more than one instance of Ballerina on a machine, you get this error on the additional instances.

ballerina: failed to bind Prometheus HTTP endpoint 0.0.0.0/0.0.0.0:9797:  Address already in use

**Comment by sanjiva** [comment]
I assume you started with -observe right?

So this is like a debug port for a Java program .. you have to give a port to open for remote debug. Normally we give 5005 if you're using Idea right? So this is similar except that there's a default port.

We have two options:
- if the user explicitly gives a port then we have to fail if that's not available
- if the default port's not available we can open another port and print it out

**Comment by afkham** [comment]
I didn't start with observe. I guess observe is set to true by default. Yes, if the default port is not available, and the user didn't specify the port, we should pick an available port. However, if the user specified port is unavaialble, we should throw an error and the process should exit.

**Comment by afkham** [comment]
This has been fixed
