### ISSUE TITLE
SQL Client with JDBC URL provided as options results in a compilation error

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#6810]
**Description:**
endpoint sql:Client testDB {
        username: "SA",
        password: "",
        options: {url:"jdbc:hsqldb:hsql://localhost:9001/TEST_SQL_CONNECTOR"}
};

**Comment by anupama-pathirage** [comment]
With new ballerina data clients above can be achieved as follows.
```ballerina
import ballerina/jdbc;

endpoint jdbc:Client testDB {
        url: "jdbc:hsqldb:file:./target/tempdb/TEST_SQL_CONNECTOR",
        username: "SA",
        poolOptions: { maximumPoolSize: 1 }
    };
```
