### ISSUE TITLE
check doesn't work with endpoint action invocation

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#6811]
int result = check testDB -> update("INSERT INTO STOCK(SYMBOL,PRICE) VALUES (?,?)", params);

doesn't work. It is the same for all endpoint action invocations. 

P.S. 
int result =? testDB -> update("INSERT INTO STOCK(SYMBOL,PRICE) VALUES (?,?)", params);
used to work

**Comment by sanjiva** [comment]
This was a grammar miss ... fix coming.

**Comment by anupama-pathirage** [comment]
Checked in 0.970.0 beta 14 and this is fixed now.
