### ISSUE TITLE
No way to document the returned variables in APIs

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#6828]
For example,
```ballerina
function getDecodedJWTComponents (string[] encodedJWTComponents) returns ((json, json)|error)
```
How is anyone supposed to know that the first json in the tuple is jwtHeader and 2nd one is jwtPayload?
With named params, we used to have self documenting APIs.

How about something similar to the following with optional annotations?

```ballerina
function getDecodedJWTComponents (string[] encodedJWTComponents) returns ((@{name=jwtPayload}  json, @{name=jwtHeader} json)|error)
```

**Comment by shehan360** [comment]
This issue seem to be fixed: https://ballerina.io/swan-lake/learn/api-docs/ballerina/jwt/functions.html#decodeJwt
