### ISSUE TITLE
[HTTP] Include Circuit Breaker in Simple Client Endpoint

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#6854]
Currently, all resiliency related clients are excluded from the simple client endpoint. Circuit Breaker needs to be included in the simple client endpoint as well.

**Comment by pubudu91** [comment]
Closed via #6920

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/6920
