### ISSUE TITLE
[HTTP] Rename client endpoint and server endpoint names

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#6881]
**Description:**

As below 

Protocol          | Org / Package | Service Endpoints | Supported Service Types | Client Endpoints
HTTP, HTTP2 | ballerina/http   | Listener                  | Service                             | ClientLoadBalanceClientFailoverClient

For more details please refer to 

https://docs.google.com/document/d/1Jw_vnL0T9NrkkzaXG18nVsSmoQ5y-c9qomeNUFUTajM/edit?usp=sharing

**Comment by pubudu91** [comment]
Closed via #6939
