### ISSUE TITLE
[HTTP] Issue with redirect  

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#6891]
**Description:**
HTTP redirect after redirecting to the server does not download the resource.

Use case: When a user wants to pull a package from central, the request first goes to central and then it is redirected to the file server which will server the package archive. Though the request is redirected to the file server, the package archive is not downloaded. 

This works fine with curl. Trace logs when the request is sent by curl and ballerina is attached. 

[ballerina.txt](https://github.com/ballerina-platform/ballerina-lang/files/1888443/ballerina.txt)
[curl.txt](https://github.com/ballerina-platform/ballerina-lang/files/1888444/curl.txt)

**Comment by arukshani** [comment]
This is fixed with https://github.com/wso2/transport-http/pull/100
