### ISSUE TITLE
[HTTP] Entity Body API related changes 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#6892]
**Description:**
- Change getPayload implementation to rely on content-type. If content-type is not available, return a blob.
- Change setXXXPayload/getXXXPayload to setPayload and getPayload. Make use of type system. (XXX = Json/Xml/String/Blob)
- Rename setMultiparts to setBodyParts.

**Comment by shafreenAnfar** [comment]
duplicate https://github.com/ballerina-platform/ballerina-lang/issues/6490

**Comment by arukshani** [comment]
Fixed in #7008
