### ISSUE TITLE
Test global variables initialized when using an imported package

### ISSUE THREAD

**Issue by dushaniw** [ballerina-platform/ballerina-lang#6942]
**Description:**
After building and pushing the package to ballerina central, the test.bal inside tests package also get pushed to central. Because of that, when importing the package and executing, the test.bal also gets initialized. If we have defined global variables inside tests, user will get execution errors.  

**Steps to reproduce:**
Define a global endpoint inside tests/test.bal file and build the package and push it to central. 

```ballerina
import ballerina/io;
import ballerina/http;
import ballerina/log;
import ballerina/test;
import ballerina/config;

string url = setConfParams(config:getAsString("ENDPOINT"));
string accessToken = setConfParams(config:getAsString("ACCESS_TOKEN"));
string clientId = setConfParams(config:getAsString("CLIENT_ID"));
string clientSecret = setConfParams(config:getAsString("CLIENT_SECRET"));
string refreshToken = setConfParams(config:getAsString("REFRESH_TOKEN"));
string refreshTokenEndpoint = setConfParams(config:getAsString("REFRESH_TOKEN_ENDPOINT"));
string refreshTokenPath = setConfParams(config:getAsString("REFRESH_TOKEN_PATH"));

endpoint Client gMailEP {
    oAuth2ClientConfig:{
        accessToken:accessToken,
        baseUrl:url,
        clientId:clientId,
        clientSecret:clientSecret,
        refreshToken:refreshToken,
        refreshTokenEP:refreshTokenEndpoint,
        refreshTokenPath:refreshTokenPath,
        clientConfig:{}
    }
};

function setConfParams(string|() confParam) returns string {
    match confParam {
        string param => {
            return param;
        }
        () => {
            log:printInfo("Empty value, found nil!!");
            return "";
        }
    }
}
```

Create a new project and import your package as wso2/package-name. Simply run a main function, and you will get execution errors due to global variables/endpoints defined inside test.bal in imported package.

```ballerina
import ballerina/io;
import wso2/gmail;

public function main(string[] args) {
    io:println("Hello, World!");
}
```

**Affected Versions:**

ballerina-tools-0.970.0-alpha3-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by muthulee** [comment]
Hi Dushani,

For now please don't push the test package. When you are building to push, please remove test package. 

thanks,
Dimuthu

**Comment by NatashaWso2** [comment]
When building the package to be pushed to central using "ballerina build", we don't include the tests inside the package to  the generated balo in the latest master. Since this issue is fixed closing this issue.
