### ISSUE TITLE
[Windows] Cannot build the ballerina-lang repo

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#6956]
**Description:**
JDK - 1.8.0_161-b12
Maven- 3.5.3
Severity - L1
Priority -Highest

**Steps**
1. Build the ballerina-lang repository (09/04/2017)

**Issue**
The following error is logged. Cannot traverse to the below path and directs to JRE even though the JDK is set in the path.
`C:\Program Files\Java\jre1.8.0_161/../lib/tools.jar ` 

```
Downloaded from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-publ
ic/org/apache/velocity/velocity/1.5/velocity-1.5.jar (392 kB at 95 kB/s)
Downloaded from wso2-nexus: http://maven.wso2.org/nexus/content/groups/wso2-publ
ic/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar (
575 kB at 138 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:33 min
[INFO] Finished at: 2018-04-09T13:40:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:
2.17:check (validate) on project ballerina-parent: Execution validate of goal or
g.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apa
che.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could
not be resolved: Could not find artifact com.sun:tools:jar:1.8.0 at specified pa
th C:\Program Files\Java\jre1.8.0_161/../lib/tools.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
```

**Comment by dilinisg** [comment]
**Update:**
1. Build the ballerina-lang repo - 17/04/2018

**Issue**
1. The build is successful, but the docker directory was not created.
2. The target directories were also not created in distribution/zip/ballerina and distribution/zip/ballerina-tools folders

Therefore, it's a blocker to run samples with a build pack

**Comment by dilinisg** [comment]
Verified building the ballerina lang repo after ballerina-lang 0.97.0 release and still the issue persists. 

The build is successful, but the target directories are not created in ballerina and ballerina-tools directories

**Comment by keizer619** [comment]
There were few issues with windows, now we have fixed those and we have configured a seperate Jenkins job for windows as well [1]

[1] https://wso2.org/jenkins/view/All%20Builds/job/ballerina-platform/job/ballerina__win/
