### ISSUE TITLE
Improve log API

### ISSUE THREAD

**Issue by afkham** [ballerina-platform/ballerina-lang#6960]
We can now have the following function signatures:

log:debug(string)
log:info(string)
log:warn(string)
log:error(string msg, error err = ())

**Comment by pubudu91** [comment]
Still cannot get rid of the `print` prefix since `error` is marked as a reserved word.

Cannot make `error` an optional argument since default value assignment is only supported for primitive types.

**Comment by pubudu91** [comment]
Removed `printErrorCause(string msg, error err)` and replaced it with `printError(string msg, error? err = ())`
