### ISSUE TITLE
Internal error occurs when method signature parameter names differ

### ISSUE THREAD

**Issue by erandiganepola** [ballerina-platform/ballerina-lang#6967]
**Description:**
An internal error occurs when method signature parameter names differ from method implementation parameter names (case sensitive).

Example:
* Method signature:
public function updateContact (string contactID, json contactRecord) returns (boolean|SalesforceConnectorError);

*  Implementation:
public function SalesforceConnector::updateContact (string contactId, json contactRecord)
returns boolean|SalesforceConnectorError {
    return updateRecord(CONTACT, contactId, contactRecord);
}

Error: "error: fail to compile file: null"

**Comment by lankavitharana** [comment]
This is fixed in master, please check and reopen if issue still exist for you
