### ISSUE TITLE
DirectoryListenerConnectorTest fails in Mac

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#6969]
**Description:**
DirectoryListenerConnectorTest fails in Mac.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
Mac

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**
Gihan/Pamod

**Comment by uthaiyashankar** [comment]
The reason for the test failure is due to starvation and race condition. It roughly takes about 8-15 seconds for the callback. Increasing the Thread.sleep to 5000, will let the callback to happen. That will solve the problem.

**Comment by wggihan** [comment]
I have added incremental thread sleep to the test case. It will wait  1,2.3,..,20 before failing. 

https://github.com/ballerina-platform/ballerina-lang/pull/6991
