### ISSUE TITLE
[HTTP] Improve redirection handler to support HTTP/2

### ISSUE THREAD

**Issue by isudana** [ballerina-platform/ballerina-lang#6976]
**Description:**
Need to research on what it means for redirection in HTTP/2 and include support for it in HTTP Redirection handler. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by arukshani** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9039
