### ISSUE TITLE
Undefined compile error thrown for mismatch function params

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#6978]
**Description:**

The following error is thrown during execution

"error: fail to compile file: null" 

**Steps to reproduce:**

1. Create the following ballerina file and execute 

```
import ballerina/io;

public type Person object {
        public {
		string name;
		int age;	
	}

	public function foo(string greeting);
};

public function Person::foo(string greet){
	io:println(greet);
}

```

2. Error mentioned in the description will be thrown 

The cause for the issue is the mismatch between the variable name used in the function signature and it's implementation. 

**Affected Versions:**

ballerina-0.970.0-alpha3

**OS, DB, other environment details and versions:**

Mac

**Comment by lankavitharana** [comment]
This is fixed with PR - https://github.com/ballerina-platform/ballerina-lang/pull/7187

with above change, you will have to have matching function signatures in interface and implementation, otherwise it will be a semantic failure.
