### ISSUE TITLE
[HTTP] LB and Failover related API changes

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-lang#6980]
**Description:**

- Change lbMode to LbConfig | FailoverConfig availabilityMode

LBConfig{
     String algo;
     function () - >
}

- Add a config to load balancer whether to fail over in case of a failure.

Refer : https://github.com/ballerina-platform/ballerina-lang/issues/6888

**Comment by VijithaEkanayake** [comment]
Fixed with: https://github.com/ballerina-platform/ballerina-lang/pull/7623, https://github.com/ballerina-platform/ballerina-lang/pull/7505
