### ISSUE TITLE
Cannot give nil as the default value of a function argument

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#6995]
Consider the following function from the log API.
```ballerina
public native function printError(string msg, error? err = ());
```
Calling the above function in a program results in the following error:
``
error: fail to compile file: null
``
An NPE is thrown in the following line: https://github.com/ballerina-platform/ballerina-lang/blob/0a0aeadcddba50a0da51d26b9a66b5f7564cda80/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/programfile/PackageInfoWriter.java#L604

**Comment by SupunS** [comment]
Fixed with PR: https://github.com/ballerina-platform/ballerina-lang/pull/7444
