### ISSUE TITLE
Failed to run the package when multiple versions are in local ballerina home

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#7002]
**Description:**
After building and pushing the package to ballerina central with _new versions_ few times and when we import the package and execute it, each time it creates a new directory with new version in **.ballerina_home** directory.

Since there are multiple versions in the **.ballerina_home** directory when we import the package and run the code it gives following types of error messages.
> redeclared symbol 'Account'
> implementation already exist for the given function 'init' in same package

This might  be due to the reason that compiler doesn't recognize to import package with the latest release tag.

**Steps to reproduce:**
Create a ballerina-package and push it to central with a version 1.0 and pull the package. Again push the same package with version 1.1 and pull.

Import the package into a new project and run it.

**Affected Versions:**
0.970.0-alpha3-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced in the latest master **0.971.1-SNAPSHOT**, hence closing this issue.
