### ISSUE TITLE
[Installer] Does not show the correct name of the ballerina tools package

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7005]
**Description:**

Tried to install ballerina tools from the windows installer and noticed that the name of the pack is wrong. Both the tools and ballerina installers have the same name. 
![image](https://user-images.githubusercontent.com/1845370/38540184-b63e32b8-3cb8-11e8-9096-1f398ed954f5.png)

Expecting **Ballerina Tools %version%** as the name of the installer

**Comment by ChanakaCooray** [comment]
This will be available in the next release.

**Comment by keizer619** [comment]
Yes this is fixed as @ChanakaCooray has mentioned, hence closing this issue 
![screen shot 2018-06-11 at 8 42 46 am](https://user-images.githubusercontent.com/2918812/41211233-8a8f3510-6d53-11e8-9aa5-02250bfd8d93.png)
![screen shot 2018-06-11 at 8 42 57 am](https://user-images.githubusercontent.com/2918812/41211234-8ac3d1e4-6d53-11e8-8f1a-ecc9536d9ea9.png)
