### ISSUE TITLE
[Installer] Tools pack installer does not provide a way to repair/remove package

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7006]
**Description:**
OS - Windows

When trying to run the ballerina installer (ballerina-0.970.0-alpha1-SNAPSHOT-windows-x64) for the second time (after a successful installation), it provides an option to repair/remove the package.

![e2](https://user-images.githubusercontent.com/1845370/38541694-c98a5ef8-3c97-11e8-84da-4fe9d84b9139.PNG)

But, when trying the same with Tools installer (ballerina-tools-0.970.0-alpha1-SNAPSHOT-windows-x64), it does not provide such option, rather it shows the same installation page.
![1](https://user-images.githubusercontent.com/1845370/38541731-e3f5bd50-3c97-11e8-904a-31e48741127c.PNG)

**Comment by keizer619** [comment]
This is expected behavior, even we are pushing users to use ballerina-platform installer instead of run time installer. Hence i am closing this issue
