### ISSUE TITLE
[Installer] The user account control window does not show the correct name of the pack

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7019]
**Description:**
The User Account Control window that will pop up when installing and uninstalling packages does not show the correct **Program Name**. Please refer the screen shot below

![image](https://user-images.githubusercontent.com/1845370/38548173-bc609f30-3cce-11e8-8e6c-09ecdc7757dd.png)

**OS, DB, other environment details and versions:**
OS - Windows 7

**Comment by ChanakaCooray** [comment]
Fix will be available in the next release.

**Comment by keizer619** [comment]
As this have been fixed with current installers i am closing the issue
