### ISSUE TITLE
Fatal error when casting json to int

### ISSUE THREAD

**Issue by vlgunarathne** [ballerina-platform/ballerina-lang#7021]
**Description:**
A fatal error occurs when trying to cast a json field with an integer to a int variable.

**Steps to reproduce:**
```ballerina
import ballerina/io;

public function main(string[] args) {
    json jsonSample = {"recordCount":100};
    io:println(jsonSample.recordCount);
    int count = check <int>jsonSample.recordCount;
    io:println(count);
}

```

Following error occurs
```
fatal error: 7
error: error, message: 7
	at .:main(sample.bal:6)
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lafernando** [comment]
This is fixed now.
