### ISSUE TITLE
[Installer] Ending the Setup Wizard prematualy

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7023]
**Steps to reproduce:**
1. Run the installer (ballerina-0.970.0-alpha1-SNAPSHOT-windows-x64) to **remove** an already installed package
2. Click on Remove installation ->and Remove again
3.  The user account control window will pop up
4. Close the window or keep it idle for some time. Then it will show a warning message like below
![err](https://user-images.githubusercontent.com/1845370/38549023-1e2ef05a-3cab-11e8-9fb2-a3529fd7e8f1.PNG)
5. Click ok. Then you will get a message like below
![err2](https://user-images.githubusercontent.com/1845370/38549245-85e3e2a0-3cab-11e8-9972-f62746370239.PNG)

**Issue**
It says "To install this program at a later time, run setup wizard again". But, the program was not removed since it was failed. This message should be reworded (It is also said through the message "Your system has not been modified")

**OS, DB, other environment details and versions:**
OS - Windows 7

**Comment by ChanakaCooray** [comment]
@dilinisg, these are the standard messages shown in an MSI installer. In addition, this message seems to be meaningful since your first action is to install the program.

**Comment by dilinisg** [comment]
Closing the issue based on the previous comment
