### ISSUE TITLE
[Installer] Provide a user direction to find where the pack is installed when run Linux .deb installer

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-lang#7024]
**Description:**
When run the ballerina-linux-0.970.0-alpha1-SNAPSHOT.deb file using the following command 
sudo dpkg -i ballerina-linux-0.970.0-alpha1-SNAPSHOT.deb
Command line output is displayed as below

Selecting previously unselected package ballerina.
(Reading database ... 260108 files and directories currently installed.)
Preparing to unpack ballerina-linux-0.970.0-alpha1-SNAPSHOT.deb ...
Unpacking ballerina (0.970.0-alpha1-SNAPSHOT) ...
Setting up ballerina (0.970.0-alpha1-SNAPSHOT) ...

Suggest to include the file system path in the command line output to show where ballerina will be installed in the file system. Then it will be easy for a user to find the location in the local file system.

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Suggested Labels**
Type Improvement

**Comment by kavithasub** [comment]
The same observed when run rpm installer in Fedora instance, and the suggestion would be the same.

**Comment by ThilinaManamgoda** [comment]
This is the default behaviour for deb installation. We can verify it with [Python deb installer](https://ubuntu.pkgs.org/16.04/ubuntu-main-amd64/python_2.7.11-1_amd64.deb.html) as well.

**Comment by ShanikaWickramasinghe** [comment]
Closing the issue as this is the default behaviour
