### ISSUE TITLE
[HTTP] Improve API to cover different concepts

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#7030]
**Description:**
For example functions like the following for commonly used http codes can be created.
`Eg : _ = caller->created(); `would respond with a 201 response
and 
`Eg : _ = caller->ok();` would respond with a 200 OK response

**Comment by arukshani** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/10448
