### ISSUE TITLE
[Installer][Improvement] Improvements for the setup completion page

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7041]
**Description:**
In some setups, when the installation is completed it gives options such as to open the folder of the destination, open read me etc. Please see a sample attached here. 

![image](https://user-images.githubusercontent.com/1845370/38554711-8b7f5dc4-3cbb-11e8-86fb-61dc05f423ba.png)

It's comprehensive if we can further guide the user by proving such options

**Comment by chamithkumarage** [comment]
The ReadMe file comes with the binary has info about building Ballerina from the source which is useless for someone who just got the binary version installed (this should be fixed).

What if we mention the BBE URL (https://ballerinalang.org/docs/by-example/) instead of opening the ReadMe?

**Comment by dilinisg** [comment]
+1 for mentioning the BBE URL. I think the latest URL is https://ballerina.io/learn/by-example/

**Comment by keizer619** [comment]
Read me file now has been improved to redirect users to getting start and learn materials like BBE and BBG. Hence i am closing the issue.

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/distribution/zip/ballerina-tools/README.md
