### ISSUE TITLE
Provide a meaningful backend message when running the Linux installer for the 2nd time after a successful installation

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-lang#7055]
**Description:**
When run the ballerina-linux-0.970.0-alpha1-SNAPSHOT.deb file using the following command
sudo dpkg -i ballerina-linux-0.970.0-alpha1-SNAPSHOT.deb
Command line output is displayed as below

Selecting previously unselected package ballerina.
(Reading database ... 260108 files and directories currently installed.)
Preparing to unpack ballerina-linux-0.970.0-alpha1-SNAPSHOT.deb ...
Unpacking ballerina (0.970.0-alpha1-SNAPSHOT) ...
Setting up ballerina (0.970.0-alpha1-SNAPSHOT) ...

Run the same command for the 2nd time (after a successful installation in the 1st attempt). Same output will be displayed in the command line as above. 
Suggest to give a meaningful message for the user if ballerina is installed once and exist in the local file system.

**Suggested Labels**
Type/Improvement

**Comment by chamithkumarage** [comment]
These messages are standard text given by dpkg. They are common to all packages you install via dpkg.

**Comment by ShanikaWickramasinghe** [comment]
Closing the issue as this is common to all pkgs
