### ISSUE TITLE
balx execution broken in alpha4: invalid program file format

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#7081]
**Description:**
ballerina can no longer execute compiled (balx) files

**Steps to reproduce:**
$ ballerina build hello.bal
$ ballerina run hello.balx
ballerina: ballerina: invalid program file format
$ ls
hello.bal       hello.balx 
$ ballerina run hello.bal
Hello, World!

**Affected Versions:**
0.970.0-alpha4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by afkham** [comment]
Fixed
