### ISSUE TITLE
Improve JMS synchronous message receive call

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-lang#7089]
**Description:**

Implement underlying JMS blocking message receive call using a separate thread executor. This is to avoid blocking the Ballerina thread on I/O operations.

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#6 to get latest updates of this issue
