### ISSUE TITLE
Improve support for distributed transactions with JMS connector

### ISSUE THREAD

**Issue by Asitha** [ballerina-platform/ballerina-lang#7094]
**Description:**

Need to improve support for distributed transactions with JMS connector. To do this seamlessly we might need to introduce an XaConnection object for JMS connector.

**Comment by daneshk** [comment]
Closing this issue. Since we moved JMS module to https://github.com/wso2-ballerina/module-jms repository. 
Please refer wso2-ballerina/module-jms#7 to get latest updates of this issue
