### ISSUE TITLE
[HTTP] When a service acting as a proxy, HttpClient sends an incorrect content length for a json message if it has a trailing space

### ISSUE THREAD

**Issue by isudana** [ballerina-platform/ballerina-lang#7127]
**Description:**

I have following ballerina service configuration. 

``
import ballerina/io;
import ballerina/http;

endpoint http:Listener frontendEP {
    port:9090
};

endpoint http:Client backendClientEP {
    targets: [
        {
            url: "http://localhost:7090"
        }
    ]
};

@http:ServiceConfig {
    basePath:"/frontend"
}
service<http:Service> frontendHttpService bind frontendEP {
    @http:ResourceConfig {
        path:"/"
    }
    frontendHttpResource (endpoint client, http:Request clientRequest) {

        var reqPayload = clientRequest.getJsonPayload();
        json reqJsonPayload = {};
        match reqPayload {
            json resultantJsonPayload => {
                reqJsonPayload = resultantJsonPayload;
            }
            http:PayloadError err => {
                http:Response errorResponse = new;
                json errMsg = {"error":"expected request message not received"};
                errorResponse.setJsonPayload(errMsg);
                _ = client -> respond(errorResponse);
            }
        }
        string reqStringPayload = reqJsonPayload.toString() but {() => ""};
        io:println("Request : " + reqStringPayload);
        http:HttpFuture httpFuture = new;
        // Submit a request
        var submissionResult = backendClientEP -> submit("GET", "/backend/main", clientRequest);
        match submissionResult {
            http:HttpConnectorError err => {
                io:println("Error occurred while submitting a request");
                http:Response errorResponse = new;
                json errMsg = {"error":"error occurred while submitting a request"};
                errorResponse.setJsonPayload(errMsg);
                _ = client -> respond(errorResponse);
            }
            http:HttpFuture resultantFuture => {
                httpFuture = resultantFuture;
            }
        }

        // Get the requested resource
        http:Response res = new;
        var result = backendClientEP -> getResponse(httpFuture);
        match result {
            http:Response resultantResponse => {
                res = resultantResponse;
            }
            http:HttpConnectorError err => {
                io:println("Error occurred while fetching response");
                http:Response errorResponse = new;
                json errMsg = {"error1":"error occurred while fetching response"};
                errorResponse.setJsonPayload(errMsg);
                _ = client -> respond(errorResponse);
            }
        }

        var responsePayload = res.getJsonPayload();
        json responseJsonPayload = {};
        match responsePayload {
            json resultantJsonPayload => {
                responseJsonPayload = resultantJsonPayload;
            }
            http:PayloadError err => {
                http:Response errorResponse = new;
                json errMsg = {"error":"expected response message not received"};
                errorResponse.setJsonPayload(errMsg);
                _ = client -> respond(errorResponse);
            }
        }
        http:Response successResponse = new;
        successResponse.setJsonPayload(responseJsonPayload);
        _ = client -> respond(successResponse);
    }
}
``

Here I am logging the payload of clientRequest and delivering the same clientRequest to the backend. 
If the request sent from the client (here I have used jmeter) contains a trailing while space, at the ballerina side trailing space is getting removed but still original content-length of the request is delivered to the backend. 

**Steps to reproduce:**
Use above ballerina service.
Invoke it with having a trailing space at the end of the json message. 

**Affected Versions:**
ballerina-0.970.0-alpha3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by arukshani** [comment]
This is no longer reproducible. Working as expected, hence closing.
