### ISSUE TITLE
weird type checking error with "throw"

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-lang#7285]
This code:
        throw <error> { message: "ff" };

Gives a weird error:

incompatible types: expected 'error', found 'error'

**Comment by afkham** [comment]
Now the error is:
incompatible types: expected 'error', found 'map'

**Comment by hasithaa** [comment]
This will be fixed with new error type.

**Comment by lankavitharana** [comment]
PR https://github.com/ballerina-platform/ballerina-lang/pull/12773 merged, hence closing
