### ISSUE TITLE
[Runtime] [Ubuntu] Installing /Uninstalling packages 0.970.0-beta0 does not seem to work

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#7296]
**Description:**
When testing the runtime and going through the ballerina help command I came across install/un-install commands. However, I could not find a command to list the currently available packages to select a package to un-install. 

It would be better if the help can include such a command or else remove the un-install feature if its not currently supported

**Steps to reproduce:**
1.run the ballerina help command
2.try to un install a package

**Affected Versions:**
0.970.0-beta0

**JDK**
java version "1.8.0_131"

**Related Issues (optional):**
 #2960
**Suggested Labels (optional):**
Runtime

**Comment by NatashaWso2** [comment]
Uninstall command is currently not supported, hence closing this issue.
