### ISSUE TITLE
[Installer][Windows] One of the packs get removed when installing with both platform and runtime

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7299]
**Steps to reproduce:**
1. Install the tools pack from ballerina-platform-windows-installer-x64-0.970.0-beta0
2. Then install the runtime pack from ballerina-runtime-windows-installer-x64-0.970.0-beta0 to a different location
3. Check if the pack installed from step 1 is available

**Issue**
The previous pack will be deleted. Same happens vise versa.

**Affected Versions:**
beta 0

**OS, DB, other environment details and versions:**
Windows 7

**Comment by ChanakaCooray** [comment]
@dilinisg, as for the moment, we assume that the user will only use platform or runtime at a time. That is the reason we are using the same name for platform and runtime distribution when installing as well. So when we are installing one, the installer will uninstall the other.

**Comment by dilinisg** [comment]
Closing the issue based on the previous comment
