### ISSUE TITLE
[Installer][Windows] Cannot run programs in Platform distribution

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7315]
**Steps to reproduce:**
1. Download the pack from ballerina-platform-windows-installer-x64-0.970.0-beta0
2. Copy samples\helloworld.bal inside the platform-home
3. Run the sample

**Issue**
The below error is logged. Please note that the same steps were followed in the runtime pack and the sample could be run successfully

```
C:\Ballerina\toolsNew\beta0\bin>ballerina.bat run ..\samples\helloworld.bal
The input line is too long.
The syntax of the command is incorrect.

C:\Ballerina\toolsNew\beta0\bin>ballerina run ..\samples\helloworld.bal
The input line is too long.
The syntax of the command is incorrect.
C:\Ballerina\toolsNew\beta0\bin>
```

**Affected Versions:**
Beta-0

**OS, DB, other environment details and versions:**
Windows 7

**Comment by ChanakaCooray** [comment]
@dilinisg, please check and verify this with the latest installer.

**Comment by dilinisg** [comment]
Verified in the Beta13 installer and it is working as expected. Therefore, closing the issue
