### ISSUE TITLE
[Ubuntu] the deb file installers does not show which location the installation happens

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#7317]
**Description:**
the deb file installers does not show which location the installation happens. The installation should print the location where the folder structure gets created.

Also it would be ideal if the packages being installed are listed along with the size of the installation. 

**Steps to reproduce:**
1.run the installer as shown on the logs below

**Affected Versions:**
 0.970.0-beta0

**JDK**
java version "1.8.0_131"

**output**
```
shavantha@shavantha-ThinkPad-X1-Carbon-4th:~/products/ballerina/platform$ sudo dpkg -i ballerina-platform-linux-installer-x64-0.970.0-beta0.deb 
(Reading database ... 327117 files and directories currently installed.)
Preparing to unpack ballerina-platform-linux-installer-x64-0.970.0-beta0.deb ...
Unpacking ballerina-0.970.0-beta0 (0.970.0-beta0) over (0.970.0-beta0) ...
```

From the folder structure I located that as /opt/ballerina/ballerina-0.970.0-beta0

**Comment by ThilinaManamgoda** [comment]
This is the default behaviour for deb installation. We can verify it with [Python deb installer](https://ubuntu.pkgs.org/16.04/ubuntu-main-amd64/python_2.7.11-1_amd64.deb.html) as well.

**Comment by shavantha** [comment]
closing the jira as per the above  comment
