### ISSUE TITLE
[Windows] Some files are not removed when the pack is removed

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7318]
**Steps to reproduce:**
1. Run the installer - ballerina-runtime-windows-installer-x64-0.970.0-beta0
2. Run ballerina init command
3. Build a sample. The some hidden files will be created
4. Run the installer again and remove the pack

**Issue**
Some files will not get removed when the pack is removed

![2](https://user-images.githubusercontent.com/1845370/38805719-d3c9d6f6-416e-11e8-9fe7-8a8bfc8daee2.PNG)

**Affected Versions:**
beta-0

**OS, DB, other environment details and versions:**
Windows 7

**Comment by ChanakaCooray** [comment]
@dilinisg, this is the expected behaviour of windows uninstall process. Because when you are uninstalling a program, it is not supposed to delete the user created files.

**Comment by dilinisg** [comment]
Closing based on the previous comment
