### ISSUE TITLE
[Mac Platform installer] When extracting, naming conflicts are occurring with ballerina runtime installer

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#7319]
**Description:**
If we have both Mac runtime installer and  platform installer, When extracting, both will have the same name and it is going to replace the other distribution.

**Steps to reproduce:**

- Extract the Mac run time installer
- Extract the Mac platform installer
- Since we cannot select a separate locations to extract in Mac, both of them will extract to the same default location.
- Then since it's containing the same name for runtime and platform. it will ask to replace considering both are same. (Screenshot attached)

**Affected Versions:**
ballerina-platform-macos-installer-x64-0.970.0-beta0.pkg
ballerina-runtime-macos-installer-x64-0.970.0-beta0.pkg

**OS, DB, other environment details and versions:**
OS-macOS High Sierra
Default fresh installers 

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/ballerina-platform-macos-installer-x64-0.970.0-beta0.pkg,ballerina-runtime-macos-installer-x64-0.970.0-beta0.pkg

<img width="621" alt="screen shot 2018-04-16 at 4 16 15 pm" src="https://user-images.githubusercontent.com/14923354/38805766-b1ab1974-4194-11e8-93aa-3cb2991899d7.png">

**Comment by chamithkumarage** [comment]
This behavior is acceptable (and discussed previously) as there's no point (and no use) of keeping both platform and the runtime running side-by-side. The user can always select one over the other.

**Comment by dilinisg** [comment]
Closing based on the previous comment
