### ISSUE TITLE
[Ubuntu][Runtime] [Platform] The re-installation should ideally indicate to the user that the folder structure already exist

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#7320]
**Description:**

 The re-installation should ideally indicate to the user that the folder structure already exist. Currently multiple installations happen but no information is shown. Proceeding with the installation should happen only after user provides feedback for a Y/N option

**Steps to reproduce:**
1.run the package installation steps

**Affected Versions:**
 0.970.0-beta0

**OS, DB, other environment details and versions:**

**JDK**
java version "1.8.0_131"
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
With the 1.1.0 release we have included this will not be a problem as users being push to use ballerina dist commands to get new versions. On the other hand if somebody downloads a installer and install it will be same location as now we don't keep separate files for each versions. Hence i am closing this issue
