### ISSUE TITLE
Installing ballerina instructions need to be updated

### ISSUE THREAD

**Issue by chamarasilva** [ballerina-platform/ballerina-lang#7321]
**Description:**
In Mac OS version, Once package install, It goes to "/Library/Ballerina" location and it automatically set into the path variable. It is not needed to specifically set the variable. But documentation [1] says invalid file path [/usr/local/ballerina] and instructed to set path variable. These need to be updated align with the new installation package.

**Comment by Susankha** [comment]
The same issue applies for Linux (with the actual installation path /opt/ballerina, but "UNINSTALLING BALLERINA" section of the document mentioned /usr/local/ballerina)

**Comment by Nashaath** [comment]
Fixed via [1].
[1] https://github.com/ballerina-platform/ballerina-www/pull/1059

**Comment by samgnaniah** [comment]
Closing this since this seems to be fixed now.
