### ISSUE TITLE
[Ubuntu] the runtime and platform installations happen at the same location overriding the previous installation

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#7323]
**Description:**
 the runtime and platform installations happen at the same location overriding the previous installation

**Steps to reproduce:**
1.invoke the runtime installation
2.invoke the platform installation

Ideally there should be two deferent folder paths

**Affected Versions:**
 0.970.0-beta0

**JDK**
java version "1.8.0_131"

**Comment by keizer619** [comment]
This is the expected behavior as there is no use case to install runtime and platform both and it allows to have multiple versions to be installed.
