### ISSUE TITLE
[Composer] : Browse button need to place in file save window 

### ISSUE THREAD

**Issue by chamarasilva** [ballerina-platform/ballerina-lang#7331]
**Description:**
When the bal file saving window, there should be a file browse button in order to browse the file patch easily. in current compose only way is to copy or type the entire file path to save drop down the window. 
![pic1](https://user-images.githubusercontent.com/7007542/38824763-f6185e90-41c7-11e8-8717-1c319f7c3939.png)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
