### ISSUE TITLE
Ballerina swagger generator fails when no annotations are present

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#7336]
**Description:**
If annotations are not present, swagger generation fails with error "ballerina: no value present". Should instead communicate which particular annotations are needed.

**Steps to reproduce:**
1. Download [demo_small.bal.txt](https://github.com/ballerina-platform/ballerina-lang/files/1917822/demo_small.bal.txt) and rename to demo_small.bal,
2. Run:
$ ballerina swagger export demo_small.bal
ballerina: no value present
$

**Affected Versions:**
Ballerina Tools version: 0.970.0-beta0

**Comment by sanjeewa-malalgoda** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/7613
