### ISSUE TITLE
Query params ignored on redirection

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#7339]
**Description:**

On redirection, if the "Location" header contains query params, they are ignored and thus redirection fails.

We also seem to not consider "[308 - Permanent Redirect](https://tools.ietf.org/html/rfc7238)" status code for redirection.

**Comment by Bhashinee** [comment]
Fixed in https://github.com/wso2/transport-http/pull/119 and https://github.com/ballerina-platform/ballerina-lang/pull/7412
