### ISSUE TITLE
Package builder adds "_" as the identifier to the match statement pattern even if user didn't enter any identifier value 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#7348]
**Description:**
In the package builder when creating a match statement pattern name is set to "_" when there is no identifier given by the user. This causes problem when generating source from the AST.

**Steps to reproduce:**
1. Add match statement as below 
```Ballerina
int | string a = 5;
        match a {
            int => {}
            string => {}
        }
```
2. Get the generated AST or try changing the diagram from composer. This will change the user's code to have "_" as the identifier in match patterns.

**Affected Versions:**
Current master

**Comment by Anoukh** [comment]
Type match has been removed with PR #11826. Hence this issue is not valid. It will not be valid for the new value match as well. Hence closing this issue.
