### ISSUE TITLE
"RequestLimits" infomation need to change in API docs

### ISSUE THREAD

**Issue by chamarasilva** [ballerina-platform/ballerina-lang#7358]
In API documentation says "RequestLimits" is an object. Since this is not an object and it is a record we need to change the API docs accordingly.

![image](https://user-images.githubusercontent.com/7007542/38861037-35357d42-424f-11e8-96e6-7db3b31bf6df.png)

**Comment by arukshani** [comment]
This is fixed. API doc properly display it as a type.
https://ballerina.io/learn/api-docs/ballerina/http.html#RequestLimits
