### ISSUE TITLE
"host" variable not works in ServiceEndpointConfiguration 

### ISSUE THREAD

**Issue by chamarasilva** [ballerina-platform/ballerina-lang#7360]
Value of the "Host" variable not taking into the "ServiceEndpointConfiguration". 

![pic2](https://user-images.githubusercontent.com/7007542/38862082-a720982c-4251-11e8-92d4-8e74e811d9b9.png)

![pic3](https://user-images.githubusercontent.com/7007542/38862247-0e20341a-4252-11e8-9dfe-3b9efc57c850.png)

**Comment by afkham** [comment]
This is actually the bind address. In your machine, the machine name and localhost both must be bound to 127.0.0.1. If you provide an IP address, this will work.
