### ISSUE TITLE
[Windows] The input line is too long error when running a sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7366]
**Steps to reproduce:**
1. Build the ballerina lang repo in a linux environment- 17-04-2018
2. Copy the runtime pack to a windows environment
3. Run a sample
`ballerina.bat run samples\hello-world.bal`

**Issue**
The following error is logged.
```
The input line is too long.
The syntax of the command is incorrect.
```
When searching the root cause for the error in the web, it says the error can be due to an issue in the java path. But, the samples are working successfully when it is run against a pack that is downloaded via the windows installer.

**OS, DB, other environment details and versions:**
Windows 7

**Comment by keizer619** [comment]
@ChanakaCooray is looking into this

**Comment by dilinisg** [comment]
Observed this issue again when installing the pack with the Ballerina Platform Installer.
Verified in both Windows 7 and 10 OS's. Hence, reopening

**Comment by ChanakaCooray** [comment]
@dilinisg, please check and verify this with the latest installer.

**Comment by dilinisg** [comment]
Verified in beta13 and it is fixed now. Hence, closing.
