### ISSUE TITLE
streams-within-services sample does not have instructions on how to invoke the service

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#7373]
**Description:**
streams-within-services sample does not have instructions on how to invoke the bal file

**Steps to reproduce:**
run ./ballerina run <path to streams-within-services.bal file>
**Affected Versions:**

the sh files should have a client.sh to indicate which endpoint to call

**Comment by kavithasub** [comment]
@shavantha this is fixed with 98f9a190e920ac43bbc6c218c9b1d8aa53c4a154, hence closing the issue.

**Comment by anupama-pathirage** [comment]
Closing as it is fixed with https://github.com/ballerina-platform/ballerina-examples/commit/98f9a190e920ac43bbc6c218c9b1d8aa53c4a154
