### ISSUE TITLE
[Sample] jms-durable-topic-message-subscriber fails in ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-lang#7413]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT
**Description:**

Run the below command to execute the sample
./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/jms-durable-topic-message-subscriber/jms-durable-topic-message-subscriber.bal

Sample jms-durable-topic-message-subscriber fails with the below error

ballerina: initiating service(s) in 'jms-durable-topic-message-subscriber.bal'
error: ballerina.runtime:CallFailedException, message: call failed
	at .:..<init>(jms-durable-topic-message-subscriber.bal:5)
caused by error, message: error while connecting to broker. Error creating connection: Unable to Connect
	at ballerina.jms:createConnection(<native>)

Please include in the description file if theres something other than executing the .bal file is necessary when running the sample.

**Comment by shavantha** [comment]
please move to https://github.com/ballerina-platform/ballerina-examples

**Comment by ShanikaWickramasinghe** [comment]
Moved to https://github.com/ballerina-platform/ballerina-examples
