### ISSUE TITLE
[Sample] jms-queue-message-producer-transactional fails in ballerina-0.970.0-beta1-SNAPSHOT

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-lang#7414]
**Environment**
Oracle jdk 1.8.0_121
ballerina-0.970.0-beta1-SNAPSHOT

**Description:**

Run the below command to execute the sample
./ballerina run /home/shanika/WSO2/ballerina-cmd4-BBEx/ballerina-examples/examples/jms-queue-message-producer-transactional/jms-queue-message-producer-transaction.bal

Throws the below error

error: ./jms-queue-message-producer-transaction.bal:26:9: variable assignment is required
compilation contains errors

Please include in the description file if theres something other than executing the bal file is necessary when running the sample.

**Comment by shavantha** [comment]
please move to https://github.com/ballerina-platform/ballerina-examples

**Comment by ShanikaWickramasinghe** [comment]
Moved to  https://github.com/ballerina-platform/ballerina-examples

**Comment by shavantha** [comment]
verified the issue with Ballerina 0.971.0
