### ISSUE TITLE
Cannot debug when running a package

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#7419]
**Description:**

Tried to debug when executing as a package, which failed.
````
ballerina run <Package> --debug 5006
````
There was no error. The debug points didn't get a hit

**Steps to reproduce:**

**Affected Versions:**
0.970-beta1

**Comment by pranavan15** [comment]
Closing issue as this is not there in the latest version.

**Comment by pranavan15** [comment]
Closing issue as this problem is not there in the latest Ballerina versions.
