### ISSUE TITLE
ballerina build command exit code

### ISSUE THREAD

**Issue by Nirothipan** [ballerina-platform/ballerina-lang#7470]
**Description:**

When encountering errors while executing the command **ballerina build <pkg_name>**, the exit code given is 0. 
Shouldn't this be other than 0?

**Affected Versions:**
0.970 beta-1-SNAPSHOT

**Comment by Kishanthan** [comment]
Can you check with the latest release? 
For any error cases (example : compilation error), the exit code would be 1. For success , the code would be 0. You can verify this from the main class too - https://github.com/ballerina-platform/ballerina-lang/blob/master/cli/ballerina-launcher/src/main/java/org/ballerinalang/launcher/Main.java

**Comment by Kishanthan** [comment]
Closing as this is not there in the latest version
