### ISSUE TITLE
[installer] [rhel] Un installing the ballerina installer not works

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#7488]
**Description:**
Uninstalling the ballerina installer not works on Redhat linux.

**Steps to reproduce:**
- install the ballerina installer
> [root@ballerinaonrethat3 sw]# rpm -ivh  ballerina-runtime-linux-installer-x64-0.970.0.beta1.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:ballerina-runtime-0.970.0.beta1-1################################# [100%]
- Uninstall using below [1]
> [root@ballerinaonrethat3 sw]# rpm --erase Ballerina
error: package Ballerina is not installed
- But when check the location is has installed
>[root@ballerinaonrethat3 sw]# ls /opt/
Ballerina  node-v8.11.1-linux-x64
[root@ballerinaonrethat3 sw]# ls /opt/Ballerina/
ballerina-runtime-0.970.0-beta1

[1] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-rpm-uninstalling

**Affected Versions:**
ballerina-runtime-linux-installer-x64-0.970.0.beta1.rpm

**OS, DB, other environment details and versions:**
rhel 7.3 | oracle jdk 1.8.0_161

**Suggested Labels (optional):**
Type/bug
Priority/High

**Comment by ThilinaManamgoda** [comment]
This issue has been fixed in latest RPM installer.

**Comment by kavithasub** [comment]
Thanks @ThilinaManamgoda .
Verified with beta13 installer as below, hence closing.
>[root@ballerinaonrethat3 cloud-user]# rpm --erase ballerina-platform
[root@ballerinaonrethat3 cloud-user]# ls /opt/Ballerina/
[root@ballerinaonrethat3 cloud-user]#
