### ISSUE TITLE
[Installers] Failed dependencies error in running ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-lang#7493]
**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Description:**
When run the ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm file using the following commands

rpm --install ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm
rpm -ivh ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm

Observed the following error in the console log

**error: Failed dependencies:
	/bin/sh is needed by ballerina-platform-0.970.0.beta1-1.x86_64**

But when use the command with the flag nodeps this error was not observed
rpm -ihv --nodeps ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm

**Comment by kavithasub** [comment]
This is verified with beta13 installer 
>[root@ballerinaonrethat3 cloud-user]# rpm -ivh ballerina/ballerina-runtime-linux-installer-x64-0.970.0-beta13.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:ballerina-runtime-0.970.0.beta13-################################# [100%]
[root@ballerinaonrethat3 cloud-user]# 
[root@ballerinaonrethat3 cloud-user]# ls /opt/Ballerina/
ballerina-platform-0.970.0-beta13  ballerina-runtime-0.970.0-beta13

@ShanikaWickramasinghe , you can close the issue now.
