### ISSUE TITLE
Defining a native function as private is not get affected

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#7500]
**Description:**
Even though we define a native function as private (or isPublic = false); it is not get affected. 

**Steps to reproduce:**
Eg: 

@Description {value:"Creates the forever runtime"}
@Param {value:"streamQuery: The siddhi query by which the siddhi app runtime is created"}
@Param {value:"inStreamRefs: References of the input streams in the forever"}
@Param {value:"inTableRefs: References of the input tables in the forever"}
@Param {value:"outStreamRefs: References of the output streams in the forever"}
@Param {value:"outTableRefs: References of the output tables in the forever"}
@Param {value:"funcPointers: References of the functions to invoke as the streaming action"}
native function startForever (string streamQuery, any inStreamRefs, any inTableRefs, any outStreamRefs, any outTableRefs, any funcPointers);

@BallerinaFunction(
        orgName = "ballerina", packageName = "builtin",
        functionName = "startForever",
        args = {
                @Argument(name = "streamQuery", type = TypeKind.STRING),
                @Argument(name = "inStreamRef", type = TypeKind.ARRAY),
                @Argument(name = "inTableRef", type = TypeKind.ARRAY),
                @Argument(name = "outStreamRef", type = TypeKind.ARRAY),
                @Argument(name = "outTableRefs", type = TypeKind.ARRAY),
                @Argument(name = "funcPointers", type = TypeKind.ARRAY)
        },
        returnType = {@ReturnType(type = TypeKind.NONE)},
        isPublic = false)

In above startForever is defined as a private function but still, we can access the function within the bal file.

**Comment by hasithaa** [comment]
@mohanvive Can you explain, what do you mean by bal file? Is it in same package or different package. ?

**Comment by mohanvive** [comment]
We are postponing the issue to find a better option. I have explored the possibility of migrating the function to runtime package and make it private. But it seems, we have to do a bit of hack to find out the symbol to create the function invocation node. BTW, it is a general problem that we have to solve.

**Comment by hasithaa** [comment]
This issue is fixed latest master. Additionally, We have removed the built-in module concept from JBallerina 1.0.0.
