### ISSUE TITLE
Docerina support for new function argument syntax

### ISSUE THREAD

**Issue by pzfreo** [ballerina-platform/ballerina-lang#7519]
**Description:**
Ballerina documentation needs to support defaultable/named parameters as well as "rest" parameters. I couldn't find a way to do this

**Steps to reproduce:**
Create a method with rest parameters (e.g. (string... rest)) and there is no clear way to document these.

**Affected Versions:**
All

**OS, DB, other environment details and versions:**
NA

**Related Issues (optional):**
NA

**Suggested Labels (optional):**
Docerina

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Language has evolved a lot since this. Now The language has [`Ballerina Flavored Markdown`](https://v1-0.ballerina.io/spec/lang/v2019R3/#section_9.3)  to address the documentation problem in general.
> The documentation for the parameters and a return value must consist of a Markdown list, where each list item must have the form `ident - doc`, where `ident` is either the parameter name or return, and `doc` is the documentation of that parameter or of the return value.

e.g:
```ballerina
    # Adds parameter `x` and parameter `y`
    # + x - one thing to be added
    # + y - another thing to be added
    # + return - the sum of them
    function add (int x, int y) returns int { return x + y; }
```
