### ISSUE TITLE
[Windows Installer] The banner in the installer is missing

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7551]
**Description:**
The banner which was on the left side is missing

![4](https://user-images.githubusercontent.com/1845370/38996047-3afc2246-43e2-11e8-95bb-39b8d23c0d1d.PNG)

**Affected Versions:**
Ballerina Platform installer beta1

**OS, DB, other environment details and versions:**
Windows 7

**Comment by ChanakaCooray** [comment]
@dilinisg, please check and verify this with the latest installer.

**Comment by dilinisg** [comment]
Verified in the Beta13 installer and the banner is visible. Hence, closing
