### ISSUE TITLE
When service obtained using typedesc unable to have global variables inside it

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#7577]
**Description:**

In use case if the user defines the service and specifies the service type to be used in the in the config. The following method is used to obtain the service from its type:
        `Service service = BLangConnectorSPIUtil.getServiceFromType(context.getProgramFile(), clientServiceType);`

When a global variable is used in this `service` which is obtained by using its type a `NullReferenceException` is thrown as follows:

```
error: ballerina.runtime:CallFailedException, message: call failed
        at .:chatApp.onText(websocket-chat-application.bal:51)
caused by ballerina.runtime:NullReferenceException
        at .:broadcast(websocket-chat-application.bal:64)
```

This is because the callback service needs to be initialized and it should be done only once. 

**Steps to reproduce:**
The following code will throw an error:
https://gist.github.com/riyafa/5d44baf163b17a2898f14b2b421c5384
Here the map is defined inside the `WebSocketService`.
When the map is defined globally as in the following it works fine:
https://github.com/ballerina-platform/ballerina-examples/blob/84f4a0168fb217a3a11e24771e3784bd28eba5e4/examples/websocket-chat-application/websocket-chat-application.bal#L35-L39

**Comment by riyafa** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/4180

**Comment by hasithaa** [comment]
@riyafa , With new service re-design, we can't have a state within the service. Hence we don't have this usecase anymore. Shall we resolve this issue?
