### ISSUE TITLE
Unable to compile ballerina project with two or more packages

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#7582]
**Description:**
Compile errors are printed when compiling a package when there are two packages. 

**Steps to reproduce:**
- Create a ballerina project with two packages with ballerina init.

```bash
.
├── .ballerina
│   └── repo
│       └── $anon
│           └── car_pkg
│               └── 0.0.0
│                   └── car_pkg.zip
├── .gitignore
├── .svnignore
├── Ballerina.toml
├── car_pkg
│   └── car.bal
├── target
│   └── car_pkg.balx
└── van_pkg
    └── van.bal
```

- Compile a single package.

``` bash
anuruddha$ ballerina build car_pkg/
error: van_pkg/van.bal:7:5: undefined field 'port' in struct 'ballerina.net.http:ServiceEndpoint'
error: van_pkg/van.bal:14:1: service struct 'ballerina.net.http:Service' does not match with service type interface
error: van_pkg/van.bal:17:9: not enough arguments in call to 'setStringPayload()'
error: van_pkg/van.bal:18:13: not enough arguments in call to 'respond()' 
```

- It looks like build tries to compile both packages even though I have specified single package in build command. Both packages are having the code with correct syntax.

**Affected Versions:**
0.970.0-beta3

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**

**Comment by lankavitharana** [comment]
Tried in latest master branch and works fine for me, hence closing the issue, please check and reopen with a sample if the issue still exists for you.
