### ISSUE TITLE
[WebSocket] Enable client endpoint to block channel read

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#7597]
**Description:**
A user of the client endpoint must be able to block channel read to perform other tasks before receiving data from the backend. This is essential for gateway scenarios like proxy, mediation and broadcasting.

Possible changes would be to have an `autoread` config for the client endpoint which is true by default and can be made false. If made false a method must be available for the endpoint namely `startReading` that would start reading from the channel.

**Comment by irunika** [comment]
Already fixed in master
