### ISSUE TITLE
Config files cannot have # in the middle of a string config value.

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#7668]
**Description:**
Cannot parse the config file if there is a '#' char in a config value.

**Steps to reproduce:**
Example:
```
my.config.value="foo#bar"
```

Example error:
```
', ' 30:0 extraneous input 'i' expecting {<EOF>, '	', '
', '
', ' '}
```

**Affected Versions:**
0.970.0-beta0

**OS, DB, other environment details and versions:**
MAC

**Comment by riyafa** [comment]
Closing this as it has been reported again in a newer issue https://github.com/ballerina-platform/ballerina-lang/issues/9292
