### ISSUE TITLE
Variables cannot be used with union types.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#7700]
**Description:**

Refer the following sample to reproduce the error.
```ballerina
public type ParamTest string|int;
function testIssue() {

    string s1 = "Anne";
    foo("John"); //Literal values Ok
    foo(s1); //Variables gives error
}

function foo(ParamTest... p1) {
    io:println(p1);
}
```

Error:
`org.ballerinalang.util.exceptions.BLangRuntimeException: error: error, message: org.ballerinalang.model.values.BRefValueArray cannot be cast to org.ballerinalang.model.values.BStringArray`

**Comment by lankavitharana** [comment]
This works in current master, hence reducing the priority of the issue (keeping the issue to track and add a proper test case)

**Comment by lankavitharana** [comment]
test PR merged, hence closing
