### ISSUE TITLE
Quotes should be omitted when reading/writing csv records

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#7705]
**Description:**
Currently when reading composite CSV records i.e "foo,1986","CC24" the composite fields return "foo,1986" with the quotes included.

Ideally this should be transparent to the caller. The same applies when writing records where if a composite field is provided the quotes should be placed internally

**Steps to reproduce:**

1. Read composite CSV record 
2. Notice the records being enclosed with quotes 

**Affected Versions:**
0.970.0-beta6

**OS, DB, other environment details and versions:**
OSX

**Comment by wggihan** [comment]
This issue fixed now.
