### ISSUE TITLE
Nested transactions giving inconsistent behaviour with coordinatior during failures

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#7706]
**Description:**
Nested transactions send beginTransaction notification to the coordinator with the same global id and block id during the retry attempts. So coordinator gives already registered error during the retry attempt.

**Comment by Manuri** [comment]
Closing as this is fixed after changes in https://github.com/ballerina-platform/ballerina-lang/pull/12010
