### ISSUE TITLE
Errors are collected twice

### ISSUE THREAD

**Issue by nirmal070125** [ballerina-platform/ballerina-lang#7711]
**Description:**

<img width="1123" alt="screen shot 2018-04-21 at 9 52 24 am" src="https://user-images.githubusercontent.com/413016/39080603-6981d1ce-454f-11e8-8c88-d4431793a483.png">

**Steps to reproduce:**
Have an object and function interfaces without function implementations.

**Affected Versions:**
Ballerina 0.970.0-beta6-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lankavitharana** [comment]
I tried with below sample code with master branch

```ballerina
function main(string... args) {
        Person p = new;
}

type Person object {
        public {
                int age,
        }

        function test1();

        function test2();
};
```
it gives the following error, which is correct without any duplicates

error: ./test1.bal:3:13: cannot initialize object 'Person', no implementation for the interface 'Person.test1'
error: ./test1.bal:3:13: cannot initialize object 'Person', no implementation for the interface 'Person.test2'
compilation contains errors

hence closing the issue
