### ISSUE TITLE
[HTTPs] NPE when certPass is not given

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#7784]
**Description:**
Following code segment produces a NPE if the certPass is not provided. (org/ballerinalang/net/http/HttpConnectionManager.java)

```
if (!listenerConfiguration.getKeyStoreFile().equals(config.getKeyStoreFile())
                    || !listenerConfiguration.getKeyStorePass().equals(config.getKeyStorePass())
                    || !listenerConfiguration.getCertPass().equals(config.getCertPass())) {
                return true;
            }
```
**Steps to reproduce:**

Create two HTTPS services which binds to the same port.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Bhashinee** [comment]
Fixed in above PR. But we do not expect users to create two ballerina services binding to the same port.
