### ISSUE TITLE
[BBE] : "Async" sample giving compilation error. 

### ISSUE THREAD

**Issue by chamarasilva** [ballerina-platform/ballerina-lang#7860]
Env :  v0.970.0-beta12 composer

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/7007542/39143215-d263a1a2-474a-11e8-9684-cc25706207d4.png">

**Comment by afkham** [comment]
This function has been renamed to runtime:sleep()

**Comment by afkham** [comment]
Fixed
