### ISSUE TITLE
Improve Ballerina crash log implementation

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#7863]
Ballerina crash logs use Java.util logging framework. Logging properties file is bundled with the ballerina-logging jar file. I see no reason to have separate properties file as we expect no one to modify it. There we can hard-code these properties and their values in the code itself to clean up the implementation. 

Here is the PR which was merged 
https://github.com/ballerina-platform/ballerina-lang/pull/7862

**Comment by vinok88** [comment]
In https://github.com/ballerina-platform/ballerina-lang/pull/18323/files we are creating the crash logger on demand. We use the logging.properties for console logging now. Having the logging.properties is useful for them since they can use it to fine-tune their standard library based logging.
