### ISSUE TITLE
Windows security alert when running the examples

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#7873]
**Description:**
Do we have a way to get rid of this  security alert when running the samples?

![1](https://user-images.githubusercontent.com/1845370/39166949-f069973e-477b-11e8-9629-0d8927c8ae50.JPG)

**Comment by ChanakaCooray** [comment]
@dilinisg, this is not related to the installers, you can notice this issue when you are installing ballerina without the installers with fresh JRE as well.

**Comment by dilinisg** [comment]
Removing the installer tag based on the previous comment

**Comment by afkham** [comment]
Isn't this a standard warning because Ballerina tries to open ports? Don't you get the same with Tomcat as well for example?

**Comment by ChanakaCooray** [comment]
@afkham, but we can notice this warning even when running "Ballerina" only in command prompt without any command. But seems to be no network call or port opening in that path.

![ballerina-network-call](https://user-images.githubusercontent.com/4003117/39304589-c2b3e36e-4977-11e8-8347-8cc18f2a2c1c.png)

**Comment by keizer619** [comment]
Since this is for JRE and cannot be avoided by installers or Ballerina side i will be closing this. 

Please feel free to reopen if there is any concern
