### ISSUE TITLE
[HTTP] Headers does not replace with setHeader() function when a request is used more than one time

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#7876]
**Description:**

In a scenario, where we send a GET request after setting an header, afterwards if we change the same header value and send a GET request again, it is observed that the second request contains 2 headers with the same key. 

The expected behavior is to replace the header value with the new value, but instead of that, it adds another header with same key.

Please note that we can reuse the **http:Request** object for multiple calls after fixing https://github.com/ballerina-platform/ballerina-lang/issues/7522.

**Steps to reproduce:**

After exectuting following program with enabling HTTP trace logs, it is observed that in the second GET request there are 2 headers as follows

Authorization: 1
Authorization: 2

```
import ballerina/io;
import ballerina/http;

endpoint http:Listener httpListener {
    port:9090
};

service<http:Service> hello bind httpListener {
    sayHello(endpoint conn, http:Request req) {
        string header = req.getHeader("Authorization");
        io:println("Header value : " + header);
        _ = conn->respond(new);
    }
}

endpoint http:Client httpClient {url:"http://localhost:9090"};

function main(string... args) {
    http:Request req = new;
    req.setHeader("Authorization", "1");

    var response = httpClient->get("/hello/sayHello", request = req);
    match response {
        http:Response res => io:println(res);
        http:HttpConnectorError err => io:println(err);
    }

    req.setHeader("Authorization", "2");

    response = httpClient->get("/hello/sayHello", request = req);
    match response {
        http:Response res => io:println(res);
        http:HttpConnectorError err => io:println(err);
    }
}
```

**Affected Versions:**
Ballerina 0.970.0-beta13
Ballerina 0.970.0-beta14-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by arukshani** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/8136
