### ISSUE TITLE
Cannot initialize record literals if LHS type is a union type

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#7891]
**Description:**
If we define a variable definition with LHS type as a union with record literal type, then we cannot initialize that variable in a single line

**Steps to reproduce:**
```ballerina
Person? p = { age:9, name:"saman"};
```
above code doesn't work
workoround is 
Person a = {age:9, name:"saman"};
Person? p = a;

**Comment by Kishanthan** [comment]
The above works now for null, but the following does not work for error.

```
Person|error p = { age:9, name:"saman"};
```
