### ISSUE TITLE
Add structural equivalency compile time check

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#7955]
**Description:**
Related to discussion at - [https://groups.google.com/forum/#!topic/ballerina-dev/J0QYiYIKCNg](https://groups.google.com/forum/#!topic/ballerina-dev/J0QYiYIKCNg)

In summary, when two structures are converted, 
* The two structs are equivalent (this will be a safe conversion)
* The two structs are not equivalent from RHS -> LHS, but LHS -> RHS is equivalent, that means, there is a chance in the runtime, that the runtime equivalency test is successful (this will be an unsafe conversion at compile time)
* The two structs are not equivalent from both RHS -> LHS and LHS -> RHS, thus, there's no chance this can be equivalent in runtime also, so this should be a compile time error.

**Comment by pubudu91** [comment]
There's no construct called structs in the language anymore. The equivalency/subtyping rules for structural types objects and records were updated/added over several PRs such as #10473, #11353, #15180. Hence closing this issue.
