### ISSUE TITLE
Files are not shown in the folder when a sample is opened from BBE

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8032]
**Steps to reproduce:**
1. Open a sample from BBE

**Issue**
![1](https://user-images.githubusercontent.com/1845370/39245406-5218ae62-48b1-11e8-8463-c72e691e1237.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox 59.0.2 (64-bit)

**Comment by dilinisg** [comment]
Updated the composer script to the latest and it worked. Hence, closing

**Comment by dilinisg** [comment]
Observed this again in both Firefox and Chromium. Hence, reopening

**Comment by kavithasub** [comment]
This I could observe in Firefox-59.0.2.

**Comment by hevayo** [comment]
Fixed in master
