### ISSUE TITLE
[composer] improve with an option to clear the console output

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8034]
**Description:**
Console output getting clear if I re-run a bal file, but no option to clear it by user preference.

![clear](https://user-images.githubusercontent.com/15671620/39245559-c54350ae-48b1-11e8-8364-25b85034978c.jpeg)
**Affected Versions:**
beta-15

**OS, DB, other environment details and versions:**
Firefox-59.0.2

**Suggested Labels (optional):**
Type/improvement

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
