### ISSUE TITLE
Wrong syntax in the sample file opened when creating a project

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8037]
**Steps to reproduce:**
1. Create a project and verify the sample file

![2](https://user-images.githubusercontent.com/1845370/39246102-366fdd5a-48b3-11e8-9f73-1b14d532b8d5.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox 59.0.2 (64-bit)

**Comment by hevayo** [comment]
fixed with 0.970.0-beta16
