### ISSUE TITLE
[composer] [UX] tooltip not bring to front when mouse hover on the code at edge places

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8039]
**Description:**
For $subject, see image

![tooltip](https://user-images.githubusercontent.com/15671620/39246391-230f31b0-48b4-11e8-8eaf-f5d2aa1fb199.jpeg)

**Affected Versions:**
beta15

**OS, DB, other environment details and versions:**
Firefox-59.0.2

**Suggested Labels (optional):**
Type/bug
Priority/major
UX

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this issue.

![tooltip](https://user-images.githubusercontent.com/13446645/45357309-8ea23980-b5e3-11e8-9b0c-1e1a9127a2ef.png)
