### ISSUE TITLE
Add organization support in debugger

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#8041]
**Description:**
Currently there is no way to identify whether the debug hit occurred on current project or SDK. So we need to add the support to consider the organization as well.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing since this requirement is no longer valid with the new jBallerina debugger implementation
