### ISSUE TITLE
No way to distinguish two files with same name in debug hit

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#8042]
**Description:**
```
project
   |-abc
       |-def/main.bal
       |-xyz/main.bal
```
In above project structure, if debug hit occurs in one of the main files, only the name file will be sent. There is no way to distinguish the file.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pranavan15** [comment]
This issue is resolved by PR: #10760. Hence, closing this issue.
