### ISSUE TITLE
Misalignment of a drop down 

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8045]
**Steps to reproduce:**
1. Right click towards the right side of the menu
![3](https://user-images.githubusercontent.com/1845370/39248724-7a651168-48ba-11e8-9755-e4e3632b1db8.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Fixed in 0.975.0
