### ISSUE TITLE
Design view is not loaded for some samples

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8046]
**Steps to reproduce:**
1. Open sample from the BBE and verify the design view
Observed this issue in below samples
- failover
- try-catch-finally
- hht-failover

![4](https://user-images.githubusercontent.com/1845370/39248906-fdc896ec-48ba-11e8-950d-db25cea26c6b.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox 59.0.2 (64-bit)

**Comment by kavithasub** [comment]
This is observed for more service samples (including above functions) on Firefox-59.0.2.
