### ISSUE TITLE
[composer] Explorer->newfile doesn't show the text for filename when entering

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8047]
**Description:**
when adding file name is not readable as below
![file1](https://user-images.githubusercontent.com/15671620/39248861-dcc2c152-48ba-11e8-8c40-ec9f90e6c69f.jpeg)

once add succeed it shows as below
![file2](https://user-images.githubusercontent.com/15671620/39248903-fc61e7d6-48ba-11e8-9b91-adeeb2f81bd6.jpeg)

**Affected Versions:**
beta15

**OS, DB, other environment details and versions:**
Firefox-59.0.2

**Comment by nadeeshaan** [comment]
cannot reproduce in the latest master.
