### ISSUE TITLE
[composer] Create File from welcome page opens Open File window

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8049]
**Description:**
As below click on create file button
![create2](https://user-images.githubusercontent.com/15671620/39249528-7b8abe06-48bc-11e8-8ca6-3987b968264a.jpeg)

opens window as below
![create](https://user-images.githubusercontent.com/15671620/39249548-84467c06-48bc-11e8-8e04-d0af83c1b637.jpeg)

Expect: user expectation would be create a new file

**Affected Versions:**
beta15

**OS, DB, other environment details and versions:**
Firefox-59.0.2

**Comment by hevayo** [comment]
Renamed Create file to Open file. fixed in 0.970.0-rc
