### ISSUE TITLE
Reformat code is removing the comments and free spaces added

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8051]
**Description:**
Reformat code is removing the comments and free spaces added

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/4854
