### ISSUE TITLE
[Composer]Delete button of the design view is clickable even delete is working in edit option.

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8053]
**Description:**
Delete button of the design view is not working

**Steps to reproduce:**
Create a new bal file
Add a code segment
Click on the delete button in the design view.
delete button is not doing what it suppose to do. (If delete is only possible in edit option, We should not make it as clickable in other windows)

**Affected Versions:**
ballerina-tools-0.970.0-beta15-SNAPSHOT

**OS, DB, other environment details and versions:**
macOS High Sierra
ballerina-tools-0.970.0-beta15-SNAPSHOT
JDK 1.8.0_152

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/High
Affected/ballerina-tools-0.970.0-beta15-SNAPSHOT

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9299
