### ISSUE TITLE
Fix inconsistencies in running bal files with services and main

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#8055]
**Description:**
With PR - [1] - https://github.com/ballerina-platform/ballerina-lang/pull/8010/files
ballerina will only hold the server from exiting if the entry package contains both service and main, say entry package just have the main function but an import package has a service, then what happens is, the service starts, main executes, service stops and bvm exists. 

need to finalize correct behavior in scenarios like above

**Comment by hasithaa** [comment]
Now spec defined correct behavior. @lankavitharana if JBalallerina has implemented the correct behavior, shall we close this issue?

**Comment by lankavitharana** [comment]
@hasithaa Actually "Module and program execution" section in the spec doesn't have specific details about the main function execution order, the current execution order of the implementation is as below
1) initialization phase
2) run main function (if any)
3) listener phase

and also the behavior, when there is a main and service are together, is described as the above description, (means, unless there is a service in the current package which has the main, execution will automatically exit regardless of services defined in the dependent packages). I think we need to  come to a conclusion on that, in the implementation

**Comment by hasithaa** [comment]
Actually Spec mentions this, I have extracted the text from the spec. (2019R3+)

Module initialization : 
>A module's initialization function performs expression evaluation so as to initialize the identifiers declared in the module's declarations; if evaluation of an expression completes abruptly, then the module initialization function immediately returns the error value associated with the abrupt completion. If a module defines a function named __init, then a module's initialization function will end by calling this function; if it terminates abruptly or returns an error, then the module's initialization function will return an error value. Note that the __init function of the root module will be the last function called during a program's initialization phase.

Entry Function (This is `main` function right now)
>This specification does not define any mechanism for processing the program command-line arguments typically provided by an operating system. The Ballerina standard library provides a function to retrieve these command-line arguments. In addition, the Ballerina platform provides a convenient mechanism for processing these arguments. This works by generating a new command-line processing module from the specified root module. The __init function of the generated module retrieves the command-line arguments, parses them, and calls a public function of the specified root module (typically the main function). The parsing of the command-line arguments is controlled by the declared parameter types, annotations and names of the public functions. The generated module, which imports the specified root module, becomes the new root module.

Listener Phase
> If the initialization phase of program execution completes successfully, then execution proceeds to the listening phase, which is described in the next section. The termination of the listening phase, which may be successful or unsuccessful, terminates the program execution.

>The methods defined by the Listener abstract object type allow for the management of the lifecycle of a listener object and its attached services. A listener declaration registers a listener object with a module, so that it can be managed by the module. The runtime state of each module includes a list of listener objects that have been registered with the module. A listener object that has been registered with a module is called a module listener

> If at the start of the listening phase of program execution there are no module listeners, then the listening phase immediately terminates successfully. Otherwise, the __start method of each module listener is called; if any of these calls returns an error value, then the listening phase terminates unsuccessfully with this error value as its return value.

Termination
> The listening phase of program execution continues until either the program explicitly exits, by calling a standard library function, or the user explicitly requests the termination of the program using an implementation-dependent operating system facility (such as a signal on a POSIX system). In the latter case, the __gracefulStop or __immediateStop method of each registered listener will be called before termination.

See service `Service declaration` how __attach method of listeners works.

**Comment by lankavitharana** [comment]
@hasithaa ok earlier I understood that like main is not a part of the initialization phase. Since it's the last part of the initialization phase then, we are doing what spec says, the only deviation is that we are stopping the listeners if there is no module-level listener defined in the entry module(even though there are module-level listeners defined in dependent modules). This was required for the transaction module.
If there is ballerina module with just a main method(no service) and it imports transaction module, then keeping the transaction listener up and running even after executing the main is what we were trying to avoid with this. Anyway, for the transactions, that design is going to change so that transaction listener won't be a module-level listener anymore(@warunalakshitha please note) and they will explicitly manage transaction listener lifecycle if there is a transaction(transaction implementation will take care of that).
So we can change the current execution behavior, once the transaction module is properly refactored.

**Comment by hasithaa** [comment]
This is already fixed in SL and other improvements are captured here https://github.com/ballerina-platform/ballerina-lang/issues/27338.
