### ISSUE TITLE
Cannot import a swagger definition

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8064]
**Steps to reproduce:**
1. Download the swagger definition from Swagger Pet store
http://petstore.swagger.io/v2/swagger.json
2. Import it 

![8](https://user-images.githubusercontent.com/1845370/39253410-6b211a48-48c5-11e8-8f42-56a69c0ad371.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
