### ISSUE TITLE
[Composer] Create project option is not working in the welcome page

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8068]
**Description:**
when we click on the create project option in the welcome page, it will not loading the create project window.

**Steps to reproduce:**
Go to the Welcome page
Click on the Create project option
There's no create project window and it will just open a bal file

**Affected Versions:**
ballerina-tools-0.970.0-beta15-SNAPSHOT

**OS, DB, other environment details and versions:**
macOS High Sierra
ballerina-tools-0.970.0-beta15-SNAPSHOT
JDK 1.8.0_152

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/High
Affected/ballerina-tools-0.970.0-beta15-SNAPSHOT

**Comment by nadeeshaan** [comment]
Cannot reproduce in the latest master
