### ISSUE TITLE
[composer] create project -> hello_service.bal needs to be fixed

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8069]
**Description:**
As $subject it should be fixed with 
>    // Objects and structs can have function calls
        response.setPayload("Hello Ballerina!\n");

see below error,

![hello](https://user-images.githubusercontent.com/15671620/39254270-563b8e36-48c7-11e8-9e6c-a5e838df5ae6.jpeg)

**Affected Versions:**
beta15

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox-59.0.2

**Comment by hevayo** [comment]
Fixed in beta17
