### ISSUE TITLE
Difficult to distinguish errors and warning messages

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8073]
**Description:**
ballerina: HTTP trace log enabled warning/info message seems like an error message. Better to change the color

![9](https://user-images.githubusercontent.com/1845370/39256860-97fb6ae8-48cd-11e8-9094-9ba2da129275.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
