### ISSUE TITLE
Outdated content in the Composer About page

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8076]
Issues
1. Version is wrong
2. Git issues tracker redirect the user to ballerina attic
https://github.com/ballerina-attic/composer/issues 

![12](https://user-images.githubusercontent.com/1845370/39257590-84bb17f6-48cf-11e8-8a61-4abc7f465821.png)

**Comment by kavithasub** [comment]
Better if the Version should be updated dynamically.
