### ISSUE TITLE
[composer] Observed deleting from design not updating the source, but vise vera works

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8077]
**Description:**
Checked with http_client.bal 
- deleted from source as was updates the design view
- deleted from design as below, but it was not updates the source. I have tried by saving and re-open the file. in case design view doesn't open.
![edit2](https://user-images.githubusercontent.com/15671620/39257815-0efc63f2-48d0-11e8-85cb-8209ce7ccd2a.jpeg)
![edit3](https://user-images.githubusercontent.com/15671620/39257819-1173f398-48d0-11e8-8c7d-ffa76a2f7c9d.jpeg)

**Affected Versions:**
beta15

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox-59.0.2

**Comment by nadeeshaan** [comment]
Cannot reproduce in the latest master ee2415a296c8ec08e8491a8a57ce86d47e1483ec
