### ISSUE TITLE
[Composer] expand and collapse button is not working in non-edit mode 

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8079]
**Description:**
In the design view, we have the expand and collapse button, but this is not working in non-edit mode.
if it's design that way, it should show only in edit mode.

**Steps to reproduce:**
Go to the design view 
click on the expand and collapse button.
It won't work as expected. But it's working in edit mode.
If this is working only in edit mode, then this icon should  show in that mode only

**Affected Versions:**
ballerina-tools-0.970.0-beta15-SNAPSHOT

**OS, DB, other environment details and versions:**
macOS High Sierra
ballerina-tools-0.970.0-beta15-SNAPSHOT
JDK 1.8.0_152

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/High
Affected/ballerina-tools-0.970.0-beta15-SNAPSHOT

**Comment by NatashaWso2** [comment]
The expand and collapse button works fine in the non-edit mode in ballerina 0.981.2-SNAPSHOT
Since this issue is resolved closing this issue.
