### ISSUE TITLE
Formatting issue in the properties of endpoint

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8085]
**Description:**
1. Original content is as follows.
Sample can be found from https://central.ballerina.io/packages/wso2/twitter
2. Add a if condition from the design view
![13](https://user-images.githubusercontent.com/1845370/39259266-9da99d74-48d3-11e8-9cad-0e04066ed030.png)
3. Undo the addition

**Issue**
Formatting issue in the properties of endpoint
![14](https://user-images.githubusercontent.com/1845370/39259291-b20522f2-48d3-11e8-80e7-003333a299cc.png)

**Comment by NipunaMarcus** [comment]
Formatting is not yet properly implemented for the language server hence it not available in composer. We are in the process of implementing formatting.

**Comment by NipunaMarcus** [comment]
Initial formatting implementation added support for the endpoint formatting. PR:https://github.com/ballerina-platform/ballerina-lang/pull/9182

Hence closing this issue.
