### ISSUE TITLE
Cannot add headers again when all headers were removed in try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8120]
**Steps to reproduce:**
1. Run a service and go to try it
2. Add a header 
3. Remove the header

**Issue**
No option to add headers again
![20](https://user-images.githubusercontent.com/1845370/39288558-212a226e-4946-11e8-8e15-bac0ff419285.png)

**Affected Versions:**
Tools - beta 17

**OS, DB, other environment details and versions**
Firefox Browser - 59.0.2 (64-bit)

**Comment by shavantha** [comment]
verified the fix for this issue with 0.970.2
