### ISSUE TITLE
[composer] Edit mode - all add symbols "+" are appears when collapse the main window(localObserver)

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8123]
**Description:**
As $subject see in image1, I can view all in expand the resource windows under edit mode. In image2 I tried to collapse the main window(localObserver) and observed a UX issue.
image1
![correctedit](https://user-images.githubusercontent.com/15671620/39289163-90421042-4948-11e8-8465-117d7367796a.jpeg)

image2
![issueedit](https://user-images.githubusercontent.com/15671620/39289167-95e2cf3c-4948-11e8-9fa2-4a1ef1e250aa.jpeg)

**Affected Versions:**
beta17

**OS, DB, other environment details and versions:**
Firefox-59.0.2
Ubuntu 15.10

**Comment by shavantha** [comment]
verified with 0.970.2
