### ISSUE TITLE
[composer] [ux] syntax error indicator disappears, if user navigates to bal files back forth

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8124]
**Description:**
As $subject, see I there is a syntax error in image1. Save the bal file now, and navigate to another bal file and come back. As in image2 error indicator (redline) has disappeared.
image1
![syntax](https://user-images.githubusercontent.com/15671620/39289784-22f14b86-494b-11e8-98ec-1a5fb9d324b8.jpeg)

image2
![syntax2](https://user-images.githubusercontent.com/15671620/39289830-37539156-494b-11e8-9c11-1c2358137435.jpeg)

**Affected Versions:**
beta17

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox-59.0.2

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
