### ISSUE TITLE
The search window is not visible and it will be opened when "Change all occurrences" is clicked

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8128]
**Steps to reproduce:**
1. Open a code
2. Right click on the code and select  "Change all occurrences"

**Issue**
The search window will be opened and it is not visible and disappears instantly
![22](https://user-images.githubusercontent.com/1845370/39290031-d7c6ad4e-494b-11e8-9c15-05503bb24efc.png)

**Comment by nadeeshaan** [comment]
This is common to both VSCode and Monaco. Specific case for the Monaco editor. Hence closing
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/1329674/39308122-47413e42-4982-11e8-8e2f-3ac90b0e2fe5.gif)
