### ISSUE TITLE
Change all occurrences is not working

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8132]
**Steps to reproduce:**
1. Write click on a code segment and click on "Change all occurrences"

Nothing happens, so how to change is not clear.

**Affected Versions:**
Tools - beta 17

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by NipunaMarcus** [comment]
When you click on "Change all occurrences" if editor finds the same text in the file it will select and add multiple cursors at those locations which you can change at once. Please refer below screenshot.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9109762/39303338-620c1792-4973-11e8-9dae-679fe3a2591d.gif)
