### ISSUE TITLE
Cannot add an endpoint from the design view for the second time

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8134]
**Steps to reproduce:**
1. Add a endpoint from the design view

**Issue**
1. The endpoint will be added to the source view, but it will reflect in the design view
2. Also, you can't add another endpoint from the design view as the + button disappears

**Affected Versions:**
Tools - beta 17

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by nadeeshaan** [comment]
Fixed in latest master, hence closing the issue
