### ISSUE TITLE
[composer] Help-> about window still shows beta0, we should update the version of composer dynamically.

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8146]
**Description:**
As $subject, see below.
![version](https://user-images.githubusercontent.com/15671620/39299202-cd9abb0c-4965-11e8-9397-c74872658f7c.jpeg)

**Affected Versions:**
beta17

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox-59.0.2

**Comment by kavithasub** [comment]
Duplicate #8076

**Comment by shavantha** [comment]
vefiried
