### ISSUE TITLE
Debug points will be added in all files when there are files with same name

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8152]
**Steps to reproduce:**
1. Create a service named hello
2. Create a program named hello
3. Add a debug point to the line 3 of hello service

**Issue**
A debug point will be added to the line 3 of hello program too

**Affected Versions:**
Tools - beta 17

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
