### ISSUE TITLE
[installer] [deb] "failed to create symbolic link ‘/usr/bin/composer’: File exists" when re-installing the deb

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8176]
**Description:**
As $subject see 
>kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ sudo dpkg -r ballerina-0.970.0-beta19 
(Reading database ... 245976 files and directories currently installed.)
Removing ballerina-0.970.0-beta19 (0.970.0-beta19) ...
kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ 
kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ ls /opt/
google  ibm  idea-IC-172.4155.36  skypeforlinux  sublime_text  sybase
kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ 
kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ sudo dpkg -i /home/kavitha/BALERINA/19/ballerina-platform-linux-installer-x64-0.970.0-beta19.deb 
Selecting previously unselected package ballerina-0.970.0-beta19.
(Reading database ... 243750 files and directories currently installed.)
Preparing to unpack .../ballerina-platform-linux-installer-x64-0.970.0-beta19.deb ...
Unpacking ballerina-0.970.0-beta19 (0.970.0-beta19) ...
Setting up ballerina-0.970.0-beta19 (0.970.0-beta19) ...
ln: failed to create symbolic link ‘/usr/bin/composer’: File exists

after un-install
>kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ ls /usr/bin/ballerina 
ls: cannot access /usr/bin/ballerina: No such file or directory
kavitha@kavitha-ThinkPad-X1-Carbon-3rd:/$ ls /usr/bin/composer 
/usr/bin/composer

**Steps to reproduce:**
- install ballerina using platform installer
- uninstall it
- re-install

**Affected Versions:**
beta19

**OS, DB, other environment details and versions:**
Env:
ubuntu 15.10 | oracle jdk 1.8.0_161
"ballerina-platform-0.970.0-beta19" installer

**Comment by keizer619** [comment]
This is now fixed, hence closing the issue.

**Comment by kavithasub** [comment]
Verified the issue as fixed.
