### ISSUE TITLE
[Composer] Composer servers are starting in same port without throwing an error

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8182]
**Description:**
Composer servers are starting in same port without throwing an error

**Steps to reproduce:**
Start the Beta 17 pack composer
Start the Beta 19 pack composer (Both started the same time)
Both are started on 9091 port without throwing any address already in use error(Attached screenshots)

**Affected Versions:**
ballerina-platform-0.970.0-beta17-SNAPSHOT
ballerina-platform-0.970.0-beta19-SNAPSHOT

**OS, DB, other environment details and versions:**
macOS High Sierra
ballerina-platform-0.970.0-beta19-SNAPSHOT
JDK 1.8.0_152

**Suggested Labels (optional):**
Type/Bug
Severity/Critical
Priority/Normal
Affected/ballerina-platform-0.970.0-beta19

<img width="792" alt="screen shot 2018-04-26 at 7 25 27 pm" src="https://user-images.githubusercontent.com/14923354/39310558-4d79cbb6-4988-11e8-9672-24123ae54f21.png">

<img width="731" alt="screen shot 2018-04-26 at 7 27 22 pm" src="https://user-images.githubusercontent.com/14923354/39310565-55b5f02a-4988-11e8-9c51-6754171091b6.png">

**Comment by hevayo** [comment]
Fixed in master
