### ISSUE TITLE
GC limit exceeded when executing the jms producer with 40kb message

### ISSUE THREAD

**Issue by sashikamw** [ballerina-platform/ballerina-lang#8214]
**Description:**
jms producer ballerina service gets unresponsive due to GC overhead limit exceeded error when sending 40 kb message using 10 - 5 works with 1ms delay.

**Steps to reproduce:**
https://github.com/sashikamw/ballerina-stabilitytest/tree/master/ServiceScenarios/Scenario03_JMS/beta17/MultipleWorkers

**Affected Versions:**
ballerina-runtime-0.970.0-beta17

**OS, DB, other environment details and versions:**
Debian 9.3

**Observations**
```
caused by error, message: gC overhead limit exceeded
	at ballerina.jms:createTextMessage(<native>)

error, message: gC overhead limit exceeded
	at main(multi_queue_prodcer.bal:101)
error, message: gC overhead limit exceeded
	at main(multi_queue_prodcer.bal:38)
error, message: gC overhead limit exceeded
	at ballerina.jms:send(<native>)

```

```
error, message: gC overhead limit exceeded
	at ballerina.jms:send(<native>)
error, message: gC overhead limit exceeded
	at main(multi_queue_prodcer.bal:47)
error, message: gC overhead limit exceeded
	at main(multi_queue_prodcer.bal:29)
error, message: gC overhead limit exceeded
	at main(multi_queue_prodcer.bal:20)

```

Heap Dump - https://drive.google.com/file/d/1bBBkvnlgEIZaXz3M0CKQ9RUcZV6PmenX/view?usp=sharing

**Comment by aashikam** [comment]
We tried to reproduce this issue using the artifacts provided but couldn't. Please report if you face this issue again.
