### ISSUE TITLE
No tool-tips for some features in the menu

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8236]
**Description:**
No tooltips for some features in the menu
![32](https://user-images.githubusercontent.com/1845370/39347830-383270a2-4a12-11e8-95ef-b3b990c942ca.png)
![33](https://user-images.githubusercontent.com/1845370/39347833-3be275da-4a12-11e8-8faa-0d1d4e39c36c.png)

**Affected Versions:**
Version - Ballerina-0.970.0-rc1

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
I guess you are referring to menu icons. It is not mandatory to have an icon for the menu items we only put icons for general cases where the user has a knowledge of that icon.
