### ISSUE TITLE
Null temp values are shown when debugging

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8241]
**Steps to reproduce:**
1. Debug the hello world service sample

**Issue**
Please refer the screen shot. Those values will not be populated as well
![36](https://user-images.githubusercontent.com/1845370/39348484-f0bfda68-4a14-11e8-95bf-11afbcf8b052.png)

**Affected Versions:**
Version - Ballerina-0.970.0-rc1

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by pranavan15** [comment]
This issue has been resolved via PR: https://github.com/ballerina-platform/ballerina-lang/pull/10322. Hence, closing this issue.
