### ISSUE TITLE
[composer] Expanding console overlapping other windows in Edge browser

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8244]
**Description:**
As $subject see image1. But note that in firefox tested this and no such issue.

image1
![edge](https://user-images.githubusercontent.com/15671620/39349412-807a0b80-4a18-11e8-9c0e-6b6a86ec6263.jpeg)

image2
![firefox](https://user-images.githubusercontent.com/15671620/39349448-9d3391b0-4a18-11e8-87c4-953c22d09738.jpeg)

**Affected Versions:**
beta-rc1

**OS, DB, other environment details and versions:**
Windows 10 | Edge
resolution: 1920*1080

Ubuntu 15.10 | Firefox-59.0.2
resolution: 1920*1080

**Comment by kavithasub** [comment]
Related to
#8261

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
