### ISSUE TITLE
Wrong path shown in try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8245]
**Steps to reproduce:**
1. Run the header based routing sample and try-it

**Issue**
The path loaded in the try is wrong. It should be /hbr/route
![40](https://user-images.githubusercontent.com/1845370/39349470-b0b64d54-4a18-11e8-9af9-718fd6e1a52d.png)

**Affected Versions:**
Version - Ballerina-0.970.0-rc1

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by pahans** [comment]
fixed in 0.973.0
