### ISSUE TITLE
Path added is not visible in try-it

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8246]
**Description**
Path added is not visible in try-it 

**Steps to reproduce:**
1. Run a service and open the try-it
2. Change/add the path of the service method..

![41](https://user-images.githubusercontent.com/1845370/39349600-22f2ff70-4a19-11e8-9bcb-86627529cd5f.png)

**Issue**
Added path is not visible, but the request will be successful

**Affected Versions:**
Version - Ballerina-0.970.0-rc1

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by kavithasub** [comment]
Same observed in Windows 10 | Edge browser.

**Comment by hevayo** [comment]
Fixed in Master
