### ISSUE TITLE
The response is not received when debugging a service

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8251]
**Steps to reproduce:**
1. Debug the helloworld service sample
2. Invoke the service with try-it
3. Keep stepping over the lines

**Issue**
The response will not be received and the below error is observed on the console
![43](https://user-images.githubusercontent.com/1845370/39350215-18ed21de-4a1b-11e8-90ed-c6dc9e8ab617.png)

**Affected Versions:**
Version - Ballerina-0.970.0-rc1

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by DimalChandrasiri** [comment]
Cannot recreate issue.

**Comment by DimalChandrasiri** [comment]
This issue

**Comment by pranavan15** [comment]
Closing issue as this problem is not reproducible in the latest Ballerina versions. Reopen if you have any concerns.
