### ISSUE TITLE
[GA] [installer] rpm - package ballerina-platform-0.970.0.beta19-1.x86_64 (which is newer than ballerina-platform-0.970.0-1.x86_64) is already installed.

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8257]
**Description:**
- installer beta19 has already installed
- install ballerina as below => log prints

>[root@ballerinaonrethat3 ballerina]# rpm --install ballerina-platform-linux-installer-x64-0.970.0.rpm 
	package ballerina-platform-0.970.0.beta19-1.x86_64 (which is newer than ballerina-platform-0.970.0-1.x86_64) is already installed

Env:
rhel 7.3 | oracle jdk 1.8.0_161
ballerina-platform-linux-installer-x64-0.970.0.rpm

**Comment by hevayo** [comment]
Outdated hence closing
