### ISSUE TITLE
[Composer] Run function is not working 

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8260]
**Description:**
Run is not working in Chrome.

**Steps to reproduce:**
Open Hello service sample via BBE in the composer(Welcome page sample)
Run the bal file.
It's not showing any output. 
Debug mode also can see the same problem

 Same steps are working in  safari and Firefox

**Affected Versions:**
platform-macos-installer-x64-0.970.0

**OS, DB, other environment details and versions:**
macOS High Sierra
platform-macos-installer-x64-0.970.0
JDK 1.8.0_152
Chrome Version 66.0.3359.117

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/High
Affected/platform-macos-installer-x64-0.970.0

**Comment by chalitha87** [comment]
Observe the same behaviour in Debug mode also

**Comment by kavithasub** [comment]
Observed the same with windows edge too.
Windows 10 | Edge
ballerina-platform-windows-installer-x64-0.970.0

But note that open a bal file from local repo is supports Run/Debug  (in both menu/Debug)

**Comment by shavantha** [comment]
verified this issue
