### ISSUE TITLE
[composer] [GA] opens in edge browser with overlapping windows

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8261]
**Description:**
As $subject, see below

![composer1](https://user-images.githubusercontent.com/15671620/39355881-0f14b4ea-4a2c-11e8-99d4-64b0155fa957.jpeg)

![overlap](https://user-images.githubusercontent.com/15671620/39567185-b61c097e-4edb-11e8-93aa-ad9f0a328213.jpeg)

**Affected Versions:**
GA

**OS, DB, other environment details and versions:**
Windows 10 | Edge
ballerina-platform-windows-installer-x64-0.970.0

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
