### ISSUE TITLE
Endpoint metadata is not cleared properly when a service is stopped

### ISSUE THREAD

**Issue by yasassri** [ballerina-platform/ballerina-lang#8262]
**Description:**

In testerina we allow users to start/stop endpoints. If users try to start a service, stop the service and try to start the same service again following error is thrown. The reason for this is, the service registry is not being cleared. The network interface stops but the registry is not cleaned. 

```
Listening for transport dt_socket at address: 5005
Failed to execute the test function [testAirlineReservationService] of test suite package [airline_reservation]. Cause: error: error, message: error: error, message: service registration failed: two services have the same basePath : /airline
	at ballerina.http:register(<native>)

	at ballerina.test:startServices(<native>)
```

**Steps to reproduce:**

Execute a similar testerina program as below.

```ballerina
import ballerina/test;
import ballerina/http;

// Function to test Airline reservation service
@test:Config
function testAirlineReservationService() {
    _ = test:startServices("airline_reservation");
    test:stopServices("airline_reservation");
    _ = test:startServices("airline_reservation");
    test:stopServices("airline_reservation");
}
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
This issue cannot be reproduced in ballerina 0.975.1-SNAPSHOT, hence closing this issue.
