### ISSUE TITLE
"Ballerina API Reference" page in the Help menu is not redirecting to the proper page.

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8265]
**Description:**
"Ballerina API Reference" page in the Help menu is not redirecting to the proper page.

**Steps to reproduce:**
Start the composer
Go to the help Menu
Click on the "Ballerina API reference" page
It will load a page not found. (attached a screenshot)

**Affected Versions:**
platform-macos-installer-x64-0.970.0

**OS, DB, other environment details and versions:**
macOS High Sierra
platform-macos-installer-x64-0.970.0
JDK 1.8.0_152
Chrome Version 66.0.3359.117

**Suggested Labels (optional):**
Type/Bug
Severity/Major
Priority/High
Affected/platform-macos-installer-x64-0.970.0

<img width="1368" alt="screen shot 2018-04-27 at 3 20 52 pm" src="https://user-images.githubusercontent.com/14923354/39356810-a52eebb0-4a2e-11e8-8ee2-5dc2b3679ff3.png">

**Comment by hevayo** [comment]
Works in 0.975.0
