### ISSUE TITLE
[composer] [chrome] some texts are overlapping yet in design view

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8266]
**Description:**
Please see below as an example.

![textover](https://user-images.githubusercontent.com/15671620/39356898-d8fe8aae-4a2e-11e8-8a5d-410350431fba.jpeg)

**Affected Versions:**
GA

**OS, DB, other environment details and versions:**
Windows 10 | Chrome-66.0.3
ballerina-platform-windows-installer-x64-0.970.0

**Comment by hevayo** [comment]
Fixed in 0.975.0
