### ISSUE TITLE
[composer] edge - debugging shows "could not connect to debugger" after success debug

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8267]
**Description:**
Please see below,

![debug-wrong](https://user-images.githubusercontent.com/15671620/39357518-c201b360-4a30-11e8-915c-3f3b12ed46e8.jpeg)

**Affected Versions:**
GA

**OS, DB, other environment details and versions:**
Windows 10 | Edge
ballerina-platform-windows-installer-x64-0.970.0

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this.
