### ISSUE TITLE
[0.970.0-GA-pack2] Try-it is not working for any service

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8268]
**Description:**
Try-it is not working for services

**Steps to reproduce:**
1. Open the helloworld service sample ->Run
2. Invoke the service with try-it

**Issue**
![45](https://user-images.githubusercontent.com/1845370/39359729-cea9f17e-4a38-11e8-8232-0ba60cf916bf.png)

**Affected Versions:**
Version - Ballerina-0.970.0 - pack2

**OS, DB, other environment details and versions:**
Chromium Browser - Version 51.0.2704.79 Ubuntu 15.10 (64-bit)
OS - Linux

**Comment by shavantha** [comment]
verified the fix for this issue with 0.970.2
