### ISSUE TITLE
[0.970.0-GA-pack2] Design view is not loaded for Workers sample

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8270]
**Description:**
Design view is not loaded for Workers sample

![46](https://user-images.githubusercontent.com/1845370/39360207-fa8f5c5a-4a3a-11e8-9c66-1c3e4ff38e5c.png)

**Affected Versions:**
Version - Ballerina-0.970.0

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)
OS - Linux

**Comment by hevayo** [comment]
Fixed in 0.970.1

**Comment by shavantha** [comment]
verified the fix for this issue with 0.970.2
