### ISSUE TITLE
Cannot import a record

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8271]
**Description:**
Cannot import a record

**Steps to reproduce:**
1. Go to Tools -> import record and import a valid json

It does not import it

**Affected Versions:**
Version - Ballerina-0.970.0

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)
OS - Linux

**Comment by shavantha** [comment]
I tried with a large json payload as below and couldn't import the code. will reopen
```

{
	"id": "0001",
	"type": "donut",
	"name": "Cake",
	"ppu": 0.55,
	"batters":
		{
			"batter":
				[
					{ "id": "1001", "type": "Regular" },
					{ "id": "1002", "type": "Chocolate" },
					{ "id": "1003", "type": "Blueberry" },
					{ "id": "1004", "type": "Devil's Food" }
				]
		},
	"topping":
		[
			{ "id": "5001", "type": "None" },
			{ "id": "5002", "type": "Glazed" },
			{ "id": "5005", "type": "Sugar" },
			{ "id": "5007", "type": "Powdered Sugar" },
			{ "id": "5006", "type": "Chocolate with Sprinkles" },
			{ "id": "5003", "type": "Chocolate" },
			{ "id": "5004", "type": "Maple" }
		]
}
```


![nested_json](https://user-images.githubusercontent.com/6552100/40100566-fbe6d378-5901-11e8-8e53-0b400ff0ed71.png)
