### ISSUE TITLE
A WARN should be printed when running ballerina init is run on a top level of a project

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8272]
A WARN should be printed when running ballerina init is run on a top level of a project

if a ballerina project folder has already a `.ballerina` created and if we try to run the command` ballerina init `on a folder above the project folder then a WARN should be printed

```
|
|
---ballerina <== A warn if a user runs ballerina init hear
  |_ _ examples
       |_ _ hello-world << this level already has a .balleria file
```

**Comment by shavantha** [comment]
This is to prevent https://github.com/ballerina-platform/ballerina-lang/issues/8264

**Comment by NatashaWso2** [comment]
This issue is already tracked with https://github.com/ballerina-platform/ballerina-lang/issues/11239, hence closing this.
