### ISSUE TITLE
Need to reject variable names that are the same as package prefix

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#8284]
**Description:**
At the moment Ballerina allows creating variable names that are the same as package prefixes and this causes code completion failures and confusing code. I suggest prohibiting such variable names.

**Steps to reproduce:**
import wso2/twitter;

endpoint twitter:Client twitter {
};

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Spec allows this. 

> A module-prefix declared by an import-decl is in the same symbol space as a xmlns-namespace-prefix declared by an xmlns-decl-stmt. This symbol space is distinct from a module's main symbol space used by other declarations.

Once of design decision for this was, when we refer a module-prefix we always use `:` after that. This is not applicable to other declarations.  Hence there is no confusion. 

I tested with latest VSCode plugin, seems like mention issue is already fixed. Hence closing this issue.
