### ISSUE TITLE
Showing 1.java in MacOS terminal title when Hello World executed

### ISSUE THREAD

**Issue by chamarat-wso2** [ballerina-platform/ballerina-lang#8285]
**Description:**
  

Followed https://ballerina.io/learn/quick-tour/ to run HelloWorld and in the Terminal Title showing as 1.java

Lang-> Ballerina 0.970.0
OS -> MacOS 10.13.2 (17C88)

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.1 so closing this issue.
