### ISSUE TITLE
Improve Internal Error Message

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#8286]
The part, "We thank you for helping make us better dancers." seems to have a grammar issue. Maybe we can change it a bit to become like "We thank you for helping us become better dancers".

**Comment by sanjiva** [comment]
+1 but I *think* its ok .. lets ask Jackie ;-).

**Comment by lafernando** [comment]
Okay :) @appellj

**Comment by appellj** [comment]
I'd go with "We thank you for helping us to become better dancers" (insert "to) or, if you want to use even more word play, "We thank you for helping us to improve our dance steps."

**Comment by pubudu91** [comment]
Doesn't that last part about becoming better dancers sound odd? I like the second one @appellj suggested more: "We thank you for helping us to improve our dance steps.". But dance steps still feel a bit too literal. How about something like "We thank you for helping us to improve our craft." or some other word which wouldn't stretch the ballerina narrative too far?

**Comment by appellj** [comment]
Maybe we should go with: "Thank you for helping us to improve our performance." That's a much more subtle play on words.

**Comment by praneesha** [comment]
Let's reword the message as follows:

> Oh no, something went wrong.
> 
> The "ballerina-internal.log" file located in the current directory will indicate what the problem is.
> We REALLY appreciate it if you can share the code that broke Ballerina with us together with this log file by creating a bug report on https://github.com/ballerina-platform/ballerina-lang/issues.
> 
> Thank you for helping us to improve Ballerina.
>

**Comment by praneesha** [comment]
This is fixed via [1].

[1] https://github.com/ballerina-platform/ballerina-lang/pull/19274
