### ISSUE TITLE
VSCode plugin show error when invoking twitter -> tweet

### ISSUE THREAD

**Issue by chintana** [ballerina-platform/ballerina-lang#8288]
**Description:**
I'm following https://ballerina.io/learn/quick-tour and VSCode plugin show following error for twitter -> tweet. The program complies and run without any issues though.

<img width="864" alt="screen shot 2018-04-30 at 2 32 05 pm" src="https://user-images.githubusercontent.com/27903/39451539-cf160c40-4c83-11e8-89ce-06362c2c7072.png">

**Affected Versions:**

VSCode - 1.22.2
VSCode Plugin - 0.970.0 release

**OS, DB, other environment details and versions:**

macOS 10.13.4

**Comment by nadeeshaan** [comment]
Has been fixed in latest Language Server plugin. Hence Closing the issue. Please reopen if the issue still can be observed
