### ISSUE TITLE
[Improvement][UI] The scrollbar of the composer is not clearly visible 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8300]
**Description:**
The scrollbar of the composer is not clearly visible. Could we use a white color for that. will help those having issues in 
![screenshot](https://user-images.githubusercontent.com/6552100/39464130-4fe0e9ac-4d39-11e8-9ab4-559fc4c11c33.png)

**Steps to reproduce:**
1.check any file browser window

**Affected Versions:**
1.Release version:ballerina-tools-0.970.1-SNAPSHOT.zip

**OS, DB, other environment details and versions:**
Firefox 59.02
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by srsharon** [comment]
This issue can not be reproduced in the new released pack Release version:ballerina-tools-0.970.3-SNAPSHOT.zip

Hence please close this issue @hevayo
