### ISSUE TITLE
Export diagram fails on firefox on windows 7

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8310]
**Description:**
Export diagram fails on firefox on windows 7

**Steps to reproduce:**
1.open a sample ex:hello-world.bal
2.click on export diagram
3.enter the path
4.enter the file name

**Affected Versions:**
ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Firefox-59.0.2
Windows 7

Note: the given error message is also invalid and not clear 

![export_diagram](https://user-images.githubusercontent.com/6552100/39469334-4d377254-4d55-11e8-8e14-de36e9a15ceb.png)

**Comment by pahans** [comment]
related to https://github.com/ballerina-platform/ballerina-lang/issues/6256

**Comment by pmhofman** [comment]
Same here, in Chrome (on Windows 10 Education), but with message: 
`Cannot read property 'currentStyle' of undefined`

**Comment by DimalChandrasiri** [comment]
Fixed with PR #9729
