### ISSUE TITLE
Auto-completion suggestions did not work on composer on windows 7 firefox browser

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8311]
**Description:**
Auto-completion suggestions did not work on composer on windows 7 firefox browser

**Steps to reproduce:**
1.create a type
2.inside the main function type a part of the type name

Note: on ubuntu this works as given on the screen shot

**Affected Versions:**
```
ballerina-tools-0.970.1-SNAPSHOT

```
**OS, DB, other environment details and versions:**
Windows 7
Firefox 59.0.2
![ubuntu](https://user-images.githubusercontent.com/6552100/39469755-731ef896-4d57-11e8-907e-cdc6259855ce.png)

**Comment by hevayo** [comment]
Fixed in 0.973.0
