### ISSUE TITLE
Getting an error log when running a bal file which imports a package using ballerina native interface (non builtin)

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#8314]
**Description:**
$subject.
The error message is `error occurred when pulling the package`
This seems to be because, when the org is not ballerina, before checking whether the package is in BALLERINA_HOME/bre/lib, it is directly checked in local .ballerina or ballerina central causing the aforementioned error message. However, the bal file runs fine.

**Steps to reproduce:**
1. Copy paste the relevant native package jars in to BALLERINA_HOME/bre/lib
2. Import that native package in a bal file.
3. Run the bal file

**Affected Versions:**
0.970.0

**Comment by Manuri** [comment]
For the 0.970.1 version the error log is,

```bash
could not find package wso2/mongodb:*
```

**Comment by shobhitJava** [comment]
same issue. Is there any fix yet on this?

**Comment by Manuri** [comment]
@shobhitJava This is not fixed yet. Expected to be fixed in an up coming release. 
Please note that this is a harmless error message which is misleading. **Even though you get this error, code written using the package should work.**

**Comment by shobhitJava** [comment]
I read this comment on a post so tried it but I am not able to run the code. It is giving me the error "  could not find package wso2/mongodb:*"

**Comment by Manuri** [comment]
@shobhitJava Are you getting any errors other than "could not find package wso2/mongodb:*" ? Can you post a sample code you are trying to run?

**Comment by shobhitJava** [comment]
no I am not getting any error other then this , but my services are not getting started as execution is getting stopped after getting this error.
Attaching source code
Changing the extension due to file type
[test.bal.txt](https://github.com/ballerina-platform/ballerina-lang/files/2192374/test.bal.txt)
[hello_service.bal.txt](https://github.com/ballerina-platform/ballerina-lang/files/2192375/hello_service.bal.txt)

**Comment by Manuri** [comment]
Could you please let us know the ballerina version and the mongodb package version you are using?

**Comment by shobhitJava** [comment]
Please find the version below

[root@blockchain-1 ~]# mongod --version
db version v4.0.0
git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64
========================


[root@docker-repo ballerina-platform-0.976.1-SNAPSHOT]# ballerina -v
Ballerina 0.976.1-SNAPSHOT


Mongo db is running on different server. I have given you locahost file, in my version I have replaced the IP of server. Also with JAVA code it is getting connected. So connectivity issue is not there.

**Comment by Manuri** [comment]
@shobhitJava Kindly note that I was asking the mongodb package version you have installed in ballerina, not the mongo database server version. 

At the moment WSO2 MongoDB package is not released to Ballerina central therefore you have to download it from [2] and install according to the provided instructions. Also, the latest release of the WSO2 MongoDB package(0.5.7) supports Ballerina 0.975.0 only. Therefore you won't be able to use the MongoDB package with the latest Ballerina 0.976.1-SNAPSHOT. Once the next Ballerina version is released, compatible MongoDB package also will be released. For now you can try MongoDB 0.5.7 with Ballerina 0.975.0. 

[1] https://github.com/wso2-ballerina/package-mongodb
[2] https://github.com/wso2-ballerina/package-mongodb/releases

**Comment by shobhitJava** [comment]
Okay, welll I have followed the instruction given in (2).  For the version related to ballerina, I will wait for newer version.
Thanks for your feedback.
