### ISSUE TITLE
[composer] Command-Palette-> Fold levels are functioning the same way like folding line by line

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8315]
**Description:**
Issue

* Right click on source-> Command-Palette-> Fold levels (fold level1 to fold level 9) seems folding line by line only (functioning like same way). 
* Sort keys given is not working. I could use Ctrl+Shift +n +K (n => 1-9)

Observed
command-palette-> Fold : folding entire code from where the cursor
command-palette-> Fold All :  folding entire code from where the cursor

![fold1](https://user-images.githubusercontent.com/15671620/39471247-d5e8b1d0-4d5f-11e8-99e9-9e4e22ae994b.jpeg)

**Affected Versions:**
ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox 59.0.2

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
