### ISSUE TITLE
Best to remove the --publicPath parameter when we use the --help for composer

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8316]
**Description:**
Best to remove the --publicPath parameter when we use the --help for composer. Currently when we use the --help we see a parameter called --publicPath but if its not needed for users this parameter should be remved

**Steps to reproduce:**
1.type ./ballerina --help
2.type ./ballerina --publicPath and check to give some path

**Affected Versions:**
ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu/Windows

**Comment by hevayo** [comment]
Fixed in 0.970.1
