### ISSUE TITLE
[composer] Command-Palette-> Format Document seems not working

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8318]
**Description:**
Issue
* Right click on source-> Command-Palette-> Format Document : seems it doesn't do any function. 
I assumed it is similar to refactor source code, is it?

![format](https://user-images.githubusercontent.com/15671620/39471797-caccc784-4d62-11e8-874d-c5e13aad730f.jpeg)

**Affected Versions:**
ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox 59.0.2

**Comment by NipunaMarcus** [comment]
We are in the process of implementing this feature .... there is a open task for this hence closing this issue and linking this to the task.
