### ISSUE TITLE
[composer] Command-Palette-> Rename Symbol seems not working

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8321]
**Description:**
Issue
*Right click on source-> Command-Palette-> Rename Symbol : It was not rename the variable as I tried below
- selected a variable
- rename it 
- enter 

![rename](https://user-images.githubusercontent.com/15671620/39471948-ab91d818-4d63-11e8-8757-12808c874c8a.jpeg)

**Affected Versions:**
ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox 59.0.2

**Comment by hevayo** [comment]
Rename works for some scenarios in composer so this is a language server issue for the given case.
