### ISSUE TITLE
Incompatible browsers  need to show a message to the user

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8322]
**Description:**
For incompatible browsers we need to show a message to the user. Currently an animated circular icon keeps moving below the ballerina logo which gives an indication that the application is still loading. If we can show a message similar to "not compatible with this browser" will be useful for the user

**Steps to reproduce:**
1.Open the ballerina composer on IE11

**Affected Versions:**
ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
1.Windows 7
2.IE11

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
