### ISSUE TITLE
[Quick Start Guide] The order of the guide needs to be changed

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8324]
**Description:**
As per the guide[1] we are expecting to run a hello-service.bal but the document first shows the run command and then only shows the sample hello-service.bal. Ideally, the code example should come on top followed by the ballerina init and ballerina run hello_service.bal commands 

Based on the current order it is confusing to the user as there is no hello-service.bal to run as given on the top of the document

[1]https://ballerina.io/learn/quick-tour/

**Comment by shavantha** [comment]
cant we move the step ballerina run hello_service.bal  after showing the code yesterday I was initially thinking that hello-world-service.bal in examples were to be used instead of hello-service.bal becuase i was not able to locate the code to run, 

currently the user has to scroll down to locate the code and then come backup to read the remaining steps :)

**Comment by samgnaniah** [comment]
Yes, that might work. Will have a look and see if it makes sense.

**Comment by samgnaniah** [comment]
I'd like more opinions before we implement to be honest. I feel it's nice to see something working within the first few clicks itself. Gives a good impression. Shall we start a thread and discuss?

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-www/issues/878 to track this. Hence closing this issue.
