### ISSUE TITLE
[Quick Start Guide] The doc link to https://apps.twitter.com/  is not correct

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8325]
**Description:**
The doc link to `https://apps.twitter.com/`  is not correct. Since the url is shown as a link users should be pointed to `https://apps.twitter.com/`  and not to `https://ballerina.io/`

**Steps to reproduce:**
1.check the link for https://apps.twitter.com/

**Comment by jeradrutnam** [comment]
This is fixed with the PR #771

**Comment by pubudu91** [comment]
Closing this as per above comment.
