### ISSUE TITLE
[Quick Start] There is no instruction given to follow up after downloading

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8326]
**Description:**
There is no instruction given to follow up after downloading.
- Since the downloads are installers, user will be able to run the installers simply.
- Suggestion : We should mention something like "Run the installers , navigate to prefer folder ..."

![instruction](https://user-images.githubusercontent.com/15671620/39482729-c644b958-4d8d-11e8-8e03-e4551454a2da.jpeg)

**Comment by samgnaniah** [comment]
Seems redundant to me. I think those things will be obvious to a user right?

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-www/issues/879 to track this. Hence closing.
