### ISSUE TITLE
[Quick Start] Mention the per-requisit as to be installed vscode

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8327]
**Description:**
Suggestion : We should mention here to the user to be installed VScode as per-requisite 

![vscode](https://user-images.githubusercontent.com/15671620/39482847-2ec12f20-4d8e-11e8-9253-5e1ceb0eb5c5.jpeg)

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-www/issues/880 to track this. Hence closing.
