### ISSUE TITLE
[Quick Start]  Setting up ballerina.home should be mentioned in the doc

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8328]
**Description:**
Setting up ballerina.home should be mentioned in the doc

- After the step in below image, it should be appended. Note that after the user navigates to VScode, it will anyway notify the user configure ballerina.home. Better include in doc too.

![vscode2](https://user-images.githubusercontent.com/15671620/39482944-7c0994b6-4d8e-11e8-9b63-cec6dc454fed.jpeg)

**Comment by samgnaniah** [comment]
Tried this out and it worked for me without setting up ballerina.home. Did you restart VS Code?

**Comment by kavithasub** [comment]
@samgnaniah , it was a warning notification for me to set ballerina home config when I open project folder as below.
If this is working fine without set ballerina.home manually, we can resolve this issue.
![config2](https://user-images.githubusercontent.com/15671620/39506768-3fea22ce-4df8-11e8-833a-e7ef5477dd40.jpeg)

(Windows 10 )

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-www/issues/881 to track this. Hence closing.

**Comment by ShanikaEdiriweera** [comment]
@samgnaniah Did not work out for me even after restarting VS Code. How to set ballerina.home ?

**Comment by dasunpubudumal** [comment]
Ran into the same problem and I troubleshooted it like this.

`ballerina` bash command lies in `/usr/bin/ballerina`. However, it is linked to `/usr/lib/ballerina/ballerina-0.981.0/bin/ballerina` bash script. Thus, the original script which runs is the latter.

Open that script and see this particular line: 

```bash
# set BALLERINA_HOME
BALLERINA_HOME=`cd "$PRGDIR/.." ; pwd`
`
There you have it! Just put up a `echo $BALLERINA_HOME` in that script (After the `set BALLERINA_HOME` command), and run `ballerina` in your terminal - you'll get the location of `ballerina.home` (In my case, it is `/usr/lib/ballerina/ballerina-0.981.0`). Just copy it and paste it in VSCode settings, and restart VSCode.

**Comment by frntn** [comment]
Thanks @dasunpubudumal 
I had that message : `The configured "ballerina.home" seems incorrect.`

I can confirm the `$BALLERINA_HOME` is the parent folder of the dereferenced symlink 
And it fixes the error

---

Going further, 
For future releases the installer should abstract away the version number with some kind of `latest` symlink (or similar) 
So we won't need to update our vscode settings along with ballerina upgrade...

I tried this pattern manually : 
```bash
$ ls -la /usr/lib/ballerina/
total 12
drwxr-xr-x   3 root root 4096 Sep 11 23:16 .
drwxr-xr-x 161 root root 4096 Sep 11 22:57 ..
drwxr-xr-x   7 root root 4096 Sep 11 22:57 ballerina-0.981.1
lrwxrwxrwx   1 root root   36 Sep 11 23:16 latest -> /usr/lib/ballerina/ballerina-0.981.1
```
And updated my settings accordingly :
```javascript
{
    "ballerina.home": "/usr/lib/ballerina/latest"
}
```

But then got the following error :
`Version of ballerina found inside the configured "ballerina.home" does not match with this plugin's version. Some features may not work properly.`

The extension should then be updated not to retrieve the ballerina version from its path...

**Comment by xgenvn** [comment]
On MacOS, for homebrew-based installation, the path is `/opt/homebrew/Cellar/ballerina/2201.5.0`.
