### ISSUE TITLE
[Quick Start Guide] Lets ask user to open project folder into editor

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8331]
**Description:**
As given below, it will open bal file only into "Open Editors". 
But if we want to continue the guide with creating new bal files, we should mention to open initial project folder into editor.
`code /<folder path>`

![editor1](https://user-images.githubusercontent.com/15671620/39503992-7d3da6ee-4de6-11e8-944f-a8214111b238.jpeg)

![editor2](https://user-images.githubusercontent.com/15671620/39504000-843242a2-4de6-11e8-9475-2bfbee891325.jpeg)

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
Windows 10 
VScode plugin

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-www/issues/882 to track this. Hence closing this issue.
