### ISSUE TITLE
[Quick Start Guide] Curl command given for tryit needs to be corrected

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8332]
**Description:**
Curl should be corrected to access resource at root level
`curl http://localhost:9090 -X POST`

- Do the changes in to hello_service.bal as per guide

![config](https://user-images.githubusercontent.com/15671620/39504410-1497c89c-4de9-11e8-8ea5-24ac71a83bbb.jpeg)

- Try with given Curl

![curl](https://user-images.githubusercontent.com/15671620/39504413-17c77e7c-4de9-11e8-9472-5ad7d6e47698.jpeg)
- Resource not found.

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
Windows 10 
VScode plugin

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerina-platform/ballerina-www/issues/883 to track this. Hence closing this issue.
