### ISSUE TITLE
[Query] [ballerina search] some endpoints for ballerina central listing as private repo?

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8333]
**Description:**
As $subject seems we have listed private repo endpoints as in below image. 
I tried as in guide by searching google endpoints and ballerina search listed as below. 
But I'm not sure is this correct?

![search](https://user-images.githubusercontent.com/15671620/39505528-8b24f4e2-4df0-11e8-9acf-4ec33cca9523.jpeg)

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
Windows 10

**Comment by NatashaWso2** [comment]
You can push packages with any org-name to central. When we search for a package we do a text search on the metadata of the package and show the results. Closing this issue since the behavior is correct.
