### ISSUE TITLE
[Query] When un-installing ballerina some system created log files were not removed

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8335]
**Description:**
When un-installing ballerina in Ubuntu using `sudo dpkg -r ballerina-0.970.0` command, some system created log files were not removed.

eg: ballerina-internal.log in side opt/ballerina/ballerina-0.970.0/docs/examples/hello-world-service

Since this is not a user created file, don't we have to removed them when un-installing ballerina?

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10

**Comment by hevayo** [comment]
Outdated
