### ISSUE TITLE
Can we rearrange the sample list on the welcome page to reduce scrolling down the page?

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8336]
**Description:**
If we can re-organize the samples, so that the bottom of the sample list is in the same level, we can reduce the amount of scrolling down the page
![50](https://user-images.githubusercontent.com/1845370/39508138-f0ebea84-4dfe-11e8-9bf8-bf0a5eb7c047.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10

**Comment by hevayo** [comment]
We use the same ordering as in ballerina.io so to preserve consistency will keep it as it is.
