### ISSUE TITLE
[composer] Reformat Code undo the changes done

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8337]
**Description:**
Edit-> Reformat Code - is it something similar to refactor?
- See below image1, I had remove some code block and current part of code as below. Saved it
![reform](https://user-images.githubusercontent.com/15671620/39513647-a7e753be-4e12-11e8-98b6-24c16bf80834.jpeg)

- Select Reformat Code, will Undo the changes. See image2
![reform2](https://user-images.githubusercontent.com/15671620/39513681-becc67c2-4e12-11e8-9b59-0c3109c509ad.jpeg)

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
Windows 10

**Comment by hevayo** [comment]
This issue is fixed in master and will be available with 0.980.0.
