### ISSUE TITLE
"Create recode" UI displays an syntax error even for valid json array.

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8338]
**Description:**
Create recode UI displays an syntax error even for valid json array. 

**Steps to reproduce:**
Go to the Create recode option in Tools menu
Enter a recode name
Enter a **valid** Json Array content.
Click on the save button.
Error is saying "Please make sure JSON attribute names are align with ballerina variable naming conventions" (Screenshot attached)

**Affected Versions:**
ballerina-platform-macos-installer-x64-0.970.0.pkg

**OS, DB, other environment details and versions:**
macOS High Sierra
platform-macos-installer-x64-0.970.0
JDK 1.8.0_152
Chrome Version 66.0.3359.117

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/High
Affected/platform-macos-installer-x64-0.970.0

<img width="599" alt="screen shot 2018-05-02 at 2 02 38 pm" src="https://user-images.githubusercontent.com/14923354/39513932-714bf048-4e13-11e8-8f23-d88e9a97e930.png">

**Comment by pahans** [comment]
json should be entered as  
```javascript
{
  fname: "John",
  lname: "Stallone"
}
```

not json p = {json...}
