### ISSUE TITLE
Need to hover over the visible scroll bar to see the area

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8339]
**Description:**
When you scroll down the code, the visible scroll bar on the right does not show the area unless you hover over the scroll bar when scrolling down

![53](https://user-images.githubusercontent.com/1845370/39514252-52edbc34-4e14-11e8-956b-77491d0a0c0d.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
This feature is part of Monaco editor hence we are unable to fix it. BTW this behavior is in line with VSCode as well.
