### ISSUE TITLE
Issues in the syntax description pop up

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8340]
**Description:**
Issues in the syntax description pop ups
1. Keywords are highlighted (in blue) which is not required
2. Some words are not completed properly (part of the word is in the next line)

![55](https://user-images.githubusercontent.com/1845370/39514972-52306bbe-4e16-11e8-9922-601ad0c6b349.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this issue.

![clientpopup](https://user-images.githubusercontent.com/13446645/45402698-93fb9480-b674-11e8-8416-721da0226427.png)
