### ISSUE TITLE
[composer] Newly added if/while in design view are cannot be deleted from design

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8343]
**Description:**
As $subject, 
- Open a bal file  if_else.bal or while.bal
- Go to edit mode and add one more if statement from graphical view => added 
- Save and goto edit mode and try to delete

![delete](https://user-images.githubusercontent.com/15671620/39515861-f01f55cc-4e18-11e8-94ee-e9ca28cd1fb4.jpeg)

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
Windows 10 
Chrome 66.0.3

**Comment by pahans** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9299
