### ISSUE TITLE
[composer] foreach doesn't have graphical suggetion to add from design view

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8344]
**Description:**
As $subject see below image.
Issues:
- Open foreach.bal => design view not loading
- Add new bal file and try to add foreach from design => couldn't find any suggestion
- Add new bal file, and add below source => now I can see foreach 
`
function main(string... args ) {
     string[] fruits = ["apple", "banana", "cherry"];
      foreach v in fruits {
        io:println("fruit: " + v);
    }
}`

![foreach](https://user-images.githubusercontent.com/15671620/39516996-32bac076-4e1c-11e8-871a-6471a1d05b80.jpeg)

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
Windows 10 
Chrome 66.0.3

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9447
