### ISSUE TITLE
Composer does not add the relevant import on code when we add an object via sequence diagram

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8348]
**Description:**
Composer does not add the relevant import on code when we add an object via diagram.

**Steps to reproduce:**
1.Click on the plus sign of a sequence diagram
2.Add an item such as an http endpoint or a websub
3.The composer adds a code such as ex:    endpoint http:APIListener ep1 {};
However, the relevant import the user has to add manually to the code. As in the screenshot attached, for websub endpoint a red line is shown to indicate that the import is missing. If we are generating code then we should also generate the relevant import statement on code

![sequence_diagram](https://user-images.githubusercontent.com/6552100/39521464-39878bd6-4e2c-11e8-9be5-6559d57670c4.png)

**Affected Versions:**
Ballerina 0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 16.04
Firefox 59.0.2

**Comment by hevayo** [comment]
Fixed in 0.975.0
