### ISSUE TITLE
The behaviour of Ballerina command line arguments option is not clear 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8351]
The Ballerina command line arguments UI does not validate the inputs we enter. Also it is not clear what happens when a value is entered to this field

steps
1.enter any garbage value to Ballerina command line arguments

![commandline_arguments](https://user-images.githubusercontent.com/6552100/39523776-658989ac-4e34-11e8-9362-0c03af4bf2a1.png)

Note: can we show an example as we have given in remote debug UI

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
