### ISSUE TITLE
When adding an endpoint from the design view the package should be imported automatically

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8353]
**Description:**
When adding an endpoint from the design view, the package (ballerina/http) should be imported automatically. Otherwise, it is giving an error to the user and the user needs to manually add it which hinders the usability aspect of the composer.

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
duplicate #8348
