### ISSUE TITLE
Add an endpoint to add the http:Client endpoint by default from the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8354]
**Description:**
Add an endpoint to add the http:Client endpoint by default from the design view. Currently, it only has the below endpoints.
![57](https://user-images.githubusercontent.com/1845370/39526643-0a519580-4e3d-11e8-97de-5b7bf6597de2.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Fixed with 0.975.0
