### ISSUE TITLE
No tooltips for the UI elements in the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8355]
**Description:**
No tooltips for the UI elements in the design view
![59](https://user-images.githubusercontent.com/1845370/39527156-693d7fc2-4e3e-11e8-9964-f16995a897ad.png)
![60](https://user-images.githubusercontent.com/1845370/39527169-6e49c0a2-4e3e-11e8-87cf-77bfa96f5973.png)
![62](https://user-images.githubusercontent.com/1845370/39527226-8afb5de6-4e3e-11e8-8bd5-f140890d43c5.png)

**Comment by hevayo** [comment]
Fixed in master will be available in 0.976.0
