### ISSUE TITLE
Swagger view and some other features are not prominent in the design view

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8356]
**Description:**
1. The icon of the swagger view is too small and it is not prominent for the user
2. The other icons such as the zoom in/out button, delete buttons are too small for the user to click.
3. The cursor is shown when you hover over the delete button

![60](https://user-images.githubusercontent.com/1845370/39527304-b8bec1be-4e3e-11e8-9f92-09491c7c7b89.png)

![62](https://user-images.githubusercontent.com/1845370/39527939-61df9998-4e40-11e8-83a0-999ec86e82e8.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
