### ISSUE TITLE
Expectation of the zoom in/out button is not clear

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8357]
**Description:**
I expected the design view will zoom in when I clicked on the zoom in button. But, it only expanded the collapsed areas in the design. IMO, the icon should be changed

![61](https://user-images.githubusercontent.com/1845370/39527612-787a59be-4e3f-11e8-83f1-d33fb1932bf3.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by nadeeshaan** [comment]
Zoom in is expected to zoom the hidden fields and provide an in-depth view. hence closing the issue
