### ISSUE TITLE
Swagger view button is only visible when we edit the design

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8359]
**Description:**
Swagger view button is only visible when we go to the edit mode of the design. Better if it is visible all the time

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
