### ISSUE TITLE
Errors in the swagger definition

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8361]
**Description:**
1. Open query param matrix param sample -> go to the swagger view

**Issue**
Swagger definition is not loaded and an error is shown to the user
![66](https://user-images.githubusercontent.com/1845370/39528873-ee2bb3da-4e42-11e8-93ad-5bdfac66465f.png)

**Affected Versions:**
ballerina-0.970.0

**OS, DB, other environment details and versions:**
Ubuntu 15.10
Firefox - 59.0.2 (64-bit)

**Comment by shavantha** [comment]
I also got the same error
