### ISSUE TITLE
Some tabs are not shown completely when many tabs are open

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8363]
**Description:**
Some tabs are not shown completely when many tabs are open. No horizontal scroll bar for the entire page as well

![69](https://user-images.githubusercontent.com/1845370/39529336-0a5fda9e-4e44-11e8-9291-ede885a7ef1d.png)

**Comment by shavantha** [comment]
verified the fix for this issue with 0.970.2
