### ISSUE TITLE
Windows - Cannot find file 

### ISSUE THREAD

**Issue by fjoalland** [ballerina-platform/ballerina-lang#8364]
Hello,

I downloaded ballerina from the official source. I tried different examples and I have the same issues:
![image](https://user-images.githubusercontent.com/6407511/39533478-74c14018-4e2f-11e8-8e5a-de7e1dbb985b.png)
In the directory ballerina, when I run the command "**ballerina run hello-world.bat**" I move from the directory D:\Ballerina to C:\Windows\System32 and the answer is "cannot find file 'hello-world.bal'".

**Comment by samisawso2** [comment]
You need to have the ballerina source file, that is `hello-world.bal` in the current directory. 

Have you copied a sample `hello-world.bal` into your current directory form somewhere or created a `hello-world.bal` yourself?

You can find a hello world sample in D:\Ballerina\ballerina-0.970.0\docs\examples\hello-world\hello_world.bal

Copy that file to current directory and then you can run 

`ballerina run hello-world.bal`

**Comment by fjoalland** [comment]
Sorry perhaps I caused you confusion but I created my hello-word by myself in a new directory in my disk D.

I tried to run an example here C:\Ballerina\ballerina-0.970.0\docs\examples\hello-world\hello_world.bal and it worked!

But it has no sense, why can't I run another file on the other disk.

**Comment by TylerJewell** [comment]
@fjoalland - I am not quite following the issue. Are you saying that the file is in both locations, one on a C:\ drive and another on D:\ drive, and in one case the build worked and another case it fails?  Can you show us a `tree` command for the D:\ drive?

**Comment by kavithasub** [comment]
There is a similar issue which has reported in[1].
[1] https://github.com/ballerina-platform/ballerina-examples/issues/248

**Comment by samisawso2** [comment]
This is probably due to an issue in how paths are being handled in bat file and seem like a bug. Need to test on a windows machine. But my initial feeling is that `BALLERINA_HOME` variable usage in the execution line from within the bat file has some issue across drives.

**Comment by pumudu88** [comment]
I came across a similar issue with different ballerina command "init".
Issue seems to be in bat script, where it sets current drive to 'ballerina home drive' instead of actual current drive.

**Cause :**  
https://github.com/ballerina-platform/ballerina-lang/blob/master/distribution/zip/ballerina/bin/ballerina.bat#L50

**Fix :** 
`if not "%curDrive%" == "%ballerinaDrive%" %curDrive%:`

It seems this if condition is also redundant because current drive shouldn't change based on ballerina home.

Hope this helps.

**Comment by Kishanthan** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/51
