### ISSUE TITLE
The Objects and Endpoint count only gets incremented for endpoints/objects added via definision feature which is confusing

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8365]
**Description:**
The Objects and Endpoint count only gets incremented for endpoints/objects added via definition feature. If we add an endpoint by clicking on the + icon of the sequence diagram the count is not incremented.

**Steps to reproduce:**
1.Click edit button for the sequence diagram
2.Add multiple endpoints from the option as shown in the first screen shot
3.Check the count on the composer as shown in the second screen shot 

Next,Click on definition as shown on the third screen shot and add the endpoint the count gets incremented
**Affected Versions:**

**OS, DB, other environment details and versions:**
1.Ubuntu 16.04
2.Firefox 59.0.2
![endpoint_sequence](https://user-images.githubusercontent.com/6552100/39567791-b206e604-4edd-11e8-9179-0001e568e337.png)

![count](https://user-images.githubusercontent.com/6552100/39561892-3cabeae2-4ec6-11e8-8493-d1205f88a2a9.png)

![definision](https://user-images.githubusercontent.com/6552100/39567798-bbd664de-4edd-11e8-9f45-538286839a99.png)

**Comment by nadeeshaan** [comment]
We are currently showing the count for global endpoints and global objects. It would be meaningful to mention that clearly in the label. Because showing the endpoint count of all the available endpoints even within the resources/ services/ function will not make sense

**Comment by NatashaWso2** [comment]
Composer no longer shows the endpoint or object count in the design view, hence closing this issue.
