### ISSUE TITLE
composer does not display the sequence diagram for pb.bal files in grpc samples

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8366]
**Description:**
composer does not display the sequence diagram for pb.bal files in grpc samples

**Steps to reproduce:**
1.check the grpc samples on composer and open the bp.bal files ex:grpc_secured_unary_pb.bal
**Affected Versions:**

**OS, DB, other environment details and versions:**
Ubuntu16.04
FIrefox 59.0.2

**Comment by keizer619** [comment]
As this sample contains objects it would not render a diagram. It will only list down created objects in the drop down menu. Hence closing this issue.
