### ISSUE TITLE
[Improvement] Better to provide a feature to move bal files within folders 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8369]
**Description:**
 Better to provide a feature to move bal files within folders 

**Steps to reproduce:**
1.try to move a bal file within folders after opening the folder structure on the composer 

**Affected Versions:**
Ballerina 0.970.0

**OS, DB, other environment details and versions:**

1. Ubuntu 16.04
2. Firefox 59.0.2

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
