### ISSUE TITLE
[Chaos] Composer started with --host[IP]  becomes unresponsive after opening multiple balfiles 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8370]
**Description:**
After starting the composer with the --host flag and passing the IP address, The composer became unresponsive after opening more than 8 bal files. For each bal file a new tab is opened-up and afterworlds it does not load the composer

**Steps to reproduce:**
1.Start the composer as `./composer --host <your-ip-address>`
2.from the welcome page try to open more than 8 samples

**Affected Versions:**
Ballerina 0.970.0

**OS, DB, other environment details and versions:**
1.Ubuntu 16.04
2.Firefox 59.0.2
![open_multiple](https://user-images.githubusercontent.com/6552100/39615692-36076250-4f95-11e8-8b0d-a980e1276a29.png)

After opening the 8 bal files I move to open the welcome page and below is the output

![unresponsive](https://user-images.githubusercontent.com/6552100/39615695-3a8de646-4f95-11e8-9f17-df93aea9536c.png)

Each time I restart the composer since the tabs are kept in memory I get the same error

**Comment by shavantha** [comment]
![htop](https://user-images.githubusercontent.com/6552100/39616163-b7cf728a-4f97-11e8-9692-c1a880430842.png)

**Comment by shavantha** [comment]
**Below are multiple outputs from the process using the glance tool**

![glance_output2](https://user-images.githubusercontent.com/6552100/39618721-a68ad702-4fa2-11e8-950d-b14852122158.png)
![glance_output3](https://user-images.githubusercontent.com/6552100/39618727-abe53094-4fa2-11e8-8148-3e77989d9c1d.png)

**Comment by hevayo** [comment]
This is no longer reproducible in 0.975.0. Please reopen if you encounter this issue again.
