### ISSUE TITLE
[Chaos] Composer becomes unresponsive if composer started with --host, a service started remotely and try to start the same service locally

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8372]
**Description:**
The below issues are there in composer, if composer starts with --host, remotely start a service and try again to start the same service on first machine's running browser. Please see steps to recreate.
Issues
- In machine one running browser, the composer get stucked
- In machine2 running browser, the composer console prints error log as "address already used"

**Steps to reproduce:**
- Start the composer in one machine with --host (e.g. `./composer --host <IP1>`
- Access the composer in second machine
- Run a service from BBE (e.g. helloworld_service.bal) => Service up and running
Observed: This service could invokable from any of the machine with IP1
- Now try to start the same service from machine1 
Observed: Service initialized, but not started. Now in machine1 the composer get prints error log address already in use.

This issue can reproduce vise-verse. 
Note that when browser running on first machine is refreshed, everything come to work.

**Affected Versions:**
0.970.0

**OS, DB, other environment details and versions:**
machine1 - ubuntu 16.04 | Firefox
machine2 - ubuntu 16.04

**Comment by hevayo** [comment]
Fix is to prevent composer being able to access from another machine since it is a security issue.

**Comment by hevayo** [comment]
Please ignore the previous comment. This is the expected behavior, even though you access composer from another machine the service will get started on the machine that the composer runs so you would get address already in use error the second time.
