### ISSUE TITLE
Refactor/rename ballerina/auth/auth_provider.bal to Properly Reflect the Usage

### ISSUE THREAD

**Issue by isurulucky** [ballerina-platform/ballerina-lang#8381]
**Description:**
Currently ballerina/auth/auth_provider.bal does acts as an interface for plugging in different userstores. However, the naming is conflicting with the AuthProvider type in ballerina/http/secure_listener.bal. Need to refactor/rename ballerina/auth/auth_provider.bal to reflect that its an interface for a userstore.

**Affected Versions:**
0.970.0

**Comment by ldclakmal** [comment]
Thanks for the suggestion. This was a valid concern. We have refactored Ballerina authentication framework in v1.0 [1] and this was fixed. Closing the issue since this is not longer valid.
[1] https://ballerina.io/learn/writing-secure-ballerina-code/
