### ISSUE TITLE
Composer icons should be more user friendly to reduce thinktime for the user

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8383]
**Description:**
The behavior of the + symbol on the sequence diagram is conducing. If the + symbol is not used or there is no item to e added practically we need to disable the symbol

**Steps to reproduce:**
1.Open the sample transactional-queue-message-producer
2.Click on the + icon on the bottom of the chart (Screen shot attached)
If there is no object to be added logically on that step then the + symbol should be grayed out 
**Affected Versions:**

**OS, DB, other environment details and versions:**
1.Ubuntu
2.59.0.2

`If we gray-out those which cannot be used then the think time for the user can be cut down and improve usability ` As seen from the diagram both 1 and 2 + icons looks the same but only 2 provides us the options to work from
![plus_icon](https://user-images.githubusercontent.com/6552100/39739520-ee8eecb4-52ae-11e8-98e6-e687e07a1bf5.png)

**Comment by hevayo** [comment]
There will not be a case where the + button will not have a component to add. In 0.975.0 plus button always have an item.
