### ISSUE TITLE
The sequence diagram for identify_trends sample does not load

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8400]
**Description:**
The sequence diagram for identify_trends sample does not load

**Steps to reproduce:**
1.load the identity trends sample

**Affected Versions:**
Ballerina 0.970.0

**OS, DB, other environment details and versions:**
1.Ubuntu 16.04
2.Firefox 59.0.2
![identify_trend](https://user-images.githubusercontent.com/6552100/39751526-153a3b3a-52d6-11e8-9806-bea9998921b3.png)

**Comment by hevayo** [comment]
Works in 0.970.1
