### ISSUE TITLE
the folder name are not loaded on composer if we give / after the folder name

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8421]
**Description:**
the folder name are not loaded on composer if we give / after the folder name

**Steps to reproduce:**
1.Click on open project directory
2.Give the path upto  <path on your macheine>/ballerina-examples/examples/

**Affected Versions:**
Ballerina 0.970.0-SNAPSHOT
Ballerina 0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Firefox 59.0.2
Ubuntu 16.04

**Comment by shavantha** [comment]
![folder_names](https://user-images.githubusercontent.com/6552100/39796054-fd5fd38e-5371-11e8-86ae-65fad887e33c.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8440
