### ISSUE TITLE
Reformat Code breaks the exciting code

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8432]
**Description:**
Reformat Code breaks the exciting code

**Steps to reproduce:**
1.click on reformat code after opening a sample

**Affected Versions:**
Ballerina 0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
1.Ubuntu 16.04
2.Firefox 59.0.2

![after reformat](https://user-images.githubusercontent.com/6552100/39799817-47a65f56-5383-11e8-8be2-acab31d7e0ef.png)
![before_reformat](https://user-images.githubusercontent.com/6552100/39799818-47d5a0cc-5383-11e8-8333-4c622562b0c1.png)

**Comment by NipunaMarcus** [comment]
This has been fixed with the source gen improvements hence closing this issue.
