### ISSUE TITLE
Save File As name should be the name of the existing file.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#8447]
**Description:**
The name of the files you would want to save as should contain the name of the original file.

**Steps to reproduce:**

- Open example Hello World/Hello World Service 
- The .bal file that opens up is 'hello_world_service'
- Go to file > Save as / ⌘+Shift+S / CTRL+Shift+S 
- File Name contains the name of the last saved file.

Expected / correct result should be
- File Name should contain 'hello_world_service.bal' 

![image](https://user-images.githubusercontent.com/10986966/39806748-44f1f7c4-5398-11e8-94e4-191955a0c55d.png)

**Suggested Labels **
component/Composer

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
