### ISSUE TITLE
Rename Symbol capability throws NPE in LS

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#8455]
**Description:**
Rename Symbol capability not working in LS.

**Steps to reproduce:**
1. Add following code in VS code editor.
```
import ballerina/http;

@http:ServiceConfig {
    basePath: "/"
}
service<http:Service> hello bind {port:9090} {
    @http:ResourceConfig {
        methods: ["POST"],
        path: "/"
    }
    hi (endpoint caller, http:Request request) {
        string payload = check request.getTextPayload();
        http:Response res;
        res.setPayload("Hello "+payload+"!\n");
        _ = caller->respond(res);
    }
}
```
2. Right click on `payload` and click on "Rename Symbol" 
3. Check the exception thrown.

**Affected Versions:**
0.97.0

**OS, DB, other environment details and versions:**
Mac OS

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by NipunaMarcus** [comment]
This has been fixed hence closing this issue.
