### ISSUE TITLE
[debugger] When debugging services, debug server is not killed

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#8480]
<a href="https://github.com/roonyh"><img src="https://avatars0.githubusercontent.com/u/3872221?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roonyh](https://github.com/roonyh)**
_Thursday Feb 01, 2018 at 14:10 GMT_
_Originally opened as https://github.com/ballerina-lang/plugin-vscode/issues/44_

----

Stopping debugging does not kill started debug server, when debugging services.

Gives the address already in use error.

**Comment by lankavitharana** [comment]
you need to kill the service, we cannot kill the service for "debugStop" command.
