### ISSUE TITLE
Code completion Doesn't work inside service block

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#8481]
<a href="https://github.com/ajanthan"><img src="https://avatars2.githubusercontent.com/u/525801?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ajanthan](https://github.com/ajanthan)**
_Monday Apr 30, 2018 at 21:00 GMT_
_Originally opened as https://github.com/ballerina-lang/plugin-vscode/issues/54_

----

I have downloaded the latest version of Ballerina(0.970.0)  and installed vscode plugin from marketplace to my vscode 1.22.2. I was able to add ServiceConfig with code completion but not ResourceConfig.

**Comment by nadeeshaan** [comment]
This Has been already fixed in Language Server. Hence closing the issue
