### ISSUE TITLE
Installing from .vsix not clear for Mac

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#8482]
<a href="https://github.com/samisawso2"><img src="https://avatars2.githubusercontent.com/u/7627249?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [samisawso2](https://github.com/samisawso2)**
_Monday May 07, 2018 at 16:35 GMT_
_Originally opened as https://github.com/ballerina-lang/plugin-vscode/issues/57_

----

The commands does not work on Mac. Need better instructions.

**Comment by roonyh** [comment]
@samisawso2 The option 2 from [here](https://github.com/ballerina-platform/ballerina-lang/tree/master/tool-plugins/vscode/plugin#quick-start) should work on any platform.

**Comment by roonyh** [comment]
Please reopen if the updated linked instructions are not clear enough or not accurate.
