### ISSUE TITLE
Instruction on how to create a project and run

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#8483]
<a href="https://github.com/samisawso2"><img src="https://avatars2.githubusercontent.com/u/7627249?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [samisawso2](https://github.com/samisawso2)**
_Monday May 07, 2018 at 16:36 GMT_
_Originally opened as https://github.com/ballerina-lang/plugin-vscode/issues/58_

----

$subject missing in any docs. 

How do I create a project? 

How do I run my program from VS code?

**Comment by samgnaniah** [comment]
This is now covered in the Quick Tour so I'm closing this.

https://ballerina.io/learn/quick-tour/
