### ISSUE TITLE
[WebSub] Add/Improve Tests

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#8489]
**Description:**
Unit tests need to be added to cover scenarios/aspects such as
- service definition
- service configuration
- annotations
- dispatching  

Integration tests need to be improved to cover 
- discovery with redirection
- subscription with redirection
- subscription with additional parameters - additional params need to be ignored as per the recommendation

**Comment by chamil321** [comment]
Fixed by https://github.com/ballerina-platform/ballerina-lang/pull/10100. hence closing the issue
