### ISSUE TITLE
[Docarina] Need more data to add links to data types in ballerina central package detail

### ISSUE THREAD

**Issue by Minoli** [ballerina-platform/ballerina-lang#8535]
**Description:**
There are two options to link the primitive and external package data types from package details in ballerina central
1.  Add links to ballerina.io primitive types and ballerina packages datatypes.
2. To have the primitive types and external packages in central and have links to the related data types. 

The current value passed to package detail datatype href attribute is <package-name>.html#<datatype-name> for local and external packages and primitive-types.html#<datatype-name> for primitive types. 

Need the following data to go forward with option 1 or 2 to structure the data type path from [1].
- Organization name 
- Package name
- datatype : isPrimitive/ isExternal

[1] https://github.com/Minoli/ballerina-registry/blob/master/registry.docs/resources/templates/page.hbs

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment]
Closing as no longer relevant.
