### ISSUE TITLE
Can not pull Ballerina connectors 

### ISSUE THREAD

**Issue by ranga-siriwardena** [ballerina-platform/ballerina-lang#8536]
**Description:**
When trying to pull a connector it gives following message. 

ballerina pull wso2/twitter
package version information is missing from the remote repository

Also, when trying to import the connector and build it gives a similar error. 

ballerina build member_service.bal 
package version information is missing from the remote repository error: ./member_service.bal:3:1: cannot resolve package 'wso2.twitter'

**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.970.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
We did some refactors to the code of pulling packages in the new release. This scenario is working fine with the latest stable release:  [Ballerina 0.970.1](https://ballerina.io/downloads/). Can you try this scenario with **Ballerina 0.970.1**?

**Comment by NatashaWso2** [comment]
This scenario works fine with both Ballerina 0.970.0 and 0.970.1 so closing this issue.
