### ISSUE TITLE
Unable to run most sample on composer Build taken on 14th May 2018

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8544]
**Description:**
Unable to run any sample on composer Build taken on 14th May 2018

**Steps to reproduce:**
1.try to run basic samples on composer

**Affected Versions:**
Ballerina 0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
```
Ubuntu 16.04/ Windows 10
java version "1.8.0_131"
```
![composer](https://user-images.githubusercontent.com/6552100/39980309-e6f61ea0-5768-11e8-832b-d046d9113148.png)

**Comment by shavantha** [comment]
keeping the issue reopened

**Comment by pahans** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/8706
