### ISSUE TITLE
the functionality of the remove button on  file rename dialog box is not correct

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8550]
**Description:**
the cancel button file rename seems to take the changes made and not reset to original file name. On some occasions the new file name is kept other times we see another file generated.

**Steps to reproduce:**
1.open a sample
2.select the full sample name ex:steams.bal and set as streams123.bal
3.click on cancel button: 
Note: the folder structure will have the original file and another file with the new name

**Affected Versions:**
ballerina-tools-0.970.2
**OS, DB, other environment details and versions:**
1.ubuntu 16.04
2.Firefox 39.0.3

Note: ideally the remove button should reset the user change to the original file name
![remove_button](https://user-images.githubusercontent.com/6552100/39994104-dbea8046-5795-11e8-8587-e434415b601b.png)

**Comment by shavantha** [comment]
![composer](https://user-images.githubusercontent.com/6552100/39994791-f5afddf8-5797-11e8-9ca5-1f82aeea32f6.png)

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9005
