### ISSUE TITLE
if we dont pass the required details for ./ballerina list the user should be provided with a hint

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8553]
**Description:**
if we dont pass the required details for ./ballerina list the user should be provided with a hint

**Steps to reproduce:**
1.execite ballerina list
Note: no message is printed
2.execute ballerina run and we get a message like
```
ballerina: no ballerina program given
Run 'ballerina help' for usage.

```
Note: similar to the message we get for `ballerina run` we should provide a repose to the user for` ballerina list`

**Affected Versions:**
1.Ballerina 0.970.2-SNAPSHOT

**OS, DB, other environment details and versions:**
1.Ubuntu 16.04

**Comment by shavantha** [comment]
currently the only way to find out is `ballerina list --help`

**Comment by NatashaWso2** [comment]
If 'ballerina list' is executed without any parameters, dependency trees for all packages in that particular project will be shown. This is the expected behavior so closing this issue.
