### ISSUE TITLE
The COPYWRITE year is shown as 2017 in the COPYRIGHT file in ballerina-lang 

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8571]
**Description:**
The COPYWRITE year is shown as 2017 in the COPYRIGHT files in ballerina-lang and  ballerina-0.970.2-SNAPSHOT

```

Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

This product includes software developed at WSO2 (http://wso2.com/).

```

**Comment by anupama-pathirage** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/8256. Hence closing this.
