### ISSUE TITLE
Different errors for different I/O errors

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#8591]
**Description:**
At the moment we return one error for all the I/O errors. We need a way to distinguish different I/O errors. This is specially needed for resiliency stuff.

**Comment by riyafa** [comment]
@shafreenAnfar Can this issue be closed because we now use generic error for all errors? It is not I/O specific?

**Comment by shafreenAnfar** [comment]
I am closing this as we have fixed this for http.
