### ISSUE TITLE
Ballerina Package for Emailing

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#8617]
**Description:**
Currently theres no way of sending emails using ballerina. Can we have a ballerina package for emailing purposes ? Given that it has to be a native package.

**Comment by pubudu91** [comment]
@hemikak Better if this is raised on the dev group?

**Comment by hemikak** [comment]
@pubudu91  +1

**Comment by mkasovic** [comment]
Few months ago I had a need to send emails using Ballerina via SMTP. So I have created simple connector to do the job (https://github.com/in2group/connector-smtp). Maybe it can be used as a starting point for offical SMTP Ballerina connector?

**Comment by anupama-pathirage** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/4378

**Comment by Shan1024** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/4378.

**Comment by keizer619** [comment]
This feature has been raised in the Stackoverflow as well
https://stackoverflow.com/questions/53645207/ballerina-how-do-connect-with-smtp-server-and-send-email
