### ISSUE TITLE
Return values of ballerina/internal:delete function is wrong

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#8632]
**Description:**
According the definition it states that the file delete function returns a boolean or an error. But the implementation never returns a boolean.

ballerina native - https://github.com/ballerina-platform/ballerina-lang/blob/6b0e20447ddeefa7e7ae8528c4fc784262bf0c4d/stdlib/ballerina-builtin/src/main/ballerina/internal/file.bal#L96

Implementation - https://github.com/ballerina-platform/ballerina-lang/blob/6b0e20447ddeefa7e7ae8528c4fc784262bf0c4d/stdlib/ballerina-builtin/src/main/java/org/ballerinalang/nativeimpl/internal/Delete.java#L71

IMO it should return an `error?`. If what is expected is a file to be deleted, and if that fails, then its an error.

**Steps to reproduce:**

**Affected Versions:**
0.970.1, 0.970.0

**OS, DB, other environment details and versions:**
OSX, Linux

**Comment by riyafa** [comment]
Resolved in https://github.com/ballerina-platform/ballerina-lang/pull/8852
