### ISSUE TITLE
Impossible to run ballerina program with IntelliJ plugin on Windows

### ISSUE THREAD

**Issue by hayaofr** [ballerina-platform/ballerina-lang#8636]
**Description:**

Impossible to run a ballerina service or main program in IntelliJ with the "Run Application" Icon.
In the run view I have :
ballerina: cannot find file 'C:\Dev\test_ballerina\Test.bal'

I have an other issue that could be related in command line :
In my test_ballerina directory, the command "ballerina run Test.bal" works but "ballerina run .\Test.bal" does not work. ".\Test.bal" comes from Powershell tab completion
**Steps to reproduce:**

**Affected Versions:**
ballerina-platform-0.970.1
ballerina Intellij plugin 0.970.1

**OS, DB, other environment details and versions:**
Windows 10
IntelliJ 2018.1.3 (CE)

**Related Issues (optional):**

**Suggested Labels (optional):**

idea, intellij

**Suggested Assignees (optional):**

**Comment by Shan1024** [comment]
@hayaofr - Can you create a separate issue for the 2nd issue(which is related to command line) mentioned here?

@manuranga  - Can you check the 2nd issue mentioned here?
