### ISSUE TITLE
Definition names are not Unique

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#8736]
**Description:**
Consider the two types of definitions, Record, and a Function. Currently, we can define both a function and a Record with the same name in the same package. Which should not be allowed.

**Steps to reproduce:**

```
import ballerina/io;

type Person {
    string name;
};

function Person() {
    io:println("Hello!");
}
```

**Affected Versions:**
v0.971.1-SNAPSHOT

**Comment by Shan1024** [comment]
See https://github.com/ballerina-platform/ballerina-lang/issues/9022.

**Comment by hasithaa** [comment]
Already fixed in master. (JBallerina 1.0.0-Alpha)
