### ISSUE TITLE
Unable to configure timeout for http:Listener endpoints

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#8764]
**Description:**
At the moment, it is not possible to configure the timeout for http:Listener endpoints. 

**Steps to reproduce:**
Try to configure a timeout for a request in the following code.
```
// A service endpoint represents a listener
endpoint http:Listener listener {
    port: config:getAsInt("FUNC_PORT", default = 8080)
};
```
**Affected Versions:**
0.971.0

**OS, DB, other environment details and versions:**
Any OS

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**

**Comment by arukshani** [comment]
Fixed with #9172
