### ISSUE TITLE
Incorrect encoding results in String.Base64Decode API with "utf-8" encoding

### ISSUE THREAD

**Issue by mpmunasinghe** [ballerina-platform/ballerina-lang#8783]
**Description:**
While decoding base64 encoded string using the String.Base64Decode() method the expected output result is not the exact as the String before decoding. 

With initial findings it was evident that the issue is primarily occurring do to the String initialization in [257](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-builtin/src/main/java/org/ballerinalang/nativeimpl/Utils.java#L257) instead of returning a decoded byte array. 

Also in line the encoding type format is hard coded to ISO-8859-1 [255](https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-builtin/src/main/java/org/ballerinalang/nativeimpl/Utils.java#L255) this should use the parsed charset to the method. 

**Steps to reproduce:**
Create a utf-8 string get the checksum and encode with base64 encode. Parse the encoded string through base64Decode in String then get the checksum. The resulting checksum values will not match. 

**Affected Versions:**
Current 

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**
Shan

**Comment by arukshani** [comment]
@mpmunasinghe

While doing the encoding we should use the passed charset only to get the byte array and to get the encoded string value out of that we should use ISO-8859-1. Please see [1].

I have tried the mentioned steps to recreate the issue but that works fine. This is the sample code I tried.

    public void testChecksum() throws UnsupportedEncodingException, NoSuchAlgorithmException {
        byte[] original = "ði ıntəˈnæʃənəl fəˈnɛtık əsoʊsiˈeıʃn".getBytes("utf-8");
        byte[] encodedBytes = Base64.getEncoder().encode(original);
        String encodedString = new String(encodedBytes, StandardCharsets.ISO_8859_1);
        byte[] decodedBytes = Base64.getDecoder().decode(encodedString.getBytes(StandardCharsets.ISO_8859_1));
        String decodedString = new String(decodedBytes, "utf-8");
        //Checksum of the original
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.reset();
        md.update(original);
        byte[] originalDigest = md.digest();
        BigInteger originalChecksum = new BigInteger(1,originalDigest);


        //Checksum after decoding
        md.reset();
        md.update(decodedString.getBytes("utf-8"));
        byte[] decodedDigest = md.digest();
        BigInteger checkSumAfterDecode = new BigInteger(1,decodedDigest);
        System.out.println(originalChecksum);
        System.out.println(checkSumAfterDecode);
        Assert.assertEquals(originalChecksum, checkSumAfterDecode);
    }

Is there any other way I can recreate the issue you are experiencing? 

[1] https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Encoder.html#encodeToString-byte:A-

**Comment by arukshani** [comment]
Ideally, the following function should directly return a decoded byte array instead of further trying to convert it to a string with a given charset. 

public native function string::base64Decode(string charset = "utf-8") returns string|error;

Since the logic is correct labeling this as an improvement. The above function is currently used for JWT authentication and since the byte array to string conversion has been moved to mime jwt package unnecessarily has to use mime as a dependency. Once it is sorted out we will add this improvement.

**Comment by wggihan** [comment]
This was addressed with the new encoding module refactoring.
```
import ballerina/encoding;

public function decodeBase64(string input) returns byte[]|error
```
