### ISSUE TITLE
Composer document update event sent after completion request.

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#8839]
**Description:**
If a user types fast or use completions to add text continuously the completion breaks. If you look at the syntax errors you can see it shows an error related to a previous state. This issue can be observed more in unsaved files. Please see the attached screen for an example.

![screenshot from 2018-06-01 15-28-28](https://user-images.githubusercontent.com/323846/40835290-9bf191d6-65b0-11e8-8070-78c7553aec29.png)

**Comment by DimalChandrasiri** [comment]
Unable to reproduce in the latest pack. 

Version Checked : v0.981.1
