### ISSUE TITLE
Improve `any` to other type casting

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#8853]
**Description:**
Currently, we cannot directly cast an `any` value to another value. The below code snippet will produce an error(`error: 'string' cannot be cast to 'int'`) which can be confusing to the user because the `string`->`int` casting is possible in Ballerina.

```ballerina
any choice = io:readln("Enter choice 1 - 5: ");
var intChoice = <int>choice;
```

We need to add an additional line to cast the `any->string` first, like below.
```ballerina
any choice = io:readln("Enter choice 1 - 5: ");
string s = <string>choice;
var intChoice = <int>s;
```

It is better if we can do this unboxing automatically.

See also https://github.com/ballerina-platform/ballerina-lang/issues/8842.

**Comment by MaryamZi** [comment]
This is no longer valid with the changes introduced with https://github.com/ballerina-platform/ballerina-lang/pull/13479, introducing the type cast expression specified in the 0.990.0 spec. 

`string` to `int` conversion cannot be done using the diamond operator. 

The current alternative is to use `.convert()`, but this would change in the future (refer - https://groups.google.com/d/topic/ballerina-dev/9wSEMbqkltI/discussion).
```ballerina
    var intChoice = int.convert(choice);
```
