### ISSUE TITLE
Installation warning on ubuntu

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#8881]
**Description:**

Installing ballerina via the linux deb package using ubuntu software center gives the below warning.

```
The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.
```

![installwarning](https://user-images.githubusercontent.com/16300038/40990562-bfbc7e5e-68e0-11e8-89d3-64b93542edf0.png)

**Steps to reproduce:**

**Affected Versions:**

0.970.0
0.970.1

**OS, DB, other environment details and versions:**

OS
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
These are causing due to package ownership is not root. This has been now fixed with latest installers.
