### ISSUE TITLE
Support switch-case like conditions using match

### ISSUE THREAD

**Issue by lahirus** [ballerina-platform/ballerina-lang#8882]
**Description:**
@sameera-jayasoma mentioned that there is a plan to support $subject at [this](https://stackoverflow.com/questions/50333592/does-ballerina-support-switch-case) SO question, 

**Affected Versions:**
0.970.1

**Comment by Anoukh** [comment]
@lahirus we have introduced this feature with the new match statement and will be available with 0.990 release. Hence closing the issue.
