### ISSUE TITLE
[gRPC][Stub Generator] Passing --output path not working in Stub generator.

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#8889]
**Description:**
In gRPC stub generator tool, we cannot pass output directory path using (--output).

**Steps to reproduce:**
Try ballerina sample [1] with below command.
ballerina grpc --input proto_to_ballerina.proto --output grpc-client

1. https://github.com/ballerina-platform/ballerina-examples/tree/master/examples/proto-to-ballerina

**Affected Versions:**
0.970.1

**OS, DB, other environment details and versions:**
This is not environment specific issue. Tested in Mac

**Related Issues (optional):**
No

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**
@daneshk

**Comment by gocoolcode** [comment]
@daneshk  - I tried without passing --output argument and it is still failing with same

**Comment by gocoolcode** [comment]
@daneshk  - I am using stable version - 0.970.1 
I downloaded nightly snapshot and still facing issue.I will try on different machine and update you.

When the stable 0.973 will be released?

...../grpc-service-master/guide >>../ballerina-platform-0.973.1-SNAPSHOT/bin/ballerina grpc --input target/grpc/orderMgt.proto
Continue with existing protoc executor.
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

**Comment by gocoolcode** [comment]
[2018-06-07 14:51:50,080] ERROR {org.ballerinalang.launcher.Main} - Error occurred at generating proto descriptor.
org.ballerinalang.net.grpc.exception.BalGenerationException: Error occurred at generating proto descriptor.
        at org.ballerinalang.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:141)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:66)

**Comment by daneshk** [comment]
@gocoolp sorry for delay in updating the issue. We have fixed similar issue #9533 which is in windows env. Could you please verify your issue in latest RC pack[1].  

1. https://product-dist.ballerina.io/dev/0.980.0/ballerina-platform-0.980.0.zip

**Comment by gocoolp** [comment]
@daneshk  - I tried on Windows machine with RC.Getting below error (snippet from ballerina log)

[2018-07-11 23:05:27,881] ERROR {org.ballerinalang.launcher.Main} - 
<home>\gprc-service\guide\desc_gen\target\grpc\orderMgt-descriptor.desc: No such file or directory 
org.ballerinalang.protobuf.exception.BalGenToolException: 
C:\Gokul\Learning\VSCodeWorkspace\gprc-service\guide\desc_gen\target\grpc\orderMgt-descriptor.desc: No such file or directory
	at org.ballerinalang.protobuf.utils.BalFileGenerationUtils.generateDescriptor(BalFileGenerationUtils.java:103)
	at org.ballerinalang.protobuf.utils.BalFileGenerationUtils.getProtoByteArray(BalFileGenerationUtils.java:150)
	at org.ballerinalang.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:152)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)

**Comment by daneshk** [comment]
@gocoolp Thanks for testing in RC pack. I created new issue #9607 for this. since this issue is already closed. I will update my finding there.
