### ISSUE TITLE
Debugger becomes broken after pressing stop button

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#8890]
Can be reproduced with hello world main sample.
If we press stop btn next to resume btn, while flow is paused on a debug hit, we cannot start subsequent debug sessions until we restart composer.

**Comment by pahans** [comment]
Could not reproduce this issue.

**Comment by pahans** [comment]
Was able to reproduce this with electron.

**Comment by pahans** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9576 @kaviththiranga can you verify the fix?
