### ISSUE TITLE
Refactor the createEntityError() and getParserError() methods in MimeUtil

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#8896]
Refactor the `createEntityError()` and `getParserError()` methods in `MimeUtil.java` class to use the `BLangVMErrors.createError(context, message)` method.

We can also get rid of `org.ballerinalang.mime.util.STRUCT_GENERIC_ERROR` constant.

**Comment by arukshani** [comment]
This is fixed with #9059
