### ISSUE TITLE
Invalid Diagnostic Position metrics for Record Symbol

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#8917]
**Description:**
Consider the Following Record definition

![selection_171](https://user-images.githubusercontent.com/1329674/41081960-49f4c9a4-6a4a-11e8-94ed-5eeb3eb63810.png)

When checking the typeDefinition node, start line has become line 3 and end line has become line 1

This only happens when there are not fields within the record

**Affected Versions:**
v0.973.1-SNAPSHOT

**Comment by Kishanthan** [comment]
This is not reproducible. I can see the correct line numbers for an empty record as below.

<img width="269" alt="screen shot 2018-06-13 at 10 00 57 am" src="https://user-images.githubusercontent.com/690559/41330414-ffd9a244-6ef0-11e8-9b04-a43074c72148.png">


<img width="657" alt="screen shot 2018-06-13 at 9 55 58 am" src="https://user-images.githubusercontent.com/690559/41330321-6a9876a6-6ef0-11e8-94c3-a1d647c9152f.png">

**Comment by nadeeshaan** [comment]
Issue can be observed when we look at the Diagnostics position of the typeNode

**Comment by Shan1024** [comment]
Already fixed in https://github.com/ballerina-platform/ballerina-lang/pull/9654.
