### ISSUE TITLE
[gRPC] Support contract first approach for service creation

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#8954]
**Description:**
Current gRPC implement supports only code first approach. We need to support contract first where generate service code from the proto file.

**Steps to reproduce:**
N/A. This is an improvement. we are not support this

**Affected Versions:**
N/A. This is an improvement. we are not support this

**OS, DB, other environment details and versions:**
N/A. This is an improvement. we are not support this

**Related Issues (optional):**
None

**Suggested Labels (optional):**
improvement

**Suggested Assignees (optional):**
daneshk

**Comment by arukshani** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/10560
