### ISSUE TITLE
is:sprintf API doc deos not detail what the format paramters are 

### ISSUE THREAD

**Issue by samisawso2** [ballerina-platform/ballerina-lang#8969]
public function sprintf(string format, any[] args) returns (string)

What are the supported %formats here? The API doc says nothing. 

If I have the JSON 
```
json jsonMsg = { a: 15.6, b: 18.9, operation: "add" };
```

How can I sprintf `jsonMsg["a"]` and `jsonMsg["b"]`?

Following does not work: 
```
string resultMessage = io:sprintf("Addition result %f + %f :", jsonMsg["a"], jsonMsg["b"]);
```

**Comment by riyafa** [comment]
There are some inconsistencies in `sprintf` function and it needs to be revisited https://github.com/ballerina-platform/ballerina-lang/issues/9323
