### ISSUE TITLE
null error when running ballerina program 

### ISSUE THREAD

**Issue by mpmunasinghe** [ballerina-platform/ballerina-lang#8991]
**Description:**
when running ballerina run on a simple helloworld program against the nightly build **ballerina-platform-macos-installer-x64-0.974.0**. I get the following error when installed with mac osx installation. 
`ballerina: error loading balo null`

When I run the externally downloaded binary the execution happens with the same user. 

The above error can be avoided only when the ballerina run is executed under super user. 

**Steps to reproduce:**
- Install ballerina nightly build ballerina-platform-macos-installer-x64-0.974.0 on mac os. 
- execute ballerina run hello-world.bal on a ballerina file

**Affected Versions:**
0.974.0

**OS, DB, other environment details and versions:**
MacOs

**Related Issues (optional):**

**Suggested Labels (optional):**
Critical, Bug, Installer

**Suggested Assignees (optional):**
Tharik

**Comment by lankavitharana** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9035
