### ISSUE TITLE
ballerinax balo not packaged in nightly build 974.0

### ISSUE THREAD

**Issue by mpmunasinghe** [ballerina-platform/ballerina-lang#8997]
**Description:**
In the nightly build **0.974.0** relevant balo files for **ballerinax** package is not shipped. 

**Steps to reproduce:**
- import ballerina/docker or balleinax/kuberenetes in a ballerina project.
- run ballerina build and below error will be visible
`cannot resolve package 'ballerinax.docker'`

**Affected Versions:**
974.0 nightly build

**OS, DB, other environment details and versions:**
Mac OS

**Related Issues (optional):**

**Suggested Labels (optional):**
Bug, Critical

**Suggested Assignees (optional):**
Tharik

**Comment by keizer619** [comment]
This is fixed in following PR.
https://github.com/ballerina-platform/ballerina-distribution/pull/67
