### ISSUE TITLE
support user authentication for JMS connections

### ISSUE THREAD

**Issue by JensWalter** [ballerina-platform/ballerina-lang#9016]
**Description:**
If I want to configure a JMS provider through JNDI, the current configuration parameters do not allow me to set an explicit username and password for the actual connection. The documentation uses ActiveMQ, which allows the credentials to be set through the connection URL, but this is not really applicable to other JMS providers.

Therefore I would really like to extends the JMS connection configuration, so it can hold credentials in addition the current properties.

I would provide a pull request for this issue, but since I'm just starting with ballerina, I am not sure what the correct place for such credentials is. Therefore I would suggest two solution which seam feasable in my opinion and ask for some feedback of what would be the right approach here.

Option 1:
```
jms:Connection conn = new({
    initialContextFactory:"com.tibco.tibjms.naming.TibjmsInitialContextFactory",
    providerUrl:"tcp://server1:7222,tcp://server2:7222",
    properties:{
        "java.naming.security.principal":"admin",
        "java.naming.security.credentials":"admin",
        "ConnectionUsername":"admin",
        "ConnectionPassword":"admin"
    }
});
```

Option 2:
```
jms:Connection conn = new({
    initialContextFactory:"com.tibco.tibjms.naming.TibjmsInitialContextFactory",
    providerUrl:"tcp://server1:7222,tcp://server2:7222",
    connectionUsername:"admin",
    connectionPassword:"admin",
    properties:{
        "java.naming.security.principal":"admin",
        "java.naming.security.credentials":"admin"
    }
});
```

**Steps to reproduce:**
Configuring a TIBCO EMS as JMS provider fails, since no authentication can be given.
```
jms:Connection conn = new({
    initialContextFactory:"com.tibco.tibjms.naming.TibjmsInitialContextFactory",
    providerUrl:"tcp://server1:7222,tcp://server2:7222",
    properties:{
        "java.naming.security.principal":"admin",
        "java.naming.security.credentials":"admin"
    }
});
```
**Affected Versions:**
v0.970.1

**Suggested Labels (optional):**
Type/New Feature, component/stdlib

**Suggested Assignees (optional):**

**Comment by VijithaEkanayake** [comment]
@JensWalter We'll go through your suggested approaches and give you a feedback asap.

**Comment by VijithaEkanayake** [comment]
@JensWalter Let's go with the option 2.

We can define username and password as nullable types within ConnectionConfiguration record type. Then we can improve the createConnection() implementation done in[1]. you can implement another Ballerina function to populate the default values for the credentials if the user hasn't passed username,password and call the createConnection().

```
public type ConnectionConfiguration {
    string initialContextFactory = "wso2mbInitialContextFactory";
    string providerUrl = "amqp://admin:admin@ballerina/default?brokerlist='tcp://localhost:5672'";
    string connectionFactoryName = "ConnectionFactory";
    string username?;
    string password?;
    map properties;
};
```

[1]. https://github.com/ballerina-platform/ballerina-lang/blob/master/stdlib/ballerina-jms/src/main/ballerina/jms/connection.bal#L29

**Comment by a5anka** [comment]
@VijithaEkanayake I think It is better if we do not populate the defaults for username and password if the user has not provided them in the record. 

1. If the user **has not provided username and password** we should use [ConnectionFactory#createConnection()](https://docs.oracle.com/javaee/7/api/javax/jms/ConnectionFactory.html#createConnection--) method in the native implementation.

2. If the user **has provided username and password** we should use [ConnectionFactory#createConnection(username, password)](https://docs.oracle.com/javaee/7/api/javax/jms/ConnectionFactory.html#createConnection-java.lang.String-java.lang.String-) method in the native implementation.

This way the ballerina API will be similar to how the JMS API works. 
WDYT?

**Comment by JensWalter** [comment]
I totally agree with @a5anka here. We must not populate defaults for credentials, because this would lead to very weird behavior.
Using credentials when present is fine, otherwise use the connect without credentials as described in the code snippet above.

**Comment by VijithaEkanayake** [comment]
@a5anka , @JensWalter +1 the suggestions. I too think making Ballerina API similar to JMS API would be the cleaner approach here.
