### ISSUE TITLE
[Composer] Welcome page responsive improvement

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9041]
**Description:**
Middle content needs to be properly re-arrange/react on view-port size change for better readability. 

E.g.  
- Column count can be reduce on smaller screens
- Left buttons can be move to top

![image](https://user-images.githubusercontent.com/7569427/41339153-c9b2a9d8-6f11-11e8-872a-1ac7be3aba66.png)

**Steps to reproduce:**
Open composer with the welcome screen and reduce screen size

**Affected Versions:**
v0.970.1

**OS, DB, other environment details and versions:**
Windows 10, Chrome

**Suggested Labels (optional):**
[Type/UX]

**Suggested Assignees (optional):**
@srsharon

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
