### ISSUE TITLE
[Composer] Edited state wont roll back after undoing to original state

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9047]
**Description:**

![composer](https://user-images.githubusercontent.com/7569427/41344279-504e8104-6f1e-11e8-950f-2677a4368062.gif)

**Steps to reproduce:**
After editing a file. Try undoing the change to original state using "ctrl+z"
And you will notice that edited state asterisk mark on the tab wont go and when you try closing the file, it will prompt to save file.

**Affected Versions:**
v0.974.1.SNAPSHOT

**OS, DB, other environment details and versions:**
Windows 10, Chrome

**Suggested Labels (optional):**
[Type/UX]

**Suggested Assignees (optional):**
@kaviththiranga

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
