### ISSUE TITLE
Check the possibility of packaging OpenJDK with Ballerina distribution

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerina-platform/ballerina-lang#908]

**Comment by uthaiyashankar** [comment]
We are working on this.

**Comment by keizer619** [comment]
This is done in ballerina-distribution repository [1]. There we will include additional components such as docker, kubernetes and etc. Basically it will produce following distributions by embedding JRE. These will be used to create installers for each operating system.

- ballerina-platform-linux-{version}.zip
- ballerina-platform-macos-{version}.zip
- ballerina-platform-windows-{version}.zip
- ballerina-runtime-linux-{version}.zip
- ballerina-runtime-macos-{version}.zip
- ballerina-runtime-windows-{version}.zip

Additionally it will produce follow 2 distributions without JRE.
- ballerina-platform-{version}.zip
- ballerina-runtime-{version}.zip

[1] https://github.com/ballerina-platform/ballerina-distribution
