### ISSUE TITLE
Rename composer view menu items to something meaningful

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#9123]
**Description:**
Currently in composer view menu item names doesn't exactly say what user will see when they open particular panel. We need to name left and bottom panels and add those name to the view menu.  

<img width="1440" alt="screen shot 2018-06-15 at 9 36 46 pm" src="https://user-images.githubusercontent.com/9109762/41478189-6b0fdc64-70e4-11e8-9fc8-d278ccf5c20b.png">

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
