### ISSUE TITLE
Installing a new version failed in first attempt in ubuntu

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#9125]
**Description:**
Installing using the linux installer fails at the first attempt with the following error message

```
Selecting previously unselected package ballerina-0.975.0.
(Reading database ... 216310 files and directories currently installed.)
Preparing to unpack .../ballerina-platform-linux-installer-x64-0.975.0.deb ...
Unpacking ballerina-0.975.0 (0.975.0) ...
Setting up ballerina-0.975.0 (0.975.0) ...
ln: failed to create symbolic link ‘/usr/bin/ballerina’: File exists
ln: failed to create symbolic link ‘/usr/bin/composer’: File exists
```

![issue_dist](https://user-images.githubusercontent.com/16300038/41497174-a34adc5e-713f-11e8-81e9-d06e32fcc8b2.png)

**Affected Versions:**
0.974.0
0.975.0

**OS, DB, other environment details and versions:**

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

**Comment by keizer619** [comment]
This is now fixed.
