### ISSUE TITLE
Add xml content-based routing to routingService sample.

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerina-platform/ballerina-lang#913]
Here is the sample. This can be merged with the existing sample

import ballerina.net.http;
import ballerina.lang.xml;
import ballerina.lang.message;
import ballerina.lang.system;

@BasePath ("/cbr")
service contentBasedRouting {

    @POST
    resource cbrResource (message m) {

        http:HTTPConnector nyseEP = new http:HTTPConnector("http://localhost:9090/nyseStocks");
        http:HTTPConnector nasdaqEP = new http:HTTPConnector("http://localhost:9090/nasdaqStocks");

        message response;
        xml xmlMsg;
        string nameString;
        string nyseString;

        nyseString = "nyse";

        xmlMsg = message:getXmlPayload(m);
        nameString = xml:getString(xmlMsg, "/name/text()");

	system:println(nameString);

        if (nameString == nyseString) {
            response = http:HTTPConnector.post(nyseEP, "/", m);
        } else {
            response = http:HTTPConnector.post(nasdaqEP, "/", m);
        }

        reply response;
    }
}

@BasePath ("/hbr")
service headerBasedRouting {

    @GET
    resource cbrResource (message m) {

        http:HTTPConnector nyseEP = new http:HTTPConnector("http://localhost:9090/nyseStocks");
        http:HTTPConnector nasdaqEP = new http:HTTPConnector("http://localhost:9090/nasdaqStocks");

        message response;
        string nameString;
        string nyseString;

        nyseString = "nyse";

        nameString = message:getHeader(m, "name");

        if (nameString == nyseString) {
            response = http:HTTPConnector.post(nyseEP, "/", m);
        } else {
            response = http:HTTPConnector.post(nasdaqEP, "/", m);
        }

        reply response;
    }
}

@BasePath("/nyseStocks")
service nyseStockQuote {

    @POST
    resource stocks (message m) {

        message response;
        xml payload;

        payload = `<return><exchange>nyse</exchange><name>IBM</name><value>127.50</value></return>`;
        message:setXmlPayload(response, payload);

        reply response;
    }
}

@BasePath("/nasdaqStocks")
service nasdaqStocksQuote {

    @POST
    resource stocks (message m) {

        message response;
        xml payload;

        payload = `<return><exchange>nasdaq</exchange><name>IBM</name><value>127.50</value></return>`;
        message:setXmlPayload(response, payload);

        reply response;
    }
}

**Comment by shafreenAnfar** [comment]
This is no longer valid. Hence closing the issue.
