### ISSUE TITLE
Add closure support for object-type-descriptors

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#9144]
**Description:**
Consider the following program.

```ballerina
function foo() {
  int i = 10;
  object {
    new() {}
    function bar () {
      int j = 2 * i;
    }
  } b = new;
  var lambda = b.bar;
  lambda(); 
}
```

**Affected Versions:**
0.975.0

**Comment by hasithaa** [comment]
This need to be fixed for records and annotations as well.

**Comment by KRVPerera** [comment]
The issue is related to issue https://github.com/ballerina-platform/ballerina-lang/issues/20731 as well.

**Comment by hasithaa** [comment]
@KRVPerera Shall we restrict this saying this is not supported at the moment.

**Comment by hasithaa** [comment]
Another use case is the ability to create service objects dynamically using closures. See https://github.com/ballerina-platform/ballerina-lang/issues/19608.

**Comment by gimantha** [comment]
Field annotations and other edge cases will be handled in #34395
