### ISSUE TITLE
ballerina services are not starting when we run ballerina service using docker 

### ISSUE THREAD

**Issue by Susankha** [ballerina-platform/ballerina-lang#9148]
**Description:**

When we deploying a ballerina service on docker, that ballerina service is not starting.
We can see the following log in the docker logs.

native function not available ballerina.test:startServices

**Steps to reproduce:**

Deploying service [1] on docker as mentioned in [1] and start the Docker container.

[1] - https://github.com/ballerina-guides/restful-service#deployment

**Affected Versions:**

Ballerina 0.970.1

**Comment by pubudu91** [comment]
Tested on 0.975.0 and it's working fine.

**Comment by anupama-pathirage** [comment]
Closing as per the above comment. Please feel free to reopen if you have further issues.
