### ISSUE TITLE
Delete confirmation when deleting a definition

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#9176]
**Description:**
User should have a delete confirmation prompted when an action like delete is done.

![delete](https://user-images.githubusercontent.com/10986966/41658795-271ddeb4-74b5-11e8-95b0-edbbd6a9f7d3.gif)

**Comment by NipunaMarcus** [comment]
I don't think this is necessary. Because user can always undo or redo stuff as this is an IDE. It's a normal thing in a IDE to delete stuff and undo the delete. it is annoying to get a confirmation every time we delete something. WDYT?

**Comment by pahans** [comment]
Agree with @NipunaMarcus. We don't need ask for delete confirmation since undo option is available.
