### ISSUE TITLE
Error is printed to browser console when adding definition blocks in composer diagram 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#9177]
**Description:**
Error is printed to browser console when adding a definition blocks in composer using diagram 
```
Invalid value for package org:  undefined
  .
  .
  setOrg @ package.js:134

```

**Steps to reproduce:**
1. Add a main function using diagram view.

**Comment by NatashaWso2** [comment]
This issue is not reproducible in ballerina 0.981.2-SNAPSHOT so closing this issue.
