### ISSUE TITLE
No code completion for a record from a package

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#9178]
**Description:**

**Steps to reproduce:**
This is my sample code. I am expecting to see the fields when I type "st. " at the end of the code but I am not.

```
import ballerina/http;
import wso2/twitter;
import ballerina/config;

endpoint twitter:Client tw {
   clientId: config:getAsString("clientId"),
   clientSecret: config:getAsString("clientSecret"),
   accessToken: config:getAsString("accessToken"),
   accessTokenSecret: config:getAsString("accessTokenSecret"),
   clientConfig: {}   
};

endpoint http:Listener listener {
    port: 9090
};

@http:ServiceConfig {
    basePath: "/"
}
service<http:Service> hello bind listener {

    @http:ResourceConfig {
        path: "/",
        methods: ["POST"]
    }
    hi (endpoint caller, http:Request request) {
        string payload = check request.getTextPayload();
        twitter:Status st = check tw->tweet(payload);
        _ = caller->respond("Tweeted: "+ st.text +"\n");
    }
}
```

**Affected Versions:**
0.975

**OS, DB, other environment details and versions:**
Mac OS, latest VS Code

**Related Issues (optional):**

**Suggested Labels (optional):**
Category/Language Server

**Suggested Assignees (optional):**
Joseph

**Comment by nadeeshaan** [comment]
@DSotnikov we did a completion strategy revamp and after those changes, we can see the completions for the particular use-case. I'm using the latest twitter release available and the latest master build. Hence closing the issue and please reopn if the issue exists further.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1329674/41832271-eff52872-7868-11e8-9640-01927b653c71.gif)
