### ISSUE TITLE
Code completion fails for @kubernetes:Service annotation 

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#9179]
**Description:**
There is no code completion for @kubernetes:Service annotation (before endpoint)

**Steps to reproduce:**
See code sample: https://github.com/ballerina-guides/ballerina-demo/blob/master/5_demo_kubernetes.bal

**Affected Versions:**
0.975

**OS, DB, other environment details and versions:**
Mac OS, latest VS Code

**Related Issues (optional):**

**Suggested Labels (optional):**
Category/Language Server

**Suggested Assignees (optional):**
Joseph

**Comment by nadeeshaan** [comment]
Duplicate of #8932. Hence closing the issue
