### ISSUE TITLE
Improve binary expression type check logic

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#9256]
**Description:**
Consider the below example

```ballerina
int a = 23;
float f = 34;
float c = a + f;
```

Above binary expression's expected type is float, so in this example, expr in lhs (which is an int) has to be converted to float. Since int to float is a safe explicit conversion, currently the conversion expr is being added at **desuger** phase. But, ideally this check and adding required conversion expr should be done at type check level.

This is applicable to any binary expressions (ADD, SUB, BITAND, BITOR, BITXOR, etc) which the member expressions (lhs, rhs) needs explicit conversion expression added to them.

**Comment by hasithaa** [comment]
We have removed implicit conversion between numeric types and now conversion is explicit, which solves this problem.
