### ISSUE TITLE
Redundant brackets in boolean conditions

### ISSUE THREAD

**Issue by lahirus** [ballerina-platform/ballerina-lang#9268]
**Description:**
This is an improvement suggestion. I was developing an if statement for calculating age from date of birth.
```
 if ((time.month() < check <int>dataOfBirthValues[1]) || ((time.month() == check <int>dataOfBirthValues[1])
                && time.day() < check <int>dataOfBirthValues[0])) {
}
```
Above if condition has several brackets that might be unnecessary. Something like following would be more simple,
```
 if (time.month() < check <int>dataOfBirthValues[1] || (time.month() == check <int>dataOfBirthValues[1]
                && time.day() < check <int>dataOfBirthValues[0]) {
}
```
**Affected Versions:**
0.975.0

**Comment by Kishanthan** [comment]
The simplified version of the if condition expression also should work. I just checked with the latest grammar. Whats is the issue/error that you are facing? Associativity or Ordering?

**Comment by Kishanthan** [comment]
Closing this as this is not an issue and the precedence ordering is according to what is mentioned in the specification. The simplified if condition without any additional parenthesis also will work as expected.
