### ISSUE TITLE
support for JMS request/reply

### ISSUE THREAD

**Issue by JensWalter** [ballerina-platform/ballerina-lang#9270]
**Description:**
There is currently no way to implement JMS Request/Reply through ballerina. To make this possible I would recommend implementing a QueueRequestor (maybe TopicRequestor too), to handle this kind of task.

Sadly the JMS QueueRequestor class is not quite usable, since it does not implement a timeout for the call. To support timeouts, the implementation needs to contruct and handle the JMS resources manually.
sample java code:
```
QueueSession session = connection.createSession();
Queue reqQueue = session.createQueue(queueName);
QueueSender sender = session.createSender(reqQueue);
Queue replyQ = session.createTemporaryQueue();
MessageConsumer replyConsumer = session.createConsumer(replyQ);
TextMessage message = session.createTextMessage();
message.setJMSReplyTo(replyQ);
message.setText(msg);
sender.send(message);
Message replyMsg = replyConsumer.receive(RESPONSETIMEOUT);
```

I would see something like the following syntax to simplify the procedure in ballerina:
```
endpoint jms:QueueRequestor queueRequestor {
    session:jmsSession,
    queueName:"MyQueue",
    requestTimeout: 5000
};
function main(string... args) {
    match (jmsSession.createTextMessage("Hello from Ballerina")) {
        error e => {
            log:printError("Error occurred while creating message", err=e);
        }
        jms:Message msg => {
            var response = queueRequestor->request(msg);
            match (response) {
                jms:Message msg => {
                    log:printInfo("success");
                } 
                error err => {
                    log:printInfo("Error occurred while sending message");
                } 
            }
        }
    }
}
```

**Affected Versions:**
0.975.0

**Suggested Labels (optional):**
component/stdlib/jms, Type/New Feature

**Suggested Assignees (optional):**
I would start working on this.

**Comment by riyafa** [comment]
@JensWalter Thank you for the suggestion on implementing a Queue and Topic requester in Ballerina. We have this [issue](https://github.com/ballerina-platform/ballerina-lang/issues/8110) still in the Ballerina JMS implementation. We need to come up with a proper design to implement `Replyto` Header support in JMS endpoint. Once this has been implemented the usecase of `QueueRequester` and `TopicRequester` that you have suggested can be implemented in pure Ballerina code without using java. We welcome your suggestions on a proper design to implement the `Replyto` header in Ballerina. We are planning at the moment to use the object structural similarity concept to implement this.

**Comment by JensWalter** [comment]
Given the endpoint does support setting a `ReplyTo` header, how would you approach the issue that the send method sometimes returns `(?error)` and sometimes `(Message|error)`. Wouldn't this be more confusing to a developer?

I think the changing function signature is one of the major reasons for going for a separate implementation path.
Although that requirement could also be fulfilled by implementing a seconds function on the QueueSender.

**Comment by JensWalter** [comment]
I took a step back and looked at the actual language definition and compared how the JMS enpoint works in comparison to other endpoint definitions. The issue here is, that I only discovered more inconsistencies of how JMS is implemeted (and I agree that it will be important to get this right).

from the language spec:
"Client endpoints represent external systems that one or more of the workers interacts with.
...
An action represents a single capability or functionality that is offered to its consumers by an endpoint. An action may or may not provide a response to the caller directly in response to the request."

for http:
```
endpoint http:Client clientEndpoint {
    url: "https://postman-echo.com"
}; 

```
-> represents the server to interact with
```
var response = clientEndpoint->get("/get?test=123");
```
-> action defines the resource (URI) and the interaction model (GET)

for jdbc:
```
endpoint jdbc:Client testDB {
    url: "jdbc:mysql://localhost:3306/testdb", ...
};
```
-> represents the server to interact with
```
ret = testDB->update("INSERT INTO student(age, name) values
                          (23, 'john')");
```
-> action defines the resource (table) and the inteaction model (insert)

for JMS:
```
jms:Connection jmsConnection = new({
    initialContextFactory:"bmbInitialContextFactory",
    providerUrl:"amqp://admin:admin@carbon/carbon?"
                + "brokerlist='tcp://localhost:5672'"
});
```
-> a resource defines the server to interact with
```
jms:Session jmsSession = new(jmsConnection, {
    acknowledgementMode:"AUTO_ACKNOWLEDGE"
});
```
-> another resource defines part of the interaction model
```
endpoint jms:QueueSender queueSender {
    session:jmsSession,
    queueName:"MyQueue"
};
```
-> the endpoint defines the resource to interact with (queue)
```
queueSender->send(msg)
```
-> action has nothing left to declare and it is just forcing the exeution

So to bring JMS up to par with the other endpoint definitions JMS should look like this:
```
endpoint:JMS testJMS {
    initialContextFactory:"bmbInitialContextFactory",
    providerUrl:"amqp://admin:admin@carbon/carbon?"
                + "brokerlist='tcp://localhost:5672'"
}
```
actions:
```
testJMS->send(string Queue, Message msg, additionalParams? params);
testJMS->request(string Queue, Message msg, additionalParams? params) returns Message
```
with additionalParams should consist of something like:
timeout?
deliverymode?
...

**Comment by riyafa** [comment]
The reason that there is a separate connection and session concept in JMS is to allow re usability. By this it is possible to create one connection and use it to create multiple sessions. Then the sessions can be used to send to multiple destinations.  We already have a simplified version of the QueueSender as you have suggested namely [SimpleQueueSender](https://ballerina.io/learn/api-docs/ballerina/jms.html#SimpleQueueSenderEndpointConfiguration) which creates a session and connection for you internally without you having to do it on your own.
Like you said according to the spec there should be another `send` method where one can specify the queue name or more useful way would be to take a `Queue` object in this send method like below:
`queueSender->sendTo(Queue queue, Message msg, additionalParams? params);`
In this case if the `queueSender` already has a queue specified the method should throw and error. We need to address this also.

Your suggestions are most welcome and let us know if you think this could be further improved in any other ways. As you have mentioned we need to address the missing `QueueRequester` and `TopicRequester` functionalities after the `replyTo` header support has been provided.

**Comment by a5anka** [comment]
Adding to what @riyafa  mentioned, we were planning to introduce a new Object type called Queue and Topic which are structurally equivalent to Destination type similar to JMS API. These constructs can be used to implement the replyTo and temporary queue/topic support.

**Comment by JensWalter** [comment]
To be honest, I cannot agree with those statements. 
Reusing one connection for mutliple sessions is fine. But I see no reasing why a concept like this needs to be exposed to a ballerina developer. A JMS Session has no functional value when you want to implement a message producer.

Even the JMS2 acknowledged this, by introducing a JMSContext object.
"JMSContext replaces the separate Connection and Session objects in the classic API with a single object."
http://www.oracle.com/technetwork/articles/java/jms20-1947669.html

The SimpleQueueSender is a step in the right direction, since it simplifies the interaction model. But it comes at a high cost. I need a "simple something" for every interaction model (queue send, queue request, topic publish, topic request), not even mentioning the receiving part (that would be at least another 4 implementations). So "simple" will become quite complex and hard to differentiate.

As for the sendTo-function, I would really try to avoid that a developer can specify the destination through the endpoint and action invocation. In general, I would go for setting the destination on a action level, since it changes through implementation (like the http endpoint).

@a5anke
What would be the reason to bring a Queue/Topic object into the ballerina space. I know it is neccessary for the Java implementation, but since those destinations have no functional purpose, what would this object do?

Coming from the simpliest case of an jms send implementation:
```
JMSContext ctx = connectionFactory.createContext();;
ctx.createProducer().send(ctx.createQueue("queue.a"), "sample payload");
```
The destination is defined by 2 properties, name ("queue.a") and type (queue).
So if I would run this in ballerina, I already have the type of the destination, since I have to construct a QueueSender. That leaves me with the name of the destination which is always a string. So having a destination typed object brings no added value to the implementation.

What I'm experimenting with right now is kind of different implementation structure.
I try to expose the JMS connection as endpoint and build the interaction model as explicit calls on top.
This would look something like this:
```
//endpoint definition
endpoint jms:Client client{... jms connection attributes including optional topic 
                                              and queue connection factory ..}
//jms message definition
public type Message object{
	public string messageId;
	public string correlationId;
	public map properties;
	...
	private string destination; //cannot be set from the outside
	private string? replyTo; //cannot be set from the outside
	...
}
//endpoint usage
client->sendToQueue("A.queue.send", msg);
response = client->requestFromQueue("A.queue.request", msg);

client->publishToTopic("A.topic.publish",msg);
response=client->requestFromTopic("A.topic.request",msg);
```

Sadly I cannot get this running, due to a lot of refactoring happening in the master branch right now.


What I didn't look at so far is, how the endpoint (since it is the connection) can be reused for receiving messages. For the receiving part, the session becomes functional, since it is responsible for rollback/acknowledgement and recovery.

So the receiving part needs to have access to the session.

PS: I know that the JMS message also has the acknowledge/rollback functions, but these are misleading since the JMS spec requires the session to roll back in case somebody triggers a msg.rollback(). But it is a tradoff worth considering, because it is easier to understand.

**Comment by a5anka** [comment]
Hi @JensWalter,

I will explain the thinking behind current implementation and answer your questions.

We wanted to implement the Ballerina JMS API very similar to the JAVA API to make the Ballerina API as powerful as the JAVA API. The advantage of being close to JAVA API is that we can have a set of "dumb" native functions and implement the wrapper classes in Ballerina depending on the requirement. On the other hand, if we wrap the connections and sessions in Ballerina native method implementations we will have to implement another set of native methods to support advanced JMS use cases. Therefore we chose to implement the Ballerina JMS API very close to JAVA API and write wrapper classes like SimpleQueueSender completely in Ballerina using the Ballerina JMS API.

Regarding the session Object type, there are few functional values we get out of having a separate session object. I agree that for trivial use-cases having a session object does not add any value. For example, a JMS session can be used to create a single transaction that combines work spanning its producers and consumers into atomic units. i.e. if a user wants to include multiple producers in the same transaction he can use the same session to do that. This will work even with the JMS providers which do not support distributed transactions. If we create a session for each producer we can never get this scenario working with a JMS provider that does not support distributed transactions.

### sendTo method implementation

Regarding the sendTo function, I also agree that we should be able to specify the destination dynamically in the method call. But if we can specify the destination either in sendTo method or endpoint, I don't see why we should avoid implementing both. 

### Destination Object type

When you call the getReplyTo method in a message, you could get either a topic destination or a queue destination. If we just return a string from getReplyTo method, there is no way to know whether the reply to destination is a queue or a topic. Therefore we need some way to capture the queue/topic
type information. One way to do this is by introducing an object type called Destination with the queue/topic type information. We might not need a Queue/Topic object types when we have a destination object as you have mentioned. 

Some sample code will look like below. Please note that this is just theoritcal code and will not work with current API since we have not implemented the replyTo support. 

```ballerina

import ballerina/jms;

jms:Connection jmsConnection = new ({   
        initialContext: "wso2mbInitialContextFactory",
        providerUrl: "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"
});

jms:Session jmsSession = new (conn, {
    acknowledgementMode: "AUTO_ACKNOWLEDGE"        // optional
};

endpoint jms:QueueReceiver consumer {
      session: jmsSession,
    queueName: "MyQueue"                        // optional
}

endpoint jms:Sender jmsProducer {
    session: jmsSession;
}
service<jms:Consumer> jmsListener bind consumer {
    onMessage (endpoint consumer, jms:Message message) {
           jms:Destination destination = message.getReplyTo(); 
           jms:Message m = jmsSession.createTextMessage("Response text");
           jmsProducer -> sendTo(destination, m);
    }
}
```

On a final note, I do not think the JMS API should work exactly same as the HTTP API. I agree that we need to be as close as possible to be consistent. But we should not sacrifice functionality when trying to
be close to HTTP API. We should take the domain-specific requirements and have a very thin native method implementation to allow the maximum flexibility when designing the JMS API. We can always have more Ballerina code to hide the complexity when required.

### References

1. https://docs.oracle.com/javaee/7/api/javax/jms/Session.html

**Comment by a5anka** [comment]
@JensWalter Is it possible to write the API you propose just using the Ballerina JMS API (i.e. without implementing any native methods)? 

I think this is a good use case to identify and fix the limitations we have in the current API.

**Comment by JensWalter** [comment]
I think so. At least with the annotation support available in ballerina (so far I couldn't get any annotations running and there is no non-java annotation support yet). But in the end, I'm also using just the JMS primitives available through the API.
For going forward on this issue, we need to bring at least a minimal set of JMS API to ballerina (mentioned in the TODOs above) and then later take care of the abstraction on top.

**Comment by JensWalter** [comment]
Hi @a5anka ,

I started implementing this and found something maybe inconvenient I wanted to bring up.
In the above sample, you mentioned a `sendTo `funtion to explicitly set the destination.
Since we already have `Destination` as ballerina object, we could also use this, to take advantage of the `Message.setDestination()` from the JMS API. This would propably more consistent then to overload the function and enable `Destination` and `String` support.
In code it would look something like this.
```
//receiver
service<jms:Consumer> jmsListener bind consumer {
    onMessage (endpoint consumer, jms:Message message) {
           jms:Destination destination = message.getReplyTo(); 
           jms:Message m = jmsSession.createTextMessage("Response text");
           m -> setDestination(destination);
           jmsProducer -> send(m);
    }
}
//sending
function main(string ... args) {
    jms:Destination replyDest = jmsSession.createTemporaryQueue();
    jms:Destination requestDest = jmsSession.createQueue("q.a");
    jms:Message m = jmsSession.createTextMessage("test request");
    m->setDestination(requestDest);
    m->setReplyTo(replyDest);
    jmsProducer -> send(m);
    var replyMsg = consumer->receive(replyDest, timeout=5000);
}
```
The default rule for the MessageProducer still applies, if a destination is set on the endpoint level it is the default, but can be overwritten at the message level.
