### ISSUE TITLE
Support for logs with formated string

### ISSUE THREAD

**Issue by malinthaprasan** [ballerina-platform/ballerina-lang#9285]
**Description:**
Currently, we can add ballerina log parameters using simple string format. But most of the time, we need to log strings with parameters. Typically we use string concatenation in these cases.

For instance, usually there will be lots of debug level logs but none of them will be printed in the console as the level is higher than debug. But if we use string concatenation as the logging string, the concatenation will anyway happen before checking the log level which can lead to a performance issue.

It would be really useful if log: package can provide formatted strings like slf4j does [1]

eg:
```
log:prinfDebug("Name of the city is {}", city);
```

[1] https://www.slf4j.org/faq.html#logging_performance

**Affected Versions:**
0.975

**Comment by daneshk** [comment]
We can achieve the same behavior with the following options,
Option 01: using string template expressions 
```ballerina
string x = "apple";
log:printDebug(string `Names of the fruits are ${x}, ${"orange"}.`);
```
Option 02: using `io:sprint` functions
```ballerina
string x = "apple";
log:printDebug(io:sprintf("Names of the fruits are %s, %s.", x, "orange"));
```
Hence closing this issue. Please check the discussion [1] for more information about this support.
1. https://groups.google.com/forum/#!topic/ballerina-dev/ivZoGMVgvDA
