### ISSUE TITLE
Adding elements to JSON array results in NPE

### ISSUE THREAD

**Issue by lahirus** [ballerina-platform/ballerina-lang#9291]
**Description:**
I'm trying a suggestion at SO Q.
https://stackoverflow.com/questions/51067068/how-to-enrich-json-array-in-ballerina

Running the B7a service with Idea plugin and got the error.

```
            json studentArray = [];

            foreach i, x in studentInfoXml.selectDescendants("student").elements(){

                json studentResponseJson = getStudentJson(x);
                studentArray[studentArray.count()] = studentResponseJson;
            }

```

> 
> [2018-06-28 11:21:08,249] ERROR {org.ballerinalang.launcher.Main} - null 
> java.lang.NullPointerException
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateFinallyInstructions(CodeGenerator.java:3096)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateFinallyInstructions(CodeGenerator.java:3091)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:533)
> 	at org.wso2.ballerinalang.compiler.tree.statements.BLangReturn.accept(BLangReturn.java:44)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1284)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:480)
> 	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1284)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:2524)
> 	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:53)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1284)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:480)
> 	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:54)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1284)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.processWorker(CodeGenerator.java:1513)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visitInvokableNode(CodeGenerator.java:1458)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:468)
> 	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:66)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1284)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.lambda$visit$162(CodeGenerator.java:429)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:429)
> 	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:150)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1284)
> 	at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generateBALO(CodeGenerator.java:344)
> 	at org.wso2.ballerinalang.compiler.CompilerDriver.codegen(CompilerDriver.java:200)
> 	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:172)
> 	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:139)
> 	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:106)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:139)
> 	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:155)
> 	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:79)
> 	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:257)
> 	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:93)
> 	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at org.ballerinalang.launcher.Main.main(Main.java:66)
>  
> 

**Affected Versions:**

B7a 0.975.0.
Idea plugin 0.974.0
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by JensWalter** [comment]
Just fyi, as the one who posted the answer on stackoverflow, I tried it with the current SNAPSHOT build (0.976.1-SNAPSHOT) and that one worked without issues.

here the code snipped I tested it with:
```
import ballerina/io;

function main(string... args){
    json j1 = {"studentId":1};
    json result = [];
    foreach i in 1 ... 3 {
         result[result.count()] = j1;
    }
    io:println(result);
}
```

**Comment by lahirus** [comment]
Ok. Thanks @JensWalter . I just tested and it works in a main function. Error seems to be only occurring when I use it in a service.

**Comment by SupunS** [comment]
This looks like an issue in the `count()` function. Below two lines inside a resource causes the same issue:
```ballerina
string[] strArray = ["foo", "bar"];
int size = strArray.count();
```
