### ISSUE TITLE
toml config parameter with "#" in the value throws error

### ISSUE THREAD

**Issue by jpvadell** [ballerina-platform/ballerina-lang#9292]
At config file, If I have a parameter value with # in it, I receive this error:

', ' 9:0 extraneous input 'd' expecting {<EOF>, '       ', '
', '
', ' '}

param = "Demo#123"

If I change the # for other character, works.

param = "Demo@123"

**Comment by pubudu91** [comment]
This issue is already reported in #7668. The issue is with the grammar, which currently seem to consider # as the start of a comment, even when it's used within quotes. We might have to revisit the TOML grammar to address this issue.

**Comment by NatashaWso2** [comment]
This seems to be an issue with the toml grammar. We have tracked the issue with [#9778](https://github.com/ballerina-platform/ballerina-lang/issues/9778)

**Comment by Manuri** [comment]
Closing this since the issue is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/9778
