### ISSUE TITLE
Running test while having a directory without permission result in Bad, Sad.

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-lang#9303]
**Description:**
If you have a program directory containing a directory without permission for the given user, if the user runs ballerina test command it will give a bad sad error. See the directory structure and the error response below.

```
.
├── ballerina-internal.log
├── hello_service.bal
├── org.sample
│   ├── mysample.bal
│   └── without_permission [dir without permission]
└── tests
    └── hello_service_test.bal
```
When we run `ballerina test` it will give the following error. 

```
---------------------------------------------------------------------------
    T E S T S
---------------------------------------------------------------------------
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

**Affected Versions:**
0.975.0

**OS, DB, other environment details and versions:**
Ubuntu, Linux

PS. marking this as priority high since this issue affects composer rendering when there are directories without permission in the program path. 
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2149735/ballerina-internal.log)

**Comment by Dilhasha** [comment]
FYI:

When there is a test.bal file inside the tests directory without permission, following error is thrown. But, for directories without permission above access denied exception is thrown.

> ballerina test test_module

Compiling source
        dilhasha/test_module:0.1.0
error: error reading source file /home/dilhasha/Documents/ipaas-test/ballerinatest/src/test_module/tests/main_test2.bal
