### ISSUE TITLE
Setup Test environment for Installers

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#9307]
**Description:**
Ballerina distributions are mainly available as installers (.msi for windows, .deb for ubuntu, .pkg for macos and .rpm for centos).  

Our integration tests run only against .zip file. This needs to be further enhanced to do the installation in each OS by installers and run tests by against that. 

We can do this step once installer has been generated in each node.

**Comment by hevayo** [comment]
Sprint 8 plan 
- All the test cases
- Windows installer support

**Comment by keizer619** [comment]
Automation has been done for installers in following PR
ballerina-platform/ballerina-release#12

Hence closing this issue and open other issues for remaining sub tasks
