### ISSUE TITLE
build fails in unit test because of logger incompatibility

### ISSUE THREAD

**Issue by pmhofman** [ballerina-platform/ballerina-lang#9308]
**Description:**
During unit tests in the build, the build fails with the following error message:
```
[ERROR] There was an error in the forked process
[ERROR] java.util.logging.LogManager incompatible with org.ballerinalang.logging.BLogManager
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] java.util.logging.LogManager incompatible with org.ballerinalang.logging.BLogManager
```
I suggest specification of the compatible Java SDK/runtime versions in the documentation.

If ballerina is also supposed to work with IBM java (`/usr/lib/jvm/java-1.8.0-ibm-1.8.0.5.10-1jpp.1.el7.x86_64`), then a fix might be required.

Started another build with Oracle java `/usr/lib/jvm/java-1.8.0-oracle-1.8.0.151-1jpp.5.el7.x86_64`, which does work, so I switched to that one.

**Steps to reproduce:**
- checkout latest master
- mvn clean install

**Work around**
use `/usr/lib/jvm/java-1.8.0-oracle-1.8.0.151-1jpp.5.el7.x86_64` instead of `/usr/lib/jvm/java-1.8.0-ibm-1.8.0.5.10-1jpp.1.el7.x86_64`

**Affected Versions:**
0.976.1

**OS, DB, other environment details and versions:**
RHEL7
`/usr/lib/jvm/java-1.8.0-ibm-1.8.0.5.10-1jpp.1.el7.x86_64`

running build behind corporate proxy (see issue #9151 )

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
We make use of Java util logging as the logging backend and have extended the `java.util.logging.LogManager` since we needed do some logging configurations of our own. Will test with the IBM JDK and see what's going on there.

**Comment by pubudu91** [comment]
Did some testing with IBM JDK 8 and apart from the instance mentioned here, it also fails when building the bouncy castle module as well. So at least for now, let's just explicitly state the JDKs we support. Sent PR #9629 to add this info to the README.

**Comment by Kishanthan** [comment]
Closing as documentation is updated. Created #9857 separately to track supporting IBM JDK 8.
