### ISSUE TITLE
Increment/Decrement postfix/prefix cannot used within in array 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#9347]
**Description:**
We cannot use increment postfix/prefix as the index for an array. 

Eg: intArray[index++] = 1;
Above is not valid. 

**Steps to reproduce:**
```ballerina
int [] intArray = [];

function main(string... args) {
    int index = 0;

    intArray[index] = 0;
    intArray[index++] = 1;
}
```

**Above code segment provides below errors.** 
```ballerina
error: ./TestBallerina.bal:7:19: invalid token '++'
error: ./TestBallerina.bal:7:21: mismatched input ']'. expecting ';'
compilation contains errors
```

**Affected Versions:**
0.975.0

**Suggested Assignees (optional):**
@hasithaa @SupunS

**Comment by hasithaa** [comment]
@mohanvive 
By design, Postfix arithmetic operations are statements. You can't use those as expressions.

**Comment by hasithaa** [comment]
It is a design decision we made. Please refer mail. https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/L2vRwTCrHOk/rk-sCJEBBQAJ

**Comment by mohanvive** [comment]
Thanks, @hasithaa for the reference.
