### ISSUE TITLE
Endpoint initialization order depends on file name

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#9350]
**Description:**
I have two files in a ballerina project in a package with composite Listener endpoints. 
```
.
├── Ballerina.toml
└── student_app
    ├── my_app.bal
    └── sql_svc.bal
```
1. sql_svc.bal
```ballerina
import ballerinax/composite;
import ballerina/io;

endpoint composite:Listener mysql_ep {
    port: 3306,
    host: "mysql-svc"
};

@composite:ContainerConfig {
    name: "mysql-endpoint",
    labels: { "region": "SL" },
    replicas: 1,
    enableLiveness: true,
    livenessPort: 3306,
    image: "ballerina_mysql:1.0.0",
    env: { "MYSQL_ROOT_PASSWORD": "root" }
}
service<composite:Container> MySQL_Service bind mysql_ep {}
```
2. my_app.bal
```ballerina
import ballerina/io;
import ballerina/jdbc;
import ballerinax/composite;
import ballerina/http;
import ballerinax/kubernetes;

endpoint jdbc:Client testDB {
    url: "jdbc:mysql://" + composite:getHost(mysql_ep) + ":" + composite:getPort(mysql_ep) + "/testdb",
    username: "root",
    password: "root",
    poolOptions: { maximumPoolSize: 5 },
    dbOptions: { useSSL: false }
};

@kubernetes:Service {
    serviceType: "NodePort"
}
endpoint http:Listener student_ep {
    port: 9090
};

@kubernetes:Deployment {
    singleYAML: true
}
@http:ServiceConfig {
    basePath: "/students"
}
service<http:Service> Student_APP bind student_ep {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/"
    }
    getStudent(endpoint outboundEP, http:Request request) {
        http:Response response = new;

        var selectRet = testDB->select("SELECT * FROM student", ());
        table dt;
        match selectRet {
            table tableReturned => dt = tableReturned;
            error e => io:println("Select data from student table failed: "
                    + e.message);
        }

        io:println("\nConvert the table into json");
        var jsonConversionRet = <json>dt;
        match jsonConversionRet {
            json jsonRes => {
                response.setJsonPayload(untaint jsonRes);
            }
            error e => {
                io:println("Error in table to json conversion");
                response.setTextPayload("Error in table to json conversion");
            }
        }
        _ = outboundEP->respond(response);

    }
}
```
The package compiles without errors. But, following error occurs while running the balx.
```
ballerina: initiating service(s) in 'student_app.balx'
error: ballerina/runtime:CallFailedException, message: call failed
	at anuruddha/student_app:0.0.0:anuruddha/student_app:0.0.0.<init>(my_app.bal:7)
caused by ballerina/runtime:NullReferenceException
	at ballerinax/composite:0.0.0:getHost(composite_listner.bal:110)
```
If we change the file name of the `my_app.bal` to `zmy_app.bal` everything works. Looks like the endpoints are initalized according to the alphabetical order of files, where it should be based on dependencies. 

**Steps to reproduce:**
1. Get a clone or download the source from this repository (https://github.com/anuruddhal/kubernetes/tree/composite).
2. Checkout to composite branch. `git checkout composite`
2. Run the Maven command ``mvn clean  install`` from the cloned directory.
3. Copy ``kubernetes/target/kubernetes-extension-<version>.jar`` file to ``<BALLERINA_HOME>/bre/lib`` directory.
4. Unzip ``kubernetes/target/kubernetes-extension-<version>-ballerina-binary-repo.zip`` file and copy `ballerinax` folder to ``<BALLERINA_HOME>/lib/repo`` directory.
5. Copy ``ballerinax-composite-<version>.jar`` file to ``<BALLERINA_HOME>/bre/lib`` directory.
6. Unzip ``composite/target/ballerinax-composite-<version>-ballerina-binary-repo.zip`` file and merge `ballerinax` folder to ``<BALLERINA_HOME>/lib/repo`` directory.
7. Build the project and run the resulting balx file.

**Affected Versions:**
0.976.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Mac OS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment]
@rdhananjaya this too should now work correctly with the global variable reordering changes right?

**Comment by rdhananjaya** [comment]
Yes this should work now as we have introduce dependency tracking into annotations.

**Comment by hasithaa** [comment]
We are resolving this issue as per the above comment.
