### ISSUE TITLE
Remove Compensation related instructions codes. 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#9371]
The current implementation of Compensation (https://github.com/ballerina-platform/ballerina-lang/pull/9222) has used 3 new instruction codes, But this logic can be de-sugared into lambda and function invocation.

**Comment by hasithaa** [comment]
Also, use memory based implementation, instead of using context.globalProps. Eg:.

https://github.com/ballerina-platform/ballerina-lang/pull/9222/files#diff-c735d95ed1b3a1ef6bfdfb80fed69154R70

**Comment by vinok88** [comment]
This compensation implementation has been already removed. Will be handled as part of the ballerina transactions.
