### ISSUE TITLE
[IntelliJ IDEA Plugin] Project Initialization

### ISSUE THREAD

**Issue by NGimhana** [ballerina-platform/ballerina-lang#9378]
**Description:**
When creating a new Ballerina Project, the typical **hello_service.bal** is not automatically initiated.

**Steps to reproduce:**
Reproduce the behaviour of **ballerina init -i** in Ballerina Plugin

**Affected Versions:**
0.975.0

**OS, DB, other environment details and versions:**
UBUNTU 16.04

**Comment by Shan1024** [comment]
Users can easily create a new file (with a main or a service) from the `File` menu. ballerina init command creates this sample service since there is no other way for users to to auto-generate a example service. Since closing the issue.
