### ISSUE TITLE
Field 'License' does not exist on type Repository

### ISSUE THREAD

**Issue by Thumimku** [ballerina-platform/ballerina-lang#9384]
**Description:**
While getting repository using github endpoint function _getRepository()_ and match the response with _github4:Repository repository_ below error occurs

_Field 'License' does not exist on type Repository_.

As said in the error message, there is no filed as License in Repository type.
[link](https://central.ballerina.io/wso2/github4)
**Steps to reproduce:**

**Affected Versions:**
0.975.0
**OS, DB, other environment details and versions:**
UBUNTU 16.04
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
@Thumimku Can you please report this issue in the repo for [wso2/github4](https://github.com/wso2-ballerina/package-github)?

Closing this since this is irrelevant to Ballerina itself.
