### ISSUE TITLE
[ dushaniw/gdrive3 ] Signature does not match with endpoint interface | Incompatible Types

### ISSUE THREAD

**Issue by NGimhana** [ballerina-platform/ballerina-lang#9400]
**Description:**
When trying to use **dushaniw/gdrive3** package, programs give below Issues and compilation failed eventually. 
- error: dushaniw/gdrive3:0.3.0/gdrive_endpoint.bal:37:26: **_redeclared symbol 'gDriveConfig'_**
- error: wso2/Ballerina:0.0.1/noti_sender_main.bal:34:1: **_invalid endpoint type_** **_dushaniw/gdrive3:0.3.0:Client, function 'init' signature does not match with endpoint interface_**
- error: dushaniw/gdrive3:0.3.0/gdrive_endpoint.bal:43:37: **_incompatible types: expected 'Basic|OAuth2|JWT', found 'string'_**
- error: wso2/Ballerina:0.0.1/noti_sender_main.bal:34:34: **_invalid literal for type 'other'_**

**Affected Versions:**
0.975.0

**OS, DB, other environment details and versions:**
UBUNTU 16.04

**Comment by nadeeshaan** [comment]
@NGimhana make sure the gDrive package is implemented with the same ballerina version you are using

**Comment by pubudu91** [comment]
Shouldn't this issue be reported to the repo of the package in question itself? Looking at the package in question, [dushaniw/gdrive3](https://central.ballerina.io/dushaniw/gdrive3), it hasn't been updated to support v0.975.0.

**Comment by pubudu91** [comment]
Closing this since this is irrelevant to Ballerina
