### ISSUE TITLE
Folders are not shown in a desired alphabetical order

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#9435]
**Description:**
In the composer when you open a project, the folders are not shown in a desired alphabetical order. Folder names starting in block letters are separated from that are not.

**Steps to reproduce:**
Open composer and try to open a project from the file menu.

**Affected Versions:**
0.970.1

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by Shan1024** [comment]
I believe the sort order is `A-Z`, `a-z`. So the directories which starts with `A` wont be listed with the directories which starts with `a`. This is the default behavior for most applications.

**Comment by nadeeshaan** [comment]
If we consider the native file explorer Directories starting with A and a comes together. I think, in order to maintain a similar experience we have to fix this

**Comment by hevayo** [comment]
Composer is discontinued hence closing the issue.
