### ISSUE TITLE
[Composer] Unnecessary package name in a file when creating a new file inside a folder

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/ballerina-lang#9437]
**Description:**
Inside a project folder, when you create a new file inside a sub folder, the file is created with a default template where is a package name on top. But as per the example I tried (quick tour), defining a package name on top is not needed and it throws an error if you try to define it.

**Steps to reproduce:**
Open a project folder in composer.
Create a new sub folder.
Create a new bal file inside that sub folder.
"package sub_folder_name" is displayed on top

**Affected Versions:**
Ballerina 0.970.1

**Comment by rasika** [comment]
Thanks for reporting this. The fix added in https://github.com/ballerina-platform/ballerina-lang/pull/9477
