### ISSUE TITLE
[IO] Return EoF as an Error

### ISSUE THREAD

**Issue by pamod** [ballerina-platform/ballerina-lang#9439]
**Description:**
Currently byte, character, record and data io apis return zero content upon receiving EoF. This would be applicable for reading/writing file content, since when reading files it's assured at-least 1 byte will be read if present.

However, the above case will not be applicable for TCP/socket channels. Sockets could return zero bytes depending on the state of the channel. 

Hence, it would be applicable to return an error when EoF is reached.

**Comment by wggihan** [comment]
The TCP socket design changed with v0.990.3 and with new design there is no usage of channels directly. So this task is now invalid, hence closing the issue.
