### ISSUE TITLE
[Composer] Ballerina Composer clashes with Composer, the PHP Dependency Manager

### ISSUE THREAD

**Issue by menuka94** [ballerina-platform/ballerina-lang#9442]
**Description:**
Unable to run Ballerina `composer` in a system where [PHP composer](https://getcomposer.org/) is already installed. IMO, the command will be better off as `ballerina composer`.

**Steps to reproduce:**
Install [Composer, the PHP Dependency manager](https://getcomposer.org/). Then install Ballerina and run `composer`

**Affected Versions:**
0.975.1

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Suggested Labels (optional):**
Improvement

**Comment by hevayo** [comment]
Agreed that composer is a somewhat common command so let's discuss on this for another name. 

For the time being, you can try renaming the composer script and run or give the exact location of the script.

**Comment by hevayo** [comment]
We will change the composer command to be a subcommand of the ballerina command. The new way to launch composer will be "ballerina compose". You can find the discussion here [1]

[1] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ballerina-dev/5UAcQnVaY-s/XPnJBVWjDAAJ

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
