### ISSUE TITLE
[Composer] Ballerina Composer is not working with IE

### ISSUE THREAD

**Issue by renuka-fernando** [ballerina-platform/ballerina-lang#9452]
**Description:**
Just loading page with IE for composer.
![image](https://user-images.githubusercontent.com/23183042/42355123-fe7054fc-80e8-11e8-9b92-cc077a98681c.png)

**Steps to reproduce:**
Run composer with `composer` command.
Copy the url and paste it in IE address bar. (since it is not my default browser).
Worked successfully with Google Chrome (67.0), Microsoft Edge(40).

**Affected Versions:**
Ballerina 0.975.1

**OS, DB, other environment details and versions:**
IE11.0.15063.0, Windows 10

**Comment by hevayo** [comment]
As of now we do not have any plans in supporting IE please find the compatible browsers here https://github.com/ballerina-platform/ballerina-lang/tree/master/composer. Thanks
