### ISSUE TITLE
'string ' to 'int' conversion results in a 'int|error' type

### ISSUE THREAD

**Issue by SaranganJ** [ballerina-platform/ballerina-lang#9463]
**Description:**

var intResult = <int>strVal;
It returns a 'int|error' type. Not an 'int' type .As it is returning 'int|error' type ,we are unable to perform any integer operations

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Converting a string to int is an unsafe conversion. Hence it returns a union type of int and error('int|error'). Meaning your 'intResult' variable can be either an int or an error. To evaluate the int value you should use a 'match' where you have to handle both int and error cases.

```ballerina
    var intResult = <int>strVal;
    match intResult {
        int value => io:println(value);
        error err => io:println("error: " + err.message);
    }
```

Refer: https://ballerina.io/learn/by-example/type-conversion.html

**Comment by SaranganJ** [comment]
Yh! I handled that 'match' too .But still  it outputs the same error.
![screenshot from 2018-07-06 14-19-53](https://user-images.githubusercontent.com/25496010/42369520-d8422d02-8127-11e8-995f-6e485d06184a.png)

**Comment by hemikak** [comment]
Within the match statement you can see the variable "val". That has the casted integer value. "intResult" does not have the value of the casted integer. "intResult" is an union type.

Here are your options

Option 1 (Handle both int and error cases - https://ballerina.io/learn/by-example/match.html) : 
```ballerina
var intResult = <int>strVal;
match intResult {
    int val => {
        int l = val;
        time:Time time1 = time:currentTime();
        int sec = time1.second();
        //.....(rest of the code)
    }
    error err => {
        io:println("error: " + err.message);
    }
}
```

Option 2 (If an error occurs, use a default value - https://ballerina.io/learn/by-example/match-expression.html): 
```ballerina
int val = <int>strVal but { error e => -1 };
```

Option3 (Ignore the error completely. This is ideal on situations where you are so sure that an error would not occur - https://ballerina.io/learn/by-example/check.html)
```ballerina
int val = check <int>strVal;
```

**Comment by SaranganJ** [comment]
Sorted out.Thanks for the response
