### ISSUE TITLE
Cannot go back to design view from swagger view after editing the swagger

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#9474]
**Description:**
When you try to edit in the swagger view and go back to the design view, will not go back or prompt an error. Instead stays in the swagger view.

**Steps to reproduce:**
1. Go to design view
2. Add a service definition
3. Switch to the swagger view and edit the basePath
3. Try go back to design view clicking on the back button

**Affected Versions:**
v0.976.1-SNAPSHOT

**Comment by hevayo** [comment]
Fixed with #9448
