### ISSUE TITLE
Cannot push to Ballerina Central

### ISSUE THREAD

**Issue by kasvith** [ballerina-platform/ballerina-lang#9475]
**Description:**
After following the community program listed in [here](https://ballerina.io/community-program/) I encountered a situation where i cannot push this to the central.

- Project Structure
![image](https://user-images.githubusercontent.com/13379595/42378094-a5abdf7a-8143-11e8-969a-8327727b4194.png)

- Package.md
![image](https://user-images.githubusercontent.com/13379595/42379150-84c1b6b4-8147-11e8-977f-7439666a12fa.png)

- Ballerina.toml
![image](https://user-images.githubusercontent.com/13379595/42379178-96eea0f4-8147-11e8-9289-3ae1c391a253.png)

- Settings.toml in <USER_HOME>/.ballerina
![image](https://user-images.githubusercontent.com/13379595/42379257-c54b7a26-8147-11e8-9611-2dc0fcc3cce8.png)

- Error message from bellerina
![image](https://user-images.githubusercontent.com/13379595/42378107-b7becb1e-8143-11e8-936e-2859914aad4f.png)

> Note: Package building successfully and working fine in the machine. Steps are followed in exact way as community program

**Steps to reproduce:**
- Follow the steps in the Community Program
- In the publishing stage you will get the error `ballerina: summary of the package exceeds 50 characters` when followed it exactly. I ve not set anything beside the Package.md description as in the community program

**Affected Versions:**
Ballerina 0.975.1

**OS, DB, other environment details and versions:**
- Windows 10 Education version 1803 (build 17134.112)
- used [Cmder](http://cmder.net/) as console emulator on windows (v180206)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NatashaWso2** [comment]
This is a duplicate issue of https://github.com/ballerina-platform/ballerina-www/issues/971, hence closing this issue

**Comment by kasvith** [comment]
thank you !.
