### ISSUE TITLE
Ballerina Composer cannot be opened

### ISSUE THREAD

**Issue by HishanIndrajith** [ballerina-platform/ballerina-lang#9497]
**Description:**
Ballerina Composer cannot be opened. When command composer is given, the output is 'Error: Could not find or load main class org.ballerinalang.composer.server.launcher.ServerLauncher'

**Steps to reproduce:**
I used windows command prompt as the terminal emulator.
**Affected Versions:**
Ballerina 0.975.1
**OS, DB, other environment details and versions:**
Windows 10 Education
**Related Issues (optional):**

**Suggested Labels (optional):**
Composer,Bug

**Suggested Assignees (optional):**

**Comment by HishanIndrajith** [comment]
I could resolve the issue by replacing

FOR %%C in ("%BALLERINA_HOME%\lib\resources\composer\services\*.jar") DO set BALLERINA_CLASSPATH=!BALLERINA_CLASSPATH!;".\lib\resources\composer\services\%%~nC%%~xC"
with
FOR %%C in ("%BALLERINA_HOME%\lib\resources\composer\services\*.jar") DO set BALLERINA_CLASSPATH=!BALLERINA_CLASSPATH!;"%BALLERINA_HOME%\lib\resources\composer\services\%%~nC%%~xC"

**Comment by yohanym95** [comment]
then what is a command to command line for run composer.

**Comment by nadeeshaan** [comment]
@yohanym95 just run the composer.bat script from command line. This particular class loading issue has been fixed in the latest distributions

**Comment by yohanym95** [comment]
i use 0.970.1 ballerina  version and i run the composer.bat in command line but can't open to composer.

![capture](https://user-images.githubusercontent.com/31344335/42421237-e72eb8fc-82ef-11e8-8bd0-95ace4f6512b.JPG)
