### ISSUE TITLE
Unexpected behaviour in multi-lined string template literal 

### ISSUE THREAD

**Issue by irunika** [ballerina-platform/ballerina-lang#9504]
**Description:**
There is an unexpected behaviour when running multi-lined string template literal in the code.

**Steps to reproduce:**
Run the following code
```ballerina
import ballerina/io;

function main (string... args) {
    string name = "John";
    int age = 30;
    string msg1 = "Hi " + name + "with age " + age 
                    + " successfully connected to the chat";

    string msg2 = string `Hi {{name}} with age {{age}} 
                    successfully connectedd to the chat`;

    io:println("msg1: " + msg1);
    io:println("msg2: " + msg2);
}
```
output looks like
```
msg1: Hi Johnwith age 30 successfully connected to the chat
msg2: Hi John with age 30 
                    successfully connectedd to the chat
```
I guess both `msg1` and `msg2` should give the same behavior. But `msg2` prints some stuff in a new line with the same stuff that have been put in a new line in the code. Because of this string template literals cannot be used when it is needed in multi-line
 
**Affected Versions:**
Ballerina 0.976.1-SNAPSHOT

**Comment by Shan1024** [comment]
@irunika - This is the expected behavior of string templates. Whatever characters we include between **``** characters are printed as it is without any changes after replacing variables.
