### ISSUE TITLE
Composer electron app creates two folders in windows AppData folder

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#9524]
**Description:**
The ballerina composer electron application creates two different folders named **Ballerina Composer** and **ballerina-composer** in the following path.

_C:\Users\<User>\AppData\Roaming_

**OS, DB, other environment details and versions:**
Windows 10 Pro
Version 1803
OS Build 17134.112

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina

**Comment by kaviththiranga** [comment]
@jshrek thanks for the provided solution. 
Just FYI, We are no longer maintaining Composer Electron distribution.
