### ISSUE TITLE
Secured Service with Basic Authentication executed in different manner - ballerina 0.970.1.deb and 0.975.1.deb version

### ISSUE THREAD

**Issue by KasunAratthanage** [ballerina-platform/ballerina-lang#9547]
**Description:**

Secured Service Basic Authentication executed in different manner on ballerina-platform-Linux-installer -x64-0.970.1.deb version and the ballerina-platform-Linux-installer -x64-0.975.1.deb version.

**Steps to reproduce:**

Please find the below Test1 & Test2.
Implemented Scenario : Ballerina Secured REST Service with Basic Authentication

**Test 1**
Installed ballerina-platform-Linux-installer -x64-0.970.1.deb version.

 _**Service Level - Configurations**_

@http:ServiceConfig {
    basePath: "/banktest",
    authConfig: {
        authentication: { enabled: true },
        scopes: ["scope1"]
    }
}

 **_Resource Level - Configurations_**
 
@http:ResourceConfig {
    methods: ["GET"],
    path: "/account/{accountId}",
    authConfig: {
        scopes: ["scope2","scope1"]
    }
}

**_Please note : accountId  = ACC001 (" accountId " is a unique ID of this implementation)_**

**_Username and Password defined in ".toml" file._**

 ["b7a.users"]

      ["b7a.users.admin"]
      password="pass1"
      scopes="scope1,scope2"

      ["b7a.users.user"]
      password="pass2"
      scopes="scope1"

**_Invoke the service using cURL command._**
curl -vk -u admin:pass1 https://localhost:9090/banktest/account/ACC001

**Actual Output**  

Inputs | Results
-- | --
Valid user name and password | Authentication successful
Invalid user name and password | **Authentication failure**

**Expected Output**

Inputs | Results
-- | --
Valid user name and password | Authentication successful
Invalid user name and password | **Authentication failure**

Actual output values are matched with the Expected Outputs.

**Test 2**

Installed  ballerina-platform-Linux-installer (-x64-0.975.1.deb ) version.
Used same configurations and toml file (Test1).
Invoke the service using same cURL command.
curl -vk -u admin:pass1 https://localhost:9090/banktest/account/ACC001

**Actual Output** 

Inputs | Results
-- | --
Valid user name and password | Authentication successful
Invalid user name and password | **Authentication successful**

**Expected Output** 

Inputs | Results
-- | --
Valid user name and password | Authentication successful
Invalid user name and password | **Authentication failure**

Actual output values are not matched with the Expected Outputs.

**Affected Versions:**
ballerina-platform-Linux-installer -x64-0.975.1.deb 
**OS, DB, other environment details and versions:**
ubuntu 16.04 LTS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayomawdb** [comment]
Hi @KasunAratthanage! This is to inform you that this issue will be resolved with PR ##9728. 
Thank you for reporting this concern!
