### ISSUE TITLE
Ballerina build/test command output is not consistent across different OS

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#9554]
On windows, the following output is observed for ballerina test command. The success symbol is incorrect.

<img width="883" alt="screen shot 2018-07-10 at 11 42 01 am" src="https://user-images.githubusercontent.com/690559/42492403-993868ee-8436-11e8-9231-794f6db76a95.png">

**Comment by Kishanthan** [comment]
Same for failure symbol as well.

<img width="936" alt="screen shot 2018-07-10 at 11 46 34 am" src="https://user-images.githubusercontent.com/690559/42492515-f2a7fa7a-8436-11e8-9679-364f1055d6b8.png">

**Comment by pubudu91** [comment]
Closing this since this was fixed with PR #9564
