### ISSUE TITLE
Composer is Conflicting with PHP Composer

### ISSUE THREAD

**Issue by kasvith** [ballerina-platform/ballerina-lang#9556]
**Description:**
Many developers may have installed **PHP Composer** in their machines (including me).
Ballerina composer is a new one and since names are pretty same they are conflicting.

PHP Composer is there for many years and they will never change the name, so ballerina will have to avoid this problem preventing users manually changing the name of scripts in the bin folder (i changed it to bal-composer myself to avoid conflicts)

**Steps to reproduce:**
- Install ballerina and php composer in the same machine
- Run composer in any directory and you will get them conflicted as os does not knows which composer to run.
- So it will run the one found 1st in the PATH which may lead to one composer to be started

**Affected Versions:**
- Any with the composer

**OS, DB, other environment details and versions:**
- Any OS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by menuka94** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/9442.

**Comment by kasvith** [comment]
thanks, Closing issue due to conflict
