### ISSUE TITLE
File system changes are not reflected in the composer

### ISSUE THREAD

**Issue by kasvith** [ballerina-platform/ballerina-lang#9559]
**Description:**
Ballerina Composer is not tracking changes made for the files in the file system by an external editor.
This is a basic feature in IDE/Editors to ensure the user has not made any accidental modification outside the editor.

Generally an IDE/Editor would ask

> The file is modified outside the editor, would you like to reload it ?

This feature should be added to Ballerina Composer.

**Steps to reproduce:**
- Open composer
- Create a project
- Create and open a .bal file
- Open the same project in another IDE/Editor like VSCode/IntelliJ and modify the same .bal file opened in the Composer UI and save it
- Go back to Composer
- Your changes are not there and composer holds previous changes still 
- If you hit save on the composer it will erase the changes you made externally

**Affected Versions:**
Ballerina 0.975.1

**OS, DB, other environment details and versions:**
For now Windows 10
This might be still in other OSes too

**Related Issues (optional):**

**Suggested Labels (optional):**
bug, composer

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
We are looking into the possibility to base Composer tooling on [Theia IDE](https://github.com/theia-ide/theia). Hopefully this will resolve the need to maintain basic IDE features on our own. We are holding implementation of this until the path forward is decided- to avoid redundant efforts. We are in the process of evaluating Theia and will soon be able to clear up the path forward.

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
