### ISSUE TITLE
[Suggestion]Composer could be distributed seperately

### ISSUE THREAD

**Issue by kasvith** [ballerina-platform/ballerina-lang#9560]
**Description:**
It's common that many people outside may not wish to even install the composer for ballerina.

So this ballerina composer can be distributed as **Ballerina Studio** as a separate application.
As the current application is using a web interface for interact with users, it could be easily moved to an **Electron App** like **VSCode** with minimal changes.

Then the application can be developed and distributed separately. 
This will allow 
- To reduce the setup size
- To avoid any conflict with the PHP Composer(yes now its ballerina studio or whatever fits in)
- To be standalone
- To have customizations

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment]
Thanks for the suggestion. We have already developed an Electron-based editor for Ballerina. It's available on 0.980.0 release as well. @kaviththiranga may give more details.

**Comment by nadeeshaan** [comment]
@kasvith You can find the electron-based distributions at https://ballerina.io/downloads/
