### ISSUE TITLE
Distorted Electron Application Icon 

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#9569]
**Description:**
The application icon of the electron application is distorted as shown in the below image.
![icon](https://user-images.githubusercontent.com/11191791/42500885-0de379ea-8450-11e8-8595-ee99c1bdad67.PNG)

**Affected Versions:**
v0.980.0

**OS, DB, other environment details and versions:**
Windows 10 Pro
Version 1803
OS Build 17134.112

**Comment by jeradrutnam** [comment]
Fixed: #9647
