### ISSUE TITLE
untaint unary expression rule is not applied in Swagger to ballerina code generation

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#9572]
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**
ballerina 0.975.0

**OS, DB, other environment details and versions:**
Linux

**Comment by NipunaMarcus** [comment]
Closing this issue as we are changing the OpenAPI CLI tool design but will attach this to the new issue to track and evaluate during the development.
