### ISSUE TITLE
Invoke the service using HTTP client program

### ISSUE THREAD

**Issue by SithumRavishara** [ballerina-platform/ballerina-lang#9580]
**Description:**
There is a issue in step of invoke the service using HTTP client program in a new command line.
Command of:- 
`curl -v -X POST -d '{"a": 10, "b":  200, "operation": "add"}' "http://localhost:9090/calculator/operation" -H "Content-Type:application/json"`

Response -

C:\Users\Sithum> curl -v -X POST -d '{"a": 10, "b":  200, "operation": "add"}' "http://localhost:9090/calculator/operation" -H "Content-Type:application/json"
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: 10,/
* Could not resolve host: 10,
* Closing connection 0
curl: (6) Could not resolve host: 10,
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: b:/
* Could not resolve host: b
* Closing connection 1
curl: (6) Could not resolve host: b
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: 200,/
* Could not resolve host: 200,
* Closing connection 2
curl: (6) Could not resolve host: 200,
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: operation:/
* Could not resolve host: operation
* Closing connection 3
curl: (6) Could not resolve host: operation
curl: (3) [globbing] unmatched close brace/bracket in column 4
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to ::1 port 9090 failed: Connection refused
* connect to 127.0.0.1 port 9090 failed: Connection refused
* Failed to connect to localhost port 9090: Connection refused
* Closing connection 4
curl: (7) Failed to connect to localhost port 9090: Connection refused

**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.970.1
**OS, DB, other environment details and versions:**
Windows 10
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by riyafa** [comment]
This is related to this: https://ballerina.io/community-program/index.html

**Comment by riyafa** [comment]
It is a connection refused error that you have here. It is not related to the ballerina program. @SithumRavishara can you please check if the ballerina service is running before invoking it using the curl command?

**Comment by SithumRavishara** [comment]
yeh it is working properly.

**Comment by vinok88** [comment]
Closing based on the last comment.
