### ISSUE TITLE
Console in the composer not working correctly 

### ISSUE THREAD

**Issue by jayamaljayamaha** [ballerina-platform/ballerina-lang#9584]
**Description:**
We can run the package using the composer when we run that results print in the console, In the calculator package when we run it we have to select one option but we cant do that in the console in the composer but we can do that in windows terminal we cannot enter the option so cannot go ahead

I think the problem is the console in the composer not working correctly 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pahans** [comment]
Closing in favour of https://github.com/ballerina-platform/ballerina-lang/issues/9499
