### ISSUE TITLE
Installing new distribution doesn't replace the composer application in mac applications

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#9588]
**Description:**
If we have a older version of ballerina platform installed in a mac, installing new distribution doesn't replace the older composer version in application directory of mac. 

**Steps to reproduce:**
1. Install older distribution of ballerina platform using installer.
2. Install newest distribution of ballerina platform using installer.
3. Run composer using application shortcut in application directory.

**Affected Versions:**
Older - 0.976.0
New - 0.980.0 - RC1

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/wso2/ballerina-build-artifacts/commit/2272e6dfd845c57a5c8f14a58cfe53f4c245f761>
However, since composer is no longer maintained, this is not valid anymore.
Closing as per above comments.
