### ISSUE TITLE
Build failed because services not started

### ISSUE THREAD

**Issue by HisharaPerera** [ballerina-platform/ballerina-lang#9611]
**Description:**
Build failed because services not started

**Steps to reproduce:**

- clone project from this link https://github.com/HisharaPerera/auction-service

- Directed to scatter-gather-messaging/guide and run "ballerina build scatter-gather-messaging " command

**Affected Versions:**
latest master (0.980.0-RC2)
**OS, DB, other environment details and versions:**

**Comment by lankavitharana** [comment]
PR merged hence closing
