### ISSUE TITLE
Ballerina doesn't run on jdk1.9 on windows

### ISSUE THREAD

**Issue by NirodhaSuchinthana** [ballerina-platform/ballerina-lang#9620]
**Description:**
Initially, I installed Balllerina on my windows 10 and set path. When checking the installation with 'ballerina -v' it gives me 'Ballerina is supported only on JDK 1.8 and above' error.
At the same time I checked jdk version. It is java 9.0.4
**Steps to reproduce:**

**Affected Versions:**
Ballerina 0.975.1

**OS, DB, other environment details and versions:**
Windows 10
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Related Issues (optional):**
N/A
**Suggested Labels (optional):**
Bug
**Suggested Assignees (optional):**
N/A

**Comment by jayamaljayamaha** [comment]
hey 

NirodhaSuchinthana you are right because Oracle says Java SE 9 has reached the end of support. you can see if you go to oracle website. you should try with java 8 or java 10 
![jdk9](https://user-images.githubusercontent.com/24557887/42725975-b1573244-87aa-11e8-921c-796fc3f90d6e.PNG)

**Comment by bluebob** [comment]
_Good point_. Downside is that 10 (at least according to [Oracle Java SE Support Roadmap](http://www.oracle.com/technetwork/java/javase/eol-135779.html)) only lasts until September this year when 11 comes out. That said, my suggested patch above definitely works with 10 seeing as that's what I'm using now.
I guess when 11 comes out it'll be simple to update my patch - assuming that there's not something better from the devs themselves before then.

**Comment by pubudu91** [comment]
It'd be best to stick to JDK/JRE 8 for building/running Ballerina. While you may be able to use Ballerina with Java 9, the experience may not be as smooth as with Java 8.

**Comment by keizer619** [comment]
Ballerina only supports JDK/JRE8, error message has been updated to mention only 1.8 (not above) [1], Also documentation has been updated by specifying 1.8 [2] is supported.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/9780
[2] https://github.com/ballerina-platform/ballerina-www/pull/1086
