### ISSUE TITLE
Bug/Errors

### ISSUE THREAD

**Issue by SupunSPWithana** [ballerina-platform/ballerina-lang#9631]
**Description: About Errors/Bugs**

1.Instead of downloading curl I think we can work with GitBash

2.In the calculator lib.bal and main.bal I think we have to remove the package statement(package calculator) which is automatically generating...

3.line 19 main.bal 'c' is defined twise.

4.sometimes when trying to run(inside main folder,outside calculator folder) 'ballerina run calculator' it showed the error messege "error: fail to compile file: null"

5.In the 'Create a Client for Calculator Service' when running 'ballerina run client.bal' it shows the error message as "2018-07-13 11:53:39,120 ERROR [] - Connection refused: no further information: localhost/127.0.0.1:9090 : {message:"Connection refused: no further information: localhost/127.0.0.1:9090", cause:null}" instead of the output "Addition result 15.6 + 18.9 : 34.5"

![screenshot 46](https://user-images.githubusercontent.com/26740844/42681862-7c040cfc-86a6-11e8-8ceb-2e0c4e2ba5f8.png)
![screenshot 47](https://user-images.githubusercontent.com/26740844/42681864-7c608ae0-86a6-11e8-8b5d-f401f82296c9.png)

**Comment by vinok88** [comment]
You may be getting the "connection refused" error since you are invoking an incorrect URL. Other points you made are also user errors. If you think there is room for improvement in the guide, please report to https://github.com/ballerina-platform/ballerina-www repo. Thanks.
