### ISSUE TITLE
[composer] Enter vs Tab for Code Completion

### ISSUE THREAD

**Issue by inthirakumaaran** [ballerina-platform/ballerina-lang#9633]
**Description:**
This is one of the minor performance enhancement suggestion for the ballerina composer. Normally there is a difference whether to use code completion with tab or with enter.

Using enter will complete the statement as you would expect. Using tab will complete the statement and delete everything forward until the next dot, parentheses, semicolon or space.

![code](https://user-images.githubusercontent.com/17597685/42688481-01aacec8-86ba-11e8-8944-788ea202a704.gif)

But here enter and tab both complete the statement as we expected. So it would be better to differentiate these two methods. 

**Steps to reproduce: just try tab and enter for code completion**

**Affected Versions: all the versions have this**

**Comment by nadeeshaan** [comment]
@inthirakumaaran this is a IDE specific feature and we use monaco editor for composer source editor. This feature is not available in monaco (as well as in VSCode refer https://github.com/Microsoft/vscode/issues/4878). Hence closing the issue.
