### ISSUE TITLE
Error as 'could not find package wso2/ftp:*' while using FTP File Connector v0.97.0 in  Ballerina v0.970.1

### ISSUE THREAD

**Issue by NipunaDilhara** [ballerina-platform/ballerina-lang#9637]
**Description:**
Tried to use the Ballerina FTP File Connector (https://github.com/wso2-ballerina/package-file/releases) by following the same examples as in https://github.com/wso2-ballerina/package-file/tree/v0.97.0. The 'FTP Listener' example gives 'could not find package wso2/ftp:*' message but works fine after that. The 'FTP Client' example gives 'could not find package wso2/ftp:*  ballerina: Oh no, something really went wrong. Bad. Sad.' message.

FTP Listener code
```
import wso2/ftp;
import ballerina/io;

endpoint ftp:Listener remoteLocation {
    protocol:ftp:FTP,
    host:<ip_address>,
    port:21,
    secureSocket: {
        basicAuth: {
            username: <user_name>,
            password: <password>
        }
    },
    path:"/"
};

service monitor bind remoteLocation {
    fileResource (ftp:WatchEvent m) {
        foreach v in m.addedFiles {
            io:println("Added file path: ", v.path);
        }

        foreach v in m.deletedFiles {
            io:println("Deleted file path: ", v);
        }
    }
}
```

FTP Client code
```
import wso2/ftp;
import ballerina/io;

endpoint ftp:Client client {
    protocol: ftp:FTP,
    host: <ip_address>,
    port:21
};

function main (string[] args) {
    //To create a folder in remote server
    error? dirCreErr = client -> mkdir("/home/nipuna3/");
    match dirCreErr {
        error err => {
            io:println("An error occured.");
            return;
        }
        () => {}
    }
}
```
Ballerina-internal.log for FTP Listener code.
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2194766/ballerina-internal.log)

Ballerina-internal.log for FTP Client code.
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2194763/ballerina-internal.log)

**Steps to reproduce:**

**Affected Versions:**
0.970.1

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/9638

**Suggested Labels (optional):**
File Connector

**Suggested Assignees (optional):**

**Comment by NipunaDilhara** [comment]
There are some syntax errors in the example codes of File Connector. FTP Client code is working after fixing them. But still getting the 'could not find package wso2/ftp:' message.

**Comment by wggihan** [comment]
You need to copy complied balo file to the lib folder along with dependency jars. We have added an installation script with new release. Please, check that.

**Comment by Kishanthan** [comment]
This issue is still there in 0.980.1, where even for success scenarios, this error or rather a log is getting printed on the console.

**Comment by wggihan** [comment]
This is not an FTP package specific issue. Original issue as mention in here need to fix from the Ballerina central side. https://github.com/ballerina-platform/ballerina-lang/issues/9777
