### ISSUE TITLE
ballerina: unsupported program file version 17

### ISSUE THREAD

**Issue by JayathmaChathurangani** [ballerina-platform/ballerina-lang#9640]
Ballerina Version Using : 0.975.1
OS Using: Windows 8.1

I created a simple ballerina echo service project via IntelliJ and was able to build and run balx. 

But when I tried to build or run (previous balx file) using the command prompt I am getting the following errors.
_When trying to build,_
ballerina: cannot find file 'E:\folder\name.bal'
_When trying to run (previous built balx file using IntelliJ),_
ballerina: unsupported program file version 17

**Comment by pubudu91** [comment]
Can you check the version on the command prompt? Just run `ballerina version` and see.. The error message indicates that you are trying to run a program compiled using a different Ballerina version than the one you are trying to run it with..

**Comment by JayathmaChathurangani** [comment]
Yes when I checked the version in the command prompt it correctly says the version is 0.975.1

**Comment by pubudu91** [comment]
Then are you sure you are using the same version in IntelliJ? If it's saying version 17 is unsupported, you are either using a really old Ballerina version or a version newer than 0.975.1

**Comment by JayathmaChathurangani** [comment]
When I checked the project SDK version and version using the command prompt both are same.

**Comment by NipunaRanasinghe** [comment]
As mentioned before, this behavior can be observed when trying to run a ballerina program which has been built using a different ( order/newer ) ballerina version. However, it would be great if you can provide more details ( ballerina plugin version, ballerina code, a screenshot of the package structure ) to reproduce the issue.

**Comment by Shan1024** [comment]
As Nipuna mentioned, this is not a bug. This happens because the previously built balx file is not compatible with the newer ballerina versions. Recompiling the ballerina project with new ballerina version should fix this issue.
