### ISSUE TITLE
[Sugesstion] Add a cURL like HTTP client functionality to composer itself

### ISSUE THREAD

**Issue by AmilaIndika789** [ballerina-platform/ballerina-lang#9641]
**Description:**
It would be much easier if there is an in-built HTTP client program to invoke the service from the composer it self. Then it won't be necessary to invoke service separately.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pahans** [comment]
Hi, @AmilaIndika789 we have try it client for this. You can open it by clicking Try it button appears in the console when you run a service.
![selection_194](https://user-images.githubusercontent.com/1552869/42745380-0d63e5a0-88f0-11e8-8ae9-41eec927fbaa.png)

**Comment by AmilaIndika789** [comment]
Thanks.
