### ISSUE TITLE
improve error message for failed import

### ISSUE THREAD

**Issue by rabbah** [ballerina-platform/ballerina-lang#9646]
**Description:**
This error message  should be reworded for clarity and grammar:`your ballerina version does not support for package: wso2/twitter:*. following versions are supported: 0.9.13,0.9.14`

**Steps to reproduce:**
I have a ballerina program with a import wso2/twitter.. 

**Affected Versions:**
Ballerina build 0.975.

**OS, DB, other environment details and versions:**
Mac OS.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment]
Central does not know the users ballerina version when pulling a package. Central only knows the balo range of the user's ballerina version. Hence we could reword as following unless the message can be modified from the CLI:

`package 'wso2/twitter:*' does not support your ballerina version. following are the 'wso2/twitter' package versions compatible with your ballerina version: '0.9.13, 0.9.14' `

**Comment by rabbah** [comment]
maybe: `The package 'wso2/twitter' <version number?> is not compatible with your Ballerina compiler. Try one of these package versions instead: '<versions>'.`

**Comment by hemikak** [comment]
+1. Thanks for the suggestion @rabbah
