### ISSUE TITLE
Issue in rendering the sequence diagrams in composer on Windows

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#9650]
**Description:**

![composer-error2](https://user-images.githubusercontent.com/1335271/42800117-1055c6ca-89b8-11e8-845f-d35fb885782f.png)

The error in the above image occurs when trying to edit a bal file created inside a folder inside a ballerina project.

**Steps to reproduce:**

**Affected Versions:**
0.980.0 RC

**OS, DB, other environment details and versions:**
Windows 10.

**Comment by DimalChandrasiri** [comment]
Cannot recreate in version v0.981.1
