### ISSUE TITLE
Latest Ballerina packages do not get pulled when there is an older version of package

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#9653]
**Description:**
The Ballerina packages which are pulled from Ballerina Central get invalidated when a new Ballerina version is installed. But the latest versions of the packages do not get pulled automatically when the code which uses the packages, is built with a latest Ballerina version.

**Steps to reproduce:**
There should be an older version of package which is compatible with Ballerina older version. Then install the latest version of Ballerina. When trying to build a code sample which uses the pulled package, the following error will occur.
```
Compiling source
package:0.0.0
ballerina: format error: ballerina: unsupported program file version 18
```
Please refer an real use case which is given under "Related issues" secion.

**Related Issues**
https://stackoverflow.com/questions/51359780/error-in-fetching-updates-for-ballerina-central-packages

**Comment by NatashaWso2** [comment]
This issue is fixed with #9887, hence closing this issue.
