### ISSUE TITLE
composer not initiating 

### ISSUE THREAD

**Issue by mster3313** [ballerina-platform/ballerina-lang#9657]
**Description:**
when composer command is run from terminal composer is not opened. (I have installed laravel composer and when invoking composer command laravel composer is initiated). link http://localhost:9091 won't open composer i had to manually run composer to make the link work.
It will be useful to distinguish ballerina composer from other composers.

Composer explorer window, when folder structure is changed manually in the directory, is not updated/refreshed automatically. Every time i had to manually refresh.

-----Composer icon on taskbar need to be fixed----
![capture](https://user-images.githubusercontent.com/27721463/42842535-1622c260-8a2b-11e8-8fef-4321c88f5631.PNG)

Even these are very minor issues i hope they affect user experience.

**Affected Versions:**
Ballerina 0.980.0

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment]
@mster3313 thanks for reporting the issue. 

Have you used the Ballerina installer to install Composer?
If you used the installer, you can simply use the start menu shortcut created for Composer to launch it.
More Info: https://ballerina.io/learn/quick-tour/#run-the-composer

We are now packaging Composer with [Electron](https://electronjs.org/). Hence now there is no need to manually open the browser and point it to http://localhost:9091.

Fix for the distorted task bar icon is already [merged](https://github.com/ballerina-platform/ballerina-lang/commit/1ae9954bed0d0f1e578ac5c9069f1213a6b56127) and will be available with the next release.

However, the command conflict with composer (php dependency manager) is still valid for linux users and we will look into possible solutions.

**Comment by kaviththiranga** [comment]
@mster3313 I have created a separate issue to track command conflict 

https://github.com/ballerina-platform/ballerina-lang/issues/9659

**Comment by kaviththiranga** [comment]
@mster3313 Regarding automatic refresh on explorer upon file system changes:

We hope to add this functionality for future - along with similar functionality for editor tabs where the tab will refresh when a file is changed on disk by external means.

Created a seperate issue to track this https://github.com/ballerina-platform/ballerina-lang/issues/9661

**Comment by kaviththiranga** [comment]
Closing this as per the previous answers.
