### ISSUE TITLE
Composer command conflicts with PHP composer (Dependency Manager)

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#9659]
Some devs have experienced the command conflict when they have already set up Laravel, etc. PHP dev enviornments in their machines.

Possible solutions:

- Change command to bcompoer or something meaningfull
- Document this in the troubleshooting section under composer docs

**Comment by mikeschinkel** [comment]
+1 to this. I ran into the same thing when trying to install to evaluate Ballerina.

**Comment by anupama-pathirage** [comment]
Duplicate issue https://github.com/ballerina-platform/ballerina-lang/issues/9442

**Comment by kaviththiranga** [comment]
Closing this issue and please refer to https://github.com/ballerina-platform/ballerina-lang/issues/9442 for further tracking.
