### ISSUE TITLE
build command fails when there is a tests package in the same level of the folder hierarchy

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#9670]
**Description:**
build command fails when there is a tests package in the same level of the folder hierarchy.

resiliency-circuit-breaker
 └── guide
     ├── inventory_services
     │   ├── inventory_service.bal
     │   └── tests
     │       └── inventory_service_test.bal
     ├── order_services
     │   ├── order_service.bal
     │   └── tests
     │       └── order_service_test.bal
     └── tests
         └── integration_test.bal

Therefore integration tests have been removed from ballerina guides:
 Following are the commits:
- https://github.com/ballerina-guides/resiliency-circuit-breaker/commit/e400828189cda7d0db969915eeb94e8f4181023e
- https://github.com/ballerina-guides/asynchronous-invocation/pull/14/commits/73b6bcbabe61b7743116268429dac446a7d01b6b
- https://github.com/ballerina-guides/resiliency-timeouts/pull/21/commits/9f3a1b1ce80435408d1853de2041ee9fd4fbd258

**Comment by NatashaWso2** [comment]
We have removed the top level tests/ folder in the current master.
