### ISSUE TITLE
Configurations in ballerina.conf cannot be taken when there is a special character.

### ISSUE THREAD

**Issue by dushansilva** [ballerina-platform/ballerina-lang#9678]
**Description:**
When there is the character "#" in the ballerina.conf file , that configuration and every configuration below that cannot be obtained. For example check the images below 

**ballerina.conf file**
![image](https://user-images.githubusercontent.com/18071381/42920546-dc4eaf9e-8b34-11e8-9fc6-a5cf048c2d9b.png)

**Code to retrieve value from conf file**
![image](https://user-images.githubusercontent.com/18071381/42920475-64675f08-8b34-11e8-8519-9ac7a33bd859.png)

**Output**
![image](https://user-images.githubusercontent.com/18071381/42920561-f845a8c4-8b34-11e8-8b7d-50f1c6835b07.png)

**Affected Versions:**
Ballerina 0.975.1

**Comment by pubudu91** [comment]
This is a known issue, reported in #7668 and #9292. Hence closing this.
