### ISSUE TITLE
Record to Map conversion doesn't do type checking

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#9681]
**Description:**
Record to Map conversions doesn't do compile-time/runtime type checking. If the target map is constrained, the conversion happens without any failures, even if the record contains an field with type that is not compatible with the constraint-type of the map.

**Steps to reproduce:**
```ballerina
import ballerina/io;

type Person record {
    string name;
    int age;
};

function main(string... args) {
    Person e = {name:"Supun"};
    map<int> m = <map<int>> e;
    io:println(m);
}
```

Here the conversion should fail, since the constraint type is `int`, and the record contains a field of type `string`.

**Affected Versions:**
v0.980.0

**Comment by warunalakshitha** [comment]
With the introduction of stamp and convert methods, type checking will be done before record to map conversion. You will observe following error messages when use incompatible record to map conversions/stamapings.

**convert:** incompatible types: 'Person2' cannot be converted to 'map<int>'
**stamp:** incompatible stamp type: type 'Person2' cannot be stamped as type 'map<int>'
