### ISSUE TITLE
Cannot customize installation path in MAC OS installer. 

### ISSUE THREAD

**Issue by chamarasilva** [ballerina-platform/ballerina-lang#9692]
Once click change install location button it goes to the destination selection section. But there is no option to customize the installation location.
![installer](https://user-images.githubusercontent.com/7007542/42985286-6cbf1a80-8c0e-11e8-9139-fe1e856127db.png)

<img width="622" alt="dest" src="https://user-images.githubusercontent.com/7007542/42985290-75306688-8c0e-11e8-927b-ee783d52d2a5.png">

**Comment by keizer619** [comment]
Now we have configured Installers to used a fixed path for macOS (`/Library/Ballerina/`) and we will not allow users to change above location. Hence i am closing this issue
