### ISSUE TITLE
Convert 'any' to 'string'

### ISSUE THREAD

**Issue by Ketharan** [ballerina-platform/ballerina-lang#9699]
**Description:**
How to convert 'any' type to 'string'

```
var Result = <string>p.messages[0]["messageId"];
match Result {
    string val => {
         io:println( val);
     }
      error err => {
           io:println("error: " + err.message);
      }
}
```

It gives an error like ' preceding patterns are too general or the pattern ordering is not correct'

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment]
@Ketharan I can see that you have added the error case as a match clause. Since the string conversion is safe, we do not expect an error in this case. Therefore can you try removing the error clause from the match statement?
