### ISSUE TITLE
Improve semantic analyzing support in documentations

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#9704]
**Description:**
Only the parameters, fields and return value are validated. Content in **`` `...` ``** are not validated. 

## Spec

BFM also provides conventions for referring to Ballerina-defined names from within documentation strings in a source file. An identifier in backticks `X`, when preceded by one of the following words:

- type
- endpoint
- service
- variable
- var
- annotation
- module
- function
- parameter

is assumed to be a reference to a Ballerina-defined name of the type indicated by the word. In the case of parameter, the name must be unqualified and be the name of a parameter of the function to which the documentation string is attached. For other cases, if the name is unqualified it must refer to a public name of the appropriate type in the source file's module; if it is a qualified name M:X, then the source file must have imported M, and X must refer to a public name of an appropriate type in M. BFM also recognizes `f()` as an alternative to function `f`. In both cases, f can have any of the following forms (where m is a module import, x is a function name, t is an object type name, and y is a method name):

```ballerina
    x()
    m:x()
    t.y()
    m:t.y()
```

**Example**

    # Adds parameter `x` and parameter `y`
    # + x - one thing to be added
    # + y - another thing to be added
    # + return - the sum of them
    function add (int x, int y) returns int  { return x + y; }

**Comment by hasithaa** [comment]
@dulvinw is working on this feature.
