### ISSUE TITLE
Ballerina Composer shortcut is not getting removed when do uninstalll

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#9708]
This cause to create broken shortcuts in windows. 

![image](https://user-images.githubusercontent.com/1356214/43063495-9648564c-8e79-11e8-9862-bccb8caa3d04.png)

![image](https://user-images.githubusercontent.com/1356214/43063591-e485e7a2-8e79-11e8-8b05-5d496bb1d9a6.png)

**Comment by kaviththiranga** [comment]
Closing the as we are no longer maintaining composer.
