### ISSUE TITLE
Attempt to send record type in gRPC throws Null Pointer Exception in compiler

### ISSUE THREAD

**Issue by autodidaddict** [ballerina-platform/ballerina-lang#9718]
**Description:**
I am trying to create a gRPC service that doesn't send and receive strings (JSON), I want to use real protobuf messages. My first attempt to do so (found in this
 [gist](https://gist.github.com/autodidaddict/75538cbd456b991e0e6f722e3241a5a2)), when I try and compile, produces a null pointer exception.

**Steps to reproduce:**
Run `ballerina build` on the file in the gist.
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2219040/ballerina-internal.log)

**OS, DB, other environment details and versions:**
Ubuntu 18.04 (Pop! OS)

**Suggested Labels (optional):**
bug

**Comment by daneshk** [comment]
This is due to an issue in deriving response message type when passing complex types like optional, union, tuple etc. Current implementation doesn't support passing those values. 
We need to validate it correctly and send proper error messages.

**Comment by Manuri** [comment]
Closing since the relevant PRs are merged as per @daneshk 's input.
