### ISSUE TITLE
VScode cannot detect the home config var correctly when installing Ballerina via Homebrew

### ISSUE THREAD

**Issue by xlogan** [ballerina-platform/ballerina-lang#9724]
**Description:**
The extension keeps warning: The configured "ballerina.home" seems incorrect.

  * I've installed via homebrew. The package is located at: /usr/local/Cellar/ballerina/0.980.0
  * The ballerina.home config is: "ballerina.home": "/usr/local/Cellar/ballerina/0.980.0"

**Affected Versions:**
0.980.0

**OS, DB, other environment details and versions:**
- installed the extension from vscode marketplace

**Suggested Labels (optional):**
Type/Bug, Component/VScode plugin

**Comment by nadeeshaan** [comment]
@xlogan do you have other ballerina versions installed in the same location?

**Comment by xlogan** [comment]
Yes, I do. I copied the location to config the ballerina.home variable in VScode settings.

**Comment by nadeeshaan** [comment]
@xlogan can you try having only the latest ballerina version (v0.980) in the installation directory for the moment?

**Comment by xlogan** [comment]
Nice, it works now. I removed the package from Homebrew, downloaded the package. Thanks for your support @nadeeshaan

**Comment by xlogan** [comment]
Noted! Thanks @rasika

**Comment by rasika** [comment]
Please note that homebrew ballerina 0.980.1 onwards; you can **just use** `/usr/local/Cellar/ballerina/0.980.0` for the `ballerina.home` in the **vscode plugin**.

[1]https://github.com/Homebrew/homebrew-core/pull/30426

**Comment by xlogan** [comment]
Awesome!

**Comment by nkhine** [comment]
on ubuntu, installing it using the linux .deb from https://ballerina.io/downloads/

```
"ballerina.home": "/usr/lib/ballerina/ballerina-0.980.1"
```
