### ISSUE TITLE
Json compare

### ISSUE THREAD

**Issue by vanjikumaran** [ballerina-platform/ballerina-lang#9735]
**New Feature Description:**
JSON compare, Since the ballerina, contain the JSON as a part of it native datatype. Comparing 2 JSON variable should be a native function in a ballerina. If the same elements and values are part of variables. It should return true regardless of the order of elements

**Comment by MaryamZi** [comment]
Introduced with https://github.com/ballerina-platform/ballerina-lang/pull/10904.
