### ISSUE TITLE
Context menu icons aren't hidden in collapsed diagram

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#9765]
**Description:**
The context menu icons are not hidden when the diagram is collapsed.

![capture](https://user-images.githubusercontent.com/11191791/43386023-ff430486-93ff-11e8-91ce-1d234a9aa351.PNG)

**Steps to reproduce:**
Open hello world service.
Add multiple workers from diagram.
Collapse the diagram.

**Affected Versions:**
v0.980.2

**OS, DB, other environment details and versions:**
Windows 10

**Comment by DimalChandrasiri** [comment]
If we add a component while the diagram is collapsed, the context menu is duplicated on hover. 

![capture](https://user-images.githubusercontent.com/11191791/43386496-648c2eca-9401-11e8-9cab-3ab814807736.PNG)

**Comment by pahans** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9819
