### ISSUE TITLE
Could not find package wso2/kafka:* issue

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#9777]
**Description:**

`could not find package wso2/kafka:*` message gets printed even when the build is exiting with status code 0.

Complete Tavis log - https://travis-ci.org/ballerina-guides/messaging-with-kafka/builds/409675684

<img width="489" alt="messaging-with-kafka - travis ci 2018-07-31 09-10-43" src="https://user-images.githubusercontent.com/4003115/43436370-d9f6bd56-94a1-11e8-9b7a-e9eedaf67312.png">

**Comment by mkasovic** [comment]
I had similar issue with other native connectors. Problem is that Ballerina expects to find content of balo folder from connector distribution zip to be present in user's home folder at location $HOME/.ballerina/repo.

So, in case of redis connector, for example, distribution files should in the following locations:
- $BALLERINA_HOME/bre/lib/wso2-redis-package-0.5.5.jar
- $BALLERINA_HOME/lib/repo/wso2/redis/0.0.0/redis.zip
- $HOME/.ballerina/repo/wso2/redis/0.0.0/redis.zip

**Comment by NatashaWso2** [comment]
This error comes for all the native connectors which are not pushed to central. Please refer the original issue for more updates https://github.com/ballerina-platform/ballerina-lang/issues/8314

**Comment by NatashaWso2** [comment]
Closing this issue since it is already tracked with  #8314
