### ISSUE TITLE
Values defined in toml with "#" in the value throws an error

### ISSUE THREAD

**Issue by NatashaWso2** [ballerina-platform/ballerina-lang#9778]
**Description:**
The issue is with the toml grammar which seem to consider "#" as the start of a comment even when it's used within quotes. We need revisit the toml grammar to address this issue.

**Steps to reproduce:**
Values defined in the toml as below would give the error: 
_param = "Demo#123"_

**Affected Versions:**
0.980.2-SNAPSHOT

**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/9292
https://github.com/ballerina-platform/ballerina-lang/issues/9678
https://github.com/ballerina-platform/ballerina-lang/issues/7668
https://github.com/ballerina-platform/ballerina-lang/issues/11357

**Comment by pubudu91** [comment]
The following works btw: `password="123#asd"`
Note that the characters preceding the `#` are numeric
