### ISSUE TITLE
Calling `.values()` on a constrained map, returns any[]

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#9785]
**Description:**

Calling `.values()` on a constrained map, returns `any[]`. Shouldn't it return an array of constrained type (i.e `map<Person>` should return `Person[]`)? 

```ballerina
type Person record {
    int id;
    string name;
};

function main(string... args) {
    map<Person> personMap;
    personMap["personA"] = {id: 1, name: "Person A"};
    personMap["personB"] = {id: 2, name: "Person B"};

    // Attempt 1
    Person[] persons = personMap.values();
    // Attempt 2
    Person[] persons = <Person[]> personMap.values();
    // Attempt 3
    Person[] persons = check <Person[]> personMap.values();
}

```
Above attempts gave following errors;

Attempt 1: `error: ./main.bal:16:24: incompatible types: expected 'Person[]', found 'any[]'`
Attempt 2: `error: ./main.bal:16:24: incompatible types: expected 'Person[]', found 'Person[]|error'`
Attempt 3: `error: error, message: 'any' cannot be cast to 'Person[]'`

**Affected Versions:**
0.980.1

**Suggested Labels (optional):**
Type/bug, Component/BVM

**Suggested Assignees (optional):**
@Anoukh, @Shan1024

**Comment by pubudu91** [comment]
With the new lang lib changes, the `values()` function is not there anymore. Instead, there's `entries()` which returns a map of tuples. The tuple contains the key and the value. You can do something like below for getting an array of values in the map. Hence closing this issue. 
```ballerina
import ballerina/io;

public function main() {
    map<int> m = {"one": 1, "two":2, "three":3};
    int[] iarr = [];

    m.forEach(function (int v) {
        iarr[iarr.length()] = v;
    });

    io:println(iarr);

    int[] init = [];
    iarr = m.reduce(function (int[] accum, int v) returns int[] {
        accum[accum.length()] = v;
        return accum;
    }, init);

    io:println(iarr);
}
```
