### ISSUE TITLE
[VSCode] Better support for modifying Ballerina configuration in Settings

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#9786]
**Description:**
See following screenshot. All Ballerina configuration are highligheted as "edit in settings.json" while other configuration shown with drop down box, text fields etc.

![image](https://user-images.githubusercontent.com/1356214/43444220-daec5558-94c0-11e8-8394-2b1cec088559.png)

**Comment by roonyh** [comment]
Fixed by #10286
