### ISSUE TITLE
Error accessing record value by variable key

### ISSUE THREAD

**Issue by frankrobert** [ballerina-platform/ballerina-lang#9800]
**Description:**

When following this [example](https://ballerina.io/learn/by-example/records.html) I wanted to try accessing the `Person` record not only with `p1.name` or `p1["name"]` but also test some of the functionalities of Ballerina by accessing the record with `p1[key]`. The latter gives an error

![image](https://user-images.githubusercontent.com/4380529/43468523-37daa9cc-94b2-11e8-9d58-89e30684dbef.png)

Executing `ballerina run` results in the same error:
```sh
ballerina run hello/hello.bal
error: ./hello.bal:15:17: invalid index expression: expected string literal
compilation contains errors
```
I believe the expected behaviour should be the same as it is in languages such as JavaScript where you can access object keys using variables.

**Steps to reproduce:**
* Use this code
```ballerina
import ballerina/io;

type Person record {
  string name,
  int age,
  Person? parent,
  string status,
  string...
};

function main (string... args) {
  Person p1 = {};
  string key = "name";
  p1.name = "peter";
  io:println(p1[key]);
}
```
* Run `ballerina run [path to script]`

**Affected Versions:**
```sh
ballerina -v
Ballerina 0.980.1
```

**OS, DB, other environment details and versions:**
![image](https://user-images.githubusercontent.com/4380529/43468397-d935be2a-94b1-11e8-9320-116c690e4724.png)

```sh
uname -r
4.17.11-041711-generic
```

**Related Issues (optional):**

**Suggested Labels (optional):**

Possibly a bug or feature request.

**Suggested Assignees (optional):**

**Comment by frankrobert** [comment]
Another example would be the following which I would've expected to work:
```ballerina
import ballerina/io;

type Person record {
  string name,
  int age,
  Person? parent,
  string status,
  string warehouse_1,
  string warehouse_2,
  string...
};

function main (string... args) {
  Person p1 = {};
  string[] warehouses = ["C0004", "C0005"];

  foreach idx, w in warehouses {
    p1[`warehouse_{{idx}}`] = w;
  }
}
```

**Comment by SupunS** [comment]
@frankrobert Thanks for reporting.

Initially this was done intentionally, since the field-access needed to be statically validated during compile time, for records and objects (because they are predefined structures). However with the open records concept, now mandating keys to be static seems a burden. We are having an discussion on this, will update on the outcome.

**Comment by Anoukh** [comment]
This feature has been introduced in https://github.com/ballerina-platform/ballerina-lang/pull/13719. Hence closing the issue.
