### ISSUE TITLE
Version compatibility error when building .980.1 app with older connector in cache

### ISSUE THREAD

**Issue by TylerJewell** [ballerina-platform/ballerina-lang#9804]
**Description:**
During compilation of the 3_demo_connector (see the standard demos in the BBGs) for .980.1, received this error.

```
C:\tyler\ballerina\demo>ballerina build 3_demo_connector.bal
Compiling source
    3_demo_connector.bal
ballerina: format error: ballerina: unsupported program file version 17
```

Wiping cache in `~/.ballerina` resolved the issue. Subsequent build was able to download a newer version of the Twitter package and avoid the issue.

**Steps to reproduce:**
1. Had a cache with a Twitter package build with the May release, I think it was .970.
2. Used the master branch of the demo repo from the BBG
3. Build or run the 3_demo_connector.bal file.

**Comment by NatashaWso2** [comment]
This issue is fixed with  #9887 and the fix is available with 0.981.0-rc1 release, hence closing this issue.
