### ISSUE TITLE
Importing same package in a package.

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#9812]
**Description:**
When you are importing the same package in a package, ballerina compiler fails and gives Oh no, bad sad error.Well, this is not a huge issue. No one really imports the same package (except me) but its nice to have decent error message for this.

**Steps to reproduce:**
Make a package (example - Package)
make a .bal file and add 
```
import ballerina/io;
import Package; //issue 

public function test1() {
    io:println ("Hello from test1");
}
```
Make a Client.bal outside of the package (or in any other package).
```
import ballerina/io;
import Package;

function main(string... args) {
    Package:test1();
}
```

ballerina build.

**Affected Versions:**
0.980

Internal Log - https://pastebin.com/HKdtcyaP

**Comment by SupunS** [comment]
Duplicated of https://github.com/ballerina-platform/ballerina-lang/issues/4878
