### ISSUE TITLE
Error message needs to be improved

### ISSUE THREAD

**Issue by prabhashthere** [ballerina-platform/ballerina-lang#9814]
**Description:**
I am trying to deploy a REST service on Kubernetes.
Here is a Kubernetes annotation i used in my code
```
@kubernetes:Deployment {
    enableLiveness:true
    dockerHost:"tcp://192.168.99.100:2376", 
    dockerCertPath:"/home/prabhash/.minikube/certs"
}
```
This contains a syntax error, a comma is missing at the end of the line two
should be `enableLiveness:true,`

But I get an error message saying,
`error: ./hello.bal:6:5: invalid token 'dockerHost'`

The error message should be improved to identify the missing comma.

**Affected Versions:**
`Ballerina 0.980.1`

**Comment by SupunS** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/3673
