### ISSUE TITLE
Endpoint interactions are not listed in the default worker.

### ISSUE THREAD

**Issue by DimalChandrasiri** [ballerina-platform/ballerina-lang#9815]
**Description:**
The endpoint interactions for the default worker is not listed.

![image](https://user-images.githubusercontent.com/11191791/43504759-2693a03a-9582-11e8-89b7-f9d8c235aade.png)

**Steps to reproduce:**
Add an endpoint via the design view.
Then use the design view to add an endpoint interaction.

**Affected Versions:**
v0.980.2

**OS, DB, other environment details and versions:**
Windows 10

**Comment by nadeeshaan** [comment]
No longer valid since the particluar feature has been deprecated. Hence closing the issue
