### ISSUE TITLE
Need a proper solution to keep task timer/appointment running

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#9832]
**Description:**
Currently we have to use runtime:sleep() to stop the tasks from exiting. Need a proper solution instead. Tasks should run till timer.stop() is called. 

**Steps to reproduce:**
https://ballerina.io/learn/by-example/task-timer.html

**Comment by hasithaa** [comment]
@raj-rajaratnam , Thanks for reporting this issue, We will fix this issue in next release.

**Comment by raj-rajaratnam** [comment]
Is there a fix for this in the latest versions?

**Comment by hasithaa** [comment]
Not yet. We are working on a fix.

**Comment by NipunaMarcus** [comment]
This is fixed hence closing this issue.

**Comment by raj-rajaratnam** [comment]
@hasithaa is there a fix for this in 0.982.0?

**Comment by Kishanthan** [comment]
No, this is a larger problem that we hav to solve. Not only for tasks, but a generic solution needed to handle signals from BVM point of view.

In general, we have to make the BVM to wait for all ballerina tasks (timers, appointments, program exit, etc) to complete. But there should be a way to notify those running tasks in the event of BVM exit/interruption. To handle this we need some kind of a ballerina signal handlers, We had a initial discussion on this as the notes can be found from here - https://docs.google.com/document/d/16W36cEprx1j2pVzd6B0bOwQ-xA0mpt8nV4_LZPqHMjA/edit

**Comment by anupama-pathirage** [comment]
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/13632
Refer the sample : https://github.com/ballerina-platform/ballerina-lang/blob/master/examples/task-service-timer/task_service_timer.bal
