### ISSUE TITLE
Support running on IBM JDK 8

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#9857]
**Description:**
Created as a followup item from #9308

**Comment by mohanvive** [comment]
Are we planning to support running ballerina in IBM JDK since we are now shipping the JDK with the installation itself?

**Comment by keizer619** [comment]
@mohanvive I think we don't need to support as we already pack inbuilt JRE along with the installation.

@Kishanthan 
We have also included to fetch JRE dependencies along with ballerina update tool as well. Hence i am closing this issue as as all the installations will use inbuilt JRE. Please feel free to reopen if there are any concerns
