### ISSUE TITLE
Ballerina 0.980.1 installed on Windows machine throws errors when invoking the broker.bat file

### ISSUE THREAD

**Issue by sdkottegoda** [ballerina-platform/ballerina-lang#9916]
**Description:**
The error "'C:\Program' is not recognized as an internal or external command, operable program or batch file" is thrown when <ballerina_home>/bin/broker.bat is executed after the ballerina installation in windows.

**Comment by sdkottegoda** [comment]
Resolving this causes the following error to be printed: 
You must set the JAVA_HOME variable before running the Broker.

**Comment by wggihan** [comment]
Ballerina no longer ship broker with the distribution.
