### ISSUE TITLE
Ballerina composer icon in windows taskbar is not rendered properly

### ISSUE THREAD

**Issue by lakshani** [ballerina-platform/ballerina-lang#9926]
**Description:**
Ballerina composer icon in windows taskbar is not rendered properly
![image](https://user-images.githubusercontent.com/11018512/43722295-94bb70f4-99b2-11e8-9214-ec776aaad693.png)

**Steps to reproduce:**

1. Open the Composer
2. Look at the taskbar

**Affected Versions:**
v0.980.1.

**OS, DB, other environment details and versions:**
Windows 10

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
