### ISSUE TITLE
Formatting issue in VSCode using Ballerina plugin

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#9943]
**Description:**
I am on Ubuntu and I tried formatting my code in VSCode using keyboard shortcut Ctrl + Shift +I  and this is what I get for a WebSocket service: 

```
import ballerina/http;

service<http:WebSocketService> echo bind {
    port: 9090
} {
    onText (endpoint caller,     string text,     boolean final) {
        _ = caller ->pushText(text, final = final);
    }
}
```

The expected formatting is something like the following:
```
import ballerina/http;

service<http:WebSocketService> echo bind {port: 9090} {
    onText (endpoint caller, string text, boolean final) {
        _ = caller->pushText(text, final = final);
    }
}
```

Such formatting issues in VSCode needs to be fixed.

**Comment by nadeeshaan** [comment]
Formatting implementation is being revisited and this particular issue will be addressed with https://github.com/ballerina-platform/ballerina-lang/issues/9942. Hence closing the issue.
