### ISSUE TITLE
Add individual code expand/collapse option

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9944]
**Description:**
Currently there is no way users can expand/collapse individual code blocks in the diagram view by clicking on the collapsed "..." icon.

![image](https://user-images.githubusercontent.com/7569427/43815761-e81fd126-9aee-11e8-8ce5-675b73598a98.png)

**Suggested Labels (optional):**
[Type/UX]

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
