### ISSUE TITLE
Add statement expand/collapse option

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9946]
**Description:**
Currently there is no way users can collapse statement blocks when going through the diagram like we do in source code.

![image](https://user-images.githubusercontent.com/7569427/43817890-8c349ef4-9af9-11e8-9aa5-c25a60225816.png)

![image](https://user-images.githubusercontent.com/7569427/43817963-fb12774c-9af9-11e8-964a-31e66c365ff4.png)

**Suggested Labels (optional):**
[Type/UX]

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
