### ISSUE TITLE
Add service container expand/collapse option to view only mode

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9948]
**Description:**
Currently service container expand/collapse option is only there in edit mode. Need to have this option in view only mode as well.

![image](https://user-images.githubusercontent.com/7569427/43819169-77e04858-9aff-11e8-813d-6bde35ac8e15.png)

**Suggested Labels (optional):**
[Type/UX]

**Comment by NipunaMarcus** [comment]
@jeradrutnam  this design has been changed i believe. Did we able to resolve this issue?

**Comment by jeradrutnam** [comment]
@NipunaMarcus - Yes. Closing the issue, since the design is changed and issue is no-more.
