### ISSUE TITLE
Add jump to code line option to diagram view only mode

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9954]
**Description:**
Currently jump to code line option is there in edit mode. Need to make it available for diagram view only mode as well.

![image](https://user-images.githubusercontent.com/7569427/43824806-a26ce12e-9b10-11e8-828c-1b11a8a60ea2.png)

**Suggested Labels (optional):**
[Type/UX]

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin. Currently there is not diagram only view in VS code hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
