### ISSUE TITLE
Endpoint details are missing in the diagram

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-lang#9955]
**Description:**
Currently there is only endpoint name show in the diagram. But we need to show other details as well.

![image](https://user-images.githubusercontent.com/7569427/43825031-3be69f70-9b11-11e8-9aa7-51079a0b5be7.png)

![image](https://user-images.githubusercontent.com/7569427/43825142-9f1e7b4e-9b11-11e8-93ce-eea02fd2a4e7.png)

**Suggested Labels (optional):**
[Type/UX]

**Comment by NipunaMarcus** [comment]
@jeradrutnam what type of details that we need additionally ? URL?

**Comment by jeradrutnam** [comment]
@NipunaMarcus - Yes URL and the endpoint type. May be we can have it in the tooltip.

**Comment by mohanvive** [comment]
Issue is no longer valid for Swan Lake release. Hence, closing it.
