### ISSUE TITLE
[IDEA] Need to expand the variable tags for each debug step to see the variables in the current frame

### ISSUE THREAD

**Issue by pranavan15** [ballerina-platform/ballerina-lang#9967]
**Description:**
In IDEA, we require to expand the variable tags (triangle symbol) for each debug step to see the variables in the current frame, which is not user friendly. If we could see the variables without collapsing them for each debug step, it would provide a good user experience.

**Suggested Labels (optional):**
Type/Improvement

**Comment by NipunaRanasinghe** [comment]
@pranavan15 this is fixed with the new DAP based debugger implementation. :) Hence closing.
