### ISSUE TITLE
Intellij idea's false negative error warning

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#9971]
**Description:**
The following code is correct and works fine, but idea displays an error warning. 

```
    int end = math:randomInRange(1,5);

    foreach i in 1 ... end {
        io:println(i);
    }
```

![intellij-b7a](https://user-images.githubusercontent.com/4526877/43859361-02459c94-9b16-11e8-8e27-ee898db720f3.png)

**Comment by NipunaRanasinghe** [comment]
I was able to reproduce the issue and have started working on fixing it
