### ISSUE TITLE
"could not find package wso2/ftp:*" error when using ftp v0.97.3 with ballerina 0.980.1

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#9972]
**Description:**
Followed FTP repo's readme file to install the package. However I'm getting compilation error "could not find package wso2/ftp:*"

**Comment by wggihan** [comment]
This is not an ftp package specific file. This error come for all the native connectors. Please refer the original issue for more updates https://github.com/ballerina-platform/ballerina-lang/issues/8314
