### ISSUE TITLE
Doc updates.

### ISSUE THREAD

**Issue by rswijesena** [ballerina-platform/ballerina-lang#9973]
**Description:**

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

Documentation should be updated with the latest version.  below tag is missing. https://ballerina.io/learn/quick-tour/
documentation {
       A resource is an invokable API method
       Accessible at '/hello/sayHello
       'caller' is the client invoking this resource 

       P{{caller}} Server Connector
       P{{request}} Request
    }

**Comment by samgnaniah** [comment]
It looks like the syntax in this issue is already invalid. I just tested out the Quick Tour with the latest release and the code in the doc matches with what I see in the service. I'm closing this now, but please reopen if more clarification is required.
