### ISSUE TITLE
[Proposal] Supporting ANSI Color Sequences in Composer Terminal

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#9979]
**Description:**
Currently we have libraries such as [shan1024/chalk](https://central.ballerina.io/shan1024/chalk) which is capable of colorizing terminal output with the standard ANSI escape characters. For example; below code will print a colorized text.

```
import ballerina/io;
import shan1024/chalk;
function main (string... args) {
    chalk:Chalk c = new(chalk:WHITE, chalk:RED);
    string colorizedText = c.write("Hello world !!!");
    io:println(colorizedText);
}
```

In **VSCode**, it is printed without any issue;

<img width="675" alt="screen shot 2018-08-09 at 3 03 13 pm" src="https://user-images.githubusercontent.com/1448489/43890830-6f47fe84-9be5-11e8-8ae2-440bb8bd268d.png">

**However**, In Composer these ANSI characters are printed without any pre-processing.

<img width="695" alt="screen shot 2018-08-09 at 2 27 31 pm" src="https://user-images.githubusercontent.com/1448489/43890689-ffa895de-9be4-11e8-9351-d49309d82438.png">

**Comment by NipunaMarcus** [comment]
We have decided to discontinue composer and move all the capabilities to the Ballerina VS code plugin  hence closing this issue.

>Checkout VS code plugin for Ballerina here: https://marketplace.visualstudio.com/items?itemName=ballerina.ballerina
