### ISSUE TITLE
Proto to ballerina int32 conversion error

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#9993]
**Description:**
When I try to generate ballerina files from a .proto file, ballerina files will be generated without any error. however it fails to handle int32 data type in .proto file. it shows as a struct in _pb.bal file.

**Steps to reproduce:**

1. ballerina init
2. copy .proto file to the directory  -  https://pastebin.com/Wc7i6dLq
3. ballerina grpc --input route_guide.proto 
4. (files generates perfectly)
5. open client/_pb.bal file (ex - RouteGuide_pb.bal)
6. note 

```
type Point record {
    struct latitude;
    struct longitude;
    
};
```

**Affected Versions:**
Ballerina 0.980.1
**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Suggested Labels (optional):**
Component/gRPC

**Comment by daneshk** [comment]
Closing this issue, since fix is merged to master branch
